### ISSUE TITLE
"Dangerous World Gen Distance From Spawn" needs better config description.

### ISSUE THREAD

**Issue by Cakx** [Alex-the-666/Ice_and_Fire#1000]
Hi there!

Since you are using the distanceSq funciton to calculate the distance from the world spawn, you should update your config description for the "Dangerous World Gen Distance From Spawn" setting and maybe give a little text example so that modpack authors or players actually know what values to put there in order to get the desired block distance.

The value that has to be entered right now is (desired block distance)²,
meaning if you want for example dangerous stuff to spawn at around 7000 blocks away from spawn you need to enter a value of 49000000.

While the implementation is pretty reasonable from a performance perspective the description in the config is simply wrong and probably confuses any normal user who expects a different behaviour.

Also your default value of 200 is more or less ineffective. Dragons are likely to spawn right next to the world spawn with this low value.  I think this value could also be a little higher (at least 4000 meaning actually 200 blocks)

Alternativly you could also update your code to square the entered block distance on mod initilization and save it in another permanent variable (more performant than squaring it every time it's needed) that is then used for all the distance calculations. Which would make user tweaking a little easier as they could actually enter the raw desired block distance instead of the squared distance.

(Keep in mind that the max entered value in the config would then be at around ~46340 which would again need a little config description update.)

Keep up the good work! This mod has a lot of potential. :)

**Comment by AlexModGuy** [comment]
just changed how it worked to fix it
