### ISSUE TITLE
Walking mobs ignore their home position

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1005]
I tried to have my dragon wandering around after setting her a return point. A few MC days later I found that she is gone, patrolling the area I discovered that she went away about 150 blocks, completely ignore the home, it is after she flies that she return to the spot and stay there.

**Comment by mser7** [comment]
This goes the same for any other walking mobs with the homepoint system

**Comment by AlexModGuy** [comment]
this is intended
