### ISSUE TITLE
PlayerRevive Medusa issue

### ISSUE THREAD

**Issue by CreativeMD** [Alex-the-666/Ice_and_Fire#1010]
Hey there,
I'm the author of [PlayerRevive](https://minecraft.curseforge.com/projects/playerrevive), somebody reported an issue with your mod and mine https://github.com/CreativeMD/PlayerRevive/issues/16. The player does not die, but is only knocked out when turned into stone. I would like to add an exception for it, to make the player die immediately.

Can you give me the line where you turn the player into a stone statue? It should be enough to add something on my end to fix it.

In Regards
CreativeMD

**Comment by AlexModGuy** [comment]
https://github.com/Alex-the-666/Ice_and_Fire/blob/1.12.2/src/main/java/com/github/alexthe666/iceandfire/entity/EntityGorgon.java#L209

**Comment by CreativeMD** [comment]
Thanks a lot, I'm pretty sure the bug is fixed. I will close the issue as soon as it is confirmed. Again thanks for your help!
