### ISSUE TITLE
Fire dragon's breath attack loses its effect when griefing is off

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1011]
for ice dragons, they froze mobs with their breath, but for fire dragons, the breath don't set the mobs on fire on contact, since they put down fire, and the mob walk into it, when griefing is turned off, they can't set down any fire, and thats good, since fire itself is griefing

solution is set the breath to set mobs on fire like the ice dragons freezing ability.

**Comment by AlexModGuy** [comment]
fixed
