### ISSUE TITLE
Stage 5 Dragons vanish & sink into the void during battle!

### ISSUE THREAD

**Issue by Nimflora** [Alex-the-666/Ice_and_Fire#1013]
Twice now, while fighting stage 5 dragons underground - both fire AND ice - they've vanished. Upon entering spectator mode and floating below the ground, I find them still there - just clipping through layers of earth and slowly sinking into the void. I've tried to attach a lead to them and pull them back up to no avail. This is extremely upsetting, as I spend so many valuable materials to be able to fight these things, only to have my reward vanish due to an annoying glitch. PLEASE fix this!!!

**Comment by AlexModGuy** [comment]
in the meantime, don't use the ice dragon blood sword.

**Comment by Nimflora** [comment]
i haven't been!! but will keep in mind

**Comment by Darkmega18** [comment]
Cyclic monster balls are your friend. and so is creative mode if bull happens and you still want said reward that fell through the world to oblivion. :V

**Comment by Nimflora** [comment]
what are cyclic monster balls? also yes ive been doing that but approximating what i might have looted isn't the same as getting it

**Comment by Darkmega18** [comment]
Cyclic is a mod that adds some staffs and magical items of various natures and utilities. Pretty useful mod. The monster ball of which is an item that can pick up what seems to be most mobs and redeploy them elsewhere. of course this opens up all sorts of cheese, but it's also good for unstucking particularly large mobs and moving them around. just the other night I had a fire dragon hanging out on a mountain about to attack a village, so I 1v1'd him and slayed it without too much issue.

but then decided to take the dead dragon in a monsterball and leave it on my friend's door step as a present cause she wanted to... uh... study them, and potentially get an egg to get tamed one. but I don't think it was big enough. :P

**Comment by AlexModGuy** [comment]
dupe #1448
