### ISSUE TITLE
iceandfire 1.5.2 bug: Statues are not statues.

### ISSUE THREAD

**Issue by Darkmega18** [Alex-the-666/Ice_and_Fire#1014]
Well, to test the issue for the medusa player revive thing I toyed around with turning other things to stone first and having medusa do it herself, but instead I noticed that most if not everything that isn't something out of this mod being stoned doesn't properly have it's AI shut off or whatever you're doing. which resulting in stoned frozen mobs, 

even a lowly zombie or cow, just casually sliding along and looking around while stone or a gardener enderman (mobultion). They do have their animations frozen for the most part for vanilla things, but they just keep on rolling, usually a little slower than original, but still "alive" but at the same time reacting to a pick like there were statued and immune to most other attacks :V .

Sometimes I end up being able to do damage to said stoned enemies, and in the case of the cows I "killed" a few stone cows with the seeping damage that wasn't blocked.

**Comment by AlexModGuy** [comment]
mowzies mobs does this to the mod, dupe #307

**Comment by Iashar** [comment]
Many of these problems happen without that mod installed. The statues also Despawn. And they can be killed simply with a high enough damage weapon.

**Comment by bluecraney** [comment]
the sliding is toward the origin of the world
