### ISSUE TITLE
Something in the mod turns off particles

### ISSUE THREAD

**Issue by CrimsonToenail** [Alex-the-666/Ice_and_Fire#1017]
While using the mod, I don't know what triggers it, but after a few minutes, I notice that particle effects are missing. I tried turning them off and back on in the settings, and exiting the world, and rejoining. The only thing that fixes it is completely closing the game, and restarting it, but it eventually happens again.

**Comment by snakemasterepic** [comment]
I believe that it is pixies.  Not 100% confident, but I noticed the same issue with them in particular, and everything else is fine.

**Comment by AlexModGuy** [comment]
fixed
