### ISSUE TITLE
Villager zombies in snow zombie village will not become a snow villager

### ISSUE THREAD

**Issue by BlueWither** [Alex-the-666/Ice_and_Fire#1018]
<img src="https://i.imgur.com/3LR4skS.png">
It seems that there is no zombie of the snow villager.

**Comment by mser7** [comment]
Not yet

**Comment by AlexModGuy** [comment]
it would be quite difficult and not worth our time to add a them, especially considering how vanilla will be implementing their own snow villagers soon.
