### ISSUE TITLE
Cockatrice stare does not work like Gorgon

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1024]
Gorgon can petrified mobs despite they don't look at her, by turning their head, while cockatrice cannot, if the cockatrice can force the mob to look at it, then the stare will be much more effective.

**Comment by AlexModGuy** [comment]
no

**Comment by mser7** [comment]
Why not? It would help out the cockatrice so much

**Comment by mser7** [comment]
Fine
