### ISSUE TITLE
Dragons having trouble navigating through piles and layers

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1026]
Snow layers or Snow piles usually cause dragons to confuse due to their large widen hitbox, perhap make them move through those blocks? And this make the dragon look like they are sleeping inside the gold, more similar to folklore. This create a possibility of burring your dragon under the block, so it should walk on the block if it a one block full

**Comment by mser7** [comment]
Only large dragons should sink

**Comment by AlexModGuy** [comment]
#1449
