### ISSUE TITLE
this mod is not available on forge multiserver?

### ISSUE THREAD

**Issue by SimplyRin** [Alex-the-666/Ice_and_Fire#1034]
Owner name is not set when hatching dragon with multi server
On a multiserver, it is not recognized even if you right-click on the dragon with "Dragon Command Staff".

Minecraft Version: 1.10.2
Minecraft Forge: 1.10.2-forge1.10.2-12.18.3.2185
Ice And Fire Version: 1.0.2

![https://i.gyazo.com/1733e9e48cb7170d211723125cad319b.png](https://i.gyazo.com/1733e9e48cb7170d211723125cad319b.png)

**Comment by AlexModGuy** [comment]
1.10.2 is no longer supported. please update to  a 1.12.2 version
