### ISSUE TITLE
Cockatrice's glare is too weak

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1037]
Despite being the stronger attack, the glare still suck comparing to the melee. I propose adding more effects to the stare, the Wither III is nice, but maybe a strong dose of Slowness to implicate its paralize/petrifying ability, also Nausea would also be great, as this will annoy players

**Comment by mser7** [comment]
I am thinking Slowness so strong that it basically make the mob stand still like a statue, so the cockatrice can just keep staring until the mob is dead, and it cannot move any closer to fight the cockatrice.

**Comment by AlexModGuy** [comment]
ill do nausia

**Comment by mser7** [comment]
No slowness!???
