### ISSUE TITLE
Fire dragon's roost generate outside of Extreme Hills biomes

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1038]

**Comment by LordDecay26** [comment]
this isn't a bug, this works as intended, i do believe.

**Comment by mser7** [comment]
Many people complained that too common roost got in the way of their early game, and it overshadow the ice dragons spawn biome areas, another proof is that they was hinted to spawn only in extreme hills in early concepts, so I think it should be changed.
Since ice dragons also spawn in vanilla taiga and ice plains, I suggest add in deserts as another biome that can spawn fire dragons, along with extreme hills biomes

**Comment by EvilDylan** [comment]
It would also prevent them from spawning and immediately burning down a forest, which would be better on performance.

Presumably any dragon living in a forest would have burned it down long before any adventurer found it.

**Comment by AlexModGuy** [comment]
intended
