### ISSUE TITLE
Tamed cockatrice won't move after area unloads/loads

### ISSUE THREAD

**Issue by Crowfooted** [Alex-the-666/Ice_and_Fire#1044]
More explanation of symptoms:

Tamed cockatrice followed, patrolled and sat just fine to begin with - then after logging off, and logging back into the server, my cockatrice (that was in the area) would not move, even when set to following or patrolling.

Setting the cockatrice to ANY mode (including patrolling/following, with the standing up animation showing) and then dealing damage to it with a punch, causes it to do its sitting down animation.

My interpretation of this is that the cockatrice is stuck on sitting mode serverside.

**Comment by EvilDylan** [comment]
I had this issue with my own cockatrice. I believe I found a workaround.
I left it in follow mode when I next quit, and it began following me again when I reloaded.

This also seems server-side to me.

EDIT: I have also noticed that after growing up into an adult cockatrice, they do not tend to fight until the world is restarted; perhaps this is related?

**Comment by AlexModGuy** [comment]
fixed
