### ISSUE TITLE
Pneumaticraft Incompatibility: Exception in Gorgon setAttackTarget

### ISSUE THREAD

**Issue by mjdg** [Alex-the-666/Ice_and_Fire#1046]
When Pneumaticraft: Repressurized is installed and a Gorgon spawned, NullPointerExceptions are continually thrown inside a FutureTask.    The problem occurs in a small instance with only Ice and Fire, Pneumaticraft and JEI, though it only shows up in the logs.   The Ice and Fire version tested is 1.5.2, and Pneumaticraft version is 1.12.2-0.7.8-259.

Here are some crash reports from a larger instance generated by VanillaFix after encountering a Gorgon structure:

[Report 1 - first type of error seen](https://paste.dimdev.org/fipezeheke.mccrash)
[Report 2 - seen later, perhaps after Gorgon was unloaded](https://paste.dimdev.org/ugaqovojey.mccrash)

It seems like the problem is that Pneumaticraft adds a packet which causes setAttackTarget to be called on the client, but Ice and Fire assumes it's only called on the server.  I've no idea which mod is in the wrong here, but I've created this issue because it looks like it'd be easier to fix on the Ice and Fire side!

**Comment by EverSoul** [comment]
I am getting this crash as well. Wish I had a clue how to fix. Every time I encounter a gorgon I crash.
