### ISSUE TITLE
Stage 5 Dragons

### ISSUE THREAD

**Issue by Iashar** [Alex-the-666/Ice_and_Fire#1050]
Stage 5 dragon geodes are currently able to spawn inside/on top of one another. This makes for a TON of lag when engaging one of them, as the other begins breaking blocks to attack as well, and the volume of broken blocks alone is pretty impressive. They also tunnel up and out of the terrain if they catch you in their mouth, making the grounded items problem even more exacerbated. 
I'd like to suggest that Dragon geode generation be spaced by at least 300 blocks from center of one to center of the other.
And maybe make the geode itself not breakable by the dragon, unless the tunneling to surface is intended...?

**Comment by snakemasterepic** [comment]
I know that tunneling is intended because otherwise, you could just dig a hideout tunnel and use fire resistance to safely snipe the dragon without much combat, but the rest of this issue is definitely a design bug.

**Comment by AlexModGuy** [comment]
fixed
