### ISSUE TITLE
Totem of Undying Renders Player Immune to Gorgon

### ISSUE THREAD

**Issue by snakemasterepic** [Alex-the-666/Ice_and_Fire#1051]
If the player looks at the gorgon with a totem of undying, a statue is created, but the player appears to have the totem still intact despite it actually being consumed.  If the player places another item in the slot occupied by the totem, the totem will disappear.  However, in this state, the player can look at the gorgon and attack without any problem.

**Comment by LordDecay26** [comment]
kinda sounds like a baller feature tbh

**Comment by mser7** [comment]
Tbh, it sounded legit to be a feature, but right now, the totem prevent the gorgons petrification, but will completely mess up the game afterward, relogging will fixed this.

I don't remember whether the totem will be consumed after the gorgon kill you.

**Comment by AlexModGuy** [comment]
seems legit tho
