### ISSUE TITLE
I:"Dragon Griefing"=0 doesn't stop dragons from destroying everything.

### ISSUE THREAD

**Issue by ProsperCraft** [Alex-the-666/Ice_and_Fire#1054]
# Dragon griefing - 2 is no griefing, 1 is breaking weak blocks, 0 is default [range: 0 ~ 2, default: 0]
    I:"Dragon Griefing"=0

this is my config- yet dragons still roast blocks to ash they spit fire at.

**Comment by Crowfooted** [comment]
Can confirm - obviously the config only refers to the dragon's ability to actually break blocks, but their fire can still convert it, which can be upsetting for people wanting to preserve their worlds.

**Comment by tyler489** [comment]
Doesnt it say thay that needs to be a 2 for no griefing??

**Comment by Crowfooted** [comment]
Yeah, there is a bit of a mistake in the OP but I can confirm that setting it to 2 does prevent dragons from destroying blocks directly, but its fire attack still converts blocks to charred stone, which is still pretty griefy.

**Comment by AfterRebelion** [comment]
You must be using an old version, because in 1.5.2-1.12.2 `I:"Dragon Griefing"=2` stops all kinds of griefing, even dragon breath attacks.
