### ISSUE TITLE
[1.5.2-1.12.2] Walk Node Processing Crashing Dedicated Server

### ISSUE THREAD

**Issue by kreezxil** [Alex-the-666/Ice_and_Fire#1059]
Server Crash Reports:
http://paste.ubuntu.com/p/krqmkJtz6s/
http://paste.ubuntu.com/p/jHh2t8Pgss/

I don't know what the players were doing.

**Comment by AlexModGuy** [comment]
@kreezxil change the max-tick-time in server.properties to -1. It's the only solution I've discovered.

**Comment by kreezxil** [comment]
that encourages insane lag. I've been using values like 480000, which is
also insane. But I will try your solution.
