### ISSUE TITLE
Add configuration option to disable dragon griefing

### ISSUE THREAD

**Issue by Sunconure11** [Alex-the-666/Ice_and_Fire#106]
There should be a configuration setting for disabling dragon griefing, but it should take certain values to allow certain amounts of griefing

0 = off
1 = dragon fire spreads (this could be swapped with the option for 2 though if you desire)
2 = dragons can break plants
3 = default

There should also be options to allow players to change the distance between dragon nests, and toggle the spawn rate of mobs.

**Comment by PlatinumFox** [comment]
i would agree with this

**Comment by JayZX535** [comment]
I agree as well.
