### ISSUE TITLE
Dragons break graves from the Tombstone mod.

### ISSUE THREAD

**Issue by ProsperCraft** [Alex-the-666/Ice_and_Fire#1060]
I have lost my equipment, and players due to the fact that dragons don't respect hardness when breaking/converting blocks to ash.  

Perhaps blocks could be checked for hardness before converted/broken?

**Comment by ghost** [comment]
btw, tombstone has specially changed the unlocalized name of grave to have a chance to be compatible, but some attacks seem to not check this condition.

**Comment by AlexModGuy** [comment]
fixed
