### ISSUE TITLE
Mod ignores "Dangerous World Gen Distance From Spawn" config

### ISSUE THREAD

**Issue by Crowfooted** [Alex-the-666/Ice_and_Fire#1062]

**Comment by ProsperCraft** [comment]
Can confirm.

**Comment by darchitectlp** [comment]
Literally spawned next to a mermaid rock. Had the "dangerous world gen" set to 1200 blocks...

**Comment by crazyirishwrencher** [comment]
Elsewhere it was posted that the value needs to be squared. Thus if you want 1000 block "safe zone" you have to actually set the value to 1,000,000. The poster said they derived the claim from looking at the source code.

**Comment by AlexModGuy** [comment]
fixed
