### ISSUE TITLE
Crash on load into world.

### ISSUE THREAD

**Issue by Huxington** [Alex-the-666/Ice_and_Fire#1064]
Been playing the Ancient Towncraft Modpack, and you start off in the Between Lands, and as soon as I get to the overworld I crash and get States, Ice and Fire.

From what I can tell I spawn beside a dragon, and as soon as it uses its fire breath I crash. Ive sunk at least 6 hours into the game already, so I really hope this can be fixed.

https://paste.dimdev.org/vadafapobo.mccrash

**Comment by ProsperCraft** [comment]
Hello Huxington, I am the author of that pack, and we have been working with the States mod which was just added to fix this, disable the States mod, and you will be able to continue as we get the conflict sorted out.

**Comment by Huxington** [comment]
Thanks a bunch! Works just fine now
