### ISSUE TITLE
villager trading re balance needed.

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#107]
I noticed that villager trading is really really unbalanced. Pictures below to show. It all just seems off and completely like its wrong. There are alot more examples if one were to go and look.

![2016-12-24_20 36 15](https://cloud.githubusercontent.com/assets/23727270/21469454/46946fc2-ca1d-11e6-96ae-590ead516a64.png)

![2016-12-24_20 36 21](https://cloud.githubusercontent.com/assets/23727270/21469455/49afe678-ca1d-11e6-8196-32a029aae294.png)

![2016-12-24_20 39 39](https://cloud.githubusercontent.com/assets/23727270/21469456/4b5ac8da-ca1d-11e6-9164-1aa8b9e69ac0.png)

![2016-12-24_20 43 36](https://cloud.githubusercontent.com/assets/23727270/21469457/4ce5baac-ca1d-11e6-9c21-9ecedafdcf3e.png)

**Comment by Alex-the-666** [comment]
image number 2 and 4 are as intended, not so much the other too.
