### ISSUE TITLE
Deathworms Stuck Burrowing + Deathworm Clipping

### ISSUE THREAD

**Issue by verybutter** [Alex-the-666/Ice_and_Fire#1070]
Deathworms, both tamed and wild, are stuck under the ground burrowing. No matter what blocks are destroyed, they remain under and do not respond to player or mob presence. The only way I've been able to get rid of them is with the /kill command. I'm going out on a limb here and assuming this is a bug, and it's kind of annoying when you have pet deathworms with sand pens.

There's another one where the deathworms keep clipping through the floor of any material, in my specific cases, falling into pens below, and past that, onto the surface (the base they're in is in the air).

**Comment by AlexModGuy** [comment]
dupe #928
