### ISSUE TITLE
Wild dragons melt trough the floor and end up under the world

### ISSUE THREAD

**Issue by samoja12** [Alex-the-666/Ice_and_Fire#1071]
This is not once in the blue moon occurrence, it happens often enough to be annoying, about 1/4 or even up to 1/3 of all dragons i attack will at some point, after taking some damage, vanish, when searching for dragon lairs i found out where they went, switching to creative i went trough bedrock to confirm it, and sure enough, missing dragons were right there, under bedrock, flapping away fruitlessly.

**Comment by AlexModGuy** [comment]
fixed
