### ISSUE TITLE
I kill a dragon and the loot dont appear 

### ISSUE THREAD

**Issue by JosefoMaster** [Alex-the-666/Ice_and_Fire#1072]
i kill a lot of dragons in my world and i right click the corpse but the loot dont appear at all pls help

**Comment by samoja12** [comment]
Your hand needs to be empty.

**Comment by JosefoMaster** [comment]
My hand is empty, the dragon became bones and then dissapear but 0 loot

**Comment by samoja12** [comment]
try reinstalling the mod, also are you running any other mods besides, they may be creating a conflict.

**Comment by JosefoMaster** [comment]
I found the problem, the mod Selims Enchants is creating the conflict, how do i fix this?

**Comment by JosefoMaster** [comment]
Nevermind the creator of selims mods fix this problem, thanks!
