### ISSUE TITLE
Hypogryph breeding breaks occasionally

### ISSUE THREAD

**Issue by samoja12** [Alex-the-666/Ice_and_Fire#1074]
I don't know what is causing it, but sometimes Hypogryphs will just refuse to breed, i know that accidentally mounting them breaks them for sure but recently i had a previously breeding pair break at random after already being bread several times, they still take rabbit stew but they will stay on the ground and nor move towards each other, as far as i can tell after extensive testing the condition is irreversible.

**Comment by AlexModGuy** [comment]
#1659
