### ISSUE TITLE
Dragon horn can depetrify tamed dragons

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1078]
Capture a petrified tamed dragon using the horn. and upon release it is good as new

**Comment by ghost** [comment]
I would rather keep it this way and be a secret.

**Comment by ghost** [comment]
Ill treat it as a feature

**Comment by mser7** [comment]
Tamed dragons should drop their armor once petrified if this got fixed

**Comment by AlexModGuy** [comment]
fixed
