### ISSUE TITLE
Dragon has sleeping problems

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#108]
I watched as an ice dragon landed from flying, it started spinning in a circle trying to sleep and eventually fell asleep. as it slept it preceded to move about in what I can only describe as like a puck on an air hockey table. it also was breaking the ground while doing this spinning/sliding sleeping glitch. At one point it also turned invisible. i was using optifine zoom while it turned invisible but i got closer to it and it turned invisible again without using optifine zoom.
![2016-12-24_20 47 28](https://cloud.githubusercontent.com/assets/23727270/21469468/ee17c4a6-ca1d-11e6-92b6-fb4a82800004.png)
![2016-12-24_20 47 31](https://cloud.githubusercontent.com/assets/23727270/21469469/f0fb6704-ca1d-11e6-9519-6fc65685ece8.png)
![2016-12-24_20 47 32](https://cloud.githubusercontent.com/assets/23727270/21469470/f307d08c-ca1d-11e6-80b8-e9d91361f06c.png)
![2016-12-24_20 47 33](https://cloud.githubusercontent.com/assets/23727270/21469472/f4e409f2-ca1d-11e6-8241-5aa0e322f5a8.png)
![2016-12-24_20 47 41](https://cloud.githubusercontent.com/assets/23727270/21469473/f7742b34-ca1d-11e6-8a82-9c6bb55c262c.png)
![2016-12-24_20 47 43](https://cloud.githubusercontent.com/assets/23727270/21469474/f9673efe-ca1d-11e6-8f8c-d9ff967f2894.png)
![2016-12-24_20 47 53](https://cloud.githubusercontent.com/assets/23727270/21469475/fc33e31c-ca1d-11e6-8367-dc863bc07d9a.png)

**Comment by Alex-the-666** [comment]
I'm unable to replicate this issue. Is anyone else able to?

**Comment by PlatinumFox** [comment]
I replicated it again in Beta 6 I just watched those 2 naturally spawning dragons for a while. Recorded it this time (I had my recording software open) Unlisted video you can only view with the link below.

https://www.youtube.com/watch?v=i0CPP_RqetE

**Comment by Alex-the-666** [comment]
Hmm. does this only happen when the dragon was flying earlier?

**Comment by PlatinumFox** [comment]
Now that I think of it that could be a possibility. That is the same dragon that was flying in the jerky flying video I put up. Maybe it happens when they land.

**Comment by Alex-the-666** [comment]
Is this still an issue in build 07?

**Comment by PlatinumFox** [comment]
just got home form work, will get beta 7 and start testing

**Comment by Alex-the-666** [comment]
... and does it still happen?

**Comment by PlatinumFox** [comment]
I have yet to see it happen again. It's just one of those things that happened by chance.

**Comment by Alex-the-666** [comment]
Reopen if it occurs again.
