### ISSUE TITLE
Suggestions bc I don't know where else to put them

### ISSUE THREAD

**Issue by CosmicGlowsticks** [Alex-the-666/Ice_and_Fire#1081]
More frozen/charred block types, like frozen and charred fences and walls, glass/windows, iron bars, sand, and doors would be great. Or perhaps an ice-themed light source for my little ice dragon nursery and cave for the larger ones.

With this mod, I've always wanted to make a kingdom/medieval/fantasy themed world. I would suggest either adding to villages with castles, or even a bit of a stretch and adding a whole kingdom biome.

This one guy in the comments on the forge page suggested various creatures like the hydra, basilisk, etc. And I LOVED that suggestion. I second it. And I would like to add to that with kelpies. They're creepy, and somewhat similar to sirens in the sense of luring. I also suggest more aquatics in addition to the hippocampus, sirens, and serpent (Which I hope is tamable, it says nigh on impossible, so I mean I think that means it might just happen) to bring more life to the oceans. Like, a kraken or something.

I also suggest more types of dragons, not in terms of elements though. Currently, there is one species for both fire and ice elements; wyverns. I suggest other types, such as quadrupedal for those who prefer that. I personally prefer the wyverns, though. I've just seen that suggestion a few times and thought I'd put it out there. 

I'm just spitting out things I'd like to see, NOT demanding at all, sorry if I come across that way, as I don't intend to at all. Basically an idea puke bucket, with ideas listed how much I'd like to see them most to least. If I sound rude at all, I apologize ahead of time, that's a personal problem I have, I have trouble telling if I sound rude or not. 

Feel free to add in the comments, release your idea puke here, I guess

**Comment by PCAwesomeness** [comment]
https://github.com/Alex-the-666/Ice-and-Fire-Suggestions/issues

**Comment by mser7** [comment]
Now you should close this issue
