### ISSUE TITLE
Dying to a Gorgon deletes any worn armour

### ISSUE THREAD

**Issue by GamertechAU** [Alex-the-666/Ice_and_Fire#1083]
MC: 1.12.2
IaF: 1.5.2

When a player is killed by the Gorgon's stare, the statue forms as intended and a grave is spawned at the site with their inventory.

The issue is, any armour they were wearing gets deleted, both vanilla and modded.

This only occurs if the player dies to a Gorgon, with all other deaths the tombstone saves the armour as intended. I can't find anything about this in the wiki, so I'm assuming this is a bug.

**Comment by ghost** [comment]
Hi Gamertech, to fight a gorgon, you need a blindhold to not be turned in stone.
I made some checks, and when you don't have this item on your eyes (to have the effect Blindness 3 on you), a statue appears and your equiped items (in armor slots) are waste forever (as the statue is only decorative and can be picked up with silk touch)
Also, this is the normal behavior (with grave mod or not, it's the same result), so i think my mod isn't involved in this issue.
NB : now, it's up to Alex to see if the armor should be dropped or not.

**Comment by GamertechAU** [comment]
I'm aware of the blindfold, but the armour being deleted can be incredibly painful as the Gorgon can 1 shot any unprepared player even wearing end-game gear, a lot of which can be very expensive to craft.

Ideally, the armour should be dropped into the grave as per any other death. I'll change the title too.
