### ISSUE TITLE
Lair blocks replacing bedrock

### ISSUE THREAD

**Issue by Siteris** [Alex-the-666/Ice_and_Fire#1085]
If underground dragon lair spawns very low in the world, it might replace the bedrock blocks with the lair blocks such as icy cobble and that ashen cobble stuff if it is close enough...  (already caused 2 deaths :D)
![2018-10-01_17 01 01](https://user-images.githubusercontent.com/43758819/46305577-802fb800-c5ba-11e8-960b-5caeabd4e8a7.png)

**Comment by kuroyure** [comment]
They also replace end portals

**Comment by medtryx** [comment]
I just had the end portal in my world overwritten by a Dragon lair as well. 
![2018-10-25_15 09 28](https://user-images.githubusercontent.com/17153102/47547738-4487c580-d8bc-11e8-92b0-144246c9fc63.png)

**Comment by mser7** [comment]
This is verey bad

**Comment by AlexModGuy** [comment]
fixed
