### ISSUE TITLE
Too many dragons and no way to stop them from destroying blocks

### ISSUE THREAD

**Issue by ClockyVaudeville** [Alex-the-666/Ice_and_Fire#1086]
I played around with this mod  a few weeks ago and the most glaring issue I found was that dragon nests spawned absolutely everywhere. For example I could go wandering and find two level 3 dragon nests within less than 30 blocks of each other. Beyond this I found with my tamed dragons they destroyed blocks even after I went into the config and set them to not be able to destroy anything. Is anyone else having this issue? If so can you guys help me fix it? I love this mod but it's a shame I can't play it.

**Comment by Morinor** [comment]
I usually set the chance for generating dragon lairs to some ridiculosly high numbers, at least over 2000.
Thats fine for single player, but on a server thats still too many dragons, and each destroys a large area around itself...

**Comment by AlexModGuy** [comment]
config
