### ISSUE TITLE
Hippogryph disappears when effected by Siren's Song

### ISSUE THREAD

**Issue by Rogue186** [Alex-the-666/Ice_and_Fire#1087]
upon flying near a siren in survival and being effected by her song the hippogryph mount being ridden would disappear. this first occured on a personal server and was tested 3 times (twice in creative world, having recreated the apparent dissapearing; and once on the server in question where the hippogryph appeared to have stayed on the journeymap [minimap mod we are using] but then disappeared soon after being effected by the song)

**Comment by mser7** [comment]
I think this also happen when you are grabbed by a dragon or cyclops.

**Comment by AlexModGuy** [comment]
not able to reproduce
