### ISSUE TITLE
Stymphalian arrows wont fire with dragon bone bow

### ISSUE THREAD

**Issue by GamertechAU** [Alex-the-666/Ice_and_Fire#1089]
MC: 1.12.2
Forge: 2765
Ice and Fire: 1.5.2

When used with stymphalian arrows the dragon bone bow won't fire.

The same arrows work with other bows, and the dragon bow works fine with other arrows. It's just those 2 combined that have an issue.

**Comment by AlexModGuy** [comment]
the dragon bow is meant to only fire dragon arrows.
