### ISSUE TITLE
Dragon Meal has Broken Recipe

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#109]
Was just messing around with things and noticed that the dragon meal recipe is bones with any protein. the results where interesting. (I dont think dragons eat silver)
![2017-01-08_16 03 14](https://cloud.githubusercontent.com/assets/23727270/21753506/d738b524-d5bc-11e6-877c-e35eb6b3b135.png)
reference^^
![2017-01-08_16 06 17](https://cloud.githubusercontent.com/assets/23727270/21753508/dd5464e4-d5bc-11e6-8d4f-e957857b2b2e.png)
![2017-01-08_16 06 28](https://cloud.githubusercontent.com/assets/23727270/21753511/dec8deea-d5bc-11e6-89b7-ff6dc2353e3d.png)
![2017-01-08_16 06 41](https://cloud.githubusercontent.com/assets/23727270/21753512/e0195d38-d5bc-11e6-8539-e65ab4415fd0.png)
![2017-01-08_16 06 50](https://cloud.githubusercontent.com/assets/23727270/21753513/e1a7edd6-d5bc-11e6-80c6-1c1cab796bb9.png)
![2017-01-08_16 07 04](https://cloud.githubusercontent.com/assets/23727270/21753515/e329c7ec-d5bc-11e6-978c-331e41fe6733.png)
![2017-01-08_16 07 31](https://cloud.githubusercontent.com/assets/23727270/21753518/e49fdaee-d5bc-11e6-892f-b2f868d01376.png)

**Comment by Alex-the-666** [comment]
ill try fixing this asap :)

**Comment by Alex-the-666** [comment]
fish are not supposed to be on its recipes, as it should be a bit harder to obtain meat than just spening a few minutes fishing.
