### ISSUE TITLE
silver weapons don't do extra damage to undead

### ISSUE THREAD

**Issue by Shivaxi** [Alex-the-666/Ice_and_Fire#1090]
as the title says, pretty straight forward issue, silver weapons are not doing the extra +2 damage to undead that they claim they are.  Tested on a skeleton for example, silver sword, which claims to do 5 attack damage +2 to undead.  Skeleton took 5 damage every swing.  Tested on something not undead just to see, like a pig and cow, who also took exactly 5 damage.

**Comment by AlexModGuy** [comment]
fixed
