### ISSUE TITLE
Huge walls of unexplored chanks

### ISSUE THREAD

**Issue by Tarena397** [Alex-the-666/Ice_and_Fire#1091]
Hello. I would like to ask if the mod generates any biome itself, coz today when I started to explore unexplored land I got a huge wall on the chanks border (Which was lead to snow villagers and an ice dragon). It was a snow biome just in the middle of the Cherry Blossom Forest (I play with Biomes O' Plenty ). Any solution for this?` 
(Plus it creates an empty chunk)

https://ibb.co/kXQHeU
https://ibb.co/m74ztp
https://ibb.co/gaauR9
https://ibb.co/i7RCDp
https://ibb.co/htNkYp
https://ibb.co/jdOg69

(I'm sorry, I'm not quite sure how to post an image here)

**Comment by PlatinumFox** [comment]
@Tarena397 those flat walls are just chunk errors in the game. Basically the game messed up when trying to load that part of the world. They are not part of the mod. They can happen with any mod that adds world generation such as new structures and biomes.

**Comment by Tarena397** [comment]
> @Tarena397 those flat walls are just chunk errors in the game. Basically the game messed up when trying to load that part of the world. They are not part of the mod. They can happen with any mod that adds world generation such as new structures and biomes.

Thank You for the reply! 
Idk, I think it might happen because of the new BOP version I loaded (I do not use any other World generation mods), but that chunks bug occurs after I installed Ice and Fire because that snow biome is where I found Ice villagers and Ice dragons.

**Comment by EvilDylan** [comment]
Whenever you add new biomes to a world, it means that the same seed will yield a different result. These messy chunk boundaries occur when you generate new parts of the world after doing this, as it will generate the world according to what should be there with the new biomes installed, not what was there in the old seed calculation.

If you check in F3, I imagine you'll find that the cherry blossom forest isn't called a cherry blossom forest by the game anymore.
