### ISSUE TITLE
troll should make Different damage can be caused by different actions?

### ISSUE THREAD

**Issue by MokoBlack** [Alex-the-666/Ice_and_Fire#1094]
Just a suggestion.
i see the troll attack action so reallike and nice but it just make the same damage 
so i think why not make the troll's attack damage based on it's attack action and dirrerent effect？
 for example:
the chop can make more damage than base damage
the sweeping can attack multiple tragets 
the kick can make more knockback
i like this mob of ice and fire (also dragon）

**Comment by AlexModGuy** [comment]
no
