### ISSUE TITLE
Items don't drop when killed by Fire/Ice Dragon- is this intended behaviour?

### ISSUE THREAD

**Issue by Seraphaestus** [Alex-the-666/Ice_and_Fire#1095]
First time this happened I reasoned it as the dragon burning me to a crisp along with my items, but the second time I died was to an ice dragon which attacked me with its ice spikes attack, which doesn't seem to make sense that it would result in none of my items spilling out when I die

**Comment by AlexModGuy** [comment]
ice dragons destory items to equal them with fire dragons
