### ISSUE TITLE
Ticking entity crash

### ISSUE THREAD

**Issue by Bradwurst** [Alex-the-666/Ice_and_Fire#1097]
[crash-2018-10-22_14.52.41-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/2503101/crash-2018-10-22_14.52.41-client.txt)

Game crashes to desktop while exploring, or in chunks with Ice and Fire entities. Error given is ticking entitiy.

**Comment by DingleFlop** [comment]
This happens on MP, only crashes client.

**Comment by DingleFlop** [comment]
https://paste.dimdev.org/aduzuwowad.mccrash

Actually it does seem to be all I&F entities. This is the same thing happening with a Dragon.

**Comment by AlexModGuy** [comment]
mod conflict causes this issue, another mod is registering properties to our mobs that upsets the order of tracking values. It is usually primitive mobs, minecraft comes alive or animania, but I don't see any of those.

**Comment by GordoGavin** [comment]
> mod conflict causes this issue, another mod is registering properties to our mobs that upsets the order of tracking values. It is usually primitive mobs, minecraft comes alive or animania, but I don't see any of those.

Are there any other mods off-hand that you would know that tick ice and fire this because pretty much every 10 minutes I'm on my RAD server it crashes from something in the ice and fire mod.
