### ISSUE TITLE
Crash when connecting near (on?) Hippogryph after server restart,

### ISSUE THREAD

**Issue by DingleFlop** [Alex-the-666/Ice_and_Fire#1099]
This crash happens when connecting or walking into an area that causes a Hippogryph to load. This was using recommended forge 2768 with mod version 1.5.2

https://paste.dimdev.org/olecatexuy.mccrash

Adds to 
https://github.com/Alex-the-666/Ice_and_Fire/issues/1097

**Comment by AlexModGuy** [comment]
another mod is writing over ice and fire data. tell them not to ascribe DataParameters to classes that dont need them!
