### ISSUE TITLE
Config option for safe radius around spawn does not seem to work.

### ISSUE THREAD

**Issue by thedustboy** [Alex-the-666/Ice_and_Fire#1103]
For some reason, when I change the config option for radius around spawn to not spawn hostile mobs (Dragons, etc.), they still spawn inside that radius. The radius I tried to use is 3000 blocks, maybe that is too high? The range given in the config file is "1 ~ 2147483647"

**Comment by Morinor** [comment]
Yea, Ive got that issue too.
Im currently working on the modpack for the unofficial official thaumcraft discord, and until now, iceandfire was a part of it (I love the mod), but even though the dragon generation was set to 3000 and something, over time, the dragons and other mobs just got annoying.
So we can only keep it if theres a way to keep the dragons out of the area people base in...
As I saw this config option I thought thatd be it, but sadly it doesnt seem to work

**Comment by AlexModGuy** [comment]
fixed
