### ISSUE TITLE
Deathworms get stuck in the ground

### ISSUE THREAD

**Issue by Jack-0-Spades** [Alex-the-666/Ice_and_Fire#1105]
I have noticed several mid-sized and smaller deathworms getting stuck in the sandstone layer below the desert sand. This does not happen to bigger worms, but does happen often enough to be annoying especially if you are hunting them.

**Comment by laserlemons** [comment]
I'm also seeing this issue. I must not have seen any large death worms because they're all stuck on my server.

**Comment by AlexModGuy** [comment]
fixed
