### ISSUE TITLE
Please set take away Hippogryph's wander. 

### ISSUE THREAD

**Issue by Jack-0-Spades** [Alex-the-666/Ice_and_Fire#1106]
Just as the title says, maybe you could make it a config option, to disable wander on tamed Hippogryphs, or at least add a way to call them back. Once they get going it can be easy to lose them forever, which is really sad. :(

**Comment by Jack-0-Spades** [comment]
Even if they are sitting they will still sometimes fly off, at which point you can kiss them all all the stuff they carry goodbye.

**Comment by mser7** [comment]
You can shift right click it with a stick to set a home point, so it will always return, this is on the authors fault for not fully aware players of this feature

**Comment by Jack-0-Spades** [comment]
That is very useful to know, thank you. I still think there should be more ways to call your hippogryph to you, as it can be easy to lose.
