### ISSUE TITLE
I can not find sirens, deathworms, or any newer mobs.

### ISSUE THREAD

**Issue by SKILLZTIME** [Alex-the-666/Ice_and_Fire#1107]
I play in 1.12.2, I have dowload several different versions of LLibrary and Ice and Fire but I can not find:
-Sirens
-Hippocampi/Hippocampus
-Death Worm
-Stymphalian Bird
-Cocatrice
-Troll
-Sea Serpent
-Myrmex
-Amphiptere
Please help as I really want to see these mobs.
I have the latest ice and fire mod version for 1.12.2 and the latest 1.12.2 LLibrary.
PLEASE HELP

**Comment by SKILLZTIME** [comment]
Also I forgot, I can not find any new items either

**Comment by BlueWither** [comment]
What version? The latest version is 1.5.2.
You should search them in creative mode.
Sea Serpent, Myrmex, Amphithere are not added yet.

**Comment by SKILLZTIME** [comment]
I do search them in creative. Also thanks I will check the version.

**Comment by AlexModGuy** [comment]
update the mod. theres no way they wouldnt be there. Make sure youre downloading from the actual, official curseforge, not some third party website.
