### ISSUE TITLE
Dragons hunting AI ignore height limit?

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1110]
Another issue related to flying limit, I was having my dragon flying around a homepoint, until a zombie attack me and the dragon approach the mob, killing it, then I have it start flying again, but this time, the dragon fly above the limit and ascend forever, then I have it kill another mob, which fixed it.

**Comment by GundunUkan** [comment]
I've encountered the same problem, dragons randomly ignore the height limit, more often than not.

**Comment by AlexModGuy** [comment]
fixed
