### ISSUE TITLE
Could you add a config option for Hippogryph / Dragon flight speed?

### ISSUE THREAD

**Issue by Frinckles** [Alex-the-666/Ice_and_Fire#1113]
I enjoy using them as transportation but they're a bit too fast by default. It would be nice to be able to tone them down slightly. Thanks.

**Comment by aleferna12** [comment]
Would just like to support this idea, the Hippogryphs are a little too fast and that hinders the Amphithere practically useless. If the latter has a flight speed option, I'm sure it would be possible for the other flying mounts!
