### ISSUE TITLE
Dragons disappearing

### ISSUE THREAD

**Issue by CytricAcid** [Alex-the-666/Ice_and_Fire#1114]
this has happened to me twice now- once, when my server shut down while i was riding a dragon, and when i started the server back up, my dragon was gone.

the second time my server must have bugged because as soon as i mounted my dragon, it started vibrating in the opposite direction i wanted to go, and then suddenly i was on the ground, no dragon in sight. 

nothing in the logs seems to show anything unusual, except missing the usual "[dragon name] moved too quickly!" that usually happens when i'm flying.
forge version: 14.23.5.2770

**Comment by kreezxil** [comment]
install gotta go fast mod to solve the moved to quickly messages. I've found that relogging the client returns the dragons. Also use the dragon horn to recall them. Other than that he's gonna need some kind of log to fix your issue.

**Comment by AlexModGuy** [comment]
install gotta go fast mod

**Comment by AlexModGuy** [comment]
dupe #1447
