### ISSUE TITLE
[1.5.2-1.12.2] On Forge build 2772 Pathfinding server crash is back

### ISSUE THREAD

**Issue by kreezxil** [Alex-the-666/Ice_and_Fire#1115]
http://paste.ubuntu.com/p/2YP8H3XtrZ/
http://paste.ubuntu.com/p/TsVFFPdVjJ/
http://paste.ubuntu.com/p/j5gHCvKh6s/
http://paste.ubuntu.com/p/nzfskJvMST/
http://paste.ubuntu.com/p/vdPR3hyvbv/
http://paste.ubuntu.com/p/bckTjN2p4M/
http://paste.ubuntu.com/p/TwqwDcJ5qr/
http://paste.ubuntu.com/p/zqSKBXHvFQ/
http://paste.ubuntu.com/p/X4qpQKyHMs/
http://paste.ubuntu.com/p/SKt6nnRkHD/

**Comment by AlexModGuy** [comment]
in server.properties change max tick time to -1 to fix this. nothing I can do about it
