### ISSUE TITLE
[1.5.2-1.12.2] on Forge build 2772 VillagerAIFearUntamed crashing dedicated server

### ISSUE THREAD

**Issue by kreezxil** [Alex-the-666/Ice_and_Fire#1116]
http://paste.ubuntu.com/p/Dpvth8V5QV/
http://paste.ubuntu.com/p/428rrgRB64/

**Comment by AlexModGuy** [comment]
> 	at com.minecolonies.coremod.entity.EntityCitizen.func_70636_d(EntityCitizen.java:557)

This is an issue with minecolonies. The Ice and Fire code doesn't contain any iterations whatsoever(which is what is causing the crash) so some other mod is interfering
