### ISSUE TITLE
Dragons Not Spawning

### ISSUE THREAD

**Issue by appleschloss** [Alex-the-666/Ice_and_Fire#1117]
I'm running a server where this is in the modpack on the server and we keep having occassional issues of dragons not being in their underground nests. One nest even had 0 treasure in it but it hadnt been touched before.

**Comment by appleschloss** [comment]
Also have now had an instance where we had a dragon spawn in their nest properly, only to despawn when we had to leave and come back to it

**Comment by appleschloss** [comment]
13.11 11:19:01 [Server] Server thread/WARN [Sponge]: Entity NBT: {HurtByTimestamp:0,Attributes:[{Base:462.0d,Name:"generic.maxHealth"},{Base:0.0d,Name:"generic.knockbackResistance"},{Base:0.4760000002384186d,Name:"generic.movementSpeed"},{Base:0.0d,Name:"generic.armor"},{Base:0.0d,Name:"generic.armorToughness"},{Base:64.0d,Name:"generic.followRange"},{Base:17.0d,Name:"generic.attackDamage"}],Invulnerable:0b,ArmorTail:0,Gender:0b,AbsorptionAmount:0.0f,AttackDecision:0b,Hovering:0b,FallDistance:0.0784f,InLove:0,FireBreathing:0b,ForgeCaps:{"llibrary:extendedentitydatacapability":{"Ice And Fire - Siren Property Tracker":{CharmedBySiren:0b},"Ice And Fire - Stone Property Tracker":{StoneBreakLvl:0,TurnedToStone:0b}}},HandDropChances:[0.085f,0.085f],PersistenceRequired:0b,Items:[],ArmorNeck:0,ArmorBody:0,ArmorHead:0,ModelDead:0b,Leashed:0b,HomeAreaZ:2360,HomeAreaY:27,HomeAreaX:-632,Air:300s,DeadProg:0.0f,HandItems:[{},{}],AgeTicks:2760136,Variant:0,ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],OwnerUUID:"",Flying:0b,Tackle:0b,Pos:[-631.5d,14.796599998474122d,2360.5d],CanPickUpLoot:0b,HurtTime:0s,ForgeData:{SpongeData:{CanGrief:1b,maxAir:300}},Sitting:0b,FallFlying:0b,ForcedAge:0,PortalCooldown:0,Hunger:50,DeathTime:0s,Age:0,Motion:[0.0d,-0.1552320045166016d,0.0d],UUIDLeast:-9141632315606266391L,Health:462.0f,LeftHanded:0b,OnGround:0b,Dimension:0,DeathStage:0,Rotation:[202.82437f,0.0f],UpdateBlocked:0b,UUIDMost:-2355548543758286181L,Sleeping:1b,Fire:-1s,ArmorItems:[{},{},{},{}]}
13.11 11:19:01 [Server] Server thread/WARN [Sponge]: Entity: EntityFireDragon['Fire Dragon'/466006, l='world', x=-631.50, y=14.80, z=2360.50]
13.11 11:19:01 [Server] Server thread/WARN [Sponge]: Entity bounding box: null
13.11 11:19:01 [Server] Server thread/WARN [Sponge]: Calculated bounding box: box[-636.8235002607107, 14.796599998474122, 2355.1764997392893 -&gt; -626.1764999479055, 23.19660057067871, 2365.8235000520945]
13.11 11:19:01 [Server] Server thread/WARN [Sponge]: Motion: (0, -0.155, 0)
13.11 11:19:01 [Server] Server thread/WARN [Sponge]: BB Size: 1,210 &gt; 1,000 avg edge: 9.898
13.11 11:19:01 [Server] Server thread/WARN [Sponge]: Entity being removed for bounding box restrictions

**Comment by GundunUkan** [comment]
Check if the config option for dragons despawning is set to "True".

**Comment by appleschloss** [comment]
Yes. The majority of our dragons spawn in just fine, but the large nests seem to turn up empty at least 50% of the time.

**Comment by appleschloss** [comment]
It is, but is it normal for them to despawn and then not respawn when youre back in the chunk? Or to never have spawned if you were in the chunk?

**Comment by GundunUkan** [comment]
They will _not render_ when you exit the chunk, not despawn. What the config means is that is you set it to true you allow dragons to permanently despawn.

**Comment by appleschloss** [comment]
My only concern is that theres a warning under it for if you leave it as false it could cause lag and our server already has occasional issues with lag.

**Comment by appleschloss** [comment]
Also why does the error say something about bounding box restrictions?

**Comment by AlexModGuy** [comment]
This is sponge removing entities for being too large. Edit your sponge configs.
