### ISSUE TITLE
When a dragon is equipped with armor, it lags even more.

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1118]
Even if the dragon is sitting, when stand next to it your performance is decreased, if the dragon was flying around, but as a distance, the game wouldn't become that laggy.

**Comment by mser7** [comment]
Correction: It turn out the problem was because the dragon was wearing armor, I had mine in full diamond armor, and when standing next to it, framerate drop sharply. You might want to check if other mobs with armor will cause the same issue.

**Comment by AlexModGuy** [comment]
fixed
