### ISSUE TITLE
Dragons don't respect block hardness

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#1119]
https://github.com/Alex-the-666/Ice_and_Fire/blob/1.12.2/src/main/java/com/github/alexthe666/iceandfire/entity/EntityDragonBase.java#L1296
`public Block setBlockUnbreakable() {
        this.setHardness(-1.0F);
        return this;
    }`
The test about block hardness is not correct as it doesn't check that an unbreakable block return -1f

**Comment by khift363** [comment]
I suspect this is why Dragons are able to destroy gravestones. This is a pretty significant bug, if true.

**Comment by AlexModGuy** [comment]
fixed
