### ISSUE TITLE
Please Register Loot Tables to allow LootTweaker Integration (suggestion)

### ISSUE THREAD

**Issue by khift363** [Alex-the-666/Ice_and_Fire#1123]
In developing my modpack I discovered that Ice & Fire was not registering any loot tables for the mobs it adds. This is an issue because without appropriately registered loot tables the modpack development tool LootTweaker cannot edit the drops for a mob. I would love to use LootTweaker to add drops to the various Ice & Fire mobs so as to integrate them better with my modpack, but unfortunately with unregistered loot tables I cannot do that.

To confirm that this wasn't a mod interaction with another mod in my pack, I made a new instance with the following details:

Minecraft v1.12.2
Forge v14.23.5.2778 (more recent versions currently have conflicts with LLibrary)
CraftTweaker v4.1.13
Ice and Fire v1.5.2
LLibrary v1.7.15
LootTweaker v0.0.8

In this instance, I created a new world and used the command "/ct loottables all" to dump all registered loot tables. I then checked in the "[Instance]\dumps\loot_tables" directory and confirmed that no mob loot tables were dumped that originated from Ice and Fire.

In the mean time, if you cannot push an update that registers this mod's loot tables for whatever reason, if you could post the locations of the loot tables within the mod I could potentially use that to hack together a way to edit the loot tables. Currently LootTweaker cannot do this, but in their upcoming 0.0.9 release they're adding a way to edit an unregistered loot table, but only if you already know its directory path. Without knowing where to write to that feature is insufficient - I need your help to find the directory path.

As an additional note, I also understand that this would help enable integration with Just Enough Resources, a JEI addon that displays monster and chest loot. Like LootTweaker, JER finds the data it displays by using the list of registered loot tables, so if your loot tables are unregistered it cannot detect them. I'm not certain if it's automatic past that point or not, there may be another step, but I know getting the loot table registered is one of the steps.

Thank you for your time and understanding.

**Comment by AlexModGuy** [comment]
All loot tables have been registered for all mobs, even dragons. This will be in 1.6.0!
