### ISSUE TITLE
Add Roaming Capability to Pixies

### ISSUE THREAD

**Issue by ilightwas** [Alex-the-666/Ice_and_Fire#1126]
So I was digging more into the mod and had an Idea for a magical area. Would like to get a lot of pixies around the area but the problem is they will keep stealing itens if they are not tamed. And if they are tamed they can only follow or sit down. So an extra option when right clicking them to roam around would be nice. Hopefully they would behave more naturally around, could even put down some of the hovels around (or some new interactions with the world) and see they playing.

**Comment by AlexModGuy** [comment]
move this to suggestions
