### ISSUE TITLE
Alter tame dragon hostility checks to accommodate other players

### ISSUE THREAD

**Issue by jordanpg** [Alex-the-666/Ice_and_Fire#1131]
Currently, it seems tamed dragons are restricted from attacking tamed mobs, but only if they are owned by the same player. I suggest this behavior should be altered; we just had an experience where one player's tamed fire dragon killed another player's tamed ice dragon near-immediately after it hatched, causing a lot of frustration and confusion. The [relevant code](https://github.com/Alex-the-666/Ice_and_Fire/blob/eacdf75d3205fdc699cc444edce82a69ccd6e2ee/src/main/java/com/github/alexthe666/iceandfire/entity/DragonUtils.java#L200) appears to suggest that any other player's tamed mobs would be fair game for a dragon to attack, which seems non-ideal for a multiplayer server.

Perhaps some aspects of this this are intended functionality, though if so, I think some relevant config options would be a good addition.

**Comment by AlexModGuy** [comment]
Made it so tamed dragons will not attack any other mob that is tamed.
