### ISSUE TITLE
6 months?

### ISSUE THREAD

**Issue by kreezxil** [Alex-the-666/Ice_and_Fire#1132]
Hey there @Alex-the-666 you're favorite mod pack designer here from World of Dragons. Last update from you was July 19, 2018. We're going on a full 6 months. There've been at least two college breaks in that time. Any chance there is an update coming out?

Btw, if I build a mainentance release based on the current branch will you merge the changes and publish it? Or do you care if I create a new mod on CurseForge. I would call it the Mainentance Release version. IE, I would update it with your changes throughout the year plus bug fixes for the new forge builds.

According to that CC-BY-4.0 license you assigned it on CurseForge I'm thinking you don't care one way or the other.

![image](https://user-images.githubusercontent.com/3880072/50001441-7d5e2580-ff62-11e8-969a-0c891a6b9586.png)

**Comment by AlexModGuy** [comment]
https://github.com/Alex-the-666/Ice_and_Fire/commit/eacdf75d3205fdc699cc444edce82a69ccd6e2ee
Last commit was 9 days ago. Development may be slow, but it is happening.

**Comment by AlexModGuy** [comment]
If you fork a build and would like to push it to fix bugs, I'd love to merge it. But i definitely do NOT want two versions of my mod floating around on the web ;) The liscense is now LGPLv3. I promise there will be much more progress over the next two weeks after friday, when I have my surgery.

**Comment by kreezxil** [comment]
Is there anything I can do to encourage you to at least push a binary
version to CurseForge at least once a month?

**Comment by kreezxil** [comment]
What kind of surgery? School was the reason before. 

Since I am asking you to share, I'll share too. 

Back in March 24 2018 I went to the ER because I was white as a sheet. I was down to 20% oxygen, after I was transferred to a larger hospital it was discovered that I was suffering from a 45% bilateral pulmonary embolism in both lungs (double lung clots). The doctors fixed me. Then this past thanksgiving I fell and possibly triggered a small baby stroke [TIA] that officially occurred on December 5th 2018, a scan two weeks ago. Tests were performed and while not disclosed then it was disclosed to me yesterday that they discovered .6 cm (60 mm) lesion on one of my nerve clusters (not sure the exact wording used here) in my brain.

**Comment by AlexModGuy** [comment]
Oh gosh that sounds absolutely awful! I hope your condition improves, best of luck. No, its for something minor, but I should be bedridden for a week or two.
For your other question, I would gladly do that if I could, but I'm still working on myrmex, although they're 90% done right now, just ironing out their ""taming"" and bugs. I'm currently considering releasing the update with just them and a bugfix, with the ampitheatre and the sea serpent left to a later date.
