### ISSUE TITLE
Snow Village Gen Crash

### ISSUE THREAD

**Issue by vallan0** [Alex-the-666/Ice_and_Fire#1135]
[crash-2017-06-01_12.54.06-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/2683714/crash-2017-06-01_12.54.06-server.txt)
what i've tried:
mixing up potentially all combinations of llib & ice and fire 1.12
removed all other mods except ice and fire & llib then repeat step 1
what worked:
a previous version of I&F but mod had bugs and no hippogriffs
(got more crash log of the whole modpack if nessesary)
edit: 
is using: 1.5.2
was using 1.2.0

**Comment by AlexModGuy** [comment]
fixed
