### ISSUE TITLE
Dupe bug with TAN [1.12.2]

### ISSUE THREAD

**Issue by Sheziss** [Alex-the-666/Ice_and_Fire#1137]
I'm using the last release of Ice and Fire (1.5.2) and I've noticed that breaking a dragon egg or a dragon skull drops two of the same item. I'm currently using the last release of Tough As Nails (1.12.2 139) but I've tested older releases too and all of them have the same bug. I have not tested older versions of I&F though.
The issue has been reported on Tough As Nails github many months ago but no answer has been given. 
My forge build is 1.12.2-14.23.5.2768 (it should be the last recommended one). I will update the topic when I will test older forge builds. I will probably do it because I remember playing with another build some months ago and everything was fine.
Hope this is useful for you. Keep up the good work <3

**Comment by Sheziss** [comment]
Nevermind, it still dupes dragon eggs in the old forge 2705, which I used after 2768.

**Comment by AlexModGuy** [comment]
fixed
