### ISSUE TITLE
Incorrect drops from Gold Piles

### ISSUE THREAD

**Issue by Ironence** [Alex-the-666/Ice_and_Fire#1141]
Currently, Gold piles will drop 2 gold nuggets, with 1 additional nugget for every layer. The problem with this is that each layer needs 2 nuggets to make. As an example, you could use 4 nuggets to make a 2 layer pile, but If you break it you only get 3 nuggets back

**Comment by AlexModGuy** [comment]
this is called diminishing returns and is intended
