### ISSUE TITLE
Tamed Dragon Unstoppable AI Rampage

### ISSUE THREAD

**Issue by khift363** [Alex-the-666/Ice_and_Fire#1142]
Finally found and hatched a dragon egg in my modpack server, and for the most part the dragon was working fine for a couple hours. I could fly around on it, mount, dismount, it'd respond to the Dragon Command Staff and sit, etc etc. However, seemingly at random, the dragon gets stuck in some sort of loop where it just continues to perform its aggressive / hunt / wander AI pretty much no matter what I do. I get off the dragon, and even if the dragon was "sitting" beforehand it is no longer sitting and runs off to murder nearby mobs, destroying everything in its path. If I catch up to it and use the Dragon Command Staff on it to mark it as sitting again, it visually sits down but continues to run around destroying everything and killing mobs. If I mount the dragon, it continues to run around of its own accord, adding its desired movements to the movements I command via WASD. If I then dismount the dragon, I will be teleported back to where I mounted it, but the dragon remains at the dismount point. If I put the dragon in the Dragon Horn or an EnderIO Soul Vial and take it back out, nothing changes - it always comes out in wander mode, even if put in while sitting, and it continues to disregard the sitting status. The only way I have found to pull the dragon out of this loop is to restart the entire server, which is obviously not a tenable solution for a bug that has occurred three times in four hours.

The server environment is a modpack running the following:
Minecraft v1.12.2
Forge v14.23.5.2778
Ice and Fire v1.5.2
LLibrary v1.7.15
Many other mods, but none that should interact with mob AI

A video of the problem:
https://youtu.be/DdXOD99jduU

**Comment by khift363** [comment]
This is now happening with Hippogryphs too.

**Comment by GundunUkan** [comment]
The problem it is showing aggressive behavior is most likely because it is hungry.

**Comment by khift363** [comment]
Given that the problem occurs when hunger is in the vicinity of 99 hunger, that isn't possible. Or if it is, it's a bug related to hunger.

**Comment by AlexModGuy** [comment]
it seems like you are rapidly double clicking with your mouse when you interract with the dragon. both the mesagethat displays when you sneak click and the one when you normal click appear at the same time. Perhaps this could be causing the issue

**Comment by khift363** [comment]
I suspect that is related to another bug, where getting off of an Ice and Fire mount via shift will cause the game to think shift is held down until you touch it again. Very minor, but frustrating until we figured out what was causing it.

In the video, I was only only single clicking. I can say that for sure.

We've been seeing more and more hippogryphs exhibit this behavior, too, so it's not dragon exclusive, and that probably rules out hunger as hippogryphs don't have hunger. They do the same things - they wander around even while visibly sitting, and will try and move of their own accord while you're riding them, often kicking you off and teleporting you back to where you got on.

**Comment by AlexModGuy** [comment]
fixed dragon sit-walking
