### ISSUE TITLE
Japanese lang File

### ISSUE THREAD

**Issue by BlueWither** [Alex-the-666/Ice_and_Fire#1145]
I did not know how to use Pull-Request, so write it here.

> itemGroup.iceandfire=Ice And Fire
> iceandfire.empty =空
> 
> tile.iceandfire.lectern.name=書見台
> tile.iceandfire.podium.name=基壇
> tile.iceandfire.podium_oak.name=樫の基壇
> tile.iceandfire.podium_spruce.name=松の基壇
> tile.iceandfire.podium_birch.name=白樺の基壇
> tile.iceandfire.podium_jungle.name=ジャングルの基壇
> tile.iceandfire.podium_acacia.name=アカシアの基壇
> tile.iceandfire.podium_dark_oak.name=ダークオークの基壇
> tile.iceandfire.fire_lily.name=火ユリ
> tile.iceandfire.frost_lily.name=氷ユリ
> tile.iceandfire.goldpile.name=堆積した金
> tile.iceandfire.silverpile.name=堆積した銀
> tile.iceandfire.silverOre.name=銀鉱石
> tile.iceandfire.sapphireOre.name=サファイア鉱石
> tile.iceandfire.silverBlock.name=銀ブロック
> tile.iceandfire.sapphireBlock.name=サファイアブロック
> tile.iceandfire.charedDirt.name=焼け焦げた土
> tile.iceandfire.charedGrass.name=焼け焦げた草ブロック
> tile.iceandfire.charedStone.name=焼け焦げた石
> tile.iceandfire.charedCobblestone.name=焼け焦げた丸石
> tile.iceandfire.charedGravel.name=焼け焦げた砂利
> tile.iceandfire.charedGrassPath.name=焼け焦げた草の道
> tile.iceandfire.ash.name=灰
> tile.iceandfire.frozenDirt.name=凍てついた土
> tile.iceandfire.frozenGrass.name=凍てついた草ブロック
> tile.iceandfire.frozenStone.name=凍てついた石
> tile.iceandfire.frozenCobblestone.name=凍てついた丸石
> tile.iceandfire.frozenGravel.name=凍てついた砂利
> tile.iceandfire.frozenGrassPath.name=凍てついた草の道
> tile.iceandfire.frozenSplinters.name=凍てついた木片
> tile.iceandfire.dragon_ice.name=ドラゴンアイス
> tile.iceandfire.dragon_ice_spikes.name=ドラゴンアイスの棘
> tile.iceandfire.egginice.name=凍ったドラゴンの卵
> tile.iceandfire.pixie_house_0.name=茶色キノコの妖精の小屋
> tile.iceandfire.pixie_house_1.name=赤キノコの妖精の小屋
> tile.iceandfire.pixie_house_2.name=白樺の妖精の小屋
> tile.iceandfire.pixie_house_3.name=樫の妖精の小屋
> tile.iceandfire.pixie_house_4.name=ダークオークの妖精の小屋
> tile.iceandfire.pixie_house_5.name=松の妖精の小屋
> tile.iceandfire.jar_empty.name=瓶
> tile.iceandfire.jar_pixie.name=妖精入り瓶
> tile.iceandfire.jar_0.name=ピンクの妖精入り瓶
> tile.iceandfire.jar_1.name=紫の妖精入り瓶
> tile.iceandfire.jar_2.name=青の妖精入り瓶
> tile.iceandfire.jar_3.name=緑の妖精入り瓶
> tile.iceandfire.jar_4.name=黄色の妖精入り瓶
> tile.iceandfire.nest.name=ドラゴンの巣材
> tile.iceandfire.desert_myrmex_resin.name=砂漠ミュルメクス樹脂
> tile.iceandfire.desert_myrmex_resin_sticky.name=べとつく砂漠ミュルメクス樹脂
> tile.iceandfire.jungle_myrmex_resin.name=ジャングルミュルメクス樹脂
> tile.iceandfire.jungle_myrmex_resin_sticky.name=べとつくジャングルミュルメクス樹脂
> tile.iceandfire.desert_myrmex_cocoon.name=砂漠ミュルメクスの繭
> tile.iceandfire.jungle_myrmex_cocoon.name=ジャングルミュルメクスの繭 
> tile.iceandfire.myrmex_desert_biolight.name=砂漠ミュルメクスの蛍光体
> tile.iceandfire.myrmex_jungle_biolight.name=ジャングルミュルメクスの蛍光体
> tile.iceandfire.myrmex_desert_resin_block.name=硬化した砂漠ミュルメクス樹脂 
> tile.iceandfire.myrmex_jungle_resin_block.name=硬化したジャングルミュルメクス樹脂 
> tile.iceandfire.myrmex_desert_resin_glass.name=砂漠ミュルメクスの樹脂ガラス 
> tile.iceandfire.myrmex_jungle_resin_glass.name=ジャングルミュルメクスの樹脂ガラス 
> 
> 
> item.iceandfire.bestiary.name=ベスティアリ
> item.iceandfire.manuscript.name=手書きの紙片
> item.iceandfire.sapphireGem.name=サファイア
> item.iceandfire.silverIngot.name=銀インゴット
> item.iceandfire.silverNugget.name=銀塊
> item.iceandfire.silver_helmet.name=銀のヘルメット
> item.iceandfire.silver_chestplate.name=銀のチェストプレート
> item.iceandfire.silver_leggings.name=銀のレギンス
> item.iceandfire.silver_boots.name=銀のブーツ
> item.iceandfire.silver_pickaxe.name=銀のツルハシ
> item.iceandfire.silver_sword.name=銀の剣
> item.iceandfire.silver_axe.name=銀の斧
> item.iceandfire.silver_shovel.name=銀のシャベル
> item.iceandfire.silver_hoe.name=銀のクワ
> item.iceandfire.fire_stew.name=炎ユリの調合薬
> item.iceandfire.frost_stew.name=氷ユリの調合薬
> item.iceandfire.dragonegg.name=ドラゴンの卵
> item.iceandfire.dragonscales.name=ドラゴンの鱗
> item.iceandfire.dragonHelmet.name=ドラゴンのヘルメット
> item.iceandfire.dragonChestplate.name=ドラゴンのチェストプレート
> item.iceandfire.dragonLeggings.name=ドラゴンのレギンス
> item.iceandfire.dragonBoots.name=ドラゴンのブーツ
> item.iceandfire.dragonbone.name=ドラゴンの骨
> item.iceandfire.witherbone.name=ウィザーの骨
> item.iceandfire.fishing_spear.name=銛
> item.iceandfire.wither_shard.name=ウィザーの骨の欠片
> item.iceandfire.dragonbone_sword.name=ドラゴンの骨の剣
> item.iceandfire.dragonbone_shovel.name=ドラゴンの骨のシャベル
> item.iceandfire.dragonbone_pickaxe.name=ドラゴンの骨のツルハシ
> item.iceandfire.dragonbone_axe.name=ドラゴンの骨の斧
> item.iceandfire.dragonbone_hoe.name=ドラゴンの骨のクワ
> item.iceandfire.dragonbone_sword_fire.name=燃えるドラゴンの剣
> item.iceandfire.dragonbone_sword_ice.name=凍えるドラゴンの剣
> item.iceandfire.dragonbone_arrow.name=ドラゴンの骨の矢
> item.iceandfire.dragonbone_bow.name=ドラゴンの骨の弓
> item.iceandfire.dragon_skull.name=ドラゴンの頭蓋骨
> item.iceandfire.dragonarmor_iron.name=鉄のドラゴン用装備
> item.iceandfire.dragonarmor_gold.name=金のドラゴン用装備
> item.iceandfire.dragonarmor_diamond.name=ダイヤのドラゴン用装備
> item.iceandfire.dragon_meal.name=ドラゴンの餌
> item.iceandfire.fire_dragon_flesh.name=ファイアドラゴンの肉
> item.iceandfire.ice_dragon_flesh.name=アイスドラゴンの肉
> item.iceandfire.fire_dragon_heart.name=ファイアドラゴンの心臓
> item.iceandfire.ice_dragon_heart.name=アイスドラゴンの心臓
> item.iceandfire.fire_dragon_blood.name=ファイアドラゴンの血
> item.iceandfire.ice_dragon_blood.name=アイスドラゴンの血
> item.iceandfire.dragon_stick.name=ドラゴン指令の杖
> item.iceandfire.dragon_horn.name=ドラゴンの角笛
> item.iceandfire.dragon_horn_fire.name=ドラゴンの角笛
> item.iceandfire.dragon_horn_ice.name=ドラゴンの角笛
> item.iceandfire.dragon_flute.name=ドラゴンの骨のフルート
> item.iceandfire.hippogryph_egg.name=ヒッポグリフの卵
> item.iceandfire.iron_hippogryph_armor.name=鉄のヒッポグリフの鎧
> item.iceandfire.gold_hippogryph_armor.name=金のヒッポグリフの鎧
> item.iceandfire.diamond_hippogryph_armor.name=ダイヤのヒッポグリフの鎧
> item.iceandfire.gorgon_head.name=ゴルゴンの首
> item.iceandfire.stone_statue.name=石像
> item.iceandfire.blindfold.name=目隠し
> item.iceandfire.pixie_dust.name=妖精の粉
> item.iceandfire.ambrosia.name=アンブロシア
> item.iceandfire.sheep_helmet.name=羊変装の帽子
> item.iceandfire.sheep_chestplate.name=羊変装の服
> item.iceandfire.sheep_leggings.name=羊変装のズボン
> item.iceandfire.sheep_boots.name=羊変装の靴
> item.iceandfire.shiny_scales.name=輝く鱗
> item.iceandfire.earplugs.name=耳栓
> item.iceandfire.deathworm_chitin_yellow.name=黄色のデスワームの殻
> item.iceandfire.deathworm_chitin_white.name=白のデスワームの殻
> item.iceandfire.deathworm_chitin_red.name=赤のデスワームの殻
> item.iceandfire.deathworm_yellow_helmet.name=黄色のデスワームのヘルメット
> item.iceandfire.deathworm_yellow_chestplate.name=黄色のデスワームのチェストプレート
> item.iceandfire.deathworm_yellow_leggings.name=黄色のデスワームのレギンス
> item.iceandfire.deathworm_yellow_boots.name=黄色のデスワームのブーツ
> item.iceandfire.deathworm_white_helmet.name=白のデスワームのヘルメット
> item.iceandfire.deathworm_white_chestplate.name=白のデスワームのチェストプレート
> item.iceandfire.deathworm_white_leggings.name=白のデスワームのレギンス
> item.iceandfire.deathworm_white_boots.name=白のデスワームのブーツ
> item.iceandfire.deathworm_red_helmet.name=赤のデスワームのヘルメット
> item.iceandfire.deathworm_red_chestplate.name=赤のデスワームのチェストプレート
> item.iceandfire.deathworm_red_leggings.name=赤のデスワームのレギンス
> item.iceandfire.deathworm_red_boots.name=赤のデスワームのブーツ
> item.iceandfire.deathworm_egg.name=デスワームの卵
> item.iceandfire.deathworm_egg_giant.name=巨大デスワームの卵
> item.iceandfire.rotten_egg.name=腐った卵
> item.iceandfire.stymphalian_bird_feather.name=ステュムパリデスの鳥の羽
> item.iceandfire.stymphalian_arrow.name=ステュムパリデスの矢
> item.iceandfire.stymphalian_arrow.desc=その矢羽は鳥のように矢を飛ばす。
> item.iceandfire.troll_weapon.axe.name=トロールの斧
> item.iceandfire.troll_weapon.column.name=トロールの石柱
> item.iceandfire.troll_weapon.column_forest.name=トロールの苔むした石柱
> item.iceandfire.troll_weapon.column_frost.name=トロールの凍った石柱
> item.iceandfire.troll_weapon.hammer.name=トロールのハンマー
> item.iceandfire.troll_weapon.trunk.name=トロールの丸太
> item.iceandfire.troll_weapon.trunk_frost.name=トロールの凍った丸太
> item.iceandfire.troll_tusk.name=トロールの牙
> item.iceandfire.troll_leather_forest.name=森林トロールの革
> item.iceandfire.troll_leather_frost.name=寒冷トロールの革
> item.iceandfire.troll_leather_mountain.name=山岳トロールの革
> item.iceandfire.forest_troll_leather_helmet.name=森林トロールのヘルメット
> item.iceandfire.forest_troll_leather_chestplate.name=森林トロールのチェストプレート
> item.iceandfire.forest_troll_leather_leggings.name=森林トロールのレギンス
> item.iceandfire.forest_troll_leather_boots.name=森林トロールのブーツ
> item.iceandfire.frost_troll_leather_helmet.name=寒冷トロールのヘルメット
> item.iceandfire.frost_troll_leather_chestplate.name=寒冷トロールのチェストプレート
> item.iceandfire.frost_troll_leather_leggings.name=寒冷トロールのレギンス
> item.iceandfire.frost_troll_leather_boots.name=寒冷トロールのブーツ
> item.iceandfire.mountain_troll_leather_helmet.name=山岳トロールのヘルメット
> item.iceandfire.mountain_troll_leather_chestplate.name=山岳トロールのチェストプレート
> item.iceandfire.mountain_troll_leather_leggings.name=山岳トロールのレギンス
> item.iceandfire.mountain_troll_leather_boots.name=山岳トロールのブーツ
> item.iceandfire.troll_leather_armor_helmet.desc=-10%% 遠距離ダメージ
> item.iceandfire.troll_leather_armor_chestplate.desc=-30%% 遠距離ダメージ
> item.iceandfire.troll_leather_armor_leggings.desc=-20%% 遠距離ダメージ
> item.iceandfire.troll_leather_armor_boots.desc=-10%% 遠距離ダメージ
> item.iceandfire.sickly_dragon_meal.name=ドラゴンの毒餌
> item.iceandfire.sickly_dragon_meal.desc=ドラゴンの成長を止める
> item.iceandfire.myrmex_desert_egg.name=砂漠ミュルメクスの卵
> item.iceandfire.myrmex_jungle_egg.name=ジャングルミュルメクスの卵 
> item.iceandfire.myrmex_desert_resin.name=砂漠ミュルメクスの樹脂の塊 
> item.iceandfire.myrmex_jungle_resin.name=ジャングルミュルメクスの樹脂の塊 
> item.iceandfire.myrmex_desert_chitin.name=砂漠ミュルメクスの外骨格 
> item.iceandfire.myrmex_jungle_chitin.name=ジャングルミュルメクスの外骨格 
> item.iceandfire.myrmex_stinger.name=ミュルメクスの毒針 
> item.iceandfire.myrmex_desert_staff.name=砂漠ミュルメクスの杖
> item.iceandfire.myrmex_jungle_staff.name=ジャングルミュルメクスの杖 
> item.iceandfire.myrmex_desert_sword.name=砂漠ミュルメクスの剣
> item.iceandfire.myrmex_jungle_sword.name=ジャングルミュルメクスの剣
> item.iceandfire.myrmex_desert_pickaxe.name=砂漠ミュルメクスのツルハシ
> item.iceandfire.myrmex_jungle_pickaxe.name=ジャングルミュルメクスのツルハシ
> item.iceandfire.myrmex_desert_axe.name=砂漠ミュルメクスの斧
> item.iceandfire.myrmex_jungle_axe.name=ジャングルミュルメクスの斧
> item.iceandfire.myrmex_desert_shovel.name=砂漠ミュルメクスのショベル
> item.iceandfire.myrmex_jungle_shovel.name=ジャングルミュルメクスのショベル 
> item.iceandfire.myrmex_desert_hoe.name=砂漠ミュルメクスのクワ
> item.iceandfire.myrmex_jungle_hoe.name=ジャングルミュルメクスのクワ 
> item.iceandfire.myrmex_desert_sword_venom.name=砂漠ミュルメクスの毒針の剣
> item.iceandfire.myrmex_jungle_sword_venom.name=ジャングルミュルメクスの毒針の剣
> item.iceandfire.myrmex_desert_helmet.name=砂漠ミュルメクスのヘルメット
> item.iceandfire.myrmex_desert_chestplate.name=砂漠ミュルメクスのチェストプレート 
> item.iceandfire.myrmex_desert_leggings.name=砂漠ミュルメクスのレギンス
> item.iceandfire.myrmex_desert_boots.name=砂漠ミュルメクスのブーツ
> item.iceandfire.myrmex_jungle_helmet.name=ジャングルミュルメクスのヘルメット 
> item.iceandfire.myrmex_jungle_chestplate.name=ジャングルミュルメクスのチェストプレート
> item.iceandfire.myrmex_jungle_leggings.name=ジャングルミュルメクスのレギンス
> item.iceandfire.myrmex_jungle_boots.name=ジャングルミュルメクスのブーツ
> 
> 
> item.banner.firedragon.white=白のファイアドラゴン柄
> item.banner.firedragon.orange=橙のファイアドラゴン柄
> item.banner.firedragon.magenta=赤紫のファイアドラゴン柄
> item.banner.firedragon.lightBlue=空色のファイアドラゴン柄
> item.banner.firedragon.yellow=黄色のファイアドラゴン柄
> item.banner.firedragon.lime=黄緑のファイアドラゴン柄
> item.banner.firedragon.pink=桃色のファイアドラゴン柄
> item.banner.firedragon.gray=灰色のファイアドラゴン柄
> item.banner.firedragon.silver=薄灰のファイアドラゴン柄
> item.banner.firedragon.cyan=水色のファイアドラゴン柄
> item.banner.firedragon.purple=紫のファイアドラゴン柄
> item.banner.firedragon.blue=青のファイアドラゴン柄
> item.banner.firedragon.brown=茶色のファイアドラゴン柄
> item.banner.firedragon.green=緑のファイアドラゴン柄
> item.banner.firedragon.red=赤のファイアドラゴン柄
> item.banner.firedragon.black=黒のファイアドラゴン柄
> 
> item.banner.icedragon.white=白のアイスドラゴン柄
> item.banner.icedragon.orange=橙のアイスドラゴン柄
> item.banner.icedragon.magenta=赤紫のアイスドラゴン柄
> item.banner.icedragon.light_blue=空色のアイスドラゴン柄
> item.banner.icedragon.yellow=黄色のアイスドラゴン柄
> item.banner.icedragon.lime=黄緑のアイスドラゴン柄
> item.banner.icedragon.pink=桃色のアイスドラゴン柄
> item.banner.icedragon.gray=灰色のアイスドラゴン柄
> item.banner.icedragon.silver=薄灰のアイスドラゴン柄
> item.banner.icedragon.cyan=水色のアイスドラゴン柄
> item.banner.icedragon.purple=紫のアイスドラゴン柄
> item.banner.icedragon.blue=青のアイスドラゴン柄
> item.banner.icedragon.brown=茶色のアイスドラゴン柄
> item.banner.icedragon.green=緑のアイスドラゴン柄
> item.banner.icedragon.red=赤のアイスドラゴン柄
> item.banner.icedragon.black=黒のアイスドラゴン柄
> 
> entity.firedragon.name=ファイアドラゴン
> entity.icedragon.name=アイスドラゴン
> entity.dragonegg.name=ドラゴンの卵
> entity.dragonarrow.name=ドラゴンの骨の矢
> entity.dragonskull.name=ドラゴンの頭蓋骨
> entity.dragonfire.name=ドラゴンの炎
> entity.dragonfirecharge.name=ドラゴンのファイアチャージ
> entity.dragonice.name=ドラゴンの氷
> entity.dragonicecharge.name=ドラゴンのアイスチャージ
> entity.snowvillager.name=雪国の村人
> entity.Villager.craftsman=職人
> entity.Villager.fisherman=釣り人
> entity.Villager.shaman=呪術師
> entity.hippogryph.name=ヒッポグリフ
> entity.hippogryph.black=青毛ヒッポグリフ
> entity.hippogryph.brown=栃栗毛ヒッポグリフ
> entity.hippogryph.chestnut=鹿毛ヒッポグリフ
> entity.hippogryph.creamy=栗毛ヒッポグリフ
> entity.hippogryph.dark_brown=黒鹿毛ヒッポグリフ
> entity.hippogryph.gray=芦毛ヒッポグリフ
> entity.hippogryph.white=白毛ヒッポグリフ
> entity.hippogryph.raptor=ヘビクイヒッポグリフ
> entity.hippogryph.alex=ファイアヒッポグリフ
> entity.hippogryph.dodo=ドードーヒッポグリフ
> entity.player.name=プレイヤー
> entity.stonestatue.name=石像
> entity.gorgon.name=ゴルゴン
> entity.if_pixie.name=妖精
> entity.if_pixie.type_0=ピンクの妖精
> entity.if_pixie.type_1=紫の妖精
> entity.if_pixie.type_2=青の妖精
> entity.if_pixie.type_3=緑の妖精
> entity.if_pixie.type_4=黄色の妖精
> entity.cyclops.name=サイクロプス
> entity.siren.name=セイレーン
> entity.hippocampus.name=ヒッポカムポス
> entity.deathworm.name=デスワーム
> entity.deathwormegg.name=デスワームの卵
> entity.if_cockatrice.name=コカトリス
> entity.if_cockatriceegg.name=腐った卵
> entity.stymphalianbird.name=ステュムパリデスの鳥
> entity.stymphalianfeather.name=ステュムパリデスの鳥の羽
> entity.stymphalianarrow.name=ステュムパリデスの矢
> entity.if_troll.name=トロール
> entity.myrmex_worker.name=ミュルメクスワーカー
> entity.myrmex_soldier.name=ミュルメクスソルジャー 
> entity.myrmex_queen.name=ミュルメクスクイーン
> entity.myrmex_sentinel.name=ミュルメクスセンチネル 
> entity.myrmex_royal.name=ミュルメクスロイヤル
> entity.myrmex_egg.name=ミュルメクスの卵
> 
> 
> dragon.red=赤
> dragon.green=エメラルド
> dragon.bronze=ブロンズ
> dragon.gray=灰
> dragon.blue=青
> dragon.sapphire=サファイア
> dragon.silver=銀
> dragon.white=白
> dragon.stage=ステージ 
> dragon.fire=ファイア
> dragon.ice=アイス
> dragon.name=名前: 
> dragon.unnamed=名無し
> dragon.health=体力: 
> dragon.stage=ステージ 
> dragon.gender=性別: 
> dragon.gender.male=オス
> dragon.gender.female=メス
> dragon.hunger=空腹度: 
> dragon.owner=主: 
> dragon.untamed=懐いていない
> dragon.armor_head=頭
> dragon.armor_neck=首
> dragon.armor_body=胴
> dragon.armor_tail=尾
> dragon.hatchtime=孵化時:
> dragon.days.front=(
> dragon.days.back=日)
> dragon.command.sit=ドラゴンは待機した
> dragon.command.stand=ドラゴンは自由行動になった
> dragon.command.new_home=ドラゴンのホームポジションが設定されました %d, %d, %d.
> hippogryph.command.new_home=ヒッポグリフのホームポジションが設定されました %d, %d, %d.
> myrmex.message.raised_reputation=ミュルメクスのコロニーでの好感度が上がった %d, → %d. 
> myrmex.message.lowered_reputation=§cミュルメクスのコロニーでの好感度が下がった %d, → %d. 
> myrmex.message.peaceful=このミュルメクスのコロニーは中立的だ
> myrmex.message.hostile=§cこのミュルメクスのコロニーは敵対的だ
> myrmex.message.trade=このミュルメクスのコロニーは取引に応じている
> myrmex.message.no_trade=§cこのミュルメクスのコロニーは取引に応じていない
> myrmex.message.can_use_staff=このコロニーではミュルメクスの杖を使う事ができます
> myrmex.message.cant_use_staff=§cこのコロニーではミュルメクスの杖を使う事ができません
> myrmex.message.null_hive=このミュルメクスは巣を持っていません！
> myrmex.message.staff_set_named=杖は%dのコロニーに適応され  %d, %d, %dが中心になった 
> myrmex.message.staff_set_unnamed=杖はミュルメクスのコロニーに適応され、%d, %d, %dが中心になった
> myrmex.message.staff_already_set=§cこの杖はもうこのコロニーに適応されています！
> myrmex.message.staff_not_set=§cこの杖はどのミュルメクスのコロニーにも適応されていません
> myrmex.message.staff_desc=コロニーに結び付けられています
> myrmex.message.staff_no_desc=どのコロニーにも結び付けられていません 
> myrmex.message.colony_named=%dのコロニー 
> myrmex.message.colony=ミュルメクスのコロニー
> myrmex.message.hive_opinion=コロニーの評価: %d 
> myrmex.message.rooms=部屋: 
> myrmex.message.room.food=貯蔵室 (%d, %d, %d) 
> myrmex.message.room.nursery=育児室 (%d, %d, %d) 
> myrmex.message.room.misc=普通の部屋 (%d, %d, %d) 
> myrmex.message.room.enterance_surface=入り口表面 (%d, %d, %d) 
> myrmex.message.room.enterance_bottom=入り口下側 (%d, %d, %d) 
> myrmex.message.delete=削除 
> myrmex.message.enablebreeding=繁殖許可
> myrmex.message.disablebreeding=繁殖不許可 
> myrmex.message.establishroom_food=貯蔵室を作る
> myrmex.message.establishroom_nursery=育児室を作る
> myrmex.message.establishroom_misc=普通の部屋を作る
> myrmex.message.establishroom_enterance_surface=入り口（表面）を作る
> myrmex.message.establishroom_enterance_bottom=入り口（下側）を作る 
> myrmex.message.create_new_room=部屋を作っています (%d, %d, %d) 
> myrmex.message.dupe_room=§cそこにはもう部屋があります！§r(%d, %d, %d)
> myrmex.message.added_food_room=貯蔵室を追加しました(%d, %d, %d) 
> myrmex.message.added_nursery_room=育児室を追加しました(%d, %d, %d) 
> myrmex.message.added_misc_room=普通の部屋を作りました(%d, %d, %d) 
> myrmex.message.added_enterance_bottom=入り口（下側）を作りました(%d, %d, %d) 
> myrmex.message.added_enterance_surface=入り口（表面）を作りました(%d, %d, %d) 
> cockatrice.command.0=コカトリスは偵察状態になった
> cockatrice.command.1=コカトリスは待機した
> cockatrice.command.2=コカトリスは追従状態になった
> myrmex.caste_worker.name=ワーカー
> myrmex.caste_soldier.name=兵隊
> myrmex.caste_queen.name=女王
> myrmex.caste_royal.name=王
> myrmex.caste_sentinel.name=哨兵
> 
> 
> bestiary.contains=コンテンツ:
> bestiary.introduction=基本情報
> bestiary.firedragon=ファイアドラゴン
> bestiary.firedragonegg=ファイアドラゴンの卵
> bestiary.icedragon=アイスドラゴン
> bestiary.icedragonegg=アイスドラゴンの卵
> bestiary.materials=ドラゴンの報酬
> bestiary.alchemy=ドラゴンの血
> bestiary.villagers=雪国の村人
> bestiary.tameddragons=懐いたドラゴン
> bestiary.hippogryph=ヒッポグリフ
> bestiary.gorgon=ゴルゴン
> bestiary.pixie=妖精
> bestiary.cyclops=サイクロプス
> bestiary.siren=セイレーン
> bestiary.hippocampus=ヒッポカムポス
> bestiary.deathworm=デスワーム
> bestiary.cockatrice=コカトリス
> bestiary.stymphalianbird=ステュムパリデスの鳥
> bestiary.troll=トロール
> bestiary.myrmex=ミュルメクス
> 
> lectern.nopages=追加できる情報は見当たらない。
> silvertools.hurt=アンデッドに+2ダメージ
> dragon_sword_fire.hurt1=アイスドラゴンに+8ダメージ
> dragon_sword_fire.hurt2=炎で飲みこみ、突き飛ばす
> dragon_sword_ice.hurt1=ファイアドラゴンに+8ダメージ
> dragon_sword_ice.hurt2=氷に閉ざし、突き飛ばす
> myrmextools.hurt=虫でないものとデスワームに+4ダメージ
> myrmextools.poison=毒（0:10）
> 
> 
> message.iceandfire.dragonWander=ドラゴンは散策中だ。
> message.iceandfire.dragonFollow=ドラゴンは追従している。
> message.iceandfire.dragonSit=ドラゴンは待機している。
> message.iceandfire.dragonSleep=ドラゴンは眠っている。
> message.iceandfire.knownAs=このドラゴンの名は 
> message.iceandfire.dragonWanderName=は散策中だ。
> message.iceandfire.dragonFollowName=は追従している。
> message.iceandfire.dragonSitName=は待機している。
> message.iceandfire.dragonSleepName=は眠っている。
> message.iceandfire.dragonGrown=このドラゴンはステージ
> message.iceandfire.dragonGrownEnd=に成長した！
> message.iceandfire.dragonGrownName=はステージ
> 
> death.attack.dragon.player_0=はドラゴンに真っ二つにされた
> death.attack.dragon.player_1=はドラゴンにずたずたに引き裂かれた
> death.attack.dragon.player_2=はドラゴンに貪り食われた
> death.attack.dragon_fire.player_0=はドラゴンにKFCにされた
> death.attack.dragon_fire.player_1=はドラゴンに焼き尽くされた
> death.attack.dragon_fire.player_2=はドラゴンに灰燼に帰さしめられた
> death.attack.dragon_ice.player_0=はドラゴンに凍結させられた
> death.attack.dragon_ice.player_1=はドラゴンに氷にされた
> death.attack.dragon_ice.player_2=はドラゴンに二度と動けなくされた
> death.attack.gorgon.player_0=はゴルゴンに石像にされた
> death.attack.gorgon.player_1=はゴルゴンゾーラにされてしまった
> death.attack.gorgon.player_2=はゴルゴンに石化された
> key.dragon_strike=ドラゴンストライク
> key.dragon_fireAttack=ドラゴンブレス
> key.dragon_down=ドラゴンから降りる/下ろす
> key.dragon_change_view=ドラゴンに騎乗中の三人称視点を変更する
> 
> achievement.manuscript=In Tatters!
> achievement.manuscript.desc=Acquire a manuscript.
> achievement.bestiary=Fantastic Beasts!
> achievement.bestiary.desc=Craft a bestiary.
> achievement.silver=Shiny!
> achievement.silver.desc=Mine silver ore.
> achievement.silverTool=Better than gold!
> achievement.silverTool.desc=Craft a silver tool.
> achievement.sapphire=Snow Emeralds!
> achievement.sapphire.desc=Mine sapphire ore.
> achievement.dragonEncounter=Those who don't believe in magic will never find it!
> achievement.dragonEncounter.desc=Encounter a dragon of any kind.
> achievement.dragonKill=Hiccup!
> achievement.dragonKill.desc=Get killed by a dragon.
> achievement.dragonSlayer=Dragon Slayer!
> achievement.dragonSlayer.desc=Slay a dragon.
> achievement.dragonHarvest=Lord of Bones!
> achievement.dragonHarvest.desc=Harvest the remains of a dragon.
> achievement.dragonHatch=Mother of Dragons!
> achievement.dragonHatch.desc=Hatch a young dragon.
> achievement.dragonRide=Better than a horse!
> achievement.dragonRide.desc=Ride a dragon.
> achievement.dragonBreed=Donkey!
> achievement.dragonBreed.desc=Breed two dragons.
> achievement.boneTool=Needs more Wither!
> achievement.boneTool.desc=Craft a dragon bone tool.
> achievement.dragonArmor=Monster Hunter!
> achievement.dragonArmor.desc=Craft armor out of dragon scales.
> achievement.fireSword=Fight fire with fire!
> achievement.fireSword.desc=Craft a flame infused sword.
> achievement.iceSword=Icy Surprise!
> achievement.iceSword.desc=Craft an ice infused sword.
> achievement.tameHippogryph=Half Bird, Half Horse. All Awesome.
> achievement.tameHippogryph.desc=Tame a hippogryph.
> achievement.findGorgon=Look into my eyes...
> achievement.findGorgon.desc=Encounter a gorgon.
> achievement.killGorgon=Now find me a kraken...
> achievement.killGorgon.desc=Kill a gorgon.
> achievement.findPixie=How Quaint!
> achievement.findPixie.desc=Encounter a pixie.
> achievement.killPixie=I don't believe in magic!
> achievement.killPixie.desc=Kill a pixie.
> achievement.tamePixie=Magical Forest Friends!
> achievement.tamePixie.desc=Befriend a pixie.
> achievement.jarPixie=That's Unethical!
> achievement.jarPixie.desc=Put a pixie in a jar.
> 
> tc.aspect.mythus=神話、伝説、未確認、怪物
> tc.aspect.draco=ドラゴン
>

**Comment by AlexModGuy** [comment]
alrght ill add it for you.

**Comment by BlueWither** [comment]
Thank you!

**Comment by BlueWither** [comment]
New(I do not know whether this can be posted at the moment. I will delete this if there is a problem.)

item.iceandfire.amphithere_feather.name=アンピプテラの羽
item.iceandfire.amphithere_arrow.name=アンピプテラの矢
item.iceandfire.amphithere_arrow.desc=突風であらゆるものを吹き飛ばす！
item.iceandfire.sea_serpent_fang.name=シーサーペントの牙
item.iceandfire.sea_serpent_scales_blue.name=シーサーペントの鱗
item.iceandfire.sea_serpent_scales_bronze.name=シーサーペントの鱗
item.iceandfire.sea_serpent_scales_deepblue.name=シーサーペントの鱗
item.iceandfire.sea_serpent_scales_green.name=シーサーペントの鱗
item.iceandfire.sea_serpent_scales_purple.name=シーサーペントの鱗
item.iceandfire.sea_serpent_scales_red.name=シーサーペントの鱗
item.iceandfire.sea_serpent_scales_teal.name=シーサーペントの鱗
item.iceandfire.sea_serpent_helmet.name=海王のヘルメット
item.iceandfire.sea_serpent_chestplate.name=海王のチェストプレート
item.iceandfire.sea_serpent_leggings.name=海王のレギンス
item.iceandfire.sea_serpent_boots.name=海王のブーツ
item.iceandfire.sea_serpent_arrow.name=汐の矢
item.iceandfire.sea_serpent_arrow.desc=水流の影響が無効
item.iceandfire.sea_serpent_armor.desc_0=水中呼吸をもたらす
item.iceandfire.sea_serpent_armor.desc_1=攻撃力が上がる(他の部位に装備で更に上がる)

entity.amphithere.name=アンピプテラ
entity.seaserpent.name=シーサーペント

sea_serpent.blue=青
sea_serpent.bronze=ブロンズ
sea_serpent.deepblue=藍
sea_serpent.green=緑
sea_serpent.purple=紫
sea_serpent.red=赤
sea_serpent.teal=青緑

amphithere.command.new_home=アンピプテラのホームポジションが設定されました　%d, %d, %d.
amphithere.command.0=アンピプテラは自由行動になった
amphithere.command.1=アンピプテラは待機している
amphithere.command.2=アンピプテラは追従している

bestiary.amphithere=アンピプテラ
bestiary.seaserpent=シーサーペント

Although language files are not working now... #1318
