### ISSUE TITLE
Dodo hippogryph's skin in unmatch with its originated mobs

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1146]
the dodo hippogryph's skin was based on the dodo and quagga skin from Fossils and Archeology, but the mod has since changed the mob's skin, therefore the hippogryph's skin needs to be changed as well.

**Comment by AlexModGuy** [comment]
not an issue. F/A 1/12/2 is not out yet

**Comment by mser7** [comment]
true, but I will get on this again once it comes out
