### ISSUE TITLE
Pixie village in spooky dark forest

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1148]
Seem like a suitable place for defenseless little girls to live
![2018-12-24_15 10 49](https://user-images.githubusercontent.com/22555489/50397256-ae7bf880-07a1-11e9-809d-166e470a978f.png)
![2018-12-24_15 10 39](https://user-images.githubusercontent.com/22555489/50397257-af148f00-07a1-11e9-93b7-5c8ea2fc7b3b.png)

**Comment by AlexModGuy** [comment]
intended.
