### ISSUE TITLE
Suggestions: Small tweaks to Pixies and Dragons?

### ISSUE THREAD

**Issue by SirAron111** [Alex-the-666/Ice_and_Fire#1149]
Would it be possible to ad a config option that allows splitting the dragon grifing rules in 2 different parts?

I would like to be able to set for my Modpack that Tamed Dragons don’t destroy blocks but still have wild Dragons be able to get rid of weak blocks so they cannot get stuck on trees and things like that.

Also would It be possible to configure the way dragons attack in the configs to for example I think it’s too easy if people can just shift click themselves free when a dragon eats them. They should only be able to get out of the dragon’s mouth after it chomped or the player throws an enderperl to get free or some other teleporting/magic. (So an option to disable the shift freeing would be nice).

An option to slightly buff dragons against ranged attackers by giving them more armor or making them seek whoever fired arrows at them or a slight speed increase when running / flying to players would be good if that could be set in the config to (complete knockback resistance would be good to I think) so Modpack makers who want these dragons to be a fearful enemy but also have a lot of op mods installed could make good use of that in terms of config options.

As for Pixies I find it sad that they only spawn once on chunk generation. I had some players of my pack tell me that they build a base near a pixy village but at some point all the pixies despawnded and now they have a ghost town of pixie houses there. It should be possible to have new pixies spawn at day or night when there are a certain number of pixie houses near each other. So that new pixies can spawn!

Pixies also should be able to, when hit by players, inflict a levitation buff (pixie dust) onto the player as self defense letting  the aggressor float upwards for a bit, that would be fun I think.

I love the mod and thank you for reading this.

**Comment by AlexModGuy** [comment]
fixed the dragon one
