### ISSUE TITLE
Jungle Myrmex don't have their separated spawn egg like desert

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1156]
This is outragous

**Comment by PlatinumFox** [comment]
Go take the egg and spawn it in a jungle biome, it is biome dependent.

**Comment by mser7** [comment]
I just spawn some in a desert flatworld and both jungle and desert come out of the spawn egg randomly

**Comment by mser7** [comment]
Also I prefer Jungle than desert Myrmex, and there is no Jungle preset. Spawn eggs are a tool in creative anyway.

**Comment by AlexModGuy** [comment]
intended
