### ISSUE TITLE
Myrmex sentinels can't gnaw Animania mobs???

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1157]
Have it fight against an animania piglet

**Comment by mser7** [comment]
Tested on Chickens and Pigs, haven't got around to test the rest yet
![2018-12-26_08 54 22](https://user-images.githubusercontent.com/22555489/50430274-a2a14b00-08f5-11e9-960b-5d678dc71cbd.png)
![2018-12-26_08 54 26](https://user-images.githubusercontent.com/22555489/50430275-a2a14b00-08f5-11e9-93cd-f524effcfc69.png)
![2018-12-26_08 55 34](https://user-images.githubusercontent.com/22555489/50430276-a339e180-08f5-11e9-9b3e-60459711b933.png)
![2018-12-26_08 55 35](https://user-images.githubusercontent.com/22555489/50430277-a339e180-08f5-11e9-8270-dd61ab54bce2.png)
![2018-12-26_08 55 36](https://user-images.githubusercontent.com/22555489/50430279-a339e180-08f5-11e9-83ab-85cab92f4f47.png)
![2018-12-26_08 55 37](https://user-images.githubusercontent.com/22555489/50430280-a3d27800-08f5-11e9-914b-8dca08c8ca6d.png)
![2018-12-26_08 55 38](https://user-images.githubusercontent.com/22555489/50430281-a3d27800-08f5-11e9-8978-a79ac70daf68.png)
![2018-12-26_08 54 15](https://user-images.githubusercontent.com/22555489/50430282-a3d27800-08f5-11e9-9f6f-e73c6ff259fe.png)

**Comment by AlexModGuy** [comment]
this is an issue with animania mobs that they have, for some reason, hardcoded it to be IMPOSSIBLE to damage while they are riding other mobs.

**Comment by AlexModGuy** [comment]
Bug With Animania. No point leaving this open if I can't fix it.
