### ISSUE TITLE
Myrmex Path finding

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#1158]
Sentinel workers that gather items closest to the entrance hole go back down it and deposit items. (assuming this is how it is supposed to work).
but
The sentinels that go a bit farther from the hole decide to ignore going back to the entrance and try to make a direct beeline to the storage room causing them to walk in a circle over it or walk through solid walls which just makes them end up staring at the room through walls and not moving.

**Comment by AlexModGuy** [comment]
dupe #1449
