### ISSUE TITLE
My own Myrmex Sentinels are killing my pets

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1159]
Using TOP, I discovered the Myrmex have the "tamable" tag on their tooltip, but they don't actually tamed to you, the Queen which I hatched next to lay out wild Myrmex that is passivd to me, but still attack my pets

Also would like them to tame so that dragon strike don't affecy them thanks

**Comment by mser7** [comment]
That death message is important as well

**Comment by mser7** [comment]
Tamable Myrmex
![2018-12-26_09 15 00](https://user-images.githubusercontent.com/22555489/50430435-7934ef00-08f6-11e9-8a19-6872046f8467.png)

**Comment by mser7** [comment]
![2018-12-26_09 23 46](https://user-images.githubusercontent.com/22555489/50430827-e6e21a80-08f8-11e9-8f32-6eab70fc4f7e.png)

**Comment by AlexModGuy** [comment]
they aren't tamable, they extend EntityTamable just to have access to its methods. Although I guess i could just make them animals.

**Comment by mser7** [comment]
But the thing is they are killing my own pets, despite me having 100 reputation with the colony, could you just add the make them tamed? It's not like there is a way to make them sit, or wander on your demand, all the Myrmex casts are hostile toward my pets

**Comment by mser7** [comment]
How about this, why don't you make Myrmex queen that is hatched from the egg near you tamed to you, you are its owner, and all her offsprings also have you as the owmer?

"Ants doesn't understand loyalty, they will eat their own kind and even the one that raise them"
The owner tag is only there so the Myrmex can know and not attack your pets, or your pets attacking them, Myrmex also smart enough to give you a reputation for their hive, you don't even have to add in sitting, standing, following order for them, just the owner tag is ok, like vanilla horses, you can only ride them, have Myrmex attack villagers and animals even when tamed

"the colony that always have maximum reputation with you, at all time isn't tamed."
