### ISSUE TITLE
Hippocampus

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1184]
I have always dislike hippocampus, they are the worst mob.
![2018-04-14_00 20 58](https://user-images.githubusercontent.com/22555489/50442239-91296480-0930-11e9-9154-31b0bc204704.png)

**Comment by ghost** [comment]
nigga go die

**Comment by mser7** [comment]
So is this how it is going to be?
- Glitchy GUI that mess with you inventory as you are trying to interract with it
- Need to conquer a late game structure that require atleast full diamond gears just to get the stuff to lure, tame and breed
- Completely overshadowed by another equine mob that can fly and was added as the first additional mobs, inb4 "muh sea bed", thus make them become redundant as parrots
- Come in all different annoying rainbow colors
- Is a punching bag on land, don't even run away after being hit

Until I can lure one as soon as I see it, which will be in 1.13, and when the taming issue got fixed, I will always despite them, and take joy as I watch them die from taking falling damage at y=255.
