### ISSUE TITLE
Myrmex hatching time in the config isn't working

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1186]
Also the range is from 1~10000, but the default is 35000?
![2018-12-26_16 30 24](https://user-images.githubusercontent.com/22555489/50477237-0616a000-09fe-11e9-94dd-f4ab8f41b804.png)

**Comment by ShatteredXeno** [comment]
it worked for me (the myrmex eggs must be underground or covered with un'transparent blocks to hatch)

**Comment by mser7** [comment]
Thanks for the call, I will check again later, I thought this only applied to the queen

**Comment by ShatteredXeno** [comment]
but you are right. the myrmex hatch length default being 35000 is weird

**Comment by Karltheenderman** [comment]
but you are right. the myrmex hatch length default being 35000 is veird
