### ISSUE TITLE
[Enhancement] Stereo Audio Issue

### ISSUE THREAD

**Issue by TechnoMysterio** [Alex-the-666/Ice_and_Fire#1189]
This isn't particularly a bug, instead it's an issue relating to the sound effects in the mod. I've done some sound design for other mods in the past, and it took me a while to discover this issue myself.

Many of the sounds for the mod are in stereo, although not all. Stereo sounds in Minecraft are always played in both ears, even if the sound source is to the side of the player, behind them, etc. This can be a problem if the audio is coming from a certain position in the world. Since it always plays in both ears, you can't tell its direction, so an approaching mob can confuse you when it always sounds like it's right in front of you. Stereo sounds played over and over like this also tend to become more annoying.

Stereo sounds, however, are generally fine for things like music, ambience, or larger events that need more impact or that happen around the player, like summoning the Wither in vanilla.

As such, I'd recommend going over the sounds in the mod and converting ones which should be more directional (mob sounds mostly) to mono. This would help improve the in-game audio the mod has, and would also help cut down the filesize.

As a side question, I do think the sounds the mod has are very good, so I'm curious as to how they were made, or who did them? I thought I may have recognised some sounds from clips of Game of Thrones I've seen, though I'm not entirely sure.

**Comment by Lordician** [comment]
I second this.
I already pointed and helped out a couple of mods with the same issue.
Converting them to mono also helps with how loud they sound and some mod compatibility with reverb, echo or sound culling mods.

I'll see if i can put a proper pull request in.
