### ISSUE TITLE
Flying Error

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#119]
Kinda hard to show this in a screen shot, but a dragon was flying around and I noticed that it was not moving it was flying in place. When i flew up close enough to it in creative it just shot straight up in the air and that was the last i saw of it. the screen shot below probably won't be much help but ill post it anyways.
![2017-01-15_15 55 15](https://cloud.githubusercontent.com/assets/23727270/21972873/a0dbb23c-db8a-11e6-91d6-f58af8c48d89.png)

**Comment by Alex-the-666** [comment]
probably stuck at the edge of the chunk. This is sort of intended, we don't want dragons going around loading chunks :P
