### ISSUE TITLE
mymex compatibility tps freeze.

### ISSUE THREAD

**Issue by BretonAerouant** [Alex-the-666/Ice_and_Fire#1190]
oh, when, you combine the 1.6.0 for 1.12.2  version of the mod with bop, dynamic trees and dynamic trees bop compatibility the tps will randomly freeze while a mimex is onscreen, this problem will persist if you relog, (in short nothing moves and you cannot interact with anything wile this bug is taking place)

**Comment by AlexModGuy** [comment]
is there anything in the console output?

**Comment by AlexModGuy** [comment]
dupe #1510
