### ISSUE TITLE
Myrmex Queen Attacks larvae which spawned from egg player placed

### ISSUE THREAD

**Issue by BlueWither** [Alex-the-666/Ice_and_Fire#1194]
I just wanted to move egg, so I replaced an egg.
But when larva spawned, the queen killed it.

**Comment by mser7** [comment]
I think I reported this already

**Comment by mser7** [comment]
Yep, now close this duplicate
https://github.com/Alex-the-666/Ice_and_Fire/issues/1162

**Comment by BlueWither** [comment]
Oh Sorry

**Comment by mser7** [comment]
Good boy
