### ISSUE TITLE
Tamed dragons blast shouldn't replace blocks

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1197]
The explosion I can tolerate, but it shouldn't replace blocks and make a mess, wild ones are free to do whatever they want.

**Comment by GundunUkan** [comment]
This is still the same attack tho, makes no sense. The dragons are tamed and suddenly their fire magically is more concerned about its surroundings.

**Comment by mser7** [comment]
I got a new one open up for this issue that I explain more detail

**Comment by mser7** [comment]
https://github.com/Alex-the-666/Ice_and_Fire/issues/1200
