### ISSUE TITLE
Possible Dragon and/or Sword Damage bug

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#120]
It is either a problem with the dragons health or the damage that a Fire/Ice dragon bone sword inflicts. No matter the stage  (tested stages 1,2,3 and assuming it would be the same for stage 4 and 5) hitting any dragon twice with the dragon bone sword that was meant to oppose the dragon (tested on both fire and ice dragons) kills the dragon. Using a fire sword on a fire dragon kills it in 3 hits. Also using the fire or ice sword on regular vanilla mobs kills them in about 3 hits.

**Comment by raptorfarian** [comment]
The issue was actually due to dragons spawning in with low health and has now been resolved.
