### ISSUE TITLE
Tamed dragon still grief despite the config setting

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1200]
They still destroy terrain, and their bullet still create a mess
![2018-12-27_17 20 29](https://user-images.githubusercontent.com/22555489/50477077-59d4b980-09fd-11e9-9eda-57475d2e207b.png)
![2018-12-27_17 20 31](https://user-images.githubusercontent.com/22555489/50477078-59d4b980-09fd-11e9-962d-a56b37b1e801.png)

![2018-12-27_17 35 58](https://user-images.githubusercontent.com/22555489/50477251-1890d980-09fe-11e9-823e-df614011f3ce.png)

**Comment by mser7** [comment]
If it was "grief due to stuck" then I also don't approve, since I can get it out myself

**Comment by mser7** [comment]
For the dragon's blast attack, my reason for it not destroying terrain is that the dragon blow out a less powerful breath, but is still strong enough to damage mobs.

**Comment by GundunUkan** [comment]
Still dragonfire, no matter how weak it should still scar the land. Makes no sense.

**Comment by mser7** [comment]
Yeah, I didn't really thought about irl dragon's breathing logic, I just want to use this attack  without having it messes up the terrain, lets just leave it for Alex to decide.

**Comment by mser7** [comment]
My tamed dragon nearly killed me by blasting its bullet at me, how about this, tamed dragons no long perform breath attack on their own if this rule is set to false, you can still use it breath attack while riding it, breath attack will still be full power when used
