### ISSUE TITLE
Can't Disable Myrmex

### ISSUE THREAD

**Issue by EvilDylan** [Alex-the-666/Ice_and_Fire#1206]
Deleted and regenerated config. There appears to be no option to disable myrmex. Perhaps it doesn't generate in the config properly?

**Comment by AdaraChristine** [comment]
I don't think they included a spawn setting. Too bad because i don't want the Myrmex. So im not going to update.

**Comment by scotty9090** [comment]
As far as I can tell you can only disable the nests from being generated - which doesn't help on an existing world obviously.

**Comment by EvilDylan** [comment]
I didn't see any option to disable the nests--the only option in my config about them is the rarity in mine, whereas everything else has a rarity and a binary for spawning or not. Even the gorgons, cyclopses, and sirens, which also spawn with structures.

**Comment by AlexModGuy** [comment]
fixed
