### ISSUE TITLE
Remove collision for hitboxes on the wings

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1208]
The dragon is being pushed around by mobs touching it wings

**Comment by mser7** [comment]
And maybe at the head and tail also, basically only keep the collision for the center belly hitbox

**Comment by AlexModGuy** [comment]
no

**Comment by mser7** [comment]
Can you at least remove the wings hitboxes, my big dragon got pushed around whenever I approach it to check its info
