### ISSUE TITLE
Myrmex goes to a spot, and don't know what to do next

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1212]
They are trying to tend to the egg
![2018-12-29_16 23 12](https://user-images.githubusercontent.com/22555489/50536447-50775880-0b87-11e9-9cfd-9e08e4c70353.png)
![2018-12-29_16 24 03](https://user-images.githubusercontent.com/22555489/50536448-510fef00-0b87-11e9-8f89-36c1624788c3.png)
and the gif:
https://imgur.com/MkE7pUA

**Comment by AlexModGuy** [comment]
dupe #1449
