### ISSUE TITLE
Dragons should attack passive mobs from other mods

### ISSUE THREAD

**Issue by Sunconure11** [Alex-the-666/Ice_and_Fire#122]
Just a nitpicky kind of suggestion

**Comment by Alex-the-666** [comment]
Do you have an idea how I should be able to tell which mobs from other mods are hostile and which are passive?

**Comment by PlatinumFox** [comment]
Don't really know a lot about coding. But I know some mobs in the mo creatures mod only attack certain mobs/passive mobs. If it's open source maybe you could look there for ideas.

**Comment by Alex-the-666** [comment]
That mod isn't open source so I am unable to see how it ticks.

**Comment by Sunconure11** [comment]
You can decompile it. Decompilers are everywhere.

**Comment by Sunconure11** [comment]
I know of two mods that are open source you can look at:

https://github.com/BobMowzie/MowziesMobs

https://github.com/Lycanite/LycanitesMobs

**Comment by charlesbevans** [comment]
Mowzie's appear indiscriminate. I've watched the carnivorous plants gobble up skeletons, zombies, fluid cows, and a first-person view from a certain player, who will remain nameless, but waked right on to one.
You can ask mo' creatures' devs, but I expect they're checking inheritance.
Alternatively, you could check the mob drops for food, dragons are only interested in food... or shiny objects.
