### ISSUE TITLE
Wild dragon sits

### ISSUE THREAD

**Issue by BlueWither** [Alex-the-666/Ice_and_Fire#1220]
![](https://i.imgur.com/dvR4F9A.png)
I don't know why it happened, but it happened when it fights with little maid from LittleMaidMob Reengaged peko build.
https://forum.minecraftuser.jp/viewtopic.php?t=31761

**Comment by AlexModGuy** [comment]
I believe the issue may be on the little maids mob side. Do they have a github so I can see the code of the mob?

**Comment by BlueWither** [comment]
https://github.com/Verclene/LittleMaidReengaged/releases
This is,  but for 1.10.2.
Japanese forum is closing now, so I can't send comment.

**Comment by AlexModGuy** [comment]
the little maid mod needs to deal with this. there's no way forr me to stop them from forcing dragons to sit.
