### ISSUE TITLE
Dragon nests spawn in villages

### ISSUE THREAD

**Issue by Sunconure11** [Alex-the-666/Ice_and_Fire#123]
https://www.dropbox.com/s/e661o9771655c02/Screenshot%202017-02-03%2014.59.18.png?dl=0

This should not be the case.

On a side note, we need a configuration option for the spawn rates of mobs, as well as structures.

https://www.dropbox.com/s/rj4yf7qu3m6vx7j/Screenshot%202017-02-10%2016.25.26.png?dl=0

**Comment by Alex-the-666** [comment]
Ive fixed the spawn rates, but sadly I cannot figure out whether a block is in or out of a village to spawn dragons so that issue cannot be solved.
