### ISSUE TITLE
Make cockatrice more sensitive in detect enemies

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1244]
If a mob is detected going after a chicken, the cockatrice will hostile toward it, not even hitting the chicken, just target it is enough. Can this behavior be applied to tamed cockatrice protecting players? If it detect a mob targeting a player,or another cockatrice, it will immediately attack it.

**Comment by mser7** [comment]
And I notice cockatrices can stare at chickens enemy from much further distance.

**Comment by mser7** [comment]
This one go for the mobs immediately after summoned, proving that cockatrice can be much more efficient in protecting themself or players.
https://imgur.com/7uSG7Xl

**Comment by AlexModGuy** [comment]
no. this would make cockatrice as laggy or even more than sirens pre 1.6.0.
