### ISSUE TITLE
Option to disable structures in Superflat mode (1.12.2-1.5.2)

### ISSUE THREAD

**Issue by noobanidus** [Alex-the-666/Ice_and_Fire#1250]
Greetings!

While I've yet to fully experience your Mod, I'm primarily interested in adding compatibility for it to for my mod (Dude! Where's my Horse?). While that compatibility isn't planned for my next release (compatibility with other mods unfortunately took up more time), I've got Ice and Fire sitting in my libs folder and thus it's loaded whenever I play.

Unfortunately, random dragon monuments seem to be spawning in my superflat worlds and if I happen to turn my back, they come waltzing along and munch on my horses. Which is hilarious! Unfortunately it's a little frustrating; I was hoping there would be an option to disable structure generation JUST in superflat mode (or better yet, an option to enable it and have it specifically disabled by default similar to how Astral Sorcery works) but unfortunately there wasn't.

Is there a chance of adding an option to disable structure generation in superflat worlds? 

Additionally, is there an a chance that this could be made the default for superflat worlds and the option instead enables the generation of these structures in superflat?

Thanks a bunch! I look forward to summoning your dragons via my mod -- eventually!

**Comment by AlexModGuy** [comment]
alright, i'll look into it

**Comment by mser7** [comment]
I thought there is already a generate config option for each separated structures, that will disabled it on whatever world you create?

**Comment by noobanidus** [comment]
There are indeed, but a) that requires going through the config to disable every structure type, and b) that requires going back through and enabling them again when I'm not in a superflat world. Given that I do a lot of testing that involves wiping the `run` folder, it can be tiresome to have to modify the configuration that frequently -- a single "no gen in superflat" would resolve everything.

It's not a huge deal though, just one of minor convenience.
