### ISSUE TITLE
[feature request] blacklist for blocks a dragon can't destroy

### ISSUE THREAD

**Issue by kreezxil** [Alex-the-666/Ice_and_Fire#1256]
@Alex-the-666 I know it's technically upon the author of the other mods to increase the resistance of their blocks. But as you are well aware and do know from personal experience those authors can't always be reached and for many reasons can't even revisit the mod, sometimes ever.

Add a blacklist for blocks that Dragons can't destroy no matter what. 

Maybe even go so far as to add an area blacklist as well, for instance anything in coords xyz to coords xyz can't be destroyed by a dragon at all. Which would be great for creating Dragon zoo's on a server.

This would eliminate all the bickering about "blah blah gravestone mod blah blay your dragon blah destroyed it" but it would also eliminate complaints about dragons breaking other things a pack/server owner did not want them to break.

**Comment by mser7** [comment]
Can I also instead a whitelist feature?

**Comment by AlexModGuy** [comment]
i'll look into this

**Comment by AlexModGuy** [comment]
blacklistedBreakBlocks in the config
