### ISSUE TITLE
Dragons attempting to fly past render distance and getting stuck

### ISSUE THREAD

**Issue by Kusark** [Alex-the-666/Ice_and_Fire#126]
Whenever dragons fly too far and try to go past whatever your render distance is (and into chunks that haven't been loaded), they stop in one place and they don't move, this happens a lot when they fly way too high in the air, although I believe flying too high is a different issue. It slows things down a lot. Perhaps dragons should just fly around in a circle when they take off instead of flying off into the distance and up into the air.

**Comment by PlatinumFox** [comment]
I have also seen this problem. Some times when in creative mod flying toward the dragon made it shoot straight up in the air. Also I think that wild dragons should have a height limit if them getting stuck by the render border cannot be fixed but while riding a dragon it should not have a height limit.

**Comment by Alex-the-666** [comment]
There is no way for the server(which handles dragon flight) to tell your render distance. Unfixable.
