### ISSUE TITLE
Sirens should do small tick damage when luring you.

### ISSUE THREAD

**Issue by StoneLegion** [Alex-the-666/Ice_and_Fire#1263]
Your mod has given nothing but heads to me and others compared to the other 200+ mods. Most due to the fact we have had sirens on the world border trapping people on the border. Sirens pulling people against a surface they can't get up so their stuck against without being able to reach the sirens. Sirens in 2 packs close enough to force the user to be stuck between the 2 groups.

None stop issues it's actually quite annoying to get requests of help to move someone or even just kill them because they don't want to live any longer.

Could you do something where they stop if it lasts too long or start damaging the player slowly so they can die and move on in life?

**Comment by AlexModGuy** [comment]
fixed, i added a config for how long they can lure players with a cooldown inbetween songs
