### ISSUE TITLE
Can still hear Siren and be attracted while wearing Ear Defenders from Immersive Enginnering

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1264]
It is basically a sound muffer, it can also be attatched to helmets, so if possible, can you make wearing ear defended helmets players immune to Sirens?

**Comment by DoomRater** [comment]
I hate to say it, but this does not appear to work.  Simply searching for earmuff does not seem sufficient as Ear Defenders can be attached to helmets in NBT data.  Tested in 1.12.2 version 1.9.1 using Immersive Engineering 0.12-98 and attaching Ear Defenders to a Thaumcraft Void Thaumaturge Hood (Thaumcraft 6.1BETA26).
