### ISSUE TITLE
[1.6.0-1.12.2] Major server lag issues -- possibly found

### ISSUE THREAD

**Issue by kreezxil** [Alex-the-666/Ice_and_Fire#1265]
In my new version of the World of Dragons I have discovered massive amounts of lag spiking. Through normal methods of investigation I have removed the mods that were "apparently causing it" and managed to improve things quite a bit.

But it was still happening and the dev from Minecolonies suggested I use Spark from [](https://sparkprofiler.github.io). This is an awesome java program that sits inside the mods/plugins folder and profiles your server/client in ways that are superior to most other methods.

Cutting to the chase, it appears there is some recursive code being executed in the walk node processor. Sadly the screenshot doesn't show it, But when you hover over the elements it will show you the ms of lag being caused. In most cases it exceeds 39,000 ms. There are some heavy instances where it his 290,000 ms+ and I think those might be caused by unnecessary or too deep recursion.
![process nesting](https://www.kreezcraft.com/wp-content/uploads/2019/01/HyYFV6eGN.png)

Not sure how long the analysis will remain up, [https://sparkprofiler.github.io/#j51miE9T2k](https://sparkprofiler.github.io/#j51miE9T2k). I hope that it can give you some insight.

I noticed that spark had a mapping option so I turned that on for 1.12.2, in this screen shot we can see on the hovered line that there is 113,356 ms of lag recorded. ![major lag](https://www.kreezcraft.com/wp-content/uploads/2019/01/Screenshot_1.png)

Possible related reports: #1059, #993, #287, #260, #233, #131, #50

**Comment by AlexModGuy** [comment]
we use the vanilla walk node processor and always have. The only mob that uses a modded walk node processor is the death worm. I have no clue what could be causing vanilla to have a hissy fit, but as you can see, 98.99% of the lag is being inherited from the vanilla animal class. Regardless, I will look into this.

**Comment by AlexModGuy** [comment]
also thanks for introducing this tool, it is very intresting

**Comment by AlexModGuy** [comment]
WalkNodeProcessor.getSafePoint() seems to be the root of the issue.

**Comment by AlexModGuy** [comment]
Alright, 1.6.1 will contain an Experimental Pathfinding system, which is essentially a dumbed down version of the current one, that doesn't check as large of an area every tick. It will be configurable in 1.6.1.

**Comment by kreezxil** [comment]
@Alex-the-666 my friend Raycoms aka H3lay of https://github.com/ldtteam/minecolonies has a path finding system they use that fixes lots of the issues. If you want, they have welcomed the thought of talking with you. You can find them on Discord at https://discord.gg/xPmZmv3 and I've already invited them to yours.

**Comment by AlexModGuy** [comment]
@kreezxil I have taken a look at the code and unfortunately a lot of it looks quite specialized to minecolonies and their behavior, and I don't believe much of it could be extrapolated to the dragons. I'll have to create my own sometime

**Comment by kreezxil** [comment]
ok, it was a thought.

I did talk with the minecolonies team, and they were interested in
collaborating with you to create a walk node processor replacement library
that mods could use.
