### ISSUE TITLE
Tamed Dragon Disappear

### ISSUE THREAD

**Issue by Mimiokish** [Alex-the-666/Ice_and_Fire#1266]
Hey, I am playing this mod on my server. This is one of the greatest mod I have ever played. However, we are currently experiencing tamed dragon disappearing. It happens when we right click and hold the horn.  It also happens when we let the dragon out and have she sit on the ground.  I looked up the config file. There is no such option for me to set tamed despawn to false. We also tried to give a tamed dragon a name tag which in vanilla minecraft should prevent system to despawn the mods. But It won't work. Tamed dragon still disappear. Do you guys know how to fix this?

**Comment by Draconian4466** [comment]
don't know if this helps but I have had this issue when I try to put my dragon out of the horn nothing comes out and my horn is empty a relgog fixes it

**Comment by Mimiokish** [comment]
> 
> 
> don't know if this helps but I have had this issue when I try to put my dragon out of the horn nothing comes out and my horn is empty a relgog fixes it

Yeah, that happened to me too. Also, when I flying with my dragon, it disappear too. 
I might have language barrier. What you mean by relgog? exit and login again?

Another problem the mod author should know that, sometimes, when I dismount at place A, I will be teleport to place B where I mount the dragon. But the dragon will still stay in place A.

**Comment by Draconian4466** [comment]
yeah I meant exit and log in again sorry for the typo this fixes it if your talking about the glitch I think you are.

**Comment by AlexModGuy** [comment]
this is most likely due to your server removing entities it deems moving too fast or too large. Tell me if there is anything in the logs of an AxisAllignedBB or bounding box, or if it contains the message "moved too quickly". Tell me if you have Sponge or Bukkit or a similar service as well.

**Comment by Mimiokish** [comment]
> 
> 
> this is most likely due to your server removing entities it deems moving too fast or too large. Tell me if there is anything in the logs of an AxisAllignedBB or bounding box, or if it contains the message "moved too quickly". Tell me if you have Sponge or Bukkit or a similar service as well.

haha, well, i do i have the Sponge installed. But I did not see any message says remove entities or moved too quickly. Is there anything I can do to fix this?

**Comment by Mimiokish** [comment]
> 
> 
> yeah I meant exit and log in again sorry for the typo this fixes it if your talking about the glitch I think you are.

Yeah, thank you for helping.

**Comment by AlexModGuy** [comment]
see #1114 and https://forums.spongepowered.org/t/entity-being-removed-for-bounding-box-restrictions/26206

**Comment by Mimiokish** [comment]
> see #1114 and https://forums.spongepowered.org/t/entity-being-removed-for-bounding-box-restrictions/26206

Great! this actually works.

For other people having same problem:
**First, go to here download this sever-side-only mod called gotta go fast**
https://minecraft.curseforge.com/projects/gotta-go-fast

**Then, find config/sponge/global.conf, and change these to 0**
max-bounding-box-size
max-speed

you should be good to go : )

**Comment by kreezxil** [comment]
Alex the dragons disappearing after being released from the horns is happening again. Please join my server, we'll give you creative status so you can test it first hand.

**Comment by AlexModGuy** [comment]
dupe #214
