### ISSUE TITLE
Arrows bouncing off of dragons

### ISSUE THREAD

**Issue by Kusark** [Alex-the-666/Ice_and_Fire#127]
The arrows just bounce off the dragon. And yes, I'm definitely hitting it's bounding box, I've got F3+B on to make sure that I am. I think this ties in with the other dragons trying to fly past the render distance, but I'm not sure.

**Comment by Kusark** [comment]
Ok, whenever I leave the chunk of the dragon and shoot it with the arrow that seems to work. Also whenever I enter the chunk of the dragon that's attempting to leave my render distance and then try to shoot the other dragon, it works. I know that sounded confusing, perhaps I can try to replicate this again and record it, but this must have something to do with chunks.

**Comment by Alex-the-666** [comment]
Arrows aren't meant to hurt them. try dragonbone arrows.
