### ISSUE TITLE
One sugar piece should heal pixie completely

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1272]
One sugar heal 5 hp, which is 1/2 of pixies health atm, it should completely them back to full health when eaten

**Comment by AlexModGuy** [comment]
no. sugar is already cheap to make as is and mostly useless.

**Comment by mser7** [comment]
I just want to heal my pixie up quickly

**Comment by mser7** [comment]
they fly around all over the place when tamed, it is very difficult to double click them twice
