### ISSUE TITLE
Have tamed pixies calm down and stay still when not following the player

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1281]
I notice tamed pixie will hover near the ground when you are standing still, but only after a while, can you make it so if the player is standing still, then pixies will stop moving and hover near the ground?

**Comment by mser7** [comment]
This videos demonstrated it, pixies not immediately flop down when you are standing still, and there is no need for them to fly around anymore
https://youtu.be/mCBSQ2_sNHk?t=282

**Comment by mser7** [comment]
I understand that if player are flying then the pixies will sink down too low, if that is the case, then pixies should fly up to stay close to you, and not stay still, then so be it

**Comment by AlexModGuy** [comment]
intended
