### ISSUE TITLE
tamed stage 5 dragon dissappearing

### ISSUE THREAD

**Issue by Malcolmhooi** [Alex-the-666/Ice_and_Fire#1284]
i have been having my dragon for awhile now and even went far awat places with no problem on kreez's server but at one point i decided to go help a friend who also lost his dragon, i started flying and server decided to kick me and after getting back in my dragon was gone and i fell down to the floor, i tried searching the whole area ,spamming the flute and even camping at the home set i set for the dragon 46km away for hours hoping it would come back. is there anything else that could be done other than just get a new one?

**Comment by AlexModGuy** [comment]
minecraft servers often kill one's mount when booting them from the server. I'm not quite sure what can be done to fix it, but I would look into #1114 and #1266
