### ISSUE TITLE
Add Tinker's Construct support in the future

### ISSUE THREAD

**Issue by Sunconure11** [Alex-the-666/Ice_and_Fire#129]
A lot of mods with their own materials for weaponry and what not add support for that mod. Maybe you can add Dragonbone as a possible material for Tinkers Construct?

https://github.com/SlimeKnights/TinkersConstruct/wiki/Building-an-addon

https://github.com/SlimeKnights/TinkersConstruct

If needed, you can look at mods that have made their own stuff for Tinkers Construct.

https://github.com/MinecraftModDevelopmentMods/BaseMetals

https://minecraft.curseforge.com/projects/tinkers-construct/relations/dependents?filter-related-dependents=3

https://minecraft.curseforge.com/projects/tinkers-construct/relations/dependents?filter-related-dependents=2

**Comment by Alex-the-666** [comment]
Wouldn't this mean our mod would have to require Tinkers?

**Comment by PlatinumFox** [comment]
I think sunconure might be referring to extra tic i think? the applied energistics mod doesnt have anything to do with TC but with extra tic you are able to use some applied energistics parts for TC tools and what not. or i could be misunderstanding what he is saying.

**Comment by Sunconure11** [comment]
I was referring to the fact that Tinkers Construct has an API you can hook into and add support for its materials. You would not need Tinkers Construct for this mod if this was implemented.

**Comment by mser7** [comment]
An example for this would be Extra Utils 2, it has the experience and demonic ingot as a material for TiC, but it doesn't require neither TiC nor PlusTiC. If there is TiC installed along with it, it will automatically branch TiC compat
Also this mod already has silver compat for TiC, but that is because the material is written off Ore dict, I suggest using sapphire for material as well

**Comment by mser7** [comment]
I have another idea, if liquid sapphire is added for this, then snow villagers should produce liquidfied sapphire when smelted.

**Comment by ReineRosette** [comment]
I might be looking into doing this myself, with it's own addon. I've done a lot of coding, but not for MC so it might be a bit.

**Comment by SokyranTheDragon** [comment]
I've started working on integrating it a few days ago. I've already implemented some stuff in there. A lot of that is unfinished (dragon bone material doesn't have anything unique right now), and someone else will have to make new textures (I'm not capable of making new ones). And it might be a good idea to check the additions to language files I've made, just in case.

https://github.com/exploder1531/Ice_and_Fire/tree/Tinker's-Construct-Integration

**Comment by SokyranTheDragon** [comment]
I wanted to add support for Construct's Armory (and maybe a few other Tinker's addons as well), but I'll take care of that once I'm done with supporting the mod itself.

**Comment by AlexModGuy** [comment]
as much as i appreciate all of you working on your own add-ons, tinkers construct support will be a major feature for 1.8.0. I don't want you all to waste your time in vain.

**Comment by SokyranTheDragon** [comment]
Couldn't you just use my work? At least to have some base for your own integration? I'm working on a fork that could be easily merged if you wanted to do so.

You'd just need to tweak some stuff so it matches how you want to balance it, modify some values so it work as you want it to, as well as add a few new textures (and potentially tweak the language files).

I got back to working on Minecraft mods after a few year break, and I thought that contributing here might be nice. Especially considering that this is one of my most favorite mods (if not the most favorite one already).

**Comment by AlexModGuy** [comment]
fixed
