### ISSUE TITLE
Have dragons dig down to enemies

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1291]
There is a cheese for dragons atm where if you dig down a deep 1x1 hole, the dragon wouldn't be able to get you, the dragon should break the ground and get to its enemies if they are 3 blocks lower, and is directly below its feet.
![2018-12-13_15 24 43](https://user-images.githubusercontent.com/22555489/51008625-278b9600-157f-11e9-8b86-7811af3eb668.png)

**Comment by AlexModGuy** [comment]
no
