### ISSUE TITLE
mymrex colonys are to rare and they don't have an entrance

### ISSUE THREAD

**Issue by ShatteredXeno** [Alex-the-666/Ice_and_Fire#1292]
i made 6 worlds an only the first one had a myrmex colony, although i set the hive generation chance to max (10000). i think the solution is that there is a comand that allows to locate the structures of this mod. but the myrmex colonys do not have entrances.

**Comment by AlexModGuy** [comment]
you made them rarer by increasing that number, which is a ratio. you made it so they spawn in 1/10000 chunks. lower it to make them more common
