### ISSUE TITLE
Dragon vanishes/teleports after getting on and trying to move.

### ISSUE THREAD

**Issue by Goldfort1555** [Alex-the-666/Ice_and_Fire#1293]
Everytime I mount a dragon and try to move at all it either teleports or just dies? and them im kicked from the server for a invalid move player error. Its on a server and we do have quite a few mods, so could be a incompatibility thing but it refuses to give me a crash log so im not sure how to check whats causing it.

**Comment by AlexModGuy** [comment]
dupe #942
