### ISSUE TITLE
Underground dragon emerging and destroying your base

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1301]
It is just a matter of time until someones base is destroyed because he built it near a giant dragon cave because of the dragon, and then he ragequit because its a late game base, can there be a slight warning about this in-game, perhap in the bestiary, so players can check the underground near his base, I also thinking of a special splash text that warn you about this

**Comment by mser7** [comment]
Like in the dragon cave entry:"the giant dragon inside can wake up from its slumber and erupt from his cave and destroy the ground near him if there is too much disturbance, so one should make sure there isn't any in the underground of his future home"

**Comment by PlatinumFox** [comment]
Warning system is unneeded. If a player does this then it is just pure stupidity and/or misfortune that this happens. (check under your house its not that hard).

**Comment by mser7** [comment]
Its not hard, but bc people is unfamiliar with digging around below to check under their base, so we give them a warning in the book so they are aware of the danger, and they can't no longer be mad at us if their base got destroyed because they ignored the book

One time I tried to find a new base location, and after finished moving items and built the first house, I went out and explore and there was a giant dragon that managed to staircase out of its cave from bedrock, I dont even mine anywhere near it since the resources is already gathered beforehand

**Comment by mser7** [comment]
Also Alex said it is intended for giant dragons to break out of the cave

**Comment by AlexModGuy** [comment]
theyre dragons... its kinda what they do... destroy things
