### ISSUE TITLE
1.6.1 dragons fly too high

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1314]
my dragon was flying around near a homepoint happily until I have it kill a live prey, after that it took off normally, but quickly ascent into the sky far from my view, shortly after I discovered that it is hanging around ~256, which is where the flying height limit is, but I want to have it fly near the ground and now is there no way it fix it, and I would also love to use it to fly to my sky base at  y=256, so can you fix the AI so it always fly near the ground no matter what? I have no idea to fix this

**Comment by AlexModGuy** [comment]
fixed
