### ISSUE TITLE
1.6.1 set a new default height limit in the config

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1315]
Since dragons are teleported below the limit, set the default at 260 so I can at least fly above the building limit

**Comment by empty789** [comment]
Please fix it. Let us set a height in the config. I tried increasing "Max Dragon Flight Height", but it doesnt do anything. We try to build in a mountain on y=200+ and we can't bring the dragons up there.

**Comment by empty789** [comment]
Nvm for everyone having troubles. I first set the height to 1000, as it was mentioned as the max range, but this did nothing. Set the flight height in the config to 255 and everything works as expected.

**Comment by AlexModGuy** [comment]
fixed
