### ISSUE TITLE
Sitting above dragon

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#132]
When flying a dragon the player sits directly above the armor and it does not look right. Since dragons come in all sizes depending on how you feed them maybe instead of moving the player add a dragon saddle item and recipe and add a slot to the dragon gui where the player puts on the dragons armor place the saddle there and when you fly the saddle hides where the player is really sitting. 

(just trying to suggest a fix, again I have no clue about coding, hiding the fact that the player hovers above the dragon seems easier in my head than moving the player... plus a dragon saddle would probably look cool and could maybe have chests be added).

**Comment by Alex-the-666** [comment]
Pics please

**Comment by PlatinumFox** [comment]
![2017-03-03_02 17 06](https://cloud.githubusercontent.com/assets/23727270/23541803/b35cdc82-ffb7-11e6-95b0-e95c6945dd5b.png)

![2017-03-03_02 17 08](https://cloud.githubusercontent.com/assets/23727270/23541805/b7a9d862-ffb7-11e6-9200-ec402e856307.png)

![2017-03-03_02 17 13](https://cloud.githubusercontent.com/assets/23727270/23541806/ba0ec36a-ffb7-11e6-9fb9-7c8d9ceb2c80.png)

![2017-03-03_02 17 20](https://cloud.githubusercontent.com/assets/23727270/23541808/bbddcbd2-ffb7-11e6-8925-2e262f3d8a62.png)

**Comment by Alex-the-666** [comment]
Seems to be old issue, what build are you using

**Comment by PlatinumFox** [comment]
Beta 6 (latest)

**Comment by Alex-the-666** [comment]
What stage dragon is this?

**Comment by PlatinumFox** [comment]
Stage 3 between 50-60 ish days I think.

**Comment by Alex-the-666** [comment]
Yes confirmed issue!

**Comment by Alex-the-666** [comment]
fix
