### ISSUE TITLE
Myrmex stops when cocoons are filled with items

### ISSUE THREAD

**Issue by BlueWither** [Alex-the-666/Ice_and_Fire#1320]
They no longer have cocoons that can contain items, and they stop moving.
When I put new cocoon, they moved again.

**Comment by mser7** [comment]
What do they do when stopped? Just standing there?

**Comment by BlueWither** [comment]
Workers which carrying item stands and not move again.
Also, they can't stack items when cocoon is full.
For example, if a cocoon filled items including some seeds, but they won't carry seeds on that cocoon anymore.

**Comment by mser7** [comment]
You should make a new issue for item stacking issue then, this one is about cocoon being fulled, I confused from reading your first description
