### ISSUE TITLE
Strange MiencraftServer Freez with Mobs

### ISSUE THREAD

**Issue by SirAron111** [Alex-the-666/Ice_and_Fire#1321]
So I updated the mod to iceandfire-1.6.1-1.12.2   and now a bit of time after spawning in the world the World Freezes and you can’t do anything anymore just push around the mobs with your body but not attack them and nothing moves can’t even drop items but it isn’t a crash I have to use task manager to stop minecraft as I can’t do anything can this be fixed?

Here is a link to the log of the console:
https://pastebin.com/W4t2MzHn

**Comment by AlexModGuy** [comment]
old outdated version, probably was related to #1449
