### ISSUE TITLE
Reduce cockatrice's food searching range while following

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1329]
While the cockatrice is following you, and if it need to heal, then it will try to leave you if there is food far away. So when folllowing, the food searching range of the cockatrice need to be reduced, maybe to a 5 blocks radius, so that it wouldnt leave you anymore and would eat the food that is around it, after the range is reduced, have the food searching AI to priority over the basic AI, since cockatrice will not take long to get to the food this time.

**Comment by mser7** [comment]
I am fine with its range while wandering, as it can seek food from far away, and can heal easier

**Comment by AlexModGuy** [comment]
no
