### ISSUE TITLE
[1.6.1-1.12.2] Lag much better but still there with the new system.

### ISSUE THREAD

**Issue by kreezxil** [Alex-the-666/Ice_and_Fire#1331]
see also #1265 

New spark profiler data: https://sparkprofiler.github.io/#QMJnULf58m

**Comment by kreezxil** [comment]
here's another pointing a finger at cockatrices, looks like they might responsible for 3kms of lag each. https://sparkprofiler.github.io/#LO5HYYQzjp

**Comment by mser7** [comment]
maybe because of the increase in how far can cockatrice attack?

**Comment by mser7** [comment]
If it so can you add a config for cockatrice's enemy targetting? My world is fine even with 20 cockatrices running around
