### ISSUE TITLE
Myrmex Queen should not move too much

### ISSUE THREAD

**Issue by BlueWither** [Alex-the-666/Ice_and_Fire#1335]
She often moves about, occasionally going out into the hallway and plugging the hallway.
Perhaps she is using the same AI as the worker?
Besides, she has a heavy belly and I think it strange to move fast.

**Comment by SirAron111** [comment]
To add to that the myrmex layer isn’t big enough at least the room the queen is in should be bigger so she doesn’t die from suffocation after spawning in.

**Comment by AlexModGuy** [comment]
fixed
