### ISSUE TITLE
Error 1/21/2019 , crashes on load.

### ISSUE THREAD

**Issue by clay3583** [Alex-the-666/Ice_and_Fire#1337]
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bake(ModelLoader.java:419)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:161)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:640)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:475)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 10223992048 bytes (9750 MB) / 10702815232 bytes (10207 MB) up to 10702815232 bytes (10207 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -Xms10G -XX:+UseParallelGC -XX:ParallelGCThreads=3 -XX:MaxGCPauseMillis=3 -Xmn256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2796 Optifine OptiFine_1.12.2_HD_U_E3 73 mods loaded, 73 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                        | Version                  | Source                                               | Signature                                |
	|:----- |:------------------------- |:------------------------ |:---------------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                 | 1.12.2                   | minecraft.jar                                        | None                                     |
	| LC    | mcp                       | 9.42                     | minecraft.jar                                        | None                                     |
	| LC    | FML                       | 8.0.99.99                | forge-1.12.2-14.23.5.2796.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                     | 14.23.5.2796             | forge-1.12.2-14.23.5.2796.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | ivtoolkit                 | 1.3.3-1.12               | minecraft.jar                                        | None                                     |
	| LC    | otgcore                   | 1.12.2 - v7              | minecraft.jar                                        | None                                     |
	| LC    | dsurroundcore             |                          | minecraft.jar                                        | None                                     |
	| LC    | mercurius_updater         | 1.0                      | MercuriusUpdater-1.12.2.jar                          | None                                     |
	| LC    | antiqueatlas              | 4.5.0                    | [CORE]antiqueatlas.jar                               | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LC    | antiqueatlasoverlay       | 1.2                      | [CORE]antiqueatlas.jar                               | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LC    | ctm                       | MC1.12.2-0.3.3.22        | [QOL]connectedTextureMod.jar                         | None                                     |
	| LC    | appliedenergistics2       | rv6-stable-6             | [CORE]appliedenergistics2.jar                        | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LC    | jei                       | 4.14.4.259               | [CORE]justenoughitems.jar                            | None                                     |
	| LC    | jee                       | 1.0.4                    | [CORE]appliedenergistics2JEI.jar                     | None                                     |
	| LC    | baubles                   | 1.5.2                    | [CORE]baubles.jar                                    | None                                     |
	| LC    | guideapi                  | 1.12-2.1.8-63            | [LIBRARY]Guide-API-1.12-2.1.8-63.jar                 | None                                     |
	| LC    | bloodmagic                | 1.12.2-2.3.3-101         | [CORE]bloodMagic.jar                                 | None                                     |
	| LC    | thaumcraft                | 6.1.BETA26               | [CORE]thaumcraft.jar                                 | None                                     |
	| LC    | botania                   | r1.10-358                | [CORE]botania.jar                                    | None                                     |
	| LC    | ceramics                  | 1.12-1.3.6               | [CORE]ceramics.jar                                   | None                                     |
	| LC    | embers                    | 1.12                     | [CORE]embersRetro.jar                                | None                                     |
	| LC    | twilightforest            | 3.9.851                  | [DIFFICULTY]twilightforest.jar                       | None                                     |
	| LC    | immersiveengineering      | 0.12-88                  | [CORE]immersiveEngineering.jar                       | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LC    | engineersdoors            | 0.8.0                    | [CORE]immersiveEngineeringJEI.jar                    | None                                     |
	| LC    | jeresources               | 0.8.5.27                 | [CORE]justenoughresources.jar                        | None                                     |
	| LC    | mystcraft                 | 0.13.7.02                | [CORE]mystcraft.jar                                  | None                                     |
	| LC    | akashictome               | 1.2-12                   | [QOL]AkashicTome.jar                                 | None                                     |
	| LC    | quark                     | r1.5-144                 | [QOL]quark.jar                                       | None                                     |
	| LC    | autoreglib                | 1.3-24                   | [LIBRARY]AutoRegLib-1.3-24.jar                       | None                                     |
	| LC    | psi                       | r1.1-69                  | [CORE]psi.jar                                        | None                                     |
	| LC    | scannable                 | 1.6.3.22                 | [CORE]scannable.jar                                  | None                                     |
	| LC    | tc6aspects4jei            | 0.0.2a                   | [CORE]thaumicAspectJEI.jar                           | None                                     |
	| LC    | tcinventoryscan           | 2.0.10                   | [CORE]thaumicInventoryScanning.jar                   | None                                     |
	| LC    | thaumicjei                | 1.2.1                    | [CORE]thaumicJEI.jar                                 | None                                     |
	| LC    | waystones                 | 4.0.67                   | [CORE]waystones.jar                                  | None                                     |
	| LC    | mcjtylib_ng               | 3.1.1                    | [LIBRARY]mcjtylib-1.12-3.1.1.jar                     | None                                     |
	| LC    | xnet                      | 1.7.6                    | [CORE]xnet.jar                                       | None                                     |
	| LC    | aether_legacy             | 1.12.2-v3.2              | [DIFFICULTY]aetherlegacy.jar                         | None                                     |
	| LC    | ichunutil                 | 7.1.4                    | [LIBRARY]iChunUtil-1.12.2-7.1.4.jar                  | None                                     |
	| LC    | mightyenderchicken        | 7.2.0                    | [DIFFICULTY]anthropamorphiccowmod.jar                | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | lex                       | 1.0.8                    | [LIBRARY]LibEx-1.12.2-1.0.8.jar                      | None                                     |
	| LC    | nex                       | 2.0.8                    | [DIFFICULTY]netherEX.jar                             | None                                     |
	| LC    | progressivebosses         | 1.4.1                    | [DIFFICULTY]progressive bosses.jar                   | None                                     |
	| LC    | openterraingenerator      | v6                       | [GEN]OpenTerrainGenerator.jar                        | e9f7847a78c5342af5b0a9e04e5abc0b554d69e0 |
	| LC    | biomebundle               | 5.1                      | [GEN]Biome_Bundle.jar                                | None                                     |
	| LC    | farseek                   | 2.3.1                    | [LIBRARY]Farseek-1.12-2.3.1.jar                      | None                                     |
	| LC    | streams                   | 0.4.4                    | [GEN]streams.jar                                     | None                                     |
	| LC    | worleycaves               | 1.3.0                    | [GEN]worleycaves.jar                                 | None                                     |
	| LC    | lunatriuscore             | 1.2.0.42                 | [LIBRARY]LunatriusCore-1.12.2-1.2.0.42-universal.jar | None                                     |
	| LC    | malisiscore               | 1.12.2-6.4.0             | [LIBRARY]malisiscore-1.12.2-6.4.0.jar                | None                                     |
	| LC    | placebo                   | 1.5.1                    | [LIBRARY]Placebo-1.12.2-1.5.1.jar                    | None                                     |
	| LC    | wanionlib                 | 1.12.2-2.2               | [LIBRARY]WanionLib-1.12.2-2.2.jar                    | None                                     |
	| LC    | clumps                    | 3.1.1                    | [PERF]clumps.jar                                     | None                                     |
	| LC    | badwithernocookiereloaded | 1.12.2-3.3.16            | [QOL]badwithernocookie.jar                           | None                                     |
	| LC    | comforts                  | 1.4.1.1                  | [QOL]comforts.jar                                    | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LC    | trumpetskeleton           | 1.12-1.0.2.1             | [QOL]dootskeleton.jar                                | None                                     |
	| LC    | harvest                   | 1.12-1.2.7-20            | [QOL]easyHarvest.jar                                 | None                                     |
	| LC    | jaff                      | 1.7_for_1.12             | [QOL]Few Fish.jar                                    | None                                     |
	| LC    | waila                     | 1.8.26                   | [QOL]HWYLA.jar                                       | None                                     |
	| LC    | inventorytweaks           | 1.63+release.109.220f184 | [QOL]inventoryTweaks.jar                             | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LC    | login_shield              | 1.12.2-3-g7c6e7ac        | [QOL]Login_Shield.jar                                | None                                     |
	| LC    | nmsot                     | 1.2.2-mc1.12.2           | [QOL]noMobSpawningOnTrees.jar                        | None                                     |
	| LC    | norecipebook              | 1.2.1                    | [QOL]norecipebook.jar                                | None                                     |
	| LC    | gnomed                    | 1.0.0                    | [QOL]redinfestion2thereturn.jar                      | None                                     |
	| LC    | roost                     | 1.3.0                    | [QOL]roost.jar                                       | None                                     |
	| LC    | snad                      | 1.12.1-1.7.09.16a        | [QOL]snad.jar                                        | None                                     |
	| LC    | stg                       | 1.12.2-1.2.3             | [QOL]swingthroughgrass.jar                           | None                                     |
	| LC    | toastcontrol              | 1.8.0                    | [QOL]toastControl.jar                                | None                                     |
	| LC    | llibrary                  | 1.7.14                   | [LIBRARY]llibrary-1.7.14-1.12.2.jar                  | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LC    | iceandfire                | 1.6.1                    | [TRIAL]iceandfire-1.6.1-1.12.2.jar                   | None                                     |
	| LC    | dsurround                 | 3.4.10.6                 | [QOL]DynamicSurroundings.jar                         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LC    | presets                   | 3.4.10.6                 | [QOL]DynamicSurroundings.jar                         | None                                     |
	| LC    | unidict                   | 1.12.2-2.9.2             | [LIBRARY]UniDict-1.12.2-2.9.2.jar                    | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin ([LIBRARY]malisiscore-1.12.2-6.4.0.jar)
  
LoadingPlugin ([QOL]quark.jar)
  vazkii.quark.base.asm.ClassTransformer
IvToolkit ([TRIAL]IvToolkit-1.3.3-1.12.jar)
  
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.OTGClassTransformer
CTMCorePlugin ([QOL]connectedTextureMod.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Inventory Tweaks Coremod ([QOL]inventoryTweaks.jar)
  invtweaks.forge.asm.ContainerTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-88.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
llibrary (llibrary-core-1.0.6-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.4.10.6.jar)
  org.blockartistry.DynSurround.asm.Transformer
FarseekCoreMod ([LIBRARY]Farseek-1.12-2.3.1.jar)
  farseek.core.FarseekClassTransformer
	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
	Launched Version: vivecraft-1.12.2-jrbudda-NONVR-8-r5-forge
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 417.71, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: 16x AMD Ryzen 7 2700X Eight-Core Processor 
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 24
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6.0 NVIDIA 417.71
	OpenGlRenderer: GeForce GTX 1080 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by AlexModGuy** [comment]
forge issue(googled func_99999_d). downgrade forge
