### ISSUE TITLE
Runaway Dragon

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#134]
I hoped off my dragon turned around and it flew off. (I was in creative testing dragon flying)
Had I been in survival mode and needed to get on my dragon there would have been no way to do so. Maybe anchor it to the player some how and when it does fly off (it is very cool that it still has a mind of its own when not being ridden) the player can call it back with the horn or the staff some how by clicking on a block or something.

**Comment by Alex-the-666** [comment]
Use a dragon command staff to order it to stay
