### ISSUE TITLE
Hippogryph crash when targetting I think [Ice and Fire 1.6.1-1.12.2] [Forge 14.23.5.2808]

### ISSUE THREAD

**Issue by renadi** [Alex-the-666/Ice_and_Fire#1349]
https://paste.dimdev.org/ocubavisec.mccrash

I'm not sure exactly what's happening, but if I idle in this world for any length of time (5-15 minutes) I come back to this error, I have seen hippogryphs in other worlds, but may have been using different versions of other mods.

**Comment by renadi** [comment]
as a comment, the only mod I added recently was Sky resources 2, though I feel it's unlikely that h as caused this sort of issue.

**Comment by AlexModGuy** [comment]
fixed
