### ISSUE TITLE
Dragons Skyrocketing

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#136]
This has happened twice in 2 different worlds. The first time i was walking around on a dragon in a glacier biome and I walked over a pond tried to take off and shot up into the sky with an insane amount of speed and then the game crashed. The second time in a new world I was at the base of a mountain on a fire dragon using it to dig and then all of a sudden it skyrocketed straight up. you are unable to dismount and the game will crash the only thing to do is make a new world unless you have a back up.

I got a quick pic of the y coordinate on my phone before the game crashed git hub wont let me post it
the y coordinate was 6359865

**Comment by PlatinumFox** [comment]
![iandf bug](https://cloud.githubusercontent.com/assets/23727270/23536761/1eedfc60-ff95-11e6-9638-6a89805de99c.png)

Got the photo to work 
taken on phone while game was crashing

**Comment by PlatinumFox** [comment]
I just re tested this and replicated it twice I think it may have to do with walking on water while riding the dragon.

**Comment by Alex-the-666** [comment]
I might have just fixed this... but i need more testing.

**Comment by Alex-the-666** [comment]
@PlatinumFox if this is still persistant in build 07, please re open the issue.

**Comment by PlatinumFox** [comment]
Will try to replicate again when I get off work.
