### ISSUE TITLE
Conflict with CTM causes crash

### ISSUE THREAD

**Issue by wanderingmage** [Alex-the-666/Ice_and_Fire#1362]
Any graphic enhancements cause ice and fire to crash the client Including CTM, and optifine. This is with CTM. This does not happen with a forge server.

[crash-2019-02-01_11.56.54-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/2822761/crash-2019-02-01_11.56.54-client.txt)

**Comment by Jaari** [comment]
Have you considered that the version of CTM you are using is not compatible with forge above version 2772? https://minecraft.curseforge.com/projects/ctm/files/2629306

**Comment by AlexModGuy** [comment]
issue with CTM
