### ISSUE TITLE
1.6.1 Dragon skeleton spawn underwater and bugging out

### ISSUE THREAD

**Issue by zEpiixz** [Alex-the-666/Ice_and_Fire#1363]
So apperantly some ice dragon skeletons are spawning underwater and they freak the fuck out.
I would upload a gif if i would know how but i think you can imagine what i mean.

**Comment by ghost** [comment]
can you do it? i, interested in seeing one

**Comment by zEpiixz** [comment]
i tried but my pc cant handle it. The fps are lagging more than the skeleton doing weird stuff ^^

**Comment by AlexModGuy** [comment]
fied
