### ISSUE TITLE
Siren's call makes you float

### ISSUE THREAD

**Issue by AbstractFox** [Alex-the-666/Ice_and_Fire#1371]
for some reason, you more of float rather than walk/swim.
For example, if a siren is below the player on a ledge and there is no water, the player will float down to it. Instead you should walk/jump

**Comment by GundunUkan** [comment]
Umm, they are literally pulling you. I don't see anything wrong with that.

**Comment by AbstractFox** [comment]
No, they are _attracting_ you. They sing and you are supposed to run after them because they are hypnotising you.

**Comment by AbstractFox** [comment]
they aren't using jedi mind powers to pull your body forward.

**Comment by AlexModGuy** [comment]
theyre pulling it to you
