### ISSUE TITLE
[1.6.1] Items Name Error

### ISSUE THREAD

**Issue by TheProtectedVoid** [Alex-the-666/Ice_and_Fire#1377]
All Pixies related blocks (Houses and Jars) and Deathworm Eggs appears missing names...
I've checked it in all translations, and this error still happening...

![image](https://user-images.githubusercontent.com/10207479/52442578-a33f1b00-2b0a-11e9-8d20-76b95b8bfd57.png)

**Comment by BlueWither** [comment]
#1324
