### ISSUE TITLE
Lagspikes caused by Myrmex hive mobs entrance

### ISSUE THREAD

**Issue by TheonlyTazz** [Alex-the-666/Ice_and_Fire#1379]
Using Ice and Fire Version: 1.6.1

Myrmex Hives seems to stay loaded when mobs want to pathfind but cant.
Hive have multiple entrances and are rather big, maybe related to

https://github.com/Alex-the-666/Ice_and_Fire/issues/1343

![image](https://user-images.githubusercontent.com/3908847/52513053-91dc3880-2c08-11e9-91a6-3aca67918d87.png)
![image](https://user-images.githubusercontent.com/3908847/52513064-9bfe3700-2c08-11e9-8f05-4a333a0b2701.png)
![image](https://user-images.githubusercontent.com/3908847/52513071-a15b8180-2c08-11e9-9ebb-8354c10baa07.png)

https://github.com/Vyraal1/FTB-Interactions/issues/402

**Comment by AlexModGuy** [comment]
#1449
