### ISSUE TITLE
Gorgon head's can petrify entities from Fossils

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1383]
Toys, Fossil models, and eggs, there might be more, who know?
![2019-02-10_09 54 12](https://user-images.githubusercontent.com/22555489/52528871-46ff1580-2d1b-11e9-91b5-e599bac790ab.png)
![2019-02-10_09 54 26](https://user-images.githubusercontent.com/22555489/52528872-4797ac00-2d1b-11e9-8a77-5f2f3a0ecbbb.png)
![2019-02-10_09 54 33](https://user-images.githubusercontent.com/22555489/52528873-4797ac00-2d1b-11e9-9bff-1ec833904f1b.png)

**Comment by Spinogaming** [comment]
i hope they on't fix the egg one cause that would actually be usefull for making egg fossils models for museums

**Comment by AlexModGuy** [comment]
not really sure how i could fix this, plus other players like it so I may let it remain
