### ISSUE TITLE
Myrmex queen lays eggs while still a larvae

### ISSUE THREAD

**Issue by SuspiciousMango** [Alex-the-666/Ice_and_Fire#1389]
I was working on a new build when I noticed this behavior. I put down a Myrmex queen egg and it hatched into a larvae that began laying eggs. I would come back every few minutes and notice another egg on the ground that I can only assume were laid by the larval queen. I feel like this is not intended behavior and couldn't find any other issues reporting this. If it has been reported and closed already, I can't wait for the fix! (photos for clarity)

https://imgur.com/a/p4dvk8b

**Comment by Robomnz** [comment]
im also having this issue
