### ISSUE TITLE
Stage 5 fire dragon despawned while beeing mounted

### ISSUE THREAD

**Issue by Nashor-Senpai** [Alex-the-666/Ice_and_Fire#1391]
Pretty much what the title said. I mounted my dragon and tried to fly but it started flying backwards and after a few seconds i got kicked from the mount and the dragon just despawned. Im using the latests version of the mod and I alredy tried teleporting all the nearest fire dragons to me without any luck.

**Comment by AlexModGuy** [comment]
dupe
