### ISSUE TITLE
Myrmex queens crash game

### ISSUE THREAD

**Issue by Robomnz** [Alex-the-666/Ice_and_Fire#1403]
if you spawn 5-10 of myrmex queens at once it crashes your single player game and if you have a server it will crash your server as well

**Comment by GarchompGirl** [comment]
Yep I experienced this. I thought what caused it was the Gestation config due to me setting it to 1.

**Comment by AlexModGuy** [comment]
crashlog?

**Comment by AlexModGuy** [comment]
cannot reproduce in 1.8.0
