### ISSUE TITLE
Suggestions: A collection of small ideas for the mod

### ISSUE THREAD

**Issue by SirAron111** [Alex-the-666/Ice_and_Fire#1405]
Here is a list of Ideas and tweaks I had in mind for the mod after having it in my modpack for over half a year now, by listening to player feedback and the like.

1.	Easy way to adjust what items are in the Loot table for the dragons nest chests to enable Modpack makers to make killing a dragon actually rewarding! I know it’s possible with other Mods to adjust it over various scripts and the like but wouldn’t it be easy to just have a editable list right in the options where you can add items like "minecraft:pumpkin; rarity 0" or "AweosomemodX:Item20; rarity 100" would also help servers to adjust things.

2.	Dragons rushing to their nest if they detect someone stealing from it if they are still alive!

3.	Dragons in Underground Dragon spheres shouldn’t get stuck on things in their own nest or at least have them big enough for them to actually move around a bit.

4.	**Compatibility for Dragons with dynamic trees: The Dragons always get stuck on these Trees as they cant break the Tree only the leaves. They should knock them over unless it’s a really big redwood tree.**

5.	**Option to adjust the intervals of dragon attacks: The melee attack and the fire attacks are a lot more dangerous than the bite attack since it just picks you up and you can even shift out of the attack like a mine cart. Being able to adjust it so that it can’t use the same attack 5 times would make it more challenging. Or having them fly over the player shooting fire/ice down sometimes instead of always sticking close to the player (Mowzie's Mobs Naga does a decent job at that for reference that mod generally has a good way to make combat feel fluid that would definitely suit Dragons, Cyclopes and other mobs from this mod)**

6.	Option to enable ice and fire dragon nest spawn in biomes that don’t match the dragon type (random) so it will be less problematic for players to find ice dragons on servers that have a restricted over world area and use other dimensions to get dragons to spawn in (for example aroma mining dimension enabling them to regenerate the dim folder and having new dragons spawn for new players but it only has fire dragons as it doesn’t count as cold biome.)

7.	Make the attack range of cockatrice adjustable it’s pretty hard to fight a cockatrice that’s 40 blocks away and shooting at you with it’s wither beam.

8.	Adjusting the Cyclops Structure so he can walk outside of his house and not get stuck on the door or all the bones inside when his mobgrifing is turned off!

9.	**Generally working on the Myrmex Base so they can actually move around inside by making the ground flat for better walking and only the sides and ceiling have sticking out blocks. And making the rooms a bit bigger for the big mobs like the queen not to get stuck suffocating all the time!**

10.	Add a timer to how long mobs get turned to stone from the gorgon and gorgon head. It’s just to op if it turns even bosses to stone forever or kills players instantly.

11.	Improve Ice dragons a bit to make them as cool as fire dragons (Slowness debuff just isn’t as cool as burn damage) add in frostbite debuff that does the same thing fire does just with icy effects. Having them shoot blue fire (or cold icicles and ice bombs like the fire dragon does with fire)

That’s all I got for now. I hope some of these ideas strike your fancy.

**Comment by AlexModGuy** [comment]
1. The dragons already use the vanilla loot table system.
2. no, this would make them constantly check all nearby chests and log all players nearby, making them even more lag machines. They already are alerted when a plyer takes from a tagged chest, however.
3. Sounds easy in words, probably the most difficult thing to do of any suggestion. See #1449 
4.That is an issue on their dev side. Dragons can break all wooden blocks weaker than stone/iron.
5.they already randomly choose whether to melee or ranged every time they attack
6. see suggestions tracker
7.Thats their "super power". Just dont look at them :P
8. see point 3
9.See point 3
10.nope. its supposed to be OP, its a one time item use.
11. they arent blue fire dragons. they're more unique.
