### ISSUE TITLE
Silver gear doesn't repair with OreDict Silver

### ISSUE THREAD

**Issue by DarkYuan** [Alex-the-666/Ice_and_Fire#1406]
**Tested on:**
- iceandfire-1.6.1-1.12.2

**Other relevant mods:**
- EmbersRekindled-1.12
- UniDict-1.12.2-2.9.2

Repairing Ice & Fire armor or tools on the vanilla anvil does not support Embers' silver ingot. Because of that, it also isn't supported on the Dawnstone Anvil.

**Comment by AlexModGuy** [comment]
hmm, thats odd. Silver Ingots are registered to "ingotSilver" and should be repairable with anything that matches that.
