### ISSUE TITLE
Conflict with Lycanites mods

### ISSUE THREAD

**Issue by brykkiller** [Alex-the-666/Ice_and_Fire#1407]
The problem is that some animations of mods and their parts of bodies are lost (when Ice and Fire and Lycanites mods are installed together). For example wisp, and sylph.

**Comment by BugmanBugman** [comment]
ice and fire doesn't do this because i had both of the mods and nothing happens

**Comment by BugmanBugman** [comment]
Do you have any screenshots? Sounds like an optifine problem
