### ISSUE TITLE
Levitating Dragon

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#141]
They no longer sky rocket up into the millions of blocks and make your game crash but when riding a dragon if you just add a little bit of water (walking over it) you now gently float strait up into the air. you can not control the dragon to stop it the only way to stop it is to dismount (fall) and then the dragon will slowly descend straight down.

**Comment by PlatinumFox** [comment]
only tested with fire dragon. waited 30 min for ice dragon to hatch but it did not... will test more later to see if ice dragons hatch at all.

**Comment by Alex-the-666** [comment]
fixed
