### ISSUE TITLE
Siren lures even with earplugs

### ISSUE THREAD

**Issue by Thethuthinnang** [Alex-the-666/Ice_and_Fire#1417]
In the recent update, the sirens lure me for 1~2 seconds even when I have earplugs. Each time it happened, I double-checked to make sure I had switched from my usual helmet to the earplugs, and I had. (I always do that as a precaution when I'm along the shoreline or anywhere in the ocean.) But the sky still shades pink, I see hallucinations of sirens, and I still get pulled to them for those few seconds.
(They also turned on my auto-jump, for some reason?)

**Comment by AlexModGuy** [comment]
fixed
