### ISSUE TITLE
Den Spawn 

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#142]
Don't know if this counts but i recorded the top of a dragon den spawning at y 48.
![2017-03-11_23 03 18](https://cloud.githubusercontent.com/assets/23727270/23828972/0b21b9e2-06b1-11e7-862a-91b49ae077af.png)

![2017-03-11_23 02 35](https://cloud.githubusercontent.com/assets/23727270/23828973/1540b73e-06b1-11e7-8bfc-9dda9646718e.png)

![2017-03-11_23 04 07](https://cloud.githubusercontent.com/assets/23727270/23828974/18425eec-06b1-11e7-91b0-80b5fc71c1b3.png)

**Comment by Alex-the-666** [comment]
Non Issue?  That is the intended height.
