### ISSUE TITLE
Dragon Flight Glitch? Not sure what's happening.

### ISSUE THREAD

**Issue by Thethuthinnang** [Alex-the-666/Ice_and_Fire#1423]
My dragons have several glitches, I think. I hatched both Ice and Fire dragons in the latest version of the mod, and I have one of each now that is stage 5.

- Several times now when I was flying on it, it suddenly dropped down to the ground, as though I had dismounted. (I was in creative mode, so I didn't fall to my death, thankfully.) This is happening with my ice dragon, but I haven't tested yet to see if it happens with my fire dragon.

- There seems to be a problem with it not resetting itself into a proper "staying" position after I dismount following a successful flight. It'll be up on its legs, like it's standing, even though it's not moving around. I right-click it with the dragon command staff to put it back on "staying" (I have to cycle through "wandering," as though it is already in "staying" mode), and it'll hunch down again in a proper stay. (This has happened with both ice and fire dragons.)

- Half the time that I start flying with it, the wing noise is silent, and every time this happens, the chunks around us (previously generated) won't load, and I end up flying over vacant space and my dragon disappears underneath me (although in this case, my dragon is still with me and I see it again from the mounted view when I turn it back and re-enter the chunk that we lifted off from). When the wing flap noise is there, this doesn't happen, so I'm not sure what's going on there. (This has happened with both ice and fire dragons.)

- When I turn my head one direction or another when standing next to it, it disappears for a moment, although its shadow remains. That's not such a big deal, but I thought I'd mention it, in case it's related to the rest. (This only happened with the ice dragon so far.)

For all of these, I've tried logging out, rebooting, and stuff like that. It didn't make a difference. Thank you so much for your attention and help.

**Comment by Thethuthinnang** [comment]
EDIT: I think I noticed what is happening with the sudden drop down? When I push "x" to lower us in the air, the game is sometimes dismounting me, instead. The dragon falls to the ground, and I'm left in the air (creative mode). (I haven't changed the keys at all.)

**Comment by AlexModGuy** [comment]
fixed the x error.
