### ISSUE TITLE
Dragon Bodies Dropping After Leaving Area

### ISSUE THREAD

**Issue by Watermelonbreak** [Alex-the-666/Ice_and_Fire#1429]
For whatever reason, after I kill a dragon, it completely disappear. I found the solution, which is me leaving the area first, give are take a few chunks, and then coming back to see that fresh body dropped. I don't know why the body doesn't just drop first but at least it isn't game-breaking. Still kind of annoying having to do it every time I kill a dragon.
By the way awesome mod, I absolutely love it.

**Comment by AlexModGuy** [comment]
#1447
