### ISSUE TITLE
All dragons disappearing after a certain Y level is reached.

### ISSUE THREAD

**Issue by EvoStrange** [Alex-the-666/Ice_and_Fire#1434]
After around y 160, any dragons spawned/ spawned by horn disappear. I can still hear them, and see particle effects, but the actual Dragon is invisible. Sometimes when placed by a horn, they show up for a second, but then still disappear. If you are wondering, this issue is happening on a server, and other entities don't disappear, just the dragons.

**Comment by AlexModGuy** [comment]
#1447

**Comment by AlexModGuy** [comment]
i have fixed this one
