### ISSUE TITLE
Ice Dragon can not lay egg after use dragon horn on it.

### ISSUE THREAD

**Issue by ColaLiao** [Alex-the-666/Ice_and_Fire#1435]
Ice Dragon can not lay egg after use dragon horn on it.

**Comment by EvoStrange** [comment]
Thank you to ColaLiao for responding, but I figured out the issue for anyone wondering, if your SERVER has a max flight height that is higher than your client side maximum in the config, Dragons will not render for you, alas, it is a client side issue!

**Comment by ColaLiao** [comment]
but I play single player game…
and there is no such problem with Fire Dragon
I tried many times
