### ISSUE TITLE
Crash with Foamfix

### ISSUE THREAD

**Issue by BugmanBugman** [Alex-the-666/Ice_and_Fire#1438]
https://paste.dimdev.org/xoqopaqadu.mccrash

**Comment by AlexModGuy** [comment]
>     at lucraft.mods.heroesexpansion.worldgen.spiderlab.VillageSpiderLabHouse.addComponentParts(VillageSpiderLabHouse.java:148)

this is an issue with the heroexpansion mod not checking if a block truly is a stair block or not. the only ice and fire relate dpart was that a myrmex was loading the block.
