### ISSUE TITLE
Fire dragon cubic chunks crash

### ISSUE THREAD

**Issue by uncrushedIce** [Alex-the-666/Ice_and_Fire#1442]
Although being over 100 blocks away from the dragon causing the crash, my game crashes after ~30sec whenever I´m in survival mode. Not in creative or spectator though.

https://paste.dimdev.org/ejecakoyuf.coffeescript

I love your mod!!
Cheers,
uncrushedIce

**Comment by AlexModGuy** [comment]
>	at net.minecraft.world.chunk.Chunk.handler$getEntitiesOfTypeWithinAAAB_CubicChunks$zzk000(Chunk.java:2354)

This seems to be an issue with Cubic Chunks. bring this up to their dev

**Comment by Niko-sk2x** [comment]
If someone knows how to reproduce the issue, with any mods, please let me know. I've seen this issue extremely sporadically (3 times to be exact) since about 2 years ago when initially testing buildcraft compatibility. I was never able to reproduce it, or figure out what causes it.
