### ISSUE TITLE
Dragons Sinking Through Ground Megaissue 

### ISSUE THREAD

**Issue by AlexModGuy** [Alex-the-666/Ice_and_Fire#1448]

**Comment by yqmtat** [comment]
That's really annoying me, and I thought it was that I used iced dragon sword and the ice block covering fire dragon makes it disappear upon hitting on it. I was playing single map btw.

**Comment by UznKe** [comment]
So what is the fix now? Cuz i have the same problem...

**Comment by Ale20k4** [comment]
I think that's the same issue I've reported with hippogryphs they too tend to sink in the ground
