### ISSUE TITLE
Fix point for Ja_jp

### ISSUE THREAD

**Issue by BlueWither** [Alex-the-666/Ice_and_Fire#1451]
I did not know how to use Pull-Request, so write it here.
I also made translation for next update, but I wrote it on #1145.

item.iceandfire.dragonbone_sword_fire.name=火龍の剣
item.iceandfire.dragonbone_sword_ice.name=氷龍の剣

myrmex.message.raised_reputation=このミュルメクスのコロニーとの信頼度が %d 上がり %d となった
myrmex.message.lowered_reputation=§cこのミュルメクスのコロニーとの信頼度が %d 下がり %d となった

myrmex.message.enablebreeding=繁殖を許可する
myrmex.message.disablebreeding=繁殖を不許可にする

myrmex.message.peaceful=このミュルメクスのコロニーは中立的です
myrmex.message.hostile=§cこのミュルメクスのコロニーは敵対的になりました！
myrmex.message.trade=このミュルメクスのコロニーは取引に応じています
myrmex.message.no_trade=§cこのミュルメクスのコロニーは取引に応じていません！

myrmex.message.room.misc=汎用貯蔵室 (%d, %d, %d)
myrmex.message.establishroom_misc=汎用貯蔵室を作る
myrmex.message.added_misc_room=汎用貯蔵室を追加しました(%d, %d, %d)
myrmex.message.added_enterance_bottom=入り口（下側）を追加しました(%d, %d, %d)
myrmex.message.added_enterance_surface=入り口（表面）を追加しました(%d, %d, %d)

**Comment by AlexModGuy** [comment]
could you please just send over the new ja_jp file instead of just pieces of it?

**Comment by BlueWither** [comment]
OK. I'll send you on discord
