### ISSUE TITLE
Sea Serpent head

### ISSUE THREAD

**Issue by PCAwesomeness** [Alex-the-666/Ice_and_Fire#1453]
![2019-03-16_18 05 58](https://user-images.githubusercontent.com/8507148/54482847-b20aa300-4817-11e9-9c37-b23fc37c2e4e.png)

There doesn't seem to be any bugs with the sea serpent's head, but the general model style can be fixed a bit.

Due to how low the snout is positioned, the eyes kinda disconnect midway; as well as this, the bottom of the texture that signifies the back of the mouth is visible.

I would suggest giving the sea serpent model a small tweak; raising the snout up by approximately half a pixel (do it similarly to how high the fire dragon's snout is positioned) and shallowing the head and as many segments as it takes for the model to flow nicely should work. 

![2019-03-17_13 21 58](https://user-images.githubusercontent.com/8507148/54495960-91922580-48b7-11e9-8c3d-656b551ff408.png)

![2019-03-17_13 22 00](https://user-images.githubusercontent.com/8507148/54495963-948d1600-48b7-11e9-9178-fe362e1052a7.png)

In addition to this, I'd recommend moving the lower jaw forward by a pixel (but moving the teeth back a pixel so that they don't clip through each other) and having it rotate closer to the very back, so that its mouth could open similarly to the dragons.

**Comment by AlexModGuy** [comment]
fixe
