### ISSUE TITLE
Amphiptere flying

### ISSUE THREAD

**Issue by PCAwesomeness** [Alex-the-666/Ice_and_Fire#1454]
The amphiptere flying AI is good most of the time; however, it can run into a few issues.

![2019-03-16_18 40 55](https://user-images.githubusercontent.com/8507148/54483033-fba8bd00-481a-11e9-8169-0034db1ac9f7.png)

If you spend enough time near a flying amphipter in survival, it will tilt downwards and start flying around in a downward-facing position.

As well as this, if they fly too low to the ground, they start shaking from side to side.

**Comment by PlatinumFox** [comment]
https://youtu.be/zZqZfzTjWF4

Happened to me when I shot it.

**Comment by AlexModGuy** [comment]
@PlatinumFox 
this is partially intended;

if any of you read the bestiary it says that shooting them will cause them to crash down to the ground, allowing the player to tame them.

**Comment by PlatinumFox** [comment]
@Alex-the-666  i know its intended behavior and animation but they just get stuck doing a circle and never land

**Comment by PlatinumFox** [comment]
Samoja from discord pointed out that the arrow kept flying it went right thru the amphitere. maybe that has something to do with it

**Comment by AlexModGuy** [comment]
dupe #1656
