### ISSUE TITLE
Sea Serpents are WAYYYY to LOUD

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#1456]
My master volume is at 25% and then my Hostile mod volume is also turned down to 25% and they are SUPER loud. Almost ear raping-ly loud. Specifically the water blast sound but they are just way to loud overall.

**Comment by BlueWither** [comment]
Sea serpents are not monsters, but animals.
So you should turn down animals voice

**Comment by AlexModGuy** [comment]
not an issue
