### ISSUE TITLE
Ice Dragon stands(?) after flying (not a proper "stay")

### ISSUE THREAD

**Issue by Thethuthinnang** [Alex-the-666/Ice_and_Fire#1465]
I had this issue with the last version, and it is still happening in the latest version (1.7). After flying, my stage 3~4 (didn't go up to 5) Ice Dragon didn't settle back into a "stay" when we landed but remained in a standing position. The first time, it started to walk, and the second time, it just stood there. Both times, I think it was technically in a "stay" but I had to cycle through with the command staff before it crouched back down into a proper stay.

**Comment by AlexModGuy** [comment]
fixed in 1.8.0
