### ISSUE TITLE
stuck on tamed Amphithere flying in circles: can't land or dismount

### ISSUE THREAD

**Issue by Thethuthinnang** [Alex-the-666/Ice_and_Fire#1467]
I cannot get off my Amphithere. Shift clicking, x-clicking... nothing works. It keeps flying in a small circular motion, up and down, even when I'm not touching any keys. I switched between creative and survival modes, but I still cannot get off, and it won't land or stop flying in circles.

EDIT: I rebooted MC before I posted this, and I was dismounted when the world reloaded, with my Amphithere in "follow" mode.

**Comment by AlexModGuy** [comment]
fixed
