### ISSUE TITLE
Disabled Deathworms Still Spawn

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#1470]
Hello! I love the Ice & Fire mod, but I dislike the deathworms. I saw that they can be disabled in the config, so I gave that a try. Sadly, deathworms still spawn in my worlds. I apologize if this is an error on my part, but I thought I'd bring it to your attention. I also apologize if there's already another issue about this (I looked through the list + looked in the related issues suggestion, but I found none similar). If needed, I can try to provide the config file, but I may need a little instruction (I found a file called IceAndFireConfig.class , but I wasn't sure if this is the right one..). Anyways, any help or solution is appreciated! Thank you for reading!

![image1 (1)](https://user-images.githubusercontent.com/41302383/54578674-027c2f00-49d7-11e9-93bf-c3917bd46889.jpeg)

![2019-03-18_23 22 42](https://user-images.githubusercontent.com/41302383/54578695-11fb7800-49d7-11e9-8701-8fb3f41da7f4.png)

![2019-03-18_23 22 51](https://user-images.githubusercontent.com/41302383/54578700-16279580-49d7-11e9-9657-9023fe7f14c7.png)

**Comment by gra010603** [comment]
Actually, I'm sorry. I want to delete this entire issue. It's probably my fault.

**Comment by ghost** [comment]
I shouldn't have written this. It's probably my fault. Could you delete this post?
