### ISSUE TITLE
Sea Serpent causes crash

### ISSUE THREAD

**Issue by BlueWither** [Alex-the-666/Ice_and_Fire#1471]
---- Minecraft Crash Report ----
// There are four lights!

Time: 2019-03-19 20:54:27 JST
Description: Ticking entity

java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
    at java.util.ArrayList$Itr.next(Unknown Source)
    at net.minecraft.world.chunk.Chunk.getEntitiesOfTypeWithinAABB(Chunk.java:934)
    at net.minecraft.world.World.getEntitiesWithinAABB(World.java:3080)
    at net.minecraft.entity.ai.EntityAINearestAttackableTarget.shouldExecute(SourceFile:91)
    at com.github.alexthe666.iceandfire.entity.ai.FlyingAITarget.shouldExecute(FlyingAITarget.java:34)
    at net.minecraft.entity.ai.EntityAITasks.onUpdateTasks(SourceFile:94)
    at net.minecraft.entity.EntityLiving.updateEntityActionState(EntityLiving.java:885)
    at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2359)
    at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:678)
    at net.minecraft.entity.EntityAgeable.onLivingUpdate(EntityAgeable.java:178)
    at net.minecraft.entity.passive.EntityAnimal.onLivingUpdate(SourceFile:43)
    at com.github.alexthe666.iceandfire.entity.EntitySeaSerpent.onLivingUpdate(EntitySeaSerpent.java:353)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:377)
    at com.github.alexthe666.iceandfire.entity.EntitySeaSerpent.onUpdate(EntitySeaSerpent.java:205)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1955)
    at net.minecraft.world.World.redirect$updateEntity$zcg000(World.java:4117)
    at net.minecraft.world.World.updateEntities(World.java:1759)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: iceandfire:seaserpent (com.github.alexthe666.iceandfire.entity.EntitySeaSerpent)
  Entity ID: 15265
  Entity Name: Sea Serpent
  Entity's Exact location: -1056.48, 58.87, -1361.42
  Entity's Block location: World: (-1057,58,-1362), Chunk: (at 15,3,14 in -67,-86; contains blocks -1072,0,-1376 to -1057,255,-1361), Region: (-3,-3; contains chunks -96,-96 to -65,-65, blocks -1536,0,-1536 to -1025,255,-1025)
  Entity's Momentum: 0.13, 0.05, -0.10
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {HurtByTimestamp:0,Attributes:[{Base:236.34777545928955d,Name:"generic.maxHealth"},{Base:0.0d,Name:"generic.knockbackResistance"},{Base:0.25d,Name:"generic.movementSpeed"},{Base:3.0d,Name:"generic.armor"},{Base:0.0d,Name:"generic.armorToughness"},{Base:1.0d,Name:"forge.swimSpeed"},{Base:64.0d,Name:"generic.followRange"},{Base:47.26955509185791d,Name:"generic.attackDamage"}],Invulnerable:0b,FallFlying:0b,ForcedAge:0,PortalCooldown:0,AbsorptionAmount:0.0f,AttackDecision:1b,FallDistance:0.0f,InLove:0,DeathTime:0s,Ancient:1b,ForgeCaps:{"dsurround:emojidata":{as:0,es:0,et:0},"llibrary:extendedentitydatacapability":{"mm:living":{frozenYaw:0.0f,freezeProgress:0.0f,frozenPitch:0.0f,prevHasAI:0b,frozenYawHead:0.0f,frozenEntityID:-1,frozenLimbSwingAmount:0.0f,frozenRenderYawOffset:0.0f,frozenSwingProgress:0.0f},"Ice And Fire - Chicken Property Tracker":{TimeUntilNextEgg:1},"Ice And Fire - Siren Property Tracker":{CharmedBySiren:0b,SirenID:0},"Ice And Fire - Frozen Property Tracker":{TicksUntilUnfrozen:0,IsFrozen:0b},"Fossils - Mammal Tracker":{EmbryoProgress:0,Pregnant:0b,Embryo:0},"Ice And Fire - Stone Property Tracker":{StoneBreakLvl:0,TurnedToStone:0b}}},HandDropChances:[0.085f,0.085f],PersistenceRequired:0b,JumpingOutOfWater:0b,Age:0,Motion:[0.1309168556648347d,0.051181895934747194d,-0.10058773494842271d],Leashed:0b,UUIDLeast:-7768634622310474464L,Health:236.34778f,VFAABB:[-1058.454303690746d,58.87199514371319d,-1363.387287812323d,-1054.5151740997578d,62.81112473470135d,-1359.4481582213348d],LeftHanded:0b,Scale:7.878259f,Air:300s,OnGround:0b,Dimension:0,Rotation:[-127.28671f,1.023638f],UpdateBlocked:0b,HandItems:[{},{}],Variant:2,ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],UUIDMost:8091244826017286743L,Pos:[-1056.484738895252d,58.87199514371319d,-1361.4177230168289d],Fire:0s,ArmorItems:[{},{},{},{}],TicksSinceRoar:681,CanPickUpLoot:0b,Breathing:0b,HurtTime:0s}

-- Affected level --
  Level name: 新規ワールドへ のコピー のコピー のコピー のコピー のコピ
  All players: 1 total; [EntityPlayerMP['Nonname114'/528, l='新規ワールドへ のコピー のコピー のコピー のコピー のコピ', x=-1051.99, y=62.32, z=-1348.56]]
  Chunk stats: ServerChunkCache: 210 Drop: 0
  Level seed: 6821789961232094564
  Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
  Level generator options: {"diamondSize":8,"lapisCenterHeight":16,"lavaLakeChance":80,"redstoneMaxHeight":16,"diamondMaxHeight":16,"coalMaxHeight":128,"coalMinHeight":0,"seaLevel":63,"graniteCount":10,"riverSize":4,"gravelMinHeight":0,"graniteSize":33,"redstoneSize":8,"fixedBiome":-1,"waterLakeChance":4,"dioriteMinHeight":0,"andesiteCount":10,"graniteMaxHeight":80,"redstoneMinHeight":0,"lapisSize":7,"dirtCount":10,"ironMinHeight":0,"dioriteMaxHeight":80,"coalCount":20,"gravelCount":8,"coalSize":17,"gravelSize":33,"ironMaxHeight":64,"lapisSpread":16,"dioriteCount":10,"andesiteSize":33,"biomeSize":4,"graniteMinHeight":0,"goldCount":2,"diamondCount":1,"dirtSize":33,"gravelMaxHeight":256,"goldSize":9,"ironCount":20,"diamondMinHeight":0,"ironSize":9,"redstoneCount":8,"andesiteMinHeight":0,"dioriteSize":33,"goldMaxHeight":32,"dungeonChance":8,"andesiteMaxHeight":80,"dirtMinHeight":0,"lapisCount":1,"goldMinHeight":0,"dirtMaxHeight":256,"lowerLimitScale":512.0,"biomeDepthOffset":0.0,"upperLimitScale":512.0,"heightScale":684.412,"biomeScaleWeight":1.0,"biomeDepthWeight":1.0,"mainNoiseScaleZ":80.0,"mainNoiseScaleY":160.0,"depthNoiseScaleX":200.0,"mainNoiseScaleX":80.0,"baseSize":8.5,"depthNoiseScaleZ":200.0,"stretchY":12.0,"depthNoiseScaleExponent":0.5,"biomeScaleOffset":0.0,"coordinateScale":684.412,"useStrongholds":true,"useMineShafts":true,"useTemples":true,"useLavaOceans":false,"useCaves":true,"useWaterLakes":true,"useLavaLakes":true,"useMonuments":true,"useRavines":true,"useDungeons":true,"useVillages":true}
  Level spawn location: World: (54,64,178), Chunk: (at 6,4,2 in 3,11; contains blocks 48,0,176 to 63,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 12156 game time, 12156 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 62859 (now: false), thunder time: 56116 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 1.8.0_151, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 2105278160 bytes (2007 MB) / 4277534720 bytes (4079 MB) up to 4277534720 bytes (4079 MB)
  JVM Flags: 8 total; -Xms4G -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:MetaspaceSize=256M -XX:MaxMetaspaceSize=256M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
  FML: MCP 9.42 Powered by Forge 14.23.5.2796 Optifine OptiFine_1.12.2_HD_U_E3 66 mods loaded, 66 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                       | Version            | Source                                          | Signature                                |
       |:------ |:------------------------ |:------------------ |:----------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                | 1.12.2             | minecraft.jar                                   | None                                     |
       | LCHIJA | mcp                      | 9.42               | minecraft.jar                                   | None                                     |
       | LCHIJA | FML                      | 8.0.99.99          | forge-1.12.2-14.23.5.2796.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                    | 14.23.5.2796       | forge-1.12.2-14.23.5.2796.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | unicodefontextensioncore | 1.12.2-2.6         | minecraft.jar                                   | None                                     |
       | LCHIJA | foamfixcore              | 7.7.4              | minecraft.jar                                   | None                                     |
       | LCHIJA | dsurroundcore            |                    | minecraft.jar                                   | None                                     |
       | LCHIJA | gottagofast              | 1.1                | gottagofast-1.1.jar                             | None                                     |
       | LCHIJA | unicodefontextension     | 1.12.2-2.7         | UnicodeFontExtension-1.12.2-2.7.jar             | None                                     |
       | LCHIJA | advancedtools            | 1.12-2.2.2         | AdvancedTools-1.12-2.2.2.jar                    | None                                     |
       | LCHIJA | biomesoplenty            | 7.0.1.2425         | BiomesOPlenty-1.12.2-7.0.1.2425-universal.jar   | None                                     |
       | LCHIJA | craftstudioapi           | 1.0.0              | CraftStudio-1.0.0.93-mc1.12-alpha.jar           | None                                     |
       | LCHIJA | animania                 | 1.6.2              | animania-1.12.2-1.6.2.jar                       | None                                     |
       | LCHIJA | jei                      | 4.8.0.108          | jei_1.12.2-4.8.0.108.jar                        | None                                     |
       | LCHIJA | quark                    | r1.5-144           | Quark-r1.5-144.jar                              | None                                     |
       | LCHIJA | autoreglib               | 1.3-24             | AutoRegLib-1.3-24.jar                           | None                                     |
       | LCHIJA | baubles                  | 1.5.2              | Baubles-1.12-1.5.2.zip                          | None                                     |
       | LCHIJA | betteranimals            | 3.1                | betteranimals-4.0.jar                           | None                                     |
       | LCHIJA | betterbuilderswands      | 0.12.0             | BetterBuildersWands-1.12-0.12.0.251+d6c4d93.jar | None                                     |
       | LCHIJA | blockcraftery            | 1.12.2-1.1.0       | blockcraftery-1.12.2-1.1.0.jar                  | None                                     |
       | LCHIJA | bookshelf                | 2.3.574            | Bookshelf-1.12.2-2.3.574.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | caliper                  | 1.1.41             | Caliper-1.12.2-1.1.41.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | ctm                      | MC1.12.2-0.3.3.22  | CTM-MC1.12.2-0.3.3.22.jar                       | None                                     |
       | LCHIJA | chisel                   | MC1.12.2-0.2.1.35  | Chisel-MC1.12.2-0.2.1.35.jar                    | None                                     |
       | LCHIJA | comforts                 | 1.4.1.1            | comforts-1.12.2-1.4.1.1.jar                     | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHIJA | cosmeticarmorreworked    | 1.12.2-v1          | CosmeticArmorReworked-1.12.2-v1.jar             | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCHIJA | dynamictrees             | 1.12.2-0.9.4       | DynamicTrees-1.12.2-0.9.4.jar                   | None                                     |
       | LCHIJA | dynamictreesbop          | 1.12.2-1.4.1e      | DynamicTreesBOP-1.12.2-1.4.1e.jar               | None                                     |
       | LCHIJA | ebwizardry               | 4.1.2              | Electroblob's+Wizardry+-+4.1.2+-+MC+1.12.2.jar  | None                                     |
       | LCHIJA | familiarfauna            | 1.0.10             | FamiliarFauna-1.12.2-1.0.10.jar                 | None                                     |
       | LCHIJA | fastleafdecay            | v14                | FastLeafDecay-v14.jar                           | None                                     |
       | LCHIJA | flying_things            | 1.5.1              | flying_things-1.5.1-1.12.jar                    | None                                     |
       | LCHIJA | foamfix                  | 0.10.3-1.12.2      | foamfix-0.10.3-1.12.2.jar                       | None                                     |
       | LCHIJA | forgelin                 | 1.7.4              | Forgelin-1.7.4.jar                              | None                                     |
       | LCHIJA | llibrary                 | 1.7.17             | llibrary-1.7.17-1.12.2.jar                      | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | fossil                   | 8.0.0              | fossilsarcheology-8.0.0.jar                     | None                                     |
       | LCHIJA | iceandfire               | 1.7.0              | iceandfire-1.7.0-1.12.2.jar                     | None                                     |
       | LCHIJA | ironbackpacks            | 1.12.2-3.0.1-2     | IronBackpacks-1.12.2-3.0.1-2.jar                | None                                     |
       | LCHIJA | jaff                     | 1.7_for_1.12       | JustAFewFish-1.7_for_1.12.jar                   | None                                     |
       | LCHIJA | lootbags                 | 2.5.7              | LootBags-1.12.2-2.5.7.jar                       | None                                     |
       | LCHIJA | mantle                   | 1.12-1.3.3.42      | Mantle-1.12-1.3.3.42.jar                        | None                                     |
       | LCHIJA | mknutils                 | 3.2.0              | MKNUtils-mc1.12.2-3.2.0.jar                     | None                                     |
       | LCHIJA | testdummy                | 1.12               | MmmMmmMmmMmm-1.12-1.14.jar                      | None                                     |
       | LCHIJA | mobbattle                | 2.0.2[1.12]        | Mob Battle Mod 2.0.2 [1.12].jar                 | None                                     |
       | LCHIJA | moreplayermodels         | 1.12.2             | MorePlayerModels_1.12.2(18jan18).zip            | None                                     |
       | LCHIJA | mowziesmobs              | 1.5.3              | mowziesmobs-1.5.3.jar                           | None                                     |
       | LCHIJA | naturescompass           | 1.5.0              | NaturesCompass-1.12.2-1.5.0.jar                 | None                                     |
       | LCHIJA | recipehandler            | 0.13               | NoMoreRecipeConflict-0.13(1.12.2).jar           | None                                     |
       | LCHIJA | patchouli                | 1.0-16             | Patchouli-1.0-16.jar                            | None                                     |
       | LCHIJA | placeableitems           | 3.2                | placeableitems-3.2.jar                          | None                                     |
       | LCHIJA | puddles                  | 1.1                | Puddles-1.1.jar                                 | None                                     |
       | LCHIJA | quarkoddities            | 1                  | QuarkOddities-1.12.2.jar                        | None                                     |
       | LCHIJA | spartanweaponry          | beta 1.2.3         | SpartanWeaponry-1.12.2-beta-1.2.3.jar           | None                                     |
       | LCHIJA | spartanfire              | 0.05               | spartanfire-0.05.jar                            | None                                     |
       | LCHIJA | spartanshields           | 1.4.1              | SpartanShields-1.12.2-1.4.1.jar                 | None                                     |
       | LCHIJA | specialmobs              | 1.0.0_for_mc1.12.2 | specialmobs-1.0.0_for_mc1.12.2.jar              | None                                     |
       | LCHIJA | tconstruct               | 1.12.2-2.12.0.115  | TConstruct-1.12.2-2.12.0.115.jar                | None                                     |
       | LCHIJA | torohealthmod            | 1.12.2-11          | torohealth-1.12.2-11.jar                        | None                                     |
       | LCHIJA | tumbleweed               | 1.11-0.4.5         | tumbleweed-1.11-0.4.5.jar                       | None                                     |
       | LCHIJA | universalbestiary        | 1.1.0              | universalbestiary-1.12.2-1.1.0.jar              | None                                     |
       | LCHIJA | vanillafix               | 1.0.10-SNAPSHOT    | VanillaFix-1.0.10-98.jar                        | None                                     |
       | LCHIJA | waddles                  | 0.6.0              | Waddles-1.12.2-0.6.0.jar                        | None                                     |
       | LCHIJA | yoyos                    | 1.12.2-1.2.0.18    | yoyos_1.12.2-1.2.0.18.jar                       | None                                     |
       | LCHIJA | dsurround                | 3.4.10.5           | DynamicSurroundings-1.12.2-3.4.10.5.jar         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | presets                  | 3.4.10.5           | DynamicSurroundings-1.12.2-3.4.10.5.jar         | None                                     |
       | LCHIJA | mysticallib              | 1.12.2-1.0.0       | mysticallib-1.12.2-1.0.0.jar                    | None                                     |
  Loaded coremods (and transformers): llibrary (llibrary-core-1.0.10-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-98.jar)
                                        
                                      ForgelinPlugin (Forgelin-1.7.4.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      LoadingPlugin (Quark-r1.5-144.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      CorePlugin (UnicodeFontExtension-1.12.2-2.7.jar)
                                        bre.ufex.asm.Transformer
                                      DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.4.10.5.jar)
                                        org.blockartistry.DynSurround.asm.Transformer
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      GottaGoFastLoader (gottagofast-1.1.jar)
                                        com.thiakil.gottagofast.coremod.GottaGoFastASMTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
  Suspected Mods: Ice and Fire (iceandfire)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [EntityPlayerMP['Nonname114'/528, l='新規ワールドへ のコピー のコピー のコピー のコピー のコピ', x=-1051.99, y=62.32, z=-1348.56]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'

**Comment by AlexModGuy** [comment]
fixed
