### ISSUE TITLE
Request ice and fire dimensional spawning

### ISSUE THREAD

**Issue by EternalOne11** [Alex-the-666/Ice_and_Fire#1475]
Can you make it so that by default ice and fire mobs only spawn in the overworld. And the player must add dimensions that they want them to spawn in the config.

**Comment by SokyranTheDragon** [comment]
You could just disable the blacklist, which is going to enable dimension whitelist instead.

I know that it's not as convenient as having it set up like that by default, but at least it's better than a few other mods I've seen that support blacklist only.

**Comment by AlexModGuy** [comment]
^^
