### ISSUE TITLE
Ice Dragons

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#1476]
Tamed Ice Dragon breath freeze turns mobs and players into ice cubes, however, they can still move and attack. May or may not be a bug, but the ice breath damage is embarrassingly low, took a good 45 seconds to kill a non-armored player.

**Comment by yqmtat** [comment]
that's a hardcore issue😂, i think it is intended, if you check fandom wiki of iaf you are suggested to get speed buff otherwise you can be bitten, grabbed and shaken to death.
