### ISSUE TITLE
Troll health regens during combat

### ISSUE THREAD

**Issue by Thethuthinnang** [Alex-the-666/Ice_and_Fire#1481]
I don't remember seeing this before. Is it supposed to happen and I've just never noticed before? (I usually use ice or fire swords to fight them, but this time, I was using a vanilla iron sword.)

**Comment by AlexModGuy** [comment]
intended. trolls have regen.

**Comment by Thethuthinnang** [comment]
Thanks for the reply and for the clarification. Not sure who does the wiki, but the Troll page should probably be updated to reflect this in the "Combat" section.
