### ISSUE TITLE
Amphithere needs to be smaller and more agile to prevent getting stuck and suffocation.

### ISSUE THREAD

**Issue by SirAron111** [Alex-the-666/Ice_and_Fire#1489]
Always getting stuck models are to big make them a bit smaller and smarter when fling around.
![2019-03-24_16 06 56](https://user-images.githubusercontent.com/39855956/54881324-0bde1f00-4e4f-11e9-87f5-00c9f806517a.png)

**Comment by SirAron111** [comment]
its like the 10 time i see this happen now XD

**Comment by BlueWither** [comment]
It would be nice if they would not suffocate in the block, like a dragon.

**Comment by ghost** [comment]
I have managed to reproduce this issue.

**Comment by AlexModGuy** [comment]
dupe #1656
