### ISSUE TITLE
[Suggestion]Sneaking Myrmex Sentinel

### ISSUE THREAD

**Issue by BlueWither** [Alex-the-666/Ice_and_Fire#1492]
Perhaps the reason why Myrmex Sentinel can not leave the colony is that it is using the same AI as other Myrmex, even though it is taller than the other Myrmex.
Currently, Royals can leave the colony because they are the same height as workers and soldiers.
As a simple solution, I can raise two.
One is that when Myrmex Sentinel is at a low ceiling, it will be temporarily crouched and change the collision detection like a Soldier.
The other is to make collision detection the same as a soldier.

**Comment by AlexModGuy** [comment]
not for suggestions bugs only
