### ISSUE TITLE
Game freezing after being grabbed by any mob

### ISSUE THREAD

**Issue by blokmasta** [Alex-the-666/Ice_and_Fire#1494]
If I dismount the jaws of a dragon or cyclops the game freezes. TPS goes to 0. The framerate is still ok but no mobs are moving and nothing can break.

**Comment by BugmanBugman** [comment]
Sounds like a RAM problem, what are your specs?

**Comment by blokmasta** [comment]
12 GB of ram, 3.5 ghz 8 core processor, 500GB SSD

**Comment by AlexModGuy** [comment]
grabbing behavior has changed
