### ISSUE TITLE
How do I disable dragon spawns in certain dimensions? 

### ISSUE THREAD

**Issue by AnnaTheKitty** [Alex-the-666/Ice_and_Fire#1495]
I have both Twilight Forest and Ice and Fire, when going around the world testing out my modpack I made I saw a dragon spawned directly next to/on a boss area. Is there a way for me to be able to disable the spawns of dragons in certain dimenssions because I rather not have my friends deal with this problem.

Screenshots:
![2019-03-28_19 18 00](https://user-images.githubusercontent.com/48998087/55199425-6a2d3980-5190-11e9-8270-59e745b3bcc6.png)
![2019-03-28_19 33 05](https://user-images.githubusercontent.com/48998087/55199427-6a2d3980-5190-11e9-9b96-0f7c0c4bfbb7.png)
![2019-03-28_19 33 19](https://user-images.githubusercontent.com/48998087/55199429-6a2d3980-5190-11e9-92fa-1ba5ea8b84d8.png)
![2019-03-28_19 33 27](https://user-images.githubusercontent.com/48998087/55199430-6a2d3980-5190-11e9-9131-8bb9ac18f288.png)

**Comment by AlexModGuy** [comment]
see dragonBlacklistedDimensions and dragonWhitelistedDimensions in the config.
