### ISSUE TITLE
dragon bone flute does not work right

### ISSUE THREAD

**Issue by sbcu** [Alex-the-666/Ice_and_Fire#1496]
so my pet goes flying and I use the flute but then the pet does not seam to have the ability to fly by itself.

**Comment by AlexModGuy** [comment]
what do you mean?

**Comment by sbcu** [comment]
so I will leave my Amphithere in wander mod with it homed near me and it will circle around the home point in the air and I use the flute and it comes down and then a bit latter I try to get it back up in the air by it self I can mount and fly it just fine but alone it can not fly I also tried this with a hippogriff.
