### ISSUE TITLE
Config option for min distance between structures?

### ISSUE THREAD

**Issue by Thethuthinnang** [Alex-the-666/Ice_and_Fire#1498]
Would it be possible to add/configure minimum distance between Ice and Fire structures? Dragon lairs as well as dragon roosts sometimes generate in an overlapping fashion, and structures like the Cyclops lair and Gorgon temple often seem to generate in pairs or small clusters. (Also things like the snow villages.) Sometimes, you'll get a single vanilla village with three fire dragon roosts encircling it. I don't think it's a question of the rate at which they spawn (I usually dial it down from the default config to make things a little rarer), but if there could be a way to adjust how close various Ice and Fire structures (or even just identical ones, like all roosts or all temples) are to each other, that would be a nice option to have.

Here's an example of what I mean:
![2019-03-30_18 15 58 ice and fire structure generation](https://user-images.githubusercontent.com/47260138/55282933-bb6a3400-531c-11e9-8584-e7d0defbcb80.png)

**Comment by AlexModGuy** [comment]
dupe #1069
