### ISSUE TITLE
fire dragon in cold biome in release 

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#150]
Release version Flying around fire dragon spawned in cold biome
![2017-04-01_22 38 40](https://cloud.githubusercontent.com/assets/23727270/24584397/2eae95b6-173b-11e7-8f7d-a66fb045397c.png)
![2017-04-01_22 38 45](https://cloud.githubusercontent.com/assets/23727270/24584398/2f8d229a-173b-11e7-8be4-0990b6b1464c.png)
![2017-04-01_22 38 50](https://cloud.githubusercontent.com/assets/23727270/24584399/30539678-173b-11e7-98a2-74883e413725.png)

**Comment by Alex-the-666** [comment]
hmmm ok

**Comment by Alex-the-666** [comment]
What biome is this
