### ISSUE TITLE
Requesting Hook for Apathetic Mobs

### ISSUE THREAD

**Issue by whizzball1** [Alex-the-666/Ice_and_Fire#1501]
Hello!

I'm writing a mod for peaceful mode players that need mob drops or are required to kill mobs in modpacks. The mod works by making hostile mobs ignore players.

I'm currently looking through your code to find special cases I need to work with, and I'd prefer to use methods that don't require tick-by-tick checks. I see in EntityDragonBase that you only setAttackTarget to players in one method. I plan to use LivingSetAttackTargetEvent to set your dragons' attack target to null when this occurs. Will this work? Are there any other ways in which your dragon attacks except using its attackTarget?

Are there any special cases for other bosses that I will have to worry about?

Thanks!

**Comment by AlexModGuy** [comment]
LivingSetAttackTargetEvent should already fire through that so theres no need for a hook.
