### ISSUE TITLE
"Bioluminescence" sounds a little bit weird

### ISSUE THREAD

**Issue by yqmtat** [Alex-the-666/Ice_and_Fire#1504]
I'm a life science student, and the word bioluminescence means the production and emission of light by a living organism (defined by wikipedia)
honestly, it is strange to pick up bunches of light, not to mention we use this word to generalize about a phenomenon rather than some kinds of substance, and I think luciferin or fluorescein could be a better appellation of this sticky-texture-ed substance.

**Comment by AlexModGuy** [comment]
not an issue
