### ISSUE TITLE
the myrmex sound effect sounds creepy to me.

### ISSUE THREAD

**Issue by yqmtat** [Alex-the-666/Ice_and_Fire#1505]
I think you did a great job on rendering a terror atmosphere, I'm really impressed and feeling overwhelmed when entering a hive, which makes me trembling, stunned and horrified.(ツ)

**Comment by Thethuthinnang** [comment]
I agree, it sounds amazing. Particularly terrifying for me is the sound they make when they grab you to attack. It's like something out of the movie _Alien_. D:
