### ISSUE TITLE
bestiary lang

### ISSUE THREAD

**Issue by llronaldoll** [Alex-the-666/Ice_and_Fire#1506]
the language file is not translating the bestiary!

**Comment by TheProtectedVoid** [comment]
Are you using the latest version?

**Comment by llronaldoll** [comment]
iceandfire-1.7.1-1.12.2

**Comment by TheProtectedVoid** [comment]
I've tested and worked perfectly...

**Comment by NightStr** [comment]
Good day, how are you test it? I try making the russian translate, i put a localization file into directory `src/main/resources/assets/iceandfire/lang/bestiary/ru_RU/` already compiled mod and in the bestiary still was be the english language. 

I try change in game locale and nothing, none of the existing translations it does not work on.

Encoding the file of a translate is utf8. What i do wrong? Maybe i need recompile mod before translate is going work. or something like this?

**Comment by f-sage** [comment]
none of the bestiary translations work!! i think the issue might be in the writeFromTxt() function in GuiBestiary.java
i'm using iceandfire-1.7.1-1.12.2

**Comment by AlexModGuy** [comment]
this is fixed, but the translations(specifically russian and japanese) were not encoded in UTF-8.

If any are interested in redoing it in UTF-8 I would happily merge your PR.

The portuguese translation was made in UTF-8 and it works fine now.
