### ISSUE TITLE
INCOMPATABILITY WITH AE2 - Extra Brackets in item JSONs

### ISSUE THREAD

**Issue by rcistano** [Alex-the-666/Ice_and_Fire#151]
~I was unable to tame and/or ride the dragons that I spawned in.~

When are the items and blocks going to have textures?

**Comment by PlatinumFox** [comment]
What stage was your dragon(click on it and see what day it is) and you might want to elaborate more on the items and blocks having textures?

**Comment by rcistano** [comment]
When I spawned it in, it looks as though it would be an adult dragon. When I right click on it, it does nothing. Half of the items/blocks are black and pink boxes, meaning there is no texture to it.

**Comment by PlatinumFox** [comment]
the dragon you are spawning in is not a tame one u must hatch it from an egg and grow it

**Comment by rcistano** [comment]
How does one hatch it?

**Comment by Alex-the-666** [comment]
- Dragon taming is not a thing. You must learn how to hatch them from the bestiary.

-But this texture thing is. Im not having missing textures, and neither are a lot of people. send pictures.

**Comment by rcistano** [comment]
Pictures are attached.

![2017-04-02_10 03 59](https://cloud.githubusercontent.com/assets/13685776/24589273/b5ef8a16-178c-11e7-99f9-ceb05907ae8a.png)
![2017-04-02_10 04 25](https://cloud.githubusercontent.com/assets/13685776/24589274/b5f0a022-178c-11e7-8cbd-ba984dc4e155.png)
![2017-04-02_10 04 42](https://cloud.githubusercontent.com/assets/13685776/24589275/b5f109e0-178c-11e7-9f85-c00132ddfab3.png)
![2017-04-02_10 04 54](https://cloud.githubusercontent.com/assets/13685776/24589276/b5f25a84-178c-11e7-9663-2d3d1b71ec86.png)

**Comment by rcistano** [comment]
So tell me, why is no one else having this problem?

**Comment by Alex-the-666** [comment]
Because you must be using mods that are creating conflicts.

Uninstall all other mods but ice and fire and llibrary and slowly add mods back to see which one causes this.

**Comment by thephoenixlodge** [comment]
I'm having the same issue @rcistano, if you post your modlist I can compare it to mine and use that as a starting point to figuring out what may be causing it

**Comment by thephoenixlodge** [comment]
Well, I've found what mod is causing it. Based on the above screenshots I was able to see AE2 and ExtraUtils were installed, so I figured I may as well try those, and as it turns out, it's being installed alongside AE2 that does it.

**Comment by SOL3675** [comment]
I had same issue but after I added Optifine, it correctly rendered.
That's weird...
![2017-04-11_15 32 38](https://cloud.githubusercontent.com/assets/16431933/24895627/627ecbfc-1ecc-11e7-897e-8472056daea6.png)

Mod List here.
https://pastebin.com/AXN2Fy1S

**Comment by itinerant-coder** [comment]
I'm running a mod pack with this mod and was trying with AE2 (Switched to Refined Storage).

The issue was with AE2 enabling strict JSON parsing and some of the JSON files for this mod having extraneous closed brackets at the end of the files.

For example, https://github.com/Alex-the-666/Ice_and_Fire/blob/dd6344e0439c17509cb8975f43ed08c031cf98e3/src/main/resources/assets/iceandfire/models/item/dragonarmor_iron_tail.json

Has two extra '}' characters as of the writing of this comment.

AE2 can fix this by not enabling strict JSON parsing or this mod could fix it by going through each JSON file and cleaning up the formatting, and users can work around this by switching to Refined Storage from AE2.

**Comment by runescapejon** [comment]
Hello! can you backport this fix to 1.10.2 ? or if you don't support 1.10.2 anymore can you guide me on where is the fix within your commit so i can be able to apply that myself 
thanks!

EDIT: nvm i got it
