### ISSUE TITLE
Ampthithere stuck too much

### ISSUE THREAD

**Issue by BlueWither** [Alex-the-666/Ice_and_Fire#1518]
![2019-04-06_12 18 48](https://user-images.githubusercontent.com/34153394/55664534-71c4a080-586a-11e9-9921-ac207c64a193.png)
![2019-04-06_12 20 19](https://user-images.githubusercontent.com/34153394/55664536-7c7f3580-586a-11e9-8e81-599eed51651a.png)
They should turn back when they hit blocks.
It is also good to change hitbox...

**Comment by AlexModGuy** [comment]
dupe #1656
