### ISSUE TITLE
Compatibility issues with The Midnight Mod

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#1519]
1. There is no way to turn off pixies spawning in another dimension. Bad mobs does not work on them. I think it may have something to do with their huts. (Ive also seen Stymph birds spawn in The Midnight and was unsuccessful at getting them out of the dimension as well).
![Pixies in the Dark](https://user-images.githubusercontent.com/23727270/55665837-f932f500-5813-11e9-9bca-62d313a9e9e4.png)

2. Video explains it...
https://youtu.be/HzBdzWEt5-o

**Comment by AlexModGuy** [comment]
im going to close this one as its not intended, but its really cute and beautiful to see them in this dimension. But I will look into adding a dimensional blacklist a la #1625
