### ISSUE TITLE
Dragon grabbing is really buggy

### ISSUE THREAD

**Issue by Dune-Jumper** [Alex-the-666/Ice_and_Fire#152]
https://gfycat.com/AncientRecentGalapagospenguin At the end of this gif I'm floating in the air and there is no way to "dismount" until something kills me.

**Comment by Alex-the-666** [comment]
Hmm thats strange, usually you should be dismounted at the end of the shake with half health taken off.

**Comment by Partonetrain** [comment]
Saving and quitting seems to be a temporary fix.

**Comment by Alex-the-666** [comment]
I put this in the mega issue
