### ISSUE TITLE
Silver Ingot - Dictionary Registartion Warning

### ISSUE THREAD

**Issue by Fisch37** [Alex-the-666/Ice_and_Fire#1520]
Wile reading through the launch log, I found this.
Aparrently you did something wrong in your code.
Since I'm not very experienced in Java I will leave you a picture of what I found.
![image](https://user-images.githubusercontent.com/46005543/55665895-f998b380-5846-11e9-9cf6-7ba5b546ee43.png)

**Comment by AlexModGuy** [comment]
fixed
