### ISSUE TITLE
silver wont smelt 

### ISSUE THREAD

**Issue by TheOneTraveler** [Alex-the-666/Ice_and_Fire#1522]
i know this used to be an issue in earlier versions, but im in version 1.7.1 and silver wont smelt
![2019-04-06_09 32 48](https://user-images.githubusercontent.com/46114469/55670214-be4eb280-584f-11e9-8eee-a3959d00edb5.png)

**Comment by yqmtat** [comment]
I thought you mean silver won't smelt in the smeltery from tinkers‘construct in title

**Comment by JohanaJoestar** [comment]
I have the same problem
