### ISSUE TITLE
Myrmex are considered passive mobs.

### ISSUE THREAD

**Issue by Renari** [Alex-the-666/Ice_and_Fire#1528]
They will spawn in peaceful worlds.

**Comment by PCAwesomeness** [comment]
That's been a recurring trend with most mobs this mod adds, but these ones have a reason for persisting on Peaceful, solely because you can ally with them.

~~Plus, if they did despawn on Peaceful, Myrmex hives would become empty.~~

**Comment by AlexModGuy** [comment]
^
