### ISSUE TITLE
Forge Ore error

### ISSUE THREAD

**Issue by ICEconchy** [Alex-the-666/Ice_and_Fire#1529]
TO USERS: YES this is a BUG in the mod Ice and Fire report it to them!
> [14:40:18] [Server thread/WARN] [FML]: * at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:674)
> [14:40:18] [Server thread/WARN] [FML]: * at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:646)
> [14:40:18] [Server thread/WARN] [FML]: * at com.github.alexthe666.iceandfire.core.ModRecipes.preInit(ModRecipes.java:103)
> [14:40:18] [Server thread/WARN] [FML]: * at com.github.alexthe666.iceandfire.IceAndFire.preInit(IceAndFire.java:86)
> [14:40:18] [Server thread/WARN] [FML]: * at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [14:40:18] [Server thread/WARN] [FML]: * at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)...
> [14:40:18] [Server thread/WARN] [FML]: ****************************************
> [14:40:18] [Server thread/WARN] [FML]: ****************************************
> [14:40:18] [Server thread/WARN] [FML]: * A broken ore dictionary registration with name foodSimpleEgg has occurred. It adds an item (type: class com.github.alexthe666.iceandfire.item.ItemMyrmexEgg) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.

**Comment by AlexModGuy** [comment]
fixed
