### ISSUE TITLE
The silver ore cannot be smelted and the zaphire ore too.

### ISSUE THREAD

**Issue by JohanaJoestar** [Alex-the-666/Ice_and_Fire#1532]
I have a problem in the Ice and Fire mod. The silver ore, when I get it, does not allow it to be put in the oven to obtain the ingot. I used the JEI mod, and the traditional way of obtaining the ingot appears, burning it, but the mod shows me the extraction without the mineral underneath, and it does not allow to burn it.
And the sapphire mineral has the same problem.
I do not have any other mod that adds minerals.
I have the latest update of Ice and Fire mod 1.7.1 and LLibrary 1.7.18.
Will anyone know what is due?
I would appreciate help.
![image](https://user-images.githubusercontent.com/49662919/56173522-97ad1c00-5fb3-11e9-8f12-a1d0514fbb3d.png)

**Comment by JonMaker050** [comment]
Same here

**Comment by AlexModGuy** [comment]
fixed
