### ISSUE TITLE
Dragons undefeatable?

### ISSUE THREAD

**Issue by dacianalyse** [Alex-the-666/Ice_and_Fire#1534]
I'm not sure if it's just my computer but the dragons that have roosts become invisible at random times, mostly while flying and it makes it impossible to avoid them, and then I'm dead immediately. Also in the dragon dens, everything just lags so massively and I can only fire one arrow before it stops. The dragons don't wake up after being hit either. It was never that bad in previous versions

**Comment by AlexModGuy** [comment]
fixed
