### ISSUE TITLE
Dragon Name

### ISSUE THREAD

**Issue by Mugiwaxar** [Alex-the-666/Ice_and_Fire#1538]
Hey!
I can't find any way to change my dragon name, is it possible?

**Comment by an0nimu5** [comment]
Nametag?

**Comment by Mugiwaxar** [comment]
Doesn’t work
That put the dragon on your shoulders when you click with a nametag

**Comment by an0nimu5** [comment]
I tested it a moment ago and works fine...
maybe try click+shift with nametag

**Comment by Mugiwaxar** [comment]
Nothing to do :(
Click do nothing, and shift click open the Dragon Gui
Maybe the Dragon have to grow?

**Comment by an0nimu5** [comment]
I think your dragon must grow to stage 2. It should help....
I pretty sure it's a bug.

**Comment by Mugiwaxar** [comment]
My dragon is on stage 3
If I click on it with a nametag, I mount it
If I shiftClick, it's open the dragon's GUI

**Comment by AlexModGuy** [comment]
nametag
