### ISSUE TITLE
Weird stage 1 ice dragon model

### ISSUE THREAD

**Issue by an0nimu5** [Alex-the-666/Ice_and_Fire#1539]
Fire dragons looks fine, but ice dragons...
![2019-04-16_12 43 46](https://user-images.githubusercontent.com/49610831/56434423-d8b77000-62d4-11e9-9183-b3258b652bae.png)
![2019-04-05_15 47 52](https://user-images.githubusercontent.com/49610831/56436091-01daff00-62db-11e9-9c2b-68762e4ffbb2.png)

This happens only when the ice dragon rides on the player

**Comment by AlexModGuy** [comment]
fixed
