### ISSUE TITLE
Dragons deep down in nether, also not killable... (see images)

### ISSUE THREAD

**Issue by jonabrv1965** [Alex-the-666/Ice_and_Fire#154]
Hello everyone. I stumble upon this mod looking for a challenge for my new draconium evolution gear (wyvern armor and sword). I was able to find two level 5 dragons while quarrying the nether looking for draconium dust... but.. I cannot kill any of those dragons, cannot hit them with the sword nor with the bow. If I get to close to one of them I'm teleported inside walls (have to use my pickaxe to get out) and i?m slowed down to the point I practically do not move...the one probe does not show them, the waila do not detect them... (I'm playing in survival mode)

![2017-04-02_12 44 37](https://cloud.githubusercontent.com/assets/13445986/24589677/201e62c4-17a4-11e7-9206-cc95f66ad862.png)
![2017-04-02_12 49 39](https://cloud.githubusercontent.com/assets/13445986/24589678/244bdb7e-17a4-11e7-8973-73ae060b3339.png)

Versions : Draconic-Evolution-1.10.2-2.0.9.192-universal, llibrary-1.7.4-1.10.2, forge-1.10.2-12.18.3.2254

I have several other mods in a private modpack. If needed I can upload the FML Log.

**Comment by GundunUkan** [comment]
You can't kill them because, for what I know, they can only be killed by dragon bone weapons from this mod. The teleporting in the walls might be just the dragon knocking you in the walls, and that thing where you're brought to the point where you almost can't move - well, that's because the dragon is using the grab attack, which is kinda glitchy at this point and that's what slows you down. Keep in mind that this mod was released yesterday and due to that it still needs some fixing here and there. Hope I was of some help. ☺

**Comment by CraftyAngyl** [comment]
While testing in creative I killed problem dragons with regular diamond axes.  I don't know what is causing the problem, but these dragons can be damaged just the same as any other mob, they just have more health.

**Comment by jonabrv1965** [comment]
Hi all, I cannot "hit" the dragons with any kind of weapon (I have not tested the bone ones yet)

For some conversation at Discord, I understand that there is not supposed to be dragons down in nether and I was encouraged to post the above pictures...

I have yet to find some surface dragon to test the weapon issue.

Nevertheless, if for some reason I cannot attack a mighty dragon with my best weapon (right now the Draconic Staff, a very very powerful but very, I mean very, expensive one) this mod is not what I'm looking for...

And last but not least, I do know this is a very early stage of the Mod (although I do not know why is marked as "release" in curse), and my intention is to collaborate by giving feedback to the authors.. :-)

**Comment by jonabrv1965** [comment]
Hey all, I just got a surface dragon, a magnificent ice dragon, and was able to kill him with my staff. I guess the problem with the nether dragons is because spawn where should not....

**Comment by jonabrv1965** [comment]
Uhmm... found a fire dragon in surface, when approach seems like the dragon grab me with its teeth and bump me against terrain. The bad part is that I get slowed, cannot almost move...and...cannot hit it... I move away very slowly, for about 40 blocks, and save and reload and appear in the middle of the dragons nest..., the dragon became un-hitable once again grabbed me, once again slowed... I guess the entity lose its hitbox for some circumstance and never recover it and my avatar stays in some kind of loop. To evade this, I teleport myself (using RFTools teleport system) to my base where regain normal movement.

**Comment by Alex-the-666** [comment]
ok nether issues has been fixed and ill make a separate issue for your other bug

that bug is really annoying and probably our biggest bug btw
