### ISSUE TITLE
turn fire breath and fire bomb off

### ISSUE THREAD

**Issue by saraminecraft** [Alex-the-666/Ice_and_Fire#1540]
Hi! Your mod is genius :) I would like to turn off fire breath and fire bomb as the dragons on my server are setting so many fires it is lagging out parts of the world. I also have fire spread off so the fires are persistent. I cant find any setting in the config file for this. Is there another way to do this? Maybe just remove fire dragons? Let me know if there is a workaround or config setting I can use. 
<3 Sara

**Comment by mrhappypenguin** [comment]
This is a big issue. My world was unplayable after a few minutes due to constant fire spread. Disabling fire tick is not an ideal solution. I would like an option to disable fire breath and fire bombs spreading fire.

**Comment by AlexModGuy** [comment]
should no longer be issue in 1.8.0
