### ISSUE TITLE
statues drift toward the origin of the world

### ISSUE THREAD

**Issue by bluecraney** [Alex-the-666/Ice_and_Fire#1542]
statues drift toward the origin of the world every time the chunk is loaded and unloaded.
how to induce:
1. stone any creature with medusa's head
2. move statue with silk touch pick of any sort
3. place away for the origin of the world
4. move away and back toward so the chunk the statue is in becomes unrendered then rerendered
notes:
-happens as a stand-alone mod and with other mods installed
-happens in all game modes
-happens in all world generation types
-using one probe you can mote the statues are actually mobs with there ai turned off not entities like item frames or chests
-happens in the latest version
-happens on servers
-happens in single player
![image](https://user-images.githubusercontent.com/40034092/56472244-994a6a00-6421-11e9-812d-de03ce7e3ada.png)

**Comment by AlexModGuy** [comment]
not able to reproduce in 1.8.0
