### ISSUE TITLE
Spam errors in the console 1.12.2

### ISSUE THREAD

**Issue by DatrixTHLK** [Alex-the-666/Ice_and_Fire#1543]
Hi,

https://gist.github.com/DatrixTHLK/86a536bf71c95d64f70efd5753235294 Massive console spam in the FML Log. This is only a small portion of the fml log.

Minecraft 1.12.2
Forge: 14.23.5.2836
Fire and Ice: 1.7.1
Phosphor: 0.2.2+build43

My fps goes down to at least 3 and I can barely move. This is due in part to Phosphor saying this is an illegal exception, or bad practice. I originally sent this to phosphor because I thought it was on their end.

**Comment by AlexModGuy** [comment]
fixed

**Comment by DatrixTHLK** [comment]
Thanks for fixing the issue. I appreciate the response.
