### ISSUE TITLE
[sponge forge / 1.7.0] Dragon egg not hatching

### ISSUE THREAD

**Issue by greenalex27** [Alex-the-666/Ice_and_Fire#1544]
Verisons:
Sponge: spongeforge-1.12.2-2768-7.1.6-RC3639.jar
Ice and fire: 1.7.0

mods and plugins: https://pastebin.com/V7pgg25M

When trying to hatch an egg (within 5 blocks) it disappears once hatched. Its suppose to hatch.

**Comment by AlexModGuy** [comment]
dupe  #1655
