### ISSUE TITLE
Dragon bones don't seem to stack correctly.

### ISSUE THREAD

**Issue by GundunUkan** [Alex-the-666/Ice_and_Fire#155]
I don't know if it's intended or not, but dragon bones form stacks of only 8, which could be quite inconvenient.

**Comment by Alex-the-666** [comment]
intended

**Comment by GundunUkan** [comment]
Oh, ok, thanks. :) Just out of pure curiosity, may I ask why is that so?

**Comment by Alex-the-666** [comment]
we don't want players carrying around so many in order to make them more rare - same reason cakes and chicken eggs only stack to certain amounts.

**Comment by GundunUkan** [comment]
Ah, thanks! I see your point. ;)
