### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by Horator** [Alex-the-666/Ice_and_Fire#1557]
So, we have some mistakes.
One: My friend can`t tame a dragon.Only host can have his own dragon.Sometimes, when we tryed to make a dragon for my friend, the egg of fire dragon dissapeared.
Two: My dragon can just teleport in the caves.I dont know how it could be.
Three:If my dragon will die, the game will crash.

Myrmex has very many problems.
One:They are really like to spin in one place and doing nothing.
Two:When you try to make really cool hive they can just stuck and doing nothing again.They will ignore your commands.
Three:When workers with soldiers go for some loot they can find hard place to escape(or not hard to escape), jump in this place and stuck again.
Four:They are not atacking agressive mobs like zombies (sorry, if it should be like that).
Five:The eggs, that queen trade, they should be useful,but they spawn agressive myrmex,and your myrmex will kill the new myrmex (he will also atack you).Maybe we doing something wrong?
Six:If you have not one entrance, your myrmex will stuck again.
Thats all problems we have seen.
Sorry for mistakes!I dont speak english well.

Some offers:
Myrmex are good, they are interesting, but they are bad now.I think you should make them smarter and better.
I think will be good, if you add more settings, like which mobs they will atack, and which will not atack.
More settings for the hive will be good too, like outposts.
Will be good, if you will can see, which task are making your myrmex, like "Following worker","Collecting item"(and the item, or mob will glow)
If you can take your myrmex with you, like pet.
If you can see, how many myrmex you have in the hive.

Thats all, i think,maybe, i will make a comment with more problems or offers, thank`s for reading! Ü

**Comment by AlexModGuy** [comment]
dupe #412
