### ISSUE TITLE
Possible conflict with Phosphor

### ISSUE THREAD

**Issue by Sunconure11** [Alex-the-666/Ice_and_Fire#1558]
https://pastebin.com/hsHZHQtG

**Comment by TensorTime** [comment]
I think this is related to https://github.com/Alex-the-666/Ice_and_Fire/issues/1555.  I was getting the crash in that issue from various particle effects within Ice and Fire and the stack trace shows that it was coming through calls to Phosphor.  Phosphor seems to be included as embedded code either within Ice and Fire or LLibrary. 

When I install Phosphor directly which overrides the embedded library with a more recent version the error message in this issue starts to show up,  often followed by a soft crash where eventually the world becomes unresponsive and you have to force close the client.

**Comment by EightBlade** [comment]
I'm having this problem, too. Also causes lag spikes galore.

**Comment by AlexModGuy** [comment]
fixed
