### ISSUE TITLE
Myrmex armor, weapons, and tools cannot be repaired

### ISSUE THREAD

**Issue by Shivaxi** [Alex-the-666/Ice_and_Fire#1559]
as title says, Myrmex armor, weapons, and tools cannot be repaired, tested with latest version for 1.12.2

**Comment by JWTHDYTWA** [comment]
I confirm. It must be fixed.

**Comment by AlexModGuy** [comment]
fixed

**Comment by chezpaul** [comment]
What do you need to use to repair them? I can't repair them with the "skin" nor the stinger
Oh but I'm running 1.7.1
K I'm guessing it's broken in 1.7.1 so does 1.8.0 fix it?
