### ISSUE TITLE
command staff not working

### ISSUE THREAD

**Issue by Dinoramsey** [Alex-the-666/Ice_and_Fire#156]
when riding a dragon if you left click you end up hitting the dragon and after getting hit if you land the dragon ends up running away forcing you to chase it down. Also using a command staff doesn't stop it from flying and if you put it in the the horn if you send it out it still continues to fly. Only way to stop it is to mount it then immediately use a command staff so it doesn't fly away which is hard since you gotta chase it down. Would be nice if you couldn't hit it while riding it like horses. FYI this was only with fire dragons haven't tried this with the ice variants.

**Comment by Dinoramsey** [comment]
btw the command staff only doesn't work when the dragon flys. if its on the ground it works like it should

**Comment by Alex-the-666** [comment]
I'm not able to hit my dragon when riding it?
