### ISSUE TITLE
Dragons disappearing after being released from the horns

### ISSUE THREAD

**Issue by Nightressa** [Alex-the-666/Ice_and_Fire#1561]
I am using 1.12.2 1.7.1 Version of Ice And Fire. Dragons seem to be disappearing the moment they are being released from a dragon horn. Is there any mod/plugin that could cause this to happen?

**Comment by Snakes4Lyfe** [comment]
I've had the same issue. I was on the Mystical Reign modded Minecraft server and we had 3 fire dragons. Two were possibly stage 4 females and a stage 2 male.  Our first dragon I believed vanished because it was unnamed so we named the other female and male. My friend put them both into a horn. Later on, when the male was big enough to breed my friend attempted to take the female out of the dragon horn when it vanished.

**Comment by RivaHakushia** [comment]
> I've had the same issue. I was on the Mystical Reign modded Minecraft server and we had 3 fire dragons. Two were possibly stage 4 females and a stage 2 male. Our first dragon I believed vanished because it was unnamed so we named the other female and male. My friend put them both into a horn. Later on, when the male was big enough to breed my friend attempted to take the female out of the dragon horn when it vanished.

To help towards this if it is a known conflict with mods/plugins - https://pastebin.com/EQrTFzvd

**Comment by AlexModGuy** [comment]
not sure if will persist on 1.8.0

**Comment by I-CHief-I** [comment]
Hi i have the same issue , when i use the dragon horn on a lvl4 dragon , its erased .. when i use dragon horn multiple time on a dragon 1_3lvl , sale issue ... i have other mod maybe is a know issue ? And when i ride a dragon and i put the f5 camera , i not see really much... and on video we see all of the dragon body and our player .. can you help me?i would like use your mod into a server based on this mod

**Comment by GrandAlbert** [comment]
Yeah I had this problems too, not just once but twice actually, the first time I place down the dragon from the horn but it didn’t spawn and the dragon horn said it was empty, but for some reason the dragon miraculously came back to the horn later. But the second time I place the dragon down and the server lagged a bit then the dragon disappeared, I logged out and back in but the dragon was still not there

**Comment by laundmo** [comment]
this happened on our server too, right after we added sponge, so i assume its a conflict with that

usign a golden lasso to capture the dragon has the same result, it dissapears after spawning

**Comment by Logory123** [comment]
i had the same issue on a single player world. I was pissed and i just logged off and when i came back the dragon was sleeping where i saw him last. 

I think reloging in the world might fix it

**Comment by itsfriday19** [comment]
I'm also experiencing the problem--playing on Minecraft 1.12.2 with Ice and Fire 1.8.4. Exiting and loading the world again does bring the dragon back, but it's a crapshoot as to whether it'll bring it back where you last tried to release it or where you last picked it up from. It really does need fixing, it's making me anxious using the horns. Does anyone know a way of "backing up" your dragon besides obviously backing up your save file? What I mean to say is, can we store them in a horn and then duplicate the horn? (This already somehow happened with one of my dragons, I have a copy of him sitting in one of my chests but I have no clue how that happened or how to replicate it).

EDIT: finally happened, one of my dragons permanently disappeared after using the Dragon Horn

**Comment by samthelizard** [comment]
I also had an issue with this and to prevent it, I just downloaded the extra utilities mod, it has the golden lasso which basically works like the horn, except it can pick up any animal/ other mob. So until this is hopefully fixed, if you guys want, you should download it, makes my life a lot easier too. I think it'll help you guys too.

**Comment by itsfriday19** [comment]
Yeah I got NotEnoughWands and I’ve been using its Capture Wand (config set so it doesn’t use XP or anything). That’s been working well for me in the meantime.

**Comment by HeatherComputer** [comment]
Seeing this on Enigmatica 2 Expert, I've given up on using the horn. They don't actually vanish, relogging shows them in the horn. After four attempts it spawned again.
poor bella.

**Comment by BTOptimizer** [comment]
Got a report of this happening to a player who caught their dragon in a Dragon Horn mid-air and it not being in the horn when they attempted to place the dragon after they were on the ground. This was on an MC Eternal multiplayer server running iceandfire-1.9.1-1.12.2. Relogging didn't help according to the player.

**Comment by thearyaanyadav** [comment]
Could you PLEASE fix this. I've wasted a LOT of time today with this issue, with 5 dragon pets all gone to waste. Issue is occuring with MC Eternal.

**Comment by BugmanBugman** [comment]
How bout you upgrade to 1.16.4

![](https://i.ytimg.com/vi/kkBgqTXLgTw/maxresdefault.jpg)

**Comment by DisruptionSystemsINC** [comment]
Experiencing Glitch in MCEternal currently and it's pretty Frustrating and annoying.
Seems like in happens when you put the dragon in a horn while mid-air more frequently
Also it seems like Dragons are cleared from their Dragonhorns on death, possibly an issue with Corail Tombstones

**Comment by DisruptionSystemsINC** [comment]
> How bout you upgrade to 1.16.4
> 
> ![](https://camo.githubusercontent.com/a5e1ae38e8e2503d3114a9054c365ca392c6a780b85a22e23c832be135262c69/68747470733a2f2f692e7974696d672e636f6d2f76692f6b6b42677154584c6754772f6d617872657364656661756c742e6a7067)

"Just upgrade the pack bro, can't be that hard"
