### ISSUE TITLE
silver axe is not classified as an axe tool

### ISSUE THREAD

**Issue by Shivaxi** [Alex-the-666/Ice_and_Fire#1567]
The silver axe isn't in the toolAxe ore dictionary and therefore does not actually chop wood and wood items correctly.

**Comment by DoomRater** [comment]
For that matter, it cannot be cast to ItemSword correctly for monsters that expect it, such as the Mo'Creatures Werewolf, causing a crash when you attack them with it.

Edit: The pickaxe also crashes when used to attack werewolves, as do shovels.  Swords don't though.

Edit 2: On further inspection my crash seems to have more to do with whatever's been done wrong over with #1601 due to the way things are being typecasted.  I may need to re-file as a new issue as dragon bone shovels and pixkaxes aren't crashing, and neither are chitin based tools, or the troll column.

**Comment by Sunlordess** [comment]
> For that matter, it cannot be cast to ItemSword correctly for monsters that expect it, such as the Mo'Creatures Werewolf, causing a crash when you attack them with it.
> 
> Edit: The pickaxe also crashes when used to attack werewolves, as do shovels. Swords don't though.
> 
> Edit 2: On further inspection my crash seems to have more to do with whatever's been done wrong over with #1601 due to the way things are being typecasted. I may need to re-file as a new issue as dragon bone shovels and pixkaxes aren't crashing, and neither are chitin based tools, or the troll column.

HEY! I fixed my issue and the problem was the Damage Indicators mod i had installed. Not sure if you use this one, but it could possibly fix the issue for both of you? maybe?
http://www.9minecraft.net/damage-indicators-mod/
heres the mod i had installed. Hope it helps!

**Comment by DoomRater** [comment]
Then MoCreatures is just as likely a culprit.  I am not using that mod.

And as an aside, never use 9Minecraft again for mods... it's a shady bad place to get them from.

Edit: I did look at the code.  The Silver Axe is indeed inheriting from the wrong tool class.  That part is not a mod conflict at all, it has been created incorrectly.

**Comment by DoomRater** [comment]
https://github.com/Alex-the-666/Ice_and_Fire/blob/abb36e2d7a640b1b34954bb7904c872c345c54de/src/main/java/com/github/alexthe666/iceandfire/item/ItemModAxe.java#L31

This line STILL refers the axe as "itemTool" instead of "itemAxe".

**Comment by BugmanBugman** [comment]
Wait does it really crash when you attack werewolves with an axe?

**Comment by DoomRater** [comment]
Attacking a Mo' Creatures Werewolf would crash with an error saying the item could not be cast to itemSword.  Funny enough, none of the other axes cause this crash, only silver tools (except Silver Sword). Let me know if I need to refile.

**Comment by BugmanBugman** [comment]
Yup, just tested it out and you are correct. Do you know if it applies to other axes?

**Comment by DoomRater** [comment]
I tried every variant of axe in the mod that doesn't have silver attached to its name and they do not.  Which is why I'm not entirely sure whose fault it really is.
