### ISSUE TITLE
Problem on Server

### ISSUE THREAD

**Issue by GabrielMROV** [Alex-the-666/Ice_and_Fire#1571]
[BUG ICE AND FIRE.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/3200201/BUG.ICE.AND.FIRE.txt)
![BUG ICE AND FIRE](https://user-images.githubusercontent.com/26826845/58059431-38f33900-7b43-11e9-9986-601a1195933c.png)

**Comment by AlexModGuy** [comment]
fixed
