### ISSUE TITLE
[1.12.2] Can't Loot Dragons/Mounted Tamed Dragon Disappeared

### ISSUE THREAD

**Issue by Tinklehorn** [Alex-the-666/Ice_and_Fire#1572]
I've been able to loot before, but all of a sudden it just broke. I killed a stage 3 dragon, then after a day of real-time playing, I killed a stage 5 and then a stage 4. I ran around for 30 minutes on the latter two right clicking everywhere and nothing worked. Tried reloading chunks, restarting the game, and killing a second dragon (the stage 4), but nothing had worked so far. 

I also would like to mention since I'm here that I had a stage 3 dragon disappear after I died to a second dragon while mounted. I think it grabbed me while I died, but there was no death message and no sign of my dragon, so I'm 100% certain that it just disappeared out of thin air. It hasn't happened since then, but I still feel as though it's something important to be mentioned. I have a hunch that it maybe has something to do with the fact that a hostile dragon grabbing you makes you mount them, so maybe it conflicted with my tamed dragon being mounted as well?

**Comment by Tinklehorn** [comment]
So a small update, I reinstalled minecraft and added things back in one by one. The bug started again after I put back in my config settings from my old folder, so it has something to do with that. I'm not sure what mod is doing it though.

**Comment by Tinklehorn** [comment]
Yup! I took out Howling Moon and Ice and Fire's config as to reset it, and I can now loot dragons again. 

Everything's all fixed.

**Comment by katubug** [comment]
Hey, I have a question about the issue you were having. When you were trying to loot the dead dragons, did you hear the looting sound and nothing dropped? Or did the right click just not seem to work? One of my players is having a similar issue.
