### ISSUE TITLE
Game keeps crashing

### ISSUE THREAD

**Issue by BabyBlueVixenYT** [Alex-the-666/Ice_and_Fire#1573]
The game crashed whilst initializing game
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: net/ilexiconn/llibrary/server/core/api/LLibraryCoreAPI

I tried redownloading it, useing a differnt version of it(downloading it somewhere else),and useing all of the llibrary files. Here is a part of the crash report(above) hope it helps.

**Comment by Xorbah** [comment]
...You need llibrary.

**Comment by BabyBlueVixenYT** [comment]
I ended up installing llibrary wrong...
oops ^^;
