### ISSUE TITLE
dragon render distance too short

### ISSUE THREAD

**Issue by Shivaxi** [Alex-the-666/Ice_and_Fire#1578]
I'm not sure why but dragons don't render very far (it looks kinda like 32-64 blocks ish?) when other mobs from other mods can render much farther.  It would be very helpful if we could see dragons from much further out

**Comment by Seraphaestus** [comment]
Also it would be lovely to have this as a config option. I thought it was but couldn't find it and was quite dissapointed

**Comment by JumpyDragon** [comment]
Yes, this would be very helpful... as it currently is, I am getting fire-bombed to death before I can even spot them in the sky.
