### ISSUE TITLE
Crash when pixie jar place near nether portal

### ISSUE THREAD

**Issue by pixzi** [Alex-the-666/Ice_and_Fire#1580]
How? 
crashed - gave crash report

How to repeat?
By placing within proximity of a nether portal- crashes after about 30 seconds.

In a modpack? if so which?
Yes - Transient

Version?
1.12.2 - 1.7.1

Crash report:
https://paste.dimdev.org/afafonixes.mccrash

Issue was brought up that crashed in modpack, i was able to replicate it as they did also.

**Comment by AlexModGuy** [comment]
fixed
