### ISSUE TITLE
I think internal server stops responding (likely mod incompatibility with New Tardis)

### ISSUE THREAD

**Issue by Keltas** [Alex-the-666/Ice_and_Fire#1581]
When I enter Tardis from New Tardis mod by spectre0987 the internal server seems to stop responding. I cannot interact with blocks, cannot drop items, the game freezes completely when trying to save and exit until I use task manager to force it to close. I would report it on the Tardis mod but ATM their issues tracker is down (I think due to some spammer). I have this issue while having following mods installed: iceandfire-1.7.1-1.12.2.jar, jei_1.12.2-4.15.0.279.jar, llibrary-1.7.19-1.12.2.jar, tardis-0.1.0D.jar .
This is the log (there is no crash report): https://pastebin.com/Uajj438u
Steps to reproduce:
1. Install Tardis mod together with Ice and Fire (plus JEI for convenience).
2. Give yourself Tardis corail and plant it on the ground.
3. While looking at it type "/tardis grow".
4. Right click on the door of tardis with the key.
5. Walk inside.
The interior should generate but you cannot close the doors or walk back outside. When exiting the game it freezes.
I believe the issue may be related to worldgen as I sometimes (every hour or two) run into this exact same issue (with internal server stopping) during generation of new terrain. I cannot say if this problem during world generation is related to this one, and triggered by Ice and Fire, as it is too rare to troubleshoot it in my main modpack to find the culprit. Whenever I get this issue during worldgen I have a Cascading Worldgen Lag triggered by one mod or another (usually mystcraft but if disabled it simply changes to another mod) in my log.

**Comment by aetreia** [comment]
I have the exact same problem but u have no idea which mod causes it :/ can't even open my single player world because I get the "waiting for server" message instantly.... And I can only force close the game

**Comment by AlexModGuy** [comment]
This isnt a full crash so im unsure of what the issue is
