### ISSUE TITLE
Cyclic "Inventory Upgrade" & Hippogryph Conflict

### ISSUE THREAD

**Issue by TimBobWe** [Alex-the-666/Ice_and_Fire#1582]
Minecraft Version: 
1.12.2

Forge Version: 
14.23.5.2836

Mod Version: 
Cyclic: 1.12.2-1.19.9
Ice & Fire: 1.7.1-1.12.2
Enigmatica 2: Expert 1.64d

Single Player or Server: Both

If you have eaten an Inventory Upgrade from Cyclic, thus unlocking the extra inventory slots and functionality, riding a Hippogryph breaks the player inventory. No items can be picked up and the player is unable to interact with Crafting Tables. Hippocampus do not seem to cause the same issue. All other mobs are untested.

Player is forced to Relog.

**Comment by TimBobWe** [comment]
Upon retesting right now I am finding the bug to be less consistent than previously experienced.
The most consistenly unusable non-player inventory is the "Crafting Station" from Tinker's Construct.

The bug occurs after dismounting, not sporadically while mounted. This is a major oversight in my original description. My apologies.

**Comment by AlexModGuy** [comment]
should be fixed with riding overhaul in 1.8.4
