### ISSUE TITLE
Internal server lag/Constant "Waiting for server" message

### ISSUE THREAD

**Issue by aetreia** [Alex-the-666/Ice_and_Fire#1585]
I just SUPPOSE this problem is caused by ice and fire so please don't throw rocks at me.
I have been playing my modded Minecraft with no problems whatsoever but after encountering a death worm, I can't play my single player world anymore, as I get constant "waiting for server" message on One Probe. Mobs don't move, nothing drops, the map doesn't load, only like 10x1 chunks. I tried restarting the game several times and also instantly teleporting from the place but I can't even do that. My client says I moved wrongly and something like "did the server time change, running XY ms behind, skipping xy ticks"

This is really bothering me because I don't want to lose my world. I can't find any crash report in my .Minecraft folder, just by the way, I can just use the client output or whatever that is.
Thank you

**Comment by Xorbah** [comment]
If you suspect it's Ice and Fire, remove the mod from the mods folder,
reload the world, get away from the area you're in,  and re-add Ice and
Fire.

**Comment by DatrixTHLK** [comment]
Just an idea you may want to have VanillaFix within your mod list in case you'd like to confirm it also. Unless you have done so.
