### ISSUE TITLE
[I&F 1.7.1] World-griefing issues using any "entities morphing" mods.

### ISSUE THREAD

**Issue by Yldales** [Alex-the-666/Ice_and_Fire#1587]
Hi,

When a player use mods like MorePlayerModels or Metamorph to take the appareance of a Myrmex Queen, Ice and Fire will generate a Myrmex Hive above the morphed player every seconds.
- Affect singleplayer and multiplayers worlds.
- Affect worlds with MorePlayerModels's gamerule `mpmAllowEntityModels` on false.
- Using a MorePlayerModels morph, hive's blocks seems to be only "visual" and dissapear after the next login.
- Using a Metamorph morph, hive's blocks stay.

I'm using:
- Minecraft 1.12.2
- Forge 14.23.5.2807
- Ice and Fire 1.7.1
- LLibrary 1.7.19
- MorePlayerModels 1.12.2
- McLib 1.0.2
- Metamorph 1.1.8

**Comment by BugmanBugman** [comment]
Mods like those aren’t compatible with anything and should only be used by themselves.
