### ISSUE TITLE
Tamed and wild dragons flying to block limit and never coming down

### ISSUE THREAD

**Issue by NoahNinja** [Alex-the-666/Ice_and_Fire#159]
While playing in survival and creative, dragons will take off from their nests or wherever and fly normally, but constantly going up, I followed one to the top of the world, it flew normally,  it didn't come down

**Comment by GundunUkan** [comment]
Yeah, I was playing in my survival and noticed that, too, with multiple dragons.

**Comment by AlexModGuy** [comment]
fixed in 1.2.0.
