### ISSUE TITLE
Dragon Fire spam

### ISSUE THREAD

**Issue by hellwolf95** [Alex-the-666/Ice_and_Fire#1590]
so last night on 6/9/19 i noticed that a player on the server i played on was fighting a dragon. so i tped to him in spectator mode to see. and to my surprise, I watched this dragon spam fire every second at the player. this ended up causing a huge amount of fire that spread and on top of that lots of ash blocks being flung everywhere. 

so id like to suggest a cooldown on a dragons fire attack and allow it to be config if possible. or at least tweak the ais targeting system to only use fire when the target is far away.

**Comment by kreezxil** [comment]
this was on the World of Dragons pack.

We need a dragon fire cool down.

WOD is super optimized now, it stays up for about 40+ hours with 10 to 15 players avg an hour on the weekend.

At least we've come back to needing to some constrains on dragons.

Cheers!

**Comment by AlexModGuy** [comment]
fixed
