### ISSUE TITLE
null

### ISSUE THREAD

**Issue by ZuranaSuki** [Alex-the-666/Ice_and_Fire#1591]
null

**Comment by AlexModGuy** [comment]
not much we can do about that.

**Comment by ZuranaSuki** [comment]
lazy ass devs

**Comment by kodabeer** [comment]
FYI, they've been patching bugs last few days. If there's nothing they can realistically do to scale armour size with another mod then that's not something to call them lazy for. You try going through 70 bugs a day.

**Comment by BugmanBugman** [comment]
Maybe don’t use stuff like moreplayermodels. What have you actually created?

**Comment by ZuranaSuki** [comment]
> FYI, they've been patching bugs last few days. If there's nothing they can realistically do to scale armour size with another mod then that's not something to call them lazy for. You try going through 70 bugs a day.

Who are you talking too? i dont see who your replying too
