### ISSUE TITLE
Particle Settings 

### ISSUE THREAD

**Issue by FuneralPartly** [Alex-the-666/Ice_and_Fire#1593]
When activating any setting that decreases or minimizes particles, this does not include any particles rendered in this mod.  

Aka, this is tested with optifine. The Animation settings do not disable the fire particles generated by the dragons, siren music notes, or etc. Which can help with the particles causing crashes?  Plus random particle glitches when Sirens sing and it is just non stop music notes never going away. But that problem is probably on my end.

**Comment by Xorbah** [comment]
Optifine issues are usually not something taken into account as the source
for it is closed source and mod developers more often than not cannot do
anything about errors dealing with it. If the particles for a mod aren't
noticeably decreasing with the setting you had mentioned then it's likely
that the mod doesn't register particles in the way they're supposed to.

**Comment by FuneralPartly** [comment]
I used optfine to specifically turn off certain particles, I can do more tests without it. But I know some rigs can't handle the obsessive particles. I personally have the problem of crashes due to rendering particles. I am unsure how the coding for the config and particles are, not skilled in Java programming, But having a section to turn particles on or off should be semi-simple. Granted programming is never easy, having a way to enter a particle generation limit would be better but more coding and I will not put more programmers in pain. It would just be nice for more people to be able to use the mod.

**Comment by Xorbah** [comment]
Oh, I absolutely get where you're coming from. Wasn't trying to chastise
you if it felt that way. A lot of people have issues when dealing with
Optifine and other graphically intensive mods. It sucks, but until
Optifine's developer decided to open source his work other developers are
stuck either letting the bug persist or making hacky (and inefficient)
workarounds for said graphical errors.
