### ISSUE TITLE
Mobs spawn in abundance

### ISSUE THREAD

**Issue by LmAOfromSuperiorServers** [Alex-the-666/Ice_and_Fire#1595]
There are loads of problems with the fire and ice mod, one of which being mobs of all types will spawn in hordes. Originally the mod was fine but would affect server performance slightly, and overtime it got MUCH MUCH worse. Dragons of levels 4 and 5 have issues like not despawning after being killed/ when all mobs are slain and sometimes they just disappear in general when being fought. Medusa and trolls cause tons of problems because they freeze mobs, so mobs will still be alive but not able to do anything, and eventually they just start piling up until the server goes kapoot. We thought changing the mob spawn rate manually would fix things, but apparently fire and ice mobs are unaffected by that. We finally had to just remove the mod after it nearly corrupted our server with horrible lag and whatnot. Please, I’m begging you. Fix these issues! :( 
![C66BBCA6-F2D4-41C7-9C4E-A61970BF985B](https://user-images.githubusercontent.com/51982131/59736379-40733400-920e-11e9-9793-4cf4a95d34d6.jpeg)

**Comment by LmAOfromSuperiorServers** [comment]
This is one of the few screenshots I took when we had the mod because I thought it was so ridiculous. I had another one with at least 200 trolls just surrounding our base but I lost the screenshot.

**Comment by AlexModGuy** [comment]
trolls are supposed to be rare and most players dont even encounter them. its extremely odd how you are having hundreds of them spawn and I predict its due to a mod conflict

**Comment by BugmanBugman** [comment]
try https://www.curseforge.com/minecraft/mc-mods/tick-dynamic

**Comment by ValentineBlaze** [comment]
I had this happen to me too I think the hoard is bound to a mod that gives an effect called curse and I think I got it from a soul orb dropped by a wraith in the nether that I then used I cant remember what mod that is that summons those wraiths I think its quark trolls were not the only thing that spawned it was all mobs that could spawn in the area

**Comment by BugmanBugman** [comment]
Is this a product of quarks soul bead?

**Comment by AlexModGuy** [comment]
yeah looks like it
