### ISSUE TITLE
Tide Armour causes game to crash when trying to equip

### ISSUE THREAD

**Issue by Sunlordess** [Alex-the-666/Ice_and_Fire#1601]
In short, i tried to equip the Tide armour (helmet) but my game immediately crashed. After loading MC again and trying to get into the world i was playing on, it just kept crashing because of it. As a result, i tried multiple methods to try it get back onto this world (its just a mod testing world so i can see if any mods i download will clash) including restarting MC, shutting down my computer and disabling the mod. Even after disabling the mod, it would still crash. However, enabling the mod again after disabling seemed to help (the first time at least) as i was able to get back onto the world.
So i tested again to see if maybe it was just a one-time glitch, cause ya never know right? But no. It seems that you are unable to equip the Tide Armour- or at least the helmet- without it crashing.
You can equip the armour to _mannequins_ without it crashing.

I'm using Forge 1.12.2 and the latest version of this mod.

Here is the crash report i received;
[CrashreportforIaF.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/3322184/CrashreportforIaF.txt)

Hope this is a problem that can be fixed!

**Comment by Sunlordess** [comment]
The problem with this was the Damage Indicators mod i had installed;
http://www.9minecraft.net/damage-indicators-mod/
It not only caused problems with this mod, but also all potions in minecraft.
Hope this can help solves some issues for people!

**Comment by BugmanBugman** [comment]
Don’t use damage indicators and don’t use  9minecraft bro
