### ISSUE TITLE
Client Crash: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean

### ISSUE THREAD

**Issue by OsirisKalev** [Alex-the-666/Ice_and_Fire#1603]
Running version 1.7.1-1.12.2

https://pastebin.com/bb2bZPvA

I should add, while this causes a crash in the client, it does not cause the server to crash out.

I've noticed that other threads from last year were referencing Thaumcraft 6 as the culprit, but that was fixed I assume? I also see problems about Primitive mobs but that's also over a year ago. If this is still the issue, no problem, I'll try and get rid of other mods (ie primitive mobs) that might be causing this.

Edit: A reset of the server seems to have fixed this problem. The client crash is no longer occuring.

**Comment by AlexModGuy** [comment]
dupe #963
