### ISSUE TITLE
Dimension whitelist and blacklist not working properly

### ISSUE THREAD

**Issue by Noble772** [Alex-the-666/Ice_and_Fire#1604]
I've been having an issue where despite me only having the overworld on my whitelist, flowers, dead dragons, and some mobs will spawn in other dimensions. I've experienced this bug in the Atum and the Twilight Forest.
[Modlist.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/3346621/Modlist.txt)

**Comment by AlexModGuy** [comment]
dupe, willfix with #1625
