### ISSUE TITLE
Silver Ore still won't smelt in v1.7.1

### ISSUE THREAD

**Issue by TheOreoroar** [Alex-the-666/Ice_and_Fire#1607]
Silver Ore won't smelt, it just stays in the smelting menu and does nothing in the smelter.
Idk if I've set up the smelting forge wrong for my first time or this is pretty much a bug. I'm confident that this is a bug from what I saw people reporting the Same bug I'm having on curseforge.

**Comment by anvilknight** [comment]
same here

**Comment by Arctic90x** [comment]
You're not the only one having this problem, I am also.

**Comment by SilPan** [comment]
affects me too

**Comment by AlexModGuy** [comment]
fixed
