### ISSUE TITLE
When hatching a dragon in a lan game they do not spawn when egg is done hatching they seem to dissapear

### ISSUE THREAD

**Issue by dragonofrage1** [Alex-the-666/Ice_and_Fire#1608]
i tried with both types of the eggs ice and fire the fire egg would make the hatching noise and nothings there and the ice egg dissapear after hearing the ice break but then in the place the ice was could no longer place anything please try to fix this

**Comment by RivaHakushia** [comment]
I am also running a SpongeForge server and have noticed with the configs if it's at the default timer for Dragons to hatch, the egg makes a noise the moment you place water or set on fire then the egg it's self dissappears, if you re-log into the server the eggs return to their first state and this seems to just loop, 

Know if you set the Hatch timer to 1 making it instant, Baby dragons seem to hatch, at least for the SpongeForge Server I am running, I would suggest @dragonofrage1 trying this out with your configs and see if this helps, I am unaware if this is just the mod it's self or a conflicting mod/plugin but I do hope this gets looked into as I would personally like to use the default timer for my Custom Modpack server.

Current Mods/Plugins my Server uses : https://pastebin.com/EQrTFzvd

**Comment by AlexModGuy** [comment]
dupe  #1655
