### ISSUE TITLE
Can't interact with mobs

### ISSUE THREAD

**Issue by 0hShush** [Alex-the-666/Ice_and_Fire#1609]
so basically i can't hit any vanilla and ice and fire mobs and there is a slight delay when i hit blocks

**Comment by anvilknight** [comment]
that sounds like a memory issue what is your's set to

**Comment by Convergence2738** [comment]
You could also have suffered a ticking entity bug/crash. When you get one, the world freezes, mobs freeze, and items cannot be interacted with. You can't see ticking entity crashes in sp as the world usually doesn't generate a crashlog(you usually crash on save and quit)
