### ISSUE TITLE
[feature request] different block breaking rules

### ISSUE THREAD

**Issue by Zygus42** [Alex-the-666/Ice_and_Fire#161]
There are 3 settings: None, Soft & Hard.  Unfortunately Soft and Hard both lead to major ecological disasters, particularly in forests - wouldn't be so bad if they actually knocked the trees down, but just leads to really ugly hard to fix hanging bits of wood and leaves.  None presumably leads to the underground dragons not being able to tunnel to the surface.  I would really like an option where the underground dragons tunnel out, and then revert to No block breaking once they're out on the surface.

Another alternative/add-on I would quite like to see is dragons "ghosting" through soft blocks, as that would stop them getting stuck in forests with the No block breaking option on.

**Comment by Kusark** [comment]
Feature requests can go on the Discord suggestion chat, not here. This is for issues & bugs

**Comment by Alex-the-666** [comment]
Move this to suggestions https://github.com/Alex-the-666/Ice-and-Fire-Suggestions/issues
