### ISSUE TITLE
Recent server crash!

### ISSUE THREAD

**Issue by iamweirdie** [Alex-the-666/Ice_and_Fire#1610]
Hello, my server crashed and produced this particular crash log. I'm still trying to find out who did what but in the meantime, i hope the log helps.
[crash-2019-07-06_23.05.10-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/3365269/crash-2019-07-06_23.05.10-server.txt)

**Comment by AlexModGuy** [comment]
at net.shadowmage.ancientwarfare.structure.tile.TileTotemPart.getAdditionalPositions

not our issue
