### ISSUE TITLE
Editing the config using 'mod options' in game has literally no effect

### ISSUE THREAD

**Issue by kaporli** [Alex-the-666/Ice_and_Fire#1612]
When editing the config for ice and fire with mod options has zero effect, when trying to increase the Ampithere spawns i increased the spawn weight to 1000 and to see if it had any effect. It didn't so then i made it 0 to see if that changed anything. It also didn't then once I had an Ampithere I wanted its health to be increased from 50 to 100, it had no effect in game. Same story when trying to decrease the damage from dragons. Is there a fix for this?

**Comment by SynexWolf** [comment]
Did you restart the game after editing it? A lot of the configs require a game restart, even when it's via mod options

**Comment by AlexModGuy** [comment]
fixed in 1.8.0
