### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by Angrigo** [Alex-the-666/Ice_and_Fire#1614]
Error in the client, crashing the game, are you trying to cast a byte to a boolean in isFlying() ??
https://pastebin.com/PDs7dGyS
EDIT: 
another one, casting int as boolean
https://pastebin.com/1ujQCMCP

**Comment by AlexModGuy** [comment]
dupe #963

**Comment by Angrigo** [comment]
I have no thaumcraft in my modpack
