### ISSUE TITLE
Troll crashes game.

### ISSUE THREAD

**Issue by londonkxss** [Alex-the-666/Ice_and_Fire#1620]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.10-1.12.2.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 7/15/19 4:02 AM
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.client.entity.EntityPlayerSP cannot be cast to net.minecraft.entity.player.EntityPlayerMP
	at DamageIndicatorsMod.core.DIEventBus.livingEvent(DIEventBus.java:229)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_80_DIEventBus_livingEvent_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:567)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1846)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at DamageIndicatorsMod.core.DIEventBus.livingEvent(DIEventBus.java:229)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_80_DIEventBus_livingEvent_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:567)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: iceandfire:if_troll (com.github.alexthe666.iceandfire.entity.EntityTroll)
	Entity ID: 175
	Entity Name: Troll
	Entity's Exact location: -19.40, 31.00, -263.60
	Entity's Block location: World: (-20,31,-264), Chunk: (at 12,1,8 in -2,-17; contains blocks -32,0,-272 to -17,255,-257), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, -0.06, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['honeyelectrify'/174, l='MpServer', x=-27.35, y=23.92, z=-259.35]]
	Chunk stats: MultiplayerChunkCache: 370, 370
	Level seed: 0
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 229631 game time, 19381 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 106 total; [EntityBat['Bat'/260, l='MpServer', x=30.25, y=41.10, z=-217.25], EntityZombie['Zombie'/281, l='MpServer', x=-46.70, y=17.00, z=-319.62], EntityZombie['Zombie'/282, l='MpServer', x=-42.96, y=17.00, z=-319.48], EntityCreeper['Creeper'/283, l='MpServer', x=-33.85, y=58.00, z=-319.54], EntityCreeper['Creeper'/284, l='MpServer', x=-32.50, y=63.00, z=-319.50], EntitySkeleton['Skeleton'/285, l='MpServer', x=-43.67, y=69.00, z=-335.50], EntityZombie['Zombie'/286, l='MpServer', x=-48.74, y=16.00, z=-277.41], EntitySkeleton['Skeleton'/287, l='MpServer', x=-60.50, y=69.00, z=-275.50], EntityZombie['Zombie'/288, l='MpServer', x=-60.60, y=68.00, z=-283.51], EntityZombie['Zombie'/289, l='MpServer', x=-52.70, y=69.00, z=-282.20], EntitySpider['Spider'/34, l='MpServer', x=-70.50, y=63.00, z=-186.50], EntityPig['Pig'/293, l='MpServer', x=-0.67, y=67.00, z=-337.48], EntitySheep['Sheep'/295, l='MpServer', x=-6.55, y=67.00, z=-338.52], EntityPig['Pig'/301, l='MpServer', x=11.50, y=63.00, z=-302.50], EntityPig['Pig'/302, l='MpServer', x=10.50, y=63.00, z=-302.50], EntitySpider['Spider'/303, l='MpServer', x=5.50, y=63.00, z=-300.50], EntityPig['Pig'/304, l='MpServer', x=13.50, y=64.00, z=-298.50], EntityPig['Pig'/305, l='MpServer', x=14.50, y=64.00, z=-299.50], EntitySkeleton['Skeleton'/306, l='MpServer', x=7.55, y=64.00, z=-289.22], EntityCreeper['Creeper'/307, l='MpServer', x=-36.42, y=69.00, z=-253.83], EntityCreeper['Creeper'/308, l='MpServer', x=-40.44, y=68.00, z=-243.22], EntitySpider['Spider'/316, l='MpServer', x=38.04, y=41.00, z=-318.00], EntityZombie['Zombie'/317, l='MpServer', x=35.14, y=43.00, z=-318.49], EntityPig['Pig'/318, l='MpServer', x=35.75, y=67.00, z=-312.50], EntityPig['Pig'/319, l='MpServer', x=41.50, y=68.00, z=-310.75], EntityPig['Pig'/320, l='MpServer', x=32.50, y=67.00, z=-317.50], EntitySkeleton['Skeleton'/321, l='MpServer', x=8.50, y=64.00, z=-282.50], EntityCreeper['Creeper'/322, l='MpServer', x=-2.52, y=34.77, z=-259.33], EntityCreeper['Creeper'/323, l='MpServer', x=-15.88, y=32.00, z=-267.47], EntityCreeper['Creeper'/324, l='MpServer', x=-5.50, y=66.00, z=-257.50], EntityPig['Pig'/325, l='MpServer', x=6.29, y=64.00, z=-327.36], EntityPig['Pig'/326, l='MpServer', x=2.24, y=65.00, z=-329.54], EntitySkeleton['Skeleton'/327, l='MpServer', x=-39.90, y=15.00, z=-285.61], EntitySkeleton['Skeleton'/328, l='MpServer', x=-47.55, y=16.00, z=-282.58], EntityBat['Bat'/331, l='MpServer', x=-13.44, y=17.93, z=-323.34], EntityZombie['Zombie'/332, l='MpServer', x=-2.50, y=63.00, z=-320.50], EntitySheep['Sheep'/333, l='MpServer', x=-6.57, y=66.00, z=-334.61], EntityPig['Pig'/334, l='MpServer', x=-1.50, y=67.00, z=-335.50], EntityPig['Pig'/335, l='MpServer', x=-3.73, y=64.00, z=-331.49], EntitySheep['Sheep'/336, l='MpServer', x=-9.26, y=66.00, z=-335.51], EntityPig['Pig'/337, l='MpServer', x=-5.58, y=65.00, z=-334.21], EntityCreeper['Creeper'/338, l='MpServer', x=-14.22, y=64.00, z=-322.19], EntityPig['Pig'/339, l='MpServer', x=26.74, y=67.00, z=-323.33], EntityItem['item.item.rottenFlesh'/340, l='MpServer', x=-44.04, y=16.00, z=-256.12], EntitySkeleton['Skeleton'/341, l='MpServer', x=-47.25, y=16.00, z=-259.52], EntityCreeper['Creeper'/342, l='MpServer', x=-33.50, y=69.00, z=-256.50], EntityPig['Pig'/352, l='MpServer', x=33.28, y=81.00, z=-264.50], EntityPig['Pig'/353, l='MpServer', x=27.78, y=70.00, z=-251.56], EntityCreeper['Creeper'/358, l='MpServer', x=44.50, y=68.00, z=-253.50], EntityZombie['Zombie'/359, l='MpServer', x=42.71, y=69.00, z=-244.51], EntitySheep['Sheep'/360, l='MpServer', x=25.42, y=66.00, z=-229.87], EntityZombieVillager['Zombie Villager'/361, l='MpServer', x=15.26, y=65.00, z=-209.52], EntityPig['Pig'/363, l='MpServer', x=47.45, y=72.00, z=-294.43], EntityPig['Pig'/364, l='MpServer', x=47.50, y=74.00, z=-290.15], EntityPig['Pig'/365, l='MpServer', x=47.55, y=72.00, z=-295.38], EntityPig['Pig'/366, l='MpServer', x=44.50, y=71.00, z=-293.50], EntityPig['Pig'/368, l='MpServer', x=29.53, y=72.00, z=-257.55], EntityBat['Bat'/373, l='MpServer', x=48.07, y=19.14, z=-223.13], EntityBat['Bat'/374, l='MpServer', x=52.37, y=29.10, z=-222.89], EntityBat['Bat'/388, l='MpServer', x=33.22, y=19.24, z=-229.27], EntityBat['Bat'/389, l='MpServer', x=47.27, y=23.49, z=-226.27], EntitySkeleton['Skeleton'/395, l='MpServer', x=45.50, y=40.00, z=-218.50], EntitySkeleton['Skeleton'/396, l='MpServer', x=44.50, y=63.00, z=-211.50], EntityZombie['Zombie'/397, l='MpServer', x=47.50, y=62.00, z=-221.50], EntityPlayerSP['honeyelectrify'/174, l='MpServer', x=-27.35, y=23.92, z=-259.35], EntityTroll['Troll'/175, l='MpServer', x=-19.40, y=31.00, z=-263.60], EntityCreeper['Creeper'/176, l='MpServer', x=-24.79, y=21.00, z=-260.56], EntityTroll['Troll'/177, l='MpServer', x=-19.16, y=31.00, z=-264.93], EntityItem['item.tile.dirt.default'/178, l='MpServer', x=-22.88, y=21.00, z=-259.39], EntityItem['item.tile.stonebrick'/179, l='MpServer', x=-21.60, y=32.00, z=-263.37], EntitySkeleton['Skeleton'/180, l='MpServer', x=-74.50, y=23.00, z=-287.50], EntityCreeper['Creeper'/181, l='MpServer', x=-78.50, y=23.00, z=-286.50], EntityBat['Bat'/184, l='MpServer', x=-88.25, y=15.02, z=-317.83], EntityPig['Pig'/185, l='MpServer', x=-83.78, y=69.00, z=-309.51], EntityPig['Pig'/186, l='MpServer', x=-86.45, y=68.00, z=-312.63], EntityPig['Pig'/187, l='MpServer', x=-92.31, y=67.00, z=-305.35], EntityZombie['Zombie'/188, l='MpServer', x=-64.55, y=69.00, z=-293.51], EntityPig['Pig'/191, l='MpServer', x=-77.50, y=70.00, z=-317.03], EntityZombie['Zombie'/192, l='MpServer', x=-68.50, y=22.00, z=-208.50], EntityZombie['Zombie'/193, l='MpServer', x=-75.48, y=69.00, z=-208.23], EntityZombie['Zombie'/194, l='MpServer', x=-78.20, y=69.00, z=-205.49], EntityTroll['Troll'/195, l='MpServer', x=-49.67, y=15.00, z=-259.24], EntitySkeleton['Skeleton'/196, l='MpServer', x=-50.51, y=38.00, z=-263.70], EntityBat['Bat'/197, l='MpServer', x=-69.14, y=22.14, z=-255.84], EntitySkeleton['Skeleton'/198, l='MpServer', x=-66.50, y=67.00, z=-255.75], EntityItem['item.item.rottenFlesh'/199, l='MpServer', x=-61.21, y=15.00, z=-252.54], EntityTroll['Troll'/200, l='MpServer', x=-61.19, y=17.00, z=-251.76], EntityItem['item.tile.stonebrick'/201, l='MpServer', x=-55.13, y=16.00, z=-250.13], EntityItem['item.tile.stone.diorite'/202, l='MpServer', x=-61.13, y=17.00, z=-250.13], EntityZombie['Zombie'/224, l='MpServer', x=-21.50, y=66.00, z=-193.50], EntityZombie['Zombie'/225, l='MpServer', x=-21.50, y=66.00, z=-193.50], EntityCreeper['Creeper'/226, l='MpServer', x=-6.50, y=66.00, z=-195.50], EntityPig['Pig'/227, l='MpServer', x=-5.50, y=67.00, z=-244.50], EntityPig['Pig'/228, l='MpServer', x=-7.50, y=65.00, z=-244.50], EntityPig['Pig'/229, l='MpServer', x=-6.50, y=66.00, z=-243.50], EntityPig['Pig'/230, l='MpServer', x=-0.78, y=68.00, z=-243.71], EntityBat['Bat'/231, l='MpServer', x=-23.12, y=27.98, z=-233.23], EntityPig['Pig'/232, l='MpServer', x=-16.38, y=69.00, z=-236.72], EntitySquid['Squid'/233, l='MpServer', x=-32.14, y=62.43, z=-220.87], EntityZombie['Zombie'/234, l='MpServer', x=-54.50, y=63.00, z=-195.50], EntityCreeper['Creeper'/235, l='MpServer', x=-51.37, y=63.00, z=-195.22], EntitySquid['Squid'/236, l='MpServer', x=10.89, y=58.09, z=-241.78], EntitySheep['Sheep'/237, l='MpServer', x=6.50, y=69.00, z=-244.23], EntitySheep['Sheep'/238, l='MpServer', x=9.80, y=68.00, z=-243.48], EntityPig['Pig'/243, l='MpServer', x=-2.45, y=69.00, z=-228.55], EntitySquid['Squid'/244, l='MpServer', x=-28.76, y=61.00, z=-223.60]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 297724888 bytes (283 MB) / 939524096 bytes (896 MB) up to 13958643712 bytes (13312 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx13G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 98
	FML: MCP 9.42 Powered by Forge 14.23.5.2772 Optifine OptiFine_1.12.2_HD_U_E3 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version      | Source                           | Signature                                |
	|:--------- |:------------------- |:------------ |:-------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.2       | minecraft.jar                    | None                                     |
	| UCHIJAAAA | mcp                 | 9.42         | minecraft.jar                    | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2772.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.23.5.2772 | forge-1.12.2-14.23.5.2772.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | voxelmap            | 1.9.10       | VoxelMap-Mod-1.12.2.jar          | None                                     |
	| UCHIJAAAA | backpack            | 3.0.2        | backpack-3.0.2-1.12.2.jar        | None                                     |
	| UCHIJAAAA | damageindicatorsmod | 1.0          | Damage-Indicators-Mod-1.12.2.jar | None                                     |
	| UCHIJAAAA | llibrary            | 1.7.17       | llibrary-1.7.17-1.12.2.jar       | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHIJAAAA | iceandfire          | 1.7.1        | iceandfire-1.7.1-1.12.2.jar      | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.10-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13497 Compatibility Profile Context 23.20.822.3584' Renderer: 'AMD Radeon(TM) Vega 3 Graphics'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2772
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) Vega 3 Graphics GL version 4.5.13497 Compatibility Profile Context 23.20.822.3584, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD Ryzen 3 2200U with Radeon Vega Mobile Gfx 
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13497 Compatibility Profile Context 23.20.822.3584
	OpenGlRenderer: AMD Radeon(TM) Vega 3 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by BugmanBugman** [comment]
Please reformat this in hastebin or something. Your optifine is outdated and your forge is severely outdated, and try to switch out damage indicators with The One Probe, it has better integration.

**Comment by BugmanBugman** [comment]
Dude your llibrary is outdated too cmon

**Comment by BugmanBugman** [comment]
Yup reading through your crash report it isn’t IF it says at the top damage indicators, it’s that one. Switch it for TOP

**Comment by londonkxss** [comment]
oh gosh im embarrassed sl dfdjsjd
ill update everything when i can, im using specific versions for forge &
optifine thanks to some modpack, thank you so much ;;

**Comment by AlexModGuy** [comment]
at DamageIndicatorsMod.core.DIEventBus.livingEvent(DIEventBus.java:229)

not our bug
