### ISSUE TITLE
Suggestion: A Sky ruling Mobs at really high altitudes. Fitting with the current ones.

### ISSUE THREAD

**Issue by SirAron111** [Alex-the-666/Ice_and_Fire#1621]
Suggestion: A Sky Ruling Dragon style mob at really high altitudes.

You Made Dragons Living in over world nests and underground layers! (Maybe reduce the max default flight heights to 100 not 125 to prevent normal dragons from going way over the range they can detect people rummaging through their nests I did that in my modpack and it works great.)

You made Sea serpents in the ocean! (Maybe prevent Ink sacks to drop from squids killed by them as they really make a lot of Squid kills XD)

All you need to make now is something to rule the layers of the sky way above the dragon flight height living in clouds (maybe a cloud nest once in a while) I am talking about 2 distinct Monsters for the sky here one smaller and one bigger.

1.	The Harpies they would live in the sky maybe atop maintains and or sky structures. They would fit in very well with the sirens and the gorgon you already have.

2.	Te Big Sky Dragon like creature I mean something like a Quetzalcoatl or a Shenlong like sky snake Asian Dragon to fit in with your sea searpents and your Western stlye dragons. They could have an always on the clouds (cloud block nest maybe) or don’t land at all always in the sky maybe wing less and they just fly hovering very magical.(above 150 blocks height until build height) This would make sky bases loving people a bit less save if suddenly a giant Sky Snake rattles on the front door.

Here are some pictures of what I mean. (Of course not Minecraftyfied yet but your models are all so awesome I bet you could turn this into something useful)
![Harpy ](https://user-images.githubusercontent.com/39855956/61384302-a35cf700-a8b0-11e9-8a2e-0d0fa5217e49.jpg)
![TESL-Shrieking_Harpy](https://user-images.githubusercontent.com/39855956/61384303-a35cf700-a8b0-11e9-986b-ac68c399a112.jpg)
![QMob](https://user-images.githubusercontent.com/39855956/61384315-a821ab00-a8b0-11e9-809e-50432d2853b3.jpg)
![Asia Dragon](https://user-images.githubusercontent.com/39855956/61384316-a821ab00-a8b0-11e9-8801-db51e138d611.png)

**Comment by BugmanBugman** [comment]
By suggestions they mean QOL stuff and tweaks and minor stuff. I don’t think they’re going to a full fledged mob. They have their set list of upcoming mobs, amphs, stym birds, and Hippo’s already fill these niches to an extent
