### ISSUE TITLE
broken ore dictionary thingy

### ISSUE THREAD

**Issue by Morinor** [Alex-the-666/Ice_and_Fire#1622]
So I was restarting my server, and happened to see this in the log.
So I do as instructed.

17.07 22:23:42 [Server] Server thread/WARN * A broken ore dictionary registration with name foodSimpleEgg has occurred. It adds an item (type: class com.github.alexthe666.iceandfire.item.ItemMyrmexEgg) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
17.07 22:23:42 [Server] INFO TO USERS: YES this is a BUG in the mod Ice and Fire report it to them!

**Comment by AlexModGuy** [comment]
fixed
