### ISSUE TITLE
Unable to fly on hippogryph

### ISSUE THREAD

**Issue by BluuJayy** [Alex-the-666/Ice_and_Fire#1624]
Pressing space makes the hippogryph jump up and down. Holding space makes it fly but stays on the same level it was on when it started and when holding space to go up it just goes down. Space is only bound to jump in controls. Flying worked before, now it won't and when i move by foot on the hippogryph it goes to that location but when i get off it stays at that location but i get teleported back to where i got on the hippogryph. I'm not sure if it happens with dragons as I dont have one yet.

**Comment by AlexModGuy** [comment]
what other mods are you using?

**Comment by Stargentian** [comment]
This sounds exactly like #921 
If you have inventory pets try making sure it's up to date. If not, check for other mods that have flight.

**Comment by AlexModGuy** [comment]
dupe #516
