### ISSUE TITLE
Locate Command, Colonies, more entities, ...

### ISSUE THREAD

**Issue by CTH999** [Alex-the-666/Ice_and_Fire#1626]
1. I think all of those things (Sirens Island, Cyclops Cove, and so on), should be on the `/locate` command

2. Colonies:
2a. I got this idea from the "Myrmex". I think that all organisms that would logically form a colonie should. Taking in account their current AI For groups. Dragons form colonies by subtype (Some sort of separation. Their color)? And, maybe certain dragons are less vicios? The dragon colony is a hatching ground. The dragons will lay eggs, and dragons are capable of "making fires so hot that the stone becomes an eternal fuel-source" (Basicly, there is netherack there). The dragons periodicly breath on them, and so on. The younger ones can't easily hunt, so the intermediate aged ones bring animals, so the younger ones can learn, and eat. A small lstorage area, and so on. Sometimes it's in a mountain, sometimes not. (But always protected by more than just giant fire-breathing or equally giant super-chilling reptiles. As if _that's_ not enough!) So, bigger roosts (The reason why it's a colony will soon be apparent)

      2b The "Myrmex" are awesome. However, It would be neat if they expanded their colony as needed (More entrances if needed, moving the queens chamber, breeding grounds, and so on (Some ants breed fungi). Maybe set it up more similar to ants, with the older ones getting separated, and dealing with the waste? (Do research). But, they expand, and expand. Up, and down. They do have _some_ limits. No more than "x" rooms. It must be within "x" blocks of the original queens chambers (Which start at different locations).
Sometimes they will dig tunnels farther, but only to a _great_ reward (Into a farm pen, for instance)
You can, if you are able to make new rooms, order them to make new rooms. Then, they will produce more resin (X amount of food (It looks at how much food it restores)), produce resin. Then, they will use that to expand, digging out blocks. No longer are the tunnels entirely resin. THey use some of the blocks the obtain in the walls as well, and the rest are but in mounds above their base. If they are in a cavern, they will use some of those blocks and more resin to make the hallway, and rooms.
The room creation interface is like mine-colonies, except it puts you in something like spectator, but you can't exit the area in which they can build. You use it, and place what you need. The hologram is always visible, if you are in the interface.All rooms have properties, which can be edited when you click on rooms (The edges of rooms are showed by rods). For hallways, I'm not sure how to set it up, but you click and drag it. You could make hallways straight, with sharp turns, or the halways _also_ the turns! Rooms don't have entrances or exits, they form them when it starts.
There are of course more rooms. Breeding rooms, where eggs are made. Nursureys, where eggs are put to hatch (In little tubes that get sealed by a thin layer. The newborn hatches, pushes out, and is fed. It grows up there, then goes to work. When it's done working, it goes to the "barracks" (Ant colonies are quite organized), which, once placed, in the properties, be set to which type it holds. And, since they know what the egg will hatch into when it's born (Not here. When the egg hatches, then it picks what type comes out, depending on what's needed). There is a production room, where some worker ants produce resin, which is transported to areas being made, then a storage room. it's properties allow you to say how much surplus (How much extra is made), and how many workers are allowed to work on it.

This will only work if you _create_ the colony. ANd, you can even desing the dragon colonies! When you hatch one, there is a chance of a tame dragon mating with a wild dragon, which will yield a tame dragon, and, rarely, tame the wild one! If it stays wild, then the egg might go, or might stay. If it becomes stay, the egg will stay. The colony grows. More dragons can attract more wild dragons, and since there are more tame, also tame those dragons!

Every dragon has a `1/x` (x is the chances of one of them becoming willing to deal with the other branch's (Fire deal with ice, for instance) with another, which is in the config), and that is the percent chance. If one ice and one fire are will to deal with another, great, because they won't fight! If it's a NBT trait, their offspring will be gaurenteed to get the trait, so long as the parent was always with "x" blocks from egg to stage 2. Of course, both of those dragons will be considered traitors... (Or something) (Keeping dragons is difficult) where y is the "whater dragon multiplier". And, it's rerolled every "x" days, or the willingness to deal with another might be a NBT trait! And, ice-fire dragons can mate if they have that NBT tag, but the egg that comes out will probally be the type of the mother, possibly the other type, or most likely neither type, because there is no egg. But, eventually in a controlled envirment, you could get a pen of both types!

And, maybe fire dragons, in roosts, produce _small_ amounts of netherack, for their eggs (Or constantly breathe fire), and ice dragons freeze water, and lower the tempature to hatch their young, if they where brought to a location and bred their.

And, Maybe a "King of Dragons"? Taming requires a boss-fight, but once you gain his respect (Similar to the Cockatrice) , he will give you an egg (There is a queen, or at least was, you figure that one out), to hatch the "leader of dragons" this dragon will be much more powerful, commands respect from all dragons, and so on. Now, if you managed to breed two of them... but, just owning one is enough! Peace will be within all dragons you have tamed! Not other people though. That's why you might want more eggs, to give to friends. Or, hatch it, and run, to make peace rule throught the entire place! Or,something like that. The king idea is good...
Or, when you defeat him, a value get set from 0 to 1, marking you as the person who did that, and the same effect? Is the new egg a third/ fourth/ fifth type of dragon? Maybe the egg hatches into a special dragon that combines  the properties of all three dragons?

I also think that, if you aren't within "x" blocks whenever a dragon hatches, it is born wild, unless another tame dragon is nearby. That means you could have a wild and non-wild roost, and so on.

and, in the nether, a smaller variant of the fire dragon should spawn. The end has it's own types, and so on. Then, you can put in other dim_ids, and set up other dimensions to spawn dragons of your choice! Maybe this planet is fire? (The idea being that you could set it up, where, with AR (Advanced rocketry), you have a planet that is real close to the star, and have lots and lots of fire dragons. Or really far away and only ice?)

And, I, for one, want to be able to launch those bomb-things. the "b" key perhaps does the "bombs"? and, dragons, being so large, should have saddle bags! The large the dragon, the more storage capacity!

(I might re-write this to make it easier to read, if it's hard. I wrote it when I had just come up with them, and my mind was jumping around. So, the thing might be a bit jumpy.)

Of course these are just concepts

**Comment by BugmanBugman** [comment]
I think everything is solid except for the water dragon, it doesn’t really fit. The sea serpent already fills that niche, and the devs only want 3 types of dragons.

**Comment by CTH999** [comment]
true. But maybe the sea serpent is a type of dragon? (They've got it coded in, so they could just advertise it as another one)

And, I can understand why they might just want three. Maybe!
Also, glad you liked it!

**Comment by AlexModGuy** [comment]
no suggestions on this tracker please
