### ISSUE TITLE
Idea for 2 more entities, and slight improvments.

### ISSUE THREAD

**Issue by CTH999** [Alex-the-666/Ice_and_Fire#1627]
Just an idea for two more entities (Goes great with [Locate Command, Colonies, more entities...](https://github.com/Alex-the-666/Ice_and_Fire/issues/1626)

So, I have come up with 2 ideas:

Pegasus (This one's self explanatory. Flying horse, maybe a war-horse, or maybe another, similar one that's a war horse), similar to a hypogrpih, but more, pegasusy.

Unicorn:
These majestic beasts have many uses. They are not the unicorns of fairytails. Inteligent, Ornery and powerful. They won't attack unprovocked, so _don't_ provoke them. When they attack, they can ram into you with their horn, and if that doesn't kill you, the deadly toxin (Poision and wither) will! Now, it get's even better. They are intelligent, so they'll atack your mount first! Unless the mount tries to kill them, then they priotzie you! They travel in groupls (herds), and if you anger one, you anger them all. Seeing as one is deadly...
But, if you do kill them, they will drop 1 unicorn horn, and somehow you can get up to 5 bottles of unicorn blood. If you put a unicorn horn in a crafting table, it will create 9 powdered unicorn horn. Putting that in the table will create 5 gold dust or  silver dust, depending on what type of unicorn you slayed (Gold or silver), but, putting in 3 unicorn blood will make a potion that will remove all negative potion effects, regenerate your health by instant healing, and so on.
A unicorn can be saddled, and can be armoured. It has a part for the head, and a part for the body (The head one has a hole for the spike), and you can tell it to ram into someone.

Improvments
On a dragon, the "B" key should send out those explosive varients, and any animals that have multiple attacks, we should be able to acces all of them. Please.

Of course, this is your mod, so your choice.

**Comment by Xorbah** [comment]
I don't know if you're in the discord or not, but they don't tend to accept
new creature ideas. They already have a huge backlog of work they have to
do that will keep them busy at the very minimum of the next two years
dealing with this mod.

**Comment by CTH999** [comment]
I'm not in the discord, and I'm providing ideas. They don't want to use them, that's fine. Maybe later, they'll think "Hm... what about adding in a unicorn", and subconsiosly the remember this.

Or, they thing "nice idea" or "definitely not"

I'm just drying to help! Let's hope I did (Although, I do hope they do the "Improvments" part)

**Comment by BugmanBugman** [comment]
They don’t (usually) do mobs that are already in other mods. If you want mods that have unicorns and Pegasus, there’s Mo Creatures, the Unicorn and Pegasus mod, and wizardry

**Comment by CTH999** [comment]
@Velocihater 

True, however, they could do it in a different way, and, it's an idea (Personally, I don't really care that much if I have them, it's an idea)

besides. I don't want those mods (Wizardry is the one that's alright in that list, but stil;l no.).

But, who knows! And, like you said: Usually

**Comment by AlexModGuy** [comment]
not suggestions tracker
