### ISSUE TITLE
Silver ore and melt

### ISSUE THREAD

**Issue by Molochnik123** [Alex-the-666/Ice_and_Fire#1629]
Silver ore does not melt in the furnace, what to do?

**Comment by AssaultSquid** [comment]
so i have the same issue and i looked at the recipe for silver ingots using JEI and the furnace recipie for silver ore is AIR+furnace=AIR
im not sure how to fix the reicpe myself but that seems to be the issue

**Comment by BugmanBugman** [comment]
its a known issue don’t worry, it should be fixed in the next update

**Comment by AlexModGuy** [comment]
fixed
