### ISSUE TITLE
Hippogryph wing flap noisy

### ISSUE THREAD

**Issue by PugLyf** [Alex-the-666/Ice_and_Fire#1633]
This isn't a game-breaking issue or even something that affects gameplay at all. The sound hippogryphs make when they are flying is excessive though. In my opinion, they are louder than they should be given their size and they can be heard even beyond the point my game renders the model for them (on far viewing distance). These two things make it impossible for me to travel in areas they spawn without constant loud flapping noises. This isn't much of a bug per se, but I don't think it's intentional and I think it would be an improvement if changes were made to make this not the case.

Edit: After looking into sounds with Dynamic Surroundings it appears to be entity.enderdragon.flap sound that is also being used for the hippogryphs (but you probably already knew that.), however lowering the volume for that specific sound through the mod doesn't affect the sound coming from the hippogryphs at all, but I am able to disable the sound altogether.

**Comment by AlexModGuy** [comment]
change dragonFlapNoiseDistance in the config
