### ISSUE TITLE
Suggestion: Burning grass block turn over normal grass over time

### ISSUE THREAD

**Issue by Tarena397** [Alex-the-666/Ice_and_Fire#1637]
Hello. Burning grass blocks leaving not nice visual appearance in big areas, my idea is that - can you please consider of turning burned grass blocks into normal blocks over time? It would take too much time t go around and manually place dirt blocks, I think many people would appreciate that change as well. Thank You!

**Comment by BugmanBugman** [comment]
This is the issues tracker not the suggestions. This is already being added

**Comment by AlexModGuy** [comment]
Fixed in 1.8.0
