### ISSUE TITLE
Dragon's Breath Particles and Fancy Block Particles

### ISSUE THREAD

**Issue by mxnmnm** [Alex-the-666/Ice_and_Fire#1648]
i was hoping we could get some compat between the two mods and have the number of particles a dragon produces when he breaths go down when fancy block particles is installed.  I go from 200ish fps down to 10 when I'm in the middle of a dragon's shot and the particles are at their worst.  Having the particles reduced when fancy block particles is installed would really be nice.

**Comment by AlexModGuy** [comment]
dragons breath should be less laggy in 1.8.0
