### ISSUE TITLE
Entities turned into stone turn invisible while breaking.

### ISSUE THREAD

**Issue by Carvercarver1** [Alex-the-666/Ice_and_Fire#1652]
Just so it won't slip under the radar: for some reason, when breaking, statue of the entity turns invisible instead of showing the cracks. Several people expirienced the same issue.

**Comment by ValentineBlaze** [comment]
I have had this happen as well for my server

**Comment by Carvercarver1** [comment]
Also, this applies to the freezing: ice cube (either if hit by Ice dragon breath or sword) also turns invisible, probably when cracks appear too.

**Comment by Carvercarver1** [comment]
Issue still persists on 1.8.0.
