### ISSUE TITLE
Recipe conflict

### ISSUE THREAD

**Issue by Drain94** [Alex-the-666/Ice_and_Fire#1654]
Bottle block from forbidden and arcanus (thaumcraft addon) have the same recipe like jar from ice and fire i write to NoMoreRecipeConflict autor bcs this mod dont help with this but i see they have problem with them mod not only with this but with more bugs. 
I know its not too much important think but i love compatibility your mod with thaumcraft and its little problematic on survival servers give every player tons of Jar's bcs they cant craft it.

**Comment by BugmanBugman** [comment]
no recipe conflict should totally fix this

**Comment by AlexModGuy** [comment]
^

**Comment by Drain94** [comment]
Ye like i say i try this and this dont help

**Comment by BugmanBugman** [comment]
How doesn’t it work?

**Comment by Drain94** [comment]
Mod don't show arrow in any workbench to switch recipe only in personal eq craft space but here its impossible craft jar's, on curse mod site people have problem too with 1.12 version, also button(mouse wheel like autor say and custom button) to switching recipe dont work too i try too older version's on 1.12 but every time the same,also try contact to mod owner but last update was in feb.People on site have problems with some mods too on 1.12 version.
