### ISSUE TITLE
Bug report when launching server

### ISSUE THREAD

**Issue by ValentineBlaze** [Alex-the-666/Ice_and_Fire#1660]
this happens for almost every item, and well it sounds so angry so here is the report * A broken ore dictionary registration with name egg has occurred. It adds an item (type: class com.github.alexthe666.iceandfire.item.ItemDeathwormEgg) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Ice and Fire report it to them!

**Comment by AlexModGuy** [comment]
fixed
