### ISSUE TITLE
Multiple Mounting Related Ampithere Bugs

### ISSUE THREAD

**Issue by JessieDagger** [Alex-the-666/Ice_and_Fire#1662]
This is a list of multiple bugs that have been encountered in regards to mounting Ampitheres whilst playing on a Multiplayer Server.

1) After mounting an Ampithere, players can be stuck perma-crouching upon dismounting. (You have to press your crouch key, sometimes a few times, to undo the perma-crouch.) Oftentimes, the player doesn't know they are stuck in this bugged state, because they player walks normal speed, not crouch speed.

2) The perma-crouch bug is also linked to two other bugs. The first of which is, upon mounting your Ampithere whilst in the "perma-crouched" state, the Ampithere will not gain altitude. To the player, they are riding their Ampithere. To the game (and other players), their Ampithere is back wherever the player first mounted it. Dismounting during this bug will cause your Ampithere to teleport back to wherever you originally mounted it, because according to the game it never left that location. It is also important to note that upon mounting while in the bugged crouch state, the amphithere's state will change as if you had also crouch-right-clicked on it (ie; the amphithere will go from staying to following).

3) Like the above bug, there is also a similar issue that occurs due to the "Perma-crouch" bug, but this version is only visual to another player. When a player mounts their Ampithere while perma-crouched, everything appears fine to them, but to a different player, there is a riderless Ampithere flying around, and said Ampithere's owner is still standing wherever they mounted it. Unknown whether this consistently causes a rider or Ampithere to teleport away once the player dismounts.

4) Occasionally, and randomly, when mounting an Ampithere, the Ampithere will fly directly up with no prompting, and will not stop ascending until you use a Dragon Bone Whistle to force it to land.

5) Sometimes when a player dismounts an Ampithere, the Ampithere will vanish until the player reloads the chunk, or relogs.

**Comment by shanzenos** [comment]
I can confirm this issue is still a huge problem. In that weird crouched state players can't properly interact with anything (pressure plates, switches, doors, redstone, chests, villager trades, etc.) and can't even see themselves crouching. It also happens with every mount in the mod, (for us, typically hippogryphs).
