### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Volkosoby** [Alex-the-666/Ice_and_Fire#1663]
So I recently added this mod to my multiplayer server. Everything works fine expect for the dragon eggs. Whenever an egg hatches the baby dragon disappears??

**Comment by Stargentian** [comment]
Try relogging then looking for the dragon. I've had this happen to me long ago when taking dragons out of horns on multiplayer servers, and that made them visible again.
Edit: This looks similar to #1655

**Comment by Volkosoby** [comment]
> Try relogging then looking for the dragon. I've had this happen to me long ago when taking dragons out of horns on multiplayer servers, and that made them visible again.
> Edit: This looks similar to #1655

No like the dragon doesn't appear at all

Oh I figured it out! I just had the dragon hatch speed too high for the server. Thank you for your time.
