### ISSUE TITLE
Bestiary not showing text

### ISSUE THREAD

**Issue by f-sage** [Alex-the-666/Ice_and_Fire#1668]
So I got myself the (1.8.0) latest build from this repository and there is no text on pages except the entry title. I only see the illustrations on their proper place. 
I tried to change modpack to one with vanilla font (no russificator), switching game locale to en/esp/whatever, 'forced unicode font' option, changing 'using vanilla font' cfg to true. None of these worked.

What do I do wrong ppl...

**Comment by zucaluca** [comment]
Assuming you tried adding manuscripts to the bestiary using the lectern already?

**Comment by f-sage** [comment]
Well I tested it on full book in creative so yes
And recipes coded in txt file are not there either

**Comment by Xorbah** [comment]
Could you drop the build here?

**Comment by f-sage** [comment]
you could just clone the repository and run gradle bat file but fine
[iceandfire-1.8.0.zip](https://github.com/Alex-the-666/Ice_and_Fire/files/3486914/iceandfire-1.8.0.zip)

**Comment by MasterOfTheCats** [comment]
You do know 1.8 isn’t even out yet, right?

**Comment by f-sage** [comment]
Yeah I know. This debug version is just labeled 1.8.0.
But I probably should edit the report, thanks.

**Comment by Sholooloo** [comment]
Dude, close this, you're not supposed to even have 1.8 yet, that's your issue

**Comment by AlexModGuy** [comment]
@ f-sage The issue is that the current russian translations were not in UTF-8, so they were not loaded, this is normal behavior and means that someone who knows russian will have to retranslate all of it in UTF-8 format.

**Comment by f-sage** [comment]
What. It's not about russian... None of the languages work.

**Comment by AlexModGuy** [comment]
hmm youre correct, the console is spamming

java.io.FileNotFoundException: iceandfire:lang/bestiary/en_us/introduction_0.txt
