### ISSUE TITLE
Dragon AI and Other Issues

### ISSUE THREAD

**Issue by DiscountDan** [Alex-the-666/Ice_and_Fire#167]
~-Upon leaving and re-entering the server, dragons set to stay would set to wander and fly off into the distance.~
 [] -Dragons set to stay would sometimes simply elect to wander if I mounted and/or dismounted them by accident.
[] -Dragons flight patterns can be wonky. Won't show my friend riding it, and when he'd dismount the dragon  it would rubberband him back to where he'd used to be.
[] -When using the Dragon Horn to bring back a tier 5 dragon, I'd hear it but it would not be around

**Comment by Alex-the-666** [comment]
- just fixed the stay one

**Comment by Alex-the-666** [comment]
Going to spit this into multiple issues

**Comment by Alex-the-666** [comment]
for "When using the Dragon Horn to bring back a tier 5 dragon, I'd hear it but it would not be around" just relog. MC issue dealing with big mobs.
