### ISSUE TITLE
1.8.0 Particles disappearing after a little bit

### ISSUE THREAD

**Issue by zucaluca** [Alex-the-666/Ice_and_Fire#1673]
After about 20 minutes of playtime I was mining stone and all of a sudden I noticed no particles when breaking stone. This is on singleplayer and mods used are JEI, llibrary 1.7.19 and "I and F" 1.8.0.
Before this happened I boated near a dark oak forest (possible pixies), saw a hippocampus, and lured by a siren. I think these are the only 3 that could have possibly did it? Everything else is vanilla if it helps.

**Comment by Spinogaming** [comment]
This happened in almost every version before it too

**Comment by mxnmnm** [comment]
Yea it's always really annoying when it happens and with the update it seems to be happening more frequently.

**Comment by AlexModGuy** [comment]
fixed. i literally tested it by spawning 100 pixies and 20 sirens in a room and waited for 20 mins
