### ISSUE TITLE
Missing textures on all dragons

### ISSUE THREAD

**Issue by MooniePie** [Alex-the-666/Ice_and_Fire#1675]
![2019-08-09_22 56 35](https://user-images.githubusercontent.com/37883399/62816688-2c0a3400-baf9-11e9-8733-a21430c82127.png)
![w h y](https://user-images.githubusercontent.com/37883399/62816689-33c9d880-baf9-11e9-8c0b-155caee3edc5.jpg)

**Comment by AlexModGuy** [comment]
remove your resource pack
