### ISSUE TITLE
Dragon AI problems on 1.8.0

### ISSUE THREAD

**Issue by Carro1001** [Alex-the-666/Ice_and_Fire#1676]
-Dragons sometimes do not function at all until hit, they stand still doing nothing
-Dragons might randomly walk/fly around in circles, doesn't matter if it's wild or not
-Flying dragons constantly drift in the air when mounted flying
-Dragon AI might freeze the game, this is a maybe, not sure if it was the cause

Edit: Extra bugs i found
-Dragons use their breath attacks way less
-If you are directly under a dragon, it might stop attacking you, even if you keep attacking it

**Comment by PlatinumFox** [comment]
Dragons noses are too heavy. dismounting in the air or using dragon flute makes them look straight at the ground and fall

**Comment by AlexModGuy** [comment]
fixed all but " -Flying dragons constantly drift in the air when mounted flying"
