### ISSUE TITLE
Inner left ice dragon horn glitch

### ISSUE THREAD

**Issue by Jceratops** [Alex-the-666/Ice_and_Fire#1678]
When walking, the inner left horn of a ice dragon will move around when walking. The flying is fine.

**Comment by SuspiciousMango** [comment]
I had this same problem and was gonna report it but noticed it had already been reported so here are some images of the problem. Taken using version 1.8.0
![2019-08-13_15 05 12](https://user-images.githubusercontent.com/32881537/62969838-23a54800-bddc-11e9-94b2-a8ba70dfb710.png)
![2019-08-13_15 05 15](https://user-images.githubusercontent.com/32881537/62969837-230cb180-bddc-11e9-9e51-7ad26da1313d.png)
