### ISSUE TITLE
Exiting the game with a baby dragon on your back makes it evaporate upon relogging back into the world

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#168]

**Comment by Alex-the-666** [comment]
This a horrid vanilla bug that I cant seem to fix ;(

**Comment by Quizer9O8** [comment]
Tamed dragons disappear when the game mode is set to peaceful too.

**Comment by Nimflora** [comment]
This is still happening in 1.12.2, by the way.
