### ISSUE TITLE
Unable to put baby dragons on shoulder

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#1683]
Title

**Comment by BlueWither** [comment]
Right-clicking on a stage 1 dragon stops the dragon from moving.
However, the dragon's voice will continue to be heard from around the player and will not be able to shoot arrows.
When I re-entered the world, this state was settled.

**Comment by WreckWrack** [comment]
Also experiencing this, however when I try and set the Dragon to wander or escort it doesn't move and if I try to force it to move using a chain the chain will just extend infinitely.
