### ISSUE TITLE
Dimension Whitelist and Blacklist still won't block flowers from spawning in Atum and other dimensions

### ISSUE THREAD

**Issue by Noble772** [Alex-the-666/Ice_and_Fire#1684]
Even after this update and trying to use both the whitelist and blacklist, both the frost and fire lilies still spawn in other dimensions despite them not being on the whitelist and on the blacklist when using the blacklist. I tried making a new config file to no avail.

**Comment by Foolish-Mammal** [comment]
yeah I had the same problems too
