### ISSUE TITLE
Dragons not rendering properly

### ISSUE THREAD

**Issue by MohawkyMagoo** [Alex-the-666/Ice_and_Fire#1685]
Latest version - dragons dont seem to be rendering properly - missing wings, and bits of throat and tails

**Comment by MohawkyMagoo** [comment]
![2019-08-10_08 42 59](https://user-images.githubusercontent.com/2426129/62819405-bc259900-bb4c-11e9-9adc-dfabd609f948.png)
![2019-08-10_08 47 36](https://user-images.githubusercontent.com/2426129/62819406-bc259900-bb4c-11e9-90c8-489b660eb985.png)
![2019-08-10_08 48 44](https://user-images.githubusercontent.com/2426129/62819407-bc259900-bb4c-11e9-94b1-c9a27ab33c8a.png)
![2019-08-10_08 40 33](https://user-images.githubusercontent.com/2426129/62819408-c6e02e00-bb4c-11e9-9d5a-24fdfd8f9285.png)
![2019-08-10_08 40 52](https://user-images.githubusercontent.com/2426129/62819409-c6e02e00-bb4c-11e9-8e06-d4951bbf5b2e.png)

**Comment by MohawkyMagoo** [comment]
Not using Optifine

**Comment by BugmanBugman** [comment]
By any chance were you using any resource packs?

**Comment by MohawkyMagoo** [comment]
My mistake I still had the better dragons texture pack loaded - all fine
