### ISSUE TITLE
dragon noise needs fixing

### ISSUE THREAD

**Issue by Zygus42** [Alex-the-666/Ice_and_Fire#169]
You can hear dragons flying/flapping as loud as if they were next to you until you can't hear them any more at all.  So no matter how high they are above you, or how many squares away, the noise remains the same.  Vanilla Minecraft reduces villager honking as you move away from them, so the principle is built into the game.

**Comment by Alex-the-666** [comment]
well actually the dragon sounds would cut out if you were more than 20 blocks away from them so that is why it works as it does.

**Comment by Zygus42** [comment]
Sorry to repost in a closed post, but that is not the case.  I'm testing a new world using world stripper, so I can see where the underground dragons are nesting, and you can hear the sound from a very long way away.  Way more than 20 blocks that's for sure - maybe 8 or 9 chunks.
