### ISSUE TITLE
Bug: tamed Dragons don’t work properly

### ISSUE THREAD

**Issue by SirAron111** [Alex-the-666/Ice_and_Fire#1690]
Can’t mount tamed dragons since the update or make them wander/escorte they just stand on the same spot all the time. i even tamed a new one in creative still doesnt work.

**Comment by SirAron111** [comment]
Ok I made a new new tamed one to try it again: Also doesn’t respond to being chained the chain just stretches. He is literally stuck. All modes on the staff for dragons don’t work they say it changed mode to X but still he is just stuck. It also happens to be that I can’t hit it with projectiles they just bounce off.

![2019-08-10_14 13 08](https://user-images.githubusercontent.com/39855956/62821726-c5792a80-bb79-11e9-84a6-6c2b3f756f2f.png)

I even dug out all under him to see if he was on a block or so (this is the 3 dragon I tried btw)
He just gets stuck in air.
What I also noticed is that the dragon always turns his behind to your face. (Does he not like me? It says he is tamed by me)

![2019-08-10_14 17 51](https://user-images.githubusercontent.com/39855956/62821727-c8741b00-bb79-11e9-99ef-78d4185b8cea.png)
![2019-08-10_14 18 06](https://user-images.githubusercontent.com/39855956/62821728-c8741b00-bb79-11e9-886c-7e615d6c9322.png)
![2019-08-10_14 18 17](https://user-images.githubusercontent.com/39855956/62821729-c8741b00-bb79-11e9-973e-b011ac7a701a.png)

**Comment by SirAron111** [comment]
After relogging a few times and making new dragons I got one that works.
But if you fly on it and its big you don’t zoom out enough to properly see the world in 3 person mode and in first person you literally glitch into the dragon even more since it now does dive and ascend flights. You literally can’t flight on it like that. Can’t even see the mobs I want to hit.
![2019-08-10_14 33 34](https://user-images.githubusercontent.com/39855956/62821920-bcd62380-bb7c-11e9-998f-b1fc33f30b10.png)
![2019-08-10_14 33 37](https://user-images.githubusercontent.com/39855956/62821922-bfd11400-bb7c-11e9-8101-32b349632a99.png)
![2019-08-10_14 34 45](https://user-images.githubusercontent.com/39855956/62821925-c5c6f500-bb7c-11e9-8f95-74536f5734ff.png)
![2019-08-10_14 34 46](https://user-images.githubusercontent.com/39855956/62821930-cbbcd600-bb7c-11e9-8d7b-34ae82db1c7b.png)
Would it be possible to add a item like the Cyclops eye as an upgrade that lets you see what the dragon sees (in form of a little side cam so you can actually aim) or simply a better custom mounting/flight  gui

**Comment by gamingboy2003** [comment]
i got the same thing

**Comment by Thethuthinnang** [comment]
I am having the same issues.
