### ISSUE TITLE
Tamed dragon bugs

### ISSUE THREAD

**Issue by Dark0neW0lf** [Alex-the-666/Ice_and_Fire#1693]
When I try to look at the tamed dragon's face they turn around from me like if they are trying to avoid eye contact and I can't ride them when I click on them or pick up a baby dragon. Also baby dragons cannot be hit and when I click on them it stays still and it thinks that it's sitting on my shoulder because I hear it's sounds next to me when I'm far from it.

**Comment by CLittleLunaC** [comment]
I have the same issues with the baby dragons, when I try to pick them up the stay put and look where my player is looking instead of getting on my shoulder the only way I found to get them off my shoulder was to Re-log or pick them up using a Dragon horn.

**Comment by MrTweedpants** [comment]
This is happening to me too! Is there a fix yet????

**Comment by johnpauljhonpual** [comment]
Same here! Updated from 1.6.1 a couple days ago and was greeted with this!

Edit: Found out there was an update recently and now it's fixed!

**Comment by AlexModGuy** [comment]
fixed this in 1.8.1 but forgot to close
