### ISSUE TITLE
Dragon forge never finishes

### ISSUE THREAD

**Issue by kevindwitama** [Alex-the-666/Ice_and_Fire#1695]
Dragonsteel of both types cannot be produced. Two problems may occur - either
a) the progress bar of the forge reaches the end and stays there, nothing else happens, or
b) the progress bar immediately resets when the player interacts with the forge

Tested in both multi- and singleplayer.
Another thing to note after updating to 1.8 is that in multiplayer the server states that there are 2 missing entries in the save:

Missing minecraft:entities:
    iceandfire:dragonice
    iceandfire:dragonfire

Did /fml confirm to proceed. Not sure if related

Mod list/debug info (generated using a manually triggered crash):
https://pastebin.com/g4UfT4BB

**Comment by AlexModGuy** [comment]
java.lang.Throwable
    at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1925)

That doesnt look good. I assume this is a mod conflict

**Comment by kevindwitama** [comment]
> 
> 
> java.lang.Throwable
> at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1925)
> 
> That doesnt look good. I assume this is a mod conflict

Is it actually related to the problem though? Again, the crash was triggered manually by holding down (Ctrl + F3 + C) to provide debug info - it was not caused by mods. However, a mod conflict might still be the cause for the original issue. Might be related to #1691 and #1705.

**Comment by AlexModGuy** [comment]
fixed
