### ISSUE TITLE
Bug: can't fly off with the amphithere

### ISSUE THREAD

**Issue by Renicuzwhynot** [Alex-the-666/Ice_and_Fire#1696]
Whenever I tame an amphithere, and I try to fly down, it tries to both sit and fly.

**Comment by AlexModGuy** [comment]
are you looking up? amphitheres fly like elytras.

**Comment by Renicuzwhynot** [comment]
Yes I know, I have no problem with flying.
I only have the problem with taking off, it makes those buggy movements,
because it both wants to sit and fly when Im trying to take it off.

Alexthe666 <notifications@github.com> ezt írta (időpont: 2019. aug. 10.,
Szo 18:51):

**Comment by AlexModGuy** [comment]
should be fixed in 1.8.4
