### ISSUE TITLE
[Suggestion] base bestiary should contains info on lectern

### ISSUE THREAD

**Issue by Zygus42** [Alex-the-666/Ice_and_Fire#170]
When you make a base/blank Bestiary out of 3 Manuscripts, it's blank and doesn't tell you what to do next.  A 1 page hint about using a lectern to increase the knowledge would be great - just noticed that the completed Bestiary has an Introduction that does just that - I'm guessing that it's meant to be in the base Bestiary when you make it.

Also, Bestiary should not be allowed to be put in Manuscript slot of Lectern, where it does nothing.

Also, vanilla Books should not be allowed to be put into the Bestiary slot of the Lectern, where they use up a Manuscript page, but come out as blank vanilla Books.

**Comment by Alex-the-666** [comment]
1 - it is supposed to come with the introduction when you craft it

2 - Why not? you can pit chicken in the fuel slot in vanilla and it wont work. I dont want to stop people form discovering things :)

3 - same as 2, but ive fixed them actually becoming something already

**Comment by Alex-the-666** [comment]
so ill look into 1 because it seems to be the only real issue here
