### ISSUE TITLE
Deathworm Gauntlet

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#1703]
when in off hand the gauntlet does not show animation

having a gauntlet on an armor stand and an item from while using a gauntlet makes the other gauntlets go off as well.

**Comment by lag42** [comment]
the first part of that isn't just the deathworm gauntlet and i already reported it in this issue
https://github.com/Alex-the-666/Ice_and_Fire/issues/1694

**Comment by AlexModGuy** [comment]
off hand is a vanilla issue.

See: using bow in off hand
