### ISSUE TITLE
Dragon glitch, I don't know why it happened(Maybe with More player models)

### ISSUE THREAD

**Issue by BlueWither** [Alex-the-666/Ice_and_Fire#1707]
![2019-08-11_09 11 16](https://user-images.githubusercontent.com/34153394/62828130-c19ce500-bc19-11e9-87a0-4e3563ceb2ee.png)
![2019-08-11_09 11 53](https://user-images.githubusercontent.com/34153394/62828134-ca8db680-bc19-11e9-848a-4a364d4d43a5.png)
This is a dragon tamed by creative meal
Maybe More player models caused that...

**Comment by BugmanBugman** [comment]
Don’t use More Playermodels, it tends to be incompatible

**Comment by BlueWither** [comment]
Ok

**Comment by AlexModGuy** [comment]
fixed
