### ISSUE TITLE
dragons "pull up" while flying

### ISSUE THREAD

**Issue by aycfes** [Alex-the-666/Ice_and_Fire#1709]
it is MUCH more severe in ice dragons, but from what i've tested, all dragons have dificulty to go down and fly back up afterwards, ice ones also start flying straight up, fast, when you try to hover.
this still happens in the latest version.

i'm almost sure this is cause by the hitbox of the player and the dragon pushing each other away.

**Comment by CosmicGlowsticks** [comment]
Yeah, I noticed this too. It started just now for me, in the nether out of all places. Either that or I didn't notice it till I was in a cave, but for sure it's more severe.

**Comment by Carro1001** [comment]
Fire dragons also constantly drift forward whenever im not inputting anything

**Comment by CosmicGlowsticks** [comment]
> 
> 
> Fire dragons also constantly drift forward whenever im not inputting anything

I get that too!

**Comment by AlexModGuy** [comment]
fixed
