### ISSUE TITLE
Alot of Bugs that are probably incompatibility's with mods

### ISSUE THREAD

**Issue by kohlth** [Alex-the-666/Ice_and_Fire#1711]
minecraft version 1.12.2
Ice and fire version 1.8.0
mods 
[modlist_11-08-2019_01-31-14.pdf](https://github.com/Alex-the-666/Ice_and_Fire/files/3489519/modlist_11-08-2019_01-31-14.pdf)

notable things
did not delete config from earlier version but it still works 
disabled spawning of evil chicken things that look at you and cause damage
lowered detection range of dragons to 40

bugs
-dragons walk in circles 
dragons will constantly walk in circles and sometimes spin in place even when there is prey or a player near by in survival

-dragons disapear most of the time flying up and will fly up at weird angles
dragons will attempt to fly up, sometimes feet first, then they will suddenly disappear

- dragons stuck flying 
the dragons that do survive and dont disapear seem to sometimes stay stuck in one place between blocks mid air 

-magma balls dont move 

-ice spikes dont hurt or knock back on the edge of them 

![2019-08-11_01 51 07](https://user-images.githubusercontent.com/28970985/62830077-f6834a80-bbcd-11e9-8768-c2ffeb5a4f7a.png)
- image of dragon stuck mid flight

**Comment by CLittleLunaC** [comment]
Same here, I've had dragons continuously fly in circles Even after using the dragon bone flute and they dont land

**Comment by AlexModGuy** [comment]
dupe #1449 dupe #1698
