### ISSUE TITLE
Suggestion Tinkers Dragon Parts Fix

### ISSUE THREAD

**Issue by SirAron111** [Alex-the-666/Ice_and_Fire#1714]
With the implemented new tinkers materials you also added the Blizzard and Inferno trait. These 2 have a big downside to them. They may do great damage maybe a bit too much even but you should remove the knockback part it simply prevents people from making more than one swing at a Monster so you have to run after it to kill it as it flys away way too far.

If someone wants knockback it’s easy to add pistons but having it on the material is a bit annoying and many people will not use these parts even if they are strong as you have to run after monsters.

**Comment by AlexModGuy** [comment]
no
