### ISSUE TITLE
Question about Escort Mode

### ISSUE THREAD

**Issue by Thethuthinnang** [Alex-the-666/Ice_and_Fire#1716]
I tamed a wild fire dragon in creative mode, flew on it a bit, then when I landed and put it on escort mode, it just circled (walking) around in one spot without following me as I started walking away. I had landed to fight another dragon that I saw, and when I started fighting it, my tamed dragon didn't follow me and didn't engage in the fight. It just kept circling in place. (It was on a desert, so no obstructions or anything to consider.) Another wild (ice) dragon I tamed in creative mode kept going after rabbits in escort mode rather than following me, until I got nearly render distance away, and then it came over (but kept chasing rabbits and/or circling around in one spot). They both seem to default to circling around in one spot in this mode.  

I guess I'm wondering how dragon escorts are intended to function: if they're meant to focus on what we're doing and what we need (especially when fighting mobs), like tamed wolves or cockatrices in follow mode, or if they're meant to be doing their own thing but keeping their activities within render/flute distance of us or something?  

Thanks for the help and thanks big time for this amazing mod. I play Minecraft basically for the joy and thrill of this mod and really appreciate all the hard work that goes into it.

**Comment by AlexModGuy** [comment]
theyre meant to follow you but not too closely. its bugged and wip
