### ISSUE TITLE
Hippocampus crash upon mounting

### ISSUE THREAD

**Issue by LocatedEagle232** [Alex-the-666/Ice_and_Fire#1718]
Forge: 14.23.5.2838
Mod: 1.7.1
I tamed and put a saddle upon a rapidly moving hippocampus underwater. It continued moving after being tamed. I immediately crashed with an 'Invalid move player packet received'. It repeats anytime I try to join.

I tried to mimic this issue in another world.... I successfully mounted and rode it for at least 1.5 seconds. Then the game glitched and I began slowly falling through the world.

**Comment by anvilknight** [comment]
happend with me and my dragon

**Comment by OMortinho** [comment]
fixed in 1.8 i think

**Comment by ghost** [comment]
> Forge: 14.23.5.2838
> Mod: 1.7.1
> I tamed and put a saddle upon a rapidly moving hippocampus underwater. It continued moving after being tamed. I immediately crashed with an 'Invalid move player packet received'. It repeats anytime I try to join.
> 
> I tried to mimic this issue in another world.... I successfully mounted and rode it for at least 1.5 seconds. Then the game glitched and I began slowly falling through the world.

fixed in 1.8

**Comment by anvilknight** [comment]
it's not for dragons
