### ISSUE TITLE
Mounts issue or maybe seat issue

### ISSUE THREAD

**Issue by ColaLiao** [Alex-the-666/Ice_and_Fire#1721]
after i change ver. 1.7.1 to 1.8.0
other mods which has seat become...
![Seat2](https://user-images.githubusercontent.com/16384174/62891504-76e5af00-bd78-11e9-9dd8-15829e7242e1.png)
i change back to 1.7.1 to make sure and...
![Seat](https://user-images.githubusercontent.com/16384174/62891567-97ae0480-bd78-11e9-95a1-6575aeedb692.png)
all the seats have this problem.

and maybe it also a reason why when i riding a horse and it often teleport me back to where i mounts after 1.8.0

**Comment by Zygus42** [comment]
This is affecting carts as well when you get into them.  Took me hours to narrow it down, but it's iceandfire-1.8.0.  

Files:
    forge-1.12.2-14.23.5.2838-installer-win
    only mods iceandfire-1.8.0 and llibrary-1.7.19-1.12.2

Test:
Put down rail track, put cart on it, get in cart - you get teleported 3 blocks in the direction behind you, still sitting in the cart.  You get out, you and the cart get teleported forwards 1 block.

Does not do this with just llibrary-1.7.19-1.12.2 installed, and does not do it with iceandfire-1.7.1-1.12.2 and llibrary-1.7.19-1.12.2 installed, so is definitely something you introduced in the 1.8.0 version.

This is a pretty serious bug, as it makes all railroads unusable.

**Comment by debaubau** [comment]
I'm having the same issues!

**Comment by Zygus42** [comment]
Rolling back to 1.7.1 "fixes" it.

**Comment by Circine** [comment]
Applies to boats as well

**Comment by WhiteWolfZorra** [comment]
I had this issue (and tested it) on my server and Ice and Fire does this with Decocraft2 and other décor mods as well. It is a compatibilty issue between the mods.
![unknown](https://user-images.githubusercontent.com/47290208/63176710-0d7dce80-c00c-11e9-8f9f-608bc89de3c3.png)

**Comment by ColaLiao** [comment]
@WhiteWolfZorra i don't think it is a compatibilty issue between the mods,
because it's also happen on Vanilla Cart and Vanilla Horse,
and Hippogryph too.

i hope this issue can be hotfix as soon as it can.

**Comment by ColaLiao** [comment]
Mounts issue when riding
https://clips.twitch.tv/CourteousGiantLlamaArsonNoSexy

Mounts issue when flying
https://clips.twitch.tv/AmusedTallSnailUncleNox

**Comment by WhiteWolfZorra** [comment]
No I assure you it is a compatibly issue for the seating. I have tested it
along with a small team of testers. It has also been tested with several
other mods. All the décor and seating mods worked on the server without Ice
and Fire, and as soon as Ice and Fire is added, the seating gets messed up
again. What you linked me there with the random teleporting/glitching isn't
the same thing with the seating. Those are two different bugs. It happens
with all Ice and Fire mounts, dragons, hippogryph, hippocampi, ampitheres,
along with glitching vanilla Minecraft boating. What me and my team of
testers have discovered is it has something to do with each other's
rendering. Whenever someone else enters or leaves another render (or an
entity that renders things like a villager sometimes) the glitching starts
to happen and you get spazzed out and teleported everywhere. With the boat
the same glitching and teleporting happens and the boat sinks.

I do hope there is a hotfix for bugs very soon.

**Comment by Zygus42** [comment]
It's not an incompatibility issue, because as I stated in my note above, it happens with just ice&fire and no other mods - hence is just a bug, not a mod incompatibility.
