### ISSUE TITLE
game crashing on entering a world

### ISSUE THREAD

**Issue by pxchas** [Alex-the-666/Ice_and_Fire#1722]
i've tried everything from reinstalling to trying older versions to giving more ram, but no luck :(
every time i load into a minecraft singleplayer world, i crash with the java has stopped working message?
at first i thought it was because i had pams harvestcraft and the twilight forest too, but when i tried loading just ice and fire it crashed too.

**Comment by AlexModGuy** [comment]
cant do anything without a crash log.
