### ISSUE TITLE
armor texture glitch

### ISSUE THREAD

**Issue by Qwerty111111111** [Alex-the-666/Ice_and_Fire#1723]
The texture of the armor is glitched and all messed up. It looks like a mess. I'm using other mods such as Optifine, but when I tested it with the mod alone I didn't have this problem. If it is Optifine or any other mod that is breaking the armor texture could you let me know?

**Comment by BlueWither** [comment]
Maybe Mo'Bends? or the mod about player's appearance

**Comment by ColaLiao** [comment]
if it's Mo'Bends problem, you can turn off player animation in config to fix it.

**Comment by AlexModGuy** [comment]
mo bends
