### ISSUE TITLE
Crafttweaker recipe issue

### ISSUE THREAD

**Issue by ZariusCane** [Alex-the-666/Ice_and_Fire#1727]
Trying to gate some of the weapons/tools with other items found in my modpack via crafttweaker. Only some of the items will take on the new recipe while the others are also keeping their base recipe.  

DragonsteelFire Shovel, hoe, axe(weapon) seem to keep their base recipes even if I remove them via crafttweaker.  Several of the Dragonsteel Fire Armor were acting the same way, some of them updated to a new recipe while the others kept the base recipe despite removing them. I assume its going to be the same for FrostSteel stuff too.

**Comment by AlexModGuy** [comment]
are you sure you're using the right names for the items?
