### ISSUE TITLE
Suggestion: make Dragons not get stuck on dynamc trees when grifing is true.

### ISSUE THREAD

**Issue by SirAron111** [Alex-the-666/Ice_and_Fire#1728]
Suggestion: make Dragons not get stuck on dynamci trees when grfing is true.

I mean Dragons have a really hard time Breaking the Dynamic trees from the Dyanmic trees mod makes them literally get stuck even If dig when stuck and grifing it true.

They should be able to break the trees when touching them completely. Like knocking them over! It’s mostly the wood that doesn’t break the leaves regenerate to fast I think.

https://github.com/ferreusveritas/DynamicTrees/issues/303

**Comment by stormbringerGT** [comment]
This is true. They used to just walk by and they would knock over, but now they get stuck in them.

**Comment by AlexModGuy** [comment]
fixed
