### ISSUE TITLE
Sleeping and flying Dragons are ignorant to far reaching ranged attacks.

### ISSUE THREAD

**Issue by SirAron111** [Alex-the-666/Ice_and_Fire#1729]
Dragons sometimes don’t retaliate when attacked. If you attack them from outside their range! 

Happens mostly when they fly and have another target they let you hit them and don’t do anything or when they sleep (especially all the time in underground nests) they don’t get angry and attack or maybe it’s that they aren’t knockback resistant enough and cant?

Well anyway Dragons should always get angry and chase away players who attacked them.

**Comment by qnebra** [comment]
Well, that was kind of issues with game balance. Maybe something like "targeting system"?

1. Player shoots dragon:
- dragon waking and gets angry
2. Player has a choice:
- A - shoot dragon
- B - leave
Option A - dragon can determine from which direction arrow comes, more arrows more precise tracking. Forcing player to constant move.
Option B - dragon make some angry noises and go sleep.

Wait, wait, wait. I just describe current system. Duh.

**Comment by SirAron111** [comment]
Dragons should have a better memory than an elephant. And never forget a player who hurt them (if not tamed) as these duds always decide to ignore the player attacking them and instead not even wake up or simply keep flying. They need to decide o I get attacked on range better land on that guys face and fireball him or if they get meleed and lose a lot of hp start to fly away instead of keeping getting stuck on trees…. They should also be smart enough to fly away to safety if they get low I mean if they are stuck somewhere and just keep getting hit doing flip all it won’t be nice to play with them.

Currently on my Modpack I even have increased all sources of damage most mobs (including dragons can do) so they could potentially one shoot player with no armor or skills but the players can just hide under trees and snipe the guy with a few arrows and he is down giving them access to super good armor and loot.

Also since they turn everything to ashes and ice there should at least be a setting to increase or slow down the speed at which the blocks change back. I mean they hit everything just not the players.

And they seem to ignore certain types of projectiles completely. Like electro blobs wizardry magic spells or Immersive revolvers and rail guns.

**Comment by dong1993523** [comment]
me too , they won't move.  They slept all the time.
