### ISSUE TITLE
Arrows not hitting younger dragon stages

### ISSUE THREAD

**Issue by DovahStud** [Alex-the-666/Ice_and_Fire#173]
As the title says, when I shoot any of the younger dragons (stages 1-3 I think), arrows either go right through them or bounce right off.

**Comment by PlatinumFox** [comment]
are you using dragon bone arrows?

**Comment by DovahStud** [comment]
Nope, regular arrows, but that might lead to another possible issue. I can hit larger dragons with normal arrows just fine.

**Comment by PlatinumFox** [comment]
i don't think your supposed to be able to use regular arrows on dragons. 
hitting baby dragons with regular arrows doesn't sound like a bug but the adult ones does

**Comment by DovahStud** [comment]
Okay well I guess I found something at least lol.

**Comment by Alex-the-666** [comment]
@PlatinumFox is correct
