### ISSUE TITLE
Hippogryph moved wrongly!

### ISSUE THREAD

**Issue by debaubau** [Alex-the-666/Ice_and_Fire#1731]
Hi,

We've got a modded server. Up until today hippogryph riding was fine. For some reason, hippogryphs now instantly give a "Hippogryph moved wrongly!" message to the console, start rubberbanding with the player until the player hops off the hippogryph, and where you land is randomly placed between where you started and where you ended before the rubberbanding. We're using the latest Ice and Fire version, just updated a few days ago when it became available.

Flying in creative is fine, flying with broomsticks from EvilCraft is fine. Haven't tested out any other flying mounts yet.

**Comment by ColaLiao** [comment]
Sounds like my issue #1721

**Comment by debaubau** [comment]
> Sounds like my issue #1721

Yeah, I think it's the same issue. Damn :(

**Comment by BugmanBugman** [comment]
See if downloading https://www.curseforge.com/minecraft/mc-mods/randompatches fixes it. It has a patch that fixes rubberbanding.

**Comment by AHrubik** [comment]
I have users experiencing this bug with Horses and Hippogryphs on my server. I will try the mod and report back.

**Comment by AHrubik** [comment]
Random Patches mod solved the users getting kicked for riding the Hippogryphs but they still can't fly with them and the server log spam is quite prolific regarding "Hippogryph moved wrongly".

Flying error message we're seeing is "...vehicle floating too long."

**Comment by AlexModGuy** [comment]
download the gotta go fast mod.

**Comment by AlexModGuy** [comment]
alright, new build will be rolling out this week. included is a coremod(you dont need to install anything extra, it just means I did some hacky code so i can edit vanilla side stuff) that disables both the "moved wrongly" and "moved too fast" messages along with the teleporting that they cause. Atleast while riding a dragon, amphithere or hippogryph.

**Comment by Akhorishaan** [comment]
Looks like this is still happening on 1.8.3, running a multiplayer server and it is constantly spamming moved too quickly/wrongly when anyone is flying around on a hippogryph, with extreme rubber banding.  Sometimes it doesn't even stop when they stop moving, requiring them to disconnect and reconnect to be able to continue playing.

**Comment by tealtoxic** [comment]
I would like to second @Akhorishaan comment. it rubberband when fly with hippogryph constantly spamming moved too quickly
