### ISSUE TITLE
Compatibility issues with exotic birds mod and amphithere spawns

### ISSUE THREAD

**Issue by adalada** [Alex-the-666/Ice_and_Fire#1733]
With just exotic birds and ice and fire installed, amphitheres become super rare to find in jungles. Parrots from exotic birds also don't spawn. Same happens sometimes with cockatrices in savannas.

**Comment by BugmanBugman** [comment]
This isn’t an incompatibility, when you have mods that add a lot of mobs they take up spawn slots in the world spawning system so some won’t get the chance to spawn. Consider removing one of the mods.

**Comment by AlexModGuy** [comment]
^^^^

or adjusting the spawn rates in the config files
