### ISSUE TITLE
Trolls constantly taking damage

### ISSUE THREAD

**Issue by Aerski** [Alex-the-666/Ice_and_Fire#1736]
With Toro's Damage Indicators installed you can see Trolls are constantly taking damage by suffocating in cave walls. If you build to them you will see they're stuck in the roof of the cave because of how big they are (a guess) It's annoying seeing hit points in the ground, and troll hurt noises when exploring caves. 
![Capture](https://user-images.githubusercontent.com/54050857/63055163-4e160480-beb3-11e9-8cd7-84b075a3090c.PNG)

Minecraft Version 1.12.2
Iceandfire-1.8.0-1.12.2
Forge 1.12.2-14.23.5.2838
Windows 64 bit VER 1809 os build 17763.615

**Comment by BugmanBugman** [comment]
Don’t use damage indicators, use dynamic surroundings because their hit points aren’t buggy and only appear when you see the monster and deal damage
