### ISSUE TITLE
Stone statues bug

### ISSUE THREAD

**Issue by CosmicGlowsticks** [Alex-the-666/Ice_and_Fire#1739]
Was anything changed about getting statues from petrified mobs? Even in survival a silk touch pick just destroys it instantly and nothing drops, but the hitbox is still there and whatever item (like a skeleton's bow) is still there just floating. And troll eyes stay too, just floating there ominously. Kinda creepy in the dark. After the mob turns invisible, you can petrify it again. It has a buggyish texture. Hitting it again gave the same result. I tried this a third time and it finally dropped a statue.

**Comment by AlexModGuy** [comment]
dupe #1835 #959
