### ISSUE TITLE
Dragon fire doesn't despawn

### ISSUE THREAD

**Issue by DrPenguinni** [Alex-the-666/Ice_and_Fire#1740]
Some of the fire left by a dragon doesn't despawn. This fire also deals no damage and when you punch it, the ground below the fire breaks instead. It's like it's not even there.

**Comment by BugmanBugman** [comment]
Why didn’t u f2?

**Comment by NetherDragon55** [comment]
I noticed that too. The only way to make it despawn is by placing and removing a block where there’s the fire.

**Comment by mxnmnm** [comment]
Simply right clicking it with an empty hand makes it go away it seems to be some sort of syncing issue but idk
