### ISSUE TITLE
incompatibility with multiple mods

### ISSUE THREAD

**Issue by Bruno2592** [Alex-the-666/Ice_and_Fire#1741]
in the new version 1.8 of ice and fire, I am having crashes when starting the game, which was not the case in the previous version, the mod is having incompatibility with other mods

**Comment by BlueEyesEthan** [comment]
This happened to me too only 2 mods (not including llibrary) worked

**Comment by BugmanBugman** [comment]
1. How does the mod have incompatiblities with its own library
2. Why aren’t you posting any crash reports
3. How do you know it’s this mod

**Comment by Bruno2592** [comment]
Because I do not know

**Comment by BugmanBugman** [comment]
"Because I do not know" Why in the world would you open this?
