### ISSUE TITLE
Iced and Flaming sword items offset in inventory

### ISSUE THREAD

**Issue by GundunUkan** [Alex-the-666/Ice_and_Fire#1742]
![image](https://user-images.githubusercontent.com/26864687/63186164-72651300-c064-11e9-9ce1-4b8220e5f4ce.png)
 Nuff said lmao

**Comment by ColaLiao** [comment]
i don't have this issue, my Iced and Flaming sword items position is correct.

**Comment by AlexModGuy** [comment]
not able to reproduce
