### ISSUE TITLE
Hierarchical Pathfinding

### ISSUE THREAD

**Issue by SamuraiShogun1102** [Alex-the-666/Ice_and_Fire#1744]
I have an idea on how to improve the AI pathfinding on all the creatures of ice and fire, it's something I got from a video from Tango Tek on his new WIP improved villagers mod found in youtube in one of his videos of the part 1 of the improved villagers mod, eventually he worked hours on pathfinding the miners by using a special pathfinding system called Hierarchical Pathfinding to help improve the pathfinding on his villagers, if Ice and Fire have this feature, it will be a great performance for the AI that include Amphitheres, Dragons, Hippogryphs, Hippocampuses, Myrmex, Sea serpents, Cyclops, and Trolls so I recommend Ice and Fire should have this pathfinding system.

**Comment by AlexModGuy** [comment]
dupe #1449
