### ISSUE TITLE
Pre 1.8.0 version dragons seem to be converted to male only

### ISSUE THREAD

**Issue by PT400C** [Alex-the-666/Ice_and_Fire#1746]
Hey,

I noticed that old dragons (pre 1.8.0) in their caves are now all male dragons - didn't encounter one female out of 20 dragons. 

Doesn't maybe the datafixer work properly - so it misses gender data of the dragons when translating the mobs to their 1.8.0 version?

PT400C

**Comment by BugmanBugman** [comment]
The old Gold and Silver dilemma. I think it’s encouraged to restart your world, all the old structures are obsolete and outdated anyways.

**Comment by PT400C** [comment]
That's what I don't understand. Until this year I was JurassiCraft's lead programmer and we always assured the best compatibility between versions. So when there were mayor changes, we created features to convert old to new data. And even if old stuff was generated and "obsolete" it would still work just fine (ice and fire also messed up the loottables in old dinosaur structures). Avoiding this would save users a lot of time. Now I can drop my world into NBTExplorer and wipe chunks with old structures manually - not the user-friendliest I could think of.
