### ISSUE TITLE
Dragons don't really guard their treasure

### ISSUE THREAD

**Issue by GundunUkan** [Alex-the-666/Ice_and_Fire#175]
I've noticed that it is fairly easy to steal from a dragon. You just have to wake it up (I'm talking 'bout the big ones underground) and hide. It'll break free, fly up and never return. Then, all those treasures are all yours. Same thing with the roosted stage 3 draggies. I think that the dragons should have some sort of home points around their lairs or roosts, like villagers stick around their villages, otherwise it's quite easy for the player to get really rich and powerful without having to fight and kill the dragon.

Also, I've got a question: Aren't there supposed to be nests with eggs inside some of the big ones's lairs? 'Cuz I've never seen any, and in the "Previews" spoiler in the forums it shows the image of one. Am I not getting something right here? XD

**Comment by Alex-the-666** [comment]
answer to your question: there used to be nests there but players just kept stealing the eggs instead of fighting the dragon so now a female stage 4 and 5 drop eggs

**Comment by Alex-the-666** [comment]
Dragons should now, when flying, stick in a 128 block radius around their cave/roost
