### ISSUE TITLE
Stymphs don't have drop

### ISSUE THREAD

**Issue by BlueWither** [Alex-the-666/Ice_and_Fire#1750]

**Comment by BugmanBugman** [comment]
Yes they do? Do you not have any mods that add copper and bronze like thermal foundation? I killed one the other day and they dropped perfectly fine

**Comment by BlueWither** [comment]
I'll try
If they drop something, I'll close this

**Comment by BlueWither** [comment]
I killed some stympharian birds in creative mode, but they didn't drop anything.
I don't have copper and bronze
In 1.8.0

**Comment by BugmanBugman** [comment]
Dude I literally told you why they don’t drop, because you don’t have any copper or bronze in your game

**Comment by BlueWither** [comment]
It dropped iron ingots and nuggets, and their feathers at 1.7.1.
