### ISSUE TITLE
Chains crash the game.

### ISSUE THREAD

**Issue by VulcanVet** [Alex-the-666/Ice_and_Fire#1752]
Attempting to attach chains to a cobblestone wall crashed the world. Now unplayable as crashes immediately on startup. Attached crash reports. Chains attached on the other end to vanilla horse and animania leghorn hen.
[crash-2019-08-18_16.19.13-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/3513198/crash-2019-08-18_16.19.13-client.txt)

[crash-2019-08-18_16.09.09-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/3513197/crash-2019-08-18_16.09.09-client.txt)

**Comment by ghost** [comment]
Already fixed just download 1.8 again.

**Comment by AlexModGuy** [comment]
fixed
