### ISSUE TITLE
weird dragon ai problem

### ISSUE THREAD

**Issue by KatherineLee318** [Alex-the-666/Ice_and_Fire#1753]
this is on the mod pack world of dragons on 1.12.2 with 1.8.0 of ice and fire.

while watching players fight dragons I have noticed the ai acting strangely they barely attack at times and just do some overall weird things.
[https://youtu.be/W8OT9EM7B20](url) "sorry accidently posted before adding this"

**Comment by AlexModGuy** [comment]
dupe #1449
