### ISSUE TITLE
Dragon baby picking up in MP doesn't render correctly for owner

### ISSUE THREAD

**Issue by lolsteamroller** [Alex-the-666/Ice_and_Fire#1754]
Picking up baby dragon doesn't render for the one who picks up, the dragon stays in the same place.

However, it does display correctly for other players nearby you. Disconnecting drops the dragon from the shoulder. Feels weird though. No errors from the server, running Forge with some other mods?

Any idea on how to fix it, or find the mod interferring? Feels weird to have other clients looking ok. 

Screenshots attached.
![drake_1](https://user-images.githubusercontent.com/7465747/63229553-218f1f00-c20a-11e9-95a3-9131da5607c8.png)
![drake_2](https://user-images.githubusercontent.com/7465747/63229554-2227b580-c20a-11e9-8984-8e0fdbadb4b4.png)
![drake_3](https://user-images.githubusercontent.com/7465747/63229555-2227b580-c20a-11e9-8a72-c941d5596e42.png)

**Comment by TheSpiderDungeon** [comment]
Happens in singleplayer for me. The dragon locks in place on the ground and turns its head to face the same direction you are, but it's not on the shoulder.
