### ISSUE TITLE
Myrmex crashes the game when it tries to make its burrow on structures

### ISSUE THREAD

**Issue by SirAron111** [Alex-the-666/Ice_and_Fire#1755]
Myrmex crashes the game when it tries to make its burrow on structures
https://pastebin.com/zTpUERcN

**Comment by AlexModGuy** [comment]
>    at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.constructWorldData(GenericStructure.java:329)

not us, Recurrent Complex issue
