### ISSUE TITLE
Heroes expansion problem

### ISSUE THREAD

**Issue by HunterM543** [Alex-the-666/Ice_and_Fire#1756]
![2019-08-18_15 18 34](https://user-images.githubusercontent.com/46468042/63231151-44024780-c1cc-11e9-944f-5d0f231b8a58.png)
![2019-08-18_15 18 46](https://user-images.githubusercontent.com/46468042/63231153-482e6500-c1cc-11e9-8625-18ed18eb2840.png)
![2019-08-18_15 20 34](https://user-images.githubusercontent.com/46468042/63231154-4d8baf80-c1cc-11e9-8b88-2c55f0ed6d74.png)
![2019-08-18_15 20 36](https://user-images.githubusercontent.com/46468042/63231156-4fee0980-c1cc-11e9-8fbc-b2459c2681cc.png)
 
All of these errors happen when I have heroes expansion and lucraft, please help and fix

**Comment by BugmanBugman** [comment]
What makes you think that this is caused by ice and fire. It’s literally optifine.
