### ISSUE TITLE
Config is missing options to disallow mobs from attacking passive (animal) mobs

### ISSUE THREAD

**Issue by stormbringerGT** [Alex-the-666/Ice_and_Fire#1761]
Minecraft 1.12.2
iceandfire-1.8.0-1.12.2

The config file used to have an option so that dragon's wouldn't attack passive animal mobs. This option seems to have been removed in the current version.

Also consider adding it for Hippogriffs as they can't depopulate an area of animals in short order.

**Comment by AlexModGuy** [comment]
i dont ever recall that being an option.
