### ISSUE TITLE
Dragons breath, mainly Ice Dragon one is underpowered

### ISSUE THREAD

**Issue by AspectSk** [Alex-the-666/Ice_and_Fire#1763]
Yes it might seem silly but dragons are really underpowered, mainly regarding their breath, and mainly ice dragons.

Btw i cannot be sure if this is a big bug or a feature so if it is a bug just know that i though it was a feature

When you overhauled dragons, you mentioned you reduced the damage of their breath, that was the only nerf aside from reducing the damage that the fire/ice balls deal to the area,entities and general range of the attack which is fine but the problem is that you didnt reduce it, you completely erased it, i did some tests and found out that the breath doesnt do anything aside from lighting ground on fire or putting spikes there

Generally i think the Ai dragons is too passive and weirder than it was in the previous patch, i can easily without a single problem stand the other way from a stage 5 dragon and shoot it and he wont do anything about it, i think he should start actually breathing fire or trying to get close and not just stand there seemingly trying to run away, if i could i would post a video of this but i cant, he also seemed to like to spin in circles, this is the same issue as in one of the issues a bit below this one

I also think that the dragons were much easier to control in the older version stopping when you stopped holding the movement key and not acting like some sort of weird amphitere-normalflyer hybrid and continuing for some distance which is too long for it to be an insta stop and too short to be a continuous thing.

**Comment by AlexModGuy** [comment]
doubled breath damage and increased range. ice dragon breath now does 50% more damage
