### ISSUE TITLE
Dragons not spawning at all

### ISSUE THREAD

**Issue by FirstFandomFangirl** [Alex-the-666/Ice_and_Fire#1764]
I have played around with this mod in the past, and really enjoyed it, so today I popped it out of storage into my mod folder and started it up in survival. After poking around the map a bit, I noticed that I hadn't run across any dragon roosts. When I played with this mod before, I found quite a few pretty quickly, so I thought this was odd, and switched to creative mode to search the overworld. I found a gorgon, cyclops, hippogriffs and hippocampi, death worms, etc. but no dragons. Figuring I got a bugged world, I deleted it and loaded a new one. Still no dragons. I tried once more, increasing the chance for dragon roosts to spawn even, but even worlds where I extensively searched the overworld I found nothing. Finally, I went and removed every mod but Ice and Fire and LLibrary from my mods folder, assuming it was clashing with one of them, and loaded it up once more. Still no dragons. Every other creature, but no dragons. I also dinked around in spectator mode a bit to search underground, and I didn't spot a single dragon cave either. Pretty disappointing, not sure what this is causing this since it hasn't already been mentioned and hoping for a fix soon.

**Comment by BugmanBugman** [comment]
try deleting your config, perhaps it’s something wrong with it. Did you by accident disable the structures?

**Comment by FirstFandomFangirl** [comment]
That worked! Thank you very much!

**Comment by jaykay0972** [comment]
> try deleting your config, perhaps it’s something wrong with it. Did you by accident disable the structures?

hey could you help me too which config?

**Comment by TiagoGamer26** [comment]
> try deleting your config, perhaps it’s something wrong with it. Did you by accident disable the structures?

what config

**Comment by FirstFandomFangirl** [comment]
> > try deleting your config, perhaps it’s something wrong with it. Did you by accident disable the structures?
> 
> what config

Your minecraft or instance folder > config > "iceandfire-common". Delete the file by that name, then run your game again and it'll generate a fresh one.
