### ISSUE TITLE
crashed while flying in creative mode

### ISSUE THREAD

**Issue by Robomnz** [Alex-the-666/Ice_and_Fire#1766]
[crash-2019-08-20_17.41.57-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/3518866/crash-2019-08-20_17.41.57-server.txt)

**Comment by BugmanBugman** [comment]
Looks like the same issue as #1762 , should be fixed by Alex though

**Comment by AlexModGuy** [comment]
fixed
