### ISSUE TITLE
[Suggestion]Dragon Explorer Map

### ISSUE THREAD

**Issue by migmolrod** [Alex-the-666/Ice_and_Fire#1768]
My idea would be to add a new trade for villagers (vanilla cartographers and/or Ice and Fire shamans come to my mind) called Dragon Explorer map (to be consistent with already existing maps from the 1.11: Exploration Update).

It would serve to locate the nearest dragon underground lair, pretty much like Woodland Explorer maps and Ocean Explorer maps do with their respective structures.
https://minecraft.gamepedia.com/Explorer_Map

Is that even possible? I could see it as a really great addition.

**Comment by AlexModGuy** [comment]
not suggestion tracker
