### ISSUE TITLE
Armor Texture issues

### ISSUE THREAD

**Issue by TheSexyYeti** [Alex-the-666/Ice_and_Fire#1769]
No one else on the Minecraft Forum will help me with this. So I figured maybe one of the mod author from the effected mods could help me. But your armors, and armors from other mods have these messed up textures. Do you have any idea what's doing this?.
![2019-08-17_22 01 08](https://user-images.githubusercontent.com/50222286/63358122-89438800-c338-11e9-86d9-263e69f87701.png)
![2019-08-17_22 00 55](https://user-images.githubusercontent.com/50222286/63358130-8ba5e200-c338-11e9-8fde-7f51659c9cb5.png)

**Comment by AlexModGuy** [comment]
dupe #1723
