### ISSUE TITLE
World Gen Issues - Possibly Mod Conflicts?

### ISSUE THREAD

**Issue by Schyler-Lowry** [Alex-the-666/Ice_and_Fire#1770]
I tried testing this mod with the following other mods installed:
Millenaire
Recurrent Complex
Mowzie's Mobs
Dynamic Trees

I don't believe my pack uses any other world gen mods, besides Open Terrain Generator? Either way I'm using vanilla world gen settings. The issue I have encountered can be seen in these screenshots:
https://i.imgur.com/Glvuhub.jpg
https://i.imgur.com/jQmrcXJ.jpg

As you can see, in the first one, the structures are all spawning much too close to each other, as well as other issues. And in the second one, the structure does not look like it's supposed to spawn like that all.

**Comment by sen2000** [comment]
not sure if this is where I put it but when the mod updated my amphitheres don't land when im riding them anymore, they just glitch at the ground until I look forward then they continue flying

**Comment by Schyler-Lowry** [comment]
I fixed my issue by removing any non-vanilla world gen mods like FFH, Biome Bundle, OTG, etc. Using this with Recurrent Complex, Millenaire, Electroblobs Wizardry, and I'm about to try it with Quark now, but I suspect that I will not have any issues with the addition of Quark.

**Comment by AlexModGuy** [comment]
first issue is just RNG Jesus not wanting you to have a good time.

Second issue is the dragons lair trying to find a good place to spawn the structure, but the hill isnt very forgiving. No mod conflict.
