### ISSUE TITLE
Killed a dragon, picked up loot and game crashes on launch

### ISSUE THREAD

**Issue by LegitGamer1017** [Alex-the-666/Ice_and_Fire#1772]
[crash-2019-08-20_20.22.02-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/3523182/crash-2019-08-20_20.22.02-client.txt)
So I stumbled upon a roost and i killed the dragon. I looted the chest, putting the items into my backpack (from Useful Backpacks mod) and my game just crashed, and each time I load up the world, it crashes again. I don't remember the specific item I put in the backpack (I was doing it quickly as I needed to do something) but I know it was from the chest. I attached my crash log to see if that helps at all. I run a lot of mods and I'm trying to see which one broke my game. 

EDIT: Reading the crash log, it seems like the error is from: 
"at com.github.alexthe666.iceandfire.block.BlockGoldPile.func_176205_b(BlockGoldPile.java:53)" 

I do remember breaking the Gold Pile and picking the nuggets up. 
I was able to pause the game and take a screenshot. I can attach it if needed. Currently, my character is standing on a gold pile if that's relevant.

**Comment by AlexModGuy** [comment]
> 	at baritone.ad.b(Unknown Source)
	at baritone.ad.a(Unknown Source)
	at baritone.ad.a(Unknown Source)
	at baritone.j.a(Unknown Source)
	at baritone.j.onTick(Unknown Source)
	at baritone.x.a(Unknown Source)
	at baritone.x$$Lambda$1999/1556874384.accept(Unknown Source)

Baritone issue

**Comment by LegitGamer1017** [comment]
alright, thank you.
