### ISSUE TITLE
so there seems to be a conflict with more player models 

### ISSUE THREAD

**Issue by hc1219** [Alex-the-666/Ice_and_Fire#1774]
In the new minecraft 1.12.2 build 1.8 the dragons models bug out when you are riding them.
This problem fixes when more player models is uninstalled.
the only mod that changed was ice and fire .
![well then](https://user-images.githubusercontent.com/44955250/63437732-4e992880-c3e8-11e9-9233-d380ef063066.png)

**Comment by AlexModGuy** [comment]
fixed
