### ISSUE TITLE
Amphiteres can drown when called with a flute

### ISSUE THREAD

**Issue by Ernesto-Velasco-Aguilar** [Alex-the-666/Ice_and_Fire#1776]
Amphiteres will go into land mode when using the flute, if the amphitere is over a body of water when being called it will dive into the seafloor and drown unless you make it follow you to the surface (you can't ride it because the game won't let you ride on water, and the amphitere won't try to swim to the surface) this may happen as well when shotting wild ones.

**Comment by AlexModGuy** [comment]
fixed
