### ISSUE TITLE
Full compatibility with In Control

### ISSUE THREAD

**Issue by aran-gilman** [Alex-the-666/Ice_and_Fire#1778]
In Control ([link to curseforge](https://www.curseforge.com/minecraft/mc-mods/in-control)) is a mod that lets the user configure mob spawns, and I've been using it to limit mob spawns to certain dimensions.

Unfortunately, it does not work for all Ice and Fire monsters in all dimensions. For example, I can't seem to prevent sea serpents and cockatrice from spawning, and I can only prevent hippogryphs from spawning in dimensions other than 0 (e.g. if I configure In Control to not spawn them in dimensions 0 and 10, they will not spawn in dimension 10 but will spawn in 0).

I did see the issue for providing expanded mob spawning controls to the config (though I closed the tab and now can't find it), but I think supporting In Control is still worthwhile because it gives modpack creators access to additional tools, such as allowing mobs to spawn only in Lost Cities' cities or to have different stats.

**Comment by AlexModGuy** [comment]
most of the mobs dont spawn traditionally, but rather as a part of world gen. Yo
