### ISSUE TITLE
[1.12.2] "Splitting II" Trait doesn't appear to work.

### ISSUE THREAD

**Issue by SonicX8000** [Alex-the-666/Ice_and_Fire#1785]
Minecraft: 1.12.2
Forge: 14.23.5.2838

Mods: 4
iceandfire-1.8.1
llibrary-1.7.17-1.12.2
Mantle-1.12-1.3.3.55
TConstruct-1.12.2-2.12.0.157

-----

Tinker's Material: Dragon Bone for Arrow Shafts grants the 'Splitting II' trait... however... it doesn't appear to be working correctly as no arrows are 'split' after firing a bunch of them.

In a test I did... I've fired 20 Cobalt Arrows with the 'Splitting II' trait and none of them spawned an extra arrow... however if I use Bone Arrow Shafts which grants 'Splitting' then the Arrows do split from time to time.

Perhaps maybe the Splitting trait goes up to Rank 1 only and then any higher it breaks or something? Maybe there could be it's own Trait like 'Spreading' where you fire 3 arrows at once but uses up more ammo in a way, if that could work out?

*EDIT*
Viewing the NBT stuff on the Dragon Bone Arrow Shaft... it looks like the "Splitting II" Trait is called 'splinters2' while for Bone Arrow Shaft's "Splitting" it's called 'splitting'.

Also... the "Splitting II" Trait's Tooltip while at a Tool Forge appears to have a typo. Reading as...

"Two for one!\The sudden acceleration of releasing an arrow cause it to split into two."

-----

P.S.
Unsure if intended... but while the Inferno Modifier & Blizzard Modifier can't be mixed... you can mix the Fiery Modifier with the Blizzard Modifier which will freeze mobs but then instant-thaws them. They still get the Slowness III effect, however.

You can also mix the Inferno II & Blizzard II Traits together if you put them on a Shuriken.

**Comment by BugmanBugman** [comment]
I think the inferno thing is intentional, fiery should not work with blizzard too
