### ISSUE TITLE
Dragons Teleporting Into The Void [1.8.1 bug]

### ISSUE THREAD

**Issue by Kingdomall** [Alex-the-666/Ice_and_Fire#1786]
Hello I/F team, I hope that you truly take this report seriously.
In a couple of servers since 1.8.0 I as well as several others have been teleported underground while riding a fire dragon. It happens only during flight and normally only when the dragon is flying really fast or hovering. I was hoping that this issue was fixed for 1.8.1, but it's not. The Wyrmroost developer Wolf says it has something to do with the hitboxes. Maybe it's that?
We also had a similar issue with Hippogryphs. A player was flying on one and was teleported into the ground, suffocating.
I can provide logs but I'm not quite sure if it will help. Note: Every bit of "___Fell out of the world" was the owner Zyranna killing herself, but every other player was killed by this bug. In one instance in 1.8.0, WolfShotz experienced the issue and two messages labeled "Received passengers for unknown entity" popped up right before he died due to the void.
_[21:36:00] [Client thread/WARN] [net.minecraft.client.network.NetHandlerPlayClient]: Received passengers for unknown entity
[21:36:01] [Client thread/WARN] [net.minecraft.client.network.NetHandlerPlayClient]: Received passengers for unknown entity
[21:36:19] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] WolfShotz fell out of the world_ This was 1.8.0.

In 1.8.1, logs display no warning whatsoever besides the "___ Fell into the world" message.

_[14:36:13] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] torterrta fell out of the world
[14:36:19] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] <torterrta> oh fuck oh fuck
[14:36:22] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] <torterrta> my dragon_

This is as much detail as I can give. I hope this helps.

**Comment by AlexModGuy** [comment]
fixed in 1.8.4
