### ISSUE TITLE
Dragon armor and dragon texture phasing in and out

### ISSUE THREAD

**Issue by 2fwess** [Alex-the-666/Ice_and_Fire#1787]
There is an issue in v.1.8.1 probably with the new stitching textures that causes the dragon texture to phase in and out. As you can see in the video attached it occasionally turns the dragon from male to female texture as well as make all the armour disappear

**Comment by 2fwess** [comment]
[Broken textures copy.mp4.zip](https://github.com/Alex-the-666/Ice_and_Fire/files/3533898/Broken.textures.copy.mp4.zip)

**Comment by AlexModGuy** [comment]
dupe #1856
