### ISSUE TITLE
Dragons have autism

### ISSUE THREAD

**Issue by samakotleta** [Alex-the-666/Ice_and_Fire#1789]
1.8.1

Documented case of dragon autism can be observed there:
https://cdn.discordapp.com/attachments/608170288269754372/614355394235727877/kek.webm

**Comment by MetroNight** [comment]
That poor bastard was just having fun chasing his tail and you ran up and punched him to death

**Comment by UnlimitedTurtlez** [comment]
i agree with sam and they do not protect their nests at all that should be the highest priority

**Comment by AlexModGuy** [comment]
fixed
