### ISSUE TITLE
Issue?

### ISSUE THREAD

**Issue by Chancho91** [Alex-the-666/Ice_and_Fire#1790]
Not sure if this is an issue, but is the lower jaw of the ice dragons supposed to be longer? 
![2019-08-23_14 12 10](https://user-images.githubusercontent.com/24527489/63614468-26a8f100-c5b1-11e9-96c4-59d5358f1115.png)
![2019-08-23_14 18 28](https://user-images.githubusercontent.com/24527489/63614469-26a8f100-c5b1-11e9-94c3-e060f9a420d5.png)

**Comment by AlexModGuy** [comment]
yes
