### ISSUE TITLE
Plenty of bugs with tamed amphiteres

### ISSUE THREAD

**Issue by Ernesto-Velasco-Aguilar** [Alex-the-666/Ice_and_Fire#1793]
**1-**around 10% of the times, when flying with the amphitere from point A to B the server will not detect the player getting on the amphitere, instead it thinks the player its still standing on point A, so if you get off the mount you will be teleported back to point A.
Worst part its that the server DOES detect where you move the amphitere to, so you will be separated from your pet and you will have to walk all the way back to it. 

If you get off the amphitere while you were on top of water, amphiteres don't avoid sinking on water so your pet will just drown.

**2-** The amphitere won't go into land mode while you ride it, even if you hit the floor, it will however work if you use the dragon flute

**3.** When you get off the amphitere while its flying, it will often keep flying on the direction it was facing when you got off (tho this could make for cool feature where your amphitere keeps flying around 6 seconds and then lands, so you could jump into a fight and have your pet go to safety).

**Comment by AlexModGuy** [comment]
fixed 1, fixed 2
