### ISSUE TITLE
Hippogryph disapearing 

### ISSUE THREAD

**Issue by rottenbottle** [Alex-the-666/Ice_and_Fire#1795]
So this happened twice in fact, the second time it almost killed me. The first time this happen is when I'm on Hippogryph then try /tp to somewhere else and it disappear which I can understand but the second time it literally disappeared mid-air while flying and almost killed me. I'm on a server.

**Comment by rottenbottle** [comment]
mod version is the newest one version 1.8.1 for 1.12.2

**Comment by AlexModGuy** [comment]
fixed in 1.8.4
