### ISSUE TITLE
Tamed dragons walk/fly away when in stay-mode

### ISSUE THREAD

**Issue by Kajtetto** [Alex-the-666/Ice_and_Fire#180]
I have tamed a dragon and raised it to stage 5 in creative, right clicked it with the dragon staff so it was supposed to be in stay-mode and went to build a tunnel when suddenly I heard wings flapping. I flew back to where i have left the dragon and saw up and found the dragon taking off to the skies. The only way I could get it back was to fly after it and mounting it and flying it back down. But even then when i thought it finaly was staying (because I clicked it with the staff once more), it flew away again like one second after i've clicked. It was not such a big problem because i was in creative, but it can be really problematic if you tame and raise a tier 5 dragon in survival and when you log off and back on the other day the first thing it does is to fly away. Especially on a server. Then you won't even see it leaving you.

**Comment by Alex-the-666** [comment]
just fixed

**Comment by Kajtetto** [comment]
Cool:)
