### ISSUE TITLE
Dragon armor problem

### ISSUE THREAD

**Issue by Serg443** [Alex-the-666/Ice_and_Fire#1803]
when the fire dragon blinks, the armor he wore appears on his body for a second. I took it off, still it appears. And when I put on the dragon armor again, it did not appear and appeared only when it blinks, and only on the body. (again my dragon is red, female, stage 5 maximum size)

Sorry for my english, again... Stupid translator.

**Comment by Serg443** [comment]
newest version. No resourcepacks, that changing dragon textures.

**Comment by AlexModGuy** [comment]
fixed in 1.8.4
