### ISSUE TITLE
Dragons not breaking blocks properly or at all during flight even with griefing on 0

### ISSUE THREAD

**Issue by Meiken094** [Alex-the-666/Ice_and_Fire#1804]
I have Dragon griefing set to 0 (default) because I don't expect a block to stop a dragon from coming over and cooking/eating my ass. Either way, dragons seem to somewhat break blocks when walking but to my experience within the twilight forest and some I've found underground they **do not break** not even **one** **block** when in their flight animation.

**Comment by AlexModGuy** [comment]
fixed
