### ISSUE TITLE
Dragon Horn Issue?

### ISSUE THREAD

**Issue by Chancho91** [Alex-the-666/Ice_and_Fire#1806]
I noticed that a small part of the horn disappears at the same they blink. It seems to happen when they're at stage 5. I'm using the newest version of the mod.
![2019-08-25_00 06 21](https://user-images.githubusercontent.com/24527489/63645576-94e3d580-c6cf-11e9-8420-7899cf2d2b0a.png)
![2019-08-25_00 06 23](https://user-images.githubusercontent.com/24527489/63645578-9a412000-c6cf-11e9-9e51-14e0619a3929.png)

**Comment by AlexModGuy** [comment]
fixed
