### ISSUE TITLE
flying and sitting errors

### ISSUE THREAD

**Issue by UnlimitedTurtlez** [Alex-the-666/Ice_and_Fire#1807]
-sitting in crops the dragons flicker in and out of existence
-when flying the dragon maneuvers like it has no idea wtf its suppose to do
flying a dragon is quite annoying when it tilts so much and could it be possible to mount the back of their heads instead of neck cuz when aiming the breath its hard to see

also an unrelated complaint, why the heck are they WYVERNS and you call them dragons? 
give them 4 legs the species is not correct
https://youtu.be/T8QfC18echQ

**Comment by ColaLiao** [comment]
see the Game of Thrones, you will find the answer

**Comment by superlord9362** [comment]
1. Wyverns are dragons.
2. The dragons are based on the dragons from Game of Thrones, Smaug from the cinematic version of The Hobbit, and Skyrim.
"I'll say this when you create a fantasy world you are at full libraty as a creator to name things as you please. While the dragons in the mod have a 'wyvern' design in the sense that they are wing walkers. Their elemental breath and love of gold is based off traditional dragon mythology within the western world. Our dragons are the typical modern design which has removed the hexapedal physique in favour of one that makes them more physiologically relatable, such designs are also seen in Eldar Scrolls, Game of Thrones and the cinematic version of the Hobbit." - Raptorfarian on the I/F official discord.

**Comment by UnlimitedTurtlez** [comment]
so you didnt watch the video

**Comment by ColaLiao** [comment]
we all known about the differences between Wyvern and Dragon, and tell you why this mod call them dragon.
and why so serious?
