### ISSUE TITLE
Myrmex's eating up massive amount of frame time with the new A* pathfinding

### ISSUE THREAD

**Issue by Kovak** [Alex-the-666/Ice_and_Fire#1811]
Ever since the 1.8.1 update my server is getting consistent lag spikes of around ~3 seconds that is sourced from the A* pathfinding algo running on EntityMyrmexBase

This is a regression from 1.8.0, perhaps go back to the old pathfinding for the more numerous entities?

**Comment by RaeshaFox** [comment]
My server is now constantly crashing due to the Myrmex's pathfinding lagspikes. [Here's one detailed crash log.](https://pastebin.com/ei2JrNmW) Hopefully this can help source the exact issue.

**Comment by AhiVT** [comment]
I also have had this issue. The lag accumulates and then ultimately causes the world to be at least 20 seconds behind. I had to remove it from my modpack and restore my world due to the lag unfortunately.

**Comment by KamiSami** [comment]
This is issue for me too, hoping to see fix for this.

**Comment by AlexModGuy** [comment]
#1884
