### ISSUE TITLE
Bugs 1.8.1

### ISSUE THREAD

**Issue by Pancakes02** [Alex-the-666/Ice_and_Fire#1813]
I found a few of bugs while testing out the new version of Ice and Fire mod (1.8.1)
- Baby dragon glitch with armor 
I had two green dragons, I put gold armor on my female and it appeared on the male too. When I took the armor off if still showed on the dragons, even if I put a different armor on the gold armor wouldn't go away.
-Wild dragon disappears after getting killed
I killed a stage 3 female dragon and when her health hit 0 she started to do the dying animation but then disappeared.
-Dragon nest/roost spawning in water
I made a new world and the I found a dragon's nest almost all engulfed in water by the ocean. :/
-Dragons getting stuck in blocks while in the "turn" animation
With the new rotation and twists and turns I've seen a few dragons get stuck on blocks while in flight, keeping them in a sideways-up position.

**Comment by AlexModGuy** [comment]
dupe #1856 , dupe #344 fix the circles
