### ISSUE TITLE
Suggestion: Dragon-breakable blocks whitelist option

### ISSUE THREAD

**Issue by inkdear** [Alex-the-666/Ice_and_Fire#1817]
I think it would be useful to be able to configure a whitelist of blocks dragons are explicitly able to break, along with what they are able to break according to their dragon griefing setting. So, for example, a dragon on setting '1' could break weak blocks + the contents of the whitelist, and a dragon on setting '2' could only break blocks on the whitelist. I'm not sure what the limits of what they can break are on setting 0, but presumably the whitelist could be used to define specific blocks as breakable in that case too.

**Comment by AlexModGuy** [comment]
blacklist exists and whitelist would be too tedious and too narrow scope to persue.
