### ISSUE TITLE
Dragons walking in air

### ISSUE THREAD

**Issue by TRCI101** [Alex-the-666/Ice_and_Fire#1818]
Hey there Alex, I've come to inform you of an animation error that occurred in ice and fire 1.8.1. During flight, sometimes a dragon's flight animation will switch over to the walking animation. While the picture provided may have other mods in the background, do keep in mind that I had recreated this bug in a world with just Ice and fire and Llibrary 1.19. No other mods are the cause of this strange behavior. 

![2019-08-27_20 01 15](https://user-images.githubusercontent.com/54606761/63816710-36a13780-c907-11e9-85fc-d4e8493463ac.png)

**Comment by TRCI101** [comment]
Here is a second picture from the front as well:
![2019-08-27_20 15 00](https://user-images.githubusercontent.com/54606761/63817009-584eee80-c908-11e9-8519-7c2eeb5f6ec0.png)

**Comment by AlexModGuy** [comment]
how can one recreate this bug?

**Comment by AlexModGuy** [comment]
should be fixed in 1.8.4
