### ISSUE TITLE
1.8+ Dragon Model Resouce Packs make handing Dragon bone sword wrong position 

### ISSUE THREAD

**Issue by DarkerGodzilla** [Alex-the-666/Ice_and_Fire#1819]
![2019-08-28_11 59 27](https://user-images.githubusercontent.com/54614369/63827215-82e28b00-c98c-11e9-9e87-509c9d19944c.png)

like this

**Comment by ColaLiao** [comment]
![image](https://user-images.githubusercontent.com/16384174/63891118-0b0d7280-ca17-11e9-8be8-cd2f37e604c7.png)

i dont have this problem with the last version...

**Comment by DarkerGodzilla** [comment]
which MC forge your MC version?
my forge version is 14.23.5.2768 
But I don't know if it's related

**Comment by ColaLiao** [comment]
2768 too.
maybe you use some player model mod caused this problem.

**Comment by DarkerGodzilla** [comment]
I've taken all of another mod off but I have this same issue. 

![2019-08-29_06 21 19](https://user-images.githubusercontent.com/54614369/63899076-b02f4780-ca25-11e9-953f-273915c1f9cc.png)

**Comment by ColaLiao** [comment]
your problem seems like #1742 
could you let us know the mod list of your modpack?

**Comment by DarkerGodzilla** [comment]
![1](https://user-images.githubusercontent.com/54614369/63988608-51da9580-cb07-11e9-9276-312eed1af906.png)

**Comment by ColaLiao** [comment]
try remove optifine?

**Comment by DarkerGodzilla** [comment]
I've remove another mods but I have this same issue again.

**Comment by DarkerGodzilla** [comment]
NOW I know that issue. that cause Wild Dragon 1.8+ and GOT Dragons resource packs.

**Comment by AlexModGuy** [comment]
issue with resource packs. will probs have to make a new github for it
