### ISSUE TITLE
Pualdron of Repulsion causes Dragons to disappear instead of being flung

### ISSUE THREAD

**Issue by DoomRater** [Alex-the-666/Ice_and_Fire#1821]
Thaumic Periphery adds a Pauldron of Repulsion which pushes everything away on damage.  Unfortunately, dragons that are hit by this disappear entirely, never to be seen again.  Kinda hard to fight dragons when they blink out of existence, and this could cost someone their pet dragon if I fought nearby it.

**Comment by AlexModGuy** [comment]
This is done by using 
> mob.knockBack(player, 2F, player.posX - mob.posX, player.posZ - mob.posZ);
