### ISSUE TITLE
Dragons disappear as soon as I mount them

### ISSUE THREAD

**Issue by swegboie** [Alex-the-666/Ice_and_Fire#1823]
I've tamed two dragons on singleplayer, and at stage 4 and 5, when I tried to mount them, they disappear. Closing the game and reopening didn't work, nor did relogging. Help?

The first time it happened, the dragon disappeared shortly after I flew it and landed it

The second time it disappeared as soon as I mounted it

**Comment by AlexModGuy** [comment]
dupe #1701
