### ISSUE TITLE
1.10.2: My game is constantly crashing

### ISSUE THREAD

**Issue by connortheplay** [Alex-the-666/Ice_and_Fire#1824]
Hello. I´m playing on a online minecraft Server with 40 mods (including Ice and Fire) and if i am near a Dragon, my whole game just crashes and Shows me this report:

The game crashed whilst ticking entity
Error: java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Boolean

-- Entity being ticked --
Details:
	Entity Type: iceandfire.firedragon (com.github.alexthe666.iceandfire.entity.EntityFireDragon)
	Entity ID: 821690
	Entity Name: Fire Dragon
	Entity's Exact location: -800,85, 25,38, -310,61
	Entity's Block location: World: (-801,25,-311), Chunk: (at 15,1,9 in -51,-20; contains blocks -816,0,-320 to -801,255,-305), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Entity's Momentum: 0,00, -0,08, 0,00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

What can i do that my game stops crashing? Please send help as soon as possible

**Comment by Xorbah** [comment]
Well you're on 1.10.2 and that was an incredibly buggy version for ice and
fire. You're SOL.

**Comment by BugmanBugman** [comment]
What he said. It’s such a deprecated version
