### ISSUE TITLE
Receipt with witherbone

### ISSUE THREAD

**Issue by gollariel** [Alex-the-666/Ice_and_Fire#1825]
Witherbone from iceandfire is compatible with other mods, but witherbone from other mods, can not be used for crafting iceandfire stuff (tested with NetherEX).

**Comment by Xorbah** [comment]
Then why is the issue posted here lmao

**Comment by gollariel** [comment]
Because this is an issue in ice and fire receipts.  Receipt from iceandfire does not wait for any witherbone, iceandfire use only they own witherbone. Expected to wait for any witherbone.
It can be fixed manually via crafttweaker, but would be better to do this once in icaandfire

**Comment by Skullfun** [comment]
How do u fix it?
