### ISSUE TITLE
[Suggestion] rotten eggs and dispensers

### ISSUE THREAD

**Issue by Morinor** [Alex-the-666/Ice_and_Fire#1831]
The feature that dispensers can throw rotten eggs and produce cockatrices gets pretty annoying when building automatic chicken farms. cockatrices tend to glitch into blocks when growing up in a confined space and just build up over time.
As there isnt really a point to fire rotten eggs from a dispenser to create untamed cockatrices, itd be nice if that feature could be toggled on and off in the configs.

**Comment by zucaluca** [comment]
You can make an item sorter (eggs and rotten eggs) before your dispenser system in any case.

**Comment by Morinor** [comment]
yes, but it breaks existing systems.
