### ISSUE TITLE
Dragons, dragon roost, and dragon lairs not spawning

### ISSUE THREAD

**Issue by BigBoats123** [Alex-the-666/Ice_and_Fire#1832]
I played the mod for over 4 hours trying to find dragons and was not able to find any. The only thing I found were dragon skeletons everywhere, especially in the glacier biomes, there were 5 dragon skeletons one time. I uninstalled and reinstalled the mod and nothing worked. I don't know if this is a bug or not, but I was running it with the latest version of Optifine, Journey Map, and JEI. 
All the other mobs spawned normally, dragons were the only thing bugging out.
Also the dragon skeletons always spawn with 20 hp.

**Comment by ColaLiao** [comment]
try remove ice and fire config then create new world

**Comment by AlexModGuy** [comment]
you messed something up in the config.
