### ISSUE TITLE
Dragon Roost spawn exactly same rate despite config.

### ISSUE THREAD

**Issue by ani2nice** [Alex-the-666/Ice_and_Fire#1834]
I have done a test, adjusting the spawn chance of roosts going higher then down to even 1!
They spawn at the same alarming frequency and it ruins the game experience having to deal with them literally everywhere.
![picture](https://user-images.githubusercontent.com/15664677/64404849-40cfde00-d04b-11e9-9d3a-f84002de42e5.png)
You'll not my coords in the picture, I had to put a 500 block dangerous spawn limit from the spawn area and this is not far outside of that and if I went another 100 or so blocks in any direction I was finding much of the same. The config is either affecting it in an unknown way or it just simply isn't affecting it at all and needs looked at. (The pic above I had the spawn chance set at "1"

**Comment by ColaLiao** [comment]
lower number make higher chance, you know?

**Comment by ani2nice** [comment]
If that was the case then in the config description they need to fix it

"# 1 out of this number chance per chunk for generation [range: 1 ~ 10000,
default: 360]"
^ this means the higher the number the higher chance to spawn?
Or they need to word it better

**Comment by ani2nice** [comment]
Okay I am going to be honest, the entire config file needs cleanup and clarification... some numbers say lower means lower chance and others say higher but they all use the same number range... and some like above leave me confused on what the number means for a spawn chance.

**Comment by AspectSk** [comment]
1 out of the specified number meaning lower numbers are more spawn chance, i think its pretty clear, 1 out of 2 means 50% spawn chance and 1 out of 50 means 2%

**Comment by AlexModGuy** [comment]
he misread it
