### ISSUE TITLE
Settings change by themselves

### ISSUE THREAD

**Issue by GroundWife** [Alex-the-666/Ice_and_Fire#1841]
Sometimes it happens every time I create a new world, other times they change mid-game. When I scroll through the mod settings I often see a bunch of options that can be turned to Default, which is odd because I have **never** even touched them.

Examples:
Cockatrice Search Lengths got turned to 10 while the default is 30.
Cyclops Attack Strength got turned to 110 while the default is 15.0.

It seems that the Search Lengths are most often affected. I'm actually surprised this hasn't been brought up before since I've had this issue with earlier versions as well (i.e. prior to the addition of Myrmex, Amphitere), even when using the mod by itself. Any ideas why this is happening? #

**Comment by AlexModGuy** [comment]
See #1883
