### ISSUE TITLE
Trying to activate the universal filled bucket too late.

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#1847]
Hello, noticed this error message in the log files of my client:

`[15:05:30] [Client thread/ERROR] [FML]: Trying to activate the universal filled bucket too late. Call it statically in your Mods class. Mod: Ice and Fire`

Minecraft 1.12.2
Ice and Fire 1.8.1
Forge 2844

**Comment by AlexModGuy** [comment]
fixed
