### ISSUE TITLE
Issues I Want To Address (A Thread)

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#1850]

**Comment by xSenpei** [comment]
Stage 5 Dragons are getting invisible all the time youre on them. Also you cant see what youre attacking bcs the dragon head is in the sight. Buggy af...

**Comment by seoyeaji** [comment]
I'm having these issues too. Especially with the dragons turning invisible. It's so annoying. I keep hearing roars i want to kill my own dragon but i cant because i cant see it.

**Comment by AlexModGuy** [comment]
this is way too many issues and github is meant to report multiple issues - split this issue into others(many of them already exist)
