### ISSUE TITLE
The Russian myth(farytales)

### ISSUE THREAD

**Issue by shoverno2** [Alex-the-666/Ice_and_Fire#1853]
What about to add some Russian farytales things?
Actually, there many cool and beautiful things\creatures.
From simple talking guide cat on great oak, to the deadly creature "Koshey bessmertniy"("Koshey" the immortal(actually, no, he is like lich, his phylactery is needle...that's in egg... that's in duck... that's in rabit... that's in chest... that's near Oak... That oak on island... That island in ocean fom MILES AWAY!))
And there many others, including already added mermaid.
...
Another funny story. "Mech kladenets"(sword "kladenets", sword treasure)...
And what the material?
It's dimonds))))))))))))
Yep, it's like this was added in vanilla)))

**Comment by AlexModGuy** [comment]
not for ideas, this place is for bugs
