### ISSUE TITLE
Silver in Tinker's Smeltery

### ISSUE THREAD

**Issue by Spencer2131** [Alex-the-666/Ice_and_Fire#1854]
When Ice and Fire's Silver is added to tinker's smelter it doesn't mix with gold to make electrum.  If no other silver generating mods are in the pack there is no way to make the alloy.

**Comment by wolf653** [comment]
Is electrum in your game? Cause it needs to be in the game in order to alloy just install base metals

**Comment by AlexModGuy** [comment]
^^
