### ISSUE TITLE
Dragon Armor renders when taken off

### ISSUE THREAD

**Issue by 56811285** [Alex-the-666/Ice_and_Fire#1856]
sometimes when you take off or put on armor for you dragon, the visuals doent change, this is in 1.8.1
![2019-09-18_19 55 13](https://user-images.githubusercontent.com/44178367/65209954-6b0f9b80-da4e-11e9-9f07-ab05e4c2f180.png)
![2019-09-18_19 55 43](https://user-images.githubusercontent.com/44178367/65209957-6d71f580-da4e-11e9-8fd4-6f3b2b8645e9.png)

**Comment by AspectSk** [comment]
Yeah this happened to me too, i think i had to restart minecraft for it to be normal again

**Comment by AlexModGuy** [comment]
fixed in 1.8.4
