### ISSUE TITLE
Siren song causing deadlock

### ISSUE THREAD

**Issue by ThreePhases** [Alex-the-666/Ice_and_Fire#1857]
While using the mod as included in World of Dragons (not sure if that is the newest version) A siren's song pulled me in to her Island. Not a problem - because I can take the siren. The problem turned out to be that the song pulled me into a side of the Island that was too steep to pull me up against. So I ended up bopping up and down like mad, not getting any closer to the siren (which would have stopped the spell and allowed me to kill her), not causing death, and the constant moving up and down preventing me from breaking blocks in front of me (so I couldn't break the lock)

Usually the siren's song will draw you close enough within a reasonable amount of time (10 seconds? 20?) - I propose to change the song such that if she hasn't managed to pull you close enough in that time (probably due to terrain problems), she stops singing for a short time, preventing deadlock.

(something similar happened to me earlier when there was a siren Island on the other side of a narrow stretch of land - I somehow managed to get out of that but can't remember how)

**Comment by ghost** [comment]
I have had the same problem and I completely agree with you.

**Comment by ColaLiao** [comment]
i remember it can be configuration in the config file.
you can change the song effect tick.

**Comment by ThreePhases** [comment]
So how do I change the config file, exactly? I tried to find this but failed. I need to ask the server admin to change it and I'd rather be as specific as possible.

**Comment by ColaLiao** [comment]
# how long(in ticks) can a siren use its sing effect on a player, without a cooldown. [range: 100 ~ 24000, default: 12000]
    I:"Siren Max Sing Time"=12000

**12000 means half of minecraft day**

    # how long(in ticks) a siren has to wait after failing to lure in a player [range: 100 ~ 24000, default: 2000]
    I:"Siren Time Between Songs"=2000

**Comment by AlexModGuy** [comment]
you can change this in the ingame config to.

esc(pause game) -> mod options -> Ice and Fire -> config -> Siren Max Sing Time -> change to 400(or how short you want it)
