### ISSUE TITLE
 Crash Between Ice and Fire and Rats

### ISSUE THREAD

**Issue by mxnmnm** [Alex-the-666/Ice_and_Fire#1858]
I posted this on the rats github and since you said it was an Ice and Fire issue I figured I should put it here so you can keep track of it

https://paste.dimdev.org/orakefuwin.mccrash

For context I was stripping the world using world stripper and it randomly crashed so idk if this could also happen normally.

**Comment by AlexModGuy** [comment]
>       | LCHIJA | iceandfire                        | 1.8.0                           | iceandfire-1.8.0.jar                               | None                                     |

issue fixed in 1.8.1
