### ISSUE TITLE
No floor treasure in dragon lairs

### ISSUE THREAD

**Issue by Pedecto** [Alex-the-666/Ice_and_Fire#186]
Using version 1.01. Occasionally, but not always, caverns will be devoid of gold and chests. See pic. Pic is of a fire dragon, but it happens in ice dragon caves as well.

It might be irrelevant, but I also haven't found a single egg yet. Coincidence?

![2017-04-09_19 45 34](https://cloud.githubusercontent.com/assets/20426644/24842447/5e2650ae-1d5d-11e7-9ec4-af6a0e2cb819.png)

**Comment by PlatinumFox** [comment]
Eggs come from state four or five female dragons. There is no visible way to tell a male from a female so just go on a killing spree and one should drop an egg.

**Comment by Pedecto** [comment]
Ah, ok. The pre-release pictures gave me the impression the eggs would spawn as blocks, but I suppose that would make stealing them a bit too easy. 

Barren caves are still an issue, but a lot less important than some of the others I've seen reported.

**Comment by Robomnz** [comment]
im still having this issue


i have the latest version installed

**Comment by AlexModGuy** [comment]
fixed
