### ISSUE TITLE
1.8+ better dragons resourcepack

### ISSUE THREAD

**Issue by kihgy** [Alex-the-666/Ice_and_Fire#1863]
I am a fanboy of the resourcepack, and was really sad when the dragons were redone and I can use the pack. I wish to see the pack be updated to 1.8+ with the new model and all the genders, I know the pack got merged with the vanilla textures, but I really like the color saturation of the dragons in the pack

**Comment by BugmanBugman** [comment]
This isn’t an issue plz close
