### ISSUE TITLE
Dragon Forge won't give me the Dragonsteel no matter what age the dragon is

### ISSUE THREAD

**Issue by TobiDoesMC** [Alex-the-666/Ice_and_Fire#1867]
The Dragon Forge won't give me the Dragonsteel no matter what age the dragon is

**Comment by AlexModGuy** [comment]
what does it give you instead?

**Comment by TobiDoesMC** [comment]
nothing it just keeps going and gives nothing out of the forge

**Comment by ZeRoyalPanda** [comment]
I'm having a similar experience only its giving me ash
