### ISSUE TITLE
Tamed Cockatrice will not follow or patrol after either sitting or relogging while sitting.

### ISSUE THREAD

**Issue by FlyGuy240** [Alex-the-666/Ice_and_Fire#1868]
When you make a cockatrice sit and re-log, or let them sit long enough, they will not follow or patrol. They will only sit in one spot and do nothing.

Edit: If they are in follow mod and you re-log they will follow, however they don't teleport to you when you get too far, nor do they aggro mobs you hit. They act purely defensive, only after a mob hits you will they attack it.

**Comment by CodeGourami** [comment]
I can confirm this is true. having the same issue with cockatrices not following or patrolling. as if they still are sitting. They still do aggro on anything you hit for me though.

Also, Putting cockatrices on patrol doesnt make them patrol a 50 block radius. they just walk off into the distance.

**Comment by maciek204290** [comment]
Can also confirm, though it worked fine on a juvenile one.
