### ISSUE TITLE
Dragons aren't defending 

### ISSUE THREAD

**Issue by Syferia** [Alex-the-666/Ice_and_Fire#187]
Dragons don't really defend their hoard or spawn place. I can walk up and take stuff out of the chests, and they don't go after me

**Comment by NoahNinja** [comment]
In the new update, the dragons stay in a 64 block radius of their roosts, they don't seem to ever land though

**Comment by GundunUkan** [comment]
Yeah, same here. They now stay in the proper area, but still fly to the top of the world and don't come back.

**Comment by Alex-the-666** [comment]
should be more agressive in 1.11.2
