### ISSUE TITLE
model glitches and armor disappears

### ISSUE THREAD

**Issue by Varg95** [Alex-the-666/Ice_and_Fire#1870]
Hey its not a crash but the model of the dragon glichtes as you can see in the pics and when i got of said dragon it didnt have its armor on. but its still in its inventory. And when i put it on again it appeard again but now the other dragon tamed dragon in close to it has it on too but its not in its inventory.

![2019-09-25_11 46 10](https://user-images.githubusercontent.com/23167416/65590228-b95ef600-df8a-11e9-9205-a3070f346333.png)
![2019-09-25_11 46 10_2](https://user-images.githubusercontent.com/23167416/65590229-b9f78c80-df8a-11e9-9a8a-f058b7c3aca7.png)
![2019-09-25_11 46 15](https://user-images.githubusercontent.com/23167416/65590230-b9f78c80-df8a-11e9-8049-307bc512ceb6.png)
![2019-09-25_11 46 16](https://user-images.githubusercontent.com/23167416/65590231-b9f78c80-df8a-11e9-95a7-31da668f449d.png)
![2019-09-25_11 50 22](https://user-images.githubusercontent.com/23167416/65590232-b9f78c80-df8a-11e9-8351-c2c14a76e4a9.png)

**Comment by AlexModGuy** [comment]
dupe
