### ISSUE TITLE
Ticking entity crash

### ISSUE THREAD

**Issue by deadspidervenom** [Alex-the-666/Ice_and_Fire#1874]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ApotheosisCore (Apotheosis-1.12.2-1.10.5.jar)
  midnight (themidnight-0.3.5.jar)
  SCFMLCorePlugin (StalkerCreepers-1.12.1.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  HatedMobsLoadingPlugin (hatedmobs-1.4.1.jar)
  CosmicLibFakeCoreMod (CosmicLib-1.12.2-0.4.0.BETA.jar)
  BlurPlugin (Blur-1.0.4-14.jar)
  TickrateChanger (TickrateChanger-1.0.14.jar)
  PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  DLFMLCorePlugin (DynamicLights-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 9/28/19 2:17 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70636_d(EntityDragonBase.java:1322)
	at com.github.alexthe666.iceandfire.entity.EntityFireDragon.func_70636_d(EntityFireDragon.java:203)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70071_h_(EntityDragonBase.java:1810)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70636_d(EntityDragonBase.java:1322)
	at com.github.alexthe666.iceandfire.entity.EntityFireDragon.func_70636_d(EntityFireDragon.java:203)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70071_h_(EntityDragonBase.java:1810)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: iceandfire:firedragon (com.github.alexthe666.iceandfire.entity.EntityFireDragon)
	Entity ID: 10858
	Entity Name: Fire Dragon
	Entity's Exact location: -209.99, 77.23, 379.87
	Entity's Block location: World: (-210,77,379), Chunk: (at 14,4,11 in -14,23; contains blocks -224,0,368 to -209,255,383), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.23, -0.38, 0.25
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['JojoThyme'/496, l='New World', x=-344.43, y=57.23, z=265.36]]
	Chunk stats: ServerChunkCache: 1375 Drop: 0
	Level seed: 8746025866450333006
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (12,64,-252), Chunk: (at 12,4,4 in 0,-16; contains blocks 0,0,-256 to 15,255,-241), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 12816 game time, 12816 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 84444 (now: false), thunder time: 127295 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2250840288 bytes (2146 MB) / 3561488384 bytes (3396 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 88 mods loaded, 88 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                          | Version             | Source                                            | Signature                                |
	|:------ |:--------------------------- |:------------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                   | 1.12.2              | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp                         | 9.42                | minecraft.jar                                     | None                                     |
	| LCHIJA | FML                         | 8.0.99.99           | forge-1.12.2-14.23.5.2838.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                       | 14.23.5.2838        | forge-1.12.2-14.23.5.2838.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | passableleavescore          | 1.0.0               | minecraft.jar                                     | None                                     |
	| LCHIJA | dsurroundcore               | 3.5.4.3             | minecraft.jar                                     | None                                     |
	| LCHIJA | abyssvoice                  | 0.1.3               | AbyssVoice+[0.1.3].jar                            | None                                     |
	| LCHIJA | ambientenvironment          | 1.0.1               | AmbientEnvironment-1.0.2.jar                      | None                                     |
	| LCHIJA | placebo                     | 1.6.0               | Placebo-1.12.2-1.6.0.jar                          | None                                     |
	| LCHIJA | apotheosis                  | 1.10.4              | Apotheosis-1.12.2-1.10.5.jar                      | None                                     |
	| LCHIJA | babymobs                    | 1.5.5               | BabyMobs-1.12-1.5.5.jar                           | None                                     |
	| LCHIJA | baubles                     | 1.5.2               | Baubles-1.12-1.5.2.jar                            | None                                     |
	| LCHIJA | betterbedrock               | 5.1                 | BetterBedrock-1.12.2-5.1.11.jar                   | None                                     |
	| LCHIJA | bloodmoon                   | 1.5.3               | Bloodmoon-MC1.12.2-1.5.3.jar                      | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | blur                        | 1.0.4-14            | Blur-1.0.4-14.jar                                 | None                                     |
	| LCHIJA | bookshelf                   | 2.3.585             | Bookshelf-1.12.2-2.3.585.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | bouncy_creepers             | 0.0.4               | BouncyCreepers-0.0.4.jar                          | None                                     |
	| LCHIJA | spawnermod                  | 1.0-1.12.2          | branders-enhanced-mob-spawners.v1.4.1-1.12.2.jar  | None                                     |
	| LCHIJA | extendedrenderer            | v1.0                | coroutil-1.12.1-1.2.32.jar                        | None                                     |
	| LCHIJA | coroutil                    | 1.12.1-1.2.32       | coroutil-1.12.1-1.2.32.jar                        | None                                     |
	| LCHIJA | configmod                   | v1.0                | coroutil-1.12.1-1.2.32.jar                        | None                                     |
	| LCHIJA | cosmiclib                   | 0.4.0               | CosmicLib-1.12.2-0.4.0.BETA.jar                   | d3974446c00f9f1d275edce305771eeddf30c658 |
	| LCHIJA | dtm                         | 1.0                 | DarkThemeMod-1.0.jar                              | None                                     |
	| LCHIJA | dungeonmobs                 | 5.8.4               | dungeonmobs-5.8.4-MC1.12.2.jar                    | None                                     |
	| LCHIJA | dynamiclights               | 1.4.9               | DynamicLights-1.12.2.jar                          | None                                     |
	| LCHIJA | dynamiclights_onfire        | 1.0.7               | DynamicLights-1.12.2.jar                          | None                                     |
	| LCHIJA | dynamiclights_creepers      | 1.0.6               | DynamicLights-1.12.2.jar                          | None                                     |
	| LCHIJA | dynamiclights_dropitems     | 1.1.0               | DynamicLights-1.12.2.jar                          | None                                     |
	| LCHIJA | dynamiclights_entityclasses | 1.0.1               | DynamicLights-1.12.2.jar                          | None                                     |
	| LCHIJA | dynamiclights_mobequipment  | 1.1.0               | DynamicLights-1.12.2.jar                          | None                                     |
	| LCHIJA | dynamiclights_flamearrows   | 1.0.1               | DynamicLights-1.12.2.jar                          | None                                     |
	| LCHIJA | dynamiclights_floodlights   | 1.0.3               | DynamicLights-1.12.2.jar                          | None                                     |
	| LCHIJA | dynamiclights_otherplayers  | 1.0.9               | DynamicLights-1.12.2.jar                          | None                                     |
	| LCHIJA | dynamiclights_theplayer     | 1.1.3               | DynamicLights-1.12.2.jar                          | None                                     |
	| LCHIJA | fantasticlib                | 1.12.2.021          | FantasticLib-1.12.2.021.jar                       | None                                     |
	| LCHIJA | dynamicstealth              | 1.12.2.090          | DynamicStealth-1.12.2.090.jar                     | None                                     |
	| LCHIJA | exoticbirds                 | 1.0                 | Exotic Birds 1.12.2-3.0.0.jar                     | None                                     |
	| LCHIJA | eyesinthedarkness           | 0.0.5               | EyesInTheDarkness-0.0.5.jar                       | None                                     |
	| LCHIJA | fragileglassft              | 2.1.0               | Fragile Glass and Thin Ice 1.12.2-2.1.0.jar       | None                                     |
	| LCHIJA | ghostly                     | 1.0.15-bugfix       | ghostly-1.0.15-bugfix.jar                         | None                                     |
	| LCHIJA | grue                        | 1.5.0               | Grue-1.12.2-1.5.0.jar                             | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | hardcoredarkness            | 2.0                 | HardcoreDarkness-MC1.12.2-2.0.jar                 | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | llibrary                    | 1.7.19              | llibrary-1.7.19-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | hatedmobs                   | 1.4.1               | hatedmobs-1.4.1.jar                               | None                                     |
	| LCHIJA | hidenames                   | 1.4                 | HideNames-1.12-1.4.jar                            | None                                     |
	| LCHIJA | howlitdo                    | 1.1                 | HowlItDo-1.1.jar                                  | None                                     |
	| LCHIJA | iceandfire                  | 1.8.1               | iceandfire-1.8.1.jar                              | None                                     |
	| LCHIJA | jei                         | 4.15.0.268          | jei_1.12.2-4.15.0.268.jar                         | None                                     |
	| LCHIJA | kaishiweapons               | v2018.01            | Kaishi's Weapons REBORN v2018.01 [1.12.2].jar     | None                                     |
	| LCHIJA | lycanitesmobs               | 2.0.0.9 - MC 1.12.2 | lycanitesmobs-1.12.2-2.0.0.9.jar                  | None                                     |
	| LCHIJA | meanmobs                    | 1.0.2               | meanmobs-[1.0.2]-{1.12.2}.jar                     | None                                     |
	| LCHIJA | muchmorespiders             | 1.2                 | mmsr-1.0.2-1.12.2.jar                             | None                                     |
	| LCHIJA | mobends                     | 0.24                | mobends-0.24_for_MC-1.12.jar                      | None                                     |
	| LCHIJA | mowziesmobs                 | 1.5.4               | mowziesmobs-1.5.4.jar                             | None                                     |
	| LCHIJA | torotraits                  | 1.12-1              | torotraits-1.12-1.jar                             | None                                     |
	| LCHIJA | nemesissystem               | 1.12.1-2            | nemesissystem-1.12.1-2.jar                        | None                                     |
	| LCHIJA | nightmares                  | 1.0.4               | Nightmares-1.12.2-1.0.4.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | cobwebs                     | 1.0.4               | realistic-cobwebs-1.12.2-1.0.4.jar                | None                                     |
	| LCHIJA | realistictorches            | 2.1.1               | RealisticTorches-1.12.2-2.1.1.jar                 | None                                     |
	| LCHIJA | tiffitlib                   | 1.0.3               | tiffitlib-1.0.3.jar                               | None                                     |
	| LCHIJA | sanity                      | 1.0.3               | sanity-1.0.3.jar                                  | None                                     |
	| LCHIJA | scpcraft                    | 1.0                 | SCPCraft-1.0-Decline.jar                          | None                                     |
	| LCHIJA | tickratechanger             | 1.0.14              | TickrateChanger-1.0.14.jar                        | None                                     |
	| LCHIJA | sleepingoverhaul            | 1.0.0               | SleepingOverhaul-1.12.2-1.0.0.jar                 | d3974446c00f9f1d275edce305771eeddf30c658 |
	| LCHIJA | smelly                      | 1.0.3               | smelly-1.12-1.0.4-9.jar                           | None                                     |
	| LCHIJA | soundfilters                | 0.11_for_1.12       | SoundFilters-0.11_for_1.12.jar                    | None                                     |
	| LCHIJA | spartanweaponry             | beta 1.3.0          | SpartanWeaponry-1.12.2-beta-1.3.0.jar             | None                                     |
	| LCHIJA | craftstudioapi              | 1.0.0               | CraftStudio-1.0.1.95-mc1.12-alpha.jar             | None                                     |
	| LCHIJA | tektopia                    | 1.1.0               | tektopia-1.1.0.jar                                | None                                     |
	| LCHIJA | tektopiainformation         | 1.4.0               | TektopiaInformation-1.12.2-1.1.0-1.4.0.jar        | None                                     |
	| LCHIJA | beneath                     | 1.5.1               | The+Beneath-1.12.2-1.5.1.jar                      | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | thutcore                    | 5.21.0              | thutcore-1.12.2-5.21.0.jar                        | None                                     |
	| LCHIJA | thutcore_compat             | 1.0                 | thutcore-1.12.2-5.21.0.jar                        | None                                     |
	| LCHIJA | thuttech                    | 6.1.6               | thuttech-1.12.2-6.1.6.jar                         | None                                     |
	| LCHIJA | tumbleweed                  | 1.11-0.4.5          | tumbleweed-1.11-0.4.5.jar                         | None                                     |
	| LCHIJA | variedcommodities           | 1.12.2              | VariedCommodities_1.12.2(15may18.jar              | None                                     |
	| LCHIJA | 113_water_mechanics         | 1.0.2               | WaterMechanicsBackport-1.0.3-1.12.2-NETHERFIX.jar | None                                     |
	| LCHIJA | waystones                   | 4.0.72              | Waystones_1.12.2-4.0.72.jar                       | None                                     |
	| LCHIJA | weather2                    | 1.12.1-2.6.12       | weather2-1.12.1-2.6.12.jar                        | None                                     |
	| LCHIJA | worleycaves                 | 1.5.1               | worleycaves-1.5.1.jar                             | None                                     |
	| LCHIJA | cyclopstek                  | 1.0.34              | cyclopstek-1.0.34.jar                             | None                                     |
	| LCHIJA | orelib                      | 3.5.2.2             | OreLib-1.12.2-3.5.2.2.jar                         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround                   | 3.5.4.3             | DynamicSurroundings-1.12.2-3.5.4.3.jar            | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | ladylib                     | 2.1                 | Ladylib-2.1.jar                                   | None                                     |
	| LCHIJA | lumen                       | 0.4.0               | lumen-Beta 0.4.1.jar                              | None                                     |
	| LCHIJA | passableleaves              | 2.0.0               | PassableLeaves-1.12.2-2.0.0.jar                   | None                                     |
	| LCHIJA | midnight                    | 0.3.5               | themidnight-0.3.5.jar                             | None                                     |
	| LCHIJA | weeping-angels              | 1.12.2-39           | weeping-angels-39.jar                             | None                                     |

	Loaded coremods (and transformers): 
ApotheosisCore (Apotheosis-1.12.2-1.10.5.jar)
  shadows.ApotheosisTransformer
midnight (themidnight-0.3.5.jar)
  com.mushroom.midnight.core.transformer.MidnightClassTransformer
SCFMLCorePlugin (StalkerCreepers-1.12.1.jar)
  atomicstryker.stalkercreepers.common.SCTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
HatedMobsLoadingPlugin (hatedmobs-1.4.1.jar)
  fr.uranoscopidae.hatedmobs.asm.HatedMobsTransformer
CosmicLibFakeCoreMod (CosmicLib-1.12.2-0.4.0.BETA.jar)
  
BlurPlugin (Blur-1.0.4-14.jar)
  com.tterrag.blur.BlurTransformer
TickrateChanger (TickrateChanger-1.0.14.jar)
  me.guichaguri.tickratechanger.TickrateTransformer
PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
  teamrtg.passableleaves.asm.PassableLeavesTransformer
LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
DLFMLCorePlugin (DynamicLights-1.12.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['JojoThyme'/496, l='New World', x=-344.43, y=57.23, z=265.36]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Enhanced Default v1.09.zip
	OpenGlVersion: 4.6.0 NVIDIA 431.36
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by AlexModGuy** [comment]
#1884
