### ISSUE TITLE
Issue with Trolls

### ISSUE THREAD

**Issue by Kazaap88** [Alex-the-666/Ice_and_Fire#1875]
I was messing around with trolls in order to scare my friends on a server. I went out a few hundred blocks and put down a spawn egg in creative, and it petrified. After that, I hit the troll with a myrmex chitin pickaxe, and it disappeared, leaving only the weapon. I went into a superflat world to test this again, and found that it happened every time. The weapons also still move as if the troll was alive, however, they don't attack.
![2019-09-28_18 47 20](https://user-images.githubusercontent.com/55931723/65823246-a49b9000-e220-11e9-9922-cc8712d7fa99.png)

**Comment by Kazaap88** [comment]
Upon a second look, the eyes also still remain.

**Comment by Kazaap88** [comment]
After relogging, they have returned to being petrified normal trolls

**Comment by AlexModGuy** [comment]
dupe #1835
