### ISSUE TITLE
Config option for hardcore crafting

### ISSUE THREAD

**Issue by Zeinoth** [Alex-the-666/Ice_and_Fire#1878]
With this hypothetical config enabled, dragonforge ingots will require diamonds instead of iron, and to craft dragon-scale (and other) armors you will need to craft it with a diamond one  (e.g craft 8 scales with a diamond chestpiece to make a dragonscale chest piece

**Comment by Zeinoth** [comment]
Another suggestion: Make dragons immune to slowness, this will make them a little harder to kite. Also make them like ocelots in the sense that they avoid water, currently (from my personal observations) dragons in water just waddle towards you making for easy pickings

**Comment by AlexModGuy** [comment]
no

**Comment by Xorbah** [comment]
Based and redpilled Alex
