### ISSUE TITLE
suggestion: make wild dragons stronger (stat wise) than tame ones

### ISSUE THREAD

**Issue by Zeinoth** [Alex-the-666/Ice_and_Fire#1879]
The reason for this being that tamed ones are already initially stronger (due to the better control of the person riding it), but then in addition to that you can apply armor to it, making it even more powerful in comparison to wild ones. Perhaps wild dragons could have some passive armor because they are more "ferocious" or w/e, but become a little weaker when tamed. In my opinion, this would make tame and wild dragons both more balanced, because the loot you get from wild dragons is insanely good, and tame dragons should have threats if they have no armor (if no other mobs can kill a tame dragon without armor, why bother getting armor, thats the kind of idea im trying to get across). Also i dont if this is a bug, but dragon breath does basically no damage and just applies a status effect

**Comment by AlexModGuy** [comment]
no
