### ISSUE TITLE
Flying dragons constantly drift in the air when mounted flying

### ISSUE THREAD

**Issue by AlexModGuy** [Alex-the-666/Ice_and_Fire#1888]

**Comment by AlexModGuy** [comment]
isnt this kinda intended?

**Comment by aycfes** [comment]
Don't think, so, it isn't as much drifting, as it is sliding to a certain direction for no reason

It is most visible on ice dragons, where if you ride them, start flying, and just try to stay there, hovering, it will start moving up, very fast, after a few seconds.
You also can't really lower your altitude well, as if you try while hovering you barely move down, and even when moving horizontally, if you don't land, you fly right back up when you let go of the down key

**Comment by Fargoth8624** [comment]
I'm getting a similar issue. Ice Dragons are just rising in the air constantly with no input. Fire dragon is similar, but slower.

**Comment by AlexModGuy** [comment]
fixed
