### ISSUE TITLE
When the player is pressing down button, ice dragon flies down slooooowlyyyy and doesn't do the fall animation.

### ISSUE THREAD

**Issue by an0nimu5** [Alex-the-666/Ice_and_Fire#1891]
1. Ice dragons constantly fly up. Especially when they're not controlled by the player.
2. When the player is pressing down button, ice dragon flies down  slooooowlyyyy and doesn't do the fall animation.

Both bugs have been tested on fire dragons, but only ice dragons have those issues.
I also noticed one more thing. Ice dragons don't do an epic roar like fire dragons. It's intentional? It would be neat if ice dragons would be as epic as fire dragons.

**Comment by AlexModGuy** [comment]
fixed the first one, 
not sure about the second one
