### ISSUE TITLE
model glitch 1.8.2 when lilliputian or thicc entities is installed

### ISSUE THREAD

**Issue by Varg95** [Alex-the-666/Ice_and_Fire#1895]
i reported this before but it still happens so i looked in it further and it happens when lilliputian or thic entities is installed. without it they work fine i hope there is a fix for this. my applogies for not reporting it better last time

![2019-10-02_13 09 05](https://user-images.githubusercontent.com/23167416/66039739-fb9daf80-e515-11e9-8a2b-4f6472ad32fe.png)
![2019-10-02_13 09 06](https://user-images.githubusercontent.com/23167416/66039741-fb9daf80-e515-11e9-9995-3cd019447c00.png)
![2019-10-02_13 09 04](https://user-images.githubusercontent.com/23167416/66039742-fc364600-e515-11e9-80ac-5cff41a6a575.png)
![2019-10-02_13 08 59](https://user-images.githubusercontent.com/23167416/66039743-fc364600-e515-11e9-9204-8b383fd7c47c.png)

**Comment by AlexModGuy** [comment]
@Varg95 enable GLErrorFix in iaf config

**Comment by Varg95** [comment]
seems fixed thanks a lot!
