### ISSUE TITLE
Exception Ticking World

### ISSUE THREAD

**Issue by Shinigami-Apples** [Alex-the-666/Ice_and_Fire#1899]
I was wondering if I could possibly get some help with this issue, it's been plaguing my server for the past few days, a little after we installed this mod. 

Seemingly at random, my server crashes, causing it to roll back anywhere from a few minutes to a day ago, ignoring several autosaves and causing my partner and I to lose a lot of progress. I've deduced that it seems to be whenever we are excessively exploring, and the crash usually happens a moment or two after coming across a dragon hoard. 

My server is on a backdated version of Forge ( forge-1.12.2-14.23.5.2837 ), so my partner loaded up his game with the newest version of Forge and the issue still happened shortly after finding a dragon hoard. 

I will attach two crash reports, one is the latest crash from my server, and the other is the crash from my partner's singleplayer game. I would just like to know if this is an actual issue or if we have incompatible mods, ect. 

[crash-2019-10-02_14.44.00-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/3682888/crash-2019-10-02_14.44.00-server.txt)
[crash-2019-10-02_18.14.12-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/3682889/crash-2019-10-02_18.14.12-server.txt)

**Comment by AlexModGuy** [comment]
> at com.ferreusveritas.dynamictrees.blocks.BlockDynamicLeaves.func_180650_b(BlockDynamicLeaves.java:122)
	at electroblob.wizardry.worldgen.WorldGenSurfaceStructure.lambda$removeFloatingTrees$0(WorldGenSurfaceStructure.java:357)
	

Seems to be a conflict between Dynamic Trees and Electrobob's Wizardy. You should bring it up to their devs.
