### ISSUE TITLE
Ice and Fire are missing mods.

### ISSUE THREAD

**Issue by Juliankiller** [Alex-the-666/Ice_and_Fire#190]
It says that I have to get the Mods. Where I can download it?

**Comment by PlatinumFox** [comment]
There are links to forge installer, I and F download, and Llibrary doeload ehich are all needed to run the mod in the minecraft forums post. Ask questions like these in the discord please there are many people who can help. I'm pretty sure Alex just wants bug reports in the GitHub lol.
