### ISSUE TITLE
Myrmex cause error spam on server and eventually crash it

### ISSUE THREAD

**Issue by JamesATeasdale** [Alex-the-666/Ice_and_Fire#1900]
It doesn't produce a crash log, but spawning a myrmex spams some sort of exception in chat until the server crashes.

stymphian birds have a similar issue, but it's just one error rather than a spam and doesn't seem to have an effect on the server after spawn.

The file was 61mb at over 400 000 lines so i cut out what i thought was just pointless and repetitive. Sorry if that ruins the log
[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/3683387/latest.log)

**Comment by JamesATeasdale** [comment]
specifically the sentinel. All the other Myrmex spawn fine

**Comment by AlexModGuy** [comment]
[net.minecraft.world.World:func_175674_a:5837]: java.lang.Exception: Tried getting entities from giant bounding box of box[4078.850000023842, 54.0, -187.14999997615814 -> 4144.149999976158, 83.95000004768372, -121.85000002384186]

**Comment by JamesATeasdale** [comment]
The first two times this happened (in a random encounter) I think it was near a giant and trying to recreate it was only possible near a giant, but giants seem totally fine on their own. It doesn't matter if the sentinels react with the giant or not it seems, but it will eventually crash. I don't know what's happening, it looks like the myrmex try to find a base in the giants home with their ai and that crashes the server. Sorry I couldn't be much help; the myrmex sentinel spamming errors in the server seems like an issue, at least for reading what's happening in the server.

**Comment by AlexModGuy** [comment]
dupe #1158
