### ISSUE TITLE
Death worms causing game freezing lag.

### ISSUE THREAD

**Issue by HEAAAG** [Alex-the-666/Ice_and_Fire#1901]
Game log uploaded below.
It's not a crash log due to the problem being ungodly amounts of lag not something immediately game-breaking, causing rubber banding and slowly freezing the game.

[!Warning!]
VERY long log.
   
[2019-10-03-1.log.gz](https://github.com/Alex-the-666/Ice_and_Fire/files/3683746/2019-10-03-1.log.gz)

I hope I have been of assistance, good day.

**Comment by AlexModGuy** [comment]
that log is unreadable.

**Comment by HEAAAG** [comment]
Oh...
Well in any case, updating to ver 1.8.2 of the mod has allowed me to access the world without much 
further issue.

I apologise If I have wasted your time.
Good day.
