### ISSUE TITLE
New speed 'fix' causing speed checks...

### ISSUE THREAD

**Issue by Gorgok** [Alex-the-666/Ice_and_Fire#1903]
iceandfire-1.8.2.jar

Been using GottaGoFast and later RandomPatches speed check removers forever since not being able to run at whatever speed i desire is silly. Installed this latest version of Ice and Fire and now i'm getting speed checked even with RandomPatches still on the server. Would be nice if the fix didn't interfere with the other.

**Comment by AlexModGuy** [comment]
fixed
