### ISSUE TITLE
A bug occuring with shaders.

### ISSUE THREAD

**Issue by PenumbraStar** [Alex-the-666/Ice_and_Fire#1905]
Hello, I have used shaders with many mods. I know they are not technically supported, however I have been running into a bug that I can not pin down. Most recently, I ran into a visual bug which causes certian mobs and items to glow extremely bright. I am not sure how to contact the shader devs so after running into the bug with the dragons from your mod I decided to see if you have any idea what is going on. Sorry for the inconvenience.
![2019-10-02_21 49 31](https://user-images.githubusercontent.com/9439860/66093810-c453f080-e55f-11e9-9613-9452c4379d55.png)
![2019-10-02_21 49 32](https://user-images.githubusercontent.com/9439860/66093811-c4ec8700-e55f-11e9-8998-195e901ea5db.png)

.

**Comment by AlexModGuy** [comment]
the dragon eyes render on the same code as the spider eyes. how do those look with this shader?

**Comment by PenumbraStar** [comment]
Spider eyes look normal, with a slight glow to them, sorry bout not getting back to you sooner.
