### ISSUE TITLE
Texture or model missing for dragonsteel fluids

### ISSUE THREAD

**Issue by stevesloven** [Alex-the-666/Ice_and_Fire#1906]
Missing texture or model for dragonsteel fluids

error log - https://pastebin.com/HgE4R16B

pic -
![2019-10-03_12 40 29](https://user-images.githubusercontent.com/5517126/66116241-0cfcbf80-e5db-11e9-8e89-f44934c9e089.png)

**Comment by AlexModGuy** [comment]
fixed
