### ISSUE TITLE
Slower computers unable to connect after latest update

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#1909]
After the latest update, my players are unable to connect to my server. I believe that this is due to Ice and Fire breaking RandomPatches fix for this, possibly in commit d3d1f2d (see also https://github.com/TheRandomLabs/RandomPatches/issues/63).

**Comment by AlexModGuy** [comment]
yeah it definitely is due to that. Don;t know what you could do other than remove Random Patches

**Comment by TheRandomLabs** [comment]
Fixed in 1.12.2-1.18.2.3. RandomPatches no longer touches the vehicle movement speed if Ice and Fire is installed.

**Comment by ghost** [comment]
I can confirm that the issue is resolved with the latest versions of Ice and Fire and RandomPatches. Thank you both @Alex-the-666 and @TheRandomLabs for all the work you do on these excellent mods!
