### ISSUE TITLE
Broken Ore dictionary registration.

### ISSUE THREAD

**Issue by EnergyVenom** [Alex-the-666/Ice_and_Fire#1911]
I am using the RLCraft mod for my server and the server console mentioned that there was a broken dictionary registration for 2 items in this mod pack and to report it to you guys. 

04.10 19:10:58 [Server] Server thread/WARN [FML]: ****************************************
04.10 19:10:58 [Server] Server thread/WARN [FML]: * A broken ore dictionary registration with name ingotSilver has occurred. It adds an item (type: class com.github.alexthe666.iceandfire.item.ItemGeneric) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
04.10 19:10:58 [Server] INFO TO USERS: YES this is a BUG in the mod Ice and Fire report it to them!
04.10 19:10:58 [Server] Server thread/WARN [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:679)
04.10 19:10:58 [Server] Server thread/WARN [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:651)
04.10 19:10:58 [Server] Server thread/WARN [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:649)
04.10 19:10:58 [Server] Server thread/WARN [FML]: *  at com.github.alexthe666.iceandfire.core.ModRecipes.preInit(ModRecipes.java:54)
04.10 19:10:58 [Server] Server thread/WARN [FML]: *  at com.github.alexthe666.iceandfire.IceAndFire.preInit(IceAndFire.java:86)
04.10 19:10:58 [Server] Server thread/WARN [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
04.10 19:10:58 [Server] Server thread/WARN [FML]: ****************************************
04.10 19:10:58 [Server] Server thread/WARN [FML]: ****************************************
04.10 19:10:58 [Server] Server thread/WARN [FML]: * A broken ore dictionary registration with name nuggetSilver has occurred. It adds an item (type: class com.github.alexthe666.iceandfire.item.ItemGeneric) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
04.10 19:10:58 [Server] INFO TO USERS: YES this is a BUG in the mod Ice and Fire report it to them!
04.10 19:10:58 [Server] Server thread/WARN [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:679)
04.10 19:10:58 [Server] Server thread/WARN [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:651)
04.10 19:10:58 [Server] Server thread/WARN [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:649)
04.10 19:10:58 [Server] Server thread/WARN [FML]: *  at com.github.alexthe666.iceandfire.core.ModRecipes.preInit(ModRecipes.java:55)
04.10 19:10:58 [Server] Server thread/WARN [FML]: *  at com.github.alexthe666.iceandfire.IceAndFire.preInit(IceAndFire.java:86)
04.10 19:10:58 [Server] Server thread/WARN [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
04.10 19:10:58 [Server] Server thread/WARN [FML]: ****************************************

**Comment by BugmanBugman** [comment]
RLCrafts fault for not updating, tell Shivaxi to update
