### ISSUE TITLE
main feature of this mod is still autistic

### ISSUE THREAD

**Issue by samakotleta** [Alex-the-666/Ice_and_Fire#1912]
#curedragonautism
https://cdn.discordapp.com/attachments/608170288269754372/629950804022788116/help.webm

**Comment by kodabeer** [comment]
oH lOoK aT mE i haTE dRAgOonZ. 
Pathetic, take your toxicity elsewhere because it is not needed here, especially here.

**Comment by panthera** [comment]
I take great offense to this cause I have autism and I can function normally, do your research before you start comparing things to us on the spectrum please

**Comment by AlexModGuy** [comment]
fixed
