### ISSUE TITLE
all mounts still randomly teleport in 1.8.2

### ISSUE THREAD

**Issue by ColaLiao** [Alex-the-666/Ice_and_Fire#1913]
all mounts still randomly teleport in 1.8.2

I play IaF mod with other mods, but all mounts are fine in 1.7.1

only happened in multiplayer.

**Comment by talhanation** [comment]
same problem here mounts cannot be used next to a Player

**Comment by G1R-Productions** [comment]
Yeah when within render distance of other players mounts teleport and rubber band like crazy in 1.8.2. It honestly seems worse than before. Before this update if you dismounted once you entered render distance of another place and waited for a little bit you could then proceed to use your mount again but now even when I do that it still rubber bands.

**Comment by ColaLiao** [comment]
without this problem fix , all mounts will always useless even update to 2.0

**Comment by ColaLiao** [comment]
https://www.twitch.tv/liaocola/clip/CourteousGiantLlamaArsonNoSexy?filter=clips&range=all&sort=time

https://www.twitch.tv/liaocola/clip/AmusedTallSnailUncleNox?filter=clips&range=all&sort=time

**Comment by Wulfesprit** [comment]
Same issue - anywhere near another player and hippogryph flight is useless or worse (random dangerous TPs and game lockups).   Is this fixable?

**Comment by ColaLiao** [comment]
not yet

**Comment by voidswrath** [comment]
any update on this? It is for all mounts on my server from ice and fire and other mods like dragon mounts

**Comment by AlexModGuy** [comment]
fixed on 1.8.4
