### ISSUE TITLE
crashing from ticking world

### ISSUE THREAD

**Issue by GodHenko** [Alex-the-666/Ice_and_Fire#1916]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LibLoader (# LibLoader.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.4.22.2-build.0405.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  LoadingPlugin (Reskillable-1.12.2-1.12.5.jar)
  MMFMLCorePlugin (MultiMine-1.12.2.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  CoreMod (TickProfiler-1.12-0.0.7.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.16-universal.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.21_mc1.12.2.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  TNTUtilities Core (tnt_utilities-mc1.12-1.2.3.jar)
  CreativePatchingLoader (CreativeCore_v1.9.67_mc1.12.2.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 10/6/19 3:08 AM
Description: Exception ticking world

java.lang.NoSuchMethodError: net.minecraft.inventory.ContainerHorseChest.<init>(Ljava/lang/String;I)V
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.initDragonInv(EntityDragonBase.java:290)
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.<init>(EntityDragonBase.java:171)
	at com.github.alexthe666.iceandfire.entity.EntityFireDragon.<init>(EntityFireDragon.java:41)
	at com.github.alexthe666.iceandfire.structures.WorldGenFireDragonRoosts.func_180709_b(WorldGenFireDragonRoosts.java:60)
	at com.github.alexthe666.iceandfire.event.StructureGenerator.generate(StructureGenerator.java:99)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1184)
	at net.minecraft.world.chunk.Chunk.populateCB(Chunk.java:1124)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:162)
	at net.minecraft.world.World.func_72964_e(World.java:451)
	at net.minecraft.world.World.func_175726_f(World.java:446)
	at net.minecraft.world.World.func_180495_p(World.java:1139)
	at atomicstryker.ruins.common.RuinTemplate.checkArea(RuinTemplate.java:230)
	at atomicstryker.ruins.common.RuinTemplate.checkArea(RuinTemplate.java:187)
	at atomicstryker.ruins.common.RuinGenerator.createBuilding(RuinGenerator.java:249)
	at atomicstryker.ruins.common.RuinGenerator.generateNormal(RuinGenerator.java:199)
	at atomicstryker.ruins.common.RuinsMod.generateSurface(RuinsMod.java:234)
	at atomicstryker.ruins.common.RuinsMod.access$300(RuinsMod.java:44)
	at atomicstryker.ruins.common.RuinsMod$RuinsWorldGenerator.generate(RuinsMod.java:203)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1184)
	at net.minecraft.world.chunk.Chunk.populateCB(Chunk.java:1134)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:162)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:175)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:416)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:916)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:454)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:695)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.initDragonInv(EntityDragonBase.java:290)
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.<init>(EntityDragonBase.java:171)
	at com.github.alexthe666.iceandfire.entity.EntityFireDragon.<init>(EntityFireDragon.java:41)
	at com.github.alexthe666.iceandfire.structures.WorldGenFireDragonRoosts.func_180709_b(WorldGenFireDragonRoosts.java:60)
	at com.github.alexthe666.iceandfire.event.StructureGenerator.generate(StructureGenerator.java:99)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1184)
	at net.minecraft.world.chunk.Chunk.populateCB(Chunk.java:1124)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:162)
	at net.minecraft.world.World.func_72964_e(World.java:451)
	at net.minecraft.world.World.func_175726_f(World.java:446)
	at net.minecraft.world.World.func_180495_p(World.java:1139)
	at atomicstryker.ruins.common.RuinTemplate.checkArea(RuinTemplate.java:230)
	at atomicstryker.ruins.common.RuinTemplate.checkArea(RuinTemplate.java:187)
	at atomicstryker.ruins.common.RuinGenerator.createBuilding(RuinGenerator.java:249)
	at atomicstryker.ruins.common.RuinGenerator.generateNormal(RuinGenerator.java:199)
	at atomicstryker.ruins.common.RuinsMod.generateSurface(RuinsMod.java:234)
	at atomicstryker.ruins.common.RuinsMod.access$300(RuinsMod.java:44)
	at atomicstryker.ruins.common.RuinsMod$RuinsWorldGenerator.generate(RuinsMod.java:203)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1184)
	at net.minecraft.world.chunk.Chunk.populateCB(Chunk.java:1134)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:162)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:175)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:416)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['GodTheWeaboo'/172, uuid='7e4fe6e3-cc9c-470d-b271-12dedc4930c4', l='world', x=4143.11, y=63.00, z=4204.62, cx=258, cd=262, tl=656, v=true, d=false](GodTheWeaboo at 4143.107917851595,63.0,4204.622213915386)]
	Chunk stats: ServerChunkCache: 725 Drop: 0
	Level seed: -473048775
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (79,64,278), Chunk: (at 15,4,6 in 4,17; contains blocks 64,0,272 to 79,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 10226 game time, 10226 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 4081 (now: false), thunder time: 156820 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:916)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:454)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:695)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.9.177-xxxx-std-ipv6-64
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2398833952 bytes (2287 MB) / 2942304256 bytes (2806 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 4 total; -Xmx5120M -Xms1024M -XX:ParallelGCThreads=2 -XX:ThreadStackSize=512
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 104 mods loaded, 104 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                          | Version              | Source                                        | Signature                                |
	|:------ |:--------------------------- |:-------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                   | 1.12.2               | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                         | 9.42                 | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                         | 8.0.99.99            | custom.jar                                    | None                                     |
	| LCHIJA | forge                       | 14.23.5.2838         | custom.jar                                    | None                                     |
	| LCHIJA | creativecoredummy           | 1.0.0                | minecraft.jar                                 | None                                     |
	| LCHIJA | itemphysic                  | 1.4.0                | minecraft.jar                                 | None                                     |
	| LCHIJA | ivtoolkit                   | 1.3.3-1.12           | minecraft.jar                                 | None                                     |
	| LCHIJA | foamfixcore                 | 7.7.4                | minecraft.jar                                 | None                                     |
	| LCHIJA | tnt_utilities_core          | 1.2.3                | minecraft.jar                                 | None                                     |
	| LCHIJA | dsurroundcore               | 3.5.4.3              | minecraft.jar                                 | None                                     |
	| LCHIJA | forgeendertech              | 1.12.2-4.4.22.2      | ForgeEndertech-1.12.2-4.4.22.2-build.0405.jar | None                                     |
	| LCHIJA | adhooks                     | 1.12.2-3.2.2.0       | AdHooks-1.12.2-3.2.2.0-build.0220.jar         | None                                     |
	| LCHIJA | advanced-fishing            | 1.3.3                | Advanced-Fishing-1.12.2-1.3.3.jar             | None                                     |
	| LCHIJA | alcatrazcore                | 1.0.4                | alcatrazcore-1.0.4.jar                        | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LCHIJA | antiqueatlas                | 4.5.1                | antiqueatlas-1.12.2-4.5.1.jar                 | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCHIJA | anvilpatch                  | 1.0.0                | anvilpatch-1.0.0.jar                          | None                                     |
	| LCHIJA | aquaculture                 | 1.6.8                | Aquaculture-1.12.2-1.6.8.jar                  | None                                     |
	| LCHIJA | carrots                     | 1.0.0b1              | carrotslib-mc1.12.2-1.0.0b1.jar               | None                                     |
	| LCHIJA | armorunder                  | 1.0.0                | armorunder-mc1.12.2-1.0.0.jar                 | None                                     |
	| LCHIJA | autoreglib                  | 1.3-32               | AutoRegLib-1.3-32.jar                         | None                                     |
	| LCHIJA | bacodifficulty              | 1.0.3                | BacoDifficulty-1.0.3.jar                      | None                                     |
	| LCHIJA | battletowers                | 1.6.5                | BattleTowers-1.12.2.jar                       | None                                     |
	| LCHIJA | baubles                     | 1.5.2                | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA | mujmajnkraftsbettersurvival | 1.3.4                | Better_Survival-1.3.4(1.12.1).jar             | None                                     |
	| LCHIJA | bettercombatmod             | 1.5.6                | BetterCombat-1.12.2-1.5.6.jar                 | None                                     |
	| LCHIJA | bloodmoon                   | 1.5.3                | Bloodmoon-MC1.12.2-1.5.3.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | bnbgaminglib                | 2.17.6               | BNBGamingLib-1.12.2-2.17.6.jar                | None                                     |
	| LCHIJA | bountifulbaubles            | 0.0.1                | Bountiful Baubles-1.12.2-0.1.2.jar            | None                                     |
	| LCHIJA | campfire                    | 1.2                  | campfire-1.12-v1.2.jar                        | None                                     |
	| LCHIJA | carryon                     | 1.12.2               | CarryOn MC1.12.2 v1.12.2.jar                  | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCHIJA | toughasnails                | 3.1.0.141            | ToughAsNails-1.12.2-3.1.0.141-universal.jar   | None                                     |
	| LCHIJA | comforts                    | 1.4.1.2              | comforts-1.12.2-1.4.1.2.jar                   | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | reskillable                 | 1.12.2-GRADLE:BUILD  | Reskillable-1.12.2-1.12.5.jar                 | None                                     |
	| LCHIJA | compatskills                | 1.12.2-1.16.3        | CompatSkills-1.12.2-1.16.3.jar                | None                                     |
	| LCHIJA | coralreef                   | 2.0                  | CoralReef-2.5-1.12.2.jar                      | None                                     |
	| LCHIJA | wearablebackpacks           | 3.1.4                | WearableBackpacks-1.12.2-3.1.4.jar            | None                                     |
	| LCHIJA | corpsecomplex               | 1.0.6                | corpsecomplex-1.12.2-1.0.6.jar                | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | craftablechainmail          | 1.0                  | craftablechainmail-1.0.jar                    | None                                     |
	| LCHIJA | craftablehorsearmour        | 1.3                  | CraftableHorseArmour-1.3.0-1.12.jar           | None                                     |
	| LCHIJA | crafttweaker                | 4.1.19               | CraftTweaker2-1.12-4.1.19.jar                 | None                                     |
	| LCHIJA | jei                         | 4.15.0.268           | jei_1.12.2-4.15.0.268.jar                     | None                                     |
	| LCHIJA | crafttweakerjei             | 2.0.3                | CraftTweaker2-1.12-4.1.19.jar                 | None                                     |
	| LCHIJA | creativecore                | 1.9.9                | CreativeCore_v1.9.67_mc1.12.2.jar             | None                                     |
	| LCHIJA | defiledlands                | 1.4.2                | defiledlands-1.12.2-1.4.2.jar                 | None                                     |
	| LCHIJA | disenchanter                | 1.6                  | disenchanter-[1.12]1.6.jar                    | None                                     |
	| LCHIJA | dldungeonsjbg               | 1.12.10              | DoomlikeDungeons-1.12.10-MC1.12.2.jar         | None                                     |
	| LCHIJA | dynamictrees                | 1.12.2-0.9.5         | DynamicTrees-1.12.2-0.9.5.jar                 | None                                     |
	| LCHIJA | traverse                    | 1.6.0                | Traverse-1.12.2-1.6.0-69.jar                  | None                                     |
	| LCHIJA | dttraverse                  | 1.5                  | dttraverse-1.5.jar                            | None                                     |
	| LCHIJA | enhancedvisuals             | 1.0                  | EnhancedVisuals_v1.2.6_mc1.12.2.jar           | None                                     |
	| LCHIJA | familiarfauna               | 1.0.11               | FamiliarFauna-1.12.2-1.0.11.jar               | None                                     |
	| LCHIJA | firstaid                    | 1.6.10               | firstaid-1.6.10.jar                           | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| LCHIJA | foamfix                     | 0.10.5-1.12.2        | foamfix-0.10.5-1.12.2.jar                     | None                                     |
	| LCHIJA | foodexpansion               | 1.3                  | FoodExpansion1.3.3-1.12.2.jar                 | None                                     |
	| LCHIJA | forgelin                    | 1.8.4                | Forgelin-1.8.4.jar                            | None                                     |
	| LCHIJA | tschipplib                  | 1.1.3                | TschippLib MC1.12.2 v1.1.3.jar                | None                                     |
	| LCHIJA | forgottenitems              | 1.2.1                | ForgottenItems MC1.12.2 v1.2.1.jar            | None                                     |
	| LCHIJA | globalgamerules             | 2.2                  | GlobalGameRules-1.12.2-2.2.7.jar              | None                                     |
	| LCHIJA | grapplemod                  | 1.12.2-v11.1         | grapplemod-v11.1-1.12.2.jar                   | None                                     |
	| LCHIJA | llibrary                    | 1.7.19               | llibrary-1.7.19-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire                  | 1.7.1                | iceandfire-1.7.1-1.12.2.jar                   | None                                     |
	| LCHIJA | infernalmobs                | 1.7.6                | InfernalMobs-1.12.2.jar                       | None                                     |
	| LCHIJA | inventorytweaks             | 1.64+dev.146.2180b27 | InventoryTweaks-1.64+dev.146.jar              | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | itlt                        | 1.0.0                | itlt-1.12-1.0.0.jar                           | None                                     |
	| LCHIJA | levelup2                    | ${version}           | Level Up! 2-1.1.23-1.12.jar                   | None                                     |
	| LCHIJA | lycanitesmobs               | 2.0.0.9 - MC 1.12.2  | lycanitesmobs-1.12.2-2.0.0.9.jar              | None                                     |
	| LCHIJA | mobends                     | 0.24                 | mobends-0.24_for_MC-1.12.jar                  | None                                     |
	| LCHIJA | multimine                   | 1.6.2                | MultiMine-1.12.2.jar                          | None                                     |
	| LCHIJA | notreepunching              | 2.0.18               | notreepunching-2.0.18.jar                     | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LCHIJA | potioncore                  | 1.8_for_1.12.2       | PotionCore-1.8_for_1.12.2.jar                 | None                                     |
	| LCHIJA | potionfingers               | r1.0-5               | PotionFingers-r1.0-5.jar                      | None                                     |
	| LCHIJA | qualitytools                | 1.0.7_for_1.12.2     | QualityTools-1.0.7_for_1.12.2.jar             | None                                     |
	| LCHIJA | realistictorches            | 2.1.1                | RealisticTorches-1.12.2-2.1.1.jar             | None                                     |
	| LCHIJA | reborncore                  | 3.16.3.476           | RebornCore-1.12.2-3.16.3.476-universal.jar    | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJA | reccomplex                  | 1.4.8.2              | RecurrentComplex-1.4.8.2.jar                  | None                                     |
	| LCHIJA | roguelike                   | 1.8.0                | RoguelikeDungeons-1.12.2-1.8.0.jar            | None                                     |
	| LCHIJA | roughtweaks                 | 1.0                  | roughTweaks0.2.4-1.12.2.jar                   | None                                     |
	| LCHIJA | ruins                       | 17.2                 | Ruins-1.12.2.jar                              | None                                     |
	| LCHIJA | silentlib                   | 3.0.13               | SilentLib-1.12.2-3.0.13+167.jar               | None                                     |
	| LCHIJA | scalinghealth               | 1.3.37               | ScalingHealth-1.12.2-1.3.40+145.jar           | None                                     |
	| LCHIJA | sereneseasons               | 1.2.16               | SereneSeasons-1.12.2-1.2.16-universal.jar     | None                                     |
	| LCHIJA | sit                         | v1.2.3               | sit-1.12.2-v1.2.3.jar                         | None                                     |
	| LCHIJA | somanyenchantments          | 0.4.4                | So Many Enchantments V0.4.4.jar               | None                                     |
	| LCHIJA | spartanweaponry             | beta 1.3.1           | SpartanWeaponry-1.12.2-beta-1.3.1.jar         | None                                     |
	| LCHIJA | spartanfire                 | 0.05                 | spartanfire-0.05.jar                          | None                                     |
	| LCHIJA | spartanshields              | 1.5.4                | SpartanShields-1.12.2-1.5.4.jar               | None                                     |
	| LCHIJA | spawnercontrol              | 1.6.3b               | SpawnerControl-1.6.3b.jar                     | None                                     |
	| LCHIJA | stg                         | 1.12.2-1.2.3         | stg-1.12.2-1.2.3.jar                          | None                                     |
	| LCHIJA | switchbow                   | 1.5.7                | switchbow-1.5.7.jar                           | None                                     |
	| LCHIJA | tanspit                     | 1.12.2-1.3           | tanspit-1.12.2-1.3.jar                        | None                                     |
	| LCHIJA | tickprofiler                | 1.12-0.0.7           | TickProfiler-1.12-0.0.7.jar                   | None                                     |
	| LCHIJA | tnt_utilities               | 1.2.3                | tnt_utilities-mc1.12-1.2.3.jar                | None                                     |
	| LCHIJA | toolbelt                    | 1.9.10               | ToolBelt-1.12.2-1.9.10.jar                    | None                                     |
	| LCHIJA | xat                         | 0.25.2               | Trinkets and Baubles-1.12.2-0.25.2.jar        | None                                     |
	| LCHIJA | trumpetskeleton             | 1.12-1.0.2.1         | trumpetskeleton-1.12-1.0.2.1.jar              | None                                     |
	| LCHIJA | tumbleweed                  | 1.11-0.4.5           | tumbleweed-1.11-0.4.5.jar                     | None                                     |
	| LCHIJA | variedcommodities           | 1.12.2               | VariedCommodities_1.12.2(15may18.jar          | None                                     |
	| LCHIJA | waystones                   | 4.0.72               | Waystones_1.12.2-4.0.72.jar                   | None                                     |
	| LCHIJA | wolfarmor                   | 2.2.3.6              | wolfarmor-1.12.2-2.2.3.1798-universal.jar     | None                                     |
	| LCHIJA | xpfromharvest               | 1.1.0                | xpfromharvest-1.12.2-1.1.0.jar                | None                                     |
	| LCHIJA | xpbook                      | v1.1.1               | xptome-1.12.2-v1.1.1.jar                      | None                                     |
	| LCHIJA | orelib                      | 3.5.2.2              | OreLib-1.12.2-3.5.2.2.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | phosphor-lighting           | 1.12.2-0.2.6         | phosphor-1.12.2-0.2.6+build50-universal.jar   | f0387d288626cc2d937daa504e74af570c52a2f1 |
	| LCHIJA | dsurround                   | 3.5.4.3              | DynamicSurroundings-1.12.2-3.5.4.3.jar        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |

	Loaded coremods (and transformers): 
LibLoader (# LibLoader.jar)
  
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CorePlugin (ForgeEndertech-1.12.2-4.4.22.2-build.0405.jar)
  
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  
LoadingPlugin (Reskillable-1.12.2-1.12.5.jar)
  codersafterdark.reskillable.base.asm.ClassTransformer
MMFMLCorePlugin (MultiMine-1.12.2.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
CoreMod (TickProfiler-1.12-0.0.7.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.16-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
ItemPatchingLoader (ItemPhysic_Full_1.4.21_mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
TNTUtilities Core (tnt_utilities-mc1.12-1.2.3.jar)
  ljfa.tntutils.asm.ExplosionTransformer
CreativePatchingLoader (CreativeCore_v1.9.67_mc1.12.2.jar)
  
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.16.3.476
		Runtime Debofucsation 1
	Profiler Position: N/A (disabled)
	Player Count: 1 / 6; [EntityPlayerMP['GodTheWeaboo'/172, uuid='7e4fe6e3-cc9c-470d-b271-12dedc4930c4', l='world', x=4143.11, y=63.00, z=4204.62, cx=258, cd=262, tl=656, v=true, d=false](GodTheWeaboo at 4143.107917851595,63.0,4204.622213915386)]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by AlexModGuy** [comment]
dupe #1830
