### ISSUE TITLE
Armor again, Dragon Scale vs Diamond

### ISSUE THREAD

**Issue by CraftyAngyl** [Alex-the-666/Ice_and_Fire#192]
A full suit of Dragon Scale is no better than a full suit of Diamond armor, but the change log states that dragon scale armor is now better than diamond armor.  If you look at the numbers the armor toughness is all the same for both, but the dragon scale chestplate is 7 and leggings 7 while the diamond chestplate is 8 and the leggings 6.  7+7 and 8+6 are the same thing.  The only benefit is if you use dragon scale leggings with a diamond chestplate and the helmet and boots don't matter.  If the dragon scale leggings are +1 on the diamond, then shouldn't the dragon scale chestplate be +1 on the diamond too?  Also are the helmet and boots supposed to be the same as diamond?

**Comment by Alex-the-666** [comment]
fixed in 1.11.2
