### ISSUE TITLE
Dragon knockback makes dragon disappear

### ISSUE THREAD

**Issue by LordRael** [Alex-the-666/Ice_and_Fire#1923]
While using Ice and Fire, Spartan Weapons, and the compatibility mod, I have twice caused a dragon to vanish.  Both time I've been at least partially submerged in water, and using an Iced Dragonbone Mace, both unenchanted and enchanted.  It does not happen every time.

**Comment by LordRael** [comment]
Edit:  I just caused a third vanishing, without water being involved this time.  It seems to happen if I hit the dragon while, or shortly after escaping, being grabbed.

**Comment by Gorgok** [comment]
I actually think i encountered this before, and it had to do with a knockback effect i had on me against agressors. It would effectively teleport the dragon to 0, 0 or something like that (as seen by /forge entity list e@(type=iceandfire:fire_dragon or something like that). I removed the item giving me the knockback effect and forgot about it happening.

**Comment by DoomRater** [comment]
Can confirm the Pauldron of Repulsion from Thaumic Periphery causes this same effect.

**Comment by AlexModGuy** [comment]
dupe #1821
