### ISSUE TITLE
Stage 1 dragons can use grab attack

### ISSUE THREAD

**Issue by NoahNinja** [Alex-the-666/Ice_and_Fire#193]
I was in a creative world, I made a cage, put a wild stage 1 dragon in with a spawn egg, then went into survival, I walked over to it, it grabbed me, did the animation, and I lived with 1 heart left, due to my diamond boots

**Comment by darthvader45** [comment]
This is intended to me.  Any stage should be able to use the grab attack.

**Comment by Alex-the-666** [comment]
fixed in 1.11.2
