### ISSUE TITLE
Banner patterns not showing

### ISSUE THREAD

**Issue by CLittleLunaC** [Alex-the-666/Ice_and_Fire#1935]
This may be my resource pack but the banner patterns do not show what so ever. Vanilla patterns show just fine just in the style of the resource pack. I looked at the issues and saw no one else has the same issue and I would like to be able to see the patterns while using the dokucraft resource pack.

**Comment by ColaLiao** [comment]
resource pack higher than 16x will happen

**Comment by CLittleLunaC** [comment]
So a resource pack higher than 16x will prevent it from showing? Can I make textures at the same resolution as the resource pack to fix this? Or do I have to get the lower resolution of the resource pack?

**Comment by ColaLiao** [comment]
you can just change all banner textures of the resourcepack to16x to fix it.

**Comment by CLittleLunaC** [comment]
Alright thank you! I also found out that it isn't just ice and fire but millenair has the same issue. I'll snag a 16x texture pack and use it's banner textures instead.
