### ISSUE TITLE
Dragons no longer support PBR Textures for Shaders

### ISSUE THREAD

**Issue by Carro1001** [Alex-the-666/Ice_and_Fire#1936]
Ever since the update that reverted the way the armor layers, etc are applied, resource packs that add reflections, refraction, etc, to the dragons, no longer work.
This is the effect i've used to be able to make:
![2019-08-19_00 36 50](https://user-images.githubusercontent.com/47877096/66691873-e3ddce00-ec6f-11e9-92c1-5f7262495546.png)
![2019-08-19_00 37 01](https://user-images.githubusercontent.com/47877096/66691878-f0622680-ec6f-11e9-82d3-16270b10d8c7.png)

**Comment by AlexModGuy** [comment]
The armor should render on its own layer now.
