### ISSUE TITLE
Entity Render Crash Issue;

### ISSUE THREAD

**Issue by SilverKnight9** [Alex-the-666/Ice_and_Fire#1937]
I placed an ice dragon skull on some stone slabs and now my game continually crashes when I log in reporting an entity render crash with the skull.

**Comment by NeonPopsicle** [comment]
I'm having this same exact issue. Placed my fire dragon skull on the stone slabs of my wall and if I look directly at the skull than I crash my game over and over. It claims to be a rendering crash.

 I've tried to get rid of it with world edit and it acts as if it is not a true block or that it can't be removed with //set air.

**Comment by NeonPopsicle** [comment]
![2019-12-15_09 38 00](https://user-images.githubusercontent.com/58912297/70865314-c94efc00-1f21-11ea-9afe-1482e2b8db11.png)
![2019-12-15_09 38 54](https://user-images.githubusercontent.com/58912297/70865316-cce28300-1f21-11ea-8f96-da7a1f111795.png)

**Comment by AlexModGuy** [comment]
fixed
