### ISSUE TITLE
Error casting EntityPlayerMP to EntityDragonBase

### ISSUE THREAD

**Issue by AstralWoodland** [Alex-the-666/Ice_and_Fire#1938]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  CustomSkinLoader (CustomSkinLoader_Forge-14.10a.jar)
  Inventory Tweaks Coremod (【R键整理】InventoryTweaks-1.63.jar)
  iceandfire (iceandfire-1.8.3.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 10/10/19 1:02 PM
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.entity.player.EntityPlayerMP cannot be cast to com.github.alexthe666.iceandfire.entity.EntityDragonBase
	at com.github.alexthe666.iceandfire.entity.EntityDragonFireCharge.func_70227_a(EntityDragonFireCharge.java:115)
	at net.minecraft.entity.projectile.EntityFireball.func_70071_h_(EntityFireball.java:98)
	at com.github.alexthe666.iceandfire.entity.EntityDragonFireCharge.func_70071_h_(EntityDragonFireCharge.java:59)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.github.alexthe666.iceandfire.entity.EntityDragonFireCharge.func_70227_a(EntityDragonFireCharge.java:115)
	at net.minecraft.entity.projectile.EntityFireball.func_70071_h_(EntityFireball.java:98)
	at com.github.alexthe666.iceandfire.entity.EntityDragonFireCharge.func_70071_h_(EntityDragonFireCharge.java:59)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: iceandfire:dragonfirecharge (com.github.alexthe666.iceandfire.entity.EntityDragonFireCharge)
	Entity ID: 16656
	Entity Name: 龙炎弹
	Entity's Exact location: -131.11, 67.31, 888.00
	Entity's Block location: World: (-132,67,888), Chunk: (at 12,4,8 in -9,55; contains blocks -144,0,880 to -129,255,895), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Entity's Momentum: -1.45, 0.34, 0.17
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: 新的世界
	All players: 1 total; [EntityPlayerMP['sawthewhat'/8956, l='新的世界', x=-131.91, y=65.76, z=886.24]]
	Chunk stats: ServerChunkCache: 545 Drop: 0
	Level seed: 1292715553230352554
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-111,64,239), Chunk: (at 1,4,15 in -7,14; contains blocks -112,0,224 to -97,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 5406 game time, 5406 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 86063 (now: false), thunder time: 123189 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1753302784 bytes (1672 MB) / 2994208768 bytes (2855 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -Xmx6144m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2815 Optifine OptiFine_1.12.2_HD_U_E3 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version                  | Source                                 | Signature                                |
	|:------ |:--------------------- |:------------------------ |:-------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2                   | minecraft.jar                          | None                                     |
	| LCHIJA | mcp                   | 9.42                     | minecraft.jar                          | None                                     |
	| LCHIJA | FML                   | 8.0.99.99                | forge-1.12.2-14.23.5.2815.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                 | 14.23.5.2815             | forge-1.12.2-14.23.5.2815.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | chinjufumod           | 3.2.2                    | ChinjufuMod[1.12.2]3.2.2.jar           | None                                     |
	| LCHIJA | customskinloader      | 14.10a                   | CustomSkinLoader_Forge-14.10a.jar      | 52885f395e68f42e9b3b629ba56ecf606f7d4269 |
	| LCHIJA | llibrary              | 1.7.19                   | llibrary-1.7.19-1.12.2.jar             | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire            | 1.8.3                    | iceandfire-1.8.3.jar                   | None                                     |
	| LCHIJA | flammpfeil.slashblade | mc1.12-r28               | SlashBlade-mc1.12-r28.jar              | None                                     |
	| LCHIJA | torohealthmod         | 1.12.2-11                | torohealth-1.12.2-11.jar               | None                                     |
	| LCHIJA | xaeroworldmap         | 1.4.10.1                 | XaerosWorldMap_1.4.10.1_Forge_1.12.jar | None                                     |
	| LCHIJA | inventorytweaks       | 1.63+release.109.220f184 | 【R键整理】InventoryTweaks-1.63.jar         | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | jei                   | 4.8.5.138                | 【物品管理】jei_1.12.2-4.8.5.138.jar         | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CustomSkinLoader (CustomSkinLoader_Forge-14.10a.jar)
  customskinloader.forge.loader.LaunchWrapper
Inventory Tweaks Coremod (【R键整理】InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
iceandfire (iceandfire-1.8.3.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['sawthewhat'/8956, l='新的世界', x=-131.91, y=65.76, z=886.24]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 382.33
	OpenGlRenderer: GeForce GTS 450/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2

**Comment by DSchaedler** [comment]
Been having this problem as well on my sever. Tried multiple options for fixing this mod, with little success.

[Crashlogs.zip](https://github.com/Alex-the-666/Ice_and_Fire/files/3721300/Crashlogs.zip)

**Comment by Xhale1** [comment]
Yep, having this same issue. Occurred twice when getting near dragon dens on the surface, and once getting very close to the skull of a dragon (also near a den). It doesn't occur again after rebooting the game.

My guess is it's the check a dragon runs to see if a chest is opened devolving into an infinite loop.
