### ISSUE TITLE
Compat issue between Mystical World and Ice and Fire silver

### ISSUE THREAD

**Issue by FlyGuy240** [Alex-the-666/Ice_and_Fire#1947]
When crafting ice and fire silver into a block it crafts the mystical world silver block. I'm not sure if its a problem on both ends, but the same thing happens when you craft a mystical world set of ingots into a block. 

This doesn't effect functionality unless one or the others are disabled. 

On another note, it would be nice to be able to "enable/disable" Ice and fire silver in the config. That way when you break a silver pile you get the other mods silver nuggets if it has them. I know you can disable silver ore gen but I didn't notice anything else related to silver.

**Comment by BugmanBugman** [comment]
get no more recipe conflict

**Comment by AlexModGuy** [comment]
^
