### ISSUE TITLE
Tidal Armor Causes massive Lag

### ISSUE THREAD

**Issue by kreezxil** [Alex-the-666/Ice_and_Fire#1948]
First reported at https://github.com/kreezxil/World-of-Dragons/issues/346 seems to be related to #376

1. Install LagGoggles, 
1. put on Tidal Armor. 
1. Do a scan 
1. see the massive TPS drop.

Ice and Fire version: 1.12.2 - 1.8.3

**Comment by AlexModGuy** [comment]
not able to replicate
