### ISSUE TITLE
Dragons do not follow the commands given and are very difficult to control.

### ISSUE THREAD

**Issue by ArslanEgeYldrm** [Alex-the-666/Ice_and_Fire#1949]
I told one of the dragons to accompany me and I burned a place with another dragon, but the dragon that should accompany me does not even follow me. 
Another mistake is that when you go 500 blocks with borozan and get the dragon out of the borozan, when I get on the dragon, the dragon doesn't take off and doesn't move and burn the place, please correct

**Comment by AlexModGuy** [comment]
fixed in 1.8.4
