### ISSUE TITLE
Sudden crash from lecturn

### ISSUE THREAD

**Issue by Jaybluebird8709** [Alex-the-666/Ice_and_Fire#1953]
so uh..... I inserted the Manuscripts into the lecturn when trying to add new pages to the bestiary and it just crashed me game.
[crash-2019-10-14_21.54.26-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/3727093/crash-2019-10-14_21.54.26-client.txt)

**Comment by Jaybluebird8709** [comment]
welp nvm? haven't anorther instance of the issue so.... I guess it's good for now?

**Comment by dmdufrene** [comment]
I had this issue also.
[crash-2019-11-24_13.25.14-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/3884071/crash-2019-11-24_13.25.14-client.txt)

**Comment by AlexModGuy** [comment]
fixed
