### ISSUE TITLE
Not generate in world

### ISSUE THREAD

**Issue by KingAkrej** [Alex-the-666/Ice_and_Fire#1956]
I have everything installed usually I have a library but dragons do not generate or other monsters.

java -Xmx5628m -Xms256m

**Comment by KingAkrej** [comment]
standalone mod works without a problem
my modpack:
Baubles-1.12-1.5.2.jar                                                
 CarryOn MC1.12.2 v1.12.2.jar                                          
ChickenChunks-1.12.2-2.4.2.74-universal.jar                           
 ElectroblobsWizardry-4.2.5-MC1.12.2.jar                               
Hwyla-1.8.26-B41_1.12.2.jar                                           
iceandfire-1.8.3.jar                                                  
InventoryTweaks-1.63.jar                                              
IronBackpacks-1.12.2-3.0.8-12.jar                                     
jei_1.12.2-4.15.0.268.jar                                             
journeymap-1.12.2-5.5.5.jar                                           
 llibrary-1.7.19-1.12.2.jar                                            
OptiFine_1.12.2_HD_U_E3.jar                                           
Thaumcraft-1.12.2-6.1.BETA26.jar                                      
 ThaumicJEI-1.12.2-1.6.0-27.jar                                        
 tombstone-3.6.0-1.12.2.jar                                            
VeinMiner-1.12-0.38.2.647+b31535a.jar                                 
WailaHarvestability-mc1.12-1.1.12.jar

**Comment by AlexModGuy** [comment]
play with the config a little
