### ISSUE TITLE
Config not working

### ISSUE THREAD

**Issue by NoahNinja** [Alex-the-666/Ice_and_Fire#196]
I changed the block breaking in the config to 2 (no breaking) I went into my world, fooled around for a while, then looked at the config, and the block breaking was set to 0 (block breaking)

**Comment by PlatinumFox** [comment]
Did u click file then save before you closed the config

**Comment by NoahNinja** [comment]
Yes

**Comment by AlexModGuy** [comment]
config system will be changed in 1.5.0
