### ISSUE TITLE
Dragon Scales won't create Parts in TCon Part Builder

### ISSUE THREAD

**Issue by MagisterXero** [Alex-the-666/Ice_and_Fire#1961]
Dragon scales are recognized as TiC Parts, but cannot be built in the part builder.
Dragon bones work, so there is probably just a missing recipe reference somewhere.

![image](https://user-images.githubusercontent.com/1440404/67146867-71678200-f25d-11e9-9743-73998c28b236.png)
![image](https://user-images.githubusercontent.com/1440404/67146874-86dcac00-f25d-11e9-82f9-e1412b66eb52.png)
![image](https://user-images.githubusercontent.com/1440404/67146877-8cd28d00-f25d-11e9-8a4f-2c244216a67e.png)
![image](https://user-images.githubusercontent.com/1440404/67146880-93610480-f25d-11e9-959c-6db2322413f3.png)
![image](https://user-images.githubusercontent.com/1440404/67146882-98be4f00-f25d-11e9-8792-e03fa2a32ce7.png)
![image](https://user-images.githubusercontent.com/1440404/67146887-a5db3e00-f25d-11e9-9748-b019966aaf62.png)
![image](https://user-images.githubusercontent.com/1440404/67146903-e2a73500-f25d-11e9-8d9c-9aa3bffba61e.png)

**Comment by MagisterXero** [comment]
Also some weird issue with bones, even though the part creates.
![image](https://user-images.githubusercontent.com/1440404/67146929-28fc9400-f25e-11e9-93cc-80bc1c3236b0.png)

**Comment by AlexModGuy** [comment]
i dont work on the construct's armory, this is another mod which is an addon of ice and fire. report this to them.
