### ISSUE TITLE
Dragon disappearing

### ISSUE THREAD

**Issue by whereismydragon** [Alex-the-666/Ice_and_Fire#1963]
hello there
this has happened to me several times, in which my dragon will disappear, either i "shift" out of dragon while flying, or dragon will just disappear for no reason after I logged into the server(this happened today, didn't happen since I had installed this mod) 
Also today even the wild dragon starts to disappear after I entered combat with them.

this is very stressful.

are there anyways to improve this bug?(i assume this is a bug)

**Comment by TheRealBaroe** [comment]
I'm having the same issue but with it being on my shoulder. It's already happened twice now.

**Comment by AlexModGuy** [comment]
fixed
