### ISSUE TITLE
A way to obtain amphitheres feather without killing them

### ISSUE THREAD

**Issue by kihgy** [Alex-the-666/Ice_and_Fire#1965]
Killing them is toi cruel, and amphitheres are too rare, maybe right click on your tamed amphi after sometimes will get a feather?

**Comment by DoomRater** [comment]
If you have Roots installed, why not add it to the list of animals that behave with the Animal Harvest ritual?  That's one of the entire goals of the Roots mod- to encourage pacifism and living in harmony with nature.

**Comment by AlexModGuy** [comment]
intended
