### ISSUE TITLE
How to disable dragon spawning in other dimensions

### ISSUE THREAD

**Issue by DGuillotine** [Alex-the-666/Ice_and_Fire#1966]
I'm an avid user of dimension mods in Minecraft because I really love them and the atmosphere they create. However, that atmosphere is greatly disturbed when I find something like a dragon in the likes of the Aether or the Twilight Forest. I've checked the configuration folders and have seen a black/white list for dragon spawning in certain dimensions. Unfortunately, I don't know how to use it and how to even add something like Twilight Forest, Aether II, The Betweenlands, etc, into the black/white list configurations. That's my main problem. Secondly, I'd like to know whether or not other structures like the Cyclops caves, the Gorgon Temples, etc, will spawn outside of the overworld and how to disable that, too. Thank you in advance!

**Comment by ghost** [comment]
Check the ice and fire config. Set dragons to spawn only in dimension 0 (which is overworld ID). Set it to whitelist. Dragons will now only spawn in the overworld. Other structures will not generate in other dimensions.

**Comment by DGuillotine** [comment]
> Check the ice and fire config. Set dragons to spawn only in dimension 0 (which is overworld ID). Set it to whitelist. Dragons will now only spawn in the overworld. Other structures will not generate in other dimensions.

It seems that's already the case as it is the default settings by which the mod has been set up. However, I still have problems with the dragons themselves finding their way into dimensions in which they simply do not belong. Among the clouds of the Aether and the the forest of the Twilight. It does seem, however, that the one mod that remains unaffected by the likes of the dragons is The Betweenlands. Quite fortunately, I believe. Simply, I'd just like to know whether there is a number that represents the likes of the Aether and Twilight Forest in terms of identification like there is one for The Betweenlands (Apparently, being 1). So, would the Aether and the Twilight be 2 and 3? I cannot say for sure. Thank you for your help again in advance!

**Comment by glitch-chara** [comment]
I need help with this as well,
Minecraft ice and Fire how do you stop mobs spawning in different dimensions
I don't know how to do it

**Comment by BugmanBugman** [comment]
Minecraft ice and Fire says "Check the ice and fire config. Set dragons to spawn only in dimension 0 (which is overworld ID). Set it to whitelist. Dragons will now only spawn in the overworld. Other structures will not generate in other dimensions."

**Comment by ffuentesm** [comment]
And how do you prevent mobs from spawning at all?
what should I set in the configs?
