### ISSUE TITLE
When dragons blink, the armor is removed temporarily.

### ISSUE THREAD

**Issue by ThatOneGaymer** [Alex-the-666/Ice_and_Fire#1967]
Whenever dragons blink, because the whole texture changes, it temporarily removes the visual armor. Tested with a stage 5 grey fire dragon and full fire dragonsteel armor, unsure if this is the case with all dragons and all armor

**Comment by ThatOneGaymer** [comment]
Just testing with a stage five ice with ice dragonsteel armor, the issue isn't there? so maybe it's one or two specific cases, still unsure

**Comment by AlexModGuy** [comment]
fixed
