### ISSUE TITLE
Extreme lag

### ISSUE THREAD

**Issue by Biohazard041** [Alex-the-666/Ice_and_Fire#1971]
Using 1.8.3 of Ice and Fire, llib is updated, but i'm getting extreme lag from entities that increases when I get closer, and it returns to normal if I manage to fly away. I have noticed it particularly with Myrmex, as even a relatively small colony will have an incredible amount of lag on the game that renders it unplayable. However, I have noticed it outside of Myrmex colonies, and I was messing around with death worms, but I do not remember the circumstances that caused it.

**Comment by AlexModGuy** [comment]
dupe #1757
