### ISSUE TITLE
Hippogryphs disappearing?

### ISSUE THREAD

**Issue by Jaybluebird8709** [Alex-the-666/Ice_and_Fire#1973]
fairly often when I've gon traveling with my hippogryph it will just vanish. if I relog or step away for a moment they'll comeback... sometimes. then if I get hit by a lag spike or I try to load more chunks my hippogryph just cease to exist.just tryin' to explore the world and I keep losin' muh ride

**Comment by AlexModGuy** [comment]
fixed in 1.8.4
