### ISSUE TITLE
Mount Issues and Dragon's Fire

### ISSUE THREAD

**Issue by StygianIkazu** [Alex-the-666/Ice_and_Fire#1974]
When trying to ride a hippogriff or amphithere (I assume other mounts have this issue), they can randomly glitch out, fall through the ground and suffocate to death. Also, if I go to mount a hippogriff, there is a high chance the hippogriff's inventory will pop up, even without a chest. If this happens (9 out of 10 times it does), if I ride it somewhere and then dismount, I suddenly get teleported back to where I originally mounted the hippogriff. Thirdly, dragon fire causes massive lag. I get lock-ups that result in death while fighting dragons even when I have 8 gb of ram dedicated to Minecraft.

**Comment by ColaLiao** [comment]
#1913 
Mounts issues exist since 1.8.0
really need it fixed or i can only play 1.7.1

https://www.twitch.tv/liaocola/clip/CourteousGiantLlamaArsonNoSexy?filter=clips&range=all&sort=time

https://www.twitch.tv/liaocola/clip/AmusedTallSnailUncleNox?filter=clips&range=all&sort=time
