### ISSUE TITLE
Myrmex of the same hive killing each other

### ISSUE THREAD

**Issue by SpaceAwe** [Alex-the-666/Ice_and_Fire#1975]
I have been trying to work on a myrmex hive and was having some issues with all the workers dissapearing and found that when some soldiers were born after completing the larva and pupa stages that they would start attacking the workers of hive killing them, then they'd get killed trying to kill the queen.

**Comment by democat3457** [comment]
Same issue on Rebirth of the Night, with both naturally generated ones and man-made ones. I&F version 1.9.1, 1.12.2
https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/issues/400
