### ISSUE TITLE
[please fix] IF Amphithere AI behavior

### ISSUE THREAD

**Issue by kreezxil** [Alex-the-666/Ice_and_Fire#1976]
**Describe the bug**  
Amphitheres are the flying snakes that spawn in the jungle from Ice and Fire in a variety of colors and fly like a uh. Elytra! There's two bugs with them actually. Both trigger after taming them. One, once you mount a tamed amphithere, move some distance away, then dismount, you'll instantly be brought back where you mounted it. I noticed chunks do not load when this happens, as if the game thinks you're actually not moving. The second bug I noticed is, after a while, the tamed amphithere reverted to untamed behavior, though the dismounting bug did not trigger, however I cannot reproduce this bug reliably, so just assume it's one bug being discussed. That is, the dismount bug.

**To Reproduce**  

1.  Tame amphithere with the whole process you're supposed to (shoot it down, mount it til it likes you)
2.  Mount it.
3.  Move some distance away  
    3.a If you moved too far from where you mounted, stuff will start not being loaded (including the game unloading your mount until you go closer to your original location)
4.  You dismount and get teleported back where you mounted it.

**Versions:**

*   Minecraft: 1.12.2
*   Forge: 14.23.5.2847
*   Mod Pack : WoD 19.9.234
*   Mod Name: Ice and Fire
*   Mod Version: 1.8.3

**Additional context**  
There is nothing more to add on my end on this. No logs and no screenshots. There's no specific creature id to this.

Original report received at https://github.com/kreezxil/World-of-Dragons/issues/358

**Comment by AlexModGuy** [comment]
fixed
