### ISSUE TITLE
Issues with armor textures

### ISSUE THREAD

**Issue by Armintage1** [Alex-the-666/Ice_and_Fire#1977]
Hello, I'm having a issue with the textures of the dragon scale armor. If anyone have a solution I really apreciate it. And sorry for my bad english hehe.
![2019-10-23_21 01 52](https://user-images.githubusercontent.com/56924529/67443719-6786ab80-f5dc-11e9-8cb5-3000947c8b61.png)
![2019-10-23_21 30 26](https://user-images.githubusercontent.com/56924529/67443723-6b1a3280-f5dc-11e9-912f-ea1ea8ecff4f.png)

**Comment by juanlost** [comment]
Im having the same exact problem :c

**Comment by AlexModGuy** [comment]
mod conflict w/ better player models
