### ISSUE TITLE
Dragon Horn not working, deleting my dragons

### ISSUE THREAD

**Issue by DustyToastt** [Alex-the-666/Ice_and_Fire#1978]
Since I can't afford to constantly feed my dragon, I decided to put it in a Dragon Horn. But when I attempted to call it back out, it just wasn't there anymore, no sign of it ever existing. I tested this with several other dragons and they all went missing. Please fix this ASAP

I am using version 1.8.3

**Comment by adyrawr** [comment]
This is also happening in version 1.12.2

**Comment by DustyToastt** [comment]
> This is also happening in version 1.12.2

1.8.3 is in version 1.12.2

**Comment by Ahri0511** [comment]
normally when you have them in a dragon horn they look like they're gone but they're not move the horn in your inventory (the dragon will reappear in the horn) and then you can summon it by holding right click for a lot longer!

**Comment by Skiafray** [comment]
I've had a similar issue where the dragon horn get's deleted when I use it while mounted.
