### ISSUE TITLE
Stage 4+ Fire Dragon crashing server

### ISSUE THREAD

**Issue by adyrawr** [Alex-the-666/Ice_and_Fire#1979]
It seems to be a conflict with the dragon trying to do a certain ability and not being able to? 

The crash line: https://pastebin.com/FtHFQgbM
The entire console: https://pastebin.com/H46Ns17Y

Tbh it's probably an issue on my end but the server itself doesn't even want to run correctly without the haphazard way I have somehow put it together :")

**Comment by AlexModGuy** [comment]
dupe #1938
