### ISSUE TITLE
Dimension Provider issue

### ISSUE THREAD

**Issue by Sarous** [Alex-the-666/Ice_and_Fire#1980]
Issue summary
Crash bug related to riding Ice and Fire creatures through dimensional transports (SGCraft Stargates).

Original post and discussion on SGCraft: https://github.com/AlmuraDev/SGCraft/issues/111

Crash Reports:
<details>
<summary>---- Minecraft Crash Report ----</summary>

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  RandomPatches (randompatches-1.12.2-1.18.1.1.jar)
  Quark Plugin (Quark-r1.6-177.jar)
  Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.1.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.11-core.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  IMLoadingPlugin (infinimend-1.12-1.0.2.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 9/18/19 10:38 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at gcewing.sg.tileentity.SGBaseTE.teleportEntityToWorld(SGBaseTE.java:2386)
	at gcewing.sg.tileentity.SGBaseTE.teleportEntityToDimension(SGBaseTE.java:2364)
	at gcewing.sg.tileentity.SGBaseTE.teleportToOtherDimension(SGBaseTE.java:2344)
	at gcewing.sg.tileentity.SGBaseTE.teleportEntity(SGBaseTE.java:2262)
	at gcewing.sg.tileentity.SGBaseTE.teleportEntityAndRiders(SGBaseTE.java:2139)
	at gcewing.sg.tileentity.SGBaseTE.entityInPortal(SGBaseTE.java:2079)
	at gcewing.sg.tileentity.SGBaseTE.checkForEntitiesInPortal(SGBaseTE.java:2012)
	at gcewing.sg.tileentity.SGBaseTE.func_73660_a(SGBaseTE.java:831)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at gcewing.sg.tileentity.SGBaseTE.teleportEntityToWorld(SGBaseTE.java:2386)
	at gcewing.sg.tileentity.SGBaseTE.teleportEntityToDimension(SGBaseTE.java:2364)
	at gcewing.sg.tileentity.SGBaseTE.teleportToOtherDimension(SGBaseTE.java:2344)
	at gcewing.sg.tileentity.SGBaseTE.teleportEntity(SGBaseTE.java:2262)
	at gcewing.sg.tileentity.SGBaseTE.teleportEntityAndRiders(SGBaseTE.java:2139)
	at gcewing.sg.tileentity.SGBaseTE.entityInPortal(SGBaseTE.java:2079)
	at gcewing.sg.tileentity.SGBaseTE.checkForEntitiesInPortal(SGBaseTE.java:2012)
	at gcewing.sg.tileentity.SGBaseTE.func_73660_a(SGBaseTE.java:831)

-- Block entity being ticked --
Details:
	Name: minecraft:gcewing.sg.sgbasete // gcewing.sg.tileentity.SGBaseTE
	Block type: ID #580 (tile.sgcraft:stargateBase // gcewing.sg.block.SGBaseBlock // sgcraft:stargatebase)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (377,71,89), Chunk: (at 9,4,9 in 23,5; contains blocks 368,0,80 to 383,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #580 (tile.sgcraft:stargateBase // gcewing.sg.block.SGBaseBlock // sgcraft:stargatebase)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Terra
	All players: 1 total; [EntityPlayerMP['Silver'/235, l='Terra', x=378.24, y=71.50, z=87.28]]
	Chunk stats: ServerChunkCache: 555 Drop: 0
	Level seed: 4365448150591359093
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: {"landScheme":"vanilla","tempScheme":"medium_zones","rainScheme":"medium_zones","biomeSize":"medium","amplitude":1.0,"generateBopOre":true,"generatePoisonIvy":true,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":true,"generateEndFeatures":true,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"coordinateScale":684.412,"heightScale":684.412,"upperLimitScale":512.0,"lowerLimitScale":512.0}
	Level spawn location: World: (240,64,256), Chunk: (at 0,4,0 in 15,16; contains blocks 240,0,256 to 255,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3703363 game time, 4904871 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 44073 (now: false), thunder time: 23508 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 575767672 bytes (549 MB) / 2134114304 bytes (2035 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 2, allocated: 11, tallocated: 96
	FML: MCP 9.42 Powered by Forge 14.23.5.2836 Optifine OptiFine_1.12.2_HD_U_E3 36 mods loaded, 36 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version               | Source                                             | Signature                                |
	|:------ |:----------------- |:--------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2                | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp               | 9.42                  | minecraft.jar                                      | None                                     |
	| LCHIJA | FML               | 8.0.99.99             | forge-1.12.2-14.23.5.2836.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2836          | forge-1.12.2-14.23.5.2836.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | infinimend        | 1.0.2                 | minecraft.jar                                      | None                                     |
	| LCHIJA | randompatches     | 1.12.2-1.18.1.1       | randompatches-1.12.2-1.18.1.1.jar                  | None                                     |
	| LCHIJA | movillages        | 1.5.4                 | [1.12]MoVillages-1.5.4.jar                         | None                                     |
	| LCHIJA | absentbydesign    | 1.12.2-1.0.4          | absentbydesign-1.12.2-1.0.4.jar                    | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
	| LCHIJA | amidst-forge      | 1.12.2-0.6.1          | amidst-forge-1.12.2-0.6.1.jar                      | None                                     |
	| LCHIJA | biomesoplenty     | 7.0.1.2441            | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar      | None                                     |
	| LCHIJA | craftstudioapi    | 1.0.0                 | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
	| LCHIJA | twilightforest    | 3.9.984               | twilightforest-1.12.2-3.9.984-universal.jar        | None                                     |
	| LCHIJA | animania          | 1.6.2                 | animania-1.12.2-1.6.2.jar                          | None                                     |
	| LCHIJA | jei               | 4.15.0.268            | jei_1.12.2-4.15.0.268.jar                          | None                                     |
	| LCHIJA | quark             | r1.6-177              | Quark-r1.6-177.jar                                 | None                                     |
	| LCHIJA | autoreglib        | 1.3-32                | AutoRegLib-1.3-32.jar                              | None                                     |
	| LCHIJA | chunkpregenerator | 2.1                   | Chunk+Pregenerator+V1.12-2.1.jar                   | None                                     |
	| LCHIJA | crafttweaker      | 4.1.19                | CraftTweaker2-1.12-4.1.19.jar                      | None                                     |
	| LCHIJA | ctgui             | 1.0.0                 | CraftTweaker2-1.12-4.1.19.jar                      | None                                     |
	| LCHIJA | crafttweakerjei   | 2.0.3                 | CraftTweaker2-1.12-4.1.19.jar                      | None                                     |
	| LCHIJA | dynamictrees      | 1.12.2-0.9.5          | DynamicTrees-1.12.2-0.9.5.jar                      | None                                     |
	| LCHIJA | dynamictreesbop   | 1.12.2-1.4.1e         | DynamicTreesBOP-1.12.2-1.4.1e.jar                  | None                                     |
	| LCHIJA | erebus            | 1.0.30                | Erebus-1.0.30.jar                                  | None                                     |
	| LCHIJA | exoticbirds       | 1.0                   | Exotic+Birds+1.12.2-2.2.1.jar                      | None                                     |
	| LCHIJA | waila             | 1.8.26                | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LCHIJA | llibrary          | 1.7.19                | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire        | 1.8.1                 | iceandfire-1.8.1.jar                               | None                                     |
	| LCHIJA | ic2               | 2.8.187-ex112         | industrialcraft-2-2.8.187-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | infinitefluids    | 1.2.0                 | infinitefluids-1.11-1.2.0.jar                      | None                                     |
	| LCHIJA | malisiscore       | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                       | None                                     |
	| LCHIJA | mca               | 6.0.0-beta            | MCA-1.12.2-6.0.0-beta-universal.jar                | None                                     |
	| LCHIJA | norecipebook      | 1.2.1                 | noRecipeBook_v1.2.2formc1.12.2.jar                 | None                                     |
	| LCHIJA | quarkoddities     | 1                     | QuarkOddities-1.12.2.jar                           | None                                     |
	| LCHIJA | randomtweaks      | 1.12.2-2.7.1.0        | randomtweaks-1.12.2-2.7.1.0.jar                    | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |
	| LCHIJA | sgcraft           | 1.13.2                | SGCraft-2.0.2.jar                                  | None                                     |
	| LCHIJA | thebetweenlands   | 3.4.11                | TheBetweenlands-3.4.11-universal.jar               | 38067d6878811efb38b6a045521cfd80b9b60b38 |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
RandomPatches (randompatches-1.12.2-1.18.1.1.jar)
  com.therandomlabs.randompatches.core.RPTransformer
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.1.jar)
  com.chocohead.biab.BornInABarn
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.11-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
IMLoadingPlugin (infinimend-1.12-1.0.2.jar)
  net.crazysnailboy.mods.infinimend.asm.IMClassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Silver'/235, l='Terra', x=378.24, y=71.50, z=87.28]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
</details>

<details>
<summary>---- Minecraft Crash Report ----</summary>
WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 9/18/19 11:27 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at gcewing.sg.tileentity.SGBaseTE.teleportEntityToWorld(SGBaseTE.java:2386)
	at gcewing.sg.tileentity.SGBaseTE.teleportEntityToDimension(SGBaseTE.java:2364)
	at gcewing.sg.tileentity.SGBaseTE.teleportToOtherDimension(SGBaseTE.java:2344)
	at gcewing.sg.tileentity.SGBaseTE.teleportEntity(SGBaseTE.java:2262)
	at gcewing.sg.tileentity.SGBaseTE.teleportEntityAndRiders(SGBaseTE.java:2139)
	at gcewing.sg.tileentity.SGBaseTE.entityInPortal(SGBaseTE.java:2079)
	at gcewing.sg.tileentity.SGBaseTE.checkForEntitiesInPortal(SGBaseTE.java:2012)
	at gcewing.sg.tileentity.SGBaseTE.func_73660_a(SGBaseTE.java:831)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at gcewing.sg.tileentity.SGBaseTE.teleportEntityToWorld(SGBaseTE.java:2386)
	at gcewing.sg.tileentity.SGBaseTE.teleportEntityToDimension(SGBaseTE.java:2364)
	at gcewing.sg.tileentity.SGBaseTE.teleportToOtherDimension(SGBaseTE.java:2344)
	at gcewing.sg.tileentity.SGBaseTE.teleportEntity(SGBaseTE.java:2262)
	at gcewing.sg.tileentity.SGBaseTE.teleportEntityAndRiders(SGBaseTE.java:2139)
	at gcewing.sg.tileentity.SGBaseTE.entityInPortal(SGBaseTE.java:2079)
	at gcewing.sg.tileentity.SGBaseTE.checkForEntitiesInPortal(SGBaseTE.java:2012)
	at gcewing.sg.tileentity.SGBaseTE.func_73660_a(SGBaseTE.java:831)

-- Block entity being ticked --
Details:
	Name: minecraft:gcewing.sg.sgbasete // gcewing.sg.tileentity.SGBaseTE
	Block type: ID #254 (tile.sgcraft:stargateBase // gcewing.sg.block.SGBaseBlock // sgcraft:stargatebase)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (181,71,219), Chunk: (at 5,4,11 in 11,13; contains blocks 176,0,208 to 191,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #254 (tile.sgcraft:stargateBase // gcewing.sg.block.SGBaseBlock // sgcraft:stargatebase)
	Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: DragonGate Crash Test
	All players: 1 total; [EntityPlayerMP['Silver'/797, l='DragonGate Crash Test', x=181.40, y=75.36, z=221.57]]
	Chunk stats: ServerChunkCache: 1266 Drop: 0
	Level seed: -2797538843616219480
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (168,64,248), Chunk: (at 8,4,8 in 10,15; contains blocks 160,0,240 to 175,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 30171 game time, 30171 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 53778 (now: false), thunder time: 22124 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 357530936 bytes (340 MB) / 1068359680 bytes (1018 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2836 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID          | Version               | Source                        | Signature                                |
	|:------ |:----------- |:--------------------- |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft   | 1.12.2                | minecraft.jar                 | None                                     |
	| LCHIJA | mcp         | 9.42                  | minecraft.jar                 | None                                     |
	| LCHIJA | FML         | 8.0.99.99             | forge-1.12.2-14.23.5.2836.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge       | 14.23.5.2836          | forge-1.12.2-14.23.5.2836.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | llibrary    | 1.7.19                | llibrary-1.7.19-1.12.2.jar    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire  | 1.8.1                 | iceandfire-1.8.1.jar          | None                                     |
	| LCHIJA | malisiscore | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar  | None                                     |
	| LCHIJA | sgcraft     | 1.13.2                | SGCraft-2.0.2.jar             | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Silver'/797, l='DragonGate Crash Test', x=181.40, y=75.36, z=221.57]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
</details>

**Comment by AlexModGuy** [comment]
issue with SGBaseTE
