### ISSUE TITLE
1.12.2 Hippogryph (and possibly other tamed flying creatures) riding problems?

### ISSUE THREAD

**Issue by 0Charm0** [Alex-the-666/Ice_and_Fire#1982]
Okay, so basically every time i jump on a hippogryph and fly or even just walk (dont know yet if it's the same with dragons but i suspect it) it'll be super glitchy, like i'll be teleported back and forth the way i'm trying to go and if i'm flying up and down it does the same thing, like my hyppogryph is teleporting from the ground to me very quickly.
When i fly back and forth it's the same but it also causes it to go painfully slow and slowly glitching back down to the ground. And when i've already stopped pressing anything it continues to just fly that way for a good minute.

They didn't always used to do this and i've been trying to reconfigure things in my world to make it stop. I'm suspecting it may be a mod but i'm not totally sure.

Here's a list of the mods i have just in case it is that.
BetterFPS
Bibliocraft
ChunkAnimator
Dynamic Surroundings
VoxelMap
Fossils&Archeology Revival
JEI
NEI
RecurrentComplex
Reliquary
Rougelike Dungeons
Ruins
ToroCrafts Damage Indicators
Tough As Nails
TravellersBackpack
Veinminer
Wings

Sorry if this can't really do much as i made this account to only ask this, since i feel like i'm out of options.

**Comment by ColaLiao** [comment]
#1913

**Comment by kreezxil** [comment]
I have players that report this issue from time to time in the World of Dragons pack. 

https://github.com/kreezxil/World-of-Dragons/issues/365

**Comment by AlexModGuy** [comment]
fixed
