### ISSUE TITLE
stage 2 dragons should have the following AI of a wolf

### ISSUE THREAD

**Issue by kihgy** [Alex-the-666/Ice_and_Fire#1984]
stage 3 and above can escort, you can bring stage 1 along with you on your shoulders, you cant bring stage 2 to go adventuring with you anywhere, there is the horn and chain option, but I want them to follow me on their will. So can you make stage 2 to follow you like a tamed wolf? Stage 2 cant fly too, so it is basically just an aggressive wolf, probably will have to make stage 2 dragons to respect your personal space like cockatrices too

**Comment by kihgy** [comment]
stage 2 should have the following option instead of escorting

**Comment by AlexModGuy** [comment]
no
