### ISSUE TITLE
Cannot get entity data on entity without data cap

### ISSUE THREAD

**Issue by FrostCreeper07** [Alex-the-666/Ice_and_Fire#1988]
So lately i've been having a crash issue between LLibrary and Ice and Fire [here](https://pastebin.com/fSJzQUrr) is the crashlog, i can load into my world but then it crashes with said error.

**Comment by FrostCreeper07** [comment]
Can you please respond and tell me if your at least looking in to it

**Comment by AlexModGuy** [comment]
issue is with llibrary
