### ISSUE TITLE
Thousand of podiums... 

### ISSUE THREAD

**Issue by Couldbne1** [Alex-the-666/Ice_and_Fire#1989]
I am having an issue with literally thousands upon thousands of podiums spawning on my server, like covering the trees and mountainside. (part of a [report ](https://docs.google.com/spreadsheets/d/1LesFSKmL6-IIVQIjnsiTl6c6JsCudJPPA0nKJ0kUQio/edit#gid=0) from the server of me /killing them) Is there anything I can do to stop this short of removing the mod?

**Comment by AlexModGuy** [comment]
Seems like a id conflict
