### ISSUE TITLE
Cannot Loot Dragon Skeleton

### ISSUE THREAD

**Issue by Fatestoryteller** [Alex-the-666/Ice_and_Fire#1991]
I have right clicked the dragon skeletons I have found in my single player world and nothing happens. It did this with an empty hand, and with a pickaxe, sword, and regular axe. It moves when I move against it, but otherwise I cannot seem to interact with it. I am playing the most recent 1.12.2 version. Thank you in advance for the time you take to read this and for the mod in general.

**Comment by Fatestoryteller** [comment]
Ok, so I am either wrong, and this was never a problem, or it was fixed when I opened it up to lan... because my wife and I can now loot skeletons just fine... but I could have sworn I couldn't do it before. Could also be that I couldn't loot skeletons till after I looted my first dragon carcass because that was the first time we killed a dragon on my world.

**Comment by wolf653** [comment]
Dragon hitboxes tend to be a bit annoying click near the torso perhaps
