### ISSUE TITLE
dragons vanish for no reason

### ISSUE THREAD

**Issue by drecalen** [Alex-the-666/Ice_and_Fire#1992]
whether it is fighting them, or looting them, or riding tamed dragons,
they seem to simply vanished into thin air as if they despawned, even AFTER i changed the config to prevent ANY despawning. 
3 out of 5 times they just vanish. 
need to know how to fix this so i can give the a-ok to the people on my server

**Comment by TheFlash787** [comment]
Hey! This is happening for us too. Running version `1.7.1-1.12.2` as part of the RLCraft modpack. This might happen while someone is flying with the dragon, hatching the egg (producing no dragon in the end) or doing nothing with it. There are other cases where the horn ends up deleting the dragon, too.

**Comment by TheFlash787** [comment]
Related? https://github.com/Alex-the-666/Ice_and_Fire/issues/1978

**Comment by Netbox-0** [comment]
Hi, we're running version 1.8.3-1.12.2 and it is happening to us as well. The dragon was chained to a cobblestone wall in a chunkloaded base. The dragon disappeared but the wall still had the chain around it. The dragon horn or flute did nothing to get it back. Rightclicking the chain did not bring the dragon back.

**Comment by GooberYT** [comment]
I looked in the log for my server when my dragon disappeared and here is what it said:
[12:41:28] [Server thread/WARN] [minecraft/NetHandlerPlayServer]: Fire Dragon moved wrongly!
[12:41:29] [Server thread/WARN] [minecraft/NetHandlerPlayServer]: Fire Dragon (vehicle of GooberYT) moved too quickly! 14.286683366264455,0.0,-4.154202016827426

So is the server despawning them because they think its someone cheating?

**Comment by border999** [comment]
I'm having a similar issue. But I believe my issue is the dragons from Ice and Fire begin ticking in CC worlds because they aren't properly handling how to pathfind or some such thing in the altered chunk system that CC implements.

**Comment by TheFlash787** [comment]
https://github.com/Alex-the-666/Ice_and_Fire/issues/2017 https://github.com/Alex-the-666/Ice_and_Fire/issues/2043

**Comment by TheFlash787** [comment]
@Alex-the-666 Are we able to have an update on this?

**Comment by stacytritt** [comment]
i need this to be fixed pleasee @Alex-the-666

**Comment by juanlost** [comment]
Having the same problem with Hippogryph, vanish when flying, i also run the command "/gamerule disableElytraMovementCheck" but still having the issue.

**Comment by AlexModGuy** [comment]
fixed vehicle vanishing bug
