### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by bigenergy** [Alex-the-666/Ice_and_Fire#1994]
When I teleport to a random point on my server, if there is a dragon nearby, I get a client crash
Forge 2847
iceandfire-1.8.3

https://paste.dimdev.org/ajeduvisuz.mccrash

**Comment by gamax92** [comment]
This issue was likely caused by Vampirism. It has a special entity that only appears on Halloween, this entity adds a DataParameter to EntityTameable, which will create an ID conflict with any class extending from EntityTameable if the special entity's DataParameter register's afterwards.

**Comment by AlexModGuy** [comment]
^^^. Report this to their devs.
