### ISSUE TITLE
Visual Bug? 

### ISSUE THREAD

**Issue by Fufox** [Alex-the-666/Ice_and_Fire#1999]
![bug](https://user-images.githubusercontent.com/57326746/68089561-17a7b000-fe38-11e9-9542-6d1b40432726.jpg)

How can i fix it? i need help :( 
This happens with Dragon scale armors and dragonsteel armors only 👎

**Comment by ColaLiao** [comment]
do not use any character animation mod,
if use mo'bends mod, turn off player animation in the config file.

**Comment by Fufox** [comment]
You're God damn right. Thank you very much!
