### ISSUE TITLE
Error code java.lang.NoSuchFieldError: TAB when updating version of RLCraft Ice and Fire

### ISSUE THREAD

**Issue by Nyixid** [Alex-the-666/Ice_and_Fire#2002]
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  LibLoader (# LibLoader.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.4.22.2-build.0405.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  LoadingPlugin (Reskillable-1.12.2-1.12.5.jar)
  MMFMLCorePlugin (MultiMine-1.12.2.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  CoreMod (TickProfiler-1.12-0.0.7.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.16-universal.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.21_mc1.12.2.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  TNTUtilities Core (tnt_utilities-mc1.12-1.2.3.jar)
  CreativePatchingLoader (CreativeCore_v1.9.67_mc1.12.2.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 11/7/19 1:54 PM
Description: Initializing game

java.lang.NoSuchFieldError: TAB
	at com.chaosbuffalo.spartanfire.init.ItemRegistrySFire.registerItems(ItemRegistrySFire.java:86)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_211_ItemRegistrySFire_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.chaosbuffalo.spartanfire.init.ItemRegistrySFire.registerItems(ItemRegistrySFire.java:86)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_211_ItemRegistrySFire_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1437355608 bytes (1370 MB) / 2135949312 bytes (2037 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 121 mods loaded, 121 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                          | Version              | Source                                         | Signature                                |
	|:----- |:--------------------------- |:-------------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                   | 1.12.2               | minecraft.jar                                  | None                                     |
	| LCH   | mcp                         | 9.42                 | minecraft.jar                                  | None                                     |
	| LCH   | FML                         | 8.0.99.99            | forge-1.12.2-14.23.5.2838.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                       | 14.23.5.2838         | forge-1.12.2-14.23.5.2838.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | creativecoredummy           | 1.0.0                | minecraft.jar                                  | None                                     |
	| LCH   | itemphysic                  | 1.4.0                | minecraft.jar                                  | None                                     |
	| LCH   | ivtoolkit                   | 1.3.3-1.12           | minecraft.jar                                  | None                                     |
	| LCH   | foamfixcore                 | 7.7.4                | minecraft.jar                                  | None                                     |
	| LCH   | tnt_utilities_core          | 1.2.3                | minecraft.jar                                  | None                                     |
	| LCH   | dsurroundcore               | 3.5.4.3              | minecraft.jar                                  | None                                     |
	| LCH   | forgeendertech              | 1.12.2-4.4.22.2      | ForgeEndertech-1.12.2-4.4.22.2-build.0405.jar  | None                                     |
	| LCH   | adhooks                     | 1.12.2-3.2.2.0       | AdHooks-1.12.2-3.2.2.0-build.0220.jar          | None                                     |
	| LCH   | advanced-fishing            | 1.3.3                | Advanced-Fishing-1.12.2-1.3.3.jar              | None                                     |
	| LCH   | alcatrazcore                | 1.0.4                | alcatrazcore-1.0.4.jar                         | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LCH   | antiqueatlas                | 4.5.1                | antiqueatlas-1.12.2-4.5.1.jar                  | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCH   | antiqueatlasoverlay         | 1.2                  | antiqueatlas-1.12.2-4.5.1.jar                  | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCH   | anvilpatch                  | 1.0.0                | anvilpatch-1.0.0.jar                           | None                                     |
	| LCH   | aquaculture                 | 1.6.8                | Aquaculture-1.12.2-1.6.8.jar                   | None                                     |
	| LCH   | carrots                     | 1.0.0b1              | carrotslib-mc1.12.2-1.0.0b1.jar                | None                                     |
	| LCH   | armorunder                  | 1.0.0                | armorunder-mc1.12.2-1.0.0.jar                  | None                                     |
	| LCH   | autoreglib                  | 1.3-32               | AutoRegLib-1.3-32.jar                          | None                                     |
	| LCH   | bacodifficulty              | 1.0.3                | BacoDifficulty-1.0.3.jar                       | None                                     |
	| LCH   | battletowers                | 1.6.5                | BattleTowers-1.12.2.jar                        | None                                     |
	| LCH   | baubles                     | 1.5.2                | Baubles-1.12-1.5.2.jar                         | None                                     |
	| LCH   | baubleshud                  | 5.0.2                | BaublesHud-1.12.2-5.0.2.jar                    | None                                     |
	| LCH   | mujmajnkraftsbettersurvival | 1.3.4                | Better_Survival-1.3.4(1.12.1).jar              | None                                     |
	| LCH   | bettercombatmod             | 1.5.6                | BetterCombat-1.12.2-1.5.6.jar                  | None                                     |
	| LCH   | forgelin                    | 1.8.4                | Forgelin-1.8.4.jar                             | None                                     |
	| LCH   | betterfoliage               | 2.2.0                | BetterFoliage-MC1.12-2.2.0.jar                 | None                                     |
	| LCH   | bloodmoon                   | 1.5.3                | Bloodmoon-MC1.12.2-1.5.3.jar                   | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCH   | bnbgaminglib                | 2.17.6               | BNBGamingLib-1.12.2-2.17.6.jar                 | None                                     |
	| LCH   | bountifulbaubles            | 0.0.1                | Bountiful Baubles-1.12.2-0.1.2.jar             | None                                     |
	| LCH   | campfire                    | 1.2                  | campfire-1.12-v1.2.jar                         | None                                     |
	| LCH   | carryon                     | 1.12.2               | CarryOn MC1.12.2 v1.12.2.jar                   | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCH   | chunkanimator               | 1.2                  | ChunkAnimator-MC1.12-1.2.jar                   | None                                     |
	| LCH   | toughasnails                | 3.1.0.141            | ToughAsNails-1.12.2-3.1.0.141-universal.jar    | None                                     |
	| LCH   | comforts                    | 1.4.1.2              | comforts-1.12.2-1.4.1.2.jar                    | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCH   | reskillable                 | 1.12.2-GRADLE:BUILD  | Reskillable-1.12.2-1.12.5.jar                  | None                                     |
	| LCH   | compatskills                | 1.12.2-1.16.3        | CompatSkills-1.12.2-1.16.3.jar                 | None                                     |
	| LCH   | coralreef                   | 2.0                  | CoralReef-2.5-1.12.2.jar                       | None                                     |
	| LCH   | wearablebackpacks           | 3.1.4                | WearableBackpacks-1.12.2-3.1.4.jar             | None                                     |
	| LCH   | corpsecomplex               | 1.0.6                | corpsecomplex-1.12.2-1.0.6.jar                 | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCH   | craftablechainmail          | 1.0                  | craftablechainmail-1.0.jar                     | None                                     |
	| LCH   | craftablehorsearmour        | 1.3                  | CraftableHorseArmour-1.3.0-1.12.jar            | None                                     |
	| LCH   | crafttweaker                | 4.1.19               | CraftTweaker2-1.12-4.1.19.jar                  | None                                     |
	| LCH   | ctgui                       | 1.0.0                | CraftTweaker2-1.12-4.1.19.jar                  | None                                     |
	| LCH   | jei                         | 4.15.0.268           | jei_1.12.2-4.15.0.268.jar                      | None                                     |
	| LCH   | crafttweakerjei             | 2.0.3                | CraftTweaker2-1.12-4.1.19.jar                  | None                                     |
	| LCH   | creativecore                | 1.9.9                | CreativeCore_v1.9.67_mc1.12.2.jar              | None                                     |
	| LCH   | custommainmenu              | 2.0.9                | CustomMainMenu-MC1.12.2-2.0.9.jar              | None                                     |
	| LCH   | defiledlands                | 1.4.2                | defiledlands-1.12.2-1.4.2.jar                  | None                                     |
	| LCH   | disenchanter                | 1.6                  | disenchanter-[1.12]1.6.jar                     | None                                     |
	| LCH   | dldungeonsjbg               | 1.12.10              | DoomlikeDungeons-1.12.10-MC1.12.2.jar          | None                                     |
	| LCH   | dynamictrees                | 1.12.2-0.9.5         | DynamicTrees-1.12.2-0.9.5.jar                  | None                                     |
	| LCH   | traverse                    | 1.6.0                | Traverse-1.12.2-1.6.0-69.jar                   | None                                     |
	| LCH   | dttraverse                  | 1.5                  | dttraverse-1.5.jar                             | None                                     |
	| LCH   | enchdesc                    | 1.1.19               | EnchantmentDescriptions-1.12.2-1.1.19.jar      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | enhancedvisuals             | 1.0                  | EnhancedVisuals_v1.2.6_mc1.12.2.jar            | None                                     |
	| LCH   | familiarfauna               | 1.0.11               | FamiliarFauna-1.12.2-1.0.11.jar                | None                                     |
	| LCH   | fbp                         | 2.4.1                | FancyBlockParticles-1.12.x-2.4.1.jar           | None                                     |
	| LCH   | firstaid                    | 1.6.10               | firstaid-1.6.10.jar                            | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| LCH   | foamfix                     | 0.10.5-1.12.2        | foamfix-0.10.5-1.12.2.jar                      | None                                     |
	| LCH   | foodexpansion               | 1.3                  | FoodExpansion1.3.3-1.12.2.jar                  | None                                     |
	| LCH   | tschipplib                  | 1.1.3                | TschippLib MC1.12.2 v1.1.3.jar                 | None                                     |
	| LCH   | forgottenitems              | 1.2.1                | ForgottenItems MC1.12.2 v1.2.1.jar             | None                                     |
	| LCH   | globalgamerules             | 2.2                  | GlobalGameRules-1.12.2-2.2.7.jar               | None                                     |
	| LCH   | grapplemod                  | 1.12.2-v11.1         | grapplemod-v11.1-1.12.2.jar                    | None                                     |
	| LCH   | llibrary                    | 1.7.19               | llibrary-1.7.19-1.12.2.jar                     | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | iceandfire                  | 1.8.0                | iceandfire-1.8.0.jar                           | None                                     |
	| LCH   | infernalmobs                | 1.7.6                | InfernalMobs-1.12.2.jar                        | None                                     |
	| LCH   | inventorytweaks             | 1.64+dev.146.2180b27 | InventoryTweaks-1.64+dev.146.jar               | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | itlt                        | 1.0.0                | itlt-1.12-1.0.0.jar                            | None                                     |
	| LCH   | levelup2                    | ${version}           | Level Up! 2-1.1.23-1.12.jar                    | None                                     |
	| LCH   | loadingscreens              | 0.3.1                | LoadingScreens-1.12.2-0.3.1.jar                | None                                     |
	| LCH   | lostcities                  | 2.0.21               | lostcities-1.12-2.0.21.jar                     | None                                     |
	| LCH   | lostsouls                   | 1.1.4                | lostsouls-1.12-1.1.4.jar                       | None                                     |
	| LCH   | lycanitesmobs               | 2.0.0.9 - MC 1.12.2  | lycanitesmobs-1.12.2-2.0.0.9.jar               | None                                     |
	| LCH   | reborncore                  | 3.16.3.476           | RebornCore-1.12.2-3.16.3.476-universal.jar     | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCH   | mainmenuscale               | 1.0                  | MainMenuScale-1.3.2.jar                        | None                                     |
	| LCH   | mobends                     | 0.24                 | mobends-0.24_for_MC-1.12.jar                   | None                                     |
	| LCH   | multimine                   | 1.6.2                | MultiMine-1.12.2.jar                           | None                                     |
	| LCH   | neat                        | 1.4-17               | Neat 1.4-17.jar                                | None                                     |
	| LCH   | notreepunching              | 2.0.18               | notreepunching-2.0.18.jar                      | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LCH   | potioncore                  | 1.8_for_1.12.2       | PotionCore-1.8_for_1.12.2.jar                  | None                                     |
	| LCH   | potionfingers               | r1.0-5               | PotionFingers-r1.0-5.jar                       | None                                     |
	| LCH   | qualitytools                | 1.0.7_for_1.12.2     | QualityTools-1.0.7_for_1.12.2.jar              | None                                     |
	| LCH   | realistictorches            | 2.1.1                | RealisticTorches-1.12.2-2.1.1.jar              | None                                     |
	| LCH   | reccomplex                  | 1.4.8.2              | RecurrentComplex-1.4.8.2.jar                   | None                                     |
	| LCH   | resourceloader              | 1.5.3                | ResourceLoader-MC1.12.1-1.5.3.jar              | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCH   | roguelike                   | 1.8.0                | RoguelikeDungeons-1.12.2-1.8.0.jar             | None                                     |
	| LCH   | roughtweaks                 | 1.0                  | roughTweaks0.2.4-1.12.2.jar                    | None                                     |
	| LCH   | ruins                       | 17.2                 | Ruins-1.12.2.jar                               | None                                     |
	| LCH   | silentlib                   | 3.0.13               | SilentLib-1.12.2-3.0.13+167.jar                | None                                     |
	| LCH   | scalinghealth               | 1.3.37               | ScalingHealth-1.12.2-1.3.40+145.jar            | None                                     |
	| LCH   | sereneseasons               | 1.2.16               | SereneSeasons-1.12.2-1.2.16-universal.jar      | None                                     |
	| LCH   | sit                         | v1.2.3               | sit-1.12.2-v1.2.3.jar                          | None                                     |
	| LCH   | somanyenchantments          | 0.4.4                | So Many Enchantments V0.4.4.jar                | None                                     |
	| LCH   | soundfilters                | 0.11_for_1.12        | SoundFilters-0.11_for_1.12.jar                 | None                                     |
	| LCH   | spartanweaponry             | beta 1.3.1           | SpartanWeaponry-1.12.2-beta-1.3.1.jar          | None                                     |
	| LCH   | spartanfire                 | 0.05                 | spartanfire-0.05.jar                           | None                                     |
	| LCH   | spartanshields              | 1.5.4                | SpartanShields-1.12.2-1.5.4.jar                | None                                     |
	| LCH   | spawnercontrol              | 1.6.3b               | SpawnerControl-1.6.3b.jar                      | None                                     |
	| LCH   | stg                         | 1.12.2-1.2.3         | stg-1.12.2-1.2.3.jar                           | None                                     |
	| LCH   | switchbow                   | 1.5.7                | switchbow-1.5.7.jar                            | None                                     |
	| LCH   | tanspit                     | 1.12.2-1.3           | tanspit-1.12.2-1.3.jar                         | None                                     |
	| LCH   | tickprofiler                | 1.12-0.0.7           | TickProfiler-1.12-0.0.7.jar                    | None                                     |
	| LCH   | tnt_utilities               | 1.2.3                | tnt_utilities-mc1.12-1.2.3.jar                 | None                                     |
	| LCH   | toolbelt                    | 1.9.10               | ToolBelt-1.12.2-1.9.10.jar                     | None                                     |
	| LCH   | travellersbackpack          | 1.0.20.20            | TravellersBackpack-1.12.2-1.0.20.20.jar        | None                                     |
	| LCH   | xat                         | 0.25.2               | Trinkets and Baubles-1.12.2-0.25.2.jar         | None                                     |
	| LCH   | trumpetskeleton             | 1.12-1.0.2.1         | trumpetskeleton-1.12-1.0.2.1.jar               | None                                     |
	| LCH   | tumbleweed                  | 1.11-0.4.5           | tumbleweed-1.11-0.4.5.jar                      | None                                     |
	| LCH   | variedcommodities           | 1.12.2               | VariedCommodities_1.12.2(15may18.jar           | None                                     |
	| LCH   | waystones                   | 4.0.72               | Waystones_1.12.2-4.0.72.jar                    | None                                     |
	| LCH   | wolfarmor                   | 2.2.3.6              | wolfarmor-1.12.2-2.2.3.1798-universal.jar      | None                                     |
	| LCH   | xpfromharvest               | 1.1.0                | xpfromharvest-1.12.2-1.1.0.jar                 | None                                     |
	| LCH   | xpbook                      | v1.1.1               | xptome-1.12.2-v1.1.1.jar                       | None                                     |
	| LCH   | orelib                      | 3.5.2.2              | OreLib-1.12.2-3.5.2.2.jar                      | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dsurround                   | 3.5.4.3              | DynamicSurroundings-1.12.2-3.5.4.3.jar         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dshuds                      | 3.5.4.0              | DynamicSurroundingsHuds-1.12.2-3.5.4.0BETA.jar | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | phosphor-lighting           | 1.12.2-0.2.6         | phosphor-1.12.2-0.2.6+build50-universal.jar    | f0387d288626cc2d937daa504e74af570c52a2f1 |

	Loaded coremods (and transformers): 
LibLoader (# LibLoader.jar)
  
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CorePlugin (ForgeEndertech-1.12.2-4.4.22.2-build.0405.jar)
  
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  
LoadingPlugin (Reskillable-1.12.2-1.12.5.jar)
  codersafterdark.reskillable.base.asm.ClassTransformer
MMFMLCorePlugin (MultiMine-1.12.2.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
CoreMod (TickProfiler-1.12-0.0.7.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.16-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
ItemPatchingLoader (ItemPhysic_Full_1.4.21_mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
TNTUtilities Core (tnt_utilities-mc1.12-1.2.3.jar)
  ljfa.tntutils.asm.ExplosionTransformer
CreativePatchingLoader (CreativeCore_v1.9.67_mc1.12.2.jar)
  
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 440.97' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.16.3.476
		Runtime Debofucsation 1
		RenderEngine: 0
	Launched Version: forge-14.23.5.2838
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 440.97, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz`

**Comment by Faoost** [comment]
I have the same issue

**Comment by Faoost** [comment]
So in version of RLCraft "Spartan and Fire" has version 0.0.5, I updated it to 0.0.7 and RLCraft version 2.8.1 started. Thx to XzeroAir

**Comment by Faoost** [comment]
And remove ISeeDragons from mods, it cause many errors, my server crashed sometimes even if you shoot dragon with bow
