### ISSUE TITLE
Bug: Dragons turn blocks to charred or frozen ones they shouldn’t be able to. Like Bedrock!

### ISSUE THREAD

**Issue by SirAron111** [Alex-the-666/Ice_and_Fire#2003]
Bug: Dragons turn blocks to charred or frozen ones they shouldn’t be able to. Like Bedrock!

It’s like I stated in the title. Dragons can Burn or Freeze trough bedrock and then the player or even the dragon can break through the bedrock layer.

I think there should be an option as to set what blocks by block name or at least by block hardness dragons should be able to burn. It doesn’t make much sense if they can burn/freeze bedrock or obsidian etc. Dirt,Grass,Stone etc are ok but not such tough/unbreakable blocks.

This also btw results in these blocks all turning to normal Stone or dirt when they revert, instead of the actual block they once have been. This is a similar issue with dragons who burn buildings made from different materials all turning into clean stone.

**Comment by ghost** [comment]
There is already a config option for blacklisting blocks that dragons cannot break or burn.

**Comment by SirAron111** [comment]
Ye but I mean some blocks should be default right like flipping bedrock especially since the last update where dragons actually started hunting players, you see things like an underground dragon being pushed around when it sleeps glitching into the wall than digging upwards suddenly living in the nearest players base, burning holes trough the world… I mean its good they finally get to the player but still. 
![2019-11-13_21 18 50](https://user-images.githubusercontent.com/39855956/68800915-3e958b80-065b-11ea-8b5f-82b41ad14868.png)
i even changed it all to withlist and reversed all blocks so i  didnt add badrock and instead added dirt and grass and stuff but that option doesnt work at all they simply destroy everything than....also underground dragons that glitched into walls or so simply come at you like from 1k blocks away. is tehre a way to turn of dragons breath attacks tturning blocks? i want them do break blocks with the body but not with fire or ice transforming them.

**Comment by SirAron111** [comment]
https://github.com/Alex-the-666/Ice_and_Fire/issues/2012 Same issue. I did blacklist bedrock i even tried it and it still gets turned. The fire or the spreading fire and ice etc from dragons ignores certain blocks even if they are on that list. it works fine for chests and stuff but bedrock simply gets stoned

**Comment by Mike-U5** [comment]
@SirAron111 is right. Dragons do not respect the blacklist.
Seems like it's still not fixed.
