### ISSUE TITLE
changing a mobs homepoint while riding them

### ISSUE THREAD

**Issue by kihgy** [Alex-the-666/Ice_and_Fire#2005]
This is a mechanic unique to dragons atm, you can look down, and right click them with food, or horn to heal or immediately capture them, this is very useful, and need to be improved. Firstly, to other rideable mobs like gryphs, campus, and amphithere, look down and right click to heal while riding them. Secondly, is the dragon staff, it can be right clicked and it will alter the order of the mob, but the order would just be resetted when the player get off. The staff should alter the homepoint position instead of the order, changing or removing the homepoint, on other mobs this should be done with a stick while riding them, this way, one can safely set the homepoint to the new location to prevent the mob from flying away before you can reach them again.

**Comment by AlexModGuy** [comment]
no
