### ISSUE TITLE
(Suggestion) custom dragon nests

### ISSUE THREAD

**Issue by NoahNinja** [Alex-the-666/Ice_and_Fire#201]
I want my dragon to be able to wander and not fly away to never be seen again, maybe you could take the dragon staff and shift-right click on a block to assign a home point for the nearest tame dragon, it will stay in a 64 block radius of this point, it will also fly to that point at night.

**Comment by GundunUkan** [comment]
If this is added I'll be very happy. You won't have to fly and take your dragon back in creative.

**Comment by Kajtetto** [comment]
This is a great idea! And it solves many problems. It is also logical that dragons should have a home point where they would sleep.

**Comment by Alex-the-666** [comment]
Move this to suggestion tracker https://github.com/Alex-the-666/Ice-and-Fire-Suggestions/issues
