### ISSUE TITLE
Deathworms do not appear to respect config changes - Version 1.8.3

### ISSUE THREAD

**Issue by Mario90900** [Alex-the-666/Ice_and_Fire#2018]
I am running version 1.8.3 of the mod, in a kitchen sink modpack I am putting together, and I attempted to tune down the spawn rates for Cockatrice and Deathworms in the deserts. I turned it down a ton, reducing both of their spawn weights to 1, and the spawn check up to 14. It appears to work with Cockatrice, as I rarely ever see them spawn while flying around in creative, but Deathworms still spawn upwards to 25-30 of them around me after exploring a desert a bit. I run /cofh killall to check the counts of them around me.

It also seems like they do not spawn through regular mob spawns? I left the game to idle for a few ingame days, and none actually spawned around me. Do they only spawn during world generation? Thanks for your help, and keep up the great work!

**Comment by wolf653** [comment]
Did you edit the configs while the world was open if so it will just reset back to the former setting edit the configs in the main menu

**Comment by Mario90900** [comment]
No, I've double checked the settings. The config file still reads the settings I set it to, as well as checking the ingame config and how the game is reading it.

**Comment by Mario90900** [comment]
On further testing, I get the feeling that there is a disconnect between worldgen spawns and regular hostile spawning? I was able to get 44 Cockatrice and 22 Deathworms to spawn teleporting around to a desert in a test world, but after getting rid of them with the killall command, they rarely if ever respawn back, which is likely do to my cranking up of the settings. I realize it may also be important to note that I am running Biomes O Plenty, though I am not sure if those biomes would be much different.

There also might be inconsistencies with the configs for spawn weight and the secondary check? The Trolls have their default spawn rate set to 40, and the config says that lower = lower chance to spawn. Both Cockatrice and Deathworms have the same config and say the same, which a much smaller weight to them. Yet I've never seen a troll spawn despite looking, and the other two are common. Is the config actually being read the other way around, where higher is less common?

**Comment by AlexModGuy** [comment]
for some mobs, yes. Many mobs, especially those that generate in some sort of "structure" like the dragons and gorgons and whatnot, spawn as world generation.
