### ISSUE TITLE
(Suggestion) Ender dragon swapper

### ISSUE THREAD

**Issue by Kajtetto** [Alex-the-666/Ice_and_Fire#202]
Since the ender dragon is already in game, it would be cool if you swapped his model to your dragon model and gave him some new attacks as well, so he wasn't weaker than the ice & fire dragons.

Also after killing the dragon when he drops the egg it would be cool if you could get you your own ender dragon. I know that you said that you would not add any more elemental dragons, but the ender dragon is already in game as i said before so i think that would be cool.

**Comment by Alex-the-666** [comment]
going to move this to suggestion tracker.

**Comment by Kajtetto** [comment]
OK
