### ISSUE TITLE
Dragon Sound Effects Are Ridiculously Broken

### ISSUE THREAD

**Issue by Boolyman** [Alex-the-666/Ice_and_Fire#203]
You can hear dragon wings flapping at the same volume over half a dozen chunks away.  There is no directional indicator, no increasing or decreasing volume as you get  closer or move further away.  The people playing my pack end up turning off their Friendly Creature volume because its so annoying.  Can you please either give the sound the appropriate modulation based on distance and position.... or make it so you can't hear it so far away.

Also, there are high amounts of block lag whenever players are within a 2 chunk radius of a dragon.  I will turn off the dragon's abilities to break blocks and see if that helps... but I would rather the issue just get fixed,.

**Comment by GundunUkan** [comment]
It'll be a cool idea to also make the dragons's roar be heard from very far away, much like the wing flapping right now, so you could be just walkin around casually and suddenly hear a mighty roar and start to panic. XD I dunno, I just think it'll add a little bit more epicness to a dragon encounter.

**Comment by NoahNinja** [comment]
Gundanukan, maybe you could hear a faint breathing noise when above a dragon lair to make them easier to find
