### ISSUE TITLE
block of silver and gold pile

### ISSUE THREAD

**Issue by kihgy** [Alex-the-666/Ice_and_Fire#2034]
copy of snow block and snow layer mechanic, when you fill a treasure pile to an extend, it should create a full block which you can mine with silk touch to obtain the full block, if not then the block break into the amount of piles that made it, pile block can create the same amount of piles that made it, and those piles can be used to create a full block in the crafting grid

**Comment by kihgy** [comment]
not sure if it take more than 9 layers to create 1 full block tho

**Comment by AlexModGuy** [comment]
no
