### ISSUE TITLE
Ice Dragon Eggs

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#204]
Fire dragon eggs take roughly 5 min to hatch but some times ice dragon eggs take much much longer. i waited for over an hour for 6 ice dragon eggs to hatch and i don't think that they were ever going too. i have tried everything i can think of. loading new worlds, using different ice dragon eggs, putting egg in before water and vice versa, going to cold biomes, surrounding the egg in different forms of ice or snow... you get the idea.

**Comment by NoahNinja** [comment]
You have to be above a certain world height to hatch ice eggs, I built a pillar about 30 blocks high, then made a pool of water at the top, put and egg in, and it hatched

**Comment by PlatinumFox** [comment]
is this confirmed by the devs?

**Comment by Alex-the-666** [comment]
If its taking so long break it and put it back - the egg is checking if the dragon's hitbox area is large enough so it wont suffocate on birth.

**Comment by PlatinumFox** [comment]
i did keep breaking some but they still would not hatch. also it was in a plains biome...so i don't know if the egg was detecting grass blocks as a threat or not but i am pretty sure that there was enough room for it to hatch.
