### ISSUE TITLE
Hovering over the bestiary crashes the game - RLCRAFT

### ISSUE THREAD

**Issue by Seanom** [Alex-the-666/Ice_and_Fire#2041]
In RL craft(twitch launcher), it appears something from the Ice and Fire mod has been tweaked/removed and this causes the game to crash when I mouse over the bestiary.(I'm not certain if that's due to Shivaxi doing some tweaking or if it's an update from a previous version.

I'm also not sure where to find the list of unlocked items from the bestiary but here is a crash report 
[crash-2019-11-17_08.18.40-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/3855385/crash-2019-11-17_08.18.40-client.txt)

It does not matter where the bestiary is located, but a quick assumption is that something was removed that has already been unlocked and that's causing an out of bounds exception. 

It first occurred when the item was in the lectern but crashes every time the contents of the appears bestiary displays. (Currently in the hotbar of the player). Holding the bestiary is possible but displaying it's contents is not.

I managed to find a older version using the default java launcher that works this is the list bestiary list 
![image](https://user-images.githubusercontent.com/331839/69005607-594a5780-091c-11ea-9c98-3848aec84509.png)

: edit loading the save up in the older java version is fine, so this appears to be something related to the updated RL craft which affects the bestiary?

Ice and Fire version is 1.8.1 in the java version and 1.7.1 in the twitch version. (I think I may have just spotted the issue)

**Comment by AlexModGuy** [comment]
fixed in 1.8.3
