### ISSUE TITLE
Glacier Biome spawning too frequently

### ISSUE THREAD

**Issue by Knightdream144** [Alex-the-666/Ice_and_Fire#205]
Hi there, So I appear to be encountering a large amount of Glacier Biomes that are spawning throughout my world. I don't mind having the biome in my world but it seems like it spawns too often. Is it possible somehow or someway to disable it or turn the spawn rate down?

**Comment by NoahNinja** [comment]
You just got lucky, I spent 10 minutes flying around in creative, not a single one

**Comment by Knightdream144** [comment]
interesting, However some maps I find a reduced spawn rate of these biomes. But as you said its prob just luck

**Comment by Alex-the-666** [comment]
should be fixed in coming 1.11.2 edition
