### ISSUE TITLE
Dragon horn glitch

### ISSUE THREAD

**Issue by Kevin671x** [Alex-the-666/Ice_and_Fire#2050]
So, I just encountered a glitch where if you put two of the same colored dragons in two different horns, they both look like males. I had one stage 5 female fire dragon that was Emerald and in full diamond armor.. Shortly after, I got another Emerald Fire Dragon that was male and grew it to stage 5. After doing this, I released my female dragon, (the first one I had) and It came out looking like a male but still said female. Additionally, when I released my male emerald dragon, it had the diamond armor of my female dragon, yet I never game him one.  Another weird thing both the female and male dragons started switching textures between male and female.

**Comment by AlexModGuy** [comment]
fixed
