### ISSUE TITLE
Dragon Grabbing may make world unplayable.

### ISSUE THREAD

**Issue by Carro1001** [Alex-the-666/Ice_and_Fire#2051]
There is a very rare chance that if a dragon grabs a player and something forces the dragon to "release" the player, the internal server cannot comprehend where the player is, and the world is no longer joinable, for example, if a dragon grabs you and it dies, there is a chance of this error ocurring, sadly the command log doesn't give me any information either.
![image](https://user-images.githubusercontent.com/47877096/69283651-90926000-0bcb-11ea-9044-0ff46d43c442.png)

The game output is also spammed by this 
![image](https://user-images.githubusercontent.com/47877096/69283687-a2740300-0bcb-11ea-814e-39bd21d2f45f.png)

There is no crash report to it, so i cannot give more information on this issue, it happened more than once to me before, though.

Update: I found some crash reports supposedly related to the problem.
[crash-2019-11-20_20.44.58-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/3872093/crash-2019-11-20_20.44.58-client.txt)

**Comment by Devintrainer** [comment]
Except same issue, except it's EVERY TIME I DISMOUNT A DRAGON.

**Comment by AlexModGuy** [comment]
fixed
