### ISSUE TITLE
Dragon despawning in RLcraft while ridden

### ISSUE THREAD

**Issue by Iamoutofideas** [Alex-the-666/Ice_and_Fire#2052]
Yo my dragon just completely despawned. idk what happened to it. maybe if you could make a way to summon a dragon you've already tamed or something?

**Comment by wolf653** [comment]
Were you holding a dragon horn?

**Comment by Iamoutofideas** [comment]
might have been my in my hotkeys. I think I was using a sword at the time. But it's not in my horn.. lmao.

**Comment by AlexModGuy** [comment]
RLCraft version is no longer supported.
