### ISSUE TITLE
1.8.3 , no loot at dragon chests..

### ISSUE THREAD

**Issue by tealtoxic** [Alex-the-666/Ice_and_Fire#2054]
updated to latest. and friends report that no more loots from dragon chests. i went and check around for new dragon places, and confirmed no loot in chests. any tips? im gonna downgrade to the version that i know that works and has loot.

**Comment by tealtoxic** [comment]
UPDATE: I revert back to 1.7.1 and go to new chunks to find dragon place, and check chest, item is appearing fine again. but the already discovered dragon places on 1.8.3 that has chests no item.

**Comment by AlexModGuy** [comment]
dupe #1845
