### ISSUE TITLE
Multiplayer lag, when flying close to player

### ISSUE THREAD

**Issue by Naggorath** [Alex-the-666/Ice_and_Fire#2056]
hey, i am using this mod on a server where me and a couple of mates play from time to time. so i managed to tame a hippogryph. it works fine,  except whenever i am flying close to another player, i get a large amount of lag/stutter. do anybody here know if there is a solution to that problem or if its a bug or whatever?

**Comment by AlexModGuy** [comment]
sghould be fixed in 1.8.4
