### ISSUE TITLE
Misc Structures Not Spawning In The Beneath

### ISSUE THREAD

**Issue by CalaMariGold** [Alex-the-666/Ice_and_Fire#2057]
I did lots of testing and found that the misc structures would not spawn in the Beneath, despite setting spawn rates really high to test and setting the whitelist dimensions for misc structures to 10 and enabled the whitelist.

Worth noting that Dragon dens did spawn in the Beneath, just not misc structures.

Hoping you can look into this, thanks!

**Comment by AlexModGuy** [comment]
what are the "misc structures"? you are refering to?
