### ISSUE TITLE
Breeding Two hippogryphs

### ISSUE THREAD

**Issue by juanretamales** [Alex-the-666/Ice_and_Fire#2060]
bug: i Breeding Two hippogryphs with rabbit stew (appear the hearts), but not get the egg, 
the hippogryphs have gender? how is the diference? 
Version: 1.8.3 for 1.12.2

**Comment by AlexModGuy** [comment]
there is no gender for hippogryphs, the egg spawns from one of them.

**Comment by AlexModGuy** [comment]
not able to replicate in 1.8.4
