### ISSUE TITLE
(Suggestion) Config to set which biomes can spawn dragon roosts/caves 

### ISSUE THREAD

**Issue by inkdear** [Alex-the-666/Ice_and_Fire#2067]
It would be really handy to be able to decide where these spawn within the overworld, also the ability to choose by dragon type (so you could set ice dragons to spawn in certain mountainous biomes in a world with no ice biomes, for example.) It would also make it easier to make packs which have terrain-damaging dragons, but want to give users the ability to choose base locations (other than spawn) which definitely won't have any stage 5s waiting to dig their way out from underground.

**Comment by Normal69** [comment]
I second this (1.12.2 MC) as I've tried to set roosts and caves to spawn in the End dimension - and that biome is neither cold or hot - I think that is what preventing them to generate some interesting bits in the End and company for the lonely End Dragon now. :)

**Comment by inkdear** [comment]
Thought I would add another note that it would be convenient to be able to enable/disable and configure rates for roosts/caves indepently of eachother. Usage examples: making it so above ground dragons are only found in certain biomes, ability to make much rarer above ground dragons without making it harder to find stage 5 dragons underground, etc. 

I see the above ground and below ground dragons as quite 'different' as far as worldgen goes, despite both being a way to spawn a dragon. An above-ground dragon is an immediate hazard to the player and changes the nature of the overworld/exploration, whereas a below-ground dragon is more like a boss fight that you find (and which sometimes emerges from the ground to wreak havoc but y'know)

**Comment by Normal69** [comment]
Ping?

**Comment by smoothuk** [comment]
This would be great.  I too often discover plains villages being assaulted by dragons and it would be nice to be able to just have them generate in biomes that villages do not spawn in, or in high-up places like mountains and extreme hills.
