### ISSUE TITLE
Dragons aren't that aggressive 

### ISSUE THREAD

**Issue by GundunUkan** [Alex-the-666/Ice_and_Fire#207]
I've seen a lot of dragons by now and only once did I see one attack a sheep, but otherwise they let animals and even villagers walk around them without reacting. Wild dragons also don't mind players being around them as long as they don't stick around for too long or hit them, but I don't really consider that an issue, it kinda gives them more of a real life animal personality.

**Comment by EnderiumSmith** [comment]
they have a food bar like the player. you can see that on tamed dragons. but they should be a bit more active in chasing after the target.

**Comment by Alex-the-666** [comment]
Duplicate #216
