### ISSUE TITLE
Dragons are invisible

### ISSUE THREAD

**Issue by RoseaBee** [Alex-the-666/Ice_and_Fire#2070]
I keep getting attacked by invisible dragons. The sounds are there and the entity dot in the minimap that i use appear, but it's my only literal saving grace because the dragons themselves do not appear while I still hear the sounds of flapping wings and hellish roars and literally have my ass set on fire or frozen off from out of nowhere. I feel I should add that the dot just zings back and forth on the map wildly as well.

**Comment by Morpheus1101** [comment]
An issue ive noticed somewhat related is that at certain angles of view, the dragons//serpants are invisible and dont render untill your facing a certain direction...this maybe whats happening here

**Comment by RoseaBee** [comment]
That's not even remotely what it is. The dragon does not render AT ALL. Above, below, left, right, in front, behind, strafing in any direction, the dragon isn't there. The entity dot on my mini map shows it slingshots back and forth at ridiculous speeds and I still get set on fire or frozen by an enemy that I cannot see or get locked on to in order to defeat and end up getting killed and losing all of my stuff.

I can see the serpents and all other mobs just fine. This problem is literally solely with the dragons.
