### ISSUE TITLE
Error: Hippogryph moved wrongly!

### ISSUE THREAD

**Issue by PenumbraStar** [Alex-the-666/Ice_and_Fire#2071]
Lots of console spam whenever someone tries to ride a Hippogryph. Allow flight is enabled. No crash logs that I can post. Any suggestions on a fix or any chance of looking into the issue?

**Comment by MastaNub** [comment]
riding a hippogryph or a dragon will spam the console and kick for for flying.

**Comment by juanlost** [comment]
I solved today that issue using the command "gamerule disableElytraMovementCheck" in server console and changing "allow-flight=true" in server.properties. But still having an issue, when you get an Hippogryph for like 1 min, it just dissapear, in server console says "Hippogryph moved wrongly".

**Comment by AlexModGuy** [comment]
fixed
