### ISSUE TITLE
Server Crash from interacting with dragon

### ISSUE THREAD

**Issue by Air1N** [Alex-the-666/Ice_and_Fire#2072]
[Crash Log Link](https://pastebin.com/euxjjyLw)

Didn't happen until about halfway through killing a snow biome dragon. Now I can't even join my server or the thing crashes

**Comment by BoksmanTheMighty** [comment]
https://paste.dimdev.org/nibusofeje.mccrash

I seem to be having a similar problem.

**Comment by AlexModGuy** [comment]
fixed
