### ISSUE TITLE
Broken flying sound effect

### ISSUE THREAD

**Issue by GundunUkan** [Alex-the-666/Ice_and_Fire#208]
I'm aware there's already an issue for the wing flapping sound keep playing after a dragon lands, but I noticed a dragon starting to make the same sound before it even got in the air for the first time.

**Comment by DominoFirey** [comment]
I can approve of this, an Ice Dragon i met after it finished flying and it was walking on land it was still playing the Wing flaps sounds.

**Comment by Alex-the-666** [comment]
Duplicate #203
