### ISSUE TITLE
My Friend's dragon egg disappeared on server

### ISSUE THREAD

**Issue by SteveAdture** [Alex-the-666/Ice_and_Fire#2082]
If I open a server or LAN
Admin(me) can only hatch the dragon egg.
If another player try to hatch dragon egg after that not so long the egg will became to invisible (but Admin can only see that egg) together with egg crack sound

(In other player view)It looks like the egg already hatch but no dragon appears

(In Admin view)The egg still on fire/water.

**Comment by doxxerx** [comment]
someone could have stolen it i mean they are really hard to get
