### ISSUE TITLE
Dragon Armor Rendering

### ISSUE THREAD

**Issue by AwesomeAlec1** [Alex-the-666/Ice_and_Fire#2083]
Hi. I am having a problem getting my dragon's armor to display correctly. 
When I put it on my dragon for the first time, everything worked perfectly, displaying all the pieces. However, when I took it off to check how much its armor changed and then reequipped it, some of the pieces didn't re-render. Now my fully-armored dragon doesn't appear to have any neck or tail armor. Which pieces choose to reappear and which ones choose to disappear seems to be random when I take off and put back on different pieces. While this issue isn't crash-inducing or anything, I would like it cleaned up, as seeing my dragon with only half a set of armor despite being fully equipped is rather annyoing for my OCD.

Please note: The armor is only de-RENDERING. It is not actually disappearing, and my dragon, despite LOOKING half-armored, is actually getting the full armor increase still. It's just a really annoying visual bug.

**Comment by AwesomeAlec1** [comment]
Also, I've since gotten the body and tail armor to show consistently, but the helmet only shows when my dragon's eyes are open, but then the helmet disappears and the neck armor reappears when she blinks. Then when she opens her eyes again, the neck armor disappears and the helmet comes back again. Relogging in to the server that my dragon is on doesn't fix the issue, also.

**Comment by juanlost** [comment]
Same problem here!

**Comment by AlexModGuy** [comment]
fixed in 1.8.4
