### ISSUE TITLE
Dragon disappears while fighting

### ISSUE THREAD

**Issue by GapHusky** [Alex-the-666/Ice_and_Fire#2084]

**Comment by GapHusky** [comment]
Only happens when fighting hand to hand doesn't disappear when fighting with a bow.

**Comment by ghost** [comment]
Same thing happened to me. I am scared that it will reappear.

**Comment by DenilsonNM** [comment]
It happens to me when I fight with an ice sword

**Comment by Dark0neW0lf** [comment]
Same thing happens to me but it happens when they are affected with the burning or freezing effects of the dragon bone or steel weapons

**Comment by AlexModGuy** [comment]
should be fixed in 1.8.4
