### ISSUE TITLE
Dragon body breaks apart when riding and player is upside down while riding

### ISSUE THREAD

**Issue by Alphakip** [Alex-the-666/Ice_and_Fire#2088]
![javaw_lvL96DlUv2](https://user-images.githubusercontent.com/38961891/71202231-01737900-2259-11ea-8727-fc04d946bdd1.png)

**Comment by DangerNoodle9000** [comment]
activate "DRAGON GL ERROR FIX" in the ice and fire config.
that fixed it for me

**Comment by AlexModGuy** [comment]
^
