### ISSUE TITLE
Dragon teleports underground while riding

### ISSUE THREAD

**Issue by Thrakoss** [Alex-the-666/Ice_and_Fire#2089]
Dragon teleported to y = -100 while riding killing me and it

**Comment by BluRael** [comment]
A friend of mine just experienced this. I've attached a snippet of the log which shows the errors occuring plus the death point: x=744, y=-483, z=-70
[Alucard Errors.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/4000994/Alucard.Errors.txt)

**Comment by AlexModGuy** [comment]
fixed in 1.8.4
