### ISSUE TITLE
Bugs Everywhere and no Dev Response

### ISSUE THREAD

**Issue by Boolyman** [Alex-the-666/Ice_and_Fire#209]
Mod just came out, but feels like its already been abandoned.  There are no responses to recent tickets, no udpates to the mod, no commit changes.

-Dragons sound is still broken, can be heard at same volume for half a dozen chunks.
-Block breaking is still malfunctioning.
-Dragons are causing tons of lag as their poorly animated flight patterns send them dangling halfway out of a wall.  
-Dragon hit box and collision is a nightmare... half the time i see a broken textured wing tip clipping strait through the side of a mountain, and that tells me there is a dragon on the other side of the wall.  Most of the time i can just sit on that side of the wall and beat the tip of the wing until the dragon somewhere inside dies.  Oddly, i dont do this for the loot... I do it so that I can have a little peace of mind from the nonstop louder-than-anything-else flapping noise the permeates through everything within a 300 block radius... despite the dragon not actually flying.  Go figure.

**Comment by PlatinumFox** [comment]
I can assure you that it is not dead. The devs are in college and I can tell you from a first hand experience that things can get rough. Also finals are coming up soon and teachers usually start dishing out more work around this time (at least try do for me). The mod is not dead it literally just came out lol. The devs are just busy.

**Comment by Alex-the-666** [comment]
commit 3 days ago. Fuck off.
