### ISSUE TITLE
Dragon Dissapeared

### ISSUE THREAD

**Issue by TBRedwolf** [Alex-the-666/Ice_and_Fire#2091]
I'm playing on version 1.7.1 of this mod and I was moving my stage 1 dragon to a new house. I had her on my shoulder and only had to walk 300-400 blocks before I put her down. As I did so she flickered out of existence and I haven't been able to find her since. I re-logged just in case it was a visual glitch but she wasn't there, I retraced my steps to my house and she wasn't there either. Anyone   had and/or fixed this problem?

**Comment by AlexModGuy** [comment]
update your mod.
