### ISSUE TITLE
crash when using Myramex Staff to attack dragons

### ISSUE THREAD

**Issue by Mizhok** [Alex-the-666/Ice_and_Fire#2095]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.21.3.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.9-1.12.2.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  Quark Plugin (Quark-r1.6-177.jar)
  iceandfire (iceandfire-1.8.3.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  CharmLoadingPlugin (Charm-1.12.2-1.3.6.jar)
  RandomPatches (randompatches-1.12.2-1.19.1.1.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 12/21/19 8:35 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.github.alexthe666.iceandfire.entity.EntityMyrmexSwarmer.func_184191_r(EntityMyrmexSwarmer.java:104)
	at net.minecraft.entity.ai.EntityAITarget.func_179445_a(SourceFile:120)
	at net.minecraft.entity.ai.EntityAITarget.func_75296_a(SourceFile:148)
	at com.github.alexthe666.iceandfire.entity.ai.MyrmexAISummonerHurtTarget.func_75250_a(MyrmexAISummonerHurtTarget.java:26)
	at com.performant.coremod.entity.ai.goals.CustomPriotizedSlowedGoal.shouldExecute(CustomPriotizedSlowedGoal.java:59)
	at com.performant.coremod.entity.ai.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:178)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:760)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at com.github.alexthe666.iceandfire.entity.EntityMyrmexRoyal.func_70636_d(EntityMyrmexRoyal.java:134)
	at com.github.alexthe666.iceandfire.entity.EntityMyrmexSwarmer.func_70636_d(EntityMyrmexSwarmer.java:155)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at com.github.alexthe666.iceandfire.entity.EntityMyrmexBase.func_70071_h_(EntityMyrmexBase.java:239)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.github.alexthe666.iceandfire.entity.EntityMyrmexSwarmer.func_184191_r(EntityMyrmexSwarmer.java:104)
	at net.minecraft.entity.ai.EntityAITarget.func_179445_a(SourceFile:120)
	at net.minecraft.entity.ai.EntityAITarget.func_75296_a(SourceFile:148)
	at com.github.alexthe666.iceandfire.entity.ai.MyrmexAISummonerHurtTarget.func_75250_a(MyrmexAISummonerHurtTarget.java:26)
	at com.performant.coremod.entity.ai.goals.CustomPriotizedSlowedGoal.shouldExecute(CustomPriotizedSlowedGoal.java:59)
	at com.performant.coremod.entity.ai.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:178)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:760)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at com.github.alexthe666.iceandfire.entity.EntityMyrmexRoyal.func_70636_d(EntityMyrmexRoyal.java:134)
	at com.github.alexthe666.iceandfire.entity.EntityMyrmexSwarmer.func_70636_d(EntityMyrmexSwarmer.java:155)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at com.github.alexthe666.iceandfire.entity.EntityMyrmexBase.func_70071_h_(EntityMyrmexBase.java:239)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: iceandfire:myrmex_swarmer (com.github.alexthe666.iceandfire.entity.EntityMyrmexSwarmer)
	Entity ID: 31226
	Entity Name: Myrmex Swarmer
	Entity's Exact location: 263.40, 84.23, 304.85
	Entity's Block location: World: (263,84,304), Chunk: (at 7,5,0 in 16,19; contains blocks 256,0,304 to 271,255,319), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -0.08, -0.13, 0.22
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['soulfurdioxide'/22242, l='New World', x=265.91, y=83.36, z=307.35]]
	Chunk stats: ServerChunkCache: 955 Drop: 0
	Level seed: 3185145301832469833
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {"diamondSize":8,"lapisCenterHeight":16,"lavaLakeChance":80,"redstoneMaxHeight":16,"diamondMaxHeight":16,"coalMaxHeight":128,"coalMinHeight":0,"seaLevel":63,"graniteCount":10,"riverSize":4,"gravelMinHeight":0,"graniteSize":33,"redstoneSize":8,"fixedBiome":-1,"waterLakeChance":4,"dioriteMinHeight":0,"andesiteCount":10,"graniteMaxHeight":80,"redstoneMinHeight":0,"lapisSize":7,"dirtCount":10,"ironMinHeight":0,"dioriteMaxHeight":80,"coalCount":20,"gravelCount":8,"coalSize":17,"gravelSize":33,"ironMaxHeight":64,"lapisSpread":16,"dioriteCount":10,"andesiteSize":33,"biomeSize":4,"graniteMinHeight":0,"goldCount":2,"diamondCount":1,"dirtSize":33,"gravelMaxHeight":256,"goldSize":9,"ironCount":20,"diamondMinHeight":0,"ironSize":9,"redstoneCount":8,"andesiteMinHeight":0,"dioriteSize":33,"goldMaxHeight":32,"dungeonChance":8,"andesiteMaxHeight":80,"dirtMinHeight":0,"lapisCount":1,"goldMinHeight":0,"dirtMaxHeight":256,"lowerLimitScale":512.0,"biomeDepthOffset":0.0,"upperLimitScale":512.0,"heightScale":684.412,"biomeScaleWeight":1.0,"biomeDepthWeight":1.0,"mainNoiseScaleZ":80.0,"mainNoiseScaleY":160.0,"depthNoiseScaleX":200.0,"mainNoiseScaleX":80.0,"baseSize":8.5,"depthNoiseScaleZ":200.0,"stretchY":12.0,"depthNoiseScaleExponent":0.5,"biomeScaleOffset":0.0,"coordinateScale":684.412,"useStrongholds":true,"useMineShafts":true,"useTemples":true,"useLavaOceans":false,"useCaves":true,"useWaterLakes":true,"useLavaLakes":true,"useMonuments":true,"useRavines":true,"useDungeons":true,"useVillages":true}
	Level spawn location: World: (-152,64,256), Chunk: (at 8,4,0 in -10,16; contains blocks -160,0,256 to -145,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 5949 game time, 5949 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 86860 (now: false), thunder time: 52147 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 412848888 bytes (393 MB) / 2046296064 bytes (1951 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 105 mods loaded, 105 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version          | Source                                           | Signature                                |
	|:------ |:-------------------- |:---------------- |:------------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2           | minecraft.jar                                    | None                                     |
	| LCHIJA | mcp                  | 9.42             | minecraft.jar                                    | None                                     |
	| LCHIJA | FML                  | 8.0.99.99        | forge-1.12.2-14.23.5.2847.jar                    | None                                     |
	| LCHIJA | forge                | 14.23.5.2847     | forge-1.12.2-14.23.5.2847.jar                    | None                                     |
	| LCHIJA | foamfixcore          | 7.7.4            | minecraft.jar                                    | None                                     |
	| LCHIJA | opencomputers|core   | 1.7.5.192        | minecraft.jar                                    | None                                     |
	| LCHIJA | randompatches        | 1.12.2-1.19.1.1  | randompatches-1.12.2-1.19.1.1.jar                | None                                     |
	| LCHIJA | engineersdecor       | 1.0.16           | engineersdecor-1.12.2-1.0.16.jar                 | ed58ed655893ced6280650866985abcae2bf7559 |
	| LCHIJA | jei                  | 4.15.0.291       | jei_1.12.2-4.15.0.291.jar                        | None                                     |
	| LCHIJA | immersiveengineering | 0.12-92          | ImmersiveEngineering-0.12-92.jar                 | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA | alternatingflux      | 0.12.2-2         | alternatingflux-0.12.2-2.jar                     | None                                     |
	| LCHIJA | quark                | r1.6-177         | Quark-r1.6-177.jar                               | None                                     |
	| LCHIJA | autoreglib           | 1.3-32           | AutoRegLib-1.3-32.jar                            | None                                     |
	| LCHIJA | bannerelytra         | 1.0              | bannerelytra-1.0.jar                             | None                                     |
	| LCHIJA | baubles              | 1.5.2            | Baubles-1.12-1.5.2.jar                           | None                                     |
	| LCHIJA | betteradvancements   | 0.1.0.77         | BetterAdvancements-1.12.2-0.1.0.77.jar           | None                                     |
	| LCHIJA | bettercombatmod      | 1.5.6            | BetterCombat-1.12.2-1.5.6.jar                    | None                                     |
	| LCHIJA | betterinvisibility   | 1.0              | betterinvisibility-1.12-1.0.jar                  | None                                     |
	| LCHIJA | betternether         | 0.1.8.5          | betternether-0.1.8.5.jar                         | None                                     |
	| LCHIJA | patchouli            | 1.0-20           | Patchouli-1.0-20.jar                             | None                                     |
	| LCHIJA | bewitchment          | 0.21.3           | bewitchment-1.12.2-0.0.21.3.jar                  | None                                     |
	| LCHIJA | carryon              | 1.12.3           | CarryOn MC1.12.2 v1.12.3.jar                     | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCHIJA | cd4017be_lib         | 6.4.14           | CD4017BE_lib-1.12.2-6.4.14.1.jar                 | None                                     |
	| LCHIJA | charm                | 1.12.2-1.3.6     | Charm-1.12.2-1.3.6.jar                           | None                                     |
	| LCHIJA | comforts             | 1.4.1.2          | comforts-1.12.2-1.4.1.2.jar                      | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | controlling          | 3.0.7            | Controlling-3.0.7.jar                            | None                                     |
	| LCHIJA | configmod            | v1.0             | coroutil-1.12.1-1.2.33.jar                       | None                                     |
	| LCHIJA | extendedrenderer     | v1.0             | coroutil-1.12.1-1.2.33.jar                       | None                                     |
	| LCHIJA | coroutil             | 1.12.1-1.2.33    | coroutil-1.12.1-1.2.33.jar                       | None                                     |
	| LCHIJA | craftablehorsearmour | 1.3              | CraftableHorseArmour-1.3.0-1.12.jar              | None                                     |
	| LCHIJA | craftingtweaks       | 8.1.9            | CraftingTweaks_1.12.2-8.1.9.jar                  | None                                     |
	| LCHIJA | crafttweaker         | 4.1.20           | CraftTweaker2-1.12-4.1.20.jar                    | None                                     |
	| LCHIJA | ctgui                | 1.0.0            | CraftTweaker2-1.12-4.1.20.jar                    | None                                     |
	| LCHIJA | crafttweakerjei      | 2.0.3            | CraftTweaker2-1.12-4.1.20.jar                    | None                                     |
	| LCHIJA | diethopper           | 1.1              | diethopper-1.1.jar                               | None                                     |
	| LCHIJA | lootablebodies       | 2.4.0            | DrCyanosLootableBodies_1.12-2.4.0.jar            | None                                     |
	| LCHIJA | easyelytrato         | 1.1              | easyelytrato_1.12-1.1.jar                        | None                                     |
	| LCHIJA | eleccore             | 1.9.452          | ElecCore-1.12.2-1.9.452.jar                      | None                                     |
	| LCHIJA | csb_ench_table       | 1.1.3            | EnchantingTable-1.12-1.1.3.jar                   | None                                     |
	| LCHIJA | engineersdoors       | 0.8.0            | engineers_doors-1.12.2-0.8.0.jar                 | None                                     |
	| LCHIJA | fairylights          | 2.1.9            | fairylights-2.1.9-1.12.2.jar                     | None                                     |
	| LCHIJA | fastbench            | 1.7.3            | FastWorkbench-1.12.2-1.7.3.jar                   | None                                     |
	| LCHIJA | fivefeetsmall        | 1.0.1            | FiveFeetSmall-v1.0.1-1.12.2.jar                  | 12d137bcc36051a1c2c8ea7211cfc1da1c6e9dea |
	| LCHIJA | foamfix              | 0.10.9-1.12.2    | foamfix-0.10.9-1.12.2.jar                        | None                                     |
	| LCHIJA | forgelin             | 1.8.4            | Forgelin-1.8.4.jar                               | None                                     |
	| LCHIJA | cfm                  | 6.3.1            | furniture-6.3.1-1.12.2.jar                       | None                                     |
	| LCHIJA | waila                | 1.8.26           | Hwyla-1.8.26-B41_1.12.2.jar                      | None                                     |
	| LCHIJA | llibrary             | 1.7.19           | llibrary-1.7.19-1.12.2.jar                       | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire           | 1.8.3            | iceandfire-1.8.3.jar                             | None                                     |
	| LCHIJA | immersivehempcraft   | 1.12-0.0.7.1     | Immersive HempCraft-1.12-0.0.7.1.jar             | None                                     |
	| LCHIJA | immersivepetroleum   | 1.1.9            | immersivepetroleum-1.12.2-1.1.9.jar              | None                                     |
	| LCHIJA | immersiveposts       | 0.1.4            | ImmersivePosts-0.1.4.jar                         | 0ba8738eadcf158e7fe1452255a73a022fb15feb |
	| LCHIJA | jaff                 | 1.7_for_1.12     | JustAFewFish-1.7_for_1.12.jar                    | None                                     |
	| LCHIJA | jeresources          | 0.9.2.60         | JustEnoughResources-1.12.2-0.9.2.60.jar          | None                                     |
	| LCHIJA | matchlockweapons     | 0.8              | Matchlock Guns Mod-1.12.2-7a.jar                 | None                                     |
	| LCHIJA | mcjtylib_ng          | 3.5.4            | mcjtylib-1.12-3.5.4.jar                          | None                                     |
	| LCHIJA | mekanism             | 1.12.2-9.8.3.390 | Mekanism-1.12.2-9.8.3.390.jar                    | None                                     |
	| LCHIJA | mekanismgenerators   | 1.12.2-9.8.3.390 | MekanismGenerators-1.12.2-9.8.3.390.jar          | None                                     |
	| LCHIJA | mekores              | 2.0.12           | mekores-2.0.12.jar                               | None                                     |
	| LCHIJA | tbone                | v1.6.8+mc1.12.2  | TBone-v1.6.8+mc1.12.2.jar                        | None                                     |
	| LCHIJA | metalchests          | v6.1.0+mc1.12.2  | MetalChests-v6.1.0+mc1.12.2.jar                  | None                                     |
	| LCHIJA | metaltransport       | v2.6.9+mc1.12.2  | MetalTransport-v2.6.9+mc1.12.2.jar               | None                                     |
	| LCHIJA | moarboats            | 4.1.2.1          | moarboats-1.12.2-4.1.2.1.jar                     | None                                     |
	| LCHIJA | mousetweaks          | 2.10             | MouseTweaks-2.10-mc1.12.2.jar                    | None                                     |
	| LCHIJA | movinglightsource    | 1.0.15           | movinglightsource-1.12.2-1.0.15.jar              | None                                     |
	| LCHIJA | mysticalmechanics    | 0.11             | Mystical Mechanics-0.11.jar                      | None                                     |
	| LCHIJA | mystgears            | 1.0.5            | mystgears-1.0.5.jar                              | None                                     |
	| LCHIJA | nametagstweaks       | 1.12             | NameTagsTweaks-1.12.jar                          | None                                     |
	| LCHIJA | norecipebook         | 1.2.1            | noRecipeBook_v1.2.2formc1.12.2.jar               | None                                     |
	| LCHIJA | noworldgen5you       | 1.0.6            | NoWorldgen5You-1.12.2-1.0.6.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | opencomputers        | 1.7.5.192        | OpenComputers-MC1.12.2-1.7.5.192.jar             | None                                     |
	| LCHIJA | omlib                | 3.1.3-246        | omlib-1.12.2-3.1.3-246.jar                       | None                                     |
	| LCHIJA | performant           | 1.12.2-1.4       | performant-1.12.2-1.4.jar                        | None                                     |
	| LCHIJA | placebo              | 1.6.0            | Placebo-1.12.2-1.6.0.jar                         | None                                     |
	| LCHIJA | plated               | 0.1.0            | Plated-0.1.0.jar                                 | None                                     |
	| LCHIJA | potioncore           | 1.8_for_1.12.2   | PotionCore-1.8_for_1.12.2.jar                    | None                                     |
	| LCHIJA | qualitytools         | 1.0.7_for_1.12.2 | QualityTools-1.0.7_for_1.12.2.jar                | None                                     |
	| LCHIJA | quarkoddities        | 1                | QuarkOddities-1.12.2.jar                         | None                                     |
	| LCHIJA | reborncore           | 3.16.4.478       | RebornCore-1.12.2-3.16.4.478-universal.jar       | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJA | rs_ctr               | 0.2.2            | RedstoneControl-1.12.2-0.2.3.jar                 | None                                     |
	| LCHIJA | additionalstructures | 2.3.1            | Rex's-Additional-Structures-1.12.x-(v.2.3.1).jar | None                                     |
	| LCHIJA | rsgauges             | 1.1.9            | rsgauges-1.12.2-1.1.9.jar                        | ed58ed655893ced6280650866985abcae2bf7559 |
	| LCHIJA | spartanweaponry      | beta 1.3.8       | SpartanWeaponry-1.12.2-beta-1.3.8.jar            | None                                     |
	| LCHIJA | spartanfire          | 0.07             | spartanfire-0.07.jar                             | None                                     |
	| LCHIJA | spartanshields       | 1.5.4            | SpartanShields-1.12.2-1.5.4.jar                  | None                                     |
	| LCHIJA | stevescarts          | 2.4.32.137       | StevesCarts-1.12.2-2.4.32.137.jar                | None                                     |
	| LCHIJA | stg                  | 1.12.2-1.2.3     | stg-1.12.2-1.2.3.jar                             | None                                     |
	| LCHIJA | tipthescales         | 1.0.4            | TipTheScales-1.12.2-1.0.4.jar                    | None                                     |
	| LCHIJA | toastcontrol         | 1.8.1            | Toast Control-1.12.2-1.8.1.jar                   | None                                     |
	| LCHIJA | wearablebackpacks    | 3.1.4            | WearableBackpacks-1.12.2-3.1.4.jar               | None                                     |
	| LCHIJA | wolfarmor            | 2.2.3.6          | wolfarmor-1.12.2-2.2.3.1798-universal.jar        | None                                     |
	| LCHIJA | woolplates           | v1.2             | woolplates-1.12.x-v1.2.jar                       | None                                     |
	| LCHIJA | xaerominimap         | 1.19.3           | Xaeros_Minimap_FP1.19.3_Forge_1.12.jar           | None                                     |
	| LCHIJA | xaeroworldmap        | 1.5.2            | XaerosWorldMap_1.5.2_Forge_1.12.jar              | None                                     |
	| LCHIJA | yoyos                | 1.12.2-1.3.3.25  | yoyos_1.12.2-1.3.3.25.jar                        | None                                     |
	| LCHIJA | rendertoolkit        | 1.3.7            | Commons0815-1.12.2-1.3.7.jar                     | None                                     |
	| LCHIJA | guitoolkit           | 1.3.7            | Commons0815-1.12.2-1.3.7.jar                     | None                                     |
	| LCHIJA | commons0815          | 1.3.7            | Commons0815-1.12.2-1.3.7.jar                     | None                                     |
	| LCHIJA | kiwi                 | 0.5.3.32         | Kiwi-1.12.2-0.5.3.32.jar                         | None                                     |
	| LCHIJA | cuisine              | 0.5.16-build907  | Cuisine-0.5.16-build907.jar                      | None                                     |
	| LCHIJA | openglasses          | @VERSION@-50     | OpenGlasses-MC1.12.2-2.2-50.jar                  | None                                     |
	| LCHIJA | phosphor-lighting    | 1.12.2-0.2.6     | phosphor-1.12.2-0.2.6+build50-universal.jar      | f0387d288626cc2d937daa504e74af570c52a2f1 |
	| LCHIJA | snowrealmagic        | 0.3.3            | SnowRealMagic-0.3.3.jar                          | None                                     |
	| LCHIJA | eleccoreloader       | 1.9.452          | ElecCore-1.12.2-1.9.452.jar                      | None                                     |
	| LCHIJA | wrapup               | 1.12-1.1.3       | WrapUp-1.12-1.1.3.jar                            | None                                     |

	Loaded coremods (and transformers): 
BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.21.3.jar)
  
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.9-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  li.cil.oc.common.asm.ClassTransformer
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
iceandfire (iceandfire-1.8.3.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CharmLoadingPlugin (Charm-1.12.2-1.3.6.jar)
  svenhjol.charm.base.CharmClassTransformer
RandomPatches (randompatches-1.12.2-1.19.1.1.jar)
  com.therandomlabs.randompatches.core.RPTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.16.4.478
		Runtime Debofucsation 1
		RenderEngine: 0
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['soulfurdioxide'/22242, l='New World', x=265.91, y=83.36, z=307.35]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by AlexModGuy** [comment]
at com.performant.coremod.entity.ai.goals.CustomPriotizedSlowedGoal.shouldExecute(CustomPriotizedSlowedGoal.java:59)

issue is with mod called "preformant"
