### ISSUE TITLE
[1.12.2; Bug] IndexOutOfBounds

### ISSUE THREAD

**Issue by andr9528** [Alex-the-666/Ice_and_Fire#2096]
Tried to shift click in more manuscripts to the lectern, while there where already one in there and ended up getting a IndexOutOfBounds exception. 

Pretty self explanatory, id say.

https://pastebin.com/ARuUqGsb

**Comment by andr9528** [comment]
trying to join the world after that exception results in the world saving and giving this message
![image](https://user-images.githubusercontent.com/21788044/71379242-e7c09180-25ca-11ea-980c-e800e969feb7.png)

time to find world edit and remove the lectern...

**Comment by andr9528** [comment]
After removing the block with mcedit, the game was fine again. Something bad must have happened behind the scenes.

**Comment by AlexModGuy** [comment]
fixed
