### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by ArrisanAmoria** [Alex-the-666/Ice_and_Fire#2097]
While walking around to find dragons (and not finding one because of the number of mods) I think it would be nice to add a menu in which we can configure the spawn of the mod's mobs. For example, define the minimum space between dragon nests, or between mermaid rocks. A bit of a menu like in the Millennium mod for those who know.

**Comment by AlexModGuy** [comment]
its the config, you can reach it under Mod Options
