### ISSUE TITLE
Game crash when dragon near

### ISSUE THREAD

**Issue by skyeblueocean** [Alex-the-666/Ice_and_Fire#2099]
Every time I’m near a dragon or try to interact with one, my entire game crashes. It’s only been since I updated to the version with dragon steel.

**Comment by srwaggon** [comment]
@skyeblueocean Can you please share your crash report?

If it is anything like the issue reported [here](https://github.com/xcube16/ISeeDragons/issues/4) with the [ISeeDragons](https://github.com/xcube16/ISeeDragons) mod, then simply disabling the ISeeDragons mod worked for me, while the author fixes the issue.

**Comment by skyeblueocean** [comment]
I’ve someone fixed the issue, I think my computer was just having a rough day 😂

**Comment by srwaggon** [comment]
@skyeblueocean, for posterity, what was the fix?

**Comment by skyeblueocean** [comment]
I disabled the ISeeDragons mod
