### ISSUE TITLE
Dragon Lairs On The Surface [Simple Dimensions?)

### ISSUE THREAD

**Issue by MokahTGS** [Alex-the-666/Ice_and_Fire#210]
I'm using simple dimensions to generate some overworld like dimensions and have noticed that the fire dragons spawn in lairs, but on the surface.  Not sure if this is normal or if they were supposed to be underground only.

I'm also not sure if this is because its a generated dimension and not the actual overworld.

https://www.dropbox.com/s/6zy548v31tucxqo/2017-04-16_15.33.15.png?dl=0

**Comment by Pedecto** [comment]
That's a roost. So yeah, that's normal. The underground lairs have ore embedded in the stone, and a lot more treasure. 
That roost is raised up a bit, so it does look a bit odd. They're normally aligned with the blocks around it, but that's more of a weird worldgen hiccup than a bug.

**Comment by MokahTGS** [comment]
OK, good to know...just didn't know what was normal and not.
