### ISSUE TITLE
Dragons constantly but slowly float up when being flown in servers.

### ISSUE THREAD

**Issue by Zangunaz** [Alex-the-666/Ice_and_Fire#2107]
As said in the title, playing on a modded server on the latest version of Ice and Fire. My 68 day old ice dragon slowly floats upwards while I'm riding her, even when staying still. I've tested it on younger dragons as well, and they all have an almost imperceptible upwards drift.

![image](https://user-images.githubusercontent.com/49125591/71774569-86d87800-2f3f-11ea-8e04-1c7e77584375.png)

**Comment by AlexModGuy** [comment]
fixed
