### ISSUE TITLE
Baby dragons on shoulder disappearing after logging off 

### ISSUE THREAD

**Issue by Spaz123** [Alex-the-666/Ice_and_Fire#211]
In my experience, it only happens to dragons who are on your shoulder. I've tested this in many different worlds, both new and old, and they have disappeared without fail.  As far as I know, there's no way to get them back. Like I said, it only happens to dragons on your shoulder. If they are on the ground or being flown, they're fine.

**Comment by PlatinumFox** [comment]
This was reported a while ago

**Comment by PlatinumFox** [comment]
#168
