### ISSUE TITLE
When installing a dragon skull, a client crashes

### ISSUE THREAD

**Issue by Kashwar** [Alex-the-666/Ice_and_Fire#2110]
On the version for 1.12.2, when interacting with a dragon skull, a client crashes from the creative (with a higher probability), as well as with the skulls of the killed dragons (1,2,3,4,5). We thought that the business of the NBT tags, but it is not. The client flies even from ordinary skulls - not from creativity. Moreover, the client crashes from the one who is closest to the skull. Other players on the server can play further.

**Comment by AlexModGuy** [comment]
fixed
