### ISSUE TITLE
Dragons Despawning Issue

### ISSUE THREAD

**Issue by prwoyt** [Alex-the-666/Ice_and_Fire#2121]
I'm using a modpack pretty similar to RLCraft, most of the mods from RLCraft are in there with only a few added outside mods, such as Mowzie's Mobs. Dragons weren't appearing in roosts, so when I went to check in creative if I could spawn dragons, I can, but as soon as larger dragons attack, they disappear. I should also mention that I was having tick errors while I was playing. I then went into my forge config file and made it so the game removes any entities cause errors. Any fixes?

java.lang.IncompatibleClassChangeError: Class net.minecraft.util.math.BlockPos does not implement the requested interface net.minecraft.block.state.IBlockStatejava.lang.IncompatibleClassChangeError: Class net.minecraft.util.math.BlockPos does not implement the requested interface net.minecraft.block.state.IBlockState at io.github.xcube16.iseedragons.ISeeDragons.dragonBreakBlockHook(ISeeDragons.java:381) at com.github.alexthe666.iceandfire.entity.EntityDragonBase.breakBlock(EntityDragonBase.java:1613) at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70619_bc(EntityDragonBase.java:336) at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:769) at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359) at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178) at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43) at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70636_d(EntityDragonBase.java:1243) at com.github.alexthe666.iceandfire.entity.EntityFireDragon.func_70636_d(EntityFireDragon.java:219) at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179) at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70071_h_(EntityDragonBase.java:1793) at net.minecraft.world.World.func_72866_a(World.java:1996) at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) at net.minecraft.world.World.func_72870_g(World.java:1958) at net.minecraft.world.World.func_72939_s(World.java:1762) at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) at java.lang.Thread.run(Thread.java:745)

-- Entity being ticked ---- Entity being ticked --Details: Entity Type: iceandfire:icedragon (com.github.alexthe666.iceandfire.entity.EntityIceDragon) Entity ID: 2506 Entity Name: Ice Dragon Entity's Exact location: -50.81, 63.96, 230.20 Entity's Block location: World: (-51,63,230), Chunk: (at 13,3,6 in -4,14; contains blocks -64,0,224 to -49,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511) Entity's Momentum: -0.26, -0.50, 0.00 Entity's Passengers: [] Entity's Vehicle: ~~ERROR~~ NullPointerException: null

This is what I got when I changed those remove entity values back to false. This also occurs for fire dragons.

I also tried using an older version, and the game responds by crashing on launch.

EDIT: I believe I fixed it. It may have been caused by ISeeDragons.

**Comment by Deadlyperiapsis** [comment]
I am having this exact same issue with RLCraft. How did you fix the issue caused by ISeeDragons?

**Comment by prwoyt** [comment]
I actually just uninstalled it.
