### ISSUE TITLE
Difficult to see while riding the larger dragons

### ISSUE THREAD

**Issue by Kaijudile** [Alex-the-666/Ice_and_Fire#2123]
It isn't impossible to see, however when actively flying it constantly obscures your vision which can make navigating relatively difficult. Using third person view is a little better, but just barely.

![2020-01-16_15 07 20](https://user-images.githubusercontent.com/59978391/72559266-6a5b0a80-3872-11ea-8f6d-06c12318394e.png)
![2020-01-16_15 07 29](https://user-images.githubusercontent.com/59978391/72559280-73e47280-3872-11ea-8f4b-cee53722edbe.png)
![2020-01-16_15 07 35](https://user-images.githubusercontent.com/59978391/72559356-9ecec680-3872-11ea-847d-5b221d703d92.png)
![2020-01-16_15 08 23](https://user-images.githubusercontent.com/59978391/72559292-7ba41700-3872-11ea-84f0-f08aaccfc491.png)

**Comment by ghost** [comment]
Just press f7 to change the camera

**Comment by Kaijudile** [comment]
you mean f5 right? because the bottom screenshot is using the third person view

**Comment by ghost** [comment]
F7 change the camera when riding dragons like that
![2020-01-19_15 38 16](https://user-images.githubusercontent.com/35016063/72686278-be175f00-3ad1-11ea-88cd-74b7ba88bb32.png)

**Comment by AlexModGuy** [comment]
partically fixed in 1.8.4
