### ISSUE TITLE
Fps drop and game is not playable when a dragon comes to the surface

### ISSUE THREAD

**Issue by Shadowpudding** [Alex-the-666/Ice_and_Fire#2124]
all of the blocks a dragon brakes drop and cause major performence issues. i think this could be fixed if the blocks don't drop anymore or the dragons stop trying to get out of their nests. it's only a problem with stage 4 and 5 dragons in the moment. the game doesn't crash in my case.

**Comment by AlexModGuy** [comment]
Fixed in 1.8.4
