### ISSUE TITLE
Dragon roosts can spawn on villages

### ISSUE THREAD

**Issue by smoothuk** [Alex-the-666/Ice_and_Fire#2125]
Not sure if this is intended behaviour, but dragon roosts can spawn a little too close to villages.. so close that they can generate right on top of the village, as seen in the image I linked below.

[https://imgur.com/a/jQOxk8t](https://imgur.com/a/jQOxk8t)

**Comment by mgaray99** [comment]
This is always hilarious when I see it in game, as if it was a village full of nitwits who decided to live next to a dragon.
