### ISSUE TITLE
Dragons Being Reset

### ISSUE THREAD

**Issue by Imiru-0** [Alex-the-666/Ice_and_Fire#2127]
I recently had an incident where I was playing on a public server and my dragons when put in dragon horns would be reset. They changed gender, color, became stage 1, and type and after I loaded a backup of my player data it happened again. I cant think of any reason for it happening other than the dragon horns. I was playing with the RAD modpack(Rougelike Adventures and Dungeons).

**Comment by AlexModGuy** [comment]
sounds like someone cleared the NBT data tag on the dragon horn. don't do that.
