### ISSUE TITLE
Amphitheres cannot land and disappear 

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#2128]
Hi.  I had an issue where I cannot land an amphithere.  They can take off ok, but whenever I try to land one they cannot make the transition from flying to walking on the ground.  Then, whenever I try to dismount, the amphithere just disappears.  I am playing with a very large number of mods, so this may be due to a conflict with some other mod.  Thanks for your time!

**Comment by AlexModGuy** [comment]
fixed in 1.8.4

**Comment by ghost** [comment]
Hello in the latest 1.12 version this seems to happen to me whenever an amphithere tries to walk or be on the ground..

example: https://www.youtube.com/watch?v=4fmHiT72axI
