### ISSUE TITLE
Tamed dragons despawn if you tp while they are sitting on your shoulder 

### ISSUE THREAD

**Issue by GundunUkan** [Alex-the-666/Ice_and_Fire#213]
I hatched a baby dragon and teleported to a waypoint using Xaero's Minimap. At first the dragon appeared to still be on my shoulder, but after a second or two it was gone. I teleported back to where I originally was. I could still hear the  dragon screech, but didn't see her on anywhere on the minimap, nor in the game itself. I reloged and now I couldn't even hear it anymore. This could be fixed if the player is a bit more careful and remembers to first put the dragon in the dragon horn, but even the slightest mistake could lead to the entity's despawning.

**Comment by Alex-the-666** [comment]
Duplicate issue of #168
