### ISSUE TITLE
Can't attack/damage dragons a server with some of my friends.

### ISSUE THREAD

**Issue by MrTiger109** [Alex-the-666/Ice_and_Fire#2130]
We've tried everything from normal hitting to using explosions and potions. Still, can't do damage to dragons so we can't get any of their flesh and etc.

**Comment by kodabeer** [comment]
I'm going to assume you guys already killed it and it's just sitting there laying on the ground, hence why you'd be unable to damage it, just try right clicking it with an empty hand. On the other hand if it never died in the first place ignore this comment Alex. Take a glass of water and slam it down you champ.

**Comment by MrTiger109** [comment]
Nope, they're alive and moving around. Freshly spawned, all dimensions that spawn them. Just can't hit them. We can do critical hits but it doesn't do any damage.

**Comment by Aeonerx** [comment]
A mi me pasa lo mismo, lo haz podido solucionar?

**Comment by zerolokitwo** [comment]
Hello i actually found a fix to this, im aware that the OP probably isnt looking anymore but i figured others might look for it.

Delete the file  "ISeeDragons"     And restart the server dragons should now be able to be damaged! Hope it helps

**Comment by MrTiger109** [comment]
We haven't used that mod in so long lmao but I really appreciate your attempt to help me. Thank you.
