### ISSUE TITLE
Having an issue with my tamed Dragon only making ash in the Dragon Fire Forge

### ISSUE THREAD

**Issue by ZeRoyalPanda** [Alex-the-666/Ice_and_Fire#2133]
My Tamed Dragon is only outputting ash in the fire dragon forge, my dragon is fully leveled up and isn't able to make and dragonsteel. Anyone got any ideas?

**Comment by AlexModGuy** [comment]
There needs to be both iron ingots and dragon blood of the associated type in the forge. otherwise they will only make ash.
