### ISSUE TITLE
Broken Dragon Horn item

### ISSUE THREAD

**Issue by GundunUkan** [Alex-the-666/Ice_and_Fire#214]
Sometimes the dragon horn would appear empty even if there is a dragon inside it. Reloging does the trick, but it's really irritating to constantly relog to be able to get your dragon back.

**Comment by EnderiumSmith** [comment]
EnderIO soul vials are an alternative to the horn

**Comment by GundunUkan** [comment]
Yeah, but I don't wanna install anymore mods, cuz my PC is very low on memory.

**Comment by AlexModGuy** [comment]
fixed
