### ISSUE TITLE
ASM crash

### ISSUE THREAD

**Issue by kellanj103** [Alex-the-666/Ice_and_Fire#2141]
Whenever I load up minecraft crashes. There's no actual crash log so here's the minecraft log its self. It tried to load up the main instance of minecraft but the launcher said it crashed. https://pastebin.com/E2crhqfh Thank you for your time

**Comment by YouEXE666** [comment]
Is Llibray in the mod folder? Ice and fire requires it and crashes minecraft immediately without it.

**Comment by kellanj103** [comment]
> Is Llibray in the mod folder? Ice and fire requires it and crashes minecraft immediately without it.

Ah I see now. Thank you. Hehe I didn't realize my common mistake.
