### ISSUE TITLE
Suggestion: Add Custom Support for Construct Armory (an addon for Tinkers Construct)

### ISSUE THREAD

**Issue by Warrof** [Alex-the-666/Ice_and_Fire#2142]
Just seems a shame to have access to your epic Dragonsteel for weapons and not armor.
Construct Armory's author actually prefers that other mods add compatibility.

Link to it's Curseforge page below.
https://www.curseforge.com/minecraft/mc-mods/constructs-armory

**Comment by kodabeer** [comment]
Wrong Github page, and either way Armory Expansion already does this.

**Comment by AlexModGuy** [comment]
^

**Comment by Warrof** [comment]
Thank for point that out, And sorry.
