### ISSUE TITLE
While being ridden Hippogryphs Won't ascend/descend

### ISSUE THREAD

**Issue by TheDaemonic** [Alex-the-666/Ice_and_Fire#2144]
While riding Hippogryphs I am currently not able to fly upwards or downwards they will only fly in the cardinal directions. They will move up and down if not trying to fly but if they are flying you can only move on the x and z axis. I am not using any other mods, and i'm using LLibrary 1.7.19, and am using Ice and fire 1.8.4

**Comment by BlueWither** [comment]
Oh I have same issue

**Comment by AlexModGuy** [comment]
fixed in hotfix
