### ISSUE TITLE
Armor bugs 

### ISSUE THREAD

**Issue by Dark0neW0lf** [Alex-the-666/Ice_and_Fire#2147]
I equipped myself with the fire dragon steel armor and after I fought a dragon I then switched to third person and the armor dissapeared but it was still equipped in the armor slots and same thing happened with the silver armor.
I also found a bug with the dragon armor as well where when I equip an armor to a dragon then the other tamed dragons wearing different armors will get the same texture of that armor and these happend in the 1.8.4 version

**Comment by SamuraiShogun1102** [comment]
I realized that foamfix anarchy causes the armor to disappear due to it's high texture cpu cache so I disable the foamfix core to fix it, and I figured out the textures id of the dragon armor have the same render id.

**Comment by AlexModGuy** [comment]
fixed
