### ISSUE TITLE
Invalid Player Move Packet

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#2151]
Hi.  I am having an issue where whenever I fly a dragon or amphithere, it glitches out and disappears.  Then the game crashes and I get an invalid player move packet error message.  I'm playing with around 300 mods, so it could be a conflict with some other mod.

**Comment by AlexModGuy** [comment]
what version

**Comment by ghost** [comment]
1.8.4

**Comment by ghost** [comment]
Figured out the crash, ice and fire is incompatible with Thaumic Arcana
