### ISSUE TITLE
ice and fire is incompatible with Thaumic Arcana

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#2152]
Hi. I am having an issue where whenever I fly a dragon or amphithere, it glitches out and disappears. Then the game crashes and I get an invalid player move packet error message. I'm playing with around 300 mods, so it could be a conflict with some other mod.

**Comment by BugmanBugman** [comment]
What version?

**Comment by ghost** [comment]
1.8.4

**Comment by ghost** [comment]
Figured out the crash, ice and fire is incompatible with Thaumic Arcana

**Comment by AlexModGuy** [comment]
doesnt seem to be on our end.

**Comment by oliverrook** [comment]
As the new maintainer of thaumic arcana, going to look into this problem on this end and see what I can do. Just posting this in case I need some form of assistance with access to a class file to override code on my end, as I know you're not developing for 1.12.2 anymore.
