### ISSUE TITLE
Myrmex queen not laying eggs and workers getting lost

### ISSUE THREAD

**Issue by TheDerpyMinekraftUtuber** [Alex-the-666/Ice_and_Fire#2153]
I was trying to create a man made myrmex hive and after a while (20-30 minutes) of them doing their thing, the queen stopped laying eggs and the workers got lost and never found their way back to the nest unless I used a chain on them to pull them back to their nest.

Edit: the workers also sometimes sit in front of items without picking them up.

Edit 2: after doing some stuff, (killing the worker's soldier escorts) the workers started to pick up items again, but shortly after returned to staring at the items.

Edit 3: i tried updating the mod, and things started working fine, but the queen stopped laying eggs again.

**Comment by BugmanBugman** [comment]
1.8.4?

**Comment by TheDerpyMinekraftUtuber** [comment]
this is version 1.8.3, maybe i should update it, I will close this thread if the problem is solved.

Edit: queen still not laying eggs, workers are picking up items after a punch.

**Comment by BlueWither** [comment]
I saw queen laying eggs at 1.8.4.

**Comment by TheDerpyMinekraftUtuber** [comment]
guess it must be an issue on my end.
