### ISSUE TITLE
Ice dragons not breeding

### ISSUE THREAD

**Issue by GrandAlbert** [Alex-the-666/Ice_and_Fire#2154]
I have this problem where I’ve dragons would not breed. I have two stage 4 dragons both male and female, I give the lily mixture the first the male the pen the female, and nothing happens, I tried the exact same thing with stage one fire dragons and it worked instantly creating a nest. I’ve tried this with ice dragons several times but no sauce.

**Comment by AlexModGuy** [comment]
fixed
