### ISSUE TITLE
Small bugs noticed in newest update.

### ISSUE THREAD

**Issue by Misteriawolfe** [Alex-the-666/Ice_and_Fire#2158]
![image](https://user-images.githubusercontent.com/45872028/73736713-e07ebe80-4706-11ea-9410-258a5fdc6278.png)

![image](https://user-images.githubusercontent.com/45872028/73736741-eeccda80-4706-11ea-9a5f-6c06d17a3bd8.png)

![image](https://user-images.githubusercontent.com/45872028/73736759-f9876f80-4706-11ea-9514-62cbcec1e4da.png)

The Ghost clone is seen from first person in front of me.

Riding my dragon made All of my armor (cosmetic and attached) disappear completely. I'm using Cosmetic armor reworked, baubles and RPG inventory and every single thing derender off my player model. Relogging did not fix.

Just tryna do my part to help point them out. I jumped on this newest release (which appears to have been a bad idea LOL). My server Loves this mod, though.

**Comment by Shayden13** [comment]
I have the same problem. I removed the rest of my mods but it still happens.

**Comment by BlueWither** [comment]
I think disappearing armor is not a "small" bug.
You should report it independently.

**Comment by IColorfulLily** [comment]
I had the same issues with my tail and ears dissappearing along with my wings. They were still there but they were invisible. And it was a bit laggy for me which is unusual for me.

**Comment by AlexModGuy** [comment]
fixed
