### ISSUE TITLE
Dragon armour is broken

### ISSUE THREAD

**Issue by ThatOnePersonWho** [Alex-the-666/Ice_and_Fire#2160]
with multiple dragons, armour will change texture so that it is the same on both of them, a dragon wearing silver armour will suddenly have a gold texture when another dragon has gold armour on, and after I took armour off one of them, the other would have no armour except for the tail . After some testing, I found silver dragon armour suddenly turns grey except for a small portion of the face. Further testing revealed that all armour became darker when a dragon is ridden.

**Comment by ThatOnePersonWho** [comment]
Accidentally pressed send so:
with multiple dragons, armour will change texture so that it is the same on both of them, a dragon wearing silver armour will suddenly have a gold texture when another dragon has gold armour on, and after I took armour off one of them, the other would have no armour except for the tail . After some testing, I found silver dragon armour suddenly turns grey except for a small portion of the face.

**Comment by AlexModGuy** [comment]
fixed
