### ISSUE TITLE
PLAYER TRANSPARENT SKIN APPEARS IN DRAGON MOUNTING

### ISSUE THREAD

**Issue by Shayden13** [Alex-the-666/Ice_and_Fire#2162]
I have recently added the 1.8.4 ice and fire mod version and when I´m flying on a dragon, my player skin appears in the third and first person point of view. I removed the rest of the mods I had but It still happens.
![Capture](https://user-images.githubusercontent.com/60667169/73773590-c1257700-4782-11ea-930a-11a830b6fe40.png)

**Comment by SamuraiShogun1102** [comment]
Didn't happen to me

**Comment by Shayden13** [comment]
If I play in a previus world only with the Ice and Fire 1.8.4 mod and I mount a dragon, it happens. But if I create a new world It doesn't happen. And if I add new mods, It happens in the new world created as well.

**Comment by Shayden13** [comment]
It's like the player hit box or the sitting point is displaced. So strange.
![1580986326304_Capture](https://user-images.githubusercontent.com/60667169/73933760-7409e800-48dd-11ea-9b23-26f7723792d5.png)

**Comment by SamuraiShogun1102** [comment]
I figure out when I dismount the dragon, that's when my armor goes invisible to both vanilla and modded.

**Comment by AlexModGuy** [comment]
fixed
