### ISSUE TITLE
Game Crashed

### ISSUE THREAD

**Issue by PersianDrogon** [Alex-the-666/Ice_and_Fire#2164]
I had put up a modpack but when launching , it crashed after trobleshooting it appeared Ice and Fire was causing the problem. and since im a fan of this mod and its neat I thought I'd report it for future bug fixes heres the log : [Click Here](https://pastebin.com/raw/Y6bPxneU)

**Comment by PersianDrogon** [comment]
its the latest version btw just wanted you to be alarmed

**Comment by YouEXE666** [comment]
IS llibray in the mods folder?

**Comment by PersianDrogon** [comment]
It is

**Comment by AlexModGuy** [comment]
fixed
