### ISSUE TITLE
hippogriph

### ISSUE THREAD

**Issue by Colossus610** [Alex-the-666/Ice_and_Fire#2165]
i cant fly up or down while riding an hippogryph but only when im riding a dragon(the hippogryph still open it's wings as well)

**Comment by BlueWither** [comment]
Re-download 1.8.4

**Comment by katsucks** [comment]
No, riding hippogryphs is definitely more janky, unnatural, and very glitchy. Redownloading the mod didn't seem to fix it. In fact, here's a summary of things that's wrong with the hippogryphs in the new update:
1. As previously mentioned, the flying is very unnatural. Not only can you **not** fly diagonally when pressing forward and either side keys, but the hippogryph cannot run diagonally either.
2. Walking off the edge seems to break it a little bit. The gryph will hover strangely for a bit before entering its flying animation, but you cannot fly downwards until you hold up for a second, as if the gryph does not realize it's actually flying.
3. And this is more just a personal preference. The speed increase for hippogryphs going forward just feels off now, especially when paired with the inability to fly diagonally, you either fly incredibly fast or move at a snails pace. I really prefer the smooth increase in speed when flying a gryph.

I know the update basically just came out, but no one seems to be actually talking about these specific issues. Hopefully this isn't just an issue on my end;;

**Comment by MissileMann** [comment]
I'm having the exact same issue in the latest version. Went back to 1.8.3 because I did not like how the flying was. Not sure if you had it too but I couldn't walk backwards while on land either.
