### ISSUE TITLE
Multiple, possible issues regarding the tail mod & wings mod. 

### ISSUE THREAD

**Issue by thelittleantlion** [Alex-the-666/Ice_and_Fire#2167]
A person in the discord server asked me to post it, i am unsure if its I/F causing the issue, but the problem just appeared in the latest 1.8.4 update.
As the player was riding the Dragon, their tail and ears (from the tail mod) disappeared. I suspect that this could be caused by the player being connected to the Dragon model.
The second issue involves the wings mod. Before the 1.8.4 update the person didnt have any problems, but from now on the wings disappear completely, and the player model/texture gets glitched out.
The third issue involves armour. After dismounting the tamed Dragon, all of her armour disappeared, the only way she could fix it was by re-opening the world
And the last issue involves the Dragon horn. When the person picked up her dragon a new one appeared.

I do not know what could be causing the problem. Btw the person already tried reinstalling mods, re-equipping armour, nothing worked. Thank you in advance for clarification.

**Comment by Shayden13** [comment]
I have the same problem. I think when you mount on the dragon, the player hit box ir the point where the player should be sitting is displaced.

**Comment by AlexModGuy** [comment]
fixed
