### ISSUE TITLE
Skin and armor glitches and other random glitches.

### ISSUE THREAD

**Issue by IColorfulLily** [Alex-the-666/Ice_and_Fire#2168]
I use the tails mod and the wings mod along with the ice and fire mod. I can no longer hear dragon wings flap. When disummining dragons some times an extra summon horn appears. I get really laggy when air born on a dragon especially when I have my two other dragons following. Have to be in f5 mode to get off the dragon or my armor tail ears and wings will dissappear and will only reappear if I get off in f5 mode. If I go off in first person then my tail ears wings and armor will be invisable. They are still there but I can't see them and it makes my skin glitch. My front hair piece dissappeares then when it returns it floats in side my head and I lag a lot when air born. I had no problems like these in previous versons so I am reluctant to believe this has anything to do with my other mods. I may send an update post if I have trouble breeding my dragons or if any other glitches show up. Please fix them and thank you for your hard work. This mod is truly one of my favorites thank you

**Comment by AlexModGuy** [comment]
fixed
