### ISSUE TITLE
Dragon Hunger Tick Bug

### ISSUE THREAD

**Issue by vaIenn** [Alex-the-666/Ice_and_Fire#2169]
I've noticed this quite annoying bug recently whilst I've been playing. I try to feed my dragons, let's say with steak for example, I feed them, and then their hunger level depletes to zero. No matter if the hunger was at say.. 90 beforehand, I feed the beast and it's hunger meter just depletes to zero. I like to keep my dragons out of horns in a den, so hearing babies and adult dragons starve to death isn't very fun.. Please fix this asap it's soooo annoying

**Comment by Magikaprfainted** [comment]
i have also had this happen as well, i used the creative dragon meal to tame wild dragons and had this same issue, chalked it up to it being a new feature.

**Comment by vaIenn** [comment]
I was told that it was from using creative dragon meal on wild dragons... that shouldn’t be the case anyway. Let’s just hope it gets fixed soon.

**Comment by AlexModGuy** [comment]
fixed
