### ISSUE TITLE
I cant launch the mod

### ISSUE THREAD

**Issue by Agentx49** [Alex-the-666/Ice_and_Fire#217]
i cant launch the mod there is no crash report and all i have is the mod and llibrary

**Comment by Spaz123** [comment]
There might be a conflict with another mod. Try starting up the game without any mods except Llibrary and Ice and Fire. Then add in one of the other mods you're using, and start it up again. Continue this process, adding one mod in at a time, until you add a mod that makes the game crash. It can get tedious, but it's the best way to find out which mod has a conflict.

**Comment by NoahNinja** [comment]
Or it is the wrong version of llibrary

**Comment by Agentx49** [comment]
Well I have no other mods and I have the newest llibrary version

**Comment by PlatinumFox** [comment]
are u you using the correct minecraft forge version

**Comment by Alex-the-666** [comment]
We can't do anything without a changelog.

**Comment by Agentx49** [comment]
I am using newest forge and there s no crash log. It just won't start

**Comment by DarkiHungary** [comment]
my game always crashes with this massage "This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR" what do i do?ples help me

**Comment by Alex-the-666** [comment]
Google the issue maybe?

**Comment by LemADEC** [comment]
@DarkiHungary the message itself says it's not error and should be ignored...
@Agentx49 please provide the version number for the mod, library and forge version. We'll also need the game logs

**Comment by EPIICTHUNDERCAT** [comment]
is this still an issue? close if not please
