### ISSUE TITLE
Ice dragon lairs without dragons

### ISSUE THREAD

**Issue by LichtHund** [Alex-the-666/Ice_and_Fire#2172]
As for the latest update I have found 3 lairs of ice dragons so far where there were no dragons in them, it is a completely new world so there is no way for someone to have killed them. Block breaking is also disabled so the problem where they are digging up should affect either.

**Comment by umbecanessa** [comment]
Hey @ipsk - I've the same issue, have. you been able to fix it ?

**Comment by LichtHund** [comment]
@umbecanessa Hmm this was a while ago, i think the problem was that sponge was removing big entities, there is a setting that makes it so if the entity is too big it won't spawn.
