### ISSUE TITLE
Sea Serpent wants to be a Dragon: Fails as expected

### ISSUE THREAD

**Issue by ArmouredHeart** [Alex-the-666/Ice_and_Fire#2173]
![2020-02-07_01 20 08](https://user-images.githubusercontent.com/42709948/74005932-9e48bd80-4950-11ea-9b26-3c6a627dc3a8.png)

Poor guys always try to get onto land instead of staying in the water. Perhaps make them flop around to try and get back to the ocean?

**Comment by smoothuk** [comment]
Should have become a Tree Serpent
![2019-11-29_01 02 15](https://user-images.githubusercontent.com/59454941/78186332-7c594c00-7464-11ea-9a92-095073742aa3.png)

**Comment by AlexModGuy** [comment]
fixed
