### ISSUE TITLE
Even more bugs that I found

### ISSUE THREAD

**Issue by ThatOnePersonWho** [Alex-the-666/Ice_and_Fire#2175]
Male dragons can lose the spots on their wings.
A grey dragon turned green.
Riding a dragon with others escorting caused them all to disappear.
Riding a dragon while fighting a wild one caused my camera to turn completely black, it appears that the game was still running, sounds still played and the escape key still seemed to perform its function, I did not do any further testing but it seemed that only by closing the game could I stop this. Dying also worked, and proved that this was wholly visual as I was able to run commands.

**Comment by SamuraiShogun1102** [comment]
this didn't happen to me

**Comment by ThatOnePersonWho** [comment]
these issues no longer come up for me, no idea why they happened lmao
closing the issue anyway
