### ISSUE TITLE
Problems with dragons (stage 4 dragons)

### ISSUE THREAD

**Issue by Polomka** [Alex-the-666/Ice_and_Fire#2179]
Dragons( 4 stage dragons) crawl out from the undeground nests when a player runs past them on the surface! They see players through the blocks and get out. Is it a mistake or new mechanics?

**Comment by Danil500** [comment]
у меня драконы в подземелье выползают когда я побегаю на достаточно большой дистанчииот гнезда  и от них не збижать  и заэтого погибаю пожалуста ришыти эту проблему

**Comment by JellyBlade** [comment]
Also having this same issue, any sleeping dragon in their nest immediately wakes up and targets the player as soon as they get within the usual detection range, regardless of whether they have stolen from the nest.
Only affects adventure/survival mode obviously, spectator and creative mode don't cause them to wake up.
Edit: This even happens on a fresh installation running nothing but Ice and Fire 1.8.4 and LLibrary 1.7.19 on forge-14.23.5.2847 on 1.12.2. 
Solution: Reverting to 1.8.3 returns the dragon's wake behaviour to what I assume is the intended behaviour, where the dragon is asleep until a player steals from their hoard close to the dragon.

**Comment by AlexModGuy** [comment]
fixed
