### ISSUE TITLE
Ice Dragon got stuck. [BUG]

### ISSUE THREAD

**Issue by DominoFirey** [Alex-the-666/Ice_and_Fire#218]
So i found this ice dragon roost near to a snowy village in a snow mountain biome, and this stage 3 ice drago nwas always flying around and landing sometimes for some sleep, i decided to prepare my self to go and kill him yesterday, so i go to eat some food, make some potions, and make a shield, i return to the ice mountain ice dragon roost, and i find him flying around, (now the first time i ever encountered him first thing that happened is he teleported to me grabbed me with his mouth and 2 bites killed me with full silver armor that i crafted and found in his roost) but anyways i was starting to shoot him with my bow and arrows didn't work (well i think i needed a dragonbone bow and bone arrows for this but i didn't know about it) so arrows didn't work on him, then as he got closer for landing i ran close to him and he started to get stuck! He did not defend himself, however he was screaming and trying to move while i was killing him, but he didnt turn to my side at all, he was stuck on 1 snow block infront of him that was "blocking his path" oddly, so he couldn't move (there was lots of space and we were on a ice mountain so he could fly or move around but he was stuck) and then after atleast 30 hits of silver sword and pickaxe i killed it, oh and another bug i want to point out is that you can duplicate dragon skulls, if you wanna replicate this bug just put a dragon skull on the grass or somewhere else, then destroy it in survival mode, and boom, you duplicated it!
Thanks for your time developers, sadly i don't have any Screenshots since it was my first time with this mod.

**Comment by Alex-the-666** [comment]
Duplicate issue of #206
