### ISSUE TITLE
Tamed dragons bypassing ftbutilities claims

### ISSUE THREAD

**Issue by jinkhya** [Alex-the-666/Ice_and_Fire#2180]
Hello,
It looks like tamed dragons can bypass ftbutilities claims and burn near everything from another player who is not your ally.

Before using my tamed dragon : 
https://i.imgur.com/iDDuegZ.png
After using the dragon : 
https://i.imgur.com/qYmGYij.png
Without the fire to see better : 
https://i.imgur.com/o0apXtF.png

Forge : 1.12 2847
Ice and fire : 1.8.3
Ftbutilities : 5.4.0.124  
Ftblib : 5.4.4.5

I'll post the issue on Ftbutilities to add him in the loop :)

**Comment by Sluggasaurus** [comment]
This also happens with wild dragons, not just tamed ones.

**Comment by TheMightyMcGrew** [comment]
Ive been through several claiming/grief prevention mods that dragons just ignore completely. I dont know who to turn to on this, Ice&Fire? or the Grief-Prevention modmakers? cause dragons seem to just not care about anything, including the config option for tamed dragons not grieing, doesnt change anything, dunno about wild ones.
