### ISSUE TITLE
Some creatures don't spawn anymore?

### ISSUE THREAD

**Issue by Severynn99** [Alex-the-666/Ice_and_Fire#2181]
A long while back, these were spawning normally. But now I don't ever see them anymore!

-Amphithere
-Cockatrice
-Death Worm
-Stymphalian Birds

Is there a mod incompatibility? I have about 126 mods but I didn't see if there were incomaptibilities anywhere. I'd like them to spawn again :c

I'm using the latest version of Ice&Fire and also latest version of llib

**Comment by f-raZ0R** [comment]
Things you should check to make sure you aren't being stupid:
Are you on peaceful difficulty?
Are you looking in the places that they actually spawn?

**Comment by Severynn99** [comment]
No to the first, yes to the second. I love deathworms half to death and they don't spawn in deserts

**Comment by Severynn99** [comment]
Whoops my mistake

**Comment by MasterOfTheCats** [comment]
Try increasing their spawn rate in the config and see if they start spawning. If they do, that means they’ve just gotten rarer. I still see them every now and again.

**Comment by Celophy** [comment]
i have tehe same bug, with the same mobs, also without any other mod and editing the config, they dont spawn
