### ISSUE TITLE
Sea Serpent Bubbles CTD when using Shield Parry mod

### ISSUE THREAD

**Issue by TheSpiderDungeon** [Alex-the-666/Ice_and_Fire#2183]
So I came across a sea serpent early on and had a giga brain moment where I thought "hey I could kill this guy right now with like 0 armor and just a shield if I parry his bubbles. That's a ranged attack right? Surely it will work perfectly and nothing could go wrong."

Game froze instantly upon bubble-to-shield contact, and crashed to desktop a couple seconds later.

[Crash log](https://pastebin.com/zFe83tZT)

Got around the potential corruption by changing to peaceful to get rid of the serpent, and thankfully it worked, but uh... Yeah, PSA: don't try to parry bubbles lmfao

**Comment by naqaden** [comment]
Try again without The Betweenlands. The log indicates that is the culprit.

**Comment by TheSpiderDungeon** [comment]
Oh damn, that did it!

How in the world did the Betweenlands do that lmfao

**Comment by AlexModGuy** [comment]
betweenlands issue, report it to them
