### ISSUE TITLE
Issue: Dragons disappearing.

### ISSUE THREAD

**Issue by Condescendedwow** [Alex-the-666/Ice_and_Fire#2189]
I've encountered 3 dragons so far vanishing into thin air.
2 of them were wild, 1 was tamed.
1 wild was stage 5, the other was stage 3.
None of them were even close to dying, they just simply stopped existing.

I'm using the MC Eternal modpack on a server for me and some buddies, since this seems to be a pretty uncommon glitch for this mod.

**Comment by TheLichTree** [comment]
Same thing happened to me when shift clicking from dragon bite. Just poof. Lost 4 females that way which is annoying beyond all belief and had to cheat dragon eggs in. :/

**Comment by Mnesikos** [comment]
Just came here looking for this same issue. It seems to happen after dragons let go of a player they've picked up, but not every time... It's happened with two dragons so far in my experience, an underground dragon fighting 3 players, and an above ground fighting 1 player. Neither of which were close to dying when they poofed.

I'm running I&F 1.9.1 and llibrary 1.7.19 on a server with spongeforge 7.2.0, forge 2847, and a handful of other mods. There's nothing in either latest nor debug logs to indicate what's happening to the entities.
