### ISSUE TITLE
Some dragons just won't drop skulls when corpse is harvested

### ISSUE THREAD

**Issue by GundunUkan** [Alex-the-666/Ice_and_Fire#219]
Plus, you can't get blood from the corpse, but when only the skeleton is left, that's when you can get blood from it, which is kinda odd and unrealistic.

**Comment by EnderiumSmith** [comment]
if you collect blood it will advance a stage without dropping bones. if you dont collect blood at all it will drop its full loot including skulls. you dont need more than one anyway. if you still want it collect at most 2.

**Comment by Alex-the-666** [comment]
is it a baby dragon? you shouldn't get skulls from baby dragons.

**Comment by GundunUkan** [comment]
Nope, wild stage 3s I find.
