### ISSUE TITLE
Stage 5 mother dragons coming out of the ground?

### ISSUE THREAD

**Issue by AFluffyKitten** [Alex-the-666/Ice_and_Fire#2192]
Not sure if this is a feature or a bug, but I've been having problems of mother dragons bursting out of the ground whenever coming anywhere near their underground caves, despite being above-ground. Goes a little somethin' like this: I'm walking across the grass, no dragons or anything in sight, and all of a sudden, wait, w-what's that sound? Hundreds of stone and dirt blocks breaking? I wonder what that could be? HOLY-
My best guess is it's the mobs spawning in their caves because I'm near enough that wakes them up, but I have no clue. I've had 3 of my minecraft horses fried so far because of this.
![2020-02-09_12 20 28](https://user-images.githubusercontent.com/61095433/74594938-8bde1c00-5001-11ea-80ac-9a3d50c655cf.png)

**Comment by BugmanBugman** [comment]
i dont think its supposed to happen, you aren't the only one with the problem either so don't worry. i found that setting the griefing of the dragons to "weak blocks" or just disabling helps temporarily fix the problem.

**Comment by KirikaAetheria** [comment]
same issue here. it seems that 1.8.4 broke some things, we'll have to give the authors time to fix them. in the meantime, reverting to 1.8.3 seems to be a good temporary solution

**Comment by samthelizard** [comment]
I think everyone is having this issue. The dragons detecting you are wayyyy too strong but I'm sure the creators will fix this since this really effects survival game playing.
