### ISSUE TITLE
Player armor and holding item become invisible after take off from dragon

### ISSUE THREAD

**Issue by BlueWither** [Alex-the-666/Ice_and_Fire#2193]
It is the issue reported in #2158 and #2168, but I though it is better to report it alone.

**Comment by ShadowKain666** [comment]
I had this issue after surviving being bitten and lifted by a dragon. Nothing in-game helped, re-logging didn't help, quitting and re-starting the game didn't help. The only way I was able to fix it was by forcing the game to crash via F3 + C.

(Hold F3 + C for at least ten seconds, and then release to force  Minecraft to crash.)

**Comment by SonicX8000** [comment]
I was wondering why my armor & stuff kept disappearing... it's not only armor & held items but it seems it also affects other renders on the player, such as baubles.

The only way to fix this is to restart minecraft.

**Comment by AlexModGuy** [comment]
fixed
