### ISSUE TITLE
Dragons coming out of caves + Frozen Dragon

### ISSUE THREAD

**Issue by Jooniebug** [Alex-the-666/Ice_and_Fire#2197]
Downloaded the new update. Started playing. Before I knew it, 3 level 5 dragons are out and about destroying everything. Quite honestly ruined my world a bit. Started a new world. Literally 3 minutes later of exploring level 5 dragon pops out from the ground. 

Think their player detection distance is bugged, they sense you from up high on ground level and dig long ways to see you. 

While I watched a level 5 ice dragon and level 5 fire dragon fight, the ice dragon suddenly froze and never moved again. I tried hitting her hoping it'll break her free, but it's like she became a non-entity. Like, when I hit, it makes that sound akin to when you cast a line (you know, using a rod).

Sorry if I shouldn't be putting multiple issues on one post. Some times my eyes skip over lines :/

**Comment by DonTheBreton** [comment]
Related issues: https://github.com/Alex-the-666/Ice_and_Fire/issues/2228 https://github.com/Alex-the-666/Ice_and_Fire/issues/2239 https://github.com/Alex-the-666/Ice_and_Fire/issues/2234  https://github.com/Alex-the-666/Ice_and_Fire/issues/2235 https://github.com/Alex-the-666/Ice_and_Fire/issues/2236 https://github.com/Alex-the-666/Ice_and_Fire/issues/2211

**Comment by AlexModGuy** [comment]
fixed
