### ISSUE TITLE
Dragons are destroying blacklisted blocks if they are up against it for long enough

### ISSUE THREAD

**Issue by MetroNight** [Alex-the-666/Ice_and_Fire#2199]
I didnt want dragons to destroy any blocks so I typed minecraft:sponge into the blacklist and turned it into a white list so all the other blocks were blacklisted. They destroy sponge as easily as you would expect and all the other blocks hold them back for a bit but no matter what blocks I used they seem to be able to eventually break through.

**Comment by KirikaAetheria** [comment]
that does happen, the blacklist is bugged. but if you don't want dragons to destroy any blocks, change the griefing option to 2. it'll stop them from destroying any block, whether by breaking them or burning them with fire
