### ISSUE TITLE
Particles Disappearing

### ISSUE THREAD

**Issue by ShadowKain666** [Alex-the-666/Ice_and_Fire#2201]
After varying periods of time playing, all particles stop rendering and can only be re-enabled by re-loading the world.

I am playing using the most recent version (as I understand this has been a persistent issue for some time, but was thought to be fixed).

**Comment by SamuraiShogun1102** [comment]
Did you have memory allocation up to 8gb because the computer can automatically disable particles if Minecraft is overloaded with them because they use lots of memory

**Comment by ShadowKain666** [comment]
I have 16gb (out of 32) allocated to Minecraft via JVM argument "-Xmx16G".

**Comment by SamuraiShogun1102** [comment]
I use at least between 8gb - 12gb because allocating too much memory can cause lag.
