### ISSUE TITLE
Hippogryph Problems

### ISSUE THREAD

**Issue by Jooniebug** [Alex-the-666/Ice_and_Fire#2202]
2 problems when they fly: Often their wings are not stretched out and it looks like they are walking on air, and if they fly away far enough they will turn completely black every once in a while.

1 problem while riding them: I can press X to go down until I'm a few blocks off the ground, then I can't get any lower.

**Comment by xevilredx** [comment]
Same happens to me after the last update, hope it gets fixed soon :/
