### ISSUE TITLE
Dragon Armor Texture Glitch

### ISSUE THREAD

**Issue by CosmicGlowsticks** [Alex-the-666/Ice_and_Fire#2203]
So, I have a fire and ice dragon. I swapped their armors so they would have armors of the opposite element. Problem is, every time the dragon is re-rendered or loaded, the texture reverts to the previous armor/corresponding element. It goes to the right texture after removing one piece, however it is a temporary fix and bugs out again after re-render/loading. After reloading the world next to the dragon, the armor is the correct texture for a few moments before switching.

**Comment by AlexModGuy** [comment]
fixed
