### ISSUE TITLE
Dragon hunger draining in seconds, dragon meal not working

### ISSUE THREAD

**Issue by CosmicGlowsticks** [Alex-the-666/Ice_and_Fire#2204]
I was messing around and creative tamed a dragon. I checked on it a while later and fed it a bit, but it wouldn't stop. So I check it's hunger, and it's draining like mad. It goes back to zero in seconds, but it doesn't lose health at all. Dragon meal isn't growing it either, just feeding it (which is still ineffective). I just noticed this today

UPDATE: Apparently it's just the world, but I'll leave this up just in case it actually ends up being something

**Comment by SamuraiShogun1102** [comment]
It may be hard to fix due to how wild dragons work so it's hard to fix without breaking the wild dragon data.

**Comment by 123456789zvvxvxtitoferdian** [comment]
im having the same problem
How can i fix it? (the dragon meal isnt growing the dragon)

**Comment by CosmicGlowsticks** [comment]
> 
> 
> im having the same problem
> How can i fix it? (the dragon meal isnt growing the dragon)

I have no idea, but I'm glad to know I'm not alone!!! At least the starvation doesn't kill them with this bug. THAT would suck.

**Comment by AlexModGuy** [comment]
fixed fixed
