### ISSUE TITLE
Dragon is despawning after releasing it from the Dragon Horn

### ISSUE THREAD

**Issue by Jamal187** [Alex-the-666/Ice_and_Fire#2207]
Modpack: MC Eternal 1.3.3
Ice and Fire version: 1.8.4
My tamed Dragon has a chance to despawn after it release it from the dragon horn.

**Comment by Fabrimat** [comment]
Seems to happen only with dragon stage 4+

**Comment by stacytritt** [comment]
same problem here. happens on my server

**Comment by Fabrimat** [comment]
Do you have Sponge installed?
