### ISSUE TITLE
Crashing when entering the game.

### ISSUE THREAD

**Issue by Alexyan2218** [Alex-the-666/Ice_and_Fire#2208]
When I enter the game, a message appears saying: Ice and Fire:requires version 1.8.4 but mod is not found on client. And it says the same for Llibrary but with version 1.7.15.
The zips are in the Mod file and I’m playing in Forge 1.12.2 which is the version that the Mods’ versions are supposed to work on.

**Comment by AlexModGuy** [comment]
some other mod requiring ice and fire is doing this
