### ISSUE TITLE
Stage 4 and 5 dragons overspawning

### ISSUE THREAD

**Issue by Wolfixsp** [Alex-the-666/Ice_and_Fire#2211]
so stage 4 and 5 are overspawning outside of the caves and they have insane aggro ranges it is now super common for the ones that are on caves to just burst trough the floor and kill everything without being woken up

**Comment by goldenvixen** [comment]
I can confirm. Same is happening to me. I disabled digging to see if that will help but nope. they are still spawning outside of their caves and wrecking everything.

**Comment by emeraldsiren** [comment]
I can confirm this is happening. Started a brand new server and dragon clearly dug it's way from the horde under a river and through a mountain to kill someone on the server. The hole in this picture was created on the way to murder this player.

![image](https://user-images.githubusercontent.com/61640222/75618116-9383e180-5b26-11ea-8ba3-1cc825038900.png)

**Comment by messicedragon** [comment]
What??!! That is abnormal! The dragon dig through a mountain! Is it a bug?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "emeraldsiren"; 
发送时间: 2020年3月1日(星期天) 上午10:07
收件人: "Alex-the-666/Ice_and_Fire";
抄送: "Subscribed";
主题: Re: [Alex-the-666/Ice_and_Fire] Stage 4 and 5 dragons overspawning (#2211)




I can confirm this is happening. Started a brand new server and dragon clearly dug it's way from the horde under a river and through a mountain to kill someone on the server. The hole in this picture was created on the way to murder this player.
 

 
&mdash;

**Comment by Hyperion42** [comment]
I'm having the exact same problem, twice now I've had stage 5 dragons dig up from their lair to kill the living daylights out of me (I'm playing the RAD modpack if that's useful information)

![stage 5 dragon lair](https://user-images.githubusercontent.com/10748869/75770400-f0d49880-5d9b-11ea-9667-f3c58f7594ad.png)
![it climbed up](https://user-images.githubusercontent.com/10748869/75770405-f500b600-5d9b-11ea-9264-6cec37cce166.png)
![and killed me](https://user-images.githubusercontent.com/10748869/75770372-e914f400-5d9b-11ea-9c5e-d205dcce454f.png)

Edit - make that three. I tried setting griefing so they could only break weak blocks, but they still broke through to the surface

**Comment by DonTheBreton** [comment]
Related issues: https://github.com/Alex-the-666/Ice_and_Fire/issues/2228 https://github.com/Alex-the-666/Ice_and_Fire/issues/2239 https://github.com/Alex-the-666/Ice_and_Fire/issues/2234  https://github.com/Alex-the-666/Ice_and_Fire/issues/2235 https://github.com/Alex-the-666/Ice_and_Fire/issues/2236

**Comment by AlexModGuy** [comment]
fixed
