### ISSUE TITLE
Editing Dragonsteel values just doesn't work?!

### ISSUE THREAD

**Issue by DorkyMcDorkus** [Alex-the-666/Ice_and_Fire#2213]
It used to, but now it doesn't. Whenever I edit the config for dragonsteel base values, any of the three, in game nothing changes.

**Comment by messicedragon** [comment]
Emm...... But you know this,I&#39;m just a player... Are you really Alex-the-666? I like you make the mod (Ice and fire) , it&#39;s my favourite mod! But can you tell me when to update Ice and Fire 1.9?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "DorkyMcDorkus"; 
发送时间: 2020年3月1日(星期天) 凌晨2:37
收件人: "Alex-the-666/Ice_and_Fire";
抄送: "Subscribed";
主题: [Alex-the-666/Ice_and_Fire] Editing Dragonsteel values just doesn&#39;t work?! (#2213)




It used to, but now it doesn't. Whenever I edit the config for dragonsteel base values, any of the three, in game nothing changes.
 
&mdash;

**Comment by AlexModGuy** [comment]
you need to restart the game.
