### ISSUE TITLE
Stage 4 and 5 Dragons burrowing up to the surface

### ISSUE THREAD

**Issue by Psychopathrik** [Alex-the-666/Ice_and_Fire#2228]
I'm fairly certain that this is a bug, but if it is then you might actually consider to make it a proper feature. It resulted in some amazing experiences.
Now, this is a bug report, but also a really cool story:

I stared a new world with Ice and Fire and a bunch of other mods in Virtual Reality (using Vivecraft, but I don't think this have any bearing on the bug). After having played for maybe a week or two (Minecraft days), and just having gotten full iron armor and a bow and arrows, a large Fire Dragon flew over a hill and started attacking me (and wrecked a lot of my base, but thankfully it was early game). It managed to kill me, but I respawned in my starting hidey hole about a dozen blocks away. The dragon was unusually large, but at first I thought that either I misjudged it's size due to being in VR and it actually was a Stage 3, or that stage 4 and 5 dragons now can spawn like ordinary mobs (but hopefully rarely). After a lot of peeking out of my hidey hole and shooting at it with a LOT of arrows (and a few deaths), it finally died (I felt like a god after that, despite having cheesed it). When looting it, the skull confirmed my suspicions that it was indeed not a stage 3 dragon, but a (relatively small) stage 5! Thankfully it was female, so I got an egg (green) and some bronze scales out of it!

After this, I rebuilt my base and continued as normal, but the story doesn't end there. About a week later, I decide to go to a nearby rougelike dungeon (from the mod with the same name). On my way over there, I discovered a large, very straight diagonal tunnel sloping downwards. Since this was in the same direction that the dragon came from, this was when I started to suspect that the dragon could actually have been burrowing up to the surface. I continued to the rougelike dungeon, and when I was just a few blocks away from the door to the tower, the game started to lag like crazy. A few seconds later, the ground below me bursts open, and I'm suddenly engulfed in fire as I see a large black dragon rising from the resulting hole! Obviously, I died a few seconds later.

Currently, the black dragon is still alive (and I don't know it's stage yet), but I'm now certain that both dragons burrowed to the surface from their caves. I checked the map in the program "Unmined", and there are indeed two dragon caves at the end of the two tunnels (I will have a lot of resources once I muster the courage to loot them). It seems the dragons can track players from very far away, and are very determined to get to them (unfortuneatly, I'm not sure what triggered this tracking, or their awakening). Obviously this isn't a good feature to have as it is now (especially not if they attack early game, as they did now), but the general concept that stage 4 and 5 dragons can awaken from their slumber, rise from the depths and hunt the player down is really cool. Perhaps when a certain amount of gold have been collected in a chest, they will track it down?

But still, fix the unintentional burrowing and tracking first :D

**Comment by PT400C** [comment]
Can confirm it. After a big lag due to tons of breaking blocks a dragon emerges from the ground and kills you.

**Comment by DonTheBreton** [comment]
I have this same issue in multiplayer.

Version: 1.8.4-1.12.2

My investigations have discovered that this is actually because in previous versions, the dragons would try to burrow up, but get easily stuck on blocks and stay underground. The most recent update made them not as likely to get stuck on blocks underground and now they burrow through everything.

My understanding is the intended behavior is that they should remain sleeping until someone enters their chamber or at least within a few blocks of the dragon without sneaking. However, these dragons are burrowing up just to chase nearby animals.

Identical issue: https://github.com/Alex-the-666/Ice_and_Fire/issues/2239

**Comment by Druiddraws** [comment]
its super annoying, especially when you try and play hardcore. i spent almost 30 min bringing a horse and few other animals i found home just for a huge dragon to wake up and murder me. i hate it
