### ISSUE TITLE
[1.8.4] Wild Dragons not registered as hostile, therefore not attacked by defender mobs like Iron Golems

### ISSUE THREAD

**Issue by Carro1001** [Alex-the-666/Ice_and_Fire#2233]
Wild Dragons should be classified as hostile mobs, so things such as modded turrets and golems automatically attack them instead of doing nothing.

**Comment by Danyerious** [comment]
Hmm, maybe the Wild Dragons are not calibrated to attack iron golems nor modded turrets. Maybe they just attack players and other mobs such as sheep, pigs, chickens, ect.

**Comment by AlexModGuy** [comment]
cannot make them hostile. doing so would cause golems etc. to target baby dragons too
