### ISSUE TITLE
Dragon Detection Too Strong

### ISSUE THREAD

**Issue by samthelizard** [Alex-the-666/Ice_and_Fire#2236]
It's extremely hard to try and live in survival when you have a dragon trying to kill you every two seconds. I was trying to kill this dragon and kept dying and when I spawned in a random area, ANOTHER dragon appeared and kept killing me over and over again because I couldn't get away fast enough. Not to mention, a dragon can detect me underground as well so whenever I come back up from mining, I instantly get killed by a dragon. I was hoping if you could make it easier to sneak away from dragons _**like left shifting away from the dragon**_, basically they wouldn't be able to **detect our movement so we could escape.** _**Or make it harder for them to detect us.**_ I just think it would be really difficult to even try to make a house without a dragon flying over and burning everything down. 

It hasn't happened to me because I haven't gotten the chance but I'm positive that it wouldn't be fun to be **_attacked by a dragon mid-air while flying your own._** 

_**It would be nice if you made the dragons passive when you're riding a dragon. Like if you're riding an ice dragon, wild ice dragons won't attack you and if you're riding a fire dragon, fire dragons won't attack you, that way the players don't end up dying and losing their dragon.**_ 

Edit: This is a stage five dragon that killed me when it popped out from underground. I had to go into creative to take this screenshot.
![90510641_674442429997822_6144459069257154560_n](https://user-images.githubusercontent.com/62404656/77123537-c9760080-6a16-11ea-8e8a-2f36fe11a1bf.png)

**Comment by BlueStriker101** [comment]
Agreed. No reason a dragon should he allowed to fly over and spawn kill me right as soon as I enter a world. Their range is WAY too out of control and the config option to change it literally does not work. I tested setting it to 1 and it did nothing.

**Comment by DonTheBreton** [comment]
Related issues: https://github.com/Alex-the-666/Ice_and_Fire/issues/2228 https://github.com/Alex-the-666/Ice_and_Fire/issues/2239 https://github.com/Alex-the-666/Ice_and_Fire/issues/2234  https://github.com/Alex-the-666/Ice_and_Fire/issues/2235

**Comment by HienaKonata** [comment]
I totally agrgee with you. When i finally got my dragon to level 3 i got killed by a random dragon from out of nowhere while i was FLYING high in the air, it killed me and my dragon.
Also i recently started a new game and i have that problem you are talking about; I get killed by a dragon that got agrgod while i was mining and i spawn and get killed by another one. 
I really do love the dragons in this mod, but i think they should be controlled more because they have a huge destrictive power c:

**Comment by samthelizard** [comment]
@HienaKonata Exactly, I haven't even been able to get a dragon egg because I don't have time to get items when dragons are constantly trying to kill me but I mentioned it anyway because I was almost positive it might be an issue. I'm sure they'll fix it though so I'm just waiting patiently.

**Comment by BlueStriker101** [comment]
But will they fix it in 1.12.2? Or will they abandon it >->

**Comment by samthelizard** [comment]
@BlueStriker101 I mean I think they have to or people are gonna stop playing. It's a pretty big issue and I think it would be stupid to abandon it.

**Comment by HienaKonata** [comment]
@samthelizard yes, people are definetly gonna abandon if this is not fixed. I had to change lots of dragon setting on the mod options to make the game playable.

**Comment by AlexModGuy** [comment]
fixed
