### ISSUE TITLE
Stone charring/freezing 

### ISSUE THREAD

**Issue by mxnmnm** [Alex-the-666/Ice_and_Fire#2241]
This is somewhat of suggestion but it modifies an existing feature so I feel it's ok to put here.  It would be nice for blocks that get charred/frozen by dragons to return to the blocks that they originally were.  It would make things feel more natural which was the original purpose of this feature.

**Comment by SandwichHorror** [comment]
I think the original purpose of the feature was to have dragons leave a tangible and visible mark on the world.

**Comment by mxnmnm** [comment]
The original purpose of having it return to normal not of the actual charring
