### ISSUE TITLE
How do dragon caves spawn?

### ISSUE THREAD

**Issue by hakasapl** [Alex-the-666/Ice_and_Fire#2243]
Hello,

I'm working on getting Ice and Fire to be compatible with YUNG's Better Caves mod. I understand no support can be offered for this, I was just wondering how the mechanic of generating dragon caves worked. It could just be me, but since there are more caves from YUNG's, there seems to be less dragon caves. Do dragon caves not generate if a cave is blocking it? I can confirm that they are spawning, I just haven't seen as much as there would be in vanilla.

**Comment by Danyerious** [comment]
I am no expert but try to go into the Ice and Fire's config which can be located in Mods. If you set the "Generate Dragon Caves" to false then put that to true. c:

**Comment by AlexModGuy** [comment]
caves generate as worldgen features that have a random chance to spawn for each chunk generated. The sphere then "scorches" or "freezes" a few surrounding spheres and hollows them out, then decorates them with gold, chest, etc. Then finally spawns in the dragon.
