### ISSUE TITLE
Config file is not responsive.

### ISSUE THREAD

**Issue by Thiccempty** [Alex-the-666/Ice_and_Fire#2246]
I changed dragons health and damage in config file, both client and server, even though file remained changed, no values I set are applied to dragons, for example: changing 500 hp to 4000 hp. Still stage 5 dragon has max  500.

**Comment by Danyerious** [comment]
Thiccempty, You changed it from 500 to 4,000, right?
Well, you see, 500 is the max. You putting it at 4,000 still makes it max. Therefore, your dragon has max health and it didn't take affect because it's hp was already at max.

**Comment by AlexModGuy** [comment]
also it applies to newly spawned dragons.
