### ISSUE TITLE
Model issue with mod MorePlayerModels

### ISSUE THREAD

**Issue by Tennik** [Alex-the-666/Ice_and_Fire#2248]
Hello! You made an awesome mod, I really enjoy that!
But I found a problem with rendering armors on player when you use MorePlayerModels Mod:
https://i.gyazo.com/49ebd9118c1408cda1b015d52497f843.png
Only Sheep Armor render well
I'm using the latest version of mod for MC 1.12.2
Can you fix that, please?

**Comment by AlexModGuy** [comment]
this is up to the other mod to fix

**Comment by Tennik** [comment]
> this is up to the other mod to fix

You mean that is a problem of More Player Models mod? But why I dont have the same problem with rendering of armors in my own mod? They render properly with MPM
