### ISSUE TITLE
Ice dragon in the twilight crashes the server

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#2249]
I can't even ente the server from my account. In the middst of fighting a dragon the server crashed, I tryed to start it up again but as soon as i connected the server crashed again, I'm attaching the crash report file, and luckily my friends can still connect and play, but ntill this is fixed i can't 😢 hope there's an easy way to fix this, and that it won't happen on posterior patxes :P 
[crash-2020-03-27_14.38.54-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/4394215/crash-2020-03-27_14.38.54-server.txt)

**Comment by Danyerious** [comment]
Maybe you have too many mods installed if it's gonna crash like that. Try to remove half of the mods if you have a lot in your mods folder~ If that doesn't fix it then I hope it'll be fixed eventually!
