### ISSUE TITLE
[Bug] baby dragon neck spazzing

### ISSUE THREAD

**Issue by Quizer9O8** [Alex-the-666/Ice_and_Fire#225]
Whenever you put a dragon on your shoulder their necks start to spaz out.
![2017-04-23_22 31 14](https://cloud.githubusercontent.com/assets/19509275/25317229/e4b2f8e4-2874-11e7-87c5-d33fa08c3bc1.png)
![2017-04-23_22 31 14_3](https://cloud.githubusercontent.com/assets/19509275/25317230/e4b47278-2874-11e7-897a-0736c331dcdb.png)

**Comment by Spaz123** [comment]
This has been happening to me too. It only really seems to happen when you look around/ move.

**Comment by AlexModGuy** [comment]
fixed
