### ISSUE TITLE
1.12.2 Dragons Vanish When Killed

### ISSUE THREAD

**Issue by BlueStriker101** [Alex-the-666/Ice_and_Fire#2250]
Basically, any time I kill a dragon, it completely vanishes leaving nothint but xp. I notice that sometimes reloading the world can fix it but this never even used to happen.

**Comment by MysticaIChicken** [comment]
I also have this problem. Leaving the chunk of the dragon's death and coming back will also respawn the corpse. However, if a dragon dies from a non-player entity (e.g. Creeper explosion), the corpse will work properly and not vanish.
