### ISSUE TITLE
Cockatrice kills chicken herder in minecolonies

### ISSUE THREAD

**Issue by oneafish** [Alex-the-666/Ice_and_Fire#2251]
Whenever I hire a chicken herder in my minecolonies village, my cockatrice will kill him/her.

**Comment by bugSandwich** [comment]
I believe cockatrices attack anyone who attacks chickens near them, except their tamer, and chicken-herders definitely kill chickens. This doesn't seem to be a bug, it's likely just an unexpected interaction between the two mobs.
