### ISSUE TITLE
TP'd while near a dragon -- dragon came with and trashed my base

### ISSUE THREAD

**Issue by HammerDave** [Alex-the-666/Ice_and_Fire#2252]
Was fighting a dragon, decided it was a bad idea and TP'd away with /home.
The dragon promptly appeared at my base (1000 or so blocks away) and tore the place up.
Maybe because I was essentially touching it at the time, the code thought I was riding it?
That code should only trigger for a tame dragon, not wild.

**Comment by Danyerious** [comment]
I believe it's a bug. If it is then I hope it'll be fixed soon! :)
