### ISSUE TITLE
Error when spawning hippogryph

### ISSUE THREAD

**Issue by Tennik** [Alex-the-666/Ice_and_Fire#2253]
Hello! When I try to spawn hyppogryph with spawn egg, it doesnt appear and i get much of errors in the server log:

0:51:47 [Server thread/ERROR] [FML]: Encountered an exception while constructing entity 'iceandfire:hippogryph'
0:51:47 java.lang.reflect.InvocationTargetException: null
0:51:47 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_231]
0:51:47 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_231]
0:51:47 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_231]
0:51:47 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_231]
0:51:47 	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:293) [EntityEntryBuilder$ConstructorFactory.class:develop-003d055]
0:51:47 	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:283) [EntityEntryBuilder$ConstructorFactory.class:develop-003d055]
0:51:47 	at net.minecraftforge.fml.common.registry.EntityEntry.newInstance(EntityEntry.java:70) [EntityEntry.class:develop-003d055]
0:51:47 	at net.minecraft.entity.EntityList.func_188429_b(EntityList.java:190) [vi.class:?]
0:51:47 	at net.minecraft.item.ItemMonsterPlacer.spawnCreature(ItemMonsterPlacer.java:190) [ajv.class:?]
0:51:47 	at net.minecraft.item.ItemMonsterPlacer.func_77840_a(ItemMonsterPlacer.java:181) [ajv.class:?]
0:51:47 	at net.minecraft.item.ItemMonsterPlacer.func_180614_a(ItemMonsterPlacer.java:83) [ajv.class:?]
0:51:47 	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:811) [ForgeHooks.class:develop-003d055]
0:51:47 	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:216) [aip.class:?]
0:51:47 	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:569) [or.class:?]
0:51:47 	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:1031) [pa.class:?]
0:51:47 	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(CPacketPlayerTryUseItemOnBlock.java:54) [ma.class:?]
0:51:47 	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(CPacketPlayerTryUseItemOnBlock.java:14) [ma.class:?]
0:51:47 	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:10) [hv$1.class:?]
0:51:47 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_231]
0:51:47 	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_231]
0:51:47 	at net.minecraft.util.Util.func_181617_a(Util.java:36) [h.class:?]
0:51:47 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:692) [MinecraftServer.class:?]
0:51:47 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:394) [nz.class:?]
0:51:47 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:635) [MinecraftServer.class:?]
0:51:48 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:528) [MinecraftServer.class:?]
0:51:48 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
0:51:48 Caused by: java.lang.NoSuchMethodError: net.minecraft.inventory.ContainerHorseChest.<init>(Ljava/lang/String;I)V
0:51:48 	at com.github.alexthe666.iceandfire.entity.EntityHippogryph$HippogryphInventory.<init>(EntityHippogryph.java:1145) ~[EntityHippogryph$HippogryphInventory.class:?]
0:51:48 	at com.github.alexthe666.iceandfire.entity.EntityHippogryph.initHippogryphInv(EntityHippogryph.java:203) ~[EntityHippogryph.class:?]
0:51:48 	at com.github.alexthe666.iceandfire.entity.EntityHippogryph.<init>(EntityHippogryph.java:102) ~[EntityHippogryph.class:?]
0:51:48 	... 26 more

**Comment by Danyerious** [comment]
Hmmm, This too might be a bug. Hope it'll be fixed in the future!

**Comment by Tennik** [comment]
Sorry, seems that was a problem with my server core! I updated that and solved my problem
