### ISSUE TITLE
1.12.2 Craft tweaker dragon forge not working

### ISSUE THREAD

**Issue by SgtRalphie** [Alex-the-666/Ice_and_Fire#2258]
is there something I need to do besides what it says on github wiki for the craft tweaker recipes for the dragon forge? doing just the "mods.iceandfire.recipes.addIceDragonForgeRecipe(<input>, <bloodInput>, <output>);" produces an error with craft tweaker

**Comment by SandwichHorror** [comment]
```
import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;
import mods.jei.JEI;

mods.iceandfire.recipes.addFireDragonForgeRecipe
	(<mod:item>,<iceandfire:fire_dragon_blood>,<iceandfire:dragonsteel_fire_ingot>); 
```
That should work, it does for me. Check your syntax.

**Comment by AlexModGuy** [comment]
^
