### ISSUE TITLE
Armor Diseappearing 1.12.2

### ISSUE THREAD

**Issue by Brasair** [Alex-the-666/Ice_and_Fire#2260]
I'm having a problem every time i ride on my dragon whenever i dismount him my armor doesn't appear on my character, but it does reappear whenever i ride him again but only when i'm on my dragon. Tell me if you need any info on my game.

**Comment by xMrCaosx** [comment]
I found a possible solution.
When you dismount a Dragon you need to have the Third Person enable (In all moment), after dismount the Dragon you will see ur clothes normal and you can put again the first person, and problem fixed!.

I just tested a few minutes ago and it's working for me atleast. And im using Comestic Armor Reworked.

**Comment by AlexModGuy** [comment]
fixed
