### ISSUE TITLE
Blacklisted blocks are still affected by dragon breath.

### ISSUE THREAD

**Issue by hismajestydayama** [Alex-the-666/Ice_and_Fire#2261]
I have few blocks that I do not want dragons to destroy and I have listed them in the config, but dragons can still destroy them with their breaths. Help. 

This is the config I did: 

    # Blacklist for blocks that dragons are not to break or burn. Ex. "minecraft:chest" or "rats:rat_crafting_table" [default: ]
    S:"Blacklisted Blocks from Dragon" <
        "industrialforegoing:mob_duplicator"
        "cyclicmagic:fluid_pump"
        "cyclicmagic:fluid_pipe"
        "cyclicmagic:item_pipe"
        "cyclicmagic:item_pump"
        "cyclicmagic:cable_wireless_fluid"
        "cyclicmagic:cable_wireless"
     >

**Comment by Danyerious** [comment]
Hmm, I don't believe you can change them. If I'm wrong then please correct me. But you can try to disable it in the config. (If there even is the option to. I haven't looked.)

**Comment by AlexModGuy** [comment]
fixed
