### ISSUE TITLE
Stage 4 and 5 dragon

### ISSUE THREAD

**Issue by Pizza678** [Alex-the-666/Ice_and_Fire#2262]
Hi
I don't know if this is a feature or not but While I'm walking around in survival the stage 4 and 5 dragons seem to be targeting me on the surface and starting digging up and keep killing me and im not able to get my stuff back after they do this
And no offence but if this is a feature it's pretty stupid as early players get killed and loose everything

**Comment by Druiddraws** [comment]
its not supposed to happen, ive been using this mod for a long time and it seems to be a new issue, very annoying though

**Comment by fortestgump** [comment]
how to fix this bug?

**Comment by AlexModGuy** [comment]
fixed
