### ISSUE TITLE
[SUGGESTION] Config option for controlling rate at which myrmexes spread

### ISSUE THREAD

**Issue by Sunconure11** [Alex-the-666/Ice_and_Fire#2264]
Just what it says on the tin. I had spawned in a few myrmexes on a server that had them off, and they spread really fast. A config option to allow one to control the rate at which they spread would be useful. It could also help reduce lag, since lower spread rates would mean less entities.

**Comment by Danyerious** [comment]
That's- Not a bad suggestion. Not bad at all.

**Comment by AlexModGuy** [comment]
Spread as in colony reproduction, or foraging routes?

**Comment by Sunconure11** [comment]
Colony reproduction
