### ISSUE TITLE
Dragon bugs

### ISSUE THREAD

**Issue by TheKlimoT** [Alex-the-666/Ice_and_Fire#2265]
The player becomes invisible if he enters the dragon

**Comment by Danyerious** [comment]
Do you have a mod installed? A mod that makes players invisible when in a dragon lair?

**Comment by HARRRRRIE** [comment]
What does that do? I have that installed to

**Comment by TheKlimoT** [comment]
Nope,No, there are bugs with the dragon and the player, I can get off the dragon and the players will not see me, and only re-entry will help

**Comment by Danyerious** [comment]
Hmm, I see. Well, it might be a bug. I'm not a professional but if it IS a bug then I hope it'll be fixed in the future! <3

**Comment by AlexModGuy** [comment]
fixed
