### ISSUE TITLE
Movement and Attacking - Dragons  

### ISSUE THREAD

**Issue by abdullahasayed** [Alex-the-666/Ice_and_Fire#2266]
I am currently playing with a large customized mod pack. 

All wild dragons I have encountered, despite being hostile, more or less refused to fly (even when I am flying around them with a Mekanism Jetpack), and attack very sparingly. It seems that they get stuck in their environment and that causes that to stay around one spot and prevents them from attacking properly. 

A couple other times, I have found that even though the dragon is mobile, roaming the ground, when I am flying above it, it almost never flies up to attack and I am able to kill it with simple ranged weapons. 

I have encountered 5 dragons, all acting like this, all stage 4 or above. 

![image](https://user-images.githubusercontent.com/63065965/78277291-45298000-74e2-11ea-9f54-40422c01e006.png)

Above is a Stage 5 male dragon I encountered which did not, at any point, lift off from the ground. It stayed in one spot and never attacked me. 

My mod library: 
![image](https://user-images.githubusercontent.com/63065965/78276785-80777f00-74e1-11ea-9c0e-bc7d4000c29d.png)

![image](https://user-images.githubusercontent.com/63065965/78276814-8e2d0480-74e1-11ea-9fe3-d8b7546f271b.png)

**Comment by Xorbah** [comment]
None of this info is helpful without some kind of output log.

**Comment by Danyerious** [comment]
Ah, this is a common bug where stage 4 or 5 dragons rise above their caves. This will hopefully be fixed. For now, just keep 'Generate Dragon Caves' off. That is, if you want to play survival. I hope you understand!

**Comment by AlexModGuy** [comment]
^
