### ISSUE TITLE
1.12.2 Vanilla Mob Detection Broken?

### ISSUE THREAD

**Issue by BlueStriker101** [Alex-the-666/Ice_and_Fire#2268]
As many have reported the Dragons being able to detect players through the ground and stuff, I just recently noticed that even vanilla mobs appear to be able to see me and follow me through cave walls, floors, and ceilings. I confirmed this by watching their icons with my minimap mod I have installed. They were definitely trying to follow me. I was wondering if this was an issue with Ice and Fire, again bringing to question the existing issue with dragons being able to do the same.

**Comment by Danyerious** [comment]
Hmm, this might be a bug. I don't know if it is, I am not an expert but if it **is** a bug then I hope it'll be fixed in the future! <3
