### ISSUE TITLE
Astral Sorcery incompatable

### ISSUE THREAD

**Issue by Thanatosrage97** [Alex-the-666/Ice_and_Fire#2270]
Whenever I try and use this mod with the Astral Sorcery mod the game crashes before it even opens and the launcher just tells me 'somthing went wrong' is there a way to fix this?

**Comment by Danyerious** [comment]
Maybe it's not compatible with the Ice and Fire mod? Is there any other mod that you might think won't work with Astral Sorcery mod? If so, you might need to remove them. :3

**Comment by AlexModGuy** [comment]
cant do nothign with no crash log
