### ISSUE TITLE
Cocktrice spawn issue when disabled

### ISSUE THREAD

**Issue by Josiah957** [Alex-the-666/Ice_and_Fire#2275]
I am playing a modpack with this mod. I have a room with 4 cooked chicken spawners next to my dragon keep. Cockatrice continuously spawn in this chicken room about every 5 minutes. 

I have disabled their spawn, set the tick rate to 2billion and disabled chickens laying rotten eggs. Yet somehow the cockatrice are still spawning.

**Comment by Danyerious** [comment]
Try lowering the tick rate. Maybe it's too high. If this doesn't work then oh well! We tried!
