### ISSUE TITLE
Armor do not render correct

### ISSUE THREAD

**Issue by ElCabron569** [Alex-the-666/Ice_and_Fire#2276]
The textures of the armors are completely bugged, some parts of the armor appear and others don't, how do I fix it? 
![erro armadura](https://user-images.githubusercontent.com/63369724/78823798-ac987180-79b3-11ea-8492-0c9dab9e1198.png)

**Comment by Danyerious** [comment]
Hmm, this might be a (known) bug. Or you just have a mod that changes your character. Check your mods folder! :D If there are any mods that you think might've changed the armor then remove them and... you know the rest. Play, test, blah, blah. If that doesn't work then it might be a bug. I hope I helped! :D

**Comment by Drathonix** [comment]
You likely have Mo' Bends installed. In the mod's config file, disable player animations by changing B:player=true to B:player=false. This will fix the problem but player animations will no longer be active.

This is a problem with Mo' bends not displaying 3D models correctly.

**Comment by ElCabron569** [comment]
@Drathonix i will try it, thnx

**Comment by ElCabron569** [comment]
@Drathonix I tried this solution, and result that the problem was solved, thank you very much :D
