### ISSUE TITLE
Server Crashing when Any player finds a Dragon...

### ISSUE THREAD

**Issue by RexStarGame** [Alex-the-666/Ice_and_Fire#2277]
I created a server since a while and I'm trying to make more harder for players so I added your mod to my modpack and my server but when a player finds any kind of dragon the server crashes and this is one of my logs https://mclo.gs/BrI1FwT

**Comment by Danyerious** [comment]
Hmmm, maybe you have too many mods. Or if it's just your computer then... idk. :PP

**Comment by AlexModGuy** [comment]
>at io.github.xcube16.iseedragons.ISeeDragons.getMethodInHierarchy(ISeeDragons.java:558)

crash caused by the "I See Dragons" mod.

**Comment by RexStarGame** [comment]
thank you so much :D
