### ISSUE TITLE
Dragon armor rendering bug: global rendering?

### ISSUE THREAD

**Issue by Hyxaru** [Alex-the-666/Ice_and_Fire#2278]
I Recently got two dragons. One of them I equiped a (tail)piece of firesteel armor. The other I equiped a (tail)piece of icesteel armor.

Now the initial dragon also renders the icesteel instead of the firesteel. Re-equiping corrects the texture, but causes the other dragon to start rendering the wrong piece.

It seems the game can only render one specific armor texture and applies that to all dragons?

**Comment by Danyerious** [comment]
Yes, this is a common bug that happens when 2 dragons have different armor. This WILL be fixed soon.

**Comment by ClaymanTwinkle** [comment]
This bug has been fixed. #2257

**Comment by AlexModGuy** [comment]
fixed
