### ISSUE TITLE
Disapearing Dragons and Invulnerable Wild Dragons

### ISSUE THREAD

**Issue by PrismaKaito** [Alex-the-666/Ice_and_Fire#2280]
Well Title 
I played on the server and Wantet to attack a Wild fire dragon with my ice dragon 
After pressing attack my dragon disapeared and i was confused then i tried to attack the dragon with my Ice Dragonbone sword but wasnt able to damage it?? like he was not hitable but he killed me 
im very confused and sad that my dragon disapeared i tried it in my single player well there it works fine but in a server this bug occures
i hope it can be fixed :(
(Testet multiple times everytime its happening and wild dragons are ALL invulnerable[not attackable])

**Comment by SirAnanas** [comment]
I have the same problem.
