### ISSUE TITLE
Dragons overspawning

### ISSUE THREAD

**Issue by Moose206** [Alex-the-666/Ice_and_Fire#2286]
I love this mod, though theres this thing that makes it hard to love, and that's the sheer amount of dragons of all types on my world... I once made a world, and i spawned right next to a dragon roost, then i ran away from it, but then it turns out that after 30 seconds of running theres 2 other dragons that see me, i get killed, then i get a massive frame drop, telling me that a stage 4 or 5 dragon came out of its nest, then i get killed again by not one, not two, 3 dragons that came out the same cave, i tried going to the config and turning the spawn rate down, didn't work, made another world and theres even more dragons than the last one right next to my spawn, this is an issue that i think needs to be fixed, please, i have both type of spawnrates in 1 and i still get spammed with dragons.

**Comment by FirebIossom** [comment]
I've had this issue as well but what actually happened here is that you actually turned the spawn rate up by 'lowering' the number as that number dictates the '1 in x' chances of a dragon spawning, 1 in 1 is a guarantee for a dragon spawn as far as I can tell so maybe try something in the thousands?

As for myself I have it at 3600 roost chance and the peace is decent.

**Comment by AlexModGuy** [comment]
fixed

**Comment by Moose206** [comment]
Thank you so much for the info. im gonna try it right away
