### ISSUE TITLE
[SUGGESTION ] Biome Black/Whitelisting 

### ISSUE THREAD

**Issue by Yranic** [Alex-the-666/Ice_and_Fire#2287]
In Early game Dragons often act as spawn killers mostly fire dragons since they can spawn with their nests almost everywhere. I don't want to change how dangerous they are because otherwise they allow you to get powerful items too fast and are to weak late game. Also I don't like making the spawn from 0 too great as it removes the content. Rather I would like an option for structures and mobs to be set on Black/Whitelisted biomes they can't/only spawn in. This would allow the threat of the dragons to be banished to rarer biomes you  need to avoid early game and only enter if your looking for trouble. (fire Dragons -> vulcanic biomes).

**Comment by CitrusHappy** [comment]
the [In Control mod](https://www.curseforge.com/minecraft/mc-mods/in-control) does exactly what you want, given you configure it properly.
