### ISSUE TITLE
RenderModCapes causes Lag

### ISSUE THREAD

**Issue by Flosus** [Alex-the-666/Ice_and_Fire#2289]
Hello everyone,

Im currently playing the MC Eternal Modpack and have a huge amount of lag because if the frequent running GC. After analysing the Client wit Java Mission Control I found that Ice and Fire is causing a lot of exceptions.
The following line is causing 5762 Exceptions / Minute:
https://github.com/Alex-the-666/Ice_and_Fire/blob/1.8.4-1.12.2/src/main/java/com/github/alexthe666/iceandfire/client/render/entity/RenderModCapes.java#L48

The exceptions do not show up in the game log, only in the Mission Control.

![2020-04-13 20_11_27-Greenshot](https://user-images.githubusercontent.com/4223452/79146899-61bb9700-7dc3-11ea-8bee-bf3a3d012621.png)

Minecraft Version: 1.12.2

Ice And Fire Version: 1.8.4

**Comment by sjoosjed** [comment]
I Just began playing MC Eternal today and got down to 1 fps when i started fighting a dragon.
I run a RTX2070, 16gb ddr4 and a i7 8700 3.8ghz, i shouldn't have to much problems so i think it has to do something with fire and ice mod.
