### ISSUE TITLE
{SUGGESTION} Make the new hydra mob tamable 

### ISSUE THREAD

**Issue by Stanley-alt** [Alex-the-666/Ice_and_Fire#2290]
after you kill a hydra there should be a very small change to have it drop a egg and this egg would eventually hatch into a baby hydra that would eventually get more and more heads till it would be fully grown. From what we've seen it is big enough to be rideable so that would be possible as well.Also for people that don't want it to be tameable there should be a config that disables the dropping of those eggs and the tamable version could take every kind of damage not only fire damage

**Comment by AlexModGuy** [comment]
jesus christ no. this isnt a pets mod. the hydra is depicted in fiction and mythology as a solely hostile creature.
