### ISSUE TITLE
Levitating dragon corpses

### ISSUE THREAD

**Issue by ThatOnePersonWho** [Alex-the-666/Ice_and_Fire#2292]
killing a flying dragon caused it to do... _this_
![2020-04-14_10 24 56](https://user-images.githubusercontent.com/60660936/79208740-5ce5fa00-7e3a-11ea-9a34-a7ffaee6f88b.png)

**Comment by Danyerious** [comment]
This happened to me a few weeks ago. I'm not sure if it's a bug or not but if it is then I'm sure it'll be fixed within the next update!
