### ISSUE TITLE
Hydra lopped off head blood particles when petrified

### ISSUE THREAD

**Issue by kodabeer** [Alex-the-666/Ice_and_Fire#2296]
I was testing if dread staff would target it whilst it's petrified, and it did so twice and dealt damage that it regenerated, but what's weird is that it's now showing particles of 'blood' where a head would've been lopped off. 
![2020-04-14_16 26 47](https://user-images.githubusercontent.com/53926065/79270881-e7dfe800-7e6c-11ea-9aac-fa4819602ba9.png)

**Comment by AlexModGuy** [comment]
fixed. redownload mod
