### ISSUE TITLE
Dragon corpses still hold enemies

### ISSUE THREAD

**Issue by Zenn8** [Alex-the-666/Ice_and_Fire#2300]
When a dragon gets killed and they had a mob in their mouth this mob will stay there. I've only tested it with fire dragons and dread knights so far.
![2020-04-14_22 28 19](https://user-images.githubusercontent.com/63676510/79272531-dfee6b00-7ea1-11ea-8335-3b4000b7a0e4.png)

**Comment by slowiu06** [comment]
Usually the same thing happens to me when I kill a dragon while in its mouth. I have to press shift to move.
