### ISSUE TITLE
Stone Mob Bugginess

### ISSUE THREAD

**Issue by QWsertsDev** [Alex-the-666/Ice_and_Fire#2301]
I turned various mobs into stone and then destroyed them with a pickaxe in creative, bugginess ensued:

-Dread mobs eyes remain after their statue is broken
-Hydra receives buggy texture (Probably fixed alongside the invis issues like #2294 )

Pictures:
![Screenshot (102)](https://user-images.githubusercontent.com/34694897/79272713-d6e4a600-7e6f-11ea-9348-fae4e3317edd.png)
![Screenshot (103)](https://user-images.githubusercontent.com/34694897/79272716-d77d3c80-7e6f-11ea-992b-3d3b45bc7635.png)
![Screenshot (104)](https://user-images.githubusercontent.com/34694897/79272718-d8ae6980-7e6f-11ea-9959-a4e311add2d5.png)
![Screenshot (105)](https://user-images.githubusercontent.com/34694897/79272721-d8ae6980-7e6f-11ea-871d-d911a4783760.png)

**Comment by AlexModGuy** [comment]
fixed
