### ISSUE TITLE
Tamed ridable dragons from last mod version grabs player instead of allowing mounting

### ISSUE THREAD

**Issue by pillowasebandit** [Alex-the-666/Ice_and_Fire#2302]
Tested with dragons from previous mod version, no bite damage itself, but does damage from fall after releasing me from its mouth.

Edit: Tested with freshly spawned in dragon in current version, I can ride those no problem.
Older version dragons need to be retamed in order to ride them again.

**Comment by Traeesen** [comment]
How does one "retame" a dragon?

**Comment by pillowasebandit** [comment]
> How does one "retame" a dragon?

You need to spawn in creative dragon meal. Alex is aware of this.

**Comment by Traeesen** [comment]
Oh nice! I can get my dragon back then. Thank you!
