### ISSUE TITLE
Ice Dragons Death Visual Glitch

### ISSUE THREAD

**Issue by kodabeer** [Alex-the-666/Ice_and_Fire#2304]
Ice dragons sometimes don't look dead when they die and seem to freeze in place. Happens when killed by fire/lava

**Comment by Jceratops0** [comment]
I finnaly made an account, and come to add a few things. What seems to happen is that the majority of a dragons body is locked in it's flight animation, excluding it's head. I had one that looked like it should be flying but it was truly dead, after mostly harvesting the body. The final thing I noticed was that these locked(?) dragons jittered quite violently, maybe this was the ai still trying to fly? The best way I know how to replicate this is the spawn a sh** load of ice dragons inside the nether. If they are flying and die of fire damage you should see this glitch. It may even be replicated by taking a fire dragonsteel sword and slapping a flying ice dragon until death in the air.

**Comment by Jceratops0** [comment]
![unknown-49](https://user-images.githubusercontent.com/63693753/79296494-96098300-7ea9-11ea-8489-dc5c6068d0a7.png)
![unknown-23](https://user-images.githubusercontent.com/63693753/79296498-99047380-7ea9-11ea-843f-a21777847323.png)
