### ISSUE TITLE
Myrmex Hive BoP

### ISSUE THREAD

**Issue by FedExManGuy** [Alex-the-666/Ice_and_Fire#2310]
So me and my friends added the newest version of Ice and Fire to our server and it worked fine. Until it didn't. The server started to crash and we later found out due to someone else that it was being caused by an issue of the Myrmex Hives spawning in Biomes O Plenty biomes. 
[crash-2020-04-14_19.55.25-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/4478379/crash-2020-04-14_19.55.25-server.txt)

**Comment by AlexModGuy** [comment]
>	at biomesoplenty.common.world.ChunkGeneratorOverworldBOP.func_185931_b(ChunkGeneratorOverworldBOP.java:570)

the bug is on biomes o plenty's side, not ice and fire. report it to them.
