### ISSUE TITLE
Dragons Are transgender

### ISSUE THREAD

**Issue by Moowithhair** [Alex-the-666/Ice_and_Fire#2311]
So I've been having a problem with my dragons in both single and multiplayer in which one or two dragons change their texture to that of the opposite gender and can not bread. Idk if other people have this problem, but I hope this gets fixed in the next update

**Comment by yrsegal** [comment]
Ice and Fire says trans rights

**Comment by doxxerx** [comment]
yeah dragons do that in mythology they do what ever they want no lower mortal can tell them what to do
