### ISSUE TITLE
Dread Spawner Bug

### ISSUE THREAD

**Issue by kodabeer** [Alex-the-666/Ice_and_Fire#2315]
Posting this from the discord where it's slowly going to be getting buried, seems like there's pig spawners in mausoleum.
![DreadSpawnerBug](https://user-images.githubusercontent.com/53926065/79298403-09fa5a00-7eaf-11ea-91f7-c097b20e6d3c.png)

**Comment by jinks** [comment]
This might be an issue with the spawners reverting to a "vanilla" state after one spawn. (Pig spawners are the default spawner if it has no data iirc.)

https://github.com/Ellpeck/ActuallyAdditions/issues/162 might have some insight.
