### ISSUE TITLE
Ice dragon flying buggy

### ISSUE THREAD

**Issue by jaesunn** [Alex-the-666/Ice_and_Fire#2316]
When flying on an ice dragon, when you turn it like freaks out
https://gyazo.com/d7f753e119ff4c775ddb8fa86a32a386

**Comment by kodabeer** [comment]
I see no issue here xd

**Comment by jaesunn** [comment]
do you not see the way it turns... the fire dragon doesn't do that you can see how smooth the fire dragon is compared to the ice dragon
https://gyazo.com/851a5d82d66abf1616f7bdf6b0f0b347

**Comment by Jceratops0** [comment]
Hmm. I rode an ice dragon no prob earlier today with it being smooth. It could be a conflict with another mod of your running more
