### ISSUE TITLE
Dragons flying on the ground

### ISSUE THREAD

**Issue by HarroldSaxon** [Alex-the-666/Ice_and_Fire#2319]
For some reason, dragons are reluctant to sore through the sky, staying really close to the ground when airborne.
![2020-04-15_02 23 40](https://user-images.githubusercontent.com/16321509/79314683-9f094d00-7ec7-11ea-8038-841be6169222.png)
![2020-04-15_02 23 51](https://user-images.githubusercontent.com/16321509/79314703-a597c480-7ec7-11ea-99c2-827654f8d161.png)
![2020-04-15_02 26 37](https://user-images.githubusercontent.com/16321509/79314717-ab8da580-7ec7-11ea-81de-c2ba554d31da.png)
![2020-04-15_02 26 39](https://user-images.githubusercontent.com/16321509/79314791-c9f3a100-7ec7-11ea-89d6-e29bb38a3219.png)

As a side note, they also move in really strange ways when in flight, and sometimes breath fire out of strange places, like down from the body or out the rear.

![2020-04-15_02 26 25](https://user-images.githubusercontent.com/16321509/79315267-51d9ab00-7ec8-11ea-89dc-d6d9f221d616.png)

**Comment by Reshy** [comment]
I noticed this too, I wonder if it has to do with the height ceiling?

**Comment by HarroldSaxon** [comment]
I thought of that too. I set it to 255, but noticed no difference.  :( Maybe they wanted players not to need bows to fight dragons? doesn't make much sense to me though.
