### ISSUE TITLE
Can't ride dragon in new update

### ISSUE THREAD

**Issue by Traeesen** [Alex-the-666/Ice_and_Fire#2322]
Whenever i try to ride my dragon instead of putting me on it's back it puts me in it's mouth and deals me damage. Nothing seems to fix it.
Setting the dragon on escort makes the dragon aggresively bump into me.
It also does not attack anything that i attack or anything that attacks me.
I don't know how wandering is supposed to work on tamed dragons, but it seems to wander, it breaks blocks when wandering though, which i assume is not something a tamed dragon would do when wandering.
I did not get a second dragon egg so i cannot see if it's like that on every dragon.
I don't think i did anything weird to the dragon, well, excluding that one time i used an item from another mod which lets me ride any mob without being able to control it on the dragon w.hich actually let me ride it normally on stage 1. That shouldn't have done anything to it though.

I miss my dragon, but I can wait until it gets fixed I suppose.

**Comment by Ikorah98** [comment]
The same thing is happening to me was working perfectly fine before I installed the new update so this is definitely new.

**Comment by ghost** [comment]
To me the same thing happens to me

**Comment by Traeesen** [comment]
Update with the new resources I've gotten:
New dragons work just fine.
Glitched dragon will not fuel dragon forges.

I don't have enough patience to go in the older version, get an ice dragon, then change to the recent version, so this could very well be fire dragon specific, although i doubt it.

**Comment by xMrCaosx** [comment]
A person on Discord told me, the dragons you adopt on the versión 1.8.4 are now like Wild Dragons. The way to fix this is using the Dragon Meal Creative to tamed and become on your side again the Dragon.

I didn't test if that true or not, but she told me is the only way right now for fix this problem if  you want your dragon on your side with you again.

I will check if that work in 3 hours or more, so.. if someone can confirm is working i be gratefull :)

**Comment by Traeesen** [comment]
It works! Thank you.

**Comment by Traeesen** [comment]
Well, we've found a temporary fix and I'm pretty sure there's no more info to give on the problem other than to check if this is fire dragon specific, so I'll close the issue.
