### ISSUE TITLE
Tamed Dragon attacks friend

### ISSUE THREAD

**Issue by PrismaKaito** [Alex-the-666/Ice_and_Fire#2326]
I have a tamed ice dragon and She Attacks my friend even if he reloggs (Normaly resets it) 
if this is a known bug if yes ignore this

**Comment by tkerkering** [comment]
We also encountered this issue. Also you're not able to ride a dragon, it tries to eat you instead. Version 1.9.0.

**Comment by smoothuk** [comment]
Try retaming it by feeding it a Creative Dragon Meal.  Worth a shot.

**Comment by AlexModGuy** [comment]
fixed
