### ISSUE TITLE
1.12.2 Crafttweaker Still not Working

### ISSUE THREAD

**Issue by SgtRalphie** [Alex-the-666/Ice_and_Fire#2327]
I looked at what I was given and pasted it in, but I am still not getting it to work

import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;
import mods.jei.JEI;
mods.iceandfire.recipes.removeFireDragonRecipe(<iceandfire:dragonsteel_fire_ingot>);
mods.iceandfire.recipes.removeIceDragonRecipe(<iceandfire:dragonsteel_ice_ingot>);
mods.iceandfire.recipes.addFireDragonForgeRecipe
	(<betterwithmods:material:14>,<iceandfire:fire_dragon_blood>,<iceandfire:dragonsteel_fire_ingot>);
mods.iceandfire.recipes.addIceDragonForgeRecipe
	(<betterwithmods:material:14>,<iceandfire:ice_dragon_blood>,<iceandfire:dragonsteel_ice_ingot>);

Using this I get two different errors, one with the removal on the recipes saying that it has "no such static member" and another error saying "Truncated class file"

**Comment by BeepoWuff** [comment]
For anyone that might stumble across this there's a couple of issues that were causing the errors:

1. The previous wiki example for removing recipes was incorrect in providing `removeFireDragonRecipe` and `removeIceDragonRecipe` where it should have been `removeFireDragonForgeRecipe` and `removeIceDragonForgeRecipe` respectively. This would have been causing the *"no such static member"* error.
2. In CraftTweaker scripts all item names *must* be surrounded with `<` and `>`. For example the first removal would have been along the lines of `... removeFireDragonForgeRecipe(<iceandfire:dragonsteel_fire_ingot>);`. The easiest way to get item names in this format is to run `/ct hand` while holding the item in game then clicking what's output to chat :P
