### ISSUE TITLE
Entities Interacting with Stone Statues

### ISSUE THREAD

**Issue by MasterOfTheCats** [Alex-the-666/Ice_and_Fire#2328]
I've been playing a bit with the mod in creative - as I always do because I'm completely useless when it comes to survival - and I've noticed some weird behaviors when it came to stone statues, e.g. zombies attacking villager statues, wolves attacking skeleton statues, etc. This is an issue that should probably be fixed.
Also, just as a sidenote - id a hydra is turned to stone, its heads disappear, and only the statue of the body remains. This is just plain weird, so I assume it was not intended.

![2020-04-16_01 09 50](https://user-images.githubusercontent.com/52366568/79393977-177f1500-7f7f-11ea-9fef-5ab648cf1150.png)

![2020-04-16_01 00 09](https://user-images.githubusercontent.com/52366568/79393377-e3572480-7f7d-11ea-879a-651fb65c5058.png)

**Comment by Kodabeeer** [comment]
Duplicate post

**Comment by AlexModGuy** [comment]
dupe
