### ISSUE TITLE
Potential Memory Leak?

### ISSUE THREAD

**Issue by Aruganis** [Alex-the-666/Ice_and_Fire#233]
Alright, so on our server, several players have mentioned their game constantly freezing after awhile (including myself, and another staff member). It seems to be from Minecraft/Java eating up all of the Physical Memory possible.
We've done several tests, both on the server and singleplayer, to make it wasn't another mod, plugin, or just our computers, and we believe it's stemming from the Dragons themselves.
The issues did not occur until after Ice and Fire was added, and it seems to accelerate when dragons are nearby.
The amount of time it takes for the issue occurs seems to very, Scidia, the other staff member, recently had it happen with in about 10-15 minutes of logging in. It normally takes me about half an hour before it becomes an issue, and a friend seems to have gone several hours before it occurred.

**Comment by Sunconure11** [comment]
Run WarmRoast on the mod or equivalent, and post the results here.

https://github.com/sk89q/WarmRoast

**Comment by Aruganis** [comment]
I'll admit, I am not a smart person.
Reading through the instructions for WarmRoast completely and utterly baffled me.
As for the three mods, we have BetterFPS and Surge already, but was not aware of FoamFix. I'll give it a try.

**Comment by LeonMercer** [comment]
im also suffering from this issue, its really bad considering how good the mod is. i have 6 gigs allocated to minecraft and it still happens...

**Comment by darthvader45** [comment]
Someone has just narrowed down a possible cause for this:  Dragons using breath attacks on those not performing hostile actions (breaking gold piles, opening chests, attacking the dragon).  It constantly checks around it for mobs to attack when it should only check for those mobs performing hostile actions.  Would greatly reduce the memory leak as well as any lag and/or crashes.

**Comment by IgiariValkyr** [comment]
I'm suffering this issue on the newest 1.12 version as well. I'm not necroing this for no reason.

**Comment by darthvader45** [comment]
Really?  Let's see your modlist.  I use the latest 1.12.2 and no lag like this so far.

**Comment by EPIICTHUNDERCAT** [comment]
memory leaks are occuring in our pack as well, however we also have lycanites which cant help

**Comment by darthvader45** [comment]
Have you tried removing Lycanite's Mobs?  Might help to isolate your issue.

**Comment by EPIICTHUNDERCAT** [comment]
well duh, i was just pointing out a common factor and that is that we all have ice and fire...play with it a lil more, and tell me if you start experiencing issues

**Comment by Routhinator** [comment]
Adding to this thread, my research into memory leaks caused when this mod is in use (which also seems to be accelerated by this mods armor)  have lead to suspicion of the LLibrary mod this depends on and everything is documented here:

https://github.com/iLexiconn/LLibrary/issues/69 

It my be LLibrary, but it may also be this mods use of the hash map. Hopefully the LLibrary devs will come up with something soon. Our server lasts about 4 hours before needing a reboot due to a full heap, and if someone puts on the armor from ice and fire, the time drops to 1 hour between restarts.

**Comment by darthvader45** [comment]
That is definitely a concern, though since I'm currently running a zombie
apocalypse modpack of my own, I'm fine for now.  I'll check later when I
reach a point where I can focus on my medieval survival.

**Comment by Sunconure11** [comment]
@alexthe666

**Comment by Routhinator** [comment]
For the record it seems to be the Bronze Dragon armor set that accelerates the leak.

**Comment by darthvader45** [comment]
Huh, thought I saw something when wearing the red dragon set.

Golden rule in Minecraft: Never dig straight down.

**Comment by Routhinator** [comment]
Ok, another discovery, loading an area with charred grass (dragon is no longer there) fills the heap almost instantly and the server dies.

**Comment by darthvader45** [comment]
Yowch, that has to hurt progress.

Golden rule in Minecraft: Never dig straight down.

**Comment by Routhinator** [comment]
Release  1.7.13 of LLibrary reportedly fixes this leak. Needs testing. We removed this mod as we were getting corrupted chunks with all the restarts so we cannot test immediately.

**Comment by AlexModGuy** [comment]
^
