### ISSUE TITLE
Can't ride tamed dragon

### ISSUE THREAD

**Issue by MollyPerl** [Alex-the-666/Ice_and_Fire#2335]
I have a tamed dragon that is above stage 3 and when I click it, the dragon GUI keeps popping up and I can't ride it. This is only happening to me in the 1.9.0 update. Thank you for reading this.

**Comment by Traeesen** [comment]
Same thing happened to me! But it quickly went away when I shifted and unshifted. I'll assume you already tried that.
My best guess is that the game thinks you're shifting while you aren't.

**Comment by Pyrorapto** [comment]
same but no matter what I do I cant ride my dragon
