### ISSUE TITLE
[question]how are hydra heads handled on the server side?

### ISSUE THREAD

**Issue by Jackiecrazy** [Alex-the-666/Ice_and_Fire#2336]
I'm trying to fix some bugs in my mod that arise from attacking I&F entities. In particular, I use the server world to get entities from ID at one point so I may attack them with weapons that have longer reach, but the server world returns null for the ID of a hydra head. What would be the "correct" way to get a part in a packet? Or do I have to add explicit compatibility to trace it back to the base entity on the client first?

**Comment by AlexModGuy** [comment]
you'd have to trace it back like [the ice and fire code ](https://github.com/Alex-the-666/Ice_and_Fire/blob/1.8.4-1.12.2/src/main/java/com/github/alexthe666/iceandfire/message/MessagePlayerHitMultipart.java) does.
