### ISSUE TITLE
Hydra wont spawn

### ISSUE THREAD

**Issue by Ktendium** [Alex-the-666/Ice_and_Fire#2338]
![image](https://user-images.githubusercontent.com/49605142/79524710-8efa9480-80a4-11ea-9e16-3e2f86490359.png)
Im Unable to summon the hydra or use the egg at all. I have been able to spawn a cockatrice and a dragon but not the Hydra.

**Comment by AlexModGuy** [comment]
its tag is if_hydra in order to avoid errors with twighlight forest.
