### ISSUE TITLE
Tamed dragons wearing dragon armor cause massive FPS drops.

### ISSUE THREAD

**Issue by ShadowLink2016** [Alex-the-666/Ice_and_Fire#2341]
Not sure if this is an issue for just me, but I've tested this with both all the mods in a custom modpack I put together for me and a few friends, and just the Ice and Fire mod, version 1.9.0, Llibrary, version 1.7.19, and Optifine installed. The title pretty much says it all: In both instances, a tamed dragon wearing dragon armor causes my FPS to drop by about 50. When the armor is removed from the dragon, my FPS increases drastically. I'll post screenshots and even a video if necessary. (As far as I can tell, this never occurred for me before the 1.9.0 update. I may have just not noticed it before the update). 

![Dragon with armor](https://user-images.githubusercontent.com/21695110/79616970-5c689000-80d4-11ea-93b2-3a2c4898e0f5.png)

![Dragon without armor](https://user-images.githubusercontent.com/21695110/79617004-74401400-80d4-11ea-9edc-f509c8f00326.png)

Edit: I've noticed that this same issue was occurring back in August 2019 for someone else, and it was closed. Not sure if this issue has resurfaced, or if its just my computer being stupid or something.

**Comment by slowiu06** [comment]
I have the same problem. When there is dragon in armour near me my fps are reduced by ~70%

**Comment by ZeSethis** [comment]
I'm experiencing a similar issue. Major loss of framerate and _outrageous_ RAM usage. Equipping armor rips through the dedicated memory like it's nothing. Seems to happen with all armor types. Using the latest version of the mod from Forge. Here's two examples of the memory jump with armor being put on and taken off:
[https://i.gyazo.com/ce48a114f73b6377f3bab45a3549d68a.gif](url)
[https://i.gyazo.com/66adb9be7158ba8ae52ff05c04c4a258.mp4](url)

**Comment by AdityaGupta1** [comment]
Can confirm, same is happening to me. Banners don't seem to affect it at all, it's just the armor that causes FPS drops.
