### ISSUE TITLE
Problem with download

### ISSUE THREAD

**Issue by fractaltorrent** [Alex-the-666/Ice_and_Fire#2343]
I am trying to add Ice and Fire to a pre-existing multiplayer server. I successfully installed it and went on the server but when I look at JEI, I don't see the complete Ice and Fire mod, just spawn eggs. What should I do?

**Comment by kodabeer** [comment]
Did you only install it client side? or did you install it server side

**Comment by fractaltorrent** [comment]
Ice and Fire was install on both the client side and the server side.

**Comment by fractaltorrent** [comment]
Nevermind- figured it out!
