### ISSUE TITLE
Problems with getting on the dragon

### ISSUE THREAD

**Issue by slowiu06** [Alex-the-666/Ice_and_Fire#2346]
Insted of mounting on my dragon I'm opening its inventory (ofc without pressed shift). Sometimes I get in without this problem but it is rare.

**Comment by Orlha** [comment]
Have problem with mounting too, but instead of mounting on my dragon I somehow end up in his mouth all the time proceeding to getting damage. Can't mount anymore.
It worked with iceandfire-1.8.4.jar tho

**Comment by slowiu06** [comment]
You have a different problem, it was described in other posts. My is connected with dragon hatched after update (and those repaired with Creative Dragon Meal), which is working fine, but clicking RMB (without shift) on dragon works same way like with shift. I just realized that when I firstly use shift + RMB, then close inventory and then use RMB - this will allow me to mount on dragon at all times. My suggestion is changing way to enter dragon's inventory (e.g with staff).

**Comment by AlexModGuy** [comment]
fixed
