### ISSUE TITLE
Troll Weapon Glitch

### ISSUE THREAD

**Issue by LordVanidas** [Alex-the-666/Ice_and_Fire#2348]
I'm having an issue where trolls turned to stone will glitch out. When you try to mine them, the model disappears, but their weapon spawns in and starts floating and spinning (very slowly) in midair. You can only break them at certain angles, and if you reload the chunks or relog, the troll statues will respawn.

Screenshots:
![Troll 1](https://user-images.githubusercontent.com/41840874/79781331-53153880-830b-11ea-9fe8-f5d41fb25ede.png)
![Troll 2](https://user-images.githubusercontent.com/41840874/79781337-54466580-830b-11ea-8a3d-19ed4463b57a.png)

**Comment by kittyacelia** [comment]
![Untitled](https://user-images.githubusercontent.com/64457253/80451079-f27c9180-88f0-11ea-9fa4-cac082c512be.png)

Same issue

**Comment by fkshitanoiyingcrap** [comment]
Can confirm, but the weapon doesn't spin for me.

**Comment by GamertechAU** [comment]
Not getting the spinning, but the weapons stay floating and move as if the troll was alive and idle.

Version: 1.12.2-1.9.1

**Comment by AlexModGuy** [comment]
fixed
