### ISSUE TITLE
The mod doesn't work on server properly.

### ISSUE THREAD

**Issue by AConfusedMan** [Alex-the-666/Ice_and_Fire#2349]
The mod is required for someone to join into the server; however none of the items or mobs from the mod actually work. The spawn eggs show their colorations but don't actually work correctly and the crafting recipes don't work. The mod does work perfectly outside of the server though.

**Comment by Xorbah** [comment]
That's something on your end, not the mods. It works perfectly fine on
servers.

**Comment by AConfusedMan** [comment]
I just wonder why it isn't working for me. It's like the mod is there but nothing from it works on the server.

**Comment by ChemBench** [comment]
> The mod is required for someone to join into the server; however none of the items or mobs from the mod actually work. The spawn eggs show their colorations but don't actually work correctly and the crafting recipes don't work. The mod does work perfectly outside of the server though.

yea im getting the same thing when i make a sever
