### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by Moomaster** [Alex-the-666/Ice_and_Fire#2358]
My server crashes constantly whenever I interact with a dragon or cyclops, and even sometimes when I simply get too near one. Is there any solution to this?

**Comment by AlexModGuy** [comment]
post the crashlog otherwise we can;t do anything.

**Comment by SP4RT49** [comment]
When a player touch a dragon with an arrow, or sword, or any item, the server shutdown instantly

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LibLoader (# LibLoader.jar)
  CreativePatchingLoader (CreativeCore_v1.9.74_mc1.12.2.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.9-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.0.2.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.27_mc1.12.2.jar)
  MMFMLCorePlugin (MultiMine-1.12.2.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  CoreMod (TickProfiler-1.12-0.0.7.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  LoadingPlugin (Reskillable-1.12.2-1.13.0.jar)
  TNTUtilities Core (tnt_utilities-mc1.12-1.2.3.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.4.25.0-build.0428.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 26/04/20 16:40
Description: Ticking entity

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/culling/ICamera
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at io.github.xcube16.iseedragons.ISeeDragons.getMethodInHierarchy(ISeeDragons.java:558)
	at io.github.xcube16.iseedragons.ISeeDragons.getMethodInHierarchy(ISeeDragons.java:561)
	at io.github.xcube16.iseedragons.ISeeDragons.livingEntityAttacked(ISeeDragons.java:431)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_533_ISeeDragons_livingEntityAttacked_LivingAttackEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:585)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:857)
	at net.minecraft.entity.passive.EntityAnimal.func_70097_a(SourceFile:66)
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70097_a(EntityDragonBase.java:1457)
	at com.lycanitesmobs.core.entity.EntityProjectileBase.func_70184_a(EntityProjectileBase.java:241)
	at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(EntityThrowable.java:249)
	at com.lycanitesmobs.core.entity.EntityProjectileBase.func_70071_h_(EntityProjectileBase.java:117)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.culling.ICamera
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 26 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at io.github.xcube16.iseedragons.ISeeDragons.getMethodInHierarchy(ISeeDragons.java:558)
	at io.github.xcube16.iseedragons.ISeeDragons.getMethodInHierarchy(ISeeDragons.java:561)
	at io.github.xcube16.iseedragons.ISeeDragons.livingEntityAttacked(ISeeDragons.java:431)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_533_ISeeDragons_livingEntityAttacked_LivingAttackEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:585)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:857)
	at net.minecraft.entity.passive.EntityAnimal.func_70097_a(SourceFile:66)
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70097_a(EntityDragonBase.java:1457)
	at com.lycanitesmobs.core.entity.EntityProjectileBase.func_70184_a(EntityProjectileBase.java:241)
	at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(EntityThrowable.java:249)
	at com.lycanitesmobs.core.entity.EntityProjectileBase.func_70071_h_(EntityProjectileBase.java:117)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: lycanitesmobs:aquapulse (com.lycanitesmobs.core.entity.projectile.EntityAquaPulse)
	Entity ID: 145
	Entity Name: entity.aquapulse.name
	Entity's Exact location: 2761,55, 81,45, 3419,88
	Entity's Block location: World: (2761,81,3419), Chunk: (at 9,5,11 in 172,213; contains blocks 2752,0,3408 to 2767,255,3423), Region: (5,6; contains chunks 160,192 to 191,223, blocks 2560,0,3072 to 3071,255,3583)
	Entity's Momentum: 0,19, -0,76, 0,11
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['Akou_Odin'/115, l='world', x=2764,12, y=76,63, z=3421,96]]
	Chunk stats: ServerChunkCache: 459 Drop: 0
	Level seed: -8026627287281420630
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-184,64,232), Chunk: (at 8,4,8 in -12,14; contains blocks -192,0,224 to -177,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 11887037 game time, 13036422 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 12519 (now: false), thunder time: 72816 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 5.4.14-mtxserv
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3358205000 bytes (3202 MB) / 4294967296 bytes (4096 MB) up to 25769803776 bytes (24576 MB)
	JVM Flags: 23 total; -Xms4096M -Xmx24576M -XX:MetaspaceSize=64M -XX:MaxMetaspaceSize=512M -XX:+UseFastAccessorMethods -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:MaxGCPauseMillis=100 -XX:+ParallelRefProcEnabled -XX:ParallelGCThreads=4 -XX:ConcGCThreads=1 -XX:+DisableExplicitGC -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:InitiatingHeapOccupancyPercent=30 -XX:G1MixedGCLiveThresholdPercent=50 -XX:G1HeapWastePercent=2 -XX:G1ReservePercent=2 -XX:UseSSE=4 -XX:+UseNUMA
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 113 mods loaded, 113 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                          | Version              | Source                                            | Signature                                |
	|:------ |:--------------------------- |:-------------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                   | 1.12.2               | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp                         | 9.42                 | minecraft.jar                                     | None                                     |
	| LCHIJA | FML                         | 8.0.99.99            | minecraft_server.jar                              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                       | 14.23.5.2838         | minecraft_server.jar                              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy           | 1.0.0                | minecraft.jar                                     | None                                     |
	| LCHIJA | itemphysic                  | 1.4.0                | minecraft.jar                                     | None                                     |
	| LCHIJA | ivtoolkit                   | 1.3.3-1.12           | minecraft.jar                                     | None                                     |
	| LCHIJA | foamfixcore                 | 7.7.4                | minecraft.jar                                     | None                                     |
	| LCHIJA | tnt_utilities_core          | 1.2.3                | minecraft.jar                                     | None                                     |
	| LCHIJA | forgeendertech              | 1.12.2-4.4.25.0      | ForgeEndertech-1.12.2-4.4.25.0-build.0428.jar     | None                                     |
	| LCHIJA | adhooks                     | 1.12.2-3.2.2.0       | AdHooks-1.12.2-3.2.2.0-build.0220.jar             | None                                     |
	| LCHIJA | advanced-fishing            | 1.3.3                | Advanced-Fishing-1.12.2-1.3.3.jar                 | None                                     |
	| LCHIJA | alcatrazcore                | 1.0.4                | alcatrazcore-1.0.4.jar                            | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LCHIJA | antiqueatlas                | 4.6.3                | antiqueatlas-1.12.2-4.6.3.jar                     | None                                     |
	| LCHIJA | anvilpatch                  | 1.0.0                | anvilpatch-1.0.0.jar                              | None                                     |
	| LCHIJA | aquaculture                 | 1.6.8                | Aquaculture-1.12.2-1.6.8.jar                      | None                                     |
	| LCHIJA | carrots                     | 1.0.0b1              | carrotslib-mc1.12.2-1.0.0b1.jar                   | None                                     |
	| LCHIJA | armorunder                  | 1.0.0                | armorunder-mc1.12.2-1.0.0.jar                     | None                                     |
	| LCHIJA | autoreglib                  | 1.3-32               | AutoRegLib-1.3-32.jar                             | None                                     |
	| LCHIJA | bacodifficulty              | 1.0.3                | BacoDifficulty-1.0.3.jar                          | None                                     |
	| LCHIJA | battletowers                | 1.6.5                | BattleTowers-1.12.2.jar                           | None                                     |
	| LCHIJA | baubles                     | 1.5.2                | Baubles-1.12-1.5.2.jar                            | None                                     |
	| LCHIJA | mujmajnkraftsbettersurvival | 1.4.1                | better_survival-1.4.1.jar                         | None                                     |
	| LCHIJA | bettercombatmod             | 1.5.6                | BetterCombat-1.12.2-1.5.6.jar                     | None                                     |
	| LCHIJA | bloodmoon                   | 1.5.3                | Bloodmoon-MC1.12.2-1.5.3.jar                      | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | bnbgaminglib                | 2.17.6               | BNBGamingLib-1.12.2-2.17.6.jar                    | None                                     |
	| LCHIJA | bountifulbaubles            | 0.0.1                | Bountiful Baubles-1.12.2-0.1.4.jar                | None                                     |
	| LCHIJA | campfire                    | 1.2                  | campfire-1.12-v1.2.jar                            | None                                     |
	| LCHIJA | carryon                     | 1.12.3               | CarryOn MC1.12.2 v1.12.3.jar                      | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCHIJA | toughasnails                | 3.1.0.141            | ToughAsNails-1.12.2-3.1.0.141-universal.jar       | None                                     |
	| LCHIJA | comforts                    | 1.4.1.2              | comforts-1.12.2-1.4.1.2.jar                       | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | reskillable                 | 1.12.2-1.13.0        | Reskillable-1.12.2-1.13.0.jar                     | None                                     |
	| LCHIJA | compatskills                | 1.12.2-1.17.0        | CompatSkills-1.12.2-1.17.0.jar                    | None                                     |
	| LCHIJA | coralreef                   | 2.0                  | CoralReef-2.5-1.12.2.jar                          | None                                     |
	| LCHIJA | wearablebackpacks           | 3.1.4                | WearableBackpacks-1.12.2-3.1.4.jar                | None                                     |
	| LCHIJA | corpsecomplex               | 1.0.6                | corpsecomplex-1.12.2-1.0.6.jar                    | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | craftablechainmail          | 1.0                  | craftablechainmail-1.0.jar                        | None                                     |
	| LCHIJA | craftablehorsearmour        | 1.3                  | CraftableHorseArmour-1.3.0-1.12.jar               | None                                     |
	| LCHIJA | craftingstation             | @VERSION@            | craftingstation-0.1.7b.jar                        | None                                     |
	| LCHIJA | crafttweaker                | 4.1.19               | CraftTweaker2-1.12-4.1.19.jar                     | None                                     |
	| LCHIJA | jei                         | 4.15.0.291           | jei_1.12.2-4.15.0.291.jar                         | None                                     |
	| LCHIJA | crafttweakerjei             | 2.0.3                | CraftTweaker2-1.12-4.1.19.jar                     | None                                     |
	| LCHIJA | creativecore                | 1.9.9                | CreativeCore_v1.9.74_mc1.12.2.jar                 | None                                     |
	| LCHIJA | defiledlands                | 1.4.3                | defiledlands-1.12.2-1.4.3.jar                     | None                                     |
	| LCHIJA | disenchanter                | 1.6                  | disenchanter-[1.12]1.6.jar                        | None                                     |
	| LCHIJA | dldungeonsjbg               | 1.12.10              | DoomlikeDungeons-1.12.10-MC1.12.2.jar             | None                                     |
	| LCHIJA | dynamictrees                | 1.12.2-0.9.6         | DynamicTrees-1.12.2-0.9.6.jar                     | None                                     |
	| LCHIJA | traverse                    | 1.6.0                | Traverse-1.12.2-1.6.0-69.jar                      | None                                     |
	| LCHIJA | dttraverse                  | 1.5                  | dttraverse-1.5.jar                                | None                                     |
	| LCHIJA | sereneseasons               | 1.2.18               | SereneSeasons-1.12.2-1.2.18-universal.jar         | None                                     |
	| LCHIJA | orelib                      | 3.6.0.1              | OreLib-1.12.2-3.6.0.1.jar                         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround                   | 3.6.0.2              | DynamicSurroundings-1.12.2-3.6.0.2.jar            | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | familiarfauna               | 1.0.11               | FamiliarFauna-1.12.2-1.0.11.jar                   | None                                     |
	| LCHIJA | firstaid                    | 1.6.12               | firstaid-1.6.12.jar                               | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| LCHIJA | foamfix                     | 0.10.9-1.12.2        | foamfix-0.10.9-1.12.2.jar                         | None                                     |
	| LCHIJA | foodexpansion               | 1.3                  | FoodExpansion1.3.3-1.12.2.jar                     | None                                     |
	| LCHIJA | forgelin                    | 1.8.4                | Forgelin-1.8.4.jar                                | None                                     |
	| LCHIJA | tschipplib                  | 1.1.3                | TschippLib MC1.12.2 v1.1.3.jar                    | None                                     |
	| LCHIJA | forgottenitems              | 1.2.1                | ForgottenItems+MC1.12.2+v1.2.1.jar                | None                                     |
	| LCHIJA | friendlyendermite           | 1.0                  | FriendlyEndermite_v1.0.1_mc1.12.2.jar             | None                                     |
	| LCHIJA | globalgamerules             | 2.2                  | GlobalGameRules-1.12.2-2.2.7.jar                  | None                                     |
	| LCHIJA | grapplemod                  | 1.12.2-v11.1         | grapplemod-v11.1-1.12.2.jar                       | None                                     |
	| LCHIJA | llibrary                    | 1.7.19               | llibrary-1.7.19-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire                  | 1.9.1                | iceandfire-1.9.1-1.12.2.jar                       | None                                     |
	| LCHIJA | infernalmobs                | 1.7.6                | InfernalMobs-1.12.2.jar                           | None                                     |
	| LCHIJA | inventorytweaks             | 1.64+dev.146.2180b27 | InventoryTweaks-1.64+dev.146.jar                  | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironchest                   | 1.12.2-7.0.67.844    | ironchest-1.12.2-7.0.72.847.jar                   | None                                     |
	| LCHIJA | iseedragons                 | 0.12                 | ISeeDragons-0.12.jar                              | None                                     |
	| LCHIJA | itlt                        | 1.0.0                | itlt-1.12.2-1.0.2.jar                             | None                                     |
	| LCHIJA | journeymap                  | 1.12.2-5.7.1         | journeymap-1.12.2-5.7.1.jar                       | None                                     |
	| LCHIJA | levelup2                    | ${version}           | Level Up! 2-1.1.23-1.12.jar                       | None                                     |
	| LCHIJA | lostcities                  | 2.0.21               | lostcities-1.12-2.0.21.jar                        | None                                     |
	| LCHIJA | lostsouls                   | 1.1.4                | lostsouls-1.12-1.1.4.jar                          | None                                     |
	| LCHIJA | lycanitesmobs               | 2.0.3.0 - MC 1.12.2  | lycanitesmobs-1.12.2-2.0.3.0.jar                  | None                                     |
	| LCHIJA | mobends                     | 0.24                 | mobends-0.24_for_MC-1.12.jar                      | None                                     |
	| LCHIJA | multimine                   | 1.6.2                | MultiMine-1.12.2.jar                              | None                                     |
	| LCHIJA | notreepunching              | 2.0.20               | notreepunching-2.0.20.jar                         | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LCHIJA | potioncore                  | 1.8_for_1.12.2       | PotionCore-1.8_for_1.12.2.jar                     | None                                     |
	| LCHIJA | potionfingers               | r1.0-8               | PotionFingers-r1.0-8.jar                          | None                                     |
	| LCHIJA | qualitytools                | 1.0.7_for_1.12.2     | QualityTools-1.0.7_for_1.12.2.jar                 | None                                     |
	| LCHIJA | quickhomes                  | 1.2.2                | QuickHomes-1.2.2.jar                              | None                                     |
	| LCHIJA | quickteleports              | 1.1.1                | quickteleports-1.12.2-1.1.1.jar                   | None                                     |
	| LCHIJA | realistictorches            | 2.1.1                | RealisticTorches-1.12.2-2.1.1.jar                 | None                                     |
	| LCHIJA | reborncore                  | 3.16.4.478           | RebornCore-1.12.2-3.16.4.478-universal.jar        | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJA | reccomplex                  | 1.4.8.2              | RecurrentComplex-1.4.8.2.jar                      | None                                     |
	| LCHIJA | roguelike                   | 1.8.0                | RoguelikeDungeons-1.12.2-1.8.0.jar                | None                                     |
	| LCHIJA | roughtweaks                 | 1.0                  | roughTweaks0.2.4-1.12.2.jar                       | None                                     |
	| LCHIJA | ruins                       | 17.2                 | Ruins-1.12.2.jar                                  | None                                     |
	| LCHIJA | silentlib                   | 3.0.13               | SilentLib-1.12.2-3.0.13+167.jar                   | None                                     |
	| LCHIJA | scalinghealth               | 1.3.37               | ScalingHealth-1.12.2-1.3.42+147.jar               | None                                     |
	| LCHIJA | sit                         | v1.2.4               | sit-1.12.2-v1.2.4.jar                             | None                                     |
	| LCHIJA | somanyenchantments          | 0.4.4                | So+Many+Enchantments+V0.4.4.jar                   | None                                     |
	| LCHIJA | spartanweaponry             | beta 1.3.8           | SpartanWeaponry-1.12.2-beta-1.3.8.jar             | None                                     |
	| LCHIJA | spartanfire                 | 0.08                 | spartanfire-0.08.jar                              | None                                     |
	| LCHIJA | spartanshields              | 1.5.4                | SpartanShields-1.12.2-1.5.4.jar                   | None                                     |
	| LCHIJA | spawnercontrol              | 1.6.3b               | SpawnerControl-1.6.3b.jar                         | None                                     |
	| LCHIJA | stg                         | 1.12.2-1.2.3         | stg-1.12.2-1.2.3.jar                              | None                                     |
	| LCHIJA | switchbow                   | 1.5.7                | switchbow-1.5.7.jar                               | None                                     |
	| LCHIJA | tanspit                     | 1.12.2-1.3           | tanspit-1.12.2-1.3.jar                            | None                                     |
	| LCHIJA | tickprofiler                | 1.12-0.0.7           | TickProfiler-1.12-0.0.7.jar                       | None                                     |
	| LCHIJA | tnt_utilities               | 1.2.3                | tnt_utilities-mc1.12-1.2.3.jar                    | None                                     |
	| LCHIJA | toolbelt                    | 1.9.12               | ToolBelt-1.12.2-1.9.12.jar                        | None                                     |
	| LCHIJA | xat                         | 0.30                 | Trinkets and Baubles-1.12.2-0.30.jar              | None                                     |
	| LCHIJA | trumpetskeleton             | 1.12-1.0.2.1         | trumpetskeleton-1.12-1.0.2.1.jar                  | None                                     |
	| LCHIJA | tumbleweed                  | 1.11-0.4.5           | tumbleweed-1.11-0.4.5.jar                         | None                                     |
	| LCHIJA | variedcommodities           | 1.12.2               | VariedCommodities_1.12.2(21nov19).jar             | None                                     |
	| LCHIJA | waystones                   | 4.0.72               | Waystones_1.12.2-4.0.72.jar                       | None                                     |
	| LCHIJA | wolfarmor                   | 2.2.3.6              | wolfarmor-1.12.2-2.2.3.1798-universal.jar         | None                                     |
	| LCHIJA | worldedit                   | 6.1.10-SNAPSHOT      | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
	| LCHIJA | xpfromharvest               | 1.1.0                | xpfromharvest-1.12.2-1.1.0.jar                    | None                                     |
	| LCHIJA | xpbook                      | v1.1.4               | xptome-1.12.2-v1.1.4.jar                          | None                                     |
	| LCHIJA | phosphor-lighting           | 1.12.2-0.2.6         | phosphor-1.12.2-0.2.6+build50-universal.jar       | f0387d288626cc2d937daa504e74af570c52a2f1 |
	| LCHIJA | snowrealmagic               | 0.3.3                | SnowRealMagic-0.3.3.jar                           | None                                     |

	Loaded coremods (and transformers): 
LibLoader (# LibLoader.jar)
  
CreativePatchingLoader (CreativeCore_v1.9.74_mc1.12.2.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.9-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  invtweaks.forge.asm.ContainerTransformer
TransformLoader (DynamicSurroundings-1.12.2-3.6.0.2.jar)
  
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  
ItemPatchingLoader (ItemPhysic_Full_1.4.27_mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
MMFMLCorePlugin (MultiMine-1.12.2.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
CoreMod (TickProfiler-1.12-0.0.7.jar)
  
BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
LoadingPlugin (Reskillable-1.12.2-1.13.0.jar)
  codersafterdark.reskillable.base.asm.ClassTransformer
TNTUtilities Core (tnt_utilities-mc1.12-1.2.3.jar)
  ljfa.tntutils.asm.ExplosionTransformer
CorePlugin (ForgeEndertech-1.12.2-4.4.25.0-build.0428.jar)
  
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.16.4.478
		Runtime Debofucsation 1
	Profiler Position: N/A (disabled)
	Player Count: 1 / 999; [EntityPlayerMP['Akou_Odin'/115, l='world', x=2764,12, y=76,63, z=3421,96]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Nekotaga** [comment]
Its because of the ISeeDragons thing, that is only for RLCraft which has the old version of Ice n Fire

**Comment by SP4RT49** [comment]
I've the last version of ice & fire :/

**Comment by Nekotaga** [comment]
That's what i mean, ISeeDragons only works with 1.7, remove the mod and it'll work fine

**Comment by SP4RT49** [comment]
okay i'm gonna try this !

edit : It's work fine ! Juste delete ISeeDragons when you use Ice & Fire 1.9.1
