### ISSUE TITLE
Dragon Failure Error

### ISSUE THREAD

**Issue by JennGreencher** [Alex-the-666/Ice_and_Fire#2363]
Hello dear developers.
I wanted to say that your mod Ice and Fire is very cool and interesting. It is very cool to travel, meeting dragons and other things from your mod. But I would like to say another  problem. My friend and I were going to get ourselves dragon eggs to get dragons out of them. We found two ice females of dragons 4 and 5 of the stage. When they had little HP left, they disappeared. This is probably a bug, but please fix it. Thanks in advance. We are waiting for new updates)

**Comment by AlexModGuy** [comment]
dupe #344
