### ISSUE TITLE
New monster idea

### ISSUE THREAD

**Issue by BrasterHater** [Alex-the-666/Ice_and_Fire#2364]
I think is cool see in game orchs and Yeti

**Comment by ThatOnePersonWho** [comment]
tHiS iSn'T a SuGgEsTiOn PaGe
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
