### ISSUE TITLE
Hydra's shield bug

### ISSUE THREAD

**Issue by Garam1207** [Alex-the-666/Ice_and_Fire#2365]
Hallo dear developers.
Coincidently  I found a bug.
When you block a breath of hydra with a shield the crash will happen in the game.
https://twitter.com/i/status/1253218313271783425

**Comment by Kodabeeer** [comment]
Give him a mod list, there was a similar issue that was apparently related to another mod, iirc it was betweenlands

**Comment by AlexModGuy** [comment]
issue is with betweenlands, again.
