### ISSUE TITLE
(1.9.0) Dreadstone Spawners don't spawn new mobs like a normal spawner would. 

### ISSUE THREAD

**Issue by QuantumExp** [Alex-the-666/Ice_and_Fire#2367]
Hello there! Love the mod! I am experiencing an issue though. It seems that after the mausoleums have generated in the world, the spawners that generate with them don't continue to spawn new mobs, regardless of the players vicinity to it. Normal spawners stop working if a player is too far away, and start working when the player gets closer, but these spawners don't seem to work at all. I mean, the mausoleum does spawn with some dread mobs in it, but no new mobs spawn after the mausoleum's initial generation. Thus, the mausoleums are easy to clear out and aren't all that challenging. 

Another thing, dread mobs are more intent on killing animals outside the mausoleum than the player that just entered the mausoleum, but this is an issue for a different report.

**Comment by Corruptedtouch** [comment]
Following on from this, they seem to spawn one entity each then convert to a pig spawner. The overworld outside of the mausoleum becomes overrun with pigs. Great for farming up some meat for Dragon meal, but I'm guessing that's not what was intended. ^_^

**Comment by QuantumExp** [comment]
I have never seen that. For me, they just don't spawn anything at all. The only dread mobs in the mausoleum are there upon initial world gen, but after that, no new ones would appear. The spawners simply wouldn't work. It makes the mausoleum too easy to clear out.
