### ISSUE TITLE
Dragon Doesn't Attack Me

### ISSUE THREAD

**Issue by kenijey** [Alex-the-666/Ice_and_Fire#237]
it's just flying around....flying....flying.....flying.... i looted all its chests and gold piles, but he's still flying :D 
MC:1.11.2 Forge:2309
edit: i tried attacking it with my pickaxe, but it still doesn't care me.

**Comment by blackviperr** [comment]
i still have this issue too

**Comment by AlexModGuy** [comment]
should be fixed in 1.5.0
