### ISSUE TITLE
Dragon staff is too small

### ISSUE THREAD

**Issue by DrPenguinni** [Alex-the-666/Ice_and_Fire#2370]
The dragon staff item, when held out, is no bigger than a sword. I remember it being sized like an actual staff.

**Comment by AlexModGuy** [comment]
![2020-04-23_13 53 13](https://user-images.githubusercontent.com/8662109/80148354-ccaa6200-8569-11ea-98dd-cf388549faf6.png)
looks fine to me.

**Comment by DrPenguinni** [comment]
![2020-04-23_15 57 39](https://user-images.githubusercontent.com/41919574/80148893-57478d00-857b-11ea-8881-bf7e327632a9.png)
This is with Ice and Fire 1.9.0, the hotfixed version
