### ISSUE TITLE
Armored dragons cause severe rendering lag

### ISSUE THREAD

**Issue by quietust** [Alex-the-666/Ice_and_Fire#2378]
Looking in the direction of an armored dragon (even if it's behind a wall) causes significant lag in version 1.9.0 - framerate drops noticeably (especially when uncapped with VSync off), and the memory allocation rate skyrockets to nearly 1GB per second, resulting in frequent "emergency" garbage collection (causing multi-second delays) when combined with other mods.

Steps to reproduce:
1. Disable VSync and set Max Framerate to Unlimited.
2. Create a Superflat Creative world using the "Readstone Ready" preset.
3. Give yourself a dragon spawn egg, creative dragon meal, a dragon command staff, and any piece of dragon armor.
4. Spawn the dragon, tame it, order it to stand still.
5. Press Alt+F3, then Shift+right-click the dragon to open its inventory.
6. Note the "Mem:" line at the upper-right (increases slowly, in increments of ~30MB a few times per second), the Framerate (~270fps with my configuration), and the FPS indicator at the bottom left (all green)
7. Equip the dragon with a piece of armor. Observe that the Framerate has dropped (for me, down to 51fps), "Mem:" is increasing rapidly (and constantly rolling over), and the FPS indicator is mostly yellow with frequent red spikes.
8. Remove the armor from the dragon and watch everything return to normal.

This does not occur in version 1.8.4.

Java version: 1.8.0_51 64-bit (bundled)
Forge version: 1.12.2-14.23.5.2847
Mods: iceandfire-1.9.0, llibrary-1.7.19-1.12.2
CPU: Core i7-4790 @ 3.60 GHz
GPU: GeForce GTX 760

**Comment by Kodabeeer** [comment]
Update to 1.9.1

**Comment by quietust** [comment]
It figures I'd forget to clear the "is:open" filter before searching...
