### ISSUE TITLE
Mausoleums 

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#2379]
Players can not mine into mausoleums but dragons can use breath on the walls then players can get in without getting a gravemasters key. the key seems redundant then.

make dreadblocks immune to dragons breath

**Comment by kodabeer** [comment]
Wasn't this fixed in 1.9.1?

**Comment by PlatinumFox** [comment]
yep im just an idiot

**Comment by PlatinumFox** [comment]
closing
