### ISSUE TITLE
I cant open minecraft with 1.9.1

### ISSUE THREAD

**Issue by Mahdytepig** [Alex-the-666/Ice_and_Fire#2382]
This is the crashlog 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  LibLoader (# LibLoader.jar)
  CreativePatchingLoader (CreativeCore_v1.9.90_mc1.12.2.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  CoreMod (TickProfiler-1.12-0.0.10.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.5.2.0-build.0459.jar)
  LoadingPlugin (Xaeros_Minimap_20.5.2_Forge_1.12.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  Born in a Barn (Born In A Barn V1.8-1.12-1.1.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.28_mc1.12.2.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  MMFMLCorePlugin (MultiMine-1.12.2.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  LoadingPlugin (Reskillable-1.12.2-1.13.0.jar)
  WolfArmorCore (wolfarmor-1.12.2-3.4.1.1-UNIVERSAL-signed.jar)
  TNTUtilities Core (tnt_utilities-mc1.12-1.2.3.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 4/25/20 2:17 AM
Description: Initializing game

java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/core/ModItems
	at com.chaosbuffalo.spartanfire.init.ItemRegistrySFire.<clinit>(ItemRegistrySFire.java:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_240_ItemRegistrySFire_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.github.alexthe666.iceandfire.core.ModItems
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 19 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.chaosbuffalo.spartanfire.init.ItemRegistrySFire.<clinit>(ItemRegistrySFire.java:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_240_ItemRegistrySFire_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 544385736 bytes (519 MB) / 1483210752 bytes (1414 MB) up to 3008888832 bytes (2869 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3228m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 128 mods loaded, 128 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                          | Version              | Source                                        | Signature                                |
	|:----- |:--------------------------- |:-------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                   | 1.12.2               | minecraft.jar                                 | None                                     |
	| LCH   | mcp                         | 9.42                 | minecraft.jar                                 | None                                     |
	| LCH   | FML                         | 8.0.99.99            | forge-1.12.2-14.23.5.2838.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                       | 14.23.5.2838         | forge-1.12.2-14.23.5.2838.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | creativecoredummy           | 1.0.0                | minecraft.jar                                 | None                                     |
	| LCH   | itemphysic                  | 1.4.0                | minecraft.jar                                 | None                                     |
	| LCH   | ivtoolkit                   | 1.3.3-1.12           | minecraft.jar                                 | None                                     |
	| LCH   | xaerominimap_core           | 1.12.2-1.0           | minecraft.jar                                 | None                                     |
	| LCH   | foamfixcore                 | 7.7.4                | minecraft.jar                                 | None                                     |
	| LCH   | tnt_utilities_core          | 1.2.3                | minecraft.jar                                 | None                                     |
	| LCH   | damageindicatorsmod         | 1.0                  | [1.12.2]DamageIndicatorsMod-3.5.1 (2).jar     | None                                     |
	| LCH   | forgeendertech              | 1.12.2-4.5.2.0       | ForgeEndertech-1.12.2-4.5.2.0-build.0459.jar  | None                                     |
	| LCH   | adhooks                     | 1.12.2-3.2.3.0       | AdHooks-1.12.2-3.2.3.0-build.0435.jar         | None                                     |
	| LCH   | advanced-fishing            | 1.3.3                | Advanced-Fishing-1.12.2-1.3.3.jar             | None                                     |
	| LCH   | aireducer                   | 0.1.3                | AIReducer-1.12.2-0.1.3.jar                    | None                                     |
	| LCH   | alcatrazcore                | 1.0.4                | alcatrazcore-1.0.4.jar                        | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LCH   | antiqueatlas                | 4.6.3                | antiqueatlas-1.12.2-4.6.3.jar                 | None                                     |
	| LCH   | antiqueatlasoverlay         | 1.2                  | antiqueatlas-1.12.2-4.6.3.jar                 | None                                     |
	| LCH   | anvilpatch                  | 1.0.0                | anvilpatch-1.0.0.jar                          | None                                     |
	| LCH   | aquaculture                 | 1.6.8                | Aquaculture-1.12.2-1.6.8.jar                  | None                                     |
	| LCH   | carrots                     | 1.0.0b1              | carrotslib-mc1.12.2-1.0.0b1.jar               | None                                     |
	| LCH   | armorunder                  | 1.0.0                | armorunder-mc1.12.2-1.0.0.jar                 | None                                     |
	| LCH   | autoreglib                  | 1.3-32               | AutoRegLib-1.3-32.jar                         | None                                     |
	| LCH   | bacodifficulty              | 1.0.3                | BacoDifficulty-1.0.3.jar                      | None                                     |
	| LCH   | battletowers                | 1.6.5                | BattleTowers-1.12.2.jar                       | None                                     |
	| LCH   | baubles                     | 1.5.2                | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCH   | baubleshud                  | 5.0.2                | BaublesHud-1.12.2-5.0.2.jar                   | None                                     |
	| LCH   | mujmajnkraftsbettersurvival | 1.4.1                | better_survival-1.4.1.jar                     | None                                     |
	| LCH   | bettercombatmod             | 1.5.6                | BetterCombat-1.12.2-1.5.6.jar                 | None                                     |
	| LCH   | forgelin                    | 1.8.4                | Forgelin-1.8.4.jar                            | None                                     |
	| LCH   | betterfoliage               | 2.2.0                | BetterFoliage-MC1.12-2.2.0.jar                | None                                     |
	| LCH   | bloodmoon                   | 1.5.3                | Bloodmoon-MC1.12.2-1.5.3.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCH   | bnbgaminglib                | 2.17.6               | BNBGamingLib-1.12.2-2.17.6.jar                | None                                     |
	| LCH   | bountifulbaubles            | 0.0.1                | Bountiful Baubles-1.12.2-0.1.5.jar            | None                                     |
	| LCH   | campfire                    | 1.2                  | campfire-1.12-v1.2.jar                        | None                                     |
	| LCH   | carryon                     | 1.12.3               | CarryOn MC1.12.2 v1.12.3.jar                  | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCH   | chunkanimator               | 1.2                  | ChunkAnimator-MC1.12-1.2.jar                  | None                                     |
	| LCH   | toughasnails                | 3.1.0.141            | ToughAsNails-1.12.2-3.1.0.141-universal.jar   | None                                     |
	| LCH   | comforts                    | 1.4.1.3              | comforts-1.12.2-1.4.1.3.jar                   | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCH   | reskillable                 | 1.12.2-1.13.0        | Reskillable-1.12.2-1.13.0.jar                 | None                                     |
	| LCH   | compatskills                | 1.12.2-1.17.0        | CompatSkills-1.12.2-1.17.0.jar                | None                                     |
	| LCH   | coralreef                   | 2.0                  | CoralReef-2.5-1.12.2.jar                      | None                                     |
	| LCH   | wearablebackpacks           | 3.1.4                | WearableBackpacks-1.12.2-3.1.4.jar            | None                                     |
	| LCH   | corpsecomplex               | 1.0.10.1             | corpsecomplex-1.12.2-1.0.10.1.jar             | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCH   | craftablechainmail          | 1.0                  | craftablechainmail-1.0.jar                    | None                                     |
	| LCH   | craftablehorsearmour        | 1.3                  | CraftableHorseArmour-1.3.0-1.12.jar           | None                                     |
	| LCH   | crafttweaker                | 4.1.20               | CraftTweaker2-1.12-4.1.20.jar                 | None                                     |
	| LCH   | ctgui                       | 1.0.0                | CraftTweaker2-1.12-4.1.20.jar                 | None                                     |
	| LCH   | jei                         | 4.15.0.291           | jei_1.12.2-4.15.0.291.jar                     | None                                     |
	| LCH   | crafttweakerjei             | 2.0.3                | CraftTweaker2-1.12-4.1.20.jar                 | None                                     |
	| LCH   | creativecore                | 1.9.9                | CreativeCore_v1.9.90_mc1.12.2.jar             | None                                     |
	| LCH   | custommainmenu              | 2.0.9.1              | CustomMainMenu-MC1.12.2-2.0.9.1.jar           | None                                     |
	| LCH   | defiledlands                | 1.4.3                | defiledlands-1.12.2-1.4.3.jar                 | None                                     |
	| LCH   | disenchanter                | 1.6                  | disenchanter-[1.12]1.6.jar                    | None                                     |
	| LCH   | dldungeonsjbg               | 1.13.2               | DoomlikeDungeons-1.13.2-MC1.12.2.jar          | None                                     |
	| LCH   | reccomplex                  | 1.4.8.2              | RecurrentComplex-1.4.8.2.jar                  | None                                     |
	| LCH   | dynamictrees                | 1.12.2-0.9.7         | DynamicTrees-1.12.2-0.9.7.jar                 | None                                     |
	| LCH   | traverse                    | 1.6.0                | Traverse-1.12.2-1.6.0-69.jar                  | None                                     |
	| LCH   | dttraverse                  | 1.5                  | dttraverse-1.5.jar                            | None                                     |
	| LCH   | sereneseasons               | 1.2.18               | SereneSeasons-1.12.2-1.2.18-universal.jar     | None                                     |
	| LCH   | orelib                      | 3.6.0.1              | OreLib-1.12.2-3.6.0.1.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dsurround                   | 3.6.1.0              | DynamicSurroundings-1.12.2-3.6.1.0.jar        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | enchdesc                    | 1.1.20               | EnchantmentDescriptions-1.12.2-1.1.20.jar     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | enhancedvisuals             | 1.0                  | EnhancedVisuals_v1.2.7_mc1.12.2.jar           | None                                     |
	| LCH   | familiarfauna               | 1.0.11               | FamiliarFauna-1.12.2-1.0.11.jar               | None                                     |
	| LCH   | fbp                         | 2.4.1                | FancyBlockParticles-1.12.x-2.4.1.jar          | None                                     |
	| LCH   | firstaid                    | 1.6.13               | firstaid-1.6.14.jar                           | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| LCH   | foamfix                     | 0.10.10-1.12.2       | foamfix-0.10.10-1.12.2.jar                    | None                                     |
	| LCH   | foodexpansion               | 1.3                  | FoodExpansion1.3.3-1.12.2.jar                 | None                                     |
	| LCH   | tschipplib                  | 1.1.3                | TschippLib MC1.12.2 v1.1.3.jar                | None                                     |
	| LCH   | forgottenitems              | 1.2.1                | ForgottenItems MC1.12.2 v1.2.1.jar            | None                                     |
	| LCH   | friendlyendermite           | 1.0                  | FriendlyEndermite_v1.0.1_mc1.12.2.jar         | None                                     |
	| LCH   | globalgamerules             | 2.2                  | GlobalGameRules-1.12.2-2.2.7.jar              | None                                     |
	| LCH   | grapplemod                  | 1.12.2-v11.1         | grapplemod-v11.1-1.12.2.jar                   | None                                     |
	| LCH   | llibrary                    | 1.7.19               | llibrary-1.7.19-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | iceandfire                  | 1.9.1                | iceandfire-1.9.1-1.12.2.jar                   | None                                     |
	| LCH   | infernalmobs                | 1.7.6                | InfernalMobs-1.12.2.jar                       | None                                     |
	| LCH   | inventorytweaks             | 1.64+dev.151.822d839 | InventoryTweaks-1.64+dev.151.jar              | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | iseedragons                 | 0.12                 | ISeeDragons-0.12.jar                          | None                                     |
	| LCH   | itlt                        | 1.0.0                | itlt-1.12.2-1.0.2.jar                         | None                                     |
	| LCH   | levelup2                    | ${version}           | Level Up! 2-1.1.23-1.12.jar                   | None                                     |
	| LCH   | loadingscreens              | 0.3.1                | LoadingScreens-1.12.2-0.3.1.jar               | None                                     |
	| LCH   | lostcities                  | 2.0.22               | lostcities-1.12-2.0.22.jar                    | None                                     |
	| LCH   | lostsouls                   | 1.1.4                | lostsouls-1.12-1.1.4.jar                      | None                                     |
	| LCH   | lycanitesmobs               | 2.0.7.1 - MC 1.12.2  | lycanitesmobs-1.12.2-2.0.7.1.jar              | None                                     |
	| LCH   | reborncore                  | 3.19.3.524           | RebornCore-1.12.2-3.19.3.524-universal.jar    | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCH   | mainmenuscale               | 1.0                  | MainMenuScale-1.3.2.jar                       | None                                     |
	| LCH   | mobends                     | 0.24                 | mobends-0.24_for_MC-1.12.jar                  | None                                     |
	| LCH   | mousetweaks                 | 2.10                 | MouseTweaks-2.10-mc1.12.2.jar                 | None                                     |
	| LCH   | multimine                   | 1.6.2                | MultiMine-1.12.2.jar                          | None                                     |
	| LCH   | neat                        | 1.4-17               | Neat 1.4-17.jar                               | None                                     |
	| LCH   | notreepunching              | 2.0.20               | notreepunching-2.0.20.jar                     | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LCH   | potioncore                  | 1.9_for_1.12.2       | PotionCore-1.9_for_1.12.2.jar                 | None                                     |
	| LCH   | potionfingers               | r1.0-8               | PotionFingers-r1.0-8.jar                      | None                                     |
	| LCH   | qualitytools                | 1.0.7_for_1.12.2     | QualityTools-1.0.7_for_1.12.2.jar             | None                                     |
	| LCH   | realistictorches            | 2.1.1                | RealisticTorches-1.12.2-2.1.1.jar             | None                                     |
	| LCH   | resourceloader              | 1.5.3                | ResourceLoader-MC1.12.1-1.5.3.jar             | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCH   | rltweaker                   | 0.3.0                | RLTweaker-1.12.2-0.3.0.jar                    | None                                     |
	| LCH   | roguelike                   | 1.8.0                | RoguelikeDungeons-1.12.2-1.8.0.jar            | None                                     |
	| LCH   | roughtweaks                 | 1.0                  | roughTweaks0.2.4-1.12.2.jar                   | None                                     |
	| LCH   | ruins                       | 17.2                 | Ruins-1.12.2.jar                              | None                                     |
	| LCH   | silentlib                   | 3.0.13               | SilentLib-1.12.2-3.0.14+168.jar               | None                                     |
	| LCH   | scalinghealth               | 1.3.37               | ScalingHealth-1.12.2-1.3.42+147.jar           | None                                     |
	| LCH   | sit                         | v1.3                 | sit-1.12.2-v1.3.jar                           | None                                     |
	| LCH   | somanyenchantments          | 0.4.4                | So Many Enchantments V0.4.4.jar               | None                                     |
	| LCH   | soundfilters                | 0.12_for_1.12        | SoundFilters-0.12_for_1.12.jar                | None                                     |
	| LCH   | spartanweaponry             | beta 1.3.8           | SpartanWeaponry-1.12.2-beta-1.3.8.jar         | None                                     |
	| LCH   | spartanfire                 | 0.05                 | spartanfire-0.05.jar                          | None                                     |
	| LCH   | spartanshields              | 1.5.4                | SpartanShields-1.12.2-1.5.4.jar               | None                                     |
	| LCH   | spawnercontrol              | 1.6.3b               | SpawnerControl-1.6.3b.jar                     | None                                     |
	| LCH   | stg                         | 1.12.2-1.2.3         | stg-1.12.2-1.2.3.jar                          | None                                     |
	| LCH   | switchbow                   | 1.5.7                | switchbow-1.5.7.jar                           | None                                     |
	| LCH   | tanspit                     | 1.12.2-1.3           | tanspit-1.12.2-1.4.jar                        | None                                     |
	| LCH   | tickprofiler                | 1.12-0.0.10          | TickProfiler-1.12-0.0.10.jar                  | None                                     |
	| LCH   | tnt_utilities               | 1.2.3                | tnt_utilities-mc1.12-1.2.3.jar                | None                                     |
	| LCH   | toolbelt                    | 1.9.12               | ToolBelt-1.12.2-1.9.12.jar                    | None                                     |
	| LCH   | xat                         | 0.29.2               | Trinkets and Baubles-1.12.2-0.29.2.jar        | None                                     |
	| LCH   | trumpetskeleton             | 1.12-1.0.2.1         | trumpetskeleton-1.12-1.0.2.1.jar              | None                                     |
	| LCH   | tumbleweed                  | 1.12-0.4.7           | tumbleweed-1.12-0.4.7.jar                     | None                                     |
	| LCH   | variedcommodities           | 1.12.2               | VariedCommodities_1.12.2(21nov19).jar         | None                                     |
	| LCH   | waystones                   | 4.1.0                | Waystones_1.12.2-4.1.0.jar                    | None                                     |
	| LCH   | wolfarmor                   | 3.4.1.1              | wolfarmor-1.12.2-3.4.1.1-UNIVERSAL-signed.jar | None                                     |
	| LCH   | xaerominimap                | 20.5.2               | Xaeros_Minimap_20.5.2_Forge_1.12.jar          | None                                     |
	| LCH   | xpfromharvest               | 1.1.0                | xpfromharvest-1.12.2-1.1.0.jar                | None                                     |
	| LCH   | xpbook                      | v1.1.4               | xptome-1.12.2-v1.1.4.jar                      | None                                     |
	| LCH   | dshuds                      | 3.6.0.0              | DynamicSurroundingsHuds-1.12.2-3.6.0.0.jar    | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | phosphor-lighting           | 1.12.2-0.2.6         | phosphor-1.12.2-0.2.6+build50-universal.jar   | f0387d288626cc2d937daa504e74af570c52a2f1 |
	| LCH   | snowrealmagic               | 0.3.3                | SnowRealMagic-0.3.3.jar                       | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)
  invtweaks.forge.asm.ContainerTransformer
TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
LibLoader (# LibLoader.jar)
  
CreativePatchingLoader (CreativeCore_v1.9.90_mc1.12.2.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
CoreMod (TickProfiler-1.12-0.0.10.jar)
  
CorePlugin (ForgeEndertech-1.12.2-4.5.2.0-build.0459.jar)
  
LoadingPlugin (Xaeros_Minimap_20.5.2_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
Born in a Barn (Born In A Barn V1.8-1.12-1.1.jar)
  com.chocohead.biab.BornInABarn
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ItemPatchingLoader (ItemPhysic_Full_1.4.28_mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  
MMFMLCorePlugin (MultiMine-1.12.2.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
LoadingPlugin (Reskillable-1.12.2-1.13.0.jar)
  codersafterdark.reskillable.base.asm.ClassTransformer
WolfArmorCore (wolfarmor-1.12.2-3.4.1.1-UNIVERSAL-signed.jar)
  
TNTUtilities Core (tnt_utilities-mc1.12-1.2.3.jar)
  ljfa.tntutils.asm.ExplosionTransformer
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 432.00' Renderer: 'GeForce GTX 660/PCIe/SSE2'
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.19.3.524
		Runtime Debofucsation 1
		RenderEngine: 0
	Launched Version: forge-14.23.5.2838
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 660/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: CH 1.10 Shader Fix By Shivaxi FORGE VERSION.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD Ryzen 5 2400G with Radeon Vega Graphics

**Comment by Kodabeeer** [comment]
Update spartan and fire.

**Comment by Mahdytepig** [comment]
> Update spartan and fire.

Thanks!
