### ISSUE TITLE
Biomes o plenty causing really odd spawn rate for structures

### ISSUE THREAD

**Issue by Amayapuppy** [Alex-the-666/Ice_and_Fire#2383]
Constantly finding dread and gorgon structures almost everywhere I go, the gorgon structures are often not by the sea either

**Comment by Skydragonsz** [comment]
I also have this problem
I'm on version 1.9.1 for the Ice and fire mod
Minecraft version 1.12.2
Forge: 14.23.5.2847
BOP: 7.0.1.2444

**Comment by mikan9** [comment]
I'm also experiencing really high spawn rates for these structures, although, I'm not using BOP, but Traverse.

Version 1.9.1
Forge: 14.23.5.2854
Traverse: 1.6.0-69

Are the 1.8 configs not compatible with 1.9 maybe?

**Comment by jojos38** [comment]
Same issue here
Minecraft 1.12.2
Version 1.9.1
Biome O Plenty 7.0.1.2444
Forge 14.23.5.2847
I have set the spawn rate to 1 and the min distance to 1000 blocs, it helped
