### ISSUE TITLE
dragon horns drop more in my slot when stored dragon in creative mode

### ISSUE THREAD

**Issue by DarkerGodzilla** [Alex-the-666/Ice_and_Fire#2384]
Can I setting or not ?

**Comment by DarkerGodzilla** [comment]
after updated 1.9.0 
when I stored dragon by Dragon horn in creative mode
Dragon horns has create more in my slot

**Comment by DarkerGodzilla** [comment]
![minecraft 2 bug_LI](https://user-images.githubusercontent.com/54614369/80660517-1806c800-8ab6-11ea-89f2-6d5eaccacedd.jpg)

**Comment by AlexModGuy** [comment]
should be fixed
