### ISSUE TITLE
Hydra fighting shield crash

### ISSUE THREAD

**Issue by xromsca** [Alex-the-666/Ice_and_Fire#2389]
I tried to fight a hydra and the poison spit kept crashing my game every single time.

**Comment by xromsca** [comment]
Also I originally thought it was because my computer just couldn't handle it but I can handle the dragons fire/ice breaths just fine without any issues.

**Comment by Kodabeeer** [comment]
Provide a mod list

**Comment by xromsca** [comment]
Here ya go, I managed to fight a hydra. It seems that when you use a shield against a Hydra that's when it crashes

Aether II
Animania 
Baubles
Better Animals Plus 
Better Foliage
BiblioCraft 
Biomes O' Plenty
Carpenter's Blocks 
Chameleon 
CraftStudio API
Doggy Talents
DrZhark's CustomSpawner
DrZhark's Mo'Creatures Mod
Dynamic Surroundings
Dynamic Trees
Dynamic Trees BOP
DynamicSurroundingsCore
Forge Mod Loader
Ice and Fire
IvToolkit
Just Enough Items
LLibrary 
MalisisCore
MalisisDoors
Mantle
Minecraft
Minecraft Coder Pack
Minecraft Comes Alive
Minecraft Forge 
OrbisLib 
OreLib Support Mod 
Pam's HarvestCraft
Phosphor Lighting Engine
RadixCore 
Recurrent Complex
Serene Seasons
Shadowfacts' Forgelin
Storage Drawers
Thaumcraft 
The Twilight Forest
Tinkers' Construct
Waila
Xaero's Minimap

**Comment by Kodabeeer** [comment]
Hm, I was thinking it’d be similar to an issue related to between lands. Probably throw a crash log here for Alex to read when he gets to I/F again.

**Comment by xromsca** [comment]
Alright, again it seemed to crash when I used my shield but I will

**Comment by Thethuthinnang** [comment]
I am having this crash, too. The game is fine until I try to use my shield during the hydra fight, then it immediately crashes.
