### ISSUE TITLE
Insane FPS drop while ice dragons are around

### ISSUE THREAD

**Issue by HARRRRRIE** [Alex-the-666/Ice_and_Fire#2390]
I do use other mods

**Comment by Tangosucka** [comment]
Yes something changed last update dragons cause massive fps lag now

**Comment by Xorbah** [comment]
You could have at least provided the output log, a mod list, something.

**Comment by NovaXeros** [comment]
**-- Please disregard this post, I note I have an older version where the below bug is actually fixed more recently! --**

Noticing a similar drop in FPS, but it's particularly apparent when the dragons are wearing armour.

In the same room with no changes save the below:

Without stage 1 ice dragon - 31 fps.
With stage 1 ice dragon - 29 fps.
With 1 piece of armour on the dragon - 15 fps
With all pieces of armour on the dragon - 11 fps.

Taking the armour back off the dragon immediately increases the fps back to 30.

No errors in the log and I don't think it's an incompatibility with a mod, just seems to be some kind of potential rendering/graphical issue, but here's the mod list for our server for clarity (it's an Enigmatica 2 light server with some changes made, such as adding ice and fire/AUNIS):

`

Name | File
-- | --
/dank/null | DankNull-1.12.2-1.7.89.jar
Actually   Additions | ActuallyAdditions-1.12.2-r151-2.jar
Actually   Baubles | ActuallyBaubles-1.12-1.1.jar
Advanced   Rocketry | AdvancedRocketry-1.12.2-1.7.0-208-universal.jar
AE2   Stuff | ae2stuff-0.7.0.4-mc1.12.2.jar
AE2   Wireless Terminal Library | AE2WTLib-1.12.2-1.0.34.jar
AI   Improvements | AIImprovements-1.12-0.0.1b3.jar
Akashic   Tome | AkashicTome-1.2-12.jar
AppleCore | AppleCore-mc1.12.2-3.2.0.jar
AppleSkin | AppleSkin-mc1.12-1.0.9.jar
Applied   Energistics 2 | appliedenergistics2-rv6-stable-7.jar
ArchitectureCraft   - TridentMC Version | architecturecraft-1.12-3.98.jar
Astral   Sorcery | astralsorcery-1.12.2-1.10.22.jar
AutoRegLib | AutoRegLib-1.3-32.jar
AUNIS | aunis-1.12.2-1.9.7-beta.jar
Backpacks | backpack-3.0.2-1.12.2.jar
Bad   Wither No Cookie - Reloaded | badwithernocookiereloaded-1.12.2-3.3.16.jar
Baubles | Baubles-1.12-1.5.2.jar
BdLib | bdlib-1.14.3.12-mc1.12.2.jar
Better   Advancements | BetterAdvancements-1.12.2-0.1.0.77.jar
Better   Builder's Wands | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar
Better   Questing | BetterQuesting-3.5.323.jar
Better   Questing - Quest Book | questbook-3.1.1-1.12.jar
Better   Questing - Standard Expansion | StandardExpansion-3.4.173.jar
BetterFps | BetterFps-1.4.8.jar
Block   Drops (JEI Addon) | blockdrops-1.12.2-1.4.0.jar
Blockcraftery | blockcraftery-1.12.2-1.3.1.jar
Blood   Magic | BloodMagic-1.12.2-2.4.3-105.jar
Bookshelf | Bookshelf-1.12.2-2.3.590.jar
Botania | Botania r1.10-363.jar
Brandon's   Core | BrandonsCore-1.12.2-2.4.18.210-universal.jar
Building   Gadgets | BuildingGadgets-2.7.4.jar
Chameleon | Chameleon-1.12-4.1.3.jar
Chisel | Chisel-MC1.12.2-1.0.1.44.jar
Chisels   & Bits | chiselsandbits-14.33.jar
Chunk-Pregenerator | Chunk Pregenerator   V1.12-2.2.jar
Clumps | Clumps-3.1.2.jar
CodeChicken   Lib 1.8.+ | CodeChickenLib-1.12.2-3.2.3.358-universal.jar
CoFH   Core | CoFHCore-1.12.2-4.6.3.27-universal.jar
CoFH   World | CoFHWorld-1.12.2-1.3.1.7-universal.jar
Colytra | colytra-1.12.2-1.2.0.4.jar
Common   Capabilities | CommonCapabilities-1.12.2-2.4.5.jar
ConnectedTexturesMod | CTM-MC1.12.2-1.0.1.30.jar
Controlling | Controlling-3.0.8.jar
Cooking   for Blockheads | CookingForBlockheads_1.12.2-6.5.0.jar
Cosmetic   Armor Reworked | CosmeticArmorReworked-1.12.2-v4b.jar
CraftTweaker | CraftTweaker2-1.12-4.1.19.jar
Custom   Backgrounds | CustomBackgrounds-MC1.12-1.1.1.jar
Custom   Main Menu | CustomMainMenu-MC1.12.2-2.0.9.1.jar
Cyclops   Core | CyclopsCore-1.12.2-1.6.1.jar
Dark   Utilities | DarkUtils-1.12.2-1.8.230.jar
Default   Options | DefaultOptions_1.12.2-9.2.8.jar
Demagnetize | demagnetize-1.12.2-1.1.1.jar
Diet   Hoppers | diethopper-1.1.jar
Ding | Ding-1.12.2-1.0.2.jar
Dirt2Path   [FORGE] | dirt2path-1.8.0.jar
DiscordSuite | DiscordSuite-2.2.4.jar
Draconic   Evolution | Draconic-Evolution-1.12.2-2.3.25.351-universal.jar
Ender   IO | EnderIO-1.12.2-5.1.55.jar
Ender   Storage 1.8.+ | EnderStorage-1.12.2-2.4.6.137-universal.jar
EnderCore | EnderCore-1.12.2-0.5.74.jar
Engineer's   Doors | engineers_doors-1.12.2-0.8.0.jar
Environmental   Tech | environmentaltech-1.12.2-2.0.20.1.jar
Extra   Bit Manipulation | ExtraBitManipulation-1.12.2-3.4.1.jar
Extra   Utilities | extrautils2-1.12-1.9.9.jar
Farming   for Blockheads | FarmingForBlockheads_1.12.2-3.1.28.jar
Farseek | Farseek-1.12-2.5.jar
FastFurnace | FastFurnace-1.12.2-1.3.1.jar
FastWorkbench | FastWorkbench-1.12.2-1.7.3.jar
Fence   Jumper | fencejumper-1.12-1.0.5.jar
FoamFix​ | foamfix-0.10.10-1.12.2.jar
Forestry | forestry_1.12.2-5.8.2.418.jar
FTB   Backups | FTBBackups-1.1.0.1.jar
FTB   Library | FTBLib-5.4.4.5.jar
FTB   Utilities | FTBUtilities-5.4.0.124.jar
Fullscreen   Windowed (Borderless) for Minecraft | FullscreenWindowed-1.12-1.6.0.jar
Gas   Conduits | GasConduits-1.12.2-1.2.2.jar
Guide-API | Guide-API-1.12-2.1.8-63.jar
GunpowderLib | GunpowderLib-1.12.2-1.0.jar
Hwyla | Hwyla-1.8.26-B41_1.12.2.jar
Ice   and Fire: Dragons in a whole new light! | iceandfire-1.9.0.jar
Immersive   Engineering | ImmersiveEngineering-0.12-92.jar
Immersive   Petroleum | immersivepetroleum-1.12.2-1.1.9.jar
Immersive   Tech | immersivetech-1.12-1.3.10.jar
In   Control! | incontrol-1.12-3.9.16.jar
Industrial   Craft | industrialcraft-2-2.8.177-ex112.jar
Industrial   Foregoing | industrialforegoing-1.12.2-1.12.13-237.jar
Inventory   Tweaks | InventoryTweaks-1.64+dev.150.jar
Iron   Chests | ironchest-1.12.2-7.0.72.847.jar
JAOPCA | JAOPCA-1.12.2-2.2.8.103.jar
JEI   Bees | jeibees-0.9.0.5-mc1.12.2.jar
JEI   Villagers | jeivillagers-1.12-1.0.2.jar
JourneyMap | journeymap-1.12.2-5.7.0.jar
Just   Enough HarvestCraft (JEHC) | just-enough-harvestcraft-1.12.2-1.7.0.jar
Just   Enough Items (JEI) | jei_1.12.2-4.15.0.293.jar
Just   Enough Pattern Banners | jepb-1.12-1.2.1.jar
Just   Enough Petroleum | JustEnoughPetroleum-0.1.jar
Just   Enough Resources (JER) | JustEnoughResources-1.12.2-0.9.2.60.jar
Just   Enough Throwing In Fluids (JETIF) | jetif-1.12.2-1.5.1.jar
Just   Sleep | JustSleep-1.0.0.1.jar
KleeSlabs | KleeSlabs_1.12.2-5.4.12.jar
LibVulpes | LibVulpes-1.12.2-0.4.2-74-universal.jar
LLibrary | llibrary-1.7.19-1.12.2.jar
Loot   Capacitor Tooltips | lootcapacitortooltips-1.3.jar
LootTableTweaker | LootTableTweaker-1.12.2-1.1.17.jar
LunatriusCore | LunatriusCore-1.12.2-1.2.0.42-universal.jar
Mantle | Mantle-1.12-1.3.3.55.jar
McJtyLib | mcjtylib-1.12-3.5.4.jar
MCMultiPart | MCMultiPart-2.5.3.jar
Mekanism | Mekanism-1.12.2-9.8.3.390.jar
Mekanism   Generators | MekanismGenerators-1.12.2-9.8.3.390.jar
Mekanism   Tools | MekanismTools-1.12.2-9.8.3.390.jar
MemoryTester | MemoryTester-0.4.2.jar
ModTweaker | modtweaker-4.0.17.jar
More   Overlays | moreoverlays-1.15.1-mc1.12.2.jar
Morph-o-Tool | Morph-o-Tool-1.2-21.jar
Mouse   Tweaks | MouseTweaks-2.10-mc1.12.2.jar
MTLib | MTLib-3.0.6.jar
MysticalLib | mysticallib-1.12.2-1.6.0.jar
Neat | Neat 1.4-17.jar
No   Mob Spawning on Trees | NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar
No   Night Vision Flashing | NoNVFlash-1.12.2-1.2.0.3-universal.jar
NuclearCraft | NuclearCraft-2.18o-1.12.2.jar
OldJavaWarning | OldJavaWarning-1.12.2-1.1.11.jar
OpenBlocks | OpenBlocks-1.12.2-1.8.1.jar
OpenComputers | OpenComputers-MC1.12.2-1.7.5.192.jar
OpenModsLib | OpenModsLib-1.12.2-0.12.2.jar
Ore   Excavation | OreExcavation-1.4.150.jar
p455w0rd's   Library | p455w0rdslib-1.12.2-2.3.161.jar
Pam's   HarvestCraft | Pam's HarvestCraft   1.12.2zg.jar
Phosphor   (Forge) | phosphor-1.12.2-0.2.6+build50-universal.jar
Placebo | Placebo-1.12.2-1.6.0.jar
PlaneFix | PlaneFix-1.12.2-1.0.0.jar
Pretty   Beaches | PrettyBeaches_1.12.2-1.0.4.jar
Project   Intelligence | ProjectIntelligence-1.12.2-1.0.9.28-universal.jar
Quark | Quark-r1.6-178.jar
Quick   Leaf Decay | QuickLeafDecay-MC1.12.1-1.2.4.jar
RandomPatches | randompatches-1.12.2-1.21.0.0.jar
ReAuth | reauth-3.6.0.jar
Reborn   Core | RebornCore-1.12.2-3.19.2.522-universal.jar
Redstone   Arsenal | RedstoneArsenal-1.12.2-2.6.3.18-universal.jar
Redstone   Flux | RedstoneFlux-1.12-2.1.0.6-universal.jar
Resource   Loader | ResourceLoader-MC1.12.1-1.5.3.jar
RFTools | rftools-1.12-7.73.jar
RFTools   Dimensions | rftoolsdim-1.12-5.71.jar
Rustic | rustic-1.1.2.jar
Scannable | Scannable-MC1.12.2-1.6.3.24.jar
Schematica | Schematica-1.12.2-1.8.0.169-universal.jar
Shadowfacts'   Forgelin | Forgelin-1.8.4.jar
Spice   of Life: Carrot Edition | solcarrot-1.12.2-1.8.3.jar
Storage   Drawers | StorageDrawers-1.12.2-5.4.1.jar
Streams | Streams-1.12-0.4.8.jar
Super   Sound Muffler: Revived | supersoundmuffler-revived_1.12.2_1.0.2.10.jar
SwingThroughGrass | stg-1.12.2-1.2.3.jar
Tesla   Core Lib | tesla-core-lib-1.12.2-1.0.17.jar
Thaumcraft | Thaumcraft-1.12.2-6.1.BETA26.jar
Thaumic   Inventory Scanning (Thaumcraft Addon) | ThaumicInventoryScanning_1.12.2-2.0.10.jar
Thaumic   JEI | ThaumicJEI-1.12.2-1.6.0-27.jar
Thaumic   Tinkerer | thaumictinkerer-1.12.2-5.0-353c71c.jar
Thermal   Cultivation | ThermalCultivation-1.12.2-0.3.3.12-universal.jar
Thermal   Dynamics | ThermalDynamics-1.12.2-2.5.5.21-universal.jar
Thermal   Expansion | ThermalExpansion-1.12.2-5.5.4.43-universal.jar
Thermal   Foundation | ThermalFoundation-1.12.2-2.6.3.27-universal.jar
Thermal   Innovation | ThermalInnovation-1.12.2-0.3.3.12-universal.jar
Tinkers   Construct | TConstruct-1.12.2-2.13.0.183.jar
Tinkers'   Tool Leveling | TinkerToolLeveling-1.12.2-1.1.0.jar
Tips | Tips-1.12.2-1.0.8.jar
TipTheScales | TipTheScales-1.12.2-1.0.4.jar
Toast   Control | Toast   Control-1.12.2-1.8.1.jar
Tomb   Many Graves 2 | TombManyGraves-1.12-4.2.0.jar
Torchmaster | torchmaster_1.12.2-1.8.1.81.jar
ToroHealth   Damage Indicators | torohealth-1.12.2-11.jar
UniDict | UniDict-1.12.2-2.9.2.jar
Unloader | unloader-1.2.0.jar
ValkyrieLib | valkyrielib-1.12.2-2.0.20.1.jar
Villager   Market | villager-market-1.12.2-1.0.2.jar
WanionLib | WanionLib-1.12.2-2.2.jar
Wawla   - What Are We Looking At | Wawla-1.12.2-2.6.274.jar
Wireless   Crafting Terminal | WirelessCraftingTerminal-1.12.2-3.12.97.jar
WrapUp | WrapUp-1.12-1.1.3.jar
XNet | xnet-1.12-1.8.2.jar
YNot | YNot-0.2.4.jar

`

**Comment by HARRRRRIE** [comment]
Thank you I shall look into it

**Comment by NovaXeros** [comment]
**-- Please disregard this post, I note I have an older version where the below bug is actually fixed more recently! --**

Worth mentioning too that I'm using Chocapic13's V8 Ultra shaders. Haven't yet tried without shader, but have noticed the same drop with other versions of his shaders such as 7.1 Medium and 7.1 High - the actual FPS numbers are different, but the drops are the same (lowest framerate when dragon wearing armour, etc.)

**Comment by Thethuthinnang** [comment]
I am having lag issues, as well, around glaciers. FPS drops to 3~4. Immediately goes back to normal when I leave the glacier biome. Not sure if it's ice dragon related; I didn't see any roosts where I experienced the lag but I don't know if there were any lairs underground.

**Comment by FearAK** [comment]
> 
> 
> I am having lag issues, as well, around glaciers. FPS drops to 3~4. Immediately goes back to normal when I leave the glacier biome. Not sure if it's ice dragon related; I didn't see any roosts where I experienced the lag but I don't know if there were any lairs underground.

I'm having this issue on 1.16.5 right now, did you ever find a fix?
