### ISSUE TITLE
''java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/core/ModItems'' problem

### ISSUE THREAD

**Issue by IIFadedII** [Alex-the-666/Ice_and_Fire#2395]
whenever i try to launch minecraft this ''error'' pops up, i have looked through the crash file but i dont know what to excactly look after. I use the latest forge for 1.12.2 (aka version 2847), i am playing the RLCraft modpack but with an updated Ice And Fire and a few extra mods, those mods are: 
Atum 
Mo Creatures
Iron Chests
Mowzie's Mobs
NetherEx+LibraryEx
The Midnight
Rex's Additional Structures
Illagers+
Journey Map

So i was wondering, is it something with the mod itself, the other added mods or some config stuff?

**Comment by IIFadedII** [comment]
found the issue, i had to update the spartan and fire mod, im dumb lol

**Comment by Coronayeet1209** [comment]
whenever i launch rlcraft halfway throw the start up an eror pops up and says this 

The game crashed whilst initializing game Error: java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/core/ModItems Exit Code: -1

**Comment by Coronayeet1209** [comment]
can i have help

**Comment by BotThatWillTryToHelp** [comment]
just try uninstalling the ice and fire mod if this will show again or try to reinstall the mod
