### ISSUE TITLE
I have found 4 different bugs in the current newest version.

### ISSUE THREAD

**Issue by IColorfulLily** [Alex-the-666/Ice_and_Fire#2403]
This is with the current newest version. Baby dragons will teleport back to where you picked them up. Stage 2 dragons end up flying too far and when you catch up to them they sky rocket. And the summening crystal doesn't always work. And the last bug is that some times when using the dragon horn an extra appears in my inventory. Not that I am complaining about the horn bug. But bad or good makes no difference a bug is a bug and I feel I should report any bugs or issues so that I can do my part in supporting this mod.

**Comment by AlexModGuy** [comment]
fixed
