### ISSUE TITLE
Dragon and cyclops? bugs

### ISSUE THREAD

**Issue by TinyFloof** [Alex-the-666/Ice_and_Fire#2406]
Found a few bugs when checking out the newest version (absolutely love it btw).
1. In creative after a dragon is placed in a horn (it showed the dragon was in) the sounds kept playing. After reloading the world, the dragon was outside of the horn but it still said it was inside. Calling the dragon out effectively caused a duplication. I had two exact same dragons.
2. Baby dragons can be picked up, but teleport back to their original spot after placing them down. Also, sometimes the newly hatched dragons can't be seen. I did lower the hatch time to under 10 so maybe that's the problem.
3. Spotted a cyclops and its sheep with no cave. I could interact with it normally and it could walk around with no restrictions.

**Comment by Nekotaga** [comment]
The third isnt a bug but a new feature, wandering cyclops, theres a small chance of them spaawning, tho the other two do sound like bugs

**Comment by TinyFloof** [comment]
Oohhh thank you! I wasn't sure about hat one because it seemed too intentional. Better to mention it than to leave a bug in

**Comment by AlexModGuy** [comment]
should be fixed
