### ISSUE TITLE
Issues : 1.12.2

### ISSUE THREAD

**Issue by Nemozinioux** [Alex-the-666/Ice_and_Fire#2411]
So I encountered many issues with the mod, which are :
 - Pixies don't follow. I drop them cakes as told in the bestiary but they just eat them and do nothing else 
 - Baby dragon pathfinding is absolutely weird. My dragon goes anywhere (even through walls) if I don't tell it to seat, and even being bound to a chain doesn't limit it's move range
 - The dragon horn that clones : when you use a dragon horn on your dragon, the empty dragon horn disappears and is replaced by a dragonhorn with your dragon in. It wouldn't be annoying if the empty dragonhorn did disappear in creative mode. But it doesn't. And if sadly your inventory is full when you use the empty dragonhorn, you'll never see your dragon again. Kinda annoying.

I hope these will be fixed soon, because this mod is truly amazing. Sorry if there are misspellings, I'm French :)

**Comment by AlexModGuy** [comment]
should be fixed
