### ISSUE TITLE
wild dragons vanish when grabbing me with mouth

### ISSUE THREAD

**Issue by galenr150** [Alex-the-666/Ice_and_Fire#2415]
any time a dragon tries to grab me in its mouth when im fighting it, after a second or 2, it vanishes as if it was just deleted from existence, no particles or sound or anything. its happened across a couple different versions and on a few different packs, survival and creative, multiplayer and single players. currently on latest version of of MC eternal with version 1.9.0 version of this mod. had it happening on 1.8.4 as well, and maybe a couple other versions. happens practically every time im grabbed, i think once out of around 10-15 times the dragon didnt vanish. each time i've been grabbed, it was by a dragon in a cave, i dont know if the ones that spawn on the above ground structures are too small to grab me, or if thats just coincidence or luck.

**Comment by galenr150** [comment]
i tried turning off dragons despawning, and it didnt vanish. but i was also on a superflat, so its possible that its also me/the dragon hitting the cave weirdly or somethin like that. that config option also says it could cause a lot of lag though, which isn't ideal really

**Comment by midfastno1** [comment]
then they are scared

**Comment by Skyvex3** [comment]
*bump* having this issue aswell and its very frustrating to deal with, playing Enigmatic 2: Expert using Ice and Fire 1.8.4.
Seems like its a problem with the dragon getting stuck in the wall or something? idk.
I am 100% sure it cant happen to dragons above ground.
Any update on this?

Also: Is it intended that you are able to escape a dragon grab attack by pressing L-Shift? Seems pretty weird that you are able to just escape from the attack like that.

**Comment by colemanshropshire** [comment]
Why was this closed, the issue is not fixed

**Comment by Neko2n** [comment]
> Why was this closed, the issue is not fixed

Maybe it's fixed for the next update?
Edit: Just noticed the date this issue was opened and the version it was opened for. It was closed in the mass wiping of the GitHub issues earlier in February of this year. Even if it was reopened, it wouldn't be a valid issue due to the fact that Alex has dropped support for versions below 1.16.
