### ISSUE TITLE
Forge fails to load ...

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#2418]
This is a forge's log 
[latest.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/4578634/latest.txt)
He said at the end of the log that it was the fault of ice and fire
Ice And Fire Mod Ver.1.9.1 1.12.2

**Comment by AlexModGuy** [comment]
nothing about this is the fault of ice and fire. its just a warning that something tried to be registered twice and wouldnt result in a crash.
