### ISSUE TITLE
Gorgon Temples Incorrectly Spawning

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [Alex-the-666/Ice_and_Fire#2424]
I checked previous issues for duplicates. Did not find any.

Forge: forge-1.12.2-14.23.5.2847-universal
Ice and Fire Version: iceandfire-1.9.1-1.12.2
latest.log: https://gist.github.com/pinkpig3777/6fc449bc0fd9591cbdedb5e7296d8697
debug.log: https://gist.github.com/pinkpig3777/c1b98c2aef8edf083ef63737fd05f77f

**Problem:** 
The gorgon temple does spawn in beach biomes but it spawns at a bad position as seen here:
https://gyazo.com/25f3aa851eeaec0c0fb6340e9cf1621d
and here:
https://gyazo.com/53e81a6b162b3dc4e58932f9d0eb4cab

This has happened before on a previous world. I believe that one used the realistic terrain generator from Quark.

However, this time that feature from Quark was disabled so it was more natural.

**Question/Suggestion:**
Could you please make it so it's possible to have the structure generate in desert biomes instead (on the surface). I feel it's a lot less likely to cause problems in a desert (or as many) because there is more space. 

Love this mod, hope this gets fixed. Thanks!

**Comment by PiggiesGoSqueal** [comment]
As a side note, it would appear the world generation problems are not limited to gorgon temples alone:
https://gyazo.com/837ecdd70dda7ebb56c016e9b10f7fd1

**Comment by CitrusHappy** [comment]
updating this issue, still happening with latest version
[proof](https://preview.redd.it/hhkgyx50b3151.png?width=1024&auto=webp&s=47c81d64067c90ba95f4addb45fd9263df76c3f0)

**Comment by Drakeofdark** [comment]
Honestly, i'm down with a sunken gorgon temple but the water doesn't really work to sell the effect

**Comment by PiggiesGoSqueal** [comment]
> Honestly, i'm down with a sunken gorgon temple but the water doesn't really work to sell the effect

Agreed :P which is why I've disabled Gorgon Temples unfortunately.

**Comment by ghost** [comment]
As I understand, Gorgon Templates spawns near water, But as they are quite big, they can't be generated properly. 
So, I suppose, the only way to fix it is to remake this spawn condition temporary until a proper way to implement a such spawn condition is not found.
