### ISSUE TITLE
Give players iFrames when dragons use the breathe attack

### ISSUE THREAD

**Issue by DwagonO** [Alex-the-666/Ice_and_Fire#2433]
I highly doubt that a STAGE 3 dragon absolutely ANNIHILATING my armor from MAX DURABILITY to NONE while unbreaking 3 is used. This probably only happens to multiplayer and made me lose a full set of mending unbreaking 3 protection 4 armor during 1 fight. During multiplayer have a dragon used a breathe attack and see how fast it drains you. It literally has no iframes whatsoever

**Comment by AlexModGuy** [comment]
![Screenshot (472)](https://user-images.githubusercontent.com/8662109/83340741-c73ee680-a290-11ea-9215-1d11185a956c.png)

what are you on about

**Comment by BugmanBugman** [comment]
https://minecraft.gamepedia.com/Damage#Immunity

I think this is what he means
