### ISSUE TITLE
Cockatrices don’t obey 

### ISSUE THREAD

**Issue by angel124xxx** [Alex-the-666/Ice_and_Fire#2437]
When I set it to follow, they don’t follow, when I set it to patrol they just sit there. Same goes for wander

**Comment by Senslok** [comment]
I am having the same issue, did you ever find a fix for it?

**Comment by Mechanical12** [comment]
You leave them on something other than sit and then leave and rejoin the world

**Comment by midfastno1** [comment]
they are silly then

**Comment by mnsnownutt** [comment]
I am having the same issue and logging in and out of the world does not work.  I need to completely close MC and restart.  Using RAD modpack and, needless to say, having to restart it every single time is not ideal with the loading time for the modpack.
