### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by CainSeldon** [Alex-the-666/Ice_and_Fire#244]
Posted on the forum but will copy/paste here http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2498069-ice-and-fire-dragons-in-a-whole-new-light-build-1?page=194#c4137

Crash when generating chunks in snow biomes:

---- Minecraft Crash Report -------- Minecraft Crash Report ----
WARNING: coremods are present: llibrary (llibrary-1.7.6-1.11.2.jar) SpongeCoremod (spongeforge-1.11.2-2282-7.0.0-BETA-2319.jar) TANLoadingPlugin (ToughAsNails-1.11-2.0.5.jar)Contact their authors BEFORE contacting forge
// Shall we play a game?
Time: 5/29/17 10:12 PMDescription: Exception ticking world
java.lang.NullPointerException: Exception ticking world at net.minecraft.entity.passive.EntityVillager.func_175554_cu(EntityVillager.java:1836) at net.minecraft.entity.passive.EntityVillager.func_190672_a(EntityVillager.java:852) at net.minecraft.entity.passive.EntityVillager.func_180482_a(EntityVillager.java:839) at com.github.alexthe666.iceandfire.entity.EntitySnowVillager.func_180482_a(EntitySnowVillager.java:38) at com.github.alexthe666.iceandfire.world.village.SnowVillagePieces$Village.spawnVillagers(SnowVillagePieces.java:981) at com.github.alexthe666.iceandfire.world.village.SnowVillagePieces$WoodHut.func_74875_a(SnowVillagePieces.java:1315) at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:47) at com.github.alexthe666.iceandfire.world.village.MapGenSnowVillage.func_180709_b(MapGenSnowVillage.java:50) at com.github.alexthe666.iceandfire.event.StructureGenerator.generate(StructureGenerator.java:124) at net.minecraftforge.fml.common.registry.GameRegistry.redirect$onGenerateWorld$zzc000(GameRegistry.java:585) at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:172) at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1002) at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:973) at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:158) at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$zpc000(PlayerChunkMapEntry.java:1079) at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126) at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147) at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221) at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) at java.lang.Thread.run(Unknown Source)
A detailed walkthrough of the error, its code path and all known details is as follows:---------------------------------------------------------------------------------------
-- Head --Thread: Server threadStacktrace: at net.minecraft.entity.passive.EntityVillager.func_175554_cu(EntityVillager.java:1836) at net.minecraft.entity.passive.EntityVillager.func_190672_a(EntityVillager.java:852) at net.minecraft.entity.passive.EntityVillager.func_180482_a(EntityVillager.java:839) at com.github.alexthe666.iceandfire.entity.EntitySnowVillager.func_180482_a(EntitySnowVillager.java:38) at com.github.alexthe666.iceandfire.world.village.SnowVillagePieces$Village.spawnVillagers(SnowVillagePieces.java:981) at com.github.alexthe666.iceandfire.world.village.SnowVillagePieces$WoodHut.func_74875_a(SnowVillagePieces.java:1315) at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:47) at com.github.alexthe666.iceandfire.world.village.MapGenSnowVillage.func_180709_b(MapGenSnowVillage.java:50) at com.github.alexthe666.iceandfire.event.StructureGenerator.generate(StructureGenerator.java:124) at net.minecraftforge.fml.common.registry.GameRegistry.redirect$onGenerateWorld$zzc000(GameRegistry.java:585) at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:172) at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1002) at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:973) at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:158) at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$zpc000(PlayerChunkMapEntry.java:1079) at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126) at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147) at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221)
-- Affected level --Details: Level name: Ardonia All players: 1 total; [EntityPlayerMP['Cain_Seldon'/159, l='Ardonia', x=-443.54, y=96.16, z=526.12]] Chunk stats: ServerChunkCache: 1833 Drop: 0 Level seed: -5167008807735468010 Level generator: ID 10 - BIOMESOP, ver 0. Features enabled: true Level generator options: Level spawn location: World: (191,64,230), Chunk: (at 15,4,6 in 11,14; contains blocks 176,0,224 to 191,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511) Level time: 3377342 game time, 4447 day time Level dimension: 0 Level storage version: 0x04ABD - Anvil Level weather: Rain time: 77505 (now: false), thunder time: 21133 (now: false) Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: falseStacktrace: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) at java.lang.Thread.run(Unknown Source)
-- System Details --Details: Minecraft Version: 1.11.2 Operating System: Linux (amd64) version 3.10.23-xxxx-std-ipv6-64 Java Version: 1.8.0_101, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 3107835592 bytes (2963 MB) / 4145545216 bytes (3953 MB) up to 4145545216 bytes (3953 MB) JVM Flags: 3 total; -Xmx4096M -Xms4096M -XX:MaxPermSize=256m IntCache: cache: 2, tcache: 103, allocated: 0, tallocated: 0 FML: MCP 9.38 Powered by Forge 13.20.0.2296 33 mods loaded, 33 mods active States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored UCHIJAAAA minecraft{1.11.2} [Minecraft] (minecraft.jar) UCHIJAAAA mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) UCHIJAAAA FML{8.0.99.99} [Forge Mod Loader] (custom256.jar) UCHIJAAAA forge{13.20.0.2296} [Minecraft Forge] (custom256.jar) UCHIJAAAA spongeapi{7.0.0-SNAPSHOT-0e27053} [SpongeAPI] (spongeforge-1.11.2-2282-7.0.0-BETA-2319.jar) UCHIJAAAA sponge{1.11.2-2282-7.0.0-BETA-2319} [SpongeForge] (spongeforge-1.11.2-2282-7.0.0-BETA-2319.jar) UCHIJAAAA animania{1.0.4.7} [Animania] (animania-1.11.2-1.0.4.7.jar) UCHIJAAAA biomesoplenty{6.1.0.2211} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.1.0.2211-universal.jar) UCHIJAAAA bullseye{2.0.0} [Bullseye] (Bullseye-1.11.2-2.0.0.jar) UCHIJAAAA catclearlag{0.7.1} [CatClearLag] (CatClearLag-0.7.1.jar) UCHIJAAAA cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.11.2.jar) UCHIJAAAA dynmap{2.4-3} [Dynmap] (Dynmap-2.4-forge-1.11.2.jar) UCHIJAAAA gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar) UCHIJAAAA llibrary{1.7.6} [LLibrary] (llibrary-1.7.6-1.11.2.jar) UCHIJAAAA iceandfire{1.1.0} [Ice and Fire] (iceandfire-1.1.0.jar) UCHIJAAAA journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) UCHIJAAAA luckperms{3.1.51} [LuckPerms] (LuckPerms-Sponge-3.1.51.jar) UCHIJAAAA mobrepeller{v1.1} [MobRepeller] (MobRepeller-v1.1.jar) UCHIJAAAA morpheus{1.11.2-3.2.14} [Morpheus] (Morpheus-1.11.2-3.2.14.jar) UCHIJAAAA netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.11-4.3.1.jar) UCHIJAAAA nucleus{0.28.1-S6.0} [Nucleus] (Nucleus-0.28.1-1.11.2-S6.0-plugin.jar) UCHIJAAAA realistictorches{2.1.0} [Realistic Torches] (RealisticTorches-1.11.2-2.1.0.jar) UCHIJAAAA realstonetools{7.0.2} [Real Stone Tools] (RealStoneTools-Forge-7.0.2.jar) UCHIJAAAA roguelike{1.6.6} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.6.jar) UCHIJAAAA serverlistplus{3.4.7} [ServerListPlus] (ServerListPlus-3.4.7-Universal.jar) UCHIJAAAA lteleporters{1.11.2-2.1.2} [Simple Teleporters] (SimpleTeleporters-1.11.2-2.1.2.jar) UCHIJAAAA thutcore{4.4.1} [ThutCore] (thutcore-4.4.1.jar) UCHIJAAAA thuttech{5.0.0} [Thut's Tech] (thuttech-5.0.0.jar) UCHIJAAAA timewarp{2.2.1-r6.0.0} [TimeWarp] (timewarp-2.2.1-r6.0.0.jar) UCHIJAAAA tmotd{1.0} [TitleMOTD] (TitleMOTD.-.1.0.jar) UCHIJAAAA toughasnails{@MOD_VERSION@} [Tough As Nails] (ToughAsNails-1.11-2.0.5.jar) UCHIJAAAA treechopper{1.1.2} [Tree Chopper] (TreeChopper-1.11.2-1.1.2.jar) UCHIJAAAA worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) Loaded coremods (and transformers): llibrary (llibrary-1.7.6-1.11.2.jar) net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcherSpongeCoremod (spongeforge-1.11.2-2282-7.0.0-BETA-2319.jar) org.spongepowered.common.launch.transformer.SpongeSuperclassTransformerTANLoadingPlugin (ToughAsNails-1.11-2.0.5.jar) toughasnails.asm.transformer.BlockCropsTransformer toughasnails.asm.transformer.EntityRendererTransformer toughasnails.asm.transformer.WorldTransformer Profiler Position: N/A (disabled) Player Count: 1 / 100; [EntityPlayerMP['Cain_Seldon'/159, l='Ardonia', x=-443.54, y=96.16, z=526.12]] Is Modded: Definitely; Server brand changed to 'fml,forge,sponge' Type: Dedicated Server (map_server.txt)

**Comment by Alex-the-666** [comment]
same issue as #249
