### ISSUE TITLE
fire dragons breathe has no iframes and is completely not ok

### ISSUE THREAD

**Issue by DwagonO** [Alex-the-666/Ice_and_Fire#2441]
this needs to be eradicated right away https://youtu.be/FIZxdXB3Aeg

**Comment by Jackiecrazy** [comment]
Yeesh, that dude just going "get good" isn't gonna help anyone. Config has fire values if you need to adjust them, and it looks like you're running NoDamI? There's a whitelist for dragon damage there too. Don't know if you solved your issue already, just rifling through old ones and decided to say something just in case you haven't found the solution yet.
