### ISSUE TITLE
Morph mod makes dragons disappear

### ISSUE THREAD

**Issue by davizon200** [Alex-the-666/Ice_and_Fire#2445]
Any idea why this is happening??

Tried with our old version we were using: 1.8.4

And with the newest version: 1.9.1

Any support for this?

Thanks in advance

Alfkors.

**Comment by davizon200** [comment]
okay after some more deep testing, saw its a compatibility issue with the mod "Morph" from iChun...

Dont think its a thing you can solve, i believe it has to be solved by the owner of the Morph mod.

**Comment by border999** [comment]
oh, SO THIS IS WHY!!!!
