### ISSUE TITLE
Invisible tamed dragon roaring at my house

### ISSUE THREAD

**Issue by Shoobe** [Alex-the-666/Ice_and_Fire#2446]
So I hatched a red fire dragon egg which was alright for a little bit but eventually it just kept duping itself for some reason. I ended up having to drown like 9 of the same dragon because I didn't want a duped version. I've finally managed to get it to stop duping itself but eventually I just kept hearing it roar near my house despite it not actually being visible (I have Sense Animals from Roots, it's nowhere to be found). The weird thing is judging by it's roars it's actually matured, so now I have a, or multiple, stage 5 dragons roaring in my ear every 10 seconds if I'm at my house. I know a fix could be turning off friendly animals but I'd rather not have to do that, thoughts?

**Comment by JenisisJo32** [comment]
Are you using ver 1.9.1 for 1.12.2? If so, stage 1 hatchlings are pretty glitchy right now in that release. If you put them on your shoulder at some point, the game may still think they're mounted on you, hence the screaming in your ears. Stage 1's can sound like stage 5's when their mouth is an inch from your head.

**Comment by Hamsterbutt** [comment]
I have the same problem with tamed dragon occasionally turning invisible. My dragon is stage 5. Only thing that fixes it is exiting and reentering the game.
