### ISSUE TITLE
Dragon Disappearing and glitched HP amount

### ISSUE THREAD

**Issue by Phoenixdaboss** [Alex-the-666/Ice_and_Fire#2455]
I am playing Ice And Fire mod on 1.12.2, and i set the Dragon HP to the maximum, but the Hp is always 1024 and if i shift click the dragon, the game says, it is lvl 5, even at baby dragons. And sometimes, if i fight dragons and theyre at about half Hp, they just dissapear while fighting.

**Comment by Skydragonsz** [comment]
You need to install attributeFix (yes I know, promoting other mod is bad) but vanilla minecraft has limited its hp pool to 1024 for some reason

**Comment by AlexModGuy** [comment]
^
