### ISSUE TITLE
Baby dragons kind of broken

### ISSUE THREAD

**Issue by Encryption12** [Alex-the-666/Ice_and_Fire#2469]
So I just hatched a baby fire dragon but its not working properly. When its on my shoulder I cant put it down with X only with shift. But when I press shiftvthe dragon resets back to its old location. This is causing a lot of problems because I cant even move it. Finally the dragon horn just "eats up" my dragon. Had to spawn a new one in my survival world because I used the horn on it and the dragon just dissapeared and didnt go into the horn. Is there any fix to this?

**Comment by AlexModGuy** [comment]
#2494
