### ISSUE TITLE
Issue with setting dragon down

### ISSUE THREAD

**Issue by pepperpottss** [Alex-the-666/Ice_and_Fire#2471]
Me and my friend have had a weird issue, Were on a multiplayer server that is cross modded with just two mods, fire and ice, and fossils and archeology. It’s just two of us, nobody else is on the server. When one of us place our dragons that has been sitting on our shoulders, it doesn’t register that it is down, still playing the sounds and still registering on the other players screen. To solve this we HAVE to relog or it just doesn’t change. When going into one of the areas with the dinosaurs, my dragon immediately got killed, despite me setting her down and having her set at Stay. There were no drops where she was “killed” or where I had set her to stay. In past versions, my friend whom had played it before does not remember this happening despite us being in the newest version.

**Comment by Drakeofdark** [comment]
Running into this problem too

**Comment by Nitesurgeon** [comment]
I also have this issue. Pressing X does nothing, and I checked the controls for any conflicts. The only other thing using x was "Creative: Load Toolbar Activator"
which shouldn't have mattered, but I disabled that but still X does nothing
strangely when I press shift, the dragon becomes invisible
but other players can still see it on my shoulder
