### ISSUE TITLE
Thrown Tide Trident Issue

### ISSUE THREAD

**Issue by OneYouKnow** [Alex-the-666/Ice_and_Fire#2473]
I tried to test the tide trident in creative mode with the most recent version of Ice and Fire on 1.12.2. I threw it and it landed at the floor, but when I got near to it. the trident didn't disappear like vanilla arrow would. It just stays at its point, and when I broke the blocks below it, it just continued its way like it's still flying in the air.

**Comment by truelegacy** [comment]
same issue not sure if im missin somethin
