### ISSUE TITLE
Dragon Roost Spawn Config

### ISSUE THREAD

**Issue by DemonDarling** [Alex-the-666/Ice_and_Fire#2476]
So, I changed my "Generate Dragon Roost Chance" from the default 360 to 1, thinking that would make them extremely rare (which was my intention) but when I created a world, this happened:

![2020-05-22_21 48 36](https://user-images.githubusercontent.com/65797057/82719311-55a2df00-9c77-11ea-8313-b143cf0f093c.png)

They were EVERYWHERE!

I don't know if this was caused by another mod messing with spawns, but this was ridiculous.

**Comment by Broccolon** [comment]
Yeah... Lowering the number increases the chance. of a dragon roost per chunk. You will rarely see them if you put the config for dragon roost spawning at around 700-800 it makes the incredibly rare- you'll probably never find one. If you put it at 600-700 they will still be quite rare and hard to find. 550 is what I use and it seems perfect.
