### ISSUE TITLE
Too much silver and gold in underground lairs

### ISSUE THREAD

**Issue by Sunconure11** [Alex-the-666/Ice_and_Fire#248]
https://cdn.discordapp.com/attachments/318434717525475338/319534551372136458/2017-05-31_10.55.21.png

On another server, someone pointed this out. Would it be possible to add a config to control the frequency at which gold and silver spawns in lairs?

This might wreck the balance of mods that use those metals, due to some of the derpy dragon AI at the moment.

**Comment by Alex-the-666** [comment]
fixed with config
