### ISSUE TITLE
Trolls becoming invisible when hit by a pickaxe

### ISSUE THREAD

**Issue by VictorK-M** [Alex-the-666/Ice_and_Fire#2486]
While playing the e2e modpack I hit a troll in daylight with a pickaxe, this made the troll become invisible, but the pillar it was holding was still visible. Using f3+b I see no hitbox, but when I walk into it I get pushed away.

![image](https://user-images.githubusercontent.com/39027731/82880389-a566fc00-9f3e-11ea-822d-1c2e68498b99.png)

The version of the mod is 1.8.4

**Comment by ShadowSShifter** [comment]
I’ve been having this same issue for a while

**Comment by AlexModGuy** [comment]
fixed
