### ISSUE TITLE
Crafting issue: cannot add fire dragon blood to dragon bone sword (1.9.1 in MC 1.12.2)

### ISSUE THREAD

**Issue by Thethuthinnang** [Alex-the-666/Ice_and_Fire#2489]
When I try to add a bottle of fire dragon blood to a dragon bone sword, the crafting box (the "result" box, where the crafted item is supposed to show up) is empty, so I cannot craft the flaming bone dragon sword. I haven't found an ice dragon yet to try this with the ice dragon blood. I am playing in survival, with vanilla textures.

**Comment by Thethuthinnang** [comment]
Update: Possibly a mod conflict. I started a new instance and am able to craft the fire sword without issue.

**Comment by Coda1552** [comment]
If the sword had any durability missing it won't work in the recipe, either.
