### ISSUE TITLE
Conflict Crash With Snow Villagers

### ISSUE THREAD

**Issue by kenijey** [Alex-the-666/Ice_and_Fire#249]
[crash-2017-06-01_12.54.06-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/1044327/crash-2017-06-01_12.54.06-server.txt)
please tell me if i should report it to sponge too. thanks.

**Comment by Alex-the-666** [comment]
Not a issue with sponge, just a general villager crash :)

**Comment by Alex-the-666** [comment]
Definitely a conflict with another one of you near-infinite amount of mods - I will have to look for which one is conflicting.

**Comment by AlexModGuy** [comment]
fixed in 1.2.0
