### ISSUE TITLE
Invisible dread Ghoul

### ISSUE THREAD

**Issue by SquaremelonJ** [Alex-the-666/Ice_and_Fire#2490]
Me and my friend on his server are having an issue with the mausoleum where the dread ghouls don't spawn with a physical form and have no hit box, but they can hit the player. the dread in general have a huge range which adds it the infuriating part of this they are un-killable and do tons of damage.
https://youtu.be/gQ5BFP_y7fA here is a youtube link to a video showcasing this bug.

NOTE: this only happens in the mausoleum when spawned by a lich they appear and are killable.

**Comment by TheMightyMcGrew** [comment]
Seconding this, dread ghouls are spawning invisible, but only in the mausoleums. Invis to everything and untouchable
