### ISSUE TITLE
99% RAM USAGE

### ISSUE THREAD

**Issue by SaintGearz** [Alex-the-666/Ice_and_Fire#2491]
Hi, it seems the mod is causing immense lag and I'm having a hard time pinpointing how to fix.

Here's the config: https://gist.github.com/SaintGearz/aff57b3560a7d521e34057f84811315f

**Comment by BugmanBugman** [comment]
um, how do you know its ice and fire?

**Comment by AlexModGuy** [comment]
increase your ram
