### ISSUE TITLE
a few issues with wild tamed dragons

### ISSUE THREAD

**Issue by Thethuthinnang** [Alex-the-666/Ice_and_Fire#2492]
Using the latest version (1.9.1):

* Tamed stage 5 male fire dragon disappeared when I tried to release it from the dragon horn. (I tried shutting down and restarting MC, but it was just gone, as if it hadn't ever been there.) I also tamed a stage 3 male fire dragon earlier and carried it in the horn; it did not disappear. So, I'm not sure why there is an inconsistency.

* While inside the horn, it still roared and sometimes made the wing-flapping noise.

* The tamed dragon did not fight mobs when I was attacked by mobs in the dragon lair.

* Is there a way to set an escort distance? When it's walking, it's right on top of me. When it's flying, it's a very cool animation that I really enjoy (really nice work on that!! :)) but sometimes, it stops following or gets stuck in trees. Is there a way to set walking and flying escort distance? (I do have dumber AI turned on, since the most recent version gives me a lot of lag. Maybe that's the issue with escorting.)

Thank you!

**Comment by AlexModGuy** [comment]
#2494
