### ISSUE TITLE
Game Freeze

### ISSUE THREAD

**Issue by jakubperdoch** [Alex-the-666/Ice_and_Fire#2497]
When I fight with a dragon, for example. So it always happens to me that the game freezes and when I want to disconnect, the game crashed.It happens to almost every entity from Ice_and_Fire.

**Comment by FrostStormRage** [comment]
Somewhat similar case here but not really. My game, just randomly freezes for 5 min occasionally and sometimes freezes my entire comp (-_-).

**Comment by jakubperdoch** [comment]
But after those 5 minutes, the game goes ??
