### ISSUE TITLE
Dragon scale armor cannot be repaired with the appropriate scales

### ISSUE THREAD

**Issue by Sunconure11** [Alex-the-666/Ice_and_Fire#250]

**Comment by darthvader45** [comment]
If you want, I can fix that and submit a pull request.

**Comment by darthvader45** [comment]
Though I'd need to know what color armor matches up with what color scales, etc.

**Comment by Sunconure11** [comment]
I already dealt with it. Also, the enum scenario complicated things. Doing what you said actually caused a crash. For now, in the code, until the armor is rewritten, they are repaired with dragon bones.
