### ISSUE TITLE
When running w/ infernal mobs- Gorgans turn to stone, but mobs still function

### ISSUE THREAD

**Issue by DaddyP1G** [Alex-the-666/Ice_and_Fire#2501]
I'm running a mod pack with both Infernal Mobs and Fire and Ice-  When the Gorgan turns mobs to stone in her lair.  the infernal mobes still function.  They don't move, but can still throw potions, sticky, etc.   
They also can not be broken with pickaxe.

**Comment by HARRRRRIE** [comment]
Bugs compatibility bugs
