### ISSUE TITLE
Dimension Blacklist Doesn't Work on Wandering Cyclops

### ISSUE THREAD

**Issue by mxnmnm** [Alex-the-666/Ice_and_Fire#2506]
The wandering Cyclops ignores any dimensions you blacklist and continues to spawn.

**Comment by QuantumExp** [comment]
Of course it would ignore the blacklists, it's not part of them. The blacklists that exist are for Dragons and miscellaneous structures. Mobs that have no structure assigned to them (ex: Wandering Cyclops) will ignore the blacklist.
