### ISSUE TITLE
Hydra improvement (SUGGESTION)

### ISSUE THREAD

**Issue by Drakeofdark** [Alex-the-666/Ice_and_Fire#2507]
I love the hydra but one thing always bugged me, they live in swamps with WATER but they don't have any swimming animation as far as i've seen, it's a little weird seeing as they are surrounded by deep enough water to swim in, please add, thanks.

**Comment by BugmanBugman** [comment]
this is not the suggestion tracker

**Comment by Drakeofdark** [comment]
Oof, my bad, haven't been here in awhile

**Comment by BugmanBugman** [comment]
It’s fine but go on the discord for the suggestion tracker

Sent from my iPhone

On Jun 6, 2020, at 7:48 PM, Drakeofdark <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #2507<https://github.com/Alex-the-666/Ice_and_Fire/issues/2507>.
