### ISSUE TITLE
[1.11.2] Couple of bugs I found

### ISSUE THREAD

**Issue by colejagdtiger** [Alex-the-666/Ice_and_Fire#251]
While playing the mod I found a couple of bugs

- Whenever I place an egg although it does get placed in the world a copy still remains in my inventory
- It says in the bestiary that it should take a long time to hatch an egg, however it took less than a minute to hatch an egg for me
- Dragons rarely attack me even when I attack them, and even when they do, they do not use many special attacks meaning that fighting them is rather easy

**Comment by Alex-the-666** [comment]
fixed egg placing in 1.1.1

dragons more agressive in 1.1.1
