### ISSUE TITLE
Problem Wandering Cyclops Chance and maybe other spawnrate, config file doesn't work

### ISSUE THREAD

**Issue by Darknight8151** [Alex-the-666/Ice_and_Fire#2510]
Hello, I have a monster spawn problem, even if I deactivate some spawn and restart the game it doesn't change anything ...
I even tried to reset the config file entirely by deleting it and relaunching the game nothing solves the problem, will it be fixed?
I try all but the config file doesn't work for the spawnrate, I see this problem on Wandering cyclops and hyppogryph in the desert I set to 1 the spawn Weight and they are too many...
I'm on Ice and Fire 1.9.1 on 1.12.2

https://i.imgur.com/Nl6cloc.png

https://i.imgur.com/LWe0Tqs.png

https://i.imgur.com/VPU55Ke.png

https://i.imgur.com/Jx6I9AQ.png

**Comment by Darknight8151** [comment]
Can I have help? :/

**Comment by Darknight8151** [comment]
Anyone have the same problem??? :/

**Comment by Darknight8151** [comment]
If anyone have a solution ... Cyclops attacks all mobs and creeper destroy my map because we CAN'T disable spawn of WANDERING CYCLOPS !

**Comment by Darknight8151** [comment]
The mod is dead or something? 🤔

**Comment by Darknight8151** [comment]
Still inactive this mod? 🤔

**Comment by Kodabeeer** [comment]
This mod is not inactive, it’s just that your report is due to your own idiocy. A spawn weight of 1 makes them extremely common, increase that number.

**Comment by Darknight8151** [comment]
I have try high number too already ... but yes this mod is inactive no?

**Comment by Kodabeeer** [comment]
No this mod is active, just because it hasn’t had an update in a while does not mean it is inactive. It is in the process of porting.

**Comment by Darknight8151** [comment]
The mod will be imported for a newer version of Minecraft and therefore won't have any 1.12.2 patch for any bugs currently reported by me or others?

**Comment by Carro1001** [comment]
It'll still receive bug fixes for the 1.12 version for a period of time, the dev is just currently focusing on other stuff

**Comment by Darknight8151** [comment]
ok as i saw a lot of bug posts reported and often no answer i was wondering :)

**Comment by mrcglaisek** [comment]
join the discord server if you want to get more prompt feedback https://discord.gg/ez8wkq
