### ISSUE TITLE
Dragon armor is too op

### ISSUE THREAD

**Issue by MasterValler** [Alex-the-666/Ice_and_Fire#2511]
in 1.12.2 a full set of dragon armor gives the player complete immunity to all player attacks (including tamed dragons) why idnt there a config that would allow people to disable it?

**Comment by PhoenixKnight777** [comment]
Yes. In the config file, you can disable Dragonsteel armor. If you don’t mean Dragonsteel, and just the scale armor, then no, if can’t be disabled.

**Comment by MasterValler** [comment]
not what i meant, i meant players are completely immune to other player's attacks just by wearing the full set of dragon armor (at least on the server)

**Comment by furretzu** [comment]
dragonsteel/dragon scale seem to have immunities to some things, when paired with a hydra heart, you can effectively tame a ampetheiter and never really die, and it seems to be probably a wierd thing

**Comment by TheMightyMcGrew** [comment]
you can set the dragonsteel armor with this config line 
    I:"Dragonsteel Base Armor"=12
