### ISSUE TITLE
Mausoleum problems

### ISSUE THREAD

**Issue by LUEZIS** [Alex-the-666/Ice_and_Fire#2514]
Mausoleum generating is totally broken and I set it in config to not generate, because of this fact, but despite this setting mausoleum is still generating and destroying landscape :-( (please ignore that purplish tower above mausoleum)
![2020-06-10_00 57 26](https://user-images.githubusercontent.com/40040593/84293412-08b07b00-ab48-11ea-91a2-391eaee5924e.png)

**Comment by HARRRRRIE** [comment]
Happened to me I reset the config fixed it

**Comment by Cakx** [comment]
I can confirm this issue on 1.9.1 with forge 14.23.5.2854.
A lot of Mausoleums generate on coast lines and are always placed incorrectly.

**Comment by QuantumExp** [comment]
That's not a Mausoleum. That's a Gorgon Temple. Please try to do a little research behind the structure you want to complain about before complaining. Mausoleums are enormous black structures found only in Snowy Tundras (Ice Plains), Ice Spikes, Ice Mountains, and Glaciers. Now then, Mausoleums can generate hanging from cliffs and over oceans, but that's not really a bug, just normal structure generation. Happens with several vanilla structures too. So, it's not really a bug, just vanilla structure generation.
