### ISSUE TITLE
Any dragon killed above Stage 1 leaves no corpse

### ISSUE THREAD

**Issue by AlertedCoyote** [Alex-the-666/Ice_and_Fire#2521]
Essentially as the title suggests. I'm using 1.9.1 Ice and Fire for MC 1.12.2, and when I kill a dragon older than stage 1, it disappears granting experience and nothing else. Quite irritating to be sure!

**Comment by WalterTheMighty** [comment]
That's intentional.

**Comment by Thethuthinnang** [comment]
Do you mean tamed dragons? I'm using the same version for MC 1.12.2, and I have killed several wild stage 3 dragons who all leave corpses that drop all the usual items. (They usually are vibrating or trembling in a weird, glitchy way when I first kill them. I have to leave and come back for them to be still.)

**Comment by TheSoupMaster** [comment]
I have the exact same problem
