### ISSUE TITLE
Extreme freezing issues with Stage 5 tamed dragon

### ISSUE THREAD

**Issue by Infusez** [Alex-the-666/Ice_and_Fire#2526]
I'm currently playing on a large modpack (MC Eternal) and have been running it smoothly; I've had no problems loading chunks and playing at a constant frame rate. However, after spawning a dragon from an egg my game I've began experiencing constant freezing and multiple crashes, making my game absolutely unplayable. This only happens when my dragon is down in the world, the moment I pick it up with a dragon horn I go back to running at a smooth framerate with no freezing or crashing. This also seems to only be happening with my tamed dragon, the two stage 5 dragons that I previously fought did not have any effect on my performance.

**Comment by Carro1001** [comment]
This is sadly a limitation with Minecraft itself, as it hates big entities, so a stage 5 dragon can lag the game quite a lot
