### ISSUE TITLE
Myrmex Queen statue still functions almost like a living queen.

### ISSUE THREAD

**Issue by conmeolatui** [Alex-the-666/Ice_and_Fire#2527]
The Myrmex Queen statue gotten from medusa head still lays eggs, burrows into the ground, and makes a Myrmex colony just like a normal queen despite being a statue.
It is still possible to mine it like a statue, but all other functions are still around.

**Comment by somebodyandnobody** [comment]
that happens with the taint seed from thaumcraft too
