### ISSUE TITLE
Dragon not getting in the horn and disappearing for the player

### ISSUE THREAD

**Issue by RockabillyKid** [Alex-the-666/Ice_and_Fire#2529]
Hi all,

I am playing since a week on a server with a few friends and we have a common bug, happening in different ways: If a player gets his dragon on its shoulder and then dismount, the player sees it as dismounted but the others are still seeing it on his shoulder, and the dragon is indeed on the shoulder, the only option is for the dragon-owner player to relog.

The second stage is with the dragon horn: about 4/5 times when a player tries to put his dragon inside the horn (no matter the stage), the dragon disappears for the player but it is still visible for the others (the dragon owner can still hear the dragon but can't interact with it if this happens). Same, the owner needs to relog in order for the dragon to reappear, and try again to put it in his horn.

I have read a thread about a similar problem on the internet: https://www.reddit.com/r/RLCraft/comments/ek446l/dragon_horn_glitch/
(problem explained in a different way but I believe it is the same).

I try /reload and other commands, and when discussing with the server staff they told me that the problem was mod side100%

Thanks a lot for your time and your help,

Rockabilly_Kid

**Comment by Krakenos** [comment]
I have the same issue on the server, using modpack "Roguelike Adventures and Dungeons 1.38", it has the latest version of Ice and Fire (1.9.1)
