### ISSUE TITLE
Mausoleum Generation

### ISSUE THREAD

**Issue by Skiafray** [Alex-the-666/Ice_and_Fire#2531]
I feel as though they are spawning in places they really shouldn't. Such as off the side of Cliffs, or Halfway in the Ocean. Would it be possible to make it so they only spawn in specific biomes?

**Comment by QuantumExp** [comment]
They only spawn in Snowy Tundras (Ice Plains), Ice Spikes, Ice Mountains, and Glaciers. Also, this isn't really a bug, more like a suggestion.
