### ISSUE TITLE
Hippogryphs Won't Breed

### ISSUE THREAD

**Issue by dracralyn** [Alex-the-666/Ice_and_Fire#2537]
I play on a dedicated server, and I can't seem to get my hippogryphs to breed. It worked once, right after I captured a second black one and bred it with the first black one I had, but that seems to have been the one and only time.

I have no issues on my single player game, and the server admins don't know of any restrictions they've set on anything Ice and Fire related.

I set them to wander with a stick, in an enclosed area so they can't fly away, and with no saddle or armor. I feed each of them their rabbit stew, and they just stare at each other with hearts all over the place. I've been trying for days and it only worked one time about a week ago.

**Comment by AlexLikesLlamas** [comment]
that happens to me too, i set them on wonder and wait for them to walk around because for some reason they wont walk around on wander they will just stay there, after that happens i leave and rejoin and breed them, thats what works for me.
