### ISSUE TITLE
Dragons Spawning Masivelly

### ISSUE THREAD

**Issue by SheroxGG** [Alex-the-666/Ice_and_Fire#2539]
I have Ice and fire installed on my modpack, and there are so many dragon spawns, the problem is that I am modifying the configuration to reduce it, and I have it really really low. But it is not working. I have spawning rate at 45, and they keep spawning like crazy. Any idea? Thaanks!

**Comment by Matterom** [comment]
So, if you're using the setting i think you are using. You've effectively increased the spawn chance by 20x if i remember the default right. What you want to do is turn the chance per chunk? Setting back upto about +50 or +150 to maybe up to 600 (Higher number reduces chance) And increase the world gen buffer between nests up to about 500, Generally you want to tune both numbers till you find a comfortable spawn distribution.
