### ISSUE TITLE
Dragon Riding Bugs

### ISSUE THREAD

**Issue by colejagdtiger** [Alex-the-666/Ice_and_Fire#254]
When riding a dragon I came across a couple of bugs that have not yet been reported.

1-When riding a dragon new chunks refuse to load making dragon flight not great for traveling.

2-When I try to have a dragon used an attack it does not, however for the breath weapon the sounds do play although there is no projectile or damage to the terrain.

**Comment by AlexModGuy** [comment]
fixed in 1.1.1
