### ISSUE TITLE
Insane Lag in Title Screen

### ISSUE THREAD

**Issue by Crix310** [Alex-the-666/Ice_and_Fire#2547]
Today I just discovered that Ice and Fire causes a massive lag in title screen. I don’t know what could cause it, but it’s never happened to me before in previous modpacks and I haven’t found anything on the internet about it. Do you know how to fix it? If you need it, here is my mod list:
![sfsfsffsfs](https://user-images.githubusercontent.com/47698695/85958052-04cb8800-b993-11ea-8a67-cdadb7ad0fac.png)

**Comment by Picono435** [comment]
Maybe disable the Ice And Fire custom menu?

**Comment by seraphicoria** [comment]
I had this same issue and after looking through all of my mods, the problem seemed to be caused by Prehistoric Eclipse and Obsidian Animator. It's really a shame, I really adored the mod's dino models.
