### ISSUE TITLE
Stuck dragons

### ISSUE THREAD

**Issue by Needstrongerexplosions** [Alex-the-666/Ice_and_Fire#2557]
I'm having issues where tamed dragons get sort of... Stuck?
For example, I'll hatch a dragon, pick it up, then try to put it down a short ways away. It'll teleport right back to where I picked it up from. This persists to adult sized. I tried to quit/reload but that's not working. 
It doesn't happen for creative tamed dragons.

**Comment by TheReptileMan** [comment]
Yes myself and friends are having the same issue, it only occurs when you pick the dragon up, we used dragon horns to unstick the dragon by picking them up and putting them down somewhere else but picking them up on your shoulder seems to bug them.
