### ISSUE TITLE
Dragon doesn't breath at dragon forge.

### ISSUE THREAD

**Issue by Jetprism** [Alex-the-666/Ice_and_Fire#2559]
I tried to rebuild the forge,change position for dragon,it didn't work.sometime it work with wild dragon.But when i tame it with creative dragon meal,the forge glitch and the dragon breath bar keep decrease

**Comment by DragonKing810** [comment]
i noticed this for tier 3-5 they dont do it at all

**Comment by milkev** [comment]
I tried using my tier 5 dragon for it but he doesnt like it either :C guess ill have to make a lower tier dragon so i can use the forge easier.
![2020-08-01_14 47 44](https://user-images.githubusercontent.com/22010128/89110371-41155c80-d407-11ea-9b2d-36502006d59a.png)
i ended up getting mine to work after much fiddling but like-
a fix would be awesome
