### ISSUE TITLE
Dragonforge doesn't require middle dragonforge bricks

### ISSUE THREAD

**Issue by Spinogaming** [Alex-the-666/Ice_and_Fire#2564]
![2020-07-07_12 12 57](https://user-images.githubusercontent.com/48093218/86715143-1e7f6600-c04a-11ea-8aa7-2e6e8ed2d1b0.png)
![Uploading 2020-07-07_12.13.01.png…]()

**Comment by BeepoWuff** [comment]
This was resolved by 4bb1034 for 1.15.2+
