### ISSUE TITLE
Korean 1.15.2 Translation

### ISSUE THREAD

**Issue by Garam1207** [Alex-the-666/Ice_and_Fire#2566]
Sorry for the late translation.
1.15.2 If you give me the lang file first, it will be helpful for translation.
[lang.zip](https://github.com/Alex-the-666/Ice_and_Fire/files/4891038/lang.zip)

**Comment by Carro1001** [comment]
The 1.15.2 github build has a lang file already if you wanna use it, may not be complete yet, though.

**Comment by Garam1207** [comment]
> 1.15.2 github 빌드에는 lang 파일이 이미 있는데 사용하고 싶다면 아직 완료되지 않았을 수 있습니다.

Can you give me the link?
