### ISSUE TITLE
Dragon doesnt even have a dead body

### ISSUE THREAD

**Issue by xDandGG** [Alex-the-666/Ice_and_Fire#2570]
The Titel.. could it be on other mods? cuase i have inventory pets and morph mod. As i said if i kill it, not even the skellet appears. I tried it a 2 fire and one ice dragon no one works

**Comment by Carro1001** [comment]
Morph mod causes this

**Comment by xDandGG** [comment]
ah thank u. Also very fast response

**Comment by xDandGG** [comment]
but... how even can i remove only one mod? i have aternos xD. i know im stupid

**Comment by CommandBlockGuru** [comment]
If I may, I have the same problem you have, and I've found a solution that doesn't involve getting rid of the morph mod. What I do is I walk a little bit away from the body, a bit past the render distance so it doesn't load in, then I go back and the body's there. I hope that helps. :)
