### ISSUE TITLE
Player crashes on join

### ISSUE THREAD

**Issue by JoeyDagger** [Alex-the-666/Ice_and_Fire#2571]
I can connect to my own modded 1.12.2 server I set up just fine. As soon as my girlfriend joins, she sits there for a few seconds and says she can't see anything, and disconnects. When we take this mod out she's fine. I really was excited for this mod and she was too. Logs are attached down below along with my mod list.

[2020-07-10-7.log.gz](https://github.com/Alex-the-666/Ice_and_Fire/files/4906361/2020-07-10-7.log.gz)
[2020-07-10-5.log.gz](https://github.com/Alex-the-666/Ice_and_Fire/files/4906368/2020-07-10-5.log.gz)
[2020-07-10-6.log.gz](https://github.com/Alex-the-666/Ice_and_Fire/files/4906370/2020-07-10-6.log.gz)

![image](https://user-images.githubusercontent.com/67937427/87217702-20bf1a00-c301-11ea-812c-5457e73b3e11.png)
![image](https://user-images.githubusercontent.com/67937427/87217704-2452a100-c301-11ea-9130-47d9cd609714.png)

**Comment by furretzu** [comment]
New news: it may have been something with the image below, because it has same time as your dc
![image](https://user-images.githubusercontent.com/68081783/87220142-7dd1c480-c32f-11ea-9969-4887c855af70.png)
![image](https://user-images.githubusercontent.com/68081783/87220153-8d510d80-c32f-11ea-8ecb-f9a20d3f6278.png)
also, it seems to be this mod in particular:
![image](https://user-images.githubusercontent.com/68081783/87220209-f3d62b80-c32f-11ea-84b3-4d7de5a86230.png)
Doing another check
7-10-7 logs have this
![image](https://user-images.githubusercontent.com/68081783/87221090-80d0b300-c337-11ea-96a8-fc03a4c98d69.png)
this means you clicked the disconnect button
![image](https://user-images.githubusercontent.com/68081783/87221121-a52c8f80-c337-11ea-88fd-c6cba45c76c6.png)
it seems the same here...
only 7-10-5 logs have the error caused...

**Comment by JoeyDagger** [comment]
> 
> 
> New news: it may have been something with the image below, because it has same time as your dc
> ![image](https://user-images.githubusercontent.com/68081783/87220142-7dd1c480-c32f-11ea-9969-4887c855af70.png)
> ![image](https://user-images.githubusercontent.com/68081783/87220153-8d510d80-c32f-11ea-8ecb-f9a20d3f6278.png)
> also, it seems to be this mod in particular:
> ![image](https://user-images.githubusercontent.com/68081783/87220209-f3d62b80-c32f-11ea-84b3-4d7de5a86230.png)
> Doing another check
> 7-10-7 logs have this
> ![image](https://user-images.githubusercontent.com/68081783/87221090-80d0b300-c337-11ea-96a8-fc03a4c98d69.png)
> this means you clicked the disconnect button
> ![image](https://user-images.githubusercontent.com/68081783/87221121-a52c8f80-c337-11ea-88fd-c6cba45c76c6.png)
> it seems the same here...
> only 7-10-5 logs have the error caused...

I appreciate your quick response, but I wasn't the one disconnecting. Sorry, I should have been more specific. puppylovebug03 is my girlfriend. She would crash or lose connection each time. 

Also I know the disconnections were us manually leaving. We leave sometimes either when the nether is broken or before we shut down the server. 

But like I said, I have no problem at all with my server. I can connect and play just fine. It's my girlfriend's side that doesn't work.

**Comment by JoeyDagger** [comment]
I'm using the latest version, 1.9.1.

**Comment by LucyLeviathan** [comment]
I'm having the same issue and I'm not sure what it is. I am sure it is caused by Ice and fire though...

**Comment by LucyLeviathan** [comment]
Here's the crash report

[crash-2020-07-12_02.11.40-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/4908157/crash-2020-07-12_02.11.40-client.txt)

**Comment by furretzu** [comment]
i guess ill take a look through the logs
new update: it seems it has been ticking entities, i had this issue too, with deathworms, when i tried to ride one.

**Comment by LucyLeviathan** [comment]
Any clues on how to fix it? You can delete the region file to fix the current issue but it will eventually happen again with a different entity.

**Comment by furretzu** [comment]
> > New news: it may have been something with the image below, because it has same time as your dc
> > ![image](https://user-images.githubusercontent.com/68081783/87220142-7dd1c480-c32f-11ea-9969-4887c855af70.png)
> > ![image](https://user-images.githubusercontent.com/68081783/87220153-8d510d80-c32f-11ea-8ecb-f9a20d3f6278.png)
> > also, it seems to be this mod in particular:
> > ![image](https://user-images.githubusercontent.com/68081783/87220209-f3d62b80-c32f-11ea-84b3-4d7de5a86230.png)
> > Doing another check
> > 7-10-7 logs have this
> > ![image](https://user-images.githubusercontent.com/68081783/87221090-80d0b300-c337-11ea-96a8-fc03a4c98d69.png)
> > this means you clicked the disconnect button
> > ![image](https://user-images.githubusercontent.com/68081783/87221121-a52c8f80-c337-11ea-88fd-c6cba45c76c6.png)
> > it seems the same here...
> > only 7-10-5 logs have the error caused...
> 
> I appreciate your quick response, but I wasn't the one disconnecting. Sorry, I should have been more specific. puppylovebug03 is my girlfriend. She would crash or lose connection each time.
> 
> Also I know the disconnections were us manually leaving. We leave sometimes either when the nether is broken or before we shut down the server.
> 
> But like I said, I have no problem at all with my server. I can connect and play just fine. It's my girlfriend's side that doesn't work.

if you can get your gf to send you a error log to you, then you send it to me, i may be able to find the issue and point it out
