### ISSUE TITLE
Toggling Tamed dragon griefing changes nothing

### ISSUE THREAD

**Issue by TheMightyMcGrew** [Alex-the-666/Ice_and_Fire#2572]
Tamed dragons will still insta-convert any block to charred versions of its respective block type (i.e. diamond blocks to charred stone) as well as the random fireball attack during breathing just outright erasing blocks, like a good TNT explosion size chunk of blocks. All this in spite of me toggling the B:"Tamed Dragon Griefing"=false

Ice&Fire Version 1.9.1 MC 1.12.2

**Comment by Spinogaming** [comment]
Did you not read the tooltip of the config?
0 os default, 1 is breaking weak blocks, and 2 is no griefing

**Comment by TheMightyMcGrew** [comment]
ok so tamed and wild dragons do still follow the same rules?

**Comment by TheMightyMcGrew** [comment]
and for that matter, wth is default. I get that config and all, but what does default even mean in this case?
