### ISSUE TITLE
Tamed dragon bugs

### ISSUE THREAD

**Issue by SaphiSnap** [Alex-the-666/Ice_and_Fire#2573]
So, first off, when I perch a baby dragon and then take it off my shoulder, it would teleport back to where it originally was before I picked it up and its movements are still orientated with mine and even if I set it to escort or wander, it'll remain in the same place but will turn where I'm looking. And then it teleported to me when I fell in some water. Dunno why. Bug number two involves dragon duplication. When I put a dragon in a dragon horn, I could still hear its roars and, if it was in the water, I could see the splashing particles despite it being in my horn still. I'd travel to a different dimension and back and the dragon was still there as if I hadn't stored it away. So I duplicated it.

**Comment by SaphiSnap** [comment]
Side note that I was playing RLcraft when this happened (I did update to the most recent Ice and Fire mod). Not too sure if that's what caused it.

**Comment by Kngak** [comment]
I've been having the same problem with the first issue you stated!

**Comment by FlamingSharky** [comment]
Yeah same, been having it since latest update. They wont even follow me when I tell them too. I even unload and reload the chunk

**Comment by NobleDraconian** [comment]
Related : https://github.com/Alex-the-666/Ice_and_Fire/issues/2680
