### ISSUE TITLE
Dragons teleport back to where you shift right clicked to ride them.

### ISSUE THREAD

**Issue by epicslayer999** [Alex-the-666/Ice_and_Fire#258]
As the title says, when you shift right click a Dragon old enough to be ridden and ride it, you can't hear the flapping of the wings, and once you dismount they teleport back to where they were before. Players could lose their Dragons if they make a huge trip by having the dragon just teleport back to where it was. This happened with a Fire Dragon.

**Comment by AlexModGuy** [comment]
duplicate
