### ISSUE TITLE
More tamed dragon issues :D

### ISSUE THREAD

**Issue by SaphiSnap** [Alex-the-666/Ice_and_Fire#2581]
Alright, so, I'd put my dragon in the dragon horn but when I'd try to move the dragon horn around in my inventory it didn't say it had the dragon inside it and the only way to set it back to normal was to save n quit or entering a different dimension. Practically the same thing was happening with Dragon summoning crystals, I'd bind it to my dragon and when I moved it in my inventory it wasn't bound. The only time I would know it was bounded to the crystal is if the sound effect played when I did it.
Next issue, I'd put my dragon on escort and back to sitting, but the dragon still followed me nonetheless?? It was in the sitting position, too, and no matter if I set it to wander, escort, or sit it would still follow me...

**Comment by liam124** [comment]
It’s happening to me too but do t know how to fix
