### ISSUE TITLE
Mobs form I&F targetting player from very far

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#2584]
Hello , 

Idk if it is normal or not but mobs from the mod are targetting us (every players on the server) form very far, like 100 to 200 blocks. Idk if its a feature but its rly annoying as we are just starting the survival and we get spawnkilled by them everytime. Also they seem not to lose the aggro even when underground / behind blocks

**Comment by SamuraiShogun1102** [comment]
I figured out that certain mobs underground like raiders that attack others, including dragon woke them up and find you.

**Comment by ghost** [comment]
I found a solution for the targetting range: in the config file of the mod
there is a line about targetting range. By default its set to 128 blocks '-'
