### ISSUE TITLE
Troll bug

### ISSUE THREAD

**Issue by lowisnoking** [Alex-the-666/Ice_and_Fire#2589]
I was going to my base at night and in the there was a room where a troll spawn [normal there was no ligth], but the problem is he moved 2sec and after that, he was like in stone... I tried to kill him but did nothing. I tried to restart my game, doesn't affect.
I don't know what to do.

![2020-07-24_10 09 23](https://user-images.githubusercontent.com/68743476/88400800-d9bc3480-cd96-11ea-98d2-df00141c1db8.png)

![2020-07-24_10 17 38](https://user-images.githubusercontent.com/68743476/88400855-eccf0480-cd96-11ea-8d38-b8a253400fcc.png)

**Comment by SmokePuddingEveryday** [comment]
I also get the same bug. For some reason, hitting him with a pickaxe causes his entire body to disappear but his weapon floats in midair.

**Comment by SmokePuddingEveryday** [comment]
Why did you close the issue? Did you ever find a solution?
