### ISSUE TITLE
Bugs in the mod

### ISSUE THREAD

**Issue by TinyFloof** [Alex-the-666/Ice_and_Fire#2591]
Hello there, 
I'm here to report some bugs I found (or think i found) in the latest version of the mod.
EDIT: I can send video proof if needed.

1. I was able to duplicate my dragons in Creative Mode. Once put in the horn, I could still hear the roar so I relogged. after coming back my dragon was still next to me. Checking the inventory showed my dragon is in the horn. so I put the other dragon in a horn as well. Now I had two completely identical dragons down to the name. 

2. After putting a baby dragon on my shoulder and putting it back down, if i turn my head the dragon follows like it were still on my shoulder.

3. F5 view from the front is on the side (could be intentional but not sure) 
![2020-07-26_00 53 34](https://user-images.githubusercontent.com/64585200/88467922-b7343380-cedc-11ea-851f-3248816a92a2.png)
![2020-07-26_00 55 06](https://user-images.githubusercontent.com/64585200/88467924-b9968d80-cedc-11ea-865e-a6f7a6c64e49.png)

**Comment by SaphiSnap** [comment]
I think the F5 shoulder view is intentional since the dragon itself blocks most of the screen
