### ISSUE TITLE
You can feed wheat to dragon skulls.

### ISSUE THREAD

**Issue by MightyGoat4242** [Alex-the-666/Ice_and_Fire#2594]
If you feed skulls wheat they make heart particles.
You can't seem to milk them or breed them, altough I haven't tried shearing them.

**Comment by furretzu** [comment]
thats a waste of wheat, or you can waste your food?

**Comment by SaphiSnap** [comment]
dragon skulls be like: mm weet

**Comment by SaphiSnap** [comment]
Apparently all types of skulls can be fed wheat. Huh.

**Comment by MightyGoat4242** [comment]
Yup, they all seem to be herbivores
I am pretty sure that you can't shear or interact with them in any other way though.

**Comment by Grimnott** [comment]
They're vegans, clearly an intended feature.
