### ISSUE TITLE
Myrmex bugs (No pun intended)

### ISSUE THREAD

**Issue by SaphiSnap** [Alex-the-666/Ice_and_Fire#2598]
Aight so first one involves myrmex eggs. Whenever I grab one myrmex egg it duplicates itself no matter the type. It's useful for farming myrmex items and myrmex resin chunks but it's pretty ridiculous.
Second bug involves jungle myrmex. Even though the rest of the jungle myrmex use jungle myrmex resin chunks, the queen... doesn't. The jungle myrmex queen takes desert myrmex resin for desert myrmex eggs...

**Comment by somebodyandnobody** [comment]
that second bug happens to desert myrmex too. the worker egg trade is for jungle myrmex. jungle resin for a jungle egg. how does that queen get a jungle worker egg?

**Comment by democat3457** [comment]
First bug I can reproduce with smacking myrmex eggs with a Spartan Weaponry reach weapon.

**Comment by somebodyandnobody** [comment]
it seems sometimes the trades get messed up and the myrmex want/give resin of the other type

**Comment by democat3457** [comment]
dupe bug still happens btw

**Comment by democat3457** [comment]
https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/issues/452
