### ISSUE TITLE
Shoting arrw at dragoon raises exception and crashes server

### ISSUE THREAD

**Issue by PurryFury** [Alex-the-666/Ice_and_Fire#2599]
So i made a forge server too play with friends any hit on dragon is not registered and when shot with arrow it kills the server.

**Crash Report:**

---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 2020-07-29 12:53:41 CAT
Description: Ticking entity

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/culling/ICamera
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
    at java.lang.Class.getDeclaredMethod(Unknown Source)
    at io.github.xcube16.iseedragons.ISeeDragons.getMethodInHierarchy(ISeeDragons.java:558)
    at io.github.xcube16.iseedragons.ISeeDragons.getMethodInHierarchy(ISeeDragons.java:561)
    at io.github.xcube16.iseedragons.ISeeDragons.livingEntityAttacked(ISeeDragons.java:431)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_994_ISeeDragons_livingEntityAttacked_LivingAttackEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:586)
    at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:857)
    at net.minecraft.entity.passive.EntityAnimal.attackEntityFrom(SourceFile:66)
    at com.github.alexthe666.iceandfire.entity.EntityDragonBase.attackEntityFrom(EntityDragonBase.java:1457)
    at com.github.alexthe666.iceandfire.entity.EntityMutlipartPart.attackEntityFrom(EntityMutlipartPart.java:30)
    at net.minecraft.entity.projectile.EntityArrow.onHit(EntityArrow.java:369)
    at net.minecraft.entity.projectile.EntityArrow.onUpdate(EntityArrow.java:267)
    at net.minecraft.entity.projectile.EntityTippedArrow.onUpdate(SourceFile:98)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.World.redirect$zbd000$updateEntity(World.java:5123)
    at net.minecraft.world.World.updateEntities(World.java:1762)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.culling.ICamera
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 28 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: minecraft:arrow (net.minecraft.entity.projectile.EntityTippedArrow)
  Entity ID: 62396
  Entity Name: Arrow
  Entity's Exact location: 749.32, 74.17, 81.15
  Entity's Block location: World: (749,74,81), Chunk: (at 13,4,1 in 46,5; contains blocks 736,0,80 to 751,255,95), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
  Entity's Momentum: -0.97, -0.91, -2.52
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {damage:2.0d,ForgeData:{"endercore:xpboost":-1},shake:0b,xTile:-1,Invulnerable:0b,PortalCooldown:0,life:0s,FallDistance:0.0f,inTile:"minecraft:air",zTile:-1,yTile:-1,ForgeCaps:{"mujmajnkraftsbettersurvival:arrowproperties":{NoDrag:0b,CanRecover:0b,CanDestroyBlocks:0b,ExplosionPower:0.0f},"llibrary:extendedentitydatacapability":{}},Motion:[-0.9726151436654957d,-0.912716622219916d,-2.5160492175366107d],UUIDLeast:-6120752434076502822L,inGround:0b,pickup:2b,Air:300s,OnGround:0b,Dimension:0,Rotation:[-158.86533f,-14.323364f],UpdateBlocked:0b,UUIDMost:3289041037494797103L,inData:0b,crit:1b,Pos:[749.3228763195422d,74.17099777137295d,81.14709905299479d],Fire:-1s,SurgeAABB:[749.0728763195422d,74.17099777137295d,80.89709905299479d,749.5728763195422d,74.67099777137295d,81.39709905299479d]}

-- Affected level --
  Level name: world
  All players: 1 total; [EntityPlayerMP['PurryFury'/5130, l='world', x=760.69, y=79.87, z=110.56]]
  Chunk stats: ServerChunkCache: 351 Drop: 0
  Level seed: -4493073900637243012
  Level generator: ID 09 - WildNature, ver 0. Features enabled: true
  Level generator options: {"diamondSize":8,"lapisCenterHeight":16,"lavaLakeChance":80,"redstoneMaxHeight":16,"diamondMaxHeight":16,"coalMaxHeight":128,"coalMinHeight":0,"seaLevel":63,"graniteCount":10,"riverSize":4,"gravelMinHeight":0,"graniteSize":33,"redstoneSize":8,"fixedBiome":-1,"waterLakeChance":4,"dioriteMinHeight":0,"andesiteCount":10,"graniteMaxHeight":80,"redstoneMinHeight":0,"lapisSize":7,"dirtCount":10,"ironMinHeight":0,"dioriteMaxHeight":80,"coalCount":20,"gravelCount":8,"coalSize":17,"gravelSize":33,"ironMaxHeight":64,"lapisSpread":16,"dioriteCount":10,"andesiteSize":33,"biomeSize":4,"graniteMinHeight":0,"goldCount":2,"diamondCount":1,"dirtSize":33,"gravelMaxHeight":256,"goldSize":9,"ironCount":20,"diamondMinHeight":0,"ironSize":9,"redstoneCount":8,"andesiteMinHeight":0,"dioriteSize":33,"goldMaxHeight":32,"dungeonChance":8,"andesiteMaxHeight":80,"dirtMinHeight":0,"lapisCount":1,"goldMinHeight":0,"dirtMaxHeight":256,"lowerLimitScale":512.0,"biomeDepthOffset":0.0,"upperLimitScale":512.0,"heightScale":684.412,"biomeScaleWeight":1.0,"biomeDepthWeight":1.0,"mainNoiseScaleZ":80.0,"mainNoiseScaleY":160.0,"depthNoiseScaleX":200.0,"mainNoiseScaleX":80.0,"baseSize":8.5,"depthNoiseScaleZ":200.0,"stretchY":12.0,"depthNoiseScaleExponent":0.5,"biomeScaleOffset":0.0,"coordinateScale":684.412,"useStrongholds":true,"useMineShafts":true,"useTemples":true,"useLavaOceans":false,"useCaves":true,"useWaterLakes":true,"useLavaLakes":true,"useMonuments":true,"useRavines":true,"useDungeons":true,"useVillages":true}
  Level spawn location: World: (469,64,223), Chunk: (at 5,4,15 in 29,13; contains blocks 464,0,208 to 479,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 347378 game time, 11739 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 113816 (now: false), thunder time: 125885 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 1.8.0_261, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 2619726744 bytes (2498 MB) / 3741319168 bytes (3568 MB) up to 3817865216 bytes (3641 MB)
  JVM Flags: 2 total; -Xmx4096M -Xms2048M
  IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 122 mods loaded, 122 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                                | Version               | Source                                             | Signature                                |
       |:------ |:--------------------------------- |:--------------------- |:-------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                         | 1.12.2                | minecraft.jar                                      | None                                     |
       | LCHIJA | mcp                               | 9.42                  | minecraft.jar                                      | None                                     |
       | LCHIJA | FML                               | 8.0.99.99             | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                             | 14.23.5.2854          | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | ivtoolkit                         | 1.3.3-1.12            | minecraft.jar                                      | None                                     |
       | LCHIJA | otgcore                           | 1.12.2 - v8.3         | minecraft.jar                                      | None                                     |
       | LCHIJA | foamfixcore                       | 7.7.4                 | minecraft.jar                                      | None                                     |
       | LCHIJA | damageindicatorsmod               | 1.0                   | %5b1.12.2%5dDamageIndicatorsMod-3.5.1.jar          | None                                     |
       | LCHIJA | actuallyadditions                 | 1.12.2-r151           | ActuallyAdditions-1.12.2-r151-2.jar                | None                                     |
       | LCHIJA | forgeendertech                    | 1.12.2-4.5.2.0        | ForgeEndertech-1.12.2-4.5.2.0-build.0459.jar       | None                                     |
       | LCHIJA | adlods                            | 1.12.2-1.0.8.0        | AdLods-1.12.2-1.0.8.0-build.0504.jar               | None                                     |
       | LCHIJA | alcatrazcore                      | 1.0.4                 | alcatrazcore-1.0.4.jar                             | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
       | LCHIJA | jei                               | 4.15.0.296            | jei_1.12.2-4.15.0.296.jar                          | None                                     |
       | LCHIJA | appleskin                         | 1.0.14                | AppleSkin-mc1.12-1.0.14.jar                        | None                                     |
       | LCHIJA | aquaculture                       | 1.6.8                 | Aquaculture-1.12.2-1.6.8.jar                       | None                                     |
       | LCHIJA | aquaticarmors                     | 1.0                   | aquaticarmors-1.0.1.jar                            | None                                     |
       | LCHIJA | carrots                           | 1.0.0b1               | carrotslib-mc1.12.2-1.0.0b1.jar                    | None                                     |
       | LCHIJA | armorunder                        | 1.0.0                 | armorunder-mc1.12.2-1.0.0.jar                      | None                                     |
       | LCHIJA | mantle                            | 1.12-1.3.3.55         | Mantle-1.12-1.3.3.55.jar                           | None                                     |
       | LCHIJA | biomesoplenty                     | 7.0.1.2441            | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar      | None                                     |
       | LCHIJA | redstoneflux                      | 2.1.1                 | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
       | LCHIJA | cofhcore                          | 4.6.6                 | CoFHCore-1.12.2-4.6.6.1-universal.jar              | None                                     |
       | LCHIJA | boptools                          | 0.0.3                 | boptools-1.12-0.0.3.0.jar                          | None                                     |
       | LCHIJA | baubles                           | 1.5.2                 | Baubles-1.12-1.5.2.jar                             | None                                     |
       | LCHIJA | endercore                         | 1.12.2-0.5.76         | EnderCore-1.12.2-0.5.76.jar                        | None                                     |
       | LCHIJA | enderio                           | 5.2.59                | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
       | LCHIJA | enderiointegrationtic             | 5.2.59                | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
       | LCHIJA | quark                             | r1.6-179              | Quark-r1.6-179.jar                                 | None                                     |
       | LCHIJA | tconstruct                        | 1.12.2-2.13.0.183     | TConstruct-1.12.2-2.13.0.183.jar                   | None                                     |
       | LCHIJA | conarm                            | 1.2.5.9               | conarm-1.12.2-1.2.5.9.jar                          | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCHIJA | armoryexpansion                   | 1.4.2                 | armoryexpansion-1.4.2.jar                          | None                                     |
       | LCHIJA | armoryexpansion-custommaterials   | 1.4.2                 | armoryexpansion-1.4.2.jar                          | None                                     |
       | LCHIJA | llibrary                          | 1.7.19                | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | iceandfire                        | 1.9.1                 | iceandfire-1.9.1-1.12.2.jar                        | None                                     |
       | LCHIJA | armoryexpansion-iceandfire        | 1.4.2                 | armoryexpansion-1.4.2.jar                          | None                                     |
       | LCHIJA | armoryexpansion-matteroverdrive   | 1.4.2                 | armoryexpansion-1.4.2.jar                          | None                                     |
       | LCHIJA | atop                              | 1.5                   | ATOP-1.12.2-v.1.5.jar                              | None                                     |
       | LCHIJA | autoreglib                        | 1.3-32                | AutoRegLib-1.3-32.jar                              | None                                     |
       | LCHIJA | mmdlib                            | 1.0.0-rc2             | MMDLib-1.12-1.0.0-rc2.36.jar                       | None                                     |
       | LCHIJA | basemetals                        | 2.5.0-rc2             | BaseMetals-1.12-2.5.0-rc2.332.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | baseminerals                      | 2.5.0-rc2             | BaseMinerals-1.12-2.5.0-rc2.69.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | battletowers                      | 1.6.5                 | BattleTowers-1.12.2.jar                            | None                                     |
       | LCHIJA | mujmajnkraftsbettersurvival       | 1.4.1                 | better_survival-1.4.1.jar                          | None                                     |
       | LCHIJA | betternether                      | 0.1.8.6               | betternether-0.1.8.6.jar                           | None                                     |
       | LCHIJA | bibliocraft                       | 2.4.5                 | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
       | LCHIJA | bookshelf                         | 2.3.590               | Bookshelf-1.12.2-2.3.590.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | codechickenlib                    | 3.2.3.358             | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | brandonscore                      | 2.4.18                | BrandonsCore-1.12.2-2.4.18.210-universal.jar       | None                                     |
       | LCHIJA | chameleon                         | 1.12-4.1.3            | Chameleon-1.12-4.1.3.jar                           | None                                     |
       | LCHIJA | chunkpregenerator                 | 2.1                   | Chunk+Pregenerator+V1.12-2.3.jar                   | None                                     |
       | LCHIJA | clumps                            | 3.1.2                 | Clumps-3.1.2.jar                                   | None                                     |
       | LCHIJA | cofhworld                         | 1.4.0                 | CoFHWorld-1.12.2-1.4.0.1-universal.jar             | None                                     |
       | LCHIJA | comforts                          | 1.4.1.3               | comforts-1.12.2-1.4.1.3.jar                        | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCHIJA | customspawner                     | 3.11.4                | CustomMobSpawner-3.11.5.jar                        | None                                     |
       | LCHIJA | cyclicmagic                       | 1.20.3                | Cyclic-1.12.2-1.20.3.jar                           | 0e5cb559be7d03f3fc18b8cba547d663e25f28af |
       | LCHIJA | draconicevolution                 | 2.3.25                | Draconic-Evolution-1.12.2-2.3.25.351-universal.jar | None                                     |
       | LCHIJA | mocreatures                       | 12.0.5                | DrZharks MoCreatures Mod-12.0.5.jar                | None                                     |
       | LCHIJA | sereneseasons                     | 1.2.18                | SereneSeasons-1.12.2-1.2.18-universal.jar          | None                                     |
       | LCHIJA | orelib                            | 3.6.0.1               | OreLib-1.12.2-3.6.0.1.jar                          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dsurround                         | 3.6.1.0               | DynamicSurroundings-1.12.2-3.6.1.0.jar             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | reccomplex                        | 1.4.8.2               | RecurrentComplex-1.4.8.2.jar                       | None                                     |
       | LCHIJA | dynamictrees                      | 1.12.2-0.9.8          | DynamicTrees-1.12.2-0.9.8.jar                      | None                                     |
       | LCHIJA | dynamictreesbop                   | 1.12.2-1.4.1e         | DynamicTreesBOP-1.12.2-1.4.1e.jar                  | None                                     |
       | LCHIJA | enderiobase                       | 5.2.59                | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
       | LCHIJA | enderioconduits                   | 5.2.59                | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
       | LCHIJA | enderioconduitsappliedenergistics | 5.2.59                | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
       | LCHIJA | enderioconduitsopencomputers      | 5.2.59                | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
       | LCHIJA | enderioconduitsrefinedstorage     | 5.2.59                | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
       | LCHIJA | enderiointegrationforestry        | 5.2.59                | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
       | LCHIJA | enderiointegrationticlate         | 5.2.59                | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
       | LCHIJA | enderiomachines                   | 5.2.59                | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
       | LCHIJA | enderiopowertools                 | 5.2.59                | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
       | LCHIJA | exoticbirds                       | 1.0                   | Exotic+Birds+1.12.2-3.2.0.jar                      | None                                     |
       | LCHIJA | falling_tree                      | 2.1.0                 | FallingTree-1.12.2-2.1.0%2B25.jar                  | None                                     |
       | LCHIJA | familiarfauna                     | 1.0.11                | FamiliarFauna-1.12.2-1.0.11.jar                    | None                                     |
       | LCHIJA | mod_lavacow                       | 1.1.0                 | Fish%27s+Undead+Rising-1.1.0b.jar                  | None                                     |
       | LCHIJA | foamfix                           | 0.10.10-1.12.2        | foamfix-0.10.10-1.12.2.jar                         | None                                     |
       | LCHIJA | forgelin                          | 1.8.4                 | Forgelin-1.8.4.jar                                 | None                                     |
       | LCHIJA | ichunutil                         | 7.2.2                 | iChunUtil-1.12.2-7.2.2.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | infernalmobs                      | 1.7.6                 | InfernalMobs-1.12.2.jar                            | None                                     |
       | LCHIJA | ironchest                         | 1.12.2-7.0.67.844     | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
       | LCHIJA | iseedragons                       | 0.12                  | ISeeDragons-0.12.jar                               | None                                     |
       | LCHIJA | journeymap                        | 1.12.2-5.7.1          | journeymap-1.12.2-5.7.1.jar                        | None                                     |
       | LCHIJA | libraryex                         | 1.1.3                 | LibraryEx-1.12.2-1.1.3.jar                         | None                                     |
       | LCHIJA | lycanitesmobs                     | 2.0.7.2 - MC 1.12.2   | lycanitesmobs-1.12.2-2.0.7.2.jar                   | None                                     |
       | LCHIJA | malisiscore                       | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                       | None                                     |
       | LCHIJA | malisisdoors                      | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                      | None                                     |
       | LCHIJA | mekanism                          | 1.12.2-9.8.3.390      | Mekanism-1.12.2-9.8.3.390.jar                      | None                                     |
       | LCHIJA | mekanismtools                     | 1.12.2-9.8.3.390      | MekanismTools-1.12.2-9.8.3.390.jar                 | None                                     |
       | LCHIJA | mobends                           | 1.0.0-beta-20.06.20   | MoBends_1.12.2-1.0.0-beta-20.06.20.jar             | None                                     |
       | LCHIJA | msmlegacy                         | @VERSION@             | MoreSwordsLegacy-1.12.2-1.0.7.jar                  | None                                     |
       | LCHIJA | mowziesmobs                       | 1.5.6                 | mowziesmobs-1.5.6.jar                              | None                                     |
       | LCHIJA | multimob                          | 1.0.5                 | multimob-1.0.5.jar                                 | None                                     |
       | LCHIJA | netherendingores                  | 1.12.2-1.4.1          | Netherending-Ores-1.12.2-1.4.1.jar                 | None                                     |
       | LCHIJA | netherex                          | 2.1.7                 | NetherEx-1.12.2-2.1.7.jar                          | None                                     |
       | LCHIJA | orespawn                          | 3.3.1                 | OreSpawn-1.12-3.3.1.179.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | patchouli                         | 1.0-21                | Patchouli-1.0-21.jar                               | None                                     |
       | LCHIJA | potioncore                        | 1.9_for_1.12.2        | PotionCore-1.9_for_1.12.2.jar                      | None                                     |
       | LCHIJA | qualitytools                      | 1.0.7_for_1.12.2      | QualityTools-1.0.7_for_1.12.2.jar                  | None                                     |
       | LCHIJA | quarkoddities                     | 1                     | QuarkOddities-1.12.2.jar                           | None                                     |
       | LCHIJA | xreliquary                        | 1.12.2-1.3.4.796      | Reliquary-1.12.2-1.3.4.796.jar                     | None                                     |
       | LCHIJA | additionalstructures              | 2.3.1                 | Rex%27s-Additional-Structures-1.12.x-(v.2.3.1).jar | None                                     |
       | LCHIJA | roguelike                         | 1.8.0                 | RoguelikeDungeons-1.12.2-1.8.0.jar                 | None                                     |
       | LCHIJA | ruins                             | 17.2                  | Ruins-1.12.2.jar                                   | None                                     |
       | LCHIJA | spartanweaponry                   | beta 1.3.8            | SpartanWeaponry-1.12.2-beta-1.3.8.jar              | None                                     |
       | LCHIJA | spartanbm                         | 0.3                   | spartanbm-0.3.jar                                  | None                                     |
       | LCHIJA | spartanfire                       | 0.08                  | spartanfire-0.08.jar                               | None                                     |
       | LCHIJA | spartanshields                    | 1.5.4                 | SpartanShields-1.12.2-1.5.4.jar                    | None                                     |
       | LCHIJA | spartanweaponryarcana             | beta 1.0.3            | SpartanWeaponryArcana-1.12.2-beta-1.0.3.jar        | None                                     |
       | LCHIJA | spawnercontrol                    | 1.6.3b                | SpawnerControl-1.6.3b.jar                          | None                                     |
       | LCHIJA | storagedrawers                    | 5.2.2                 | StorageDrawers-1.12.2-5.4.2.jar                    | None                                     |
       | LCHIJA | surge                             | 2.0.77                | Surge-1.12.2-2.0.77.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | vanillafix                        | 1.0.10-150            | VanillaFix-1.0.10-150.jar                          | None                                     |
       | LCHIJA | variedcommodities                 | 1.12.2                | VariedCommodities_1.12.2(21nov19).jar              | None                                     |
       | LCHIJA | varodd                            | 5.2                   | varodd-1.12.2-5.2.jar                              | None                                     |
       | LCHIJA | waystones                         | 4.1.0                 | Waystones_1.12.2-4.1.0.jar                         | None                                     |
       | LCHIJA | wildnature                        | 1.2                   | wildnature-1.2.jar                                 | None                                     |
       | LCHIJA | worleycaves                       | 1.5.1                 | worleycaves-1.5.1.jar                              | None                                     |
       | LCHIJA | betteranimalsplus                 | 9.0.1                 | betteranimalsplus-1.12.2-9.0.1.jar                 | None                                     |
       | LCHIJA | phosphor-lighting                 | 1.12.2-0.2.6          | phosphor-1.12.2-0.2.6%2Bbuild50-universal.jar      | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LCHIJA | armoryexpansion-conarm            | 1.4.2                 | armoryexpansion-1.4.2.jar                          | None                                     |
       | LCHIJA | osv                               | 5.0                   | Ore+Stone+Variants-5.1-1.12-r1.jar                 | None                                     |
  Loaded coremods (and transformers): TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
                                        
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
                                        mekanism.coremod.KeybindingMigrationHelper
                                      OTGCorePlugin (OTG-Core.jar)
                                        com.pg85.otg.forge.asm.excluded.OTGClassTransformer
                                      CorePlugin (ForgeEndertech-1.12.2-4.5.2.0-build.0459.jar)
                                        
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      iceandfire (iceandfire-1.9.1-1.12.2.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      BetterFoliageLoader (BetterFoliage-MC1.12-2.3.1.jar)
                                        mods.betterfoliage.loader.BetterFoliageTransformer
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
                                        
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
                                        
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6%2Bbuild50-universal.jar)
                                        
                                      LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
                                        lumien.chunkanimator.asm.ClassTransformer
  Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                              * Offline mode for dedicated servers is NOT supported by Ender IO.
                             This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
            Authlib is : /C:/Users/Egor/Desktop/minecraft/minecraft_server.1.12.2.jar
            
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - quarkIntegration (Enabled/Not Forced)
  Suspected Mods: ISeeDragons (iseedragons), Ice and Fire (iceandfire)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 20; [EntityPlayerMP['PurryFury'/5130, l='world', x=760.69, y=79.87, z=110.56]]
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server (map_server.txt)

**Comment by AdleyBro** [comment]
We have the same problem. The difference is that I throw a javelin instead of an arrow. In singleplayer there is no problem, tho. It may be a situational bug, because in our server the dragon couldn't be attacked by any way, and neither it could attack us; it was just standing on the floor, rotating itself and moving its wings but we couldn't attack it (melee) or be attacked by it, but throwing the javeling crashed the server. The version is 1.12.2

**Comment by PurryFury** [comment]
> 
> 
> We have the same problem. The difference is that I throw a javelin instead of an arrow. In singleplayer there is no problem, tho. It may be a situational bug, because in our server the dragon couldn't be attacked by any way, and neither it could attack us; it was just standing on the floor, rotating itself and moving its wings but we couldn't attack it (melee) or be attacked by it, but throwing the javeling crashed the server. The version is 1.12.2

Yeah I figured out the issue. Some mods were not implemented to be used on the server and so are dragon, so when you hit a dragon with an arrow, since you can't hit it with a sword, it detects a collision but can't actually reduce the HP since dragon object is messed up in multi and so the server hits a dead end cause it can't resolve dragon as in-game object.
