### ISSUE TITLE
impossible to get Gray and Silver egg dragons from breeding

### ISSUE THREAD

**Issue by Nao-stuff** [Alex-the-666/Ice_and_Fire#2601]
Me and a friend were trying to get Gray and Silver dragons by breeding our tamed dragons, but is just impossible.
over 40 eggs and none of them is Gray (speaking of Fire Dragons).
Same case with Ice dragons, we get every color except Silver.

My friend notice something in the decompiler code.
The method createEgg uses a random int using "3" as bound in the fixed parameter.
![01](https://user-images.githubusercontent.com/30702322/88891566-0d6ce380-d209-11ea-8bcd-ca48f66d1618.png)

Here's an example:
https://compiler.javatpoint.com/opr/test.jsp?filename=JavaRandomNextIntExample2
Using "3" instead "i" in nextInt() and runing the script we will NEVER get '3' value.

Then, looking at the DragonEgg enum he notice that the Gray egg has actually the index '3'.
![02](https://user-images.githubusercontent.com/30702322/88891568-0d6ce380-d209-11ea-8cb5-381e2534e104.png)

Sorry for bad english ;p

Regards!

**Comment by WalterTheMighty** [comment]
It's widely believed that this is intentional.

**Comment by Nao-stuff** [comment]
> It's widely believed that this is intentional.

Yep, it cross my mind too.
It just makes more sense that such a dumb bug xD 

But idk why those color were so "rare" or "special", if that's the reason.
