### ISSUE TITLE
Statues disappear instead of displaying cracks

### ISSUE THREAD

**Issue by somebodyandnobody** [Alex-the-666/Ice_and_Fire#2607]
when i use a pickaxe on a stone statue, the model is disappearing instead of showing any cracks. anything the mob is holding remains. it seems like its an issue with the actual statue. please fix this

**Comment by MightyGoat4242** [comment]
I have also noticed this, they don't always disappear, sometimes you can just break them normally.
Some mobs also have animations when turned into stone, for example bats.

**Comment by vrnRaptor** [comment]
Same problem:
![89641867-51bc4b80-d8bb-11ea-879c-244939f6ac69](https://user-images.githubusercontent.com/13599993/89705074-cb5b4480-d962-11ea-9062-fb62948acdbc.gif)

**Comment by somebodyandnobody** [comment]
also if you do it to mobs from mods, like mowzies mobs, it will sometimes revert to the original texture. sometimes you can act like the mob is guarding your base. that isnt annoying, but it really is when the thing disappears
