### ISSUE TITLE
Updating from 1.8-1.9 with newest llibrary, game doesn't launch. any help is appreciated

### ISSUE THREAD

**Issue by LifeSovereign** [Alex-the-666/Ice_and_Fire#2608]
I just updated the ice and fire version I was using from 1.8 to 1.9, with the most recent llibrary plugin as well. However, when I launched Minecraft, the game launches but shortly closes out with this error: 

The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/core/ModItems

I don't know if this error was already addressed, or if I did something wrong, so any help would be appreciated. Thanks.

[crash-2020-08-03_15.23.48-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5018046/crash-2020-08-03_15.23.48-client.txt)

**Comment by kodabeer** [comment]
You need to update spartanfire and spartan weaponry
