### ISSUE TITLE
Tamed Dragon on server

### ISSUE THREAD

**Issue by LoneHamos** [Alex-the-666/Ice_and_Fire#2610]
Hi, First i love your mod, he's incredible. A really good mob that i enjoy to play with my friend.

I'm playing on a private server with my friend but we have an issue with tamed dragon. Is there a way that he's fire dragon and my ice dragon stop try to kill each other ? 
If we let them out wandering they always hit each other.

Is there any solution ?

**Comment by WalterTheMighty** [comment]
This is intentional. Your best bet is to keep them away from each other.

**Comment by LoneHamos** [comment]
So our dragon will always fight each other ? 
Even fire vs fire dragon or Ice/Ice ?

**Comment by WalterTheMighty** [comment]
No. Dragons of the same type will respect each other. Dragons of opposing types will seek to destroy one another.

**Comment by LoneHamos** [comment]
Last question, sorry to bother you ^^'. I suppose it will be the same with the new uncoming Lightning Dragon ?
