### ISSUE TITLE
Texture bug minecraft 1.10

### ISSUE THREAD

**Issue by Ashfurr** [Alex-the-666/Ice_and_Fire#2612]
![image](https://user-images.githubusercontent.com/39094834/89430133-b00fef80-d73e-11ea-8c8b-b4653363a4ef.png)
hello, i have this problem on 1.10 can someone help me to fix this ?

**Comment by SPS360G** [comment]
@Ashfurr if you have the applied energistics mod it has been know to cause issues with the textures. also 1.10 version is no longer supported so the only true fix (other than finding out what mod incompatibility it could be and removing it) is to upgrade to the 1.12.2 version of the mod.

**Comment by Ashfurr** [comment]
It's okay I fix it by add  optifine ^^
