### ISSUE TITLE
Visual Bug that is really annoying

### ISSUE THREAD

**Issue by thelegendaryfox** [Alex-the-666/Ice_and_Fire#2624]
Basically I was playing with mods then my game crashed so I got back on and my screen had the effect when you get lured by a siren. Confused, I restarted and still had the glitch, I cant find out a way to get it off and even when I got into NORMAL MINECRAFT I can still see it, thats right NORMAL VANILLA MINECRAFT. Please figure out a way to fix this for me, I reinstalled minecraft and still nothing!
![Minecraft 1 8 9 8_15_2020 2_55_34 PM](https://user-images.githubusercontent.com/69731518/90319596-85c0ed80-df07-11ea-9855-aaae46c702b2.png)
![Minecraft 1 8 9 8_15_2020 2_55_43 PM](https://user-images.githubusercontent.com/69731518/90319601-8e192880-df07-11ea-9bd5-65772615e2fc.png)

**Comment by Exotic0015** [comment]
This isn't the mod's fault. It seems like you turned on the "**3D Anaglyph**" setting in the video settings, try turning that off.

**Comment by thelegendaryfox** [comment]
ok thanks
