### ISSUE TITLE
Ice and fire missing registry entries

### ISSUE THREAD

**Issue by BxacT** [Alex-the-666/Ice_and_Fire#2625]
> [20:32:55] [Server thread/INFO] [FML]: Injecting existing registry data into this server instance
> [20:32:55] [Server thread/INFO] [FML]: Registry EntityEntry: Found a missing id from the world iceandfire:dragonice
> [20:32:55] [Server thread/INFO] [FML]: Registry EntityEntry: Found a missing id from the world iceandfire:dragonfire
> [20:32:55] [Server thread/ERROR] [FML]: Unidentified mapping from registry minecraft:entities
> [20:32:55] [Server thread/ERROR] [FML]: iceandfire:dragonice: 117
> [20:32:55] [Server thread/ERROR] [FML]: iceandfire:dragonfire: 115
> [20:32:55] [Server thread/WARN] [FML]: Forge Mod Loader detected missing registry entries.
There are 2 missing entries in this save.
If you continue the missing entries will get removed.
A world backup will be automatically created in your saves directory.
Missing minecraft:entities:
iceandfire:dragonice
iceandfire:dragonfire
Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.

**Comment by Iwwom** [comment]
Hey, did you find any solution to this problem?
