### ISSUE TITLE
Glacier biome glitch

### ISSUE THREAD

**Issue by CookieCraver** [Alex-the-666/Ice_and_Fire#2630]
Whenever you go into a glacier biome for the ice dragons the world goes see through and x ray, it glitches so bad it closes my server and lags me out in single player,please fix this as I love this mod would like to get the ice dragons they are so pretty :( I am playing on 1.12.2

**Comment by nicola-de-smet** [comment]
Got the same bug especially in the dungeon of the ice biome, everything seems to be flying around ... 1.12.2 version too
