### ISSUE TITLE
Dragon bugs

### ISSUE THREAD

**Issue by elux567** [Alex-the-666/Ice_and_Fire#2634]
Hello!
am having issues with the dragon horn, sometimes it works sometimes it bugs and i have to reload my session.
and the other thing is, when increasing the dragons health it caps at 2048 and i dont know why it wont go past this number, since in the config file i set it to be 6000

**Comment by eehunter** [comment]
2048 is the hard limit for entity health in Minecraft. To get around this, one would have to do some weird code stuff to make it work correctly.
