### ISSUE TITLE
Dragon has drowned

### ISSUE THREAD

**Issue by prestonhashworth** [Alex-the-666/Ice_and_Fire#2635]
Tamed dragons left sitting will apparently randomly walk off and drown. Is this a feature or a bug? Too much like an actual child for my comfort!

**Comment by Grimnott** [comment]
I have this problem too. I've hatched 2 dragons so far, and both have drowned without even making it past stage 1. I don't live anywhere near water nor do the dragons even have a way to leave my house and access water. Very disappointing :(
