### ISSUE TITLE
Myrmex hive generation is broken

### ISSUE THREAD

**Issue by PCAwesomeness** [Alex-the-666/Ice_and_Fire#2639]
![2020-08-31_19 26 44](https://user-images.githubusercontent.com/8507148/91758740-19e0b500-eb96-11ea-9844-caa0e489212d.png)

Myrmex hives will generate with directly exposed or even dissected tunnels.

![2020-08-31_19 30 22](https://user-images.githubusercontent.com/8507148/91759000-8956a480-eb96-11ea-94ed-abc0b4bafe22.png)

In addition to this, what appears to be one of the entrance tunnels is directly blocked off by a wall of sandstone.

Of course, more structures may suffer from broken generation; if it turns out to be the case, I will repurpose this issue into a bigger one.

**Comment by AlexModGuy** [comment]
Close. please report to the special BETA bug reporter instead.
