### ISSUE TITLE
Dragons Unable to Mate

### ISSUE THREAD

**Issue by colejagdtiger** [Alex-the-666/Ice_and_Fire#264]
When I attempt to have two dragons mate nothing happens. One is female the other is male, both are set to wander mode, I give the mixture to the male and then the female, however even after waiting for 5 minutes nothing happens.

**Comment by colejagdtiger** [comment]
Also both of the dragons are stage 4.

**Comment by WilliamBlaze** [comment]
i believe that currently breeding only works for stage 5 dragons, regardless of the fact that the bestiary implying that stage 4's can also breed.
