### ISSUE TITLE
Item icon's are gone

### ISSUE THREAD

**Issue by honzagaleka** [Alex-the-666/Ice_and_Fire#2657]
![issue](https://user-images.githubusercontent.com/70820322/92312772-53fdec80-efc4-11ea-8fd8-22b956f2c6ef.png)

With new version of Ice and Fire, item icons are glitching
![image](https://user-images.githubusercontent.com/70820322/92312811-c66ecc80-efc4-11ea-8fd2-00f2953315e6.png)

**Comment by AlexModGuy** [comment]
remove old resource pack
