### ISSUE TITLE
MC crashing after "Chest aggro" in 1.1.1

### ISSUE THREAD

**Issue by ThatsMyLive** [Alex-the-666/Ice_and_Fire#266]
So, I had to register to GitHub just because I love this awesome mod and I want to help out a bit with what issues I find.

I just installed the new version 1.1.1 of the mod and wanted to test what issues I could find and what is fixed. But I did not get as far as to check on everything as the biggest issue seems to be the "Wild Dragons will now agro to nearby players who break gold/silver piles or open nearby chests."

If you open chests or destroy the piles and the dragon is close enough (veery small range) the game stops doing stuff. Like I can still run and fly around but the world stops loading, all entities stop moving/freeze and you cant even open anything anymore (noticed this after trying to open a lair chest again and nothing happend).
You can go into MC pause menu but no saving or else, after a while waiting it then suddenly chrashed withour error report.

Ok, so far to that, I get back to checking things a bit and if I find anything else I tell ya! ;)
Still though, I am really in love with this mod and I cant wait for more! A mod that gets my dragon-heart to beat faster, just so perfect!

<3 ThatsMyLive

**Comment by ThatsMyLive** [comment]
OKay a small update: Also tamed dragons if attacked by the player start to get agro after a while and it just does the same as wild dragons agro -> it freezes entity movement and after a while it crashes. So there must be something wrong with the dragon agro somwhere.

**Comment by gchpaco** [comment]
I have this problem, too, and the common call in the server thread when it locks up is `com.github.alexthe666.iceandfire.entity.ai.DragonAIAirTarget.getNearbyAirTarget()` according to VisualVM.  There may be an AI loop.  It triggers upon aggro.

**Comment by AlexModGuy** [comment]
@ThatsMyLive @gchpaco while i'm figuring out this issue, edit the config so advancedDragonAI is false; this should make it run like normal but dumber dragon ai.

**Comment by gchpaco** [comment]
Will do, thanks!

**Comment by kreezxil** [comment]
I have some actual crash reports in regards to this from my own server:

https://gist.github.com/anonymous/67943973df5b0c2d484228c2f6337e09
https://gist.github.com/anonymous/61fd86f24f3a6e481f57f9412bee64e1
https://gist.github.com/anonymous/3804616a32c1c1fa5125f7f37167f5b9

I'm building a new modpack called Word of Dragons where you modpack is at its core.

Mods currently in the pack are:

https://gist.github.com/23a4279e1f4a5cbd17f1465aa20fbec2

**Comment by kreezxil** [comment]
Would like to point out that setting the dragon ai to false, ie to make them dumb on the server, while it does allow us to get near the dragon, as soon as we attack them, it forces the dragon get target function which subsequently crashes the server.

So the setting is good as long you avoid all dragons so they don't load and don't attack anything. :(

**Comment by ThatsMyLive** [comment]
@kreezxil Do you turn dragon ai off or advanced ai. Because on my server everything works fine now, just as the dragons are as dumb as in 1.1.0 version. It simply turns off those target stuff. Maybe some other issue?

**Comment by kreezxil** [comment]
I turned off advance ai didn't see the other one Will look again.

**Comment by kreezxil** [comment]
@ThatsMyLive  this is my config https://gist.github.com/3cf3d388f183f7dfc822ad2e953e2f9c
 I don't see "dragon ai" only "advanced" and it is false.

**Comment by ThatsMyLive** [comment]
@kreezxil mhm... its the same as mine on the server. But for me and my three friends everything works fine without advanced AI. I have no clue. Do you have any other mods on the server? Because we only have the ice and fire :D

**Comment by AlexModGuy** [comment]
should be fixed in 1.2.0.
