### ISSUE TITLE
Dragon spawning in the nether

### ISSUE THREAD

**Issue by B-Wither** [Alex-the-666/Ice_and_Fire#2671]
![2020-09-06_09 36 13](https://user-images.githubusercontent.com/63962480/92315693-7f182880-f024-11ea-91f1-b927878217b2.png)

**Comment by ZeSethis** [comment]
Found some dens that are spawning there, too. Only have the ice and fire mod and its dependency, nothing else.
![2020-09-05_19 48 04](https://user-images.githubusercontent.com/63993539/92315831-29eeff00-efb1-11ea-973d-74b9cc0f21ef.png)

**Comment by Carro1001** [comment]
Complement for this issue, the dimension blacklist/whitelist config seems to be gone, and they also spawn in the end.
