### ISSUE TITLE
[2.0.0] Gorgon temple gen issue list

### ISSUE THREAD

**Issue by Carro1001** [Alex-the-666/Ice_and_Fire#2674]
-They may generate incomplete, like cut in half, or even worse, maybe because of chunk borders

-They may spawn fully underground, not even visible

-The basic thing since 1.12 where they spawn underwater

**Comment by leyxcx** [comment]
here's one example ![2020-09-06_19 54 08](https://user-images.githubusercontent.com/67163463/92321043-c4674500-f07a-11ea-837c-fdc5404ddfe3.png)
