### ISSUE TITLE
Dragon Eggs Fizzling Out

### ISSUE THREAD

**Issue by EpicSquid** [Alex-the-666/Ice_and_Fire#268]
I have found the issue with dragon eggs fizzling out, there is a call in line 103 of EntityDragonEgg.java that checks for the nearest player (within 5 blocks) using world.getClosestPlayerToEntity(this, 5) != null, this causes 2 problems
a) People can steal other people's dragons
b) The dragon egg's "fizzle out" whenever the player walks away  at precisely 60 seconds (in ticks) and the entity death is not related to the player's being near (i.e. not null response), as such the dragon egg will just die, and no dragon will spawn.

Perhaps make it so that the radius is configurable or keep track of the player who placed the egg could solve the issue, or at the very least make it so that the dragon taming and ownership is decided by the first player to come withing 5 blocks, and have the dragon spawn regardless of player vicinity.

**Comment by darthvader45** [comment]
It would be rather simple to add an NBT tag to the egg called "dragonOwner", which would return the player's UUID, meaning that if you create a new account under a new purchased Minecraft, that user won't own the dragon, but if you change your username on the original account, you'd still own the dragon.  It would apply to the egg and the dragon that hatches.

**Comment by DogResidue** [comment]
I've had this same problem, my dragon eggs keep disappearing.
