### ISSUE TITLE
Baby Dragons Breaking

### ISSUE THREAD

**Issue by BlueEyesEthan** [Alex-the-666/Ice_and_Fire#2680]
I was playing with the mod in 1.12.2 everything worked fine until I hatched my first dragon egg of the world, and I made it sit but when I accidentally fell off of something it teleported to me, and now it's not moving and it won't get back up. I tried to rejoin but he still didn't move and when I put him on my shoulder and removed him he would teleport right back to it's original position. And each time I leave somewhere it always teleports to me and it almost died, and when I hatched it, it stayed in the air until I left which is where it teleported, please fix this this is a major bug that needs to be removed

![2020-09-06_10 48 05](https://user-images.githubusercontent.com/54153705/92331975-2b5f0c80-f02f-11ea-9709-82672325b8e0.png)
![2020-09-06_10 48 15](https://user-images.githubusercontent.com/54153705/92331978-331eb100-f02f-11ea-81af-5902a8a990e3.png)
![2020-09-06_10 48 25](https://user-images.githubusercontent.com/54153705/92331982-36b23800-f02f-11ea-82c0-34a828c1ad1d.png)

**Comment by SpiritualBanana** [comment]
Why does this have the 1.15.2 label? Doesn't the report state that they're playing in 1.12.2? 

Anyway, I'm having a similar problem with the mod, with the dragon teleporting back after I put them on my shoulder.

**Comment by NobleDraconian** [comment]
Can confirm, experiencing the same problem here on 1.12.2. Baby dragons will teleport back to the position they were in if you try to unmount them from your shoulder.
