### ISSUE TITLE
Ice and fire 2.0.0 (1.15.2) Update bug list

### ISSUE THREAD

**Issue by SLZT** [Alex-the-666/Ice_and_Fire#2685]
So I found some bugs for the new 2.0.0 (Phase 2 / 1.15.2) Update. I decided to report all of the bugs I found to make it easier for the devs to fix them and for you to be aware of them.

Ice and fire bugs:
1.) There's no sound or animation when putting a lightning dragon into a dragon horn.
2.) When you leave your world with your taimed dragons out of the horn they will de-spawn.
3.) When flying a lightning dragon his head flickers up and down weirdly.
4.) When using the new lightning dragon sword you get hit by the lightning too (Not really a bug it would still be great changing that it uses the lightning the dragon has instead of using the normal Minecraft rain lighting)
5.) When flying the lightning dragon it sometimes moves half way to left or right making it look weird.
6.) When putting a banner on a lightning dragon it spawns inside of the dragon and not on it.
7.) Trolls spawning inside of your own house even when having torches up.
8.) Dragons spawning inside of the nether.
9.) Dragons spawning inside of the end.
10.) Lightning dragon banner appears black on shield.
11.) Gorgon temple's generate only as a half.
12.) Mausoleum's generate in air.
13.) Pixie wands don't do anything when using them.
14.) When being killed by a lightning dragon the death message isn't set.
15.) Config for dragonsteel does not work.
16.) Nests can generate underwater.
17.) Copper ore does not generate normaly.
18.) Lightning dragon block does not drop when breaked.
19.) Dragons sometimes do random things when using a command staff on them, sometimes it just walks away from you even if you have it on following.
20.) Lightning dragon's arent hostile to other dragon's.
21.) Sirens tails glitch out when they sing or walk.

Shader bugs (Bugs with shaders related to ice and fire):
1.) The lightning dragon does not have any lighting when using dragon breath (Tested in seus)
2.) Dragons have a black shadow for their wings (Only appeals to some shaders)

These are all bugs I found! If you know any more bugs that should be added here please notify me on my Discord (KatzenWau#0001) or write a comment!

**Comment by random3421** [comment]
When Shaders is applied it makes every entity within the Ice and Fire mod blacked out or glitched.

**Comment by SLZT** [comment]
> When Shaders is applied it makes every entity within the Ice and Fire mod blacked out or glitched.

That could've to do with the shader, try it with another one.

**Comment by random3421** [comment]
I have tried 3 different shaders and all of them do the same thing unfortunately.

**Comment by SLZT** [comment]
> I have tried 3 different shaders and all of them do the same thing unfortunately.

I'll try it out myself, if it's true I'll add it to the list ^^

**Comment by random3421** [comment]
Okay, thank you! I have the shaders listed below. I am not very educated on how to use shaders, so maybe there is a setting somewhere to help with the glitch problem.
BSL
Sildurs
SEUS

**Comment by ApprenticeNecromancer** [comment]
You may try with the newest version of complementary shader, but it seems more like optifine bug as I havent expirence this exact issue with bsl. If it wont help try different version of optifine.

**Comment by SLZT** [comment]
> Okay, thank you! I have the shaders listed below. I am not very educated on how to use shaders, so maybe there is a setting somewhere to help with the glitch problem.
> BSL
> Sildurs
> SEUS

Alright sorry but it has to do with you ;c, I tried it out myself and what you descripted didn't happen to me. As apprenticenecromancer said try using a newer version of the shader or a different version of optifine.

**Comment by random3421** [comment]
Changing the Optifine worked for me. Thanks so much for the help!

**Comment by SLZT** [comment]
> Changing the Optifine worked for me. Thanks so much for the help!

No proplem. ^^
