### ISSUE TITLE
crash...

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#269]
[crash.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/1084247/crash.txt)
used forge 2315, please help. it happened suddenly while we are playing in the ded. server.

**Comment by ghost** [comment]
and ah, before this crash, server freezes(no any response, but looks working) for a big while. after that big while, it crashes with this crash report. please help :(

**Comment by esotericist** [comment]
This is almost certainly #266.

**Comment by AlexModGuy** [comment]
duplicate #226

**Comment by ghost** [comment]
266 *
