### ISSUE TITLE
Dragon speed

### ISSUE THREAD

**Issue by jaesunn** [Alex-the-666/Ice_and_Fire#2690]
Dragons move so fast that my PC can't keep up when i ride them, making them impossible to actually ride and use. Adding a dragon speed config would allow people with slower PC's  to actually use dragons effectively also if people just overall think they're to fast.

**Comment by SLZT** [comment]
Try making a local host forge server with ice and fire, playing on multiplayer can increase your FPS in general allot. But to add dragon speed to the config is a nice idea.

**Comment by jaesunn** [comment]
Is it free? If so how can I do it?

**Comment by SLZT** [comment]
> Is it free? If so how can I do it?

Yes, a local host server is a server run inside of your own network so yes it is free.
And there are multiple ways to do this, the best one to use for this is to host it on an 2. PC or laptop. You're not allowed to stop the PC when playing on the server tho. If you don't have a 2. PC or laptop you can host it on your own PC which wouldn't really help in your case tho as it would just take even more lag.

Another way is just to buy a VServer or a direct Minecraft Server for forge, but that can cost allot of money.

On how to create a local Host server you'll find enough tutorials on YT.

I hope this helped you out a bit. ^^

**Comment by AlexModGuy** [comment]
added speed config in 2.0.1
