### ISSUE TITLE
Ice and fire 1.15.2 doesnt work on servers

### ISSUE THREAD

**Issue by tyroxinas** [Alex-the-666/Ice_and_Fire#2693]
[crash.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5181737/crash.txt)
It’s calling a client renderer to spawn in a I&F mob but it’s running on the server end so it’s getting a null pointer.
it loads the chunk. It spawns a nearby village and then tries to load a model from I&F and crashes

- Gaiyamato from the I&F Discord

**Comment by AlexModGuy** [comment]
fixed
