### ISSUE TITLE
mobs not spawning naturally I/F 1.15.2

### ISSUE THREAD

**Issue by Phantom2909** [Alex-the-666/Ice_and_Fire#2698]
Sea serpents, Hippocampus, Amphitheres, Sirens, Stymphalian Birds, Myrmex Gorgons, Cyclops and Hydras have not been generated naturally (I started a new world).

**Comment by AlexModGuy** [comment]
they spawn for me. the new config makes them spawn 1000 blocks further from spawn, and 300 blocks apart.
