### ISSUE TITLE
[2.0.0] Ice Dragon Spikes cannot be harvested, even with silk touch.

### ISSUE THREAD

**Issue by Carro1001** [Alex-the-666/Ice_and_Fire#2705]
they drop nothing

**Comment by SLZT** [comment]
Not much of a bug as far I know. The ice dragon spikes aren't supposed to drop as they're pretty much just a little detail for the dragons breath.

**Comment by Carro1001** [comment]
they are extremely useful for mob farms tho

**Comment by SLZT** [comment]
Even if they're, it's not an bug as it's not supposed to drop anything when being broke.
