### ISSUE TITLE
problems between the bestiary and optifine I/F 1.15.2

### ISSUE THREAD

**Issue by Phantom2909** [Alex-the-666/Ice_and_Fire#2708]
This is related to a bug that I reported a few days ago. I said that the pages of the bestiary could not be seen (and I did not mention that the image froze) and only the pages were heard. But today I read on the server (discord) that the problem was for using optifine, so I removed it, and the bestiary started working normally, then I put it back and the problem came back. Would it be possible to fix the bug so that there is no more conflict with the optifine?

**Comment by SLZT** [comment]
This can't really be fixed, it's a bug with optifine and not a bug from ice and fire. The Optifine devs would need to fix this but I don't think they really will.

**Comment by Phantom2909** [comment]
> This can't really be fixed, it's a bug with optifine and not a bug from ice and fire. The Optifine devs would need to fix this but I don't think they really will.

The same thing happened to platinum fox (the bug with the bestiary gui) when he tested the beta, I don't know if he used optifine too. do you know if this problem happened in 1.12.2?

**Comment by SLZT** [comment]
Not sure if it happend in 1.12.2 too but it could idk. It's a 1.15.2 optifine bug as it doesn't happen without optifine.

**Comment by Phantom2909** [comment]
> Not sure if it happend in 1.12.2 too but it could idk. It's a 1.15.2 optifine bug as it doesn't happen without optifine.

I thought about what you said, and yesterday I did the test to reset the default settings of the optifine, and the problem with the bestiary was "fixed", and then I put back my previous configuration and the bestiary was still working correctly until i close the game. I thought it was just a matter of restarting optifine and that was it, so I closed the game, reopened it (with my settings again) and the problem returned. I think it is one of the optifine options that conflicts with I / F. Anyway, thanks for taking the time to reply.

**Comment by SLZT** [comment]
> > Not sure if it happend in 1.12.2 too but it could idk. It's a 1.15.2 optifine bug as it doesn't happen without optifine.
> 
> I thought about what you said, and yesterday I did the test to reset the default settings of the optifine, and the problem with the bestiary was "fixed", and then I put back my previous configuration and the bestiary was still working correctly until i close the game. I thought it was just a matter of restarting optifine and that was it, so I closed the game, reopened it (with my settings again) and the problem returned. I think it is one of the optifine options that conflicts with I / F. Anyway, thanks for taking the time to reply.

No proplem.
