### ISSUE TITLE
Buildings don't spawn

### ISSUE THREAD

**Issue by Quatronomikon** [Alex-the-666/Ice_and_Fire#2711]
First thing I saw when I created a word that there are less dragons and other mod stuff then the versions before. I thought ok maybe it should be like this. But when I used the locate command (/locate iceandfire:gorgon_temple) I saw the problem. Some stuff simply don't spawn. At the located position was simply nothing.
Please fix the spawnrate of modded stuff

**Comment by AlexModGuy** [comment]
it all spawns 1000 blocks away from 0, 0
