### ISSUE TITLE
Dragon Roosts not spawning

### ISSUE THREAD

**Issue by rinrandomtime** [Alex-the-666/Ice_and_Fire#2713]
I have tried on diffrent saves using the mod alone and other mods and dragon roosts are not spawning. It's not letting me config or even see the config settings either. 
Other mobs from the mod aren't spawning either. The only thing ive seen are the dragon caves spawning normally.

How do i check the configs? And how do i get dragon roosts to spawn?

**Comment by SLZT** [comment]
Locate to C:\Users\UserNameHere\AppData\Roaming\.minecraft\config and locate the ice_and_fire.cfg file and delete it, then start up minecraft to regenerate the file and the config will reset. If you still have the bug try removing all mods in your mods folder except ice and fire and caditel. Try then if it still doesn't work try deleting ice and fire + caditel and then adding them back.

**Comment by rinrandomtime** [comment]
I just tried all of those and it seems to be not working still. And im still unable to config. Thanks for replying anyway.
