### ISSUE TITLE
Can't raise dragon health beyond 512 in config

### ISSUE THREAD

**Issue by Thomasagus** [Alex-the-666/Ice_and_Fire#2715]
I tried to change dragon health to 1500, nothing happened. 
Then i decided to make max health 100,000 but that only made all the baby dragons have 512 health. 
I can't seem to raise the health higher than 512

**Comment by SLZT** [comment]
Before you report bugs check if they have been reported before, the issues tab is getting spammed with the same bugs over and over again.
