### ISSUE TITLE
Trolls spawn inside of house regardless of material

### ISSUE THREAD

**Issue by Dreamnoble** [Alex-the-666/Ice_and_Fire#2718]
I made a private server for me and a friend to play on, and we recently upgraded our house to a fortress with high walls. No matter what material the walls and ceiling are or how well lit it is, we get trolls spawning in groups of 1-3. We don't have weapons strong enough to repeatedly deal with them, and their smash attack keeps breaking the floor. I'm considering disabling them until it's been fixed.

**Comment by NeonPopsicle** [comment]
Having this same issue in 1.15!
