### ISSUE TITLE
Dragon Riding bugs still happen rarely in 1.1.1

### ISSUE THREAD

**Issue by colejagdtiger** [Alex-the-666/Ice_and_Fire#272]
Sometimes in 1.1.1 chunks will not load, the dragon, will return to its old position, and although it makes noises for a breath weapon, it will not use it, and I will constantly take small amounts of damage. This is has only happened to me twice in all of the time spent riding my dragon.

**Comment by colejagdtiger** [comment]
Just happened to me twice more(except for that I was not constantly taking damage).

EDIT: Played some more and have gotten the above bugs, however not altogether, sometimes I cannot use breath weapons but chunks load, sometimes chunks do not load but my dragon does not return to her old spot.

**Comment by ThatsMyLive** [comment]
Yeah, got the same stuff. Most of the time it works fine but sometimes its a bit stuck and you have to get off and back on, but I never had that attack problem though. Cant figure out a pattern.

**Comment by AlexModGuy** [comment]
are you using the newist version, 1.1.2?

**Comment by darthvader45** [comment]
1.1.2?  That version isn't on CurseForge.  Is it still under development?
