### ISSUE TITLE
server crash  when  booting  

### ISSUE THREAD

**Issue by skitzozombie25** [Alex-the-666/Ice_and_Fire#2723]
appon  adding   citdale  and   ice   fire to my  1.15.2 mod pack server  side the   server will repeably   crash and restart   but blame   a diffrent mod every time   first it was this  :Quark (quark) encountered an error during the common_setup event phase
§7null,
    Emendatus Enigmatica (emendatusenigmatica) encountered an error processing deferred work
§7java.lang.NullPointerException

]

then after removing thoes   mods   the server still wouldnt boot   apon removing   ice and fire and citidle  the server boots just fine i would asked   about this in your discord   but your  community was rude to me   and  started saying i was some one called drowned and ignoring me

**Comment by MokahTGS** [comment]
There was a closed issue with Server crashing and Ice & Fire, but I'm not sure if this is the same issue.  All I know is we have been holding off adding it to our modpack and I know the TNP Limitless 2 modpack was doing the same.  Would love to add this but it currently doesn't work on servers.  Fixes seem to be coming, but not released yet.

https://github.com/Alex-the-666/Ice_and_Fire/commit/b5d2c1ed84f9be0b9544bb38eaf5358cae9780e5

https://github.com/Alex-the-666/Ice_and_Fire/commit/f43e8507dfb10ecace060c239725f49811e96343
