### ISSUE TITLE
Lightning dragon idle flying animation has no smooth transitions for the head

### ISSUE THREAD

**Issue by DrPenguinni** [Alex-the-666/Ice_and_Fire#2724]
When riding a lightning dragon and stopping to hover in mid-air, the dragon's head can be seen snapping up and down, lacking a smooth transition for the head animation-wise

**Comment by SLZT** [comment]
Place check if the bug has been reported before. The issue tab is getting spammed with the same bugs over and over again. Before you report it check if the bug has been reported before.
