### ISSUE TITLE
if you give a name to the dragon and exit the game, it will disappear

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#2728]

**Comment by SLZT** [comment]
Wrong, taimed dragons in general despawn when leaving and rejoining the world. And please check the other existing issues to know this hasn't been reported before as the issues tab is getting spammed with the same bugs over and over again.

**Comment by ApprenticeNecromancer** [comment]
On my side, I can confirm its related to giving them a name. As long as my dragons were nameless they never despawned on relog (I had 6 dragons of all types). I named 3 of them and they all vanished as soon as I rejoned world. Double tested it on newly hatched dragons, only named one dissapear, also their name in their GUI is displayed as "dragon.nameName" (dragon named Name)

**Comment by SiobhanGrey** [comment]
I can confirm that only named dragons disappear. I tested multiple times with named dragons and every time my server restarted they were gone. I left my dragons unnamed and restarted the sever several times and they stayed.

**Comment by SLZT** [comment]
That could be the server idk. When playing singleplayer the dragons despawn when not in their horn no matter if they're named or not. Still check if the bug has been reported before as it's annoying seeing the same bug over and over again in the issues tab.

**Comment by SiobhanGrey** [comment]
I have done extensive testing in single player as well and I can tell you this is exactly how it works.  https://i.imgur.com/lXELeWv.png https://i.imgur.com/TpLAJaU.png

**Comment by SLZT** [comment]
> I have done extensive testing in single player as well and I can tell you this is exactly how it works. [https://i.imgur.com/lXELeWv.png](url) [https://i.imgur.com/TpLAJaU.png](url)

The Pictures are invalid, even tho I can say that every taimed dragon named or unnamed will despawn when leaving the game. (I don't know for servers as my Server hoster is currently under maintance), I've tried it multiple times with only ice and fire downloaded and they despawned every time no matter unnamed or named.

**Comment by SiobhanGrey** [comment]
Fresh install. Single Player. Ice and Fire is the only mod installed. https://i.imgur.com/UsLSfQe.gif

**Comment by SLZT** [comment]
> Fresh install. Single Player. Ice and Fire is the only mod installed. https://i.imgur.com/UsLSfQe.gif

Doesn't really matter know does it? The bug is known and done. There's still no need to report an already reported bug.

**Comment by SiobhanGrey** [comment]
It matters if the bug isn't being reported correctly.

**Comment by SLZT** [comment]
Multiple people have reported this bug and they didn't mention it only happening when the dragons being named. Samed for me I lost 2 Lv4 dragons due to this bug while they were not named.

**Comment by ghost** [comment]
I only reported this issue because I noticed it myself. I read the posts on "Github" for a bit, but no one reported exactly THIS issue. During the whole game on 1.15.2, neither wild dragons nor tamed dragons (by themselves) disappeared. I also did not have any other bugs.
I reported this problem because I thought it was NECESSARY. Also, I got support from two other people, so I think it WOULD LIKE to report this bug.

**Comment by ghost** [comment]
I hope everyone clearly understood my position?

**Comment by SLZT** [comment]
> I only reported this issue because I noticed it myself. I read the posts on "Github" for a bit, but no one reported exactly THIS issue. During the whole game on 1.15.2, neither wild dragons nor tamed dragons (by themselves) disappeared. I also did not have any other bugs.
> I reported this problem because I thought it was NECESSARY. Also, I got support from two other people, so I think it WOULD LIKE to report this bug.

The bug of taimed dragons dissapearing when exiting the game has been reported multiple times by now. Just bc for you unnamed dragons don't despawn doesn't change anything on the bug itself. I won't argue any further as in my view this thread is useless as it's just spam.

**Comment by NeonPopsicle** [comment]
When I get a dragon and leave the chunk with it sitting there, I have the same problem. They disappear completely when I return. Both dragons this happened to were named at the time.

**Comment by AlexModGuy** [comment]
fixed
