### ISSUE TITLE
Unable to add chapters to the Beastiary

### ISSUE THREAD

**Issue by TheBakerZen** [Alex-the-666/Ice_and_Fire#2729]
I've seen this issue already reported, but specifically mentioned optifine as the cause. I've never used optifine and have been unable to add manuscripts to the beastiary under any circumstance. After unlocking chapters it takes the manuscripts, but once I try to pick up the book it puts the pages back on the stack and removes the chapters I added. I'm not sure what many things do because the beastiary won't work for me.

**Comment by NeonPopsicle** [comment]
Having the same issue!

**Comment by glyyf** [comment]
Same issue, running on a forge server, clients are running optifine, but tested without and still can't add to bestiary. Can test further or supply more details if needed.

**Comment by PCat4L** [comment]
What "worked" forme. Add the chapters then take the book, left shift + right click and you should be able to read the chapters now, thing is, it stops working after few "uses", so you have to repeat the process whenever you want to read something new, what i do is get as many manuscripts as possible, then add every chapter i can. Not the desired solution but it's something...
