### ISSUE TITLE
Dragons Harming Their Riders

### ISSUE THREAD

**Issue by colejagdtiger** [Alex-the-666/Ice_and_Fire#273]
Sometimes dismounting my dragon will throw me high into the air dealing a high amount of damage from the fall, also when your riding your dragon, and use its breath weapon while you are landed on the ground, causes damage to the player riding the dragon.

EDIT: Sometimes while flying forward you can fly into the dragon breath getting hit by it(I assume this is also why you take damage while using it on the ground).

**Comment by AlexModGuy** [comment]
fixed
