### ISSUE TITLE
ice and fire can't run on servers

### ISSUE THREAD

**Issue by xiodos666** [Alex-the-666/Ice_and_Fire#2739]
I tried starting an ice and fire server and the server just couldn't handle the mod. I've tried everything to be able to run this mod but so far I've had no luck, I don't know how to fix this and I need help.

I tried running the server off Pebblehost with their Premium 8GB plan and the server overloaded and crashed.

I tried running the server off my own PC with 8GB allocated (I have 16), and the server started lagging a lot and ran over 20,000ms behind

I tried removing other mods that I thought could be the problem, until I had no other mods but Lithium, Mixinbootstrap,  Phosphor, Citadel and Ice and Fire.

I also tried turning the server chunk render distance down to between 6 and sometimes 8, still had a lot of lagspikes and the server overloaded and started lagging.

I turned down the dragon search distance from 128 down to 64, still had the same amount of lag, 
"#Range: 1 ~ 10000
	"Dragon Target Search Length" = 64"

I also simplified dragon's path finding option 
"#Turning this to true simplifies the dragon's pathfinding process, making them dumber when finding a path, but better for servers with many loaded dragons.
	"Experimental Dragon path Finder" = true"

I also enabled the option where if on servers there are too many dragons, turning it to true should help, "
"#Enable this if your server is being bombarded with moved wrongly or moved too fast console messages. REQUIRES RESTART!
	"Dragon Moved Wrongly Error Fix" = true"

If anyone is able to help me lmk on discord | xiodos#0524 I would greatly appreciate in form of help <3

![can't keep up](https://user-images.githubusercontent.com/71169530/92990490-c9206480-f491-11ea-9648-fc2c60bf9c51.PNG)

**Comment by Pokerfrog** [comment]
I have my own server and I put 8 gigs from my pc and it runs fine, could be some other mod or datapack

**Comment by xiodos666** [comment]
hey thanks for replying, i've tried everything and nothing still works :/

**Comment by Nerodon** [comment]
I am having the EXACT same problem.
This is especially bad whe the dragon decides to hunt fish in the ocean, every, single, fish, would cause 5-10s of the server to be dedicated to that dragon while its looking for its next prey.

Reduced search distance to 32, and used 
"Experimental Dragon path Finder" = true"

Only makes the issue happen less often but still does the moment the dragon gets near something that it wants to kill

Using iceandfire-2.1.0-1.16.3
Forge 34.1.25

**Comment by xiodos666** [comment]
i have that problem too, I noticed that getting rid of lycanites mobs,
rough mobs revamped, lowering the server view distance to 8 and changing
mobs view distance in the ice and fire config file down to 32 helped a bit
too. I also completely disabled dragon caves because that cause the server
to crash and made the server lag the MOST. the dragon would break blocks,
get couple blocks up, then stop, then break some more, then completely
freeze, then crash the server. If people were actually playing, fighting a
dragon would be unplayable.

**Comment by xiodos666** [comment]
i use ice and fire 1.15.2. I would look at magma for 1.16 it's almost out.
it's like paper + forge mixed together. I'm still waiting for magma 1.15 to
come out. https://discord.gg/w4khUU https://magmafoundation.org

**Comment by xiodos666** [comment]
we can add each other on discord so we can communicate on finding a fix
soon. xiodos#0524

**Comment by GcxShaman** [comment]
Hey, I am also getting something like this but it only happens with stage 4 or higher dragons that are underground. and will almost definitely cause a timeout when one uses its breath attack

it has gotten bad enough that no-one can approach a dragon without crashing
Please tell me somebody has found a solution

**Comment by BugmanBugman** [comment]
We’ll have to wait for #3032 to get merged by Alex, it contains ALOT of optimizations and fixes

**Comment by xiodos666** [comment]
what is #3032 ?

**Comment by xiodos666** [comment]
is it gonna be for 1.15.2?

**Comment by Bidgam** [comment]
I'm having the same issue as it's tied to the dragons it would seem. The tick gets worse and worse if I don't move or change something, and even then it won't go away entirely until I restart the server. Definitely this mod. Maybe it's not meant for servers? That doesn't really make sense though.

I'd like to connect with you all to figure out what could be a resolution. It's a popular mod, so I assume there's a fix.

**Comment by FractalizeR** [comment]
I can see fixes like "Fixed unlimited ghost spawns per chunk" in 2.1.2 which didn't make it yet into 1.15. Any chance of getting updates?

**Comment by xAlamaos** [comment]
The fix for this I've managed so far to get was to install the mod on the server [TooFast](https://www.curseforge.com/minecraft/mc-mods/too-fast) by [Noobanidus](https://www.curseforge.com/members/noobanidus) and also to set true the option "allow-flight=true" from server.properties
