### ISSUE TITLE
Sometimes Unable to Open Chests in a Dragon Roost

### ISSUE THREAD

**Issue by colejagdtiger** [Alex-the-666/Ice_and_Fire#275]
I have not have this happen in a lair yet, also although I cannot open one or 2 chests I am able to open the rest of them.

**Comment by AlexModGuy** [comment]
are you in spectator mode

**Comment by colejagdtiger** [comment]
No I am in survival mode, also this has only happened shortly after dismounting a dragon.

**Comment by AlexModGuy** [comment]
Update your mod to 1.1.1.

**Comment by colejagdtiger** [comment]
This was in 1.1.1.
However I am going to close this issue as this has not occured anymore, and I think that it was probably a client desync unrelated to the mod.
