### ISSUE TITLE
Unkillable dragons in servers

### ISSUE THREAD

**Issue by tookender** [Alex-the-666/Ice_and_Fire#2751]
You can't damage any dragons in multiplayer servers it's really annoying cause I can't get any of the new dragonsteel stuff.

**Comment by tookender** [comment]
Also the game version is 1.12.2 and the mod version is 1.9.1

**Comment by CelestiaSalinas** [comment]
Do you happen to have ISeeDragons and/or AIReducer? These are known to cause invincible dragons with I&F 1.9.1
