### ISSUE TITLE
Tamed dragons just disappear

### ISSUE THREAD

**Issue by tookender** [Alex-the-666/Ice_and_Fire#2752]
I was just flying on my dragon and then it just randomly disappeared for no reason the game version is 1.12.2 and the mod version is 1.9.1

**Comment by eehunter** [comment]
I've got the a similar issue in 1.15.2, mod version 2.0.0, except for me it was a 1 day old riding on my shoulder. The server console said "[15:32:33] [Server thread/WARN] [minecraft/Chunk]: Wrong location! (-18, 20) should be (-19, 19), EntityLightningDragon['Lightning Dragon'/3454, l='world', x=-287.96, y=18.40, z=320.13]" when it happened.

**Comment by AlexModGuy** [comment]
fixed

**Comment by tookender** [comment]
could you fix it on the 1.12.2 version?
