### ISSUE TITLE
1.15 - Everything is either extremely rare or doesn't spawn

### ISSUE THREAD

**Issue by Severynn99** [Alex-the-666/Ice_and_Fire#2754]
I have a few biome mods active, and tested this on four different world types, I explored each one for an hour in creative/spectator. The most 'important' creatures seem to spawn, though very rarely. Some creatures were never encountered during my testing

Creatures never encountered:
- Pixie
- Hippocampus
- Amphithere
- Cockatrice
- Stymphalian Bird
- Gorgon
- Hydra
- Dread mobs

Cyclopses and Hippogryphs were only encountered once in total

The config seems completely fine, too. It's way too rare to just seem like bad luck

**Comment by B-Wither** [comment]
I have seen amphithere and gorgon, but not seen hippocampus although there were many sea serpents.

**Comment by Pokerfrog** [comment]
I/f creatures don't spawn within 1000 blocks of spawn so that could be your issue
