### ISSUE TITLE
Can't edit the Config

### ISSUE THREAD

**Issue by arudon** [Alex-the-666/Ice_and_Fire#2755]
Hey there, I love your mod, but the number of dragon roosts is way too high. I can have 3 or 4 dragon roosts in close proximity to me at all times, making it very difficult to go anywhere or do anything without having to run away constantly. And any village I find almost immediately gets burned down because of how frequently dragon roosts generate. 

I'm supposed to be able to edit the mod config file in Minecraft itself, but when I go to the mod section and select Ice and Fire the config option is grayed out and I can't click it. Attempting to edit the config file in the executable is fruitless because I don't understand the language. 

Is there something wrong with my Minecraft launcher? Should I be able to use the config menu, or have you not implemented that yet?

**Comment by Spinogaming** [comment]
You can't change the config ingame because Forge doesn't allow that yet for 1.15.2
Also have you tried opening the .toml file with notepad++?

**Comment by arudon** [comment]
No, I haven't tried that just yet. Let me see.

**Comment by arudon** [comment]
Where do I find the .toml file?

**Comment by Spinogaming** [comment]
In .minecraft, in the config folder

**Comment by arudon** [comment]
I believe I found it. Was it "iceandfire-common.toml"?

**Comment by Spinogaming** [comment]
Yes

**Comment by arudon** [comment]
I have successfully eddited it. Thank you so much!
