### ISSUE TITLE
Dragons Can Suffocate While Walking

### ISSUE THREAD

**Issue by colejagdtiger** [Alex-the-666/Ice_and_Fire#276]
My tamed dragon sometimes suffers damage while walking on the ground, while I am riding it. I have checked and the dragon suffocation config option is set to false. Also sometimes she will get caught on blocks while flying, although damage is taken.

**Comment by colejagdtiger** [comment]
Also had this happen when having a baby dragon dismount from my shoulder if there is a ceiling, for a moment they take damage, but afterwards everything is fine.

**Comment by AlexModGuy** [comment]
should be fixed in 1.2.0
