### ISSUE TITLE
[1.12.2] Crash trying to ride Death Worm

### ISSUE THREAD

**Issue by Schlock-Konn** [Alex-the-666/Ice_and_Fire#2761]
I'm playing the Roguelike Adventures and Dungeons modpack and have experienced a crash that has locked me out of my world upon attempting to mount a deathworm. The worm was in a 1-block space between blocks and a fence and seemed to be stuck while I mounted it, which I suspect might be a possible cause. Another plausible cause may be that the fishing rod used seemed to cast and attach itself to the worm before I mounted it.

Crash logs:
[crash-2020-09-13_22.08.05-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5215041/crash-2020-09-13_22.08.05-server.txt)
[crash-2020-09-13_22.11.15-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5215042/crash-2020-09-13_22.11.15-server.txt)

**Comment by DrPenguinni** [comment]
The mod is on 1.15.2 and 1.16.1 now, I doubt 1.12.2 is still supported

**Comment by Pokerfrog** [comment]
Bug fixes will come for 1.12.2 but aren’t a priority

**Comment by nikkidarkmatter** [comment]
[crash-2020-10-24_00.30.50-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5432412/crash-2020-10-24_00.30.50-server.txt)
Adding to the issue, another crash, same issue.
