### ISSUE TITLE
1.15.2 Major Issue of mobs spawning in the wrong dimension.

### ISSUE THREAD

**Issue by OnyxBlad3** [Alex-the-666/Ice_and_Fire#2762]
I just recently made it to the Midnight portion of my modpack and have noticed an issue of Trolls and Dragons spawning like crazy, like 60-70 in one area. I tried my best to find a command or config to edit to stop this from happening. But as far as I can tell I cant find a fix.

**Comment by TheTanzer22** [comment]
What version of Minecraft are you on?

**Comment by OnyxBlad3** [comment]
Im playing on 1.15.2, its the game version in the title

**Comment by TheTanzer22** [comment]
Somehow didn't notice that... I have no idea how to help then

**Comment by AlexModGuy** [comment]
fixed

**Comment by OnyxBlad3** [comment]
Why did you close it if it wasn't fixed

**Comment by AlexModGuy** [comment]
because i just fixed it right now

**Comment by OnyxBlad3** [comment]
In a new update or?
