### ISSUE TITLE
dragon disappeared 2.0.0

### ISSUE THREAD

**Issue by azuichh** [Alex-the-666/Ice_and_Fire#2763]
I was riding a dragon on a modded sever in 1.15.2 (it was a lighting dragon if that helps) when the dragon suddenly stopped in mid-air, and soon after I got timed out. Comming back into the sever, I fell to my death and came back for my dragon. After grabbing my stuff and more importatlly the lighting dragon crystal thingy that should have tp'd the dragon to me, but I got no such luck

**Comment by AlexModGuy** [comment]
fixed
