### ISSUE TITLE
Iron Chaines uses changed (Nevermind, there is another report about this, sorry)

### ISSUE THREAD

**Issue by Frayn24** [Alex-the-666/Ice_and_Fire#2766]
The iron chaines, changed, normal iron chain is now sticky and the sticky one has the use of the normal.

![Capturar](https://user-images.githubusercontent.com/71246616/93045612-7db3b500-f64f-11ea-88eb-8bbfa46315a3.PNG)

**Comment by AlexModGuy** [comment]
fixed
