### ISSUE TITLE
Bestiary lectern not working

### ISSUE THREAD

**Issue by BenkoSVK** [Alex-the-666/Ice_and_Fire#2767]
I can´t use bestiary lectern to add more manuscripts to my bestiary. I can see GUI, I can insert my bestiary and manuscripts, but there is no option to craft. There should be another window tab for crafting probably but i can´t see it. I tried to remove optifine, resource packs, change graphics, resolution, etc... but nothing helps
![2020-09-14_11 35 31](https://user-images.githubusercontent.com/71258759/93069887-76f06680-f67e-11ea-9fb7-768e06d3a35e.png)

**Comment by ApprenticeNecromancer** [comment]
It works the same way as enchanting, just choose one of three chapters and click on it to add it to bestiary

**Comment by AlexModGuy** [comment]
^
