### ISSUE TITLE
I left and came back to my home and my bestiary was gone from the lectern.

### ISSUE THREAD

**Issue by purestone9** [Alex-the-666/Ice_and_Fire#277]
When I left and teleported back my lectern which had some manuscripts and my bestiary was empty.
I am playing on a server.
Also playing with the World of Dragons 1.0.2 pack
playing on minecraft 1.11.2 mod version 1.1.1

**Comment by ThatsMyLive** [comment]
Jep. I just tested it, as I usually do not leave my bestiary on the lectern I havent noticed before, but yes it dissapeares and all papers too that would be placed in it.
