### ISSUE TITLE
Domesticated dragons disappearing 1.15.2

### ISSUE THREAD

**Issue by Hytrug** [Alex-the-666/Ice_and_Fire#2771]
My ice dragon and my friend's fire dragon disappeared

I left the dragon in "wandering" mode and quit the game, when I went back in it was nowhere near. I used the command "/ tp @e Hytrug" several times but it didn't reappear

My friend left his dragon in "sitting" mode next to me and he disappeared from nowhere and again "/ tp @e" did not bring him back

Help please
Version 1.15.2

**Comment by TheTanzer22** [comment]
I don't know how to solve the glitch, but a dragon crystal can pull a dragon from wherever they are to the spot you use it at, so making one of those and linking it to your dragon should help prevent this in the future (Unless the glitch is despawning them or killing them in the void)

**Comment by Jusey1** [comment]
The glitch is despawning them. It seems that the dragons will despawn when the chunk is unloaded.

**Comment by Carro1001** [comment]
Is this on 2.0.1?

**Comment by AlexModGuy** [comment]
should have bneem fixed in 2.0.1.
