### ISSUE TITLE
 lightning dragon does not use the forge 2.0.1

### ISSUE THREAD

**Issue by azuichh** [Alex-the-666/Ice_and_Fire#2776]
when i build a lightning forge and that I put a dragon in front i use the forge but if i log out and log on he doesn't use it I tried to destroy the forge and replace it but nothing, he still does not use

**Comment by decodinatorX** [comment]
Hi, I encountered the same issue, sort of, I don't know what you mean by you "Logging Out" and "Logging On" but you can possibly fix this by centering your dragon in front of the forge, breaking the front aperture and placing it back!! Seemed to fix it for me and my friend on our little modpack server!!
