### ISSUE TITLE
You can't fly dragons with friends on the server. 1.15.2 / 2.0.1

### ISSUE THREAD

**Issue by Hytrug** [Alex-the-666/Ice_and_Fire#2777]
If I ride my dragon, my friend is expelled from his dragon in his view, but in my view he is still on top of the dragon

The same thing happens to me if he rides his dragon

**Comment by Jusey1** [comment]
This happens with any mount/vehicle.

**Comment by NeonPopsicle** [comment]
This has been an issue for me as well. It throws my friend off when I get on mine and vise versa
