### ISSUE TITLE
Tamed Dragon Despawn

### ISSUE THREAD

**Issue by MollyLovesReptiles** [Alex-the-666/Ice_and_Fire#2778]
Everytime I log out of my Minecraft world my tamed dragon disappears even when inside a dragon horn.

**Comment by Carro1001** [comment]
Did you update to 2.0.1?

**Comment by MollyLovesReptiles** [comment]
Yep. The dragon still despawns.

**Comment by Carro1001** [comment]
That's weird, i just tested and my dragon didn't despawn, what type is it? ice, fire, lightning?

**Comment by MollyLovesReptiles** [comment]
Lightning

**Comment by Carro1001** [comment]
is it nicknamed? what color/stage is it? I nicknamed the dragon and it didn't despawn, maybe delete the config files too if you haven't just in case, since the update added some things there

**Comment by MollyLovesReptiles** [comment]
It was unnamed and stage 5

**Comment by Carro1001** [comment]
Hmmm, yeah that's weird

**Comment by MollyLovesReptiles** [comment]
Sometimes it stays after I leave a world and sometimes it despawns.

**Comment by apertureos** [comment]
Unless this has been modified in later updates, I believe there should be something in the config called "Dragons Despawn", which is automatically set to true to reduce lag. This applies to tamed dragons as well, so dragons that are not named will despawn if the value is left unchanged.

**Comment by AlexModGuy** [comment]
^
