### ISSUE TITLE
Dragons spazzing/glitching out when flying

### ISSUE THREAD

**Issue by blackviperr** [Alex-the-666/Ice_and_Fire#278]
Ever since I started using this amazing mod I've noticed that when the dragons fly, they spaz out in circles, usually still on the ground/glitching into the ground and flip upside down as well.
I've also noticed that I can't attack them at all with any kind of weapon & they also disappear/ reappear when walking/flying.

**Comment by Sunconure11** [comment]
I can confirm this, this seems to happen in creative, when the dragons have no targets.

**Comment by AlexModGuy** [comment]
should be fixed in 1.2.0.
