### ISSUE TITLE
Server crash due to dragonutils.isvillager

### ISSUE THREAD

**Issue by Batman854** [Alex-the-666/Ice_and_Fire#2780]
The crash report attached. 
[crash-2020-09-15_00.25.41-server (1).txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5221781/crash-2020-09-15_00.25.41-server.1.txt)

**Comment by Maruhl** [comment]
Same error on version 2.0.1

[crash-2020-09-15_18.13.05-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5226370/crash-2020-09-15_18.13.05-server.txt)

**Comment by AlexModGuy** [comment]
fixed
