### ISSUE TITLE
Dragon Mounting Issue

### ISSUE THREAD

**Issue by NeonPopsicle** [Alex-the-666/Ice_and_Fire#2788]
Hello!

I’ve been playing in a server with a few pals. When they’re mounted on their dragon and I go to mount my own near them, it makes them shift off of their own dragon. If we’re close together, we can’t get on both our dragons at the same time without someone continuously getting thrown off.

(After 1.15 bug fix release)

**Comment by divinecrnx** [comment]
Yeah, same. A temporary workaround is to mount your own dragons away from each other a few chunks away and avoid dismounting when a friend has their dragon in the sky.
