### ISSUE TITLE
Bestiary

### ISSUE THREAD

**Issue by NeonPopsicle** [Alex-the-666/Ice_and_Fire#2789]
Hello!

The bestiary does not let me add pages to it. When I try to learn another chapter with manuscripts, it says it takes it. As soon as I pull the book away, it tells me it didn’t update the book with a new chapter, and puts the manuscript back.

(After 1.15 bug fix version)

**Comment by Kirvo** [comment]
Me too, but this issue only appears on multipayer. When I tested it on singleplayer it works perfectly.

**Comment by AlexModGuy** [comment]
fixed
