### ISSUE TITLE
Silver Ore generates even when turned off in config

### ISSUE THREAD

**Issue by angelnc1989** [Alex-the-666/Ice_and_Fire#279]
Minecraft 1.11.2
Forge 13.20.0.2304
Ice and Fire 1.1.1

I turned the generation of Silver Ore off in the config file, because I have another mod that already generates Silver Ore.  I started playing and discovered a little cave with Sapphire Ore, Silver Ore from Ice and Fire and some vanilla ores.

**Comment by AlexModGuy** [comment]
That might be a dragons lair so it will still generate in a dragons lair because they like silver.

**Comment by angelnc1989** [comment]
Yes, it was a dragons lair. Is it possible to add the option to use another mods Silver Ore (defined in the config)? I like having only 1 of each ore generate in my modpacks.

**Comment by AlexModGuy** [comment]
I'll remove them from the lairs when the config is false but i wont be able to generate other mod's blocks in their place.
