### ISSUE TITLE
Gorgon temple

### ISSUE THREAD

**Issue by AbraxasSabaoth** [Alex-the-666/Ice_and_Fire#2792]
that's normal?, im using minecraft version 1.15.2, and the last versions of citadel and ice and fire, forge 31.2.0
![2020-09-16_11 02 10](https://user-images.githubusercontent.com/50122411/93349234-9ec20480-f80d-11ea-90e8-7f4396fb4e1c.png)

**Comment by ManedMorph0reload** [comment]
![изображение](https://user-images.githubusercontent.com/62159012/93383574-7ddccc00-f86c-11ea-926f-7d57fbd144ec.png)
same

**Comment by emma-noo-noo** [comment]
I likewise have this problem!
