### ISSUE TITLE
Dragons not moving after reloading save file!

### ISSUE THREAD

**Issue by ThatsMyLive** [Alex-the-666/Ice_and_Fire#280]
So I thought it would only be with that one dragon I had but I recently got a second dragon and saved my game yesterday. I just loaded my game and noticed that the dragons dont move around anymore if I set them to wandering. They dont react to it, neither staying nor wandering makes them walk.

This is also somehow related to the issue when ridable dragons just teleport back to their "stay" point. Everything worked fine with my bigger dragon until I saved and reloadet. Hes now just some passive dude standing around, they also dont breed anymore at that point, as if their AI doesnt load at all.

**Comment by colejagdtiger** [comment]
Is this in 1.1.0 or in 1.1.1?

**Comment by ThatsMyLive** [comment]
@colejagdtiger 1.1.1, but it also happende in 1.1.0, I tried.

**Comment by ThatsMyLive** [comment]
UPDATE: So I played a bit more and I found some interessting "bug". After picking up a lvl1 dragon and placing it back down it is set to "staying" automatically in version 1.1.1 the other version (1.1.0) didnt do this but they also did not move.
You can place the dragon down and click it with the command staff and then it says "dragon is wandering" and if you pick it back up and again down and click on it with the staff it again says "dragon is wandering". (I just remember in version 1.1.0 the dragon keeps the command it got and if on wandering it will be wandering even after having it picked up)

If the dragon is on the ground and you safe the file without setting it again into wandering they do not move anymore after reloading the save game even if you set them on wandering.


The only way I somehow could "unbug" it was after setting it down set it to wandering and then you can safe and reload without problems and its moving. Or the other way, you feed it until lvl2 and reload save file, then it will move again. Idk its a bit tricky and doesnt work alwyas though.

**Comment by AlexModGuy** [comment]
not able to replicate in 1.8.0
