### ISSUE TITLE
Game Crashes whenever I put my cursor over a dragon horn (1.15.2)

### ISSUE THREAD

**Issue by ajhrissl** [Alex-the-666/Ice_and_Fire#2806]
Here's a video of the bug

https://youtu.be/brrvwJZweFU

**Comment by anaoperneta** [comment]
I’m having the same problem, but it’s just in the horns with the ice dragons

**Comment by anaoperneta** [comment]
I only started having this problem when I updated to 2.0.1, version 2.0.0 I didn't have this problem
