### ISSUE TITLE
Game crashes while trying to launch

### ISSUE THREAD

**Issue by deralist** [Alex-the-666/Ice_and_Fire#2812]
I only have this mod and the citadel installed but it crashes on startup.
![error](https://user-images.githubusercontent.com/71568556/93688052-91d23900-facb-11ea-900b-8d322353b84b.PNG)
Here is the error.
[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/5250533/latest.log)
And Here is the log.

**Comment by FufiL** [comment]
Man,i have this trouble too.And i just download citadel-1.1.10,don't 1.1.11 and this all.

**Comment by Pokerfrog** [comment]
Citadel deobf won't work, download the regular one
