### ISSUE TITLE
Incompatibility with a lot of mods

### ISSUE THREAD

**Issue by Matthysse** [Alex-the-666/Ice_and_Fire#2814]
Hello!

The mod works alone, but when added to a big modpack it just doesn't work, it makes every other mod crash. You can see on the attached crash-report that it's exoticbirds which crashes the game, but it crashes only when ice and fire and citadel are in the modpack, without them, the modpack with exoticbirds works perfectly (this mod is just an exemple, when I tried to remove it another mod crash the game).
Here is the crash-report: https://pastebin.com/VmERPb7U

**Comment by AlexModGuy** [comment]
issue is with exoticbirds.client.ClientModEventSubscriber, Exotic Birds.
