### ISSUE TITLE
dragon forge

### ISSUE THREAD

**Issue by nolasabes** [Alex-the-666/Ice_and_Fire#2816]
Hello there is a bug, when I want to make dragon steel with my dragons, they do not spit fire, ice and rays, although I have the dragon blood of each type and iron
I use minecraft 1.15.2
the version of ice and fire 2.0.1

**Comment by kobiYeet** [comment]
Try to put your dragon in the front of the forge (where the aperture is) and not in the sides, it worked for me

**Comment by Pokerfrog** [comment]
Break the aperture and and place it back again, that solves the issue usually

**Comment by nolasabes** [comment]
> Break the aperture and and place it back again, that solves the issue usually

Thanks bro, that just worked for me
