### ISSUE TITLE
1.16.1 Ticking Entity Crash

### ISSUE THREAD

**Issue by MattyExie** [Alex-the-666/Ice_and_Fire#2817]
Didn't happen before install, even removed all other mods

**Comment by FTKenpachi** [comment]
al jugar con el mod el minecraft tiene un crash por un disparo de esqueleto, causado por la misma razón

**Comment by MattyExie** [comment]
Yup, Ice and Fire is literally causing shit to crash server wise. Don't download until they fix it

**Comment by MattyExie** [comment]
there goes a three month world

**Comment by AvrgDerk** [comment]
The world can easily be fixed, use an nbt editor to locate the errored mob and remove it.

**Comment by FTKenpachi** [comment]
igualmente lo mejor va a ser esperar a que arreglen el error en el mod para poder jugar en la nueva versión

**Comment by AlexModGuy** [comment]
fixed
