### ISSUE TITLE
Server crash, I'm guessing its when a fire dragon spawns but idk

### ISSUE THREAD

**Issue by seanld03** [Alex-the-666/Ice_and_Fire#2819]
[crash-2020-09-22_04.28.50-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5259067/crash-2020-09-22_04.28.50-server.txt)

**Comment by seanld03** [comment]
https://pastebin.com/YaDUkRbf

**Comment by MattyExie** [comment]
goddamn thats a lot of mods. Anyways, use pastebin next time, it'll be easier to read/look at. 
https://pastebin.com/zukhtNxF
