### ISSUE TITLE
[suggestion] Dragon sexes

### ISSUE THREAD

**Issue by LatentDesire** [Alex-the-666/Ice_and_Fire#282]
As a key feature of the mod is getting your own dragon, and the eggs to get dragons are only dropped from female dragons, there should be some ways to differentiate male and female dragons. My suggestion, female dragons have less horns on their head, or smaller ridges down their backs.

Another possible update to the dragon models is to have some way of being able to tell when a dragon has reached sexual maturity. Perhaps the horns only come in when dragons are able to breed.

**Comment by LatentDesire** [comment]
Oh, there should also be some worthwhile reward for fighting a stage five male dragon as well. (As I'm sure some may be disappointed that the struggle they've had fight a dragon in hopes of an egg.)

**Comment by AlexModGuy** [comment]
moving this to suggestions tracker
