### ISSUE TITLE
Mobs spawning in modded dimension

### ISSUE THREAD

**Issue by arudon** [Alex-the-666/Ice_and_Fire#2820]
Howdy! I'm playing in the new 1.15.2 version of Ice and Fire, and the mobs (Dragons and trolls) are spawning in the Midnight Dimension. Trolls are absolutely everywhere, and Dragon roosts are off the charts as well. Is there a way to disable mob spawning in a modded dimension?

**Comment by AlexModGuy** [comment]
there are config options for this.
