### ISSUE TITLE
Crash during startup, "Ice and Fire has class loading errors"

### ISSUE THREAD

**Issue by AnotherVagabond** [Alex-the-666/Ice_and_Fire#2821]
I added Ice and Fire to a modpack that had been running fine on its own, and had added no other mods. The crash report mentions Ice and Fire by name, so I'm guessing there's an issue there, but I'm not experienced enough with modding to know what it could be. It crashes the instant it switches from the "early loading process" window to the main window during Forge's startup.

Minecraft: 1.16.1
Forge: 32.0.108
Ice and Fire: 2.0.1

I also checked Forge versions 32.0.106 and 32.0.107 (the lowest versions of Forge allowed by several mods I'm not willing to prune from the pack), and the same crash and error occurs on those versions as well.

[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/5259211/latest.log)
[crash-2020-09-22_00.13.58-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5259213/crash-2020-09-22_00.13.58-client.txt)

**Comment by AnotherVagabond** [comment]
Didn't realize Github would make you download the files there, here's pastebins instead:
[Latest log](https://pastebin.com/54aK9V56)
[Crash log](https://pastebin.com/UeU2ELP1)

**Comment by RandomGuyWithNoName** [comment]
It happens to me too

**Comment by MattyExie** [comment]
It's an issue that they are aware of, they would most likely be working on fixing the crashes for 1.16.1.
Make sure you also instal the right Citidal

**Comment by AnotherVagabond** [comment]
There's only one Citadel for 1.16.1, and Twitch installs it automatically as a required dependency.

**Comment by MattyExie** [comment]
Alright, than as mentioned before, they are aware. 2.0.2 will be bug fixes and stuff, 2.0.1 was just a port

**Comment by Pokerfrog** [comment]
Try the server with just i/f, could be a mod confliction

**Comment by OGitsBoondock** [comment]
Only been out 2 days but I am dying to try this mod for the first time.  It is telling me that it failed auto user yadda yadda.

**Comment by Pokerfrog** [comment]
What version of citadel do you have, full file name

**Comment by Jopken** [comment]
Make sure you have citadel-1.2.0-1.16.1 downloaded and not citadel-1.2.0-deobf, worked for me.
