### ISSUE TITLE
Gorgon killing you crashes game

### ISSUE THREAD

**Issue by footwanterfin** [Alex-the-666/Ice_and_Fire#2823]
The game crashes when a gorgon turns you into stone.
[crash-2020-09-22_20.26.17-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5263061/crash-2020-09-22_20.26.17-server.txt)

**Comment by MattyExie** [comment]
Next time please use PasteBin, much easier to read from. 
https://pastebin.com/5KavP6kU
