### ISSUE TITLE
sea serpent hitbox issue

### ISSUE THREAD

**Issue by kuroyure** [Alex-the-666/Ice_and_Fire#2829]
in the wiki its mentioned that sea serpents have hitboxes in all their segments, in my experience figthing them only hitting the middle of the body deals dammage, therefore that can be considered an issue i hope

**Comment by AlexModGuy** [comment]
version?

**Comment by Pokerfrog** [comment]
I know it happens in 2.0.1, you can only hit them in the middle of their bodies not matter the size
