### ISSUE TITLE
the default spawn rate for ice villages is way to high

### ISSUE THREAD

**Issue by EnderiumSmith** [Alex-the-666/Ice_and_Fire#283]
http://imgur.com/a/0nhHm

that continent has only 4 vanilla villages but a ridiculous amount of ice villages. you come across a new one before the old one leaves render distance. and are a bit too small too. the smaller ones cant even be seen on the map at that zoom level.

also the trade of snow to gems seems a bit OP since there is snow everywhere.

**Comment by colejagdtiger** [comment]
Just change the config setting to increase the rarity.

**Comment by AlexModGuy** [comment]
^^^^^^^^^^^^
