### ISSUE TITLE
1.15.2 Ticking entity server crash

### ISSUE THREAD

**Issue by Gnnome** [Alex-the-666/Ice_and_Fire#2837]
Using version 2.0.1 on a 1.15.2 server, and keep getting a ticking entity crash when ever a dragon tries to spawn. This doesn't happen if I uninstall ice and fire.

https://pastebin.com/kXhfUSv2

Really sucks to see the mod is broken, looks like I'm going to have to wait until there is a fix.

**Comment by AlexModGuy** [comment]
fixed in 2.0.2
