### ISSUE TITLE
Structures not generating properly on 2.0.2

### ISSUE THREAD

**Issue by AeiouEnigma** [Alex-the-666/Ice_and_Fire#2843]
On Ice and Fire 1.16.1-2.0.2, the mausoleums generate with empty chests and pig spawners. They also often generate in broken ways, and perhaps much too frequently, as pictured in the attached screenshots.

![2020-09-23_21 19 00](https://user-images.githubusercontent.com/3160746/94089978-75434300-fde2-11ea-8d9c-de8c89c22819.png)
![2020-09-23_21 14 49](https://user-images.githubusercontent.com/3160746/94089792-09f97100-fde2-11ea-84fe-38c67cf4c64a.png)
![2020-09-23_21 15 28](https://user-images.githubusercontent.com/3160746/94089793-0a920780-fde2-11ea-9ad6-9a531da789b5.png)
![2020-09-23_21 18 24](https://user-images.githubusercontent.com/3160746/94089926-55ac1a80-fde2-11ea-8eae-eed0b3b100f9.png)

User coffee creamer on the Alex's Mods discord server reports broken generation of gorgon temples on 1.15.2-2.0.2 as well

![](https://cdn.discordapp.com/attachments/574284435730464770/758492707257188382/unknown.png)

Update to add that I can confirm the gorgon temple issue on 1.16.1-2.0.2
![2020-09-23_22 02 27](https://user-images.githubusercontent.com/3160746/94092351-81ca9a00-fde8-11ea-8d8e-5a6bc6b3ca01.png)
![2020-09-23_22 04 09](https://user-images.githubusercontent.com/3160746/94092485-e84fb800-fde8-11ea-9874-213124e0fb73.png)

**Comment by MokahTGS** [comment]
This is also a problem with the 1.15.2 version.

**Comment by AlexModGuy** [comment]
dupe
