### ISSUE TITLE
Arrows and Sea Serpents Crashing A Forge Server

### ISSUE THREAD

**Issue by Sl1pstr3am** [Alex-the-666/Ice_and_Fire#2849]
Modpack Link:
https://drive.google.com/file/d/1E_ZF4XsDd5kMGLUT_whx5DH_C6Dcbp1A/view?usp=sharing
Using 1.16.1 Forge 32.0.108
Crash reports attached. Looks to be some kind of problem with sea serpents and arrow collisions. The server just randomly crashes all the time. 

[crash-2020-09-23_19.55.06-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5275874/crash-2020-09-23_19.55.06-server.txt)
[crash-2020-09-23_20.06.48-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5275875/crash-2020-09-23_20.06.48-server.txt)
[crash-2020-09-23_20.11.53-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5275876/crash-2020-09-23_20.11.53-server.txt)
[crash-2020-09-23_20.16.03-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5275877/crash-2020-09-23_20.16.03-server.txt)
[crash-2020-09-23_19.46.39-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5275878/crash-2020-09-23_19.46.39-server.txt)
[crash-2020-09-23_19.47.52-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5275879/crash-2020-09-23_19.47.52-server.txt)
[crash-2020-09-23_19.50.21-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5275880/crash-2020-09-23_19.50.21-server.txt)

**Comment by Blugori** [comment]
What is your ice and fire version ?

Edit : You are not using the last version of the mod, try the 2.0.2 version : 

https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons

**Comment by Sl1pstr3am** [comment]
I'll try that and let you know how it goes.
