### ISSUE TITLE
[Suggestion] Spawn rules for cfg file

### ISSUE THREAD

**Issue by Seth0067** [Alex-the-666/Ice_and_Fire#285]
Hi Alex - Great mod!  I plan on including with my new pack for 1.11.2

Would love to see some spawn rules baked iinto your cfg:

1) Spawn restriction via Y height (so I can keep dragon lairs off sea level and onto mountain peaks or deep deep caves, where they belong)
2) Spawning biome white/blacklist

I can do these rules via some other mods, but i think your users might appreciate having this functionality baked into the mod proper.

Thanks!!

**Comment by AlexModGuy** [comment]
Hello

1. Dragon caves spawn at height 30 or lower.
2. I the config there are biome related whitelists and blacklists.

So what is your issue?

**Comment by Seth0067** [comment]
Hi Alex - 

Thanks for answering.  

I actually want the ability to set spawn heights for Dragon lairs.  My particular use case is I'd like keep the outworld lairs (with gold piles etc) only on heights of 120 or better (approxiomately).  But I am sure other users may appreciate a general cfg spawn option that reads something like:  "outdoor lair y spawn range" and to use a number range for the value,

In my cfg I see dimension white/blacklists, but no biome options.  LMK if I am missing something.

**Comment by AlexModGuy** [comment]
The issue is that they dont necessarily spawn per biome, they spawn based on if the biome has features the dragons find favorable. Ex. Ice dragons only spawn if at the current position it can snow.

**Comment by Seth0067** [comment]
and what about setting spawn heights?  in my worlds i get a number of dragons that just spawning in the middle of overworld flatland areas.  Would like to keep overworld dragons above a certain height so they spawn/lair on mountain tops, etc., but should be a user configurable value ideally.

**Comment by AlexModGuy** [comment]
https://github.com/Alex-the-666/Ice-and-Fire-Suggestions
