### ISSUE TITLE
1.16.1 ice and fire 2.0.2. mausoleum's generation bugged, dread lich don't spawn at all

### ISSUE THREAD

**Issue by jhonnsbx** [Alex-the-666/Ice_and_Fire#2850]
the mausoleums spawn weird or just one half, the chests inside it, don't have any loot, the spawners have pigs instead of dread mobs, and the dread lich spawn is either extremly rare or dont spawn at all
![2020-09-24_09 25 19](https://user-images.githubusercontent.com/16354222/94158402-f5e85a80-fe47-11ea-953c-5337efb66b29.png)
![2020-09-24_09 27 38](https://user-images.githubusercontent.com/16354222/94158702-537ca700-fe48-11ea-8173-01fabe41c1f3.png)

**Comment by bessiq** [comment]
You mean you don't like MAUSOLEUM TOWN?!? 💀 🐷 👻 

![2020-09-24](https://user-images.githubusercontent.com/7315505/94285590-d9b8ec00-ff21-11ea-8726-aba3a1b55bfd.png)

I'm sure the liches have just flown south for the winter, and they and their loot will return after some much-needed fun in the sun. 🏖️🌞🕶️

**Comment by xProBomb** [comment]
Ive also been having this problem

**Comment by Boxtaky** [comment]
Me too and when i break a spawner I get the spawner and xp, so you can generate infinite xp

**Comment by AlexModGuy** [comment]
dupe #2918
