### ISSUE TITLE
MC-1.15.2(I&F-2.0.2) : Hippocampi and Amphitheres don't spawn naturally

### ISSUE THREAD

**Issue by FranPlayer40** [Alex-the-666/Ice_and_Fire#2857]
I have the same problem since 2.0.0 and it is that amphitheres and hippocampi are not spawn naturally and to complete it I comment another that I think happens to everyone and that is that the gorgon temples are generated badly

P.S: I don't speak English well, sorry

**Comment by furretzu** [comment]
Had same issue, unsure if something broke it or not, hopefully it gets fixed in 2.1

**Comment by emma-noo-noo** [comment]
Have this issue too

**Comment by ReneSopG** [comment]
and they are untamable, i spawned with eggs and they cant be feed or riden

**Comment by B-Wither** [comment]
I may have seen Amphithere in 2.0.1, but I think it was too rare or misjudgment.
And yes, there were no hippocampi still in 2.0.2.
