### ISSUE TITLE
Duplicating Manuscript Pages in Lecturn

### ISSUE THREAD

**Issue by iSchyzm** [Alex-the-666/Ice_and_Fire#2859]
After spending 3 pages in the beastiary lecturn, only one page remained. After retreiving the book from the lecturn and exiting the menu, once the lecturn was opened once more, all pages that were originally used previously have returned. Using the pages again on the beastiary works normally as these pages have been duplicated and are not just a glitch.
![ManuscriptDuplication](https://user-images.githubusercontent.com/71853991/94207237-31f5dc80-fe95-11ea-8478-c2a30b6f50f2.gif)

**Comment by Kirvo** [comment]
This was fixed yesterday. Are you playing on version 2.0.2? Anyway, are you playing on a server?

**Comment by AlexModGuy** [comment]
^
