### ISSUE TITLE
Urgent bug - when taking a baby dragon off your shoulder or dismounting a grown dragon game crashed.

### ISSUE THREAD

**Issue by F1reStar** [Alex-the-666/Ice_and_Fire#2861]
Hey there, I have been setting up a server for 1.16.1 using this mod, and whenever I pressed the button to take my baby dragon off my shoulder I get an error message saying **server closed** and I have to restart the server. Whenever I try to join back before restarting I get this error message: **io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information:** I have asked the server host (Apex Minecraft Hosting) and after some digging they found it was a problem with the mod itself. Here is the host's exact words:
**As far as I can see, the MessageDragonControl class is trying to call a vanilla Minecraft method that doesn't exist anymore. It's highly likely this is a leftover from a previous version of the mod - Ice and Fire's 1.16.1 update is very recent (as in, 2 days old), so the creator hasn't fixed all the issues present in it just yet.**
If you could fix this soon that would be great as it makes the mod unplayable and now I am stuck on a dragon.
Thanks!

EDIT: here is the crash report:
[crash-2020-09-25_17.02.01-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5285861/crash-2020-09-25_17.02.01-server.txt)

**Comment by AlexModGuy** [comment]
update to 2.0.2.

**Comment by F1reStar** [comment]
> update to 2.0.2.

Thanks so much I didn't realise I was using an old version lol.
