### ISSUE TITLE
Flying Sea serpent

### ISSUE THREAD

**Issue by 10karat** [Alex-the-666/Ice_and_Fire#2862]
They always doubted him... But he finally did it!
(Yes it is flying) 
I went closer and it is not a client side issue, it was still doing that and not damaging me.
![Minecraft_-1 16 1-Singleplayer-2020-09-25-13-46-43](https://user-images.githubusercontent.com/70038470/94304965-11319380-ff36-11ea-8539-4e6b52e80ab3.gif)

**Comment by ScaryLemonJuice5047** [comment]
Why do you have so much crap in your inventory? Throw it now!
