### ISSUE TITLE
The Dark Structure is everywhere

### ISSUE THREAD

**Issue by ScaryLemonJuice5047** [Alex-the-666/Ice_and_Fire#2863]
![image](https://user-images.githubusercontent.com/71907577/94322099-eceeaa80-ff67-11ea-9ac2-ca108f06fbd7.png)
This is a MC biome, there were more than 10 of those structures with no loot in chests and all spawners were pig spawners.

**Comment by ScaryLemonJuice5047** [comment]
![image](https://user-images.githubusercontent.com/71907577/94322338-a3528f80-ff68-11ea-9fe5-cfd9e170c664.png)
It is this structure, all those rectangles are structures

**Comment by BlueEyesEthan** [comment]
Sorry for the invonvenience, but the Mausoleums are a bit buggy still due to them being new. This is normal at the moment and will most likely be fixed in the new update. For now, please be patient until it's release

**Comment by AlexModGuy** [comment]
fixed
