### ISSUE TITLE
Ice Dragonsteel Sword: xRay

### ISSUE THREAD

**Issue by ScaryLemonJuice5047** [Alex-the-666/Ice_and_Fire#2865]
![image](https://user-images.githubusercontent.com/71907577/94322983-8ae37480-ff6a-11ea-873a-ed1d787cca41.png)
When you hit something and it gets frozen, the ice cube creates a weir xray that shows chests and entities. I found a dragon nest underground thanks to this. Sorry for being so annoying, I know there are lots of people reporting issues, but keep motivated, I love this mod!

**Comment by 10karat** [comment]
Disable fast render on OptiFine, that should do the trick
