### ISSUE TITLE
Pixi jars make the game crash.

### ISSUE THREAD

**Issue by IvorAmlug** [Alex-the-666/Ice_and_Fire#2867]
Whenever i place a pixi jar the game crashes.
Im using the newest build for 1.15.2

**Comment by AlexModGuy** [comment]
crashlog?

**Comment by IvorAmlug** [comment]
[crash-2020-09-28_20.07.38-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5294200/crash-2020-09-28_20.07.38-client.txt)
There it is.

**Comment by AstroMancy** [comment]
having the same issue, here's my crash log. 
[crash-2020-09-28_19.54.46-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5295621/crash-2020-09-28_19.54.46-client.txt)
