### ISSUE TITLE
Terraforge not agreeing

### ISSUE THREAD

**Issue by Ninjayatsu** [Alex-the-666/Ice_and_Fire#2868]
I made it so that the dragons couldn't spawn where the player spawns in the configs, and it works, but when I generate the world with terraforged the configs for generating structures and dragons etc. do not work.

**Comment by Reidlos65** [comment]
So I think I know this one.  Terraforged defaults to setting your spawn in the center ish of one of its landmasses not 0,0.  The config is only protecting x blocks around 0,0 not where terraforged changed your spawn too. for example my terraforged world "spawn" is 804, 66,-4560

**Comment by Ninjayatsu** [comment]
Oh wow, I didn't know it worked like that, I just assumed that it was a I/F problem because they usually have alot of config issues. But thanks for the input! I'll try to figure something out lol

**Comment by Won-Ton** [comment]
You can change terraforged's spawn type to 'world origin' to have it put spawn near 0,0
