### ISSUE TITLE
Broken Mausoleums 

### ISSUE THREAD

**Issue by BlueEyesEthan** [Alex-the-666/Ice_and_Fire#2871]
So I was in another creative world in the glacier biome, found 3 Mausoleums and when I explored them I found 4 mistakes
1: This was said to be fixed, it wasn't. The dread spawners only spawn pigs (I checked every single one)
2: The chests inside every Mausoleum and the Mausoleums underground with the broken dragon forge are all empty with, again, the dread spawners spawning in pigs
3: The spawners aren't even doing anything, they just show the animation but never spawned in even a single mob
4: A Mausoleum spawned with a broken forge above ground (not sure how those work yet) with the walls of it gone, along with some other Mausoleums I found making the key useless if you can get in like this
5: This isn't on the same category, but the Medusa temples also do the same bug with no walls sometimes, making you able to see the redstone and these spawn in beaches, making the Gorgons leave and drown when getting there
![2020-09-26_21 25 05](https://user-images.githubusercontent.com/54153705/94356078-14647680-003f-11eb-85ae-3e7e66cd06c7.png)
![2020-09-26_21 18 07](https://user-images.githubusercontent.com/54153705/94355960-dfa3ef80-003d-11eb-98d9-e15468f051d1.png)
![2020-09-26_21 18 11](https://user-images.githubusercontent.com/54153705/94355961-e03c8600-003d-11eb-8467-4215df81d37d.png)
![2020-09-26_21 28 31](https://user-images.githubusercontent.com/54153705/94356100-7de48500-003f-11eb-91fe-7b70e7d170c9.png)
![2020-09-26_21 29 30](https://user-images.githubusercontent.com/54153705/94356101-7fae4880-003f-11eb-8dc7-471c4eba8e7e.png)
![2020-09-26_21 30 07](https://user-images.githubusercontent.com/54153705/94356103-80df7580-003f-11eb-8b15-08a0832c971f.png)

**Comment by jasonisop** [comment]
I have the same issue. In a forge 31.2.34 instance with iceandfire 2.0.2-1.15.2, citadel 1.1.11, and JEI 6.0.3.15 and no other mods.

**Comment by Pokerfrog** [comment]
It’s a known issue that isn’t the result of other mods

**Comment by AlexModGuy** [comment]
#2918
