### ISSUE TITLE
Problems with the Dragons, Dragon Forge and Dread Buildings. Ice and Fire v1.16.1

### ISSUE THREAD

**Issue by Shalev0** [Alex-the-666/Ice_and_Fire#2873]
I love the mod its really good but there are some bugs well at least for 1.16.1
1. Dragons wont breath into dragonforge (it did the first time i made it but when i tried again later it didnt).
2. When Dragons Breed it Crashes the Server.
3. When you fly with your dragon when chunks load it lags due to it.
4. When Dragons Break blocks it causes lags to the whole server (stage 4-5 practically freezes the server).
5. Dread buildings in ice biomes can be opened at the vault, you can harvest all the blocks inside including dragonforge bricks, the spawners (infinite xp) and all the building materials

**Comment by AlexModGuy** [comment]
#2918
