### ISSUE TITLE
Stage 5 dragons bursting from the floor for no reason [1.9.1]

### ISSUE THREAD

**Issue by Wolfixsp** [Alex-the-666/Ice_and_Fire#2874]
So I've had a server for a week, and something that has been happening is dragons randomly popping out and destroying everything,  to the point it's unplayable,  I had to disable dragon griefing meanwhile but it's sad that this stuff is happening

**Comment by BlueEyesEthan** [comment]
Apologies, but the Minecraft version 1.12.2, Ice and Fire version 1.9.1, is no longer being updated nor being fixed. Please switch onto the newer 1.15.2, or 1.16.1 versions
