### ISSUE TITLE
server on 1.16.1 crashes when mob or player is hit with an arrow

### ISSUE THREAD

**Issue by Mihail16** [Alex-the-666/Ice_and_Fire#2878]
So I made a modded server and added "fire and ice" , "citadel" and JEI. 
I started the server , everything was normal....until i got into a cave, where a skeleton shot me and the server crashed.
When i restarted the server, the skeleton was still there ,shot me the second i joined and the server crashed again.
From the serv. prop. i changed the game to peaceful, OP-ed myslef and joined again to test something.
Got a bow and shot a bat, the result was the same, server crashed.

Here is the crash report:
[crash-2020-09-27_11.52.40-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5293427/crash-2020-09-27_11.52.40-server.txt)

**Comment by xProBomb** [comment]
that was a bug in the 2.0.1 version, and was fixed in the 2.0.2 version check to make sure your using the new version 😁

**Comment by Mihail16** [comment]
yeah bro it worked, thanks.
