### ISSUE TITLE
Dragon rocket immunity

### ISSUE THREAD

**Issue by dragonhuner877** [Alex-the-666/Ice_and_Fire#2879]
when shooting a dragon with a rocket in certain spots it doesnt hit as well as larger dragons having more spots of immunity, dont even take splash damage from nearby rockets.

**Comment by TK-Sougo** [comment]
That is also happening to me. I've tested and the same can happen to serpents and hydras. I think the only hitbox that counts its the center one. Stage 3 and below dragons seem to be easier to hit with the rocket. Stage 4 and 5 gets more tricky to do so.
