### ISSUE TITLE
Config file for Roosts not working

### ISSUE THREAD

**Issue by Reidlos65** [Alex-the-666/Ice_and_Fire#2881]
Using latest 1.15.2 build - using modpack Valhalsia 2 (not a default mod in that pack but I added it)

I have edited the config file to both 
1) lower the chance of a roost spawning 
2) increased distance between dangerous things(roosts etc)

however with that config set, I am spawning a new world (modded so its possible its borking with that ofcourse) but groups of 2-3 roosts in close ish proximity ever maybe 500 blocks when i have it set to 1k distance.

All the other config settings seem to work.  I am going to test a vanilla world to see if im just getting a mod issue but wanted see if there was any possible solutions available / see if anyone else is having issue.

So still modded I tried the 3 world types to see if any of that played a role, did;
 Terraforged+BOP
BOP
Vanilla

all 3 still had clusters of dragon nests in close proximity.  

BOP/Vanilla odly also were bugging out for some reason, splitting medusa forts in half 0_0  didnt see that with my normal terraforged+BOP world but w/e

I am going to try like extreme config like 1 in near MAX chance to spawn with max distance between etc and see what happens.

Update 2:
1 in 9000 chance to spawn does seem to reduce it as one would expect, didnt see more then 1 in 7k blocks.  so chance seems to be doing a bit better, I think its the distance between that isnt working maybe.  I notice a do get medusa and cyclops spawning in clumps but maybe because of beach being a bit rare?

**Comment by MokahTGS** [comment]
I can confirm this.  The config numbers seem to have little to no effect on roost spawning.  I've halved the numbers, both ways and it seems to make little difference.

**Comment by AlexModGuy** [comment]
"halving" the numbers will make the roosts spawn twice as much. Double them to make the structures rarer

**Comment by MokahTGS** [comment]
Did this get closed because you fixed this? Or did this get closed because you are no longer supporting 1.15.2?  Or because you don't think it's an issue?

We are reporting that changing the numbers in any way (Halving or doubling) doesn't seem to make a difference in how they spawn.

**Comment by Pokerfrog** [comment]
Pretty sure it’s 1/_ chance of spawning in a chunk. 1.15.2 is still supported as far as I know and try deleting your configs after updating the mod.

**Comment by Reidlos65** [comment]
I only got them to not spawn in clusters when I put the chance like 1/4000+ or somthing crazy,  I just assumed there was an issue because 3 within 10 chunks constantly even at 1/500 WITH safe distance of 700-1000 between things set was happening.  I havent tried since the udpate that went out so ill take a test run

**Comment by Reidlos65** [comment]
So i know this is closed but wanted to get your thoughts.

Screenshot of a fresh install with the following settings:
Map Pic: https://imgur.com/o4bs20i

settings:
#How far away dangerous structures(dragon roosts, cyclops caves, etc.) must be from spawn(0, 0).
	#Range: 1 ~ 10000
	"Dangerous World Gen Dist From Spawn" = 1000
#1 out of this number chance per chunk for generation
	#Range: 1 ~ 10000
	"Generate Dragon Roost Chance" = 800

if anything those 4 are within less then 500 blocks an 1/800 chance results in these being clustered alot like this.

also things like:
#1 out of this number chance per chunk for generation
	#Range: 1 ~ 10000
	"Generate Dragon Skeleton Chance" = 300
are very rare so its alot of these configs are working just not dragons :)

Its prolly a mod conflict but just figured id post the setup.

Ill try and double it for a bit on another test later
