### ISSUE TITLE
Crash with Fairy Lights when placing Pixie Jars

### ISSUE THREAD

**Issue by anIceyGirl** [Alex-the-666/Ice_and_Fire#2886]
I'm not sure if this is an issue with Fairy Lights or Ice and Fire, but when I attempt to place a jar (empty or otherwise) down, the game crashes. I'm unable to reopen the world since when the game crashes, it saves the world just before crashing, so I have no choice but

[Link to issue on Fairy Light's Repo](https://github.com/pau101/Fairy-Lights/issues/90)
[Fairy Lights' Repo](https://github.com/pau101/Fairy-Lights)
[Crash Log](https://github.com/Alex-the-666/Ice_and_Fire/files/5298980/crash-2020-09-29_08.29.40-client.txt)

**Comment by pau101** [comment]
Just noting the error is returning `null` here where one should not do such a thing: https://github.com/Alex-the-666/Ice_and_Fire/blob/d63624ca31c8041d53623b02c0c1dfbde60d8038/src/main/java/com/github/alexthe666/iceandfire/entity/tile/TileEntityJar.java#L146-L151

**Comment by AlexModGuy** [comment]
fixed
