### ISSUE TITLE
When datapacks are used world fails to load 1.15.2 

### ISSUE THREAD

**Issue by mischiefsfocus** [Alex-the-666/Ice_and_Fire#2888]
When trying to add a datapack to an existing world in 1.15.2, through the saves file, the world fails to open. It stays stuck in the loading screen indefinitely and have to manually close down the program. It does not generate a crash report. All the other mods loaded work with the datapacks and appears to only happen with Ice and Fire. I'm not sure if this an issue just for me, but I did look to see if it had been reported previously. I use only the Vanilla Tweaks datapacks currently with 1.15.2. I have not tried to use the updated 1.16.1 as still waiting for other mods to update so I don't have to start a new world.

Thank you! Love this mod and am very happy that it has been updated.

**Comment by tygor** [comment]
I had a similar issue a few days ago. I was adding some new Vanilla Tweaks data packs. I do however how a few running successfully:

These all work:

- anti enderman grief v1.0.0
- double shulker shells v1.0.3
- more mob heads v2.2.0
- multiplayer sleep v1.0.1
- player head drops v1.0.0

These prevented the server from starting:

- fast leaf decay v2.0.3
- spawning spheres v1.1.0
- timber v2.1.0

**Comment by mischiefsfocus** [comment]
The ones that I use that I haven't had any luck with are the anti creeper grief; anti ghast grief; workstation highlights; F2L; and Pillager tools. The big ones being the anti creeper and anti ghast because after spending hours (or days) on builds only to have a creeper blow it up is beyond frustrating. I have a mod for the creeper that I was using in the 1.12.2 version that also works for 1.15.2 , but it would nice to be able to reduce the number of mods.
