### ISSUE TITLE
Just a Little Complainy Vent Thing

### ISSUE THREAD

**Issue by CommandBlockGuru** [Alex-the-666/Ice_and_Fire#2889]
I really wish that IaF stayed on 1.15.2 cause the mods for 1.16.1 are so slim. All the good mods are on 1.12.2 and 1.15.2. I'm just really upset that it won't be updated for 1.15.2 or 1.12.2 anymore. I guess I at least have a lightning dragon I guess that's good, but I was really excited for the dread queen and the fire demon guy I don't remember the name of. I'll still be updating to 1.16.1, but I'll almost never play that version.

**Comment by azuichh** [comment]
why that in issues, bc that not rly an issues

**Comment by Yolo1324** [comment]
Not an issue but l 100% agree on that. Besides, some great 1.12.2 mods are even planning to update to 1.15.2. Even Advent of Ascension.
