### ISSUE TITLE
"Missing License Information in file Mod File..."

### ISSUE THREAD

**Issue by KeterNihil0** [Alex-the-666/Ice_and_Fire#2892]
I've tried out a few different versions of Ice and Fire in the 1.16.3 version of Minecraft, but it generally doesn't seem to want to get to the title screen, I'm going tot try and see if it's a mod conflict or forge version conflict

![image](https://user-images.githubusercontent.com/66521222/94849019-b52aab80-041c-11eb-8a3b-91816b8d6cff.png)

**Comment by M3RGeo** [comment]
I fixed it by adding a license field within the mods.toml file, but after that it gives another error making the mod unplayable on 1.16.3 for the moment.( I know the mods isn't updated to 1.16.3 yet, so i expected some errors.)

The error I'm getting is 
Failed to create mod instance. ModID:iceandfire, class com.github.alexthe666.iceandfire.IceAndFire java.lang.VerifyError: Cannot inherit from final class

[crash-2020-10-01_21.15.37-fml.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5314313/crash-2020-10-01_21.15.37-fml.txt)

**Comment by KeterNihil0** [comment]
I tried that as well, same results... I'm not sure if this is a bug with this version or whether it's only happening with some users, as I've heard that some people are playing with the mod and having no issues

**Comment by M3RGeo** [comment]
I can confirm the same issue happens on 1.16.2
[crash-2020-10-01_22.53.05-fml.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5314696/crash-2020-10-01_22.53.05-fml.txt)

**Comment by KeterNihil0** [comment]
So, it seems like the 1.16.1 version ONLY works in 1.16.1, which makes sense, however the license thing may be an issue in future, so I'll leave this issue open unless somebody decides otherwise

**Comment by Green318** [comment]
I am having the same problem with the placeable items mod by ferdz_
