### ISSUE TITLE
Myrmex Cave failure of friendliness and failure of Ambrosia 

### ISSUE THREAD

**Issue by messicedragon** [Alex-the-666/Ice_and_Fire#2893]
(In Ice and Fire 1.15.2-2.0.2)
Exiting and re-entering a game will cause the Myrmex Caves' friendlyness to clear,we must once again give a myrmex resin chunk to restoration friendliness, or myrexes will against us.
And Ambrosia can stack many of them, but no matter how many you stack, you'll eat them all at once, and only one bowl will be returned.

**Comment by AlexModGuy** [comment]
fixed
