### ISSUE TITLE
Null

### ISSUE THREAD

**Issue by Esi-Sandre** [Alex-the-666/Ice_and_Fire#2894]
I installed the 1.16.1 version of ice and fire, both versions that are on the list. Both have the same issue.

![Minecraft Mod Null Error](https://user-images.githubusercontent.com/72237712/94879970-bb765300-042f-11eb-9182-f15b77e9e86d.png)

I have no idea why it isn't working, it simply says null and nothing else despite me having the correct version of citadel on the correct version. I've tried several times to restart the game and launch it again and it doesn't do anything. Forge clearly reads it and it's acknowledged in the load screen for forge.

**Comment by Pokerfrog** [comment]
What’s the entire name of your citadel file?

**Comment by Esi-Sandre** [comment]
> What’s the entire name of your citadel file?

citadel-1.2.0-deobf

![Screenshot Of File](https://user-images.githubusercontent.com/72237712/94881015-a818b700-0432-11eb-9001-8603853d88f6.png)

**Comment by Pokerfrog** [comment]
Download the regular version of citadel, deobf won’t work

**Comment by Esi-Sandre** [comment]
> Download the regular version of citadel, deobf won’t work

Gatcha, thank you!
