### ISSUE TITLE
Structures spawn

### ISSUE THREAD

**Issue by EpicViking** [Alex-the-666/Ice_and_Fire#2895]
Hey, i was building in creative and then found this...
![bug1](https://user-images.githubusercontent.com/72273784/94951838-45ccbe80-04e5-11eb-9a44-ef2744c55cec.png)

**Comment by CreatorYager** [comment]
Same thing is happening to me.. I tried to disable the gen in the configs but they still spawn.. Think the configs are broken for 1.16

**Comment by AlexModGuy** [comment]
dupe #2918
