### ISSUE TITLE
The martians can hear your lightning dragons.

### ISSUE THREAD

**Issue by WalterTheMighty** [Alex-the-666/Ice_and_Fire#2896]
They big loud.

I have one on a hill about 30 blocks off the ground. I can hear it from my room which is at y-44 and around 90 blocks away horizontally. It sounds like I'm standing right next to it. It's also at the same volume if I turn my volume down to like 5%.

**Comment by Pokerfrog** [comment]
What do have hostile entities to?

**Comment by WalterTheMighty** [comment]
Tried that, it's 20%, no change.

**Comment by Pokerfrog** [comment]
Does it stop at 0?

**Comment by trench6** [comment]
ah yes it's simple. It's all cus of the sound system I/F uses. There's no true stereo nor sense of depth unlike what you hear in normal MC, so the volume and stereo field positiong wont vary; no matter how far you are, as long as the chunk where the dragon stands is loaded, it will always sound the same. Now the volume part is most likely a bug, so i hope that gets fixed u.u

**Comment by BlueEyesEthan** [comment]
this bug does not happen just with the lightning dragons. I've had ice dragons do the same, but only the large ones
