### ISSUE TITLE
 Horn animation with lightning dragon inside. I/F 1.15.2 (2.0.2)

### ISSUE THREAD

**Issue by Phantom2909** [Alex-the-666/Ice_and_Fire#2898]
The horn does not have the purple light when it is in the item bar (but in the hand it does), I thought it was normal, until I put ice and fire dragons on the same horn and they did have the lights.
![2020-10-03_13 17 39](https://user-images.githubusercontent.com/70826397/94998926-3a2bd700-057b-11eb-95b8-def903e792d9.png)

**Comment by nighthawk037** [comment]
No, the light is in the horn on your hot bar. It's just a bit dim

**Comment by AlexModGuy** [comment]
^
