### ISSUE TITLE
Better Gorgon temple spawn 

### ISSUE THREAD

**Issue by disastercube** [Alex-the-666/Ice_and_Fire#2903]
**Minecraft 1.12.2**
--------------------------------------------------------------
Gorgon temples always spawn with send underneath making it really unrealistic if it spawns on grassy land and in most cases it makes a cravas, reducing the realism even further.
But you're lucky if it spawns on land, because it has the ability to spawn underwater as well. 
![2020-10-04_17 46 56](https://user-images.githubusercontent.com/62697421/95020335-c832bb00-066a-11eb-92f5-52527004014e.png)

**Comment by briimarie** [comment]
mine spawn up in the sky and don't even spawn as one. sometimes we find random pillars or walls from them.
