### ISSUE TITLE
Dragon server breeding error

### ISSUE THREAD

**Issue by apertureos** [Alex-the-666/Ice_and_Fire#2907]
Hi, I'm running a 1.15.2-forge-31.2.41 server with Ice and Fire 2.0.2 and whenever my friend and I try to breed his stage 5 male ice dragon and my stage 4 female ice dragon with the ice lily mixture, we are both kicked with the 'NullPointerException' error upon giving the second dragon the mixture (the server doesn't crash, though). When we log back in, a nest is made, but there is no egg. I checked console and found this message: . I tried again with two stage 4 ice dragons that were both mine, after updating my server to 1.15.2-forge-31.2.44, I got the same error.
Logs / lists:
I couldn't make a pastebin of the client logs or the 1.15.2-forge-31.2.44 logs because they were too large, so let me know if you need me to find another way to include those.

**Comment by zucaluca** [comment]
Same on Lan Worlds, but everyone except the host gets kicked.

**Comment by AlexModGuy** [comment]
fixed
