### ISSUE TITLE
Summoning crystal error 1.12

### ISSUE THREAD

**Issue by Iamoutofideas** [Alex-the-666/Ice_and_Fire#2908]
Hello there, I'm currently playing on a modded Minecraft server in 1.12.2 and the summoning crystals aren't working at all. I've tried with enough space, both ice and fire crystals and various things none seem to work. Also do ya'll plan to develop the mod for 1.12 further? or will it only stay a 1.15 and up thing? 
Thanks
 Iam.

**Comment by BlueEyesEthan** [comment]
Hello Iam. The 1.12.2 version is no longer supported, it remains 1.15.2+. However, this may be a bug for some people as I've been able to use them in 1.12, but I recommend porting up to 1.15.2 or 1.16.1 for more updates, along with the Lightning Dragon and bug fixes
