### ISSUE TITLE
Crash Exit Code 0 with Ice and fire

### ISSUE THREAD

**Issue by LittleSneeeeek** [Alex-the-666/Ice_and_Fire#2909]
Game version: 1.12.2 

I wanted to play with the ice and fire mod today and dragged it into the mods folder. I started the game and crashed immediatly with the Exit Code: 0 crash. I got checked every mod and only the fire and ice mod triggered the crash. Can you pls help me?

Mod version: iceandfire-1.9.1-1.12.2

**Comment by xZaino** [comment]
Did you install library?
