### ISSUE TITLE
Broken Configs/Structure gen

### ISSUE THREAD

**Issue by CreatorYager** [Alex-the-666/Ice_and_Fire#2913]
Setting the glacier gen to false or changing the config in general doesn't work. I've tried multiple times to change the configs and nothing happens. Also mausoleum spawns are busted.. One glacier biome can spawn up to 10 of them all very badly generated as well, floating, half destroyed, etc. Same goes with the gorgon temple.

**Comment by AlexModGuy** [comment]
merged w/  #2918
