### ISSUE TITLE
Four major issues regarding mausoleums 

### ISSUE THREAD

**Issue by Inpaladin** [Alex-the-666/Ice_and_Fire#2916]
First up is strange generation patterns.  In biomes where they can spawn, there is a mausoleum every ~150 blocks or so.  Editing the config does not appear to change anything.
Second is broken generation.  In the first image I provided you can probably see the issue.  Roughly half of the mausoleums generated have a bit of them cut off, revealing the inside.  The exposed side is always the one facing north.
Third is the spawners.  In the second screenshot you can see that the spawners in the mausoleum are all pig spawners.  This is uniform across all mausoleums generated.  
Lastly is the empty chests.  Every chest in every mausoleum is empty.

![image](https://user-images.githubusercontent.com/59532097/95154715-52505180-0747-11eb-80a0-b807452f1db7.png)

![image](https://user-images.githubusercontent.com/59532097/95154659-2f25a200-0747-11eb-855b-798df9b88e68.png)

**Comment by AlexModGuy** [comment]
merged w/  #2918
