### ISSUE TITLE
version 2.0.3. fire dragon breeding problem on lan

### ISSUE THREAD

**Issue by agr21** [Alex-the-666/Ice_and_Fire#2920]
it still kicks out the joined players,except the host,and they cant join back,tested in newly generated world
[06Oct2020 23:33:09.257] [Netty Server IO #14/ERROR] [net.minecraft.network.NettyPacketEncoder/]: java.lang.NullPointerException
[06Oct2020 23:33:09.323] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: [joined player's name] lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException

**Comment by apertureos** [comment]
Having the same issue breeding two stage five ice dragons, one being my friend's and one being mine. My server is running 1.15.2-forge-31.2.44. Here's the full server log: https://pastebin.com/xwx0WgTM. (I apologize for commenting on another issue, I just didn't want to make a duplicate one).

**Comment by naiski** [comment]
@Alex-the-666 I seem to have been able to fix this problem locally by making this change:

EntityDragonEgg.java:86
```
    @Override
    protected void registerData() {
        super.registerData();
        this.getDataManager().register(DRAGON_TYPE, Integer.valueOf(0));
        this.getDataManager().register(DRAGON_AGE, Integer.valueOf(0));
        //this.dataManager.register(OWNER_UNIQUE_ID, null); <-- Remove this line
    }
```

EDIT: PR here https://github.com/Alex-the-666/Ice_and_Fire/pull/2928
