### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by CommandBlockGuru** [Alex-the-666/Ice_and_Fire#2921]
Please LOWER ROOST SPAWN RATES
![Screenshot (11)](https://user-images.githubusercontent.com/68716063/95270529-a6236f00-0809-11eb-8bb1-73d55a808b47.png)
THIS IS MADNESS

Also for 1.15.2 it doesn't let you config the file and that makes me even more sad since I can't do it myself.

**Comment by azuichh** [comment]
and what if you just use the mod config ? they made for that ...

**Comment by Carro1001** [comment]
You know you have to edit the config outside of the game now right?

**Comment by Pokerfrog** [comment]
Yeah, its in the config file inside of your .minecraft folder

**Comment by azuichh** [comment]
yes you just have to edit them in the game folder

**Comment by CommandBlockGuru** [comment]
Wish it stayed the other way >:v
