### ISSUE TITLE
Aiming is broken for certain weapons (1.16.1) (IF ver. 2.0.3)

### ISSUE THREAD

**Issue by Johnsun369** [Alex-the-666/Ice_and_Fire#2923]
There are certain weapons that travel in the wrong direction when used. Items affected: Tide trident, Dragonbone Bow, Stymphalian bird feather bundle

Video: https://streamable.com/1fa6kc

**Comment by azuichh** [comment]
in which version of i/f ?

**Comment by BlueEyesEthan** [comment]
@azuichh that my friend is in the title

As for the aiming of these weapons, it's happened as well in the latest version. I hoped it would be fixed, but it hasn't. We'll see if it is in the next update

**Comment by azuichh** [comment]
actualy that the mincraft version i ask for i/f version

**Comment by BlueEyesEthan** [comment]
well you see, in the 2.0.2 + 2.0.3 and I believe 2.0.1 have this glitch
