### ISSUE TITLE
ice and fire's projectiles still bugged (1.16.1)(2.0.3)

### ISSUE THREAD

**Issue by jhonnsbx** [Alex-the-666/Ice_and_Fire#2924]
the ice and fire's projectile weapons (the tide trident, dragonbow and feather bundle) are still bugged (the projectiles are shout to the floor, and the charging animations don't work properly).

**Comment by BlueEyesEthan** [comment]
not just on the floor, the shots are always within random directions but always the same ones. Up, down, and depending on where you're facing, left and right. Or just straight or backwards. Hopefully this is soon fixed
