### ISSUE TITLE
weird underground structures generation (1.16.1)(2.0.3)

### ISSUE THREAD

**Issue by jhonnsbx** [Alex-the-666/Ice_and_Fire#2925]
the dragoncaves and the myrmex colonies frecuently apear cutted in some way by a random normal chunk, or another random structure.
![2020-10-06_20 34 50](https://user-images.githubusercontent.com/16354222/95277642-e851ae00-0813-11eb-9d2d-b5f38391704c.png)
![2020-10-06_20 35 04](https://user-images.githubusercontent.com/16354222/95277646-eb4c9e80-0813-11eb-8ddc-8a17c19c36f5.png)
![2020-10-06_20 35 13](https://user-images.githubusercontent.com/16354222/95277653-edaef880-0813-11eb-8485-de3a6854c56c.png)
![2020-10-06_20 36 27](https://user-images.githubusercontent.com/16354222/95277657-f0a9e900-0813-11eb-857e-4f9505727091.png)
![2020-10-06_20 34 36](https://user-images.githubusercontent.com/16354222/95277659-f3a4d980-0813-11eb-8e55-e8be1775d7e9.png)
![2020-10-06_20 34 47](https://user-images.githubusercontent.com/16354222/95277665-f56e9d00-0813-11eb-8da2-05a62ba609bf.png)

**Comment by BlueEyesEthan** [comment]
This is something that's happened to many people for a long time. Whether this will be fixed or not and Alex finds it as a bug is unknown

**Comment by TelepathicGrunt** [comment]
If that's done as a feature, then it is most likely the feature is too large and is hitting the edge of an already generated chunk which cuts it off. Features spawn in a chunk with the surrounding 8 chunks (diagonal and adjacent) being safe to generate in. Past that one chunk radius and that guarantee is gone.
