### ISSUE TITLE
Myrmex disappear when I relog | 1.16.1

### ISSUE THREAD

**Issue by Maccadams** [Alex-the-666/Ice_and_Fire#2927]
Every time I find myrmex, both wild and spawned, they all disappear when I log in next.  No error or anything, they're simply gone.

**Comment by BlueEyesEthan** [comment]
Does this always happen? Do you know if you have any other mods that could be causing this? Have you tested this?

**Comment by Maccadams** [comment]
> Does this always happen? Do you know if you have any other mods that could be causing this? Have you tested this?

it hasn't happened in any other IaF version I've used, and I opened IaF alone and it was still happening, so it can't be any other mod.
