### ISSUE TITLE
Game crashes whenever dragons are breed together (1.16.1) (2.0.2)

### ISSUE THREAD

**Issue by t0ec0llector** [Alex-the-666/Ice_and_Fire#2929]
Every time someone on my server breeds their dragons together it kicks everyone out (including them). Here's the log https://mclo.gs/CKZKt8b I've tried fixing it myself but I can't figure out why it's even happening.

**Comment by naiski** [comment]
See https://github.com/Alex-the-666/Ice_and_Fire/issues/2920
and https://github.com/Alex-the-666/Ice_and_Fire/pull/2928

EDIT: this worked for me in 1.15.2, dunno about 1.16.1
