### ISSUE TITLE
suggestion: building contest, but for everything

### ISSUE THREAD

**Issue by kuroyure** [Alex-the-666/Ice_and_Fire#2935]
since the village and pillage updates and update aquatic, minecraft structures have become increasingly better looking, i feel ice and fire needs to follow the trend with its structures, either abandoning them for mobs that dont benefit from them (hydra, cyclops/wandering version has spawning issues btw/, ligthning dragons) or reworking the extant ones like the mausoleum that is just a cube rigth now (even maybe adding new ones like sea serpent nests in deep seas in the form of sunken ships) 
For that id suggest holding building contests again for all creatures to help refresh those, maybe add true dungeons filled with trolls and chained monsters with unique rewards(like some of i/f non renewable mob ressources, hydra fangs, serpent scales, dragon scales) and block the ability to place blocks inside them or break its blocks, kinda like the mausoleum.

**Comment by BugmanBugman** [comment]
I like this idea
