### ISSUE TITLE
(2.0.3 - 1.16.3) - Config Bugs

### ISSUE THREAD

**Issue by Jusey1** [Alex-the-666/Ice_and_Fire#2936]
So, a lot of config related bugs has been fixed (such as disabling Gorgon temples) but Dragonsteel Weapon Damage and Dragonsteel Armor configs are still bugged. Also, the health for Sirens are now broken as well (I usually set Sirens to have 20 health but it isn't working at all).

Also, the config itself is still jumbling itself all over the place which makes it harder to edit and change it after the initial edit (though the initial edit works perfectly at least).

**Comment by SDUBZ** [comment]
https://gist.github.com/SDUBZ/069e01c87aaa818c78e07b35ad6e09da
