### ISSUE TITLE
dragons hover in place spinning

### ISSUE THREAD

**Issue by EnderiumSmith** [Alex-the-666/Ice_and_Fire#294]
after a dragon takes off it will spin in place like a mob on a fence moving very little and looking weird. it should circle around a much bigger area instead.

i have advanced flight AI off because the game freezes when the dragon lands with it on

**Comment by darthvader45** [comment]
I'd add an FPS-improving mod like BetterFPS, Surge and Foamfix Anarchy.  Work great.

**Comment by EnderiumSmith** [comment]
i have and fps is not the problem. with advanced AI on when a dragon lands the server freezes and i have to kill the process.

**Comment by darthvader45** [comment]
Have you tried allocating more RAM?  Also, what version of Ice and Fire?

**Comment by EnderiumSmith** [comment]
1.1.1 which is latest. i allocated all the ram.

**Comment by darthvader45** [comment]
I suggested the most likely cause, which is the dragon using its breath attack on mobs that aren't attacking it, using chests or breaking gold piles.

**Comment by EnderiumSmith** [comment]
most likely cause of what?

**Comment by darthvader45** [comment]
Of the freezing.

**Comment by EnderiumSmith** [comment]
i hit the dragon, dragon lands, server freezes, client looks unaffected, need to kill process from system manager.

**Comment by darthvader45** [comment]
#287 Take a look here.

**Comment by EnderiumSmith** [comment]
but the problem is dragons spinning in place while flying. they do that with advanced AI too.

**Comment by darthvader45** [comment]
Yeah, that might be due to dragons checking for blocks in a radius that's too large.  I think they should only check for blocks that are quite close to their collision box.  Either that or make the collision box more like that of the ender dragon.

**Comment by Burgersim** [comment]
I just wanted to say, I heve exactly the same issue: dragon takes off, spind in the air, doesn't really attack, unless it when it occasionally lands, you can loot the whole horde, while he's doing that, so not really a challenge then ^^* hope this can be fixed soon, was looking forward to epic fights against these beasts ^^

**Comment by AlexModGuy** [comment]
should be fixed in 1.2.0

**Comment by darthvader45** [comment]
@Alex-the-666 Good to hear, perhaps dragons won't be so derpy or laggy anymore.  We will see....
