### ISSUE TITLE
Lightning Dragon breeding go bababooey

### ISSUE THREAD

**Issue by Elfzenon** [Alex-the-666/Ice_and_Fire#2941]
It seems that I have doomed myself on my server by breeding a pair of Stage 5 Lightning Dragons and now the chunk (of which im permanently stuck in) kicks me instantly from the point that I join.

**Comment by GamesCrazyCarz** [comment]
Can confirm this now happens with Fire and Lightning dragons, I was lucky enough to be able to take backups of the server before I was breeding. Throws this error to the player and server console however no more info on the error
Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException

https://cdn.discordapp.com/attachments/760501548777734165/765243106051358770/Dragon_Breeding_Crash.mp4

**Comment by naiski** [comment]
I have a PR for fixing this in 1.15.2 here: https://github.com/Alex-the-666/Ice_and_Fire/pull/2928
