### ISSUE TITLE
Suggestion: Effects of Lightning Dragon's Breath

### ISSUE THREAD

**Issue by Phantom2909** [Alex-the-666/Ice_and_Fire#2947]
Fire dragons leave flames and ice dragons leave spikes (apart from the respective charred and frozen blocks), but lightning dragons only leave crackled blocks; My idea is that their breath paralyzes mobs (like a stun gun) or that electrical "particles" are left in the crackled blocks, which fulfill the same functions of causing damage, such as flames or spikes. And that the water is conductive (like real electricity). It's just an idea.

**Comment by azuichh** [comment]
the Lightning breath don't have any effect but he do more direct damage than the fire and ice breath that why he don't have any effect
