### ISSUE TITLE
[1.16.3]Tide Tridents, Feather Bundles, and Dragonbone Bows always firing straight up regardless of camera angle.

### ISSUE THREAD

**Issue by Inpaladin** [Alex-the-666/Ice_and_Fire#2948]
Title.  Don't know if this is part of the issue or it's own thing but when charging the trident it also points straight up in the 3rd person model.  The Dragonbone Bow also doesn't have a dynamic model for the different drawing stages, in that last picture the bow is fully drawn.
![image](https://user-images.githubusercontent.com/59532097/95642460-84bac100-0a5d-11eb-89aa-973504c20a6b.png)
all tridents in the second image were fired in the direction the camera is currently pointing and landed there.
![image](https://user-images.githubusercontent.com/59532097/95642543-fa269180-0a5d-11eb-8545-924dd1b91a04.png)
![image](https://user-images.githubusercontent.com/59532097/95644435-8ab79e80-0a6b-11eb-8cc7-e649166320ab.png)

**Comment by BlueEyesEthan** [comment]
This is a bug that was in the previous versions that's been found. Hopefully it'll be fixed, for an bug fix has been released and these items still are the same
