### ISSUE TITLE
Config Options not working  1.16.3

### ISSUE THREAD

**Issue by MLMII** [Alex-the-666/Ice_and_Fire#2950]
Minecraft:  1.16.3
Forge:  34.1.16
Ice & Fire:  2.0.3

Some of the config options don't seem to do anything; 

Gorgon Spawn Weight
Dangerous Structures have to be "x" apart

...

As a workaround I've completely disabled the Gorgon Temples and adjusted the other spawn weights by trial & error but being able to force a min distance between them would be a nicer option as well as allowing me to have the occasional Gorgon Temple.

**Comment by Inpaladin** [comment]
Seconding this, Dragonsteel armor/damage values and tamed dragon griefing also appear to be broken.
