### ISSUE TITLE
Stymphalian Birds crash the game whenever I shoot an arrow near them.

### ISSUE THREAD

**Issue by TheWhaleBoss7** [Alex-the-666/Ice_and_Fire#2951]
Minecraft Version: 1.15.2

Forge Version: 31.2.41

Brief Description: Normally, I am able to shoot arrows in-game at every mob I encounter. But if I ever encounter Stymphalian Birds then my game crashes whenever I shoot at them. The game crash file says it has to do with arrows (I think).

Thanks

[crash-2020-10-10_08.20.51-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5360220/crash-2020-10-10_08.20.51-server.txt)

**Comment by AlexModGuy** [comment]
issue is with com.shultrea.rin.enchantments.crossbow.EnchantmentAmmunitionless.onArrowLoose.

some enchantments mod I presume? report it to them
