### ISSUE TITLE
[1.16.3]Dragon Caves always generating with parts cut off.

### ISSUE THREAD

**Issue by Inpaladin** [Alex-the-666/Ice_and_Fire#2956]
It's kind of hard to explain with words so I'll just let screenshots explain the issue
![image](https://user-images.githubusercontent.com/59532097/95691325-2d3e6180-0bd3-11eb-824f-7ed701d4f0d6.png)
![image](https://user-images.githubusercontent.com/59532097/95691333-40513180-0bd3-11eb-8ae0-e73dc0bce8e8.png)
![image](https://user-images.githubusercontent.com/59532097/95691413-ddac6580-0bd3-11eb-84e4-1a0821659d69.png)
![image](https://user-images.githubusercontent.com/59532097/95691422-f9b00700-0bd3-11eb-950e-81e42803571e.png)
found one that intersected with a stronghold!

**Comment by Inpaladin** [comment]
![image](https://user-images.githubusercontent.com/59532097/95691453-37ad2b00-0bd4-11eb-9abb-87997cc12666.png)
again in a double dragon cave

**Comment by BlueEyesEthan** [comment]
This is an old.. bug. Whether Alex and the rest find it as a bug is unknown but wait and find out

**Comment by Inpaladin** [comment]
> This is an old.. bug. Whether Alex and the rest find it as a bug is unknown but wait and find out

I've played a ton of 1.12 and have never noticed this as often as in 1.16.  Like I said in the title, they _always_ generate like this.
