### ISSUE TITLE
Back to Config File Editing

### ISSUE THREAD

**Issue by CommandBlockGuru** [Alex-the-666/Ice_and_Fire#2957]
I just don't want my dragons to be able to break blocks and don't want a dragon close to the surface in a cave to escape. When I put dragon grieving to 2 and drags break blocks to false it doesn't even do anything. PLEASE put it back to how it was before. It's so much more confusing now, I didn't even think it was possible to edit the config setting until I had somebody tell me on here. PLEASE make it back to us being able to edit from the config.

**Comment by Inpaladin** [comment]
The config file is currently broken on the 1.16 versions.  That's why setting the values isn't working.

**Comment by CommandBlockGuru** [comment]
I'm guessing that also means 1.15.2 *Sad* Thanks m8 :)
