### ISSUE TITLE
[1.16.3] flying sea serpents

### ISSUE THREAD

**Issue by Inpaladin** [Alex-the-666/Ice_and_Fire#2958]
Sea Serpents can just... fly.
![image](https://user-images.githubusercontent.com/59532097/95706364-832efb80-0c0b-11eb-96b4-6c36ff05a4b4.png)
It appears that it's just chaining jumps over and over mid air.  For whatever reason switching to survival mode around 100 blocks away caused it to fall to the ground.

**Comment by BlueEyesEthan** [comment]
Sea Serpents have been air serpents for a long time, the creators are most likely already fixing this and I recommend being patient until they're no longer buggy, that would be hard considering the coding that goes through all this
