### ISSUE TITLE
add more options to tamed dragons

### ISSUE THREAD

**Issue by EnderiumSmith** [Alex-the-666/Ice_and_Fire#296]
heres some ideas to make managing tamed dragons easier:

1: toggle breath-if off the dragon wont use its breath attacks when AI controlled. players riding it can still use it. use flint and steel to toggle. because some want to keep a dragon in a house made of wood 

2: wander without flight-the dragon wont take off but still wander

3: follow-the dragon follows the owner

the dragon command staff will switch between 2 and 3 in addition to stay and follow

4:set home-shift right click with the command staff to set the home of the dragon

5:call-the dragon will come to the location the owner used the flute

6:commanded attack-the dragon will attack enemies that the player attacks or that attack him like a dog does. maybe shift click with the flute to toggle between the 3 possible combinations, otherwise have it active when dragon is in follow mode

**Comment by AlexModGuy** [comment]
no follow modes for dragons. these arent just flying, mountable wolves.

**Comment by AlexModGuy** [comment]
https://github.com/Alex-the-666/Ice-and-Fire-Suggestions
