### ISSUE TITLE
1.15.2-2.1.0   Config Bugs

### ISSUE THREAD

**Issue by dong1993523** [Alex-the-666/Ice_and_Fire#2968]
![IP{(NV@`9 (KE0XA2F50U$M](https://user-images.githubusercontent.com/54309998/95809630-d1461b00-0d41-11eb-8031-dda307464a57.png)
![2}H 6X{4QCO9%I2V17N%(KL](https://user-images.githubusercontent.com/54309998/95809633-d4d9a200-0d41-11eb-8cd8-e4599a2ba49a.png)
![}2_N7I2OJR%Q~3J33VA)I~3](https://user-images.githubusercontent.com/54309998/95809636-d73bfc00-0d41-11eb-98c5-860c3fefe76e.png)
![D21BR OIKKOFA3IW(`FMI 1](https://user-images.githubusercontent.com/54309998/95809642-dc994680-0d41-11eb-8058-41f72deaf6d9.png)
I changed the configuration, but it didn't work

**Comment by dong1993523** [comment]
![Uploading 2}H[6X{4QCO9%I2V17N%(KL.png…]()

**Comment by dong1993523** [comment]
![1](https://user-images.githubusercontent.com/54309998/95809755-22560f00-0d42-11eb-8728-440a5c9d8976.png)

**Comment by dong1993523** [comment]
and"Dragonsteel Base Armor"

**Comment by Inpaladin** [comment]
I reported this a few days ago, It appears to actually be an issue with most of the options in the config.  It's effecting all of the 1.15+ versions.
https://github.com/Alex-the-666/Ice_and_Fire/issues/2915
