### ISSUE TITLE
Just in case this has to be fixed on your end

### ISSUE THREAD

**Issue by Sunconure11** [Alex-the-666/Ice_and_Fire#297]
https://github.com/SpongePowered/SpongeForge/issues/1748

**Comment by Sunconure11** [comment]
There's also the issue of dragons from ice and fire despawning with sponge, causing players to lose their tamed dragons and what not. A possible fix would be to mark them as creature, as opposed to monster. Use the EnumCreatureType system for this.

**Comment by AlexModGuy** [comment]
They arent monsters. They directly extend from EntityTameable.

**Comment by Sunconure11** [comment]
https://pastebin.com/CJ9s4y5N

Stumbled upon this crash with your villagers and spongeforge as of late, posting here just in case it has to be fixed on this end.

**Comment by AlexModGuy** [comment]
fixed that
