### ISSUE TITLE
Blocks become non-interactive/ possible inventory error?

### ISSUE THREAD

**Issue by AyzelGray** [Alex-the-666/Ice_and_Fire#298]
It seems that after adding a few items to the inventory, blocks become unable to be interacted with.
 I can't get 2 minutes into the game without it being an issue, though I've tried several times.
This most recent time I made 12 planks, built a crafting table, and then couldn't click it. 
Chests won't open, destroyed blocks don't drop and can't be picked up. Can't attack dragons... It feels as if the character can't actually interact with the game, although you can still destroy building blocks.

Edit: I'm using the 1.11.2 Forge, 1.1.1 Ice and Fire mod, and Llibrary 1.11.2- 1.7.6.

**Comment by AlexModGuy** [comment]
already an issue see #287

**Comment by AyzelGray** [comment]
Thank you!
