### ISSUE TITLE
(1.16.3)(2.1.0) (suggestion) ice and fire materials use for beacon base

### ISSUE THREAD

**Issue by jhonnsbx** [Alex-the-666/Ice_and_Fire#2980]
would be nice to could make your own dragonsteel, amathiste, sapphire, silver or copper beacon, or even materials from rats mod (haha funny oratchalcum beacon)
:)

**Comment by Inpaladin** [comment]
https://github.com/Alex-the-666/Ice-and-Fire-Suggestions/issues
