### ISSUE TITLE
[1.16.3] #2.1.0 Dragons flying 5 Level break TPS ( Maybe 4 level too, did not met)

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#2982]
Dragons flying break TPS, server lag, i can't see TPS, but i think less than 1
I don't tnink this bug with 1,2,3,4. But dragon 5 lever always broke server TPS

**Comment by Daejangnamu** [comment]
Same problem.
only 5 stege dragon low TPS
version 1.16.3

**Comment by Melonendrache** [comment]
yeah i was trying to fight a stage 5 lightning dragon the lag was insane

**Comment by Daejangnamu** [comment]
![1](https://user-images.githubusercontent.com/52635462/96352909-429b1a80-1102-11eb-9e0b-9bf6b68ae422.png)
Ice dragon TPS 4
