### ISSUE TITLE
[1.16.3] Projectile weapon shoot in vertical direction

### ISSUE THREAD

**Issue by Vexhaust** [Alex-the-666/Ice_and_Fire#2985]
Projectile weapon like dragon bow and tide trident shoot their arrow to up and down

**Comment by Broccolon** [comment]
Yes, same here. Normal bows will work fine, but ice and fire projectiles seem to fail to shoot in the desired direction. Here is a video 
https://drive.google.com/file/d/1X2aRIOW-33TJ_0ieaGXAtf0-wMjkope3/view?usp=sharing

**Comment by xershel** [comment]
it's the same for me

**Comment by AkGamerRo** [comment]
I have a similar (if not the same) issue.
