### ISSUE TITLE
When I put manuscripts in a lecture, add something to the book, and take out just the book or just exit again, it keeps the same amount it had before

### ISSUE THREAD

**Issue by CommandBlockGuru** [Alex-the-666/Ice_and_Fire#2992]
Ok, so I was adding pages to my book when I noticed a glitch- whenever I added pages into the bestiary and left the lectern with the pages still in it, it would keep the pages in it but all the chapters I added stayed. It's weird and feels like cheating to me.

**Comment by ghost** [comment]
+, also have this bug

**Comment by DanDragonWolf** [comment]
I have this bug too. I also found out that if you add pages to your book and then click on the manuscript slot it will give you all of your manuscripts back. This makes the original glitch not occur, due to the Lectern not thinking that the manuscripts are inside it anymore.
