### ISSUE TITLE
1.16.3 Myrmex issues

### ISSUE THREAD

**Issue by goldfinder** [Alex-the-666/Ice_and_Fire#2993]
1. myrmex royals/queens are able to attack you even while neutral
2. Jungle Myrmex do not spawn normally.
3. Myrmex eggs hatch very very slowly, and also grow very very slowly.

**Comment by Robomnz** [comment]
oh and 4. when queen myrmex eggs hatch they crash the game as well.
[crash-2020-10-18_10.19.02-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5396688/crash-2020-10-18_10.19.02-client.txt)

also when using any myrmex spawn egg in any biome it always spawns desert ones, would be nice if they would also spawn jungle ones


@goldfinder for issue 3. try changing the times for myrmex hatching and gestation in config that should fix the hatching/growing times :)

**Comment by Mewkitty22** [comment]
@Robomnz 

Glad to see I'm not the only one having these problems. I've noticed that the spawn egg in the plains biome produces Jungle Myrmex.

**Comment by goldfinder** [comment]
> @Robomnz
> 
> Glad to see I'm not the only one having these problems. I've noticed that the spawn egg in the plains biome produces Jungle Myrmex.

1. myrmex royals/queens are able to attack you even while neutral
2. Jungle Myrmex do not spawn normally.
3. Myrmex eggs hatch very very slowly, and also grow very very slowly. (for issue 3. try changing the times for myrmex hatching and gestation in config that should fix the hatching/growing times 👍 )

4, queens hatching crashes the game
5. queens spawned in plains are immediately changed to jungle
