### ISSUE TITLE
[1.16.3] Dragon breath insanely lags the game

### ISSUE THREAD

**Issue by Paparogue** [Alex-the-666/Ice_and_Fire#3004]
Whenever a dragon breaths fire/ice the game lags insanely hard regardless if running local or on a dedicated server (1.16.3 latest)

Examples: https://i.gyazo.com/0e23051b846b599cf5198e2ae85fc374.mp4

Example2: https://i.gyazo.com/36ca1d1fbbdd187cd4565333b71e5cc8.mp4

**Comment by tronics-glitch** [comment]
I can confirm this, extreme incremental lag due to dragon breath and/or dragon pathfinding issues in 1.16.3.
Game is unplayable right now with Ice and Fire mod on.

**Comment by tronics-glitch** [comment]
22.10 01:06:17 [Server] INFO [m[33m[01:06:17] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 4086ms or 81 ticks behind
22.10 01:07:29 [Server] INFO [m[33m[01:07:29] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 5275ms or 105 ticks behind
22.10 01:07:49 [Server] INFO [m[33m[01:07:49] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 4784ms or 95 ticks behind
22.10 01:08:19 [Server] INFO [m[33m[01:08:19] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 9365ms or 187 ticks behind
22.10 01:08:52 [Server] INFO [m[33m[01:08:52] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 18140ms or 362 ticks behind

**Comment by tronics-glitch** [comment]
This ^ whenever a dragon becomes aware of my presence and starts engaging, either by moving closer to me or breathing on me.

**Comment by fzzyhmstrs** [comment]
I am also experiencing this. I had to cheat myself into creative mode to kill an ice dragon that was just wrecking havoc on the countryside and my TPS, leading me unable to actually deal with it.
