### ISSUE TITLE
Tide trident issue (1.16.3) 

### ISSUE THREAD

**Issue by Polomka** [Alex-the-666/Ice_and_Fire#3006]
Hi! Wherever I threw the trident, it flies up. Just up into the sky. The trident does not fly towards the player's gaze at all. Sometimes the trident flies in the wrong direction in which the player is looking. Should the trident look like an item in the inventory when the player is holding it, or should it be a 3d item like a vanilla trident?
![2020-10-18_16 42 01](https://user-images.githubusercontent.com/35797201/96369187-33978500-1161-11eb-97c0-b5c004c1806e.png)
![2020-10-18_16 42 10](https://user-images.githubusercontent.com/35797201/96369193-3befc000-1161-11eb-848a-2fc0c275c745.png)

**Comment by PumpKingMC** [comment]
Same
