### ISSUE TITLE
Ice and fire 1.16.3  do not spawn worms, sea snakes and dragon skeletons in 1.16.3

### ISSUE THREAD

**Issue by AsufreCoal** [Alex-the-666/Ice_and_Fire#3007]
no desove gusanos, serpientes marinas y esqueletos de dragón en 1.16.3

**Comment by Dwarfy-Dug** [comment]
same issue. Current 1.16.3 build and I have seen no serpents. deathworms etc.

**Comment by M3RGeo** [comment]
Same no death worms or sea serpernts are spawning in my worlds.

**Comment by AlexModGuy** [comment]
fixed in 2.1.2
