### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Sunconure11** [Alex-the-666/Ice_and_Fire#301]
https://pastebin.com/hSmJCUXg

**Comment by Sunconure11** [comment]
Error is being caused by Biomes O' Plenty.

**Comment by Necroverse** [comment]
Any idea for a fix for this without having to remove either of the mods? I'm having this same exact problem.

**Comment by Sunconure11** [comment]
This would have to be done on the ends of one of the mods, in the code.

**Comment by Vahras** [comment]
Also getting this crash. Hard conflict with Biomes O' Plenty.

**Comment by Necroverse** [comment]
Ok, shoot. Hopefully one of the mods comes up for a fix with this, I really like both mods a lot. Thanks for the response.

**Comment by Sunconure11** [comment]
Fixed in dev, by me.
