### ISSUE TITLE
Tried breeding dragons now anytime the chunk loads I get disconnected from server

### ISSUE THREAD

**Issue by The88KeysWalker** [Alex-the-666/Ice_and_Fire#3010]

**Comment by Inpaladin** [comment]
If you provide a minecraft/mod version it's much more likely to get fixed.

**Comment by Number1PiratePan** [comment]
Hi there, this is the guy who actually tried breeding the dragons lol.  The version we were playing on was 1.16.1 and ice and fire version (iceandfire-2.0.3-1.16.1.jar).  The moment they finished breeding I assume that the egg spawning with the nest the female creates bugged out or something while placing and now I had to abandon my base and restart elsewhere.  I breeded a Grey Male Stage 5 Fire Dragon and a Stage 4 Female Grey Fire dragon.
