### ISSUE TITLE
[1.16.3-Critical Issue] Ice and Fire make items not drop upon death.*

### ISSUE THREAD

**Issue by Gbergz** [Alex-the-666/Ice_and_Fire#3019]
**What happens:**
I believe this is a critical issue. Anyways, when you die, the items doesn't drop on the ground at all, and sometimes death messages in chat won't even appear. And if you have a gravestone mod installed (any) it won't spawnt the grave either.

**Minecraft:** 1.16.3
**Forge:** 34.1.21
**Ice and Fire:** 2.1.0
**Citadel:** 1.4.1

**Logs when dying:**
https://hastebin.com/gisejiyobu.sql

**Another death logs:**
https://hatebin.com/gzhjhgvnlw

**Screenshots GIF**
https://gyazo.com/324e07af1ed7313251cfcebe386c63c9

**Additional Information:**
Note that all of this is reproducable in a clean instance with only ice and fire. And is really an issue in my modpack. Players dying and receiving no graves etc. I think this started happening when the graveyard update for ice and fire was released.

**Edit:** 
I've heavily edited this post with new information i've gathered.

**Comment by Neko2n** [comment]
I'm playing with Gravestone and have not had this issue so far, are you 100% sure it's ice and fire causing this?

**Comment by Gbergz** [comment]
> I'm playing with Gravestone and have not had this issue so far, are you 100% sure it's ice and fire causing this?

It's happening without the Gravestone mod. Clean instance with only Ice and Fire + Citadel, Forge 34.1.21
So yes, i'm sure. 
Using this version: https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons/files/3077981

Edit: It's random, sometimes it doesn't happen and sometimes it does. Here's another log | https://hatebin.com/gzhjhgvnlw |, where it happened when killing a player with a normal Diamond Sword.

**Comment by Sabizos** [comment]
im having this issue too! bnut only in the nether..

**Comment by Gbergz** [comment]
Feel the need to bring this up again, any update on this and if it will be fixed? Really annoying bug.

**Comment by Gbergz** [comment]
Seems to still be happening with the latest release "[2.1.1](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons/files/3100004)"

One of my players playing TNP Limitless 3 just died and no gravestone or items were dropped at his death. Looks like it doesn't happen that often anymore though, only rarely. This time no error showed up in console either.
