### ISSUE TITLE
[1.16.3] Server crashes (player times out) in a certain area with biomesoplenty world type

### ISSUE THREAD

**Issue by DanielPikaman** [Alex-the-666/Ice_and_Fire#3027]
Upon entering a certain area on a seed I was using, my server would time me out. The server didn't technically crash, and thus did not create a crash report, but I would time out and would not be able to join the server again. When this happens, the server memory usage spikes and stays at a constant high amount.

Forge version used: 1.16.3-34.1.19
Seed: 2525188381704207701
Rough co-ordinates of area that causes time out: 6, 70, -690 (elevation doesn't matter)
Level-type: biomesoplenty
Mods installed: iceandfire-2.1.0-1.16.3, citadel-1.4.0, BiomesOPlenty-1.16.3-12.0.0.408-universal

I have included the debug log of the server.

[debug.log](https://github.com/Alex-the-666/Ice_and_Fire/files/5414573/debug.log)

I have also included an image of the server's memory usage, in which I have drawn a red line to show the point at which my game timed out.

![memoryuse](https://user-images.githubusercontent.com/73149978/96697693-0d304000-1341-11eb-91bc-7a2bf3c4c4e3.PNG)

**Comment by Dinusaur01** [comment]
I am also having this problem. Although it seems I only run into the error in the Ice and Fire glacier biome/ BoP snow biomes. 

This error is also present in the 1.16.1 2.0.3 version of Ice and Fire.

**Comment by DanielPikaman** [comment]
The area that causes it for me is also a snow biome.
