### ISSUE TITLE
Swimming Ice Dragons

### ISSUE THREAD

**Issue by Frosty8-0** [Alex-the-666/Ice_and_Fire#303]
In the bestiary, it says Ice Dragons can swim.  Well, in the actual gameplay, they can't.  They just walk around really slowly.  Please add a swimming feature to Ice Dragons.  It would be awesome.

**Comment by TheLastCookie11** [comment]
ye

**Comment by Frosty8-0** [comment]
Oops this belongs in suggestions
Sorry

**Comment by AlexModGuy** [comment]
no it is a bug. They were able to swim before 1.2.0.

**Comment by Frosty8-0** [comment]
Oh, really?

**Comment by Frosty8-0** [comment]
Ok

**Comment by Frosty8-0** [comment]
I'm glad I could help.
