### ISSUE TITLE
[1.16.3] 2.1.0 ICE dragon broke TPS

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#3031]
Ice dragon broke my TPS
<a href="https://ibb.co/6X9vc19"><img src="https://i.ibb.co/hYQXxZQ/2020-10-23-01-31-56.png" alt="2020-10-23-01-31-56" border="0"></a>

**Comment by M3RGeo** [comment]
I can confirm this as when i have played on the 1.16.3 2.1.0 update when fighting a ice dragon, it would cause my tps to drop and the ai as well as the visuals of the dragon would freeze in a flying attack stance, i would be unable to do any damage while it is in this state.

**Comment by tronics-glitch** [comment]
This is the same issue I posted about on this other bug: https://github.com/Alex-the-666/Ice_and_Fire/issues/3004

**Comment by tronics-glitch** [comment]
Would be nice if someone could confirm it happens only for ICE dragons, that way I could disable ice dragons via settings (I presume) and continue playing the game.

**Comment by tronics-glitch** [comment]
Seems to happen only with Ice dragons and always nearby some body of water, but I could be wrong.
