### ISSUE TITLE
Duplication bug with the manuscripts in the Bestiary Lectern

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#3034]
With fil iceandfire-2.1.0-1.16.3.jar
After choosing our subject to be added to the Bestiary, the manuscripts disappear. We leave the Bestiary lectern and when we return to the Bestiary Lectern interface, manuscrits reappear.
[https://imgur.com/a/PXwLtPG](url)

**Comment by J3RN** [comment]
This appears to be the same as #2933. Would you mind closing this issue and commenting there so that we can keep the conversation all in one place?
