### ISSUE TITLE
[1.16.3] Generation of dragon Roosts not working as intended?

### ISSUE THREAD

**Issue by Shandoo94** [Alex-the-666/Ice_and_Fire#3044]
Forge 34.1.25
Ice and Fire 2.1.0

I have noticed this since 1.12, but no matter what number i try in the config file, dragon roosts alway spawn in clusters with 4-5 roosts in close proximity to each other. 
The option for the distane between dangerous spawns does not change anything.

Here a screenshot with a spawn chance of the default 360 with the distance set to 300. There is a forth rootst behind me.
![2020-10-25_09 58 48](https://user-images.githubusercontent.com/21018028/97102992-4272c000-16aa-11eb-9137-279b3cf36cfc.png)

**Comment by Dwarfy-Dug** [comment]
I am also finding roosts in clusters .....and lowering the chance of roosts just means you are less likely to get a roost cluster in a chunk. 

Note for the OP though..... the 'distance from spawn' is how far away from the initial character spawn in the world things will spawn. So, at 1000 .... when you start the game, nothing dangerous will spawn within 1000 blocks radius of the spawn point.  Once you move away from spawn, the frequency of roosts is based on the chance in 10,000 of one spawning in a chunk. I am pretty sure the 'cluster' effect is not intended.

**Comment by kuroyure** [comment]
configs in general are not working, this is a known issue, but there arent gonna be updates for a while afaik

**Comment by Shandoo94** [comment]
> 
> 
> I am also finding roosts in clusters .....and lowering the chance of roosts just means you are less likely to get a roost cluster in a chunk.
> 
> Note for the OP though..... the 'distance from spawn' is how far away from the initial character spawn in the world things will spawn. So, at 1000 .... when you start the game, nothing dangerous will spawn within 1000 blocks radius of the spawn point. Once you move away from spawn, the frequency of roosts is based on the chance in 10,000 of one spawning in a chunk. I am pretty sure the 'cluster' effect is not intended.

I am not talking about the distance from spawn, but this option:

#How far away dangerous structures(dragon roosts, cyclops caves, etc.) must be from the last generated structure.
	#Range: 1 ~ 10000
	"Dangerous World Gen Dist Seperation" = 400
