### ISSUE TITLE
The trolls don't spawn 1.15.2 I/F (2.1.0)

### ISSUE THREAD

**Issue by Phantom2909** [Alex-the-666/Ice_and_Fire#3053]
Well trolls don't spawn normally, they are the only creatures in the mod that don't spawn normally (except that I summon them through the spawn egg).

**Comment by NathanNevesPrates** [comment]
My client side console output shoves betwen 3 - 5 Troll Spawn checks betwen Y=21 and Y=31 at trollCanSpawn and all of them respond with "false".
