### ISSUE TITLE
[2.0.3-1.15.2] Bestiary Lecturn Bug

### ISSUE THREAD

**Issue by lede701** [Alex-the-666/Ice_and_Fire#3054]
Found a bug in the lectern that allows you to fill the book without finding tons of manuscripts.  For me I had found 10 scripts and put my book in the lectern and added a couple of sections.  Took the book our of the lectern but left one manuscript in the lectern.  Next time I open the Lectern it show 10 manuscripts.  So I kept doing these same steps and was able to fill the bestiary with all topics with only finding 10 manuscripts.

**Comment by Dwarfy-Dug** [comment]
THis also happens in 1.16.3...

**Comment by J3RN** [comment]
This appears to be the same as #2933. Would you mind closing this issue and commenting there so that we can keep the conversation all in one place?
