### ISSUE TITLE
Lightning from lightning dragonsteel tools destroying items

### ISSUE THREAD

**Issue by DarkXenith** [Alex-the-666/Ice_and_Fire#3055]
The sword 1 hits a lot of mobs and since the lightning strike tends to happen after they die the items get destroyed. I really like the way the lightning dragonsteel weapons and dragons look I was thinking maybe make it so that the lightning only spawns if they're still alive if there's a check for that, or maybe do a custom lightning thing. Though I understand that may be difficult.

**Comment by Inpaladin** [comment]
I feel like this'd probably be more suggestion material since it's _technically_ working as intended, although I totally agree this should be changed.  Here's the suggestions page https://github.com/Alex-the-666/Ice-and-Fire-Suggestions/issues.
