### ISSUE TITLE
Rats Recipe is looking for a Item that you guys dont have yet?(Look at Letter C)

### ISSUE THREAD

**Issue by BedrockLegends** [Alex-the-666/Ice_and_Fire#3058]
{
  "conditions": [
    {
      "type": "forge:mod_loaded",
      "modid": "iceandfire"
    }
  ],
  "type": "minecraft:crafting_shaped",
  "pattern": [
    "CAC",
    "DFD",
    "CWC"
  ],
  "key": {
    "D": {
      "item": "rats:dragon_wing",
      "data": 0
    },
    "C": {
      "tag": "iceandfire:dragon_scales_block"
    },
    "W": {
      "item": "rats:rat_upgrade_warrior",
      "data": 0
    },
    "A": {
      "item": "rats:rat_upgrade_asbestos",
      "data": 0
    },
    "F": {
      "item": "rats:rat_upgrade_flight",
      "data": 0
    }
  },
  "result": {
    "item": "rats:rat_upgrade_dragon"
  }
}

If this should be posted under rats, just let me know

**Comment by Inpaladin** [comment]
I was wondering why that version of the recipe was missing in newer versions, ended up adding it myself with crafttweaker.  Dragon scale blocks definitely exist, it just looks like Alex didn't implement a tag for all dragon scale block types.  Currently the dragon scale blocks only use tags that correspond to their types, those being forge:storage_blocks/fire_dragon_scale, forge:storage_blocks/ice_dragon_scale, and forge:storage_blocks/lightning_dragon_scale.  

Actually now that I look at this I wonder why it's written like that as I don't think ice and fire has any tags that don't use "forge" as their source, made by forge or not.  Tbh I'm not super experienced in actually writing mods so maybe it works differently than I understand, I've never done anything with tags outside of crafttweaker.

I have no idea how to actually compile mods properly so if you do you can try changing it to forge:storage_blocks/fire_dragon_scale or something and see if that fixes it and make a pull request.
![image](https://user-images.githubusercontent.com/59532097/97261899-0db35580-17dd-11eb-9c1c-d2c5514e29d9.png)
