### ISSUE TITLE
Dragon caves empty 1.12.2

### ISSUE THREAD

**Issue by vixenthief** [Alex-the-666/Ice_and_Fire#3068]
I checked for caves in spectator mode and found I was right on top of one. So a went down to see the dragon. There was no dragon. Went into creative and survival, no dragon. Same happened for the next ones a checked for in spectator.

**Comment by umbecanessa** [comment]
Same for me - 1.12.2 - I’ve checked now more than 8 dragon caves but no dragon inside. I found the chests all of them with items and a lot of mobs, but no dragon - Ice and Fire V1.9.1 on a Sponge Server
