### ISSUE TITLE
Dragon mounting teleport glitch w/ Multiplayer

### ISSUE THREAD

**Issue by baileyblackmon** [Alex-the-666/Ice_and_Fire#3069]
Me and my friend are playing on his server with this mod (among others) and we just got a couple dragons to stage 3. Whenever one of us mounts our dragon, the other player is teleported to the person who mounted.
If one of us is mounted and the other then mounts, original mounted person get kicked off their dragon and teleported a certain distance away or is simply dismounted. Additionally, when a person gets teleported they are not on their dragon on their own screen, but on the other person's screen they appear to still be mounted. Seemed like when my friend went really far away and mounted it didn't affect me but that's not really a feasible fix. Appreciate any help!

**Comment by singulantlive** [comment]
Yes, this is an issue I've run into

**Comment by DrBlocks** [comment]
Experiencing the very same bug on our server. Sometimes players are teleported to the person who mounted, sometimes right under their own dragons who follows their cam movements, sometimes their dragon just flies away full steam in a straight line.

Server sends back 2 errors each time someone mounts :

```
[Netty Epoll Server IO #2/ERROR] [net.minecraft.command.arguments.ArgumentTypes/]: Could not serialize net.minecraftforge.server.command.ModIdArgument@67b6b076 (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!
[Netty Epoll Server IO #2/ERROR] [net.minecraft.command.arguments.ArgumentTypes/]: Could not serialize net.minecraftforge.server.command.EnumArgument@7896ab93 (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!
```
(the series of numbers after the @ changes with each try)

We tried with Forge 34.1.0 (current version we're playing on), 34.0.21, 34.0.9 and 34.0.0, which is the earliest available version for MC 1.16.3, and still get the very same issue.

Logging out and back in temporarily fixes the issue for players experiencing it - that's everyone who was mounted minus the last player who mounted - until someone mounts a dragon again (that's what we use as a workaround for now), does it work the same way for you @singulantlive and @baileyblackmon ?

**Current server configuration :** 
- citadel-1.4.1
- iceandfire-2.1.0-1.16.3
- running forge 34.1.0

**Comment by baileyblackmon** [comment]
> Logging out and back in temporarily fixes the issue for players experiencing it - that's everyone who was mounted minus the last player who mounted - until someone mounts a dragon again (that's what we use as a workaround for now), does it work the same way for you @singulantlive and @baileyblackmon ?
> 
> **Current server configuration :**
> 
> * citadel-1.4.1
> * iceandfire-2.1.0-1.16.3
> * running forge 34.1.0

Yep same way for us

**Comment by singulantlive** [comment]
@DrBlocks line for line the same thing.

**Comment by DrBlocks** [comment]
Follow-up : bug still persists with Version 2.1.1 for 1.16.3.

Server config : 

- citadel-1.4.1
- iceandfire-2.1.1-1.16.3
- running forge 34.1.0

**Comment by drawson** [comment]
This bug still exists for us when we use OpenToLAN and connect in another player locally.

- Forge 1.16.4-35.1.4
- citadel 1.5.3
- iceandfire 2.1.4-1.16.4
- HWLYA-forge 1.10.11-B78

**Comment by singulantlive** [comment]
Damn well im sorry guys. Maybe we will get a work around at some point

**Comment by terrytzh** [comment]
Same here.

- Forge 1.16.4 - 35.1.36
- citadel 1.5.3
- iceandfire 2.1.5-1.16.4
- and around 50+ other mods

I don't think ice and fire conflicts with other mods in case of this issue tho.
