### ISSUE TITLE
Mowzies Mobs make stone mobs move

### ISSUE THREAD

**Issue by TheLastCookie44** [Alex-the-666/Ice_and_Fire#307]
I stoned mobs with the gorgons head and they are still moving and attacking me. In the gorgon temple i found stoned mobs but theyre moved and attacked me too

**Comment by AlexModGuy** [comment]
sceenshots please

**Comment by Frosty8-0** [comment]
Whenever I stone something, it moves for like a second afterwards and then it stops and is completely petrified.

**Comment by TheLastCookie11** [comment]
![2017-09-11_12 32 32](https://user-images.githubusercontent.com/29627586/30270713-dd46be8c-96ed-11e7-8db0-b23d758e1950.png)

**Comment by TheLastCookie11** [comment]
theyre attacking

**Comment by TheLastCookie44** [comment]
the problem is coming from the mowzies mobs mod (1.11.2) its a new bug

**Comment by Sunconure11** [comment]
A user on the discord channel recorded this issue.

https://www.youtube.com/watch?v=uaED4WxAsdE&feature=youtu.be

https://www.youtube.com/watch?v=T6QUPqPx7yg&feature=youtu.be

**Comment by BlueWither** [comment]
This issue happens because Mowzie's Mobs removes NoAI.
https://github.com/BobMowzie/MowziesMobs/issues/63

**Comment by AlexModGuy** [comment]
fixed in latest mowzie's update
