### ISSUE TITLE
Mod crashes on New Minecraft 1.16.3 forge

### ISSUE THREAD

**Issue by BedrockLegends** [Alex-the-666/Ice_and_Fire#3070]
![2020-10-29_00 13 59_5](https://user-images.githubusercontent.com/48525410/97528389-a7186e00-197b-11eb-9894-9acb564ff59f.png)

**Comment by FeBreezy18** [comment]
This is indeed a widespread problem. Server crashes when trying to load Ice and Fire on the new 1.16.3 forge. We will need to wait for a hotfix. Just use a forge version that works for now. I'm using Forge 1.16.3-34.1.0.

**Comment by Danickar** [comment]
Forge 1.16.3-34.1.24 is the highest I have tried that still works.

**Comment by Meskino** [comment]
still crashing on 34.1.35 :(

**Comment by Sunekaer** [comment]
https://pst.ksun.io/igofuvumud.rb
