### ISSUE TITLE
Dragons and Hippogryphs Head Snap

### ISSUE THREAD

**Issue by TracedK** [Alex-the-666/Ice_and_Fire#3075]
When you ride them both, sooner or later their head snaps to their back and returns

**Comment by DenilsonNM** [comment]
same, when I ride, their heads move super weird, turning 360 degrees even. 
this is in 1.16.4 mod version: iceandfire-2.1.4-1.16.4

**Comment by brisingraerowing** [comment]
I have the same issue. 1.16.4-2.1.4 as well. Hippogryphs are also crazy fast on the ground (at least the one I tamed is). It looks a bit weird.
