### ISSUE TITLE
Failed to load 1.16.3

### ISSUE THREAD

**Issue by serofabrication** [Alex-the-666/Ice_and_Fire#3086]

**Comment by serofabrication** [comment]
Tried adding this mod with the updated citadel dependency. now i keep getting an 
Ice and Fire  has failed to load correctly
java.lang.ExceptionInInitializerError: Null
Attached is the crash log.
[crash-2020-10-31_16.42.34-fml.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5469787/crash-2020-10-31_16.42.34-fml.txt)

**Comment by vampiregirl23** [comment]
im having the same issue..use forge 1.16.3.34.1.0 it seems it doesn't like the newest forge...

**Comment by serofabrication** [comment]
I saw where others were having success with the forge 34.1.0 and tried it with that version but I still got the same error.

**Comment by GrayShark18** [comment]
i have the same problem, i use forge 1.16.3.34.1.0 and 1.16.3.34.1.33, always the same error :/

**Comment by DrBlocks** [comment]
@serofabrication I see on your attached crash log that you're using a bunch of other mods; have you tried to launch with Citadel and Ice&Fire only ?

**Comment by GrayShark18** [comment]
@DrBlocks i tried that, but even if you put chust the citadel and the iceandfire mod doesnt work :/

**Comment by BinaryVigilante** [comment]
I report the same error.

`java.lang.ExceptionInInitializerError: null`

I have tried running only Ice and Fire and Citadel but the issue still happens.

I use:
Minecraft 1.16.3
Forge 34.1.35
Ice and fire 2.1.0
Citadel 1.4.1

Crash Report: https://paste.ubuntu.com/p/FtygjfNJ67/

**Comment by MK105Cruiser** [comment]
Has there been any resolution to this? I have the same issue with this sensational mod. My kids love Ice and fire, so please help me out with a fix as they are driving me nuts. 
[021120debug.log](https://github.com/Alex-the-666/Ice_and_Fire/files/5473731/021120debug.log)

**Comment by Paparogue** [comment]
Use forge 34.1.23

**Comment by BinaryVigilante** [comment]
> 
> 
> Use forge 34.1.23

Can confirm that this works!

**Comment by BinaryVigilante** [comment]
> 
> 
> > Use forge 34.1.23
> 
> Can confirm that this works!

Can also confirm that forge version 34.1.25 and 34.1.24 also works.

**Comment by Alucabr** [comment]
I have the same problem, the game crash on the screen to load the modpack, this business of having to play only with ice and fire does not roll, we do have to give log feedback along with other mods, because nobody plays with only 1 mod .

**Comment by BinaryVigilante** [comment]
> 
> 
> I have the same problem, the game crash on the screen to load the modpack, this business of having to play only with ice and fire does not roll, we do have to give log feedback along with other mods, because nobody plays with only 1 mod .

The issue is that it only works with an older version of forge. though I saw the changelog for Ice and Fire version 2.1.1 and the issue might have been fixed, haven't had a chance to test it yet.

It doesn't have anything to do with other mods, only the forge version.

**Comment by Fnetra** [comment]
> > > Use forge 34.1.23
> > 
> > 
> > Can confirm that this works!
> 
> Can also confirm that forge version 34.1.25 and 34.

I've just tried all of them with the latest ice&fire and citadel still says null.
