### ISSUE TITLE
The mod is unusable in Minecraft 1.16.3. 

### ISSUE THREAD

**Issue by dabulue** [Alex-the-666/Ice_and_Fire#3087]
It gives this error:
java.lang.ExceptionInInitializerError: Null

There is no version of this mod that works in with the newer versions of Forge 1.16.3, even it says it is for version 1.16.3 in the CurseForge website...

**Comment by JosephGallagher2001** [comment]
I'm experiencing this as well... very strange that this is happening.
[crash-2020-11-01_14.12.12-fml.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5471586/crash-2020-11-01_14.12.12-fml.txt)
here's my crash report if you need it.

**Comment by Aracardia** [comment]
I am also having this exact problem. I even downloaded the older 1.16.3 version availble and it didn't work.

**Comment by JosephGallagher2001** [comment]
the mod worked with 1.16.3 for a while though, right?

**Comment by ALEXI5117** [comment]
> Sin embargo, el mod funcionó con 1.16.3 por un tiempo, ¿verdad?

De hecho asi fue amigo... igual me funcionaba el Mod pero ahora no se por que ya no me funciona.... instale otros mods ya que el juego me iba algo lento... y entre esos mods, vi que Forge contaba con una versión nueva (La **_Forge-1.16.3-34.1.39_** para ser precisos)  y sin embargo yo contaba con esta y funcionaba **_"forge-1.16.3-34.1.0"_**

**Comment by JosephGallagher2001** [comment]
ah, yes

**Comment by dabulue** [comment]
It's sad that such a contentful and well-made mod can't be used..

**Comment by Carro1001** [comment]
Try using forge 34.1.25, seems to be the latest version that works, and if some mods recommend higher versions, try downgrading them a bit

**Comment by livipup** [comment]
Unfortunately there are other mods which require newer versions of Forge. Rolling back to an older version is likely to cause issues for many people. I can't imagine the changes in such a minor revision are enough to make it difficult to update, so that is likely the best course of action. For the mod author to update it to the latest version.

**Comment by AlexModGuy** [comment]
fixed in 2.1.1
