### ISSUE TITLE
Ice and Fire 1.16.3 .... Map corrupted/fails to load after Ice Dragon cave entered. 

### ISSUE THREAD

**Issue by Dwarfy-Dug** [Alex-the-666/Ice_and_Fire#3088]
Initial gameplay in Plains biome was fine. Dragon caves all fine and no issues. Went in search of an Ice Dragon, and headed to a snowy biome. Dug down to first cave, and found a male. When I returned to the surface.....the map stopped loading chunks as I moved away. 
Tried again...found a female....and that was OK. Next was male...and the game failed to load map chunks again and I had to terminate the game through Task Manager. In each case, map would not load afterwards
No crash log generated. 
Had some other mods loaded...so removed them.....loaded a backup copy of the map....and repeqated steps with same results. 
Seems to trigger when I load a male Ice Dragon in a cave.

**Comment by Dwarfy-Dug** [comment]
Still have this issue with the latest build, 2.11.1 1.16.3 .... not sure if this means I have to start a fresh game, or if the map can be saved.   This is an example of what happens after a while in the snow biome. Doesn;t seem to happen in other biomes. 

https://i.imgur.com/GA2rKlB.jpg

The map has simply stopped loading ( shows in the minimap display too) and the world stops loading in. At this point it is impossible to close hte game normally or save the map. I have to terminate the game through Task Manager.

**Comment by Daejangnamu** [comment]
Same problem. Server freezes(Time out) in biome snow area.

**Comment by Dwarfy-Dug** [comment]
Did some more tesing after seeing another similar bug report. Lock up is linked directly to Ice Dragon waking up. opened fresh map in creative...went to ice biome. Dug to dragon cave....hit dragon once...dragon stood up and game broke. Everything apart from player stopped. Went back to surface and sawe a Hippogryph flapping wings but not moving...map not loading....game unresponsive and unable to intereact with anything in the world. Game locked solid on exit and had to be terminated in Task Manager...exactly what I had before. No doubt though...it was when the dragon in the cave stood up. Does not do this with fire dragons or Lightning dragons. Both of those get up...roar...and start moving about. Ice Dragon...no roar, no move...game breakage
