### ISSUE TITLE
Lectern bug: infinite manuscripts

### ISSUE THREAD

**Issue by Thelonelyroamer** [Alex-the-666/Ice_and_Fire#3089]
I'm not sure if this is a known issue already but when I filled my bestiary with a new entry I stumbled across this bug in the newest version of the mod.
I put the bestiary and 4 manuscripts onto the lectern and got a new entry for 3 manuscripts. Then I exited the lectern without taking the one remaining manuscript and the bestiary back into my inventory. When I checked the lectern again there were 4 manuscripts on it again instead of one. The number of manuscripts also automatically jumps back to 4 when I try to put the remaining one back into my inventory after getting an entry. 
This duplication bug happened every time I tried it.

**Comment by SoulRacer65** [comment]
Yeah same thing happened to me while playing on a survival world.

**Comment by J3RN** [comment]
This appears to be the same as #2933. Would you mind closing this issue and commenting there so that we can keep the conversation all in one place?
