### ISSUE TITLE
dragon still spawn after i put it in a dragon horn

### ISSUE THREAD

**Issue by silentsword06** [Alex-the-666/Ice_and_Fire#309]
I start yesterday a world where I have four ice dragon,one of them is in stage five,so I put it in dragon horn,but today when i enter in the world the dragon was still here,and when I put it in a dragon horn and walk away,and then go to the place where I put it in a horn,the dragon was still there,like if I did'nt put it in a dragon horn

**Comment by AlexModGuy** [comment]
dupe of dupe issue
