### ISSUE TITLE
trident and dragon bow animation

### ISSUE THREAD

**Issue by kobiYeet** [Alex-the-666/Ice_and_Fire#3091]
trident pointing only upwords:
![Uploading 2020-11-03_00.08.01.png…]()

arrow not showing when charging dragon bone bow:
![Uploading 2020-11-03_00.08.16.png…]()

**Comment by BugmanBugman** [comment]
What version of i/f?

**Comment by kobiYeet** [comment]
2.1.1

**Comment by AsianDropOut** [comment]
> trident pointing only upwords:
> 
> 
> arrow not showing when charging dragon bone bow:

So they fixed the bow and trident going in different directions then it supposed to shoot but the arrow not showing up for the bow still isn't working. Also the update is still compatible with 1.16.3 but not sure about citadel that supports this mod
