### ISSUE TITLE
Waking up a stage 4-5 ice dragon ice dragon completly stops my game

### ISSUE THREAD

**Issue by Azer0o0** [Alex-the-666/Ice_and_Fire#3097]
So ive been playing on my world for a while and had a bit of this problem with all types of dragons but not this severe, waking up an underground ice dragons completly freezes time ingame and i can't shoot arrows and blocks don't drop items. when i teleported home during a pause in the lag it went to normal but it kinda sucks that i cant even come close to the snowy biomes now. idk if my pc just can't keep up or smth

**Comment by Dwarfy-Dug** [comment]
have had major issues in snow biome myself. Game locking up and terrain chunks not loading.

**Comment by Dwarfy-Dug** [comment]
update...tested to see if this is what was causing my issue...anbd it 100% is!
Created fresh map....went to snow biome in creative mode....went in to Ice Dragon cave...hit dragon with hand....and after one hit, the dragon got up from it's sleeping pose, and I could no longer hit it. Hit box unresponsive. Went back up to surface, and saw Hippogryph flapping wings and not moving...and map chunks were not loading etc. 1.16.3, 2.1.1 patch

**Comment by kuroyure** [comment]
i think i may have the same issue but without the waking the dragon up part

**Comment by Dwarfy-Dug** [comment]
I suspect it's related to something the dragon does...roar or some particular animation. If the dragon is in range to detect and respond to you that would trigger the response in the same way hitting it did.

**Comment by TheWitherlord** [comment]
Hey guys having the same problem here, but you three are looking into it wrong, its the troll trying to find a spawn location and failing. https://gist.github.com/TheWitherlord/ff5de29ed4c5c9f05e639af4bc4e12c1

**Comment by Dwarfy-Dug** [comment]
Not trolls for me. Turned off troll spawning completely....and it still happens. 
Also....not directly linked to waking up a dragon, as I woke one up and it stood up, roared and all was fine. Went to the next cave, went down into it and the dragon was stood there. Couldn;t interact with it....no collision etc. Back to the surface and the game is dead with chunks not loading etc. 

Conclusion ..... It's something in the cold biomes. Either Snowy tundra...or Snowy mountains. Other things of note when the game broke was a Mausoleum nearby so I turned them off...still got the issue. Same seed...same place...go to dragon one...OK...go to dragon 2...can't touch it...and hte game is broken.

**Comment by TheWitherlord** [comment]
I understand now
