### ISSUE TITLE
MC launch crash with version 1.2.0

### ISSUE THREAD

**Issue by HardTy** [Alex-the-666/Ice_and_Fire#310]
I update the mod to version 1.2.0 and the game crashed at the launch.
Here is the crash report:
[crash-2017-09-10_18.15.58-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/1290696/crash-2017-09-10_18.15.58-client.txt)

**Comment by kopinzky** [comment]
I had this crash too.
Try to delete Biomes O'Plenty from your mod-folder.
That helped me.

**Comment by AlexModGuy** [comment]
conflict with BoP will be fixed in 1.2.1

**Comment by HardTy** [comment]
Works! THX
