### ISSUE TITLE
[1.16.3-2.1.1] Ghosts take damage

### ISSUE THREAD

**Issue by BlueEyesEthan** [Alex-the-666/Ice_and_Fire#3101]
So, as I was reading through the Ice and Fire fandom, I went onto the page of ghosts, and I scrolled down and saw that it could only be harmed with silver and phantasmal weapons, quote on quote "they are immune to most forms of damage, and only silver weapons and the Phantasmal Blade can deal damage to them.", along with them not taking damage in sunlight, "When exposed to broad daylight, ghosts will enter a dormant state; upon doing so, they will stop glowing and slowly fade into invisibility, and they become immune to all forms of damage". But during my gameplay as I was testing ghosts out and I spawned them in, and I attacked there were 2 things I noticed.

1: I spawned them in in daytime and they flew around but I noticed my cursor was aiming at something and I attacked, I could still harm the ghosts even during when they're invisible

2: They were taking damage from iron, diamond, and gold weapons, not just the ones that were listed.

This wasn't just because I was in creative mode, I went into a survival world and spawned in a swamp near a graveyard, and when I went over there I could attack with a stone axe and sword.

**Comment by AsianDropOut** [comment]
That's true. Read through the fandom too and just noticed it with my gameplay of 1.16.3. Hope this issue is fixed soon.
