### ISSUE TITLE
Issue with tamed dragons when you mount them

### ISSUE THREAD

**Issue by Jim-WM** [Alex-the-666/Ice_and_Fire#3106]
Been playing this mod for a while with my friend, the issue we are having is that we both have tamed dragons but lets say one of us mounts their dragon and is on the dragon flying or staying still it doesnt matter as soon as the other player mounts their dragon it kicks the other player that is already mounted out of his/her dragon and teleports them to you as if the game thinks they are the ones mounting the second dragon but the game acts as if the player who was kicked out of their mount is still on it, then some weird stuff can happen such as if the player who got kicked out of their mount because the second player mounted their dragon if they then press CTRL to dismount their dragon they teleport back to it but then if they mount it again it will once again kick the second player off their dragon. Its a weird cycle that happens so for the time being we will just not try to mount anything until we find a way to fix this. Any help will be greatly appreciated!
List of the mods we are using in our server (1.16.3) in case it helps:
BiomesOPlenty
citadel
clumps
cookingforblockheads
curios forge
cyclic
elevatorid
environmentalcreepers
fastfurnace
fastleafdecay
furniture
gravestone
**iceandfire**
inventorysorter
jei
justenoughresources
mcw bridges
mcw doors
mcw windows
mekanism
mekanismadditions
mekanismgenerators
mekanismtools
placebo
refinedstorage
refinedstorageaddons
reliquary
storagedrawers
uteamcore
useful backpacks
waystones
xaeros minimap
xaeros worldmap

**Comment by MXall0c** [comment]
Having the same issue, no other mods installed though.

Using minecraft 1.14.4
