### ISSUE TITLE
tamed dragon vanishing

### ISSUE THREAD

**Issue by ragnarf666** [Alex-the-666/Ice_and_Fire#3109]
i have a bound summoning crystal. i set my dragon to escort and it shows on my mini map that it is above me but its not there. the summoning crystal also will not summon it. reloading does nothing. is there simply no way to retrieve my dragon. if so that is very disappointing and this mod will be getting removed from my pack. players put too much time into finding them only to have them disappear.

**Comment by TheTaterLord** [comment]
as the bound summoning crystal isnt from ice and fire id dare say thats your issue theres a dragon horn for a reason

**Comment by ragnarf666** [comment]
the summoning crystals are part of ice and fire tho and the horn does
nothing.

**Comment by ragnarf666** [comment]
![Runtime Screenshot 2020 11 07 - 12 50 49 47](https://user-images.githubusercontent.com/74045322/98451196-65649180-20f8-11eb-9e3e-cf19c5fbbd9e.png)
