### ISSUE TITLE
WAILA Registers Pixie Hovels as the same thing

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#311]
![screenshot 551](https://user-images.githubusercontent.com/23727270/30251674-96ca8044-9632-11e7-813e-2cfe31769522.png)
![screenshot 552](https://user-images.githubusercontent.com/23727270/30251675-985a03b2-9632-11e7-979d-49ad6218f27b.png)
![screenshot 553](https://user-images.githubusercontent.com/23727270/30251676-9a490d44-9632-11e7-822c-14a0c3b02aba.png)

**Comment by EnderiumSmith** [comment]
WAILA does that with most modded blocks. it ignores metadata for some reason. try the one probe instead.

**Comment by darthvader45** [comment]
Yeah, sometimes certain vanilla and modded blocks end up labeled as air.  Mostly flowers and that sort of thing, along with doors.

**Comment by AlexModGuy** [comment]
should be fixed if latest llib is used
