### ISSUE TITLE
Mobs and structures not spawning 

### ISSUE THREAD

**Issue by redeyedkaneki** [Alex-the-666/Ice_and_Fire#3110]
I've tried several different versions of ice and fire with their respective versions of forge and citadel at no point have i been able to get structures or any mobs to spawn in game. The ONLY thing that does spawn is the graveyard with the ghost mob. I've followed tutorials on how to install the mod and im completely at a loss.

**Comment by Aracardia** [comment]
I am also having this problem. In creative you can spawn it all but it doesn't show in survivial.

**Comment by redeyedkaneki** [comment]
> I am also having this problem. In creative you can spawn it all but it doesn't show in survivial.

i actually didnt even try that but seriously so irritating

**Comment by Aracardia** [comment]
> > I am also having this problem. In creative you can spawn it all but it doesn't show in survivial.
> 
> i actually didnt even try that but seriously so irritating

yeah it is. i really wanted to play amodded 1.16 with this

**Comment by superdude808** [comment]
same problem too this is weird i just want to have a dragon farm man

**Comment by Treep3r** [comment]
Having the same problem on our server running All The Mods 6. No Ice and Fire structures or spawns in any dimension.

**Comment by AlexModGuy** [comment]
fixed in 2.1.2
