### ISSUE TITLE
Pixie House Causing Server to Stop Responding

### ISSUE THREAD

**Issue by Zulenka** [Alex-the-666/Ice_and_Fire#3113]
![6444f63ba4cf97ca9790f516ed46c1e5 (2)](https://user-images.githubusercontent.com/30535627/98455401-117c9b80-213e-11eb-98bd-16731709de97.png)

This is the thread/warning that was occurring as the server stopped responding entirely. The server wouldn't generate a crash report it would just stop responding like a broken task manager or something. Only a force stop and restart would fix it and we'd lose about 5-10 minutes of progress.

**Comment by Gbergz** [comment]
Can confirm happened on my test server aswell.
https://hatebin.com/bbabrotyqz, no actual crash report but here's part of the logs where it happened.
