### ISSUE TITLE
Breeding Dragons crashed my game and now I can't connect back to my own server but my friends can. 

### ISSUE THREAD

**Issue by Shephard7** [Alex-the-666/Ice_and_Fire#3114]
So my gf and I were breeding our two fire dragons and as soon as they did the nasty we both got kicked and got this message
"internal exception io.netty.handler.codec.decoderexception java.lang.nullpointerexception".
It also says this message when I try joining my server for the first time: An established connection was aborted by the software in your host machine.
I only get this message on my server with Ice and Fire. I joined my other server just fine. I redid all my firewall rules as well and nothing has helped. 

I've been trying to find a solution all over and found that I have to remove a line of code somewhere but I have no idea where to go and find it https://github.com/Alex-the-666/Ice_and_Fire/pull/2928/commits/6dec8896a62c58b88d80b91b82b5d15233224b8e
 Fix #2920 remove registration of NULL owner ID in EntityDragonEgg:reg… 

This is also my first time dealing with my own modded server so any help would be great, but as for now I can't play on my own server :(

**Comment by ProSatu** [comment]
I am having the same issues as well unfortunately. What information could I additionally provide to help?
