### ISSUE TITLE
Nothing spawning on 1.16.3 (server log output set to false)

### ISSUE THREAD

**Issue by Dacarian** [Alex-the-666/Ice_and_Fire#3115]
So I know this issue has already been brought to attention, but I'm hoping maybe this helps the devs resolve the issue. @Alex-the-666 @raptorfarian - It appears as though by default the mod config is forcing the spawns to false regardless of the configs settings. 

> [Server thread/INFO] [co.gi.al.ic.IceAndFire/]: {SPAWN_DRAGON_SKELETON_I_CF=false, HYDRA_CAVE_CF=false, SPAWN_SEA_SERPENT_CF=false, SPAWN_STYMPHALIAN_BIRD_CF=false, SPAWN_WANDERING_CYCLOPS_CF=false, PIXIE_VILLAGE_CF=false, SPAWN_DEATH_WORM_CF=false, FIRE_DRAGON_CAVE_CF=false, SIREN_ISLAND_CF=false, MYRMEX_HIVE_DESERT_CF=false, SPAWN_HIPPOCAMPUS_CF=false, FIRE_DRAGON_ROOST_CF=false, MYRMEX_HIVE_JUNGLE_CF=false, GORGON_TEMPLE_CF=false, COPPER_ORE_CF=false, SILVER_ORE_CF=false, LIGHTNING_DRAGON_CAVE_CF=false, SPAWN_DRAGON_SKELETON_F_CF=false, AMETHYST_ORE_CF=false, SPAWN_DRAGON_SKELETON_L_CF=false, LIGHTNING_LILY_CF=false, MAUSOLEUM_CF=false, ICE_DRAGON_CAVE_CF=false, GRAVEYARD_CF=false, SAPPHIRE_ORE_CF=false, LIGHTNING_DRAGON_ROOST_CF=false, CYCLOPS_CAVE_CF=false, FROST_LILY_CF=false, FIRE_LILY_CF=false, ICE_DRAGON_ROOST_CF=false}
[15:17:45] [Server thread/INFO] [co.gi.al.ic.IceAndFire/]: {TROLL_S=false, HIPPOGRYPH=false, AMPHITHERE=false, COCKATRICE=false, TROLL_M=false, DREAD_LICH=false, TROLL_F=false}

**Comment by FlamingSharky** [comment]
I haven't tried it myself but can the main config be changed to prevent this? Since I too, am having this problem.

**Comment by Neko2n** [comment]
The config doesn't help, this happens regardless of the iceandfire-common.toml file's settings. We just have to wait for an update.

**Comment by J3RN** [comment]
I had success with using the default Ice and Fire config files from v2.1.0. I'm not sure _why_ that makes a difference, but it seems to.

**Comment by Dacarian** [comment]
> I had success with using the default Ice and Fire config files from v2.1.0. I'm not sure _why_ that makes a difference, but it seems to.

Would you mind sharing your config files please? I can't even get 2.1.0 to launch on a fresh forge 1.16.3 server =/ but ice and fire 2.1.1 will launch just obviously doesn't work correctly

**Comment by J3RN** [comment]
Sure thing! I had to add `.txt` to the end of the filenames so that GitHub would allow me to attach them. Be sure to remove the `.txt` before you try to use them.

[iceandfire-biomes.toml.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5532795/iceandfire-biomes.toml.txt)
[iceandfire-client.toml.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5532801/iceandfire-client.toml.txt)
[iceandfire-common.toml.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5532803/iceandfire-common.toml.txt)

[Update]: I'm using IaF 2.1.1-1.16.3, Forge 34.1.42

**Comment by Dacarian** [comment]
Oooo thank you, I think that might've worked, my server log is now showing all the spawns as =true <3 I'll go 1000 blocks away and see if it spawns anything in naturally =) 

Edit: Adding in those files did fix the spawns for me, as far as I can tell everything is spawning in on my server now =D

**Comment by ghost** [comment]
What follows is the diff comparing J3RN's biomes.toml config to the current one from All The Mods 6.  Perhaps it might be useful in fixing the bug: [good-vs-allthemods.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5535221/good-vs-allthemods.txt)

**Comment by J3RN** [comment]
[This commit](https://github.com/Alex-the-666/Ice_and_Fire/commit/c6157fca66e50c0d7f895ed9be3cd278df8ec35b) removed support for the biome query syntax that is still used in the default `iceandfire-biomes.toml` file for IaF 2.1.1, which explains the lack of spawns under those conditions.

As for All the Mods, my best guess is that not all biomes identify themselves as coming from the `allthemodium` mod.
**_What?_**
Biomes in `iceandfire-biomes.toml` are identified is the format `<modid>:<biome>` (e.g. `minecraft:desert`). This is also the same format that the `/locatebiome` command takes. All the biomes listed in the All the Mods `iceandfire-biomes.toml` config are listed as `allthemodium:<biome>`, including biomes that come from minecraft itself (e.g. `allthemodium:desert` instead of `minecraft:desert`).

The folks at All the Mods may have done some custom tinkering with biome identifiers that should make that work, but that's my best guess as to why it doesn't work for now.

**Comment by FlamingSharky** [comment]
> [This commit](https://github.com/Alex-the-666/Ice_and_Fire/commit/c6157fca66e50c0d7f895ed9be3cd278df8ec35b) removed support for the biome query syntax that is still used in the default `iceandfire-biomes.toml` file for IaF 2.1.1, which explains the lack of spawns under those conditions.
> 
> As for All the Mods, my best guess is that not all biomes identify themselves as coming from the `allthemodium` mod.
> **_What?_**
> Biomes in `iceandfire-biomes.toml` are identified is the format `<modid>:<biome>` (e.g. `minecraft:desert`). This is also the same format that the `/locatebiome` command takes. All the biomes listed in the All the Mods `iceandfire-biomes.toml` config are listed as `allthemodium:<biome>`, including biomes that come from minecraft itself (e.g. `allthemodium:desert` instead of `minecraft:desert`).
> 
> The folks at All the Mods may have done some custom tinkering with biome identifiers that should make that work, but that's my best guess as to why it doesn't work for now.

seems so, thanks, ill try it out in a bit

**Comment by Atros04** [comment]
> [This commit](https://github.com/Alex-the-666/Ice_and_Fire/commit/c6157fca66e50c0d7f895ed9be3cd278df8ec35b) removed support for the biome query syntax that is still used in the default `iceandfire-biomes.toml` file for IaF 2.1.1, which explains the lack of spawns under those conditions.
> 
> As for All the Mods, my best guess is that not all biomes identify themselves as coming from the `allthemodium` mod.
> **_What?_**
> Biomes in `iceandfire-biomes.toml` are identified is the format `<modid>:<biome>` (e.g. `minecraft:desert`). This is also the same format that the `/locatebiome` command takes. All the biomes listed in the All the Mods `iceandfire-biomes.toml` config are listed as `allthemodium:<biome>`, including biomes that come from minecraft itself (e.g. `allthemodium:desert` instead of `minecraft:desert`).
> 
> The folks at All the Mods may have done some custom tinkering with biome identifiers that should make that work, but that's my best guess as to why it doesn't work for now.

Even the biomes in the All the mods are not spawning anything related to Ice and Fire. I've gone out through the biomes listed in the .toml and have had 0 luck finding dragon skeletons, caves, roosts, and ores. I am going to be updating to the most recent ATM6 tonight and trying the suggest fix of the 2.1.0 config. Will report back later.

**Comment by thevortex** [comment]
I actually did the integration that made this work, we have a custom dimension that is made up of modified vanilla like biomes, but they are from the allthemodium modid namespace not minecraft. we had this working for the single update that we first added I&F to the pack 2.1.0, but 2.1.1 appears to have broken what was working :( , hope it gets added back in

**Comment by Atros04** [comment]
I tested @J3RN 's config/toml files with All the Mods 6 and can confirm that things are spawning, generating, and behaving as they should. While I did not customize it to work the the `allthemodium` biomes, it is working with `Biomes 'o Plenty` and vanilla biomes. I might get into the toml files to add in the `Biomes you go` biomes but for now J3RN has a great workaround.

Pack: All the Mods 6
Forge: 35.0.14
MC: 1.16.4

**Comment by thevortex** [comment]
it's great if you dont mind how much we boosted the stats on some of the mobs, we didnt add them to the overworld for that reason, perhaps edit the common.toml file as well and tone things down to suit your playstyle, we set the configs for some of the mobs to as high as they are allowed to go

edit: i also tested those files and in the default state they do work, however once i started editing them to include my custom biomes in a select dimension(whitelist was setup) things stopped working

**Comment by Morderkaiser-03** [comment]
Can somebody help me?  It is that I play in minecraft java 1.16.3 and the latest version of the mod does not work for me, there is no spawn of mobs or structures of the mod, I wanted to see if there is a solution, thanks.

**Comment by Dacarian** [comment]
> Sure thing! I had to add `.txt` to the end of the filenames so that GitHub would allow me to attach them. Be sure to remove the `.txt` before you try to use them.
> 
> [iceandfire-biomes.toml.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5532795/iceandfire-biomes.toml.txt)
> [iceandfire-client.toml.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5532801/iceandfire-client.toml.txt)
> [iceandfire-common.toml.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5532803/iceandfire-common.toml.txt)
> 
> [Update]: I'm using IaF 2.1.1-1.16.3, Forge 34.1.42



> Can somebody help me? It is that I play in minecraft java 1.16.3 and the latest version of the mod does not work for me, there is no spawn of mobs or structures of the mod, I wanted to see if there is a solution, thanks.

Morder go into your config files under .minecraft or in your server config if you're hosting one and delete the ice and fire .toml and add in these ones that J3RN uploaded, it fixed my issue =)

**Comment by JessieDagger** [comment]
This might seem like a dumb question but I cannot figure out how to get rid of the .txt portion of the J3RN configs- when I download them, their file type automatically changes to a "text document" and I can't change them to be "TOML files" like they're supposed to be. How do I fix this?

**Comment by AlexModGuy** [comment]
fixed in 2.1.2
