### ISSUE TITLE
Particles, ice, water, and any transparent blocks invisible when on dragon, and dragon armor appears detached from the dragon. Screenshots included.

### ISSUE THREAD

**Issue by TheSubparSniper** [Alex-the-666/Ice_and_Fire#3117]
I'm playing on 1.12.2 and whenever i'm on a dragon, transparent blocks like water and ice and all particles (ie. dragon breath) are completly invisible. In addition to that, when in the first person perspective, any dragon armor looks detached and it looks like it's floating in front of the camera.

Screenshots:
![2020-11-09_15 56 39](https://user-images.githubusercontent.com/74195975/98557217-3559f180-22a4-11eb-98af-9fe5b55fae72.png)

![2020-11-09_15 55 24](https://user-images.githubusercontent.com/74195975/98557320-59b5ce00-22a4-11eb-823d-16713272f309.png)

**Comment by BoatTK** [comment]
I'm having a similar problem. Have you found a solution yet?
