### ISSUE TITLE
Tidbits (or suggestions) and Bugs for next update

### ISSUE THREAD

**Issue by epicslayer999** [Alex-the-666/Ice_and_Fire#312]
([SG] means suggestion, [BG] means bug. [CBG] means compatibility bug.)

- [ ] [SG] Dragons and Hippogryphs shouldn't fly if there isn't enough space for them to fully rise. (Around 5 blocks from the highest point of the mob's head for it to see it as "can't fly".).

- [ ] [CBG] Mowzie's Mobs has a glitch where in their latest version, 1.4.0, Frostmaw's ice breath and freezing ability has an effect where statues frozen from a Gorgon can still move around. Proved this by removing Mowzie's and the statues now stand still. 

- [ ] [BG] While riding a Hippogryph, if the flapping noises can be occasionally heard while they're standing on the ground. Presumably this is the Hippogryph's attempting to fly while being ridden.

- [ ] [SG] Statues of hostile mobs (Zombies, Skeletons, Creepers, etc.) shouldn't despawn while on peaceful, since they'd be considered "non dangerous" because they are simply a statue.

- [ ] [SG] On the subject of statues, they should be blocks, not entities.

- [ ] [BG or SG] If they remain entities, Zombies try to attack villager statues nonetheless.

- [ ] [SG] There could possibly be a cure for getting turned into a stone statue. (Maybe having something to do with Pixies as well!)

- [ ] [SG] Any entities that would have it be fitting to, should sleep. (Mostly the animal ones like Hippogryphs, Hippocampus, the Stymphalian bird, Cockatrice, Sea Serpents, Amphithere, and any others sleeping would fit with.)

- [ ] [SG] Already finding a Hippogryph is rare enough, they should accept rabbit meat as well instead of the also rare drop of rabbit feet.

- [ ] [SG] Like mentioned in another issue, there should be a way to tell if a dragon is male or female.

(Will be edited based on further experimentation and other suggestions/issues!

**Comment by AlexModGuy** [comment]
all issues are dupes
