### ISSUE TITLE
2.1.1-1.16.3 mobs, structure, and ores don't spawn im lost 

### ISSUE THREAD

**Issue by Oj-Studbone** [Alex-the-666/Ice_and_Fire#3120]
I've installed everything, I can get items from the mod through creative and I can find some items through vanilla dungeon chest, but I haven't found a single ore, mob, or structure. I'm really at a loss as to why nothing is spawning.

**Comment by Neko2n** [comment]
Commonly known issue, has been reported plenty of times. There's no current fix other than to either downgrade your ice and fire version to an earlier 1.16.3 version (which are highly buggy and completely broken in many aspects) or to just wait for an update.

**Comment by AlexModGuy** [comment]
fixed in 2.1.2
