### ISSUE TITLE
1.16+ updates and features for 1.12?

### ISSUE THREAD

**Issue by TigerMC** [Alex-the-666/Ice_and_Fire#3121]
Hello! I've been playing with the mod for a good while in 1.12 then made a server with friends on 1.16.1 and i was amazed to see all the new structures and even new dragons! I was wondering if there would be a way to play with this updated version of the mod but in 1.12?

**Comment by JurXeno** [comment]
They aren’t doing updates for 1.12.2 anymore, only for newer versions.

**Comment by TigerMC** [comment]
Oh I see : c

Thank you for the answer!
