### ISSUE TITLE
Cockatrice attacking player, freezes and crashes the game

### ISSUE THREAD

**Issue by Shorepion** [Alex-the-666/Ice_and_Fire#3123]
When the Cockatrice attacks my game freezes and afterwards the game crashes.
Not sure if its the "wither beam" and its negative effects or the quick charge melee attacks.

MC 1.16.1, modversion 2.0.3
Modpack: https://www.curseforge.com/minecraft/modpacks/magica-infinitum-iii v3.0.2 (Modlist on first Description page)

https://pastebin.com/54mFC6zD

**Comment by AlexModGuy** [comment]
> at com.integral.enigmaticlegacy.handlers.EnigmaticEventHandler.onPlayerTick

not ice and fire.
