### ISSUE TITLE
My forge server show me that the Ice and Fire mobs spawn are disabled

### ISSUE THREAD

**Issue by xXMolgadoGamer01Xx** [Alex-the-666/Ice_and_Fire#3125]
Hi.
I'm having an issue with my minecraft server, my server is showing me the following thing:
![image](https://user-images.githubusercontent.com/24871116/98764473-784dbf00-23a1-11eb-89aa-ca370dc2339b.png)
My server configs are completely untouched.
Hope you can help me.
Have a nice day 👍

**Comment by Cocklet** [comment]
same thing occuring for me!!!

**Comment by J3RN** [comment]
@xXMolgadoGamer01Xx @Cocklet There is already an open issue (with a temporary fix) here: https://github.com/Alex-the-666/Ice_and_Fire/issues/3115

**Comment by xXMolgadoGamer01Xx** [comment]
> @xXMolgadoGamer01Xx @Cocklet There is already an open issue (with a temporary fix) here: #3115

Okey, I'm gonna chek it out, Thx

**Comment by AlexModGuy** [comment]
fixed in 2.1.2
