### ISSUE TITLE
Suggestion: Option to allow dread lich to spawn dreads infinitely (pls read why)

### ISSUE THREAD

**Issue by windu666** [Alex-the-666/Ice_and_Fire#3126]
Okay, so I understand this is not an option in order to prevent the farming of resources.
To prevent that, maybe if this option was available in the config, the original amount of spawned dreads would drop their stuff like every other day, but what follows wouldn't.

I had this epic idea about an arena where a dread lich would be under to spawn contestants for whoever dares enter!
Also, this option would make the dread lich a more challenging adversary for mid/late game.

**Comment by AlexModGuy** [comment]
no.
