### ISSUE TITLE
Fairies too loud

### ISSUE THREAD

**Issue by CookieCraver** [Alex-the-666/Ice_and_Fire#3127]
The fairies when you place them you can hear them from like a 40 block radius and their super loud, I had to turn my blocks all the way down. Also, I have the latest version 2.1.0

**Comment by garyuu** [comment]
Same problem here with 2.1.1-1.16.3.
It will be fine if I can only hear pixie jars within maybe 8 blocks.
But it is too annoying that I can hear them in my whole base with just only one pixie jar.
Maybe some configurable variables for customization are needed here?
