### ISSUE TITLE
Graveyards spawn too much (Nov 13/15 update from Source Code)

### ISSUE THREAD

**Issue by AxolotlAccount** [Alex-the-666/Ice_and_Fire#3131]
Everywhere is filled with graveyards in the latest build from github.

Minecraft Version:  1.16.4
Forge Version: 35.0.17

Latest Log: https://hastebin.com/qetigoqijo.sql

**Comment by Carro1001** [comment]
are other things spawning tho?

**Comment by AxolotlAccount** [comment]
Yes but very few. I searched for 15 minutes flying in creative and only found 1 dragon nest. (and 10 graveyards)

**Comment by AxolotlAccount** [comment]
Update: Tested on Nov 15 version. Searched for 15 minutes in creative and I found 7 graveyards. Zero dragon nest.

**Comment by J3RN** [comment]
By editing the `config/iceandfire-common.toml` file in your game instance's folder, you can modify the spawn chances of most things (dragon caves, nests, sirens, etc). Weirdly, there's not an option for the prevalence of graveyards, which should probably be added.

**Comment by AlexModGuy** [comment]
fixed in 2.1.2
