### ISSUE TITLE
Random Server Crash

### ISSUE THREAD

**Issue by WulfTheGod** [Alex-the-666/Ice_and_Fire#3134]
Server host told me to contact you guys for this.
https://mcpaste.io/2333339bd9eec2ca

**Comment by AlexModGuy** [comment]
>     at funwayguy.epicsiegemod.ai.ESM_EntityAINearestAttackableTarget.shouldExecute(ESM_EntityAINearestAttackableTarget.java:73)

not our issue. contact epic siege mod
