### ISSUE TITLE
1.16.3 - No mobs or structures spawning

### ISSUE THREAD

**Issue by Attila-the-Bun** [Alex-the-666/Ice_and_Fire#3136]
I've ran around for ages trying to find anything from the mod but nothing seems to spawn in (though the menu indicates that Ice and Fire is active).
Please help :)

**Comment by ghost** [comment]
omg me tooo
its just a normal world :(

**Comment by KreloX** [comment]
Working alternaative config files:
https://github.com/Alex-the-666/Ice_and_Fire/files/5532795/iceandfire-biomes.toml.txt
https://github.com/Alex-the-666/Ice_and_Fire/files/5532801/iceandfire-client.toml.txt
https://github.com/Alex-the-666/Ice_and_Fire/files/5532803/iceandfire-common.toml.txt
This should help, just remember when throwing this into the config folder, remove the ".txt" thats there just for github to allow sharing it

**Comment by deeddles** [comment]
> Working alternaative config files:
> https://github.com/Alex-the-666/Ice_and_Fire/files/5532795/iceandfire-biomes.toml.txt
> https://github.com/Alex-the-666/Ice_and_Fire/files/5532801/iceandfire-client.toml.txt
> https://github.com/Alex-the-666/Ice_and_Fire/files/5532803/iceandfire-common.toml.txt
> This should help, just remember when throwing this into the config folder, remove the ".txt" thats there just for github to allow sharing it

How do you turn it into a .toml?

**Comment by AlexModGuy** [comment]
fixed in 2.1.2
