### ISSUE TITLE
Dragon armor does not provide actual armor

### ISSUE THREAD

**Issue by EnderiumSmith** [Alex-the-666/Ice_and_Fire#314]
[image](http://imgur.com/a/13bRi)

the health bar on the zombie shows its 2 natural armor points but the dragon's health bar does not show any armor despite being equipped with gold armor.

**Comment by AlexModGuy** [comment]
Dragon armor just halves/one-thirds/one-fiths damage taken

**Comment by EnderiumSmith** [comment]
what about armor piercing attacks like instant damage potions?
