### ISSUE TITLE
Manuscript dupe glitch?

### ISSUE THREAD

**Issue by PallyK** [Alex-the-666/Ice_and_Fire#3142]
was playing on a new world with 2.1.1 and decided to make a bestiary and lectern, started putting entries in and once it was done, noticed that taking the manuscripts out refilled them back to the original amount. the bestiary works as intended but the manuscripts lead to only needing four extra in order to gain every entry in the book

**Comment by Mewkitty22** [comment]
I've noticed the same issue. I am playing the most recent build.

**Comment by J3RN** [comment]
This appears to be the same as #2933. Would you mind closing this issue and commenting there so that we can keep the conversation all in one place?

**Comment by PallyK** [comment]
Alrighty, it is the same issue as #2933 didn't read the other issues to the fault is on me
