### ISSUE TITLE
Cockatrice can see and acttacks you in spectator mode 1.15.2 (I/F 2.1.0)

### ISSUE THREAD

**Issue by Phantom2909** [Alex-the-666/Ice_and_Fire#3145]
![2020-11-17_22 55 16](https://user-images.githubusercontent.com/70826397/99482491-feca4980-2929-11eb-860c-cce18075b455.png)
![2020-11-17_22 55 19](https://user-images.githubusercontent.com/70826397/99482495-01c53a00-292a-11eb-828e-1849b9cd986c.png)
Well, the cockatrice can see me in spectator.

**Comment by EuFugs** [comment]
Same issue in 1.16.4 - 2.1.3
