### ISSUE TITLE
Nothing spawns in 1.16.3 or 1.16.4

### ISSUE THREAD

**Issue by BWKing98** [Alex-the-666/Ice_and_Fire#3150]
Have tried all versions of citadel 1.4.0 or higher and am using ice and fire 2.1.1, nothing will spawn in either version of Minecraft 1.16.3 or 1.16.4. No creatures or structures but when I go in creative I can spawn them just fine with spawn eggs?

**Comment by Treep3r** [comment]
Can confirm, having the same issue on our server

**Comment by deeddles** [comment]
Same here. The only items from it that I can find are rotten eggs from chickens, but they aren't spawning anything.

**Comment by AlexModGuy** [comment]
fixed in 2.1.2
