### ISSUE TITLE
[1.16.4] Server time out

### ISSUE THREAD

**Issue by Daejangnamu** [Alex-the-666/Ice_and_Fire#3152]
Server timeout (no error)
video: https://youtu.be/doi4xg4xcZU

Modlist
![modslist](https://user-images.githubusercontent.com/52635462/99737566-e3b72f80-2b0b-11eb-8ddb-60c8877dba7f.png)

**Comment by Carro1001** [comment]
Taigas are cold biomes, so ig ice dragons would spawn there

**Comment by Daejangnamu** [comment]
> Taigas are cold biomes, so ig ice dragons would spawn there

Oh... sorry

**Comment by D-Bigboy-302** [comment]
I'm having this same exact issue. Heres my log: 
[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/5578858/latest.log)

**Comment by Carro1001** [comment]
This is definitely an i/f issue, as i've had the same problem twice before, and another dev also tested it, and confirmed it was ice and fire, i think it's when it generates an ice dragon cave, but it doesn't happen every time it generates one though

**Comment by progfz** [comment]
It's not likely to be connected to ice dragon caves - we have all kinds of dragons disabled alongside with trolls on our private server and yet we still get that taiga timeout.

**Comment by Carro1001** [comment]
Worst part is that the problem cannot be easily replicated, as i went to the same spot multiple times in my world and it only timed out once

**Comment by progfz** [comment]
Recreating world with the same seed seems to give rather reasonable recreation path though.
