### ISSUE TITLE
Ice Dragons lagging Entire Game [1.16.3]

### ISSUE THREAD

**Issue by druidicmage** [Alex-the-666/Ice_and_Fire#3156]
When ice dragons interact with water, it causes the game a *ton* of lag. From what I can tell, they freeze it, then break it, over and over again. It also seems that dragons get stuck in water (maybe *just* ice dragons) in general, which *also* lags the game.

**Comment by Davoshi** [comment]
I can confirm that, I got that happening to me too and it's so hard to deal with it

**Comment by lacomarca** [comment]
I can confirm this as well. Only happens with ice dragons :(

**Comment by AZOleZOZOLevrai** [comment]
it's also annoying when you want to kill a dragon because its delay then suddenly it can kill you ...

**Comment by BugmanBugman** [comment]
Can confirm as well

**Comment by Killer-Awesome-Phantom** [comment]
Im having the same problem i have used spark to find what mod was causing all the lag i have linked the spark report if you want to check it out.

Spark report: https://spark.lucko.me/#nWLwm957Tu

**Comment by willownezz** [comment]
same here, Ice dragons upon getting into viewing distance just almost crash my single player world, sometimes completely freezes for about 5 minutes and comes back, sometimes it does not. 

iceandfire-2.1.3-1.16.4
citadel-1.5.2

Playing on ATM6 1.3.1 modpack Ice and fire was manually updated by me.

**Comment by Cabel496** [comment]
Sama here, ice dragon lags the entire server when it is in water.

**Comment by aracaid** [comment]
Same problem when I just came to ice dragon I have like 1-0 fps. But when and came in creative same world and place no problem is normal 60fps.
And second problem .When ice dragon have cave under ocean when he break the blocks in ocean he got stuck in swimming mod and can't get out.
