### ISSUE TITLE
Scribes apparently do not have a zombie texture

### ISSUE THREAD

**Issue by BugmanBugman** [Alex-the-666/Ice_and_Fire#3158]
https://hatebin.com/heqktegcdz

**Comment by SodiumShine** [comment]
Also getting this bug. Happens when spawned naturally or when the villager is killed by a zombie.

ice and fire 2.1.5
forge 36.0.10

![image](https://user-images.githubusercontent.com/4461697/106377081-90f0d280-63ee-11eb-8302-82415a252930.png)

**Comment by ContentCrisis** [comment]
Forge 35.1.37, same version of ice and fire. Can confirm that zombie scribes have some sort of texture bug or missing texture that results in the picture from SodiumShine.
