### ISSUE TITLE
Still no worldgen in dimensions other than overworld with latest update

### ISSUE THREAD

**Issue by thevortex** [Alex-the-666/Ice_and_Fire#3160]
Ice & Fire 2.1.2
Citadel 1.5.0

First, I deleted my old configs, both iceandfire-biomes.toml and iceandfire-common.toml and had the game generate fresh ones.  I have then re-edited them at the following

https://pastebin.com/UV3KyQg5 - Biomes

https://pastebin.com/FjZHKmGa - Common

This was working in 2.1.0 but now, I am not getting any structures, or mobs, from ice and fire,but my debug info shows all values set at true

https://pastebin.com/ZSMgWygF - Debug output

**Comment by whatthedrunk** [comment]
For some reason no matter what we do we cannot get it to work anymore. 2.1.0 worked just fine.

**Comment by Peach774** [comment]
Can confirm this issue in my own pack. I tried setting the mobs to spawn in a custom dimension for my pack and they just don't spawn.

**Comment by steliosagge** [comment]
Please fix i got the same problem.

**Comment by thevortex** [comment]
oh has this been resolved?

**Comment by Carro1001** [comment]
the dev is closing all issues because the github is flooded with outdated ones, he can't track them properly

**Comment by thevortex** [comment]
k, will reopen this as I prefer to have my issue looked at rather than ignored for 4 months

**Comment by Carro1001** [comment]
Wait wait, he's still in the process of "redoing" the github, he hasnt closed all issues yet

**Comment by thevortex** [comment]
lmfao too late, issues dont go away because you close a ticket that has been ongoing for 4 months(almost 5 issue started early nov)
