### ISSUE TITLE
[1.16.4] Some structures doesn't spawn

### ISSUE THREAD

**Issue by AxolotlAccount** [Alex-the-666/Ice_and_Fire#3162]
I could find Gorgon Temples, Pixie Villages and Graveyards but not a single Dragon Nest, Siren Island and Cyclops Cave after hours of search.

Minecraft: 1.16.4
Forge: 35.1.0
Ice and Fire: 2.1.2
Citadel: 1.5.2

**Comment by ViRb3** [comment]
I saw an ice dragon nest today.
