### ISSUE TITLE
1.16.3  system requirements

### ISSUE THREAD

**Issue by Sky145454** [Alex-the-666/Ice_and_Fire#3163]
I have a Nitrado server with the IceandFire mod.  I was just about to kill a lightning dragon to get his egg because I was kicked: coneting closed because connection takes too long.  Now when I'm Jones I'm always kicked after 5 seconds and the message is always displayed to me.  And the server console says: [13:43:39] [Server thread / WARN] [minecraft / MinecraftServer]: Can't keep up!  Is the server overloaded?  Running 2026ms or 40 ticks behind.  so the server is way too slow.  My question now is how much RAM does the server need to solve the problem

**Comment by Xorbah** [comment]
How much ram do you have on said server and how big is your world? Also,
how many mods are you running? This could be a multitude of issues.
