### ISSUE TITLE
Everything Spawning Everywhere

### ISSUE THREAD

**Issue by Nimflora** [Alex-the-666/Ice_and_Fire#3165]
Booted up a new world, spawned in a forest, was immediately accosted by cockatrices. Further exploration uncovered a lot of amphitheres and a mausoleum. In a forest.

**Comment by Carro1001** [comment]
what forge version are you on?

**Comment by Nimflora** [comment]
34.1.24

**Comment by Carro1001** [comment]
update to the latest forge

**Comment by kobiYeet** [comment]
go to your config folder and delete iceandfire-biomes.toml and recreate the world

**Comment by AlexModGuy** [comment]
^
