### ISSUE TITLE
Memory Leak with Dragon Scale Armor

### ISSUE THREAD

**Issue by AnonRou** [Alex-the-666/Ice_and_Fire#317]
I'm getting a memory leak  on my client while playing with ice and fire with all versions for 1.11.2. 
I've isolated it to when viewing any dragon scale armor. It could be in the player equipment/paperdoll or while viewing other players in game. As long as the armor is equipped and visible in some way i see Java continuously consuming memory 

I've tested this in all versions of ice and fire for 1.11.2
I've tested this while using many other mods but also with nothing loaded but Llibrary and ice and fire (not even optifine or other optimization mods)
I've tested with and without JVM arguments.
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
-XX:+UseG1GC -Xmx4G -Xms4G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

-Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
I've also tested with different versions of JRE installed I've gone back as far as JRE 8u25

It doesn't matter what piece is worn, as long as any is worn and visible it happens. Naturally i can play single player in first person without issues but in 3rd person or on servers the memory leak happens.

Naturally if i leave it alone, while letting the memory pile up, Minecraft becomes completely unresponsive and of course will not properly crash unless i kill the JRE process.

**Comment by darthvader45** [comment]
@Alex-the-666 @raptorfarian I've had this same leak with 1.2.1 of Ice and Fire.  I cannot play Minecraft reliably and wear this armor at the same time.  If the fix is ready, please implement it in 1.2.2.

**Comment by AlexModGuy** [comment]
this was fixed a while ago

**Comment by darthvader45** [comment]
Was it implemented in 1.2.1?  I don't think so.
