### ISSUE TITLE
Problems with structures

### ISSUE THREAD

**Issue by Polomka** [Alex-the-666/Ice_and_Fire#3174]
Too many gorgon temples, graveyards, and spawn structures not in their biomes.
Dragon skeletons appear on the surface of the water in the oceans
![2020-11-23_10 55 34](https://user-images.githubusercontent.com/35797201/99944452-904b1880-2d7b-11eb-9eca-f4e1e6330662.png)

**Comment by J3RN** [comment]
@Polomka Thanks for reporting this! :wave:

I think this issue may be caused by some out-of-date config files. Does this issue still occur if you delete your `config/iceandfire-biomes.toml` file and let the mod re-create it?

**Comment by Polomka** [comment]
> @Polomka Thanks for reporting this! 👋
> 
> I think this issue may be caused by some out-of-date config files. Does this issue still occur if you delete your `config/iceandfire-biomes.toml` file and let the mod re-create it?


I'm sorry, this is my problem. Biomes O` plenty broke the generation
