### ISSUE TITLE
1.16.3 Ice and Fire entities and structures won't spawn naturally 

### ISSUE THREAD

**Issue by Weberton01** [Alex-the-666/Ice_and_Fire#3186]
After downloading the 1.16.3 version of ice and fire, I noticed a significant lack of ice and fire creatures, structures, and resources. It isn't impossible to get the items from the ice and fire mod in the game; for example, chickens can still lay rotten eggs, so it is still possible to get a tamed cockatrice. However, no creatures or resources are spawning in the Minecraft world. The mod is not causing any crashes.

**Comment by Carro1001** [comment]
What is the mod's version you're playing on?

**Comment by Weberton01** [comment]
> What is the mod's version you're playing on?

It is 2.1.1

**Comment by Carro1001** [comment]
Update your mod to 2.1.3, and delete iceandfire-biomes.toml from the config folder, and yes, it works on 1.16.3, as 1.16.3 and .4 are basically identical

**Comment by Weberton01** [comment]
> Update your mod to 2.1.3, and delete iceandfire-biomes.toml from the config folder, and yes, it works on 1.16.3, as 1.16.3 and .4 are basically identical

Thank you

**Comment by J3RN** [comment]
@Weberton01 If your problem is resolved, feel free to close this issue :grin:
