### ISSUE TITLE
Bestiary blank

### ISSUE THREAD

**Issue by CryoCrow** [Alex-the-666/Ice_and_Fire#3188]
I'm playing the mod pack Yao Craft on a private server with my friend. He created an Ice and Fire bestiary and added some entries to it using the lectern. However, after opening it to read the bestiary is completely blank. The only thing on the pages is the forward and back buttons. So I tried making one myself. I crafted it and opened it and it did have the introduction entry. So I put it in the lecture and added an entry took the book back and it did have the added entry and I was able to open and read the entry. So I put it back added a new one checked and it had both the new entries. However, upon adding the third entry the book only contained the new entry and the introduction. Upon adding the fourth entry the book was completely blank. No added entries and no introduction. I went into creative to test it and the same thing happened.

![20201120132339_1](https://user-images.githubusercontent.com/74978760/100120738-ed0f0780-2e3d-11eb-8875-5a35f6eb03b5.jpg)

**Comment by Brillig145** [comment]
I have the exact same problem. Watching

**Comment by Brillig145** [comment]
Ended up using creative mode to give myself pages, then found it was fine to add 2 new entries per book, but any more broke it. Creative mode solution is good, made the bestiaries/entries how they should have been, then deleted the excess.
