### ISSUE TITLE
Duplication Glitch With Manuscripts and the Beastiary

### ISSUE THREAD

**Issue by CmdrNorthpaw** [Alex-the-666/Ice_and_Fire#3189]
I have come across a way to use a small supply of manuscripts for an infinite amount of knowledge in the 1.16 version. 

To reproduce:  
1. Open the mod lectern and place 3 manuscripts and a bestiary inside.
2. Research some knowledge, noticing it consumes 3 manuscripts
3. Remove the Bestiary and close the lectern GUI
4. Open the lectern GUI again and notice that there are three manuscripts still there, however the knowledge you used them for is retained in the Bestiary

In this way, you can use 3 manuscripts to research whatever knowledge you want and not actually consume any manuscripts. I have not tested if one needs to empty the lectern of manuscripts for this to occur.

Mod version 2.1.3, Forge v31.1.0

**Comment by J3RN** [comment]
Hey @CmdrNorthpaw! Thanks for reporting this! The steps to replicate this bug are super helpful. Unfortunately this is a known issue which has yet to be resolved. The original issue is here: https://github.com/Alex-the-666/Ice_and_Fire/issues/2933. Would you mind closing this duplicate issue and commenting on the original?

**Comment by CmdrNorthpaw** [comment]
Closed as duplicate of #2933
