### ISSUE TITLE
configuring graveyard spawning does nothing

### ISSUE THREAD

**Issue by Nimflora** [Alex-the-666/Ice_and_Fire#3190]
Turned rarity to 2, and then to 9999. Graveyards always seem to pop up with the same frequency.

**Comment by GarthF** [comment]
Yeah, I generated a new world and its littered with graveyards.

**Comment by BugmanBugman** [comment]
The graveyards do seem to be overly abundant

**Comment by Bidgam** [comment]
Is 2 rare or is 9999 rare? The config could clarify this too please.
