### ISSUE TITLE
Dragoon Bow Animation 

### ISSUE THREAD

**Issue by AsianDropOut** [Alex-the-666/Ice_and_Fire#3192]
Dragon Bow is shooting fine ever since the update but the animation for when the bow charges up with the arrow hasn't been fixed since the update. I used the right arrow with it and also tried having the arrow next to the bow in the hotbar and nothing changed. Its just an invisible projectile being shot from the bow itself. However the arrow itself can be seen when, for example, when it hits a wall and can be visible when picked up.  I don't know if its just me or if its impacting everyone one else like last time.

**Comment by BugmanBugman** [comment]
https://streamable.com/ygla8g

I have a video to confirm this

**Comment by AsianDropOut** [comment]
> https://streamable.com/ygla8g
> 
> I have a video to confirm this
Its good I'm not the only one, wish more ppl can add on to this issue so it can be seen.

**Comment by aracaid** [comment]
Same problem is weird to shoot and not even see when arrow go
