### ISSUE TITLE
Bestiary does not want to render properly when its in a full window

### ISSUE THREAD

**Issue by Sunconure11** [Alex-the-666/Ice_and_Fire#320]
![screenshot 2017-09-17 01 50 36](https://user-images.githubusercontent.com/5614902/30518392-bac27f7a-9b4a-11e7-88ee-95d1edb007c9.png)

Opening and closing the book resolves it, but its still odd.

**Comment by AlexModGuy** [comment]
@Sunconure11 does this still happen

**Comment by Sunconure11** [comment]
Checking now, it does not seem so.
