### ISSUE TITLE
Multiplication of manuscripts 

### ISSUE THREAD

**Issue by OsowiecBR** [Alex-the-666/Ice_and_Fire#3206]
I am in the latest version of the mod to 1.16.4, and... look at the gif!
![BUGs](https://user-images.githubusercontent.com/74195525/100266164-2031c380-2f30-11eb-8d18-6b0935313c65.gif)

**Comment by D-Bigboy-302** [comment]
I've noticed that as well. Weird little bug.

Forge: 1.16.3-34.1.42
Mod Version: 2.1.3-1.16.4

**Comment by Dwarfy-Dug** [comment]
Can confirm...I also have this bug. same game version. Have a few mods installed..Botania, a minimap mod and craftable saddles...but everything else seems to work as intended.

**Comment by Wolfstar1010** [comment]
I've also just noticed this. Was about to report but saw it had already been brought up

**Comment by brodheadw** [comment]
Happens to me as well. Am playing with many other mods

**Comment by Glemoyn** [comment]
I can confirm I am still getting this bug.I am using Ice and fire 2.15-1.16.4 on a server (additional mods on server are Botania, Astral, Blood Magic, Create, Corail Tombstone, Biomes o Plenty, Waystones, Immersive Engineering, Jei and TheOneProbe, FTB Chunk, FTB Gui and all dependencies)
To recreate, place at least 3 manuscripts in Lectern with bestiary, click on research topic, exit lectern GUI and re-enter, the three manuscripts you used will be duplicated so you will have the same amount as before. If you use 3 manuscripts and remove any remainder from the lectern, when you leave and re-enter the GUI they will be duplicated in your inventory.
