### ISSUE TITLE
Ghosts!

### ISSUE THREAD

**Issue by Polomka** [Alex-the-666/Ice_and_Fire#3207]
1) I killed a lot of ghosts, but I didn't get a single ingot. Is this a normal drop rate for this item?   (i stopped killing after 456)

2) A flying shield emerged from the cursed chest. The properties of this mob are the same as those of a ghost. Is this a reference to something or a conflict with another mod?

![Inked2020-11-25_20 22 24_LI](https://user-images.githubusercontent.com/35797201/100272777-60ab3480-2f64-11eb-841f-f5c2bd53dce1.jpg)
![Inked2020-11-25_21 06 26_LI](https://user-images.githubusercontent.com/35797201/100272787-643ebb80-2f64-11eb-9501-b54e95b8a325.jpg)
![Inked2020-11-25_21 08 13_LI](https://user-images.githubusercontent.com/35797201/100272791-656fe880-2f64-11eb-8baf-fe962f18729d.jpg)

**Comment by Carro1001** [comment]
the 1st image is a funny spongebob easter egg

**Comment by AlexModGuy** [comment]
ingots are also a rare drop.
