### ISSUE TITLE
Ice and Fire has failed to load correctly, java.lang.ExceptionInInitializerError: null

### ISSUE THREAD

**Issue by kumpiir** [Alex-the-666/Ice_and_Fire#3212]
I tried with every version of Citadel and Ice and Fire for 1.16.4 and 1.16.3, tried deleting the whole game and mods, reinstalling but still it is the same error.
[crash-2020-11-26_12.44.44-fml.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5601992/crash-2020-11-26_12.44.44-fml.txt)

Non [a-z0-9/._-] character in path of location: iceandfire:hıppogryph_skull

Tried to do the only thing I understood so I searched if there was a file or something named like that but I couldn't find anything. I would appreciate it if you can help.

**Comment by Fnetra** [comment]
The same thing happened to me. I even tried 1.15.2 but the result was the same for multiple versions of ice&fire, citadel and forge. There is nothing on the internet that can solve this problem currently I believe, as even the developer of the mod didn't release anything regarding this issue.
