### ISSUE TITLE
DragonForge not working 

### ISSUE THREAD

**Issue by zac67911** [Alex-the-666/Ice_and_Fire#3223]
Dragon forge crafted correctly but my lightning dragon doesnt notice it. even when manually using the dragon the forge doesnt create dragonsteel?

**Comment by FurryApocalypse** [comment]
I think i just figure it out. Try to dig out your core (heart of forge) with  pickaxe. Dragon won't forge untill the heart is lighten up. Make sure that heart is black, then put items inside. Repeat after every use. Worked for me ~~

**Comment by FurryApocalypse** [comment]
> Dragon forge crafted correctly but my lightning dragon doesnt notice it. even when manually using the dragon the forge doesnt create dragonsteel?

I think i just figure it out. Try to dig out your core (heart of forge) with  pickaxe. Dragon won't forge untill the heart is lighten up. Make sure that heart is black, then put items inside. Repeat after every use. Worked  for me ~~
