### ISSUE TITLE
Error: Dragon and Waters 

### ISSUE THREAD

**Issue by map10145** [Alex-the-666/Ice_and_Fire#3226]
Hi, 

i Use forge  1.16.4 35.1.0 (recommended),citadel-1.5.2 and iceandfire-2.1.3-1.16.4. 

I have a problem with all dragons. When I fight a dragon and run to water, the dragon AI goes crazy. He jumps like a frog, does not attack the player and most importantly ... ping increases tremendously (12589 ms) and sometimes the game crashes.
I play with the girl on a small server. The server has 5000MB of RAM. Is it my fault or if I found a bug, and if I found a bug, how could I fix it.

Specification server:
Intel® Xeon® E3-1275 v5 4.0GHz Turbo DDR4
NVMe SSD 5GB
Setting Server:
#Fri Nov 27 19:31:06 CET 2020
admin-slot=false
allow-flight=true
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
difficulty=hard
enable-command-block=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings=
grow-trees=true
hardcore=false
level-name=world
level-seed=-3378197974448699400
level-type=default
max-build-height=256
max-connections=3
max-players=25
max-tick-time=60000
max-world-size=10000
motd= Zupa z Elfa
network-compression-threshold=256
online-mode=true
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
public=false
pvp=true
query-port=
query.port=
rate-limit=0
rcon.password=
rcon.port=25575
resource-pack=
resource-pack-sha1=
server-ip=
server-name=TitanAXE.com Minecraft Server
server-port=
snooper-enabled=true
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=16
sync-chunk-writes=true
text-filtering-config=
use-native-transport=true
verify-names=true
view-distance=8
white-list=false

link to my video on youtube what the error looks like. 

the best mod I've played :D

Have a good day.

"Bajooooooo"

**Comment by MrAmazomas** [comment]
Can confirm this as well... 
Tho the massive lag only happens for ice dragons. The other dragons can normally swim. Furthermore it gets stuck in the gliding animation when it enters water as well as the problems mentioned here. 
Think it might be because of the constant break of ice it creates when doing it's breath attack and the bugged AI. 

Hoping for a fix...
MrAmazonas

[Edit] Playing on single player world

**Comment by aracaid** [comment]
Same problem. Worst is that I was travelling through Ice spikes biom and stage 5 woke up.
can´t play I must remove whole biom with WE to fight him.
