### ISSUE TITLE
Dragon armor extra

### ISSUE THREAD

**Issue by JohannesGreiGutt** [Alex-the-666/Ice_and_Fire#3229]
Wouldn’t it be cool if you could take the wings of a dragon and put it on your dragon armor? Or have it on whenever you make it, and then be able to fly? And then when you upgrade to dragonsteel armor, you could have mechanic wings and a system that made your sword either iced, flamed or lightning. I think that would be pretty cool

**Comment by Carro1001** [comment]
This is an issues github, not a suggestions github, the suggestions github is https://github.com/Alex-the-666/Ice-and-Fire-Suggestions/issues
