### ISSUE TITLE
Ticking entity crash (as well as competition rewards)

### ISSUE THREAD

**Issue by Annabell-O** [Alex-the-666/Ice_and_Fire#323]
while making and setting up the server for Ice and fire, I have found that there is a ticking entity crash relating around an interaction between the snow villagers and zombies. I do not know if this is from the snow villagers being turned into zombies, or if it is from the zombie targeting AI (which seems less likely). in short I have to get rid of all snow villagers on the server or deal with constant crashes.

on the second note. you told me to post here about not receiving the award for winning the build competition. so here I am, my mine craft UN (if you need it) is of course Zyranna (I like to keep it constant). thank you.

**Comment by AlexModGuy** [comment]
dupe
