### ISSUE TITLE
I've updated Ice and Fire on RLCraft 2.8.2 and it's crashing with that message

### ISSUE THREAD

**Issue by Koszorowy** [Alex-the-666/Ice_and_Fire#3230]
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/core/ModItems
Kod zakończenia: -1

**Comment by MagmaSlime123** [comment]
Talk to the dev of RLCraft. They're responsible for the issue. Probably another mod conflict that this mod has that'll never be fixed.
