### ISSUE TITLE
[1.12.2] Water is invisible whilst riding a dragon.

### ISSUE THREAD

**Issue by MagmaSlime123** [Alex-the-666/Ice_and_Fire#3231]
Not sure if another mod is causing this or not.
I&F 1.9.1, MC 1.12.2, Forge 2854.

If this mod is dead, then please delete it. Your just another dead dev crawling into the pile of dead projects..

![2020-11-30_14 20 45](https://user-images.githubusercontent.com/51277766/100672812-4e8c1600-3317-11eb-9d27-8c3f77ab68c5.png)
![2020-11-30_14 20 55](https://user-images.githubusercontent.com/51277766/100672819-4fbd4300-3317-11eb-8dab-c80ea5ec22f4.png)

**Comment by Ninjayatsu** [comment]
Hey idiot bug reporting is gud but if u gonna be ass to epic mod 😎 don't cause ur negativity is not needed. This is the vibe zone where we vibe no p00pin on the vibe

**Comment by Spqark** [comment]
The mod isn't dead, however the Minecraft Modding for 1.12 **is** dead.

**Comment by Phantom2909** [comment]
Dude, don't be an asshole. Alex makes these mods because he likes them, not to please someone who can't cope with the changes. You already look like a Neanderthal who detested his evolved cousins, the homo sapiens. And all because you do not want to evolve to something more modern, I quote Darwin, "who adapts survives" and 1.12.2 did not survive.

**Comment by BrayDoesStuffYT** [comment]
I made an account just to clown on you. Stop being a 1.12.2 Stan and accept new version, the creator of the mod does not want to stick to Neanderthal versions, and if you cant accept change, either don't play with the mod or deal with the bugs on 1.12.2. Maybe if you actually joined the discord for Ice & Fire or read the CurseForge page, you'd know this. New versions of the mod have much more content than the practically boomer 1.12.2 version. 1.12.2 is old as is, and is on the brink of dying. 1.12.2 did not survive nor did 1.7.10, stop being an asshole. Even if the mod WAS dead, (which it isn't), people would still use it. You have a brain the size of a walnut, please get off the internet. If your underage, stay off social media platforms such as this one and please get a life other than telling a Minecraft Modder to delete his mod. If there's 1 thing worse than 1.7.10 Stans, its 1.12.2 Stans. Everytime a new popular Modding version comes out, people like you do this dumbass bull shit. I bet you like RLcraft and Orespawn LMAO. Stop being a pea brain and think about how you're words effect other people. Maybe also don't be so blunt. Now please, fuck off and do something else with your life. Just so you know, the creator of this mod has seen this. Edit: And no, I don't give a fuck if updating to a new version screws up your modpack.

**Comment by Neko2n** [comment]
The only thing dead is the >3-year-old version you're stuck on.

**Comment by Laktostolerant** [comment]
Oh no it's EnderBro again... every single rude github post on every mod I see is from this asshole

**Comment by DrPenguinni** [comment]
You're the reason why 1.12.2 is a developmentally dead version, EnderBro. Those who don't accept change get left behind.

**Comment by JurXeno** [comment]
Simple answer EnderBro: move on from 1.12.2 and use 1.16.4 versions since 1.12.2 is dead and always has been since the newer updates for Minecraft released.

**Comment by MagmaSlime123** [comment]
1.12 isn't dead. I've seen mods that are still on this version.

**Comment by Laktostolerant** [comment]
SlimeBro just stop... Get off github. You do nothing but spread toxicity.

**Comment by JurXeno** [comment]
> 1.12 isn't dead. I've seen mods that are still on this version.

It is dead, Forge no longer supports it, even if there are mods for it still, it's still dead.

**Comment by Phantom2909** [comment]
> 1.12 isn't dead. I've seen mods that are still on this version.

Nope, is dead. If forge doesn't support a version anymore, it's a dead version.

**Comment by MagmaSlime123** [comment]
Tell other mods to update then.

**Comment by JurXeno** [comment]
> Tell other mods to update then.

Fucks sakes my guy, just stop, you shouldn’t have made this issue in the first place if your doing 1.12.2.

**Comment by MagmaSlime123** [comment]
Here we go again. Toxic people.

**Comment by JurXeno** [comment]
You are the one causing all of this by saying something stupid dumb. So this is on you, not on us.

**Comment by Arkytek** [comment]
> Here we go again. Toxic people.

you are either a troll....
or you are incredibly entitled lol

**Comment by MagmaSlime123** [comment]
I'm not a troll.
