### ISSUE TITLE
[1.16.4][Compat]Dragon tries to kill every Aquaculture mob they see, causing massive lag

### ISSUE THREAD

**Issue by AxolotlAccount** [Alex-the-666/Ice_and_Fire#3234]
Description:  Dragons attack to all Aquaculture 2 mobs in the sea and it drops tick rate even on a Singleplayer world. All entities affects from this lag.

Ice and Fire Version: 2.1.3
Citadel Version: 1.5.2
Aquaculture 2 Version: 2.1.6

**Comment by Neko2n** [comment]
This happens to me as well, can confirm
