### ISSUE TITLE
Our server is crashing randomly 

### ISSUE THREAD

**Issue by philipstorrie7** [Alex-the-666/Ice_and_Fire#3235]
Hi guys We're playing on ATM6 version 1.3.3 and we're experiencing random crashes with the error "stackoverflow" We think its a conflict with some other mod and Iceandfire. I was hoping someone could help me by reading this crashlog and giving me some advice we really want to keep this mod over the rest as its leaps and bounds above the rest in quality and quantity. 

https://pastebin.pl/view/dafa0741

ps. I've asked on the ATM reddit and discord and got zero help thats why i've came here :)

**Comment by DaedalusGame** [comment]
Same issue here with a different pack (homebrewed), the server watchdog crashes the server anytime an ice and fire creature like a dragon is loaded for an extended period

**Comment by Coloradohusky** [comment]
How much RAM do you have on your server? Both @philipstorrie7 and @DaedalusGame, I'm just curious
