### ISSUE TITLE
Lightning Dragonsteel Sword Destroys Drops

### ISSUE THREAD

**Issue by jacksin125** [Alex-the-666/Ice_and_Fire#3236]
Issue: When I kill a mob with the lightning dragonsteel sword, the drops are destroyed

Version: 2.1.3 (1.16.4)

How to reproduce: Kill a mob with a lightning dragonsteel sword. I tried it with both a heavily enchanted and unenchanted sword, on cows, wither skeletons, and endermen.

Likely Cause: My guess is that the lightning triggers pretty much immediately after the drops should have spawned, thus instantly deleting them.

Possible Solution: Maybe you could check if the mob is already dead before spawning the lightning, and not spawn the lightning if it is? I think it would probably be harder to create a custom lightning entity that doesn't do damage to drops, but that would allow the lightning to always spawn which would look cooler. I don't know much about minecraft code or this mod's code, so I don't have any better ideas.

**Comment by mikuhl-dev** [comment]
Any reason this is closed? I am having this problem too. Was it fixed in a new version?
