### ISSUE TITLE
Code for some open issues.

### ISSUE THREAD

**Issue by tweakbsd** [Alex-the-666/Ice_and_Fire#3243]
Hey there, I'm a programmer by profession and minecrafter :-) and cause I'm loving your mod I started looking into your code and did some quick fixes to enhance gameplay.  These fixes are by no means an offense in anyway. Every contributer and especially you did a great job coding this mod and bugs are a normal outcome of an evolving codebase.  Hope to save you some time by posting a few fixes here:

- DragonBow not animating
  * ClientProxy.java - ClientProxy.setupClient() 
    add :
`
        IItemPropertyGetter pulling = ItemModelsProperties.func_239417_a_(Items.BOW, new ResourceLocation("pulling"));
        IItemPropertyGetter pull = (stack, worldIn, entity) -> {
            if (entity == null) {
                return 0.0F;
            } else {
                ItemDragonBow item = ((ItemDragonBow) stack.getItem());
                return entity.getActiveItemStack() != stack
                        ? 0.0F
                        : (stack.getUseDuration() - entity.getItemInUseCount()) / 20.0F;
            }
        };
        ItemModelsProperties.func_239418_a_(IafItemRegistry.DRAGON_BOW.asItem(), new ResourceLocation("pulling"), pulling);
        ItemModelsProperties.func_239418_a_(IafItemRegistry.DRAGON_BOW.asItem(), new ResourceLocation("pull"), pull);
`

- DragonBone Arrows not dealing correct damage
  *  - A constructor is missing a call to setDamage()
  * EntityDragonArrow.java 
`
    public EntityDragonArrow(EntityType typeIn, LivingEntity shooter, World worldIn) {
        super(typeIn, shooter, worldIn);
        this.setDamage(10.0F);  // fix
    }
`

- TideTrident has weird behaviour with loyalty after hitting an entity. Hits entity, falls on ground then comes back.
   * To fix this an accesstranformer.cfg entry is necessary:
`
public net.minecraft.entity.projectile.TridentEntity field_226571_aq_ # field_226571_aq_
` 

 - In EntityTideTrident.java 
  * onEntityHit() method we need to set the field corresponding to the one in access transformer. 
  `
// after this line:
DamageSource damagesource = DamageSource.causeTridentDamage(this, (Entity)(entity1 == null ? this : entity1));
// add this 
this.dealtDamage = true;  // fix

`

- This is not a fix but as an improvement I made Fire Dragonsteel fireproof like netherite in my version of the mod, 
which can easily be added like this, in IafItemRegistry.java 
 * Simply add a call to  Item.Properties.func_234689_a_()  for each item to be immune to fire. 

example:
`
public static final Item DRAGONSTEEL_FIRE_INGOT = new ItemGeneric("dragonsteel_fire_ingot", new Item.Properties().func_234689_a_()
`

- I also made fixes to Pixies, when they are tamed and you make them sit, leave the world and join again
  they don't sit anymore. They will even teleport to you if you made them sit in your base for example, go exploring, next time
you join the world they are where you are.
 But posting this fix here is a bit too much

- Dreadstone is missing stonecutting recipes which would be sweet
`
{
  "type": "minecraft:stonecutting",
  "ingredient": {
    "item": "iceandfire:dread_stone"
  },
  "result": "iceandfire:dread_stone_bricks_chiseled",
  "count": 1
}
`

`
{
  "type": "minecraft:stonecutting",
  "ingredient": {
    "item": "iceandfire:dread_stone"
  },
  "result": "iceandfire:dread_stone_bricks",
  "count": 1
}
`

`
{
  "type": "minecraft:stonecutting",
  "ingredient": {
    "item": "iceandfire:dread_stone_bricks"
  },
  "result": "iceandfire:dread_stone_slab",
  "count": 2
}
`

`
{
  "type": "minecraft:stonecutting",
  "ingredient": {
    "item": "iceandfire:dread_stone"
  },
  "result": "iceandfire:dread_stone_slab",
  "count": 2
}
`

`
{
  "type": "minecraft:stonecutting",
  "ingredient": {
    "item": "iceandfire:dread_stone_bricks"
  },
  "result": "iceandfire:dread_stone_stairs",
  "count": 1
}
`

`
{
  "type": "minecraft:stonecutting",
  "ingredient": {
    "item": "iceandfire:dread_stone"
  },
  "result": "iceandfire:dread_stone_tile",
  "count": 1
}

`

**Comment by BorisIsTheGuy** [comment]
what nice guy

**Comment by BugmanBugman** [comment]
I agree, this will be useful to alex

**Comment by kuroyure** [comment]
ty sooo much, you migth wanna make this a pr, btw, if its not asking too much, can you fix the trident not piercing through enemies like its description?

**Comment by tweakbsd** [comment]
@kuroyure
I didn't even recognize the trident should pierce through entities. So my fix is probably not right. But I'll look into it.

**Comment by kuroyure** [comment]
it has a tooltip, it describes its ability, some other bugs that need fixing include: bestiary not consuming pages, myrmex stinger blades dont deal poison dammage,(they should) hippocampi told to sit still move, trolls and stymphalian birds dont spawn, mausoleums cause deadlock. those are the ones i can remmember on top of my head.
ty for all the work, ppl like you are a blessing to i/f players
