### ISSUE TITLE
Invisible ghouls [1.16.4]

### ISSUE THREAD

**Issue by FurryApocalypse** [Alex-the-666/Ice_and_Fire#3244]
While entering mausoleum every ghoul spawned is invisible. Other mobs works fine. It seems to be happening only when spawned by mob spawner. I used egg on creative to check if it's also invisible  when spawned by egg but it works fine then (whole animation etc.). Maybe problem is coused by not showing up the animation when spawned by mob spawner (comming out from the ground seems to be deleted here).

**Comment by AlexModGuy** [comment]
fixed
