### ISSUE TITLE
Code for a few more small fixes. 

### ISSUE THREAD

**Issue by tweakbsd** [Alex-the-666/Ice_and_Fire#3258]
Thanks for implementin some of my fixes from Issue #3243 ! Hopefully it is okay I post some more here. 

If a dragon dies with armor on, it is not being dropped and gone forever. There is an empty **dropArmor()** method in
**"EntityDragonBase.java"** which could be implemented like this:

`
    public void dropArmor() {

        // NOTE: not sure if OFFHAND belongs in dropInventory() ?!?!
        EquipmentSlotType[] slotTypes = {EquipmentSlotType.HEAD, EquipmentSlotType.CHEST, EquipmentSlotType.LEGS,  EquipmentSlotType.FEET, EquipmentSlotType.OFFHAND};
        for (EquipmentSlotType slotType : slotTypes) {
            ItemStack itemStackForSlot = this.getItemStackFromSlot(slotType);
            if(!itemStackForSlot.isEmpty()) {

                this.entityDropItem(itemStackForSlot, 1);
                this.setItemStackToSlot(slotType, ItemStack.EMPTY);
            }
        }
    }
`

then in the following method:

`
public ActionResultType func_230254_b_(PlayerEntity player, Hand hand) {
...
 } else if (this.getDeathStage() == (lastDeathStage / 2) - 1 && IafConfig.dragonDropHeart) {
                    ItemStack heart = new ItemStack(this.getHeartItem(), 1);
                    ItemStack egg = new ItemStack(this.getVariantEgg(this.rand.nextInt(4)), 1);
                    if (!world.isRemote) {
                        this.entityDropItem(heart, 1);
                        if (!this.isMale() && this.getDragonStage() > 3) {
                            this.entityDropItem(egg, 1);
                        }
                    }

                    // added dropArmor()  before dragon transitions to skeleton phase
                    this.dropArmor();
                    // 
                    this.setDeathStage(this.getDeathStage() + 1);

                } else {
..
`

Scribe "Zombie-Villager" has no resource file, can be fixed easily. Copy **"scribe.png"** to 
**"resources/assets/iceandfire/textures/entity/zombie_villager/profession/scribe.png"**. I think the 
original texture fits the Zombie state well. 

Dragons attacking tamed entities with same owner should not be allowed. 

In **EntityDragonBase.java** add the following method:

`
    @Override
    public boolean shouldAttackEntity(LivingEntity target, LivingEntity owner) {

        // Maybe check if target is a dragon adn the type differs. 
        // If not matches still fall through to still allow Ice / Fire / Lightning Dragon to kill each other.

        if(this.isTamed() && target instanceof TameableEntity) {
            TameableEntity tamableTarget = (TameableEntity)target;
            UUID targetOwner = tamableTarget.getOwnerId();
            if(targetOwner != null && targetOwner.equals(this.getOwnerId())) {
                return false;
            }
        }
        return super.shouldAttackEntity(target, owner);
    } 

`

Many Entities do not render as sitting even so they are in that state when you leave and rejoin a world.
Is adding a pull ruquest open to anyone ? Never done one on github before, but I might look into that 
if it would help the mod and it's community.  

Here's a small perfomance fix in **"ClientProxy.java"** **spawnParticle()** method. Stop testing the
particle name against every possible value after it matches a value. Prevents a lot of unnecessary string 
comparisons. Doesn't help much but every bit counts since dragon are quite laggy for me. 

`
@OnlyIn(Dist.CLIENT)
    public void spawnParticle(String name, double x, double y, double z, double motX, double motY, double motZ, float size) {
        ClientWorld world = Minecraft.getInstance().world;
        if (world == null) {
            return;
        }
        // NOTE: tweakbsd performance optim else if's, otherwise 'name' would be checked against all possible values
        // on every method invocation.   
        net.minecraft.client.particle.Particle particle = null;
        if (name.equals("dragonfire")) {
            particle = new ParticleDragonFlame(world, x, y, z, motX, motY, motZ, size);
        }
        else if (name.equals("dragonice")) {
            particle = new ParticleDragonFrost(world, x, y, z, motX, motY, motZ, size);
        }
        else if (name.equals("dread_torch")) {
            particle = new ParticleDreadTorch(world, x, y, z, motX, motY, motZ, size);
        }
        else if (name.equals("dread_portal")) {
            particle = new ParticleDreadPortal(world, x, y, z, motX, motY, motZ, size);
        }
        else if (name.equals("blood")) {
            particle = new ParticleBlood(world, x, y, z);
        }
        else if (name.equals("if_pixie")) {
            particle = new ParticlePixieDust(world, x, y, z, (float) motX, (float) motY, (float) motZ);
        }
        else if (name.equals("siren_appearance")) {
            particle = new ParticleSirenAppearance(world, x, y, z, (int) motX);
        }
        else if (name.equals("ghost_appearance")) {
            particle = new ParticleGhostAppearance(world, x, y, z, (int) motX);
        }
        else if (name.equals("siren_music")) {
            particle = new ParticleSirenMusic(world, x, y, z, motX, motY, motZ, 1);
        }
        else if (name.equals("serpent_bubble")) {
            particle = new ParticleSerpentBubble(world, x, y, z, motX, motY, motZ, 1);
        }
        else if (name.equals("hydra")) {
            particle = new ParticleHydraBreath(world, x, y, z, (float) motX, (float) motY, (float) motZ);
        }
        if (particle != null) {
            Minecraft.getInstance().particles.addEffect(particle);
        }
    }

`

In **"PlayerRenderEvents.java"** is a TODO comment which will work like that:

`
import java.util.Map;
import net.minecraft.client.network.play.NetworkPlayerInfo;
import net.minecraft.client.entity.player.AbstractClientPlayerEntity;
import com.mojang.authlib.minecraft.MinecraftProfileTexture;

...

    @SubscribeEvent
    public void playerRender(RenderPlayerEvent.Pre event) {

        //  fixed rendering todo part

        if (event.getEntityLiving() instanceof AbstractClientPlayerEntity) {
                NetworkPlayerInfo info = ((AbstractClientPlayerEntity)event.getEntityLiving()).getPlayerInfo();
            if (info != null) {
                Map<MinecraftProfileTexture.Type, ResourceLocation> textureMap = info.playerTextures;
                if (textureMap != null) {
                    if (hasBetaCape(event.getEntityLiving().getUniqueID())) {

                        textureMap.put(MinecraftProfileTexture.Type.CAPE, betaTex);
                        textureMap.put(MinecraftProfileTexture.Type.ELYTRA, betaElytraTex);

                    } else if (hasRedCape(event.getEntityLiving().getUniqueID())) {

                        textureMap.put(MinecraftProfileTexture.Type.CAPE, redTex);
                        textureMap.put(MinecraftProfileTexture.Type.ELYTRA, redElytraTex);

                    } else if (hasBlueCape(event.getEntityLiving().getUniqueID())) {

                        textureMap.put(MinecraftProfileTexture.Type.CAPE, blueTex);
                        textureMap.put(MinecraftProfileTexture.Type.ELYTRA, blueElytraTex);

                    }
                }
            }
        }
        ...

}

`

That's all It got for small things. Hopefully it helps out a little bit.

**Comment by tweakbsd** [comment]
Man the github editor is broken, I checked everywher I used the code opening / ending quotes twice, but it still looks messed up :-(

**Comment by BugmanBugman** [comment]
Thank you so much !

**Comment by tweakbsd** [comment]
Another thing I wanted to mention is knockback resistance on armor. I saw code was added in the latest commit for armor 
to support it in the future on a per SET basis. There is an elegant way to add knockback resistance on a per SLOT basis 
in **"ItemDragonsteelArmor.java"** via adding this special method:

`

    @Nonnull
    @Override
    public Multimap<Attribute, AttributeModifier> getAttributeModifiers(@Nonnull EquipmentSlotType slot) {
        Multimap<Attribute, AttributeModifier> ret = super.getAttributeModifiers(slot);
        UUID uuid = new UUID(Registry.ITEM.getKey(this).hashCode() + slot.toString().hashCode(), 0);
        if (slot == getEquipmentSlot()) {
            ret = HashMultimap.create(ret);
            int reduction = material.getDamageReductionAmount(slot);

            // NOTE: round to lower number of -> reduction / 175 <- then make it a double
            // Results in 0.3 - 0.7 resistance depending on SLOT's damage reduction
            double knockbackResistance = Math.floor( ((double)reduction / 175.0) * 100) / 100.0D;
            String name = "Dragonsteel Knockback modifier " + this.slot;
            // NOTE: tweakbsd field_233820_c_ aka KNOCKBACK_RESISTANCE
            ret.put(Attributes.field_233820_c_,
                    new AttributeModifier(uuid, name, knockbackResistance, AttributeModifier.Operation.ADDITION));
        }
        return ret;
    }
`

As a sidenote I also wanted to mention that Troll armor is the perfect candidate for knockback resistance in my opinion.

**Comment by tweakbsd** [comment]
I also forget this quick fix, dread Torch on wall not rendering correctly.

**"dread_wall_torch.json"**


`
{
  "parent": "minecraft:block/template_torch_wall",
  "textures": {
    "torch": "iceandfire:block/dread_torch"
  }
}
`

**Comment by AlexModGuy** [comment]
you realize you can do a pull request right?

**Comment by tweakbsd** [comment]
That sounds great and what I wanted to hear. I was just not sure enough if pull request are a wanted thing or not. 
There is a PR in your repo but it's very old. 

I'll check out how PR are exactly working later this evening but expect one from me soon. 

Btw, keep up your great work !
