### ISSUE TITLE
1.16.4 Game hangs endlessly with Ice and Fire

### ISSUE THREAD

**Issue by footwanterfin** [Alex-the-666/Ice_and_Fire#3260]
Sometimes the game starts to hang with this mod. The log says "Can't keep up! Is the server overloaded? Running 3139ms or 62 ticks behind".

[2020-12-08-4.log](https://github.com/Alex-the-666/Ice_and_Fire/files/5661460/2020-12-08-4.log)

**Comment by Daejangnamu** [comment]
#3255
#3169 same

**Comment by lordcovale** [comment]
Similar, seems to happen more frequently when dragons use breath attacks.
