### ISSUE TITLE
Japanese language of 2.1 addition

### ISSUE THREAD

**Issue by B-Wither** [Alex-the-666/Ice_and_Fire#3263]
"block.iceandfire.ghost_chest": "呪いのチェスト",
  "block.iceandfire.graveyard_soil": "墓地の土",
  "block.iceandfire.graveyard_soil.desc": "夜間にゴーストをスポーンさせる",

  "item.iceandfire.ectoplasm": "エクトプラズム",
  "item.iceandfire.ghost_ingot": "ファンタズマルインゴット",
  "item.iceandfire.ghost_ingot.desc_0": "§6レアドロップ§r",
  "item.iceandfire.ghost_sword": "ファンタズマルブレード",
  "item.iceandfire.ghost_sword.desc_0": "ブロックを貫通する剣を飛ばす",
  "item.iceandfire.ghost_sword.desc_1": "飛ばされた剣が追加ダメージを与える",

  "entity.iceandfire.ghost": "ゴースト",

  "bestiary.ghost": "ゴースト",

  "advancements.iceandfire.kill_ghost.title": "Who You Gonna Call?",
  "advancements.iceandfire.kill_ghost.description": "ゴーストをバスターする",

**Comment by BugmanBugman** [comment]
I believe this should be a pull request

**Comment by B-Wither** [comment]
I'm sorry, I'm ignorant of github and I don't know how to do it in detail.
I've tried it before, but it didn't work well.
