### ISSUE TITLE
[1.15.2]bestiary and lectern bugs

### ISSUE THREAD

**Issue by Late-Night** [Alex-the-666/Ice_and_Fire#3272]
in version 2.1.0 the lectern only visually consumes pages(if you click the page slot, it gives you the pages back) , meaning you only need 3 pages to unlock the whole thing
and the bestiary's gui doesn't show up(but strangely can still be interacted with)

**Comment by MemeLord32** [comment]
I have encountered the issue with the lectern giving you the pages back after you use it as well in the latest version.
