### ISSUE TITLE
Server fatal exception error, possibly in combination with Good Nights Sleep mod

### ISSUE THREAD

**Issue by Bidgam** [Alex-the-666/Ice_and_Fire#3279]
Ice and Fire was mentioned in the error report, though I'm honestly not entirely certain the source of the issue.

Fatal exception error related to some sort of dimension type function on the latest 1.16.4 and Forge 35.1.12

<img width="1314" alt="IceFireSleepcrash" src="https://user-images.githubusercontent.com/71402861/101970690-846fab00-3bf1-11eb-8d35-8c9d37ccf6dd.png">

**Comment by BeepoWuff** [comment]
Resolved by 7ede5e14826201f2018b67f0650b03eab2ea516c. Should be fixed in 2.1.5.
