### ISSUE TITLE
1.16.4 (2.1.4) Extreme Spawning (Compatibility Issue with BOP and/or BYG)

### ISSUE THREAD

**Issue by BeanZephyron** [Alex-the-666/Ice_and_Fire#3280]
I am playing this mod with both Biomes 'O Plenty and Oh The Biomes You'll Go, and the spawn rates for all creatures and structures are extremely high. I have encountered ice dragon nests in warm areas, such as plains biomes, and nests that have spawned right next to each other. Pixie villages, mausoleums, gorgon temples, etc. spawn frequently regardless of any biome, including the ocean. I am not sure which out of the three mods is causing this to occur, but I have had unique structure spawning results with BYG and Ice and Fire before in previous versions.

**Comment by smoothuk** [comment]
I noticed sometimes dragon caves are absolutely rammed with vanilla hostile mobs.  Have you tried deleting and regenerating the configs?

**Comment by BeanZephyron** [comment]
I did not. Just tried it, and it worked! Thank you!
