### ISSUE TITLE
Underground Dragons in Oceans

### ISSUE THREAD

**Issue by Wolfstar1010** [Alex-the-666/Ice_and_Fire#3283]
Hello, Noticed that dragon caves were high enough to appear above ground in deep ocean biomes. Found 3 right next to each other. I'm not sure if this is an issue but I thought I'd share in case. They wake up when a player get's too close as well. BOP and BYG are also installed.

![image](https://user-images.githubusercontent.com/66505198/101976140-65344600-3c10-11eb-9725-5173480b9606.png)

**Comment by smoothuk** [comment]
Can confirm this.  Quite often now I see very large dragons rising from the ocean while I'm sailing.. pretty sure that shouldn't happen.  Probably best to disable them from spawning in ocean biomes for now.

**Comment by drakray** [comment]
It should also be noted that the caves are often chopped as seen in the picture; in fact, using Minutor, I found that most if not all dragon cave have missing part of some sort
