### ISSUE TITLE
Mod not loading

### ISSUE THREAD

**Issue by dalduros** [Alex-the-666/Ice_and_Fire#3286]
I'm running all the mods 6 on a server hosted by Bisect, single and multiplayer is having the same issue where no creatures, structures, nests or anything from Ice and Fire generates. I restarted, re-installed, reset the over world, nether and Other, I travelled 3k blocks from 0,0 and still no creatures
 I can manually spawn them in with their spawn eggs but that's it.

I noticed in the recent change log there's a reference to a config to whitelist dimensions but I can't locate how to access this configuration panel..what have I done wrong?

**Comment by Catediali** [comment]
I’m having a similar issue. I’m using the 1.16.3 version of both Ice and Fire and Citadel, and no matter how far I travel from spawn there are no Ice and Fire mobs or structures. I’m in single player though.
