### ISSUE TITLE
Ice dragon roosts not obeying Dangerous World Gen limit

### ISSUE THREAD

**Issue by Bidgam** [Alex-the-666/Ice_and_Fire#3289]
1.16.4 on Forge 35.1.4 using iceandfire-2.1.4-1.16.4

I have Dangerous World Gen Dist From Spawn at 6400, yet I see Ice Dragon roosts spawning at 4355 x 5739 and even closer in some cases it seems.

**Comment by aetherknight** [comment]
(4355, 5739) is more than 6400 blocks away from (0, 0) (assuming `BlockPos` uses the pythagorean theorem to compute distances):

```
sqrt(4355^2 + 5739^2) => 7204.3144018011
```

https://github.com/Alex-the-666/Ice_and_Fire/blob/1.16.3/src/main/java/com/github/alexthe666/iceandfire/world/IafWorldRegistry.java#L232-L236
