### ISSUE TITLE
Ice & Fire 2.1.4 for 1.16.4 - Forge: 35.1.10 - List of Myrmex related bugs

### ISSUE THREAD

**Issue by Jusey1** [Alex-the-666/Ice_and_Fire#3290]
So, the newly released update which added some much needed bugfixes for dragons and improvements to dragons with multithreading did a lot of work. Multithreading was also added to Myrmex but I believe this change completely broke Myrmex as a whole and thus there is a list of new bugs for just them... So, I am here to report them all I have found from my testings.

1. Crash on Queen hatch. This is an old bug actually but still gonna list it here. Whenever a player hatches a Myrmex Queen egg, the game will crash. I do believe it only crashes the client however, not the server... In singleplayer, it will crash and when you reload the save then the Queen will hatched and before 2.1.4, would act as expected...

2. Speaking of hatching... Despite having permanent 100 reputation with eggs you have hatched... They will be hostile to you. Actually, ALL MYRMEX COLONIES will ALWAYS be hostile to the player no matter how much reputation you have with them...

3. And speaking of reputation... It seems, despite the hostility or reputation level you have. You also can always trade with the Myrmex and use the Myrmex staff on them like you had high reputation with them. Which is kinda good I guess? This means you can just trap them and still trade with them safely as long as they cannot reach you to attack you.

4. Myrmex Workers are unable to detect dropped items. They can still detect blocks like grass, cactus, and so on. So they will pick up those but they cannot detect dropped items. This means you cannot even get your reputation up with them in survival mode anyways since they won't be able to pick up your resin chunks...

5. Myrmex causes severe lag while in combat with each other... I figured this in a singleplayer world, mind you, by spawning three workers while I was testing the workers ability to pick up items and they started fighting, which makes sense as two were jungle and one was desert... The moment they were in combat though? Game was lag spiking a lot until two of them were dead. I spawn in a soldier next who cause lag spikes once it was fighting a worker but wasn't while attacking other mobs... So this might just only be happening while Myrmex are fighting each other. This could also apply to dragons potentially perhaps?

6. Myrmex eggs still despawn on chunk unload/reload. (Old bug but will still list here).

7. Myrmex misses a lot? This is odd. A lot of time, the Myrmex will be essentially on top of it's target and still just miss around 60 to 70% of the time. At least most of them do. I think the grab attack from sentinels don't miss at all.

I believe that is all of them I have found... The Myrmex are honestly my favorite mob in the mod as they are a very complex and fascinating mob to just watch and hang out with. However, due to them being essentially broken this patch then I have to disable them until a lot of these are fixed. I do think a lot of this happens due to multithreading being given to them, but beyond that... No idea. Hope to see them fixed up quite a bit for 2.1.5.

**Comment by RangeCreed** [comment]
To add to this:

Myrex seem to be able to path ontop of fence and then get stuck. Observed some myrex near a village and they where doing circle loops on a fence after getting stuck trying to pathfind to a horse.
