### ISSUE TITLE
Players are in different heights when riding different stage dragons

### ISSUE THREAD

**Issue by Alex-the-666** [Alex-the-666/Ice_and_Fire#33]

**Comment by TheMinecraftOverlordYT** [comment]
This happens with Pixelmon also; Since it's the same entity (I assume) you would probably have to use <nbt? don't know if you can do that I've never really used nbt too much but it sounds right>, or make every stage a separate entity.

**Comment by Alex-the-666** [comment]
Please don't comment here - these are development issues.
