### ISSUE TITLE
still cant find dragons in the other

### ISSUE THREAD

**Issue by ALDBy** [Alex-the-666/Ice_and_Fire#3308]
ive been looking for them for like half an hour

i found cyclopses and cockatrices but still no dragons

**Comment by desagas** [comment]
i am 1 million percent positive that this is not an ice and fire issue. you should look at the change log for the pack that you are playing. hahah.

**Comment by Lashriel** [comment]
I think they restrict dragons specifically to only spawning past (+/-)3000,(+/-)3000. You have to go *far* to find anything.

Either way, this is an ATM6 issue.

**Comment by desagas** [comment]
Exactly. I believe that most configs are set that way to prevent dragons from destroying spawn.
