### ISSUE TITLE
Dragons are small and named and wont drop skeletons

### ISSUE THREAD

**Issue by Presyon** [Alex-the-666/Ice_and_Fire#3311]
I'm on All the Mods 6 and all the dragons I've found are small, named and after spending a year killing it doesn't drop anything. Anyone have a fix?

![Screenshot 2020-12-17 132800](https://user-images.githubusercontent.com/76184727/102545895-bbb7df00-406b-11eb-99dc-b80ab6770b61.png)

**Comment by CaspianMacky** [comment]
That looks like an Apotheosis miniboss.

**Comment by Presyon** [comment]
So am i screwed with the ice and fire mod since i cant collect dragon bones?

**Comment by Lashriel** [comment]
All The Mods shoves all Ice&Fire content into the "Other" mining dimension it adds, effectively gating all of Ice&Fire behind Allthemodium.

You can still get dragon bones, just gotta do it in that other dimension.

If you can still get Manuscripts (idk, they might be dungeon loot), a Scribe villager will still sell you dragon bones and other Ice&Fire stuff if you level them up. Their job site is a bestiary lectern.
