### ISSUE TITLE
fairies keep following you

### ISSUE THREAD

**Issue by BugmanBugman** [Alex-the-666/Ice_and_Fire#3319]
![2020-12-19_17 09 34](https://user-images.githubusercontent.com/40730042/102706026-d056cb80-4253-11eb-8bbd-3172ab97c580.png)

**Comment by Lashriel** [comment]
That's them trying to steal from your empty inventory - they'll keep trying until they find something not in your hotbar. Should probably be a cooldown on the steal-checks.

**Comment by BugmanBugman** [comment]
I agree, you cant really outrun them without killing them
