### ISSUE TITLE
Cockatrice seems to crash me, likely a mod incompatibility.

### ISSUE THREAD

**Issue by Awoo-desu** [Alex-the-666/Ice_and_Fire#3326]
Recreated by simply fighting a cockatrice. I'm not good at reading crash logs, so I'm just guesstimating. 

Forge 35.1.13
IAF 2.1.4
1.16.4 game version.

https://pastebin.com/JQxarmzt

**Comment by BugmanBugman** [comment]
"ava.lang.IllegalArgumentException: Can't find attribute botania:pixie_spawn_chance"

It's botania

**Comment by Awoo-desu** [comment]
Ah alrighty. Weird that it acted up with ice and fire's pixies too.
