### ISSUE TITLE
Weird egg behavior

### ISSUE THREAD

**Issue by GatoLeyo** [Alex-the-666/Ice_and_Fire#3328]
The hippogryph, death worm, giant death worm and cockatrice eggs have a weird behavior when thrown.
It depends on the world but hte most common patters are the respective creature appearing 10-20 to the east (mostly with hippogryphs), the eggs being thrown up to the sky when you are aiming somewhere else (mostly worms and cockatrice).
Also the hippogryph egg doesn't render when thrown but im unsure if that is intended or not (since idk if im throwing an egg or just putting one and the hippogryph just appears far away)

**Comment by KamikazePigeon** [comment]
I've also had this issue. It's quite annoying, especially because Cockatrice become dangerous to pets when left alone, and if you can't find them to tame them... :(

**Comment by BeepoWuff** [comment]
These issues should be resolved in 2.1.5. I didn't notice any issues with cockatrice / rotten eggs in my testing so please let me know if you're still having trouble.
