### ISSUE TITLE
Citadel makes End remastered mod unplayable

### ISSUE THREAD

**Issue by TheShellPepper** [Alex-the-666/Ice_and_Fire#3331]
So I have this mod in a modpack, its called End Remastered [here](https://www.curseforge.com/minecraft/mc-mods/endremastered) 
 What it does is change how getting to the end works, instead of stronghold, you collect different eyes from structures in MC. Once you collect the different eyes to go to a castle and insert them there to go to the end. So here's the problem

One of these eyes are found in mineshafts. I may not have looked hard enough but I've yet to find them. you see when I was making the modpack I included Ice and Fire along with Wyrmroost. I googled them to see if they were compat with eachother and also went to the wyrmroost discord. They said they are mostly compat except one thing, they said citadel wipes mineshaft chests. They said it was nothing wyrmroost was doing and told me to talk to citadel people. id honestly rather have ice and fire over wyrmroost but i still want it to be playable in survival. does citadel change mineshaft chest gen? Can you please look into it for the next update. thank you very much for your time and effort. any of your mods are great.

simplified version: mineshafts wiped, which mods causes that. citadel, EM, or wyrmroost.

**Comment by kodabeer** [comment]
citadel does not remove mineshaft chests, I can vouch for this as I've found them in mineshafts with citadel installed.

**Comment by TheShellPepper** [comment]
i wasnt saying they removed the chests, im referring to the loot inside.
