### ISSUE TITLE
Gorgon's dungeons are always flooded, suggestions is to change a biome other than beach as a mountain biome

### ISSUE THREAD

**Issue by FORJATARTARO** [Alex-the-666/Ice_and_Fire#3337]

**Comment by TheBv** [comment]
This is due to introduction of the water logging feature. Could be fixed by just making sure that stairs etc. aren't waterlogged.
I'll have a go at it.
Actually this is an error in with minecraft that will be fixed in the next version: https://bugs.mojang.com/browse/MC-130584
