### ISSUE TITLE
forge ore tags 1.16.4

### ISSUE THREAD

**Issue by yyttuuyy** [Alex-the-666/Ice_and_Fire#3346]
ice and fire ores and ingots contain no way to process without oretag

**Comment by garyyo** [comment]
This is causing issues with Creators-of-Create/Create#633

**Comment by aetherknight** [comment]
I've worked around this for myself using a CraftTweaker script:

```zs
// Add Ice and Fire's ores to the right tags, so they can be processed by other mods.

<tag:forge:ores>.addItems([<item:iceandfire:copper_ore>]);
<tag:forge:ores/copper>.addItems([<item:iceandfire:copper_ore>]);

<tag:forge:ores>.addItems([<item:iceandfire:silver_ore>]);
<tag:forge:ores/silver>.addItems([<item:iceandfire:silver_ore>]);

<tag:forge:ores>.addItems([<item:iceandfire:sapphire_ore>]);
<tag:forge:ores/sapphire>.addItems([<item:iceandfire:sapphire_ore>]);

// Note the typo in the ore's name
<tag:forge:ores>.addItems([<item:iceandfire:amythest_ore>]);
<tag:forge:ores/amethyst>.addItems([<item:iceandfire:amythest_ore>]);
```

Something similar could probably be handled with KubeJS, and I suspect it should be easy to fix in the mod itself or with a datapack.

**Comment by AbacusOperator** [comment]
Also ingots, nuggets and storage blocks also need forge tags.

**Comment by pwlgrzs** [comment]
> 
> 
> I've worked around this for myself using a CraftTweaker script:
> 
> ```zenscript
> // Add Ice and Fire's ores to the right tags, so they can be processed by other mods.
> 
> <tag:forge:ores>.addItems([<item:iceandfire:copper_ore>]);
> <tag:forge:ores/copper>.addItems([<item:iceandfire:copper_ore>]);
> 
> <tag:forge:ores>.addItems([<item:iceandfire:silver_ore>]);
> <tag:forge:ores/silver>.addItems([<item:iceandfire:silver_ore>]);
> 
> <tag:forge:ores>.addItems([<item:iceandfire:sapphire_ore>]);
> <tag:forge:ores/sapphire>.addItems([<item:iceandfire:sapphire_ore>]);
> 
> // Note the typo in the ore's name
> <tag:forge:ores>.addItems([<item:iceandfire:amythest_ore>]);
> <tag:forge:ores/amethyst>.addItems([<item:iceandfire:amythest_ore>]);
> ```
> 
> Something similar could probably be handled with KubeJS, and I suspect it should be easy to fix in the mod itself or with a datapack.

Hi @aetherknight , could you please advise how the whole .zs file should look like in order to make this work?
