### ISSUE TITLE
[1.16.4] IaF 2.1.4: "Dangerous World Gen Dist Seperation" not implemented?

### ISSUE THREAD

**Issue by aetherknight** [Alex-the-666/Ice_and_Fire#3349]
Minecraft 1.16.4
Forge: 31.1.15, but saw it with 31.1.0 too
Ice and Fire: iceandfire-2.1.4-1.16.4.jar

Once I get away from the world spawn, I run into an unusually dense number of dragons. I have encountered multiple dragon caves right next to each other, and there are often a lot of dragon roosts all fairly close to each other (sometimes within a few chunks of each other).

I have observed this on multiple test worlds as well, both for fire and ice dragons.

I dug into the code a little, and it looks like `IafWorldRegistry.isFarEnoughFromDangerousGen()` is hard-coded to always return true on the 1.16.3 branch (there is no 1.16.4 branch):

https://github.com/Alex-the-666/Ice_and_Fire/blob/1.16.3/src/main/java/com/github/alexthe666/iceandfire/world/IafWorldRegistry.java#L303-L315

```java
    public static boolean isFarEnoughFromDangerousGen(IWorld world, BlockPos pos) {
        /*boolean canGen = true;
        IafWorldData data = IafWorldData.get(world.getWorld());
        if (data != null) {
            BlockPos last = data.lastGeneratedDangerousStructure;
            canGen = last.distanceSq(pos) > IafConfig.dangerousWorldGenSeparationLimit * IafConfig.dangerousWorldGenSeparationLimit;
            if (canGen) {
                data.setLastGeneratedDangerousStructure(pos);
            }
        }
        return canGen;*/
        return true;
    }
```

**Comment by Syrikal** [comment]
That would explain this, where I found six dragons within render distance of each other:
![2020-12-28_16 36 18](https://user-images.githubusercontent.com/76715986/103254893-cf592480-494c-11eb-9e03-3582006f07f7.png)
(the sixth is a small green one above ground, which spawned in a roost out of frame.)

**Comment by aetherknight** [comment]
It looks to me like @TheBv 's PR should fix this, once it is released.
