### ISSUE TITLE
[1.16.4] Dragon not recognizing Dragonforge again

### ISSUE THREAD

**Issue by ongesucc** [Alex-the-666/Ice_and_Fire#3350]
I successfully completed a dragonforge; however, after the first use, the dragon now ignores it and refuses to power it. I have tried rebuilding it in a different location and restarting my game. It will not acknowledge the forge. Even when I manually try breathing fire, it doesn't enter the aperture.

**Comment by Lashriel** [comment]
The dragonforge is *extremely* finicky in general. I've gotten my dragon to recognize it in all of the following ways at various times:

1. Moving the dragon around for half an hour until I found a single-pixel area where it worked.
2. Breaking the aperture and core, replacing both.
3. Taking items out and putting them back in.
4. Bringing the forge up 1 block from the ground.
