### ISSUE TITLE
The entirety of the config files on 1.16 -> 1.16.4 being completely useless.

### ISSUE THREAD

**Issue by SelkeGore** [Alex-the-666/Ice_and_Fire#3351]
In both singleplayer worlds and on servers, the entirety of the configuration files do absolutely nothing. You cannot edit mob health, damage, spawnrates, spawn locations, nor tool data, etc. The entire thing is useless.

**Comment by Mikebobs** [comment]
Works fine for me, Dragons are now running around with 3 times the health they had before, taking a solid 10 minutes of bow shooting to take down. 

Spawn rate was severely reduced by editing as well.

**Comment by Nick-McKay** [comment]
@Mikebobs really? Because modifying armor and weapon damage on my 1.16.4 instance doesn't do anything

**Comment by TheBv** [comment]
It works for everything except items I'm pretty sure.
The config file itself is being read correctly but the items and their damage/armor values get registered before the config file gets loaded. Sadly that's the way forge handles things so there's no easy/good way around it.

**Comment by Nick-McKay** [comment]
> It works for everything except items I'm pretty sure.
> The config file itself is being read correctly but the items and their damage/armor values get registered before the config file gets loaded. Sadly that's the way forge handles things so there's no easy/good way around it.

So would the only way for me to adjust the weapon damage for the sake of my modpack balance involve me just manually changing the source files and building the jar myself?

**Comment by TheBv** [comment]
That would be one way to do it currently [this](https://github.com/Alex-the-666/Ice_and_Fire/blob/1.16.3/src/main/java/com/github/alexthe666/iceandfire/IafConfig.java) would be the file should also be fine if only the server has the updated one I think. I tried finding some ways to get around it but I haven't been successful in doing so.
