### ISSUE TITLE
Server Crash from Dragon pathfinding issue (Ice and Fire 1.2.4 for MC 1.16.4)

### ISSUE THREAD

**Issue by Assasingus14** [Alex-the-666/Ice_and_Fire#3352]
Here are the crash logs from my server. From what I gather it has something to do with the dragon pathfinding and flight. 

[crash-2020-12-27_23.07.14-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5745575/crash-2020-12-27_23.07.14-server.txt)
[crash-2020-12-27_23.03.35-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5745576/crash-2020-12-27_23.03.35-server.txt)

**Comment by 17kisern** [comment]
I also have been noticing the latest 2.1.4 causing 15 second lag spikes

**Comment by Marfjeh** [comment]
Also have the same Problem. I do however got a spark profiler report.

Maybe this helps

https://spark.lucko.me/#7WciL4rfGd

**Comment by rd-morales** [comment]
Having same issues as well on server. Happens in constantly in multiple areas. Here's all the crash reports I've saved:

[crash-2020-12-28_18.11.17-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5752951/crash-2020-12-28_18.11.17-server.txt)
[crash-2020-12-28_18.17.16-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5752952/crash-2020-12-28_18.17.16-server.txt)
[crash-2020-12-28_18.26.26-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5752953/crash-2020-12-28_18.26.26-server.txt)
[crash-2020-12-28_18.04.05-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5752954/crash-2020-12-28_18.04.05-server.txt)
