### ISSUE TITLE
[Suggestion] Config option to mute certain mobs

### ISSUE THREAD

**Issue by cimex749** [Alex-the-666/Ice_and_Fire#3362]
A config option to mute (or at least mute jarred/tamed/etc. mobs), such as Cockatices and pixies so that there isn't intense noise in a base (i.e. small army of cockatrices or a pixie dust farm).

**Comment by TimeSlinky** [comment]
I have a few pixies and their giggles are driving me nuts. A mute option for certain mobs would be greatly appreciated.
