### ISSUE TITLE
(1.16.4) Pixies In a Jar can be heard in a 20 Block or more radius around the pixie from max world hight up the to bottom 

### ISSUE THREAD

**Issue by Maxi90909** [Alex-the-666/Ice_and_Fire#3365]
Placed Jar of Pixie and I go to my crafting talbe ( arround 20 blocks away from the Pixie in the Jar) I still hear the sounds of the pixie then I tested the Tide tirdent in the rain around my House and Even 200 Blocks up I still hear the pixie sounds

**Comment by Daejangnamu** [comment]
1. Jar rendering bug
https://youtu.be/WLHcU7gpDRs


2.Sound bug 
https://youtu.be/XkcI7DFXc0I

**Comment by Maxi90909** [comment]
If you have already known about this bug sorry for posting it here again I didn't know these videos existed
