### ISSUE TITLE
can i make a suggestion

### ISSUE THREAD

**Issue by Manglefan** [Alex-the-666/Ice_and_Fire#3368]

**Comment by Carro1001** [comment]
no

**Comment by Manglefan** [comment]
where can i cause i have a really cool idea

**Comment by Carro1001** [comment]
ice and fire suggestions github, also please close this issue

**Comment by Manglefan** [comment]
can you send me the link for it
and i will

**Comment by Carro1001** [comment]
https://github.com/Alex-the-666/Ice-and-Fire-Suggestions/issues
