### ISSUE TITLE
Ticking Entity crash when getting near dragons.

### ISSUE THREAD

**Issue by Hail99wasd** [Alex-the-666/Ice_and_Fire#3371]
Crash on multiplayer server, only happens to _some_ clients. Like, my friend is just fine. 

[crash-2021-01-01_16.25.43-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5759458/crash-2021-01-01_16.25.43-client.txt)

**Comment by TheBv** [comment]
Can you possibly provide more information?
The crash mentions a fire dragon so any details about the age of it and if it's tamed or something would be really helpful in recreating the issue.

**Comment by Hail99wasd** [comment]
> Can you possibly provide more information?
> The crash mentions a fire dragon so any details about the age of it and if it's tamed or something would be really helpful in recreating the issue.

Alas I don't know much about the dragon in question, it's not tamed I can say that for certain. And I have been able to approach other dragons without crashing. It's most likely a naturally generated dragon. I could try to have my friend investigate the area where I crashed to find out more. I think I'll do that and send whatever info I get.

**Comment by Hail99wasd** [comment]
> > Can you possibly provide more information?
> > The crash mentions a fire dragon so any details about the age of it and if it's tamed or something would be really helpful in recreating the issue.
> 
> Alas I don't know much about the dragon in question, it's not tamed I can say that for certain. And I have been able to approach other dragons without crashing. It's most likely a naturally generated dragon. I could try to have my friend investigate the area where I crashed to find out more. I think I'll do that and send whatever info I get.

Went by the area where the crash had occurred and I was fine. My friend mentioned he found the skeleton of either a T5 dragon or a T3 dragon in that area (cant remember which). Unsure if that was the culprit.
