### ISSUE TITLE
Dragon wiggling continuously.

### ISSUE THREAD

**Issue by TerranE5** [Alex-the-666/Ice_and_Fire#3379]
When I installed this mod. the first thing I did was test it on creative mode, and tamed a dragon. One thing that I noticed after that is when every time I ride it, it constantly wiggles its butt and head like its trying to do the jiggly dance that I see in a snake strangling a person to death. This is the same issue.

You might be able to replicate the problem simply by looking sideways, left and right. I don't know if it's just my computer or is it a code error.

Oh, and also this applies to other flying mobs as well.

**Comment by Syrikal** [comment]
I have this too. Usually they twitch their tail towards their head, but sometimes the head jerks around too.
