### ISSUE TITLE
Tide Guardian Leggings Visual error

### ISSUE THREAD

**Issue by 78373** [Alex-the-666/Ice_and_Fire#3387]
The leggings don't appear on your avatar (they do appear in your inventory avatar though).

**Comment by 78373** [comment]
1.16.4

**Comment by TheBv** [comment]
Works fine for me (you can see my avatar updating in the background)

https://user-images.githubusercontent.com/12676257/103719606-aa5a5680-4fc9-11eb-9539-956a64e8af7c.mp4

**Comment by 78373** [comment]
You're in 1.16 latest version, correct? Hm, well thank you for the response. If its just me, that means another mod is causing the error.
