### ISSUE TITLE
1.16.4 Crash after loading Savegame

### ISSUE THREAD

**Issue by SidosX** [Alex-the-666/Ice_and_Fire#3393]
Hey
I was playing a while (~30h) everything was fine until i explored the world with my hippogryph, i got down near a ice dragon nest and get of the animal then the game freezed and crashed. now every time i want to reload the world with ice and fire ( i tried only ice and fire and citadel) it crashes. with every other mod minecraft works fine. also with every other save it works accept my main world not...
After the game closed i get the error:0 from the launcher.
if i pause the game immediately after loading in, minecraft keeps running.
when i disable ice and fire load back in go to an other place and then load the mods again it works fine.
but i want my stuff back cheating isnt an option there was too much to remember and i just dont want to run in this issue in the future...
Crash Report:
[crash-2021-01-07_16.35.14-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5782849/crash-2021-01-07_16.35.14-server.txt)

forge and mod versions should be in the report.
i hope you got time to help me solving this problem, i just wont play without ice and fire its such a great mod ^^

Have a nice Day, 
SidosX

**Comment by TheBv** [comment]
This happens if a dragon used his shake prey attack on a villager (possibly any entity with a more complex ai) and that villager then for some reason wants to go to his bed, probably because it's night time.
I'll look into if I can possibly fix this issue permanently. But if you can maybe make it daytime in your world without loading it things should hopefully work again.

**Comment by SidosX** [comment]
okay i tried that but its not working i used the command /time set day and walked up to the dragon again crash...
at least i can flee from this issue for now by setting the render distance to 2 chunks...
is there a way to desable this attack that causes the issue?

for me it looks like the same but idk ^^
report:
[crash-2021-01-07_18.24.24-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5783045/crash-2021-01-07_18.24.24-server.txt)

thank u for the fast answer u are doing a great job :D
