### ISSUE TITLE
Crash After Fighting A Fire Dragon In A Village

### ISSUE THREAD

**Issue by KamikazePigeon** [Alex-the-666/Ice_and_Fire#3396]
This may be the same as #3394 but I'm posting it anyway for more info. I know very little about code, but the errors are very similar.

Opened up a game after freshly installing Ice and Fire to a mod list that was previously working. Went into Creative, found a Fire Dragon, starting beating on it. It was breaking the villager houses like dragons do, and then suddenly the game just crashed.

Lotta mods installed, but this crash only happened after adding Ice and Fire and it didn't reference any of the mods that I saw, so...

[crash-2021-01-07_16.40.09-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5784811/crash-2021-01-07_16.40.09-server.txt)

**Comment by ghost** [comment]
Same issue here.
