### ISSUE TITLE
Tamed dragon dying for nothing. [randomly]

### ISSUE THREAD

**Issue by bryan161** [Alex-the-666/Ice_and_Fire#3399]
Well, they randomly teleport to a near location. And when that happens they get some damage.  If I'm not there for heal it, then they eventually die and this message appears: death.attack.Stucl-damage.

**Comment by pwadsworth** [comment]
Similar problem. Tamed baby lightning dragon teleported and died for no reason during a storm. Received message "kill\stuck-kill"

**Comment by TheBv** [comment]
Where the dragons sitting or where they chained?
There's some settings in the pathfinding currently that make it so if the entity is stuck they eventually teleport to their target.
That should only happen when they are following you/wandering and also when they can't reach their target.
If they were chained It's probably worth checking if the entity was chained and then not applying these options.
If it happens while they are sitting I'd do some more investigating.

**Comment by bryan161** [comment]
Just happens when the dragons are wandering, yes. But even when they are wandering and sleeping they teleport to a near location randomly and I don't know why they get hurt in that "teleport process". So the only thing that I can make for dragons don't die  with this random teleport is let it then sitting. Oh, and no, there is any dragon chained. I've never chained my dragons

**Comment by TheBv** [comment]
Thanks that helps a ton!
There's a setting currently active that makes them get hurt if they get "stuck". Which I think is set because some of the code for the pathfinding is based on the minecolonies project and it makes sense to do it there. It makes sense for most entities just not for tamed or special ones. 
I'll look into how to properly fix it.

**Comment by bryan161** [comment]
Thanks, man. I'll be waiting with my sittings dragons JAJA
