### ISSUE TITLE
1.2.1-1.11.2 Dragon Duplication with horn and server

### ISSUE THREAD

**Issue by kreezxil** [Alex-the-666/Ice_and_Fire#340]
I player of mine reported that he managed to duplicate his dragon twice so that now he has three tamed dragons when he should only have one.

Here are his words:
```
CMooney05 MoDz: All I did was keep re-logging because of how laggy it is. So first I died and immidetly quit because I had to leave and that duplicated my horn w/the dragon inside. Then I re-logged and a douplicate Of My dragon was on my roof and now I can ride it so I have 3 ice and no fire
```
If you would like to chat with him on my Discord server you can do so directly with https://discord.gg/yyaNqnv

**Comment by AlexModGuy** [comment]
fixed
