### ISSUE TITLE
[Compatibility] Common Forge OreDict tags missing from ores

### ISSUE THREAD

**Issue by Tsunamori74** [Alex-the-666/Ice_and_Fire#3401]
All of your metals and gemstones are properly tagged, but the ores are not, which makes them unprocessable by other mods that would otherwise be able to (create, immersive engineering, etc).

**Comment by Daejangnamu** [comment]
1.16.4-2.1.5 version use ?

**Comment by Tsunamori74** [comment]
Yes, updated 2 hours ago.
