### ISSUE TITLE
Ice and Fire 2.15-1.16.4 Hippocampus

### ISSUE THREAD

**Issue by SoakReam** [Alex-the-666/Ice_and_Fire#3409]
Newest version of the mod broke being able to ride a tamed hippocampus. As soon as I mount a hippocampus it immediately throws me off, not letting me be able to ride. It happens on single player and on server. It lets me ride on land but as soon as I go under water it throws me off.

**Comment by TheBv** [comment]
Could you possibly upload the log files? I tried riding the hippocampus and I didn't have any issues so I don't really have any idea what could be causing the issue.

**Comment by SoakReam** [comment]
The log files don't show anything. I tested it further and it doesn't work for me on any forge version past 1.16.4-35.1.28. In forge changelog for 35.1.29 there is "Fix entities not correctly being able to be ridden under water.". Which I think is what broke it for me as any earlier forge version works. I can still post the log file if you want. I'm using latest Ice and Fire and Citadel on forge 1.16.4-35.1.36

**Comment by TheBv** [comment]
Alright that's an interesting fact the default forge version for the project (when developing for it) is still one from 1.16.3 so that's probably why I didn't experience the issue I'll look into it tomorrow!
