### ISSUE TITLE
Hippogryph Server Crash

### ISSUE THREAD

**Issue by WenXin20** [Alex-the-666/Ice_and_Fire#3410]
`Minecraft v1.16.4`
`Forge v35.1.36`
`Ice & Fire v2.1.5`

Hippogryphs seem to crash my server, going back to the previous version didn't stop the crash.
[Crash Report](https://gist.github.com/WenXin20/54f390cd38bf666bd6b5afbfdfdd63da)

**Comment by TheBv** [comment]
Are there any errors being thrown when starting the server that could relate to ice and fire?

**Comment by WenXin20** [comment]
Hmm, not sure. I'll check next time I get the crash.

**Comment by WenXin20** [comment]
Here's the log. This time the server crashed because of the Hydra.
[Crash Report](https://gist.github.com/WenXin20/5cf842cc4ba96d954f99833f58d4fc64)
[Server Log](https://gist.github.com/WenXin20/402ac6a69f1b5cd66c00f3259cb6eaf1)

**Comment by TheBv** [comment]
Took me some time and asking but I hopefully fixed the issue. If you know how to build the mod yourself I'd appreciate if you could try the fix and see if it works or not. If not I think you'll need to wait until the next release :| I'll try ask Alex if I'm allowed to make my builds available for others.

**Comment by WenXin20** [comment]
Alright, thanks!
