### ISSUE TITLE
Literally deleted the config file

### ISSUE THREAD

**Issue by elliothawkz2** [Alex-the-666/Ice_and_Fire#3418]
Is there any way I can get it back?

**Comment by Maxi90909** [comment]
Start Up Minecraft an Load It then tere will be a new config file

**Comment by elliothawkz2** [comment]
Wait Ice and Fire uses TOML instead of cfg now?

**Comment by BugmanBugman** [comment]
Every forge mod uses toml now

**Comment by elliothawkz2** [comment]
Damn i feel old

**Comment by elliothawkz2** [comment]
lmao
