### ISSUE TITLE
 pixies in bottles do not keep their color when placed in the world

### ISSUE THREAD

**Issue by CristianUlloa** [Alex-the-666/Ice_and_Fire#3419]
if I capture a pixie in a bottle, and then place it in the world, when I go out and re-enter the world, the bottle appears to be without the pixie, when I touch the bottle a pink pixie appears when the color of the pixie originally did not it was pink

**Comment by TheBv** [comment]
Which version are you using? This should've been fixed with IaF version 2.1.5

**Comment by CristianUlloa** [comment]
> Which version are you using? This should've been fixed with IaF version 2.1.5
version: 2.1.4-1.16.4
ok
