### ISSUE TITLE
Server Issue with Hippogirffs, might be singleplayer too

### ISSUE THREAD

**Issue by BREEZ90** [Alex-the-666/Ice_and_Fire#342]
There's this issue on the server (maybe with singleplayer too) with tamed hippogriffs disappearing while in the air. So far, one has disappeared completely and another (mine) has become untamed. I can still tame it, but  it keeps untaming as I log out and back in. The saddles and inventory of it are also gone, and it flies away.

**Comment by AlexModGuy** [comment]
dupe
