### ISSUE TITLE
Ambrosia Doesn't do anything (Version 1.16.4)

### ISSUE THREAD

**Issue by Maxi90909** [Alex-the-666/Ice_and_Fire#3420]
Ambrosia Doesn't give you the Potion Effects it usually gives you only gives Saturation/Hunger Points

**Comment by Maxi90909** [comment]
https://user-images.githubusercontent.com/76815835/104202913-cc216680-542b-11eb-8c03-cd382e92bda5.mp4

**Comment by Maxi90909** [comment]
Here is a Video.

**Comment by TheBv** [comment]
I tried this in singleplayer and multiplayer both with the newest version of forge and a relatively old one and couldn't recreate this.
I'm assuming it has something to do with the other mods you're using possibly changing how potion effects get added to a player. I dunno. If this also works for you with just the mod installed please let me know!

**Comment by Maxi90909** [comment]
I think It is One of my mods I have because I also have a Bug that causes all My Status effects to disappear when I have an Status effect for example Regeneration that is give to me by a Potioneffectring from other mods. yeah all of my effects disappear as son as I swap one Item in The Hotswap. Maybe that is it. because I get a Bowl back and that counts as Hotswap swap. I don't know what this Bug Is and I don't know what mod is the cause of this.

**Comment by Maxi90909** [comment]
https://pastebin.com/50PcDmJP
 
These Are All the Mods I have maybe You know what causes This bug.
