### ISSUE TITLE
Grave not spawning when killed by ice or fire dragon breath attacks.

### ISSUE THREAD

**Issue by orionSquared** [Alex-the-666/Ice_and_Fire#343]
Hello,

I'm playing on a modpack with this mod in it and it seems that when I die via a dragon's breath attack (the only attacks that have been used against me so far as I'm still early in the pack) no grave spawns and I lose everything I have on me.

**Comment by GundunUkan** [comment]
It does spawn a grave, however, there's a high possibility that the dragon breaks it before you do.

**Comment by Anarchysun85** [comment]
So how do we keep the dragon from wiping it out. I love the mod but if I can't use the Grave mod then the other players on my server might be a little mad.

**Comment by AlexModGuy** [comment]
should be fixed in 1.5.2
