### ISSUE TITLE
 ice and fire ticking entity cockatrice game crash

### ISSUE THREAD

**Issue by StoredDonkey** [Alex-the-666/Ice_and_Fire#3432]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 1/13/21 10:05 AM
Description: Ticking entity

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
	at com.github.alexthe666.iceandfire.entity.EntityCockatrice.isStaring(EntityCockatrice.java:365)
	at com.github.alexthe666.iceandfire.entity.EntityCockatrice.func_70636_d(EntityCockatrice.java:481)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.github.alexthe666.iceandfire.entity.EntityCockatrice.isStaring(EntityCockatrice.java:365)
	at com.github.alexthe666.iceandfire.entity.EntityCockatrice.func_70636_d(EntityCockatrice.java:481)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: iceandfire:if_cockatrice (com.github.alexthe666.iceandfire.entity.EntityCockatrice)
	Entity ID: 1872625
	Entity Name: Cockatrice
	Entity's Exact location: -2059.53, 63.60, 1656.51
	Entity's Block location: World: (-2060,63,1656), Chunk: (at 4,3,8 in -129,103; contains blocks -2064,0,1648 to -2049,255,1663), Region: (-5,3; contains chunks -160,96 to -129,127, blocks -2560,0,1536 to -2049,255,2047)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['ruffelHD'/1872395, l='MpServer', x=-2122.35, y=105.76, z=1651.36]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-31,64,259), Chunk: (at 1,4,3 in -2,16; contains blocks -32,0,256 to -17,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 6629368 game time, 7409626 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 44 total; [EntityFireDragon['Fire Dragon'/1872604, l='MpServer', x=-2037.74, y=11.00, z=1655.66], EntityBat['Bat'/1872603, l='MpServer', x=-2072.57, y=19.70, z=1613.88], EntityHunter['Hunter'/1872532, l='MpServer', x=-2180.46, y=69.00, z=1677.81], EntityPlayerSP['ruffelHD'/1872395, l='MpServer', x=-2122.35, y=105.76, z=1651.36], EntityLatchedRenderer['unknown'/13, l='MpServer', x=8.50, y=65.00, z=8.50], EntityBat['Bat'/1872593, l='MpServer', x=-2114.25, y=6.10, z=1576.66], EntityHat['unknown'/14, l='MpServer', x=8.50, y=65.00, z=8.50], EntityMinecartChest['Minecart with Chest'/1872594, l='MpServer', x=-2116.79, y=39.00, z=1631.12], EntityHunter['Hunter'/1872525, l='MpServer', x=-2180.52, y=70.00, z=1711.98], EntityItemFrame['entity.ItemFrame.name'/1872463, l='MpServer', x=-2250.03, y=69.50, z=1539.50], EntityArmorStand['Armor Stand'/1872516, l='MpServer', x=-2213.50, y=73.00, z=1536.50], EntityBat['Bat'/1872580, l='MpServer', x=-2135.25, y=36.99, z=1621.97], EntityBat['Bat'/1872453, l='MpServer', x=-2112.88, y=33.10, z=1660.25], EntityArmorStand['Armor Stand'/1872517, l='MpServer', x=-2208.50, y=73.00, z=1536.50], EntityBat['Bat'/1872581, l='MpServer', x=-2135.51, y=36.10, z=1610.47], EntityArmorStand['Armor Stand'/1872518, l='MpServer', x=-2205.50, y=67.00, z=1531.50], EntityHunter['Hunter'/1872582, l='MpServer', x=-2139.53, y=63.00, z=1613.37], EntityHunter['Hunter'/1872576, l='MpServer', x=-2133.26, y=65.00, z=1703.83], EntityHunter['Hunter'/1872577, l='MpServer', x=-2139.18, y=66.00, z=1692.23], EntityHunter['Hunter'/1872578, l='MpServer', x=-2149.30, y=65.51, z=1689.97], EntityHunter['Hunter'/1872579, l='MpServer', x=-2139.97, y=68.00, z=1641.39], EntityItemFrame['entity.ItemFrame.name'/1872507, l='MpServer', x=-2213.50, y=30.50, z=1579.03], EntityBat['Bat'/1872564, l='MpServer', x=-2145.56, y=36.05, z=1619.64], EntityHunter['Hunter'/1872565, l='MpServer', x=-2150.61, y=68.00, z=1630.89], EntityItemFrame['entity.ItemFrame.name'/1872497, l='MpServer', x=-2193.50, y=30.50, z=1581.97], EntityHunter['Hunter'/1872561, l='MpServer', x=-2175.47, y=69.00, z=1678.19], EntityCockatrice['Cockatrice'/1872625, l='MpServer', x=-2059.53, y=63.60, z=1656.51], EntityMinecartChest['Minecart with Chest'/1872562, l='MpServer', x=-2168.50, y=36.06, z=1652.50], EntityMinecartChest['Minecart with Chest'/1872563, l='MpServer', x=-2145.50, y=34.06, z=1640.50], EntityHunter['Hunter'/1872489, l='MpServer', x=-2197.88, y=65.00, z=1663.59], EntityAdvancedVampire['Cultist Courn'/1872553, l='MpServer', x=-2190.21, y=64.00, z=1603.33], EntityBat['Bat'/1872554, l='MpServer', x=-2161.41, y=7.10, z=1592.71], EntityHat['unknown'/183, l='MpServer', x=-2122.35, y=104.76, z=1651.36], EntityItemFrame['entity.ItemFrame.name'/1872484, l='MpServer', x=-2214.50, y=74.50, z=1535.97], EntityBat['Bat'/1872548, l='MpServer', x=-2159.25, y=7.10, z=1578.25], EntityZotzpyre['Zotzpyre'/1872549, l='MpServer', x=-2170.50, y=30.00, z=1603.50], EntityBat['Bat'/1872485, l='MpServer', x=-2201.70, y=29.03, z=1649.56], EntityBat['Bat'/1872550, l='MpServer', x=-2177.29, y=14.10, z=1589.93], EntityAdvancedVampire['Prince Zin'/1872551, l='MpServer', x=-2177.60, y=65.00, z=1595.74], EntityMinecartChest['Minecart with Chest'/1872544, l='MpServer', x=-2175.50, y=36.06, z=1625.11], EntityBat['Bat'/1872545, l='MpServer', x=-2169.75, y=32.10, z=1620.64], EntityMinecartChest['Minecart with Chest'/1872546, l='MpServer', x=-2177.50, y=36.06, z=1638.88], EntityItemFrame['entity.ItemFrame.name'/1872483, l='MpServer', x=-2212.50, y=74.50, z=1535.97], EntityBasicVampire['Vampire'/1872547, l='MpServer', x=-2188.61, y=62.37, z=1636.44]]
	Retry entities: 2 total; [EntityLatchedRenderer['unknown'/13, l='MpServer', x=8.50, y=65.00, z=8.50], EntityHat['unknown'/14, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 653847760 bytes (623 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 40 mods loaded, 40 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version                  | Source                                        | Signature                                |
	|:------ |:------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2                   | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                 | 9.42                     | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                 | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCHIJA | forge               | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCHIJA | applecore           | 3.4.0                    | AppleCore-mc1.12.2-3.4.0.jar                  | None                                     |
	| LCHIJA | jei                 | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| LCHIJA | appleskin           | 1.0.14                   | AppleSkin-mc1.12-1.0.14.jar                   | None                                     |
	| LCHIJA | betteranimalsplus   | 8.2.0                    | betteranimalsplus-1.12.2-8.2.0.jar            | None                                     |
	| LCHIJA | biomesoplenty       | 7.0.1.2441               | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar | None                                     |
	| LCHIJA | buildcraftlib       | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                  | None                                     |
	| LCHIJA | buildcraftcore      | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                  | None                                     |
	| LCHIJA | buildcraftbuilders  | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                  | None                                     |
	| LCHIJA | buildcrafttransport | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                  | None                                     |
	| LCHIJA | buildcraftsilicon   | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                  | None                                     |
	| LCHIJA | buildcraftcompat    | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                  | None                                     |
	| LCHIJA | buildcraftenergy    | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                  | None                                     |
	| LCHIJA | buildcraftfactory   | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                  | None                                     |
	| LCHIJA | buildcraftrobotics  | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                  | None                                     |
	| LCHIJA | cfm                 | 6.3.0                    | cfm-6.3.0-mc1.12.2.jar                        | None                                     |
	| LCHIJA | chancecubes         | 1.12.2-5.0.2.385         | ChanceCubes-1.12.2-5.0.2.385.jar              | None                                     |
	| LCHIJA | extendedrenderer    | v1.0                     | coroutil-1.12.1-1.2.37.jar                    | None                                     |
	| LCHIJA | coroutil            | 1.12.1-1.2.37            | coroutil-1.12.1-1.2.37.jar                    | None                                     |
	| LCHIJA | configmod           | v1.0                     | coroutil-1.12.1-1.2.37.jar                    | None                                     |
	| LCHIJA | erebus              | 1.0.30                   | Erebus-1.0.30.jar                             | None                                     |
	| LCHIJA | ichunutil           | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | hats                | 7.1.1                    | Hats-1.12.2-7.1.1.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | howlingmoon         | 0.9                      | howlingmoon-1.12.2-0.9.jar                    | None                                     |
	| LCHIJA | llibrary            | 1.7.20                   | llibrary-1.7.20-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire          | 1.9.1                    | iceandfire-1.9.1-1.12.2.jar                   | None                                     |
	| LCHIJA | inventorypets       | 2.0.6                    | inventorypets-1.12-2.0.6.jar                  | None                                     |
	| LCHIJA | journeymap          | 1.12.2-5.5.9             | journeymap-1.12.2-5.5.9.jar                   | None                                     |
	| LCHIJA | mantle              | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LCHIJA | mca                 | 6.1.0                    | MCA-1.12.2-6.1.0-universal.jar                | None                                     |
	| LCHIJA | morph               | 7.2.0                    | Morph-1.12.2-7.2.1.jar                        | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | twilightforest      | 3.11.1021                | twilightforest-1.12.2-3.11.1021-universal.jar | None                                     |
	| LCHIJA | tconstruct          | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar              | None                                     |
	| LCHIJA | tinkertoolleveling  | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar           | None                                     |
	| LCHIJA | vampirism           | 1.6.2                    | Vampirism-1.12.2-1.6.2.jar                    | None                                     |
	| LCHIJA | teamlapen-lib       | 1.6.2                    | Vampirism-1.12.2-1.6.2.jar                    | None                                     |
	| LCHIJA | waystones           | 4.1.0                    | Waystones_1.12.2-4.1.0.jar                    | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.8141' Renderer: 'Intel(R) UHD Graphics 630'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 630 GL version 4.6.0 - Build 26.20.100.8141, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, programer_art
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 14
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 26.20.100.8141
	OpenGlRenderer: Intel(R) UHD Graphics 630
	OpenGlVendor: Intel
	CpuCount: 8
	
	
	These are all the mods in the mod list:
	
	Appleskin
Betteranimalsplus
Biomes o' Plenty
Buildcraft
CFM
Chance Cubes
Erebus
Hats
Howlingmoon
Ice and fire
Inventorypets
JEI
MCA
Morph
TConstruct
TinkerToolLevelin
Twilight forest
Vamipirism
Waystones
Erebus

Side client

Torohealth
Optifine 
Yourneymap

**Comment by Crazydude323** [comment]
I'm going to confirm that cockatrice have caused crashes on the 1.16 version as well. I don't want to post _another_ long crash report here unless asked, though.

**Comment by TheBv** [comment]
> 
> 
> I'm going to confirm that cockatrice have caused crashes on the 1.16 version as well. I don't want to post _another_ long crash report here unless asked, though.

If they have actually been causing crashes on the 1.16 version please post the crash report here or in a new issue. Since this exact issue mentioned by StoredDonkey should have been fixed in the later non 1.12 versions.

**Comment by Crazydude323** [comment]
Apologies; I did some more testing to confirm things, and it seems that cockatrices weren't the issue. They just happened to be present when whatever actually caused the crash, well... caused a crash. Spawned them in a variety of situations since then, but no crashes. If they were crashing things before, they don't seem to be causing crashes now.
