### ISSUE TITLE
Sheep huddling together and spawning alot

### ISSUE THREAD

**Issue by SaphieNyako** [Alex-the-666/Ice_and_Fire#3433]
On my server I installed ice and fire and I noticed alot of sheep are spawning but they also are huddled up in groups of 3 sheep. 
I tried without ice and fire and this issue wasnt there.
After I installed the mod again there where huddles of sheep.

What is causing this and can I turn it off cause it looks like a sheep invasion

![2021-01-13_14 57 24](https://user-images.githubusercontent.com/77398437/104467159-47168880-55b6-11eb-80b7-91082e763ac0.png)
![2021-01-13_15 10 59](https://user-images.githubusercontent.com/77398437/104467174-4a117900-55b6-11eb-8f28-5777e0bdd9f4.png)

**Comment by SaphieNyako** [comment]
Seems to happen when teleporting to an area (specific: changed from survival to creative mode and teleported there to set a starting point). Edit: If I travel normally it doesnt happen that often.

I did a kill all sheep command in the area and killed 160 sheep in a range of 100. Next 100 again about that many sheep died.

**Comment by TheBv** [comment]
When a wandering cyclops is supposed to spawn it spawns with 3 sheep and they all are placed at the same position.
I'll have the issue with wandering cyclops not spawning fixed in my draft. Thanks for bringing this up!
