### ISSUE TITLE
Dissapearing Mobs Megaissue

### ISSUE THREAD

**Issue by Annabell-O** [Alex-the-666/Ice_and_Fire#344]
We have been having a lot of complaints on the server about people's dragons and hyppogriphs (and gorgons (and gorgons not dropping heads)) disappearing, most often being while they are mid flight. I have no idea whether this is a problem with the server, or whether it is an actual ice and fire bug. but it seems that the disappearances are only reported on the ice and fire mobs. If you want, I can give you access to the server file system, and you can check logs and stuff to see what the problem is. Thanks for your time.

**Comment by UsedPlunger** [comment]
Did This ever get fixed? have had a issue with 3 stage 5 dragons disappearing after taken out of horn and dismounting

**Comment by Syrious** [comment]
In the current version I encountered this problem as well.

**Comment by AlexModGuy** [comment]
should have fixed this but might still show up

**Comment by AlexModGuy** [comment]
mid flight dissapearances should be fixed in 1.8.4
