### ISSUE TITLE
Server Crashed. "Tried to access a block entity before it was created."

### ISSUE THREAD

**Issue by Zaurimasz** [Alex-the-666/Ice_and_Fire#3440]
I am experiencing server crashes, detailed in the log.

It seems to be centered around an area which is not explored yet. 
Whenever someone connects to the serve, a message appears:

[21:53:39] [Worker-Main-24/WARN] [minecraft/WorldGenRegion]: Tried to access a block entity before it was created. BlockPos{x=-905, y=120, z=-2732}

Z coordinates vary by a few.

Whenever a player goes close enough "north"(where the unexplored area lies) to the entity which is trying to spawn there, the server freezes up and disconnects the players. Serverwatchdog stops it after 60secs.
Tried to turn off server watchdog tick time, but after the first DC, the players cannot reconnect.
Also, with the server watchdog turned off the last server message reads:

[Ice and Fire Pathfinding Worker #0/INFO] [co.gi.al.ic.IceAndFire/]: Pathfinding from [-786,15,-2492] away from [-786,14,-2492]

Other relevant mods installed include:
Alex's Mob
Aquaculture
BetterCaves
BetterMineshafts
ViomesOfPlenty
Botania
valhelsia_structures

[crash-2021-01-14_22.05.37-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5816825/crash-2021-01-14_22.05.37-server.txt)

**Comment by TheBv** [comment]
Try the new Ice and Fire version (2.1.5) and see if that fixes the issue for you. If not let me know!

**Comment by Zaurimasz** [comment]
Thank you, TheBv.

This update seems to have fixed the issue.

**Comment by RipClawMagna-1** [comment]
I am having the same issue on version 2.1.13, any idea on what to do?
