### ISSUE TITLE
"Death Worm Spawn Weight" acts as "chance" iceandfire-2.1.5-1.16.4

### ISSUE THREAD

**Issue by tylerius** [Alex-the-666/Ice_and_Fire#3442]
"Death Worm Spawn Weight" = 1000 spawns less worms even though the comment says lower = less worms.

I'm going to continue testing, I think most of the weights are weights and so on but I noticed an ass-ton of worms when set to 1. XD

Included list of mods in case.

[list.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5820361/list.txt)

**Comment by TheBv** [comment]
Jup you're absolutely right. Deathworm spawn weight and spawn chance are swapped or at least the lower != less worms.
I'll have a look if other entities have the same issues!

**Comment by tylerius** [comment]
"Mausoleum Gen Chance" = 3000 also seems to be producing a lot of Mausoleums, some very close together
