### ISSUE TITLE
Structures not spawning

### ISSUE THREAD

**Issue by elliothawkz2** [Alex-the-666/Ice_and_Fire#3443]
I tried everything
I tried changing the spawn chance to literally 10
I tried changing dangerous world gen dist to 10
I even deleted biomes.toml and get a new one
Nothing works

**Comment by elliothawkz2** [comment]
Help I am panicking rn
Does anyone have a similar issue?

**Comment by Celophy** [comment]
i have the same problem, it is the new version probably

**Comment by Caelosatron** [comment]
Is the lower the number, the higher chance of spawn?? I have been setting spawn chances to like, 3000 just trying to see a structure. Do I need to lower the value?
