### ISSUE TITLE
Blindfold blindness not working while underwater

### ISSUE THREAD

**Issue by Bonniethebunny-hub** [Alex-the-666/Ice_and_Fire#3444]
When searching a gorgon temple that was submerged in water, I noticed that as soon as I got my head into the water, I could see the whole room while still wearing the blindfol
![2021-01-15_13 31 17](https://user-images.githubusercontent.com/58606655/104727660-02196000-5736-11eb-91d0-8b8e278d06ac.png)
d.

**Comment by TheBv** [comment]
This is an issue with how minecraft enforces the blindness effect. Mojang will hopefully have fixed this in 1.17 https://bugs.mojang.com/browse/MC-167763
