### ISSUE TITLE
Can't ride dragon in multiplayer.

### ISSUE THREAD

**Issue by abarrackz** [Alex-the-666/Ice_and_Fire#3446]

**Comment by abarrackz** [comment]
I can ride the dragon in multiplayer server, but when my friend ride his dragon. I suddenly drop to the ground and the dragon fly by it self. And when I'm trying to ride the dragon my friend drop to the ground.

Sorry for bad english 👍

**Comment by pincherinio** [comment]
Yes same here/ Using latest i/f mod update and 1.16.4 MC version.

**Comment by pincherinio** [comment]
Sometimes u can both ride it and its cool for some time and then it just goes downhill and drops one of the players under the world and u need to use the kill command for the player. The dragon is flying straight forward and goes missing completely.
