### ISSUE TITLE
Ice and Fire dragon pathfinding crash

### ISSUE THREAD

**Issue by SpycrabSXL** [Alex-the-666/Ice_and_Fire#3449]
Ice and fire dragon crashing due to IStuckHandlerEntity. Rats mod had a similar issue (as I was the one who made the git) but has been fixed, maybe the same concept can be applied here?

[crash-2021-01-16_16.35.46-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5824751/crash-2021-01-16_16.35.46-server.txt)
https://pastebin.com/gYp7ZSvV

Git Link from rats mod: https://github.com/Alex-the-666/Rats/issues/513

**Comment by TheBv** [comment]
Thanks a lot for the info I'll implement the fix from the rats mod into my draft!
