### ISSUE TITLE
Structures too slow to generate

### ISSUE THREAD

**Issue by Matthysse** [Alex-the-666/Ice_and_Fire#3450]
Hello!
I'm on a pretty slow server but which works really great even with Terraforged and Biomes O Plenty, unless it tries to generate a structure from Ice and Fire, which make 100% the server crash with this message:
https://pastebin.com/9gg9G2t2
The structure isn't that big, (it's a dragon roost in this situation), and strongholds, villages, towers from DungeonsPlus generate normally without slowing down the server.

**Comment by TheBv** [comment]
Which version of the mod are you using?
The 2.1.5 version most likely won't fix this issue but the IceDragonRoost code has changed a bit so to make sure that I'm looking at the right line in the code, it would be great if you could tell me if you're using version 2.1.5 or the ones before that.

**Comment by Matthysse** [comment]
Yes it is on 2.1.5, but it doesn't do it only with the DragonRoost, but with the DragonCave too (the others work normally iirc).

**Comment by TheBv** [comment]
That's probably because Dragon roosts and dragon caves get generated in code depending on the age of the dragon.
I'll try and see if I can possibly optimize this somehow.
