### ISSUE TITLE
Change wendigo name

### ISSUE THREAD

**Issue by Eario** [Alex-the-666/Ice_and_Fire#3454]
The current name for the planned mob "wendigo", considering the mob itself, is disrespectful to the native american cultures it stems from, as stated by many native americans who have commented on it. In the interest of not offending them, I ask on their behalf that its name be changed - there are many other shapeshifting monsters in various folklores that can be drawn on instead without offending a culture that is still alive and well.

**Comment by MrAardvark47** [comment]
No? Wendigo is a cool name for a mob... You're the only one getting offended, and for a stupid reason. 

There is a game called "Until Dawn" containing creatures called "Wendigos" and no one cared back then, so why should they care about a Minecraft mod with creatures of the same name? Stop being sensitive and post a real issue please, not an "im offended omg so disrespectful omg omg" post.

**Comment by ayleafs** [comment]
> The current name for the planned mob "wendigo", considering the mob itself, is disrespectful to the native american cultures it stems from, as stated by many native americans who have commented on it. In the interest of not offending them, I ask on their behalf that its name be changed - there are many other shapeshifting monsters in various folklores that can be drawn on instead without offending a culture that is still alive and well.

the problem now is that everybody is offended by everything, and I can understand culture being misrepresented or maybe slurs and how those are offensive (only in certain contexts). my problem with what you're saying is that you've made the claim it's "offensive" without stating why.

**Comment by BugmanBugman** [comment]
> The current name for the planned mob "wendigo", considering the mob itself, is disrespectful to the native american cultures it stems from, as stated by many native americans who have commented on it. In the interest of not offending them, I ask on their behalf that its name be changed - there are many other shapeshifting monsters in various folklores that can be drawn on instead without offending a culture that is still alive and well.

This conversation has been had a million times. There was no reason to put it on here, and the devs have agreed into looking into changing the name.

It’s not a bug, you should’ve put it on the discord.

also, Native American cultures are not a monolith lol.

**Comment by MrAardvark47** [comment]
> The current name for the planned mob "wendigo", considering the mob itself, is disrespectful to the native american cultures it stems from, as stated by many native americans who have commented on it. In the interest of not offending them, I ask on their behalf that its name be changed - there are many other shapeshifting monsters in various folklores that can be drawn on instead without offending a culture that is still alive and well.

"I'm offended because the mob is hostile and uses violence, and in my culture we are against violence"

s n o w f l a k e

**Comment by BugmanBugman** [comment]
See, this is the stuff this topic elicits. Just toxic people.

**Comment by 78373** [comment]
> The current name for the planned mob "wendigo", considering the mob itself, is disrespectful to the native american cultures it stems from, as stated by many native americans who have commented on it. In the interest of not offending them, I ask on their behalf that its name be changed - there are many other shapeshifting monsters in various folklores that can be drawn on instead without offending a culture that is still alive and well.

How is it offensive? Taboo? For some, yes. But at the end of the day, if you don't like it **don't play the mod**. And where are these many native americans speaking out against the name as you say? Show me the huge outrage here? You are not the savior of native Americans and their great defender. This is a non-issue, complaining just for the sake of it.

**Comment by MrAardvark47** [comment]
> > The current name for the planned mob "wendigo", considering the mob itself, is disrespectful to the native american cultures it stems from, as stated by many native americans who have commented on it. In the interest of not offending them, I ask on their behalf that its name be changed - there are many other shapeshifting monsters in various folklores that can be drawn on instead without offending a culture that is still alive and well.
> 
> How is it offensive? Taboo? For some, yes. But at the end of the day, if you don't like it **don't play the mod**. And where are these many native americans speaking out against the name as you say? Show me the huge outrage here? You are not the savior of native Americans and their great defender. This is a non-issue, complaining just for the sake of it.

Facts

**Comment by AlexModGuy** [comment]
> This conversation has been had a million times. There was no reason to put it on here, and the devs have agreed into looking into changing the name.

It’s not a bug, you should’ve put it on the discord.

also, Native American cultures are not a monolith lol.
