### ISSUE TITLE
(1.16.4) No Armor Textures and Crash

### ISSUE THREAD

**Issue by ThatTLeef** [Alex-the-666/Ice_and_Fire#3455]
I've been playing on my 1.16.4 world for several weeks with no problem, yet today I went to raise the spawn rate for Dragon Skeleton spawn because I couldn't find any , suddenly the world started crashing after I logged back on and noticed that my Lightning Dragonsteel armor set was missing its texture. I can be in the world for a maybe a minute before it crashes, giving me an Exit Code 0. I deleted the config so that it would recrate upon loading Minecraft, but that still didn't fix it.
Here's the crash report: https://pastebin.com/rSr1PJx4
Thanks in advance.

**Comment by TheBv** [comment]
Can you possibly also provide the "latest.log" or the log that lists everything that happens from starting minecraft until closing?
Since your armor not having a texture should be related to the startup process and quite possibly whatever happens there might be related to the crash itself.

**Comment by ThatTLeef** [comment]
> Can you possibly also provide the "latest.log" or the log that lists everything that happens from starting minecraft until closing?
> Since your armor not having a texture should be related to the startup process and quite possibly whatever happens there might be related to the crash itself.

https://pastebin.com/Ue48XJyJ

**Comment by TheBv** [comment]
Good news and bad news:
Good news :The crash you're experiencing after the first crash I have already fixed in my draft which means it will hoepfully be fixed in the next release.
Bad news: The crash you've experienced the first time is quite similar to the one you're experiencing now. Some class files can't be properly loaded which might point to a bigger problem underlying both of them. I'll continue investigating!

**Comment by ThatTLeef** [comment]
> Good news and bad news:
> Good news :The crash you're experiencing after the first crash I have already fixed in my draft which means it will hoepfully be fixed in the next release.
> Bad news: The crash you've experienced the first time is quite similar to the one you're experiencing now. Some class files can't be properly loaded which might point to a bigger problem underlying both of them. I'll continue investigating!

Thanks so much, I really appreciate it. I honestly have no clue as to what could've caused all of this since the only thing I changed was in the configs. I hope you'll be able to figure this out :)
