### ISSUE TITLE
Can't ride hippocampus

### ISSUE THREAD

**Issue by Matthewt217** [Alex-the-666/Ice_and_Fire#3456]
Immediately dismounted off of tamed hippocampus with saddle only in water. Doesn't happen on land. Don't know if this is due to forge possible changing entities in water.

**Comment by Blackpinned** [comment]
Same issue for me with Ice and Fire 2.1.5-1.16.4

**Comment by Doominic08** [comment]
I'm having the same problem on the latest version of the mod on 1.16.4. I noticed that riding it on top of the water is fine but going under the water kicks you off. I tested this with the previous version of the mod and sure enough it worked fine

**Comment by Doominic08** [comment]
I found a fix: for some reason you cant ride it underwater in the latest forge launcher: use an older forge launcher version. version 35.1.28 works if your concerned about not using quark.
