### ISSUE TITLE
Ice and Fire dragons show duplicate player model in first and third person

### ISSUE THREAD

**Issue by egshels** [Alex-the-666/Ice_and_Fire#3458]
![image](https://user-images.githubusercontent.com/31183838/104986018-3152fa00-59e0-11eb-88c1-7f097b884fbb.png)

![image](https://user-images.githubusercontent.com/31183838/104986015-2dbf7300-59e0-11eb-8297-34eec3a48c96.png)

**Comment by DodoBoi** [comment]
I also have this bug, i still didnt find any anwser to fixing but i hope it will have its end in the next version

**Comment by MashiroMakamru** [comment]
I had the same issue and I found a possible fix, I had two opt fines installed on my mods and I got rid of one and reset my forge and it worked!

**Comment by DenilsonNM** [comment]
same problem
