### ISSUE TITLE
1.10.2 server crash

### ISSUE THREAD

**Issue by Byron1121** [Alex-the-666/Ice_and_Fire#346]
My friend is trying to set up a modpack server however when we were testing it I approached a dragon and the server crashed because when it went to check if the dragon was dead or not it sent an integer to a boolean (I don't really know about coding or anything that's just what the crash report said)

**Comment by AlexModGuy** [comment]
1.10 is no longer suported

**Comment by Byron1121** [comment]
I wasn't asking if you could go back and fix it (I fully understand it's no longer supported) I was simply wishing to know how I could fix it myself.
