### ISSUE TITLE
Lightening dragon dies instantly when hatched from egg by “magic” aka lightening 

### ISSUE THREAD

**Issue by MrMangoCango** [Alex-the-666/Ice_and_Fire#3462]
As the title suggest. I am on the latest version and 1.16.4

**Comment by Raoruta** [comment]
I had the same problem. There was a mod that increased the damage of Lightning Bolt that caused the spawn dragon to die. 

This mod is "Inventory Pets" mod. When I removed this mod, it improved.

I want to remove the lightning completely, but I could not.

**Comment by MrMangoCango** [comment]
Yep that is the exact mod that I have as well. That sucks. Thanks for helping me narrow it down
