### ISSUE TITLE
bestiary bug

### ISSUE THREAD

**Issue by Archuhi3** [Alex-the-666/Ice_and_Fire#3463]
Is the bestiary lectern supposed to consume the manuscripts because in my solo world and on my server I've noticed I can just put in 3 manuscripts and I can get everything unlocked in the book. 

I thought it was just me at first but I saved about 45 manuscripts and just tried to see if it worked again but it didn't for me.
About 10 mins later my friend goes "there must be like some kinda glitch or something", and so I asked "Can you just keep picking the book up with 3 manuscripts in it and it unlock everything?". he said yeah so figured I would bring this up here.
 just updated the server today as well.

Playing on All The Mods 6 1.16 version 1.4.0

**Comment by LordMeta** [comment]
I ran into this issue as well im glad it got mentioned here
