### ISSUE TITLE
[1.11.2-1.2.1] Ticking Entity Crash in Single Player

### ISSUE THREAD

**Issue by kreezxil** [Alex-the-666/Ice_and_Fire#347]
I have a player that started a creative world to test things out and had two crashes in a row. 

client crash reports:
https://pastebin.com/zJAPGxGi
https://pastebin.com/xDpZzKZU
https://pastebin.com/ChqJWmCM

I tried it and got the same result, which is weird, because we don't experience this issue when playing on the dedicated server i created for the pack.

My ssp crash report:
https://pastebin.com/9rfcz6iN

Searching the issues it appears that #70 is similar from the closed section.

**Comment by Delvos** [comment]
I am the user that reported the crash.

On loading a single player game with the World of Dragons modpack, the game crashes after about 20 seconds and makes no difference if I am in creative or survival or even if that world was made as creative or survival.

**Comment by kreezxil** [comment]
I've been doing some more intensive testing and it looks like the firedragon is big culprit.

https://gist.github.com/8ee27a19f2854100c26c2128d2388028
https://gist.github.com/d9ef9495c13cb3b0ce173035a89f9f87
https://gist.github.com/23d770e8f9189815ed1798481eb69a02
https://gist.github.com/f5944b80b610252a9152af3b72974ce7
https://gist.github.com/04b61e85f38544ee3d076c1170eaa7ea
https://gist.github.com/51ea202fdc089a035145cb79ae01832e
https://gist.github.com/4d7f5cc51969eecda30107066fb7d826
https://gist.github.com/d9df36ed879afe2208f60421db97e7c9
https://gist.github.com/21e760938433a1b0cf56a6234773c28b
https://gist.github.com/729a86495e49ea3e3eeada9d60f7a625
https://gist.github.com/7754cfc98816e5b3d46206915cad4135
https://gist.github.com/ef11fd3aef917de73353b026a28fd1f5

all of the above shows the firedragon as being a ticking entity causing a server crash. And this crash is not happening just once in a while now, it's happening rather constantly and highly frequently now.

```

-rw-r--r-- 1 root root 19195 Oct 31 18:29 crash-2017-10-31_18.29.55-server.txt
-rw-r--r-- 1 root root 19173 Oct 31 18:31 crash-2017-10-31_18.31.40-server.txt
-rw-r--r-- 1 root root 19194 Oct 31 18:51 crash-2017-10-31_18.51.53-server.txt
-rw-r--r-- 1 root root 19329 Oct 31 19:05 crash-2017-10-31_19.05.18-server.txt
-rw-r--r-- 1 root root 19299 Oct 31 19:36 crash-2017-10-31_19.36.20-server.txt
-rw-r--r-- 1 root root 19305 Oct 31 19:38 crash-2017-10-31_19.38.47-server.txt
-rw-r--r-- 1 root root 19284 Oct 31 19:43 crash-2017-10-31_19.43.18-server.txt
-rw-r--r-- 1 root root 19306 Oct 31 19:45 crash-2017-10-31_19.45.02-server.txt
-rw-r--r-- 1 root root 19302 Oct 31 19:46 crash-2017-10-31_19.46.42-server.txt
-rw-r--r-- 1 root root 19298 Oct 31 19:50 crash-2017-10-31_19.50.18-server.txt
-rw-r--r-- 1 root root 19305 Oct 31 19:55 crash-2017-10-31_19.55.32-server.txt
-rw-r--r-- 1 root root 19305 Oct 31 20:17 crash-2017-10-31_20.17.30-server.txt
```

**Comment by AlexModGuy** [comment]
>1.2.1

Haven't sen this issue recently.
