### ISSUE TITLE
Dragon caves with YUNG's Better Cave

### ISSUE THREAD

**Issue by dwiantlake** [Alex-the-666/Ice_and_Fire#3472]
I think I never find any dragon caves when using the [YUNG's Better Cave](https://www.curseforge.com/minecraft/mc-mods/yungs-better-caves) mod.
but the rest generation is works fine(e.g gorgon dungeon, cyclops cave, etc), although i'm using it with BOP, idk if either the YBC mod causing the problem or both.
Issue: either the dragon caves rarity is raising from the normal, or it doesn't work with the mod.

**Comment by BugmanBugman** [comment]
I have seen caves with YUNG. It’s just that caves aren’t as common before since they spawned like crazy due to a bug.

**Comment by dwiantlake** [comment]
> 
> 
> I have seen caves with YUNG. It’s just that caves aren’t as common before since they spawned like crazy due to a bug.

Man, ty for the replies been looking for this answer tho 4real lol, at least i've found some who actually found the caves.
