### ISSUE TITLE
Multiple nearby players can not ride dragons

### ISSUE THREAD

**Issue by Silivek** [Alex-the-666/Ice_and_Fire#3475]
Version - iceandfire-2.1.5-1.16.4.jar
Forge Version - forge-35.1.4
Minecraft Version - 1.16.4
I am running a multiplayer server and every time someone gets on a dragon nearby players get pseudo-kicked from their dragon. The player who has most recently clicked a dragon to ride will ride, and the kicked players are able to move around as if off the dragon but if the kicked players press their dismount key they teleport back to the dragon and get off it. Not sure what the exact reason is as to why this happens. This also occurs with the dragons riding your shoulder. Someone else will put their dragon on their shoulder and it will appear on other players' shoulders.
Please note that if a rider is not in render distance this will not occur.

**Comment by TheBv** [comment]
This has been addressed and will be fixed in the next release #3412
