### ISSUE TITLE
crash after meeting a dragon

### ISSUE THREAD

**Issue by zazzik** [Alex-the-666/Ice_and_Fire#3479]
We were playing TNP limitless 3 modpack, my friend met a dragon and the server crashed.
From log I can see it's related to ice and fire.
[crash-2021-01-25_15.49.28-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5866645/crash-2021-01-25_15.49.28-server.txt)

**Comment by TheBv** [comment]
This has been addressed and will make it's way into the next release #3412
