### ISSUE TITLE
with the blackstone in 1.16 can there be a volcanic biome? Why did they erase the glacier biome from the mod? It would be good if that biome returned and the volcano biome could be implemented

### ISSUE THREAD

**Issue by FORJATARTARO** [Alex-the-666/Ice_and_Fire#3480]

**Comment by somebodyandnobody** [comment]
the glacier biome was never erased.

**Comment by FORJATARTARO** [comment]
> el bioma glaciar nunca fue borrado.

of course it was deleted but because it no longer appears, did you remove it at 1.16? are you aware of now? already in these versions that biome was removed
