### ISSUE TITLE
2.1.5 increase the range of appearance of the dragon roots and dragon caves since they almost do not appear in the world it is very difficult to find a dragon they are almost disappeared

### ISSUE THREAD

**Issue by FORJATARTARO** [Alex-the-666/Ice_and_Fire#3481]

**Comment by FurryApocalypse** [comment]
> _No description provided._

First of all are you aware that there is a config that provides you possibility to change spawn rate of roots and caves as you wish? It works very well and in the 2.1.5 patch it's even better couse there are no stackable roots or caves (there is a position to change distance between the danger area).
You should go to iceandfire common config and check it out.
Also you should be aware that if you have mod that changes the biome from vanilla minecraft you gonna need to add each biome to each dragon, dragon skeleton or else in iceandfire_biomes and that file is in config folder too.

But remember even if you change anything now it wont apply on alredy generated  world. All generated and discovered chunks will be untouched. You gonna need to search changes far away when you have not been before or just create new world (there is distance also of spawn area that should be safe. Keep that in mind.)
