### ISSUE TITLE
1.16.4 Server compatibility issues

### ISSUE THREAD

**Issue by L00T3RK1NG** [Alex-the-666/Ice_and_Fire#3485]
So I´m trying to get the Ice and Fire mod on my nitrado server but it´s always the same - the server can´t handle the mod.
I don´t know what I did wrong. I downloaded the latest log and put it down below. 
Please take a look at it and tell me, what I need to do to fix that problem.
All I want is to play Minecraft with cool dragons with my friends. :(
[latest (1).log](https://github.com/Alex-the-666/Ice_and_Fire/files/5875241/latest.1.log)

**Comment by TheBv** [comment]
There should also be a debug.log that includes a lot more information would be cool if you could post that here.
Also what exactly do you mean with "the server can't handle the mod" is the server not starting at all?

**Comment by L00T3RK1NG** [comment]
Sorry for my failure... I don´t know what I did wrong the first time... I tried to start from 1 again with resetting the server to forge, installing the mods and so on.. now it works... sorry again.

BUT - It looks great :)
