### ISSUE TITLE
[Suggestion] Config option to turn off or reduce wild dragon's fire attack

### ISSUE THREAD

**Issue by faeldray** [Alex-the-666/Ice_and_Fire#349]
In both SP and MP, the fire that can comes from a dragon can really hurt TPS and FPS. I've had a few instances when I come across a section of dense forest that a dragon has set on fire and it turns into a race to see if I can put it out before the client/server becomes unplayable. This is when griefing is set to 2 in the config as well. Having the option to somehow reduce or turn off the fire attack would be greatly appreciated.

**Comment by ReaperAngels** [comment]
Maybe add an option that the fire attack does not set trees on fire.

**Comment by brisingraerowing** [comment]
I was in a Jungle when this happened. I usually have 60 - 100 FPS, I was getting 1-5 FPS then. An option to disable trees being set on fire would be very helpful.
  
EDIT: Another way to (possibly) alleviate the effects of this issue is to disable fire tick (e.g. `/gamerule doFireTick false`)

**Comment by AlexModGuy** [comment]
https://github.com/Alex-the-666/Ice-and-Fire-Suggestions/issues
