### ISSUE TITLE
Problematic Interactions With Gorgon Head And Dread Mobs

### ISSUE THREAD

**Issue by selened** [Alex-the-666/Ice_and_Fire#3495]
Minecraft version: 1.16.4
Forge version: 35.1.36
Ice and Fire version: 2.1.5
Citadel version: 1.5.3

Using the gorgon head on dread mobs has the chance to either turn them into stone (as expected) or simply turn them invisible. They don't turn into stone and simply continue doing their thing while invisible. There is no apparent pattern to whether the gorgon head works on them or not. Furthermore, using the gorgon head on a dread knight horse specifically will cause a crash.

Forge log in which I tried to use the gorgon head on all dread mobs:
https://pastebin.com/8hLvqztx
Crash log for when I used the gorgon head on a dread horse:
https://pastebin.com/LSu3GdML

**Comment by roosterwhale** [comment]
I had this problem start when I first entered a mausoleum, and it has since started affecting non-dread mobs
