### ISSUE TITLE
Lightening dragon always dying by magic when hatching 1.16.3

### ISSUE THREAD

**Issue by ChaoticDusk** [Alex-the-666/Ice_and_Fire#3509]
My friend and I are both having the issue of our baby lightning dragons dying the moment they hatch when they get struck by lightning I play on 1.16.3 and she plays on the newest version but with both have the same issue. Does anyone know why this happens? Are we hatching them wrong? any help would be appreciated.

**Comment by Carro1001** [comment]
You got inventory pets?

**Comment by 48004800** [comment]
Increase the health of the lightening dragon through config

**Comment by ChaoticDusk** [comment]
> 
> 
> You got inventory pets?

Yes, is that what's causing it? IS there anything we can do to avoid that while keeping the mod?

**Comment by Xterionix** [comment]
> Increase the health of the lightening dragon through config

For me its says Update JDK or something what should I do?

**Comment by ChaoticDusk** [comment]
It was inventory pets. I just wish I didn't have to uninstall it for things to work.

**Comment by Carro1001** [comment]
The developer may have added a config to disable the extra lightning dmg recently, by my request, but i'm not sure
