### ISSUE TITLE
Teal Sea Serpents Do Not Spawn

### ISSUE THREAD

**Issue by Syrikal** [Alex-the-666/Ice_and_Fire#3511]
Teal sea serpents don't spawn naturally in the world. I found that the sea serpent's onWorldSpawn method chooses the variant as random.nextInt(6), and so generates a number from 0-5. As teal is variant 6, they do not spawn.

![image](https://user-images.githubusercontent.com/76715986/106707790-6dc54f00-65b7-11eb-9a2e-1355c67b0ba5.png)

**Comment by TheBv** [comment]
Good catch! I'll address this in my next PR
