### ISSUE TITLE
Ice and Fire Title Screen Crash

### ISSUE THREAD

**Issue by Maxi90909** [Alex-the-666/Ice_and_Fire#3512]
https://pastebin.com/h7aEu7X9
[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/5919276/latest.log)

I think something is wrong with the custom Ice and Fire title screen. In my case it sometimes loads a World Normal and sometimes this crash happenes.

**Comment by TheBv** [comment]
You can disable the ice and fire title screen in the settings.
This might be caused by a different mod that you have installed that is also trying to change the title screen. 
That's by best bet anyway since this crash doesn't occur if you have only IaF installed.

**Comment by Maxi90909** [comment]
I now disabled the Ice and Fire title screen and that fixed it. The problem was that other mod had also a custom title screen it was the Yungs Better mineshafts mod and the by me new added  Yungs better Portals mod also has a custom title screen. I think the problem with the Ice and Fire screen should be fixed because no other Custom mod title screen causes this crash, if there are more than one custom mod title screen one of them just overwrites all of them an nothing more happens but in this case it causes a crash.
