### ISSUE TITLE
Most Mobs, Structures, and 2 Biomes not spawning

### ISSUE THREAD

**Issue by faustojc** [Alex-the-666/Ice_and_Fire#3517]
Seen structures:
- Mausoleum
- Graveyard

Seen Biomes:
- None

Seen Ice and Fire Mobs:
- Ice Dragon (Once)
- Ghost 
- Stymphalian Birds (Only twice)
- Siren (Once)
- Hippogryphs (Once)

Traveled: about 10km+ every direction

As the mention above, I only saw them so rarely in my Aternos server. I tried to increase the spawn chance up to maximum number in the config and still nothing. I traveled about 10km in every directions, still nothing even the 2 biomes are nowhere to be seen. I've Biomes O' Plenty mod installed but it's not quite the problem because I tested it in Singleplayer with multiple attempts, I saw every mobs and structures even the 2 biomes with Biomes O' Plenty mod installed :(

**Comment by IronVampyr** [comment]
Estou passando pelo mesmo problema.
Porém eu notei que o mod "Citadel" está desatualizado no meu modpack. Daqui a pouco eu vou fazer o download da versão atualizada e testar.
Logo mais eu volto com um feedback sobre o caso.
Edit: no meu caso, nada é gerado.
