### ISSUE TITLE
I/F Banner Designs Error

### ISSUE THREAD

**Issue by Mungust** [Alex-the-666/Ice_and_Fire#3519]
I do not need the talking as these pictures will prove everything. Just let me know for further details.
![2021-02-05_19 49 50](https://user-images.githubusercontent.com/78623979/107101361-e7358b00-67cb-11eb-88ea-b68383e4b8ea.png)
![2021-02-05_19 51 17](https://user-images.githubusercontent.com/78623979/107101364-e997e500-67cb-11eb-961c-00995bef6102.png)

**Comment by TheBv** [comment]
Which version are you using?
I've tried this out on the newest version and they seem to work fine for me :/

**Comment by Aeonsteel** [comment]
TheQuantumRuby posted an issue about this, it's a compat issue with refined storage.
#3037
