### ISSUE TITLE
1.16.5 crash

### ISSUE THREAD

**Issue by Gongasys** [Alex-the-666/Ice_and_Fire#3522]
[crash-2021-02-06_14.14.30-fml.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5936960/crash-2021-02-06_14.14.30-fml.txt)

**Comment by TheBv** [comment]
This crash is caused by structurized not Ice and Fire...
`Mod File: structurize-0.13.96-ALPHA-universal.jar
	Failure message: Structurize (structurize) has failed to load correctly
		java.lang.RuntimeException: Missing some newest data versions. Please update com/ldtteam/structures/blueprints/v1/DataVersion
	Mod Version: 0.13.96-ALPHA
	Mod Issue URL: https://github.com/ldtteam/Structurize/issues/new
	Exception message: java.lang.RuntimeException: Missing some newest data versions. Please update com/ldtteam/structures/blueprints/v1/DataVersion`
