### ISSUE TITLE
1.16 No config option to disable silver ore generation

### ISSUE THREAD

**Issue by LuciusV** [Alex-the-666/Ice_and_Fire#3525]
As there are many other mods that add silver ore, option to disable it in IaF would be nice to have.

**Comment by LuciusV** [comment]
Could you please clarify why this is closed without comment or resolution

**Comment by TheBv** [comment]
There's an explanation here #3596.
If you want you can create a new issue but I'll keep this in the back of my head and try implement it as well when I get around to it.

**Comment by LuciusV** [comment]
Thank you, sorry for not discovering there is separate page for suggestion.
