### ISSUE TITLE
faultiness

### ISSUE THREAD

**Issue by 48004800** [Alex-the-666/Ice_and_Fire#3527]
Generally speaking, the quality of this mod is good, but there are some imperfections
1  Dragon armor is invalid

2 Lightning arms can damage players and destroy falling objects

3 The modification of dragon steel sword and dragon steel armor is invali {by modifying config}    {including damage,
durability and armor point}

4 Giant death worms sometimes can't hurt other entities, but can hurt themselves   It's not conducive to their attack

5 If the Dragon attacks another entity, that entity will attack the corpse of the dragon after dragon dies 

6 Hatching Myrmex Eggs can lead to collapse.  Dragon Summoning Crystals cannot work after dragon horns work.
7 Dragon's fireball attack damage cannot be configured{fire ice lightning}

There was a lot of feedback here, so I sent it again and revised the unreasonable words.

**Comment by ShootToKillSTK** [comment]
I've noticed an aggressive entity attack a dragon corpses too, or at least the bones corpse that generates randomly.

Probably from mobs that attack monster entities, I noticed with the mob from Outvoted mod 'Great Hunger' attacked it, to no result, just stuck targeting it I believe.

**Comment by 48004800** [comment]
> I've noticed an aggressive entity attack a dragon corpses too, or at least the bones corpse that generates randomly.
> 
> Probably from mobs that attack monster entities, I noticed with the mob from Outvoted mod 'Great Hunger' attacked it, to no result, just stuck targeting it I believe.
This bug makes my village guards useless. They're just attacking the dead dragon.
