### ISSUE TITLE
Config for default attack strenght of Dragonsteel Sword not working

### ISSUE THREAD

**Issue by Asveste** [Alex-the-666/Ice_and_Fire#3533]
Even though I put 18.0 Damage in the config, the weapon still deals 25 Damage ingame.

**Comment by Syrikal** [comment]
I did some poking around and I _think_ it might have something to do with this line in IafConfig.java, which initializes dragonsteelBaseDamage as a float but defines it as a double.
![image](https://user-images.githubusercontent.com/76715986/107840845-11ff8080-6d84-11eb-946d-33cae23e4a35.png)

**Comment by DenilsonNM** [comment]
I am looking for the same, could they solve it? Is there a separate mod that allows you to change it?

**Comment by 04Slash** [comment]
Doing some further testing shows that the "Dragonsteel Base Durability" and "Dragonsteel Base Armor" config options don't work either.
