### ISSUE TITLE
Neutral Bone serpents still attacking

### ISSUE THREAD

**Issue by Amayapuppy** [Alex-the-666/Ice_and_Fire#3535]
Set the config to neutral and they're still attacking as if they're hostile

**Comment by BugmanBugman** [comment]
Bone serpents ??

**Comment by Carro1001** [comment]
This isn't the alex's mobs github LMAO

**Comment by Amayapuppy** [comment]
> This isn't the alex's mobs github LMAO

Oh crap my mistake lmao
