### ISSUE TITLE
pixie sound range

### ISSUE THREAD

**Issue by IKatashi** [Alex-the-666/Ice_and_Fire#3538]
I have noticed that the sound of the pixies in the jars or pets have a too long range, approximately they are more than 64 blocks away to stop listening to them, in addition to that even if you lower the sound of the friendly or enemy mods the sound continues you must remove noise in general so as not to hear them.

**Comment by roosterwhale** [comment]
I've noticed this as well. In addition, I've had an issue where the pixie noises will, as far as I can tell, generate from nearby cockatrices
