### ISSUE TITLE
minor new companions and small aesthetic tweaks

### ISSUE THREAD

**Issue by AppeaseTheBees** [Alex-the-666/Ice_and_Fire#3542]
ice and fire adds a lot of fun challenges, and tamed dragons are such a cool thing to achieve. but what about minor mystical creatures to have as companions for when you're not on epic quests?

like maybe kobold pets to help sniff out ores(you have to have moned the ore previously, possibly a small trading pool like myrmex)

dire wolves, a beefier alternative to the vanilla wolves, and one I would feel more comfortable taking into battle(especially with IaF mobs)

axebeaks, possibly an easier way to cut down taller trees

fire salamanders in the nether that when tamed can boost smelting speed when near furnaces

a homunculus, like a mini iron golem made from clay for the home! or to help you carry things!

little gnomes or brownies that will boost crop growth if you leave them offerings or attract them with a special block

I think it might be nice to have lesser mythical creatures as little pockets of wholesome between the epic adventures.
---

aesthetic tweaks are more to help blend the moods between vanilla and IaF, like new textures for the vanilla armor, so they look as cool as the copper and silver variants.

and maybe being able to put the dragon flowers in pots?

**Comment by BugmanBugman** [comment]
this should be on the suggestion tracker, since this is mainly for issues

**Comment by AppeaseTheBees** [comment]
> this should be on the suggestion tracker, since this is mainly for issues

oh sure! didn't know that suggestion tracker was a thing. ill figure out how to change it. sorry about that
