### ISSUE TITLE
Loading a Gorgon temple hocks up the the game 

### ISSUE THREAD

**Issue by Maxi90909** [Alex-the-666/Ice_and_Fire#3550]
If a Gorgon temple with a Gorgon is loaded the game hocks up allowing you to move but you can't do anything else like interacting with chest also nothing loads like mobs don't move. I have a mod installed called the one prob it is like Hawaila but for 1.16.5 it tells me just in a endless lop waiting for minecraft server Iam not playing on a server but that is normal that is says that. Simply I have to restart my computer because I can't even close minecraft it just won't do load.

These are my mods maybe some are incompatible
[Neues Textdokument.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5977960/Neues.Textdokument.txt)

**Comment by TheBv** [comment]
Sounds a lot like the issue that there was with the dread mausoleum...
Are you certain that it's the gorgon temple and not a structure that might've generated nearby? (You might be able to test this with a lower render distance)

I still feel like the dread mausoleum issue hasn't been fixed it's just a lot less likely to happen. It is probably still the expandTo method that's causing issues but I have no idea how to fix that. I tried a bunch of things but they all caused the structure to generate wrongly. :v

**Comment by Maxi90909** [comment]
It is a Gorgon temple because I was looking for a Desert to find Myrmex I stumbled over a gorgon temple as soon as it loaded the game hooked up. This also happened to me with a Fire dragon nest that was generated. It can’t be A Mausoleum because that loads with no problem or game hook ups at all. By the way this Gorgon temple game hook up happened twice(because of another gorgon temple).Since there is no water in the Gorgon temple anymore the Game hook up, it happens to every loaded Gorgon temple loaded (at least for me) This is why I don’t want to explore because my Minecraft World loads for 15-30 minutes and each time this bug happens I have to load my world new. Also when I load my world new I get send back a bit to the point short before the Gorgon temple. The Gorgon mob works fine no bugs there. But the structure that is the problem. Please Relook all Ice and Fire structures if there are problems please fix. Thank you for your effort and support that means a lot to me. Your Mod lover from Germany Keep up the great work❤️

**Comment by Maxi90909** [comment]
Hey I had had this issue just happened again and I think that this is a bug with minecrafts new world generation. Go check out Chunk pregenrators ,,Known issues and Potential Fixes 1.14-1.16'' the first one tells that that is something with the new modded world generation since 1.16. .This is the exact problem I have. Game generates something, world hook up, still able to do stuff like walking but nothing more.

 https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator
