### ISSUE TITLE
"[main/error]" issue with some things in the ice & fire mod

### ISSUE THREAD

**Issue by Nuhv** [Alex-the-666/Ice_and_Fire#3556]
Hello! i'd create a world map in Aternos server (online server), and i upload the most recently citadel library mod in the folder (the server adds mods in the right directory).

the issue i have is that the server give me some problems when it have to upload the monsters like, pixies, cyclops, hydras, i'd notice that the dragons appears into the world naturally, but the others monsters i'd mention before not, and here is the log:

[15Feb2021 23:23:41.586] [modloading-worker-1/ERROR] [net.minecraft.util.Util/]: No data fixer registered for hydra

and this log appears in red color, additionaly the server show me a log orange, look:

[15Feb2021 23:23:44.852] [main/WARN] [net.minecraft.network.datasync.EntityDataManager/]: defineId called for: class com.github.alexthe666.iceandfire.entity.EntityDreadThrall from class com.github.alexthe666.iceandfire.entity.EntityDreadKnight

otherwise the game can be play, but that things dont appear, however in a single player world map (offline) id see ghost, and hypogrips that not appear in online for example, the problem is only get in online server, maybe a lot of persons said the same to you, but i dont get nothing on internet, can you tell me how to fix that_ :3 very thanks, bye bye!

**Comment by CyberFeast2K** [comment]
That’s just an aternos error, it can’t handle more than 6 big mods
