### ISSUE TITLE
[1.16.5] Tier 3 and above dragons disappearing midair.

### ISSUE THREAD

**Issue by chemicaldawn** [Alex-the-666/Ice_and_Fire#3563]
This is a really strange bug and pretty much unlike anything I've come across in modded Minecraft.
When playing on my multiplayer server, 3 players, including myself, have run into an issue where flying dragons will straight up disappear. Summoning crystals cannot bring them back. It is notable that when they disappear, after you fall from the sky off your dragon, you take no fall damage.
The issue seems to be most prevalent when the server experiences extended lag spikes. It is usually during one of these lag spikes that the dragon will disappear.
I only have one other mod that I know interferes with flying players, and that is RandomPatches. I don't think it has any features that have to do with players riding entities, though.

When the dragons do disappear, trying to locate them by teleporting to them never works. Also, looking into the dragonPositions.dat reveals that the dragon's last known location is in the sky where it initially disappeared. It's almost as if the entities just vanish.

How to reproduce (unreliably, however):
- Play on a laggy server
- Mount a tier 3-5 dragon
- Fly around until you hit a lag spike
- In some cases, the dragon will disappear under your feet and you will fall to the ground, taking no fall damage.

**Comment by lightningjude** [comment]
I have also experienced this issue, it also happens in 1.16.4

**Comment by lightningjude** [comment]
For me it happens when 2 or more players attempt to ride their dragons, if you press shift as if to dismount the dragon, the dragon reappears in spot where it last was and free falls.
Edit: the server doesn’t even lag for me, it just disappears,

**Comment by lightningjude** [comment]
When 2 players tide their dragons at the same time
