### ISSUE TITLE
Hippogryphs and dragons confused between standing and sitting

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#357]
The standing and sitting command are often been confused in these mobs. For dragons, the staff will show in the chat that the mob is "sitting" and for hippogryphs, their sitting animation will display, but the command is actually not confirmed and the mob can still fly away. Goes the same for standing command.

**Comment by AlexModGuy** [comment]
sitting chat messages are no longer in 1.4.0 so this is moot
