### ISSUE TITLE
Bug dragon server 

### ISSUE THREAD

**Issue by AmoVible** [Alex-the-666/Ice_and_Fire#3584]
When an other player take his dargon , i get eject from mine. And other bug:
![unknown](https://user-images.githubusercontent.com/72769825/108776174-54824380-7562-11eb-86c0-cf66a6593fe3.png)

**Comment by AmoVible** [comment]
2.1.5

**Comment by Drebledore** [comment]
Having the same problem with our server same version.

**Comment by Drebledore** [comment]
The problem was optifine. Update to the latest version should fix this.
