### ISSUE TITLE
[1.2.1] Dragons Clipping Through Lairs

### ISSUE THREAD

**Issue by EvilDylan** [Alex-the-666/Ice_and_Fire#359]
I do not like the idea of dragons tunneling up through the earth and destroying all of their valuables. So, in the config I set I:dragonGriefing=1 to only let them destroy weak blocks. A very handy option to have.
This, however, was the result:
![2017-11-19_14 00 48](https://user-images.githubusercontent.com/26489839/32994254-8820da0c-cd32-11e7-9afb-848177a74a28.png)
![2017-11-18_15 46 26](https://user-images.githubusercontent.com/26489839/32994259-935f2266-cd32-11e7-91e7-02ccb6acbdaf.png)
Rather than contently sleeping all day, as I had hoped, the dragons still insisted on trying to fly. But, as they could not destroy any blocks, they instead started phasing through the walls and got stuck in the the solid rock.
Not shown here: The eternal loop of the flapping sound, which plays despite them apparently not moving while stuck like this.

I did not disturb the dragon. I wasn't even sure it was there; I only heard the excessive flapping when exploring a gorgon lair.  I'm not sure what woke it, but something did, and the result wasn't pretty.

I have a few other mods, but none of which should affect this...

**Comment by AlexModGuy** [comment]
should be fixed
