### ISSUE TITLE
Summoning Crystal Does Not TP Dragon

### ISSUE THREAD

**Issue by duke-scott** [Alex-the-666/Ice_and_Fire#3592]
Server:
Minecraft 1.16.5
Forge 36.0.42
Citadel-1.5.3
iceandfire-2.1.5-1.16.4

Client:
Minecraft 1.16.5
Forge 36.0.13
Citadel-1.5.3
iceandfire-2.1.5-1.16.4
OptiFine_1.16.5_HD_U_G6

Fire Dragon Summoning Crystal does not teleport Dragon if the dragon was put into a Dragon Horn between the binding and the usage.

Steps to recreate:
1. bind crystal to dragon
2. put dragon in horn
3. remove dragon from horn
4. attempt to use the summoning crystal

**Comment by duke-scott** [comment]
This still does not work in the new version.  I did not see it in the readme so perhaps it was not included.  Just a bit confused since it was closed.  I am assuming it is not intended behavior.

**Comment by kihgy** [comment]
Because of the huge amount of bugs, Alex decided to plunge the entire github, repost the thread if it still an issue in 2.1.6.
