### ISSUE TITLE
[1.16.5] Crash | No EntityRenderer for Sirens.

### ISSUE THREAD

**Issue by Cixon** [Alex-the-666/Ice_and_Fire#3597]
**NO SUGGESTIONS AT ALL**
_It's not. :)_

**Describe the bug**
Game crashes when trying to render a siren via LittleMaidModRebirth.

**Mod/Forge Version**
[1.16.x] v2.1.5 ICE AND FIRE
[1.16.5] FORGE v36.0.42

**To Reproduce**
1. Install LittleMaidModRebirth via BOTH link [(1)](https://www.dropbox.com/sh/dyvk8hwkejl22qh/AABjtFko9SHBMRorrK8V2zXra/LMML-Forge-1.16.x?dl=0&preview=LMML-Forge-1.16.4-2.3.10.jar) & [(2)](https://www.dropbox.com/sh/qw3xwgupau2jhb0/AACWYqA7ZBZJjHBLzt-NPSFYa/LMRB-Forge-1.16.x?dl=0&preview=LMRB-Forge-1.16.4-2.4.1.jar&subfolder_nav_tracking=1)
2. Install v2.1.5 I&F
3. Spawn a maid in fresh world via egg.
4. Tame with a default cake.
5. Right click maid and choose jukebox button _(first button)_.
6. Scroll down list of rendered entities till you crash.

**Expected behavior**
For sirens to render and not throw an error.

**Screenshots**
N/A

**Additional context**
This was tested in a single player environment, has not been tested on MP.
I&F entities had no issues rendering, it wasn't until I got further in the list the problem occurred.

### LOGS:
[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/6046041/latest.log)  **LINE 3862**
[debug.log](https://github.com/Alex-the-666/Ice_and_Fire/files/6046043/debug.log)  **LINE 11909**
[crash-2021-02-25_16.10.58-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6046049/crash-2021-02-25_16.10.58-client.txt)

**Comment by AlexModGuy** [comment]
fixed
