### ISSUE TITLE
Dragons got randomly damaged and moved [ICE AND FIRE VERSION 2.1.5]

### ISSUE THREAD

**Issue by kihgy** [Alex-the-666/Ice_and_Fire#3601]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
When having a dragon sịting, or moving, it will get hurt after a while, and got randomly moved away. This bug usually happen if you keep multiple types of dragons, and it will kill your tamed dragons.

**To Reproduce**
Probided above.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by BugmanBugman** [comment]
I believe a PR fixes dragons attacking eachother

**Comment by fallenthereaper** [comment]
I have the exact same problem, i think alex fixed on 2.1.6 update.

**Comment by kihgy** [comment]
Yeah it happen even with a single dragon and will evetually kill them with a weird death message, pls fix. Not sure this is caused while the dragon is sleeping
![2021-03-09_15 21 39](https://user-images.githubusercontent.com/54225061/110446787-22d8b300-80f2-11eb-917e-6df8771f424f.png)
