### ISSUE TITLE
dragons not dropping scales

### ISSUE THREAD

**Issue by Dinlop** [Alex-the-666/Ice_and_Fire#3603]
I have already killed more than 5 dragons and it hapenned with all of them. The problem only happened with dragons because when I killed seaserpents it dropped scales

https://user-images.githubusercontent.com/63671976/109236518-a677d300-77c7-11eb-9c64-042a8efc0028.mp4

**Comment by AlexModGuy** [comment]
could not replicate. could I get a modlist?

**Comment by Neko2n** [comment]
I remember having this issue in an older version on 1.16.1, but it fixed itself when I updated to 1.16.2 onwards. Might have been something I removed from my pack, or it might have been fixed in an update; I don't know. I _do_ know that I don't have the issue anymore despite having 253 mods in my modpack, so if needed I can provide a sort of "counter-list" to show what isn't causing the issue.

**Comment by Dinlop** [comment]
> could not replicate. could I get a modlist?

abnormals_core-1.16.4-3.0.6.jar
AI-Improvements-1.16.2-0.3.0.jar
alexsmobs-1.6.0.jar
allthemodium-1.2.0-1.16.4-35.1.13.jar
Architects-Palette-1.16.3-1.1.2.jar
AttributeFix-1.16.4-9.0.5.jar
AutoRegLib-1.6-47.jar
baubles-1.8.5-1.16.4.jar
betterendforge-1.16.4-1.5.0.jar
BetterMineshafts-Forge-1.16.4-2.0.1.jar
branders-spawnermod-1.16.4-1.7.10.jar
byg-1.1.8.jar
chocolate-1.3.0-1.16.4.jar
citadel-1.6.1.jar
Clumps-6.0.0.15.jar
CNB-1.16.3_4-1.2.10.jar
cofh_core-1.16.3-1.1.6.jar
collective-1.16.4-1.53.jar
ColossalChests-1.16.4-1.7.13.jar
comforts-forge-1.16.4-4.0.1.0.jar
CraftTweaker-1.16.5-7.1.0.132.jar
create-mc1.16.3_v0.3e.jar
createaddition-1.16.4-20210207a.jar
CreateTweaker-1.0.0.7.jar
curios-forge-1.16.5-4.0.4.0.jar
Cyclic-1.16.5-1.1.7.jar
CyclopsCore-1.16.4-1.11.1.jar
Desolation 1.0.4b 1.16.5.jar
direbats-1.1.0+1.16.5-forge.jar
DungeonCrawl-1.16.3-2.2.4.jar
DungeonsMod-1.16.3-1.2.20.jar
dungeons_mobs-1.16.4-1.0.3.jar
dungeons_plus-1.16.4-1.1.3.jar
eidolon-0.2.7.jar
endergetic-1.16.4-3.0.0.jar
Extractures(v1.2)_1.16.4.jar
fabric-api-0.29.3+1.16.jar
fins-1.3.1.jar
FletchingTableMod-1.16.4-v1.0.1.jar
flytre_lib-0.2.7.jar
forgery-1.3.3.jar
geckolib-forge-1.16.5-3.0.14.jar
Gobber2-Forge-1.16.5-2.3.48.jar
gunswithoutroses-1.16.5-1.0.8.jar
Hwyla-forge-1.10.11-B78_1.16.2.jar
iceandfire-2.1.6-1.16.4.jar
ImmersiveEngineering-1.16.4-4.1.2-129.jar
ImmersivePetroleum-1.16.4-3.1.0-2.jar
industrial-foregoing-1.16.4-3.2.8.2-6b5c95b.jar
infernal-expansion-forge-1.3.jar
inventorypets-2.0.12.jar
ironchest-1.16.4-11.2.10.jar
ironfurnaces-1.16.4-2.5.6.jar
itemcollectors-1.0.11-mc1.16.5.jar
jei-1.16.4-7.6.1.71.jar
JEITweaker-1.16.5-1.0.1.13.jar
mcw-doors-1.0.2-mc1.16.5.jar
mcw-paintings-1.0.0-mc1.16.4-5.jar
modlist.txt
morezombiev_1.16.4-1.1.jar
MouseTweaks-2.14-mc1.16.2.jar
NaturesCompass-1.16.4-1.8.6.jar
Neat 1.7-27.jar
Omni-1.16.4-1.2.1.jar
OptiFine_1.16.4_HD_U_G6.jar
outvoted-1.16.5-1.1.4.jar
overloadedarmorbar-5.1.0.jar
pandoras_creatures-1.16.3-2.0.1.jar
Patchouli-1.16.4-50.jar
Placebo-1.16.4-4.4.1.jar
polymorph-forge-1.16.5-0.24.jar
Quark-r2.4-305.jar
QuarkOddities-1.16.3.jar
rangers_haven-2.2.1.jar
relics-0.1.7.jar
repurposed_structures-1.16.4-2.3.4.jar
savageandravage-1.16.4-3.0.0.jar
SaveMyStronghold-1.16.4-1.0.jar
SimpleStorageNetwork-1.16.5-1.3.2.jar
SimplyJetpacks2-1.16.4-2.6.6.0.jar
sophisticatedbackpacks-1.16.4-2.2.1.183.jar
SoundFilters-0.14_for_1.16.2.jar
SpartanShields-1.16.4-2.1.1.jar
spiders-2.0-1.16.4-1.0.4.jar
structure_gel-1.16.4-1.7.5.jar
supplementaries-1.16.5-0.9.27.jar
TA2 beginning 1.0.3 1.16.5.jar
the-conjurer-1.16.4-1.0.13.jar
TheAbyss2 1.8.9 1.16.5.jar
thermal_cultivation-1.16.3-1.1.6.jar
thermal_expansion-1.16.3-1.1.6.jar
thermal_foundation-1.16.3-1.1.6.jar
thermal_innovation-1.16.3-1.1.7.jar
thermal_locomotion-1.16.3-1.1.6.jar
The_Undergarden-1.16.5-0.4.5.jar
TinyMobFarm-1.16.4-1.1.1.jar
titanium-1.16.5-3.2.7.jar
toadterror-1.16.4-1.0.0.jar
Toast-Control-1.16.4-4.3.1.jar
tombstone-1.16-6.2.5.jar
toughnessbar-6.1.jar
towers_of_the_wild-1.16.4-2.0.1.jar
TreeChop-1.16.4-0.13.0.jar
upgrade_aquatic-1.16.5-3.0.1.jar
valhelsia_structures-16.0.5.jar
Waystones_1.16.3-7.3.1.jar
whisperwoods-1.16.4-2.0.0.jar
Wyrmroost-1.16.3-1.2.11.jar
XaerosWorldMap_1.12.0.2_Forge_1.16.5.jar
Xaeros_Minimap_21.4.0_Forge_1.16.5.jar
YungsApi-1.16.4-Forge-4.jar

**Comment by Dinlop** [comment]
@Alex-the-666 the problem is still happening

**Comment by TheBv** [comment]
Could you post the log files? This could be related to #3647

**Comment by Dinlop** [comment]
@TheBv @Alex-the-666 https://ln2.sync.com/dl/135b20890/m2rahfxf-envcw2bp-5zuwueic-s3m8e9kb
