### ISSUE TITLE
Hippocampus riding Ice and Fire 2.1.5 1.16.4

### ISSUE THREAD

**Issue by CeratoRaptor** [Alex-the-666/Ice_and_Fire#3604]
I cannot ride my tamed Hippocampus underwater, whenever I try and ride it, it kicks me off immediately. If I ride it above water, it is perfectly fine for a moment, then it goes underwater and I get kicked off.

1. Tame a Hippocampus
2. Submerge it in water
3. Attempt to mount it
3. See error

I expected not to be kicked off upon attempting to ride it.

**Comment by TheBv** [comment]
Please check our version 2.1.6 of the mod the issue should have been resolved in that one.
