### ISSUE TITLE
Tamed dragon griefing with their breath while hunting[ICE AND FIRE VERSION 2.1.5]

### ISSUE THREAD

**Issue by kihgy** [Alex-the-666/Ice_and_Fire#3605]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
So I set my tamed dragons to fly around my base with a homepoint, and everytime it hunts it will destroy the base with its breath, is when its feeding time and the dragon wants to eat

**To Reproduce**
Provided above.

**Expected behavior**
Well, this could apply to wild dragons too: when the dragon is hungry and is looking for prey, it should use its deadly breath attack, but rather, go toward the animal and devour it. This would make it reletively safe to have wandering tamed dragons around your base. Only when it is fighting, would it unleash its full power.

**Screenshots**

**Additional context**

**Comment by AlexModGuy** [comment]
this is a suggestion
