### ISSUE TITLE
Tamed dragons randomly taking damage.

### ISSUE THREAD

**Issue by fallenthereaper** [Alex-the-666/Ice_and_Fire#3606]
**Minecraft Version: 1.16.4
Forge Version: forge-1.16.4-35.1.36
Ice and fire: iceandfire-2.1.5-1.16.4**

My tamed dragons keeps randomly loosing health, at first i thought something was attacking them, but after i check the area&moved them i realized that there was nothing hitting them, one of them had they health dragged down to 4 hearts.
After that, i created a creative world to test, i tamed a dragon and it kept having the same problem, i waited to see what would happen and the dragon died showing up this message: "death.attack.Stuck-damage"
_This happens to all dragons_

![image](https://user-images.githubusercontent.com/79212718/109250046-d4b5dc80-77e0-11eb-81b5-3e8daaa107ac.png)

**Comment by AlexModGuy** [comment]
Seems like another mod that adds "Stuck Damage" Since this doesnt match any death/damage type in ice and fire or vanilla.

**Comment by TheBv** [comment]
This is caused from IaF more specifically the stuckHandler([this](https://github.com/Alex-the-666/Ice_and_Fire/blob/bdd40cfb447e1578c57b5272b8ff0c0707c1c8c4/src/main/java/com/github/alexthe666/iceandfire/pathfinding/raycoms/AdvancedPathNavigate.java#L116 ) and [this](https://github.com/Alex-the-666/Ice_and_Fire/blob/bdd40cfb447e1578c57b5272b8ff0c0707c1c8c4/src/main/java/com/github/alexthe666/iceandfire/pathfinding/raycoms/PathingStuckHandler.java#L241) )
I did look into this last time but I just couldn't seem to recreate the issue (I can't find the old issue right now)
Hopefully with #3632 it might be easier to find out why the dragons are "stuck" in the first place.
The easiest solution would be to just remove the "withTakeDamageOnStuck(0.2f)" but I think sooner or later there might be other issues that might occur when the dragon is "stuck". So removing the withTakeDamgeOnStuck would be a short-term solution.

**Comment by User273407** [comment]
How do I remove the withTaeDamageOnStuck though.

**Comment by TheBv** [comment]
This is something that has to be changed in code and I've implemented a solution to this. 
So you'll have to wait for IaF version 2.1.7 until this gets fixed.
Until then if you make sure your dragons aren't moving/trying to move in any direction before sleeping/sitting this shouldn't happen.
