### ISSUE TITLE
Dragonsteel config values don't apply ingame [2.1.5]

### ISSUE THREAD

**Issue by 04Slash** [Alex-the-666/Ice_and_Fire#3607]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Changing any of the config values for Dragonsteel does not do anything. These include:
* "Dragonsteel Sword Base Attack Strength"
* "Dragonsteel Base Armor"
* "Dragonsteel Base Durability"

**To Reproduce**
1. Change config values (Extremely high Attack Strength, and 1 on Base Durability)
2. Open game
3. Look at tooltips and see the original, unchanged values
4. Attack a mob with dragonsteel and see it does normal damage (so not a tooltip issue)
5. Confirm durability by hitting something

**Expected behavior**
I expect the config changes to change the values ingame.

**Screenshots**
Enjoy this awful image :)
* Configs in the top left - Set prior to launching the game (even though this shouldn't matter)
* Left and middle display Sword Durability and damage (one hit from each sword)
* Right shows armor tooltips
![](https://i.imgur.com/OCUzHeB.png)

**Additional context**
Reopens #3533

**Comment by AlexModGuy** [comment]
fixed
