### ISSUE TITLE
Ice & Fire 2.1.6 - Minecraft 1.16.5 - Forge 36.0.43 - Crash on load due to "no such constructor"

### ISSUE THREAD

**Issue by Jusey1** [Alex-the-666/Ice_and_Fire#3608]
[crash-2021-02-26_00.17.02-fml.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6047519/crash-2021-02-26_00.17.02-fml.txt)

I attached crash log above. I assume it should be there.

**Comment by ModernGamingWorld** [comment]
https://github.com/Alex-the-666/Ice_and_Fire/issues/3609
