### ISSUE TITLE
[1.16.x] I&F v2.1.6 Crash | NullPointerException for Deathworm similar to last siren bug.

### ISSUE THREAD

**Issue by Cixon** [Alex-the-666/Ice_and_Fire#3610]
**NO SUGGESTIONS AT ALL**
_It's not. :)_

**Describe the bug**
Game crashes when trying to render a **Deathworm** via LittleMaidModRebirth.
_(similar bug to #3597 .)_

**Mod/Forge Version**
[1.16.x] v2.1.6 ICE AND FIRE
[1.16.5] FORGE v36.0.42

**To Reproduce**
1. Install LittleMaidModRebirth via BOTH link [(1)](https://www.dropbox.com/sh/dyvk8hwkejl22qh/AABjtFko9SHBMRorrK8V2zXra/LMML-Forge-1.16.x?dl=0&preview=LMML-Forge-1.16.4-2.3.10.jar) & [(2)](https://www.dropbox.com/sh/qw3xwgupau2jhb0/AACWYqA7ZBZJjHBLzt-NPSFYa/LMRB-Forge-1.16.x?dl=0&preview=LMRB-Forge-1.16.4-2.4.1.jar&subfolder_nav_tracking=1)
2. Install v2.1.6 I&F
3. Spawn a maid via egg.
4. Tame with a default cake.
5. Right click maid and choose book button _(first button)_.
6. Scroll down the list of rendered entities till you crash.

**Expected behavior**
For Deathworm to somewhat render and not throw an error.

**Screenshots**
N/A

**Additional context**
This was tested in a single player environment, has not been tested on MP.

### LOGS:
[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/6047777/latest.log)      **LINE 2433**
[debug.log](https://github.com/Alex-the-666/Ice_and_Fire/files/6047778/debug.log)   **LINE 10487**
[crash-2021-02-26_00.24.58-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6047779/crash-2021-02-26_00.24.58-client.txt)

**Comment by Cixon** [comment]
Thank you for fixing siren bug! No issue getting scrolled passed that mob, now I have an issue with getting the Deathworm to render...danggit! :(

**Comment by TheBv** [comment]
Yeah that mob seems to have been overlooked when fixing all the other issues similar to this (like the siren one you mentioned).
I'll create a PR once I've taken a look at some other things.

**Comment by Cixon** [comment]
> Yeah that mob seems to have been overlooked when fixing all the other issues similar to this (like the siren one you mentioned).
> I'll create a PR once I've taken a look at some other things.

I appreciate this!
