### ISSUE TITLE
Forget to remove dragon's homepoint = runaway dragon [ICE AND FIRE VERSION 2.1.6]

### ISSUE THREAD

**Issue by kihgy** [Alex-the-666/Ice_and_Fire#3616]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Take the dragon extremely far and forgot to remove the homepoint, at night your dragon will return to it even at 500 blocks away.

**To Reproduce**
Provided above

**Expected behavior**
If the dragon find itself too far away from its homepoint, it should just rest wherever. The range where it could detect its homepoint should be configurable.

**Screenshots**

**Additional context**

**Comment by kihgy** [comment]
This issue already a problem before this new mechanic, but the dragon doesn't fly that often, but with this new mechanic it will always a thread at night when you forget to remove the homepoint.

**Comment by fallenthereaper** [comment]
Why do you copy paste the text everytime you open a issue...
