### ISSUE TITLE
Banner patterns are invalid [ICE AND FIRE VERSION 2.1.6]

### ISSUE THREAD

**Issue by warning-djkajslh** [Alex-the-666/Ice_and_Fire#3620]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Not sure if it just me, or is it seemed as the banner patterns are all showed up as the invalid texture

**To Reproduce**
Just the banner pattern on a loom

**Expected behavior**
Banner patterns texture is showed.

**Screenshots**

**Additional context**

**Comment by TheBv** [comment]
Are you using any other mods besides IaF? #3037

**Comment by kihgy** [comment]
Yes quite a few

**Comment by CLittleLunaC** [comment]
Do you have Refined storage installed? it seems to be the culprit, I'm having the issue too, and from looking at the other issues posted it seems Refined Storage is the problem

**Comment by kihgy** [comment]
Gotta leave it here as a reference toward RS thread.

**Comment by AlexModGuy** [comment]
^ issue is with refined storage.
