### ISSUE TITLE
Game Crashes when I move/right after world generation (MC 1.16.5) (Ice and Fire 2.1.6)

### ISSUE THREAD

**Issue by MemeLord32** [Alex-the-666/Ice_and_Fire#3627]
The title says it all. It says something about trying to replace the trapped chest with a ghost chest.

This is the crash report:
[Ice and Fire Crashing 1.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6055873/Ice.and.Fire.Crashing.1.txt)

**Comment by MemeLord32** [comment]
When I downgraded these mods back to the versions I had them before, the game stopped having a heart attack right after world gen, so be careful when using these mods:

extended bonemeal (probably not the problem as it messes with bonemeal)
inventorytotem (probably not the problem as well as it just messes with totems)
architectury (FORGE) (Probably the problem, the others are all just tweaks to bonemeal, totems, and a tad bit of drop rates)
all loot drops (probably not the problem cause it just messes with the drop rates)

**Comment by MemeLord32** [comment]
okay. it's not fixed. 

The game crashed whilst unexpected error
Error: java.lang.ClassCastException: com.github.alexthe666.iceandfire.entity.tile.TileEntityGhostChest cannot be cast to net.minecraft.tileentity.TrappedChestTileEntity
Exit Code: -1

[Ice and Fire Crashing 2.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6056408/Ice.and.Fire.Crashing.2.txt)

**Comment by TheBv** [comment]
Apparently it's this mod : https://github.com/HexoMod/Chest-Locator that's causing the issue.
I'll still try to fix it since in theory this shouldn't happen but if you want to play until then you could try remove that mod.
**Update**: this is not an issue with the Ice and Fire mod but instead with the Chest-Locator mod
