### ISSUE TITLE
Unable to make Ambrosia [2.1.6]

### ISSUE THREAD

**Issue by SodiumZH** [Alex-the-666/Ice_and_Fire#3630]
**Describe the bug**
Ambrosia cannot be crafted with the resipe described in the Bestiary.

**To Reproduce**
1. Place golden carrot, golden melon, pixie dust and bowl in crafting table as is described in the Bestiary, i.e.:
   X X X
   carrot dust melon
   X bowl X
2. See error: nothing can be crafted.

**Expected behavior**
Ambrosia should appear in the result box of crafting table after placing the 4 ingredients above.

**Additional context**
https://user-images.githubusercontent.com/46860829/109409902-726ffe00-79d1-11eb-8558-184badf9a85b.mp4

**Comment by TheBv** [comment]
The recipe was changed 9 months ago apparently but it has never been updated in the bestiary for some reason. It only needs one pixie dust and a bowl now.

**Comment by SodiumZH** [comment]
Thank you for the information and update!
