### ISSUE TITLE
Lightning Dragonsteel sword not giving any mob drops [Minecraft 1.16.5 | Ice and Fire 2.1.5]

### ISSUE THREAD

**Issue by angryansari** [Alex-the-666/Ice_and_Fire#3633]
Minecraft: 1.16.5
Modpack: TNP Limitless 3 1.9.5
Modversion: iceandfire-2.1.5-1.16.4.jar

Repeatable: Yes

Tested in creative, Lightning Dragonsteel sword not giving any mob drops or experience when used to kill anything.
Fire and Ice swords work fine, i suspect the lightning bolt effect is causing this. This is not documented anywhere so I dont think this is intended behaviour.

**Comment by TheBv** [comment]
Yeah the lightning bolt seems to be deleting the drops/xp the mob would drop.
The only way I can see this getting fixed is by making the lightning bolt "cosmetic" I don't know about this change though :/
