### ISSUE TITLE
Dragon Skeletons EVERYWHERE [2.1.6]

### ISSUE THREAD

**Issue by SliferFox** [Alex-the-666/Ice_and_Fire#3634]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Extremely common dragon skeletons

**To Reproduce**
Literally just opened a new world in creative mode with I&F v 2.1.6 (MC 1.16.5) and flew around a bit. Within 2 minutes I've found 12+ skeletons within a short distance of each other. I've also got 51 other mods running in the background. So not sure if it's something to do with any of them.

**Expected behavior**
I expected dragon skeletons to be rather rare, and not littering the floor of my world.
In the image below there are 8 skeletons within view. And just over the hill to the top right there are even more.

**Screenshots**
![image](https://user-images.githubusercontent.com/39203273/109432095-36d43480-79cf-11eb-9a30-53f3fb66b569.png)

**Additional context**
The game & mod as a whole runs fine beyond that, just confused/concerned about the huge amount of dragon skeleton spawns.

**Comment by SodiumZH** [comment]
I have only IAF mod loaded. Dragon skeletons spawn much more frequently in 2.1.6 than in 2.1.5 but not as frequntly as yours.
