### ISSUE TITLE
Dragons spawn much less since the last two versions dragons on the surface and underground [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by LeMauval** [Alex-the-666/Ice_and_Fire#3639]
Dragons spawn much less since the last two versions
dragons on the surface and underground

Please help me

**Comment by TheBv** [comment]
This is not an issue but intended behavior.
The new version now makes sure that "dangerous things" (e.g dragons) don't spawn too close to each other
There is a setting called "Dangerous World Gen Dist Seperation" which you can lower if you want.

**Comment by Pyllow** [comment]
yeah im with the same problem , the thing is i tweaked the config file on the "Dangerous World Gen Dist Seperation" and other things to increase the spawnrate but it seems that it has no effect what so ever , after inumerous tests , the dragon spawn rate is still very low , like 5k of walking to find one dragon, and biomes exclusive like lightning and ice sometimes i simply dont find any

**Comment by duke-scott** [comment]
How does the Dangerous separation affect dragon caves, or does it? I am seeing them directly under roosts.

**Comment by Pyllow** [comment]
I was thinking , maybe using a mod like In Control! can fix the problem ? I don't know if mods like that can change something.
