### ISSUE TITLE
No Dragons spawning in 'The Other'

### ISSUE THREAD

**Issue by tuzoli** [Alex-the-666/Ice_and_Fire#3640]
After running around for hours in survival I popped into spectator mode and I still can't find any caves/dragons. There are a lot of bones, but not the living variety.
Done a 2.5k circle around spawn. Should they be spawning beyond that?
Running 'All the Mods' v.1.5.3,  Ice and Fire 2.1.6, Minecraft 1.16.4

**Comment by jeremiahwinsley** [comment]
This is an ATM6 issue, not an Ice and Fire issue.

**Comment by Rutes** [comment]
as I understand it, you need to do some toml file customizations to get dragons to spawn in other dimensions

**Comment by tuzoli** [comment]
Did some testing and I found a random post somewhere saying that you need to travel around 10k in any direction so I did some testing. Found one at around 9k, so they do spawn just extremely rarely. Thank you for the feedback everyone!
