### ISSUE TITLE
Mod Not Working In 1.16+ Due to Experimental Settings

### ISSUE THREAD

**Issue by CHOWHANBOY** [Alex-the-666/Ice_and_Fire#3642]
I have been dealing with experimental settings since i first tried playing ice and fire in 1.16.3 times, but the thing is in 1.16+ you dont have a mod config so you basically cant find a way to turn it off. I just wanna know why is Experimental Settings a thing, And why the Living Hell is it causing for nothing to spawn, like literally you cant even get ice and fire items its that much nonsense. Please remove whatever this experimental settings is....

**Comment by AlexModGuy** [comment]
what do you mean by experimental settings
