### ISSUE TITLE
Scribe villager needs zombie villager skin [ICE AND FIRE VERSION 2.1.6]

### ISSUE THREAD

**Issue by kihgy** [Alex-the-666/Ice_and_Fire#3643]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
When scribe villager got converted into zombie, the skin become invalid

**To Reproduce**
Provided

**Expected behavior**
There should be a zombie skin for scribe villagers that matches with every biomes.

**Screenshots**

**Additional context**

**Comment by TheBv** [comment]
Same as #3641

**Comment by AlexModGuy** [comment]
^
