### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by guitisch** [Alex-the-666/Ice_and_Fire#3646]
hello I created my server with the ice and fire mod , the problem is that when the server loads a dragon my minecraft crash
here is the crash report
[crash-2021-03-03_10.31.59-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6076240/crash-2021-03-03_10.31.59-client.txt)
help me

**Comment by TheBv** [comment]
Minecraft version 1.12 isn't being supported anymore.

**Comment by guitisch** [comment]
......ok

**Comment by fallenthereaper** [comment]
Close this?
