### ISSUE TITLE
Hippogryph kick has insane upwards knockback

### ISSUE THREAD

**Issue by PCAwesomeness** [Alex-the-666/Ice_and_Fire#3648]
**Description:**
Hippogryphs knock their foes very high into the air with their kick.

**To Reproduce:**
1: Spawn a hippogryph near an animal
2: Wait until it attacks the animal
3: See if it kicks the animal

**Expected behavior:**
When the hippogryph kicks the mob, the mob would be expected to be flung a long distance backwards instead of upwards.

**Additional context:**
This bug has appeared and been fixed in the past, but it somehow keeps coming back.

**Comment by TheBv** [comment]
I'd be willing to change this but this is one of the cases in which I'm uncertain of alex' intend :/
If you can link me to the previous issue or a comment from alex I'd change this.
If anyone else is certain on how this hippogryph attack should work let me know!

**Comment by warning-djkajslh** [comment]
Pretty sure this is intended :-)
