### ISSUE TITLE
Jungle Myrmex Staff crashes my game.

### ISSUE THREAD

**Issue by Spngi** [Alex-the-666/Ice_and_Fire#3649]
Whenever right-clicking or shift right-clicking with the jungle myrmex staff it crashes the game.

1. Go to a world with ice and fire installed.
2. Get a Jungle Myrmex staff
3. Right-click with it

It should command Myrmex hatched by the player.

I've seen other people complain about this, and I doubt it's my computer as I have a pretty decent rig and the other mods installed have no similar issue. I've tried with only Ice and Fire with it's dependancies and the problem still persists.

**Comment by SodiumZH** [comment]
Maybe you can firstly try right-clicking with the staff toward a myrmex to "bind" the staff to the hive. After doing this I've been able to use staff correctly (at least it did't crash and showed an UI). It seems that myrmex staff contains a pointer to the binding hive and the pointer is null before bound manually.
