### ISSUE TITLE
Randomly unable to use wooden doors/chests/beds [2.1.6/1.16.4]

### ISSUE THREAD

**Issue by SodiumZH** [Alex-the-666/Ice_and_Fire#3653]
**Describe the bug**
Sometimes wooden doors, chests and/or beds don't work after playing for tens of minutes.
Doors: unable to open, and the texture goes wrong (see screenshot)
Chests / ender chests / beds: nothing happens when right-clicking but with an animation of interaction "use" (waving arm).
Door issue and chest issue may not happen together. The issues happen randomly and disappear after restarting the game. 

**To Reproduce**
These issues happen randomly, mostly after >10 minutes' gameplay.
1. Play the game in survival mode for tens of minutes.
2. Try right-clicking wooden doors, chests, ender chests and beds.
3. See error: they are possibly uninteractable. For doors a texture error happens.

**Expected behavior**
The 4 blocks should be interactable at any time.

**Screenshots**
In the screenshot only door texture error is showed. Even the upper part of the door seems open, the collision doesn't change (unable to throw ender pearl through them).
![2021-03-04_15 09 51](https://user-images.githubusercontent.com/46860829/109938868-73739900-7d0b-11eb-8a7f-a7e94d51d7c7.png)

**Comment by TheBv** [comment]
Would it be possible for you to check if this maybe happens if you go into a certain direction?
E.g walk north/south/east/west and see if after that you can't open chests anymore.
We've had issues like this before caused by the Mausoleums so if you could verify that this has nothing to do with world generation that'd be cool!

**Comment by SodiumZH** [comment]
> Would it be possible for you to check if this maybe happens if you go into a certain direction?
> E.g walk north/south/east/west and see if after that you can't open chests anymore.
> We've had issues like this before caused by the Mausoleums so if you could verify that this has nothing to do with world generation that'd be cool!

I've not found any activity which always causes this issue yet. Riding dragons/amphitheres seems to increase the probability, but sometimes it still goes right after I ride through nearly 10,000 blocks, loading about 5 mausoleums. When I find any pattern of this issue I'll reply this comment ASAP.
