### ISSUE TITLE
Hippogryph flying in 2.1.6

### ISSUE THREAD

**Issue by kihgy** [Alex-the-666/Ice_and_Fire#3658]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
As soon they start flying, they go straight up to heaven

**To Reproduce**
Watch a hippogryph as it start flying

**Expected behavior**
Hippogryph fly normally

**Screenshots**

**Additional context**

**Comment by Psychotopia** [comment]
also getting this

**Comment by takeokuroda** [comment]
yeah even in a new world with just ice and fire, using a hippogryph in the newest version, just tested this.
you start flying in any direction and you just stop and the hippogryph  just starts floating up.
you cant decend at all for about a minute.
tried this on a server and the logs are not saying its lagging or anything so idk, not a code guy, sorry.

also turning is jank, not smooth at all.
