### ISSUE TITLE
Ice and fire mobs dramatically increase invisible glitch

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#366]
Dragons, Hippogryphs, Pixies, Gorgon, dragon eggs and skull all likely to become invisible for a short period of time, especially the dragons, eggs and skulls. They even affect vanilla mobs. I sit down a dragon while working on a villager breeder, after returned from a resource gathering trip, I found all my villagers in the breeder even the dragon become invisible but I can still sense their presence. After a while they become visible again

**Comment by AlexModGuy** [comment]
not able to replicate in 1.4.0
