### ISSUE TITLE
my game for roguelike adventures keeps crashing when i go to use a dragon horn and i have my dragon in it currently [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by FIZZ420** [Alex-the-666/Ice_and_Fire#3661]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kihgy** [comment]
Is this from the RAD modpack?
