### ISSUE TITLE
[Critical Bug] Crash | java.lang.NoClassDefFoundError: iceandfire/pathfinding/raycoms/Node

### ISSUE THREAD

**Issue by Cixon** [Alex-the-666/Ice_and_Fire#3663]
**Describe the bug**
I was playing on my server when my friend wanted to show me a ice dragon cave.
As we arrived, we killed the tier 3 dragon and as I was approaching its corpse, the server crashed.

Additional Context:
I installed a new mod that is very popular among mod-packs and the community in general.
This mod is called AI Improvements which may explain this issue.
It changes a variety of things, list of features can be read [here](https://www.curseforge.com/minecraft/mc-mods/ai-improvements).

Logs:
[debug.log](https://github.com/Alex-the-666/Ice_and_Fire/files/6096480/debug.log) **Line 8252**

**To Reproduce**
1. Install 1.16.5 Forge 36.0.42
2. Install IceAndFire v2.1.6
3. Install [AI Improvements v5-0.3.0](https://www.curseforge.com/minecraft/mc-mods/ai-improvements/files/3031978) ?
4. Spawn a dragon, kill it, see error.

**Expected behavior**
Certainly not a crash lol.

**Additional context**
This happened in a multiplayer environment.

**Comment by AlexModGuy** [comment]
#3938
