### ISSUE TITLE
[Server Hosted] 5GB server cannot handle 2 dragon riders in same area.

### ISSUE THREAD

**Issue by Cixon** [Alex-the-666/Ice_and_Fire#3664]
**Describe the bug**
So this isn't really much of a bug but it is a concern.
5GB should be more than enough for 2 even 5 dragon riders.
TPS on dedicated servers tank, causing severe issues and an unplayable environment in general.

The issue seems to lie with not only movement speed but quite possibly the animations as well.

**To Reproduce**
N/A

**Expected behavior**
Some moderate lag but not a server timed out.

**Suggestion:**
Though, there may not be a solution for now, I'd love a suggestion. _(temporary fix, or existing work around, for now.)_
I think a update to the config to disable player dragon flying or to ~~adjust overall dragon flying speed would help a lot~~.

**Comment by Diggery04** [comment]
I was on a LAN server and every time my friend mounted a dragon while I was on one I would get dismounted or teleported to them. If I was a little ways away from them when they mounted a dragon I would get teleported to them even if I was doing nothing.

**Comment by Cixon** [comment]
> 
> 
> I was on a LAN server and every time my friend mounted a dragon while I was on one I would get dismounted or teleported to them. If I was a little ways away from them when they mounted a dragon I would get teleported to them even if I was doing nothing.

It's pretty concerning, the easiest way to make servers time out just cause there's more than 1 dragon rider the server has to catch up with all the chunk loading.
