### ISSUE TITLE
Hitboxissue

### ISSUE THREAD

**Issue by Murbis1** [Alex-the-666/Ice_and_Fire#368]
Sometimes if my tamed dragon is out of the horn or i fly with him the hitbox get larger and easy to pull. I only can make the hitbox normal again if i use the DragonHorn but it gets anoying slowly. i hope you can fix it 
sincerely Mürbis
(like i sayed earlier sry for my bad english i am from germany)

**Comment by AlexModGuy** [comment]
fixed in 1.3.0
