### ISSUE TITLE
Ice dragon eggs disappear randomly[ICE AND FIRE VERSION 2.1.6]

### ISSUE THREAD

**Issue by Cryolophysis** [Alex-the-666/Ice_and_Fire#3680]
Was hatching ice dragon eggs when all of a sudden they just vanished, no ice dragons popped out, they just disappeared. the hatching process had barely formed ice around the egg when it happened and no ice went into the surrounding water.

on further looking into it, the egg and ice break after a few minutes and no dragon pops out, I have tried in 3x3 open water, 3x3 dragon ice with open water in the middle, every time no dragon pops out

on further further investigation, my multiplayer session crashed and I decided to check if my egg had returned and it did, and finally hatched, not sure whether to leave it here or not as what happened could still be very misleading to many players

**Comment by JuanJoseFerAviotti** [comment]
same
