### ISSUE TITLE
Ice and Fire dragons show duplicate player model in first and third person

### ISSUE THREAD

**Issue by egshels** [Alex-the-666/Ice_and_Fire#3683]
**Describe the bug**
See title

**To Reproduce**
er.. get on the dragon?

**Expected behavior**
Only one playermodel is displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/31183838/110759463-a04c1280-821b-11eb-96ba-a1f7f6e355d3.png)
![image](https://user-images.githubusercontent.com/31183838/110759470-a2ae6c80-821b-11eb-9dbb-3ad00e80534c.png)

**Comment by TheBv** [comment]
Are you using any other mods besides IaF?
I couldn't reproduce this with only IaF installed and not modifying the code.
By not cancelling a forge event I could however reproduce this issue with leads to me believe one of the mods you might have installed might not check if that event was cancelled or not.
If the list of mods you have installed isn't big(less than 10) I'd take a look at it more closely.
And in the case you don't have any other mods installed I don't have any idea what could cause this behavior.
