### ISSUE TITLE
getEntityInAABB Queries Causing Sever Lag [2.1.5-1.16.4]

### ISSUE THREAD

**Issue by Yourname942** [Alex-the-666/Ice_and_Fire#3684]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
It seems something from Ice and Fire is causing a lot of lag with zombie villagers.
"ice and fire's zombie villager getEntityInAABB queries are taking up 20% of the entire server thread"
"it looks like it's doing extra getEntitiesInAABB calls in the zombie villager's ticks (which is expensive)"

**To Reproduce**
1. log into multiplayer server
2. fly around a bit

**Expected behavior**
I expect this mod to not cause so much server lag

**Additional context**
 https://spark.lucko.me/#y9UCQMhEaN and https://spark.lucko.me/#kKKc5uNfLi
 Minecraft 1.16.5
 Forge 36.0.39

latest log:
https://gist.github.com/Yourname942/bde31b791186e757acacbaad0b6e7d08

**Comment by TheBv** [comment]
Amphitheres apparently target entites/players that attack villagers similair to how iron golems would. 
It seems to try find any amphitheaters within the villager's radius that got targeted/hit. 
Until this gets fixed you can reduce the "Amphithere Villager Search Length" that should help tremendously! (cutting it in half should reduce tps issues 8 fold if my math is right)

**Comment by Mondrethos** [comment]
Had the same issue, had to reduce the same value.
