### ISSUE TITLE
No Amphitheres spawning [2.1.6-1.16.4]

### ISSUE THREAD

**Issue by fdaunderer** [Alex-the-666/Ice_and_Fire#3686]
On a dedicated minecraft server, no Amphitheres are spawning. Also not spawning more than 1000 blocks away. 
In the server log you can see, that  AMPHITHERE=false

But in config it should be set to true.

linux system info:
lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.7 LTS
Release:	16.04
Codename:	xenial

java --version
java 14.0.2 2020-07-14
Java(TM) SE Runtime Environment (build 14.0.2+12-46)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)

mods folder:
citadel-1.6.1.jar
iceandfire-2.1.6-1.16.4.jar

[server.properties.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6130769/server.properties.txt)
[config.zip](https://github.com/Alex-the-666/Ice_and_Fire/files/6130729/config.zip)
[ice_and_fire_version.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6130730/ice_and_fire_version.txt)
[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/6130731/latest.log)
[system.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6130732/system.txt)

**Comment by TheBv** [comment]
Try updating to citadel 1.6.2 that fixed some issues with the biome config. Mostly that if there's only two ""biomes"" specified that an entity can spawn in, they wouldn't spawn at all.
