### ISSUE TITLE
Issue with dragon scales

### ISSUE THREAD

**Issue by jglava** [Alex-the-666/Ice_and_Fire#3697]
In a latest mod update I cant seem to obtain dragon scales, i tried killing many dragon of different stages, and of course right clicking with an empty hand (im not using the bottles for blood) I only get a heart and bones, i checked the config and there is nothing to modify related to scales, any help? or is it just me. Thanks

**Comment by Werral** [comment]
ya, I have he same issue. I've killed at least 10 dragons now without a single scale drop.

edit: I just tried a fresh install with only Ice and Fire and JEI. scales drop...so it looks like this is an issue with something else.

Cheers!
