### ISSUE TITLE
Dragonsteel Armor config doesn't work [ICE AND FIRE VERSION 2.1.6]

### ISSUE THREAD

**Issue by Thermolight** [Alex-the-666/Ice_and_Fire#3700]
**Describe the bug**
There's a line in the ice and fire common config called "Dragonsteel Base Armor", the comment above it says it's meant to edit the base value for the dragonsteel chestplate (I assume it would edit the other pieces to match). This line in particular doesn't seem to work in the latest version.

**To Reproduce**
Open "iceandfire-common.toml" config file and find the "Dragonsteel Base Armor" line
Edit the value (default is 12 if I'm not mistaken) to any other number (I originally tried 18).
Start up the game and check dragonsteel armor, it is still at the default despite having changed the config.

**Expected behavior**
Simply put, I expected it to change the armor value of dragonsteel, even just the chestplate, it did not.

**Screenshots**
Original config line and dragonsteel chestplate armor value:
![Screenshot (1)](https://user-images.githubusercontent.com/80745680/111275594-ededc400-85fb-11eb-8648-a79e852cae25.png)
![Screenshot (2)](https://user-images.githubusercontent.com/80745680/111275621-f514d200-85fb-11eb-9f88-dc13bb4461eb.png)
changed config line:
![Screenshot (3)](https://user-images.githubusercontent.com/80745680/111275691-0a89fc00-85fc-11eb-85f6-61d8976b5b93.png)
Dragonsteel chestplate armor with changed config line:
![Screenshot (4)](https://user-images.githubusercontent.com/80745680/111275761-1970ae80-85fc-11eb-8473-3c0121b34439.png)

**Additional context**
I originally discovered this while putting together a personal modpack. I was looking through the config and noticed I could make the sword stronger with a different config line (that one works btw). I wondered if the same was there for the armor and so I found the line addressed in this report, and subsequently discovered this issue. It's not a huge deal but I figured it'd be best to report it since it doesn't seem like anyone else has yet (or at least I didn't find any other reports). To be safe I tested it with nothing more than forge, citadel, and ice and fire itself, the line still doesn't have any effect. Hope I've given enough info.

**Comment by Thermolight** [comment]
sorry for all the edits :/

**Comment by zangucci** [comment]
Having the same problem, Dragonsteel chestplate armor stats don't change.

On the other hand the Dragonsteel sword damage changes just fine.

Also would be nice to see more configs for other armor pieces and weapons (such as the bow or the other dragonsteel armor parts) once this is fixed I guess.

(I'm using 1.16.5 version btw)

**Comment by TheBv** [comment]
Was fixed with  #3968
