### ISSUE TITLE
Tamed Dragon Takes Damage Daily After Feeding Sickly Dragon Meal

### ISSUE THREAD

**Issue by Mewkitty22** [Alex-the-666/Ice_and_Fire#3701]
In the most recent update, I noticed that my tamed Stage 3 Lightning Dragon seemed to be randomly taking damage.

Once a day, it seems, its health will drop from over 200 to 184.

There is nothing else besides it in the cave that I've constructed for it that might be dealing it damage. 

The only thing I've seen comperable to this is the fact that my Ice Dragon, which hasn't yet been fed a sickly dragon meal, does not increase to its new max HP whenever it ticks over to a new day in age. For instance; If the dragon is 5 days old and at 20/20 HP, when it is 6 days old I find it'll be at 20/26 HP or something like that.

This leads me to wonder whether or not my lightning dragon's HP is resetting to the previous age's max HP every time it ticks over to a new 'day'.

If anyone else is experiencing this bug I'd appreciate hearing about it.

**Comment by TheBv** [comment]
This seems like the same as #3606
Especially since the amount of damage the dragons are taking are close to 20% (which is howmuch damage the mentioned issue was causing)
Should hopefully be fixed in the next IaF version

**Comment by Mewkitty22** [comment]
Apologies! I'd looked around before posting, I swear, but I didn't see the post you referenced; otherwise I'd have refrained from making this one.

In it you mention some kind of temp fix. Any idea what steps I'd have to take in order to implement that? It'd be nice to not have to worry about my dragons taking random damage while waiting for the next release.

**Comment by TheBv** [comment]
> 
> 
> Apologies! I'd looked around before posting, I swear, but I didn't see the post you referenced; otherwise I'd have refrained from making this one.
> 
> In it you mention some kind of temp fix. Any idea what steps I'd have to take in order to implement that? It'd be nice to not have to worry about my dragons taking random damage while waiting for the next release.

No worries you couldn't have seen it since that issue was closed. 
Pretty sure if you just make sure that your dragons are sitting/staying with the dragon command staff this shouldn't happen. If it does let me know but from my testing it should be fine
