### ISSUE TITLE
How do I add biomes to the new generation configuration system?

### ISSUE THREAD

**Issue by jamesipod** [Alex-the-666/Ice_and_Fire#3703]
For instance, how would I go about adding Dragon Cave and Dragon Roost generation to the Biomes O' Plenty Biomes, or even in the Mining dimension from Just Another Mining Dimension? I can't find any sort of documentation at all. I'm well aware ATM6 has Dragon generation in other dimensions, but I am unsure on how to replicate that.

**Comment by BugmanBugman** [comment]
This isn’t an issue, this is more of a suggestion. There’s already support for modded biomes

**Comment by jamesipod** [comment]
The issue is that there's no documentation for it. I'm not suggesting any new features, I just require help adding Dragon and Dragon Cave spawns to other dimensions, as other people have asked for clarification also.

**Comment by TheBv** [comment]
https://github.com/Alex-the-666/Ice_and_Fire/wiki/How-to-specify-the-regions-structures-and-mobs-can-be-spawned
