### ISSUE TITLE
No Trolls, Deathworms, Myrmex hives, or Amphitheres are spawning

### ISSUE THREAD

**Issue by Adriborg8** [Alex-the-666/Ice_and_Fire#3713]
No Trolls, Deathworms, Myrmex hives, or Amphitheres are spawning and I don't have any mods that would replace their spawns the only thing that might be doing it is the wyrmroost mod but I don't think it's that because other people use both mods and have no problems with creatures spawning I have no other mods on that spawn modded creatures and I only have mods that add small structures that are uncommon I don't understand why the things aren't spawning since I never go into the ice and fire config. this is on version 1.16.5 and the latest version of ice and fire

**Comment by TheBv** [comment]
Make sure you update to the newest citadel version.
That should fix deathworms, myrmex and amphitheres not spawning.
Trolls are just incredibly rare by default you might want to tweak the chances a bit. The most important one would be the "Troll Spawn Weight". Hope that helps and resolves the issue if not let me know!

**Comment by Adriborg8** [comment]
> Make sure you update to the newest citadel version.
> That should fix deathworms, myrmex and amphitheres not spawning.
> Trolls are just incredibly rare by default you might want to tweak the chances a bit. The most important one would be the "Troll Spawn Weight". Hope that helps and resolves the issue if not let me know!

how do I change the troll spawns I don't go into configs that much? also is a little less common than an enderman a good spawn rate once I learn how to change the stuff

**Comment by Dkhaynes** [comment]
> Make sure you update to the newest citadel version.
> That should fix deathworms, myrmex and amphitheres not spawning.
> Trolls are just incredibly rare by default you might want to tweak the chances a bit. The most important one would be the "Troll Spawn Weight". Hope that helps and resolves the issue if not let me know!

Are you referring to 1.6.2? That's what I'm working now, and still nothing

**Comment by TheBv** [comment]
> 
> how do I change the troll spawns I don't go into configs that much? also is a little less common than an enderman a good spawn rate once I learn how to change the stuff

Go to your minecraft folder into the /config folder and edit the iceandfire-common.toml file. Look for  "Troll Spawn Weight" I'd recommend putting that value to at least 20. 
If you want me to go into more detail as to how mob-spawning works I can do that that.

**Comment by TheBv** [comment]
> 
> Are you referring to 1.6.2? That's what I'm working now, and still nothing

Yeah I'm talking about citadel version 1.6.2 . Are you using any other mods besides IaF? :/ I've just tested everything in a creative world with only IaF(2.1.6) and citadel installed and I managed to find every mob mentioned in this post.

**Comment by Dkhaynes** [comment]
> > Are you referring to 1.6.2? That's what I'm working now, and still nothing
> 
> Yeah I'm talking about citadel version 1.6.2 . Are you using any other mods besides IaF? :/ I've just tested everything in a creative world with only IaF(2.1.6) and citadel installed and I managed to find every mob mentioned in this post.

That may be it, I'm also using Alex's mobs and Better Animals Plus

**Comment by TheBv** [comment]
@Dkhaynes in that case it might just be a game of chance. Alex's mobs as well as Better Animals Plus register all of their mobs as "creatures" and if I understand the minecraft code correctly, minecraft only allows 10 creatures to spawn in a given area(not a 100% sure though). So it might just not spawn amphitheres etc in because the spawn pool is already full. I'll test this myself and if I find any other issues I'll respond once more.
EDIT: Pretty sure the max 10 creatures limit doesn't work like that ^^"
But I can confirm that myrmex, deathworms and amphitheres are spawning while using both mods. Amphitheres just tend to be a bit rarer.
