### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by JohnDBumann** [Alex-the-666/Ice_and_Fire#3714]
Hi, im doing a selfhosted server with me and my girlfriend. I had added the ice and fire mod because i like dragons and orgers and stuff. however, when my gf got near one of the new mobs(think it was a dragon) the server crashed. we have a bunch of other mods, mostly fo aesthetic but we like it. Here is the crash report + the mods(which i believe are in the crash report).
[crash-2021-03-19_20.15.46-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6174667/crash-2021-03-19_20.15.46-server.txt)

**Comment by thecrystalcat** [comment]
same problem here if you were in a biome that spawns lighting dragons then that's the issue

**Comment by TheBv** [comment]
Not enough information since minecraft sadly doesn't supply a lot when the world gen times out.
Closing this for now since there don't seem to be many new reports on this and the worldgen for most structures has changed.
