### ISSUE TITLE
Multiplayer Server Bug Mounting

### ISSUE THREAD

**Issue by Pigpharos** [Alex-the-666/Ice_and_Fire#3717]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Me and my friends have a 1.16.5 server running on Forge 36.1.0.
We installed Ice and Fire, hatched some eggs and tamed them, when we try to ride 2 dragons at the same time, im mounting mine and a friend get to mount yours its gets me "off" my dragon.
I can walk, destroy blocks but my dragon keeps on going like im mounting it. Then if i press shift to unmount teleports me to the dragon... How can we resolve this? 

**To Reproduce**
1. Mount 2 dragons at the same time on a server
2. Get kicked of your dragon
3. See error

**Expected behavior**
I would expect to ride my dragon and my friend wants to ride his dragon too.

**Screenshots**
Can't do a screenshot, the game works like normal but actually its not. You see like tou are unmounted but actually mounted, you cn keep firing ice from dragon at distance, so it's illogical

**Comment by Pigpharos** [comment]
Sorry for my english i suck at it

**Comment by TheBv** [comment]
Are you using Iaf ver 2.1.6? Because this should've been fixed in that version if not let me know.
