### ISSUE TITLE
Crashing when using myrmex staff (1.15.2 singleplayer)

### ISSUE THREAD

**Issue by CrystalDragon14** [Alex-the-666/Ice_and_Fire#3718]
I tried to use a Myrmex Staff on my hive's queen (I had given the workers resin until I had enough rep). When I try to use it after setting it to my queen, it gives me a screen with dirt on it and nothing else, I can't click anything (not sure if this is how it's supposed to look), and when I exit the screen the game crashes. When I went back into the world it said the queen was rouge when I used the staff.
Edit: it's a jungle myrmex

**Comment by AlexModGuy** [comment]
read the pinned issue
