### ISSUE TITLE
Random Server Time Out and Hang (No Error) [2.1.6]

### ISSUE THREAD

**Issue by ItsCliffGaming** [Alex-the-666/Ice_and_Fire#3722]
We keep having an issue on our server, where it will randomly disconnect everyone with the generic "Time Out" message, but no error message is generated. The server will then hang, need to be force terminated and restarted. It appears to happen when generating dragon caves, from what I can tell, but I have no solid proof to back this. But every time this happens, I go into spectator and look underground, and there is always a dragon cave in the loaded chunks. 

Also, it appears that once the server boots back up, that there aren't typically any further issues, with that specific cave. But, more exploring, more hangs, more caves. 

I noticed there was a previous thread about this, that unfortunately hit the cutoff for old discussion that was truncated. Any help or suggestions on this would be greatly appreciated!

**Comment by TheBv** [comment]
Should have been addressed with 3892837
