### ISSUE TITLE
"Dangerous structures" configs are broken. 2.1.6

### ISSUE THREAD

**Issue by OOBluefireOO** [Alex-the-666/Ice_and_Fire#3724]
Adjusting spawn-rate for gorgon temple and mausoleum doesn't do anything. Also "dangerous structures" separation adjustments doesn't work ether. 

This is more easily shown bye adjusting IaF biome configs for temples and mausoleums to something like "forest" rather than "beach"

**Comment by sum-catnip** [comment]
yep, same issue for me
tested with only this mod active, multiple times

**Comment by TheBv** [comment]
The Iaf biome config was updated at some point so this doesn't apply to it anymore.
Spawn rates work for me as well as the dangerous structures separation distance.
Closing as this is quite old now.
