### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by ExodusBF4** [Alex-the-666/Ice_and_Fire#3726]
I have gotten my myrmex hive to 100 reputation, but i am unable to trade with any of them once i hit 100 reputation. 

I right click on any type of myrmex to trade with them, and then the GUI for trading instantly pops up for what seems like a 10th of a second, then vanishes. I am unable to trade with any of my myrmex because of this.

The version i am playing on is 1.16.5, i think i'm using the latest version of ice and fire, i can't tell by the filename in my mods folder, it's confusing.

This is a short video showcasing this issue.
https://drive.google.com/file/d/19zc9mrJnYugFj42Nblo9_SamhuL8lp2X/view?usp=sharing

**Comment by TheBv** [comment]
Will be fixed in the next version #3672
