### ISSUE TITLE
Github project doesn't contain a licensing file

### ISSUE THREAD

**Issue by TheBv** [Alex-the-666/Ice_and_Fire#3727]
There should be a licensing file added to the project to actually know what you're allowed to do and what not. 
Currently you technically wouldn't even be allowed to build the project yourself.

Adding a license file would give a lot of clarity as to what exactly people are allowed to do with the project for instance if they are allowed to publish their own builds of the mods or not.

**Comment by Foxite** [comment]
This website provides some info to help you pick a license (or not): https://choosealicense.com/

If you don't want to make the code available under an open-source license, then that is fine, but it may have some bad consequences if you merge somebody's pull request and they eventually decide they don't like you (which happens surprisingly often). Again, the website explains this problem, and the solution, in more detail.
