### ISSUE TITLE
Aether II Stage 4 and 5 Dragon lairs spawning underneath Islands

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#373]
![2017-12-15_23 10 25](https://user-images.githubusercontent.com/34591880/34067332-997a1ea8-e1f0-11e7-8e7c-f870795362a2.png)
I found this While exploring the Aether in Aether II

**Comment by EnderiumSmith** [comment]
What makes the ore bits glow?

**Comment by EvilDylan** [comment]
There's options in the config specifically referring to the Aether--check those.

**Comment by AlexModGuy** [comment]
aether support not in 1.4.0
