### ISSUE TITLE
Latest ice and fire 1.16.5 [forge 36.0.45]

### ISSUE THREAD

**Issue by FurryApocalypse** [Alex-the-666/Ice_and_Fire#3731]
It's probably global bug and its about connection with other mod.
In wizzard-staff mod you can cast a spell that turns mobs into spawn eggs.
Problem here is that skeletons are counted as mobs aswell so you can kill dragon, take some of stuff and reborn it again by changin last tick of skeleton into spawn egg.
I post this ticket here couse im not  sure should i rather noticed it to wizzard staff creator or ice and fire.

**Comment by vemerion** [comment]
I have now fixed this from my side with a blacklist for the egg spell. You can see the details in the specific commit [here](https://github.com/vemerion/Wizard-Staff/commit/0e152e2bc37e3906d37539eb02a9a9f210609623).

I think you can go ahead and close this issue now.

**Comment by FurryApocalypse** [comment]
> I have now fixed this from my side with a blacklist for the egg spell. You can see the details in the specific commit [here](https://github.com/vemerion/Wizard-Staff/commit/0e152e2bc37e3906d37539eb02a9a9f210609623).
> 
> I think you can go ahead and close this issue now.

Thank you for your fast reaction!
