### ISSUE TITLE
Dragons does fueling animation, but doesnt actually fuel dragonforge [ICE AND FIRE VERSION 2.1.6]

### ISSUE THREAD

**Issue by warning-djkajslh** [Alex-the-666/Ice_and_Fire#3733]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Sometimes when the dragon try to fuel the dragonforge, the progress bar doesnt go up, neither does the actual breath take place.
The dragon seem to still wander as this happen, if it work they will stop

**To Reproduce**
1. Have multiple wander, or sitting dragons around the forge
2. Input stuff
3. Dragons glitched

**Expected behavior**
As soon as the material is input, every dragons will fuel it no matter they are flying or wandering

**Screenshots**

**Additional context**

**Comment by Wyzards** [comment]
This issue is also present in version 1.9.1 for Minecraft version 1.12.2.

**Comment by gh0stf1sh** [comment]
Can confirm nobody is able to make dragonsteel or get the forges to even power in the first place on a 1.12.2 server we are on

**Comment by TheBv** [comment]
Closing in favor of #4231
