### ISSUE TITLE
Myrmex staff crashing game

### ISSUE THREAD

**Issue by Oriansenshi** [Alex-the-666/Ice_and_Fire#3735]
I run a 1.16.4 SMP and one of my players just made a Myrmex staff, and whenever he tries to use it, the server lags for a moment, and he gets kicked from the server. Has anyone else had this problem? He has been able to replicate it multiple times, and he sent me his crash report. 
[Myrmex_Staff_Crash_Report.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6198038/Myrmex_Staff_Crash_Report.txt)

**Comment by Pilotsilver8773** [comment]
I have been getting this problem as well, I have no idea how to fix it and I cant find anything on this issue. If you find anything helpful on this subject pls message me.

**Comment by TheBv** [comment]
Fixed in #4245
