### ISSUE TITLE
Werewolf Suggestion:

### ISSUE THREAD

**Issue by Telev1s1on** [Alex-the-666/Ice_and_Fire#3737]
Now I know your not doing anything with werewolfs right now but when you are gonna be working on them make it so silver weapons or tools weaken werewolfs, and you shouldn't be cured from getting killed by a silver sword, curing your self with wolfsbane makes more sense, probably make wolfsbane rare and probably make the chance of getting infected with lycanthropy rare as well, also getting cured by dying from a silver sword would suck if your in hardcore,that's another reason for why getting cured by a silver sword or blade is dumb.

**Comment by TheBv** [comment]
https://github.com/Alex-the-666/Ice-and-Fire-Suggestions
