### ISSUE TITLE
Ice Spikes Stacking, getting in Dragonforge way [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by Chesnutthouse** [Alex-the-666/Ice_and_Fire#3738]
**Describe the bug**
The issue i'm encountering is that when an ice dragon breathes  into the forge, the ice spikes start to stack, and because of that, they get in the way of the dragonforge and the dragon will stop fueling it. ultimately not a big deal, i found some workarounds, but it is something to be aware of.

![image](https://user-images.githubusercontent.com/81349090/112521534-daf49580-8d59-11eb-84f6-33a66fe34efb.png)

**Comment by k1r0s** [comment]
can you elaborate on the workarounds? im unable to make it work :)

**Comment by k1r0s** [comment]
So I found my way by leading a drag with a chain to a bone wall, putting all the gound next to the dragonforge with dragon bone blocks which does not freeze nor produce ice spikes. Telling him to sit is also better
