### ISSUE TITLE
Ticking entity [2.1.6-1.16.4]

### ISSUE THREAD

**Issue by Yourname942** [Alex-the-666/Ice_and_Fire#3739]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
MyrmexAIStoreItems or WorldGenMyrmexHive$Room crashed our multiplayer server

**To Reproduce**
1. explore the world
2. crash

**Expected behavior**
Mob AI or spawner AI should not cause crashes

**Screenshots**

**Additional context**
Minecraft 1.16.5
Forge 36.0.46
Crash Log:
https://gist.github.com/Yourname942/cbc57be5db68d82b098bcfdb39df0035
Latest Log:
https://gist.github.com/Yourname942/fddb93e53a75c68230f344ee010b8bac

**Comment by TheBv** [comment]
Fixed with b5d45ee
