### ISSUE TITLE
Ghost Issue w/ Drops / vulnerability[ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by JonaryK** [Alex-the-666/Ice_and_Fire#3740]
Issue Description:
Playing on Valhesia 3 1.6.5, and added Ice and Fire. Ghosts on this aren't dropping ectoplasm or ingots, and I can hit them with Vanilla iron sword. I've killed at least 50 so don't think its a drop rate issue (particularly for ectoplasm).
Doesn't work with normal ghost spawns, from cursed chests, or from graveyard soil.

**Comment by TheBv** [comment]
Ghosts spawned from chests don't drop anything. Otherwise they use minecraft's default loot table system which should always work.
