### ISSUE TITLE
Myrmex Trading Menu refusing to stay open [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by TempAccount693** [Alex-the-666/Ice_and_Fire#3741]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
After earning sufficient reputation and going to a Myrmex Hive, when left-clicking any Myrmex, the trade menu briefly opens for less than a second and then disappears, making it impossible to actually trade with them. This has also been confirmed to be the case with Queens, Sentinels, Soldiers, Workers, and Royals. It recurs in the same world in both Survival and Creative Mode. 

**To Reproduce**
1. Go to a Myrmex Hive with sufficient reputation.
2. Left Click on any Myrmex 
3. See error

**Expected behavior**
I expected the trading menu to remain open until I pressed the escape key to exit, similar to how trading with villagers work. 

**Screenshots**
![ezgif com-gif-maker](https://user-images.githubusercontent.com/81407858/112598052-6adf2180-8de4-11eb-8a5d-9e719d9011f1.gif)

For context, this bug was so fast that I had to slow down the video speed by a factor of .25. I also had to remove the audio during the process, but it only featured the ambling sounds of Myrmex and my mouse clicking as I pushed the left button. 

**Additional context**
Saving and quitting to title then re-entering the world does not fix the error. Neither does restarting minecraft entirely.

**Comment by TheBv** [comment]
Will be fixed among other things in the next release  #3672

**Comment by Octo-chan** [comment]
It's still happening, Is there a version I could switch to fixing this bug without getting my world destroyed?

**Comment by TheBv** [comment]
Version 2.1.7 fixed it version 2.1.8 should be completely stable!

**Comment by Octo-chan** [comment]
Okay, and just to be sure, I can just switch the version without my world getting destroyed?
