### ISSUE TITLE
Dragons do not drop corpses in Aldim

### ISSUE THREAD

**Issue by GamingMidi** [Alex-the-666/Ice_and_Fire#3745]
For some reason when we kill any type of dragon from this mod, their corpses do not drop like usual, they just die like a normal mob, not dropping any loot.

To reproduce it afaik, download the modpack I'm playing (Aldim) from technic and I guess just kill a dragon in survival.
Maybe with modded weapons such as an emerald sword or a bow with enchantments and diamond arrows? I'm not sure.

I obviously expect the dragons to drop corpses so you can actually loot them, otherwise what's the point in killing them?

Quick note: This is 1.12.2 using Ice and Fire 1.7.1, Mods list can be found here: https://pastebin.com/qUZUzQmb

**Comment by AlexModGuy** [comment]
1.12.2 not supported
