### ISSUE TITLE
THIS MOD NOT AT FAULT ANYMORE. CAN DELETE THIS mouseclick event crash when entering world menu w/o any save files [iceandfire-2.1.6-1.16.4] Minecraft: 1.16.5

### ISSUE THREAD

**Issue by HoovySimulator2** [Alex-the-666/Ice_and_Fire#3746]
**Describe the bug**
Every time I try to go to the world menu it crashes. I recently changed from 1.16.4 to 1.16.5 and this was the first problem to occur. I don't have any save files.

**To Reproduce**
Go to world menu. Preferably without any saves. Crash.
New: Go to resourcepack menu and exit. Crash.

**Expected behavior**
I should be greeted with world creation menu. As there isn't any saves.

**Additional context**
Crash log here: https://pastebin.com/DfG8YjVX

The crash log mentions Immersive Engineering, but that was confirmed to not have anything major to do with this. Also note the amount of mods. That means it's very likely that this mod also isn't at fault.

As I use the CurseForge desktop launcher/loader thing, I simply created a new profile for 1.16.5 meaning that anything from 1.16.4 shouldn't have come over. At least any I know of.

Edit: almost forgot, disabling the mod for some reason wont help.

Edit 2: Found out that game crashes when going and exiting resourcepacks menu.

**Comment by TheBv** [comment]
Could you try go into your minecraft config folder and open the "iceandfire-client.toml" and change the "Custom main menu" from true to false? That should hopefully fix the issue. 
~~If it does: this is some weird issue that arises if multiple mods try to override the main menu background. I haven't looked into it too much since you can just disable the background. 
EDIT: I think this might actually be quite easy to fix I'll give it a shot~~

**Comment by HoovySimulator2** [comment]
I will try, thanks for fast reply!

**Comment by HoovySimulator2** [comment]
The game crashed whilst mouseclicked event handler
Error: java.lang.NullPointerException: mouseClicked event handler
Exit Code: -1

Didn't work.

**Comment by HoovySimulator2** [comment]
Found out a single mod that was causing the issue. Thanks for help. Btw for context why I in the first place came here was that the author of Immersive Engineering found that Ice and Fire was mentioned in the crash log. Next time I will do more testing before reporting.
