### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by NiceClown** [Alex-the-666/Ice_and_Fire#3747]
AI issue
https://clips.twitch.tv/CrepuscularRelatedCobraFutureMan-lu3daXtHm-WKyBrb        (muffle it, pls)
When killed, the dragon does not fly up ((
1.16.4
Iceandfire-2.1.6-1.16.4

**Comment by TheBv** [comment]
Will be fixed in the next version #3691
I do want to improve on my current implementation though.
