### ISSUE TITLE
Level 4 and 5 dragons destroying Corpses from Corpse mod

### ISSUE THREAD

**Issue by Oriansenshi** [Alex-the-666/Ice_and_Fire#3748]
I run a multiplayer server and one of my players is having an issue with level 4 and 5 dragons consistently destroying her corpse. I tried setting the corpse itemid on the destruction blacklist, and still no luck. I have confirmed with the developer of the corpse mod that the corpses should be indestructable blocks, and that i have the correct itemid on the blacklist. Is there something i am doing wrong?

**Comment by TheBv** [comment]
Should have been fixed with 3c52775
