### ISSUE TITLE
Missing Dragon Caves?

### ISSUE THREAD

**Issue by ashlynpg625** [Alex-the-666/Ice_and_Fire#375]
Hello! Maybe this is or isn't an issue, but in all of my games, I haven't been able to find a single dragon cave/lair. There are an ABUNDANCE of roosts.. but never a single cave. If the issue is that I'm not looking in the right place, could you tell me if there are any indicators or signs that there's a cave nearby? Or maybe it's a mod conflict? I'll provide the current mods I use in my game. I look and search everywhere and there just aren't any. Are they rare, so this would be normal? Thank you for any help or answers I get because I've lost all hope. 

MODS:
-Aether 
-CFM (I personally do not know what this means but it's in there)
-CoralReef
-ExtraUtils
-Ice and Fire
-LLibrary
-More Player Models
-Overpowered Inventory
-Rope Bridge
-Tough as Nails
-Waypoints
-WorldEdit

**Comment by EvilDylan** [comment]
CFM means Crayfish Furniture Mod, better known as Mr. Crayfish's Furniture Mod.
There's no real indicator for a nearby dragon caves other than the sound of a dragon if it happens to wake. However, they are large, egg-shaped structures underground, so they should be quite easy to spot if you dip into the earth on Spectator mode.

**Comment by ashlynpg625** [comment]
@EvilDylan 
Thank you! I completely forgot that it was Crayfish Furniture Mod XD Must've slipped my mind. 
As for the suggestion to use Spectator Mode.. I never thought of that! I'll certainly try that. Thank You!

**Comment by ashlynpg625** [comment]
I finally found one! This issue is now closed!
