### ISSUE TITLE
Lightning dragonforge craftweaker[2.1.6 on 1.16.5]

### ISSUE THREAD

**Issue by dupciak2137** [Alex-the-666/Ice_and_Fire#3752]
How to change recipes in LIGHTNING dragon forge?
I can change in ice and fire forges but lightning for some reason is not working.
Here is example 
mods.iceandfire.recipes.removeLightningDragonForgeRecipe(<iceandfire:dragonsteel_lightning_ingot>);

**Comment by AlexModGuy** [comment]
craft tweaker will no longer be supported, we will move to JSON come 2.1.7
