### ISSUE TITLE
Lag and World Corruption [2.1.6]

### ISSUE THREAD

**Issue by Verquinox** [Alex-the-666/Ice_and_Fire#3755]
**Describe the bug**
Occasionally, the game will begin lagging like crazy, and when I re-log, the world struggles to load chunks and eventually completely gives up. When running on a server with a world like this, it will crash the moment someone logs in.

**To Reproduce**
1. Load up a world
2. Play in it for a while (time varies)
3. See error

**Expected behavior**
No lag/corruption/crash. 

**Screenshots**
Crash report for one of the post-corruption crashes of the dedicated server:
[message (3).txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6247132/message.3.txt)

**Additional context**
This issue is extremely inconsistent which has made it very difficult to track down and reproduce, though it has happened to several singleplayer worlds and a server I was running. As a result, I cannot be 100% sure it is Ice and Fire that was causing the problem since we are running many other mods on the server, (mod list in crash report) though from my digging, Ice and Fire's worldgen seems the most likely culprit. It could also very well be a compatibility issue with some other mod.

**Comment by Verquinox** [comment]
The crash report that I got looks nearly identical to the one from this issue which was closed and supposedly fixed:
https://github.com/Alex-the-666/Ice_and_Fire/issues/3077
I don't know if that's significant at all, but I thought it was worth mentioning.

**Comment by TheBv** [comment]
Should be resolved since how structures are generated was updated.
