### ISSUE TITLE
Fun with Time In A Bottle and eggs

### ISSUE THREAD

**Issue by CloWnicide** [Alex-the-666/Ice_and_Fire#3756]
**Describe the bug**
Using the standalone Time In A Bottle item on a dragon egg causes multiple hatchlings

**To Reproduce**
1. Place egg and wait for wiggles
2. Use Time In A Bottle to the max tick accelerate
3. Profit with at least 10 dragon hatchlings

**Expected behavior**
Not hatch over 20 dragons from a single egg

**Screenshots**
https://imgur.com/yhZOZ2C

**Comment by CloWnicide** [comment]
Went into my base and see even more of them...

https://imgur.com/RmNHud8

**Comment by TheBv** [comment]
Fixed in cc380e2
