### ISSUE TITLE
Hippogryph is extremely buggy

### ISSUE THREAD

**Issue by Notthatbadsoup** [Alex-the-666/Ice_and_Fire#3762]
Whenever I stop pressing keys my hippogryph will get stuck in the air and move at a snails pace. I don't know how to get unstuck when this happens except just wait it out. It will also start drifting in the wrong direction or move way too much in one direction that I tell it to.

**Comment by MrSpeakeasy** [comment]
Me and my wife are running into this same problem. It's happening with all of the mounted creatures from Ice and Fire, the hippogryphs, hippocampus, the dragons, all of them behave very strangely to the point of being unusable. We've tried disabling all other mods but that does not fix it so I can only assume that it's a problem with the Ice and Fire mod itself.

**Comment by TheBv** [comment]
@MrSpeakeasy are you certain that this happens with all of the creatures? I can definitely confirm that this was an issue for hippogryphs for which a PR was accepted (#3672) but I haven't had this issue with dragons or Hippocampi.
