### ISSUE TITLE
Texture not rendered on Dragon, when punched game crashed

### ISSUE THREAD

**Issue by zachsai** [Alex-the-666/Ice_and_Fire#3763]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.
https://pastebin.com/vwFswDF1
![2021-04-03_17 21 56](https://user-images.githubusercontent.com/63996164/113496573-f170be80-94c8-11eb-98a0-4b6125d1106d.png)
looked like this but for an ice and fire dragon
latest 1.16.5 version
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by TheWitherlord** [comment]
Having the same issue, what other mods do you have installed by chance?

**Comment by AlexModGuy** [comment]
#3938
