### ISSUE TITLE
crash with epicfight mod [iceandfire-2.1.6-1.16.4]

### ISSUE THREAD

**Issue by R3ntora** [Alex-the-666/Ice_and_Fire#3765]
i noticed a crash issue occuring with the epic fight mod. normally the author of the epic fight mod made the 2 mods to be compatible, altho i've ran into an issue that seems to come from ice and fire and the author asked me to post the log here for help. basically, everytime i hit a mob with an ice weapon in fight mode, the game crashes, this doesn't happen to other people.

**To Reproduce**

i just hit a mob with an ice weapon in fight mode, both mods are updated to their latest version as well as citadel.

**Expected behavior**
the mob dying and me playing happily on my minecraft world slashing dragons with my ice sword looking like a total badass.

i can hit mobs with other weapons without an issue 

https://user-images.githubusercontent.com/81931199/113625185-9c4ebd00-962e-11eb-9a9d-b89c59dc620c.mp4

here's a video of the issue, when it freezes it's because the game shut down

https://user-images.githubusercontent.com/81931199/113624737-031fa680-962e-11eb-9f2a-2b65a3bc27bb.mp4

and here's the log of the crash 
[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/6260572/latest.log)

**Comment by TheBv** [comment]
Was never an issue with ice and fire. Seems to have been fixed in by the epic fight mod in [this](https://github.com/Yesssssman/epicfightmod/commit/bf011c1000217fa24c2b692d4ccd4a5d30f86eed) commit.
