### ISSUE TITLE
pixie jars have extremely long sound range [2.1.6]

### ISSUE THREAD

**Issue by Jackiecrazy** [Alex-the-666/Ice_and_Fire#3770]
**Describe the bug**
Pixies in jars will continue to play sounds even if you are very far away from them. I'm not certain of the precise range, but I can hear them giggling in my jungle treehouse from bedrock level, so it's at least 60-some blocks.

**To Reproduce**
1. Place several pixie jars at sea level
2. Fly down to bedrock level, and wait for the sounds to play

**Expected behavior**
Pixie jar sounds should have a much shorter maximum range, perhaps 4-5 blocks.

**Comment by ellektrikk** [comment]
for me no matter what i hear pixies everywhere once i put them in bottles

so i turned off block and friendly creature sounds just to get them to stop
cause they NEVER STOP its constant giggling and HEYs

**Comment by TheBv** [comment]
This will be fixed in the next release #3626

**Comment by AlexModGuy** [comment]
^
