### ISSUE TITLE
game crashes a few minutes after entering a world [2.1.6]

### ISSUE THREAD

**Issue by Quadruplay** [Alex-the-666/Ice_and_Fire#3771]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
game crashes randomly, the log says it's this mod's ghost's fault, i presume there's a cemetery nearby that is spawning ghosts, bc it's night

**To Reproduce**
i just go into a world and it crashes after a few minutes

**Expected behavior**
it shouldn't crash ig

**Screenshots**
not a screenshot per se, but idk where else to put the crash log
https://pastebin.com/WUEy50si

**Additional context**

**Comment by AlexModGuy** [comment]
#3938
