### ISSUE TITLE
Random damage to tamed dragons?

### ISSUE THREAD

**Issue by 0Charm0** [Alex-the-666/Ice_and_Fire#3772]
dont worry i fixed it lmao

**Comment by Lashriel** [comment]
You know that thing where you try to find the answer to a problem you're having, and every thread is just "Nvm I fixed it" without the answer?

Doesn't it piss you off when that happens?

... Yeah, don't do it to other people. Please, tell us *what* you did to fix it for yourself just in case the same thing works for someone else.

**Comment by Virtualhel** [comment]
> You know that thing where you try to find the answer to a problem you're having, and every thread is just "Nvm I fixed it" without the answer?
> 
> Doesn't it piss you off when that happens?
> 
> ... Yeah, don't do it to other people. Please, tell us _what_ you did to fix it for yourself just in case the same thing works for someone else.

I believe this issue was fixed in the most recent update to Ice and Fire (2.1.7), so that may be helpful for you to know.
