### ISSUE TITLE
Banner Patterns [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by Adowg565** [Alex-the-666/Ice_and_Fire#3773]
All of the banner patters are not showing and just turns the banner black regardless of whatever dye I use. It is only with the patterns this mod adds the normal Minecraft patterns and another mod I use “Additional Banners” patters do not do this.
![2021-04-08_18 29 00](https://user-images.githubusercontent.com/82189698/114115909-952ae780-9898-11eb-8281-5ad9312417ac.png)
![2021-04-08_18 28 39](https://user-images.githubusercontent.com/82189698/114115918-9825d800-9898-11eb-920d-0a3efa176c6c.png)
![2021-04-08_18 29 12](https://user-images.githubusercontent.com/82189698/114115922-9a883200-9898-11eb-8265-a742ece7267b.png)

**Comment by AlexModGuy** [comment]
issue is with refined storage

**Comment by Adowg565** [comment]
What's that, like the mod because I don't have the mod.

**Comment by wilyank** [comment]
I have the same problem in a modpack, also without the refined storage mod.
