### ISSUE TITLE
Desktop works great, server doesn't iceandfire-2.1.6-1.16.4

### ISSUE THREAD

**Issue by astrostl** [Alex-the-666/Ice_and_Fire#3776]
1.16.5-forge-36.1.0 + citadel-1.6.2 + iceandfire-2.1.6-1.16.4

Seems to work great locally in single player mode. On a server which worked fine with other mods I can connect and attempt to play, but things like spawn eggs do nothing. The server has no errors and I've wiped the config and world clean.

1. Install I&F on a clean desktop
2. Install I&F on a clean Linux server
3. Connect to the server and attempt to spawn I&F dragons

Any suggestions?

**Comment by AlexModGuy** [comment]
#3938
