### ISSUE TITLE
My own dragon despawned 

### ISSUE THREAD

**Issue by bryan161** [Alex-the-666/Ice_and_Fire#3777]
Well, I commanded him to follow me around and the its just dissapeared. It started fly around me and the Its dissapear. Or teleported. Cause I have GUI followers mod installed and it says like the dragon pass from being 10 blocks away from me to 8000 blocks away from me. He never back, even at sleep schedule

**Comment by kintyj** [comment]
Same thing just happend to me, had my first dragon following me then bam gone. I JUST SPENT AN HOUR getting her to stage 2 and poof gone. I dont have GUI followers installed, but i did have a summoning crystal linked to her but it did nothing.

**Comment by TheBv** [comment]
Closing in favor of #3870
