### ISSUE TITLE
Dragon FoodUtil crash [iceandfire-2.1.6-1.16.4]

### ISSUE THREAD

**Issue by TheWitherlord** [Alex-the-666/Ice_and_Fire#3778]
**CRASH REPORT**
Note this crash report was taken specifically from my Modpack on both singleplayer and multiplayer server.
https://gist.github.com/TheWitherlord/471d9770feb392e6f7612fcdff1b9d71

**Describe the bug**
Sometimes when a dragon is near, or even not near you, the game will crash.
Seems to happen randomly.

**To Reproduce**
1. Download Ice and Fire
2. Load a world in singleplayer or multiplayer
3. Find a dragon
4.  Wait to see if the game will crash.

**Expected behavior**
Expect the dragons to not crash when eating or whatever.

**Comment by Cixon** [comment]
OH! I see this was fixed. I'm now closing my issue #3876 . Sorry!
