### ISSUE TITLE
Hyppogriph flying system

### ISSUE THREAD

**Issue by Mikeice** [Alex-the-666/Ice_and_Fire#3781]
There is an issue with the flying system with hyppogriph, I'm playing the 1.16.5 minecraft version
At the first time I press the space-bar its goes up, but when i try ti press the X key to go down, it doesnt work for a long time, and when that happend going in any direction doesnt work at all, prasing the buttons a few times let it work, only if iam holding the forwdward button, I can up and down normaly, but in the moment I hold up the button it stucks in the place, in some times if i was freeze in a place and press up, it goes up but very slowly, but I just press up and dont hold it.

[Video](https://drive.google.com/file/d/10L91TKN0ViCdi7Igtbj_cAAEnNQ06B86/view?usp=sharing)

**Comment by JamiesMC2312** [comment]
Same issue here with "iceandfire-2.1.6-1.16.4". Impossible to control it while mounted. Trying to go ahead, it takes 30 sec to go, trying going down to land, same, game not laggy, 20 mods on.
