### ISSUE TITLE
Dragon destruction manager crashes my game

### ISSUE THREAD

**Issue by ImPickleJeff** [Alex-the-666/Ice_and_Fire#3783]
Game crashes randomly, checked latest log and last thing I could understand was that the iceandfire dragondestructionmanager was causing my game to crash. I disabled dragon griefing entirely in my config so I'm not sure if that's what caused it. 
[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/6292367/latest.log)

**Comment by AlexModGuy** [comment]
#3938
