### ISSUE TITLE
Myrmex queen stops laying eggs [ICE AND FIRE 1.12.2]

### ISSUE THREAD

**Issue by ONIZeus117** [Alex-the-666/Ice_and_Fire#3786]
My Myrmex Queen climbed the wall of her nest and when I pushed her off the wall she quit laying egg. How do i fix this issue?
Even after giving her wheat she still wont lay eggs. All her workers and soldiers died to mobs outside of the hive.

I expected the Queen to lay eggs no matter what.

**Comment by Spydrouge** [comment]
I have also had a random wild Myrmex Queen stop laying eggs in 1.12.2. She now has no workers, soldiers, sentinels, etc. 

If one enters creative mode and kills the Myrmex Queen and summon or use a spawn egg to make a new Myrmex Queen for the hive, that Queen will also never lay eggs. 

If you take those Myrmex Queens out of the hive and expose them to the surface, they will not dig down to create a new hive, but this is likely the fault of RFTweaker's 'stop Queen hive spam' patch.

Queens will still attack you if approached, indicating the if-check for laying eggs is either being entirely bypassed, or, alternatively, an air block is not being found suitable. 

Her eggTicks are increasing; it can be seen in an NBTFileExplorer. Also visible in the NBT: The Myrmex does have a hive, and of course is at growth stage 2. If you use a staff, you can see that there are about seven or so rooms in the hive, so it's not a population cap problem, and the hive is of course set to 'enable reproduction.'

The only additional thing I can think of that might be relevant is that early on the game, around the same time she stopped laying eggs,  there was a strange moment where she was near a freshly hatched royal and there was a heart particle effect around her, which doesn't seem to make any sense. Somewhere around that time she also stopped laying eggs. 

However after replacing that queen with another queen, the new queen wont lay. Which seems to suggest that the error is coming from one of the accessor functions used to talk to the hive, such as hive.repopulate(); 

Is it possible the hive is getting confused about how many members it has, or how many rooms it has, and thinks its reached some kind of pop cap?

(I also was unable to trade with the queen or any hive member after hitting 25 reputation (After spawning in a bunch of random workers to take the resin chunks); no trade interface ever opened, but I have yet to research if that was a separate, unrelated problem)
