### ISSUE TITLE
dd

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#379]
sd

**Comment by Rutes** [comment]
Similar errors reported on #383 and #384 

I am also getting crashes when attempting to start a forge server - without any other mods present except Llib.

> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   llibrary (llibrary-1.7.9-1.12.2.jar)
> Contact their authors BEFORE contacting forge
> 
> // I feel sad now :(
> 
> Time: 1/1/18 1:03 PM
> Description: Exception in server tick loop
> 
> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ice and Fire (iceandfire)
> Caused by: net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/particle/Particle
> 	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
> 	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:584)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
> 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
> 	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)
> 	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
> 	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/particle/Particle
> 	at java.lang.Class.getDeclaredMethods0(Native Method)
> 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
> 	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
> 	at java.lang.Class.getMethods(Class.java:1615)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:81)
> 	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
> 	... 32 more
> Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.Particle
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 38 more
> Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@3f2049b6 from coremod FMLCorePlugin
> 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
> 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
> 	... 40 more
> Caused by: java.lang.RuntimeException: Attempted to load class btf for invalid side SERVER
> 	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
> 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
> 	... 42 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.12.2
> 	Operating System: Linux (amd64) version 4.10.0-40-generic
> 	Java Version: 1.8.0_151, Oracle Corporation
> 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 2142658792 bytes (2043 MB) / 2595749888 bytes (2475 MB) up to 19088801792 bytes (18204 MB)
> 	JVM Flags: 2 total; -Xmx20480M -Xms2048M
> 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> 	FML: MCP 9.42 Powered by Forge 14.23.1.2582 6 mods loaded, 6 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 
> 	| State | ID         | Version      | Source                      | Signature                                |
> 	|:----- |:---------- |:------------ |:--------------------------- |:---------------------------------------- |
> 	| UC    | minecraft  | 1.12.2       | minecraft.jar               | None                                     |
> 	| UC    | mcp        | 9.42         | minecraft.jar               | None                                     |
> 	| UC    | FML        | 8.0.99.99    | forge.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UC    | forge      | 14.23.1.2582 | forge.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UC    | llibrary   | 1.7.9        | llibrary-1.7.9-1.12.2.jar   | None                                     |
> 	| UE    | iceandfire | 1.3.0        | iceandfire-1.3.0-1.12.2.jar | None                                     |
> 
> 	Loaded coremods (and transformers): 
> llibrary (llibrary-1.7.9-1.12.2.jar)
>   net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
>   net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
> 	Profiler Position: N/A (disabled)
> 	Is Modded: Definitely; Server brand changed to 'fml,forge'
> 	Type: Dedicated Server (map_server.txt)

**Comment by AlexModGuy** [comment]
fixed for 1.3.1
