### ISSUE TITLE
Crash when generating Mausoleum Structures 2.1.6 - 1.16.4

### ISSUE THREAD

**Issue by TheQKnight** [Alex-the-666/Ice_and_Fire#3790]
When playing in my world, I will randomly get this crash which boots all players off the server.

After testing for a while, I have concluded this may be a conflict between Terraforged and Ice and Fire, but not sure.

**To Reproduce**
1. Walk around the world and generate terrain

**Expected behavior**
Not to crash

Crash log:
https://pastebin.com/BQdvHURA

**Comment by TheQKnight** [comment]
Tried removing terraforged, still happens

**Comment by AlexModGuy** [comment]
#3938
