### ISSUE TITLE
The Betweenlands [ICE AND FIRE VERSION 1.12.2]

### ISSUE THREAD

**Issue by ONIZeus117** [Alex-the-666/Ice_and_Fire#3791]
**Describe the bug**
Can't get the Ring of Dispersion to make the angel ring. It doesn't show up in JEI either, what is the deal?

**Additional context**
Also why is the Supremium armor flight disabled? that's the whole point for going down the Mystical Agriculture tree.

**Comment by RolledOverTurtle** [comment]
Thats something not related to ice and fire I think you have misunderstood either what this github is for or what mod you are using.

**Comment by ONIZeus117** [comment]
oops i had both githubs open and thought i was on the betweenlands one lol my bad
