### ISSUE TITLE
Ice and Fire 2.1.6 - Myrmex don't accept my Resins and keep attacking me

### ISSUE THREAD

**Issue by DragonSorcererX** [Alex-the-666/Ice_and_Fire#3792]
**Describe the bug**
I tried giving desert resin to desert myrmex and it didn't work, I dropped on the ground near a worker, I tried right-clicking and shift+right-clicking on them with it and nothing worked.

**To Reproduce**
1. Go to a Myrmex Colony

**Expected behavior**
I expected them to collect the resin and improve my reputation.

**Note**
I don't think I have any mods that affect AI, so I don't know what could be causing this, also, this could be unrelated but I have another one of Alex's mods, the Rats mod, and the wild rats don't run away from me even when I attack them.

**Comment by Radon8472** [comment]
I have similar issues.

The worker is only focussed on attacking me, and totally ignores the resin.
Ist there any trick how to make them collect the stuff ?
