### ISSUE TITLE
Copper and Silver armor meshing with other mods

### ISSUE THREAD

**Issue by Xavveina** [Alex-the-666/Ice_and_Fire#3794]
So in my 1.16.5 server I have both the Ice and Fire mod and a mod called Mystical World. Both of them have copper and silver armor, and they can both be made by either version of copper and silver from either mod. So when you try to make the armor pieces it lets you make like 1-3 of the armor pieces from 1 of the mods, and 1-3 armor pieces from the other. But the thing is you cannot change which one you make it for. Take the chestplate for silver for example. When you use the silver, regardless of which silver it is, it let's me make the ice and fire silver chestplate. But then that means there is absolutely no way for me to make the Mystical World chestplate. It works the opposite way too, if it let's my make the Mystical World armor, then there is no way for me to make the Ice and Fire armor. So basically my question is, is there anyway to disable the copper and silver items for Ice and Fire. Obviously you'd have no idea about the Mystical World mod, so I'm asking strictly about the Ice and Fire items. I've checked the config and can't seem to find a way to disable items aside from removing the spawn of the ore's in the world. But it seems like the ore's that spawned were already switched to the Mystical World ore's. It appears that that's what they defaulted to, because they're registered as all items under that name. Any form of help is appreciated, cause I'm racking my brain about what to do about the situation. If nothing else works then I'll just end up removing the Mystical World mod, but I'd like to find a solution if possible.

**Comment by tweakbsd** [comment]
You can try this mod:

https://www.curseforge.com/minecraft/mc-mods/polymorph

Then you should be able to craft the silver or copper armor from either mod by selecting which one you want even though both have the same recipe.

**Comment by Xavveina** [comment]
> You can try this mod:
> 
> https://www.curseforge.com/minecraft/mc-mods/polymorph
> 
> Then you should be able to craft the silver or copper armor from either mod by selecting which one you want even though both have the same recipe.

Awesome, that mod did the trick! Fixed the problem right up, thanks so much!

**Comment by Neko2n** [comment]
I'd close this issue, as it's not fixable on Alex's end and is a common compat issue that's easily fixable with either Polymorph (as listed above) or Crafttweaker if you're making a modpack.
