### ISSUE TITLE
Dragon Pathfinding crashes my game with Exit Code 0? [2.1.6]

### ISSUE THREAD

**Issue by Neko2n** [Alex-the-666/Ice_and_Fire#3795]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
I was just playing some single player with my modpack to test things out, and my game randomly crashed while I was mining. This crash has happened before in Creative mode too, and seems to happen at random. I can spawn dragons in just fine, this seems to only happen when a dragon is near something else specifically (I don't know what though),

**To Reproduce**
1. Join game / create a world
2. I guess just fly around for a really long time, maybe underground?
3. Game will eventually freeze, crash, and you'll get an exit code 0 crash.

**Expected behavior**
My game to not randomly crash while I'm playing

**Screenshots**
Can't screenshot a crash, so I'll provide my latest.log. 
[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/6309597/latest.log)
Should also have my mod list in it, so if this is an incompatibility problem that should help. This is also where I made the guess "dragon pathfinding" from.
Edit: ignore the probably thousands of other problems in my latest.log, I was testing for a reason. The stuff at the bottom is what's helpful, everything else is just there for context.

**Additional context**
This happened in Singleplayer, I have yet to test if this issue occurs on a server.

**Comment by MemeLord32** [comment]
This has also happened to me, though I wonder if it's also a problem with apotheosis, and optifine as well.

Here is my crash log and I hope it helps.
[Crash Log 1.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6323162/Crash.Log.1.txt)

**Comment by AlexModGuy** [comment]
#3938
