### ISSUE TITLE
[1.16.5 - 36.1.4] [2.1.6] Server crash by IafDamageRegistry

### ISSUE THREAD

**Issue by Cixon** [Alex-the-666/Ice_and_Fire#3799]
**Describe the bug**
~~I just loaded my new forge version server with ice and fire and explored a bit only for server to get killed.~~
Taking damage kicks users from the server. For example, I walked into a cactus in survival and was booted.

**To Reproduce**
**N/A**.

**Screenshots**
**N/A**.

**Crash-report/Logs**
[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/6321084/latest.log) **Line 1615**
[debug.log](https://github.com/Alex-the-666/Ice_and_Fire/files/6321085/debug.log) **Line 7533**
[crash-2021-04-15_15.54.42-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6321086/crash-2021-04-15_15.54.42-server.txt)

**Comment by Cixon** [comment]
Found the bug, it appears that anytime a player takes damage on the server, they get booted from the server.

[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/6327765/latest.log) **Line 1628**

**Comment by Cixon** [comment]
Removing the Ice and Fire mod fixes the issue.
I hope this can be fixed sometime soon!

**Comment by CallieEZ** [comment]
Having a similar issue, although it just kinda happened at random but still reported an iafdamageregistry error

**Comment by gjroelofs** [comment]
For me this started occurring ~14h into a playthrough in which the server no longer starts with the following two exceptions:

> Caused by: java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/misc/IafDamageRegistry

> java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/entity/ai/PixieAIPickupItem$1

**Minecraft version**: 1.16.5
**Ice & Fire version**: iceandfire-2.1.6-1.16.4
**Citadel version**: citadel-1.6.3-1.16.5
**Java version:** java 10.0.2 2018-07-17
**OS**: Windows 10

**Comment by gjroelofs** [comment]
This seems related to #3875, #3743 and potentially #3910

**Comment by gjroelofs** [comment]
For me, one of the mods enabled is Performant - which specifically has multi-threading enabled for mob ticks. 
The missing class file is in the jar of IaF, could it be that (given the Concurrent exception, and the load exception), the class is getting loaded too late in the process and/or a racing condition occurs for the multithreading?

@Cixon @cnc42 - Are you guys running any Performance mods?

**Comment by Cixon** [comment]
> 
> 
> For me, one of the mods enabled is Performant - which specifically has multi-threading enabled for mob ticks.
> The missing class file is in the jar of IaF, could it be that (given the Concurrent exception, and the load exception), the class is getting loaded too late in the process and/or a racing condition occurs for the multithreading?
> 
> @Cixon @cnc42 - Are you guys running any Performance mods?

I am using performant as well as [Lithium forge](https://github.com/AeiouEnigma/lithium-forge/releases)

**Comment by Cixon** [comment]
Since issue #3743 came reported before me I will close this ticket. Thank you @gjroelofs .

**Comment by gjroelofs** [comment]
@Cixon I can't confirm completely, but the server for us starts again after disabling multi-threading on the entity tick update in Performant: (performant-common.toml)

```
multiEntities = false
..
fastCollisions = false
```
