### ISSUE TITLE
Gorgon head crash in version 2.1.6

### ISSUE THREAD

**Issue by WordStormRose** [Alex-the-666/Ice_and_Fire#3800]
When using the gorgon head on mobs or trying to mine the resulting stone mob, my game crashes with the resulting crash logs.

[crash-2021-04-16_09.39.12-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6326765/crash-2021-04-16_09.39.12-client.txt)
[crash-2021-04-16_09.46.03-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6326752/crash-2021-04-16_09.46.03-client.txt)
[crash-2021-04-16_09.41.54-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6326753/crash-2021-04-16_09.41.54-client.txt)

**Comment by TheBv** [comment]
Seems to be a compatibility issue with the lotr mods. 
Nonetheless this should be somewhat easy to fix by adding a null check. I'll look into it.

**Comment by WordStormRose** [comment]
Alright, thank you!
