### ISSUE TITLE
Audio files should be in mono, not stereo (very loud pixies and other stuff) [2.1.6]

### ISSUE THREAD

**Issue by toledkrw** [Alex-the-666/Ice_and_Fire#3801]
**The bug**
Some Ice and Fire's mobs are producing a very loud sound, from "everywhere".
The sound do not fade when we move away from it's source.

**To Reproduce**
Just hit an Ice and Fire's entity and your friend (who's far from you) will hear it as if the mob is pretty close. (It also turns finding a dragon a very difficult task in a crowded area due this).
The easiest way to see this bug is by capturing a pixie and then moving away from them. They'll still be sounding like they're very close.

**Expected behavior**
Entities' sounds should fade as we move away from them.
I tried to fix it by adding a "attenuation_distance" on ice and fire sounds.json, but had no effect.
Noticed the .ogg files in mod were in stereo channel.
Minecraft's sounds.json only treats audio files in mono channel.
Changed some audio files to mono and, voila, fixed. No more loudAF pixies.

**Screenshots**
![image](https://user-images.githubusercontent.com/57298489/115067646-9925bd80-9ec7-11eb-92a3-4b25fd56af8b.png)
![image](https://user-images.githubusercontent.com/57298489/115069301-c3787a80-9ec9-11eb-87f4-568d11dd8b0a.png)

**Additional context**
Had to find a fix for it because a friend were griefing my house due to the pixies sound.

**Comment by TheBv** [comment]
This should be fixed in the next release #3626
