### ISSUE TITLE
Gorgon Temples, Graveyards and Mausoleums don't generate in Overworld Two worlds [2.1.6]

### ISSUE THREAD

**Issue by Thombias** [Alex-the-666/Ice_and_Fire#3804]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
I'll just shamelessly copy-paste the title as it describes the bug already:
Gorgon Temples, Graveyards and Mausoleums don't generate in Overworld Two worlds

**To Reproduce**
1. Start Minecraft with Ice and Fire and Overworld Two (Forge) installed
2. Generate a new world with the world type set to "Overworld Two"
3. Use the /locate command on all Ice and Fire structures.
4. Notice how it is never actually able to find them, no matter how much you fly around or how far you teleport and retry the command

**Expected behavior**
Gorgon Temples, Graveyards and Mausoleums are supposed to generate and be found using the /locate command or simply by flying through an Overworld Two world and stumbling across them.

**Screenshots**

**Additional context**
Dragon Caves, Dragon Roosts, Cyclope Caves, Pixie Villages, Myrmex Colonies, Hydra Caves and Siren Islands do generate in their expected biomes. Basically all structures that cannot be located with the /locate command generate like normal.
I have reported this bug on the Overworld Two (Forge) Issue tracker as well, as it is not clear for me which side needs to fix this incompatibility. For example, structures that use Structure Gel API didn't initially generate in Overworld Two worlds, but the developer of Structure Gel API managed to fix this. I don't know if you can fix this incompatibility as well or if the developer for Overworld Two has to do it. If you can't or won't do it, feel free to just close this issue. :)

This was tested on Forge 36.1.0, MC 1.16.5, Ice and Fire 2.1.6 and Citadel 1.6.2

**Comment by TheBv** [comment]
Should hopefully not be an issue anymore since the way those structures are generated has changed.
