### ISSUE TITLE
Despawning Ice Dragon Eggs

### ISSUE THREAD

**Issue by NeonPopsicle** [Alex-the-666/Ice_and_Fire#3809]
Buggy Ice Dragon Eggs:

SUMMARY/SITUATION:
Hello! I am coming from a modded, public server. It can be laggy at times, and has an every other hour, quick reset to keep lag a bit clearer.
There are 40-ish mods, some small, others large. There are about 25 people tops. When people on the server find an ice egg and try to hatch it in the water, more often than not, once it turns to ice it will disappear. It either does this, or just turn the hatching egg into a piece of packed ice. Why is this a problem? Any idea? Has it happened to others?

EXPECTATION:
If there are suggestions/assumptions to fix or explain this, I would love to know.

SCREENSHOTS:
Before the issues:
[https://i.imgur.com/7ZFHuEJ.png](url)

First egg disappeared:
[https://i.imgur.com/23Fidrv.png](url)

Second egg never hatched and turned into a piece of packed ice:
[https://i.imgur.com/1PXr14U.png](url)

**Comment by SpandexPudding** [comment]
YES thank goodness someone else is having the same issue! We were able to hatch two dragons thus far that I know of on my server. I've been trying to hatch a couple more, and they are despawning. The ice breaks and nothing. It's very annoying as it takes a bit of work to get these eggs..
