### ISSUE TITLE
Bug list 1.3.0

### ISSUE THREAD

**Issue by Frosty8-0** [Alex-the-666/Ice_and_Fire#381]
-  When riding any dragon, you will bounce up and down on it and not be able to see anything
-  Why u remove the dragon breath animation?!?!
-  None of the new strike attacks work, and the current ones hardly ever hit
-  When pressing escape on a singleplayer world if u r looking at a moving dragon, they will sometimes start fritzing and lagging
-  Dragons are always walking above the ground not actually making contact with it
-  Dragon breath will constantly bounce instead of landing on the ground
-  Dragons wont regen health
-  Dragon bone arrows will (when shot)  bounce in front of the players head then continue their path
-  Dragon bone arrows won't blind cyclops'
-  the font of the bestiary is a bit difficult to read
-  Dragon's body will move up and down without the wings when not moving
-  Dragon attacks do much less damage and changing the damage config option doesn't do anything
-  Silver ice dragon wings have a texture glitch where there is a patch of lighter colored wing that overlaps the bone
-  Petrified fairies still have particles
-  White ice dragon egg now says dragon.white
-  Some snow villagers houses are cut in half

**Comment by Frosty8-0** [comment]
Oh and sometimes dismounting a dragon from your shoulder will put it far away from you

**Comment by AlexModGuy** [comment]
can you split these into multiple issues it makes it easier to handle

**Comment by Frosty8-0** [comment]
Are groups of 3 ok?

**Comment by Frosty8-0** [comment]
Ok there they have been split into groups of 3, with the exception of the last section which has 4
