### ISSUE TITLE
[iceandfire-2.1.6-1.16.4] Crash due to missing zombie villager texture.

### ISSUE THREAD

**Issue by winsrp** [Alex-the-666/Ice_and_Fire#3811]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Game crashed due to missing texture.

[Render thread/WARN] [net.minecraft.client.renderer.texture.TextureManager/]: Failed to load texture: iceandfire:textures/entity/zombie_villager/profession/scribe.png

java.io.FileNotFoundException: iceandfire:textures/entity/zombie_villager/profession/scribe.png
	at net.minecraft.resources.FallbackResourceManager.func_199002_a(FallbackResourceManager.java:63) ~[?:?]

**To Reproduce**
On a random night, a zombie villager scribe tried to show up.. crash

**Expected behavior**
a zombie villager scribe shows up...

**Comment by Thombias** [comment]
I don't get a crash but instead the zombie villager with the "Scribe" profession (at least according the texture file it's called scribe) has the purple & black missing texture. I assume i'm not crashing as i have not enough crashes installed.

**Comment by winsrp** [comment]
what can I say, I don't really get it every time I find a village, only every so often.. I'll keep track of the bug and let you know if it happens again.

**Comment by TheBv** [comment]
Fixed with #3672
