### ISSUE TITLE
[2.1.6-mc1.16.5]Dragonsteel base durability and armor config can't work

### ISSUE THREAD

**Issue by AlanightCreeper** [Alex-the-666/Ice_and_Fire#3812]
Describe the bug
Dragonsteel base durability and armor config can't work.

To Reproduce
1. Modify dragonsteel base durability and armor
2. Enter the game and press F3+H key
3. Find the armor of dragonsteel armor and the durability of dragonsteel products have no change

Expected behavior
These value in minecraft should equal to the value config modified.

**Comment by TheBv** [comment]
Fixed with #3968
