### ISSUE TITLE
Pixie model bug [2.0.3, 1.15.2]

### ISSUE THREAD

**Issue by Teothem** [Alex-the-666/Ice_and_Fire#3815]
Game crashes when meeting and interacting with pixie. Game refuses to load on again.

1. Find pixie village.
2. Something spawns.
3. Game crashes.

[crash-2021-04-22_22.38.43-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6360922/crash-2021-04-22_22.38.43-client.txt)

**Comment by AlexModGuy** [comment]
> at artifacts.common.item.UmbrellaItem$ClientEvents.onLivingRender(UmbrellaItem.java:85) 

caused by artifacts mod. that dev needs to stop assuming every mob that holds his item is a vanilla biped.
