### ISSUE TITLE
Dragon Corpse not working properly [1.12.2]

### ISSUE THREAD

**Issue by Yoshi2Dark** [Alex-the-666/Ice_and_Fire#3816]
When me and my friends kill a dragon the corpse doesn't appear until you reload the chunks

**To Reproduce**
1. Most recent version of the mod, most recent version of the dependency, Optifine, and Damage Indicators
2. Kill a dragon

**Expected behavior**
The corpse should appear when you kill a dragon

**Comment by taz4270** [comment]
It happens in 1.16.5 too
