### ISSUE TITLE
Dragon causing crash while above or in water [iceandfire-2.1.6]

### ISSUE THREAD

**Issue by GrimWolf47** [Alex-the-666/Ice_and_Fire#3817]
**Describe the bug**
So my friend is riding her dragon over the ocean its a rather small dragon stage 3 atleast she somehow crashes the server everytime she rejoins now still above the ocean we knows its her crashing the server because everything runs fine til she joins back after the server restarts.

**To Reproduce**
I honestly don't really know how to reproduce it best way I can say is get a dragon fly above the ocean leave on the dragon and rejoin.

**Expected behavior**
Well I expect my server not to crash when a dragon is above or in water

**Screenshots**
No Screenshot available

**Additional context**
There is a theory its caused by the server rendering the dragon in the water thats causing the crash

**Comment by TheBv** [comment]
Probably fixed with b5d45ee
