### ISSUE TITLE
Pixie causing Exception ticking world [2.1.6]

### ISSUE THREAD

**Issue by Lewisking50** [Alex-the-666/Ice_and_Fire#3818]
We disabled Pixies stealing items and now they apparently cause our server to crash.

1. Set `"Pixies Steal Items" = false`
2. Find Pixies
3. Log: [crash-2021-04-23_22.18.28-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6367898/crash-2021-04-23_22.18.28-server.txt)

**Expected behavior**
Pixies behave like usual, except they no longer steal items.

**Comment by Jackiecrazy** [comment]
Can confirm that pixies will (perhaps occasionally) throw an exception even if `"Pixies Steal Items = true`

**Comment by AlexModGuy** [comment]
#3938
