### ISSUE TITLE
Dragon Cave Generation Crashing Server [2.1.6]

### ISSUE THREAD

**Issue by Zulenka** [Alex-the-666/Ice_and_Fire#3819]
**Describe the bug**
The server is crashing when underground dragon caves are being generated for the first time. 

**To Reproduce**
Explore until a dragon cave spawns underneath the overworld. 

**Expected behavior**
The expected behavior, I'm assuming is that the caves are supposed to generate and NOT crash the server. 

**Screenshots**
I managed to capture part of the crash from the console. 

```
24.04 05:50:30 [Server] INFO Suppressed: java.lang.ClassNotFoundException: Failed to find class bytes for com.github.alexthe666.iceandfire.world.gen.WorldGenFireDragonCave$SphereInfo
24.04 05:50:30 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:260) ~[modlauncher-8.0.9.jar:?] {}
24.04 05:50:30 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
24.04 05:50:30 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
24.04 05:50:30 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_282] {}
24.04 05:50:30 [Server] INFO at com.github.alexthe666.iceandfire.world.gen.WorldGenFireDragonCave.createShell(WorldGenFireDragonCave.java:168) ~[iceandfire:2.1.6-1.16.4] {re:classloading}
24.04 05:50:30 [Server] INFO at com.github.alexthe666.iceandfire.world.gen.WorldGenFireDragonCave.generate(WorldGenFireDragonCave.java:75) ~[iceandfire:2.1.6-1.16.4] {re:classloading}
24.04 05:50:30 [Server] INFO at com.github.alexthe666.iceandfire.world.gen.WorldGenFireDragonCave.func_241855_a(WorldGenFireDragonCave.java:32) ~[iceandfire:2.1.6-1.16.4] {re:classloading}
24.04 05:50:30 [Server] INFO at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:classloading}
24.04 05:50:30 [Server] INFO at net.minecraft.world.biome.Biome.func_242427_a(Biome.java:254) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
24.04 05:50:30 [Server] INFO at net.minecraft.world.gen.ChunkGenerator.func_230351_a_(SourceFile:220) ~[?:?] {re:mixin,re:classloading}
24.04 05:50:30 [Server] INFO at net.minecraft.world.chunk.ChunkStatus.func_222605_b(ChunkStatus.java:77) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:ChunkStatusMixin,pl:mixin:A}
24.04 05:50:30 [Server] INFO at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:ChunkStatusMixin,pl:mixin:A}
24.04 05:50:30 [Server] INFO at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.chunk.ChunkManagerMixin,pl:mixin:APP:performant.mixins.json:world.chunk.ChunkManagerUpdatePlayerPosMixin,pl:mixin:APP:performant.mixins.json:world.chunk.ChunkManagerChunksAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
24.04 05:50:30 [Server] INFO at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?] {re:classloading}
24.04 05:50:30 [Server] INFO at net.minecraft.world.server.ChunkManager.lambda$scheduleChunkGeneration$20(ChunkManager.java:522) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.chunk.ChunkManagerMixin,pl:mixin:APP:performant.mixins.json:world.chunk.ChunkManagerUpdatePlayerPosMixin,pl:mixin:APP:performant.mixins.json:world.chunk.ChunkManagerChunksAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
24.04 05:50:30 [Server] INFO at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966) ~[?:1.8.0_282] {}
24.04 05:50:30 [Server] INFO at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) ~[?:1.8.0_282] {}
24.04 05:50:30 [Server] INFO at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_282] {}
24.04 05:50:30 [Server] INFO at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
24.04 05:50:30 [Server] INFO at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}
24.04 05:50:30 [Server] INFO at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?] {re:classloading}
24.04 05:50:30 [Server] INFO at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?] {re:classloading}
24.04 05:50:30 [Server] INFO at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_282] {}
24.04 05:50:34 [Multicraft] Skipped 1810 lines due to rate limit (30/s)
24.04 05:51:31 [Multicraft] Server shut down (running)
24.04 05:51:31 [Multicraft] Restarting crashed server in 300 seconds
```

**Additional context**
So far it's only dragon caves. I'll keep an eye on it and report any further issues with it.

**Comment by Zulenka** [comment]
`24.04 18:46:55 [Server] Server thread/FATAL [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 0226ff8a-e22a-4762-aa7d-d3b96cb437f3
24.04 18:46:55 [Server] Server thread/ERROR Encountered an unexpected exception
24.04 18:46:55 [Server] INFO net.minecraft.crash.ReportedException: Ticking entity
24.04 18:46:55 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
24.04 18:46:55 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
24.04 18:46:55 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
24.04 18:46:55 [Server] INFO at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
24.04 18:46:55 [Server] INFO at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
24.04 18:46:55 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282] {}
24.04 18:46:55 [Server] INFO Caused by: java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/entity/IafDragonDestructionManager
24.04 18:46:55 [Server] INFO at com.github.alexthe666.iceandfire.entity.EntityLightningDragon.stimulateFire(EntityLightningDragon.java:458) ~[iceandfire:2.1.6-1.16.4] {re:classloading}
24.04 18:46:55 [Server] INFO at com.github.alexthe666.iceandfire.entity.EntityLightningDragon.riderShootFire(EntityLightningDragon.java:306) ~[iceandfire:2.1.6-1.16.4] {re:classloading}
24.04 18:46:55 [Server] INFO at com.github.alexthe666.iceandfire.entity.IafDragonLogic.updateDragonServer(IafDragonLogic.java:55) ~[iceandfire:2.1.6-1.16.4] {re:classloading}
24.04 18:46:55 [Server] INFO at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70071_h_(EntityDragonBase.java:1620) ~[iceandfire:2.1.6-1.16.4] {re:classloading,pl:runtimedistcleaner:A}
24.04 18:46:55 [Server] INFO at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:entity.MobServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
24.04 18:46:55 [Server] INFO at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
24.04 18:46:55 [Server] INFO at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:entity.MobServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
24.04 18:46:55 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
24.04 18:46:55 [Server] INFO ... 5 more
24.04 18:46:55 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.github.alexthe666.iceandfire.entity.IafDragonDestructionManager
24.04 18:46:55 [Server] INFO at java.lang.ClassLoader.findClass(ClassLoader.java:523) ~[?:1.8.0_282] {}
24.04 18:46:55 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_282] {}
24.04 18:46:55 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
24.04 18:46:55 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_282] {}
24.04 18:46:55 [Server] INFO at com.github.alexthe666.iceandfire.entity.EntityLightningDragon.stimulateFire(EntityLightningDragon.java:458) ~[iceandfire:2.1.6-1.16.4] {re:classloading}
24.04 18:46:55 [Server] INFO at com.github.alexthe666.iceandfire.entity.EntityLightningDragon.riderShootFire(EntityLightningDragon.java:306) ~[iceandfire:2.1.6-1.16.4] {re:classloading}
24.04 18:46:55 [Server] INFO at com.github.alexthe666.iceandfire.entity.IafDragonLogic.updateDragonServer(IafDragonLogic.java:55) ~[iceandfire:2.1.6-1.16.4] {re:classloading}
24.04 18:46:55 [Server] INFO at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70071_h_(EntityDragonBase.java:1620) ~[iceandfire:2.1.6-1.16.4] {re:classloading,pl:runtimedistcleaner:A}
24.04 18:46:55 [Server] INFO at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:entity.MobServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
24.04 18:46:55 [Server] INFO at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
24.04 18:47:00 [Multicraft] Skipped 39 lines due to rate limit (30/s)
`

**Comment by Zulenka** [comment]
`24.04 18:50:15 [Server] Server thread/INFO [Waila/]: Syncing config to Zulenka (45a14cad-bfe8-4cb3-944a-b4085dc3128a)
24.04 18:50:15 [Server] Server thread/INFO [co.wu.pr.Prefab/]: Sent config to 'Zulenka'.
24.04 18:50:15 [Server] Server thread/INFO [structurize/]: New Server UUID 9cee89c3-0670-4e86-82ae-3d63f202bd9e
24.04 18:50:15 [Server] Server thread/WARN Can't keep up! Is the server overloaded? Running 4072ms or 81 ticks behind
24.04 18:50:26 [Server] Server thread/WARN Tried to load a DUMMY block entity @ BlockPos{x=1426, y=35, z=2833} but found not block entity block Block{minecraft:stone} at location
24.04 18:50:26 [Server] Server thread/WARN Tried to load a block entity for block Block{minecraft:stone} but failed at location BlockPos{x=1426, y=35, z=2833}
24.04 18:50:26 [Server] Server thread/WARN Tried to load a DUMMY block entity @ BlockPos{x=1424, y=29, z=2834} but found not block entity block Block{minecraft:cave_air} at location
24.04 18:50:26 [Server] Server thread/WARN Tried to load a block entity for block Block{minecraft:cave_air} but failed at location BlockPos{x=1424, y=29, z=2834}
24.04 18:50:32 [Server] Server thread/FATAL [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 154fd3db-1991-4c0b-b22e-b5a0a9e1cf04
24.04 18:50:32 [Server] Server thread/ERROR Encountered an unexpected exception
24.04 18:50:32 [Server] INFO net.minecraft.crash.ReportedException: Exception ticking world
24.04 18:50:32 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
24.04 18:50:32 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
24.04 18:50:32 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
24.04 18:50:32 [Server] INFO at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
24.04 18:50:32 [Server] INFO at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
24.04 18:50:32 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282] {}
24.04 18:50:32 [Server] INFO Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/world/structure/GraveyardStructure$Start
24.04 18:50:32 [Server] INFO at com.github.alexthe666.iceandfire.world.structure.GraveyardStructure.func_214557_a(GraveyardStructure.java:36) ~[iceandfire:2.1.6-1.16.4] {re:classloading}
24.04 18:50:32 [Server] INFO at net.minecraft.world.gen.feature.structure.Structure.func_236387_a_(Structure.java:217) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.StructureMixin,pl:mixin:A}
24.04 18:50:32 [Server] INFO at net.minecraft.world.gen.feature.structure.Structure.func_242785_a(Structure.java:223) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.StructureMixin,pl:mixin:A}
24.04 18:50:32 [Server] INFO at net.minecraft.world.gen.feature.StructureFeature.func_242771_a(SourceFile:35) ~[?:?] {re:classloading}
24.04 18:50:32 [Server] INFO at net.minecraft.world.gen.ChunkGenerator.func_242705_a(SourceFile:278) ~[?:?] {re:mixin,re:classloading}
24.04 18:50:32 [Server] INFO at net.minecraft.world.gen.ChunkGenerator.func_242707_a(SourceFile:267) ~[?:?] {re:mixin,re:classloading}
24.04 18:50:32 [Server] INFO at net.minecraft.world.chunk.ChunkStatus.func_222586_d(ChunkStatus.java:41) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:ChunkStatusMixin,pl:mixin:A}
24.04 18:50:32 [Server] INFO at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:ChunkStatusMixin,pl:mixin:A}
24.04 18:50:32 [Server] INFO at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.chunk.ChunkManagerMixin,pl:mixin:APP:performant.mixins.json:world.chunk.ChunkManagerUpdatePlayerPosMixin,pl:mixin:APP:performant.mixins.json:world.chunk.ChunkManagerChunksAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
24.04 18:50:32 [Server] INFO at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?] {re:classloading}
24.04 18:50:32 [Server] INFO at net.minecraft.world.server.ChunkManager.lambda$scheduleChunkGeneration$20(ChunkManager.java:522) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.chunk.ChunkManagerMixin,pl:mixin:APP:performant.mixins.json:world.chunk.ChunkManagerUpdatePlayerPosMixin,pl:mixin:APP:performant.mixins.json:world.chunk.ChunkManagerChunksAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
24.04 18:50:32 [Server] INFO at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966) ~[?:1.8.0_282] {}
24.04 18:50:32 [Server] INFO at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) ~[?:1.8.0_282] {}
24.04 18:50:32 [Server] INFO at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_282] {}
24.04 18:50:32 [Server] INFO at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
24.04 18:50:32 [Server] INFO at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}
24.04 18:50:32 [Server] INFO at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?] {re:classloading}
24.04 18:50:32 [Server] INFO at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?] {re:classloading}
24.04 18:50:32 [Server] INFO at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_282] {}
24.04 18:50:32 [Server] INFO at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_282] {}
24.04 18:50:35 [Multicraft] Skipped 101 lines due to rate limit (30/s)
24.04 18:51:35 [Multicraft] Server shut down (running)
24.04 18:51:35 [Multicraft] Restarting crashed server in 300 seconds
24.04 18:51:35 [Multicraft] Server stopped
24.04 18:51:35 [Disconnect] User Zulenka has disconnected, reason: Server shutting down`

**Comment by Ravin26** [comment]
I’m also experiencing this issue

**Comment by TheWitherlord** [comment]
same here

**Comment by AlexModGuy** [comment]
#3938
