### ISSUE TITLE
[1.16.5 - 36.1.4] [2.1.6] Server Crash - StymphalianBirdFlock

### ISSUE THREAD

**Issue by Cixon** [Alex-the-666/Ice_and_Fire#3824]
**Crash report:** 
[crash-2021-04-25_20.06.26-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6372889/crash-2021-04-25_20.06.26-server.txt)

**Comment by AlexModGuy** [comment]
#3938
