### ISSUE TITLE
Lots of dragon babies from 1 egg. [iceandfire-2.1.6-1.16.4] ATM6 Sky modpack

### ISSUE THREAD

**Issue by frostbyte96** [Alex-the-666/Ice_and_Fire#3825]
Tick accelerated Frozen Dragon Egg with a time in a bottle (x256 tick rate) and probably 50 or more dragons hatched from the one egg.

**To Reproduce**
1. Start hatching an ice dragon in water.
2. Use "Time in a bottle" mod to tick accelerate the egg.
3. Wait a bit for a fountain of baby dragons.

**Expected behavior**
Expect only one dragon to hatch from the egg.

![Dragon Bug](https://user-images.githubusercontent.com/43307841/116062583-6057c680-a6c7-11eb-895d-42b9fd490dd2.png)

**Comment by TheBv** [comment]
Fixed in cc380e2
