### ISSUE TITLE
Crash with Exit Code: 0 (Forge 36.1.0)

### ISSUE THREAD

**Issue by mariethepolarfox** [Alex-the-666/Ice_and_Fire#3826]
I dont know if this is from Ice and Fire but when i want to load a world, it says: "Worlds using Experimental Settings Not supported. This world uses experimental settings that could stop working at any time. We cannot guarantee it will lad or work. Here be Dragons!" i can leave the crash code in the file below if that helps. I will also Link a screenshot of all the mods i use.
<img width="1280" alt="Bildschirmfoto 2021-04-27 um 16 02 32" src="https://user-images.githubusercontent.com/80259183/116254882-03651a80-a772-11eb-9282-c89f023b15a0.png">
[crash-2021-04-27_16.12.16-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6385178/crash-2021-04-27_16.12.16-client.txt)

**Comment by AlexModGuy** [comment]
Here be dragons! text is from vanilla, not our mod.
