### ISSUE TITLE
Crash server 1.16.5 ice and fire 2.1.6

### ISSUE THREAD

**Issue by celabie** [Alex-the-666/Ice_and_Fire#3828]
**Describe the bug**
crash link to mod and ia, I don't understand how to fix it

**To Reproduce**
I don't really know it crashes purely for no real reason

**Expected behavior**
just that they explain to me how to settle because I do not understand

**Screenshots**
attached two log screens
https://cdn.discordapp.com/attachments/412709220740235265/836729086126587904/unknown.png
https://cdn.discordapp.com/attachments/412709220740235265/836728981306212382/unknown.png

**Additional context**

**Comment by AlexModGuy** [comment]
#3938
