### ISSUE TITLE
Particule error - Forge Server

### ISSUE THREAD

**Issue by Rilavalon** [Alex-the-666/Ice_and_Fire#383]
Hi,
I'm testing your awesome mod in a custom (&private) modpack .
I'm getting the following error on the forge Server: 

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ice and Fire (iceandfire)
Caused by: net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/particle/Particle

with llibrary-1.7.9-1.12.2, forge-1.12.2-14.23.1.2582  and ice&fire1.3 only

Thanks for your great job :)

PS : Here is the crash report attached.

[crash-2018-01-01_14.14.24-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/1596044/crash-2018-01-01_14.14.24-server.txt)

**Comment by AlexModGuy** [comment]
fixed for 1.3.1
