### ISSUE TITLE
Ticking Entitys (Like, a lot of them) [iceandfire-2.1.6-1.16.4]

### ISSUE THREAD

**Issue by KagetaneHiruko** [Alex-the-666/Ice_and_Fire#3830]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Server Crashes on Startup or on Client connect because of Ticking Entitys. Removing these Entitys does nothing because it seems like they all do this at once. Removing Ice and Fire and Alex's Mobs removes the problem

**To Reproduce**
1. Start Server
2. Wait for a complete Startup
3. See error

or

1. Start Server
2. Wait for a complete Startup
3. Connect

**Expected behavior**
It should not Crash & there shouldnt be that much ticking entitys

**Screenshots**
None

**Additional context**
[Server.log](https://github.com/Alex-the-666/Ice_and_Fire/files/6393100/latest.log)
[crash-2021-04-28_17.25.19-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6393106/crash-2021-04-28_17.25.19-server.txt)
Forge Version: forge-1.16.5-36.1.13

**Comment by TheBv** [comment]
Probably fixed with b5d45ee
