### ISSUE TITLE
Mausoleum dreadstone chiseled skull breakable with pickaxe [2.1.6]

### ISSUE THREAD

**Issue by NeuTraLZero** [Alex-the-666/Ice_and_Fire#3831]
**Describe the bug**
Dreadstone chiseled skull blocks that are generated with Mausoleum can still be broken with a pickaxe which allows player inside without a Gravemaster's Key. Any other Mausoleum blocks can not be broken.

**To Reproduce**
1. Find a Mausoleum
2. Use any pickaxe and try to break the chiseled skull block

**Expected behavior**
Players shouldn't be able to break these blocks to easily enter the Mausoleum without a key for near end-game loot

**Screenshots**
[Screenshot with Jade mod installed](https://i.imgur.com/iFe5wvC.png)

**Comment by TheBv** [comment]
Fixed with #3672
