### ISSUE TITLE
Trolls do not spawn [1.16.5]

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#3832]
For Some Reason, trolls do not spawn despite the changelog suggesting that they do. I have checked in all the appropriate biomes according to the wiki including their cave systems and still nothing. I have the most recent version of ice and fire (2.1.6), and the most recent version of citadel (1.6.2) for minecraft 1.16.5 forge version (36.1.0). I have tested this problem with no other mods installed except for ice and fire and the results are the exact same regardless so I can confirm that this isn't a mod conflict. I can also confirm that this isn't a forge issue as I have also tried multiple versions of forge as well, which wield the same results.

**To Reproduce**
1. just start a world
2. go to any of the 3 appropriate biomes.
3. They refuse to spawn.

**Expected behavior**
according to the wiki, trolls are supposed to spawn in caves system underneath forest, mountain, and snowy tundra biomes.

**Screenshots**
I am unable to provide screenshots due to this problem being a lack of an enemy type.

**Additional context**
I have already seen the change log on forge proclaim that this issue has been fixed, unfortunately I am inclined to disagree. However I have played older version of this mod (1.12.2) were the trolls did indeed spawn. I am very grateful for ice and fire and I appreciate your work on this mod. I am very excited for a future 1.17 version of the mod, as trolls and the other editions will go along greatly with the new cave biomes and features. thank you for your time.

**Comment by mvpetrungaro** [comment]
Same issue here.

**Comment by Mooonblaze** [comment]
Yes, they are also absent from my recently-made server.

**Comment by raffle2** [comment]
Same here! I tested all spawns for all creatures, everything works except trolls, even when you increase the spawn weight by a lot they simply refuse to spawn.
