### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by ASUSConnor** [Alex-the-666/Ice_and_Fire#3833]
**Describe the bug**
This is just overall gameplay. Several textures are missing for me. Namely, the cyclops and earplugs when they are worn. On top of that, the game will crash after a short amount of gameplay at first I would see exit code 0 but now its saying it has to do with the ice and fire mod and no other mods. 

**To Reproduce**
1. Start the game
2. Load world
3. See errors

**Expected behavior**

**Screenshots**
None I'm afraid it crashes before I can take them.

**Additional context**
I am using the latest citadel (1.6.2) and the latest version of ice and fire (2.1.6) I don't know if that may be the issue. I do have other mods installed as well. If your aware that some of these mods may be causing issues please let me know.
Forge version 1.16.5 - 36.1.4
[crash-2021-04-28_21.21.53-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6395811/crash-2021-04-28_21.21.53-client.txt)

**Comment by AlexModGuy** [comment]
#3938
