### ISSUE TITLE
Gorgon+Enigmatic Legacy=pain (Potential mod confliction)

### ISSUE THREAD

**Issue by Fre3am** [Alex-the-666/Ice_and_Fire#3834]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
The mod Enigmatic Legacy spawns players with an amulet that acts like the tombstones from many other mods when equipped or in the inventory of the player upon death. If the player dies via getting turned to stone by a Gorgon, some issue occurs with the statue it would leave behind and said Enigmatic amulet, which causes the player who died and any others in the loaded area to get disconnected from the server, and are then unable to rejoin unless their player data is cleared from the server cache, and even then, if they go to where they died they will once more suffer the same fate. This issue effects singleplayer as well, at least to some degree. It would seem that after the issue occurs in Multiplayer it corrupts one's singleplayer worlds as well, forcing them to delete them and relaunch the pack to play them? This specific part of the issue doesn't seem consistent, but the multiplayer side is 100% of the time. I'm pretty sure this is all caused by the statue 'spawning' where the Enigmatic amulet 'drops' with all the player's items, and that confliction causes the crash and corruption.

**To Reproduce**
1. Have Ice and Fire and Enigmatic Legacy installed, and make sure the Enigmatic amulet you spawn with is in your inventory, or worn.
2. Find a Gorgon from Ice and Fire, and let it turn you to stone (On a dedicated server, this seems the only way to cause the exact issue.)
3. See error and fun times

**Expected behavior**
I mean, me and the guy helping me figure this out after it happened just expected to be turned to stone.

**Screenshots**
Singleplayer error- https://gyazo.com/bd9b39c82f1e749846b1f71c93f6e48f
Multiplayer error -https://gyazo.com/b5c4097b92ff0ec2b6d9e27410b0b3cf

**Additional context**
If the amulet is not in the inventory or worn upon getting turned to stone, everything would seem to work as it should.

**Comment by Danisanjuan93** [comment]
Hi,
Today I was fighting Gorgon and a friend turned to stone. Since I have quark oddities, where a tombstone appears after the player dies, the Minecraft client crashes. The way I solved this problem was by resetting the player's position, but once you try to get close to the last tombstone (where the gorgon "kills" you), the client crashes again.

Did you find a solution to this problem?

**Comment by TheBv** [comment]
Fixed with 88e40b22
