### ISSUE TITLE
Fire Dragon Crash [2.1.6-1.16.4]

### ISSUE THREAD

**Issue by Turtar** [Alex-the-666/Ice_and_Fire#3835]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
I was walking around exploring and my singleplayer world crashed. I was brought back to the title screen. It seems like a fire dragon caused the crash. Looking at the log, I think it tried to breath fire at a mob and that's what caused it.

**To Reproduce**
1. Find a fire dragon in the wild
2. Wait for the dragon to breath fire at a mob 
3. World crash, then view the error in log

**Expected behavior**
For the world not to crash to menu

**Additional context**

[crash-2021-04-29_19.51.24-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6401040/crash-2021-04-29_19.51.24-server.txt)

**Comment by AlexModGuy** [comment]
#3938
