### ISSUE TITLE
"java.lang.NoClassDefFoundError" Potential issue with FerriteCore? [ICE AND FIRE-2.1.6-1.16.4]

### ISSUE THREAD

**Issue by Ritzumi** [Alex-the-666/Ice_and_Fire#3836]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
I has been experiencing this error recently. This bug won't occurred instantly at the soon as you joined the world but rather after the game has run for a while (After several GC run?). When it occurred, some texture of ice and fire entities will be invalided, or some will crash the game and produce a crash log (included below).
**To Reproduce**
1. Join a world
2. Play it for a while (can also try /reload to accelerate bug occurrence)
3. See error

**Expected behavior**
Most noticeable behaviors is that the texture of some Ice and Fire entities (especially multipart entities) would be invalided (the pruple-black textures) and any further mob spawn would crash the game. However, if Not Enough Crashes is installed, you will either got crash report or "server closed" page with the main screen texture become invalided. 

**Screenshots**
Unfortunately, I could not provide any screenshot. Sorry.

**Additional context**
Same error, different class.
https://gist.github.com/Ritzumi/3e3de4b36cb9e266e583a33c6f7c5918 (Crash log 1)
https://gist.github.com/Ritzumi/41a475e5d77d58d6de811db709b30944 (Crash log 2)
What FerriteCore do to improve memory
https://github.com/malte0811/FerriteCore/blob/main/summary.md
How I think it is FerriteCore?
I have read several issues open in Ice and fire to find log of the people who have same issue as me. Since not many people reporting this, I assume that it must caused by some mods (Which is hard to run test since it doesn't has a solid way to reproduce it). Surprisingly, almost every log that include mod list has FerriteCore, so I turned off some functionality of it that could interfere with Ice and Fire (multipartDeduplication). Currently, after turn it off, I experienced no issue. Will update again if there is anything I noticed.

**Comment by AlexModGuy** [comment]
#3938
