### ISSUE TITLE
ice and fire dragon roosts and caves arent spawning but the other structures like the graveyard and gorgon temples are spawning

### ISSUE THREAD

**Issue by Manglefan** [Alex-the-666/Ice_and_Fire#3837]
idk if its a mod conflict or config problem

**Comment by Manglefan** [comment]
im in version 2.1.4 1.16.4

**Comment by Manglefan** [comment]
can anyone help

**Comment by jynx474** [comment]
do a search [Ctrl+F] for the different structures (dragon roosts, caves &tc) in (your profile)\config\iceandfire_common.toml and make sure that they're able to spawn ( = True means they can  = False means they can't generate) then if needed you can also adjust their Spawn Chances.

Also if you've just started the world, you'll need to go at least 800 blocks out for any hostile Mobs or Dangerous Structures to Spawn

**Comment by Manglefan** [comment]
so if i set it to 100 does it make it more common or rarer?

**Comment by jynx474** [comment]
setting spawn chance to 100 = 100% Spawn chance... Be careful however, as setting it that high will result in a huge lag festival and possible world corruption

**Comment by Manglefan** [comment]
if thats the case why is the defualt 380

**Comment by jynx474** [comment]
Which version are you running? I play the latest version

**Comment by Manglefan** [comment]
i was running 2.1.4 for 1.16.4 but updated to latest

**Comment by jynx474** [comment]
Try lowering it to 80? you may have the spawn rate set too high

**Comment by Manglefan** [comment]
ive tried setting it to 80 and changing worlds but nothing still

**Comment by joeyjumper94** [comment]
what other mods do you have?
particularly mods related to biomes.

**Comment by Manglefan** [comment]
they have started to respawn i lowered it to 78 and it worked
