### ISSUE TITLE
No mobs, dragon dens or caves spawn in any dimension[2.1.6] Minecraft 1.16.5

### ISSUE THREAD

**Issue by CodeName-Thor** [Alex-the-666/Ice_and_Fire#3838]
We installed the mod on our server with a custom world. We expected no dragon dens would spawn in the world which is why we wanted to add those to the "Twilight Forest" dimension. After a lot of troubleshooting we still can’t figure out why nothing spawns so I came here looking for help

**To Reproduce**
1. Download mod
2. Add to server and modpack
3. change config so it adds mobs to the "Twilight Forest" dimension
4. log onto world and no mobs spawn anywhere

**Expected behavior**
I expect mobs like death worms, etc... to spawn in the overworld while dragon dens and caves spawn in the twilight forest.

Config file: https://pastebin.com/9CwbRmFL

**Additional context**
Our server host is shockbyte and we are using a custom modpack named "Epic Gamers Hub"

**Comment by TheBv** [comment]
To configure mob spawn you sadly can't just specify the dimensions you also have to edit each feature config file individually.
The blacklist/whitelist just add another layer which more or less just disables certain mobs from spawning in a given dimension.
Refer to https://github.com/Alex-the-666/Ice_and_Fire/wiki/How-to-specify-the-regions-structures-and-mobs-can-be-spawned for more info
