### ISSUE TITLE
"Ice and Fire has class loading errors"

### ISSUE THREAD

**Issue by Lionhearte** [Alex-the-666/Ice_and_Fire#3839]
Using "iceandfire-2.1.6-1.16.4" with "citadel-1.6.2", attempting to load Minecraft (MC Forge v1.16.5-36.1.16) produces an error screen:

Ice and Fire has class loading errors
java.lang.IllegalAccessError: no such constructor: com.github.alexthe666.iceandfire.ClientProxy.<init>()void/newInvokeSpecial

[crash-2021-04-30_23.18.18-fml.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6408990/crash-2021-04-30_23.18.18-fml.txt)

**Comment by AlexModGuy** [comment]
#3938
