### ISSUE TITLE
Banners missing textures

### ISSUE THREAD

**Issue by realares0414** [Alex-the-666/Ice_and_Fire#3846]
The banner patterns added by the mod are not showing up, they are the black and purple missing texture and although this is only a small part of this mod and it's amazing otherwise, it would be nice to be able to get cool dragon banners.

**Comment by robinotwilliams** [comment]
+1

**Comment by jynx474** [comment]
Are you running Mowzie's Mobs?  It's a known issue that it has a tendency to Bork Custom Banners from other mods

**Comment by AlexModGuy** [comment]
^
