### ISSUE TITLE
not all recipes are acknowledged [2.1.6]

### ISSUE THREAD

**Issue by joeyjumper94** [Alex-the-666/Ice_and_Fire#3848]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
only the first recipe registered to a type of dragon forge is acknowledged.

**To Reproduce**
get craftweaker( i used CraftTweaker-1.16.5-7.1.0.253)
open your recipes.zs and write
`mods.iceandfire.recipes.addFireDragonForgeRecipe(<item:minecraft:cobblestone>*32,<item:minecraft:bucket>,<item:minecraft:lava_bucket>);
mods.iceandfire.recipes.addFireDragonForgeRecipe(<item:minecraft:cobblestone>,<item:iceandfire:ash>,<item:iceandfire:chared_cobblestone>);`
and try both recipes in a fire dragon forge

**Expected behavior**
placing half a stack of cobblestone into the ingot slot and an empty bucket into the blood slot should make a lava bucket
and a piece of cobblestone into the ingot slot and ash into the blood slot should make charred cobblestone

**Screenshots**
![2021-05-03_23 57 21](https://user-images.githubusercontent.com/22709121/116972403-cf0cc500-ac6f-11eb-9033-82e9bd810951.png)
![2021-05-03_23 57 28](https://user-images.githubusercontent.com/22709121/116972407-d03df200-ac6f-11eb-8392-5186cb48c41c.png)
![2021-05-03_23 57 31](https://user-images.githubusercontent.com/22709121/116972408-d0d68880-ac6f-11eb-8c88-79128a9abd14.png)
![2021-05-04_00 01 23](https://user-images.githubusercontent.com/22709121/116972410-d16f1f00-ac6f-11eb-8fe8-8ee99c14f0cc.png)
![2021-05-04_00 01 40](https://user-images.githubusercontent.com/22709121/116972412-d207b580-ac6f-11eb-9429-017b5b9a9db1.png)

**Additional context**
i wanted to make cobblestone and regular stone be able to be smelted into lava so that you can have renewable lava and to be able to make the griefed versions of blocks without having to allow dragons to grief the terrain and more importantly people's builds

**Comment by AlexModGuy** [comment]
craft tweaker support dropped in favor of jsons
