### ISSUE TITLE
1.3.0 Flight Issue

### ISSUE THREAD

**Issue by GundunUkan** [Alex-the-666/Ice_and_Fire#385]
I'm not sure if its just me, or wild dragons can't really take off. Well, they sorta do, but right after that they divebomb to the ground as if they are attacking something, which isn't actually the case. So far I haven't seen a single wild dragon flying, just trying to take off and then divebomb the ground.

**Comment by AlexModGuy** [comment]
just tested - invalid issue - spawn in a bunch of wild dragons in a flat world to replicate
