### ISSUE TITLE
Crashing on loading ghost entity [2.1.6-1.16.4]

### ISSUE THREAD

**Issue by mio9** [Alex-the-666/Ice_and_Fire#3850]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Random ClassNotFoundException crashing the server occationally

**To Reproduce**
1. Install ATM6 To The Sky modpack
2. Access "The Other" dimension
3. Wait for the ghost to spawn

**Expected behavior**
Entity spawns

**Screenshots**
![image](https://user-images.githubusercontent.com/11581624/117021209-19ef1100-ad32-11eb-89ee-29fa1a9ef261.png)

**Additional context**
Detailed crash log: https://pastebin.pl/view/15dbbe04

It looks like the mod is trying to load non-existence classes whenever attempting to load something

**Comment by AlexModGuy** [comment]
#3938
