### ISSUE TITLE
Doesn’t crash just an error[1.16.5 2.1.6]

### ISSUE THREAD

**Issue by JoJesseGaming** [Alex-the-666/Ice_and_Fire#3851]
![C6EB58B1-0AA5-4633-A020-39777992E00F](https://user-images.githubusercontent.com/78740652/117032857-23f91b80-ad02-11eb-8337-9fbc83f5af4e.jpeg)

**Comment by TheBv** [comment]
Nothing to worry about as this is "intended" behavior.
