### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by I6GTRa** [Alex-the-666/Ice_and_Fire#3852]
The game crashed whilst rendering entity in world
Error: java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/util/IAFMath
Exit Code: -1 

this is my problem i can join the world but when i stay for a 1min it freezes and crashing what i have to do please help

this is the screenshot:
https://user-images.githubusercontent.com/83682154/117088826-4455c400-ad5c-11eb-8697-e4a5e74d174a.png

**Comment by TrueSpiderShark** [comment]
try updating any additional mods you have installed, sometimes that's all it takes

**Comment by I6GTRa** [comment]
All my mods are up to date

**Comment by TrueSpiderShark** [comment]
okay so apparently this happens because the classpath for IAFMath.class is not there or not recognized, I still haven't found out how to set one though
If I find out I'll tell you

**Comment by I6GTRa** [comment]
Ok—

**Comment by AlexModGuy** [comment]
#3938
