### ISSUE TITLE
Dragons placed in Horns become hostile. [Ice&Fire 2.1.6-1.16.4, Citadel 1.6.2]

### ISSUE THREAD

**Issue by Lashriel** [Alex-the-666/Ice_and_Fire#3854]
**Describe the bug**
See title. I had a tamed dragon, which outgrew its habitat. After placing it in a Dragon Horn for storage and replacing it into its new habitat, it seems to have forgotten that I'd hatched it, and it attacked me.

**To Reproduce**
1. Hatch a Dragon Egg.
2. Use a Dragon Horn on the dragon.
3. Use the Dragon Horn again to "respawn" the dragon.
4. See error.

**Expected behavior**
Dragon should retain tamed status and not attack their owner, after being summoned from a Horn.

**Comment by 1akashkalita** [comment]
I have the same issue. Please fix or find a version that works.

**Comment by TheBv** [comment]
Fixed with c01e451
