### ISSUE TITLE
"death.attack.Stuck-damage"[ICE AND FIRE VERSION, ATM6 SKY]

### ISSUE THREAD

**Issue by Artimaeus** [Alex-the-666/Ice_and_Fire#3856]
I've seen other reports of this but they were all closed due to being before 2/26. Whenever I have a tamed dragon wander it slowly loses health until it dies of the error message "death.attack.Stuck-damage" Regardless of being on an empty floor or anything. From all the assistance I've gotten on the discord, there is currently no fix to this, can you please help?

I had just healed the dragon up to roughly 500 health after just hatching it, then in about 10 seconds from setting it down to get a name tag, it died. I don't have the mod in ATM6 that keeps tamed pets alive either, so it just poofed like a regular creature dying.

**Comment by Mooonblaze** [comment]
I believe I may also be experiencing this. It is with the latest version. I have not yet had a dragon die, but tamed dragons on wander take random damage. I can test to see what the death message is if one were to die like this.

**Comment by AlexModGuy** [comment]
should be fixed
