### ISSUE TITLE
Dragons Randomly Dying - iceandfire-2.1.6-1.16.4.jar

### ISSUE THREAD

**Issue by Reshy** [Alex-the-666/Ice_and_Fire#3865]
In my modded server I've been noticing a trend of dragons randomly dying after roaming for a while in the overworld in a loaded chunk.  My players have a base near two nests, enough to occasionally see it while they roam around.  However, over time both dragons randomly died in their nests.  No other mobs I know can kill them, and the players didn't as they were just as surprised to find a free dragon corpse.

Reproduce:
It seems to happen any time a dragon's within a loaded chunk for long enough while able to fly around?  We're talking many hours though before it takes effect.  The dragon nests tend to spawn perched on mountains.  This second dragon died today at some point, and the prior day it was flying around like usual when I checked up on it.

Screenshots
Nest 1:
![2021-05-13_03 43 16](https://user-images.githubusercontent.com/2096384/118115191-81920580-b39d-11eb-9ec4-0ac0f325ea01.png)
Recent Corpse:
![2021-05-13_03 43 46](https://user-images.githubusercontent.com/2096384/118115212-88207d00-b39d-11eb-9aea-746ff0b41e27.png)

Nest 2:
![2021-05-13_03 43 54](https://user-images.githubusercontent.com/2096384/118115234-8a82d700-b39d-11eb-8de9-308a7a7ed773.png)

**Comment by Mooonblaze** [comment]
I am also having this issue in the latest version. It isn’t even limited to loaded chunks — people on my server just keep coming across dead dragons. More dead ones than living ones.

**Comment by Reshy** [comment]
Update:  Standing next to a dragon for a period of time, it's randomly taking damage while it's sleeping.


Perhaps dragons are supposed to be regenerating health while asleep, but are instead taking damage?

**Comment by TheBv** [comment]
Fixed with #3672
