### ISSUE TITLE
New Crash on Survival World 1.16.5 Custom Modpack Ice and Fire Version 2.1.6

### ISSUE THREAD

**Issue by Turbulence5101** [Alex-the-666/Ice_and_Fire#3868]
Hello, I was playing on my survival world, and while flying into a desert my game crashed. I know it's related to ice and fire as the crash log mentioned the issue related to a dragon. Would gladly appreciate the help as this is my long-running survival world :(

Not sure if this is related to another crash I remember seeing.

Crashlog: https://pastebin.pl/view/1a67f91a

**Comment by Rupeu** [comment]
The dragon is a ticking entity(corrupted mob). You will have to kill it since it will crash your game everytime. The dragon is located at 1783 23 -3100.

**Comment by Turbulence5101** [comment]
> The dragon is a ticking entity(corrupted mob). You will have to kill it since it will crash your game everytime. The dragon is located at 1783 23 -3100.

got it, thank you! I dont suppose it's possible to know what mod might have corrupted the dragon? When I relogged the dragon seemed fine,(didnt want to attack though) it was apparently a stage 4/5ish? female dragon (since she dropped an egg)

**Comment by Rupeu** [comment]
> > The dragon is a ticking entity(corrupted mob). You will have to kill it since it will crash your game everytime. The dragon is located at 1783 23 -3100.
> 
> got it, thank you! I dont suppose it's possible to know what mod might have corrupted the dragon? When I relogged the dragon seemed fine,(didnt want to attack though) it was apparently a stage 4/5ish? female dragon (since she dropped an egg)

Im not really sure there is way to know what corrupted the dragon. Tho i recommend you watch this tutorial on the ticking entity error as it explains in detail https://youtu.be/16gt5MCkVNc. Also if you killed the dragon that got corrupt you should back up your world in case the problem persists and gets at the point where you cant do anything about it.

**Comment by Turbulence5101** [comment]
> > > The dragon is a ticking entity(corrupted mob). You will have to kill it since it will crash your game everytime. The dragon is located at 1783 23 -3100.
> > 
> > 
> > got it, thank you! I dont suppose it's possible to know what mod might have corrupted the dragon? When I relogged the dragon seemed fine,(didnt want to attack though) it was apparently a stage 4/5ish? female dragon (since she dropped an egg)
> 
> Im not really sure there is way to know what corrupted the dragon. Tho i recommend you watch this tutorial on the ticking entity error as it explains in detail https://youtu.be/16gt5MCkVNc. Also if you killed the dragon that got corrupt you should back up your world in case the problem persists and gets at the point where you cant do anything about it.

I'll be sure to do that, thank you!

**Comment by AlexModGuy** [comment]
#3938
