### ISSUE TITLE
How to config dragon spawn rates?

### ISSUE THREAD

**Issue by Mr-Syntax** [Alex-the-666/Ice_and_Fire#3869]
let me first start of by saying amazing mod, really there is so much cool content

but if you could re-organize the config file so for example all cyclops configs are placed after eachother it would be alot easier to edit

it would also be extremely helpful if we could setup dragon spawns either in the config or through terraforged. love the mod but i want slightly less dragons to make it fit well with my pack.

**Comment by PlayMCwithMe** [comment]
just use this mod https://www.curseforge.com/minecraft/mc-mods/configured
and close this issue

**Comment by TheBv** [comment]
#3753
