### ISSUE TITLE
NoClassDefFoundError [iceandfire-2.1.6-1.16.4]

### ISSUE THREAD

**Issue by ArchieBeepBoop** [Alex-the-666/Ice_and_Fire#3871]
**Describe the bug**
Due to a missing definition, a dedicated server setup will crash.
java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/entity/IafDragonDestructionManager
	at com.github.alexthe666.iceandfire.entity.EntityIceDragon.stimulateFire(EntityIceDragon.java:479) ~

Crashlog included below in a pastebin.

**To Reproduce**
1. Host a dedicated server
2. Explore until ice dragons spawn
3. See error

**Expected behavior**
Not a crash.

**Additional context**
https://pastebin.com/8uA6Fm6b

**Comment by AlexModGuy** [comment]
#3938
