### ISSUE TITLE
NoClassDefFoundError and IafDamageRegistry in DragonUtils. ver iceandfire 2.1.6

### ISSUE THREAD

**Issue by Exlatus** [Alex-the-666/Ice_and_Fire#3875]
I think i found some mob or spawner. And catch this crash.
Some letters:

Description: Ticking entity
java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/entity/util/DragonUtils

And another crash. 
Description: Ticking entity
java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/misc/IafDamageRegistry

CrashLog:
first(DragonUtils) ... [https://pastebin.com/m38LfdNR](https://pastebin.com/m38LfdNR)
second(damage) ... [https://pastebin.com/3udbNRKw](https://pastebin.com/3udbNRKw)

**Comment by AlexModGuy** [comment]
#3938
