### ISSUE TITLE
Ice And Fire FoodUtils crashing my world

### ISSUE THREAD

**Issue by Klouver-github** [Alex-the-666/Ice_and_Fire#3877]
https://paste.gg/p/anonymous/8741b5dc0ad346a0ab7eae946b67f856

**Comment by Thombias** [comment]
Getting the same crash every 10-30 minutes or so. Sometimes i just stand around doing nothing and it crashes, the other time it happened was when i left the nether and interacted with a chest. It's really random. Hope this gets fixed as it's the only thing that crashes my 140 mods modpack.

**Comment by FlameyFaucet** [comment]
same here. i ran into a dragon and it instantly crashed my game with this error

**Comment by Klouver-github** [comment]
I cant even feed my Bee Farm without crashing after 2 minutes

**Comment by Jackiecrazy** [comment]
This is also consistently happening on my world. I presume a dragon is trying to eat something?

**Comment by itsfriday19** [comment]
also got a FoodUtils crash, specifically when I found an ice dragon cave and it saw me through the walls somehow? and rushed me. I heard it do its dragon breath and tons of blocks breaking, then the game window just closed. 
[crash-2021-06-09_13.27.35-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6625769/crash-2021-06-09_13.27.35-server.txt)

**Comment by AlexModGuy** [comment]
#3938
