### ISSUE TITLE
ClassNotFoundException when collecting the dragon back into the pot [2.1.6-1.16.4]

### ISSUE THREAD

**Issue by mio9** [Alex-the-666/Ice_and_Fire#3880]
**Describe the bug**
When collecting the ice dragon (probably other dragons as well), the server will crash with ClassNotFoundException

**To Reproduce**
1. Release an ice dragon
2. Let it fly around / forge something
3. Collect it back to the pot
4. Crash

**Expected behavior**
The dragon collected back into the pot like the master ball

**Screenshots**
Log file: https://gist.github.com/mio9/73e01ed98baa5f91dd6958d518ac77e2

**Additional context**
Mod is running together with other mods included by "ATM6: To the Sky"

**Comment by AlexModGuy** [comment]
#3938
