### ISSUE TITLE
Spawning for certain mobs not working [2.1.6-1.16.5]

### ISSUE THREAD

**Issue by SuicuneRules** [Alex-the-666/Ice_and_Fire#3882]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
So as i've been playing this mod recently i've noticed that some mobs haven't been spawning. Specificly the amohitheres, myrmex, and the death worms. I have not seen any of these spawn naturally what so ever, and I have tested this on both just this mod and using other mods as well thinking there might have been some complications.

**To Reproduce**
1. Go to a new world
2. fly around or walk around (easier in creative or in spectator mode)
3. See error

**Expected behavior**
I would expect that these things would spawn and i'm worried that there's something i'm not doing sense everything else seems to be working fine.

**Screenshots**

**Additional context**

**Comment by Jackiecrazy** [comment]
I have this same issue.

**Comment by TheBv** [comment]
Make sure to use citadel version 1.6.2 or newer
