### ISSUE TITLE
Ice And Fire banner patterns

### ISSUE THREAD

**Issue by kittylegitcheck** [Alex-the-666/Ice_and_Fire#3889]
In a modpack with 40-50 mods the banners are not working
**To Reproduce**
https://drive.google.com/drive/folders/1GmRHh21xo64LNe1TsWlGjbPFqPQRWl3C?usp=sharing
Mods are in link above

**Screenshots**
![image](https://user-images.githubusercontent.com/79789524/118944923-4bccbe00-b955-11eb-9b23-06804fe5ce5d.png)

**Comment by AlexModGuy** [comment]
incompatiblity with a few mods who do tricky asset loading, notably mowzie's mobs and extra storage
