### ISSUE TITLE
Siren overspawn Version 2.1.6

### ISSUE THREAD

**Issue by BushTrocity** [Alex-the-666/Ice_and_Fire#3890]
Sirens wont stop spawning in the twilight forest. It gets to the point where it will crash my server in a few mins.
It might also happen if you make a RFtools Dim but i have no tested this.

Not sure what caused the issue in the first place so i cant give details on how to replicate it.

![Siren](https://user-images.githubusercontent.com/3528732/118997196-779c7380-b956-11eb-8d10-431c89cfa81e.png)

**Comment by xSwaight** [comment]
I've got the same issue in 2.1.6 in the nether
