### ISSUE TITLE
Case study [ICE AND FIRE VERSION 2.1.6]

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#3891]
It's a new day,

Gotta stay alive.

Just answer is it your will to survive.

Playing hardcore all alone.

I've gotta get to the end on my own.

Grabbing my pick,

Got some things to find.

I know I have to explore it's a grind.

Building a house,

A new home

Journey into the unknown.

If you can craft, You can mine

Or use a sword you decide,

Just do your best in this fight.

There is only one way through the night.

Here in this hell,

I've been once before.

Getting that blaze rod I need just one more.

Make no mistake,

Not this time.

Victory soon will be mine.

Got what I need, Got all my supplies.

I want to conquer the end, That's my prize.

Who is that girl?

I don't know.

Is she a friend or a foe?

If you can craft, You can mine

Or use a sword you decide.

Just do your best in this fight,

There is only one way through the night.

This is the goal we've been working for,

Defeat the ender dragon,

Win the war.

There's no way back,

Down below.

Into the void we will go.

Desolate place now we're all alone,

We have to fight to the death,

Can't go home.

No option to run away,

Give our best,

Win the day.

If you can craft, You can mine

Or use a sword, You decide.

Just do your best in this fight,

There is only one way through the night.

If you can craft, You can mine

Or use a sword, You decide.

Just do your best in this fight,

There is only one way through the night.

**Comment by PlayMCwithMe** [comment]
delete this

**Comment by Corvus20** [comment]
but why tho

**Comment by AlexModGuy** [comment]
can you like; shut up
