### ISSUE TITLE
Trolls spawn and YUNG's Better Caves

### ISSUE THREAD

**Issue by MrEcko19** [Alex-the-666/Ice_and_Fire#3896]
Hi!
I don't know if I'm the only one, but I cant find trolls spawning in caves.

Probably this is happening because other mods changing caves like Quark, Subterranean Wilderness and YUNG's Better Caves.
Because of the Trolls 3-4 height blocks I think i'ts impossible for them for spawn in the caves, the complete overhaul makes them more strechy expect in some points and they are not spawning there neither.

Just for you to know, cause I don't know if this can be fixed or not.

Thank you!

**Comment by PssbleTrngle** [comment]
I also use quark and yungs better caves and have not seen a single troll

**Comment by TheYoloPanda** [comment]
Same issue here

**Comment by Syrikal** [comment]
Trolls are ridiculously, absurdly rare. I'd recommend upping their spawn rate in the configs.

**Comment by NixityNull** [comment]
I set troll spawn weight to 100 and still have yet to see one
