### ISSUE TITLE
CTD after removing Ice and Fire

### ISSUE THREAD

**Issue by CloWnicide** [Alex-the-666/Ice_and_Fire#3898]
I've been having this issue for the last 2 days after removing Ice and Fire from my modpack: java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/block/BlockGoldPile.

I cannot figure out how to fix this and keep having to re-add the mod back into the modpack, any ideas or specific way to fix this?

**Comment by CloWnicide** [comment]
For some reason, Allthemodium is causing the issue..

**Comment by AlexModGuy** [comment]
#3938
