### ISSUE TITLE
strange bug, 1.12

### ISSUE THREAD

**Issue by drkanbs** [Alex-the-666/Ice_and_Fire#3899]
Through exploring I stumbled on a lvl4 female fire dragon. I killed her but her body just laid there, not dropping anything and just shaking funny.  There was still oddly a hit box as well. Figured it was an odd bug and let it go,  but I know I've missed out on drops.

**Comment by AlexModGuy** [comment]
1.12 no longer suported

**Comment by Lashriel** [comment]
Not a bug. Right-click the corpse with an empty hand to start "breaking" it and claim the loot - this is still the case as of the current version.
