### ISSUE TITLE
nullpointer ServerEvents.isAnimaniaChicken

### ISSUE THREAD

**Issue by EmbershadeSC** [Alex-the-666/Ice_and_Fire#3901]
**Describe the bug**
A few seconds into the FML loading, returns to the launcher with an Exit Code 0 error
[2021-05-23-11.log](https://github.com/Alex-the-666/Ice_and_Fire/files/6529120/2021-05-23-11.log)
[crash-2021-05-23_15.59.22-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6529121/crash-2021-05-23_15.59.22-server.txt)

**To Reproduce**
1. Attempt to open game
2. Crash

**Expected behavior**
The game actually loads so I can play it

**Screenshots**
![image](https://user-images.githubusercontent.com/48605020/119280429-9f0d6d80-bbee-11eb-9124-8121fb373ceb.png)

**Comment by EmbershadeSC** [comment]
I mention this here because this started happening when I removed Fire and Ice to try to fix the game crashing due to a broken mob from this mod, but it still crashes after I put it back

**Comment by FlameyFaucet** [comment]
looking into your error log and it seems an enderman that you had around in the world has been corrupted and caused a ticking entity error. your best bet is using something to remove that entity from the world (not killing it, straight up deleting) or just make a new one.
