### ISSUE TITLE
Game Crash (Ice and Fire potential cause)

### ISSUE THREAD

**Issue by raffebaba** [Alex-the-666/Ice_and_Fire#3903]
Whenever I try to connect to the server, I join the game but the game crashes instantly.
To note that I am playing on a RAD mod but it is indicated that the potential cause is coming from the Ice And Fire mod.
I have tried to uninstall the mod, Minecraft and CurseForge and reinstall it but it does not help.

1. Launch the RAD mod
2. Click Join the server
3. See "Minecraft crashed!"

**Expected behavior**
Being able to join the server and play normally.

**Screenshots**

![image](https://user-images.githubusercontent.com/84729047/119370483-992e8f80-bcb5-11eb-950e-c0ef0fb11a4e.png)

**Comment by AlexModGuy** [comment]
1.12 no longer supported
