### ISSUE TITLE
Controlling hippogryph while flying doesn't move

### ISSUE THREAD

**Issue by plantyourcrop** [Alex-the-666/Ice_and_Fire#3905]
**when you ride hippogryph and fly it will stop moving and just go up.you can control it again if you dismount and ride it again**

**Screenshots**

**Additional context**

**Comment by plantyourcrop** [comment]
I don't really need hippogryph but this need to fix

**Comment by BlackInkBlood** [comment]
I am having this same issue. On first taking off, everything seems to be okay, but if I stop midair I lose functionality. The hippogryph will move very slowly forward, but I cannot get it to go up or down. Sometimes it will pickup speed after a delay, but ascending and descending usually remain bugged. I am using Ice and Fire with other mods.

MC Version: 1.16.5
Forge: 36.1.23

**Comment by plantyourcrop** [comment]
it doesn't effect it with other mods I tried it without a mod and it's still like that

**Comment by Irellafael** [comment]
Same issue here. First I thought it was just the server, but it happens in single player too. I only use the Ice and Fire mod and required mods. It did not occur in earlier versions, for example in version 2.1.5-1.16.4 it worked fine.

**Comment by plantyourcrop** [comment]
ikr

**Comment by NyanRose** [comment]
Also having the same issue, which was rather disappointing after getting my first hippogryph. Keeping an eye for any updates! It can get frustrating when it stalls and stops responding in air

**Comment by Irellafael** [comment]
I know, makes me want to smash my keyboard haha. I switched to Amphithere (they have a different control, more like dragons I found out). But it's just not the same..

**Comment by NyanRose** [comment]
It's better with the  2.1.7 update!
