### ISSUE TITLE
Gorgon Corrupted Chunk [2.1.6]

### ISSUE THREAD

**Issue by Artimba** [Alex-the-666/Ice_and_Fire#3909]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Upon being killed/stoned by a Gorgon, the chunk went corrupt, crashing the player killed and kicking all other players in the chunk. After being disconnected, all players caught in it were greeted to a message saying the NBT data was too large.

gist of my log:
https://gist.github.com/Skyibis/c99a1b29edca89881672201cacd3a15f
gist of another player who was caught in the crash's log:
https://gist.github.com/Skyibis/b0f63cbd250b8a0409911a100ccd9911

**To Reproduce**
Be killed by a Gorgon on latest version

**Expected behavior**
To be killed normally

**Screenshots**

**Additional context**
The crash was followed with errors following NBT data being too large. I am playing with enhanced visuals, and I had recently experienced a bug with them involving instant kills and the damage handler causing the client to hang and become unresponsive. We got it patched, but I suspect this might be a possible cause. I'm playing on a custom modpack and I recognize this might be an issue that is unrelated to your mod. I haven't done any more testing, but I thought you could provide some light by looking at the crash log and seeing if its something relating to your mod or something I should fix elsewhere. Thank you!

**Comment by firemaster1294** [comment]
I've had this issue too and I've identified the cause to be the stone statue. I was able to solve this issue by force loading the chunk (/forceload add x-coord z-coord) and then killing the stone statue entity (/kill @e[type=iceandfire:stone_statue])

**Comment by Artimba** [comment]
This fixed it! Thank you! does this happen in the standalone mod or is it a conflict with something like Enhanced Visuals or Corpse?

**Comment by firemaster1294** [comment]
Seeing as I don’t have either of those installed, I’m tempted to say it’s with the standalone? I’m not 100% certain though

**Comment by joeyjumper94** [comment]
do you have any mods for extra player inventory?
or anything else that adds even more NBT data to players?
i think your issue is caused by excessive amounts of NBT data on a statue

**Comment by Artimba** [comment]
> do you have any mods for extra player inventory?
> or anything else that adds even more NBT data to players?
> i think your issue is caused by excessive amounts of NBT data on a statue

We have curios and cosmetic armor that gets the closest to adding extending inventory, the mod list is 130+ strong, so there is a lot that could be going on with NBT, I haven't had a chance to test it standalone yet.

**Comment by ShiriYeka** [comment]
I had this problem just like 1 hour ago! Lol...
But this problem was with my server friend killing me with the Gorgon Head Legendary Weapon, the two of us got kicked by the server and the error code was the same about NBT data too large.. 
I have curious forge, Gravestone and Traveller's Backpack.
