### ISSUE TITLE
Crash on server NoClassDefFoundError

### ISSUE THREAD

**Issue by tyra314** [Alex-the-666/Ice_and_Fire#391]
I get the following crash on my server.

java.lang.NoClassDefFoundError: net/minecraft/client/particle/Particle

https://gist.github.com/tyra314/f69aa1516dae687b18be61f9d5367a18

I'm using:

- Minecraft: 1.12.2
- Forge: 14.23.1.2582
- Ice and Fire: 1.3.0

**Comment by Frosty8-0** [comment]
The new update came out that fixed that.

**Comment by tyra314** [comment]
Fixed for me. Thank you.
