### ISSUE TITLE
CTD 2.1.6-1.16.4.jar

### ISSUE THREAD

**Issue by nosnev** [Alex-the-666/Ice_and_Fire#3911]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Every time the save/world has loaded, its just crashed and close. Showing this kind of error. 
java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/client/model/IFChainBuffer

**To Reproduce**
1. Go to Saved World
2. Click on Play.
3. See error

**Expected behavior**
Play the Saved World, loaded to 100% then CTD. Then it shows the error, I had played with the Lightning Dragon already hatched up, so I really dunno whats wrong with here.

**Screenshots**
[crash-2021-05-27_00.25.49-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6548378/crash-2021-05-27_00.25.49-client.txt)

**Additional context**

**Comment by AlexModGuy** [comment]
#3938
