### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by KnoxTM** [Alex-the-666/Ice_and_Fire#3912]
**Describe the bug**
so we got a all the mods 6 server and if we go in the nether there are spawning more than 200 monsters of this Dread monsters and the server crashes how can i change that there dont spawn this much dread monsters if i join the nether

**Comment by Peanut81585** [comment]
A new version of all the mods 6 came out yesterday, 1.6.5 I think it is. I was able to update my local client and the server today and that solved this issue.
