### ISSUE TITLE
Bug in creative inventory

### ISSUE THREAD

**Issue by DevilKitten** [Alex-the-666/Ice_and_Fire#392]
All the Pixie Hovels in the creative inventory look the same, screenshot below. 
![image](https://user-images.githubusercontent.com/31811686/34471615-f47abb70-ef13-11e7-9b5d-13cd4254704a.png)

**Comment by Frosty8-0** [comment]
It doesn't do that for me.

**Comment by AlexModGuy** [comment]
fixed in 1.3.1
