### ISSUE TITLE
Server crashed cause by [ICE AND FIRE VERSION 2.1.6]

### ISSUE THREAD

**Issue by EYW-015** [Alex-the-666/Ice_and_Fire#3920]
I was attached by an Ice Dragon.
And I am Dead, at the same time Server crashed.

Run in Docker-ce
Image: "itzg/minecraft-server:java8"
Minecraft version 1.16.5
Ice and fire 2.1.6

Crash report file:
[crash-2021-05-31_22.45.25-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6571160/crash-2021-05-31_22.45.25-server.txt)

**Comment by AlexModGuy** [comment]
#3938
