### ISSUE TITLE
Lightning Dragons only spawn at badlands  [MC 1.16.5; I/F 2.1.6]

### ISSUE THREAD

**Issue by Phantom2909** [Alex-the-666/Ice_and_Fire#3921]
**Describe the bug**
Normally, the biomes in which L-Dragons can spawn are badlands, jungles and savannas, but they only spawn at badlands, not at savannas and jungles (Fire Dragons spawn at that biomes instead).

**To Reproduce**
1. Create a New World.
2. Use command /locatebiome ..... and search savannas or jungles.
3. See only Fire Dragons.

**Expected behavior**
Well, I expected that Lightning Dragons spawn at jungles, savannas and badlands, not only in one biome.

**Screenshots**

![2021-05-31_22 55 01](https://user-images.githubusercontent.com/70826397/120268523-96aad780-c26b-11eb-93a8-7d83a01162e6.png)
![2021-05-31_22 57 17](https://user-images.githubusercontent.com/70826397/120268552-a1fe0300-c26b-11eb-9e62-365151f4463d.png)
![2021-05-31_23 02 03](https://user-images.githubusercontent.com/70826397/120268562-a62a2080-c26b-11eb-839f-ffaaa1bb2f32.png)
![2021-05-31_23 02 52](https://user-images.githubusercontent.com/70826397/120268569-a9bda780-c26b-11eb-98c3-e5dfab442a1a.png)

**Additional context**
As you can see, in savanna and jungle only generated Fire roost and Fire nest.

**Comment by Samlegamer** [comment]
It also happened to me but it's not a bug, it's just that they are rarer than fire dragons 🔥
You can change their spawn rates in the configs.

**Comment by TheBv** [comment]
Was addressed with #3662
