### ISSUE TITLE
Cyclops crash issues [iceandfire-2.1.6-1.16.4]

### ISSUE THREAD

**Issue by RickBardock** [Alex-the-666/Ice_and_Fire#3922]
My world is fairly new, problems with cyclopes, it seems to me that the cyclops currently has picked up an npc. and keeps on crashing because the cyclops is currently holding the person. How do i go about disabling the cyclops's grab attack, to prevent future crashes? thank you.

        Entity Type: iceandfire:cyclops (com.github.alexthe666.iceandfire.entity.EntityCyclops)
	Entity ID: 109
	Entity Name: Cyclops
	Entity's Exact location: -2776.72, 65.00, 1683.25
	Entity's Block location: World: (-2777,65,1683), Chunk: (at 7,4,3 in -174,105; contains blocks -2784,0,1680 to -2769,255,1695), Region: (-6,3; contains chunks -192,96 to -161,127, blocks -3072,0,1536 to -2561,255,2047)
	Entity's Momentum: -0.01, -0.08, -0.03
	Entity's Passengers: [EntityCitizen['Jay B. Alessi'/107, l='ServerLevel[Bardocks Dream]', x=-2776.73, y=65.00, z=1686.06]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

[crash-2021-06-02_01.08.02-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6582271/crash-2021-06-02_01.08.02-server.txt)

**Comment by RickBardock** [comment]
Seems I cannot console kill the cyclops that has ahold of the npc in question. noone can join the server because of it, please assist.
![can't kill cyclops](https://user-images.githubusercontent.com/47097242/120431757-ef9b6e00-c346-11eb-8601-f67611cbf218.jpg)

**Comment by RickBardock** [comment]
I've had to set the cyclops to the minimum spawn chance to 1/10000 sadly seems like there is no way to disable with pickup mechanic that is crashing my server and there is currently no way that I know of to prevent spawning. Seems that It's a confliction with minecolonies and iceandfire. To resolve the cyclops's currently in the world, I had to delete the region file the mob was in and generate a new one. thank you for the mod and I look forward to a fix. please let me know if you need any additional information from me.

**Comment by TheBv** [comment]
Seems to have something todo with Minecolonies and not IceAndFire. Most likely a Cyclops picking up a Citizen from Minecolonies and it trying to pathfind while "riding" a cyclops. Might be mistaking though. Might be worth posting this on the minecolonies [github](https://github.com/ldtteam/minecolonies)

**Comment by TheBv** [comment]
Minecolonies has updated their pathfinding at some point to auto dismount if they are a passenger.
