### ISSUE TITLE
Death Worm Crash [2.1.6]

### ISSUE THREAD

**Issue by Syrikal** [Alex-the-666/Ice_and_Fire#3923]
**Describe the bug**
I'm trying to make an addon mod. When I add Ice & Fire as a dependency in build.gradle, I get this crash.

https://pastebin.com/tw7qQfuP

**Comment by TheBv** [comment]
Pretty sure this is an issue with mappings (as I found out when I tried to update them some time ago). 
This is an old issue... But try changing to forge mappings in case you're using the official ones. 
Closing since it's quite old....
