### ISSUE TITLE
Ice and Fire (iceandfire) has failed to load correctly [iceandfire-2.1.6-1.16.4.jar]

### ISSUE THREAD

**Issue by ReidosPlebs** [Alex-the-666/Ice_and_Fire#3925]
Hello, I am working on this modpack and when I try to launch it with Ice and Fire, this message is given when crashing(Removing the mod makes the game launch correctly) :

"Ice and Fire (iceandfire) has failed to load correctly
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered"

![error](https://user-images.githubusercontent.com/64786852/120716073-e8d23f80-c49b-11eb-9410-9a9af20683c9.png)

I already checked these things that might have caused the error:
- No Optifine
- No Fabric
- No Server Plugins
- Forge Version: 36.1.16
- Citadel Version: 1.6.3

Here is the crash report: https://pastebin.com/XN9ZyZge 

Has anyone suffered from the same or knows how to solve this problem? Thanks for the help!

**Comment by jamesheller0** [comment]
I have got the same issue 
and I think it happened after adding a mod so I think it must be an issue with that mod 
I can't remember exactly what mod it was but I think it was cyclic

**Comment by TheYoloPanda** [comment]
Did you find a solution?

**Comment by TheBv** [comment]
Seems to be related to `allthemodium`. Very unlikely that ice and fire was causing this since in version 2.1.6 it didn't event use any mixins.
