### ISSUE TITLE
Game crashes upon building of Beacon.

### ISSUE THREAD

**Issue by Taggart1993** [Alex-the-666/Ice_and_Fire#3928]
![2021-06-08_08 01 15](https://user-images.githubusercontent.com/85570109/121210052-3817c780-c830-11eb-975b-959ed262ce98.png)
Screenshot attached of Fire Dragonsteel Armor
Fire dragonsteel armor texture bugged after I built a max-level beacon, then crashed game upon riding Fire Dragon (stage 4 male)
Total darkness is installed, it could be because it had trouble rendering at light level 0.

**Comment by AlexModGuy** [comment]
defo #3938 interrupting asset loading
