### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by isrever** [Alex-the-666/Ice_and_Fire#3931]
**Describe the bug**
When using citadel 1.7.0, ice and fire the server crashes and stops.

09.06 21:06:38 [Server] INFO Ice and Fire (iceandfire) encountered an error during the common_setup event phase
09.06 21:06:38 [Server] INFO java.lang.NoClassDefFoundError: com/github/alexthe666/citadel/server/entity/EntityPropertiesHandler
09.06 21:

**To Reproduce**
1. download citadel 1.7.0
2. put citdadel in the mod folder
3. load the server

**Expected behavior**
Server should start, i reverted back to citadel 1.6.3 to make this work

**Comment by AlexModGuy** [comment]
its not ready for citadel 1.7.0 yet, please wait for the next iaf update
