### ISSUE TITLE
2.1.1-1.16.4 - Ice and Fire mobs don't spawn 

### ISSUE THREAD

**Issue by Dexii21** [Alex-the-666/Ice_and_Fire#3936]
2.1.1-1.16.3 (Game version 1.16.4) - Ice and Fire mobs don't spawn (randomly). You can run for miles n' hours, you won't see a single modded creature (pixies, dragons etc.:). All that spawns/you see are the default creatures (zombies, creeper etc.:). Please fix :)

**Comment by Nebula240** [comment]
Why are you using 2.1.1? Latest is 2.1.7
