### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by AlexModGuy** [Alex-the-666/Ice_and_Fire#3938]
Megaissue due to pathfinding, may already be fixed in 2.1.7.

**Comment by astrostl** [comment]
Is this closing #3776 as FIXED or as TRY AGAIN WITH THE NEW RELEASE?

In any case, thanks!

**Comment by AlexModGuy** [comment]
it should hopefully be fixed in 2.1.7. I'll need to do more testing first.

**Comment by AlexModGuy** [comment]
fixed https://github.com/Alex-the-666/Ice_and_Fire/commit/b5d45eefbb087c8376f5f2553075bf3ce155a127
