### ISSUE TITLE
Issue with loading

### ISSUE THREAD

**Issue by AJM-IKE** [Alex-the-666/Ice_and_Fire#3940]
I am having trouble with loading my game.
![Screenshot (36)](https://user-images.githubusercontent.com/85705211/121583283-ea908b80-c9e4-11eb-9b70-54eafac3129c.png)

**Comment by kamekkoopa** [comment]
I'm having the same issue.

**Comment by Jordan231111** [comment]
same i think the latest versions of citadel is bugged. this did not happen before updating citadel today
