### ISSUE TITLE
[2.1.7 - 1.16.5] Hippogryph Ticking Entity Crash

### ISSUE THREAD

**Issue by Flashbackmaniac** [Alex-the-666/Ice_and_Fire#3942]
**Bug description:**
When a Hippogryph flies in an enclosed space, it will crash the client after a short while.

**Steps to reproduce the behavior:**
1. Spawn a Hippogryph inside an enclosure using its spawn egg or via /summon.
2. Wait for it to start flying.
3. After a short time period, the client crashes.

**Expected behavior:**
I expected the Hippogryph to not crash the client.

**Crash log:**
[crash-2021-06-10_22.36.36-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6635696/crash-2021-06-10_22.36.36-server.txt)

**Additional Context:**
Wild Hippogryphs that fly in the Overworld don't seem to have any issues, however, I'd imagine that this crash could be encountered if they flew into obstructions like the overhangs in mountain biomes.

**Comment by Doominic08** [comment]
Had this same issue earlier, all i did was ride the hippogryph that the server said was the ticking entity and that solved my problem, i hope there is an official patch for this soon though.
