### ISSUE TITLE
2.1.7 server crash

### ISSUE THREAD

**Issue by Jordan231111** [Alex-the-666/Ice_and_Fire#3945]
[Server] main/ERROR [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: com.github.alexthe666.iceandfire.recipe.DragonForgeRecipe.<init>(Lnet/minecraft/item/ItemStack;Lnet/minecraft/item/ItemStack;Lnet/minecraft/item/ItemStack;)V
11.06 09:31:57 [Server] INFO Index: 7
11.06 09:31:57 [Server] INFO Listeners:
11.06 09:31:57 [Server] INFO 0: NORMAL
11.06 09:31:57 [Server] INFO 1: ASM: net.minecraftforge.registries.DeferredRegister$EventDispatcher@46efdc9c handleEvent(Lnet/minecraftforge/event/RegistryEvent$Register;)V
11.06 09:31:57 [Server] INFO 2: ASM: net.minecraftforge.registries.DeferredRegister$EventDispatcher@1c203f57 handleEvent(Lnet/minecraftforge/event/RegistryEvent$Register;)V
11.06 09:31:57 [Server] INFO 3: ASM: net.minecraftforge.registries.DeferredRegister$EventDispatcher@50da75ce handleEvent(Lnet/minecraftforge/event/RegistryEvent$Register;)V
11.06 09:31:57 [Server] INFO 4: ASM: net.minecraftforge.registries.DeferredRegister$EventDispatcher@41d3e442 handleEvent(Lnet/minecraftforge/event/RegistryEvent$Register;)V
11.06 09:31:57 [Server] INFO 5: ASM: class com.thevortex.allthemodium.AllTheModium$MekRegistry onSlurryRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
11.06 09:31:57 [Server] INFO 6: ASM: class com.thevortex.allthemodium.AllTheModium$RegistryEvents onBlocksRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
11.06 09:31:57 [Server] INFO 7: ASM: class com.thevortex.allthemodium.AllTheModium$RegistryEvents onItemsRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
11.06 09:31:57 [Server] INFO 8: ASM: class com.thevortex.allthemodium.AllTheModium$RegistryEvents onTERegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
11.06 09:31:57 [Server] INFO java.lang.NoSuchMethodError: com.github.alexthe666.iceandfire.recipe.DragonForgeRecipe.<init>(Lnet/minecraft/item/ItemStack;Lnet/minecraft/item/ItemStack;Lnet/minecraft/item/ItemStack;)V
11.06 09:31:57 [Server] INFO at com.thevortex.allthemodium.init.IAFForgeRecipes.init(IAFForgeRecipes.java:36)
11.06 09:31:57 [Server] INFO at com.thevortex.allthemodium.AllTheModium$RegistryEvents.onItemsRegistry(AllTheModium.java:110)
11.06 09:31:57 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler_309_RegistryEvents_onItemsRegistry_Register.invoke(.dynamic)
11.06 09:31:57 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
11.06 09:31:57 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
11.06 09:31:57 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
11.06 09:31:57 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120)
11.06 09:31:57 [Server] INFO at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121)
11.06 09:31:57 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
11.06 09:31:57 [Server] INFO at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56)
11.06 09:31:57 [Server] INFO at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40)
11.06 09:31:57 [Server] INFO at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:243)
11.06 09:31:57 [Server] INFO at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230)
11.06 09:31:57 [Server] INFO at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:196)
11.06 09:31:57 [Server] INFO at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44)
11.06 09:31:57 [Server] INFO at net.minecraft.server.Main.main(Main.java:95)
11.06 09:31:57 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11.06 09:31:57 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11.06 09:31:57 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11.06 09:31:57 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498)
11.06 09:31:57 [Server] INFO at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
11.06 09:31:57 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
11.06 09:31:57 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
11.06 09:31:57 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
11.06 09:31:57 [Server] INFO at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
11.06 09:31:57 [Server] INFO at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
11.06 09:31:57 [Server] INFO at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
11.06 09:31:57 [Server] INFO at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
11.06 09:31:57 [Server] INFO at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
11.06 09:31:58 [Server] main/ERROR [ne.mi.fm.ja.FMLModContainer/LOADING]: Caught exception during event RegistryEvent.Register<minecraft:item> dispatch for modid allthemodium
11.06 09:31:58 [Server] INFO java.lang.NoSuchMethodError: com.github.alexthe666.iceandfire.recipe.DragonForgeRecipe.<init>(Lnet/minecraft/item/ItemStack;Lnet/minecraft/item/ItemStack;Lnet/minecraft/item/ItemStack;)V
11.06 09:31:58 [Server] INFO at com.thevortex.allthemodium.init.IAFForgeRecipes.init(IAFForgeRecipes.java:36) ~[allthemodium:1.5.0-1.16.5-36.1.0] {re:classloading}
11.06 09:31:58 [Server] INFO at com.thevortex.allthemodium.AllTheModium$RegistryEvents.onItemsRegistry(AllTheModium.java:110) ~[allthemodium:1.5.0-1.16.5-36.1.0] {re:classloading}
11.06 09:31:58 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler_309_RegistryEvents_onItemsRegistry_Register.invoke(.dynamic) ~[?:?] {}
11.06 09:31:58 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
11.06 09:31:58 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
11.06 09:31:58 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
11.06 09:31:58 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:36.1] {re:classloading}
11.06 09:31:58 [Server] INFO at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:classloading}
11.06 09:31:58 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_302] {}
11.06 09:31:58 [Server] INFO at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[forge:?] {re:classloading}
11.06 09:31:58 [Server] INFO at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[forge:?] {re:classloading}
11.06 09:31:58 [Server] INFO at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:243) ~[forge:?] {re:classloading}
11.06 09:31:58 [Server] INFO at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[forge:?] {re:classloading}
11.06 09:31:58 [Server] INFO at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:196) ~[forge:?] {re:classloading}
11.06 09:31:58 [Server] INFO at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
11.06 09:31:58 [Server] INFO at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
11.06 09:31:58 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302] {}
11.06 09:31:58 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302] {}
11.06 09:31:58 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302] {}
11.06 09:31:58 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302] {}
11.06 09:31:58 [Server] INFO at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[idk.jar:36.1] {}
11.06 09:31:58 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
11.06 09:31:58 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
11.06 09:31:58 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
11.06 09:31:58 [Server] INFO at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
11.06 09:31:58 [Server] INFO at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
11.06 09:31:58 [Server] INFO at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)

**Comment by AlexModGuy** [comment]
remove whatever mod is trying to add craftweaker support for ice and fire, its been removed

**Comment by CKY-** [comment]
that include KubeJS?
