### ISSUE TITLE
Unable to modify Dragonforge recipes? [ICE AND FIRE 2.1.7]

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#3946]
Hello, apologies for not using the issue template, but as this  is more a question than a bug report the template didn't really fit what I am asking for.

Version 2.1.7 of Ice and Fire removed CraftTweaker support, so the scripts I was using to modify/add recipes to the Dragonforge no longer work. Is there any alternative method to modify or add new Dragonforge recipes?

**Comment by Virtualhel** [comment]
Yes, there is a way to modify the recipes with a datapack. To change the recipes, you will need to make copies of the following files: `dragonsteel_fire_ingot.json`, `dragonsteel_ice_ingot.json`, and `dragonsteel_lightning_ingot.json`. Then, open the files in a text editor and modify what you want. Next, you will need to create a pack.mcmeta file and the rest of the datapack structure [(this page will help)](https://minecraft.fandom.com/wiki/Data_Pack). For Ice and Fire, your file structure will look like /<datapack name>/data/iceandfire/dragonforge_recipes/.

**Comment by ghost** [comment]
Thanks. Was just hoping to avoid using a datapack if possible (since so far I've been able to use CraftTweaker for everything I've wanted to modify).

Appreciate the information though!

**Comment by egshels** [comment]
hey, i tried this and it's not working correctly. Making Dragonsteel use Netherite Ingots instead of Iron gives me Dragon Ice when used in an ice dragon forge...

**Comment by Virtualhel** [comment]
> hey, i tried this and it's not working correctly. Making Dragonsteel use Netherite Ingots instead of Iron gives me Dragon Ice when used in an ice dragon forge...

That means your datapack did not work correctly and the recipe did not change. I ended up making a datapack for myself so I can just send it here: 
[Netherite_Dragonsteel_fixed.zip](https://github.com/Alex-the-666/Ice_and_Fire/files/6819011/Netherite_Dragonsteel_fixed.zip)

**Comment by StrangerSon71** [comment]
This needs to stay open because crafttweaker .JSON support is broken in it.

**Comment by TheBv** [comment]
Craft Tweaker Support was removed in 2.1.7

**Comment by Gothic1096** [comment]
> > эй, я попробовал это, но у меня не получилось. Если использовать слитки незерита вместо железа в кузнице ледяного дракона, то получится драконий лёд...
> 
> Это означает, что ваш пакет данных не сработал должным образом и рецепт не изменился. В итоге я создал пакет данных для себя, чтобы просто отправить его сюда: [Netherite_Dragonsteel_fixed.zip](https://github.com/Alex-the-666/Ice_and_Fire/files/6819011/Netherite_Dragonsteel_fixed.zip)

version 1.20.1. turns into ashes instead of ingots for me. Can you explain what I'm doing wrong?
