### ISSUE TITLE
[2.1.7 - 1.16.5] Mausoleum Feature Placement Crash 

### ISSUE THREAD

**Issue by Flashbackmaniac** [Alex-the-666/Ice_and_Fire#3947]
**Bug description:**
While flying around a snowy biome, my game suddenly crashed. Looking at the crash report, it said something about a mausoleum, possibly related to its generation.

**Steps to reproduce the behavior:**
1.) Create a new world and look for snowy biomes that can generate mausoleums.
2.) Potentially encounter a crash, as it seems to happen at random while exploring the world and generating chunks. On another world to test whether the crash was repeatable, I used /locate to find a mausoleum, and that time it didn't crash.

**Expected behavior:**
I expected the generation of mausoleums (and perhaps other structures) to not crash my game.

**Crash log:**
[crash-2021-06-11_16.35.52-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6641102/crash-2021-06-11_16.35.52-server.txt)

**Comment by Doominic08** [comment]
I'm having the same issue except with graveyards.
