### ISSUE TITLE
Issues with Dragon Eggs, Baby Dragon in Shoulder, and Achievements

### ISSUE THREAD

**Issue by AguilaDaddy** [Alex-the-666/Ice_and_Fire#395]
- When you put a baby dragon in you shoulder, they don't sit, and they keep standing as if they were on ground
- The dragon eggs now have different textures of a texture pack
- Ice and Fire Achievements not working

**Comment by AlexModGuy** [comment]
Well, there are no more achivements in 1.12.2, so of course not :P

**Comment by AlexModGuy** [comment]
dupe issue
