### ISSUE TITLE
Gorgon Temple crash [2.1.7-1.16.5]

### ISSUE THREAD

**Issue by Devintrainer** [Alex-the-666/Ice_and_Fire#3951]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Trying to spawn a gorgon temple causes the game to crash.

**To Reproduce**
1. Go to wherever the temple spawns. In my case, the ocean.
2. See error

**Additional context**
I feel like the new update introduced multiple bugs involving structure generation causing crashes.

**Comment by DrPenguinni** [comment]
Did this crash happen in a server?
