### ISSUE TITLE
Config problem

### ISSUE THREAD

**Issue by jonyuy** [Alex-the-666/Ice_and_Fire#3952]
every time i change the value of  "#1 out of this number chance per chunk for generation    #Range: 1 ~ 10000"
and i start the game it simply rewrites it self or recreates the folder and it makes it impossible to change the value for dragon caves spawning

**Comment by TheBv** [comment]
You're probably editing the config file incorrectly so the file can't be read correctly hence it get's overwritten. If you want to increase the value to 1200 here's an example:
```
#1 out of this number chance per chunk for generation
#Range: 1 ~ 10000
"Spawn Wandering Cyclops Chance" = 1200
```
