### ISSUE TITLE
Hippogryph AI Ticking Entity [2.1.7]

### ISSUE THREAD

**Issue by Tyrius1** [Alex-the-666/Ice_and_Fire#3955]
Minecraft 1.16.5
Forge 36.1.31
Ice and Fire 2.1.7
Flying around in creative and randomly crashed
https://pastebin.com/9nL6r98A

**Comment by brisingraerowing** [comment]
[The line that crashes](https://github.com/Alex-the-666/Ice_and_Fire/blob/1.16.3/src/main/java/com/github/alexthe666/iceandfire/entity/EntityHippogryph.java#L1247)

I presume the mod failed to get a block for some reason, resulting in `target` being null.

**Comment by dogdude1** [comment]
I have the same issue
