### ISSUE TITLE
[2.1.7 - 1.16.5] Camera Bug

### ISSUE THREAD

**Issue by Flashbackmaniac** [Alex-the-666/Ice_and_Fire#3956]
**Bug description:**
A dragon with a day counter above 125 will shift the camera upwards for each day incremented, despite the dragon's growth capping at day 125. This affects both first and third-person views when riding the dragon.

**Steps to reproduce the behavior:**
1. Summon any dragon with a day counter of 125 (3,000,000 ticks) and tame it.
2. Summon another dragon of any kind with a day counter of 500 (12,000,000 ticks) and tame it as well.
3. Mount each of the two dragons and compare the camera positions. The older dragon will noticeably have the camera positioned higher than the younger dragon.

**Expected behavior:**
I expected the camera's position to be constant after the dragon stops growing at day 125.

**Screenshots:**
Screenshot 1: Dragon at day 125.
![image](https://user-images.githubusercontent.com/85721756/121820647-a35f0080-cc59-11eb-9bde-8b4cfad31fb6.png)
Screenshot 2: Dragon at day 500.
![image](https://user-images.githubusercontent.com/85721756/121820781-40ba3480-cc5a-11eb-9bef-4228a40f9dd1.png)
**Additional context:**
The shifting of the camera is not as noticeable initially past day 125, however, it seems to exacerbate with the increasing of the dragon's age. This is a problem I encountered with two of my tamed dragons with day counters averaging around 500, where mounting those two results in the camera being shifted higher than it should be. I suspect that the camera's adjustment with the dragon's age is not capped like the dragon's growth at day 125.

**Comment by TheBv** [comment]
The hitbox of the player/ the player itself seems to get shifted upwards even after day 125... I don't exactly know what's causing this but I'll try look into it.
![2021-06-14_16 59 17](https://user-images.githubusercontent.com/12676257/121914029-323f4c00-cd32-11eb-890b-851f7b3d5bae.png)
![2021-06-14_16 59 30](https://user-images.githubusercontent.com/12676257/121914036-32d7e280-cd32-11eb-87dd-9440735024af.png)
