### ISSUE TITLE
Mausoleum spawning one or two blocks above ground

### ISSUE THREAD

**Issue by sSpXrta** [Alex-the-666/Ice_and_Fire#3958]
**Describe the bug**
Every Mausoleum I've come across always has a one or two air block gap between it's base and the ground. Problem may have something to do with terraforged but I don't know for sure as I'm not an expert. 

**To Reproduce**
1. Possibly install terraforged as well as biome mods such as Biomes O Plenty and BYG
2. Just roam around until you find a mausoleum I guess
3. See error for yourself? 

**Expected behavior**
expect to see the building placed firmly on the ground without any weird gaps below that ruin the structure. 
![2021-06-13_23 38 38](https://user-images.githubusercontent.com/85858503/121837162-f5784400-cca2-11eb-8626-3e9e68586c24.png)

**Additional context**
Weird bug, happens to every single one I see. Might turn off Mausoleum spawns until bug is fixed. Thanks!

**Comment by TheBv** [comment]
I tried to recreate this issue with the latest stable release of terraforged(0.2.10) as well as IaF version 2.1.7 and I haven't been able to recreate this. If you're running different versions of either please let me know, otherwise if you have any other mods that could alter the terrain height map (I'm guessing that that would be the culprit) please let me know!

**Comment by sSpXrta** [comment]
> I tried to recreate this issue with the latest stable release of terraforged(0.2.10) as well as IaF version 2.1.7 and I haven't been able to recreate this. If you're running different versions of either please let me know, otherwise if you have any other mods that could alter the terrain height map (I'm guessing that that would be the culprit) please let me know!

Here's a list of all possible mods that I think might be causing this:

- BetterCaves
- Better Default Biomes
- Biomes O Plenty
- Biomes You'll Go
- Project Vibrant Journey's
- Subterranean Wilderness
- Terraforged

Here's a link to my [modpack](https://1drv.ms/u/s!AsA1i4MFDQ5OolNjwApru9zmiabb?e=EP11qI)

**Comment by TheBv** [comment]
I see you have Ice and Fire version 2.1.6 installed I'm pretty sure this issue shouldn't exist anymore in version 2.1.7.
The new version does seem to crash when playing in older worlds but it should be completely fine for newer ones. I have created a PR already though that addresses that issue #3961

**Comment by sSpXrta** [comment]
> I see you have Ice and Fire version 2.1.6 installed I'm pretty sure this issue shouldn't exist anymore in version 2.1.7.
> The new version does seem to crash when playing in older worlds but it should be completely fine for newer ones. I have created a PR already though that addresses that issue #3961

Okay! Thanks a lot. I'll try the new version and let you know if the problem persists.
