### ISSUE TITLE
Game crashes when enter certain biomes.

### ISSUE THREAD

**Issue by saiho23** [Alex-the-666/Ice_and_Fire#3959]
This is a great mod and I love it. A crashed report is below .I hope this can be fixed :)
Thank you for your time 

[crash-2021-06-14_10.50.45-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6647886/crash-2021-06-14_10.50.45-server.txt)

**Comment by TheBv** [comment]
I'm not sure if it will fix it but could you try increasing the amount of memory that's being allocated? 

I'd try 3 GB at first maybe 4 for the -xmx tag if that doesn't fix it let me know!

**Comment by saiho23** [comment]
> I'm not sure if it will fix it but could you try increasing the amount of memory that's being allocated?
> 
> I'd try 3 GB at first maybe 4 for the -xmx tag if that doesn't fix it let me know!

Firstly  Thank you for replying but i've always set the server with 22GB ram . with all the mods i've got i think ram may not be the problem causing this crash?

**Comment by TheBv** [comment]
Oh yeah I completely misread the log file I read 20480Mb as 2048Mb my mistake ^^"
I think I have an idea what could be causing the issue I'll make a PR in a bit which should hopefully resolve the issue :)

**Comment by Rutes** [comment]
> Oh yeah I completely misread the log file I read 20480Mb as 2048Mb my mistake ^^"
> I think I have an idea what could be causing the issue I'll make a PR in a bit which should hopefully resolve the issue :)

Thank you for looking into a fix - I was just about to post a similar java heap space crash. 
Seemed to maybe be related to myrmex AI? I've had 2 crashes in the last 2 days so far. Attached is my latest in case it is helpful.

[crash-2021-06-14_10.50.45-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6651716/crash-2021-06-14_10.50.45-server.txt)
