### ISSUE TITLE
[2.1.7 - 1.16.5] Yellow Hippocampi Don't Spawn

### ISSUE THREAD

**Issue by Flashbackmaniac** [Alex-the-666/Ice_and_Fire#3962]
**Bug description:**
Despite traveling thousands of blocks in ocean biomes and seeing plenty of Hippocampi, the only variant I haven't seen is the yellow one. Initially, I thought my luck in finding the yellow variant abysmal, however, the more I traveled, the more I thought that particular variant wasn't spawning at all.

**Steps to reproduce the behavior:**
1. Create a new world and find an ocean biome.
2. Search through the ocean biome and find Hippocampi, taking note of their color variants.
3. After finding a decent number of Hippocampi, notice that the yellow variants aren't spawning.

**Expected behavior:**
I expected being able to see all six Hippocampus variants naturally spawn in ocean biomes.

**Additional context:**
Using /summon, Hippocampus spawn eggs or spawners will spawn all variants like normal.

**Comment by Flashbackmaniac** [comment]
After searching around, I noticed that [this line](https://github.com/Alex-the-666/Ice_and_Fire/blob/1.16.3/src/main/java/com/github/alexthe666/iceandfire/world/feature/SpawnHippocampus.java#L38) in SpawnHippocampus.java called for integers 0 to 4 instead of 0 to 5, where 5 is the yellow Hippocampus variant. I think this is the reason why yellow Hippocampi weren't spawning.

**Comment by BugmanBugman** [comment]
Nice, that could be why. Maybe bv could look at this if he has the time
