### ISSUE TITLE
graveyard crash when generating 2.1.7

### ISSUE THREAD

**Issue by CKY-** [Alex-the-666/Ice_and_Fire#3964]
**Describe the bug**

server cash when getting close to a graveyard.

this may be related but I dont know 
https://github.com/Alex-the-666/Ice_and_Fire/issues/3947

**To Reproduce**
1. Go to a  graveyard
2. See error
 
https://pastebin.com/FHvMwzFx

Minecraft- 1.16.5

forge 36.1.25

iceandfire-2.1.7

**Comment by Aridastle** [comment]
I am having a similar issue with graveyards.
[crash-2021-06-15_20.22.01-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6658809/crash-2021-06-15_20.22.01-server.txt)

**Comment by LunafeyLazuli** [comment]
Same issue here as well 
[crash-2021-06-15_19.31.17-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6659303/crash-2021-06-15_19.31.17-server.txt)
Every time my server tries to generate a graveyard it crashes and every time I try to delete the region file it spawns in another graveyard then server crash, Ice and Fire version 2.1.7

**Comment by CKY-** [comment]
@TheBv I thought so I will close this.
