### ISSUE TITLE
the bestiary has no pictures on the pages [ICE AND FIRE VERSION 2.1.7]

### ISSUE THREAD

**Issue by zoooommbie** [Alex-the-666/Ice_and_Fire#3966]
**Describe the bug**
where it has drawings of how dragons attack etc no images are seen
1. Go to the bestiary
2. Click on a page of the bestiary
3. See error

**Comment by TheBv** [comment]
I can't seem to able to recreate this issue.
Would it be possible for you to provide the latest.log file so I can check if for some reason some images/resources couldn't get loaded?

**Comment by zoooommbie** [comment]
sure
