### ISSUE TITLE
Myrmex Resin Glass texture issue [2.1.7]

### ISSUE THREAD

**Issue by brisingraerowing** [Alex-the-666/Ice_and_Fire#3967]
**Describe the bug**
Myrmex resin glass textures are screwed up

**To Reproduce**
1. Place down a 2x2 of glass

**Expected behavior**
Frame goes around outer edge

**Screenshots**
![2021-06-15_19 45 04](https://user-images.githubusercontent.com/250409/122137515-cc76c100-ce12-11eb-8ede-3f425b172893.png)

**Additional context**
The glass in the image is Desert Myrmex Resin glass.

**Comment by TheBv** [comment]
Are you using any any other mods besides ice and fire? This doesn't seem to happen to me when using IaF version 2.1.7 even with/without OptiFine installed.

**Comment by brisingraerowing** [comment]
Let me test a few things. I have an idea of which mod it could be.

**Comment by brisingraerowing** [comment]
The culprit is Sodium Reforged. I've reported this to them.
