### ISSUE TITLE
1.3.1 issues

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#397]
I will keep comment as I found out more issues:

- Cyclops doesn't kill stoned player statue with their bite attack and left the statue floating on air.
- Dragon sometimes decide to ascent into the world height after killing a mob
- No more wings flapping noise
- Podium eggs disappearing when relog or reload the chunk
- Ice dragon movement speed on land is significantly slower than of a fire dragon

**Comment by mser7** [comment]
- baby tamed ice dragons still attack baby tamed fire dragon
- stage 3 or higher ice dragons doesn't swim.

**Comment by GundunUkan** [comment]
Also, the issue with dragons leaving their roosts seems to have returned. I found a wild fire dragon on creative and decided to "observe it's behavior" and followed it around. It finally flew off and reached the build height, and started flying towards a certain direction, completely forgetting about its roost.

**Comment by mser7** [comment]
The roost is just a decoration for the dragon spawning, i don't think they do actually have any attachment with it.

**Comment by mser7** [comment]
Dragons moving a few block away when reloading chunks
Cannot capture dead dragons using golden lasso.

**Comment by mser7** [comment]
Stoned mobs sometimes regain their old texture, but they're stilled stoned.
Stoned mobs can still be stoned again by the Gorgons head.

**Comment by AlexModGuy** [comment]
please split these if you want them fixed, this is just too much
