### ISSUE TITLE
Crashes from hippogryph - ice and fire 2.1.7-1.16.5

### ISSUE THREAD

**Issue by YOUR-WORST-TACO** [Alex-the-666/Ice_and_Fire#3971]
**Describe the bug**
Using Forge 1.16.5-36-1-31
Using Java 1.8.0-291
Mods:
- Ice & Fire
- BiomesOPlenty

Crash randomly when near Hippogryphs, looks to be an issue with AIFlyRandom, appears to be linked to loading/unloading of Hippogryphs.
[See crash log](https://pastebin.com/GyXGdnRn)

**To Reproduce**
- Find Hippogryph on a mountain,
- (happens most in biomes o plenty alps)
- Wait a little or leave and rejoin server
- crash

**Comment by TheBv** [comment]
Fixed with #3968
