### ISSUE TITLE
Game just crashed when the fire dragon starting spraying flame [iceandfire-2.1.7-1.16.5]

### ISSUE THREAD

**Issue by kl486134862** [Alex-the-666/Ice_and_Fire#3976]
**Describe the bug**
when the fire dragon starting spraying flame, it crashes the game

**To Reproduce**
1. find a Dragon
2. Let it spraying flame
3. and crash

**Expected behavior**
Burn all the villager

1. Saw a dragon starting spraying flame and game crashed
[crash-2021-06-17_01.01.21-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6664702/crash-2021-06-17_01.01.21-client.txt)
2. Try to get back into the game and immediately crashes
[crash-2021-06-17_01.11.03-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6664717/crash-2021-06-17_01.11.03-client.txt)

Thank you !

**Comment by kl486134862** [comment]
Add a Testing Crashing 
https://youtu.be/eXsiWeVl8K0
https://youtu.be/sHtxxJY2vFw

I also tried the older version, it also came with the same results [iceandfire-2.1.6-1.16.4]
[crash-2021-06-17_19.43.09-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6669854/crash-2021-06-17_19.43.09-client.txt)

**Comment by TheBv** [comment]
This doesn't seem to be an issue with ice and fire. 
Try updating OptiFine/your shaders or try disabling your shaders and see if the issue persists.
Put as I said it has probably to do with some other mod messing with the way minecraft renders things.
