### ISSUE TITLE
Tamed Dragon despawing [2.1.7]

### ISSUE THREAD

**Issue by Chancho91** [Alex-the-666/Ice_and_Fire#3981]
I had a tamed dragon follow me and suddenly it despawned. Are tamed dragon supposed to do that?

**Comment by Tezo-Locrae** [comment]
Same issue for me, it appears to be happening mostly around where the original spawn but I am unaware on how to reproducce it. It has happened to me with it on my shoulder and another player while flying his(both lightning) and twice when they were hatchlings(both fire).

We are running:
minecraft 16.5
valhesia 3 modpack 3.3.3
Ice and Fire 2.1.7
Citadel 1.7
Lootr 1.15.4
Resourceful bees
Project MMO 3.58.3 (configs to level lock tools disabled)
KotlinForForge 1.12.1
CalemiUtils 1.1.1
Bountiful 3.3.1

I'm not sure if there are any known conflicts with these but I was unable to find any in my preliminary research
