### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by reffulbeulb** [Alex-the-666/Ice_and_Fire#3986]
![image](https://user-images.githubusercontent.com/86065096/122523379-89eaf980-d049-11eb-9d18-6dc4ae4470d8.png)
![image](https://user-images.githubusercontent.com/86065096/122523547-b868d480-d049-11eb-93ff-7907eccc2dfb.png)
I don't know what's happening, I need help.

**Comment by galaxygamerguy5** [comment]
you need to use minecraft version 1.16.5 and if your downloading the mod on curseforge, use the forge modloader instead of the fabric one. hope you enjoy the mod and if it doesn't work just say it in the chat thingy
:):):)

**Comment by Virtualhel** [comment]
Two things might be wrong here. The first issue is that you're using the deobf version of Citadel, which is only for the developers to use and doesn't work in a normal game (according to the devs). Use the one found [here](https://www.curseforge.com/minecraft/mc-mods/citadel/files/3346836) instead. The second issue might be your Forge version, which needs to be 36.1.x.

**Comment by reffulbeulb** [comment]
thank you guys

**Comment by reffulbeulb** [comment]
also about fabric and the forge versions, i can't change them or else my other mods won't work

**Comment by reffulbeulb** [comment]
but i'll try the other one thats not deobf
