### ISSUE TITLE
feature placement failure on graveyard(s) [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by planettycoon** [Alex-the-666/Ice_and_Fire#3991]
**Describe the bug**
was exploring new, ungenerated chunks. server immediately crashed. crash report says that it failed to place a graveyard.

**To Reproduce**
i'm not sure how to reproduce this besides exploring the map. that's all i was doing at the time of the crash.

**Expected behavior**
uh, well. i expected my game to not crash.

**Additional context**
sorry i cant be more helpful. all i know is the information in the report and that i'm completely unable to join my server. joining the server results in the same crash report. i'm not able to join and replicate the problem or anything.

[crash-2021-06-18_19.34.57-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6679673/crash-2021-06-18_19.34.57-server.txt)

**Comment by TheBv** [comment]
Will be fixed check this out for more info: #3961
