### ISSUE TITLE
hippogyph ai null pointer exception crash [2.1.7]

### ISSUE THREAD

**Issue by NyanMC** [Alex-the-666/Ice_and_Fire#3992]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
recently i got a crash with ice and fire being the only mod mentioned in the crash report, with the error being a nullpointerexception at com.github.alexthe666.iceandfire.entity.EntityHippogryph$AIFlyRandom.func_75246_d(EntityHippogryph.java:1247) ~[?:2.1.7-1.16.5] {re:classloading} (i will attach a full crashlog somewhere below)
i couldn't observe what the hippogryph was doing to crash the game, but from the crash log it appears as if it were flying

**To Reproduce**
spawn hippogryph
get it to do ai things until it somehow throws a null pointer

**Expected behavior**
i expected the hippogryph to not throw a null pointer and crash the game when i couldn't even see one on screen

**Screenshots**
n/a

**Additional context**
crashlog: https://pastebin.com/kN4ADQsM

**Comment by Nedok** [comment]
I'm having the same error on a server. The modpack used is All The Mods 6 (1.16.10) that uses the same 2.1.7 version of ice and fire.

In my case it was spawned form anther mod and was flying about underground for about 4 second after that everything crashed. Players not in the vicinity of the entity can log on but when they load the affected entity the server crashes son after, giving the same error message but with different coordinates.

**Comment by Nedok** [comment]
Oh... missed that there where already some issue that seams related. 
#3949, #3971

**Comment by Nedok** [comment]
Seems like a fix have been merged for this problem. #3968
