### ISSUE TITLE
iceandfire-2.1.7-1.16.5.jar

### ISSUE THREAD

**Issue by RedCarl** [Alex-the-666/Ice_and_Fire#3993]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Additional context**
https://github.com/IzzelAliz/Arclight/issues/300#issuecomment-864363390

**Comment by AlexModGuy** [comment]
dupe
