### ISSUE TITLE
Dragon Inventory Broken [2.1.7-1.16.5]

### ISSUE THREAD

**Issue by Nyctoniac** [Alex-the-666/Ice_and_Fire#3994]
If you put something within the dragon inventory such as dragon armor. The dragon will not render the armor will show the effect of being armored. After which, if you close the inventory and reopen. The armor will disappear.

**To reproduce the behavior**
Summon a Dragon and tame it with a creative meal or get an egg and wait for it to hatch.
Give it dragon armor.
Close the inventory.
Reopen it.

**Expected behavior**
For it to actually wear the armor and not delete it.

**Screenshots**
![2021-06-19_12 46 29](https://user-images.githubusercontent.com/68577945/122653856-70ef5080-d0fc-11eb-9430-3d72b7348715.png)

**Comment by genderneutralnoun** [comment]
Having this issue as well.
