### ISSUE TITLE
Bizarre Multiplayer Crash [2.1.7, 2.1.6,2.1.5] 1.16.5

### ISSUE THREAD

**Issue by TripConeHead** [Alex-the-666/Ice_and_Fire#4001]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Strange mod load failure on multiplayer, presumably a mod incompatibility? Any way to tell which mod is causing it? Functioned before with the same modlist. 

**To Reproduce**
1. Use mod list
2. Attempt to start server
3. Server crashes 

**Expected behavior**
I expected the server not to crash. 

**Screenshots**

**Additional context**
Happens on all 1.16.5 versions available on curseforge. 
Crash report: https://pastebin.com/CBSU6RyD

**Comment by TheBv** [comment]
A decent amount of things have changed from citadel version 1.6.2 to 1.7
If you're using Ice and Fire version 2.1.6 you want to use version 1.6.x and for Ice and Fire version 2.1.7 you want to use Citadel version 1.7.x
