### ISSUE TITLE
Ice Dragon spawn in warm biomes [LATEST]

### ISSUE THREAD

**Issue by sSpXrta** [Alex-the-666/Ice_and_Fire#4002]
**Describe the bug**
Ice dragons seem to spawn in biomes other than snowy cold ones. 

**To Reproduce**
1. Download my modpack
2. Find Ice Dragons?

**Expected behavior**
To only see ice dragons in cold snowy biomes

**Screenshots**
![2021-06-20_22 11 58](https://user-images.githubusercontent.com/85858503/122702990-983e3e80-d21e-11eb-9b30-9d9943c2fc9b.png)

Link to modpack
https://1drv.ms/u/s!AsA1i4MFDQ5OozEoM4aR2DYNu65Q?e=pDJn5f

**Comment by TheBv** [comment]
I don't know in which biome from which mod specifically you're in but by default ice dragons spawn in biomes that are tagged as: "overworld,icy","overworld,snowy" or "overworld,cold" and to me it might be a possibility that the creator of the biome tagged it as "cold" therefor allowing a dragon to spawn.
If you only want them to spawn in "snowy" and "icy" biomes you can navigate to config/iceandfire/ice_dragon_biomes.json and change it there!
