### ISSUE TITLE
 Dragon Source Refactoring [SOURCE]

### ISSUE THREAD

**Issue by kaisavi** [Alex-the-666/Ice_and_Fire#4004]
### Issue
While going through the source code for my own purposes, I found that the code for dragons was repeated in a way that would make it difficult to fix bugs and implement changes. I am currently working on refactoring the code for the class files as described below.

### Description of Changes
Package `...iceandfire.client.model.animator`

- A new class - `DragonTabulaModelAnimator<T>` - will be implemented. It's purpose will be to act as the superclass to all Dragon animators.

- The classes `FireDragonTabulaModelAnimator`, `IceDragonTabulaModelAnimator`, and `LightningTabulaDragonAnimator` will no longer extend `IceAndFireTabulaModelAnimator` or implement `ITabulaModelAnimator<T>` Instead, they will extend `DragonTabulaModelAnimator<T>`

- Shared members of `FireDragonTabulaModelAnimator`, `IceDragonTabulaModelAnimator`, and `LightningTabulaDragonAnimator`, will be pulled up to `DragonTabulaModelAnimator`

- All Dragon types will include cases for swimming, rather than only the Ice Dragon. I believe this is a good decision because all dragons _can_ swim, they just do so differently. No new animations have to be implemented right away, or at all.

### Benefits
These changes will ease the process of fixing bugs, and implementing features related to Dragons. Alex has said in the past that he does not want to add more Dragons, but there are still parts of the community that want it. By implementing these changes, it will be easier for other modders to create addons that include additional dragons.

### Conclusion
I'm still working on this refactor, but decided to open up an issue for its discussion. I won't be able to work on it for a while because my laptop is broken, but I will get back to it very soon. When it's completed I will open a PR.

**Comment by BugmanBugman** [comment]
Godspeed to you

**Comment by kaisavi** [comment]
# Addendum 1a
### Package `...iceandfire.client.model.util` 
- Addition of `IEnumDragonAnimations` and `IEnumDragonModels`, which will act as a common interface between all dragon animation and model enumerations
- Addition of DragonAnimationLibrary which will hold a static Hashmap containing all of the dragon animations. Animation models will be registered into the hashmap using `registerModels(IEnumDragonModels, IEnumDragonAnimations)`; Animation models will be retrieved using `getModel(IEnumDragonModels, IEnumDragonAnimations)`. Both methods will be static.
- `EnumDragonAnimations` will implement `IEnumDragonAnimations` and hold string definitions instead of TabulaModels
- Addition of `EnumDragonModels` will impliment `IEnumDragonModels` and hold string definitions
 
### Package `...iceandfire.client.model.animator`
- `FireDragonTabulaModelAnimator`, `IceDragonTabulaModelAnimator`, and `LightningTabulaDragonAnimator` will override `getModel(IEnumDragonAnimations)` inherited from `DragonTabulaModelAnimator`

These changes will allow addon authors to register their own dragon models and animations during post-initialization, and allow a common behaviour between all DragonAnimators which retrieves the correct model for the type of dragon it is.

I'd like some feedback from a contributor or @Alex-the-666 because the refactor involves many changes that I want approved before I spend too much time implementing them.
You can view my current progress [on my repository](https://github.com/Onetimetwotimes/Ice_and_Fire).

**Comment by BugmanBugman** [comment]
@TheBv you may find this interesting

**Comment by TheBv** [comment]
Since there won't be any more dragons added to the game I don't believe alex will mind the refactoring...

Honestly just go ahead with it but don't expect any direct feedback from alex I've been trying to get some for months on some changes/things without any luck. But I very much doubt that he wouldn't accept your PR

Btw I looked through some of the code and just wanted to mention that the "animation" baking I introduced some time ago sadly doesn't work. I haven't really taken the time to look into why that is but you can remove things like [this](https://github.com/Onetimetwotimes/Ice_and_Fire/blob/a919a207b3630e621f1497f39a138938f3cc03cb/src/main/java/com/github/alexthe666/iceandfire/client/model/animator/DragonTabulaModelAnimator.java#L21)

**Comment by kaisavi** [comment]
> I very much doubt that he wouldn't accept your PR just make sure

Sorry, was there more you wanted to say here?
> Btw I looked through some of the code and just wanted to mention that the "animation" baking I introduced some time ago sadly doesn't work.

Yea, I was looking at it and I wasn't really sure what was going on with that. Based on the code I could tell that it probably wasn't working as intended, but I couldn't figure out exactly what the animate() method does. Maybe you could clear that up for me so I can make better decisions as far as the refactor goes.

**Comment by AlexModGuy** [comment]
As long as it doesn't introduce any further issues/complications it should be fine.

**Comment by TheBv** [comment]
> Sorry, was there more you wanted to say here?
> 
Not really just forgot to properly delete a sentence. ^^"

>Maybe you could clear that up for 
>
I think I'd have to look further into it but basically the value `llibAnimator` is a libary for all the static animations the dragon can play. In contrast the stuff in setRotationAngles are all "dynamic" e.g. based on the entities flight progress.
Basically whenever a dragon starts an animation like `SHAKE_PREY` it basically calls the animation data from that library. 
At least that's my understanding from it.
The whole idea from my commit was that we don't have to redefine the library each tick but that for some reason didn't work.
Looking back at the code I think I know why that didn't work/ I think I might have an idea how to still optimize that piece of code... It would only bring marginal fps improvements though (at most 15%  #3687)
If I do figure something out I'll create a PR for your fork :)

If you want to/have any more questions you can message me on discord directly: Bv#0365

**Comment by itsdinkd** [comment]
shake_prey causes a crash.
