### ISSUE TITLE
Server crashing on Graveyard generation [2.1.7]

### ISSUE THREAD

**Issue by lephro** [Alex-the-666/Ice_and_Fire#4007]
[crash-2021-06-21_13.18.57-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6690069/crash-2021-06-21_13.18.57-server.txt)
[crash-2021-06-21_23.32.36-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6690070/crash-2021-06-21_23.32.36-server.txt)

Our server frequently crashes when trying to generate a graveyard. 
We are running the Better Minecraft Modpack (Forge version / version 23.5).

I've attached a couple of sample crashlogs. Got dozens of them. We always delete and regenerate chunks, but its only a temporary fix until the next graveyard is about to get generated, it seems.

**Comment by AlexModGuy** [comment]
should be fixed soon
