### ISSUE TITLE
Myrmex trading inventory closing insanely fast after being opened [ICE AND FIRE VERSION 2.1.6]

### ISSUE THREAD

**Issue by Octo-chan** [Alex-the-666/Ice_and_Fire#4010]
When you open the myrmex trading inventory It instantly closes.

1. find a Myrmex nest (desert, don't think It changes anything if It's jungle tho)
2. Get your reputation to 50 or more
3. right click any myrmex from the nest you've got a reputation of 50

I expected It to stay opened until you close It, just like you close your inventory

![2021-06-22_20 10 13_3](https://user-images.githubusercontent.com/80170719/122978046-5a642600-d396-11eb-913e-d55c81440f50.png)
![2021-06-22_20 10 13_4](https://user-images.githubusercontent.com/80170719/122978051-5c2de980-d396-11eb-9eb2-0b3633b3ca34.png)
![2021-06-22_20 10 13_5](https://user-images.githubusercontent.com/80170719/122978060-5df7ad00-d396-11eb-8e5c-1db3d6932e59.png)
![2021-06-22_20 10 13_6](https://user-images.githubusercontent.com/80170719/122978067-5f28da00-d396-11eb-855b-88d63ce54cf5.png)
![2021-06-22_20 10 13_7](https://user-images.githubusercontent.com/80170719/122978070-605a0700-d396-11eb-9432-dc74e8cde141.png)

Context: Rejoining nor restarting Minecraft helped, even tried restarting my intire PC, didn't help either.

**Comment by TheBv** [comment]
Fixed with #3672
