### ISSUE TITLE
[2.1.8 - 1.16.5] Lightning Dragon Animations Don't Play

### ISSUE THREAD

**Issue by Flashbackmaniac** [Alex-the-666/Ice_and_Fire#4011]
**Bug description:**
This is pretty much a copy of my [previous bug report](https://github.com/Alex-the-666/Ice_and_Fire/issues/3973) on the lightning dragon's lack of animations, since the bug is present in 2.1.8 - 1.16.5 as well.

**Steps to reproduce the behavior:**
1. Summon a lightning dragon and tame it.
2. While it is on the ground, notice that its growl / roar animations don't play.
3. Using a dragon command staff, set the lightning dragon into escort mode and attack a mob.
4. When it attacks the mob, notice that aside from its breath and aerial tackle attacks, the other attack animations won't play.

**Expected behavior:**
I expected all of the lightning dragon's animations playing.

**Screenshot:**
The lightning dragons also have their heads tilted upwards.
![image](https://user-images.githubusercontent.com/85721756/122981922-e444cc80-d35f-11eb-9fc4-8c41df856506.png)

**Comment by TheBv** [comment]
Fixed with #3968
