### ISSUE TITLE
Ticking Entity- iceandfire/api/FoodUtils [version 2.1.8]

### ISSUE THREAD

**Issue by DaddyP1G** [Alex-the-666/Ice_and_Fire#4013]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
TIcking Entity crash  https://gist.github.com/DaddyP1G/d8c1e840532b5b27c7352ea85f4aea73

**To Reproduce**
Download 2.1.8-  stand near a dragon for a bit

**Expected behavior**
It seems to happen when Dragons are flying around killing things.

**Comment by TheBv** [comment]
Closing in favor of #4371
