### ISSUE TITLE
Loading Issue after June 22nd Update [Ice & Fire 1.16.4]

### ISSUE THREAD

**Issue by DystopianRoach** [Alex-the-666/Ice_and_Fire#4014]
Hi, I've been using Ice & Fire for a long time and this was the first issue I've ever come across when playing the mod. I'm having an issue where the game states that there's been an error loading the game and it shows me a crashlog. This ONLY started happening after installing (and re-installing just to be safe!) June 22nd's update.

I've attempted re-installing both Ice & Fire and the newest Citadel version twice with no avail.

Here's the screen I'm showed:
![image](https://user-images.githubusercontent.com/86329460/123010568-d9ecf780-d38c-11eb-9efd-76c030089124.png)

and [here](https://pastebin.com/hmMyfp9F) is a pastebin of the crashlog.

Sorry if any information is missing! I've never made a Github or error post before. Hope to get back to playing soon!

**Comment by TheBv** [comment]
Please upgrade to the newest forge version that should fix it

**Comment by DystopianRoach** [comment]
> Please upgrade to the newest forge version that should fix it

Looks like this fixed it! thank you so much!
