### ISSUE TITLE
Scribe Houses Structure Gen In Villages

### ISSUE THREAD

**Issue by zachsai** [Alex-the-666/Ice_and_Fire#4019]
ice and fire now controls villages, which stops other mods from changing the village. Please add a config to allow/disallow iceandfire modifying villages so that other mods & datapacks work for changing villages. They used to work before the last update 2.1.8

**Comment by Sember225** [comment]
Alternatively, A config option to determine the spawn chance of a scriber hut in villages would suffice as well.

**Comment by TheBv** [comment]
This has long been resolved in versions at least newer than 1.16 
We have a config value and pretty much every version hat a config value to change the weight of the village houses being generated.
