### ISSUE TITLE
Baby Dragons Glitching

### ISSUE THREAD

**Issue by OmniRat** [Alex-the-666/Ice_and_Fire#402]
I am unable to remove baby dragons after right clicking them onto my shoulder, and it would appear an unlimited number of dragons may be selected to perch on--or rather hover in front of--the character model. Quitting out of the game results in the dragons disappearing upon re-opening the world.
![babydragonglitch](https://user-images.githubusercontent.com/20730228/34551652-c54945f6-f0d0-11e7-9b18-2803a73464f6.png)

**Comment by Stargentian** [comment]
I think x is the default dismount key. If it isn't, just check your keybinds.

**Comment by OmniRat** [comment]
Cool, thanks for letting me know!

**Comment by AlexModGuy** [comment]
press X
