### ISSUE TITLE
Issue desc [ Ice and Fire 2.1.7v    Minecraft 1.16.5v ]

### ISSUE THREAD

**Issue by Yeeacub** [Alex-the-666/Ice_and_Fire#4021]
FYI! (THIS IS ON TNP LIMITLESS 3 MODPACK) 
I'm just inside my base crafting things for my powah reactor and it brings me to a server menu. Middle server says cant resolve hostname. This has happened twice within 20 minutes. The first time it happened I was confused as I was holding a furnace from fast furnace and went to go look at the block I wanted to place on but couldn't because it brought me to the server menu after me waiting staring at the backdrop of the loading screen with no text. I then went to my worlds to get back on but it asked me to make a new world as if I didn't have any worlds in the first place. Also I'm playing SINGLEPLAYER. Before the second launch it was giving me errors when I clicked on the modpack and wouldn't let me load it. It was saying something about "javaruntimeerror" cant quite remember. After testing a couple other modpacks I realized it wasn't an issue on my part. I then went to go launch TNP limitless again and it loaded just fine. Note: when I went to go launch it, it crashed immediately. Before that moment I had my RAM set to 12G (I set it to 12G in the past). I then set it to 10G and it launched. Played for awhile running around my base crafting things and it crashed again.

**Describe the bug*
hyppogryph bug causes my game to crash.

**To Reproduce**
1. Go to 'N/A'
2. Click on 'N/A'
3. See error

**Expected behavior**
Not to crash when im crafting random things

**Screenshots**

**Additional context**

First crash:
https://paste.ee/p/ErL7t

Second crash:
https://paste.ee/p/m1HkZ

**Comment by TheBv** [comment]
Should be fixed in version 2.1.8
