### ISSUE TITLE
Game crashes, near deserts and Jungles 

### ISSUE THREAD

**Issue by JustDragonss** [Alex-the-666/Ice_and_Fire#4023]
**Description**
On my modded server any time me or one of my friends go near a desert or Jungle biome the server slows severely and will proceed to crash. I've only had it happen in those two biomes, and it's usually accompanied by the message "[Server thread/WARN] [net.minecraft.world.chunk.Chunk/]: Tried to load a DUMMY block entity @ BlockPos{x=27423, y=21, z=-10047} but found not block entity block Block{minecraft:stone} at location" many times in the server prompt.   

1. Once in the game go near a desert or jungle and perhaps try going further into the biome
2. See error

**Expected behavior**
The server working as normal with minimal levels of lag. 

**Additional context**
I am running the server on 1.16.5 from my pc, I'm using 20gb of ram and my cpu is an Intel Core i9-9900KF. I'm using 
1.7.1-1.16.5 ice and fire, and 1.7.1-1.16.5 Citadel along with Tinkers Construct, waystones, Antique Atlas, Just enough Items, and mantle (a library for TConstruct). My only idea is that the myrmex are the problem seen as they are the only similarity of the 2 biomes that lag. 
[crash-2021-06-21_19.47.47-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6711534/crash-2021-06-21_19.47.47-server.txt)
(I have more crash reports if needed)

**Comment by celophys** [comment]
same...
