### ISSUE TITLE
RuntimeException: We are asking a region for a chunk out of bound

### ISSUE THREAD

**Issue by slavens** [Alex-the-666/Ice_and_Fire#4028]
highlights from the crash report:
`...
at com.github.alexthe666.iceandfire.world.gen.WorldGenIceDragonCave.generate(WorldGenIceDragonCave.java:95) ~[?:2.1.7-1.16.5] {re:classloading}
`

`
Details:
	CenterX: -1619672
	CenterZ: -1878813
	Seed: -1771354321050688298
	Biome: net.minecraft.world.biome.Biome@33b66b8a
`

`
-- Entity being ticked --
Details:
	Entity Type: iceandfire:myrmex_worker (com.github.alexthe666.iceandfire.entity.EntityMyrmexWorker)
	Entity ID: 161
	Entity Name: Myrmex Worker
	Entity's Exact location: -641.47, 58.00, -491.08
	Entity's Block location: World: (-642,58,-492), Chunk: (at 14,3,4 in -41,-31; contains blocks -656,0,-496 to -641,255,-481), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Entity's Momentum: -0.01, -0.08, -0.04
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
`
Files and a pic of the current overworld are attached.

Please note the coordinates of the failing chunk listed above and note that I haven't traveled more than 112 chunks from origin. In the picture of the map all the little spots outside the central bit are dragon spawns - some over 5 _million_ chunks from 0,0.

please let me know if more information would be useful.

[crash-2021-06-24_12.37.40-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6718154/crash-2021-06-24_12.37.40-server.txt)
![Pangea](https://user-images.githubusercontent.com/5084957/123470201-efd70400-d5a8-11eb-9afc-26ed2ed5169b.png)

**Comment by TheBv** [comment]
Version 2.1.8 introduced a maximum wander radius for myrmex that should also fix this issue :)

**Comment by slavens** [comment]
Good to know. We'll get it loaded and tested today.

**Comment by User-green** [comment]
Dupe to #4026
