### ISSUE TITLE
Tackle Attack Issue

### ISSUE THREAD

**Issue by GundunUkan** [Alex-the-666/Ice_and_Fire#403]
It's very inconvenient for wild dragons to use the tackle attack on a non-flat world if there are any trees or hills nearby, because it results in the dragon getting stuck in the obstacles, unable to continue pursuing its target. This problem could be fixed if block breaking is made a bit stronger, at least for this attack, if possible.

**Comment by AlexModGuy** [comment]
block breaking is still very powerful
