### ISSUE TITLE
ERROR AL CARGAR EL MOD [iceandfire-2.1.8-1.16.5]

### ISSUE THREAD

**Issue by d-rick** [Alex-the-666/Ice_and_Fire#4031]
al actualizar el mod a la ultima versión

**Additional context**
[crash-2021-06-26_11.33.49-fml.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6720397/crash-2021-06-26_11.33.49-fml.txt)

**Comment by Virtualhel** [comment]
You have Forge 35.1.37, which I believe is too old for the current version of Citadel. Try updating your Forge to one that is 36.1.x.
