### ISSUE TITLE
Mod refuses to load on game open

### ISSUE THREAD

**Issue by Silvaeat** [Alex-the-666/Ice_and_Fire#4034]
it says the exception message is "java.lang.ClassNotFoundException: net.minecraftforge.event.entity.EntityAttributeCreationEvent"
![image](https://user-images.githubusercontent.com/84404703/123524350-97cafb00-d697-11eb-9502-ba03c2d04921.png)
Image included of the stacktrace

**Comment by Virtualhel** [comment]
What versions of Ice and Fire, Citadel, and Forge do you have? I think it may be an issue with incompatible versions of Citadel or Forge but I can't tell which ones you have without a full crash report.

**Comment by Silvaeat** [comment]
managed to resolve the issue by reinstalling forge and citadel, thanks anyhow
