### ISSUE TITLE
Crash with Mahou Tsukai on 1.16.5 [ICE AND FIRE 2.1.7]

### ISSUE THREAD

**Issue by stepsword** [Alex-the-666/Ice_and_Fire#4040]
So someone sent me this crash log  https://pastebin.com/1ZyE13xg

I can't replicate it and I can't tell if mahou is causing it, but basically I'm doing 

```
if (entity instanceof LivingEntity) {
                fake_player.attackStrengthTicker = 1000;
                fake_player.attack(entity);
}
```

Let me know if this is something I need to fix on my end! :)

**Comment by stepsword** [comment]
https://pastebin.ubuntu.com/p/X7CS3QNxRd/

Here's another one for this

**Comment by TheBv** [comment]
Doesn't seem to be an issue anymore.
