### ISSUE TITLE
no ice and fire mobs :(  [2.1.7-1.16.5]

### ISSUE THREAD

**Issue by yuihashima** [Alex-the-666/Ice_and_Fire#4041]
so me and my friends were trying to play with the ice and fire mod (were playing allthemods6 in 1.16.5 and ver 2.1.7 of ice and fire) but in our server not a single ice and fire mob (ive played with the mod before so i know the mobs and such) had spawned even when we went far away looking for them we get the items still and (some) structures like the pixie village but no pixies or a village house with ice and fire stuff in them and I'm not sure if maybe there's some mod that ice and fire doesn't work with?

**Comment by Virtualhel** [comment]
ATM6 has Ice and Fire configured so that the mobs do not spawn in the overworld. They are found in an alternate dimension instead.

**Comment by yuihashima** [comment]
> ATM6 has Ice and Fire configured so that the mobs do not spawn in the overworld. They are found in an alternate dimension instead.

ive played in the past 1.16.4 of all the mods 6 and we had almost every mob spawn except for the lightning dragons did they change that now?

**Comment by Virtualhel** [comment]
Different mobs from Ice and Fire are found across various dimensions. Based on comments from the ATM6 Discord server, it seems there was at least one bugged version of the pack that allowed I/F mobs to spawn in the overworld. I cannot really speak on the specific version you played, as I cannot find a version of ATM6 that supported 1.16.4.

**Comment by yuihashima** [comment]
> Different mobs from Ice and Fire are found across various dimensions. Based on comments from the ATM6 Discord server, it seems there was at least one bugged version of the pack that allowed I/F mobs to spawn in the overworld. I cannot really speak on the specific version you played, as I cannot find a version of ATM6 that supported 1.16.4.

ohhhh i see that makes sense then is there any website or form i can check to see what dimensions all the mobs spawn in if you know?
