### ISSUE TITLE
Lightning Dragon Crash [1.16.5]

### ISSUE THREAD

**Issue by RedHounds** [Alex-the-666/Ice_and_Fire#4044]
Playing with a friend on a server with the Ice and Fire: Dragons mod and suddenly everything lags. Checked game console and saw an entity called Lightning Dragon to be causing the issue, with the server being forcibly shut down.

**Comment by FlameyFaucet** [comment]
Posting the server crash logs can help a lot.

**Comment by ShiriYeka** [comment]
The same issue in my server!
