### ISSUE TITLE
Problem with Dragon Eggs on server - Ice and Fire v2.1.8

### ISSUE THREAD

**Issue by xXCr0nosXx** [Alex-the-666/Ice_and_Fire#4048]
Dragon eggs (only recorded fire eggs) do not hatch. The hatching time was changed to 24000 ticks, after 20 minutes, the hatching time modified to its initial state, after 8 minutes, the eggs still did not hatch

I expected the egg to hatch after 24000 ticks, but it never did

Is there a solution?

**Comment by TheBv** [comment]
Fixed with f954f26
