### ISSUE TITLE
Guide how to destroy any Ice And Fire server and client 1.16.5 [2.1.8]

### ISSUE THREAD

**Issue by XionioXMaster** [Alex-the-666/Ice_and_Fire#4050]
**Describe the bug**
**I’m not quite sure if this has been found by other players but, if you hold two dragon horns, one in each hand. You are capable of putting a single dragon in both and coming out with two. Effectively duping a dragon.**

Once upon a time one person wrote about this, and you do not even suspect what this duped is fraught with! With it, you can lay down the server!

Made In Abyss server present

We put not a duped dragon in 1 chunk, but a duped dragon in the far one, after which we take off on it and the longer we are on the dragon, the less TPS the server has!

**To Reproduce**
1. Video: https://youtu.be/_9QmVNPd37I

**Expected behavior**
Up

**Screenshots**
Video up

**Additional context**
Thanks, Magenta_0 and Zireael

https://github.com/Alex-the-666/Ice_and_Fire/issues/4049

**Comment by TheBv** [comment]
Was fixed by yourself
