### ISSUE TITLE
Hydra crashes server if its targeting is interrupted [2.1.8]

### ISSUE THREAD

**Issue by Jackiecrazy** [Alex-the-666/Ice_and_Fire#4051]
**Describe the bug**
The hydra repeatedly calls getAttackTarget() instead of keeping a variable after its null check on line 151. If the target disappears for any reason, this will throw an NPE.

**To Reproduce**
1. Install Quark and Project: War Dance. Neither are necessary to replicate the bug, but this was how it was triggered.
2. Quark will cause squids to blind attackers, and P:WD will cause blinded entities to lose its target. Have a hydra attack a squid in water.
3. The NPE will be thrown.

**Expected behavior**
The crash in question should not happen.

**Crash Log**
[crash-2021-07-04_00.31.29-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6759199/crash-2021-07-04_00.31.29-server.txt)

**Comment by TheBv** [comment]
Closing in favor of  #4059
