### ISSUE TITLE
Dragons are not spawning

### ISSUE THREAD

**Issue by CharlyCR18** [Alex-the-666/Ice_and_Fire#4053]
I was playing in the latest version of the mod (2.1.8) with citadel 1.7.1, When a new world is created, there are no dragons, in some cases there are only skeletons, but in 5 of the 5 worlds I created, I have not been able to find any nests or dragons, with the other mobs there isn´t any trouble

**Comment by q09iaf** [comment]
I have the same problem i found 37 dead dragons and 0 alive :( help
