### ISSUE TITLE
No Nests or Dragons in sight, only dragon Skeletons [1.16.5]

### ISSUE THREAD

**Issue by DystopianRoach** [Alex-the-666/Ice_and_Fire#4058]
Hi, I haven't played Ice & Fire in a while! I booted up a new survival world and started exploring to find the terrain littered with dragon skeletons, but no nests. Out of curiosity, I changed to spectator and checked for multiple chunks- there are no dragon nests or live dragons to be seen, only skeletons. Was the chances of stumbling across a nest severely declined, or is there a bug?

(Also, not sure if this is a bug, but this cyclops seems to have spawned without his dome... not sure if that's a new addition or a bug, but thought I'd throw it in)

![image](https://user-images.githubusercontent.com/86329460/124695160-ac399f80-deb0-11eb-9401-26c4eb01ddb4.png)
![image](https://user-images.githubusercontent.com/86329460/124695187-b9ef2500-deb0-11eb-87f1-346826292cb4.png)
![image](https://user-images.githubusercontent.com/86329460/124695237-cd9a8b80-deb0-11eb-8a8a-0774d5f914ba.png)

My modlist is as follows, I'm thinking that there may be a world generation bug:
- Alex's Mobs
- Aquaculture
- Better Caves
- Better Mineshafts
- Better Weather
- Dynamic Surroundings
- Citadel (of course)
- Ice & Fire (of course)
- Comforts
- Genetic Animals
- Guard Villagers
- Project Vibrant Journeys
- Yung's Api

Hoping to see some dragons again soon! Thanks!

**Comment by Samlegamer** [comment]
I had the same problem that is precisely Project Vibrant Journey the cause.
I advise you to config it and disable the appearance of small rocks that can possibly prevent a dragon spawn.
