### ISSUE TITLE
Server hangs sometimes during chunk generation [iceandfire-1.9.1-1.12.2]

### ISSUE THREAD

**Issue by sglorch** [Alex-the-666/Ice_and_Fire#4063]
**Describe the bug**
I encountered this crash two times now while one of my players was generating a high amount of new chunks by travelling.
The server hangs during the generation of specific chunks that seem to be related to Fire Dragon-Caves. After 60 seconds, the ServerHangWatchdog kicks in and kills the server.

I assigned the server 4 GB of RAM, but I am not using any other JVM-Flags yet to optimize performance.
Is something with the generation really taking this long, and I would "solve" this by disabling the watchdog?

[crash-2021-07-11_21.21.35-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6799887/crash-2021-07-11_21.21.35-server.txt)
[crash-2021-07-11_23.35.37-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6799888/crash-2021-07-11_23.35.37-server.txt)

Another possibly unrelated problem is that after a server restart all dragons are respawned no matter if they have been killed or not.

**Comment by BugmanBugman** [comment]
1.12 not supported

**Comment by DeathGunZero** [comment]
> 1.12 not supported

also found in 1.16.5
