### ISSUE TITLE
myrmex bug server hard lagged and crash

### ISSUE THREAD

**Issue by 777Sergio777** [Alex-the-666/Ice_and_Fire#4067]
i cant think of a way to reproduce this bug cause i dont know why its happening, only saw some references to myrmex in the crash report, and this is the crash report

[crash-2021-07-12_02.10.56-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6803124/crash-2021-07-12_02.10.56-server.txt)

so if anyone can tell me why is this happening or if its really from myrmex, or how can i solve this, i will be really gratified

**Comment by Rutes** [comment]
Looks like you also hit the 60 second tick limit - similar issue to https://github.com/Alex-the-666/Ice_and_Fire/issues/4077

You mention the myrmex - there was an AI issue with myrmexes in a recent version of Ice & Fire, but it was fixed - are you using the latest version? Hmm... seems you are - 2.1.8. 
Perhaps the myrmex AI bug is not fully fixed? 
https://github.com/Alex-the-666/Ice_and_Fire/issues?q=myrmex+is%3Aissue+is%3Aopen+

I thought they fixed it with 2.1.7 - https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons/files/3347222
"-Fixed game crashing when entering certain biomes"
but perhaps not...

**Comment by 777Sergio777** [comment]
> Parece que también alcanzó el límite de ticks de 60 segundos, problema similar al [# 4077](https://github.com/Alex-the-666/Ice_and_Fire/issues/4077)
> 
> Mencionas myrmex: hubo un problema de inteligencia artificial con myrmexes en una versión reciente de Ice & Fire, pero se solucionó, ¿estás usando la última versión? Hmm ... parece que lo estás - 2.1.8.
> ¿Quizás el error de la IA de myrmex no está completamente solucionado?
> https://github.com/Alex-the-666/Ice_and_Fire/issues?q=myrmex+is%3Aissue+is%3Aopen+
> 
> Pensé que lo arreglaron con 2.1.7 - https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons/files/3347222
> "-Se corrigió el bloqueo del juego al ingresar a ciertos biomas"
> pero tal vez no ...




about that sorry i didnt closed this yet, i already fixed that

for some reason, myrmex had a wandering area of 4000 from default, i changed it to 500 and now i doesnt have these lags
