### ISSUE TITLE
Small Typo In Bestiary (Ice And Fire 2.1.8)

### ISSUE THREAD

**Issue by Figgmastah** [Alex-the-666/Ice_and_Fire#4068]
Small Typo "form black skeletons"
![2021-07-13_12 09 48](https://user-images.githubusercontent.com/76262849/125434709-8c4cbffb-58ac-4d7a-98af-8f2c89da5863.png)

**Comment by SpokenWig620933** [comment]
I can say this is still true.
Im using 2.1.9-1.16.5.
<img width="306" alt="image" src="https://user-images.githubusercontent.com/49125888/167450075-4385ad49-0a6e-43b3-8a92-e85debfc13e8.png">
There is also a typo on this page "haf-digested"
