### ISSUE TITLE
Cyclops Model temporarily go invisible when looking up

### ISSUE THREAD

**Issue by Misunderstood-Wookiee** [Alex-the-666/Ice_and_Fire#407]
As per desc. no crash or stack trace though may be a conflict with Optifine HD U7, when looking up at the Cyclopes he turns invisible to the player but can still be hurt. I don't have much info on what is causing this sorry, I may be the resource pack based issue or a general bug, but it only effects this one mob.

**Comment by AlexModGuy** [comment]
that's just vanilla, try the same thing to a pig if you look at its snout while the rest of it is off screen.
