### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by itsoxid** [Alex-the-666/Ice_and_Fire#4071]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Crashing when loading it along with other mods , I have 132 total mods

''java.lang.VerifyError: Expecting a stackmap frame at branch target 461
Exception Details:
  Location:
    com/github/alexthe666/iceandfire/entity/EntityDragonBase.breakBlock()V @457: goto''

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**
[crash-2021-07-14_16.54.33-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6817464/crash-2021-07-14_16.54.33-client.txt)

^^^ crash report 

**Additional context**

**Comment by silvercirrus** [comment]
I am having the same issue. Did you manage to find a solution?

**Comment by itsoxid** [comment]
> I am having the same issue. Did you manage to find a solution?
I removed the IseeDragons mod and it started working for me

**Comment by silvercirrus** [comment]
That worked for me as well, thank you so much!
