### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by mathieucrombe** [Alex-the-666/Ice_and_Fire#4072]
**Description**
A friend used the gorgon head on me and i'm crash

**Screenshots**
https://imgur.com/kcRPoeZ

**Comment by mathieucrombe** [comment]
> **Description**
> A friend used the gorgon head on me and i'm crash
> 
> **Screenshots**
> https://imgur.com/kcRPoeZ

I was in creative mod

**Comment by TheBv** [comment]
Fixed with #4136
