### ISSUE TITLE
Server Crash [ICE and Fire1.16.5latest]

### ISSUE THREAD

**Issue by DeathGunZero** [Alex-the-666/Ice_and_Fire#4077]
The server crashed while I was staying in some blocks(Dragon Nest on the ground, ant nest,etc). 
I've tried forge, Mohist and Arclight in 1.16.5. I don't know if it's caused by server or mod.
Environment: 

- System OS: CentOS 8
- CPU: E5-645
- RAM: 16G
- Java version: openjdk-8,11,16(All of these have been tried)
- Server Package: forge-1.16.5-36.1.32. mohist1.16.5-712,arclight.

crashreport here:
[crash-2021-07-18_09.22.24-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6835527/crash-2021-07-18_09.22.24-server.txt)

**Comment by Rutes** [comment]
"ServerHangWatchdog detected that a single server tick took 60.00 seconds"

Your server just got a little stuck. You can try increasing the max-tick-time setting to a very high value or just set it to 0 to disable it, but you'll want to track down what is eating up your resources. At first glance it seems to be something called "LagAssist".

![image](https://user-images.githubusercontent.com/5608566/126073180-a51a6f32-32f1-4361-b2c5-e23ad4033412.png)

**Comment by DeathGunZero** [comment]
Thx,dude. That help me a lot.
