### ISSUE TITLE
Underground spawning

### ISSUE THREAD

**Issue by alltair35** [Alex-the-666/Ice_and_Fire#408]
Hi alex !  Gorgon temples and dragon nests are spawning undeground :( I thought maybe it's because of the mods that I use but when I asked to people on discord, they said that I should report it to you in here.
I want to list the mods that I use (just in case). By the way, thank you guys for Ice and Fire mod. Its a masterpiece =)
Mods;
Codechickenlib
Biomes o plenty
mo creatures
DungeonDQ
Ivtoolkit
Journeymap
Just enough items
Lucky block
NetherEx
Not enough items
Optifine
Recurrent Complex
Roguelike dungeons
Damage indicators
Tree capitator
Twilight forest 
Wearable backpacks

And here are some screenshots. And again thanks for the mod man :)
![fire dragon nest underground](https://user-images.githubusercontent.com/35145203/34618400-b681c162-f24f-11e7-943d-7c827128cdd0.png)
![gorgon temple underground 1](https://user-images.githubusercontent.com/35145203/34618401-b6a67e12-f24f-11e7-82df-ca011a5464db.png)
![gorgon temple underground 2](https://user-images.githubusercontent.com/35145203/34618402-b6d24d8a-f24f-11e7-88ec-a949f44302a2.png)

**Comment by Misunderstood-Wookiee** [comment]
You sure it is not a Dragon Lare because they are supposed to spawn underground..

**Comment by alltair35** [comment]
@Misunderstood-Wookiee yes I'm pretty sure, it wasn't a dragon cave :) And you can see gorgon temple, which supposed to be on surface. I believe biomes o plenty and ice and fire have an incompatiblity.

**Comment by AlexModGuy** [comment]
getHeight method changed in 1.4.0
