### ISSUE TITLE
Ice dragon always spawn as a ticking entity [2.1.8]

### ISSUE THREAD

**Issue by Dziixd** [Alex-the-666/Ice_and_Fire#4087]
**Describe the bug**
I create a forge server to play with my friend, we hace like 45 mods in the server, when we spawn its al like a normal game, but every time that someone see a ice dragon, the server crash, i create another server with the same mods and forge version and it keeps going 

**To Reproduce**
1. make a server with forge server file
2. install ice and fire mod in the server
3. see a ice dragon
4. enjoy the crash server

[crash-2021-07-19_20.24.23-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6844476/crash-2021-07-19_20.24.23-server.txt)

i remove the entity with NBTEcplorer, but when the ice dragon spawn again, it crashes, again.

**Comment by chosti-factor** [comment]
I have the same issue.
[crash-2021-07-19_00.24.38-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6845209/crash-2021-07-19_00.24.38-server.txt)
[crash-2021-07-19_21.56.30-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6845210/crash-2021-07-19_21.56.30-server.txt)

**Comment by IdaFoll** [comment]
I have the same issue. I have tried it both with and without other mods, and it always crashes every time I come in contact with an ice dragon.
[crash-2021-07-20_13.56.43-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6849568/crash-2021-07-20_13.56.43-server.txt)

**Comment by chosti-factor** [comment]
It got fixed for me when I downgraded from Citadel 1.7.2 to 1.7.1. I was able to keep Ice and fire 2.1.8. Hope this helps!

**Comment by Dziixd** [comment]
> It got fixed for me when I downgraded from Citadel 1.7.2 to 1.7.1. I was able to keep Ice and fire 2.1.8. Hope this helps!

im gonna try it pal thx for info

**Comment by Rutes** [comment]
> It got fixed for me when I downgraded from Citadel 1.7.2 to 1.7.1. I was able to keep Ice and fire 2.1.8. Hope this helps!

Trying this also....
Linking my issue for reference https://github.com/Alex-the-666/Ice_and_Fire/issues/4094
