### ISSUE TITLE
Ice Dragon ticking entity [ICE AND FIRE 2.1.8]

### ISSUE THREAD

**Issue by thehollyraven** [Alex-the-666/Ice_and_Fire#4088]
So two friends and I were playing on a Forge server yesterday, and I ran into an Ice Dragon roost, and the server promptly crashed. One of my friends on the server had been building a redstone farm for the past 5 minutes up to that point, and lost all 5 minutes of their progress. The server crashed 4 times before we were able to figure out what had happened, and use a /kill all command in the console. It happened again today, I was heading to where the same friend was on my hippocampus, I unknowingly got in the range for an Ice Dragon to spawn in, and the server crashed. 

**Describe the bug**
Ice dragon spawns in, its AI kicks in, and then the server crashes. 

**To Reproduce**
1. Download Ice and Fire version 2.1.8
2. Load in an Ice and Fire world, either singleplayer or multiplayer, doesn't matter.
3. Load in a chunk that has an Ice Dragon in it
4. Watch the server/world crash, and then crash again once you reload it.

**Expected behavior**
Entire world crashes and it's impossible to load in without going into the console and doing a /kill all command.

If needed, the crash reports are available upon request, as we have more than one, 3 of them being just from the 18th of July alone, and all about the same issue.

**Additional context**
We have 22 mods installed on the server, the 22nd mod being Ice and Fire itself, and they are as follows;
All of the mods listed here were last updated July 17th 
- AI Improvements https://www.curseforge.com/minecraft/mc-mods/ai-improvements 1.16.2-0.3.0
- Alex's Mobs https://www.curseforge.com/minecraft/mc-mods/alexs-mobs 1.11.1
- Animal Crops https://www.curseforge.com/minecraft/mc-mods/animal-crops 0.6.1
- Aquaculture 2 https://www.curseforge.com/minecraft/mc-mods/aquaculture 2.1.19
- AutoRegLib https://www.curseforge.com/minecraft/mc-mods/autoreglib 1.6-49
- Chisels & Bits https://www.curseforge.com/minecraft/mc-mods/chisels-bits 0.3.4
- Citadel https://www.curseforge.com/minecraft/mc-mods/citadel 1.7.2
- Comforts https://www.curseforge.com/minecraft/mc-mods/comforts 4.0.1.1
- Connectible Chains https://www.curseforge.com/minecraft/mc-mods/connectible-chains-forge 1.2.0
- Craftable Horse Armour & Saddles https://www.curseforge.com/minecraft/mc-mods/cha-s 1.6
- CraftTweaker https://www.curseforge.com/minecraft/mc-mods/crafttweaker 7.1.0.350
- Dragonseeker https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragonseeker 1.0
- Neat https://www.curseforge.com/minecraft/mc-mods/neat 1.7-27
- Straw Golem Reborn https://www.curseforge.com/minecraft/mc-mods/strawgolem-reborn 1.9
- Waystones https://www.curseforge.com/minecraft/mc-mods/waystones 7.6.2
- Wyrmroost https://www.curseforge.com/minecraft/mc-mods/wyrmroost 1.2.11
- Xaero's World Map https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map 1.14.6.1 (Forge)
- Yung's API https://www.curseforge.com/minecraft/mc-mods/yungs-api Forge-11
- Yung's Better Caves https://www.curseforge.com/minecraft/mc-mods/yungs-better-caves 1.1.2
- Yung's Better Mineshafts https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge 2.0.4
- Yung's Better Strongholds https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds 1.2

**Comment by RisingInIris2017** [comment]
I have a similar issue, and I will post here instead of opening a new issue in order to avoid duplicated issue.
### To Reproduce
1. Download Ice and Fire version 2.1.8
2. Load in an Ice and Fire world, either singleplayer or multiplayer, doesn't matter.
3. Attack an Ice Dragon or let it attack you.
4. Watch the server/world crash, and then crash again once you reload it.
### Crash report
https://paste.ubuntu.com/p/hXnY2mPsNk/
### Additional context
In my situation, I used Forge server and installed no other mods.
I think this issue must be related to Ice and Fire mod itself, so I post this issue here.

Thanks for your kind-hearted help and look forward your reply.

**Comment by Rutes** [comment]
so it's not just me: https://github.com/Alex-the-666/Ice_and_Fire/issues/4094
