### ISSUE TITLE
Ice Dragon crashes server [iceandfire-2.1.8-1.16.5.jar]

### ISSUE THREAD

**Issue by TheTechPny** [Alex-the-666/Ice_and_Fire#4093]
I am also on Citadel 1.7.2.

**Describe the bug**
When a player engages an Ice Dragon the server crashes.

**To Reproduce**
He started fighting it.

**Additional context**
https://pastebin.com/P2D7ugzw
^ Crash Report ^

**Comment by LaturaD** [comment]
I have the same problem, it happened a few times.
It even crashed in a single player world.
I often got the error message "java.lang.stackoverflowerror" and when i restarted the server things like chests, respawn point adn even some blocks were resetted, to a point a minute before the crash.

**Comment by joedudev** [comment]
Same issue, I got the error defineId called for: class 
`22.07 14:59:16 [Server] Server thread/WARN [minecraft/EntityDataManager]: defineId called for: class com.github.alexthe666.iceandfire.entity.EntityDragonBase from class com.github.alexthe666.iceandfire.entity.EntityLightningDragon
22.07 14:59:16 [Server] Server thread/WARN [minecraft/EntityDataManager]: defineId called for: class com.github.alexthe666.iceandfire.entity.EntityDragonBase from class com.github.alexthe666.iceandfire.entity.EntityLightningDragon
22.07 14:59:16 [Server] Server thread/WARN [minecraft/EntityDataManager]: defineId called for: class com.github.alexthe666.iceandfire.entity.EntityDragonBase from class com.github.alexthe666.iceandfire.entity.EntityLightningDragon
22.07 14:59:16 [Server] Server thread/WARN [minecraft/EntityDataManager]: defineId called for: class com.github.alexthe666.iceandfire.entity.EntityDragonBase from class com.github.alexthe666.iceandfire.entity.EntityLightningDragon`

**Comment by Rutes** [comment]
another ticking entity crash -similar to my issue here: https://github.com/Alex-the-666/Ice_and_Fire/issues/4094
