### ISSUE TITLE
Ice Dragon Crashes Minecraft

### ISSUE THREAD

**Issue by RunicCrustacean** [Alex-the-666/Ice_and_Fire#4094]
I have Citadel 1.7.2 and the lastest Ice and Fire mod installed. 

Describe the bug
Ice Dragon causes the game to crash and re-rolls my save to a few minutes before I encounter it. 

To Reproduce
I'm continuously going in the area where the Ice Dragon is located and I just let it roam and attack. The times that it crashes is random, but being around the entity causes it. I went on creative and survival. Same outcome. Went on creative and spawned multiple ice dragons. The game crashed within seconds.  

Additional context
Here is the Crash Report:
https://pastebin.com/fwbBfG8J

**Comment by Dejeh** [comment]
I have more information on this. Standalone iceandfire + citadel mod, when using a tamed ice dragon's breath attack or when a wild ice dragon uses its breath attack, will crash the game.

**Comment by TLG310** [comment]
Why dose citadel crash ice and fire?

**Comment by Rutes** [comment]
This seems similar to my crash: https://github.com/Alex-the-666/Ice_and_Fire/issues/4059

**Comment by RunicCrustacean** [comment]
Hopefully there will be a fix. I wanna be able to experience the whole mod. It's a shame I have to avoid a specific mob.

**Comment by answering-mechine** [comment]
Downgrade from citadel 1.7.2 to 1.7.1 it’s a common issue but it should be fixed when you downgrade

**Comment by AzureZeroFrog** [comment]
I dont even have Citadel and ice dragon crashes my server. Same Bug too

**Comment by AzureZeroFrog** [comment]
Is there a way to just disable all ice dragons from spawning and kill them all off from server?

**Comment by Jadziyah** [comment]
We're having the exact same issue on our multiplayer server. Hope a fix gets instituted soon

**Comment by answering-mechine** [comment]
> I dont even have Citadel and ice dragon crashes my server. Same Bug too

How are you running ice and fire without citadel it is quite critical to the mod.

**Comment by Bastard-jpg** [comment]
its sad 3 years later its still doing it
