### ISSUE TITLE
Changing maximum health for gorgons doesn't work [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by justin-slijkhuis** [Alex-the-666/Ice_and_Fire#4107]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
When setting maximum health for an Ice and Fire mob in config then it does nothing.

**To Reproduce**
1. Open the config.
2. Change Gorgon maximum health.
3. Open the game and check the health.

**Expected behavior**
I expected the health to be the exact amount I had put in the config

**Screenshots**
![image](https://user-images.githubusercontent.com/84229234/127342938-bcc8d1da-050f-40bc-b2a9-9de15016acd1.png)
![image](https://user-images.githubusercontent.com/84229234/127345483-e0d2947e-688d-40c3-af02-45fcb7308ad4.png)

**Additional context**
None

**Comment by TheBv** [comment]
Same as #4037
