### ISSUE TITLE
Scribe villager houses generating too often, not allowed to reduce rates/disable the structure in config [2.1.8]

### ISSUE THREAD

**Issue by judenelson468** [Alex-the-666/Ice_and_Fire#4113]
Not sure if this technically counts as a bug, but I am posting it as such. The new village scribe buildings spawn way too often in villages, and the option to change the weight in the config does not allow reducing the value lower than the default (30) or disabling the structure.
![2021-07-30_16 15 32](https://user-images.githubusercontent.com/80720320/127712803-d61b2408-e9bd-4800-8b26-79dd7cac47e5.png)
![2021-07-30_16 18 41](https://user-images.githubusercontent.com/80720320/127712812-ae8c7eaa-09f1-441b-82c9-3616092d7563.png)
![bruhh](https://user-images.githubusercontent.com/80720320/127712831-03162132-2dd8-449f-86d7-82a520a63c64.PNG)

**Comment by Smokedeuch** [comment]
Yeah Same

![2021-08-08_00 10 53](https://user-images.githubusercontent.com/77568373/128622107-2c04b1d8-3944-4e8b-b181-5c2d86734d10.png)

![Scribe](https://user-images.githubusercontent.com/77568373/128622123-47a0b142-7865-4ef7-84a1-a1d4313b3b1c.GIF)
