### ISSUE TITLE
Dragons can't go above 1024 health even when changed in the config 2.1.8

### ISSUE THREAD

**Issue by DwagonO** [Alex-the-666/Ice_and_Fire#4116]
**Describe the bug**
I changed the config to make the max dragon health to become 15,000, when I went in game I check multiple dragons healthbar and they would always be stuck at 1024. I tried multiple checks to see if there's anything that would let me go above 1024 and nothing worked. 

**To Reproduce**
1. Install a mod to see enemy health.
2. Go to the config files
3. Set the max dragon health to something like 10,000 (also works on 2,000 but is harder to spot.
4. Get into the game and spawn in a bunch of dragons and check their health and kill them.

**Expected behavior**
A dragons health being above 1024

**Screenshots**
![image](https://user-images.githubusercontent.com/62491781/127756720-002676cf-d51e-405a-9c73-2553fd441ff4.png)
![2021-07-31_18 59 41](https://user-images.githubusercontent.com/62491781/127756725-31b826b7-8710-48cb-a43e-6eb4f1f5093f.png)
![2021-07-31_18 38 52](https://user-images.githubusercontent.com/62491781/127756727-69a46a06-a662-4e35-9489-426b8cd02981.png)

**Comment by TheBv** [comment]
This is a limitation with the default minecraft code. Take a look at this : https://www.curseforge.com/minecraft/mc-mods/attributefix
Should fix the issue although I've never tried it myself.
