### ISSUE TITLE
Invisible Dragons in lan world

### ISSUE THREAD

**Issue by Flemmli97** [Alex-the-666/Ice_and_Fire#412]
Dragons are invisible for players in a lan world except the host.

How to reproduce:
1. Open a lan world
2. Some player join the lan world
3. Dragons are invisible to the joined player

Versions:
MC: 1.12
Forge: 1.12.2-forge1.12.2-14.23.1.2585
Modversion: 1.3.1
LLibrary version: 1.7.9

**Comment by Flemmli97** [comment]
edit: this only happens in a lan world. i set up a server with the exact settings and there i was able to see the dragons

**Comment by billyty08** [comment]
Having same issue with all mobs from Ice&Fire not just dragons-forge 14.23.4.2715- iceandfire 1.5.1-1.12.2.jar It seamed to work when we switched to other person hosting but the next time playing it didn't show for the person joining the lan game

**Comment by AlexModGuy** [comment]
#1447
