### ISSUE TITLE
Game Crashes butServer deosnt  [2.1.8]

### ISSUE THREAD

**Issue by Erdnussflip007** [Alex-the-666/Ice_and_Fire#4122]
**Describe the bug**
Game crashes walking through the world near an ice dragon if thats important

**To Reproduce**
go onto my server and wait a little. Sorry havent tried to reproduce it else.

**Expected behavior**
Not Crash

**Screenshots**
I have non but the crashreport
[crash-2021-08-02_22.02.31-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6919404/crash-2021-08-02_22.02.31-client.txt)

**Additional context**
I was the only one on the server and the server itselve doesnt crash, only my game

**Comment by Denkusu** [comment]
I got the same problem, is there any way to disable ice dragons?

**Comment by Geicosuave** [comment]
Ive been having a similar issue

**Comment by answering-mechine** [comment]
Downgrade citadel from 1.7.2 to 1.7.1
