### ISSUE TITLE
Server crashes [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by Krerion** [Alex-the-666/Ice_and_Fire#4123]
**Describe the bug**
When anyone walks near an ice dragon, the server crashes.

**To Reproduce**
1. Go near to an ice dragon
2. Wait until it uses his ice breath.
3. The server crashes

**Expected behavior**
Not crash

**Screenshots**
Details:
	Entity Type: iceandfire:ice_dragon (com.github.alexthe666.iceandfire.entity.EntityIceDragon)
	Entity ID: 692
	Entity Name: Ice Dragon
	Entity's Exact location: 382.20, 86.40, 869.79
	Entity's Block location: World: (382,86,869), Chunk: (at 14,5,5 in 23,54; contains blocks 368,0,864 to 383,255,879), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Entity's Momentum: -0.00, -0.04, 0.27
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

[crash-2021-08-03_00.34.24-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6919968/crash-2021-08-03_00.34.24-server.txt)

**Comment by CryptNation** [comment]
Hiya,
I am also having the same issue.
I run a community with a Modpack called *Crypt's Additions*
One player was trying to find a dragon, then the server crashed
with the same error as above
[crash-reports_crash-2021-08-08_19.31.31-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6951360/crash-reports_crash-2021-08-08_19.31.31-server.txt)

**Comment by Krerion** [comment]
> Hiya,
> I am also having the same issue.
> I run a community with a Modpack called _Crypt's Additions_
> One player was trying to find a dragon, then the server crashed
> with the same error as above
> [crash-reports_crash-2021-08-08_19.31.31-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6951360/crash-reports_crash-2021-08-08_19.31.31-server.txt)

Hello, i just fix the issue with changing the versión of citadel to an older one.
