### ISSUE TITLE
Ice dragon crashing server [iceandfire-2.1.8]

### ISSUE THREAD

**Issue by vydax** [Alex-the-666/Ice_and_Fire#4125]
**Describe the bug**
Ice Dragon hitting player crashes the server, probably some mod conflict, not sure which though.

**To Reproduce**
1. Fight Ice Dragon
2. Get blasted by Ice Dragon's Blast
3. Crash server

**Expected behavior**
i was expecting a normal fight with the dragon

**Additional context**
https://pastebin.com/AC7B6r00
crashlogs from server

**Comment by FlameyFaucet** [comment]
Citadel 1.7.2 is having severe issues with Ice and Fire currently. Downgrade to citadel 1.7.1, it won't cause any further issues

**Comment by vydax** [comment]
alright thank you :)
