### ISSUE TITLE
Initialization crash[iceandfire-1.9.1-1.12.2]

### ISSUE THREAD

**Issue by FireOfDragon** [Alex-the-666/Ice_and_Fire#4128]
Describe the bug
Game crashes during initializing

To Reproduce
Just launch minecraft

Screenshots
![crash](https://user-images.githubusercontent.com/88480242/128311526-e8342499-de1f-4a1b-8980-a4752a5bab38.png)
![image](https://user-images.githubusercontent.com/88480242/128311690-823d119b-0a83-4a3d-8c0f-20a91bea3728.png)
[crash-2021-08-05_09.59.26-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6936921/crash-2021-08-05_09.59.26-client.txt)

**Comment by LukeGus** [comment]
Same thing is happening to me

**Comment by LukeGus** [comment]
For me it was ISeeDragon mod deleting it fixed it
