### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by Krerion** [Alex-the-666/Ice_and_Fire#4129]
**Describe the bug**
Error when killing an ice dragon

**To Reproduce**
Killing an ice dragon

**Expected behavior**

**Screenshots**
[11:35:05] [Server thread/ERROR] [co.te.bl.Blame/]:
****************** Blame Report 1.16.5-3.2.3-forge ******************

 Found a Loot Table path that does not exist:  iceandfire:entities/ice_dragon
 The path represented by this Loot Table is:  data/iceandfire/loot_tables/entities/ice_dragon.json
 Loot Table method called at:  net.minecraft.entity.LivingEntity.func_213354_a
                               net.minecraft.entity.MobEntity.func_213354_a
 Most common cause is that the Loot Table file is not actually at that location.
 Please let the mod author know about this so they can check to see if their Loot Table is correct.

**Comment by TheBv** [comment]
Dragons aren't supposed to drop loot when they die (in the minecraft way). They leave behind a corpse that acts as the loot hence there is no loot table for them that exists directly.
