### ISSUE TITLE
Crash while placing pixie house

### ISSUE THREAD

**Issue by jrowel20** [Alex-the-666/Ice_and_Fire#413]
The game crashed whilst rendering block entity
Error: java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}

**Comment by AlexModGuy** [comment]
dupe issue
