### ISSUE TITLE
gorgon stone statue missing texture [ICE AND FIRE 1.9.1-1.12.2]

### ISSUE THREAD

**Issue by mechanikilla** [Alex-the-666/Ice_and_Fire#4130]
**Describe the bug**
-(I&F only) statues, once hit with pick, turn invisible
-eye glow remains visible

**To Reproduce**

-Ice & fire alone
-forge 14.23.5.2855
1. petrify any entity
2. hit once with pick
3. texture vanishes (all but glowing eyes)

**Expected behavior**
intermediary "breaking" textures

**Screenshots**
-eyes glowing bottom left
-HUD entity preview reveals intended textures
![2021-08-06_05 04 17](https://user-images.githubusercontent.com/34903405/128391741-2b9f2c24-70d4-43d9-b00e-66e6e746dc43.png)

**Additional context**
-some optifine textures also dont get petrified properly ie; scary spiders (i suspect this is non solvable)
-if possible i'm willing to use previous forge versions, until fix (if exists please inform)

**Comment by DigitalWendigo** [comment]
Unfortunately 1.12.2 is no longer supported. 
I'd also suggest checking if you have optifine installed. 
If you do, try to reproduce the issue without it or any other performance mods you may have installed as the issue isn't present with just Citadel and Ise and Fire installed.
