### ISSUE TITLE
Tamed sitting dragons roar spamming [ICE AND FIRE VERSION 2.1.8]

### ISSUE THREAD

**Issue by warning-djkajslh** [Alex-the-666/Ice_and_Fire#4131]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Tamed dragons will puncture your ear drums with its roar

**To Reproduce**
1. Have multiple tamed dragons sitting
2. Constantly hear screeching sounds every 10 seconds or so

**Expected behavior**
Sitting dragons that set to sit still will not roar, only in wander or escort.

**Screenshots**

**Additional context**
Pleaseeee... this will save my sanity

**Comment by FlameyFaucet** [comment]
Just lower your volume or separate the dragons.
