### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by Mathad22** [Alex-the-666/Ice_and_Fire#4132]
**Describe the bug**
My server crashes whenever something big happens with dragons mainly  

**Screenshots**
![Capture PNG1](https://user-images.githubusercontent.com/88522216/128449639-ee53dfb4-380e-415f-9651-14004098a9ed.PNG)
![Capture PNG2](https://user-images.githubusercontent.com/88522216/128449646-7338e39b-9299-4735-9692-19aaf46d73f6.PNG)
![Capture PNG3](https://user-images.githubusercontent.com/88522216/128449649-3e6f706b-79a2-4bad-a581-c558c1545af7.PNG)

sent some screenshots of the log before the crash

**Comment by FlameyFaucet** [comment]
Citadel issue. Downgrade to Citadel 1.7.1
