### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by JatzCarlea469** [Alex-the-666/Ice_and_Fire#4134]
Sorry pls can yu help me the mod give me a problem crash with this error:
[crash-2021-08-06_16.30.13-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6946226/crash-2021-08-06_16.30.13-server.txt)

**Comment by jynx474** [comment]
Downgrade Citadel 1.7.2 to 1.7.1 v1.7.2 is bugged and Alex plainly states that on the mod page

**Comment by JatzCarlea469** [comment]
If i install citadel 1.7.3
