### ISSUE TITLE
Crash when changing biome config - v2.1.8

### ISSUE THREAD

**Issue by ForgedPie** [Alex-the-666/Ice_and_Fire#4139]
### Details
When changing the biome config for fire dragons you can not click the "Create New World", or the "Play Selected World" buttons without a crash.

### Steps to reproduce the behavior

1.  Change Biome config "Minecraft\Instances\MPS_S4 0.6\config\iceandfire\fire_dragon_biomes.json" to 
{
-"biomes": [
--- [
---- {
-----"type": "REGISTRY_NAME",
-----"negate": false,
-----"value": "atum:limestone_crags"
----},
---]
--]
}

**REPLACE "-" WITH SPACES**

2. Launch game and expect a crash from creating/loading into a world

### Crash Log
[crash-2021-08-08_08.14.49-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6951199/crash-2021-08-08_08.14.49-client.txt)

**Comment by TheBv** [comment]
Make sure the spaces are consistent and always keep them even. You can also use tools like [this](https://jsonformatter.curiousconcept.com/) to make sure what you've entered is valid.
And remove the comma after the curly bracket. It should look like this:
```
{
  "biomes": [
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "atum:limestone_crags"
      }
    ]
  ]
}
```
With "-" for spaces:
```
{
--"biomes": [
----[
------{
--------"type": "REGISTRY_NAME",
--------"negate": false,
--------"value": "atum:limestone_crags"
------}
----]
--]
}
```
