### ISSUE TITLE
A few glitches

### ISSUE THREAD

**Issue by YoonaWolfff** [Alex-the-666/Ice_and_Fire#414]
There's a few glitches. Wild and tamed dragon have a tendency to spin around in circles. Also Tamed dragons won't breathe fire or ice when they are stage 5 at 70+ hearts. I'm also having a problem with tamed dragons attacking everything and moving around when sitting. It is still a great mod! I encourage you to keep updating it, I would hate for this to die...

 

I am using 1.12.2 version 1.3.1.

**Comment by AlexModGuy** [comment]
not able to duplicate in 1.4.0
