### ISSUE TITLE
Server crash running Enigmatica 6 0.5.9

### ISSUE THREAD

**Issue by Chris5302** [Alex-the-666/Ice_and_Fire#4140]
Running enigmatica 6 server with a few additional mods including ice and fire  V2.1.8. Some people on the server were out hunting dragons and came across a T5 ice dragon, after engaging the dragon the server crashed immediately and upon restart and them rejoining crashed again. i managed to capture the crash log for combing.

https://pastebin.com/jwiqY2KZ

**Comment by QM-QM** [comment]
I and my friend had same issue with Ice Dragons. ---- **Updating Citadel fixed this issue for me. From (citadel-1.7.2-1.16.5.jar) to (citadel-1.7.3-1.16.5.jar)**

**Comment by AlexModGuy** [comment]
fixed in 2.1.9
