### ISSUE TITLE
Server crashing when going near a dragon nest

### ISSUE THREAD

**Issue by Gaeln1** [Alex-the-666/Ice_and_Fire#4141]
Description
The game crashes when going near to a Dragon Nest
Reproduce
1. Go near to a Dragon Nest
2. Dragon start flying
3. Server Crashes

**Expected behavior**
Server not crashing

**Screenshots**
[crash-2021-08-09_00.43.53-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6952417/crash-2021-08-09_00.43.53-server.txt)
**Additional context**
Citadel is the problem, 1.7.3 crashes when getting near to a dragon nest, 1.71 works perfectly.

**Comment by sikoyka** [comment]
I tried with Citadel 1.7.1 and still does it, but for me, it only crashes when I find a sapphire ice dragon. Any stage. It doesn't even attack, the moment I see the dragon, the server crashes.

**Comment by bribri69** [comment]
Hello,

Same problem when i'm starting a fight with an ice dragon... server crash
My citadel version :  citadel-1.7.2-1.16.5.jar

[crash-2021-08-12_20.40.33-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6977786/crash-2021-08-12_20.40.33-server.txt)

**Comment by Shorepion** [comment]
https://github.com/Shorepion/Magica-Infinitum-III/issues/14
same here
