### ISSUE TITLE
Swastika in one of the village houses added by ice and fire 2.1.8 1.16.5

### ISSUE THREAD

**Issue by dcdoomcat** [Alex-the-666/Ice_and_Fire#4144]
A very clear swastika appears in the savanna variant of the bestiary house in the glass on the ceiling

1. Locate savanna biome
2. Find a bestiary house (crackled cobblestone, acacia wood, desert myrmex glass ceiling, bestiary lectern inside, etc.)
3. Look up at the glass ceiling
4. Profit

Man idk lmao theres just a swastika on the roof and i dont know if yall know its there

https://user-images.githubusercontent.com/73063302/128846215-e8bd8914-f10d-486f-a9fb-8f33f15bd502.png
idk how to do images in github sorry homies

**Comment by answering-mechine** [comment]
Lol
