### ISSUE TITLE
Shooting Ghost with Bow Crashes Client and Server [ICE AND FIRE VERSION 2.1.8]

### ISSUE THREAD

**Issue by Sonnebahn** [Alex-the-666/Ice_and_Fire#4145]
**Describe the bug**
Shooting a Ghost with a Bow and Regular arrow (have not tried other arrows) freezes client and crashes server. Client freeze is instant, and must be forced to close. Server is delayed about 60 seconds, when the tick threshold is exceeded and server crashes. Server restarts normally. Client slows extremely on reload as Texture Atlas stitching, taking 30+ minutes, where normal timeframe of loading is 2-3 minutes. Client machine restart restores load time to normal.

**To Reproduce**
1. Go to the Other dimension (only place ghosts spawn)
2. Attack Ghost
3. Shoot Ghost with Bow and Arrow
4. Client Freezes
5. Server Crashes

**Expected behavior**
Ghost to die. (bow enchanted to One-shot most basic mobs)

**Additional context**
Client machine - Windows 10, 128G, Ryzen 9 5900x - client run through Curseforge maximum memory allocation.
Server - Hyper-V virtual machine running on Client machine, Ubuntu 18.04.5 LTS, 30G Ram allocated, 20G set as max for Java.
All The Mods 6 (1.7.6) + Lootr 0.0.6.18

**Comment by Tr3v1z3** [comment]
Still crash in 2.1.9

**Comment by RedBloodCat** [comment]
Still cashes

**Comment by SpicyFishOuO** [comment]
I also encountered this in the server
I was using Draconic-Evolution bow to shoot ghosts and it crashed the server!
Mod version:
iceandfire-2.1.9-1.16.5.jar
Draconic-Evolution-1.16.5-3.0.22.444-universal.jar
Server Core：
arclight-forge-1.16.5-1.0.23-SNAPSHOT.jar
arclight web: https://github.com/IzzelAliz/Arclight

**Comment by TheBv** [comment]
Can you provide the crash log? @SpicyFishOuO

**Comment by Sonnebahn** [comment]
Here's my crash report.
[https://gist.github.com/Sonnebahn/f73fd0e1c50914cabde6280068da8fa2#file-crash-2021-08-09_15-42-49-server-txt](url)

**Comment by SpicyFishOuO** [comment]
[](url)https://pan.baidu.com/s/1YcTZ-PiXX8ql52jow1lnpA?pwd=q85h

**Comment by DigitalWendigo** [comment]
Please try to reproduce this crash without the mod "Polymorph" installed. 
It's known to cause some issues with modded creatures.
