### ISSUE TITLE
Random dragon crashes server 1.16.5

### ISSUE THREAD

**Issue by AsterionXeity** [Alex-the-666/Ice_and_Fire#4148]
Hello!

The mod works alone, but when added to a big modpack it just doesn't work, well something with the dragons keeps making the whole server crash i already checked the config files aswell so im out of ideas. I have removed what i could at least the server runs as of now.
https://mcpaste.io/5856cb658ae0d922 and http://hastebin.com/evapenirob.yaml

**Comment by FlameyFaucet** [comment]
_Sigh_ Logs mentioned ice dragon. Downgrade the Citadel mod inside the pack to 1.7.1, however if you still crash then it might be a corrupted entity.

**Comment by Veynam** [comment]
I'm facing the same crash due to citadel as well. Really hope they can fix it soon.

**Comment by Lonsdale201** [comment]
Same issue.

**Comment by AlexModGuy** [comment]
fixed in 2.1.9
