### ISSUE TITLE
Lightning Dragon crashes when loading its nest.

### ISSUE THREAD

**Issue by gqrshy** [Alex-the-666/Ice_and_Fire#4152]
I was digging for minerals underground, and suddenly the system crashed under a sudden load.
We think it has something to do with the dragon's nest underground.
I'm Japanese, so I'm using a translation tool to report this. I'm sorry for my poor English.
[crash-2021-08-15_17.40.53-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6987852/crash-2021-08-15_17.40.53-server.txt)

**Comment by Samlegamer** [comment]
Hello this crash seems to be caused by the Advent of Ascension mod not by Ice and Fire.
