### ISSUE TITLE
Ice dragon causes game to crash upon player getting hit with ice breath. Singleplayer.

### ISSUE THREAD

**Issue by HydroFrog64** [Alex-the-666/Ice_and_Fire#4154]
**Describe the bug**
Ice dragon breath causes game to crash for me.  Happens on version 2.1.8 for 1.16.5

**To Reproduce**
1. Find ice dragon
2. let it attack you with it's breath 
3. See error

**Expected behavior**
Not to crash. Player takes damage (and gets frozen?) as expected.

**Additional context**

[crash-2021-08-16_00.31.29-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6994879/crash-2021-08-16_00.31.29-server.txt)

[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/6994881/latest.log)

**Comment by HydroFrog64** [comment]
Also, version 2.1.8 for 1.16.5

**Comment by Red6785** [comment]
Downgrade Citadel to 1.7.1
