### ISSUE TITLE
 [2.1.8-1.16.5] Tide Trident Error in server console by hitting a mob

### ISSUE THREAD

**Issue by SpartaWarsec** [Alex-the-666/Ice_and_Fire#4155]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug*

you throw the trident at an opponent

**To Reproduce**
you throw the trident at an opponent

**Expected behavior**
Server thread/INFO18:50:53
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: net.minecraftforge.fml.common.ObfuscationReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: field_226571_aq_
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:242)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at com.github.alexthe666.iceandfire.entity.EntityTideTrident.func_213868_a(EntityTideTrident.java:73)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.entity.projectile.ProjectileEntity.func_70227_a(SourceFile:118)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:188)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.entity.projectile.TridentEntity.func_70071_h_(SourceFile:93)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.world.World.func_217390_a(MixinWorldRedstone.java:554)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at java.lang.Thread.run(Unknown Source)
[java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoSuchFieldException: field_226571_aq_
[java.lang.Throwable:printStackTrace:-1]: at java.lang.Class.getDeclaredField(Unknown Source)
[java.lang.Throwable:printStackTrace:-1]: at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:236)
[java.lang.Throwable:printStackTrace:-1]: ... 13 more
Server thread/ERROR18:51:01
M&A Warding Candle: Caught EntityMobGriefingEvent event but the entity parameter is null even though the getEntity() method is not flagged as @Nullable. Allowing the event through because without this parameter there is no way to check a warding candle radius without this parameter. To be clear: THIS IS NOT AN M&A BUG. THIS IS A FORGE ISSUE.
18:51:02
M&A Warding Candle: Caught EntityMobGriefingEvent event but the entity parameter is null even though the getEntity() method is not flagged as @Nullable. Allowing the event through because without this parameter there is no way to check a warding candle radius without this parameter. To be clear: THIS IS NOT AN M&A BUG. THIS IS A FORGE ISSUE.
18:51:04
M&A Warding Candle: Caught EntityMobGriefingEvent event but the entity parameter is null even though the getEntity() method is not flagged as @Nullable. Allowing the event through because without this parameter there is no way to check a warding candle radius without this parameter. To be clear: THIS IS NOT AN M&A BUG. THIS IS A FORGE ISSUE.
Server thread/INFO18:52:47
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: net.minecraftforge.fml.common.ObfuscationReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: field_226571_aq_
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:242)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at com.github.alexthe666.iceandfire.entity.EntityTideTrident.func_213868_a(EntityTideTrident.java:73)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.entity.projectile.ProjectileEntity.func_70227_a(SourceFile:118)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:188)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.entity.projectile.TridentEntity.func_70071_h_(SourceFile:93)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.world.World.func_217390_a(MixinWorldRedstone.java:554)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at java.lang.Thread.run(Unknown Source)
[java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoSuchFieldException: field_226571_aq_
[java.lang.Throwable:printStackTrace:-1]: at java.lang.Class.getDeclaredField(Unknown Source)
[java.lang.Throwable:printStackTrace:-1]: at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:236)
[java.lang.Throwable:printStackTrace:-1]: ... 13 more
18:52:50
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: net.minecraftforge.fml.common.ObfuscationReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: field_226571_aq_
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:242)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at com.github.alexthe666.iceandfire.entity.EntityTideTrident.func_213868_a(EntityTideTrident.java:73)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.entity.projectile.ProjectileEntity.func_70227_a(SourceFile:118)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:188)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.entity.projectile.TridentEntity.func_70071_h_(SourceFile:93)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.world.World.func_217390_a(MixinWorldRedstone.java:554)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
[com.github.alexthe666.iceandfire.entity.EntityTideTrident:func_213868_a:78]: at java.lang.Thread.run(Unknown Source)
[java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoSuchFieldException: field_226571_aq_
[java.lang.Throwable:printStackTrace:-1]: at java.lang.Class.getDeclaredField(Unknown Source)
[java.lang.Throwable:printStackTrace:-1]: at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:236)
[java.lang.Throwable:printStackTrace:-1]: ... 13 more

**Screenshots**

**Additional context**

**Comment by AlexModGuy** [comment]
fixed in 2.1.9
