### ISSUE TITLE
[1.12.2] Dragon fire still transforms blocks despite griefing rule

### ISSUE THREAD

**Issue by MokahTGS** [Alex-the-666/Ice_and_Fire#416]
Dragons still transform ground into the cinder versions despite the dragon griefing rule being set to false.  This is an issue when dragons are trying to kill every bunny they see with tons of fire everywhere.

**Comment by ghost** [comment]
I added a link to an issue from my grave mod report section related to your mod and below, the code that could be the reason.
https://github.com/Alex-the-666/Ice_and_Fire/blob/1.12.2/src/main/java/com/github/alexthe666/iceandfire/entity/FireExplosion.java#L223-L227
so, if you could just add the griefing rules (for MokahTGS) and check for block.canEntityDestroy(IBlockState state, IBlockAccess world, BlockPos pos, Entity entity), it would be perfect :+1:

**Comment by ghost** [comment]
For my mod, i finally solved the trouble.

**Comment by NielsPilgaard** [comment]
Any update on this issue?
