### ISSUE TITLE
Can't load the mod

### ISSUE THREAD

**Issue by Thomblues** [Alex-the-666/Ice_and_Fire#4160]
![image](https://user-images.githubusercontent.com/89299086/130322441-65f34d75-4dd8-4b40-9613-8fafdfd568d5.png)

**Comment by IrregularArt** [comment]
i have some issue, this appear in the log
![image](https://user-images.githubusercontent.com/55319897/130551961-d8228525-2cb2-45e2-b459-c00bbdfa0115.png)

**Comment by IrregularArt** [comment]
i tried to download another version of the mod and solves it. 
![image](https://user-images.githubusercontent.com/55319897/130552657-bb3ce2f4-338f-4f5a-adb7-2505ec28eeb0.png)

**Comment by FlameyFaucet** [comment]
you were probably using a wrong version of citadel for your I&F mod.
