### ISSUE TITLE
Ice Dragon and Forge 2.1.8.1-1.16.5

### ISSUE THREAD

**Issue by Rithenar** [Alex-the-666/Ice_and_Fire#4161]
Ice Dragon does not breathe onto forge when facing it. I have to mount the dragon and face away from the forge for it to work

1. Place items in forge
2. Dragon doesn't do anything
3. Mount dragon
4. Face away from forge

**Expected behavior**
Dragon breathes on forge to create metal without having to re-positioning it or mounting it

**Screenshots**
https://gyazo.com/fe5173a7651bebb0587b1b53456830b0

**Additional context**
Playing ATM 6

**Comment by AlexModGuy** [comment]
fixed in 2.1.9
