### ISSUE TITLE
Error with Mahou Tsukai [iceandfire-2.1.8-1.16.5]

### ISSUE THREAD

**Issue by Shikomi36** [Alex-the-666/Ice_and_Fire#4167]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
When a boundary (barrier) is turned on by the Mahou tsukai mod in a server (we are using an aternos server), everyone gets timed out.

**To Reproduce**
1. Make the tangible boundary (barrier) [iron, iron, diamond]
2. Turn it on.
3. You will be timed out but the server will still be running.

**Expected behavior**
What was expected to happen was that the barrier would just turn on.

**Screenshots**

**Additional context**
in a client's latest log this is mostly repeated
Error executing task on Client
"java.lang.NullPointerException: null
    at com.github.alexthe666.citadel.server.entity.datatracker.EntityProperties.getEntity(EntityProperties.java:63) ~[?:1.7.3-1.16.5]
    at com.github.alexthe666.iceandfire.entity.props.ChainEntityProperties.loadNBTData(ChainEntityProperties.java:54) ~[?:2.1.7-1.16.5]
    at "
Client log that's from the site of when the boundary was turned on: 
[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/7029334/latest.log)
Please look soon, we're going to have to reset our world for the 3rd time if not. ;-;

**Comment by AlexModGuy** [comment]
fixed in 2.1.9
