### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by Alekacprep** [Alex-the-666/Ice_and_Fire#4168]
**Describe the bug**
I got hit with a fire ball and now i can't join my singleplayer world beacause it crashing

**To Reproduce**
1. Go to underground dragon lair.
2. Get hit with a fireball.
3. Crash. 

**Expected behavior**
I get blown up

**Additional context**
[crash-2021-08-23_20.15.25-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/7034254/crash-2021-08-23_20.15.25-server.txt)

**Comment by AlexModGuy** [comment]
fixed in 2.1.9
