### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION 2.1.8-1.16.5]

### ISSUE THREAD

**Issue by user43214i8957894** [Alex-the-666/Ice_and_Fire#4170]
Dragons dont spawn's ._. i was searching dragons too long time and cant fin no one

**Comment by Samlegamer** [comment]
What Mod did you install with ice and fire?

**Comment by user43214i8957894** [comment]
![image](https://user-images.githubusercontent.com/89544219/130873043-316d2326-ffe8-4c79-be1a-de245d029688.png)
