### ISSUE TITLE
Ticks take several seconds to complete due to Myrmex [2.1.8-1.16.5]

### ISSUE THREAD

**Issue by jack-cole** [Alex-the-666/Ice_and_Fire#4173]
**Describe the bug**
Game has ticks that take several seconds to complete. The log implies that it's the Myrmex.

**To Reproduce**
1. Just chilling doing nothing.
2. Have Myrmex in area.
3. Wait...
4. Lag spike occurs.

**Expected behavior**
No lag spikes.

**Additional context**
https://spark.lucko.me/459JvXTSBy
https://spark.lucko.me/ufWjxxFgHy

**Comment by jack-cole** [comment]
Some more info: My friend who saw the Myrmex workers said they were just rotating in circles. When I went to delete them to fix the issue, there were only 3 listed in the entities list. Deleting them resolved all server lag.

**Comment by AlexModGuy** [comment]
should be reduced in 2.1.9
