### ISSUE TITLE
Issue with shadows when mounting dragons [2.1.8]

### ISSUE THREAD

**Issue by guivnf** [Alex-the-666/Ice_and_Fire#4174]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
When mounting on dragons, optifine shaders get messed up. The shadows change related to the player's point of view when mounted on a dragon.

**To Reproduce**
1. install forge 1.16.5 36.2.0
2. Put ice and fire (2.1.8) mod, citadel 1.7.1 and optifine HD_U_G8
3. Launch the game, create a new world summon any type of dragon and tame it with creative dragon meal and mount on to it.

**Expected behavior**
Shadows shouldn't alter themselfs related to the player's pov

**Screenshots**

https://user-images.githubusercontent.com/77132244/131043199-4360d250-528f-4577-8f62-37201eaadb8c.mp4

**Comment by TheBv** [comment]
I've looked into this but there's nothing we can do about this. This seems to be a limitation with most shaders. You can however change how close the camera is when in third person (default F7) and if you put it as close as possible that usually fixes it.
