### ISSUE TITLE
Baby dragons randomly teleporting(2.1.8)

### ISSUE THREAD

**Issue by BudgieGryphon** [Alex-the-666/Ice_and_Fire#4175]
Dragons below stage 2(as far as I've seen, they may still do it when older) randomly teleport 10-30 blocks from their position, usually not towards the player. They can travel through walls and do it even when sleeping and set to stay. When placed on the player's shoulder and moved away they teleport back a few seconds after being placed down; using a dragon horn temporarily fixes this but they can eventually teleport again.

**To Reproduce**
1. hatch/spawn and tame a baby dragon of any species
2. remain in the area for a while, this may take some time
3. baby dragon teleports to a new location

**Expected behavior**
Baby dragons to remain in the spots they are placed in to sit or wander.

**Comment by TheBv** [comment]
Closing in favor of #3870
