### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by Forturian** [Alex-the-666/Ice_and_Fire#4176]
Hello. I would like to ask a question about dragon roost generation. Usually this number is "360", and if I want to reduce the spawn rate do I need to enter a number greater or less than 360? 
![image](https://user-images.githubusercontent.com/73849499/131098260-98ac17c0-88ce-42a4-9d46-916e93cb9e89.png)

**Comment by user43214i8957894** [comment]
i think u need to enter a number less than 360.

I wanna know how do u do that cause in my world the dragon roost's are extremely strange and too hard to see a dragon
