### ISSUE TITLE
Hundreds of NullPointerExceptions each second with Botania [ICE AND FIRE 2.1.8-1.16.5]

### ISSUE THREAD

**Issue by tyggna** [Alex-the-666/Ice_and_Fire#4177]
# Version Information
Forge version:  36.1.2  
Botania version:  1.16.5-419  

# Further Information
Link to crash log: https://gist.github.com/tyggna/ac6e7b712e9b4915e880dd8d5dd673e9  
I get one of these approximately every 8ms and I suspect that's what's causing frequent lockups in my game.

Steps to reproduce:
Install Botania 1.16.5-419 and Ice and Fire 2.1.8-1.16.5  
(I'm using Oracle java 1.8.0_301 64-bit on Windows 10)

What I expected to happen:
Either no exceptions are raised, or they are gracefully handled in such a way that they don't completely kill the system.

What happened instead:
Hundreds of NullPointerExceptions each second  (I'll be posting this bug to their mod as well)

**Comment by AlexModGuy** [comment]
should be fixed in 2.1.9
