### ISSUE TITLE
Issue with Ice Dragons

### ISSUE THREAD

**Issue by Yurillith** [Alex-the-666/Ice_and_Fire#4188]
I installed your mod (love it btw) on my 8GB RAM server and played it for a bit, altho there is a big problem, involving ice dragons, every time an Ice dragon does an ice breath attack the whole server crashes and restarts and it did it twice yesterday because the server didn't despawn the dragon the first time, is there any way I can prevent ice dragon spawn? Or just prevent them from crashing my server? Pleeease I really wanna play your mod but I dont wanna lose my server

**Comment by TheBv** [comment]
Try upgrading to version 2.1.9 that should resolve the issue
