### ISSUE TITLE
Crash server - 2.1.9-1.16.5

### ISSUE THREAD

**Issue by samos667** [Alex-the-666/Ice_and_Fire#4189]
**Describe the bug**
Server as crash when i have juste found a dragon.

**To Reproduce**
Generate to found dragon

**Crash report**
https://pastebin.com/a2EkSfuv

**Comment by Eydan990** [comment]
Why when I find a dragon and it kills an entity, does my Aternos server crash?

**Comment by Eydan990** [comment]
Why when I find a dragon and it kills an entity, does my Aternos server crash?
