### ISSUE TITLE
[MP] Grypphons and dragons randomly dissapearing while flying them + Snow villagers wont trade

### ISSUE THREAD

**Issue by loander** [Alex-the-666/Ice_and_Fire#419]
mod version: 1.3.1

gryphons and and dragons randomly despawn or throw you off while flying.
Also villagers dont seem to want to trade.

**Comment by TheRealDasAuto** [comment]
Had a Hippogryph disappear although not in flight. :( I miss my baby.

**Comment by AlexModGuy** [comment]
dupe issue
