### ISSUE TITLE
Tide Trident thrown becomes a regular trident [2.1.9-1.16.5]

### ISSUE THREAD

**Issue by LordHellscream** [Alex-the-666/Ice_and_Fire#4190]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Tide Trident becomes a regular trident after thrown

**To Reproduce**
1. throw a tide trident
2. pick it up
3. it becomes a regular trident

**Expected behavior**
tide trident returns as itself

**Screenshots**

**Additional context**

**Comment by Java-Queen** [comment]
Currently experiencing the same issue.

**Comment by Whytii99** [comment]
same issue, all players on my server experiencing this
