### ISSUE TITLE
Spawns are wack [2.1.9]

### ISSUE THREAD

**Issue by Shikomi36** [Alex-the-666/Ice_and_Fire#4191]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
I tried boosting and low the spawns of every mob because most of the mobs in the mod were just nonexistent. Now we are at the stage where im pretty sure dragon skeletons are overpowering dragon spawns, so no roost are spawning. Please tell us exactly how to lower spawns or make it easier to config. 

**To Reproduce**
1. Go to the dragon config
2. Set dragon skeletons to 1.
3. Suffer from a tundra filled with dragon corpses. 

**Expected behavior**
Dragon roost being able to spawn and we can have an easier time hunting dragons. 

**Screenshots**

![unknown-3](https://user-images.githubusercontent.com/88893564/131779175-4bc72d58-495e-48f6-b8c9-c9b5cb92cfb5.png)

**Additional context**
Most of the spawn configs are really hard to configure, please give an explanation on the ranges. Is it the higher the number the higher they spawn or vice versa?

**Comment by FlameyFaucet** [comment]
The lower the number, the more common it is. Many of I&F's configs depend on a "1 in X" chance format and the devs may have just expected you to pick that style up after you config other things.
In any case, there are already comments in the config file that point this out. To make the skeletons rarer, make the number higher.
This also applies to the spawn chance of roosts and caves (which also possess the comment that points the format out)

**Comment by Kushagra-Srivastava** [comment]
this is something you have done...not a bug nor worth making an issue

**Comment by Shikomi36** [comment]
Sorry it wasnt clear in the configs. Thanks for explaining.
