### ISSUE TITLE
Dragons vanishing from horns/crystals and eggs disappearing.

### ISSUE THREAD

**Issue by NoisyScrubBirb** [Alex-the-666/Ice_and_Fire#4192]
Hi,

Apologies if this is the wrong format but I'm on mobile currently. 
Since yesterday my server is having the issue of dragons not appearing when being released from the dragon horns/summoning crystals and often the eggs/newborn dragons are just vanishing as well.
Is there anything in the mods config files that could cause this? It's also rather random when it happens.
Any help would be deeply appreciated as the players are getting frustrated when even their second or third replacement disappears. Hatchery is also installed, is it worth telling the players to use the animal nets until this is fixed.

**Comment by zinkozapper** [comment]
I am having the same problem. It seems to have only started happening with this latest version. Half of the whenever I hatch an egg the baby dragon doesn't spawn in at all/disappears.
