### ISSUE TITLE
 Expected stackmap frame [ICE AND FIRE VERSION 1.9.1-1.12.2]

### ISSUE THREAD

**Issue by RegularAmoeba** [Alex-the-666/Ice_and_Fire#4195]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Game will start and forge will start installing all the mods upon opening, but after a while Minecraft crashes with the reason being that it expected a stackmap frame for the ice and fire 
 "com/github/alexthe666/iceandfire/entity/EntityDragonBase.breakBlock()V @457: goto"

**To Reproduce**
1. Go to CurseForge app
2. Click on modpack I created
3. launch Minecraft
4. Minecraft loads mods then crashes
5. See error

**Expected behavior**
I expected the game to open after loading the mods and bring me to the minecraft title screen

**Screenshots**
n/a

**Additional context**
I am using this mod in a modpack I created.
Here's the detailed walkthrough of the error, its code path and all known details

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at net.minecraftforge.fml.relauncher.ReflectionHelper.findConstructor(ReflectionHelper.java:326)
	at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findConstructor(ObfuscationReflectionHelper.java:194)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.<init>(EntityEntryBuilder.java:297)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$1.<init>(EntityEntryBuilder.java:265)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder.build(EntityEntryBuilder.java:265)
	at com.github.alexthe666.iceandfire.CommonProxy.registerSpawnable(CommonProxy.java:151)
	at com.github.alexthe666.iceandfire.CommonProxy.registerEntities(CommonProxy.java:84)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_207_CommonProxy_registerEntities_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1288515104 bytes (1228 MB) / 1852309504 bytes (1766 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 81 mods loaded, 81 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                           | Version                         | Source                                         | Signature                                |
	|:----- |:-------------------------------------------- |:------------------------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                                    | 1.12.2                          | minecraft.jar                                  | None                                     |
	| LCH   | mcp                                          | 9.42                            | minecraft.jar                                  | None                                     |
	| LCH   | FML                                          | 8.0.99.99                       | forge-1.12.2-14.23.5.2855.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                                        | 14.23.5.2855                    | forge-1.12.2-14.23.5.2855.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | com.elytradev.movingworld.common.asm.coremod |                                 | minecraft.jar                                  | None                                     |
	| LCH   | damageindicatorsmod                          | 1.0                             | [1.12.2]DamageIndicatorsMod-3.5.1.jar          | None                                     |
	| LCH   | movillages                                   | 1.5.4                           | [1.12]MoVillages-1.5.4.jar                     | None                                     |
	| LCH   | antiqueatlas                                 | 4.6.3                           | antiqueatlas-1.12.2-4.6.3.jar                  | None                                     |
	| LCH   | antiqueatlasoverlay                          | 1.2                             | antiqueatlas-1.12.2-4.6.3.jar                  | None                                     |
	| LCH   | jei                                          | 4.16.1.301                      | jei_1.12.2-4.16.1.301.jar                      | None                                     |
	| LCH   | appleskin                                    | 1.0.14                          | AppleSkin-mc1.12-1.0.14.jar                    | None                                     |
	| LCH   | baubles                                      | 1.5.2                           | Baubles-1.12-1.5.2.jar                         | None                                     |
	| LCH   | artifacts                                    | 1.12.2-1.2.3                    | Artifacts-1.12.2-1.2.3.jar                     | None                                     |
	| LCH   | waystones                                    | 4.1.0                           | Waystones_1.12.2-4.1.0.jar                     | None                                     |
	| LCH   | atlasextras                                  | 1.8                             | AtlasExtras-1.12.2-1.8.jar                     | None                                     |
	| LCH   | llibrary                                     | 1.7.20                          | llibrary-1.7.20-1.12.2.jar                     | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | alm                                          | 1.1                             | AvatarFlyingLemur-1.12.2-1.1.jar               | None                                     |
	| LCH   | gorecore                                     | 1.12.2-0.4.5                    | avatarmod-1.5.17-alpha.jar                     | None                                     |
	| LCH   | avatarmod                                    | 1.5.17-alpha                    | avatarmod-1.5.17-alpha.jar                     | None                                     |
	| LCH   | bettercaves                                  | 1.12.2                          | bettercaves-1.12.2-2.0.4.jar                   | None                                     |
	| LCH   | bettermineshafts                             | 1.12.2-2.2.1                    | BetterMineshaftsForge-1.12.2-2.2.1.jar         | None                                     |
	| LCH   | bibliocraft                                  | 2.4.5                           | BiblioCraft[v2.4.5][MC1.12.2].jar              | None                                     |
	| LCH   | biomesoplenty                                | 7.0.1.2441                      | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar  | None                                     |
	| LCH   | bookshelf                                    | 2.3.590                         | Bookshelf-1.12.2-2.3.590.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | chameleon                                    | 1.12-4.1.3                      | Chameleon-1.12-4.1.3.jar                       | None                                     |
	| LCH   | comforts                                     | 1.4.1.3                         | comforts-1.12.2-1.4.1.3.jar                    | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCH   | extendedrenderer                             | v1.0                            | coroutil-1.12.1-1.2.37.jar                     | None                                     |
	| LCH   | coroutil                                     | 1.12.1-1.2.37                   | coroutil-1.12.1-1.2.37.jar                     | None                                     |
	| LCH   | configmod                                    | v1.0                            | coroutil-1.12.1-1.2.37.jar                     | None                                     |
	| LCH   | cosmeticarmorreworked                        | 1.12.2-v5a                      | CosmeticArmorReworked-1.12.2-v5a.jar           | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCH   | craftstudioapi                               | 1.0.0                           | CraftStudio-1.0.0.93-mc1.12-alpha.jar          | None                                     |
	| LCH   | ctm                                          | MC1.12.2-1.0.2.31               | CTM-MC1.12.2-1.0.2.31.jar                      | None                                     |
	| LCH   | movingworld                                  | 1.12-6.353                      | movingworld-1.12-6.353-full.jar                | None                                     |
	| LCH   | davincisvessels                              | @DVESSELSVER@                   | davincisvessels-1.12-6.355-full.jar            | None                                     |
	| LCH   | dragonmounts                                 | 1.12.2-1.6.3                    | DragonMounts2-1.12.2-1.6.3.jar                 | None                                     |
	| LCH   | orelib                                       | 3.6.0.1                         | OreLib-1.12.2-3.6.0.1.jar                      | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dsurround                                    | 3.6.1.0                         | DynamicSurroundings-1.12.2-3.6.1.0.jar         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dynamictrees                                 | 1.12.2-0.9.25                   | DynamicTrees-1.12.2-0.9.25.jar                 | None                                     |
	| LCH   | dynamictreesbop                              | 1.12.2-1.5.1                    | DynamicTreesBOP-1.12.2-1.5.1.jar               | None                                     |
	| LCH   | twilightforest                               | 3.11.1021                       | twilightforest-1.12.2-3.11.1021-universal.jar  | None                                     |
	| LCH   | dynamictreesttf                              | 1.12.2-1.2.3                    | dynamictreesTheTwilightForest-1.12.2-1.2.3.jar | None                                     |
	| LCH   | fastleafdecay                                | v14                             | FastLeafDecay-v14.jar                          | None                                     |
	| LCH   | forgelin                                     | 1.8.4                           | Forgelin-1.8.4.jar                             | None                                     |
	| LCH   | futuremc                                     | 0.2.6                           | future-mc-1.12.2-0.2.6.1.jar                   | None                                     |
	| LCH   | gravestone                                   | 1.10.3                          | gravestone-1.10.3.jar                          | None                                     |
	| LCH   | huntingdim                                   | 1.0.42                          | HuntingDimension-1.12.2-1.0.42.jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | iceandfire                                   | 1.9.1                           | iceandfire-1.9.1-1.12.2.jar                    | None                                     |
	| LCH   | inventorytweaks                              | 1.63+release.109.220f184        | InventoryTweaks-1.63.jar                       | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | iseedragons                                  | 1.2                             | ISeeDragons-1.2.jar                            | None                                     |
	| LCH   | jeresources                                  | 0.9.2.60                        | JustEnoughResources-1.12.2-0.9.2.60.jar        | None                                     |
	| LCH   | jeroreintegration                            | 1.1.0                           | JEROreIntegration-1.12.2-1.1.0.jar             | None                                     |
	| LCH   | malisiscore                                  | 1.12.2-6.5.1-SNAPSHOT           | malisiscore-1.12.2-6.5.1.jar                   | None                                     |
	| LCH   | malisisdoors                                 | 1.12.2-7.3.0                    | malisisdoors-1.12.2-7.3.0.jar                  | None                                     |
	| LCH   | mobends                                      | 1.0.0-beta-20.06.20             | MoBends_1.12.2-1.0.0-beta-20.06.20.jar         | None                                     |
	| LCH   | guilib                                       | $version                        | morepaintings-paintings-1.12.2-5.0.1.2.jar     | None                                     |
	| LCH   | paintingselgui                               | $version                        | morepaintings-paintings-1.12.2-5.0.1.2.jar     | None                                     |
	| LCH   | morepaintings                                | $version                        | morepaintings-paintings-1.12.2-5.0.1.2.jar     | None                                     |
	| LCH   | shear                                        | 1.1.2                           | MoreShearables1.3.1-1.12.2.jar                 | None                                     |
	| LCH   | survivalplus                                 | 0.1.5                           | SurvivalPlus-1.12.2-0.1.5.jar                  | None                                     |
	| LCH   | morethanapickaxe                             | 0.1.5                           | MoreThanAPickaxe-1.12.2-0.1.5.jar              | None                                     |
	| LCH   | moveplus                                     | 1.12.1-2.4.6                    | moveplus-1.12.1-2.4.6.jar                      | None                                     |
	| LCH   | multimob                                     | 1.0.5                           | multimob-1.0.5.jar                             | None                                     |
	| LCH   | naturescompass                               | 1.8.5                           | NaturesCompass-1.12.2-1.8.5.jar                | None                                     |
	| LCH   | yurtmod                                      | 9.5.2                           | NomadicTents-1.12.2-9.5.2.jar                  | None                                     |
	| LCH   | overpoweredarmorbar                          | @VERSION@                       | overloadedarmorbar-1.0.4g.jar                  | None                                     |
	| LCH   | patchouli                                    | 1.0-23.6                        | Patchouli-1.0-23.6.jar                         | None                                     |
	| LCH   | petbat                                       | 1.4.8                           | PetBat-1.12.2.jar                              | None                                     |
	| LCH   | primitivemobs                                | 1.2.3a                          | primitivemobs-1.2.3a.jar                       | None                                     |
	| LCH   | roguelike                                    | 1.8.0                           | RoguelikeDungeons-1.12.2-1.8.0.jar             | None                                     |
	| LCH   | woodenshears                                 | @MAJOR@.@MINOR@.@REVIS@.@BUILD@ | SBM-WoodenShears-1.12-0.0.1b8.jar              | None                                     |
	| LCH   | spartanweaponry                              | beta 1.3.8                      | SpartanWeaponry-1.12.2-beta-1.3.8.jar          | None                                     |
	| LCH   | spartanfire                                  | 0.08                            | spartanfire-0.08.jar                           | None                                     |
	| LCH   | spartanshields                               | 1.5.4                           | SpartanShields-1.12.2-1.5.4.jar                | None                                     |
	| LCH   | spiderstpo                                   | 1.0.3                           | spiders-2.0-1.12.2-1.0.3.jar                   | None                                     |
	| LCH   | storagedrawers                               | 5.2.2                           | StorageDrawers-1.12.2-5.4.2.jar                | None                                     |
	| LCH   | tektopia                                     | 1.1.0                           | tektopia-1.1.0.jar                             | None                                     |
	| LCH   | tektopiainformation                          | 1.4.0                           | TektopiaInformation-1.12.2-1.1.0-1.4.0.jar     | None                                     |
	| LCH   | torchslabmod                                 | v1.5.2                          | torchslabmod-1.12.2-v1.5.2.jar                 | None                                     |
	| LCH   | wearablebackpacks                            | 3.1.4                           | WearableBackpacks-1.12.2-3.1.4.jar             | None                                     |
	| LCH   | ladylib                                      | 2.1                             | Ladylib-2.1.jar                                | None                                     |
	| LCH   | lumen                                        | 0.4.0                           | lumen-Beta 0.4.1.jar                           | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  pw.prok.realbench.asm.RBTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MovingWorldCore (movingworld-1.12-6.353-full.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
FutureMC (future-mc-1.12.2-0.2.6.1.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.9171' Renderer: 'Intel(R) HD Graphics 620'
	Patchouli open book context: n/a
	Launched Version: forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 620 GL version 4.6.0 - Build 27.20.100.9171, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 1.6 Feathery Dragons - Dragon Mounts 2
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 27.20.100.9171
	OpenGlRenderer: Intel(R) HD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by PlummetStudios** [comment]
1.12 is not a supported version anymore.
