### ISSUE TITLE
Ice and Fire mod banners are bugged [2.1.9.]

### ISSUE THREAD

**Issue by Tryhardion** [Alex-the-666/Ice_and_Fire#4199]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
So I returned to the old world with Ice and Fire, and found out that all my banners are bugged, only showing with pink line at the bottom. Also when creating a new banner, there appears to be the same bug. There are several more mods I am playing with but this bug happened only after I updated Ice and Fire to the newest version. Also submiting a screenshot with my mods.
![Mods](https://user-images.githubusercontent.com/90267425/132365052-6043cb5a-ebec-498c-8693-287c8fa04d86.png)

**Expected behavior**
Creating a banner with Ice and Fire pattern should create banner with that pattern.

**Comment by ZacattackG** [comment]
I hate to comment this in 2023 but what mod could be causing this cause I am running a premade mod pack the pack is world of dragons 2

**Comment by ZacattackG** [comment]
nvm updated the mod fixed it
