### ISSUE TITLE
1.17.1 update 

### ISSUE THREAD

**Issue by CoDrie** [Alex-the-666/Ice_and_Fire#4201]
Hey team,

when will your awesome mod become an update to work with 1.17.1?

Feature-request:
selected mobs/creature, for example: only pixies
Could this be possible?

**Comment by FlameyFaucet** [comment]
Regarding 1.17, from the dev in the I&F discord:
_"iaf and all my mods require mixin support with 1.17 doesnt have yet, and supposedly wont for at least a few weeks"_
_"it all depends on how difficult porting the mod will be. and i wont truly know that until after im able to port the mod, which depends on the release of the mixin support"_

In short, there is no exact ETA and it depends on Forge's pace. Best to sit and wait.
