### ISSUE TITLE
Mod fails to load correctly 

### ISSUE THREAD

**Issue by MaxiYann** [Alex-the-666/Ice_and_Fire#4205]
[crash-2021-09-11_13.42.50-fml.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/7147748/crash-2021-09-11_13.42.50-fml.txt)
[crash-2021-09-11_13.53.26-fml.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/7147749/crash-2021-09-11_13.53.26-fml.txt)
[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/7147750/latest.log)

**Comment by TheBv** [comment]
Update forge version
