### ISSUE TITLE
NO SPAWN [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by AbrysVwroc** [Alex-the-666/Ice_and_Fire#4209]
Any mob from mod, dont spawn for me on version 1.16.5.... what can i do?? (if that problem was reported, so sorry <3 )

**Comment by Culyto** [comment]
I also have this problem, could you solve it?

**Comment by AbrysVwroc** [comment]
i read on internet: 1000 blocks safe zone, i check that... If u go 1000
blocks, u'll encounter mobs... But dragons/seeserpents are veeeery rare. I
hope that helps u somehow 😉

pon., 13 wrz 2021, 19:52 użytkownik Culyto ***@***.***>
napisał:

**Comment by Culyto** [comment]
So I have to explore half the world to find dragons? is there an option for dragons to appear more often?

**Comment by AbrysVwroc** [comment]
I dont find any info about that, i have "mod menu" also... But there is no
config

pon., 13 wrz 2021, 20:54 użytkownik Culyto ***@***.***>
napisał:

**Comment by Culyto** [comment]
THANKS! :3

**Comment by Samlegamer** [comment]
can you give the mods you use?

**Comment by Culyto** [comment]
I was just using the Ice and Fire
