### ISSUE TITLE
Structures Don't Respect Dimension Whitelist [2.1.9-1.16.5]

### ISSUE THREAD

**Issue by Sindusk** [Alex-the-666/Ice_and_Fire#4210]
**Describe the bug**
Structures spawn in the overworld even when configuration is set to whitelist structures to only spawn in other dimensions.

**To Reproduce**
1. Use [Lost Cities](https://www.curseforge.com/minecraft/mc-mods/the-lost-cities) mod (or any mod that adds another dimension).
2. Set the configuration as follows:
```
[Generation]

	[Generation.Dimensions]
		#True if using blacklists, false if using whitelists for dragons and structure gen.
		"Use Dimension Blacklist" = false
		#Whitelist dragon gen dimensions. Use the format like "minecraft:the_nether" or "rats:ratlantis" 
		whitelistDimensionsDragons = ["lostcities:lostcity"]
		#Whitelisted feature(cyclops caves, hydra dens, etc) gen dimensions. Use the format like "minecraft:the_nether" or "rats:ratlantis" 
		whitelistDimensionsFeature = ["lostcities:lostcity"]
		#Whitelist mob spawn (troll, hippogryph, etc) dimensions. Use the format like "minecraft:the_nether" or "rats:ratlantis" 
		whitelistDimensionsMobs = ["lostcities:lostcity"]
```
3. Graveyards and mausoleums continue to spawn in the overworld.

**Expected behavior**
The graveyards and mausoleums should only be spawning in the configured dimension for "whitelistDimensionsFeature".

**Screenshots**
![image](https://user-images.githubusercontent.com/3503367/133216849-0e3d357a-e86e-4bd9-9bcc-c795932aef10.png)

**Additional context**
If the graveyards and mausoleums are not considered "features" for the purposes of dimension whitelisting, then a new configuration option should be added to give better control over how they are generated.

**Comment by Korocota** [comment]
In my own tests, id say nothing is getting respected on spawn rules overall.

**Comment by TheBv** [comment]
It looks like structures such as the mausoleums, graveyards and temples aren't currently affected by the whitelist/blacklist options.
You can however still configure them individually by changing the X_biomes.json files. It's a bit more of a tedious to do this it should however work.
One should probably think about if this whitelist/blacklist system should still be kept since it is somewhat redundant, although it is way easier/faster to configure.
