### ISSUE TITLE
Dragon is no Breeding

### ISSUE THREAD

**Issue by SummerToast** [Alex-the-666/Ice_and_Fire#4212]
**NO SUGGESTIONS AT ALL**
Issue

**Describe the bug**
When im trying to breed my dragons{Fire dragon} it doenst lay eggs

**To Reproduce**
3. See error

**Expected behavior**
Idk egg a

**Screenshots**
https://media.discordapp.net/attachments/884287476494131266/887886180924944384/unknown.png

**Additional context**

**Comment by FlameyFaucet** [comment]
Please do the following:
Make sure the dragons are male and female each. Check this by sneak + right clicking them.
Make sure you are using the right mixture. Fire dragons need the fire lily one.
Confirm that you are not trying to breed two different types together.

**Comment by SummerToast** [comment]
> one

Well i did...

**Comment by FlameyFaucet** [comment]
Wha- you fed them one only? You need two, that's the golden rule of mob breeding >.>
