### ISSUE TITLE
Unable to open dragon inventory or fly dragon, etc [1.9.1-1.12.2]

### ISSUE THREAD

**Issue by PresidentCthulhu** [Alex-the-666/Ice_and_Fire#4220]
**Describe the bug**
This is on the R.A.D. (Roguelike Adventures and Dungeons) mod pack. 1.12.2

After mounting the dragon, holding space goes through the flight animation start but never gets off the ground.
I am also unable to bite by pressing g, or use my breath by holding r.
When shift+right clicking the dragon with an open hand, I am unable to open the dragon's inventory

**To Reproduce**
1. No idea.
2. Started randomly.
3. Keeps happening.

**Expected behavior**
I expected the key binds, etc to work like they have for the whole time I've been playing this mod pack.
i.e. I expect holding space to fly, holding r to use breath, pressing g to bite, and open hand shift+right click to open inventory.

**Additional context**
I made an inventory pet shortly before this started happening and I found an old post saying inventory pets causes this problem.
However, that post is closed as if it is fixed.

This is also on a multiplayer server so removing Inventory Pets as a mod is not an option at the moment.

**Comment by FlameyFaucet** [comment]
1.12 is virtually unsupported. Try:
Checking if there are conflicting keybinds
Removing Inventory Pets when possible and testing if the issue goes away
Testing on a singleplayer server
Checking the mod version and updating to the latest for your MC version.

If none of the above work, it was likely fixed in a later version that isn't 1.12.

**Comment by PresidentCthulhu** [comment]
Found that the issue was the R.A.D. mod pack.
For some reason the mod pack creator used the literal newest version of Inventory Pets instead of the newest version for 1.12.2 of Minecraft.
After having the server owner download the appropriate mod version and replacing the previous version, everything works like a charm.
