### ISSUE TITLE
Dragon strike your way through a raid doesn't register the player finishing a raid [ICE AND FIRE VERSION 2.1.9]

### ISSUE THREAD

**Issue by warning-djkajslh** [Alex-the-666/Ice_and_Fire#4224]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Despite the player spamming the action button on a dragon, the kill isn't registered and no effect is rewarded.
You must atleast kill one raiders for it to be registered

**To Reproduce**
1. get a tamed dragon
2. start a raid
3. go to creative, get on the dragon and just bite your way through all the waves
4. see result as the last wave is cleared
Optional: Kill a raider with a sword and compare the result

**Expected behavior**
The effect and advancement will be given to the player despite he is using his dragon to clear through the waves.

**Screenshots**

**Additional context**

**Comment by TheBv** [comment]
This should've partially been adressed with 3c52775
