### ISSUE TITLE
Tide Trident Issue[2.1.9][Compatibility with Dungeons Mobs]

### ISSUE THREAD

**Issue by AlanightCreeper** [Alex-the-666/Ice_and_Fire#4226]
Dungeons Mobs version: 1.16.5-1.0.10
Ice and Fire version: 2.1.9

Description:
When I threw a tide trident and picked up it, it would transform into a vanllia trident if Dungeons Mobs is installed. 

To Reproduce:
Please watch the video.

https://user-images.githubusercontent.com/82942121/134770001-13765c73-ee07-43eb-8b8c-1a30be9ca0c5.mp4

**Comment by Nebula240** [comment]
Bump to this issue as it happens on The Cube Reborn modpack, featuring those two mods
