### ISSUE TITLE
Issue adding to dev environment [2.1.9-1.16.5]

### ISSUE THREAD

**Issue by chris-wjn** [Alex-the-666/Ice_and_Fire#4227]
Added the specified version to dev environment. When running the test client, it throws an error stating duplicate getScale() method in EntityDeathworm. Checked the file and indeed there are two methods named getScale() that are identical.

1. Add IAF version 2.1.9-1.16.5, and citadel version 1.8.1-1.16.5 to dev environment
2. reload gradle project
3. run test client

**Expected behavior**
test clients boots normally

**Comment by JaisDK** [comment]
[crash-2021-12-21_17.34.04-fml.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/7756420/crash-2021-12-21_17.34.04-fml.txt)
