### ISSUE TITLE
Sea serpent suddenly without texture [2.1.9]

### ISSUE THREAD

**Issue by Quakisrial** [Alex-the-666/Ice_and_Fire#4229]
So I was playing in modpack called mineshaft % monsters, everything was good, sea serpents were fine, with no problem, but suddenly, while I was adventuring I see two sea serpents chasing me, and both had no texture, the pink and black texture. I was in a cold ocean biome but I don't think that affects it as in the beginning there were sea serpents with texture.

**To Reproduce**
Steps to reproduce the behaviour:
I don't know if I did something, I did not touch anything about the config files, everything was fine at the beginning.

I expected to be chase by a beautiful sea serpent with colours.

![2021-09-26_17 04 02](https://user-images.githubusercontent.com/91437703/134826034-541e4d00-9905-47c1-a279-850f2c61bd38.png)

Those things with pink and black textures are sea serpents. Additionally, they move like a vertical thing but once they jump the animation happens.

**Comment by FlameyFaucet** [comment]
Test this with just Ice and Fire alongside Citadel. If it does not happen there, it is a pack issue, which i suggest you report to the pack developers.
If it does happen regardless, are you using Optifine?
