### ISSUE TITLE
Cannot capture pixies in jars on a dedicated server

### ISSUE THREAD

**Issue by Not-February** [Alex-the-666/Ice_and_Fire#423]
MC version 1.12.2
Ice and Fire 1.3.1

It seems to function properly in single player in both creative and survival modes, but right clicking a pixie with a jar on my dedicated survival server does nothing. The jar is not consumed, and the pixie does not turn into a pixie jar item. I tried with and without an offhand item, and at different distances from just within reach to almost touching the fairy. Nothing.

I don't get any errors in the log on either server or client when I attempt it on said server, so I have no extra information to provide.

**Comment by AlexModGuy** [comment]
fixed in 1.5.0
