### ISSUE TITLE
Death Worms Not Swimming [Ice and Fire 2.1.8-1.16.5]

### ISSUE THREAD

**Issue by AetheriMC** [Alex-the-666/Ice_and_Fire#4230]
Death worms on our server do not swim through sand as intended. The AI for the worms is otherwise working, as they will still chase prey, leap and attack, but they do so without ever retreating below the surface.

**Steps to reproduce the behavior:**
I'm not quite sure that this issue is strictly "reproduceable", other than it is a constant feature of our server, no matter if we restart or not.

**Expected behavior**
The worms should be swimming through sand and throwing blocks.

**Screenshots**
![Death Worm](https://user-images.githubusercontent.com/64112227/135525730-edefc564-9cdb-4028-9dc3-e97700dec1a6.jpg)

**Additional context**
This is a list of mods we use. I'm not sure which if any of these could have a direct impact here, but so far we've had no other issues with Ice and Fire mobs. 

[mods.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/7262347/mods.txt)

**Comment by Korocota** [comment]
Funnily enough, I did find myself fixing this by pure chance today.

Our server runs some AI improvement / simplifier mods, and the death worms being immobile one was due to the mod "Performant".

If you happen to use it, we did the following edits to the cfg file:

["Entity settings"]
fastCollisions = false
fastPathFinding = false

**Comment by FlameyFaucet** [comment]
performant: the most mod unfriendly mod ever:tm:

**Comment by Korocota** [comment]
> performant: the most mod unfriendly mod ever™️

I mean, these mods do what they promise, but should work only on vanilla entities and add modular support for popular/requested mods, because stuff like this can happen.

**Comment by AetheriMC** [comment]
@korocota Making the suggested changes to performant worked! Thank you so much for that bit of advice. Filtering through all of the mods to find out conflicting settings is such a pain.
