### ISSUE TITLE
Lightning Dragon Issues (Mode/Dragonforge/Animations) [2.1.9]

### ISSUE THREAD

**Issue by MrNoe93** [Alex-the-666/Ice_and_Fire#4231]
I am having various issues with lightning dragons that I am not having with fire/ice dragons:

- When changing lightning dragons from staying to escort, their status doesnt update until mounting the dragon.  
- Lightning dragons wont wander, when put in wander mode they sit as if in stay mode.  
- Lightning dragons will only power the dragonforge while I am riding them or when escorting, but wont in stay or wander mode.  
- If a lightning dragon is powering the dragonforge and I fly away, the dragon plays the breathing animation forever.

Tried on 1.16.5 with Forge 36.2.0, with only Ice and Fire 2.1.9 and JEI.

**Comment by FlameyFaucet** [comment]
Just a bunch of silly confirmations;
Lightning dragons sleep during the day. If these ‘issues’ are occurring during daytime, it’s because they sleep and refuse to do anything else, but they’re forcefully waken when you mount them.

And the last issue, they are meant to breathe on the forge forever. Not sure when they stop as i never used forges for that long, but i figure they only stop when they sleep or the forge runs out of blood or iron.

**Comment by MrNoe93** [comment]
You are absolutely correct about the modes and the using of the dragonforge, all that works just fine at night, I assumed they were all the same dumbly.  Them playing the animation forever does seem to be an issue even at night.  If they are breathing on the forge and then you ride them away, they just keep playing that animation without the breath.

**Comment by FlameyFaucet** [comment]
Huh, that might be a problem.

**Comment by kmwalker02** [comment]
Something else that can only be attributed to lightning dragons in my experience is that when they roar and put out their wings, some of the textures on said wings glitch out.

![here](https://user-images.githubusercontent.com/91921979/135936407-c8936595-daf2-487c-a111-e90169a4ab7e.png)
c

![here2](https://user-images.githubusercontent.com/91921979/135936506-e1294d39-e53f-4cfd-ac9c-96f3361febdb.png)
e

**Comment by Robomnz** [comment]
im having the same issue at night as this issue: Lightning dragons will only power the dragonforge while I am riding them or when escorting, but wont in stay or wander mode. they dont even blast at it even when its night time

**Comment by DigitalWendigo** [comment]
Lightning dragons work as intended, in every way, in the current dev build. 
The animations work as intended. 
The forge is being fueled and they are facing the right way when fueling it. 
Tested with every single dragon element and color in both a vanilla environment and a modded one (which included rubidium/performant and optifine/performant variants.)
