### ISSUE TITLE
Crash when i hit Sirens and randomly

### ISSUE THREAD

**Issue by NxarkNxark** [Alex-the-666/Ice_and_Fire#4232]
**Describe the bug**
I have 2 problems, the first is when i hit sirens and when i open some chests in dragon nests my game totally crash, and the second one, wich i'm not sure if the problem is form Ice and Fire or not is my server randomly crashes a lots of times and it could be Ice and Fire, here's the logs of Aternos (wich is the site that i use for my server) https://mclo.gs/q3ruu6w

**To Reproduce**
I don't really know, it's vers random

[tl-logger5266592120624617197.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/7288502/tl-logger5266592120624617197.txt)

**Comment by FlameyFaucet** [comment]
_Budschie's Morph Mod_ appears to be the problem here. remove it and test if the issue goes away.

**Comment by NxarkNxark** [comment]
That was the problem, thanks !
