### ISSUE TITLE
My Dragon Disappeared 

### ISSUE THREAD

**Issue by NxarkNxark** [Alex-the-666/Ice_and_Fire#4234]
**Describe the bug**
I was riding my lightning dragon stage 3 and it just disappeared, i can't bring him back with the summoning 
crystal and i don't have him in my horn, i don't know what happened and there was no reason for this to happen so, can someone help me ?

![image_2021-10-07_100132](https://user-images.githubusercontent.com/91837775/136353699-e19ac7e7-e66c-47ce-82ea-676fcdfc41f2.png)

**Comment by FlameyFaucet** [comment]
Mod version?

**Comment by NxarkNxark** [comment]
2.1.9

**Comment by TheBv** [comment]
Closing in favor of #3870
