### ISSUE TITLE
Crash when destroying a pixie's home

### ISSUE THREAD

**Issue by Sunconure11** [Alex-the-666/Ice_and_Fire#424]
https://pastebin.com/KCraKBq2

**Comment by Mewtwoy** [comment]
Can confirm on latest version, on my end it happened when a dragon fireball exploded near a pixie village.
Also crash report is similar: https://pastebin.com/6C7BnewR

The solution for me is to disable pixie village generation in the config files, atleast until the author fixes this.

**Comment by ncaycedo** [comment]
Not sure if I should open a new issue. From what I can see it's somehow related. I get the crash sometimes when I use the Ender Book from Cyclic to teleport to my base, where I use some pixie houses for decoration. It does not happen every time, but certainly most of the times.

https://pastebin.com/BRcP3nZJ

**Comment by AlexModGuy** [comment]
fixed
