### ISSUE TITLE
Enhancement: Dragon caves which have big openings on the surface

### ISSUE THREAD

**Issue by Mr-Syntax** [Alex-the-666/Ice_and_Fire#4240]
Under ground dragons is a good idea, but imageine if you came across a large opening in a cliff side with a little gold pile here and there, it then leads you all the way down to the dragon from there, this would really improve immersion.

**Comment by FlameyFaucet** [comment]
Great suggestion :O
Though...this is the repository for bugs-
Put suggestions here! https://github.com/Alex-the-666/Ice-and-Fire-Suggestions/issues
