### ISSUE TITLE
Ice and Fire (iceandfire) has failed to load correctly

### ISSUE THREAD

**Issue by fitzys** [Alex-the-666/Ice_and_Fire#4242]
**Mod loading error has occurred**
Trying to install mod for dragon obsessed daughter. Have installed both iceandfire and citadel.
Wasn't sure of what version of forge to install.
Not sure what I've missed.

**Screenshots**
[crash-2021-10-13_13.35.54-fml.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/7334369/crash-2021-10-13_13.35.54-fml.txt)

**Additional context**
Exception message: java.lang.ClassNotFoundException: net.minecraftforge.event.entity.EntityAttributeCreationEvent

**Comment by FlameyFaucet** [comment]
You are using 1.16.3 with Forge 34.1
Please install Forge 36.2.8 or 36.2.4 for 1.16.5.
