### ISSUE TITLE
Ice Dragon Ice-Breath-Balls [1.16.5]

### ISSUE THREAD

**Issue by BDippy** [Alex-the-666/Ice_and_Fire#4243]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
The issue is rare, and I'm not sure if the Developers are able to fix it, however the server I host on already said they cannot because of how the mod is set up. I play on version 1.16.5, and I use Apex Hosting as my server. I run a private, small server with a few mods (mainly Ice and Fire) for friends to play on- however we have a huge problem.

Ice dragons are something most of us adore, but they always seem to crash the entire server (which starts back up), and delete nearby entities. We've lost multiple dragons, and other friendly creatures due to this. We figured out what the problem is, an entity ticking issue. The specific entity is the ball of ice that shoots out whenever an ice dragon breathes their Ice Breath. That is whats causing the server to crash, and entities to be deleted. 

The server providers said there is no way to disable only the ice-ball, and instead we'd have to remove the spawn of ice dragons entirely. We want to know if there's any possible way to remove just the ice-ball, or even ice breath.

**Comment by TheBv** [comment]
Is there any chance you can provide the log files from the server (specifically the latest.log) ?
Without it it's a bit difficult to troubleshoot this issue at all.
One can of course work on a feature to remove individual attacks but it'd possibly be more efficient to just fix this issue :)

**Comment by BDippy** [comment]
If I'm honest, I have no idea how to provide the log files. This is my first time using GITHUB so it's a bit difficult to me- if you'd like my discord is B_Dip#3704, that would be easier for me but we can continue here.

**Comment by FlameyFaucet** [comment]
Go to .minecraft/logs and then go to the bottom. Post the latest.log, but if you launched the game again after the error, pick the file above the latest.
Also, paste it into a site like pastebin and provide the link so we don’t drown in text.

**Comment by BDippy** [comment]
[Latest File Ice-Breath Ball Glitch.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/7342001/Latest.File.Ice-Breath.Ball.Glitch.txt)

There! I think I did it

**Comment by FlameyFaucet** [comment]
Oh god. That is definitely not the log, all of it is jumbled text and symbols. Most likely still obfuscated for whatever reason. (Logs really should not be obfuscated either way.)
If you’re still confused on how to get the log, the server host should have a tutorial on that. Otherwise, the definitive path is:
.minecraft\logs\latest.log
If you don’t want to bother looking through the files above the latest for the log just reproduce the issue and then grab the latest.

**Comment by answering-mechine** [comment]
what's your ice and fire version and citadel version, because in the latest update of ice and fire and the newest 1.16.5 citadel fixed this issue

**Comment by BDippy** [comment]
I think I got it now! 

[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/7358260/latest.log)

Also my Ice and Fire version is 1.16.5, so is Citadel.

**Comment by TheBv** [comment]
Make sure your citadel version is version [1.8.1](https://www.curseforge.com/minecraft/mc-mods/citadel/files/3441028). That should fix it :)

**Comment by BDippy** [comment]
Thank you!
