### ISSUE TITLE
Ingots cannot be pumped out of Dragonforge  [2.1.9]

### ISSUE THREAD

**Issue by ElizaYamamoto** [Alex-the-666/Ice_and_Fire#4246]
Ingots made in a dragonforge cannot be pumped out of the forge via pipes or hoppers. They will pull out the dragonblood and iron instead. 

**To Reproduce**
1: Attatch any pipe from a mod or a hopper to a dragonforge
2: The items used to make the ingots will be taken out but the ingots in the results slot will never be taken out. 

**Expected behavior**
Completed Dragonsteel ingots should be taken out of the forge and not the resources for it.

**Comment by TheBv** [comment]
You can only pump out items from the bottom. Basically works the same as a furnace.
