### ISSUE TITLE
ice and fire Scribe crash

### ISSUE THREAD

**Issue by tudoran2007** [Alex-the-666/Ice_and_Fire#4248]
Hi!
I have a server with your mod installed and it crashes pretty frequently with this error: https://mclo.gs/0cZoPsV
I traced the bug to ice and fire due to the Scribe profession, but dont find anything in the config to help me, for example mabye disabling the scribe.
Thanks in advance

**Comment by TheBv** [comment]
I won't delve into bukkit related mod issues.
