### ISSUE TITLE
Mod changing mc menu *help not bug*

### ISSUE THREAD

**Issue by MajiCoder** [Alex-the-666/Ice_and_Fire#4249]
This isn't a bug at all, everything in the mod is working perfectly, but I'd like to take out the part of the mod that changes the Minecraft main menu. I've gotten other mods, like the Abyss 2, to not change the mc menu, but I can't get it with this mod. Any help?

**Comment by FlameyFaucet** [comment]
change the config in “iceandfire-client”, which is located inside the config folder of your .minecraft directory
