### ISSUE TITLE
Game will not load ice and fire vr 1.9.1

### ISSUE THREAD

**Issue by RohailJ** [Alex-the-666/Ice_and_Fire#4258]
When I start up my Minecraft game with and fire the game will not load and it comes up with exit code 0, anyone know why?
Here are also the list of mods:
![image_2021-10-25_201029](https://user-images.githubusercontent.com/93123451/138668272-261085a8-7728-4de2-9c5e-5067d0f11f44.png)

**Comment by Chancho91** [comment]
Maybe because your running MC 1.12.2, a severely outdated version. Just saying.
