### ISSUE TITLE
Failing to start the game [ICE AND FIRE VERSION 2.19]

### ISSUE THREAD

**Issue by LunaGoodwitch** [Alex-the-666/Ice_and_Fire#4260]
When I load up minecraft, it says Ice and Fire has failed to load correctly.

![Capture](https://user-images.githubusercontent.com/93204781/138894239-7bcaeea8-473e-4484-b2ae-1f2a0f1e897d.PNG)
These are the mods I am using.

**Comment by MinionMikel15** [comment]
same but im using just the two mods needed

**Comment by Kindnss** [comment]
I have the same problem but it says "java.lang.Defclassnotfound" or something like that.
Can anyone help me?

Edit: After reinstralling everything it worked :)

**Comment by jkwphysics** [comment]
Also having this on the server -some array out of bounds exception during initialization. It's intermittent.
