### ISSUE TITLE
Ticking Entity crash fighting Hydra [2.1.9]

### ISSUE THREAD

**Issue by MarioSMB** [Alex-the-666/Ice_and_Fire#4262]
**Describe the bug**
Server randomly crashed fighting the Hydra, the error is Ticking Entity. Crash log attached below.

**Additional context**
[crash-2021-10-27_17.43.27-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/7429413/crash-2021-10-27_17.43.27-server.txt)

**Comment by Kushagra-Srivastava** [comment]
Try uninstalling Java 15 and using JAVA 8
[DOWNLOAD FROM HERE](https://www.oracle.com/java/technologies/downloads/#java8)

Download the x64 or x86 package (whichever suits you). It should be ` tar.gz` package. Extract it. Paste it into the jdk folder. Google where the folder is according to your OS.  You will need SUDO permission.

See if this solution helps. And use only ONE JAVA BUILD if possible.
