### ISSUE TITLE
pose stack not empty [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by ventus1109** [Alex-the-666/Ice_and_Fire#4264]
When jumping and/or flying through other mods (like botania) when a dragon breath attack happens it crashes

**To Reproduce**
1. Fight a dragon,
2. Jump when attempting to do a crit attack
3. crash the game

[crash-2021-11-02_08.40.32-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/7457679/crash-2021-11-02_08.40.32-client.txt)

**Comment by Mr-Syntax** [comment]
i have the same error but thats when i try to mount a dragon
