### ISSUE TITLE
Crash when trying to mount a dragon

### ISSUE THREAD

**Issue by Mr-Syntax** [Alex-the-666/Ice_and_Fire#4265]
in this pack
https://www.curseforge.com/minecraft/modpacks/chosencraft-basic

when i try to mount a dragon it crashes instantly, ive tried turning automatic third person off but it doesent matter it still crashes :-/

its forge 36.2.0
with optifine g7
1.16.5
make up ultrafast shaders

[crash-2021-11-05_04.47.03-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/7480455/crash-2021-11-05_04.47.03-client.txt)
[crash-2021-11-05_04.42.12-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/7480457/crash-2021-11-05_04.42.12-client.txt)
[crash-2021-11-05_04.36.06-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/7480458/crash-2021-11-05_04.36.06-client.txt)

all three are from trying to mount a dragon

**Comment by Mr-Syntax** [comment]
i have inditified JEI integration as source of the crash i have no idea what the hell is going on but when i remove that mod it all works

**Comment by Mr-Syntax** [comment]
Ive also identified this mod to do the same that must be why there are different crash reports
https://www.curseforge.com/minecraft/mc-mods/little-critters

**Comment by AlexModGuy** [comment]
fixed
