### ISSUE TITLE
Chain links not working [iceandfire-2.1.9-1.16.5.jar]

### ISSUE THREAD

**Issue by mobslayer202** [Alex-the-666/Ice_and_Fire#4268]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Both Chain links do not work

**To Reproduce**
1. Get chain
2. Right click mob
3. See no effect

**Expected behavior**
The chain was supposed to behave like a lead

**Screenshots**

**Additional context**
I was playing 1.16.5 on a multiplayer server with atm6

**Comment by Nyoom-Monster** [comment]
I have been having that issue off and on, and when I try to disconnect my chains from walls, it doesn't work... I even tried to destroy the wall block.

**Comment by mobslayer202** [comment]
Mine doesn't even connect to walls

**Comment by Nyoom-Monster** [comment]
> Mine doesn't even connect to walls

Are you trying to use walls like cobblestone walls, or walls like full blocks. I made that stupid mistake before, and yea, don't do that lol.

**Comment by mobslayer202** [comment]
It didnt attach to mobs, didnt attach to non-full block walls. Haven't tried it recently though, is it fixed?

**Comment by AntoninRuan** [comment]
I am still having this issue as of today. I don't know if there is a fix or not if anyone know
