### ISSUE TITLE
Amphithere Health cannot be increased iceandfire-2.1.9-1.16.5.jar

### ISSUE THREAD

**Issue by Reshy** [Alex-the-666/Ice_and_Fire#4270]
**Describe the bug**

**To Reproduce**
Change the "Amphithere Max Health" value to a different number.

**Expected behavior**
Increasing or decreasing the maximum health value in the iceandfire config for the Amphithere should modify their health upon spawning.

Edit:  Tested, also occurs with other mobs, like Troll and Cyclops.

**Comment by TheBv** [comment]
Same as #4037
