### ISSUE TITLE
Something with entity ticking problem that crashes the game [1.16.5-0.2.0]

### ISSUE THREAD

**Issue by Spetroz** [Alex-the-666/Ice_and_Fire#4273]
Something in the ice and fire mod makes my game crash. It's something with dragons destroying blocks or smth. here is the crash report
[crash-2021-11-09_22.07.55-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/7508554/crash-2021-11-09_22.07.55-server.txt)

**Comment by Nyoom-Monster** [comment]
I'm having a similar problem where the game keeps freezing whilst riding my dragons. And, in general, my game has been freezing more often since taming an ice dragon with the creative mode dragon meal item.

**Comment by Spetroz** [comment]
Honestly, I did not find any fix to the problem. i just changed to another
version of the mod. playing a mod pack called create: above and beyond now
tho so don't have to worry about that.

Den lör 13 nov. 2021 kl 12:39 skrev Nyoom-Monster ***@***.***

**Comment by Nyoom-Monster** [comment]
No, I don't mean the mod or mod pack. I made my own pack. I'm talking about the item in Ice and Fire that you can only get in creative mode in Minecraft that tames wild dragons.

**Comment by TheBv** [comment]
This is an issue with the `ffxiimod`
