### ISSUE TITLE
Massive Animation Issues with Dragons and a few others; tested with no other mods installed [2.1.9]

### ISSUE THREAD

**Issue by Reshirou** [Alex-the-666/Ice_and_Fire#4277]
Okay actually I tested with ONLY Wyrmroost also installed too in the first two videos to see if it was all modded flying mounts or not, but these issues happen without it too

Major issues come from Dragons, all 3 types, with Medium issues in the others

Ambient Dragon Jitter
https://gfycat.com/onlyalarmedbarasinga

Dragon Neck Snapping and broken wings
https://gfycat.com/defensivelegitimatejerboa

Sea Serpent Bone Snapping
https://gfycat.com/tameglamorousamericancrayfish
(Serpents also seem to be missing some keyframes in a few animation transitions)

Amphithere Rubberband Turning
https://gfycat.com/relievedacademicanchovy
(rubberbanding animations also happen in Hippogryphs and Hippocampus)

**Comment by TheBv** [comment]
1 and 2 have now been resolved.
3 and 4 are still an issue.
Hippogryphs are also affected by 4 (see #4756)

**Comment by TheBv** [comment]
Have all been addressed in 1.18
