### ISSUE TITLE
My tamed ice and fire dragons are trying to kill each other [latest for 1.16.5 MC]

### ISSUE THREAD

**Issue by Nyoom-Monster** [Alex-the-666/Ice_and_Fire#4280]
**Describe the bug**
I have two tamed dragons (tamed with creative dragon meal). They both are trying to kill each other, in survival and creative, even when I use the dragon staff to try to make them stay still (which doesn't seem to be working), and when I use the dragon flute while they're fighting, they don't listen to it.

**To Reproduce**
1. Tame both an ice dragon and a fire dragon using the creative dragon meal item
2. Have both of them near each other
3. Watch them try to murder each other
4. The only things that stop it are mounting one of the dragons (which is really difficult when they're chasing each other, especially in survival), or right clicking them with the dragon horn item, which traps the dragons in their respective horn (like a PokeBall; this is also difficult when they're chasing each other)

**Expected behavior**
Having two tamed dragons of different species, tamed with the creative dragon meal item (I have not gotten any eggs so far so idk if this happens with naturally tamed dragons), would not be a problem because they belong to the same player, and would not want to kill each other.

**Additional context**
My dragons are stage 2-3, big enough to mount but not huge, both males.

**Comment by Ironeagle64** [comment]
I'm pretty sure this one is a feature, ice and fire dragons just hate each other no matter what

**Comment by Nyoom-Monster** [comment]
> I'm pretty sure this one is a feature, ice and fire dragons just hate each other no matter what

The tamed ones owned by one player are not supposed to kill each other, I checked.
