### ISSUE TITLE
SUGGESTION chests for dragon inventory [future?]

### ISSUE THREAD

**Issue by Nyoom-Monster** [Alex-the-666/Ice_and_Fire#4281]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the suggestion**
I would like it if the mod had the ability to add chests to the dragon's inventory, like with hippogriffs. This makes sense because they are HUGE. It would also be cool if we could have tiered options for storage, including ender chests and maybe an unlimited chest inventory (special chest variant) as a creative chest item. They could also be called saddle bags instead. And it would be cool if we could add multiple chests/bags to their inventory, the amount and tiers depending on the stage of the dragon.

The ability to craft a cage or something to put mobs in, then to put that on your dragon's back behind the player, would also be cool? But I'd assume this would reduce the chests that a dragon can hold/take up a chest slot entirely, and the number of cages you could add would also probably depend on the stage of the dragon. You could also have different strengths of cages, so they break/protect a mob better with stronger cages when in combat, so that it add risk to transporting mobs through the air earlier on. You could have wooden, bone, copper, silver, and dragonsteel cages.

Enchanted dragon armor would also be cool btw*

**Additional context**
The formatting for these issues implies that you can make suggestions if it's related to the gameplay, so I'm hoping this is allowed. If not, I apologize. I couldn't find any rules on here to give me a better idea.

If it's not allowed I would suggest having a place for suggestions to be posted? But that's only if the mod author wants.

Alternatively, I *could* try making an add-on mod for this one, to put in these suggestions, but I have never made a mod before, so I'm hesitant.

**Comment by Breadstickpotato** [comment]
1. Dragon storage 10/10, though maybe not so complex
          E.g. Larger dragons could hold more stuff.
2. Mob cages seem like a bit much for the main mod, but would
          definitely make for a great add-on.
3. Enchanted dragon armor 10/10 yes please.
4. Yeah where do you put suggestions?
