### ISSUE TITLE
Dread lich staff auto targets passive mobs, in all versions above 1.12.2

### ISSUE THREAD

**Issue by Jakeniclaz** [Alex-the-666/Ice_and_Fire#4282]
The dread lich staff seems to target non hostile mobs, in all versions above 1.12.2. It´s animation is also a little buggy, seeing as the skull it shoots has a missing texture from whichever angle you are looking at it, and from underneath. It, also doesn´t play the sound, it used to play on 1.12.2 , anymore.

Steps to reproduce behavior: 
Obtain a dread lich staff, either in survival mode or from the creative inventory, and use it near a passive or neutral mob.
This has to be done in versions above 1.12.2

**Comment by pbone64** [comment]
Adding on to this, it also targets other players - unsure if this is intended.
