### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION 1.12.2]

### ISSUE THREAD

**Issue by Cetoz8992** [Alex-the-666/Ice_and_Fire#4283]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Causing error code 0

**To Reproduce**
1. Let the mod exist in the mod folder
2. Click on launcher then run
3. See error

**Expected behavior**
"Error code 0"

**Screenshots**
Didn't take any.

**Additional context**

**Comment by PlummetStudios** [comment]
1.12 is not a supported version anymore.
