### ISSUE TITLE
Issue with Stone Statue Of Other Player

### ISSUE THREAD

**Issue by Promodzz** [Alex-the-666/Ice_and_Fire#4285]
Me and my friend went into a Gorgon temple, I proceeded to be killed by her then my friend killer her, I teleported back and tried to break my statue but did not have silk touch so it did not drop, my friend then gave me the gorgon head and I put my armor back on. I wanted to test it so my friend took his armor off and let me shoot him with it. As he was turned into a stone statue it was invisible but I could see a health bar because of the mod "neat". I proceeded to pick o up the statue with my silk touch pickaxe, then my packsack auto picked it up with my magnet upgrade. When I went to open the backpack I immediately crashed with the error message, too big of NBT Tag. I then tried to load back into the server and look in my backpack again. I crashed again but this time said something about byte size too big with a long number. After a tried a couple of times I gave it to my friend and he tried to open it and crashed as well. He then tried to put the backpack on the ground (sophisticated backpacks) and open it there. We also have keep inventory on.

**Comment by TheBv** [comment]
Fixed with #4136
