### ISSUE TITLE
Lightning Dragon Bug: Wings glitching

### ISSUE THREAD

**Issue by Pastastaar** [Alex-the-666/Ice_and_Fire#4286]
![image](https://user-images.githubusercontent.com/85465061/142300768-fb3031d2-07cf-4ebb-9891-7a0b40987827.png)
Howdy! In both multiplayer and singleplayer, dragon wings (mainly at the moment the lightning dragons as it is all we have seen) are bugging out like crazy as seen in the image.

**Comment by TheBv** [comment]
Will be fixed in the next release #4245
