### ISSUE TITLE
Not using vanilla .JSON system [2.1.9]

### ISSUE THREAD

**Issue by StrangerSon71** [Alex-the-666/Ice_and_Fire#4289]
**Describe the bug**
The .JSON system is not the vanilla one. This breaks compatibility with crafttweaker.

**Expected behavior**
Vanilla .JSON files.

**Comment by TheBv** [comment]
Ice and fire uses valid json files with 2 space indents.  There's nothing wrong with them.
Native CraftTweaker support was removed in 2.1.7
