### ISSUE TITLE
java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Boolean

### ISSUE THREAD

**Issue by XenoStone1009** [Alex-the-666/Ice_and_Fire#429]
Client crashes upon loading a Hippogryph.
Unsure if other mobs from mod do the same, this is the first instance seen.

Full Crashlog: https://hastebin.com/unopunivot.pas

**Comment by Sluggasaurus** [comment]
I've been dealing with this issue for a bit, removed the mod "recurrent complex" and now everything works without any crashes. the recurrent complex mod deals with structure generation. Hope this helps.

**Comment by AlexModGuy** [comment]
issue caused by primative mobs and similar mods
