### ISSUE TITLE
Tide Trident Loyalty returns basic trident [2.1.9]

### ISSUE THREAD

**Issue by CritLoren** [Alex-the-666/Ice_and_Fire#4290]
**Describe the bug**
The Tide Trident returns as a regular basic trident when enchanted with Loyalty

**To Reproduce**
1. Get Tide Trident
2. Enchant with Loyalty
3. Throw

**Expected behavior**
For the trident to return itself

**Additional context**
Playing on Better Minecraft Plus modpack, using version 2.1.9 of Ice and Fire

**Comment by littlepianist** [comment]
I also have the same issue
