### ISSUE TITLE
Invisible Ghouls iceandfire-2.1.9-1.16.5.jar

### ISSUE THREAD

**Issue by Reshy** [Alex-the-666/Ice_and_Fire#4293]
**Describe the bug**
There is a bug that causes Ghouls, when spawned from a spawner, to be invisible, snowing no model, mob information, flame particles, or hitboxes but still being able to strike you.

**To Reproduce**
Put a ghoul into a mob spawner, and spawned ghouls will be bugged.

**Expected behavior**
Ghouls should be visible.

**Screenshots**
![2021-11-23_10 49 24](https://user-images.githubusercontent.com/2096384/143086259-19b8511c-d09a-4424-b2ee-c3e71ebe71e5.png)
![2021-11-23_10 49 49](https://user-images.githubusercontent.com/2096384/143086352-47154b26-7ef1-4493-9980-7f6131e872c5.png)
![2021-11-23_10 50 06](https://user-images.githubusercontent.com/2096384/143086366-698d212a-a070-4dd7-b697-1fb3bec5d01f.png)

You can see in the screenshots the particles for a new mob spawn, but there's nothing shown.  Audibly you can hear them and be hurt by them.  Using a mod that sets nearby mobs on fire still damages and levitates them, but no flame particles are visible.  You can see the ghoul's drops floating around in the last screenshot.

My guess is it has something to do with the ghoul's emerging from the ground animation.  Here's the log if it helps:
[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/7590404/latest.log)

**Comment by TheBv** [comment]
Mob spawning works fine the default spawner. 
In the logs a mod you had installed was causing issues with dread spawners though. This has been addressed with 9cd2e43
