### ISSUE TITLE
Random Crash iceandfire-2.1.9-1.16.5.jar

### ISSUE THREAD

**Issue by Reshy** [Alex-the-666/Ice_and_Fire#4295]
**Describe the bug**
Crashed randomly after starting up world.

**To Reproduce**
Unknown

**Additional context**
[crash-2021-11-25_10.27.34-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/7604835/crash-2021-11-25_10.27.34-client.txt)
[crash-2021-11-25_10.54.54-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/7604910/crash-2021-11-25_10.54.54-server.txt)
[crash-2021-11-25_11.00.38-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/7604911/crash-2021-11-25_11.00.38-server.txt)

**Comment by TheBv** [comment]
Should be fixed with 9cd2e43
