### ISSUE TITLE
Why this crash appears without this mod installed ? I NEVER installed it !

### ISSUE THREAD

**Issue by Kasia1403** [Alex-the-666/Ice_and_Fire#4296]
[crash-2021-11-25_22.26.02-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/7608547/crash-2021-11-25_22.26.02-server.txt)

Chocolate Quest Repoured authors / developers don't want to help me !

**Comment by Tangosucka** [comment]
is this a serious post?   Your crash has nothing to do with this mod
