### ISSUE TITLE
Using a horn on your dragon causes it's armour texture to vanish untill right clicked on.

### ISSUE THREAD

**Issue by raptorfarian** [Alex-the-666/Ice_and_Fire#43]

**Comment by Dakotsie** [comment]
In addition to it disappearing, the 2 leftmost armor slots are bugged which results in the armor completely disappearing with no way to get the armor item back.

**Comment by Alex-the-666** [comment]
@Dakotsie i fixed that in one of the builds, but the armor not appearing on the dragon is still an issue.
