### ISSUE TITLE
Complete lack of any structure generation (and potentially mob spawn issues as well) [2.1.9]

### ISSUE THREAD

**Issue by Hookshark** [Alex-the-666/Ice_and_Fire#4301]
For context, I run and am part of a server that runs a pack from Curseforge called "All the Magic - Spellbound"
And no matter what or how I alter the settings I can't get any of the ice and fire caves, roosts, or skeletons to show up
I've even started a single player world with the spawn chance set to highest so it should generate a bunch, but nothing generates.

**To Reproduce**
1. Get the "All the Magic - Spellbound" Mod-pack from Curseforge
2. Run the pack and Alter config as needed *(Highest Spawn rate used for example in this reproduction)*
3. If it eases the solving of the problem, also add "Advanced Xray" mod to search for the ice and fire blocks used for the roosts and dens while exploring *(Charred Dirt, Charred Stone, Charred Cobble, etc)*
4. Start a single player world *(All settings left alone except changing to creative and allowing commands)*
5. Open the x-ray via hotkey and add the blocks to the menu so the X-ray will highlight the blocks
6. Use "/rtp" to random teleport out of the 1000 block radius where generation isn't permitted
7. While exploring around there will be zero generation of any Dens, Roosts, or Skeletons

**Expected behavior**
Proper generation of dragon roosts and dens as the X-ray would detect them when you fly overhead or near them

**Additional context**
There is also an issue of the only place I've managed to spot a mob from the mod is in the twilight forest, and it was the siren.
So, lack of mob spawns may be an issue as well

***Thanks for any aid in advance!***

**Comment by Hookshark** [comment]
To add to this, some of the other mods that add structures seem to fail to generate also.

**Comment by PallyK** [comment]
this should be sent over to the atm team as it might be in relation to the modpack rather than the mod itself. iirc atm6 moved many of the ice and fire features to a custom other dimension

**Comment by Hookshark** [comment]
That was indeed the issue, thanks! just had to place an allthemodium teleport pad in the nether to get to the dimension
