### ISSUE TITLE
No blood from Ice Dragons iceandfire-2.1.9-1.16.5.jar

### ISSUE THREAD

**Issue by Reshy** [Alex-the-666/Ice_and_Fire#4302]
**Describe the bug**
Harvesting an ice dragon with a bottle does not drop blood, unlike other dragons.

**To Reproduce**
Kill an ice dragon
Use the bottle on the dragon.

**Expected behavior**
Ice Dragon Blood should enter your inventory, rather than consuming the bottle and not giving the blood.

**Comment by DigitalWendigo** [comment]
Please provide a full list of your mods and a log file. 
I can not reproduce this issue in either 2.1.9 or the Alpha version.
