### ISSUE TITLE
Tamed dragons disappearing during flight [2.1.9-1.16.5]

### ISSUE THREAD

**Issue by notrealwoman** [Alex-the-666/Ice_and_Fire#4308]
Tamed dragons have been disappearing during flight; it's now happened 3 times to a Stage 5 male ice dragon, a Stage 4 female ice dragon, and another Stage 3 female ice dragon, all sapphire (if that makes any difference). While flying the mounted dragon it will just outright vanish, and the player falls from the air where the dragon was previously. There is no sign of the dragon in the air after this (as normally if you dismount your dragon, it will hover above). The dragons cannot be resummoned with bound crystals, and as far as I am aware they only disappear when in flight. I have also attempted to call the dragons with the dragon bone flute, to see if there is a chance they are just too far up for me to see. No luck on getting any of the 3 to return.

I have no idea what it is that causes this or how to potentially replicate the issue for testing, it happens at very obscure times, I was able to travel 16,000 blocks and back with one of the dragons before having this happen, another was able to grow fully to max Stage 5, it's very hard to gauge when it'll happen or if it'll happen at all.

Our server admin attempted to teleport the dragon(s) by name in creative mode, but was unable to do so, we figure it was as a result of our server restarting, but it was listed that there was no entity to teleport.

**Comment by DigitalWendigo** [comment]
What other mods are you using?
I had an issue with some performance mods a long while ago, where if a certain entity stops being rendered, it will outright be deleted.

**Comment by DigitalWendigo** [comment]
Please provide a full list of your mods and a log file. 
If this issue has been resolved for you or is no longer valid, then please confirm so this can get closed as I can not reproduce this on either 2.1.9 or the new alpha release.

**Comment by notrealwoman** [comment]
Just Enough Resources (JER)
Mushroom Quest
Hwyla
Thermal Cultivation
Nuclear Science
Small Ships
Allomancy
Pam's HarvestCraft 2 - Trees
Theurgy
Pam's HarvestCraft 2 - Food Extended
Thermal Foundation
Mekanism Additions
Mekanism
Frozen Up
Mekanism Generators
Mekanism Tools
CoFH Core
Thermal Expansion
Druidcraft
Blueprint
Simple Planes (Forge)
CC: Tweaked
Forbidden and Arcanus
Eidolon
YUNG's API (Forge)
Ensorcellation
Draconic Evolution
Autumnity
Ice and Fire: Dragons
Refined Storage
Chisel
Pigawatts Reloaded
Brandon's Core
Curios API (Forge)
Dungeon Crawl
ConnectedTexturesMod
Ore Excavation
Oh The Biomes You'll Go
YUNG's Better Caves (Forge)
Archer's Paradox
Industrial Foregoing
YUNG's Bridges (Forge)
Nature's Aura
Mantle
Corail Tombstone
Valhelsia Core
Biomes O' Plenty
Controlling
Mana and Artifice
Blood Magic
YUNG's Better Mineshafts
Cooking for Blockheads
LibX
Cat Jammies
Tiny Redstone
Thermal Locomotion
AppleSkin
LibVulpes
Environmental Tech
Advanced Rocketry
Fast Leaf Decay
Just Enough Items (JEI)
Iron Chests
Numina
Modular Powersuits
ValkyrieLib
Macaw's Windows
Patchouli
Thermal Innovation
Aquaculture 2
YUNG's Extras
YUNG's Better Dungeons
Macaw's Doors
Pam's HarvestCraft 2 - Crops
Macaw's Trapdoors
Alex's Mobs
Environmental Core
ObserverLib
Pam's HarvestCraft 2 - Food Core
Quantum Quarry Plus
YUNG's Better Strongholds
Titanium
Mouse Tweaks
Electrodynamics
Clumps
GeckoLib
Storage for ComputerCraft
Citadel
CodeChicken Lib 1.8.+
JourneyMap
Nature's Compass
Astral Sorcery
Mystical World
Ballistix
Tinkers Construct
Biomancy

It's been many many months since that incident, and I no longer possess the log files, I apologize. I am not the owner of the server, and he did not hold onto the log. The above modlist is from one of the custom modpacks the disappearing happened on there a few.
