### ISSUE TITLE
Incopatability with BetterBreeding Mod

### ISSUE THREAD

**Issue by Skylandy** [Alex-the-666/Ice_and_Fire#431]
Again, like I said on the suggestions, I'm a big fan of this mod. It's pretty much the main one I'm using on my first dedicated server.

I've encountered a few bugs/issues/whatever though. One is that I almost always take fall damage when dismounting a stage 4 and above dragon. Is this on purpose or will it be fixed at some point?

Another is that while sometimes the pixies drop items once you hit them whilst they are wild, they also don't. If you catch them in a jar, whatever they were holding seems to disappear too (may be wrong on this), is that intentional?

I've seen it mentioned, but I've also noticed an issue where dragons can pick players up through walls and sometimes hold them inside walls, suffocating them. This is probably because I have 2 on dragon griefing, to be honest.

Mostly, I've been having some real issues breeding both hippogryphs and dragons. I've tried to breed them (male and female respectively, both green stage 4 fire dragons) on wander (though this is kinda tough when they get to this size, lost a dragon this way cos I didn't have a flute with me) or staying/sitting but the dragons only seemed to breed once and not since, despite consuming the breeding food and showing a quick burst of hearts (if not for this, I'd have wondered if it was because I was breeding again too soon etc). The gryphons did not breed at all on my survival server, again showing hearts when fed. If it's something I'm doing wrong etc, please let me know!

I'm running the following mods (besides this and llibrary):
Crayfish Furniture, EasyBreeding, Optifine, Torocraft's Damage Indicators, and both Xaero map mods (client side), with PureBDcraft resource packs.

EDIT: (Thanks to Mewtwoy) EasyBreeding seems incompatible with mod, which is a shame. For the time being I've removed it from the server. Hopefully this'll be fixed at some point.

**Comment by Mewtwoy** [comment]
"I'm running the following mods (besides this and llibrary):
Crayfish Furniture, **EasyBreeding**, Optifine, Torocraft's Damage Indicators, and both Xaero map mods (client side), with PureBDcraft resource packs."

That might be your problem

**Comment by Skylandy** [comment]
It is supposed to only affect certain creatures, chickens, cows, sheep and pigs... but I'll give it a try when I get home.

**Comment by Skylandy** [comment]
Okay, I think the breeding is working now, but I along with others on the server are crashing upon death in the overworld (nether is fine). 

The game crashed whilst rendering block entity
Error: java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}

All I did was breed a hippogryph and dragon... and now this keeps happening. Any ideas?
*Edit, not together, but... well, you know. xD

**Comment by Mewtwoy** [comment]
ItemBlock#canPlaceBlockOnSide is (indirectly) calling BlockAir#setBlockBoundsBasedOnState, which expects the Block at the specified position to be an instance of BlockAir. This isn't the case, since ItemBlock#canPlaceBlockOnSide is called before the block is placed in the world.

Vanilla avoids this by using Air for the block form of air

If you dont understand, its a bug within the coding of whatever "block" or "entity" is supposed to appear after breeding the dragon, in this case you probably bred them near a wall or somewhere where the "block" can attach to the side.

This might just be speculation but who knows, i might be wrong too

**Comment by Skylandy** [comment]
It's as good a guess as any! Don't suppose you could suggest a fix? It could be one of the nest blocks or something.

**Comment by Skylandy** [comment]
Also, found that areas far away from base do not cause crash upon death. Gonna try to narrow the area down a little... but I can't see any nests etc at the moment... Must've removed them.

EDIT: Solved the crash, or at least the reason behind it. Gonna put as separate issue.

**Comment by AlexModGuy** [comment]
fixed crash
