### ISSUE TITLE
Class loading error 1.16.5

### ISSUE THREAD

**Issue by Eszesag77** [Alex-the-666/Ice_and_Fire#4311]
Hi,
I can't start the mod on 1.16.5, I only have the citadel and ice and fire mod in the mod folder and when I load this message shows.

![class loading error](https://user-images.githubusercontent.com/95963448/146085705-5e253158-3bf9-4c6d-8471-a7a1b60327ab.png)

I don't know what class loading error is. 

Any help appreciated, thank you very much!

[crash-2021-12-14_19.24.10-fml.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/7715009/crash-2021-12-14_19.24.10-fml.txt)

**Comment by TheBv** [comment]
I'm not certain if it's the issue but try downloading the 1.8.1 version of citadel that does not have the word `deobf` in it 
aka. this one https://www.curseforge.com/minecraft/mc-mods/citadel/download/3441028

**Comment by Eszesag77** [comment]
Thank you, I have no idea how it works but it does. Much appreciated!
