### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by GlanceIn** [Alex-the-666/Ice_and_Fire#4312]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Won't launch on any modpack I make. if I include the mod with other mods it will just render the game at 1 fps upon launch and i will be stuck in the mc home menu unable to click on anything

**To Reproduce**
1. Go to curse forge and include multiple mods with the ice and fire dragon mod in a mod pack
2. Click on play, then load into the game through the minecraft launcher
3. wait a minute before you are stuck on 1 fps

**Expected behavior**
I expected it to not run at 1 fps

**Screenshots**

**Additional context**
the random fact lines (or whatever they're called) in the top right of the mc home menu also start flashing, it flashes to different 2 different random facts every second and I thought it was unusually fast

**Comment by ghost** [comment]
This does not provide enough information, if at all could you show images logs crashes? anything in between?
