### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by olivermjmj** [Alex-the-666/Ice_and_Fire#4315]
I litterly can't find a single structure from Ice and Fire (i can find the ores) but 0 structures and 0 dragons (im using the newest version 2.1.9

**Comment by ElardHuaraca** [comment]
> I litterly can't find a single structure from Ice and Fire (i can find the ores) but 0 structures and 0 dragons (im using the newest version 2.1.9

I have the same problem in my case if the structures are generated but when trying to configure the iceandfire-common.toml the changes do not work as the most basic one that prevents dragons from breaking blocks.

**Comment by DigitalWendigo** [comment]
More information is needed. 
A full list of your mods and a log file. 
Furthermore if you are using a terrain altering mod then you can expect there to be issues. 
Namely mods that add biomes or remove vanilla ones by replacing them with their own will cause ice and fire structures/creatures to not generate propperly. 
In that case you will need to add the custom biomes to the ice and fire creatures/structures biome.json files manually.
