### ISSUE TITLE
Random Crash  [2.1.9-1.16.5]

### ISSUE THREAD

**Issue by Rversse** [Alex-the-666/Ice_and_Fire#4316]
**Describe the bug**
It happen twice. The game crash for no reason in the middle of the game. I just walk, running from Dragon, and the game crash randomly.

**Additional context**
Crash Log
[crash-2021-12-22_23.18.25-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/7763951/crash-2021-12-22_23.18.25-server.txt)

**Comment by DigitalWendigo** [comment]
By the looks of it this is a large modpack and I suggest you forward this to the modpack maker. 
Also try reproducing this issue without Flywheel.
The crash log also mentions forbidden_arcanus, so I suggest you try reproducing this without that mod as well. 

Probably unrelated to the issue, but I suggest you update your java version and forge.
