### ISSUE TITLE
Changing health or max health bug [2.1.9-1.16.5]

### ISSUE THREAD

**Issue by KentukySG** [Alex-the-666/Ice_and_Fire#4318]
Changing the health or max health of certain mobs, like cyclops and gorgon, won't show the changes in game after modifying the stats on config/iceandfire-common.toml.

Cyclop default health is 150, I changed to 1000 restarted the server and cyclop still have 150. Using version 2.1.7 fix this, but I want to use the most recent version at the moment, which is 2.1.9. Changing max health of dragons works fine in both versions, that's why I know is a bug only for the 2.1.9 and 2.1.8.

Gorgons health is 100, changing to any value won't change her health at all and it will stay 100.

Sea serpents when changing the health, spawns with only 1/3 of his max health. e.g Health 154/500 or 214/960.

not tested with other mobs.
I'm using the torohealth mod to see their health.

**Comment by DigitalWendigo** [comment]
Try adding the mod called AttributeFix and see if the issue still persists. 
The mod fixes a bunch of vanilla based issues with upper health limits, which prevent a lot of mods from functioning propperly.

**Comment by TheBv** [comment]
Same as #4037

**Comment by KentukySG** [comment]
> Try adding the mod called AttributeFix and see if the issue still persists. The mod fixes a bunch of vanilla based issues with upper health limits, which prevent a lot of mods from functioning propperly.

![serp](https://user-images.githubusercontent.com/96577858/171472178-d485e36b-357e-4f8c-8d8b-1e595a985cc5.png)
Nothing changed, even with a new save

**Comment by KentukySG** [comment]
![gorg](https://user-images.githubusercontent.com/96577858/171472816-1061128f-9ec5-47a1-9a50-3fe06e5d0975.png)
![gorg1](https://user-images.githubusercontent.com/96577858/171472827-c4b93eae-c1bc-40ea-8273-e55dcbf4f1d8.png)

**Comment by DigitalWendigo** [comment]
It's now been adressed in the current development builds. Once a full release for the final 1.16.5 update is aired on curseforge you'll be able to switch over to that and the issue will be fixed. For the time being you will unfortunately have to endure the bug. 
Of course you could use the development builds, but it is not recommended as they are still under development and may give raise to different game-breaking bugs. Especially on servers.
