### ISSUE TITLE
Fairy Houses Cause Crash Upon Death

### ISSUE THREAD

**Issue by Skylandy** [Alex-the-666/Ice_and_Fire#435]
I have narrowed down recent crashing to the presence of fairy houses.

Here is the crash error that occurs whenever someone dies within loading distance of a fairy house.

Error: java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}

At first I didn't know what was causing regular crashes around my base. I tried removing all recent changes and finally figured out it was the fairy houses. When they were place and I died next to them, my game would crash. I relogged and then removed them, dying in the same spot and I would respawn at the bed properly.

I tested each house I had with me, one at a time. The red mushroom pixie hovel, dark oak pixie hovel and normal oak pixie hovel all caused crashes. I haven't tried any others, but this seems to be all pixie hovels affected. To test to see if it was just because I'd moved the hovels, I went to a pixie village and died there. Same issue, same crash. Pretty sure it's a general thing with all hovels.

Pixies are adorable and their houses make great decorations, so please fix!

**Comment by AlexModGuy** [comment]
dupe issue
