### ISSUE TITLE
issue myrmex staff

### ISSUE THREAD

**Issue by Drago1809** [Alex-the-666/Ice_and_Fire#4351]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
when right click with desert myrmex staff game crash 

**To Reproduce**
1. take a desety myrmex staff 
2. right click
3. crash 

**Expected behavior**
normally choose a queen to subjet

sorry if i m weird it s my first time on github ...

**Comment by Nitrouni** [comment]
It happens to me too.

**Comment by TheBv** [comment]
Fixed with #4245
