### ISSUE TITLE
GAME CRASHES EVERYTIME I OPEN IT

### ISSUE THREAD

**Issue by cooldrip** [Alex-the-666/Ice_and_Fire#4354]
this is my crash report and i dont know what to do
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.3.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  McLib core mod (mclib-2.3.6-1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.69_mc1.12.2.jar)
  SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.4.0.jar)
  SoManyEnchantments ASM (SoManyEnchantments-0.5.5.jar)
  iceandfire (iceandfire-1.9.1-1.12.2 (1).jar)
  Quark Plugin (Quark-r1.6-179.jar)
  BlockbusterCore (blockbuster-2.3.4-1.12.2 (1).jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 1/2/22 3:33 AM
Description: Initializing game

java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/core/ModItems
	at com.chaosbuffalo.spartanfire.init.ItemRegistrySFire.<clinit>(ItemRegistrySFire.java:48)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_198_ItemRegistrySFire_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.github.alexthe666.iceandfire.core.ModItems
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.chaosbuffalo.spartanfire.init.ItemRegistrySFire.<clinit>(ItemRegistrySFire.java:48)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_198_ItemRegistrySFire_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 418413496 bytes (399 MB) / 1073741824 bytes (1024 MB) up to 7516192768 bytes (7168 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 67 mods loaded, 65 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version             | Source                                        | Signature                                |
	|:----- |:------------------ |:------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft          | 1.12.2              | minecraft.jar                                 | None                                     |
	| LCH   | mcp                | 9.42                | minecraft.jar                                 | None                                     |
	| LCH   | FML                | 8.0.99.99           | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge              | 14.23.5.2860        | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | creativecoredummy  | 1.0.0               | minecraft.jar                                 | None                                     |
	| LCH   | ivtoolkit          | 1.3.3-1.12          | minecraft.jar                                 | None                                     |
	| LCH   | rpghud             | 3.8.1               | [1.12][Forge]+RPG-HUD-3.8.1.jar               | None                                     |
	| LCH   | jei                | 4.16.1.301          | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| LCH   | appleskin          | 1.0.14              | AppleSkin-mc1.12-1.0.14.jar                   | None                                     |
	| LCH   | quark              | r1.6-179            | Quark-r1.6-179.jar                            | None                                     |
	| LCH   | autoreglib         | 1.3-32              | AutoRegLib-1.3-32.jar                         | None                                     |
	| LCH   | mmdlib             | 1.0.0-rc2           | MMDLib-1.12-1.0.0-rc2.36.jar                  | None                                     |
	| LCH   | basemetals         | 2.5.0-rc2           | BaseMetals-1.12-2.5.0-rc2.332.jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | battletowers       | 1.6.5               | BattleTowers-1.12.2.jar                       | None                                     |
	| LCH   | baubles            | 1.5.2               | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCH   | betteranimalsplus  | 8.2.0               | betteranimalsplus-1.12.2-8.2.0.jar            | None                                     |
	| LCH   | bettercaves        | 1.12.2              | bettercaves-1.12.2-2.0.1.jar                  | None                                     |
	| LCH   | bettercombatmod    | 1.5.6               | BetterCombat-1.12.2-1.5.6.jar                 | None                                     |
	| LCH   | bettermineshafts   | 1.12.2-2.2.1        | BetterMineshaftsForge-1.12.2-2.2.1.jar        | None                                     |
	| LCH   | biomesoplenty      | 7.0.1.2445          | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar | None                                     |
	| LCH   | mclib              | 2.3.6               | mclib-2.3.6-1.12.2.jar                        | None                                     |
	| LCH   | metamorph          | 1.2.12              | metamorph-1.2.12-1.12.2.jar                   | None                                     |
	| LCH   | blockbuster        | 2.3.4               | blockbuster-2.3.4-1.12.2 (1).jar              | None                                     |
	| LCH   | bountifulbaubles   | 0.0.1               | Bountiful+Baubles-1.12.2-0.1.6.jar            | None                                     |
	| LCH   | forgelin           | 1.8.3               | Forgelin-1.8.3.jar                            | None                                     |
	| LCH   | bountiful          | 2.2.2               | Bountiful-2.2.2.jar                           | None                                     |
	| LCH   | callablehorses     | 1.1.1               | callablehorses-1.12.2-1.1.1.jar               | None                                     |
	| LCH   | chunkanimator      | 1.2                 | ChunkAnimator-MC1.12-1.2.jar                  | None                                     |
	| LCH   | comforts           | 1.4.1.3             | comforts-1.12.2-1.4.1.3.jar                   | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCH   | corpse             | 1.12.2-1.0.8        | corpse-1.12.2-1.0.8.jar                       | None                                     |
	| LCH   | creativecore       | 1.10.0              | CreativeCore_v1.10.69_mc1.12.2.jar            | None                                     |
	| LCH   | dldungeonsjbg      | 1.14.10             | DoomlikeDungeons-1.14.10-MC1.12.2.jar         | None                                     |
	| LCH   | orelib             | 3.6.0.1             | OreLib-1.12.2-3.6.0.1.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dsurround          | 3.6.1.0             | DynamicSurroundings-1.12.2-3.6.1.0.jar        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | reccomplex         | 1.4.8.2             | RecurrentComplex-1.4.8.2.jar                  | None                                     |
	| LCH   | dynamictrees       | 1.12.2-0.9.26       | DynamicTrees-1.12.2-0.9.26.jar                | None                                     |
	| LCH   | dynamictreesbop    | 1.12.2-1.5.1        | DynamicTreesBOP-1.12.2-1.5.1.jar              | None                                     |
	| LCH   | dynamictreesquark  | 1.12.2-1.0.6        | DynamicTreesQuark-1.12.2-1.0.6.jar            | None                                     |
	| LCH   | enchdesc           | 1.1.15              | EnchantmentDescriptions-1.12.2-1.1.15.jar     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | enhancedvisuals    | 1.3.0               | EnhancedVisuals_v1.4.4_mc1.12.2.jar           | None                                     |
	| LCH   | foodexpansion      | 1.3                 | FoodExpansion1.3.3-1.12.2.jar                 | None                                     |
	| LCH   | grapplemod         | 1.12.2-v11.1        | grapplemod-v11.1-1.12.2.jar                   | None                                     |
	| LCH   | waila              | 1.8.26              | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| LCH   | llibrary           | 1.7.20              | llibrary-1.7.20-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | iceandfire         | 1.9.1               | iceandfire-1.9.1-1.12.2 (1).jar               | None                                     |
	| LCH   | infernalmobs       | 1.7.6               | InfernalMobs-1.12.2.jar                       | None                                     |
	| LCH   | journeymap         | 1.12.2-5.7.1        | journeymap-1.12.2-5.7.1.jar                   | None                                     |
	| LCH   | lycanitesmobs      | 2.0.8.4 - MC 1.12.2 | lycanitesmobs-1.12.2-2.0.8.4.jar              | None                                     |
	| LCH   | mobends            | 1.2.1               | MoBends_1.12.2-1.2.1-19.12.21.jar             | None                                     |
	| LCH   | mowziesmobs        | 1.5.8               | mowziesmobs-1.5.8.jar                         | None                                     |
	| LCH   | potioncore         | 1.9_for_1.12.2      | PotionCore-1.9_for_1.12.2.jar                 | None                                     |
	| LCH   | pvj                | 1.6.4               | ProjectVibrantJourneys-1.12.2-1.6.4.jar       | None                                     |
	| LCH   | qualitytools       | 1.0.7_for_1.12.2    | QualityTools-1.0.7_for_1.12.2.jar             | None                                     |
	| LCH   | roguelike          | 1.8.0               | RoguelikeDungeons-1.12.2-1.8.0.jar            | None                                     |
	| LCH   | ruins              | 17.2                | Ruins-1.12.2.jar                              | None                                     |
	| LCH   | savemystronghold   | 1.12.2-1.0.0        | savemystronghold-1.12.2-1.0.0.jar             | None                                     |
	| LCH   | somanyenchantments | 0.5.5               | SoManyEnchantments-0.5.5.jar                  | None                                     |
	| LCH   | spartanweaponry    | 1.4.0               | SpartanWeaponry-1.12.2-1.4.0.jar              | None                                     |
	| LCH   | spartanfire        | 0.07                | spartanfire-0.07.jar                          | None                                     |
	| LCH   | spartanshields     | 1.5.5               | SpartanShields-1.12.2-1.5.5.jar               | None                                     |
	| LCH   | switchbow          | 1.6.8               | switchbow-1.6.8.jar                           | None                                     |
	| LCH   | toolbelt           | 1.9.12              | ToolBelt-1.12.2-1.9.12.jar                    | None                                     |
	| LCH   | xat                | 0.31.3              | Trinkets+and+Baubles-0.31.3.jar               | None                                     |
	| LCH   | variedcommodities  | 1.12.2              | VariedCommodities_1.12.2-(06Dec21).jar        | None                                     |
	| LCH   | waystones          | 4.1.0               | Waystones_1.12.2-4.1.0.jar                    | None                                     |
	| UD    | blockbuster_core   | 2.3.4               | minecraft.jar                                 | None                                     |
	| UD    | mclib_core         | 2.3.6               | minecraft.jar                                 | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.3.jar)
  
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
McLib core mod (mclib-2.3.6-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
CreativePatchingLoader (CreativeCore_v1.10.69_mc1.12.2.jar)
  
SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.4.0.jar)
  
SoManyEnchantments ASM (SoManyEnchantments-0.5.5.jar)
  com.Shultrea.Rin.Transformer.SMEASM
iceandfire (iceandfire-1.9.1-1.12.2 (1).jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
BlockbusterCore (blockbuster-2.3.4-1.12.2 (1).jar)
  mchorse.blockbuster.core.BBCoreClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 497.29' Renderer: 'NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 497.29, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: mod_resources, vanilla, quark:emote_resources (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor 
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 9
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 497.29
	OpenGlRenderer: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by PlummetStudios** [comment]
1.12 is not a supported version anymore.
