### ISSUE TITLE
Can not tame hypogriff [2.1.9]

### ISSUE THREAD

**Issue by Ogondan** [Alex-the-666/Ice_and_Fire#4355]
Hypogriff gets bugged, it starts turning on itself and it does not attack me. I throw the rabbit paws and it does not take them, takes a loooot to get them and it takes for example one each 5 mins or kinda like that

**Comment by DigitalWendigo** [comment]
Not enough information. 
Please provide a full mod list and log file. 
I can not reproduce this. It works as intended.
