### ISSUE TITLE
Anyway in Getting the Dragon ring of its Original concept back in if I were to say Donate to get it added?

### ISSUE THREAD

**Issue by RagnarokBazil** [Alex-the-666/Ice_and_Fire#4359]
So like i made a suggestion of a dragon ring long ago.. And i wanted to know if i Donate say.. an amount to get the Original concept in.. Would it be possible? A dragon ring that turns the player into a pure dragon.. Fire ring, Turns the user into a Fire dragon stage 3, Frost ring, turns the player into a stage 3 Frost dragon.. and a Thunder ring that turns the player into a thunder dragon stage 3.. 

Like your own Morph mod... like Crazy craft used to have..  but its with the Fire and ice dragons.. 

Would that work at all? Donating to have that added in?

**Comment by lSherozl** [comment]
This is not the suggestions area, go to the suggestion github https://github.com/Alex-the-666/Ice-and-Fire-Suggestions/issues
