### ISSUE TITLE
[Suggestion] Stage 5 Dragon Attack

### ISSUE THREAD

**Issue by Aaron082001** [Alex-the-666/Ice_and_Fire#436]
When my dragon goes stage 5 its really hard to use dragon strike because the dragon is too big i cant hit a single pig while riding it.I want to suggest make the Stage 5 dragon had an area attack.For example, my dragon can attack many mob in single attack.Also i want to suggest to make the stage 5 dragon attack longer.

sry for bad english XD

**Comment by AlexModGuy** [comment]
please move this to a suggestions tracker; issues tracker is getting bogged down
