### ISSUE TITLE
Crash upon tesselating blocks [V-2.1.9]

### ISSUE THREAD

**Issue by N8rtot** [Alex-the-666/Ice_and_Fire#4360]
**Describe the bug**
The game crashes while "tesselating a block of frozen coblestone 

**To Reproduce**
Go into a single player world and wait for it to crash
![crash frozen cobblestone](https://user-images.githubusercontent.com/77558552/148246786-9f5dd526-06d1-4db7-83ad-560609fd5eb9.png)

**Comment by DigitalWendigo** [comment]
Please provide a full list of your mods and a full log file + crash log. 
There simply isn't enough information to provide any help. 
If this is no longer an issue, this should be closed.
