### ISSUE TITLE
White Screen Render Issue

### ISSUE THREAD

**Issue by Sakidoo** [Alex-the-666/Ice_and_Fire#4365]
**Describe the bug**
I can't tell if this bug is mod-related, but I thought I might just post it in case.

In the modpack MC Eternal Lite, I have a mob farm containing Ice and Fire Spawners (those out of the black boxes). Sometimes I get a white screen (no taskbar, no nothing), which sometimes does go away, but if it stayed for like 5 sec then it doesn't go away and I have to restart the game. Game doesn't crash by itself, Server does not have any exceptions during this, Input still works (When I open chat or my inventory a cursor gets displayed).

In the logs there is following exception over and over again:
`[12:02:23] [Client thread/ERROR] [net.minecraft.client.renderer.entity.RenderLivingBase]: Couldn't render entity
java.lang.ClassCastException: java.lang.Boolean incompatible with java.lang.Integer
	at com.github.alexthe666.iceandfire.entity.EntityDreadThrall.getArmorVariant(EntityDreadThrall.java:217) ~[EntityDreadThrall.class:?]
	at com.github.alexthe666.iceandfire.client.render.entity.RenderDreadThrall$2.getArmorResource(RenderDreadThrall.java:103) ~[RenderDreadThrall$2.class:?]`

**To Reproduce**
Very random behavior. Don't know if there is any persistency in the reproduction of this error, so I am just going to list what I did.
1. Go to the end.
2. Above void create a mob farm with spawners from ice and fire
3. Use farm
4. Eventually get white screen.

**Expected behavior**
No white screen

**Screenshots**
![image](https://user-images.githubusercontent.com/69990976/148643164-5d0a9df7-c8f2-4939-bfd7-4740f3503e0a.png)

**Additional context**
Mobs get glowing effect.
Mobs were on fire.
Mob spawners were moved via Cardboard Boxes from another mod.
Probably unrelated: This bug first happened after I disabled the named entity kill messages in the mod CoFHCore's server sided config.

**Comment by DigitalWendigo** [comment]
Please post this issue in the MC Eternal lite's modpack github so that the modpack maker is aware of it. 
It's likely not caused by ice and fire directly and is more than likely a cause by another mod. 
Also try posting the full log file.

**Comment by TheBv** [comment]
This isn't an issue anyone since the way this is handled was changed with 5f13ed4
