### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by Im-A-Star-Boy** [Alex-the-666/Ice_and_Fire#4367]
The lightning dragon forge specifically won't work, I've tried moving my dragon closer and further away, I've tried different dragons, it just doesn't work. All of my dragons are level 3+, all of my other forges work, but the lightning dragon one just doesn't.
![2022-01-10_00 12 33](https://user-images.githubusercontent.com/97425546/148720978-1ba93454-0e2c-4db2-b97c-3bcb13afd3fb.png)
![2022-01-10_00 12 41](https://user-images.githubusercontent.com/97425546/148720981-6fe04b8d-af6d-461f-91cf-cae520a2c7f6.png)
![2022-01-10_00 12 44](https://user-images.githubusercontent.com/97425546/148720983-5418fd58-86e9-41c4-a203-c6a0639157e7.png)
It could be some of the other mods I also have, those being Twilight Forest, Alex's Mobs, Oh the Biomes You'll Go, JEI, Farmers Delight, Mowzies Mobs, Journeymaps, Optifine, and all dependencies, but I don't think those would have any effect on it.

**Comment by DigitalWendigo** [comment]
Works just fine in the new Alpha2 release. 
Also works in the 2.1.9 version. 
![2022-05-10_20 03 58](https://user-images.githubusercontent.com/103202053/167683932-c1ea8522-953f-4504-99d6-e2ec5719dda7.png)

Provide a full list of your mods, every single one of them, and a log file.
