### ISSUE TITLE
Ice dragonsteel takes more dmg

### ISSUE THREAD

**Issue by Zorbeis** [Alex-the-666/Ice_and_Fire#4369]
ok so ice dragonsteel takes more dmg from dragon breath than dragon scale it says more resistance on dragonsteel armor description but it doesnt give much resistance compared to dragon scale. I dont think that is a feature and if it was im sorry for disturbing

Tq!

**Comment by tweakbsd** [comment]
That's a good one in my opinion. And when I looked it up I saw you are right, Dragonsteelt doesn't add extra protection from Dragonbreath.  And there is a potential bug that Lightning dragon breath attacks always deal full damage. 

It's in **ServerEvents.java** code: 

`
  @SubscribeEvent
    public void onEntityDamage(LivingHurtEvent event) {
       .... 
       /* IafDamageRegistry.DRAGON_LIGHTNING missing too*/
        if (event.getSource() == IafDamageRegistry.DRAGON_FIRE || event.getSource() == IafDamageRegistry.DRAGON_ICE) {
            float multi = 1;
            if (event.getEntityLiving().getItemStackFromSlot(EquipmentSlotType.HEAD).getItem() instanceof ItemScaleArmor) {
                multi -= 0.1;
            }
            if (event.getEntityLiving().getItemStackFromSlot(EquipmentSlotType.CHEST).getItem() instanceof ItemScaleArmor) {
                multi -= 0.3;
            }
            if (event.getEntityLiving().getItemStackFromSlot(EquipmentSlotType.LEGS).getItem() instanceof ItemScaleArmor) {
                multi -= 0.2;
            }
            if (event.getEntityLiving().getItemStackFromSlot(EquipmentSlotType.FEET).getItem() instanceof ItemScaleArmor) {
                multi -= 0.1;
            }
            event.setAmount(event.getAmount() * multi);
        }
    }
`

We could easily add **instanceof ItemDragonsteelArmor** there

**Comment by Zorbeis** [comment]
Wow I see more bugs arise from one. Well I hope a ice and fire mod dev will see this
