### ISSUE TITLE
Incompatibility with Animania [ Ticking entity ] 

### ISSUE THREAD

**Issue by Sluggasaurus** [Alex-the-666/Ice_and_Fire#437]
I posed this issue originally to Animania's github thinking it was an issue with that mod, but it seems it is actually Ice and Fire causing client sided crashes. 
https://github.com/capnkirok/animania/issues/516

Also I believe this is related to my issue with Hippogryphs earlier that I posted #430 

This issue seems to occur randomly, when players enter, or at least are near chunks that have the ice and fire dragons or hippogryphs, and they experience continued crashes until the entity is either moved by another player or removed. (after that they can be around the entity again without crashes for a while)
For example, I had a tamed Hippogryph at spawn, it crashed 2 of my friends when they tried to log in, so I moved it back to my base, and they logged in fine, then I flew it back over to them and no crashes.
However some of us have crashes when loading completely new chunks that turned out having dragon spawns, this dragon crash appears to be completely random as well.

 I have about 7 of my friends playing with me, we've all experienced this at different times.

**Comment by AlexModGuy** [comment]
dupe issue
