### ISSUE TITLE
[1.16.5] "Ticking entity" (java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/api/FoodUtils) [ICE AND FIRE 2.1.9]

### ISSUE THREAD

**Issue by aking4125** [Alex-the-666/Ice_and_Fire#4371]
**Describe the bug**
Upon exploring, this crash occurs randomly.

**To Reproduce**
1. Seems to occur during exploration randomly. Server only thus far.
2. Crashes. Server needs restarting.
3. See attached crash report?

**Expected behavior**
No crash? Game continues normally?

[crash-2022-01-16_12.23.28-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/7877532/crash-2022-01-16_12.23.28-server.txt)

**Comment by DigitalWendigo** [comment]
Please provide a full list of your mods and also a log file. 
Also try updating to the latest Alpha release found here: https://github.com/Alex-the-666/Ice_and_Fire/releases/tag/2.1.10-alpha2
