### ISSUE TITLE
ClassNotFound -- Ticking Entity [2.1.9-1.16.5]

### ISSUE THREAD

**Issue by kreezxil** [Alex-the-666/Ice_and_Fire#4375]
**Describe the bug**
Player crashed server while exploring, said they witnessed a dragon eating a sheep.

Server crash report:
https://hastebin.com/lerezihine

Issue happened in my pack [World of Dragons II](https://www.curseforge.com/minecraft/modpacks/world-of-dragons-ii)

**Comment by DigitalWendigo** [comment]
The hastebin link is empty.

**Comment by kreezxil** [comment]
it's empty now because things have take so long to get here. I'll close this.
