### ISSUE TITLE
Dragons only move when i get close enough [2.1.9-1.16.5]

### ISSUE THREAD

**Issue by RadonCoding** [Alex-the-666/Ice_and_Fire#4376]
Okay so when i see a dragon roost the dragon is like stuck flying in the air or not moving and when i get close enough it starts moving.

1. Go to a dragon roost
2. Watch it from far away
3. See the dragon not doing anything / not moving and stuck not updating

Expected it to be flying around killing animals and maybe looking for players

**Comment by ghost** [comment]
dragons wont be loaded when the distance from the chunk that you are in to the dragon chunk that the dragon is in is equal to your render distance - 1
