### ISSUE TITLE
very basic ''problem''

### ISSUE THREAD

**Issue by patvonck** [Alex-the-666/Ice_and_Fire#4378]
hello i am a complete noob when it comes to coding and tried to figure out just how to set this
     # Dragons cannot spawn in these dimensions' IDs
    I:"Blacklisted Dragon Dimensions" <
        -1
        1
     >
into a whitelisted dimension for the overworld only i think i can just change the balcklisted to whitelisted but when it comes to set which dimensions is listed, is where i am getting lost i tried =0 and <0> then i looked alot online but haven't figured out how to do such basic stuff so ye here i am...

**Comment by PallyK** [comment]
in 1.13 they flattened out most of the IDs which includes dimension IDs. instead of 0 you would put in 'minecraft:overworld' or if a modded dimension 'modname:dimensionname'

**Comment by patvonck** [comment]
sorry forgot to mention that i am in 1.12.2...
