### ISSUE TITLE
Cant Crafting mod iten

### ISSUE THREAD

**Issue by dmhKPan** [Alex-the-666/Ice_and_Fire#4379]
Hello everyone,
I cant craft anymod item. Can you help me?

**Comment by Ferr8** [comment]
I have the same - everything else works, but I can't craft any mod items.

**Comment by PallyK** [comment]
please you two, state which version you are using as well as if you are trying to craft via the blasted recipe book or not, if this is in a modpack then should be a problem of said modpack. Not of the mod itself
recipes work fine in the most recent version (2.1.9) and with it I wonder what you are attempting

**Comment by Ferr8** [comment]
Hi,
thank you and sorry for not putting the versions in the reply.

Using Minecraft 1.16.5, citadel 1.8.1, forge 36.2.20 and the latest ice and
fire 2.1.9

I am new to modding and so, I hope those are the right ones.


Where you say "via the blasted recipe book"; I'm sorry, but I don't know
what that is (I just googled it and searched the ice and fire fandom wiki
to check too).  We've been using recipes from the wiki (and checked on some
youtube videos to see that other people can craft doing that).  An example
would be that we can't craft the Bestiary, using the 3 manuscripts
(shapeless recipe) and we've seen youtubers do it and copied them.

Thank you!

**Comment by PallyK** [comment]
install check JEI that usually digs into the recipe files for mods and thankfull the mod has support for JEI

**Comment by DigitalWendigo** [comment]
Has this been resolved or is it still an issue?
Please provide more information. 

Are there any other mods involved that you have not listed?
Have you installed JEI and can still not craft items?
What launcher are you using?
Can you provide a log file?

**Comment by Ferr8** [comment]
Thank you for following up on this and my apologies for not giving an
update.
I have checked with my son and he says it is now resolved. Thank you for
your help!

**Comment by DigitalWendigo** [comment]
Alright, then please close this issue as it's been resolved. Have a nice day.

**Comment by Ferr8** [comment]
Thank you -I'll work out how to do that. I'm a dad of a gamer, so not
familiar with how to do this stuff. Thanks again for your help.

**Comment by Ferr8** [comment]
Ah, I can't close it as it wasn't my issue - I just commented I had the same.
