### ISSUE TITLE
Siren causes the server to crash.(1.16.5 and 2.1.9)

### ISSUE THREAD

**Issue by YifanHere** [Alex-the-666/Ice_and_Fire#4382]
The server crashes when the player is killed by siren.

1. Player killed by siren.
2. The server immediately crashed at that moment.

It is worth mentioning that Cyclops made similar mistake, but it never happened again.

This is the crash log:https://pastebin.ubuntu.com/p/9rcMx9dM5r/

**Comment by StickyFruitSnacks** [comment]
I am having the exact same problem.  I would really like if you could fix it please. 

It appears to be a java.lang.NullPointerException within  com.github.alexthe666.iceandfire.item.ItemDragonHornActive.func_77615_a(ItemDragonHornActive.java:124)

I have attached my crash report as well.
[crash-2022-03-17_19.37.31-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/8308235/crash-2022-03-17_19.37.31-server.txt)
