### ISSUE TITLE
Are we going to see a 1.18.1 update? Or maybe a 1.19 one?

### ISSUE THREAD

**Issue by Entyco** [Alex-the-666/Ice_and_Fire#4383]

**Comment by Nebula240** [comment]
We should first get a fix for the 1.16.5 ver.

**Comment by Ravenclaws-Rule** [comment]
YES PLEEZ GIT (See what I did there?) A 1.18.1 UPDATE!

**Comment by Rasblue** [comment]
Need some 1.18.1 of this hot baby

**Comment by SCPSLPLUGINS4ME** [comment]
probably not

**Comment by cs-AI-dev** [comment]
ima need the 1.18.1 for my new mp pls

**Comment by LaBestiaBrutal** [comment]
Aah yes, MC is not as deadly as it should, either way, we need this please!

**Comment by BronzeS8** [comment]
Yall need to stop asking for 1.18.1, it ain't gunna happen any faster the more you beg

**Comment by AlexModGuy** [comment]
nope - we are wating for 1.18.2
