### ISSUE TITLE
No Dragons

### ISSUE THREAD

**Issue by Mpk200** [Alex-the-666/Ice_and_Fire#4384]
Hey I'm sure this has been mentioned before but I didn't find any satisfying answers so here I go:
I'm playing the 1.9.1-1.12.2 version of the mod with a bunch of other mods (I can provide mod list if needed)
and no dragons spawn in my world. I have found gorgon temples before but no dragons. I hope I don't cause inconveniences and look forward to help!

**Comment by PallyK** [comment]
in I&F there is a dangerous terrain gen radius, basically until you go out far enough from spawn there won't be any dangerous structure including dragon roosts. the default in 1.12 is 200 while in 1.16 is 800 (following a common issue in the mod of being roasted day one) there also might the issue that if you're using a biome mod that it is conflicting the parameters set with ice and fire. try it without any mods that would affect terrain such as biomes o plenty

**Comment by Mpk200** [comment]
Hmm I played around in the config file amping up the generation chance and removed the main biome adding mods but still nothing... Are there other mods interfering ? I also checked beyond the radius. For some reason the roosts dont generate

**Comment by Mpk200** [comment]
Okay nvm I messed up with the spawn rate in the config files it works without the biome mods. Thank you!
