### ISSUE TITLE
Name Tags Not Working on Dragons [1.9.1-1.12.2]

### ISSUE THREAD

**Issue by FliptheGreat** [Alex-the-666/Ice_and_Fire#4386]
Having an issue with being able to name dragons with this version of the mod. Shift right clicking, right clicking, nothing seems to work using the name tag on dragons. I know in the past this has worked, unsure if updating the mod for rlcraft could have broken that or what is the issue. Thanks.

**Comment by PlummetStudios** [comment]
1.12 is not a supported version anymore.
