### ISSUE TITLE
Myrmex, TPS LOW, how to kill them, spawn myrmex disabled

### ISSUE THREAD

**Issue by ScrollDP** [Alex-the-666/Ice_and_Fire#4388]
**Describe the bug**
Myrmex cause TPS lag of server(TPS LOW)

**Expected behavior**
I want to know, how to kill these mobs,

**Screenshots**
https://timings.aikar.co/?id=dbe6820d22884c6d95137c574ecc9bab

**Additional context**
In config, I already disabled spawn Myrmex, but there are still and I don't know how to kill them.

**Comment by jinkhya** [comment]
Hello,
Also seeing tps issues with those in 1.12.
You can do /kill @e[type=iceandfire:myrmex_soldier] 
(replace soldier by queen, worker, sentinel to kill the different types

**Comment by DigitalWendigo** [comment]
Also try looking into the config file and lower the amount of pathfinding nodes a myrmex mob can use. (I think this was tied with dragons..?)
Also try lowering their wander range, and the maximum size or a colony as the default size of a colony is 80.
Meaning potentially 80 entities with expensive AI tasks. Lowering that helps a ton.

**Comment by DigitalWendigo** [comment]
Version 1.12.2 is no longer supported. Please update to a later version. 
This can probably be closed.
