### ISSUE TITLE
Buff lightning dragon's default breath attack multiplier

### ISSUE THREAD

**Issue by pantsguyapp** [Alex-the-666/Ice_and_Fire#4390]
How it should be:
The attack should have a default multiplier of 6.0

Reason for the new change:
At 6.0, stage 3 lightning will two shot any 20 hp mobs and stage 4 will one shot said mobs.

How it is right now:
Only 3.0 multiplier. In the config

The issue:
3.0 isnt that strong as the bestiary hype up the dragons to be.

**Comment by Alex-the-666** [comment]
no
