### ISSUE TITLE
Dragons and their skeletons are absolutely huge

### ISSUE THREAD

**Issue by Cyberwolf606** [Alex-the-666/Ice_and_Fire#4392]
Maybe I have a mod that's causing this but my dragons are spawning at stupidly large sizes and their hitboxes are nowhere near the same size as them. It would be interesting if it worked at all
![2022-02-06_11 07 56](https://user-images.githubusercontent.com/99134959/152690129-fb7d2b1e-84b1-4b38-a220-a4840c337c06.png)
![2022-02-06_03 57 31](https://user-images.githubusercontent.com/99134959/152690139-d0e9303a-0085-4514-91ca-97f965b2c0e7.png)
.

**Comment by TippedwithHoney** [comment]
Wow! Wich version is this, and wich other mods with wich configs do you have installed? I would really like to reproduce this for myself.

**Comment by DigitalWendigo** [comment]
I definitely suggest posting all the mods you have installed. 
Without posting a list, it'll be impossible for the developers to figure out the issue.

**Comment by DigitalWendigo** [comment]
Unless the original poster provides a list of their mods and a log, this issue can probably be closed as there is seemingly no response.
