### ISSUE TITLE
Terraforged Mob spawn crash with iceandfire-2.1.9-1.16.5

### ISSUE THREAD

**Issue by EightBlade** [Alex-the-666/Ice_and_Fire#4399]
So I'm playing with Ice and Fire and Terraforged. When I use the two together I'll consistently get random crashes with the following error: https://pastebin.com/FA6RygqR

I've had this happen around 15 times, and after lots of trial and error involving installing and removing mods that add entities I've whittled it down to Ice & Fire that causes it. 

**To Reproduce**
Step One: Install Terraforged(Beta or stable lastest, doesn't matter)
Step Two: Install Ice&Fire
Step Three: Generate world
Step Four: Run around until it eventually crashes

**Expected behavior**
I didn't expect it to crash.

**Additional context**
At first I thought it was a terraforged issue, but after reporting it and talking with the dev it appears not to be the case.

**Comment by AlexModGuy** [comment]
issue seems to stem from terraforged. 
> terraforged.mod.chunk.generator.MobGenerator.generateMobs
The dev should make sure that this doesnt call performWorldGenSpawning() for mobs that have an invalid spawn cap
