### ISSUE TITLE
Riding animal issues

### ISSUE THREAD

**Issue by Seilican** [Alex-the-666/Ice_and_Fire#440]
Myself and my wife are having 3 issues today. First after I had told my Dragon to stay it started to wander. It did this multiple times after I used the staff. 2nd my wife (Ladythorns) tamed a hippogriff but was unable to mount it like she had done with her previous one. The inventory would not come up when she right clicked it with an empty hand. 3rd I had looted a fire dragon egg put it on the fire nest like my previous dragon when the fire went out no dragon was there. I searched the area with my wife's help but was not able to find it. I am unsure if these are all related but there seems to be something going on and I was hoping you could look into it. I am sorry I do not have more detailed information.

**Comment by AlexModGuy** [comment]
what other mods are you using

**Comment by AlexModGuy** [comment]
fixed eggs fizzing out
