### ISSUE TITLE
TICKIBG ENITY: CYCLOPS [ICE AND FIRE 2.1.9]

### ISSUE THREAD

**Issue by DJLegends1011** [Alex-the-666/Ice_and_Fire#4403]
**Describe the bug**
Ticking entity Cyclyps no matter what I do whenever i join my server cyclips crashes and I get ticking entity problem

**To Reproduce**
launched server 5 times and joined stil error

**Expected behavior**
to join properly but not

**CrashLogs**
https://pastebin.com/4GCGsX2p

**Comment by TheBv** [comment]
Same as #4445 just this time with the mod `roadrunner`
