### ISSUE TITLE
Minecraft Game Crash Report [1.12.2] [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by LordOfReality** [Alex-the-666/Ice_and_Fire#4405]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.22.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MovingWorldCore (movingworld-1.12-6.353-full.jar)
  SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.4.1.jar)
  BiomeTweakerCore (BiomeTweakerCore-1.12.2-1.0.39.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  Wizardry Plugin (wizardry-0.11.1.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 2/19/22 11:29 AM
Description: Initializing game

java.lang.VerifyError: Expecting a stackmap frame at branch target 461
Exception Details:
  Location:
    com/github/alexthe666/iceandfire/entity/EntityDragonBase.breakBlock()V @457: goto
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2ab4 0791 9d00 0cb2 04d6 b407 949a 01d8
    0x0000010: 2a59 b407 9104 64b5 0791 043c 2ab6 03b5
    0x0000020: 9900 0e2a b604 94c6 0007 02a7 0004 043d
    0x0000030: 2ab4 0791 9900 0cb2 04d6 b407 949a 01a8
    0x0000040: 2ab4 01d5 2ab8 0798 9901 9db2 04d6 b407
    0x0000050: 9b05 9f01 932a b603 a799 000c b204 d6b4
    0x0000060: 079e 9901 83b2 04d6 b407 9b04 9f00 0b2a
    0x0000070: b602 6706 a300 070d a700 0613 079f 462a
    0x0000080: b601 e49a 0162 2ab6 0267 06a1 015a 2ab6
    0x0000090: 0780 9a00 0a2a b604 abc6 014c 2ab6 0720
    0x00000a0: b407 28b8 07a3 8e1b 6436 0415 042a b607
    0x00000b0: 20b4 0725 b807 a68e 1b60 a301 2b2a b607
    0x00000c0: 20b4 072e b807 a38e 1c60 3605 1505 2ab6
    0x00000d0: 0720 b407 2bb8 07a6 8e1b 6004 60a3 0102
    0x00000e0: 1505 107f a300 fb2a b607 20b4 0734 b807
    0x00000f0: a38e 1b64 3606 1506 2ab6 0720 b407 31b8
    0x0000100: 07a6 8e1b 60a3 00d4 b207 acbb 07ae 592a
    0x0000110: 1504 8715 0587 1506 87b7 07b1 b607 b799
    0x0000120: 0006 a700 b1bb 01f9 5915 0415 0515 06b7
    0x0000130: 044a 3a07 2ab4 01d5 1907 b602 553a 0819
    0x0000140: 08b9 07bb 0100 b607 c099 008a 1908 2ab4
    0x0000150: 01d5 1907 b907 c403 000b 959b 0078 1908
    0x0000160: 2ab4 01d5 1907 b907 c403 0025 969d 0066
    0x0000170: 1908 b902 5b01 00b8 07ca 9900 592a 1907
    0x0000180: b607 cc99 0050 2a59 b407 cf14 07d0 6bb5
    0x0000190: 07cf 2a59 b407 d414 07d0 6bb5 07d4 2ab4
    0x00001a0: 01d5 b402 179a 002e 2ab4 01d5 1907 2ab4
    0x00001b0: 02b4 b602 c68d b204 d6b4 07d7 989d 000f
    0x00001c0: 1908 b807 db99 0007 04a7 0004 0319 05b8
    0x00001d0: 07e1 5784 0601 a7ff 2084 0501 a7fe f084
    0x00001e0: 0401 a7fe c9b1                         
  Stackmap Table:
    same_frame(@16)
    append_frame(@46,Integer)
    same_locals_1_stack_item_frame(@47,Integer)
    append_frame(@64,Integer)
    same_frame(@101)
    same_frame(@119)
    same_frame(@123)
    same_locals_1_stack_item_frame(@126,Float)
    append_frame(@156,Float)
    append_frame(@171,Integer)
    append_frame(@204,Integer)
    append_frame(@246,Integer)
    same_frame(@293)
    full_frame(@460,{Object[#2],Integer,Integer,Float,Integer,Integer,Integer,Object[#505],Object[#599]},{Object[#279],Object[#505]})
    chop_frame(@467,2)
    chop_frame(@473,1)
    chop_frame(@479,1)
    full_frame(@485,{Object[#2]},{})

	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at net.minecraftforge.fml.relauncher.ReflectionHelper.findConstructor(ReflectionHelper.java:326)
	at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findConstructor(ObfuscationReflectionHelper.java:194)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.<init>(EntityEntryBuilder.java:297)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$1.<init>(EntityEntryBuilder.java:265)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder.build(EntityEntryBuilder.java:265)
	at com.github.alexthe666.iceandfire.CommonProxy.registerSpawnable(CommonProxy.java:151)
	at com.github.alexthe666.iceandfire.CommonProxy.registerEntities(CommonProxy.java:84)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_339_CommonProxy_registerEntities_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at net.minecraftforge.fml.relauncher.ReflectionHelper.findConstructor(ReflectionHelper.java:326)
	at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findConstructor(ObfuscationReflectionHelper.java:194)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.<init>(EntityEntryBuilder.java:297)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$1.<init>(EntityEntryBuilder.java:265)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder.build(EntityEntryBuilder.java:265)
	at com.github.alexthe666.iceandfire.CommonProxy.registerSpawnable(CommonProxy.java:151)
	at com.github.alexthe666.iceandfire.CommonProxy.registerEntities(CommonProxy.java:84)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_339_CommonProxy_registerEntities_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1174918528 bytes (1120 MB) / 2023227392 bytes (1929 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 78 mods loaded, 78 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                           | Version                 | Source                                            | Signature                                |
	|:----- |:-------------------------------------------- |:----------------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                                    | 1.12.2                  | minecraft.jar                                     | None                                     |
	| LCH   | mcp                                          | 9.42                    | minecraft.jar                                     | None                                     |
	| LCH   | FML                                          | 8.0.99.99               | forge-1.12.2-14.23.5.2860.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                                        | 14.23.5.2860            | forge-1.12.2-14.23.5.2860.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | com.elytradev.movingworld.common.asm.coremod |                         | minecraft.jar                                     | None                                     |
	| LCH   | biometweakercore                             | 1.0.39                  | minecraft.jar                                     | None                                     |
	| LCH   | ageofweapons                                 | 0.13.5                  | Age+of+Weapons+1.12.2++(v.0.13.5).jar             | None                                     |
	| LCH   | akashictome                                  | 1.2-12                  | AkashicTome-1.2-12.jar                            | None                                     |
	| LCH   | ancientbeasts                                | 1.8.2                   | ancientbeasts-1.8.2.jar                           | None                                     |
	| LCH   | artemislib                                   | 1.0.6                   | ArtemisLib-1.12.2-v1.0.6.jar                      | None                                     |
	| LCH   | autoreglib                                   | 1.3-32                  | AutoRegLib-1.3-32.jar                             | None                                     |
	| LCH   | battletowers                                 | 1.6.5                   | BattleTowers-1.12.2.jar                           | None                                     |
	| LCH   | baubles                                      | 1.5.2                   | Baubles-1.12-1.5.2.jar                            | None                                     |
	| LCH   | betterbuilderswands                          | 0.13.2                  | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar | None                                     |
	| LCH   | biometweaker                                 | 3.2.369                 | BiomeTweaker-1.12.2-3.2.369.jar                   | 631f326344f7f5fd7df7eb940760ebd52b7c9c17 |
	| LCH   | ctm                                          | MC1.12.2-1.0.2.31       | CTM-MC1.12.2-1.0.2.31.jar                         | None                                     |
	| LCH   | jei                                          | 4.16.1.302              | jei_1.12.2-4.16.1.302.jar                         | None                                     |
	| LCH   | chisel                                       | MC1.12.2-1.0.2.45       | Chisel-MC1.12.2-1.0.2.45.jar                      | None                                     |
	| LCH   | clumps                                       | 3.1.2                   | Clumps-3.1.2.jar                                  | None                                     |
	| LCH   | cyclopscore                                  | 1.6.7                   | CyclopsCore-1.12.2-1.6.7.jar                      | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCH   | colossalchests                               | 1.7.3                   | ColossalChests-1.12.2-1.7.3.jar                   | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCH   | cookingforblockheads                         | 6.5.0                   | CookingForBlockheads_1.12.2-6.5.0.jar             | None                                     |
	| LCH   | cw                                           | 1.0.2                   | creature_whisperer_1.0.2.jar                      | None                                     |
	| LCH   | curio                                        | 1.0.4                   | Curio-1.0.4.jar                                   | None                                     |
	| LCH   | movingworld                                  | 1.12-6.353              | movingworld-1.12-6.353-full.jar                   | None                                     |
	| LCH   | davincisvessels                              | @DVESSELSVER@           | davincisvessels-1.12-6.355-full.jar               | None                                     |
	| LCH   | doggytalents                                 | 1.15.1.6                | DoggyTalents-1.12.2-1.15.1.6.jar                  | None                                     |
	| LCH   | ebwizardry                                   | 4.3.5                   | ElectroblobsWizardry-4.3.5-MC1.12.2.jar           | None                                     |
	| LCH   | enderore                                     | 1.12.2-v1.1             | Ender+Ore-1.12.2-v1.1.jar                         | None                                     |
	| LCH   | ftblib                                       | 5.4.7.2                 | FTBLib-5.4.7.2.jar                                | None                                     |
	| LCH   | shetiphiancore                               | 3.5.9                   | shetiphiancore-1.12.0-3.5.9.jar                   | None                                     |
	| LCH   | endertanks                                   | 1.6.8                   | endertanks-1.12.0-1.6.8.jar                       | None                                     |
	| LCH   | epicfight                                    | 1.12.2-2.2.8            | EpicFightMod-1.12.2-2.2.8.jar                     | None                                     |
	| LCH   | llibrary                                     | 1.7.20                  | llibrary-1.7.20-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | iceandfire                                   | 1.9.1                   | iceandfire-1.9.1-1.12.2.jar                       | None                                     |
	| LCH   | eyeofdragons                                 | 0.0.1                   | eyeofdragons-0.0.2.jar                            | None                                     |
	| LCH   | foodexpansion                                | 1.3                     | FoodExpansion1.3.3-1.12.2.jar                     | None                                     |
	| LCH   | toughasnails                                 | 3.1.0.141               | ToughAsNails-1.12.2-3.1.0.141-universal.jar       | None                                     |
	| LCH   | forestry                                     | 5.8.2.422               | forestry_1.12.2-5.8.2.422.jar                     | None                                     |
	| LCH   | forgelin                                     | 1.8.4                   | Forgelin-1.8.4.jar                                | None                                     |
	| LCH   | ftbutilities                                 | 5.4.1.131               | FTBUtilities-5.4.1.131.jar                        | None                                     |
	| LCH   | waila                                        | 1.8.26                  | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
	| LCH   | ichunutil                                    | 7.2.2                   | iChunUtil-1.12.2-7.2.2.jar                        | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | inventorytweaks                              | 1.64+dev.151.822d839    | InventoryTweaks-1.64+dev.151.jar                  | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | iseedragons                                  | 1.2                     | ISeeDragons-1.2.jar                               | None                                     |
	| LCH   | journeymap                                   | 1.12.2-5.7.1            | journeymap-1.12.2-5.7.1.jar                       | None                                     |
	| LCH   | librarianlib                                 | 4.22                    | librarianlib-1.12.2-4.22.jar                      | None                                     |
	| LCH   | luckyores                                    | 1.0                     | luckyores-1.12.2-1.3.jar                          | None                                     |
	| LCH   | mantle                                       | 1.12-1.3.3.55           | Mantle-1.12-1.3.3.55.jar                          | None                                     |
	| LCH   | millenaire                                   | Millénaire 8.1.2-beta.2 | millenaire-8.1.2-beta.2.jar                       | None                                     |
	| LCH   | millenairejei                                | 0.1                     | millenairejei-1.12.2-1.0.0-beta001.jar            | None                                     |
	| LCH   | morph                                        | 7.2.0                   | Morph-1.12.2-7.2.1.jar                            | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | mowziesmobs                                  | 1.5.8                   | mowziesmobs-1.5.8.jar                             | None                                     |
	| LCH   | naturescompass                               | 1.8.5                   | NaturesCompass-1.12.2-1.8.5.jar                   | None                                     |
	| LCH   | recipehandler                                | 0.13                    | NoMoreRecipeConflict-0.13(1.12.2).jar             | None                                     |
	| LCH   | harvestcraft                                 | 1.12.2zb                | Pam's+HarvestCraft+1.12.2zg.jar                   | None                                     |
	| LCH   | patchouli                                    | 1.0-23.6                | Patchouli-1.0-23.6.jar                            | None                                     |
	| LCH   | refinedstorage                               | 1.6.16                  | refinedstorage-1.6.16.jar                         | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCH   | roguelike                                    | 1.8.0                   | RoguelikeDungeons-1.12.2-1.8.0.jar                | None                                     |
	| LCH   | xat                                          | 0.31.4                  | Trinkets+and+Baubles-0.31.4.jar                   | None                                     |
	| LCH   | spartanweaponry                              | 1.4.1                   | SpartanWeaponry-1.12.2-1.4.1.jar                  | None                                     |
	| LCH   | spartanfire                                  | 0.08                    | spartanfire-0.08.jar                              | None                                     |
	| LCH   | thaumcraft                                   | 6.1.BETA26              | Thaumcraft-1.12.2-6.1.BETA26.jar                  | None                                     |
	| LCH   | twilightforest                               | 3.11.1021               | twilightforest-1.12.2-3.11.1021-universal.jar     | None                                     |
	| LCH   | tconstruct                                   | 1.12.2-2.13.0.183       | TConstruct-1.12.2-2.13.0.183.jar                  | None                                     |
	| LCH   | tfspellpack                                  | 1.1.0                   | TFSpellPack-1.1.0-MC1.12.2.jar                    | None                                     |
	| LCH   | thaumicwaila                                 | 1.12.2-0.0.2            | ThaumicWaila-1.12.2-0.0.2.jar                     | None                                     |
	| LCH   | travelersbackpack                            | 1.0.35                  | TravelersBackpack-1.12.2-1.0.35.jar               | None                                     |
	| LCH   | tbintegration                                | 1.0.1                   | TravelersBackpackIntegration-1.12.2-1.0.1.jar     | None                                     |
	| LCH   | universalbestiary                            | 1.3.1                   | universalbestiary-1.12.2-1.3.1.jar                | None                                     |
	| LCH   | wailaharvestability                          | 1.1.12                  | WailaHarvestability-mc1.12-1.1.12.jar             | None                                     |
	| LCH   | waterskin                                    | 1.0.1                   | waterskin-1.0.1.jar                               | None                                     |
	| LCH   | waystones                                    | 4.1.0                   | Waystones_1.12.2-4.1.0.jar                        | None                                     |
	| LCH   | wizardry                                     | 0.11.1                  | wizardry-0.11.1.jar                               | None                                     |
	| LCH   | structurize                                  | 1.12.2-0.10.277-RELEASE | structurize-1.12.2-0.10.277-RELEASE.jar           | None                                     |
	| LCH   | minecolonies                                 | 1.12.2-0.11.841-ALPHA   | minecolonies-1.12.2-0.11.841-ALPHA-universal.jar  | None                                     |
	| LCH   | mospells                                     | 1.0.2                   | MoSpells-1.12.2-1.0.2.jar                         | None                                     |
	| LCH   | librarianliblate                             | 4.22                    | librarianlib-1.12.2-4.22.jar                      | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)
  invtweaks.forge.asm.ContainerTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  shetiphian.asm.ClassTransformer
LibrarianLib Plugin (librarianlib-1.12.2-4.22.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MovingWorldCore (movingworld-1.12-6.353-full.jar)
  
SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.4.1.jar)
  
BiomeTweakerCore (BiomeTweakerCore-1.12.2-1.0.39.jar)
  me.superckl.biometweakercore.BiomeTweakerASMTransformer
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Wizardry Plugin (wizardry-0.11.1.jar)
  com.teamwizardry.wizardry.asm.WizardryTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 376.54' Renderer: 'GeForce GTX 860M/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Patchouli open book context: n/a
	Launched Version: forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 860M/PCIe/SSE2 GL version 4.5.0 NVIDIA 376.54, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz

**Comment by LordOfReality** [comment]
Should I just delete ice and fire ?

**Comment by fallenthereaper** [comment]
1.12 is not supported
