### ISSUE TITLE
Issues with the gorgons structure and OTG world (i'm on 1.12.2)

### ISSUE THREAD

**Issue by GaspourTheRealOne** [Alex-the-666/Ice_and_Fire#4407]
Not a big issues but still pretty annoying with the OTG world (biome bundle) and your Gorgons structure , don't know why but the structure just cut down the map making it pretty ugly and that's only the case for this specific structure so i don't think it come from biome bundle.
![2021-11-10_23 22 39](https://user-images.githubusercontent.com/100069658/154838016-20b03c3f-ed55-4705-bd25-9235e199d745.png)
.

**Comment by Kingmiami** [comment]
I'm on OTG 1.12 as well, and it is a big issue. Gorgon structures often spawn on every single beach, and it seems that the mod completely ignores the "Spawn Gorgons" config option. It's infuriating how they leave versions buggy and broken like this.
