### ISSUE TITLE
Certain creature's health config doesn't work [ICE AND FIRE VERSION 2.1.9]

### ISSUE THREAD

**Issue by pantsguyapp** [Alex-the-666/Ice_and_Fire#4410]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Some creatures will retain the default health amount even if changed in the config file.

**To Reproduce**
Tested on Cyclops and Cockatrice, go to the config, change their health and spawn some with the new config

**Expected behavior**
Their health should be similar to the new number

**Screenshots**

**Additional context**

**Comment by DigitalWendigo** [comment]
Have you tried with AttributeFix? 
It fixes some vanilla based issues with upper attribute limits by increasing the upper limit. 
THis was less of an issue in 1.12.2 but has been an increasingly more common issue with 1.16.5.

**Comment by TheBv** [comment]
Same as #4037
