### ISSUE TITLE
IAF 2.1.9 Tamed dragons disappearing at random when ridden in modded multiplayer server

### ISSUE THREAD

**Issue by Kermatus** [Alex-the-666/Ice_and_Fire#4413]
**Describe the bug**
In a multiplayer server, me and my friends fire dragons suddenly vanished while we were riding it. 
When I got my first dragon I was riding it for the first time when it became stage 4, I was flying around with it for the first time and as I was heading back to base it suddenly vanished and I fell off of it. I had no luck finding it after logging back into the server to see if that would fix it. 
A few days later my friend got his own dragon and once it became stage 3 he started to ride it to see how the flight was.  Everything seemed fine but the dragon suddenly vanished while he was flying it. In anticipation of another dragon vanishing, I crafted a summoning crystal for him before his dragon became stage 3. However, the summoning crystal didn't work after the dragon vanished and it doesn't say what dragon it is bound to. 
We didn't receive any death message when the dragons vanished and I know they didn't die due to hunger since they both were full. They both had nametags used on them and mine had a full set of iron armor before it vanished and both dragons were fed primarily dragon meal. 

**To Reproduce
Steps to reproduce the behavior:**
fly with a stage 3+ fire dragon for the first time in a multiplayer server (I'm not sure if it affects just fire dragons but I haven't gotten eggs from the other types yet to test)
and fly around for a bit (I'm uncertain how long it will take in all honesty since it happened randomly for both of us)

**Expected behavior**
Tamed dragons shouldn't vanish out of existence suddenly while riding them

**Screenshots**
Here is a picture of my friend's dragon summoning crystal after the dragon vanished 
![2022-02-22_10 03 55](https://user-images.githubusercontent.com/96867748/155168368-49197713-727a-49fd-9670-5d92cbde0a09.png)

**Comment by TheBv** [comment]
Any chance you can provide the log files(latest.log) from the server the day this happened?
Might help troubleshoot this issue without having to directly recreate it.

**Comment by Kermatus** [comment]
> 

I'll contact the server owner and see if he can provide me the files.

**Comment by XionioXMaster** [comment]
My players had the same until I turned on the prohibition of the disappearance of dragons in the config, apparently, hand dragons disappear because of this
