### ISSUE TITLE
Crashed when dragon is attacking

### ISSUE THREAD

**Issue by JustDudeIt123** [Alex-the-666/Ice_and_Fire#4416]
Game get crashed when the dragon is attacking

The first time I killed one dragon without any crashes. Then I created an armor from his scales and went further, where I met another dragon. I hit it a couple of times and the game crashed. it is often get crashed when the dragon uses its breath. but once the crash happened without it. maybe Tconstruct arrows are to blame, but I'm not sure.

the game should not crash

here is the crash report
`---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2/25/22 11:30 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at tonite.tinkersarchery.modifiers.traits.Finishing.getEntityDamage(Finishing.java:32) ~[?:1.2.0] {re:classloading}
	at tonite.tinkersarchery.library.util.ProjectileAttackUtil.attackEntity(ProjectileAttackUtil.java:61) ~[?:1.2.0] {re:classloading}
	at tonite.tinkersarchery.entities.TinkersArrowEntity.func_213868_a(TinkersArrowEntity.java:216) ~[?:1.2.0] {re:classloading}
	at net.minecraft.entity.projectile.ProjectileEntity.func_70227_a(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:188) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at tonite.tinkersarchery.entities.TinkersArrowEntity.func_70071_h_(TinkersArrowEntity.java:165) ~[?:1.2.0] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld$$Lambda$16954/989743184.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:alloc.chunk_random.WorldMixin,pl:mixin:APP:sodium.mixins.json:world.chunk_access.WorldMixin,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$16060/1032820521.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at tonite.tinkersarchery.modifiers.traits.Finishing.getEntityDamage(Finishing.java:32) ~[?:1.2.0] {re:classloading}
	at tonite.tinkersarchery.library.util.ProjectileAttackUtil.attackEntity(ProjectileAttackUtil.java:61) ~[?:1.2.0] {re:classloading}
	at tonite.tinkersarchery.entities.TinkersArrowEntity.func_213868_a(TinkersArrowEntity.java:216) ~[?:1.2.0] {re:classloading}
	at net.minecraft.entity.projectile.ProjectileEntity.func_70227_a(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:188) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at tonite.tinkersarchery.entities.TinkersArrowEntity.func_70071_h_(TinkersArrowEntity.java:165) ~[?:1.2.0] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld$$Lambda$16954/989743184.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: tinkersarchery:tinkers_arrow (tonite.tinkersarchery.entities.TinkersArrowEntity)
	Entity ID: 42913
	Entity Name: entity.tinkersarchery.tinkers_arrow
	Entity's Exact location: -2255.32, 74.35, -1223.86
	Entity's Block location: World: (-2256,74,-1224), Chunk: (at 0,4,8 in -141,-77; contains blocks -2256,0,-1232 to -2241,255,-1217), Region: (-5,-3; contains chunks -160,-96 to -129,-65, blocks -2560,0,-1536 to -2049,255,-1025)
	Entity's Momentum: 1.55, 0.42, -4.31
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:alloc.chunk_random.WorldMixin,pl:mixin:APP:sodium.mixins.json:world.chunk_access.WorldMixin,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A}

-- Affected level --
Details:
	All players: 2 total; [ServerPlayerEntity['JustDudeIt'/401, l='ServerLevel[Тест 0.8]', x=-1926.84, y=62.07, z=-749.39], ServerPlayerEntity['Riop'/34063, l='ServerLevel[Тест 0.8]', x=-2258.43, y=72.00, z=-1215.16]]
	Chunk stats: ServerChunkCache: 5067
	Level dimension: minecraft:overworld
	Level spawn location: World: (-64,66,2), Chunk: (at 0,4,2 in -4,0; contains blocks -64,0,0 to -49,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 585363 game time, 641817 day time
	Level name: Тест 0.8
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 107409 (now: false), thunder time: 118257 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$16060/1032820521.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4614690488 bytes (4400 MB) / 7147094016 bytes (6816 MB) up to 7147094016 bytes (6816 MB)
	CPUs: 8
	JVM Flags: 11 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmn128M -Xmx6806M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.26.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.26.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.26.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.26.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.26.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.26
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		inventorysorter-1.16.1-18.1.0.jar                 |Simple Inventory Sorter       |inventorysorter               |18.1.0              |DONE      |Manifest: NOSIGNATURE
		rhino-forge-1605.1.5-build.75.jar                 |Rhino                         |rhino                         |1605.1.5-build.75   |DONE      |Manifest: NOSIGNATURE
		mowziesmobs-1.5.19.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.19              |DONE      |Manifest: NOSIGNATURE
		ftb-jar-mod-1605.1.0-build.28.jar                 |FTB Jar Mod                   |ftbjarmod                     |1605.1.0-build.28   |DONE      |Manifest: NOSIGNATURE
		TrashSlot_1.16.3-12.2.1.jar                       |TrashSlot                     |trashslot                     |12.2.1              |DONE      |Manifest: NOSIGNATURE
		tinkersarchery-1.2.0.jar                          |Tinkers' Archery              |tinkersarchery                |1.2.0               |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.129.jar                          |Just Enough Items             |jei                           |7.7.1.129           |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.16.5-10.0.22.449.jar                   |Mekanism                      |mekanism                      |10.0.22             |DONE      |Manifest: NOSIGNATURE
		ftb-dripper-1605.1.0-build.16.jar                 |FTB Dripper                   |ftbdripper                    |1605.1.0-build.16   |DONE      |Manifest: NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.2.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.2        |DONE      |Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.3.jar                        |Waystones                     |waystones                     |7.6.3               |DONE      |Manifest: NOSIGNATURE
		shutupexperimentalsettings-1.0.3.jar              |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.3               |DONE      |Manifest: NOSIGNATURE
		Placebo-1.16.5-4.6.0.jar                          |Placebo                       |placebo                       |4.6.0               |DONE      |Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |DONE      |Manifest: NOSIGNATURE
		TravelersBackpack-1.16.5-5.4.5.jar                |Traveler's Backpack           |travelersbackpack             |5.4.5               |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-13.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-13     |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.16.5-10.3.29.jar                |Bookshelf                     |bookshelf                     |10.3.29             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		u_team_core-1.16.5-3.2.1.196.jar                  |U Team Core                   |uteamcore                     |3.2.1.196           |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		iceandfire-2.1.9-1.16.5.jar                       |Ice and Fire                  |iceandfire                    |2.1.9-1.16.5        |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.16.5-10.0.22.449.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.22             |DONE      |Manifest: NOSIGNATURE
		toast-control-1_16_4-4_3_1.jar                    |Toast Control                 |toastcontrol                  |4.3.1               |DONE      |Manifest: NOSIGNATURE
		JEITweaker-1.16.5-1.0.1.35.jar                    |JEI Tweaker                   |jeitweaker                    |1.0.1.35            |DONE      |Manifest: NOSIGNATURE
		sodium-forge-2.9.10-rev.ea6353c.jar               |SodiumReforged                |sodium                        |2.9.10+rev.ea6353c  |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.16.5-0.12.1.127.jar         |Just Enough Resources         |jeresources                   |0.12.1.127          |DONE      |Manifest: NOSIGNATURE
		CraftTweaker-1.16.5-7.1.2.455.jar                 |CraftTweaker                  |crafttweaker                  |7.1.2.455           |DONE      |Manifest: NOSIGNATURE
		ProjectE-1.16.5-PE1.0.1B.jar                      |ProjectE                      |projecte                      |PE1.0.1B            |DONE      |Manifest: NOSIGNATURE
		dragonfight-1.7.jar                               |dragonfight mod               |dragonfight                   |1.7                 |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.26-universal.jar                |Forge                         |forge                         |36.2.26             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		tl_skin_cape_forge_1.16.5-1.19.jar                |TLSkinCape                    |tlskincape                    |1.19                |DONE      |Manifest: 19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		betterendforge-1.16.5-1.7.jar                     |BetterEnd Forge               |betterendforge                |1.16.5-1.7          |DONE      |Manifest: NOSIGNATURE
		world_generation_profiler-1.16.5-1.4.1.10.jar     |World Generation Profiler     |worldgenerationprofiler       |1.4.1.10            |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		ironchest-1.16.5-11.2.13.jar                      |Iron Chests                   |ironchest                     |1.16.5-11.2.13      |DONE      |Manifest: NOSIGNATURE
		CraftingTweaks_1.16.5-12.2.1.jar                  |Crafting Tweaks               |craftingtweaks                |12.2.1              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.26-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		cofh_core-1.16.5-1.3.1.jar                        |CoFH Core                     |cofh_core                     |1.3.1               |DONE      |Manifest: NOSIGNATURE
		thermal_foundation-1.16.5-1.3.2.jar               |Thermal Series                |thermal                       |1.3.2               |DONE      |Manifest: NOSIGNATURE
		TConstruct-1.16.5-3.3.2.324.jar                   |Tinkers' Construct            |tconstruct                    |3.3.2.324           |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.16.5-0.5.1.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.5.1        |DONE      |Manifest: NOSIGNATURE
		theoneprobe-1.16-3.1.4.jar                        |The One Probe                 |theoneprobe                   |1.16-3.1.4          |DONE      |Manifest: NOSIGNATURE
		appliedenergistics2-8.4.3.jar                     |Applied Energistics 2         |appliedenergistics2           |8.4.3               |DONE      |Manifest: 95:58:cc:83:9d:a8:fa:4f:e9:f3:54:90:66:61:c8:ae:9c:08:88:11:52:52:df:2d:28:5f:05:d8:28:57:0f:98
		thermal_innovation-1.16.5-1.3.0.jar               |Thermal Innovation            |thermal_innovation            |1.3.0               |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |DONE      |Manifest: NOSIGNATURE
		ToolBelt-1.16.5-1.16.0.jar                        |Tool Belt                     |toolbelt                      |1.16.0              |DONE      |Manifest: NOSIGNATURE
		endremastered-forge-R4.1.1.jar                    |End Remastered                |endrem                        |4.1                 |DONE      |Manifest: NOSIGNATURE
		towers_of_the_wild-1.16.4-2.0.1.jar               |Towers Of The Wild            |towers_of_the_wild            |1.16.4-2.0.1        |DONE      |Manifest: NOSIGNATURE
		Dimensional-Paintings-1.16.5-1.2.jar              |Dimensional Paintings         |dimpaintings                  |1.2                 |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.8.0.jar                   |Curios API                    |curios                        |1.16.5-4.0.8.0      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.2.jar                         |Patchouli                     |patchouli                     |1.16.4-53.2         |DONE      |Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.152.jar                         |Mantle                        |mantle                        |1.6.152             |DONE      |Manifest: NOSIGNATURE
		serverconfigupdater-1.3.jar                       |ServerConfig Updater          |serverconfigupdater           |1.3                 |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |DONE      |Manifest: NOSIGNATURE
		AkashicTome-1.4-16.jar                            |Akashic Tome                  |akashictome                   |1.4-16              |DONE      |Manifest: NOSIGNATURE
		thermal_expansion-1.16.5-1.3.0.jar                |Thermal Expansion             |thermal_expansion             |1.3.0               |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		harvest-1.16.3-1.0.3.jar                          |Harvest                       |harvest                       |1.0.3               |DONE      |Manifest: NOSIGNATURE
		tombstone-1.16.5-6.5.5.jar                        |Corail Tombstone              |tombstone                     |6.5.5               |DONE      |Manifest: NOSIGNATURE
		Quark-r2.4-322.jar                                |Quark                         |quark                         |r2.4-322            |DONE      |Manifest: NOSIGNATURE
		chunkpregenerator-v1.16-3.2.0.jar                 |Chunk Pregenerator            |chunkpregen                   |V1.16-3.2.0         |DONE      |Manifest: NOSIGNATURE
		structurize-0.13.219-ALPHA.jar                    |Structurize                   |structurize                   |0.13.219-ALPHA      |DONE      |Manifest: NOSIGNATURE
		cottonly-0.7.8.jar                                |Cottonly                      |cottonly                      |0.7.8               |DONE      |Manifest: NOSIGNATURE
		minecolonies-1.0.0-RELEASE-universal.jar          |MineColonies                  |minecolonies                  |1.0.0-RELEASE       |DONE      |Manifest: NOSIGNATURE
		architectury-1.22.32-forge.jar                    |Architectury                  |architectury                  |1.22.32             |DONE      |Manifest: NOSIGNATURE
		ftb-library-forge-1605.3.4-build.83.jar           |FTB Library                   |ftblibrary                    |1605.3.4-build.83   |DONE      |Manifest: NOSIGNATURE
		item-filters-forge-1605.2.5-build.9.jar           |Item Filters                  |itemfilters                   |1605.2.5-build.9    |DONE      |Manifest: NOSIGNATURE
		ftb-teams-forge-1605.2.2-build.30.jar             |FTB Teams                     |ftbteams                      |1605.2.2-build.30   |DONE      |Manifest: NOSIGNATURE
		ftb-chunks-forge-1605.3.2-build.115.jar           |FTB Chunks                    |ftbchunks                     |1605.3.2-build.115  |DONE      |Manifest: NOSIGNATURE
		kubejs-forge-1605.3.18-build.154.jar              |KubeJS                        |kubejs                        |1605.3.18-build.154 |DONE      |Manifest: NOSIGNATURE
		kubejs-mekanism-1605.1.2-build.2.jar              |KubeJS Mekanism               |kubejs_mekanism               |1605.1.2-build.2    |DONE      |Manifest: NOSIGNATURE
		kubejs-thermal-1605.1.4-build.2.jar               |KubeJS Thermal                |kubejs_thermal                |1605.1.4-build.2    |DONE      |Manifest: NOSIGNATURE
		ftb-quests-forge-1605.3.5-build.69.jar            |FTB Quests                    |ftbquests                     |1605.3.5-build.69   |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.16.x-2.1.0.jar                |AppleSkin                     |appleskin                     |mc1.16.4-2.1.0      |DONE      |Manifest: NOSIGNATURE
		kubejs-tinkers-1605.1.0-build.jar                 |KubeJS Tinkers                |kubejs_tinkers                |1605.1.0-build.9999 |DONE      |Manifest: NOSIGNATURE
		ferritecore-2.1.0-forge.jar                       |Ferrite Core                  |ferritecore                   |2.1.0               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		FallingTree-1.16.5-2.11.4.jar                     |FallingTree                   |fallingtree                   |2.11.4              |DONE      |Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		ftb-sluice-forge-1.0.7-build.22.jar               |FTB Sluice                    |ftbsluice                     |1.0.7-build.22      |DONE      |Manifest: NOSIGNATURE
		CobbleForDays-1.3.7.jar                           |Cobble For Days               |cobblefordays                 |1.3.7               |DONE      |Manifest: NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.49.jar                  |GeckoLib                      |geckolib3                     |3.0.49              |DONE      |Manifest: NOSIGNATURE
		ars_nouveau-1.16.5-1.23.11.jar                    |Ars Nouveau                   |ars_nouveau                   |1.23.11             |DONE      |Manifest: NOSIGNATURE
		drinkbeer-1.16.5-2.3.5.jar                        |Drink Beer                    |drinkbeer                     |2.3.5               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 6638d2da-33d2-42cd-a26a-af107b607aef
	Patchouli open book context: n/a
	Player Count: 2 / 8; [ServerPlayerEntity['JustDudeIt'/401, l='ServerLevel[Тест 0.8]', x=-1926.84, y=62.07, z=-749.39], ServerPlayerEntity['Riop'/34063, l='ServerLevel[Тест 0.8]', x=-2258.43, y=72.00, z=-1215.16]]
	Data Packs: vanilla, mod:inventorysorter (incompatible), mod:rhino, mod:mowziesmobs (incompatible), mod:ftbjarmod (incompatible), mod:trashslot (incompatible), mod:tinkersarchery, mod:jei, mod:mekanism, mod:ftbdripper (incompatible), mod:bettercaves (incompatible), mod:waystones (incompatible), mod:shutupexperimentalsettings (incompatible), mod:placebo (incompatible), mod:citadel (incompatible), mod:travelersbackpack (incompatible), mod:yungsapi, mod:bookshelf, mod:uteamcore, mod:iceandfire (incompatible), mod:mekanismgenerators, mod:toastcontrol (incompatible), mod:jeitweaker, mod:sodium (incompatible), mod:jeresources, mod:crafttweaker, mod:projecte, mod:dragonfight, mod:forge, mod:tlskincape (incompatible), mod:betterendforge, mod:worldgenerationprofiler, mod:ironchest, mod:craftingtweaks (incompatible), mod:cofh_core (incompatible), mod:thermal (incompatible), mod:tconstruct, mod:farmersdelight, mod:theoneprobe, mod:appliedenergistics2 (incompatible), mod:thermal_innovation (incompatible), mod:mousetweaks, mod:toolbelt (incompatible), mod:endrem, mod:towers_of_the_wild, mod:dimpaintings, mod:curios, mod:patchouli (incompatible), mod:mantle (incompatible), mod:serverconfigupdater (incompatible), mod:autoreglib (incompatible), mod:akashictome, mod:thermal_expansion (incompatible), mod:harvest (incompatible), mod:tombstone, mod:quark (incompatible), mod:chunkpregen, mod:structurize, mod:cottonly, mod:minecolonies (incompatible), mod:architectury, mod:ftblibrary, mod:itemfilters, mod:ftbteams, mod:ftbchunks, mod:kubejs, mod:kubejs_mekanism, mod:kubejs_thermal, mod:ftbquests, mod:appleskin, mod:kubejs_tinkers, mod:ferritecore (incompatible), mod:ftbsluice (incompatible), mod:cobblefordays (incompatible), mod:bettermineshafts, mod:geckolib3 (incompatible), mod:ars_nouveau, mod:drinkbeer, mod:fallingtree
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'`

**Comment by XionioXMaster** [comment]
tinkersarchery mod

**Comment by AlexModGuy** [comment]
at tonite.tinkersarchery
