### ISSUE TITLE
[1.12.2] Game crashes when attempting to use dragon horn [ICE AND FIRE VERSION 1.9.1]

### ISSUE THREAD

**Issue by Kingmiami** [Alex-the-666/Ice_and_Fire#4418]
When using dragon horn, my game crashed.

**To Reproduce**
1. Use Dragon Horn
2. See error

**Expected behavior**
This was my first time using the dragon horn item, I was unsure what was supposed to happen.

**Additional context**
[crash-2022-02-25_22.43.58-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/8145843/crash-2022-02-25_22.43.58-client.txt)

**Comment by StickyFruitSnacks** [comment]
I am having the exact same problem. I would really like if you could fix it please.

It appears to be a java.lang.NullPointerException within com.github.alexthe666.iceandfire.item.ItemDragonHornActive.func_77615_a(ItemDragonHornActive.java:124)

I have attached my crash report as well.
[crash-2022-03-17_19.37.31-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/8308257/crash-2022-03-17_19.37.31-server.txt)
