### ISSUE TITLE
game keeps cashing while attacking or riding dragon [1.16.5]

### ISSUE THREAD

**Issue by FellLazari** [Alex-the-666/Ice_and_Fire#4420]
Crash message:The game crashed whilst rendering entity in world
Error: java.util.NoSuchElementException: null
Exit Code: -1

mods : Alex mobs 1.8.0
Biomes o plenty 13.1.0.485
carryon 1.15.5.22
Citadel 1.8.1
doggytalents 2.1.14
dungeoncrawl 2.3.5
geckolib 3.0.64
ice and fire 2.1.8 (also crashes on 2.1.9)
Jouneymap 5.7.3
More player models 
nature compass 1.9.1
project E 1.0.1B
The graveyard mod 2.1
Travelers backpack5.4.6
[crash-2022-03-02_10.46.49-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/8168974/crash-2022-03-02_10.46.49-client.txt)

**Comment by DigitalWendigo** [comment]
The crashlog mentions the Racoon from Alex's mobs. Maybe put this issue in that mod's github instead.

**Comment by DigitalWendigo** [comment]
This isn't an ice and fire issue. 
This is related to Alex's mobs Racoon. 
Please report this issue on that mod's issue tracker instead. 
This issue can safely be closed as it's not related to ice and fire.
