### ISSUE TITLE
Seeing particles though solid blocks

### ISSUE THREAD

**Issue by GhostLupine** [Alex-the-666/Ice_and_Fire#4421]
I keep seeing particles through blocks, and it seems to only be particles from ice and fire that I see. I thought it was Optifine doing it, but after uninstalling it, there seemed to be no change. By ice and fire particles, I also mean hydra breath and dragon breath, not just pixie particles. I'm using 1.16.5 version 2.1.9 if this info is useful
![2022-03-02_09 38 37](https://user-images.githubusercontent.com/98993704/156395675-a2c5e896-d117-4135-8718-1c6ba9ea389b.png)

**Comment by DigitalWendigo** [comment]
Do you use any performance mods?
I can't remember exactly, but I think it was an optifine setting that needed to be disabled. 
I had this issue with another mod, and it let me see chests from that mod through walls until I disabled it. 
I think it was fast render..?

**Comment by GhostLupine** [comment]
I got this issue fixed. It was a mod that showed damage numbers. It was just called damage numbers I believe.

**Comment by HyperCodec** [comment]
Having a similar issue with embeddium/oculus. They sometimes render as black squares, always render through terrain.

Also happens with those bird things from Mowzie's Mobs
