### ISSUE TITLE
Broken dragon wings

### ISSUE THREAD

**Issue by Azzarg** [Alex-the-666/Ice_and_Fire#4439]
In the 1.16.5. version, dragon's wings break during certain poses. Most noticeably during the animation where they stand up and spread their wings. It always breaks in the same way.

On the left hand, the pointer and middle fingers will flip 180°, disconnecting the wing membrane from the remaining fingers. On the right hand, a piece of dactylopatagium disconnects from the hand and replaces the thumb, and another piece clips though the bicep.

Although mods are seen on my image, the issue persists even if I run no other mods except Ice and Fire. It happens consistantly reguardless of mod list, environment, or pose.
![20220330_142843](https://user-images.githubusercontent.com/89182296/160948704-ee4ec1d1-8088-49e5-9ef1-d51e2de6b8d1.jpg)

**Comment by TheBv** [comment]
Will be fixed in the next release #4245
