### ISSUE TITLE
Unhatching Eggs and Broken Dragon Horn

### ISSUE THREAD

**Issue by ClockyVaudeville** [Alex-the-666/Ice_and_Fire#444]
No matter what I do I cannot get the eggs to hatch, I know they're in enough space to hatch because I put my ice dragon egg in the middle of a frozen lake and destroyed the pillar I made underneath it to place the egg on. I've tried everything I can think of an if the mod creator could help me that'd be great. Also I don't think the dragon horn works, I had one successful hatch before now and my dragon flew away, I couldn't summon her back with the horn. I'm in the 1.10.2 version of the mod.

**Comment by PlatinumFox** [comment]
The dragon horn is not meant to call a dragon back. It is meant to store the dragon inside for easy travel. And if I remember correctly ice dragon eggs in particular where really buggy in that version. Try updating to the latest 1.12.2 version. (It has lots of cool new things)

**Comment by ClockyVaudeville** [comment]
I want my dragon mounts too though and that's still 1.10 I think, although I suppose if I have to all my other mods are 1.12 so...

**Comment by PlatinumFox** [comment]
@ClockyVaudeville If you must have something like dragon mounts here you go. (http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/wip-mods/2878357-realm-of-the-dragons-1-10-2-1-12) but i do recommend sticking with just I/F as it is probably the best dragon (and mythical) mod there will ever be.
