### ISSUE TITLE
Gorgon Statues Crash

### ISSUE THREAD

**Issue by Beaversforlife12** [Alex-the-666/Ice_and_Fire#4440]
A player statue causing me or anyone who is close to it to crash upon loading the game. 

1. Use gorgon statue in creative mode on a player in creative mode
2. Crash

The crash says "overload"

![image](https://user-images.githubusercontent.com/72292151/161394175-0afa6992-f79f-41d9-87af-e6ff15ad4e01.png)
Image shows me crashing infront of the statue

**Comment by XionioXMaster** [comment]
Provide logs, crash-report

> A player statue causing me or anyone who is close to it to crash upon loading the game.
> 
> Steps to reproduce the behavior:
> 
> 1. Use gorgon statue in creative mode on a player in creative mode
> 2. Crash
> 
> The crash says "overload"
> 
> ![image](https://user-images.githubusercontent.com/72292151/161394175-0afa6992-f79f-41d9-87af-e6ff15ad4e01.png) Image shows me crashing infront of the statue

**Comment by DigitalWendigo** [comment]
Logs, crash report and a mod list.

**Comment by TheBv** [comment]
Probably related to crashes regarding too much nbt data in stone statues. Has been addressed in recent commits.
