### ISSUE TITLE
Server overloaded/lags (1.15.2)

### ISSUE THREAD

**Issue by n0k1234** [Alex-the-666/Ice_and_Fire#4441]
Everytime i face a dragon the minecraft server is overloaded.

1. Face any dragon
2. Start the combat
3. Lags

**Additional context**
Minecraft 1.15.2
iceandfire-2.1.0-1.15.2
citadel-1.1.11
forge-1.15.2-31.2.0
![test](https://user-images.githubusercontent.com/103112411/161955061-fb32ea46-0b21-422e-9a02-d82d5021a098.jpg)

**Comment by littlepianist** [comment]
I am kind of sure that 1.15.2 is NEVER going to recive updates/fixes, just move on to 1.16.5
