### ISSUE TITLE
Eggs disappearing bug

### ISSUE THREAD

**Issue by Chiseris** [Alex-the-666/Ice_and_Fire#4442]
My husband got a couple eggs from some stage 5 dragons and we were trying to hatch them, however, the dragon egg would freeze like it should and then the ice would crack and the egg would be gone. We've tried it with multiple eggs we've gotten and each and every one just disappears after starting the initial hatch sequence.

**Comment by DigitalWendigo** [comment]
What performance mods are you using?
I had this issue whilst using Sodium reforged. 
Going over to optifine doesn't seem to reproduce this issue for me. 
Also, did either of you leave the area while the dragon egg was going through the process?

**Comment by Chiseris** [comment]
> What performance mods are you using? I had this issue whilst using Sodium reforged. Going over to optifine doesn't seem to reproduce this issue for me. Also, did either of you leave the area while the dragon egg was going through the process?

I don't use Sodium Reforge, not even sure what that is lol. I only use optifine but I've never had the issue with eggs before when using it. We don't leave the area, we sit there and wait and not even a couple seconds pass and it does the egg hatching sound but nothing.

**Comment by DigitalWendigo** [comment]
THis is a whild shot, but try reproducing this in a creative testing world and disable the optifine feature 'fast math' and 'fast render'. 
Also, are there any mods installed that alter mob spawning, conditions or anything of the sort?

**Comment by DigitalWendigo** [comment]
A list of the mods you have installed might help. Or a link to the modpack.

**Comment by DigitalWendigo** [comment]
Has the issue been resolved for you or is it still an issue?
If it's still an issue then please provide a full list of your mods and a log file. 
I also suggest updating to the new Alpha release, found here: https://github.com/Alex-the-666/Ice_and_Fire/releases/tag/2.1.10-alpha2 
It has several bug fixes and improvements and it might help your case as I've tested it with either of the performance mods mentioned and this is no longer an issue in the latest Alpha. 
Before updating though, I highly suggest you make a backup of the server/world.

**Comment by Chiseris** [comment]
> Has the issue been resolved for you or is it still an issue? If it's still an issue then please provide a full list of your mods and a log file. I also suggest updating to the new Alpha release, found here: https://github.com/Alex-the-666/Ice_and_Fire/releases/tag/2.1.10-alpha2 It has several bug fixes and improvements and it might help your case as I've tested it with either of the performance mods mentioned and this is no longer an issue in the latest Alpha. Before updating though, I highly suggest you make a backup of the server/world.

It hasn't been resolved, however, my husband and I are expecting our first child so we shut down our server to cut back on costs for the arrival of our baby. This thread can be closed since we probably won't be coming back to Minecraft for a while.
