### ISSUE TITLE
Only gorgon temples mausoleums and graveyards spawning nothing else.

### ISSUE THREAD

**Issue by jaykay0972** [Alex-the-666/Ice_and_Fire#4443]
I tried many times and it doesnt work i use as other mods: ore excavation veinminer and other please help me out

**Comment by XionioXMaster** [comment]
I didn’t quite understand what your problem is, everything is fine with me, maybe you are using a mod for a new generation of the world

**Comment by DigitalWendigo** [comment]
Please provide your modlist and what version you are playing on.

**Comment by DigitalWendigo** [comment]
If you've resolved this issue then this should be closed. 
It's likely a result of another terrain generator messing with the spawning conditions. 
Furthermore there is not enough information present to provide any help on the matter. 
If it hasn't been resolved for you, please provide a log file and your mod list. 
In case you're using a terrain altering mod that either changes how terrain generates overall or adds new biomes, then you will need to add the custom biomes to the respected ice and fire biome.json files indvidually.
