### ISSUE TITLE
Ice dragonsteel ability makes mobs visible through walls. [Mod Version 2.1.9]

### ISSUE THREAD

**Issue by GhostLupine** [Alex-the-666/Ice_and_Fire#4448]
So I've noticed something when I use the Ice Dragon Sword, the dragon bone and dragonsteel one. When I kill a mob with it, when it has the frozen effect over it, I see mobs through blocks when the mob dies. I don't know what it is, but it might be a conflict with a mob, and I wish Minecraft would just tell me what it is.

First I just went into a creative world to mess around to kill mobs with an ice dragonsteel sword, since it's my favorite weapon. Then I start killing things and see mobs through blocks when they die.

![2022-04-22_22 34 48](https://user-images.githubusercontent.com/98993704/164873774-dd7070e8-28e9-49a1-b041-673fb1657293.png)

**Comment by TheBv** [comment]
Do you happen to have any client performance mod installed? Anything that could change/optimize how mobs get rendered could be causing this. If you can give me a narrow list of possible mods I would be able to investigate this further.

**Comment by GhostLupine** [comment]
I am using optifine with the fresh animations resource pack. And it seems optifine was the issue. It may be a setting in optifine I'm not aware of or it was just that entirely. If that's the case, could I use Magnesium instead of Optifine?

**Comment by TheBv** [comment]
I don't know. I'm not sure how much these mods change how things get rendered.
I did try the newest version of OptiFine (G8) and it seemed to be fine but that might've just been a coincidence.
All you can do is try :v

**Comment by GhostLupine** [comment]
I'm using the same version of optifine, this is so weird. I also tried it without the fresh animations mod and the issue was still there.

**Comment by DigitalWendigo** [comment]
It's probably the 'fast render' option of OptiFine. 
I've personally had several cases where entities and tile entities become visible through walls. 
Turn that off and see if the issue persists.

**Comment by GhostLupine** [comment]
After testing, it seems that fast render enabled was the issue. It doesn't seem to make entities visible through walls anymore. Thank you guys for the help!
