### ISSUE TITLE
Dread Thrall Armors are invisible [1.16.5]

### ISSUE THREAD

**Issue by LeetleMay** [Alex-the-666/Ice_and_Fire#4449]
Every single dread thrall is naked.
They no longer have their unique armor.
![image](https://user-images.githubusercontent.com/104390244/165160292-f2f1e0b4-3b5b-48c0-a8e3-fa9d953b6399.png)

**Comment by DigitalWendigo** [comment]
Are you using any other mods that alter attributes or mobs in any for or way?
I also distinctly rememer that the difficulty setting greatly affects the chance of mobs spawning with armor.

**Comment by TheBv** [comment]
The armor is purely cosmetic and loaded in dynamically. Or at least it used to be but isn't anymore. I'll have a fix for this ready soon :)

**Comment by LeetleMay** [comment]
> The armor is purely cosmetic and loaded in dynamically. Or at least it used to be but isn't anymore. I'll have a fix for this ready soon :)

Thank you very much !

**Comment by LeetleMay** [comment]
Let me know when the fix is up

**Comment by TheBv** [comment]
Fix is up. I think it will take some time before a new version of Ice and Fire gets released though.
I've built the current project on my [fork](https://github.com/TheBv/Ice_and_Fire/releases) of this repository
