### ISSUE TITLE
 no exp and loot. 

### ISSUE THREAD

**Issue by Rothern** [Alex-the-666/Ice_and_Fire#445]
Hey.
Recently I have reduced the number of appearing dragons. However, I noticed the problem that after I defeat the dragon, I do not get experience for him, as well as scales and bones. I can only take blood from my body.

In addition, he would like to ask if it is possible to remove the skeletons of already defeated creatures?

I play on my own multiplayer server, version 1.12.2, from forge.

**Comment by estradus** [comment]
to get loot from them, right click on the body with an empty hand, and loot will come off. when it's a skeleton you can keep right clicking it for bones and eventually the skull, at which point the skeleton finally dissappears.

No idea how to get experience from them, though.

**Comment by AlexModGuy** [comment]
experience is cacluated by
5 + dragon's stage X 25
