### ISSUE TITLE
Gravestone Mod

### ISSUE THREAD

**Issue by Ruidolph** [Alex-the-666/Ice_and_Fire#446]
When the dragons kill you, even if you have the gravestone mod, your items drop onto the ground. Which is aggravating because the fire dragons can light your items on fire and destroy them.

**Comment by Ruidolph** [comment]
Or make Gravestones immune to dragon fire.

**Comment by PlatinumFox** [comment]
~~(Assuming you're talking about the gravestone mod by NightKosh: http://gravestone.nightkosh.com/)
It is NightKosh's job to add compatibility for gravestones to hold I/F items.~~

**Comment by PlatinumFox** [comment]
must be a different gravestone mod as the one above works perfectly fine with I/F.

**Comment by Ruidolph** [comment]
https://minecraft.curseforge.com/projects/gravestone-mod This is the gravestone mod that I was talking about o:

**Comment by PlatinumFox** [comment]
Its been a while but ive used that one before. yes the gravestone mod author will have to add compatibility for I/F Items. shouldn't be a problem for Alex. for now use the other one i sent above.
