### ISSUE TITLE
[2.1.9 - 1.16.5] Dragons that spawn in roosts directly on the X / Z axis will not pathfind to their roosts

### ISSUE THREAD

**Issue by Flashbackmaniac** [Alex-the-666/Ice_and_Fire#4461]
**Bug description:**
I've noticed this bug a few times, but I didn't pay much attention until I decided to mess around with the roost / cavern generation chance set to very high. When a dragon roost generates directly on an axis (Examples: 800, 0 on the X-axis or 0, 800 on the Z-axis), the dragon will fail to pathfind back to its roost. Instead, they will continue to fly to 0, 0 (and presumably 0 on the Y-axis as well) and treat that as their home position.

**Steps to reproduce the behavior:**
1. To increase the chances of this bug occurring, turn up the dragon roost chance so that enough roosts can generate to observe the bug.
2. Load up a new world and look for a dragon roost that is directly on the X-axis or the Z-axis. If one is found, notice that the dragon that spawns there starts flying away from its roost towards 0, 0 rather than patrol its surroundings.

**Expected behavior:**
I expected the dragon to wander around its roost and, if too far from the wander distance set in the main Ice and Fire config, move back to within that distance or return to the roost when it's time for it to sleep.

**Addendum:**
This bug appears to happen only with dragons that spawn in roosts since they have a home position set to a roost for pathfinding purposes (like the aforementioned wander distance and returning to the roost to sleep).

**Comment by DigitalWendigo** [comment]
Is this happening in a vanilla environment with just citadel and ice and fire installed?
Or are there other mods installed that might in any way or form alter dragon AI?
If so, please provide a list of your mods and potential log files. 

This doesn't seem to happen in the Alpha2 release. 
Probably a result of the Ai pathfinding fixes and improvements. 
Try to update to that version and see if the issue persists for you. 
https://github.com/Alex-the-666/Ice_and_Fire/releases/tag/2.1.10-alpha2

**Comment by Flashbackmaniac** [comment]
The bug appears to be addressed in one of the 2.1.10 snapshot releases. I'm closing the issue but I will look out if it crops up again.
