### ISSUE TITLE
Small Animals from Mods become invisible statues

### ISSUE THREAD

**Issue by lSherozl** [Alex-the-666/Ice_and_Fire#4464]
If you use the gorgon head on any small enough animal, it will turn into an invisible statue, that can be picked up if u mine the same spot, but then when placing down becomes invisible again. This happens with any small animals from mods. For example: a sparrow or swallow from exotic birds mod, or a lizard from another mod I forgot the name of.

**Comment by DigitalWendigo** [comment]
Are you using optifine or entity culling?
Also, what version are you using?

**Comment by lSherozl** [comment]
I am using version 1.16.5, I am not using optifine, but this is with the better Minecraft pack, which I believe has magnesium, which I believe is a forge port of sodium

**Comment by lSherozl** [comment]
> Are you using optifine or entity culling? Also, what version are you using?

The mod works fine with any and I mean any medium to large animal from other mods, even the snake from alex mobs, but anything smaller, most of the time becomes an invisible statue, I was playing on the better Minecraft plus modpack

**Comment by DigitalWendigo** [comment]
I'm looking at the modpack right now. 
I'd also suggest to put up an issue with the modpack itself so that the maker of it is aware of the bug. 
They may even have some insightful info if they are already aware of it. 

I'm also assuming you haven't changed anything about the modpack yourself?

**Comment by lSherozl** [comment]
Nope all settings are the same, I do have the exotic birds mod tho, which isnt in the original pack, but it seems to be the case for most small animals, even the ones by default in the pack, you could try adding the mod and trying to turn a small bird into stone and telling me if it worked for u https://www.curseforge.com/minecraft/mc-mods/exotic-birds

**Comment by DigitalWendigo** [comment]
Can you tell me which mobs specifically become invisible? 
From which mod and which specific mobs by name?

**Comment by TheBv** [comment]
The birds from the exotic bird mods seem to work fine - even with optifine and fast rendering.
Either it's models from a specific mod or a mod modifies minecraft's default model render system.
![image](https://user-images.githubusercontent.com/12676257/166105854-6ae2ddb4-6fca-43a4-bbcc-a5609685433a.png)

**Comment by lSherozl** [comment]
> The birds from the exotic bird mods seem to work fine - even with optifine and fast rendering. Either it's models from a specific mod or a mod modifies minecraft's default model render system. ![image](https://user-images.githubusercontent.com/12676257/166105854-6ae2ddb4-6fca-43a4-bbcc-a5609685433a.png)

I am going to open Minecraft and do this for you, so you can see, sorry if I didn't give enough information

**Comment by lSherozl** [comment]
> Can you tell me which mobs specifically become invisible? From which mod and which specific mobs by name?

Im sorry exotic birds works fine, I must of gotten the animals mixed up....this is the mods I want you to try, please try the lizard from the creatures n beasts mod, and please try the swallow from frikinzi fauna......https://www.curseforge.com/minecraft/mc-mods/creatures-and-beasts and https://www.curseforge.com/minecraft/mc-mods/creatures

**Comment by lSherozl** [comment]
![279388235_1713838485630604_5300037941757878995_n](https://user-images.githubusercontent.com/65663746/166121054-973cbafb-fa33-4cf6-8217-a3e17d9a1b5c.jpg)
Here is an image showing the weird statues they become, and you can pick them up but cant place them down

**Comment by TheBv** [comment]
Both of these mods use geckolib for easier model rendering which deviates from how minecraft/iceandfire do their model/rendering stuff. Basically the statue renderer is checking if the model is either a minecraft model or an iceandfire one and only then renders it.
The easiest solution would be to render a placeholder in those cases since otherwise one would have to incorporate geckolib as a dependency. 
I'll go ahead and do that.

**Comment by lSherozl** [comment]
> Both of these mods use geckolib for easier model rendering which deviates from how minecraft/iceandfire do their model/rendering stuff. Basically the statue renderer is checking if the model is either a minecraft model or an iceandfire one and only then renders it. The easiest solution would be to render a placeholder in those cases since otherwise one would have to incorporate geckolib as a dependency. I'll go ahead and do that.

Thank you
