### ISSUE TITLE
a

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#4469]
a

**Comment by DigitalWendigo** [comment]
It might be open terrain generator. 
If you're using a preset, it might conflict with how dragon dens spawn. 
Try to reproduce this issue with vanilla terrain generation in a temporary test world.

Another thing I can think of is biomes o plenty. I've personally not used that mod too often, but I have used 'oh the biomes you'll go'. In which case, I needed to add the new biomes from that mod, to the biome spawning conditions of each ice and fire mob inside the ice and fire folder.

**Comment by fallenthereaper** [comment]
1.12 is no longer supported

**Comment by DigitalWendigo** [comment]
This can also probably be closed. 
No point in keeping issues open on versions that are no longer being supported.

**Comment by DigitalWendigo** [comment]
As a side comment on the issue before it's closed. 
Try adding the cave biome id's to the respective dragon biome.json files found inside config/iceandfire.
Custom biomes need to be added manually to the ice and fire creatures .json files for them to spawn in said biomes.
