### ISSUE TITLE
[2.1.9 - 1.16.5] [Bug Report / Suggestion] Dread Lich spawn rates by default are too low

### ISSUE THREAD

**Issue by Flashbackmaniac** [Alex-the-666/Ice_and_Fire#4472]
**Description:**
This is less of a bug and more something I've noticed. I understand that Dread Liches have a low spawn rate to make their coveted Mausoleum Key something to work towards in order to get inside the mausoleums, but I feel like the default spawn rate for them is way too low. From what I've seen, players were reporting that they had to wait countless days in snowy biomes just for a single Dread Lich to spawn. The usual solution offered was either to bump up the spawn rate in the main config or using glitches to get into the mausoleum.

I took a look in the main config and found out that the default spawn rate for Dread Liches was 2. I'm no expert when it comes to how mob spawning works, but if this value was to be increased, I'm not sure what the new default value would be that would be sensible and still be somewhat rare to offset the rewards that a mausoleum has inside.

**Addendum:**
Another thing I've noticed is that while other Ice and Fire mobs have dedicated JSON files for biomes that they are allowed to spawn in, I did not find any for the mobs related to the mausoleums if one wants to edit where they spawn (Dread Liches, Dread Scuttlers, and Dread Thralls, for example).

**Comment by DigitalWendigo** [comment]
That's what the config is for, to let players decide if they want to make it easier or harder to get inside the structure. 
Bumping up the numbers by default would inevitably lead to another suggestion where they need to be lowered again, which of course will again be met with similar answers to configure it yourself. 
I by no means wish to come off as rude by saying this, but I believe the numbers should remain as they are and only be altered by the players in question depending on their aim and/or needs. 

For the biome config files to better control where the dread liches spawn, I do agree that this would be a nice feature to have. 
Especially if one is to place the respective ice and fire creatures/structures in a different dimension/biome.

**Comment by Flashbackmaniac** [comment]
The issue with the low spawn rates was addressed with the Troll spawn rates (which were also abysmally low), but in this case, the mention of other players having the same issue with the low spawn rate of Dread Liches sound less than an isolated issue and more so that the spawn rate was too low to begin with.

I left the latter half of the report open-ended since that's where the ambiguity of how much the increase should be, since the potential rewards from killing Dread Liches are more valuable than that of Trolls.

**Comment by DigitalWendigo** [comment]
Could you perhaps change the title to a suggestion for a better clarification?
Since this seems more like a suggestion than anything else.

**Comment by TheBv** [comment]
I think part of the issue is that one can currently only adjust the spawn weight (for more look up weighted randomness) for the mob. So if a mod adds a bunch more entities to a given area the spawn rate will get thrown off quite a bit.
Second issue is that there's a second check (1/40 chance) that a lich can't spawn. This works similar to the troll config.
I'll be adding another value to the config to address this issue so people have better control over it.

**Comment by Flashbackmaniac** [comment]
The Dread Liches' spawn weight being low was something I knew about and that people would tell others to turn up if they want to make them more common, but I wasn't aware that there's an additional check for their spawning. I agree that an additional config setting would be helpful for alleviating the issue.
