### ISSUE TITLE
Ampithere stuck in a permanent attack loop while ridden. 1.16.5 Alpha2 release. 

### ISSUE THREAD

**Issue by DigitalWendigo** [Alex-the-666/Ice_and_Fire#4473]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
When riding a tamed Ampithere, they get stuck in an infinite attack loop. Meaning while riding them, anything that comes within close proximity of its melee range will get mauled. 
This can not be disabled. 

**To Reproduce**
Play the game in either a vanilla or modded environment while having ice and fire 1.16.5 Alpha2 release installed. 

**Expected behavior**
The ampithere should only do a melee attack when the corrosponding key is pressed. 

**Screenshots**
Couldn't provide one because a screenshot won't really visually represent the issue. 

**Additional context**
None that I can think of. 

The log file doesn't mention anything either.

**Comment by Theblimp** [comment]
I am experiencing the same thing. Also playing the Alpha2 release
