### ISSUE TITLE
Dread mob spawners in mausoleums spawn empty. 1.16.5 Alpha2 release. 

### ISSUE THREAD

**Issue by DigitalWendigo** [Alex-the-666/Ice_and_Fire#4474]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
When entering the mausoleum, all spawners inside appear to be completely empty blank spawners. 

**To Reproduce**
Find a mausoleum only to to then not get greeted by anything inside. 
No mobs to hinder the player. 

**Expected behavior**
The spawners inside the structure appear to be empty, causing nothing to spawn. 

**Screenshots**
![2022-05-09_23 02 16](https://user-images.githubusercontent.com/103202053/167489070-3b5e4d90-293c-4ac5-aad4-6e535bc929e5.png)

**Additional context**
None.

**Comment by Theblimp** [comment]
Experiencing the same issue. Also playing the Alpha2 release
