### ISSUE TITLE
Certain blocks added to dragon-break blacklist not working correctly. 1.16.5 Alpha2 release.

### ISSUE THREAD

**Issue by DigitalWendigo** [Alex-the-666/Ice_and_Fire#4475]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
After adding certain items to the blacklist of what dragons can't break, they can still be broken. 
Currently the only known block that doesn't seem to work as intended is the minecraft Hopper. 

**To Reproduce**
Add "minecraft:hopper" to the blacklist. 
See that it's still broken by ice dragons's breath. Resulting in an ice spike spawning in the hoppers place. 

**Expected behavior**
The hopper to not be destroyed. 

**Screenshots**
None.

**Additional context**
Might need further testing considering only the hopper is currently not working for the blacklist. 
But it might also be some other modded blocks in the future. 

Using minecraft 1.16.5, 
Ice and fire 1.16.5 the Alpha2 release.

**Comment by Theblimp** [comment]
can confirm this also happens to me on the alpha2 release
