### ISSUE TITLE
Ice and Fire 2.1.9-1.16.5 config issues 

### ISSUE THREAD

**Issue by RadsJog** [Alex-the-666/Ice_and_Fire#4476]
When I edit the config it doesn't applied to the server I have restarted the server 5-6 times saved the config several times and also config automatically gets edited

**Comment by TheBv** [comment]
If the config gets edited that means that either the values are malformatted or the file itself.
Make sure to not add any extra spaces/line breaks as well as to be aware of capitalization and decimal spaces.
