### ISSUE TITLE
Hearts appearing when dragon egg is destroyed by a player with strength [2.1.10-1.16.5-SNAPSHOT+build.2022-5-11]

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#4479]
when the player destroys the dragon egg with strength effect on, damage hearts will appear, and additional damage sound when the level is high enough (tested at strength 20)
![image](https://user-images.githubusercontent.com/41582097/167826076-dac19568-5361-44be-9b46-8eb1f89ce90e.png)

**Comment by DigitalWendigo** [comment]
Isn't this intentional? 
I recall this happened in 2.1.9 as well. 
It doesn't affect gameplay nor causes issues.

**Comment by ghost** [comment]
intentional? thats weird

**Comment by DigitalWendigo** [comment]
This can probably be closed since it's not a bug.
