### ISSUE TITLE
[2.1.9 - 1.16.5] Dragon Corpses are unable to be targeted by commands

### ISSUE THREAD

**Issue by Flashbackmaniac** [Alex-the-666/Ice_and_Fire#4483]
**Bug description:**
As the title says, dragon corpses are unable to be targeted by commands. This could potentially lead to annoying scenarios where dragon corpses are unable to be removed in places where the player cannot physically go up to and harvest them (the only method to remove said corpses in I/F version 2.1.9 - 1.16.5). An example of this is a dragon corpse in the void past the point where the player starts taking damage. Going too far downwards would still kill the player even in Creative mode.

**Steps to reproduce the behavior:**
1. Summon some dragons, then kill them.
2. Try using some commands on the dragon corpses, such as /kill @e[type=iceandfire:ice_dragon] or /tp @e[type=iceandfire:ice_dragon] <username>.
3. Notice that dragon corpses are unable to be targeted by the commands inputted.

**Expected behavior:**
I expected being able to use commands on dragon corpses like any other entity.

**Additional context:**
This bug seems to have surfaced in I/F version 2.1.7 - 1.16.5, where a change prevented entities from targeting dead dragons. Dragon skeletons that are generated with the world, however, are still able to be targeted by entities, and oddly enough, said skeletons could be targeted normally by commands. From my playthroughs, this bug was present since that version all the way to the latest I/F version 2.1.10 development build (as of this typing, the build from 5/11/22).

**Comment by DigitalWendigo** [comment]
Have you tried to reproduce this in the new Dev build? 
https://github.com/Alex-the-666/Ice_and_Fire/releases/tag/latest-snapshot 

Please do make a backup of your world before using an Alpha/Dev build.

**Comment by Flashbackmaniac** [comment]
As stated in the original post, I noted that the bug is present in the 5/11/22 development build. The testing was done on a new world.

**Comment by TheBv** [comment]
The dragon can't be selected because minecraft thinks it is "dead"/ isn't alive.
Most mobs default way to check if an entity is attackable is to check if they are alive or not.
Previously mobs were attacking dead dragon corpses (see [this](https://github.com/Alex-the-666/Ice_and_Fire/issues/3600)) and to solve that issue the way to check if a dragon is alive or not was changed.
Minecraft commands can only target entites who are alive.

I don't see a way to fix this without the downside of entities attacking dead dragon corpses.
There is probably a way one might be able to do this but the effort currently isn't worth it for me

**Comment by Haonanzd** [comment]
I encountered the same issue when I tried to remove hundreds of both ice and fire dragon corpses I summoned for testing purposes. 
After massive digging I found a temporary solution by adding a mod: [worldedit](https://www.curseforge.com/minecraft/mc-mods/worldedit)
Use a command provided by this mod, which can get rid of both ice and fire dragon dead body and skeleton altogether:
`/butcher -f 100`
(meaning: kill all normal and friendly mobs within 100 radius)
