### ISSUE TITLE
Dragons having issue with /kill command [2.1.10-1.16.5-SNAPSHOT+build-2022-5-11]

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#4485]
- Dragon corpses will not be targeted when using /kill @e, /kill @e[type=!player], /kill @e[type=iceandfire:ice_dragon],... , though /kill @e or /kill @e[type=!player] won't kill the dragon corpses, any of the dragon hitboxes that isn't the dragon main hitbox will be killed. And you will need to use /kill [dragon main hitbox uuid] to kill dragon corpses. Additionally, you can use /kill [dragon body part hitbox uuid] to kill the dragon hitboxes without killing the dragon to create a living dragon that have only one hitbox. 
![image](https://user-images.githubusercontent.com/105374204/167976062-04585a9a-3840-4f67-9b14-0dea987de7a7.png)

**Comment by DigitalWendigo** [comment]
Seems similar to #4483

**Comment by ghost** [comment]
Well yeah, mine is just having a bit more information.

**Comment by TheBv** [comment]
Closing in favor of #4483
