### ISSUE TITLE
Dragon corpse isnt visible [iceandfire-1.9.1-1.12.2]

### ISSUE THREAD

**Issue by Gaminguide1000** [Alex-the-666/Ice_and_Fire#4488]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.
Chill
**Describe the bug**
Kill a dragon. You wont see the corpse. You will only see it, if you either reconnect to the server, or change the dimension. It seems to be a client bug, since when other players go to the same spot without having it loaded when the dragon died, they CAN see it.
**To Reproduce**
Find a dragon nest.
Kill the Dragon
Be annoyed because you need to reconnect
**Expected behavior**
I Wanna see the dragon pls
**Screenshots**

Before killing da dragon
![image](https://user-images.githubusercontent.com/63616197/168346246-aec9c213-3670-44cd-bd3d-f76d99bd43c4.png)
After killing the dragon (as you see, invisible)
![image](https://user-images.githubusercontent.com/63616197/168346255-44628af4-6543-4ab7-a3f9-25ca005ea3c7.png)
After reconnecting onto the server
![image](https://user-images.githubusercontent.com/63616197/168346454-edb9e41f-869e-46d6-8279-eec655b835c9.png)
![image](https://user-images.githubusercontent.com/63616197/168346495-8217da72-d1c8-4848-b611-c3d013a7c8d5.png)

**Comment by DigitalWendigo** [comment]
Unfortunately 1.12.2 is no longer supported. 
But as some general advice that has seemingly fixed similar issues for others, is to disable the mod called WAILA if you have it installed. 
Another potential culprit can also be optifine and/or entity culling. 
This issue is no longer present in the latest versions of IAF if not paired with Waila.

**Comment by Gaminguide1000** [comment]
Sad, i do like 1.12.2.. Still thanks for the Answer

**Comment by DigitalWendigo** [comment]
Please close this issue. Have a nice day.
