### ISSUE TITLE
java.lang.NullPointerException: mouseClicked event when trying to play single player or on server

### ISSUE THREAD

**Issue by Feral716** [Alex-the-666/Ice_and_Fire#4491]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
VERSION 1.16.5

Have 50 mods installed and all but ice and fire work fine, if I have ice and fire installed it no longer allows me to play at all as it gives me java.lang.NullPointerException: mouseClicked event. 

**To Reproduce**
not entirely sure on how or why the error occurs but it only does when I have ice and fire in my mods folder 

**Expected behavior**
all mods load, looks fine, click existing world or create new world, attempts to load, displays "saving world", crash. 

**Screenshots**
![image](https://user-images.githubusercontent.com/105568121/168450021-fe8370c1-2d6e-486f-b244-12cc6dd64d09.png)

**Additional context**
Picture above displays when I try to join my friends server which has exactly the same mods and has other people who are not having the same issues
[crash-2022-05-14_18.17.29-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/8693979/crash-2022-05-14_18.17.29-client.txt)

**Comment by TheBv** [comment]
Try deleting the `config/iceandfire` folder. Or all the `.json` files in it. E.g `amethyst_gen_biomes.json` etc. 
If that doesn't solve the issue please also add the `latest.log` / `debug.log` file as an attachment since that might reveal more information

**Comment by Feral716** [comment]
fixed my issue with single player but I still cant play on friends server, it just says disconnected and a big red X

**Comment by Feral716** [comment]
nvm its fixed, had to re download the mods
