### ISSUE TITLE
Ice dragon spawning in a lightning dragon cave

### ISSUE THREAD

**Issue by CursedDitto** [Alex-the-666/Ice_and_Fire#4492]
Alpha Release @.1.10_alpha3
seed 2029655006879426679
coords 49091 21 52037
![2022-05-15_15 15 05](https://user-images.githubusercontent.com/105383054/168477680-dbdf9571-5778-4034-b96b-5784afd81177.png)

**Comment by TheBv** [comment]
Do you happen to have set custom values in your config related to cave generation?
Either cave gen chance or dangerous structure distance could be relevant.
For me there isn't a cave at that coordinate.

**Comment by CursedDitto** [comment]
Yes, I forgot to type in the dragon generation chance,mb

"Generate Dragon Cave Chance" = 120

I changed it before I updated to the alpha release,so long ago that i don’t remember I had done it

**Comment by Flashbackmaniac** [comment]
I can confirm that this bug happens on my end as well. The I/F version I'm using is 2.1.10 - 1.16.5 Alpha 3.1. The main config file I'm using is vanilla, and I've seen this on a new world and a world that was preexisting prior to updating to this development build. In addition, I've seen fire dragon caves affected by this too, where their loot are replaced with those of the lightning dragon caves. Dragon roosts of the three elemental types are unaffected, and lightning dragon caves that generate correctly in their respective biomes are also unaffected.
