### ISSUE TITLE
Dread Spawners causing crash? [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by Syogren** [Alex-the-666/Ice_and_Fire#4493]
**Describe the bug**
It appears that the dread spawners are having issues being read as mob spawners

**To Reproduce**
1. Go near a dread spawner
2. Wait

**Expected behavior**
The game will crash and say "com.github.alexthe666.iceandfire.entity.tile.TileEntityDreadSpawner cannot be cast to net.minecraft.tileentity.MobSpawnerTileEntity"

**Comment by TheBv** [comment]
This is an issue with another mod that tries to incorrectly cast the custom dread spawner.

The log file in this issue #4293 had a similar error which was caused by `branders.spawnermod` which seems to be the enhanced mob spawner mod. They should implement a proper type check.
