### ISSUE TITLE
[2.1.10 - 1.16.5 Alpha 3.1] Hippogryph animation bug. 

### ISSUE THREAD

**Issue by DigitalWendigo** [Alex-the-666/Ice_and_Fire#4495]
The hippogryph seems to have an animation bug where at random moments. 
This seems to happen either while standing still, riding on the ground or just looking around. 
This only happens when it's ridden. 
It seems that the AI is trying to look at the player while it's being ridden, which initially causes this.

**To Reproduce**
1. Tame a hippogryph or have one tamed. 
2. Ride, move or pan the camera in any direction, at any angle. 
3. See the animation bug where it seems to almost do a full 360. 

**Screenshots**
![2022-05-16_17 33 09](https://user-images.githubusercontent.com/103202053/168618760-4073b3ac-a015-4379-8f6e-d7067c9aec80.png)

**Additional context**
Tested in both a vanilla environment with just citadel and IAF, and a separate modded environment. 
Logs will be provided if need be, but I'll exclude them for now since they do not show anything regarding the issue.

**Comment by zoriwuff** [comment]
I can't offer a fix but I wanted to second this bug for my game as well (ver 1.16.5 too). I haven't seen it been addressed yet.
