### ISSUE TITLE
Failed to load registry on multiplayer (opened on lan)

### ISSUE THREAD

**Issue by aryana1445** [Alex-the-666/Ice_and_Fire#4497]
So after a few hours of playing on a lan world with another pc on relogging i get

[14:23:14] [Render thread/INFO] [minecraft/ConnectingScreen]: Connecting to [lan server]
[14:23:16] [Render thread/ERROR] [ne.mi.re.GameData/REGISTRIES]: Unidentified mapping from registry minecraft:block
	iceandfire:dread_stone_stairs: 892

[14:23:16] [Render thread/ERROR] [ne.mi.re.GameData/REGISTRIES]: Unidentified mapping from registry minecraft:item
	iceandfire:dread_stone_stairs: 2240

[14:23:16] [Render thread/ERROR] [ne.mi.fm.ne.FMLHandshakeHandler/FMLHANDSHAKE]: Missing registry data for network connection:
	minecraft:item: iceandfire:dread_stone_stairs
	minecraft:block: iceandfire:dread_stone_stairs

[14:23:16] [Netty Epoll Client IO #2/ERROR] [ne.mi.fm.ne.FMLHandshakeHandler/FMLHANDSHAKE]: Failed to load registry, closing connection.
[14:23:16] [Netty Epoll Client IO #2/ERROR] [ne.mi.fm.ne.FMLHandshakeHandler/FMLHANDSHAKE]: Connection closed, not continuing handshake

however the hosting pc is able to continue playing whereas i cannot
not sure why or what is doing this so we made a new world and tried, nope.
deleted the .minecraft and reinstalled, nope.

**Comment by aryana1445** [comment]
using 2.1.9-1.16.5 version

**Comment by DigitalWendigo** [comment]
This has been adressed in the new Alpha and Dev builds, meaning a fix for this will be available once the new update release has been uploaded. (At the time of writing this, no date has been specified for the release yet.)

Also for the future a little tip. 
When making issue reports try to provide the full latest.log file rather than snippets of it. You can just drag and drop them and Github will handle the rest. 
It's also very useful to provide a list of your mods and a crash log if one is made. 
This tends to help people pin-point the issue in question better and also help them identify similar issues rather than having to go through every line individually.

**Comment by aryana1445** [comment]
> This has been adressed in the new Alpha and Dev builds, meaning a fix for this will be available once the new update release has been uploaded. (At the time of writing this, no date has been specified for the release yet.)
> 
> Also for the future a little tip. When making issue reports try to provide the full latest.log file rather than snippets of it. You can just drag and drop them and Github will handle the rest. It's also very useful to provide a list of your mods and a crash log if one is made. This tends to help people pin-point the issue in question better and also help them identify similar issues rather than having to go through every line individually.

thanks for the suggestion!
however there wasnt any irregularities in the launching part of the log so i assumed it would be of no use and pasting my latest.log file would show my ip which is why i prefer editing it

**Comment by aryana1445** [comment]
i also happened to give the latest alpha release a try and it worked fine!
there is another issue on the latest alpha that ill upload the log to once i get on my pc in a separate issue

**Comment by DigitalWendigo** [comment]
> thanks for the suggestion!
> however there wasnt any irregularities in the launching part of the log so i assumed it would be of no use and pasting my latest.log file would show my ip which is why i prefer editing it

You can edit the latest.log file before you drop it into Github, so that no one can see your IP.
