### ISSUE TITLE
Hydra loses its heads way to easy. [ICE AND FIRE VERSION 2.1.10]

### ISSUE THREAD

**Issue by warning-djkajslh** [Alex-the-666/Ice_and_Fire#4498]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
It seems like that Hydra's head can be chopped off by virtually any gaming mechanic.

**To Reproduce**
1. Spawn hydra and some wolves
2. As the wolves and hydra fight, you can see that the head got destroyed, too easily if you ask me 
3. 
**Expected behavior**
The Hydra will only lose its head if:
- The attacker is using a sharp weapon: sword or axe, bows don't count unless...
- The Hydra is set on fire: Since the mob needs to have all of its heads chopped off in order to die, I think fire should make an exception as the one method that can still depletes Hydra's heads.

**Screenshots**

**Additional context**

**Comment by DigitalWendigo** [comment]
Not enough information. 
Provide some steps and examples since other mod's influence may affect it. 
In the base IAF it isn't too easy to defeat a hydra in HARD difficulty unlless you get yourself end-game gear since you also have to set it on fire otherwise the heads will regenerate and increase in number.

**Comment by warning-djkajslh** [comment]
> Not enough information. Provide some steps and examples since other mod's influence may affect it. In the base IAF it isn't too easy to defeat a hydra in HARD difficulty unlless you get yourself end-game gear since you also have to set it on fire otherwise the heads will regenerate and increase in number.

in my world I had only Ice and Fire and Minecolonies is the biggest mod. I am not talking about defeating the Hydra with little trouble, I meant any mobs can slice its head off. Try to spam only the dragon strike attack on the Hydra, and its heads come off one by one, my issue is to make it so that you can only slice them off with a sword, or with fire.

**Comment by DigitalWendigo** [comment]
But that's intended behaviour. 
If you want to change that mechanic you'll have to rework the code yourself or perhaps let another mod take control of IAF creature mechanics. 
Hydras can be killed by any number of damage sources, but need fire to truly be killed otherwise the cut off head will jut regrow and multiply.

**Comment by warning-djkajslh** [comment]
So you're saying is that mechanic is hard coded into the mod? I was thinking that there could be a work around this to make this happen, to make the heads more durable, similar to how cyclops's eye has been tweaked so that only damages from arrows can blind it.

**Comment by DigitalWendigo** [comment]
It would be a bit odd to not see a hydra die when a fire breathing dragon makes kebab out of it. 
Fire, the one thing that is required to actually kill a hydra. 
So it makes sense that other damage sources remove the heads.

**Comment by warning-djkajslh** [comment]
Well, the Hydra will die as the dragon roasts it, removing the head, since it is being on fire, and fire can remove the head, but the dragon's melee can't.

**Comment by DigitalWendigo** [comment]
This is sounding more and more like a feature suggestion since it isn't a bug or glitch. 
I suggest you move this to the Suggestions section instead and close this report.

**Comment by warning-djkajslh** [comment]
Certainly doesn't seem like one to me, but what do I know?
