### ISSUE TITLE
Crash when killing or mounting a dragon [2.1.9-1.16.5]

### ISSUE THREAD

**Issue by RadonCoding** [Alex-the-666/Ice_and_Fire#4499]
Whenever i kill a dragon or mount a dragon my game crashes

https://pastebin.com/dpF0p4VA

**Comment by DigitalWendigo** [comment]
Doesn't look like it's being caused by the dragon. 
The entity that's causing the crash seems to be a Zombie. 
This looks like an issue you should probably take up to the creator of your modpack.

**Comment by RadonCoding** [comment]
> Doesn't look like it's being caused by the dragon. The entity that's causing the crash seems to be a Zombie. This looks like an issue you should probably take up to the creator of your modpack.

it was indeed dragons and this issue was solved by downloading the latest alpha of IAF

**Comment by Flashbackmaniac** [comment]
Just a heads up, the latest I/F alpha build (3.1 as of this posting) has an issue where all dragon cave generation uses that of the lightning dragon's. I suggest waiting for the next alpha build or downgrade to a previous alpha build until the next development build rolls out, which addresses this issue among other things.
