### ISSUE TITLE
Dragonsteel tools durability can not be changed via config [2.1.10 - alpha 3.1]

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#4500]

**Comment by DigitalWendigo** [comment]
Have you tried to delete the config file to let a new one generate, and then editing the values? 
Also, already existing items placed inside the inventory will not update with the new values. 
I can't seem to reproduce this on my end.

**Comment by ghost** [comment]
I've done what you said. I've tested on a super flat and a normal world, with and without other mods, with and without optifine, on the alpha 3.1 and the latest snapshot, I can't seem to change the durability of dragonsteel tools. Also, the values in the config didn't get changed/reset upon booting up minecraft, the log also does not have any important information, it doesn't even mention anything about the dragonsteel tools base durability nor any warnings/errors.

**Comment by DigitalWendigo** [comment]
Alright my last suggestion is to try out the new Dev build that's been released. 
If that doesn't solve it for you then this is something TheBv needs to take a look at. 

https://github.com/Alex-the-666/Ice_and_Fire/releases/tag/latest-snapshot

**Comment by ghost** [comment]
As I've said above, I did try the latest development build.
