### ISSUE TITLE
[2.1.10 - alpha 3.1] Unable to mount Hippogryphs, Dragons, Ampitheres and Hippocampus while a shield is equipped in the off-hand slot. 

### ISSUE THREAD

**Issue by DigitalWendigo** [Alex-the-666/Ice_and_Fire#4503]
**Describe the bug**
As the title implies, one can't have a shield in their off-hand slot while trying to ride any mount as this gets disabled and the shield animation is triggered instead. 
This also seems to happen with any item held in the off-hand slot that has a right-click function. 

**To Reproduce**
1. Have a tamed creature at the ready.
2. Equip any kind of shield in the off-hand slot. 
3. See that the animation for the shield is triggered rather than allowing the player to mount. 

**Additional context**
This seems to happen with both a vanilla shield and any modded shields as well as fishing rods.

**Comment by TheBv** [comment]
Seems to be working fine for me :v
https://user-images.githubusercontent.com/12676257/169170368-cfb81621-08f2-417c-a064-b83faf168c84.mp4

**Comment by DigitalWendigo** [comment]
Huh.. Weird. Let me do some more tests then and I'll get back to you on it later.
If I can't reproduce it any more I'll close this issue. 
Thanks for looking into it.

**Comment by DigitalWendigo** [comment]
Alright this was an issue on my end. 
Closing this. Sorry for the inconvenience.
