### ISSUE TITLE
[2.1.10 - 1.16.5 Alpha 3.1] "Dragon Gold Search Length" appears to not work

### ISSUE THREAD

**Issue by Flashbackmaniac** [Alex-the-666/Ice_and_Fire#4504]
**Bug description:**
As the title says, the config value for "Dragon Gold Search Length" appears to not work. Opening a chest or mining a pile of copper / gold / silver does not alert the dragon to the action if it's within the range set by this value (default: 30 blocks). This leads to very easy looting where one could wait until the dragon's asleep, practically walk up to any chest in its cave / roost, and take all of its valuables or piles if one chooses to do so, provided that they're not within the range to wake up the dragon (which seems to be based on how big it is, but that's a separate issue).

**Steps to reproduce the behavior:**
1. Find a dragon cave or roost.
2. Open a chest and / or mine a pile of copper / gold / silver. It's preferable when the dragon is asleep so that its position relative to any chests and / or piles that generate in the cave / roost is constant.
3. Notice that the dragon doesn't wake up in response to the chest / pile being opened / mined. Presumably, if the dragon was awake when the action was performed, it would've either spotted you already (due to their target range) or target you if it hasn't done so.

**Expected behavior:**
I expected the dragon to act accordingly if a chest / pile was opened / mined.

**Additional context:**
I haven't looked into the code, but something tells me the code that does this doesn't exist either because it's something that was removed in the past like the glacier biomes (which said config values related to them is still in the main config file for some reason) or something was done to dummy it out. In addition, the only thing I modified in the main config file is the "Dragon Target Search Length" value. However, I don't see how modifying this value could potentially mess with the dragon's detection range for chests / piles being opened / mined.

**Comment by DigitalWendigo** [comment]
My thought is that maybe because the target search length is decreased (assuming you decreased it.) it disables the dragon from effectively looking for whatever opened the chest or broke the gold pile. 
So if the chest is opened and the event triggers the -search target- but said target is not within the defined -search target- range, it might not register.

**Comment by Flashbackmaniac** [comment]
I've just tested this with the "Dragon Target Search Length" value set to default (128 blocks), and I can confirm that the dragon doesn't respond when I open a chest or mine a pile. The "Dragon Gold Search Length" value remains the same as vanilla.

**Comment by DigitalWendigo** [comment]
Tested it as well.
I can confirm this is happening even with only Ice and Fire installed. 
Changing either of the two values does not seem to do anything to wake the dragon when a pile or chest is broken/opened.

**Comment by Flashbackmaniac** [comment]
I thought a bit about this mechanic and came to the conclusion that if this were to be implemented (or reimplemented), there would need to be a way to distinguish between chests / piles that naturally generated with the cave / roost and those that were placed by the player. It would be rather unfortunate if a player happened to be close to a sleeping dragon (but not close enough to wake it up), place down a chest to sort out items to prepare for the fight, interact with said chest, and then accidentally wake up the dragon because it was within range of the "Dragon Gold Search Length" value.

**Comment by DigitalWendigo** [comment]
> I thought a bit about this mechanic and came to the conclusion that if this were to be implemented (or reimplemented), there would need to be a way to distinguish between chests / piles that naturally generated with the cave / roost and those that were placed by the player. It would be rather unfortunate if a player happened to be close to a sleeping dragon (but not close enough to wake it up), place down a chest to sort out items to prepare for the fight, interact with said chest, and then accidentally wake up the dragon because it was within range of the "Dragon Gold Search Length" value.

That would be a bit odd since when you think about it, chests make a lot of sound when opened. 
It would make sense that if you open a chest, any chest, near a sleeping dragon, it would wake it up. 
And I don't believe anyone would do that in the first place. Most people tend to walk away from the dragon, or prepare ahead of time since dragon caves are faily easy to spot even when mining. Usually you find the first scorched/cracked/frozen block and know what you're going to be up against, take several steps back and then gear up. 
Though more often than not, people trying to find dragon caves prepare before hand. 

And making it so that dragons can distinguish naturally generating chests from player placed chests would be a nightmare and a half to do, I'd imagine.

**Comment by Flashbackmaniac** [comment]
Well, the situation I put in my previous comment isn't the only way players prepare for fighting with dragons. Anyway, disregarding my lack of coding experience, I'd suggest looking at the code for player-placed frozen / charred / crackled blocks, where these blocks that are naturally generated / player placed never revert to their normal block form while blocks that are turned into those blocks via a dragon's breath eventually revert to their normal form. I think some form of reuse with this code could be had with making a dragon ignore player-based chests versus naturally-generated chests.

In any case, it's up to Bv to see how this mechanic would be handled. One thing's for sure though, and that is this part of the dragons' behavior doesn't work as it should be.

**Comment by Flashbackmaniac** [comment]
Update: After switching over to the 5/18/22 development build, the mechanic works, however, there is another bug I noticed. If the dragon is sleeping and the chest is opened / pile is mined while it is asleep during the time of day at which they sleep, the dragon will wake up for a brief moment, then go back to sleep.

Example: Opening a chest or mining a pile while it is daytime near a sleeping fire dragon in a cave within the default 30 block range will wake it up like normal.
