### ISSUE TITLE
[2.1.10 - 1.16.5 Build 2022-05-17] Dragon rendering glitch. 

### ISSUE THREAD

**Issue by DigitalWendigo** [Alex-the-666/Ice_and_Fire#4506]
**Describe the bug**
When panning up, the dragon seems to temporarily blip out of existance but as the screenshot below shows, the dragon is still within sight. 

**To Reproduce**
1. Find or spawn a dragon and fly above it or just at the same height as the dragon is flying. 
2. Pan the camera up. 
3.The dragon will temporarily become invisible for a very short moment. Panning the camera back down seems to let it phase back. 
This is more likely something related to how dragons are being rendered. 

**Screenshots**
Screenshot provided by Flashbackmaniac.
![unknown](https://user-images.githubusercontent.com/103202053/168991080-48dec09f-ba97-49f5-ac52-195d9a028a16.png)

**Additional context**
This has been tested with and without performance enhancing mods such as the likes of Optifine and Performant.

**Comment by TheBv** [comment]
That's just how minecraft rendering works. Since the "main" part of the dragon is not on the screen anymore the entire model won't be rendered.
