### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by WhiteCrow111** [Alex-the-666/Ice_and_Fire#4507]
**Crash**
Game crash's on launch, error code "Unexpected issue occured and game has crashed, we're sorry for the inconvenience, this crash may be caused by an Invalid Java Runtime Configuration Exit code: 1"

**Screenshots**
![image](https://user-images.githubusercontent.com/105816390/169120629-948d06d9-0158-4627-827f-a2035647640e.png)

Game version 1.12.2, mod version downloaded 1.9.1-1.12.2

**Comment by DigitalWendigo** [comment]
1.12.2 Is no longer supported. 
However, it's hard to determine if ice and fire is the culprit for your crash if you don't provide a crash log. 
That screenshot you provided, is not a crash log. 
Exit Code:1 can mean anything.
