### ISSUE TITLE
More Detailed Bug Description

### ISSUE THREAD

**Issue by Ruidolph** [Alex-the-666/Ice_and_Fire#451]
So previously I posted about the fact that Hippogryphs aren't working. Let me elaborate. Even when you use a stick to make them stand up, they refuse to move. They stay still even after they stand up and when you mount and dismount them, they immediately lay back down even if they were standing before they were mounted. 

My server uses the mod "ExtraUtils" that has a golden lasso and creature wands so that could be causing them to bug but I'm not entirely sure. No other mobs seem to be affected by them but the hippogryphs literally do not move. Even if you try to breed them.

**Comment by AlexModGuy** [comment]
unable to duplicate
