### ISSUE TITLE
Tamed dragons having facing angle issue [2.1.10 - 2022-5-19]

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#4511]
Tamed dragons will rotate a certain angle when the player is riding it and holding down the hotkey for breath attack, this can be seen by having the hitboxes enabled, as the visible dragon doesn't actually rotate.

**Comment by DigitalWendigo** [comment]
Could you provide some screenshots?

**Comment by gotanyideasmate** [comment]
Also this can only be reproduced with female fire dragon.

**Comment by ghost** [comment]
Tested information about this issue:
 * This is reproducible if it is day for ice and fire, night for lightning dragons, and the dragon has to be not moving.
 * How to reproduce:
   - Spawn in a dragon, or hatch an egg, either way works as long as you have that dragon tamed.
   - Mount the dragon.
   - F3+B.
   - Hold down the dragon breath hotkey.
   - Turn your player.
   - If the issue cannot be seen, try unmount the dragon and wait for a few seconds and remount to try again.
 * Screenshot:
![2022-05-20_17 36 07](https://user-images.githubusercontent.com/105374204/169511381-04370c30-c651-4ed5-a79a-a12f6d9162ac.png)
 * Tested with and only with lastest version of citadel and forge for 1.16.5, IaF dev build 2022-05-19 on a superflat and normal world.

**Comment by TheBv** [comment]
Not an issue anymore
