### ISSUE TITLE
Certain IaF entity type tags does not work [2.1.10 - dev build 2022-5-19]

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#4514]
The #iceandfire:fear_dragons and #iceandfire:scares_cockatrices does not work.

**Comment by TheBv** [comment]
`#iceandfire:fear_dragons` definitely is broken. What exactly about ` #iceandfire:scares_cockatrices` isn't working?

**Comment by ghost** [comment]
You can't reproduce it? Weird, I've put "alexsmobs:raccoon" and "alexsmobs:tasmanian_devil" in the #iceandfire:scares_cockatrices tag, yes I know neither of those are ferrets/weasels but I can do whatever I want, but it doesn't seem to work, the cockatrices just straight up attacking the raccoons, and the server just straight up crash when the cockatrices target the tasmanian devil.

**Comment by ghost** [comment]
So here's the thing with the #iceandfire:scares_cockatrices tag, instead of scaring the cockatrices like what the name and the comment of the tag and the bestiary tells, it makes cockatrices attack those mobs instead of being scared, which is more like #iceandfire:cockatrice_targets.

**Comment by TheBv** [comment]
Yeah that's basically is what it does. It acts like `cockatrice_targets`. I'm not sure why it was named this.
As far as I can tell there currently does not exist a fear mechanic for Cockatrice.
I'll see what I can do about that I think it could be a fun addition!

**Comment by DigitalWendigo** [comment]
It would make sense that a cockatrice would run away if a dragon tried to eat it rather than going for a suicide run.

**Comment by DrPenguinni** [comment]
I think that the #iceandfire:scares_cockatrices tag is meant to simply make the mob more proficient at killing cockatrices, making it deal 5x as much damage as it normally would. The bestiary itself refers to these types of mobs as the "greatest enemy" of a cockatrice; this would line up better with the idea that the mob being more proficient at killing the cockatrices would result in a rivalry being developed, and the monsters instantly targeting their greatest enemy on-sight.

**Comment by ghost** [comment]
@EmperorPlebpatine You've mistaken the meaning of the word "enemy".
