### ISSUE TITLE
My game crashes when I try to mount any type of dragon in both multi and singleplayer [ICE AND FIRE VERSION 2.1.9 1.16.5]

### ISSUE THREAD

**Issue by PedroUFirmani** [Alex-the-666/Ice_and_Fire#4516]
Everytime I try to mount a tamed or a wild dragon the game crashes, the dragon works just fine standing there or wandering on the world, but only when i try to ride it he crashes the game, not only my game but the entire lan server that i made with my cousin, he's hosting it.

1. Enter the game
2. try to mount the dragon

another thing is that if i Spawn multiple dragons on creative the game will eventually crash

[crash-2022-05-24_05.30.15-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/8765460/crash-2022-05-24_05.30.15-client.txt)
[crash-2022-05-24_05.47.15-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/8765461/crash-2022-05-24_05.47.15-client.txt)
[crash-2022-05-24_15.31.38-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/8765462/crash-2022-05-24_15.31.38-client.txt)

When i join the server the game crashes too, since i was mounted on the dragon I hope i can fix it, because i made a modpack wanting to ride the dragon from the start, and one of the principal things, if not the principal thing that i wanted to do is to be a dragon tamer

**Comment by TheBv** [comment]
If the server crashes could you provide the crash logs from your cousin who's hosting the server?
Also and I know this might be a bit much to ask for but could you try if this issue persists if you remove some of the mods? (Ideally on a different world to make sure you don't loose any mod specific things)
The ones I'd try removing would be: `Optifine`, `Quark`, `Oh the biomes you will go`, and for good measure: `twilight forest`.
All of them modify how minecraft renders the player...
Also could you give one of the newest snapshot a try and see if the issue persists? https://github.com/Alex-the-666/Ice_and_Fire/releases/tag/latest-snapshot 
I know it's a bit much but I can't seem to replicate this issue on my end even with OptiFine installed.

**Comment by PedroUFirmani** [comment]
I solved the problem, it was "little critters mod". For some reason this
mod conflicts with dragons, you can normally play but if you have too many
dragons spawned or if you mount in a dragon the game crashes. And honestly
the little critters mod is not really that necessary since bugs and bees
are so small that you don't even notice in the gameplay. I discovered the
problem just by reading the github issues, someone had the same mod and
solved it by removing the same, i hope this email helps you and your team
to get the knowledge that this mods conflict with each other for some
reason. sorry if i have a bad english, i learned it all alone, and i live
in Brazil, hope you did understand what i meant to say :)

Em sex., 27 de mai. de 2022 às 16:02, TheBv ***@***.***>
escreveu:
