### ISSUE TITLE
Crash when hitting cockatrice [2.1.10-1.16.5-SNAPSHOT+build.2022-05-19]

### ISSUE THREAD

**Issue by RadonCoding** [Alex-the-666/Ice_and_Fire#4517]
**Describe the bug**
When i hit a cockatrice the game freezes and crashes.

**To Reproduce**
1. Insall the latest shapshot
2. Hit a cockatrice
3. See error

**Additional context**
Crash report: https://pastebin.com/P37GnX8X

**Comment by TheBv** [comment]
Same as  #4515
