### ISSUE TITLE
Dragon crashes minecraft

### ISSUE THREAD

**Issue by PlayerJman001** [Alex-the-666/Ice_and_Fire#4518]
Whenever a dragon does a breath attack, or something, it crashes the game
Here is the log:
[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/8791633/latest.log)
Here is the crash report:
[crash-2022-05-29_11.46.22-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/8793062/crash-2022-05-29_11.46.22-client.txt)

It seems like optifine's fast math causes the crash

**Comment by DigitalWendigo** [comment]
Optifine is known to cause a lot of problems. 
This also no longer seems to be an issue as of the new development builds. 
Please close this issue report and have a nice day.
