### ISSUE TITLE
[1.12.2] Rampant breeding of Animania sheep due to dragons config!?!

### ISSUE THREAD

**Issue by PhoenixRiver** [Alex-the-666/Ice_and_Fire#452]
Version: iceandfire-1.3.1-1.12.2
Version: animania-1.12.2-1.4.4
Forge: forge1.12.2-14.23.1.2555
Minecraft: 1.12.2

When I changed this setting in the ice and fire config file:

```
dragons {
# True if dragons can despawn. Note that if this is false there may be SERIOUS lag issues.
B:canDragonsDespawn=true
```

The number of animania sheep has skyrocketed... I don't understand why there is this overlap but I've submitted a bug report with animania too. The reason I set it to false was that I've seen very few dragons, one, maybe two so I decided to make sure they didn't disappear before I had a chance to get tech'd up enough to take them on; I'm also playing solo on my own machine so I figured that since I wasn't moving around very much that it wouldn't cause a problem...

So I was wondering how ice and fire's config was causing another mods entity's to go crazy... (it probably shouldn't if it can help it).

For reference the Animania bug report is here:
https://github.com/capnkirok/animania/issues/532

**Comment by AlexModGuy** [comment]
that config is only referenced in one spot on the code, when the dragon dies of despawning. It isn't effecting animania.
