### ISSUE TITLE
[2.1.10 - 1.16.5 Development Build 5/19/22] Fire / Lightning dragon caves seem to be spawning only female dragons

### ISSUE THREAD

**Issue by Flashbackmaniac** [Alex-the-666/Ice_and_Fire#4521]
**Bug description:**
As the title says, fire / lightning dragon caves seem to be spawning only female dragons inside their caves.

**Steps to reproduce the behavior:**
1. Find a couple of fire dragon caves and make note of the fire dragons' genders. It is preferable to bump up the chance for dragon cave generation to find them easier.
2. Likewise, find a couple of lightning dragon caves and make note of the lightning dragons' genders.
3. After finding a reasonable amount of dragon caves (statistics-wise), notice that the only dragons that are seen inside these caves are females.

**Expected behavior:**
I expect to find both female and male dragons inside their respective caves.

**Additional context:**
I'm pretty sure this is not something due to me being unlucky with the dragon caves found. The genders of ice dragons inside their caves seem to be unaffected.

**Comment by DigitalWendigo** [comment]
![2022-06-01_12 27 14](https://user-images.githubusercontent.com/103202053/171373977-d7a3ed57-7a82-4392-9fd4-aeb7323411a6.png)
Tested on a brand new world with default settings. 
Seems to work as intended. I'm getting a mix of female and male dragons. Fire and Lightning.

**Comment by Flashbackmaniac** [comment]
Alright, I've gone around and checked the previous versions of the I/F 2.1.10 development builds to check if this oddity was also present. Reverting to the Alpha 3.0 development build gave me the same behavior, while the Alpha 3.0 development build has both male fire / lightning dragons spawning normally. I presume this is the case with every development build before Alpha 3.0 as well.

No edits to the JSON files for which biomes they spawn in, nor were any edits to their behavior were made in the main config other than turning up the spawn chances for dragon caves to make them easier to find. This was also tested in a new world.
