### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by MeteKardes** [Alex-the-666/Ice_and_Fire#4525]
**Describe the bug**
I installed a modded server in version 1.16.5 36.2.35 from a server setup platform to play with my friends, then I installed ice and fire mode and other mods. After I installed the same versions of the same mods in my files and opened the server, when I opened the server, when I wanted to enter the game, it gave the following error: Failed to synchronize registry data from server. I deleted all the mods one by one and tried again, it didn't work, but when I deleted the ice and fire mod and its add-ons, it entered the game, but when I reinstalled and tried, it didn't work, I applied to you, but I don't know what to do, I think you can help.

**To Reproduce**
3. See error

Entering the world without making mistakes

![image](https://user-images.githubusercontent.com/107354295/173235143-d4ba7329-9312-40f4-a65e-90bdb540bbb8.png)

**Additional context**

**Comment by TheBv** [comment]
Can you provide the latest.log which should be in your minecraft log folder? That should provide more information :)

**Comment by MeteKardes** [comment]
[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/8886101/latest.log)

**Comment by MeteKardes** [comment]
> Can you provide the latest.log which should be in your minecraft log folder? That should provide more information :)
[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/8886102/latest.log)

**Comment by AlexModGuy** [comment]
> java.lang.NoClassDefFoundError: com/github/alexthe666/citadel/server/entity/EntityPropertiesHandler
	at com.github.alexthe666.iceandfire.entity.IafEntityRegistry.setup(IafEntityRegistry.java:99)

downgrade citadel
