### ISSUE TITLE
Tide Tridents come back as normal tridents [2.1.9-1.16.5]

### ISSUE THREAD

**Issue by HewStudios** [Alex-the-666/Ice_and_Fire#4528]
It's a little hard to describe, since it's on a server, but it seems to be an issue with ice and fire itself. When throwing a tide trident without riptide,  and picking it up, it will be put into your inventory as a vanilla trident. It seems that enchantments are replicated on this version. It seems to be an item ID problem. I sadly do not have any reliable or clear logs for this issue.

**Comment by DigitalWendigo** [comment]
Known issue. A fix for this has been implemented in one of the development builds. 
Once a released version airs on curseforge you'll be able to update.

**Comment by XionioXMaster** [comment]
Close!
