### ISSUE TITLE
Crash when standing near a cockatrice [2.1.10-1.16.5-SNAPSHOT+build.2022-05-19]

### ISSUE THREAD

**Issue by RadonCoding** [Alex-the-666/Ice_and_Fire#4530]
**Describe the bug**
When standing near a cockatrice the game crashes

**To Reproduce**
1. Find a cockatrice
2. Stand next to it
3. Crash

**Expected behavior**
Expected the game not to crash i guess

**Additional context**
Crash report: https://pastebin.com/6VDcyZqY

**Comment by DigitalWendigo** [comment]
Try to reproduce the issue without the mods "More player models", and Create+flywheel.

**Comment by ghost** [comment]
Same as #4515 and #4517, and this issue will be fixed in the next release.
