### ISSUE TITLE
Tide Trident destroys itself.

### ISSUE THREAD

**Issue by MedicinalMan** [Alex-the-666/Ice_and_Fire#4534]
**Description**
When throwing the Tide Trident in survival, It will turn into a regular trident after a few throws. All enchantments will be removed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Get a Tide Trident.
2. Throw the Tide Trident.
3. Pick it up.
4. Repeat until it is no longer a Tide Trident.

**Expected behaviour**
The Tide Trident should behave normally and be picked up/return to the player without issue.

**Additional context**
This issue does not occur when only Ice and fire is installed, this did happen in a modpack. No other issues with Ice and Fire were encountered except for this. I am unsure which mod causes this issue as none explicitly alter tridents except [Better Trident Return](https://www.curseforge.com/minecraft/mc-mods/bettertridentreturn).

**Problematic Modpack**
[Ice and Fire Issue Pack.zip](https://github.com/Alex-the-666/Ice_and_Fire/files/8928382/Ice.and.Fire.Issue.Pack.zip)

Thank you for your time.

**Comment by DigitalWendigo** [comment]
Known issue, has been fixed in development builds. 
Until the released version airs on curseforge you'll unfortunately just have to refrain from using the tide trident.

**Comment by MedicinalMan** [comment]
Tysm. Just out of moribd curiosity, what caused it?
