### ISSUE TITLE
One hitting every mob 

### ISSUE THREAD

**Issue by NotLuxas** [Alex-the-666/Ice_and_Fire#4536]
I don't actually know if it's the mod issue or something else but when I hit a dragon ir any other mob from ice and fire mod it just one hits with hand every other mob is okay and doesn't do that

**Comment by DigitalWendigo** [comment]
Check your config settings and what other mods you have installed. 
Also, you need to provide more information. There is even a template to follow upon making an issue. Try filling that out next time. Specify your minecraft version, mod version, provide a mod list, a log file, and check your iceandfire-common config file to see if the health values haven't been tempered with. 
The more in fo you provide, the better people can help you. 
Without providing enough, chances are, no one will be able to help determine what's going on.
