### ISSUE TITLE
Game not starting (EntityAttributeCreationEvent Error) [2.1.9]

### ISSUE THREAD

**Issue by BlackLightDragon** [Alex-the-666/Ice_and_Fire#4538]
**Describe the bug**
Game doesn't  wanna launch in 1.16.4 with the mod installed

**To Reproduce**
1. Install ice and fire with forge 35.1.37 for 1.16.4
2. click play in the launcher
3. game no start
4. [crash report](https://pastebin.com/XWzt0MAE)
    [logs](https://pastebin.com/2xu5Qc02)

![image](https://user-images.githubusercontent.com/108180227/175772365-04fc456d-6298-4bbc-845c-914f88c3c869.png)

**Expected behavior**
Well a launching game

**Screenshots**

**Comment by TheBv** [comment]
This mod doesn't work with 1.16.4 or well: You need at least forge version 36.0.40.

**Comment by BlackLightDragon** [comment]
thx
the curseforge said it was compatible hence why I was a bit startled to find the opposite
