### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by GamerBritt** [Alex-the-666/Ice_and_Fire#4541]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
A clear and concise description of what the bug is. anytime i load up my game, i always get this error. eveything is up todate. pleasehelp me 

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Additional context**
![Untitled](https://user-images.githubusercontent.com/108359271/176241013-907788e5-afa5-4f7e-bbdd-4eac0dee46da.png)
![Untitled1](https://user-images.githubusercontent.com/108359271/176241081-566e55d7-12b7-46b6-a235-b5ff26075276.png)
![Untitled2](https://user-images.githubusercontent.com/108359271/176241087-7e699b20-f275-4481-bce4-dc2b344ef812.png)
![Untitled3](https://user-images.githubusercontent.com/108359271/176241127-2acb0b7b-298d-4ddb-8881-4229b65718da.png)
![Untitled4](https://user-images.githubusercontent.com/108359271/176241140-35c
!
![Untitled9](https://user-images.githubusercontent.com/108359271/176241167-00ffcb7d-e526-4672-97d5-eaf8bdaf791c.png)
![Untitled7](https://user-images.githubusercontent.com/108359271/176241169-1ae048e9-a91f-482a-9be0-96d3e5216e16.png)
[Uploading Untitled6.png…]()
10fce-9662-4665-9251-1aa98bf554db.png)
![Untitled8](https://user-images.githubusercontent.com/108359271/176241144-f719b1aa-4a33-43ff-bce3-610cd777ae27.png)
![Untitled5](https://user-images.githubusercontent.com/108359271/176241154-8a533e13-bc9a-4f6b-9444-ff7cd9e04088.png)

**Comment by AlexModGuy** [comment]
mod is not for 1.18
