### ISSUE TITLE
Mod doesn't load at all

### ISSUE THREAD

**Issue by EmbukuN** [Alex-the-666/Ice_and_Fire#4545]
I've been trying for hours on end to make the mod load properly on 1.16.4 with forge 35.1.37. I'm using citadel 1.8.1 (as recommended) which loads properly without any issues. However, the mod itself fails to load each time which is extremely frustrating. Immediate assistance is requested.
![image](https://user-images.githubusercontent.com/100770401/176922789-b908b2be-7e35-427f-b78e-1dabff5f6c45.png)
[crash-2022-07-01_21.10.46-fml.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/9029919/crash-2022-07-01_21.10.46-fml.txt)

**Comment by AlexModGuy** [comment]
> Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/EntityAttributeCreationEvent
		at gigaherz.eyes.EyesInTheDarkness.<init>(EyesInTheDarkness.java:83) ~[?:1.0.2] 

not our mod
