### ISSUE TITLE
Game crashes at start up, gives error page

### ISSUE THREAD

**Issue by Magikaprfainted** [Alex-the-666/Ice_and_Fire#4546]
Game loads and boots to error log with new update
error message reads; Ice and Fire encountered an error during the load_registries event phase
java.lang.NoClassDefFoundError: net/minecraftforge/common/ForgeSpawnEggItem.

**Comment by TheBv** [comment]
Update forge to at least version 36.2.17
I wasn't aware that some of the [changes ](https://github.com/Alex-the-666/Ice_and_Fire/commit/18284c472c125808c3329bef988366af6b95634e) made it so a new forge version is required. I'd have changed the requirements otherwise.

**Comment by Magikaprfainted** [comment]
ah will do, thank you ^_^
