### ISSUE TITLE
1.16.5 Latest Update Ice and Fire crashed with TerraForged

### ISSUE THREAD

**Issue by Ryuushen** [Alex-the-666/Ice_and_Fire#4547]
Crashlog is here
[crash-2022-07-01_19.17.12-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/9032258/crash-2022-07-01_19.17.12-client.txt)

When generating world with Terraforged it crashed

**Comment by TheBv** [comment]
The crash log mentions the mod `cooking for blockheads` trying to attach some functions to a tile entity. Seems to be related to the dread spawners. 
I will investigate this further you could try disabling mausoleums for the time being :/

**Comment by TheBv** [comment]
Fixed with [e7573ad](https://github.com/Alex-the-666/Ice_and_Fire/commit/e7573ad722ddd02ccbcdadbf91fa3f5590999059)
If you want you can check out the latest snapshot to see if it has been fixed: https://github.com/Alex-the-666/Ice_and_Fire/releases/tag/latest-snapshot 
If it hasn't let me know :)

**Comment by TheBv** [comment]
Published a new snapshot that should properly resolve the issue.
