### ISSUE TITLE
Ice and Fire not showing up in controls

### ISSUE THREAD

**Issue by Lietziboyy** [Alex-the-666/Ice_and_Fire#4548]
Ice and Fire is not showing up in controls. I cant change my keybind!

I am using my own modpack
https://www.curseforge.com/minecraft/modpacks/the-prince-pack

**Comment by Lietziboyy** [comment]
accident lol

**Comment by TheBv** [comment]
Does anything show up in the debug.log file when you launch them game?
There could be a hint there regarding wrongly executing some bit of code etc.
Providing that would be nice :)

**Comment by Lietziboyy** [comment]
https://paste.gg/p/anonymous/ec4fb9e1cb3e4d34af5737f02082008d
Does that help?

**Comment by TheBv** [comment]
I didn't find anything off interest on there so I went ahead and installed the pack.
The keybinds are there for me: 
![image](https://user-images.githubusercontent.com/12676257/177053801-884cf5d1-1d3d-41f0-8d6e-57f35a001865.png)

**Comment by Lietziboyy** [comment]
Oh no, I see the problem I meant that the Keybinds for ice and fire are not showing.
You got any Suggestions for that
