### ISSUE TITLE
Crash while creating a new world or loading an old one [iceandfire-2.1.10]

### ISSUE THREAD

**Issue by TheYoloPanda** [Alex-the-666/Ice_and_Fire#4549]
Crash while creating a new world or loading an old one, I've updated Ice and Fire in [my 1.16.5 modpack](https://www.curseforge.com/minecraft/modpacks/crif) and since then I'm having this crash.

[crash-2022-07-02_14.34.48-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/9033016/crash-2022-07-02_14.34.48-server.txt)

**Comment by TheBv** [comment]
Most likely related to the mod `info.partonetrain.iafgear` which I think is this mod https://www.curseforge.com/minecraft/mc-mods/dragon-gear/files/3135642 . I think you'll need to wait until they update it; or play without it.
