### ISSUE TITLE
game crashed shortly after loading into my world [2.1.10]

### ISSUE THREAD

**Issue by Szymonc4pro** [Alex-the-666/Ice_and_Fire#4551]
**Describe the bug**
the only reason why it seems to be that ice and fire caused the crash is the message that pops up in the launcher after a crash the message said
"The game crashed whilst exception in server tick loop
Error: java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/entity/props/FrozenEntityProperties"

**Additional context**
the way it crashed was that i was trying to swing my sword at a blaze. so the sword in question was a ice dragon steel saber from the mod [Spartan Weaponry: Ice and Fire](https://www.curseforge.com/minecraft/mc-mods/spartan-weaponry-ice-and-fire) which when hitting something gives it the ice block effect just like a regular ice dragon steel sword but i don't get why it woud crash
(i don't know what else i should write here incase you need more info just idk leave a comment saying what info is also needed to solve the issue)

**Comment by Szymonc4pro** [comment]
so i tested and if i hit a blaze with something else than my ice dragon steel saber it doesn't crash but the moment i hit one with my saber it crashed i am now going to test if the same crash happens when i use a normal ice dragon steel sword
i will also test on other enties than blazes

**Comment by Szymonc4pro** [comment]
the same crash happens when hitting zombies so i think that will also go for any other entity that can get frozen

**Comment by TheBv** [comment]
Spartan Weaponry is most likely incompatible with the newest update. You'll need to wait until the creator updates the mod since the way some entity properties get assigned have changed quite a bit.

**Comment by Szymonc4pro** [comment]
> Spartan Weaponry is most likely incompatible with the newest update. You'll need to wait until the creator updates the mod since the way some entity properties get assigned have changed quite a bit.

you mean the mod spartan weaponry or the add-on from a diffrent person: spartan weaponry: ice and fire ?

**Comment by TheBv** [comment]
Well basically any mod that has weapons that tries to freeze a target. Technically also anything that trys to chain an entity to something and some other minor things which I doubt any mod is using.

**Comment by Szymonc4pro** [comment]
> Well basically any mod that has weapons that tries to freeze a target. Technically also anything that trys to chain an entity to something and some other minor things which I doubt any mod is using.

so that woud be Spartan Weaponry: Ice and Fire 
which was last updated late may and the creator has no planned updates for now
