### ISSUE TITLE
Crash on generating world in singleplayer/launching server [inceandfire-2.1.10-1.16.5]

### ISSUE THREAD

**Issue by Aromiya-AR15** [Alex-the-666/Ice_and_Fire#4552]
**Describe the bug**
The mod loading perfectly fine but game crash instantly after generating new world in single player. Same for launching server with this mod

**To Reproduce**
1. Install mods, using recommended version of Forge
2. Getting into singleplayer

Here is the crash-log for client and latest.log for server
[crash-2022-07-02_23.35.49-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/9033348/crash-2022-07-02_23.35.49-client.txt)
[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/9033351/latest.log)
Hope you best of luck!

**Comment by TheBv** [comment]
If this has something to do with Ice and Fire you should try to delete your config files related to iceandire (back them up if you've changed anything) see if that helps fix it.
For Ice and Fire the only code that I'm aware of that could lead to a crash when loading a world/ the world select screen is related to the various entity spawn configs, hence I'm suggesting this.

**Comment by Aromiya-AR15** [comment]
I figured it out after your answer. It is the incompatible with Mobifier mod. Maybe this should be a heads-up for more people trying to use that mod

**Comment by Aromiya-AR15** [comment]
Thank you for your time
