### ISSUE TITLE
fire dragon crashing my mates server [2.1.10 and 1.16.5]

### ISSUE THREAD

**Issue by Generical12** [Alex-the-666/Ice_and_Fire#4553]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
something to do with the pathfinding of the fire dragon is causing a crash on our server

**To Reproduce**
have a dragon rendered in 

**Expected behavior**
i didnt even know there were a fire dragon around so didnt expect it to crash really

**Screenshots**

**Additional context**
it could be another mod doing this but it never did before when we had the older version sorry if it isnt ice and fire\
this is the crash report
https://pastebin.com/J56xTWg9

**Comment by TheBv** [comment]
See #4606 for a fix
