### ISSUE TITLE
last update [iceandfire-2.1.10-1.16.5] 

### ISSUE THREAD

**Issue by DragonAstemirN** [Alex-the-666/Ice_and_Fire#4554]
electric dragon head movement

electric dragon head move when riding

https://user-images.githubusercontent.com/94336869/177026433-41fe92e4-e75e-40f4-9c31-9f2c6fadde9e.mp4

https://user-images.githubusercontent.com/94336869/177026498-d372f1ff-16ae-411c-8686-5dfa243092cb.mp4

**Comment by DragonAstemirN** [comment]
affected electric dragon moves affected by riding it

https://user-images.githubusercontent.com/94336869/177026671-d77e74c8-5ce1-4f05-a954-6e38f8e661a3.mp4


the movement problem is unique to the electric dragon

**Comment by TheBv** [comment]
I'm pretty sure I've fixed these issues with the recent changes.
