### ISSUE TITLE
baby dragons- fire and lightning only

### ISSUE THREAD

**Issue by holyaurora21** [Alex-the-666/Ice_and_Fire#4556]
Mod Pack: Fantasy Realm
iceandfire-2.1.10-1.16.5

**Describe the bug**
Baby versions of the fire and lightning dragons will only spawn

**To Reproduce**
Make a server. Problem seems to be server sided only (multiplayer)

Think you can help us figure out what mods are clashing/causing this problem?

thanks

**Comment by holyaurora21** [comment]
also get invisable sea serpents

**Comment by s10w10rr1s** [comment]
like your dragons are tiny? im having the same issue

**Comment by s10w10rr1s** [comment]
christ almighty this was posted on the fourth of july and no one has taken a look at it
