### ISSUE TITLE
Crash When Rendering Pixie House While Dead

### ISSUE THREAD

**Issue by Rensik** [Alex-the-666/Ice_and_Fire#456]
I thought this bug had been fixed. Obviously not as I had it happen twice in a row. It only happens when you die near a pixie house.

https://pastebin.com/gpZZbNHr

**Comment by MokahTGS** [comment]
This crash happened to me just flying over in creative generating chunks.

https://pastebin.com/AQzuTqbf

**Comment by Skyridr** [comment]
Can confirm, respawning near a pixie house will crash the client:

https://pastebin.com/Z995yKtE

**Comment by Hjaldar** [comment]
Another example from one of my pack testers that didn't involve dying:
https://pastebin.com/wGdvud5M
