### ISSUE TITLE
Configuration of cockatrice health does not work properly

### ISSUE THREAD

**Issue by gummie2022** [Alex-the-666/Ice_and_Fire#4561]
Describe the bug
When I tried to configure its health from the default health (40) to 60, the health points were still the same.

Additional context
I am using a neat mod to know its actual health points.

![image](https://user-images.githubusercontent.com/108954683/178058775-2511fa48-cb19-4c42-bd48-163e05054dd4.png)
![image](https://user-images.githubusercontent.com/108954683/178058904-91a259be-cf97-4c61-ae41-00cecc81d5c0.png)

**Comment by TheBv** [comment]
Can't seem to replicate this for version 2.1.10 in which a lot of these issues have been fixed.
