### ISSUE TITLE
[2.1.10 - 1.16.5] Dragon corpses seem to despawn upon teleporting close to them

### ISSUE THREAD

**Issue by Flashbackmaniac** [Alex-the-666/Ice_and_Fire#4562]
**Bug description:**
Teleporting to a dragon corpse could potentially cause the dragon corpse to despawn.

**Steps to reproduce the behavior:**
1. Kill a dragon.
2. Teleport out of the dragon corpse's range at which it renders (optionally in spectator mode, the game mode at which I found the oddity).
3. Teleport back to the dragon corpse and potentially cause the dragon corpse to despawn.
4. When the oddity happens, check with F3 + B (hitbox display toggle) and see that the dragon corpse disappeared without a trace.

**Expected behavior:**
I expected the dragon corpse to not pull a disappearing act.

**Additional context:**
I was unable to get screenshots since the bug seems to occur randomly and that it happened to lightning dragons, although I have my suspicion that this bug affects ice / fire dragons as well. In addition, I was unable to replicate the bug consistently on a test world. However, there were two things I noticed before the dragon corpse despawned. The first thing was that its hitboxes lingered for a split second before despawning. The second thing was that the model did not render when loading the entity via teleporting close to it. I do not have any entity culling mods installed, nor were there any indication of anything out of the ordinary when I checked the log files.

**Comment by TheMaskedGamer06** [comment]
Also, our dragons are disappearing if we leave the server, which is really annoying since we cant pick them up in horns.

**Comment by TheMaskedGamer06** [comment]
<img width="1011" alt="Screen Shot 2022-07-08 at 9 20 13 PM" src="https://user-images.githubusercontent.com/65079286/178087995-fb71a2c6-d3ef-4e8c-a37b-f079279dd3be.png">

**Comment by Sazuzaki** [comment]
I have a similar issue where dragons will disappear altogether when leaving the loaded chunk. Could be related.

**Comment by TheBv** [comment]
Probably has to do with some nbt issues. Should be fixed in the upcoming version.
