### ISSUE TITLE
Can't pick up dragons in horn [2.1.10-1.16.5]

### ISSUE THREAD

**Issue by TheMaskedGamer06** [Alex-the-666/Ice_and_Fire#4563]
**Describe the bug**
No one on my server is able to pick up dragons in horns.

**To Reproduce**
1. Place a dragon in the world
2. Leave them for a bit/place new ones
3. Dragons won't go in horn

**Expected behavior**
The dragons would go in the horn

**Additional context**
Updated this mod in a modpack with other mods as well. Twilight Forest was another mod I added, idk if that does anything.

**Comment by TheMaskedGamer06** [comment]
https://pastebin.com/FqLqPhiL

**Comment by TheBv** [comment]
Will be fixed in the new version.
