### ISSUE TITLE
Dragons despawn when leaving chunk and are never seen again. [2.1.10]

### ISSUE THREAD

**Issue by Sazuzaki** [Alex-the-666/Ice_and_Fire#4564]
**Describe the bug**
When I load into a chunk with a dragon roost, it's there out and about at its nest. But when the chunk unloads and I come back, the dragon is gone. 

**To Reproduce**
Not sure how to reproduce as one of my mods seems to be causing it, but I'm not sure what. I've already uninstalled Performant, but still have the issue.

**Expected behavior**
Dragons to still be in said roost.

**Screenshots**
https://i.imgur.com/OvmLHLe.png

**Additional context**
Let me know if you need the complete logs. It works fine in 2.1.9

**Comment by TheBv** [comment]
Will be fixed in the new version.
