### ISSUE TITLE
Crash with Allthemodium Mod

### ISSUE THREAD

**Issue by Airisii** [Alex-the-666/Ice_and_Fire#4566]
With the newest update I tried making a world or joining a pre-existing world and it crashes. I backported to an older iceandfire version and it worked fine.

Crash Report: 
https://pastebin.com/tQTWF3tz

**Comment by thevortex** [comment]
this is an issue with the allthemodium mod, the update is due out this week for atm6, just follow our official releases and things will remain stable, this can be closed, no fault of I&F :)

**Comment by Airisii** [comment]
Alright, thank you for the response!

**Comment by FurretGod** [comment]
having this exact same issue, using the latest versions of ice and fire and allthemodium, is it because i'm on 1.16.5?

**Comment by LegendaryCrystalFox** [comment]
Just got confirmation from the AllTheMod Team that there is no fix for the crash between allthemodium and lastest version of ice and fire.
