### ISSUE TITLE
Sea Serpent Crash [2.1.10-1.16.5]

### ISSUE THREAD

**Issue by SpokenWig620933** [Alex-the-666/Ice_and_Fire#4568]
**Describe the bug**
I was just fighting the sea serpent in the water and then crashed, and every time I load into the world it crashes immediately.
https://pastebin.com/nRhGQNwp

**To Reproduce**
IDK,
I was just fighting it under water with flight.

**Expected behavior**
Not to crash...

**Comment by SpokenWig620933** [comment]
Any updates on this?

**Comment by RedstoneGamer123** [comment]
Any updates on this?

**Comment by TheBv** [comment]
You can try the latest snapshot build that should fix this issue: https://github.com/Alex-the-666/Ice_and_Fire/releases/tag/latest-snapshot
