### ISSUE TITLE
Hippocampus crash [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by Latchy2022** [Alex-the-666/Ice_and_Fire#4570]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
i try to get into my worlds and it crashes and it says something about Hippocampus

**To Reproduce**
1. Go to singleplayer
2. Click on 1 2.0 world
3. See it log in and then crash

The game crashed whilst mouseclicked event handler
Error: java.lang.NoSuchFieldError: HIPPOGRYPH
Exit Code: -1

**Comment by ModernGamingWorld** [comment]
Should be fixed with https://github.com/Alex-the-666/Ice_and_Fire/releases/tag/latest-snapshot

**Comment by TheBv** [comment]
Are you using Allthemodium? 
This crash seems similar to this one here:
https://github.com/Alex-the-666/Ice_and_Fire/issues/4566

**Comment by ModernGamingWorld** [comment]
@TheBv NOPE

**Comment by maxell45146** [comment]
Tried using the snapshot to update the IaF jar for the ATM6 modpack, same error Hippocampus crash
[debug.log](https://github.com/Alex-the-666/Ice_and_Fire/files/9107926/debug.log)
.

**Comment by TheBv** [comment]
@maxell45146 This seems to be an issue with the ATM modpack in general and not ice and fire. 
In #4566 someone mentioned that they'd have a fix for it "soon".
