### ISSUE TITLE
Crash [iceandfire-2.1.10-1.16.5.jar]

### ISSUE THREAD

**Issue by timtornado** [Alex-the-666/Ice_and_Fire#4571]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
as i was walking along in single player i saw what seemed to be an ice tornado in the distance and then the game crashed (crashlog link below.

**To Reproduce**
1. was near village and ice dragon seemed to be killing mobs
2. CRASH
3. See error

**Expected behavior**
ice dragon fights mob mob dies

**Screenshots**

**Additional context**
https://paste.ee/p/LtCIw#nYALTr4U7WNEq9T_QkYivEhxk8v65YML

**Comment by TheBv** [comment]
I'm assuming you meant to upload the log files regarding the crash, the data doesn't seem correct to me though.
Please provide the latest crash log or ideally the latest debug.log the crash appears in.

**Comment by Azeryahu** [comment]
I am having issues with 2.1.10 as well, yet I am not even able to launch my server. It says "Ice and Fire (iceandfire) encountered an error durring the load_registeries event phase" and something about "ForgeSpawnEggItem". Is there a fix for this or not?

[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/9106366/latest.log)

**Comment by TheBv** [comment]
Update forge to the newest version
