### ISSUE TITLE
My worlds wont load

### ISSUE THREAD

**Issue by Ecconotsystem** [Alex-the-666/Ice_and_Fire#4573]
I have to make a new world for this mod but after its done loading the the generation it says "joining world" then it goes to a loading screen that says "saving world" then mc stops responding and I have to close mc

**Comment by ghost** [comment]
You can't say that this is an issue with I&F with just that bit of information, please give your lastest log.

**Comment by Ecconotsystem** [comment]
![IMG_1527](https://user-images.githubusercontent.com/90052934/178800964-56bdcfb2-1c50-416b-9b7c-4a97b521a0c7.jpg)
This is what it does
