### ISSUE TITLE
Game crashing "whilst rendering overlay"

### ISSUE THREAD

**Issue by jajabinkzz** [Alex-the-666/Ice_and_Fire#4575]
I was playing perfectly fine; I went to load up the modpack I'm playing, and it would load but never make it to the play screen before taking me back to the launcher and giving me the error code

Error: net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file cucumber-client.toml of type CLIENT for modid cucumber
Exit Code: -1

https://pastebin.com/4C73P4CZ

**Comment by TheBv** [comment]
It states `Failed loading config file cucumber-client.toml of type CLIENT for modid cucumber` which tells me this has to do with the cucumber mod. I'd suggest making sure that the config file cucumber-client.toml exists or try to delete and replace it.

**Comment by jajabinkzz** [comment]
thank you! how would I go about getting the file since I don't seem to have it?

**Comment by TheBv** [comment]
I'd bring it up to the creator of the mod `Cucumber Library`
