### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION] Not compatible with A Bit Of Everything 3 Modpack on Apex Servers?

### ISSUE THREAD

**Issue by queenramrod** [Alex-the-666/Ice_and_Fire#4576]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
I added this mod to the ABOE3 modpack on my Apex server, but when I try to join the server with this modpack it gives an error that reads: 
io.netty.channel.abstractchannel$annotatedconnectexception connection timed out no further information

**To Reproduce**
1.Add mod to ABOE3 modpack
2. Add to server
3. Try to connect to server
4. Get error

**Expected behavior**
I would be able to connect to the server with this mod installed.

**Screenshots**

**Additional context**

**Comment by TheBv** [comment]
Please provide the crash log. Otherwise there's very little to go off of.
