### ISSUE TITLE
dragon_fire crash [ICE AND FIRE VERSION] 2.1.10

### ISSUE THREAD

**Issue by baddestcanvas85** [Alex-the-666/Ice_and_Fire#4577]
I am playing with 234 mods. The game kicks my from my minecraft worlds. 
https://bytebin.lucko.me/29vuB5Gqap

**Comment by Zthenerous** [comment]
Hi! I noticed you have 'Magnesium/Rubidium Extras' and I've also been having this problem. I tested it out, and removing that mod stopped conflicting with the newest version of Ice and Fire. Hope this helps.

**Edit**: Well it stopped a majority of the problem. But it still ended up crashing after I threw a fireball at myself (from Genesis, an Origins addon).
