### ISSUE TITLE
[1.12.2]  Hatched dragon attaches to wrong player

### ISSUE THREAD

**Issue by MarkColo2** [Alex-the-666/Ice_and_Fire#458]
When I play on a local single player server (LAN enabled) with my son and my wife, I have to leave the game or any dragon hatched by my son will assign to me instead of him.  My wife is running the server.  My son and I are both joining that server.

**Comment by TheMachine02** [comment]
I am fairly sure dragon is assigned to the closest player when they hatch, not the one who placed the egg. Can you try to get farther than the second player to see if the issue persist ?

**Comment by AlexModGuy** [comment]
its by closest player, not by who placed the egg
