### ISSUE TITLE
Ice and Fire (iceandfire) encountered an error during the load_registries event phase. ICE AND FIRE 1.16.5

### ISSUE THREAD

**Issue by Ailuluka** [Alex-the-666/Ice_and_Fire#4580]
I don't think it's a bug, but I didn't know where else to go for help.
It's just a crash that happens upon launching.

![Capture](https://user-images.githubusercontent.com/109475067/179410922-907afa22-109d-47ce-bff5-a360fb7a4a51.PNG)

[aaaaaa.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/9128070/aaaaaa.txt)
This is my crash report.

**Comment by TheBv** [comment]
Update forge
