### ISSUE TITLE
Lightning Dragon Crash iceandfire-2.1.9-1.16.5/ iceandfire-2.1.10-1.16.5

### ISSUE THREAD

**Issue by liviniumnetwork** [Alex-the-666/Ice_and_Fire#4589]
Ice And Fire Lightning Dragon crash
Version "iceandfire-2.1.9-1.16.5"
Just tested on new version "iceandfire-2.1.10-1.16.5", bug is still present

Description of the bug
When you have a tamed/raised lightning dragon and try to fly it, the server hangs for a moment before crashing and restarting.
When a wild lightning dragon (Stage 4 to 5) begins to fly, the server hangs for around half a minute & will not be at full performance until the wild dragon is killed. As far as my testing goes, this issue is only with lightning elements. 
It should be known that this is on my server I have with friends.

1. Get a lightning dragon (Ice And Fire version 2.1.9-1.16.5, and now iceandfire-2.1.10-1.16.5)
2. Right click to ride, it will lag for a moment before going back to normal. (You can walk around, use attacks etc)
3. Try to take off with the dragon, as described above, you should crash. 

Expected behavior:
The other elemental dragons are able to fly around without error, I would expect this to be the same for lightning. Fire and Ice are not effected by this bug.

I will add 2 crash logs, maybe they will be of help here. They are from the same time, one moments after the other.

[crash-2022-07-24_14.49.58-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/9176044/crash-2022-07-24_14.49.58-server.txt)
[crash-2022-07-24_15.00.14-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/9176045/crash-2022-07-24_15.00.14-server.txt)

**Comment by TheBv** [comment]
Most likely another mod effecting how some things are done. Either way should hopefully be slightly better with a1df3de
