### ISSUE TITLE
Error when launching world

### ISSUE THREAD

**Issue by Ecconotsystem** [Alex-the-666/Ice_and_Fire#4590]
When I launch the Ice and fire mod and try to open a world minecraft stops responding and I have to close it.
This is the crash report
[crash-2022-07-25_12.28.52-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/9184338/crash-2022-07-25_12.28.52-server.txt)

**Comment by TheBv** [comment]
The crash contains this line `Failed loading config file sleeping_bags-server.toml of type SERVER for modid sleeping_bags`
I'd look into deleting/recreating the sleeping bags config file. Doesn't seem to be an issue with ice and fire.

**Comment by Ecconotsystem** [comment]
Thank you
