### ISSUE TITLE
fire dragon crash [v2.1.10 - 1.16.5]

### ISSUE THREAD

**Issue by timtornado** [Alex-the-666/Ice_and_Fire#4591]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
was idle on the server when it randomly crashed, this is a fresh world

**Expected behavior**
no crashes

**Screenshots**

**Additional context**
https://paste.ee/p/Qzgz9

**Comment by TheBv** [comment]
Most likely a similar issue as #4606
Try identifying any mods that add extra entity pathfinding behaviors to existing mobs and try excluding ice and fire from them.
