### ISSUE TITLE
Bug with Tide Trident

### ISSUE THREAD

**Issue by Joseluisinho** [Alex-the-666/Ice_and_Fire#4592]
Hi, I think I found a bug in the mods pack in which when you throw the trident mod Ice and Fire, when you pick it up becomes a trident of Minecraft Vanilla, is version 1.16.5 I made a video in which you see this bug, I pass the link of video:

https://youtu.be/FFERjXqC7Zo

**Comment by TheBv** [comment]
Can't seem to replicate this for version 2.1.10. Closing for now.
