### ISSUE TITLE
random worldgen crash [iceandfire:2.1.9-1.16.5]

### ISSUE THREAD

**Issue by lele92007** [Alex-the-666/Ice_and_Fire#4596]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
after about 36h of uptime, the server randomly crashed
the server was running the modpack chroma tech 2, with 17 gigs or ram allocated, + 3 extra gigs for offheap
forge version is 1.16.5-36.2.22

**To Reproduce**
1. set up a server
2. generate some terrain
3. wait a few days with a player afk

**Expected behavior**
the server should be stable

**Additional context**
https://pastebin.com/h4DKRRgM

**Comment by TheBv** [comment]
Probably has to do with the mod `chocolate` (aka `chocolate-fix`) they seem to be using a mixin to affect world gen.
Not quite sure why this is breaking things but it is.
Closing for now.
