### ISSUE TITLE
[1.12.2] Crash Report

### ISSUE THREAD

**Issue by KAfable** [Alex-the-666/Ice_and_Fire#460]
https://hastebin.com/ugopevoran.sql

Was traveling a desert when it crashed me clientside.

**Comment by tyra314** [comment]
After looking into the code, I'm convinced that the vanilla code merely is broken.
But first things first. Looking at the exception and the reference code, it's clear something is wrong: `java.lang.Byte cannot be cast to java.lang.Boolean`
There should not be a fucking byte in the map under this key. Looking at `net.minecraft.network.datasync.EntityDataManager.createKey()`, I think the keys generated to internally handle the `DataParameter`s aren't unique. Therefore, it may happen that two data parameters get the same internal id and thus it will clash leading to the observed crash, in the best case! Worst case, two semantically distant `DataParameter`s are silently used from two different mods.

**Comment by AlexModGuy** [comment]
ah so primitive mobs was causing this the whole time! good to know.
