### ISSUE TITLE
Server crashes upon use of Ice Sword effect

### ISSUE THREAD

**Issue by Finntastic456** [Alex-the-666/Ice_and_Fire#4604]
Hi, I own a public Minecraft server, and we've added Ice and Fire, Spartan Weaponry, Sparton Weaponry + Ice and Fire, Alex's Mobs, Citadel, Yungs Bridges, Tetra, Create, and Immersive Portals. All are latest version of the mod for 1.16.5 except Ice and Fire. Ice and Fire is currently one version behind because the newest version won't let the server start. The image below is what happens with the Ice sword according to the console right before the server crashes instantly. My coowner and I think this is a compatibility issue, but I tested everything in single player and it worked fine. It must be something thats happening between the mod and the server. Forge on the server is running on the latest update for 1.16.5 and on Java 8 as far as I know. If you any more details are needed / you have any questions please let me know and I will get back to you ASAP. Thank you for taking the time to read this!
![image](https://user-images.githubusercontent.com/75586289/182009640-28f6fb69-11e5-4126-aeb4-e9a8c52dfb6c.png)

**Comment by TheBv** [comment]
Issue with spartanweaponry. Upgraded to the latest version of it.
https://www.curseforge.com/minecraft/mc-mods/spartan-weaponry-ice-and-fire/files/3858947
