### ISSUE TITLE
Dragons won't spawn in specified biomes or dimensions [1.16.5] Ver 2.1.102

### ISSUE THREAD

**Issue by chummybummy** [Alex-the-666/Ice_and_Fire#4607]
**Describe the bug**
None of the dragons or their corresponding structures are spawning in the specified dimensions or biomes.

**To Reproduce**
For the fire dragon biomes json I have it configured like so
{
  "biomes": [
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "blue_skies:unorthodox_valley"
      },
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "blue_skies:crystal_roughs"
      },
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "blue_skies:sunset_maple_forest"
      },
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "blue_skies:searing_grassland"
      },
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "blue_skies:moonlit_reservoir"
      },
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "blue_skies:shaded_woodlands"
      }
    ]
  ]
}
Yet no fire dragons spawn in the dimension. The same goes for the ice and the lightning dragons in their biomes and dimension. I also had the dimension whitelisted and still nothing. However I was able to get them to spawn in the hals exploration dimension, but i was using the same type REGISTRY_NAME so Im completely stumped.
Mod List: 
		BetterDungeons-1.16.4-1.2.1.jar                   |YUNG's Better Dungeons        |betterdungeons                |1.16.4-1.2.1       
		immersivecooking-1.2.0.jar                        |Immersive Cooking             |immersivecooking              |1.2.0               |DONE      
		infernal-expansion-1.16.5-2.5.0.jar               |Infernal Expansion            |infernalexp                   |2.5.0               |DONE      
		Dense Ores Reborn 1.16.5 v2.1.jar                 |Dense Ores Reborn             |denseoresreborn               |2.1                 |DONE      
		stalwart-dungeons-1.16.5-1.1.7 (2).jar            |Stalwart Dungeons             |stalwart_dungeons             |1.1.7               |DONE      
		looot-1.16.4-1.0.0.3.jar                          |Looot                         |looot                         |1.0.0.3             |DONE      |Manifest: 
		Neat+1.7-27.jar                                   |Neat                          |neat                          |1.7-27              |DONE      |Manifest: 
		helpwanted-1.3-SNAPSHOT.jar                       |Help Wanted                   |helpwanted                    |1.3-SNAPSHOT        |DONE      
		BetterCaves-Forge-1.16.4-1.1.2.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.2        |DONE      
		YungsApi-1.16.4-Forge-13.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-13     |DONE      
		pyromancer 1.7.0.3.jar                            |Pyromancer                    |pyromancer                    |1.7.0.3             |DONE      |Manifest: 
		ColouredTooltips-1.16.5-11.0.3.jar                |ColouredTooltips              |colouredtooltips              |11.0.3              |DONE      
		armorcurve-2.4.jar                                |Armor Curve                   |armorcurve                    |2.4                 |DONE      |Manifest: 
		mdecore-1.16.4-16.1.0.jar                         |MattDahEpic Core              |mdecore                       |16.1.0              |DONE      E
		extrapotions-1.16.4-1.2.jar                       |Extra Potions                 |extrapotions                  |1.16.4-1.2          |DONE      
		lootbeams-1.16.5-release-nov0221.jar              |LootBeams                     |lootbeams                     |1.16.5              |DONE      
		guardvillagers-1.16.5.1.2.6.jar                   |Guard Villagers               |guardvillagers                |1.2.6               |DONE      RE
		Apotheosis-1.16.5-4.8.99F.jar                     |Apotheosis                    |apotheosis                    |4.8.99F             |DONE      
		PickUpNotifier-v1.2-1.16.3.jar                    |Pick Up Notifier              |pickupnotifier                |1.2                 |DONE      
		The-Hordes-1.16.5-1.1.4b.jar                      |The Hordes                    |hordes                        |1.1.4b              |DONE      |Manifest: 
		BetterThanMending-1.6.0.jar                       |BetterThanMending             |betterthanmending             |1.6.0               |DONE      
		TinkersDelight-1.16-1.8.jar                       |Tinker's Delight              |tdelight                      |1.16-1.8            |DONE      |Manifest: 
		shetiphiancore-1.16-3.8.15.jar                    |ShetiPhian-Core               |shetiphiancore                |3.8.15              |DONE      
		betterendforge-1.16.5-1.6.3.jar                   |BetterEnd Forge               |betterendforge                |1.16.5-1.6.3        |DONE      
		structure_gel-1.16.5-1.7.8.jar                    |Structure Gel API             |structure_gel                 |1.7.8               |DONE      
		AdvancementPlaques-1.16.5-1.4.1.jar               |Advancement Plaques           |advancementplaques            |1.4.1               
		castle_in_the_sky-1.16.5-0.2.6.jar                |Castle in the sky             |castle_in_the_sky             |1.16.5              |DONE      
		repurposed_structures_forge-3.4.7+1.16.5.jar      |Repurposed Structures         |repurposed_structures         |3.4.7+1.16.5        
		morevillagers-FORGE-1.16.5-1.5.5.jar              |More Villagers                |morevillagers                 |1.5.5               |DONE      
		Aquamirae 3.0.0.jar                               |Aquamirae                     |ob_aquamirae                  |3.0.0               |DONE      |Manifest: 
		Blur-1.1.0-1.jar                                  |Blur                          |blur                          |1.1.0-1             |DONE      |Manifest: 
		ChunkAnimator-1.16.5-1.2.4.jar                    |Chunk Animator                |chunkanimator                 |1.16.5-1.2.4        |DONE      
		toughnessbar-6.1.jar                              |Toughness Bar                 |toughnessbar                  |6.1                 |DONE      |Manifest: 
		propertymodifier-1.16.5-0.6.4.jar                 |Property Modifier             |propertymodifier              |1.16.5-0.6.4        |DONE          
		Highlighter-1.16.5-1.1.1.jar                      |Highlighter                   |highlighter                   |1.1.1               |DONE      |Manifest: 
		lycanitesmobs-1.16.5-2.3.3.3.jar                  |Lycanites Mobs                |lycanitesmobs                 |1.16.5-2.3.3.3      |DONE      
		curios-forge-1.16.5-4.0.8.2.jar                   |Curios API                    |curios                        |1.16.5-4.0.8.2      |DONE      |Manifest: 
		carrotslib-mc1.16.5-3.0.1.jar                     |Carrots Lib                   |carrots                       |3.0.1               |DONE      |Manifest: N
		obfuscate-0.6.3-1.16.5.jar                        |Obfuscate                     |obfuscate                     |0.6.3               |DONE      |Manifest: 
		Chunk Pregenerator-V1.16-3.3.3.jar                |Chunk Pregenerator            |chunkpregen                   |V1.16-3.3.3         |DONE      
		NetherAgriculture-1.16.5-1.2.1.jar                |Nether Agriculture            |netheragriculture             |1.2.1               |DONE      
		Atlas-Lib-1.16.5-1.1.3c.jar                       |Atlas Lib                     |atlaslib                      |1.1.3c              |DONE      |Manifest: 
		majruszs-difficulty-1.16.4-1.1.0.jar              |Majrusz's Progressive Difficul|majruszs_difficulty           |1.1.0               |DONE      
		sapience-1.16.5-1.1.2.jar                         |Sapience                      |sapience                      |1.1.2               |DONE      |Manifest: 
		mutantmore-1.16.5-1.0.1.jar                       |Mutant More                   |mutantmore                    |1.0.3               |DONE      
		observerlib-1.16.5-1.5.3.jar                      |ObserverLib                   |observerlib                   |1.16.5-1.5.3        |DONE      
		cloth-config-4.14.64-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.14.64             |DONE      
		BetterBurning-1.16.5-6.0.8.jar                    |BetterBurning                 |betterburning                 |6.0.8               |DONE      
		Disenchanting-forge-1.16.5-1.7.2.jar              |Disenchanting                 |disenchanting                 |1.6.0               |DONE      
		BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        
		nomowanderer_MC1.16.5_1.2.jar                     |NoMoWanderer                  |nomowanderer                  |1.16.5_1.2          |DONE      
		mowziesmobs-1.5.25.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.25              |DONE      
		geckolib-forge-1.16.5-3.0.81.jar                  |GeckoLib                      |geckolib3                     |3.0.81              |DONE      |Manifest: 
		TonsOfEnchants-1.16.5-1.1.jar                     |Tons Of Enchantments          |tonsofenchants                |1.16.5              |DONE      
		shieldmechanics-2.8-1.16.5.jar                    |Shield Mechanics              |shieldmechanics               |2.8-1.16.5          |DONE      
		jei-1.16.5-7.7.1.152.jar                          |Just Enough Items             |jei                           |7.7.1.152           |DONE      |Manifest: 
		AttributeFix-1.16.5-10.1.4.jar                    |AttributeFix                  |attributefix                  |10.1.4              |DONE      |Manifest: 
		LibraryFerret-Forge-1.16.5-2.0.0.jar              |Library ferret                |libraryferret                 |2.0.0               |DONE      |Manifest: 
		caelus-forge-1.16.5-2.1.3.2.jar                   |Caelus API                    |caelus                        |1.16.5-2.1.3.2      |DONE      |Manifest: 
		colytra-forge-1.16.5-5.1.1.2.jar                  |Colytra                       |colytra                       |1.16.5-5.1.1.2      |DONE      |Manifest: 
		AwesomeDungeonForge-1.16.5-2.0.11.jar             |Awesome Dungeon               |awesomedungeon                |1                   
		NaturesCompass-1.16.5-1.9.1-forge.jar             |Nature's Compass              |naturescompass                |1.16.5-1.9.1-forge  
		SereneSeasons-1.16.5-4.0.1.125-universal.jar      |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.125    
		stoneholm-1.2.2.jar                               |Stoneholm                     |stoneholm                     |1.2                 |DONE      |Manifest: 
		curioofundying-forge-1.16.5-5.2.0.0.jar           |Curio of Undying              |curioofundying                |1.16.5-5.2.0.0      |DONE      
		BetterHurtTimer-1.16.3-4.5.2.3.jar                |Better Hurt Timer             |betterhurttimer               |1.16.3-4.5.2.3      |DONE      
		catalogue-1.6.1-1.16.5.jar                        |Catalogue                     |catalogue                     |1.6.1               |DONE      |Manifest: JEITweaker-1.16.5-1.1.0.49.jar                    |JEI Tweaker                   |jeitweaker                    |1.1.0.49            |DONE      |Manifest: 
		CraftTweaker-1.16.5-7.1.2.511.jar                 |CraftTweaker                  |crafttweaker                  |7.1.2.511           |DONE      
		GameStages-Forge-1.16.5-7.3.13.jar                |GameStages                    |gamestages                    |7.3.13              |DONE      
		ImmersivePetroleum-1.16.5-3.4.0-12.jar            |Immersive Petroleum           |immersivepetroleum            |3.4.0-12            
		crumbs-forge-1.0.7.jar                            |Crumbs                        |crumbs                        |1.0.7               |DONE      |Manifest: 
		forge-1.16.5-36.2.35-universal.jar                |Forge                         |forge                         |36.2.35             |DONE      |Manifest: 
		Atum-1.16.5-2.2.11.jar                            |Atum 2                        |atum                          |1.16.5-2.2.11       |DONE      |Manifest: 
		subwild-1.3.1.jar                                 |Subterranean Wilderness       |subwild                       |1.3.1               |DONE      |Manifest: 
		DynamicSurroundings-1.16.5-4.0.5.0.jar            |§3Dynamic Surroundings        |dsurround                     |4.0.5.0             |DONE      
		DungeonsArise-1.16.5-2.1.49-beta.jar              |When Dungeons Arise           |dungeons_arise                |2.1.49              |DONE      
		forge-1.16.5-36.2.35-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: 
		cofh_core-1.16.5-1.5.0.11.jar                     |CoFH Core                     |cofh_core                     |1.5.0.11            |DONE      |Manifest: 
		HungerStrikeRenewed-1.16.5-4.0.0.jar              |Hunger Strike Renewed         |hsr                           |4.0.0-edit          |DONE      
		inventoryhotswap-1.16-1.2.jar                     |Inventory Hotswap             |inventoryhotswap              |1.0                 |DONE      
		storage_overhaul-1.16.5-1.0.4.jar                 |Storage Overhaul              |storage_overhaul              |1.16.5-1.0.4        |DONE      
		wardance-0.8.7.1.jar                              |Project: War Dance            |wardance                      |0.8.7.1             |DONE      |Manifest: 
		majrusz-library-1.16.4-2.0.1.jar                  |Majrusz Library               |majrusz_library               |2.0.1               |DONE      
		dimdungeons-1.13.1.jar                            |Dimensional Dungeons          |dimdungeons                   |1.16.4-1.13.1       |DONE      
		flywheel-1.16-0.2.5.jar                           |Flywheel                      |flywheel                      |1.16-0.2.5          |DONE      |Manifest: 
		steampowered-1.16.5-1.2.0-hf1.jar                 |Create: Steam Powered         |steampowered                  |1.16.5-1.2.0-hf1    
		Mantle-1.16.5-1.6.157.jar                         |Mantle                        |mantle                        |1.6.157             |DONE      |Manifest: 
		stonecutter_recipe_tags-2.0.0-forge-1.16.jar      |Stonecutter Recipe Tags       |stonecutter_recipe_tags       |2.0.0               |
		polymorph-forge-1.16.5-0.40.jar                   |Polymorph                     |polymorph                     |1.16.5-0.40         |DONE      
		JustEnoughProfessions-1.16.5-1.2.2.jar            |Just Enough Professions (JEP) |justenoughprofessions         |1.2.2               
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |DONE      |Manifest: 
		structurize-1.16.5-1.0.392-RELEASE.jar            |Structurize                   |structurize                   |1.16.5-1.0.392-RELEA|DONE      
		FastFurnace-1.16.5-4.5.0.jar                      |FastFurnace                   |fastfurnace                   |4.5.0               |DONE      |Manifest: 
		appleskin-forge-mc1.16.x-2.4.0.jar                |AppleSkin                     |appleskin                     |2.4.0+mc1.16.4      |DONE      
		PuzzlesLib-v1.0.15-1.16.5-Forge.jar               |Puzzles Lib                   |puzzleslib                    |1.0.15              |DONE      
		byg-1.3.5.jar                                     |Oh The Biomes You'll Go       |byg                           |1.3.4               |DONE      |Manifest: 
		Aquaculture-1.16.5-2.1.22.jar                     |Aquaculture 2                 |aquaculture                   |1.16.5-2.1.22       |DONE      
		Obscuria's Essentials 3.0.0.jar                   |Obscuria's Essentials         |ob_core                       |3.0.0               |DONE      
		CosmeticArmorReworked-1.16.5-v5.jar               |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.5-v5           
		convenientcurioscontainer-1.3-1.16.5.jar          |Convenient Curios Container   |convenientcurioscontainer     |3_forge-1.16.5      
		parrying-unofficial-2.2.2a.jar                    |Parrying                      |parrying                      |2.2.2               |DONE      |Manifest: 
		TreeChop-1.16.4-0.14.6-fixed.jar                  |HT's TreeChop                 |treechop                      |0.14.6              |DONE      
		blue_skies-1.16.5-1.1.3.jar                       |Blue Skies                    |blue_skies                    |1.1.3               |DONE      |Manifest: 
		UnionLib-1.16.5-3.3.7.jar                         |UnionLib                      |unionlib                      |3.3.7               |DONE      |Manifest: 
		Piglin Expansion 1.2.jar                          |Piglin Expansion              |piglin_expansion              |1.1.0               |DONE      E
		enhanced_celestials_mobifier_integration-1.0-1.16.|Enhanced Celestials Mobifier I|enhanced_celestials_mobifier_i|1.0                 
		Architects-Palette-1.16.4-1.1.5.jar               |Architect's Palette           |architects_palette            |1.1.2               |DONE      
		incontrol-1.16-5.2.10.jar                         |InControl                     |incontrol                     |1.16-5.2.10         |DONE      |Manifest: 
		autooredictconv-1.16.4-16.1.10.jar                |Auto Ore Dictionary Converter |autooredictconv               |16.1.10             |DONE      
		InsaneLib-1.4.2-mc1.16.5.jar                      |InsaneLib                     |insanelib                     |1.4.2               |DONE      |Manifest: 
		TerraForged-1.16.5-0.2.16-BETA-2.jar              |TerraForged                   |terraforged                   |0.2.16-BETA-2       |DONE      
		Placebo-1.16.5-4.7.0.jar                          |Placebo                       |placebo                       |4.7.0               |DONE      |Manifest: 		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |DONE      |Manifest: NOSIGNATURE
		iceandfire-2.1.10-1.16.5.jar                      |Ice and Fire                  |iceandfire                    |2.1.10-1.16.5       |DONE      |Manifest: 
		customvillagertrades-1.16_V17.jar                 |Custom Villager Trades        |customvillagertrades          |1.16 v17            |DONE      
		MutantBeasts-1.16.4-1.1.3.jar                     |Mutant Beasts                 |mutantbeasts                  |1.16.4-1.1.3        |DONE      
		Bookshelf-Forge-1.16.5-10.4.32.jar                |Bookshelf                     |bookshelf                     |10.4.32             |DONE      |
		magnesium-1.5 (1).jar                             |Magnesium                     |magnesium                     |1.5                 |DONE      
		consistency_plus-0.4.3+1.16-forge.jar             |Consistency Plus              |consistency_plus              |0.4.3+1.16-forge    |DONE      
		relics-1.16.5-0.3.4.3.jar                         |Relics                        |relics                        |0.3.4.3             |DONE      |Manifest: 
		jeed-1.16.5-1.6.jar                               |Just Enough Effect Description|jeed                          |1.16.5-1.6          |DONE      
		FpsReducer-forge-1.24-mc1.16.5.jar                |FPS Reducer                   |fpsreducer                    |1.24-mc1.16.5       |DONE      
		carryon-1.16.5-1.15.5.22.jar                      |Carry On                      |carryon                       |1.15.5.22           |DONE      |Manifest: 
		MmmMmmMmmMmm-1.16.5-1.3.1.jar                     |MmmMmmMmmMmm                  |dummmmmmy                     |1.3.0               
		EquipmentCompare-1.16.5-1.2.7.jar                 |Equipment Compare             |equipmentcompare              |1.2.7               
		OreTweaker-1.16.5-2.7.1.jar                       |Ore Tweaker                   |oretweaker                    |2.7.1               |DONE      
		chocolate-1.3.0-1.16.4.jar                        |Chocolate                     |chocolate                     |1.3.0-1.16.4        |DONE      |Manifest: 
		UndeadExpansion-2.0.0-1.16.5.jar                  |Undead Expansion              |undead_expansion              |2.0.0               |DONE      
		mcw-bridges-2.0.3-mc1.16.5.jar                    |Macaw's Bridges               |mcwbridges                    |2.0.3               |DONE      
		FarmersDelight-1.16.5-0.6.0.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.6.0        |DONE      
		DistantHorizons-1.6.5a-1.16.5.jar                 |Distant Horizons              |lod                           |1.6.5a              |DONE      |Man
		endrem-5.0.3-R-1.16.5.jar                         |End Remastered                |endrem                        |5.0.3-R-1.16.5      |DONE      
		mcw-fences-1.0.5-mc1.16.5.jar                     |Macaw's Fences and Walls      |mcwfences                     |1.0.5               |DONE      
		dungeons_enhanced-1.16.5-1.7.jar                  |Dungeons Enhanced             |dungeons_enhanced             |1.7                 |
		Bountiful-1.16.4-3.3.1.jar                        |Bountiful                     |bountiful                     |1.16.4-3.3.1        |DONE      |Manifest: N
		Cataclysm-0.20.jar                                |Cataclysm Mod                 |cataclysm                     |1.0                 |DONE      |Manifest: 
		Patchouli-1.16.4-53.3.jar                         |Patchouli                     |patchouli                     |1.16.4-53.3         |DONE      |Manifest: 
		ars_nouveau-1.16.5-1.25.2.jar                     |Ars Nouveau                   |ars_nouveau                   |1.25.2              |DONE      
		buildersaddition-1.16.5-20210807a.jar             |Builders Crafts & Addition    |buildersaddition              |1.16.5-20210807a   
		cavebiomeapi-1.16.5-1.4.2.jar                     |CaveBiomeAPI                  |cavebiomeapi                  |1.16.5-1.4.2        |DONE      
		InventoryProfilesNext-forge-1.16-1.6.0.jar        |Inventory Profiles Next       |inventoryprofilesnext         |1.6.0               |DONE      
		architectury-1.32.66.jar                          |Architectury                  |architectury                  |1.32.66             |DONE      |Manifest: 
		ftb-library-forge-1605.3.4-build.90.jar           |FTB Library                   |ftblibrary                    |1605.3.4-build.90   |DONE      
		ftb-teams-forge-1605.2.3-build.40.jar             |FTB Teams                     |ftbteams                      |1605.2.3-build.40   |DONE      
		UndergroundCrates_1.16.5-1.3.1.jar                |Underground Crates            |dungeoncrates                 |1.3.1               |DONE      
		enchantwithmob-1.16.5-1.5.2.jar                   |Enchant With Mob              |enchantwithmob                |1.16.5-1.5.2        |DONE      
		TradingPost-v1.0.2-1.16.5.jar                     |Trading Post                  |tradingpost                   |1.0.2               |DONE      |Manifest: 
		Cucumber-1.16.5-4.1.12.jar                        |Cucumber Library              |cucumber                      |4.1.12              |DONE      
		item-filters-forge-1605.2.5-build.9.jar           |Item Filters                  |itemfilters                   |1605.2.5-build.9    |DONE      
		EasyMagic-v1.0.4-1.16.5.jar                       |Easy Magic                    |easymagic                     |1.0.4               |DONE      |Manifest: 
		Druidcraft-1.16.5-0.4.54 (1).jar                  |Druidcraft                    |druidcraft                    |0.4.52              |DONE      |Manifest: 
		abnormals_core-1.16.5-3.3.1.jar                   |Abnormals Core                |abnormals_core                |3.3.1               |DONE      
		upgrade_aquatic-1.16.5-3.1.2.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.1.2               |DONE      
		savageandravage-1.16.5-3.2.0.jar                  |Savage & Ravage               |savageandravage               |3.2.0               |DONE      
		extraboats-1.16.5-2.1.1.jar                       |Extra Boats                   |extraboats                    |2.1.1               |DONE      |Manifest: 		ensorcellation-1.16.5-1.5.0.4.jar                 |Ensorcellation                |ensorcellation                |1.5.0.4             |DONE      |Manifest: 
		create-mc1.16.5_v0.3.2g (1).jar                   |Create                        |create                        |v0.3.2g             |DONE      |Manifest: 
		createdeco-1.1.2-1.16.5.jar                       |Create Deco                   |createdeco                    |1.1.2-1.16.5        |DONE      
		createautomated-1.16.5-1.4.1a.jar                 |Create Automated              |createautomated               |1.16.5-1.4.1a       |DONE      
		Waystones_1.16.5-7.6.4.jar                        |Waystones                     |waystones                     |7.6.4               |DONE      |Manifest: 
		Clumps-6.0.0.28.jar                               |Clumps                        |clumps                        |6.0.0.28            |DONE      |Manifest: 
		mgui-1.16.5-3.3.0.jar                             |mgui                          |mgui                          |3.3.0               |DONE      |Manifest: 
		journeymap-1.16.5-5.8.5p5.jar                     |Journeymap                    |journeymap                    |5.8.5p5             |DONE      
		RoadRunner-mc1.16.5-1.4.1.jar                     |Meep Meep! (Road Runner)      |roadrunner                    |1.4.1               |DONE      
		comforts-forge-1.16.5-4.0.1.5.jar                 |Comforts                      |comforts                      |1.16.5-4.0.1.5      |DONE      
		tumbleweed-1.16-0.4.9.jar                         |Tumbleweed                    |tumbleweed                    |1.16-0.4.9          |DONE      
		Artifacts-1.16.5-2.10.5.jar                       |Artifacts                     |artifacts                     |1.16.5-2.10.5       |DONE      |Manifest: 		SimpleStorageNetwork-1.16.5-1.5.3.jar             |Simple Storage Network        |storagenetwork                |1.16.5-1.5.3        |DONE      
		configured-1.5.2-1.16.5.jar                       |Configured                    |configured                    |1.5.2               |DONE      |Manifest: 
		ItemBorders-1.16.5-1.1.6.jar                      |Item Borders                  |itemborders                   |1.1.6               |DONE      
		decorative_blocks-1.16.4-1.7.2.jar                |Decorative Blocks             |decorative_blocks             |1.7.2               |DONE      
		betteranimalsplus-1.16.5-11.0.5-forge.jar         |Better Animals Plus           |betteranimalsplus             |1.16.5-11.0.5       |DONE      
		Obscuria's Tooltips 1.0.0.jar                     |Obscuria's Tooltips           |ob_tooltips                   |1.0.0               |DONE      |Manifest: 
		iChunUtil-1.16.5-10.6.1.jar                       |iChunUtil                     |ichunutil                     |10.6.1              |DONE      |Manifest: 
		VillagersFollowEmeralds-1.16.5-1.0.0.jar          |Villagers Follow Emeralds     |vfe                           |1.0.0               |DONE      
		PiggyBank(FORGE-1.16.4)+-+1.0.6.jar               |Piggy Bank                    |piggybankmod                  |1.16.4-1.0.6        |DONE      
		RecipeStages-2.0.0.21.jar                         |Recipe Stages                 |recipestages                  |2.0.0.21            |DONE      
		TravelersTitles-1.16.4-1.5.jar                    |Traveler's Titles             |travelerstitles               |1.16.4-1.5          |DONE      |Manifest: 
		IceAndFireTweaker-1.0.0.5.jar                     |Ice And Fire Tweaker          |iceandfiretweaker             |1.0.0.5             |DONE      
		dotcoinmod-1.16_V13.1.jar                         |Dot Coin Mod                  |dotcoinmod                    |1.16 13.1           |DONE      
		ImmersivePosts-1.16.5-4.3.0-1.jar                 |Immersive Posts               |immersiveposts                |4.3.0-1             |DONE      
		ImmersiveEngineering-1.16.5-5.1.0-148.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-5.1.0-148    
		EnchantmentDescriptions-1.16.5-7.1.20.jar         |EnchantmentDescriptions       |enchdesc                      |7.1.20              |DONE      
		swingthroughgrass-1.16.4-1.5.3.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.4-1.5.3        |DONE      
		Jade-1.16.4-2.8.2.jar                             |Jade                          |jade                          |2.8.2               |DONE      |Manifest: 
		CreativeCore_v2.2.1_mc1.16.5.jar                  |CreativeCore                  |creativecore                  |2.0.0               |DONE      
		smoothboot-forge-1.16.4-1.2.2.jar                 |Smooth Boot                   |smoothboot                    |1.16.4-1.2.2        |DONE      
		LargeFluidTank-16.1.9.jar                         |FluidTank                     |fluidtank                     |16.1.9              |DONE      |Manifest: 
		Iceberg-1.16.5-1.0.41.jar                         |Iceberg                       |iceberg                       |1.0.41              |DONE      |Manifest: 
		SpartanShields-1.16.5-2.1.2.jar                   |Spartan Shields               |spartanshields                |2.1.2               |DONE      
		Quark-r2.4-322.jar                                |Quark                         |quark                         |r2.4-322            |DONE      |Manifest: 
		charm-forge-1.16.5-2.3.2.jar                      |Charm                         |charm                         |2.3.2               |DONE      |Manifest: 
		LegendaryTooltips-1.16.5-1.1.7.jar                |Legendary Tooltips            |legendarytooltips             |1.1.7               |DONE      
		FastWorkbench-1.16.5-4.6.1.jar                    |Fast Workbench                |fastbench                     |4.6.1               |DONE      
		InventoryHud_[1.16.2-1.16.5].forge-3.4.1.jar      |Inventory HUD+(Forge edition) |inventoryhud                  |3.4.1               |
		minecolonies-1.16.5-1.0.736-RELEASE.jar           |MineColonies                  |minecolonies                  |1.16.5-1.0.736-
		workshopsofdoom-1.16.4-1.1.0.1.jar                |Workshops of Doom             |workshopsofdoom               |1.1.0.1             
		[BETA]dannys_expansion1.16.5-1.0.9.1.jar          |Danny's Expansion             |dannys_expansion              |1.0.9               |DONE      
		ferritecore-2.1.0-forge.jar                       |Ferrite Core                  |ferritecore                   |2.1.0               |DONE      |Manifest: 
		enhancedcelestials-2.0.9-1.16.5.jar               |Enhanced Celestials           |enhancedcelestials            |2.0.9-1.16.5        |DONE      
		illagers_plus-1.16.4v1.7.2 (2).jar                |Illagers+                     |illagers_plus                 |1.16.4v1.7.2        |DONE      |Manifest: 
		Craftable+Horse+Armour++Saddle-1.16.5-1.7--Forge.j|CHA&S - Craftable Horse Armour|craftablehorsearmour          |1.7                 
		expandability-2.0.1-forge.jar                     |ExpandAbility                 |expandability                 |2.0.1               |DONE      
		valhelsia_core-16.0.15.jar                        |Valhelsia Core                |valhelsia_core                |16.0.15             |DONE      |Manifest: 		overloadedarmorbar-5.1.0.jar                      |Overloaded Armor Bar          |overloadedarmorbar            |5.1.0               |DONE      

**Additional context**

**Comment by TheBv** [comment]
Please take a look at this: https://github.com/Alex-the-666/Ice_and_Fire/wiki/How-to-specify-the-regions-structures-and-mobs-can-be-spawned
What you've specified is that you want the dragon to spawn in a biome that matches all of the names you've specified. Which isn't possible.
What you want would be something like  "biomes" : [ [BIOME1], [BIOME2], [BIOME3],...]

**Comment by chummybummy** [comment]
Thank you so much for responding. Now the Lightning dragons are spawning perfectly in Atum, but both the ice and fire dragons are still not spwaning in the ever dawn or ever bright.
This is the fire one
{
  "biomes": [
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "blue_skies:unorthodox_valley"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "blue_skies:crystal_roughs"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "blue_skies:sunset_maple_forest"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "blue_skies:searing_grassland"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "blue_skies:moonlit_reservoir"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "blue_skies:shaded_woodlands"
      }
    ]
  ]
}
this is the ice one
{
  "biomes": [
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "blue_skies:polar_highland"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "blue_skies:brightlands"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "blue_skies:frostbitten_forest"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "blue_skies:slushlands"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "blue_skies:snow_covered_pines"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "blue_skies:calming_skies"
      }
    ]
  ]
}
could it have something to do with the temperature of the biomes?

**Comment by chummybummy** [comment]
Nvm I found the problem. Blue skies has a feature that allows certain structures form specified mods to spawn, and ice and fire was not on there.
