### ISSUE TITLE
Console Error [iceandfire-2.1.10-1.16.5]

### ISSUE THREAD

**Issue by BrandonT80** [Alex-the-666/Ice_and_Fire#4608]
**Describe the bug**
Console spit out an error when a chunk was generating. It said to report the bug

**To Reproduce**
1. Go to a new chunk that spawns the lightning_dragon
2. Check console

**Expected behavior**
Spawn the dragon, no errors.

**Additional context**
https://pastebin.com/Kz9Qbte6
Above is the error console told to report to the author. Might not be a big deal.

**Comment by TheBv** [comment]
Will be fixed in the upcoming version!
