### ISSUE TITLE
Dragon Armor (Ice and Fire 2.1.10)

### ISSUE THREAD

**Issue by Daniel190403** [Alex-the-666/Ice_and_Fire#4611]
Maxed out Dragons dont get extra armor points from a dragon armor.
Also Dragons get not more than 30 armor points, even if they have a full dragon steel armor. If a Dragon has a armor that gives the Dragon 30 armor points and you max out the Dragon and than take their armor away they keep their 30 armor points even if they dont wear the armor ( I saw this with the Torohealth Mod).

**Comment by TheBv** [comment]
That's a minecraft limitation. There's mods that fix that e.g AttributeFix
