### ISSUE TITLE
1.12.2 broken completely when I try to play it.

### ISSUE THREAD

**Issue by FerrisWheel1314** [Alex-the-666/Ice_and_Fire#4612]
I have no idea why, but whenever I load the latest version of Ice and Fire 1.12.2, it lags, dragons start cloning, and disappearing right in front of, dragons moving weird and incorrectly like not following any commands all while lagging, and much more. I’ve played Ice and Fire on 1.16.5 with plenty of other mods and and shaders and resource packs before with no real issues. Other versions of Ice and Fire 1.12.2 work for me but not the latest one. Even when ice and fire is one  of the only mods Im using, it just doesnt work.

**Comment by fallenthereaper** [comment]
No support will be given to old versions.

**Comment by FerrisWheel1314** [comment]
That's fine, but is there a way to fix these problems?

**Comment by FerrisWheel1314** [comment]
OMG Im f#$%ing stupid I forgot to allocate more ram. Im so sry.
