### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by Necro376** [Alex-the-666/Ice_and_Fire#4617]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
We created a server with my friends and we are having crashes in a certain chunk and in the crash report it indicates that it is an ice and fire object to be specific it says that it is the eye of cyclops, I would like some help please

**To Reproduce**
2. Click on
3. See error

**Expected behavior**
Please help me

**Additional context**
[crash-2022-08-07_23.54.14-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/9305444/crash-2022-08-07_23.54.14-client.txt)

[crash-2022-08-07_23.54.14-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/9305444/crash-2022-08-07_23.54.14-client.txt)

**Comment by TheBv** [comment]
Try out the latest snapshot that should fix it: https://github.com/Alex-the-666/Ice_and_Fire/releases/tag/latest-snapshot

**Comment by Necro376** [comment]
> Try out the latest snapshot that should fix it: https://github.com/Alex-the-666/Ice_and_Fire/releases/tag/latest-snapshot

Thanks I'm going to try it now and I'll tell you how it goes, I'll try to exchange the versions.

**Comment by Necro376** [comment]
> Try out the latest snapshot that should fix it: https://github.com/Alex-the-666/Ice_and_Fire/releases/tag/latest-snapshot

Thank you very much, you saved our server.
