### ISSUE TITLE
Crash when launching minecraft 1.16.5 with the mod [ice and fire 1.16.5]

### ISSUE THREAD

**Issue by BENS936** [Alex-the-666/Ice_and_Fire#4619]
Hi, 
I'm facing a issue when I try to launch minecraft 1.16.5 to play with a bunch of mods and specially with ice and fire mod
The game crash everytime and I get this message : 
![image](https://user-images.githubusercontent.com/111117051/184319024-0e4ed585-8aec-4968-b386-afc39cea4258.png)
I'm using the oldest version of the mod  (from curseforge) and citadel mod

If someone can help me it would be nice, the mod looks really great and I'm exited to try it ! 😄

**Comment by CapuccinoNt** [comment]
same thing happens to me, might be bc it needs an specific version of forge idk

**Comment by CapuccinoNt** [comment]
yes indeed, you have to use forge 36.2.8

**Comment by BENS936** [comment]
I installed forge 36.2.8 and same message of error with "ForgeSpawnEggItem"
Idk what can cause this issue..

**Comment by BENS936** [comment]
I find a way to make it works, just tried with a previous version of the mod, still 1.16.5 but not the last one and it's fine

**Comment by TheBv** [comment]
You need at least forge version `36.2.17` I'd have really liked to add that as a requirement but you can only do stuff like "36.2.X"
Anyways upgrading to that forge version should solve the issue :)
