### ISSUE TITLE
Server crashes randomly after some entities are coliding - 1.16.5

### ISSUE THREAD

**Issue by NemecRaphael** [Alex-the-666/Ice_and_Fire#4625]
**Describe the bug**
The server is crashing "randomly". This happened several times the last days with the same error. The server is then removing the entity and restarts (You can see in the logs)

**To Reproduce**
just playing the server. Nobody was exploring when this happened

**Additional logs**
1. server console logs:
https://justpaste.it/2iafz

2. crash report
https://justpaste.it/4gnpp

**Comment by TheBv** [comment]
Try out the latest snapshot from here https://github.com/Alex-the-666/Ice_and_Fire/releases/tag/latest-snapshot
That should fix it

**Comment by NemecRaphael** [comment]
> Try out the latest snapshot from here https://github.com/Alex-the-666/Ice_and_Fire/releases/tag/latest-snapshot That should fix it

This worked, ty! My friend can join now, even though he couldnt join after the last crash. Is there a date expected, when the snapshot will be released on curse?

**Comment by TheBv** [comment]
I do want to push it quite soon...
I just want to figure out one more bug before that. I guess sometime next week would be realistic.
