### ISSUE TITLE
[1.12.2] Dragon Skeletons Spin and are not interactable.

### ISSUE THREAD

**Issue by Misunderstood-Wookiee** [Alex-the-666/Ice_and_Fire#463]
Latest Forge, Current version of this mod and lib, Dragon Bones when enabled generate but spin in a circle and are sometimes not intractable

(pixie huts still cause a local server crash when block beneath is broken. )

**Comment by vagner1000** [comment]
Click with the right button on the Dragon Bone, but your hand have to be empty.

**Comment by AlexModGuy** [comment]
not a real bug; any mob "spins" when loaded into the chunk. Dragon skeletons only are noticeable due to their size.
