### ISSUE TITLE
My server keeps crashing! Ice and Fire so unstable!

### ISSUE THREAD

**Issue by AzaleaCatgirl99** [Alex-the-666/Ice_and_Fire#4630]
I have been running a public server for a few days with ice and fire 1.16.5 and about over 20 times the server has crashed and rolled back due to an Ice and Fire mod spawning in. I've never had this issue with 1.12.2 and seeing the recent updates, 1.16.5 is very unstable. Please help me and other people who are having the same issue. We are getting tired of worlds crashing and breaking things.

**Comment by RadonCoding** [comment]
Perhaps you should provide some crash logs?

**Comment by RadonCoding** [comment]
It might be some other mod causing ice and fire to crash

**Comment by AzaleaCatgirl99** [comment]
Alex's Mobs
Architectury API
Ars Nouveau
Artifacts
Better Third Person
Biomes O' Plenty
Callable Horses
Campfire Spawn & Tweaks
Catalogue
Citadel
Cloth Config API
Clumps
Collective
Comforts
Configured
Content Tweaker
Controlling
Cosmetic Armor Reworked
Craft Tweaker
Curios API
Custom NPCs
Custom Starter Gear
Default Options
Disable Elytras
Double Slabs
Dungeon Crawl
Dungeons Enhanced
Dynamic Trees
Dynamic Trees - BOP
End Remastered
Epic Fight
Epic Knights
Equipment Compare
Estus
Expand Ability
Fancy Menu
Farmer's Delight
FTB Library
Gecko Lib
Global GameRules
Healing Campfire
Horse Combat Controls
Hunger Strike
Ice & Fire Tweaker
Ice & Fire: Dragons
Iceberg
Immersive FX
Improved Backpacks
JEI Integration
JEI Tweaker
Just Enough Items
Just Enough Resources
Konkrete
Lazy DataFixer
Macaw's Furniture
Macaw's Paths
Macaw's Roofs
Magnesium
Magnesium Extras
Medieval Music
Mob Sunscreen
Mouse Twekas
Mowzie's Mobs
Mutant Beasts
Mutant More
Nef's Medieval Pub
Open Loader
Patchouli
PlayerEx
RoadRunner
RPG Hud
Shoulder Surfing
Simple Discord RPC
Simple Unbreakable Tools
Simple Voice Chat
Small Ships
Structure Gel API
Twilight Forest
Tool Belt
Valhelsia Core
Valhelsia Structures
Waystones
When Dungeons Arise
Xaero's Minimap
Xaero's World Map
YUNG's API
YUNG's Better Caves
YUNG's Better Dungeons
YUNG's Better Mineshafts
YUNG's Better Strongholds
YUNG's Bridges
YUNG's Extras

Would any of these conflict? 

I'll be sure to save the crash log the next time it crashes.

**Comment by RadonCoding** [comment]
It's hard for me to tell without the crash report

**Comment by RadonCoding** [comment]
You should see a folder called crash-reports in your server folder

**Comment by RadonCoding** [comment]
that's where you can find the crash-report from

**Comment by AzaleaCatgirl99** [comment]
[crash-2022-08-21_01.54.09-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/9389151/crash-2022-08-21_01.54.09-server.txt)
