### ISSUE TITLE
Death Worms causing major tick lag [2.1.10-1.16.5-SNAPSHOT+build.2202-08-03]

### ISSUE THREAD

**Issue by Anaerin** [Alex-the-666/Ice_and_Fire#4637]
**Describe the bug**
Currently, it seems Death Worm AI is causing major periodic lag spikes (upwards of 20 seconds for a tick), taking 30% of a tick's time.

**To Reproduce**
1. Run server
2. Have a Death Worm in a loaded chunk somewhere
3. Use something like Spark to get a snapshot of ticks over 1000ms

**Expected behavior**
Ideally, it should be taking no more than 0.1% of total execution, like other mobs.

**Screenshots**
https://spark.lucko.me/6hmsZWEf5q?hl=106,94

**Additional context**

**Comment by RadonCoding** [comment]
Can reproduce server is timing out sometimes.
