### ISSUE TITLE
Sirens having 1500 health for no reason

### ISSUE THREAD

**Issue by theo-artin** [Alex-the-666/Ice_and_Fire#4639]
Hey, as title says generated/egg spawned sirens have exactly 1500 health. I checked config files and went through the mod in general. Any other mods shouldnt affect the spawns, all the other creatures work as intended and react to changes in config.

Anyone else having this issue?

**Comment by PT400C** [comment]
@theo-artin Do you have got the [All The Tweaks](https://www.curseforge.com/minecraft/mc-mods/all-the-tweaks) mod installed? I remember it to mess up the stats of various IAF mobs.
