### ISSUE TITLE
structures not generating properly or being cut off by chunk borders [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by OneEevee** [Alex-the-666/Ice_and_Fire#4640]
As stated above if a generated structure stretches over multiple chunks it has a chance for one or more of the chunks to be over written by natural world generation. The modded generation like dragon dens can be over written by village structures and I assume other similar structure.

![2022-08-29_01 58 20](https://user-images.githubusercontent.com/90638601/187165139-11cb1da5-9fba-4f5e-8c10-44dddef80280.png)
![2022-08-29_01 58 26](https://user-images.githubusercontent.com/90638601/187165145-a2d69643-0f20-4ec8-a561-147ddbcf3ba1.png)
![2022-08-29_01 59 43](https://user-images.githubusercontent.com/90638601/187165151-5ff08a8c-ae1f-46b0-ac18-fe4818574292.png)
![2022-08-29_01 59 49](https://user-images.githubusercontent.com/90638601/187165157-bf4c5fec-4bd3-4984-9cd5-8314f9681384.png)
![2022-08-29_01 59 57](https://user-images.githubusercontent.com/90638601/187165177-3f58cd82-8e2a-4c8e-884c-67c985653d61.png)
![2022-08-29_02 00 01](https://user-images.githubusercontent.com/90638601/187165186-80a94e0c-51ee-4e65-b0e9-b98966c698ce.png)
![2022-08-29_02 01 07](https://user-images.githubusercontent.com/90638601/187165196-fc412184-a380-4e36-b5a1-32785fa28a54.png)
![2022-08-29_02 01 19](https://user-images.githubusercontent.com/90638601/187165203-c78531ed-805b-4c4e-a743-f68cab98505e.png)

**Comment by TheBv** [comment]
This won't be fixed as it would probably cause more issues. See #3720
