### ISSUE TITLE
Fantasy Realm v6 now spawns only baby dragons in the overworld

### ISSUE THREAD

**Issue by HappyRock0509** [Alex-the-666/Ice_and_Fire#4642]
The recent Fantasy Realm v6 release has an updated version of Ice and Fire. Upon exploring new regions of the map, 3 new overworld dragons spawned in as baby dragons, but the power of a lvl 3. Supposedly this is a previous glitch that has happened. Seems multiple people are having the same issue.

**Comment by TheBv** [comment]
#4699
