### ISSUE TITLE
Crash on hit from Phantasmal Blade projectile [iceandfire-2.1.11-1.16.5]

### ISSUE THREAD

**Issue by wpetrowski** [Alex-the-666/Ice_and_Fire#4647]
**Describe the bug**
Got a crash to desktop when hitting with a projectile from the Phantasmal Blade: https://mclo.gs/FmTJOu2
The entity hit was a colony raider from MineColonies.

**To Reproduce**
1. Couldn't repro this, unfortunately.  I've been using the sword for a while and this is the first time I've seen a crash from this.

**Expected behavior**
No crash when using the sword.

**Screenshots**

**Additional context**
Running this mod as part of the Fantasy Realm modpack: https://www.curseforge.com/minecraft/modpacks/fantasy-realm

**Comment by wpetrowski** [comment]
Another instance of the crash, this time while fighting a Ferrous Wroughtnaut.

https://mclo.gs/tkCawyV

**Comment by TheBv** [comment]
Honestly I have no idea how this might happen.
The only thing I can think about that could cause this would be a performance type mod that modifies either the math functions minecraft uses or how random numbers are generated.

**Comment by wpetrowski** [comment]
It does seem strange, there shouldn't be any way for the code to pass a negative to nextInt at that point.  Oh well!  Thanks for having a look, I appreciate it.
