### ISSUE TITLE
Crash Report unique to ice & fire (Modpack) [2.1.10]

### ISSUE THREAD

**Issue by veilenagrde** [Alex-the-666/Ice_and_Fire#4648]
Hi! attached are the crash report, latest.log, and a screenshot of the modpack folder if that helps.

1. launch, modpack gets loaded.
2. upon loading the client crashes.

This started the moment I tried adding in a couple mods so I've already removed those mods but the crash/error still shows up. I tried relaunch with ice&fire default configs, and same thing. when I remove ice&fire my client works. So I'm out of my capacity to solve this problem on my own I hope you're able to help, if there's any other information you need please get back to me, as this modpack has been an active passion project for a few years, thanks!

**Screenshots**
![mods 9_8_2022 8_19_31 AM (2)](https://user-images.githubusercontent.com/113110825/189120184-62c5b6fc-d5a0-447a-8fe0-caeb4fc2b7d1.png)

**Additional context**
[crash-2022-09-08_08.15.07-fml.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/9526678/crash-2022-09-08_08.15.07-fml.txt)
[latest.log](https://github.com/AlexModGuy/Ice_and_Fire/files/9526680/latest.log)
![Minecraft_ 1 16 5 9_8_2022 8_24_29 AM](https://user-images.githubusercontent.com/113110825/189120973-44b85307-b2f1-45df-82e5-bbcb19ac578a.png)

**Comment by TheBv** [comment]
Update forge

**Comment by veilenagrde** [comment]
Thank you! Can I ask how you knew that?

**Comment by TheBv** [comment]
There's this line in the logs:
```
-- MOD iceandfire --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/common/ForgeSpawnEggItem
```
So it's saying that it can't find the "file" ForgeSpawnEggItem which should be in minecraftforge. Meaning "forge is missing a file" (not in the literal sense).
We use `ForgeSpawnEggItem` to register the spawn eggs which was added in some 36.X forge version.

**Comment by veilenagrde** [comment]
Oohhh ok I see, thank you for replying. I’m very new to this side on the
mod pack development  so information like this helps a lot!
