### ISSUE TITLE
Dragon Health Not Updating [ICE AND FIRE VERSION 2.1.11-MC 1.16.5]

### ISSUE THREAD

**Issue by Chancho91** [Alex-the-666/Ice_and_Fire#4649]
Bug:
The dragons health doesn't age up past 1,024. I changed their maximum to 1,500.

**To Reproduce**
1. Use Dragon Meal 
2. Dragon's Health ages up but health isn't updating

**Expected behavior**
Dragon's health should update when it ages by 1 day.

![Screenshot (135)](https://user-images.githubusercontent.com/24527489/189513013-b8a97f8d-fa09-4262-a0d4-6b396b409b2c.png)
![Screenshot (136)](https://user-images.githubusercontent.com/24527489/189513017-4545148a-4388-4be8-81a0-bcf91e03d8ea.png)

**Comment by Chancho91** [comment]
Does no one have an answer?! It been over a week!

**Comment by TheBv** [comment]
Minecraft caps the max health at 1024. You can increase it by using a mod like `AttributeFix`
