### ISSUE TITLE
Stage 5 Ice Dragon Crash [2.1.11-1.16.5]

### ISSUE THREAD

**Issue by darthvader45** [Alex-the-666/Ice_and_Fire#4652]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Whenever I go to a stage 5 ice dragon den, it crashes.

**To Reproduce**
1. Start a world.
2. Mine to a stage 5 dragon den.
3. See error

**Expected behavior**
I expect to be able to fight stage 5 dragons as normal.

**Screenshots**

**Additional context**
Add any other context about the problem [here](https://github.com/AlexModGuy/Ice_and_Fire/issues/4569#issue-1301082517).
Crash log: https://paste.ee/p/sEzMT
For clarity, I do not have the bigbrain mod or any other known AI/pathfinding-changing mods.

**Comment by TheBv** [comment]
Should be addressed with 57a72de

**Comment by darthvader45** [comment]
Thanks, updated and seems all is well, got two ice dragon eggs, a lightning dragon and now a fire dragon.  So awesome.
