### ISSUE TITLE
Wild fire and thunder dragons only spawn as babies 

### ISSUE THREAD

**Issue by Xetzly** [Alex-the-666/Ice_and_Fire#4655]
the newly generated dragons spawn as baby dragons with their normal tier power.
Upon killing them they will dissapear 

Every fire or thunder dragon i come across is a baby and i cant get any loot from them they only evaporate and drop XP

**Comment by EVaganoff** [comment]
Level 4-5 dragons spawn underground.

**Comment by s10w10rr1s** [comment]
having this same issue

**Comment by s10w10rr1s** [comment]
> Level 4-5 dragons spawn underground.

and water is wet. any other great advice for us?

**Comment by TheBv** [comment]
Refer to #4699
