### ISSUE TITLE
FoodUtils crash on 2.1.11-1.16.5-SNAPSHOT+build.2022-09-19

### ISSUE THREAD

**Issue by droidypanda** [Alex-the-666/Ice_and_Fire#4659]
FoodUtils crash was fixed 2.1.7 but is back again on latest snapshot 2022-09-19

**Describe the bug**
Crashes when a dragon tries to eat something? Not sure

**To Reproduce**
1. Walk around the world
2. "render" a dragon (no need to see it, it just has to spawn)
3. Crash

**Expected behavior**
This should have already been fixed, right?

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/114325705/192128795-e83863d2-d970-4b67-ba28-26237ae0dfc1.jpg)

**Additional context**

**Comment by TheBv** [comment]
Could you possibly try out the newest snapshot that just got released and tell me if this issue persists?
