### ISSUE TITLE
Fire Dragon Eggs burn and dissapear after beeing placed in fire

### ISSUE THREAD

**Issue by Kocytos** [Alex-the-666/Ice_and_Fire#466]
We tested it in version 1.12.2 with llibrary-1.7.9-1.12.2 and all 12 eggs burned and dissapeared.  we only had iceandfire-1.3.1-1.12.2 activated.

**Comment by AllenSeitz** [comment]
Try standing within 5 tiles of the egg at the moment it hatches. The game determines ownership of the hatchling by checking for players within a mere 5 block radius. If no players are present to witness the hatching then no baby dragon is spawned. (Thanks game.) This also means your friends can accidentally or on purpose steal your dragons.

**Comment by AlexModGuy** [comment]
^
