### ISSUE TITLE
Crash with Stage 5 Fire Dragon [1.16.5-2.1.11]

### ISSUE THREAD

**Issue by darthvader45** [Alex-the-666/Ice_and_Fire#4663]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Woke a stage 5 Fire Dragon and went to fight it.  It did a fire breath attack and I crashed with this error.  java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/api/event/DragonFireDamageWorldEvent

**To Reproduce**
1. Go to a fire dragon lair underground.
2. Wake up dragon by approaching.  It should immediately breathe fire.
3. See error.

**Expected behavior**
I expected to be able to fight the dragon to the death and not see this crash.

**Screenshots**

**Additional context**
[Crash Log](https://paste.ee/p/Y2ulY)

**Comment by TheBv** [comment]
Try out the latest snapshot and let me know if that fixes it https://github.com/AlexModGuy/Ice_and_Fire/releases/tag/latest-snapshot
