### ISSUE TITLE
Game crash when near a fire dragon [ICE AND FIRE VERSION-2.1.11-1.16.5]

### ISSUE THREAD

**Issue by FrostbiteX99** [Alex-the-666/Ice_and_Fire#4664]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
The bug is fire dragons cause crashing when you're nearby. logs have been attached below.

**To Reproduce**
1. install medival minecraft v57 of mc 1.16.5
2. create a new world and enter
3. (start point is a village). go near a fire dragon. 

**Expected behavior**
  Game crashes and error log is generated. 

**Screenshots**

**Additional context**
game crashes and a error report is generated
[2022-10-02-3.log](https://github.com/AlexModGuy/Ice_and_Fire/files/9692323/2022-10-02-3.log)
[crash-2022-10-02_16.10.00-server.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/9692324/crash-2022-10-02_16.10.00-server.txt)
[latest.log](https://github.com/AlexModGuy/Ice_and_Fire/files/9692326/latest.log)

**Comment by TheWitherlord** [comment]
yeah this is happening for me too

same exact error

**Comment by TheBv** [comment]
Can you by any chance try out the latest snapshot and see if it's fixed? https://github.com/AlexModGuy/Ice_and_Fire/releases/tag/latest-snapshot

**Comment by TheWitherlord** [comment]
> Can you by any chance try out the latest snapshot and see if it's fixed? https://github.com/AlexModGuy/Ice_and_Fire/releases/tag/latest-snapshot

For sure, I will give it a test tomorrow

**Comment by TheWitherlord** [comment]
seems like I can't replicate the error, so it must be rare.

**Comment by TheWitherlord** [comment]
> seems like I can't replicate the error, so it must be rare.

This did fix it! The server I was running was soft locked I removed the version with the bug and it was fixed.
