### ISSUE TITLE
Ignores config settings made for Twilight Forest Dimension mod [2.1.11-1.16.5]

### ISSUE THREAD

**Issue by YaBoiMattyK** [Alex-the-666/Ice_and_Fire#4667]
**Describe the bug**
Properly editing dimension whitelist or blacklist for Twilight Forest dimension mod does not set structure/mob spawns to Twilight Forest Dimension. Structures continue to spawn in minecraft:overworld

**To Reproduce**
1. Open iceandfire-common.toml
2. Edit whitelist to only mention "twilightforest:twilightforest", OR blacklist to include all dimensions EXCEPT "twilightforest:twilightforest"
3. Load Minecraft, and generate a new world
4. Browse around minecraft:overworld or twilightforest:twilightforest and look for dragon roosts, mausoleums, and other IAF structures (preferrably with a structure compass or other tool)
5. No IAF structures are in twilightforest:twilightforest. Minecraft:overworld still gets structure spawns.

**Expected behavior**
IAF structures should be removed from minecraft:overworld, and should be introduced to twilightforest:twilightforest, instead.

**Screenshots**

**Additional context**
1. Even when using blacklist settings, structures still spawn in minecraft:overworld, despite being a blacklisted dimension.

**Comment by TheDouGio** [comment]
So apparently I learned you not only have to specify the dimension but you also  have to specify the biomes they spawn in, this other github discussion should help you.
https://github.com/AlexModGuy/Ice_and_Fire/wiki/How-to-specify-the-regions-structures-and-mobs-can-be-spawned
