### ISSUE TITLE
Nowhere to post suggestions :( 

### ISSUE THREAD

**Issue by Breadstickpotato** [Alex-the-666/Ice_and_Fire#4668]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

 "But where do I put my suggestions?"

 The comments section on curseforge is in chaos, and on github it's 
      bug reports only.

P.s. I&F ender dragon for 50 million downloads.
That's how the lightning dragon got added from the
same April fools announcement (at 1 million downloads).

**Comment by TheBv** [comment]
There is a github for suggestions: https://github.com/AlexModGuy/Ice-and-Fire-Suggestions/issues . Although it's not necessarily actively maintained. It most likely will be looked at again once we start working more actively on the mod,
