### ISSUE TITLE
fixed in 2.1.9

### ISSUE THREAD

**Issue by kj117br** [Alex-the-666/Ice_and_Fire#4670]
fixed in 2.1.9

_Originally posted by @AlexModGuy in https://github.com/AlexModGuy/Ice_and_Fire/issues/4085#issuecomment-907434042_

**Comment by kj117br** [comment]
i'm kinda having the same problem in 2.1.11

**Comment by TheBv** [comment]
Please provide a crash report. It is impossible for the exact same issue to still persist since the associated code was removed.
