### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by epsichron** [Alex-the-666/Ice_and_Fire#4675]
[crash-2022-11-04_05.00.43-server.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/9935300/crash-2022-11-04_05.00.43-server.txt)

Currently playing on Roguelike Adventures and Dungeons 2 v(0.6a)
I used to be able to hunt and slay dragons without any issue, but as of recently, everytime I even hit a dragon, the whole server crashes. This... is obviously an issue. I brought it up with the RaD2 server and the config provided to try and fix this issue did not work.

 (Link to RaD2: https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons-2)

**Comment by TheBv** [comment]
Try using the latest snapshot build and let me know if that fixes it. https://github.com/AlexModGuy/Ice_and_Fire/releases/tag/latest-snapshot

**Comment by epsichron** [comment]
> Try using the latest snapshot build and let me know if that fixes it. https://github.com/AlexModGuy/Ice_and_Fire/releases/tag/latest-snapshot

Upon posting this, I decided to reinstall the version used in the RaD2 modpack as a quick fix and it seems like it has worked well. I'm not sure if any compatibility issues would arise upon updating to the newest version, but if a crash happens again, I'll be sure to update and let you know.
Thank you!
