### ISSUE TITLE
Dread lich spawns inside the mausoleum unable to get key [ICE AND FIRE VERSION 2.1.9-1.16.5]

### ISSUE THREAD

**Issue by LordGoldenwolf** [Alex-the-666/Ice_and_Fire#4678]
I've been playing with my modded server and I found a Mausoleum. I read the Bestiary a lot of time which says I have to kill a Dread lich to maybe get the Gravemaster's key. The only problem is, the Dread lich spawns inside the mausoleum and I am unable to kill it and enter the Mausoleum.

**Comment by TheBv** [comment]
They don't exclusively spawn in mausoleums. They just spawn very rarely in general.
