### ISSUE TITLE
Crash Upon Start Up [Version 2.1.9-1.16.5.jar]

### ISSUE THREAD

**Issue by Vespidazed** [Alex-the-666/Ice_and_Fire#4679]
**Describe the bug**
Came back to a forge mod pack after some time, updated everything and got crashes. Decided to make a separate pack only with Ice and Fire and Citadel, both the latest versions. 

**To Reproduce**
1. Go to Cursed Forge App
2. Create a new mod pack with Forge version 35.1.4, Ice and Fire 2.1.9, and Citadel 1.8.1 for Minecraft 1.16.4
3. After all install, select "Play" on modpack file. 
4. Proceed to login to microsoft/mojang account
5. Select Altered file (Usually the game mentions it's altered and might not run correctly) and hit Play
6. It loads game and before it hits the title screen.
7. See error

**Expected behavior**
I expected another mod to be the issue and to remove it from the pack. After removing all mods I figured I would be able to load the game without the starting screen crash. To be safe I made an entirely new pack to start from scratch unless there was some leftover code. 

**Screenshots**
![Screenshot (6640)](https://user-images.githubusercontent.com/117594488/200188077-0318e6d9-d844-499b-acb2-d88879c01929.png)
![Screenshot (6641)](https://user-images.githubusercontent.com/117594488/200188110-7ab942fd-49c2-48ff-83e0-c83992fbf0a2.png)
![Screenshot (6642)](https://user-images.githubusercontent.com/117594488/200188121-0c89a3f2-69eb-4235-8b8f-e13721d4e609.png)
![Screenshot (6643)](https://user-images.githubusercontent.com/117594488/200188123-eb676720-7174-4acf-811b-e544aacf543b.png)

**Additional context**
I'll admit I'm not the best at debugging or reading code, but it looks like it's looking for something from Citadel that either isn't there or is but isn't being read correctly.

**Comment by TheBv** [comment]
Upgrade your forge version

**Comment by Vespidazed** [comment]
To which version?

**Comment by Vespidazed** [comment]
I used the most recent version of Forge and still have this issue.
