### ISSUE TITLE
Crash in Twillight Forest

### ISSUE THREAD

**Issue by tyra314** [Alex-the-666/Ice_and_Fire#468]
I got a crash after walking around in the twilight forest for a while:
https://gist.github.com/tyra314/c8030d7ebea344920d4254bc3643d50c

Versions:
- Minecraft: 1.12.2
- Forge: 14.23.2.2611  
- Ice & Fire: iceandfire-1.3.1-1.12.2.jar 
- Twillight Forest: twilightforest-1.12.2-3.6.324-universal.jar

**Comment by jimnordb** [comment]
Try running without primitive mobs

**Comment by KAfable** [comment]
Hey just experienced a crash similar to this, any idea what the conflict with primitive mobs might be causing then?

edit: Actually I think this line might be an issue with NetherEx
`at nex.handler.EventHandler.onLivingUpdate(EventHandler.java:417)`

**Comment by AlexModGuy** [comment]
dupe issue

**Comment by tyra314** [comment]
Indeed, looks similar to #460
