### ISSUE TITLE
Issue with tide trident texture

### ISSUE THREAD

**Issue by HunterMNZ** [Alex-the-666/Ice_and_Fire#4680]
The tide trident appears in my hand as if i have thrown it and not in its original form showcased in the item picture at first i thought another mod was interfering with it but i tried it on its own and the problem persisted.
![2022-11-08_16 48 14](https://user-images.githubusercontent.com/117749368/200596936-edc55178-79c7-4f1e-844b-0f81e875bf7c.png)

**Comment by TheBv** [comment]
This is intended behavior. Same thing applies to the default Trident in Minecraft.
