### ISSUE TITLE
1.17-port Issue collection

### ISSUE THREAD

**Issue by TheBv** [Alex-the-666/Ice_and_Fire#4682]
I want to keep most issues in regards to the 1.17 port separate from many of the other ones hence this issue.
If you find any bugs/issues post them as a comment here and I'll add them to the list!

- [x]  Advancements don't work properly
- [x]  Game crashes when going through the bestiary
- [x]  The bestiary doesn't display items at the right positions
- [x] Ghosts don't turn red when hit/ don't have a damage indicator
- [x] Dread spawners don't work
- [x] Dragonsteel tools don't give their elemental effect
- [x] Dragons not lighting dragon forge

**Comment by MioSignore** [comment]
Dragonsteel tools don't give their elemental effect.

**Comment by morguldir** [comment]
- [x] Floating Gorgon Temples
  <details>
  <summary>Location</summary>
  <br>
   /tp @s -1227.60 86.23 -4321.47

   seed: -542563839240225331
  </details>
- [x] Sea Serpent models seem to be one block above the hitbox
- [x] Features sometimes spawn in the wrong biomes, e.g. pixie villages in oceans

**Comment by TheBv** [comment]
> Floating Gorgon Temples

Looked into the floating gorgon temples.
I don't think there's anything that can be done about that sadly.
The world height map for the desert (in this case) is just wrong (or maybe I'm misunderstanding what kind of information it's supposed to relay) so the structures get placed way to high. I'm pretty sure this also happens in Vanilla with Mansions
At the time of generation there sadly doesn't seem to be a way to access the actual blocks of the world so that's not a way to fix things sadly.
I'll try convert things to how modern structures generate. Maybe that can fix things.

**Comment by morguldir** [comment]
Oh right I actually fixed this, forgot to mention it though sorry: https://github.com/AlexModGuy/Ice_and_Fire/commit/92c675d86fedac532c33446f51006136711e6d9f

pos is a chunkpos, so if you add 7 you still have a chunk position, but getFirstOccupiedHeight expects coordinates

The old code did pos.x << 4 + 7, which is pos.x * 16 + 7. getBlockX does that for us.
