### ISSUE TITLE
Request update to 1.19.2Forge

### ISSUE THREAD

**Issue by ZHANGQQINYYUAN** [Alex-the-666/Ice_and_Fire#4683]
Request update to 1.19.2Forge

**Comment by melnik632** [comment]
yes, I think it is worth updating the mod to 1.19, I usually understand that the author of the mod does not have much time for his personal life and maintaining all his mods . but the author of the mod, please give at least some information 🙏

**Comment by PlummetStudios** [comment]
Request denied.

**Comment by mmiller9196** [comment]
gigachad response
