### ISSUE TITLE
Server Crashes when a single player is riding a dragon 2.1.11-1.16.5

### ISSUE THREAD

**Issue by codestripper** [Alex-the-666/Ice_and_Fire#4685]
**Describe the bug**

**To Reproduce**
1. Be a player on my server named TONREK
2. Try to ride a dragon (lightning or ice so far)
3. Server crashes

**Expected behavior**
I expect the server not to crash, as it does not crash when others are riding their dragons.
[crash-2022-11-26_04.17.26-server.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/10095680/crash-2022-11-26_04.17.26-server.txt)

**Additional context**
Crash report from server is attached. If any further information is needed, please let me know. Willing to provide whatever is needed.

I also attached a copy of the modified HR new beginnings modpack we are using which includes a modlist.

[Avalan New Beginnings-2.0.1.zip](https://github.com/AlexModGuy/Ice_and_Fire/files/10095681/Avalan.New.Beginnings-2.0.1.zip)

**Comment by TheBv** [comment]
The log sadly doesn't contain much info. 
Please try to use the latest 2.1.12 alpha and see if the issue still persists.
Closing for now; feel free to reopen it once you've confirmed it's still an issue.
