### ISSUE TITLE
Game crashes on startup due to error in load registeries phase

### ISSUE THREAD

**Issue by Asteralium** [Alex-the-666/Ice_and_Fire#4686]
When opening the game and loading my mods, this error occurs and the game creates a crash log. This is on the latest version.

> Ice and Fire (iceandfire) encountered an error during the the load_registries event phase
java.lang.NoClassDefFoundError: net/minecraftforge/common/ForgeSpawnEggItem

I've got... no idea what that means. But here is the crash log and latest.log files.

[latest.log](https://github.com/AlexModGuy/Ice_and_Fire/files/10102179/latest.log)

[crash-2022-11-28_03.51.05-fml.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/10102182/crash-2022-11-28_03.51.05-fml.txt)

**Comment by TheBv** [comment]
Update forge to at least version 36.2.17
