### ISSUE TITLE
Crash (1.16.5)

### ISSUE THREAD

**Issue by CalTheArsonist** [Alex-the-666/Ice_and_Fire#4688]
World was running completely fine for a while, then suddenly started crashing
crash log:
https://pastebin.com/ihm1PUPn

**Comment by TheBv** [comment]
Could you try the latest snapshot and see if the issue has been resolved?
https://github.com/AlexModGuy/Ice_and_Fire/releases/tag/latest-snapshot

**Comment by CalTheArsonist** [comment]
That seems to have fixed it, thanks!
