### ISSUE TITLE
Ticking Entity Error: Cockatrice [Version iceandfire-2.1.11-1.16.5]

### ISSUE THREAD

**Issue by CephalonAxii** [Alex-the-666/Ice_and_Fire#4689]
**Describe the bug**
I've been testing it and the Ticking Entity crash seems to happen when two or more Cockatrie are around being aggro'd.  Whenever I first look at them, then turn away, then look again sometimes a different Cockatrice, my game would freeze then crash. 

**To Reproduce**
Frankly not sure how to reproduce. There is devifinitly a mod causing a confliction I just don't know which one or how to start looking. But I know the crash report keeps saying Cockatrice across any new worlds I make.  The majority of my mods come from Fantasy Relm and Medieval Minecraft, both modpacks made by Sharkie that I took, put in the forge mod folder I made, and replaced magnesium and such with Optifine and Optiforge. But I know Optifine by itself isn't the issue because I had it in Medieval Minecraft when I first downloaded it a year or so and no issue.

**Comment by TheBv** [comment]
Seems to be the same issue as #4626 which should be fixed in the latest snapshot build
