### ISSUE TITLE
[1.12.2] Crash

### ISSUE THREAD

**Issue by KAfable** [Alex-the-666/Ice_and_Fire#469]
Hi one of the testers for my modpack seems to be getting crashes with with Ice and Fire on a multiplayer server. https://pastebin.com/WnfWLdKV

Any ideas on the cause?

**Comment by KAfable** [comment]
Just got the crash myself in my own testing wortld: https://hastebin.com/xibowatawo.sql

Was just randomly exploring and crashed clientside.

**Comment by AlexModGuy** [comment]
dupe issue
