### ISSUE TITLE
1.18.2 Port Issues

### ISSUE THREAD

**Issue by morguldir** [Alex-the-666/Ice_and_Fire#4697]
Any issues/fixes from the 1.17 port will also apply
- [ ] #4682 
## Resolved 
- [x] Gorgon temples contain water (again)
- [x] Dragons hover backwards
- [x] Pixie Village and Cyclops caves sometimes spawn too often
- [x] Aerial gravevyard (seed: 5068750501018189537, x:9952, y:94, z:-988)
- [x] Game crashes when selecting a dread torch wall block in creative mode
- [x] Game crash on mausoleums
- [x] https://github.com/AlexModGuy/Ice_and_Fire/issues/4707
- [x] https://github.com/AlexModGuy/Ice_and_Fire/issues/4700
- [x] Dangerous structure config options don't work

## Unresolved
- [x] Log spam about `setBlock in a far chunk` for Dragon Caves (usually after teleporting)
- [ ] Consider changing the range for dragon spawning slightly, 25-30 doesn't fit as well with the new caves
- [x] Dragon riding speed is off
- [ ] Dread spawners seem to have incorrect weight key

**Comment by TheBv** [comment]
I personally don't plan on fixing dragon cave generation in any of the in between versions since there are some plans to change them. 
I removed the mixin that fixed gorgon temples getting flooded because I thought minecraft has fixed the issue and I didn't see it occurring locally anymore. So either they reintroduced it in 1.18 or I just missed it. I'll investigate!

**Comment by astrallyzed** [comment]
When dragons die mid air they float, This applies to all the dragons
And when they spawn in they just launch themselves upwards randomly, Instead of slowly moving upwards
![This applies to every stage](https://user-images.githubusercontent.com/88703455/211325856-421a769e-cc0d-4f74-a478-a0c221328a1d.png)

**Comment by Cixon** [comment]
### The game freezes when attempting to /locate mausoleum .

**Minecraft Version:** 1.18.2
**Snapshot:** build.2023-01-11
**API:** Citadel-1.11.3

**Log** (line 501):
[latest.log](https://github.com/AlexModGuy/Ice_and_Fire/files/10401476/latest.log)

**Comment by Cixon** [comment]
### When teleporting to a found /locate gorgon_temple  . the client freezes .

**Minecraft Version:** 1.18.2
**Snapshot:** build.2023-01-11
**API:** Citadel-1.11.3

**Log** (line 125) - kinda irrelevant info tho.. :
[latest.log](https://github.com/AlexModGuy/Ice_and_Fire/files/10401542/latest.log)

**Comment by Cixon** [comment]
### Severe Server log-spam for Dragon Cave generation.

**Minecraft Version:** 1.18.2
**Snapshot:** build.2023-01-11
**API:** Citadel-1.11.3

**Log** (line 195):
[latest.log](https://github.com/AlexModGuy/Ice_and_Fire/files/10401723/latest.log)

![Screenshot (241)](https://user-images.githubusercontent.com/69068153/212072001-128e6dc9-489d-4ddd-b83b-f7c89d51a7e2.png)

**Comment by TheBv** [comment]
Both gorgon temples as well as mausoleums can now generate in the middle of the ocean.

**Comment by Atlantispy** [comment]
I've found some dragons struggling to fly, it was used in a kitchen sink modpack so could well be mod conflicts but they would fly over the edge of a cliff and they'd just plummet straight under the water at the bottom of the cliff.

Latest forge and snapshot

**Comment by MioSignore** [comment]
If no key is pressed, ice dragons swim backwards.

The power of the dragon balls is diminished compared to the 1.16 version.

Ice dragons and dread mobs aren't immune to powder snow damage.

**Comment by MioSignore** [comment]
Also the safety measure of dragons landing first when dismounting mid-air with shift is missing.
