### ISSUE TITLE
Hippogryphs won't eat rabbit foot [1.16.5]

### ISSUE THREAD

**Issue by autumnly24** [Alex-the-666/Ice_and_Fire#4701]
**The Issue**
I already have two hippogryphs I've tamed, and now I'm trying to tame a third (who I hatched from an egg from my two other hippogryphs)
It refuses to eat rabbit's foot no matter it's age, and therefore I can't tame it.

I've tried it with two other hippogryphs of various ages, same problem.

**To Reproduce**
1. Obtain Hippogryph
2. Try to feed it rabbit's foot
3. Watch as literally nothing happens

**Expected behavior**
The Hippogryph should eat the rabbit's foot and eventually be tamed

**Comment by PaulerLeOne** [comment]
You don't righ-click it, you drop the item into them.

**Comment by autumnly24** [comment]
I know this, I was dropping it.

A small update though! I was able to finally get a Hippogryph who ate them, so I'm thinking that it's just some Hippogryphs that will not eat rabbits foot, or some just have the AI goals ordered in a messy way where they have more priorities over eating it, idk
