### ISSUE TITLE
Server crash [Minecraft 1.16.5, I&F 2.1.10]

### ISSUE THREAD

**Issue by NoOneWasHere** [Alex-the-666/Ice_and_Fire#4703]
**Describe the bug**
While fighting with a cyclops, the server (not my game) stopped with a crash. Everytime I reboot the server, it starts fine and all players can join in, until I join too. At that point, the server crashes the same way.

**To reproduce**
I'm not sure what happened: I was fighting a Cyclops. I remember seeing a deathworm attacking the beast, but nothing else was out of the ordinary.

**Additional context**
[Crash log](https://mclo.gs/YxDEGTd).

**Comment by TheBv** [comment]
This was fixed in the 2.1.11 version
