### ISSUE TITLE
Crash on map opening

### ISSUE THREAD

**Issue by SupraFanatic** [Alex-the-666/Ice_and_Fire#4705]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.
SORRY FOR BAD ENGLISH
**Describe the bug**
on my modpack i install Ice And Fire, opens normaly but when i open my map or try creating a new map the game crash

Mods i use: 
Wildfire Female Gender mod
Allthemodium (i need IAF for 1 recipe)
Architectury
Autoreglib
Better Village
Biomes O'Plenty
carry on
CFM
Citadel
CodeChickenLib
cofh_core
Craft Tweaker
curios-forge
Easy_Villagers
Ftb-chunks
Ftb-library
Ftb-ranks
Ftb-teams
Ftb-ultimine
Geckolib
Hwyla
Ice And Fire 
Immersive Engineering
Industrial-foregoing
Ironchest
Ironfurnace
Jei
Libraryferret
Mantle
Macaws-doors
Macaws-paintings
Macaws-trapdoors
Optifine
Patchouli
Quark
Spartan Weaponry
Tinkers construct
Theoneprobe
Thermal_dyenamics
Thermal_expansion
Thermal_foundation
Titanium
Tl_skin_cape
TravelersBackpack
Upgradedcore
Upgradednetherite
Wailaharvestability
Waystone

**To Reproduce**
Steps to reproduce the behavior: Sorry i am new here and i dont know what is this
3. See error

**Expected behavior**
Open the map with the IOF normally to make my itens 

**Screenshots**
heres my mod folder
![Screenshot_1](https://user-images.githubusercontent.com/122132673/211122712-d112c04e-7d04-43eb-b648-daddf4784bee.png)

**Additional context**
heres the crash report
[crash-2023-01-06_08.53.32-client.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/10365191/crash-2023-01-06_08.53.32-client.txt)

**Comment by SupraFanatic** [comment]
what i do, i dont get it

**Comment by TheBv** [comment]
Try out this build of the mod https://github.com/AlexModGuy/Ice_and_Fire/releases/tag/2.1.12-alpha-1.0
That should fix it 🤞
