### ISSUE TITLE
[Suggestion] Gorgon Petrify Blacklist

### ISSUE THREAD

**Issue by herobrine150400** [Alex-the-666/Ice_and_Fire#471]
Well, I just think it would be interesting if in the config file for this mod there was a blacklist for which mobs should Gorgons be able to turn into stone, as in, they won't be able to petrify anything in that list.

It could come with the Gorgons in the list by default, because Gorgons being able to petrify Gorgons doesn't sound very right.

**Comment by AlexModGuy** [comment]
https://github.com/Alex-the-666/Ice-and-Fire-Suggestions/issues
