### ISSUE TITLE
Dragon Armor not working (1.1.11-1.16.5)

### ISSUE THREAD

**Issue by MollyLovesReptiles** [Alex-the-666/Ice_and_Fire#4710]
![2023-01-13_09 45 45](https://user-images.githubusercontent.com/70864595/212564782-cac068b5-a67a-4484-94b9-d7d1906bf211.png)

**Comment by TheBv** [comment]
They do work. It just wasn't updating the entity data so other mods couldn't read the armor stats correctly. I'll update the code so the changes can be detected.
