### ISSUE TITLE
Cyclops in caves not spawning

### ISSUE THREAD

**Issue by Telev1s1on** [Alex-the-666/Ice_and_Fire#4713]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Some Cyclops not spawning in their respective caves even after just generating the chunk(s)

**To Reproduce**
1. Make a Minecraft world 
2. Try and locate cyclops' cave through generation
3. Then see if the cyclops spawn or not

**Expected behavior**
I was playing on a multiplayer server with my friends and when I generated a few chunks I had seen 2 cyclops caves on my map close together, when I went toward them I saw no cyclops in either of them

**Screenshots**
N/A
**Additional context**
- Multiplayer Server with around 70 mods
- the cyclops couldn't have disappeared or walked away since I had just loaded the chunk and checked for them and I did not see their icons on my map as well

**Comment by Telev1s1on** [comment]
The version was 1.18.2 snapshot 1.11.23

**Comment by TheBv** [comment]
Have you tried the most recent snapshot?
I couldn't reproduce this locally with the most up-to-date version.
