### ISSUE TITLE
Server Crash w/ Cyclops Pathfinding [1.18.2 Snapshot 1/11/23]

### ISSUE THREAD

**Issue by ComeMyChild** [Alex-the-666/Ice_and_Fire#4714]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
A crash report is generated regarding Cyclops pathfinding, where it soft locks the server and ultimately crashes it with the message "watchdog took 60 seconds for a single tick"
[crash-2023-01-07_20.43.05-server.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/10430198/crash-2023-01-07_20.43.05-server.txt)

**To Reproduce**
1. Install Ice and Fire onto a server
2. Find a wandering cyclops (or enter the general vicinity of said cyclops)
3. Watch as server soft locks for 60 seconds before crashing

**Expected behavior**
It is expected that cyclops should not crash the server with its pathfinding AI.

**Screenshots**

**Additional context**
The crash report is attached, just in case it isn't an issue with Cyclops pathfinding, though I do think it is

**Comment by TheBv** [comment]
Are you sure you're using the latest snapshot?
In the crash it mentions `build.2022-12-30` the cyclops pathfinding issues should've been resolved with 8c14c92
