### ISSUE TITLE
Crash on attempted WorldGen [ICE AND FIRE VERSION 2.1.11]

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#4716]
The bug is that the game crashes after attempting to create a world with I&F.

Steps taken: 
1. Launched Minecraft successfully
2. Click Singleplayer
3. Go to create new world 
4. Create new world

**Expected behavior**
The successful outcome was that the game wouldn't crash and I'd load in.

Sorry, it's all text here, as I have added my crash logs

[crashlog HR with I & F.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/10451061/crashlog.HR.with.I.F.txt)

**Comment by TheBv** [comment]
Issue with allthemodium. They don't seem to want to update their mod though so you're probably out of luck.
