### ISSUE TITLE
Dragons teleport away when you put them off your shoulder [2.1.11-1.16.5]

### ISSUE THREAD

**Issue by quinnfrost** [Alex-the-666/Ice_and_Fire#4718]
**Describe the bug**
Stage 1 dragons teleport back where they were when you put them off your shoulder

**To Reproduce**
1. Create a new save
2. Use ```/summon iceandfire:ice_dragon ~ ~ ~ {AgeTicks:0}``` to summon a stage 1 dragon, then use creative dragon meal to tame her
3. Wait untill she started to walk randomly, while she's walking right click on her
4. Move away from the starting point while she's on your shoulder, then press shift and you can see her teleport back to the starting point

**Expected behavior**
The dragon should land at the new location, because we take her there.

**Additional context**
I did a little more digging and it turns out that even on your shoulder the dragons' ```DragonAIWander``` goal still can be triggered, which set a new destination using ```tryMoveToXYZ``` and the dragon does response to that destination. You can find a little bit more in the process by F3+B to show the hitbox of the dragon. When ```tryMoveToXYZ``` is called the surrounded hitbox (```EntityDragonPart``` I guess ) started to separate from the main body and reach for the destination. As soon as the shift key is pressed the dragon's main body teleports to other dragon parts.
Actually the ran away dragon parts seems to be the actual location of the dragon. They can take damage, attack, and fed. If you right click the parts they will teleport and stay on your shoulder for a while, untill the ```DragonAIWander``` triggered again and the parts ran away again.

**Screenshots**
![2023-01-22_17 30 50](https://user-images.githubusercontent.com/89291944/213909355-318ac866-7040-4a64-b42d-ed8cd0d03664.png)

**Comment by NotUkrainianCat** [comment]
I have the same problem, does it fix after stage 1?

**Comment by quinnfrost** [comment]
well you can't put dragons after stage 1 on your shoulder so I guess the problem won't exist
I guess the actual problem is the `DragonAIWander` does really has a exit condition for dragons on the shoulder
