### ISSUE TITLE
TOO many CYCLOPS spawning and CRASH when near the black dungeon structure. [snapshot 1.18.2]

### ISSUE THREAD

**Issue by Mattc51** [Alex-the-666/Ice_and_Fire#4721]
I’m here to report a world breaking crash when walking near the black dungeon structure, it crashes and doesn’t allow me to enter the world again. Another issue in the 1.18.2 version is that there are too many cyclops dens spawning and it takes up all the dragon spawns and basically everything else. There’s dens spawning in sets of 3 and 2 all next to each other. That’s all, thank you.

**Comment by TheBv** [comment]
Should be resolved by f455772 as well as some other commits

**Comment by Mattc51** [comment]
Hurray!!! Thank you so much!
