### ISSUE TITLE
Loot table edits don't show up in JEI [2.1.11-1.16.5]

### ISSUE THREAD

**Issue by PaloPil** [Alex-the-666/Ice_and_Fire#4722]
I edited the Stymphalian Bird's loot table in my modpack to make it drop another copper ingot from another mod.
The loot table edit worked but when I looked at the bird's JEI (Just Enough Items) loots, the edit wasn't showing up. It is the only loot table edit than cause me this issue, and other mods worked perfectly.

**Comment by TheBv** [comment]
Which version of the mod are you using?

**Comment by PaloPil** [comment]
I'm using the version 2.1.11 for 1.16.5
