### ISSUE TITLE
Over-abundance of Cyclops spawning in the world in the 1.18.2 Snapshot

### ISSUE THREAD

**Issue by imahellboy** [Alex-the-666/Ice_and_Fire#4723]
First off I would like to thank you for all the hard work you have put into keeping this mod alive and continuously updating it :)
In 1.18.2 in every biome there is 3-4 Cyclops Domes that spawn in and I believe it messes with the Dragons spawning because they are no where to be found now.
Lastly, if you get close to the black dungeon structure in the snow biomes it crashes your game and you won’t be able to load back in at all.

Thank you!

**Comment by Mattc51** [comment]
Indeed
