### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by Kiwicast** [Alex-the-666/Ice_and_Fire#4728]
Installed the Beta Mod for 1.18.2 Ice and Fire

Seems once loaded the server spams about entities already exist.

Have added screenshot to show you 
![Screenshot 2023-01-28 111227](https://user-images.githubusercontent.com/113838580/215215642-e96b24da-e8c5-4cda-a839-daadb6c0c583.jpg)

How would i resolve this

**Comment by TheBv** [comment]
I'm assuming you're using a "non-standard" forge server. This at least hasn't happened to me on the standard server.
I'll look into this but it won't be a priority unless you can confirm it's a vanilla forge server.

**Comment by Kiwicast** [comment]
Yea we using Magma, don't worry too much we will just look into another
Dragon mod if its too much.

Cheers.

**Comment by Minecraftnerdddddddddd** [comment]
Im also having this problem and im using magma can you PLEASE fix this

**Comment by TheBv** [comment]
I've done some digging and this seems to be an issue on magmas end. There's nothing I can do to fix this on our end.
I plan on rewriting the Multipart code at some point but it really isn't part of the plan for the initial 1.18 release.
There's an issue open https://git.magmafoundation.org/magmafoundation/Magma-1-18-x/-/issues/167 so hopefully they fix it at some point.

**Comment by Cixon** [comment]
Issue should have been fixed in latest 1.18.2 magma release.
Commit found here: https://git.magmafoundation.org/magmafoundation/Magma-1-18-x/-/commit/110d0d8e

Please test if this issue still exists on Magma ‘ 110d0d8e ‘ .
Thank you Bv for adding additional context for this bug!
