### ISSUE TITLE
lightning dragon crash while world loading[1.16.5]

### ISSUE THREAD

**Issue by nageih** [Alex-the-666/Ice_and_Fire#4729]
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

lightning dragon crash while world loading

1. i use java11 to run the game
2. and then it crash

I hope to enter the game normally

[latest.log](https://github.com/AlexModGuy/Ice_and_Fire/files/10545232/latest.log)
minecraft 1.16.5
forge-1.16.5-36.2.39
iceandfire-2.1.11-1.16.5

**Comment by TheBv** [comment]
Try out the latest snapshot for 1.16.5 that should fix the issue: https://github.com/AlexModGuy/Ice_and_Fire/releases/tag/latest-snapshot

**Comment by nageih** [comment]
thanks,it's useful
