### ISSUE TITLE
bug when taking dragon off the horn and being dismounted when logging off while flying also flaute dont work

### ISSUE THREAD

**Issue by kuroyure** [Alex-the-666/Ice_and_Fire#473]
when i put a dragon on a hron and try to take it off it just disapear also when i try to use the flaute on my flying dragon it does not work also when i log off the world in mid fligth i fall from my dragon

**Comment by EPIICTHUNDERCAT** [comment]
put what version of MC in your title please ex: [1.12.2] IN FRONT of your title

**Comment by AlexModGuy** [comment]
#1447
