### ISSUE TITLE
Lightning dragon roosts don't spawn at all [2.1.12-1-18-2]

### ISSUE THREAD

**Issue by PaulerLeOne** [Alex-the-666/Ice_and_Fire#4735]
I've playing in a world for a while, did plenty of exploration and eventhough i've seen several underground lightning dragon caves; lighting dragon roosts, the ones that appear on the surface, don't seem to spawn at all. Fire and ice dragon roost do spawn.

**To Reproduce**
1. Travel through savanna or jungle biomes for a while.
2. No dragon roosts appear.

**Expected behavior**
Lightning dragon roost should appear on the surface of savanna and jungle biomes.

**Screenshots**
¯\_(ツ)_/¯

**Comment by TheBv** [comment]
Fixed with [fe2405e](https://github.com/AlexModGuy/Ice_and_Fire/commit/fe2405ede0428a40cd0319613259a9d9a195c423)
