### ISSUE TITLE
there is a crash when you approach the mausoleum

### ISSUE THREAD

**Issue by Haeshka2** [Alex-the-666/Ice_and_Fire#4738]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
-there is a crash when you approach the mausoleum

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Additional context**
I'm not sure if it's because of the mausoleum or because of the mob that spawns inside. But as soon as I get close to him and the mobs start spawning, the game freezes and crashes.

**Comment by Mikaelwilker** [comment]
i have the same problem, log says the cause is when rendering entity, the dread knight
...

[crash-2023-02-03_19.28.46-client.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/10676751/crash-2023-02-03_19.28.46-client.txt)

**Comment by TheBv** [comment]
No log file provided as well as no version.
I'd be happy to reopen this once they are.
@Mikaelwilker this is very likely a incompatibility with a different mod. Something that registers banner patterns, most likely incorrectly.
