### ISSUE TITLE
Dragon steel armor material type inconsistency

### ISSUE THREAD

**Issue by quinnfrost** [Alex-the-666/Ice_and_Fire#4739]
First of all thank you guys for making this great mod, been playing it for a year now and its still a lot of fun.

The fire dragon steel material type "dragonsteel fire" is a little bit different
https://github.com/AlexModGuy/Ice_and_Fire/blob/16ccef0b6904ac2bf0eea75d2730e51351b5c8f0/src/main/java/com/github/alexthe666/iceandfire/item/IafItemRegistry.java#L39

while the others are "dragonsteel_ice"
https://github.com/AlexModGuy/Ice_and_Fire/blob/16ccef0b6904ac2bf0eea75d2730e51351b5c8f0/src/main/java/com/github/alexthe666/iceandfire/item/IafItemRegistry.java#L40
https://github.com/AlexModGuy/Ice_and_Fire/blob/16ccef0b6904ac2bf0eea75d2730e51351b5c8f0/src/main/java/com/github/alexthe666/iceandfire/item/IafItemRegistry.java#L41
might cause some trouble when determining armor type

Also, I found this when I'm developing a little addon mod for Iaf and I would like to ask that do I need any kind of permission to post my mod anywhere else? Since I did used some code from Iaf itself.

**Comment by TheBv** [comment]
All the code is under this license https://github.com/AlexModGuy/Ice_and_Fire/blob/1.16.3/LICENSE
Github shows quite nicely what you can and can't do.
I wouldn't go ahead and use any of the assets without permission though (so textures, models, etc)

**Comment by quinnfrost** [comment]
Sure I understand those great assets takes a lot of efforts to create. Thank you for the clarification.
