### ISSUE TITLE
Ice and fire mobs are covered by white light? 

### ISSUE THREAD

**Issue by YeeterBaconEater** [Alex-the-666/Ice_and_Fire#4745]
So for some reasons the ice and fire mobs(dragons pixies, etc) are covered by a white circle almost light. I don’t know why this is happening and there is no trigger, it is always like this. 
![D5EE96A0-F30C-4286-BBBE-7B67C6F7993D](https://user-images.githubusercontent.com/125711171/219824625-7154d44c-01d8-4f12-b9fa-329322279509.jpeg)

**Comment by TheBv** [comment]
Very likely some other rendering/performance optimization mod is causing this.
