### ISSUE TITLE
Game crash after spawn dragon [iceandfire-2.1.11-1.16.5.]

### ISSUE THREAD

**Issue by WaleWiadra** [Alex-the-666/Ice_and_Fire#4746]
After trying to spawn a dragon through an egg, the game immediately crashes

[crash-2023-02-18_20.01.45-server.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/10775066/crash-2023-02-18_20.01.45-server.txt)

**Comment by AlanD2005** [comment]
I have had a similar issue when playing on a singleplayer world. While roaming around the world I found that whenever I get too close to a naturally spawned dragon or spawning one with a spawn egg, it will crash my game with a similar crash report.
[crash-2023-02-18_17.16.44-server.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/10775421/crash-2023-02-18_17.16.44-server.txt)

**Comment by FruitW0rld** [comment]
Same thing is happening to me as well. However, its for the myrmex queen including dragons too.

**Comment by FruitW0rld** [comment]
Here is the crash report:
[crash-2023-02-18_20.52.25-server.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/10775537/crash-2023-02-18_20.52.25-server.txt)

**Comment by maximogta** [comment]
Same issue, even using latest alpha build from github (2.1.12-alpha-1.0)

The same issue happens in Version 2.1.10.

But there is no issue with iceandfire-2.1.9-1.16.5

**Comment by Syrikal** [comment]
This just started happening for me today. It was working yesterday, but now any dragon pathfinding will crash.

**Comment by Syrikal** [comment]
@maximogta @FruitW0rld @AlanD2005 @WaleWiadra 

Just curious, did any of you upgrade from Rubidium 0.2.10 to 0.2.11 recently? I reverted that and the crashes stopped.

**Comment by maximogta** [comment]
> @maximogta @FruitW0rld @AlanD2005 @WaleWiadra
> 
> Just curious, did any of you upgrade from Rubidium 0.2.10 to 0.2.11 recently? I reverted that and the crashes stopped.

Yes, I did, then it needs to be fixed in rubidium mod

**Comment by FruitW0rld** [comment]
Oh yeah I did. That makes a lot of sense now. Thank you.

**Comment by AlanD2005** [comment]
Let me try this.

**Comment by WaleWiadra** [comment]
> 

Yes, I did, i will try downgrade rubidium

**Comment by WaleWiadra** [comment]
> @maximogta @FruitW0rld @AlanD2005 @WaleWiadra
> 
> Just curious, did any of you upgrade from Rubidium 0.2.10 to 0.2.11 recently? I reverted that and the crashes stopped.

Yes, i did i will try downgrade rubidium maybe this will work

**Comment by WaleWiadra** [comment]
Okay guys, Rubidium downgrade to 0.2.10 works and my game stopped crashes, thank you all!!! <3
