### ISSUE TITLE
It keeps crashing

### ISSUE THREAD

**Issue by phoenix3807** [Alex-the-666/Ice_and_Fire#4747]
Everything is updated correctly but every time I try to boot up ice and fire it crashes with the crash report java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/core/ModItems

how can I fix it

**Comment by phoenix3807** [comment]
I am trying to play on 1.12.2 btw

**Comment by TheBv** [comment]
Version 1.12 is no longer actively maintained.
