### ISSUE TITLE
[1.12.2] [1.3.1] Dragon roar is too quiet

### ISSUE THREAD

**Issue by GundunUkan** [Alex-the-666/Ice_and_Fire#475]
The wing flapping and the ice/fire breath are heard from pretty far away, but the dragon's roar, which, in my opinion, should be the loudest, actually can't be heard from more than 50 blocks or so. It has an echo effect to it, but it's kinda hilarious considering how close you have to be to the dragon to actually hear the sound.

**Comment by EPIICTHUNDERCAT** [comment]
put what version of MC in your title please ex: [1.12.2] IN FRONT of your title

**Comment by AlexModGuy** [comment]
fixed
