### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by RedFaun22** [Alex-the-666/Ice_and_Fire#4752]
If you want to ride a tamed dragon or get picked up by a wild dragon in a Server that has the Ice and Fire mod and the More Playermodels mod on the version 1.16.5 in it, the game crashes and you get the error code, 
Error: java.util.NoSuchElementException: null

1. Go to a Server with the Ice and Fire mod and the More Playermodels mod on the version 1.16.5 in it
2. Click on the tamed dragon you want to ride or get picked up by a wild dragon
3. See error: java.util.NoSuchElementException: null

It shouldn't crash, when we want to ride a dragon or if we get picked up with this mods on the version 1.16.5 

We are playing on a multiplayer server on https://ploudos.com/de/ and this server works with forge

[Absturtzbericht.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/10854825/Absturtzbericht.txt)

**Comment by TheBv** [comment]
Please provide a crashlog or the latest log since otherwise it's near impossible to triage this issue

**Comment by TheBv** [comment]
Yeah this is an issue with the more players model mod.
I haven't found a way to fix this /  even found what causes this so this won't get fixed any time soon

**Comment by RedFaun22** [comment]
Oh okay. But thank you
