### ISSUE TITLE
Detected setBlock in a far chunk [iceandfire-2.1.12-1.18.2-SNAPSHOT+build.2023-01-31]

### ISSUE THREAD

**Issue by Reshy** [Alex-the-666/Ice_and_Fire#4754]
**Describe the bug**
World sometimes throws a bunch of errors relating to the generation of new dragon caves, and might be causing world hangs.

**To Reproduce**
1.  Generate the world.
2. Force chunks to load through some means.
3. See error in the logs any time a dragon cave is generated (Happens with both Ice and Fire dragons).

**Expected behavior**
This error shouldn't be occurring, and is likely causing the server to hang.

**Log Exerpt**
https://pastebin.com/dRNNHjPz

**Comment by TheBv** [comment]
Already present in #4697
