### ISSUE TITLE
Bug Crashed World permanently? [RLcraft 2.9.1 Ice and fire version]

### ISSUE THREAD

**Issue by MaxIzUnavailable** [Alex-the-666/Ice_and_Fire#4755]
**Describe the bug**
So i was playing RLcraft and got bored so as any pro would do i entered creative mod i found a black dragon and started killing it with my iron sword noticed it was too slow so i gave myself a fire sword from the mod which was taking its life faster the weird thing is when i killed the dragon the body lagged in the air and then continued to fall where half its body stayed inside a cliff when I went down to click its body whole chunks started to kind of turn invisible or dissapered and only some weird Glitch stripes you could see it seemed as if the body of the dragon was replaced for every blocj to be honest, well now i lost that world (i am unable to open it, it doesnt load) which doesnt bother me that much but obiously thus bug should be fixed, i read a lot of github posts on this place but havent seen anybody with this glitch/bug i don't know if it was a one of a kind bug but i hope this doesnt happen to anybody elses world maybe it has to do with its commpatibility with RLcraft but im just guessing at this point

[I dont know if its reproducable]
1. Find a dragon on a tall cliff
2. Kill it with a fire sword
3.if the dragon glitches through the side of the mountain click it
4. Done? Now you should have your whole world crash but before that see all of the world turn into that glitched dragons body and lots of stripes and buggy black chunks!

I wasn't able to take a screenshot since it crashed my pc and i wasnt fast enough to take a photo before my pc crashed

**Comment by TheBv** [comment]
Version 1.12 is no longer actively maintained.
