### ISSUE TITLE
Choppy riding animations [Ice and fire - 2.1.12-1.18.2 - snapshot + build. 2023-01-31]

### ISSUE THREAD

**Issue by ycymyjs** [Alex-the-666/Ice_and_Fire#4756]
Riding a Amphithere, Hippogryph when the eagle and the dragon to Turn to animation very card, looks very uncomfortable, hope can repair it

**Comment by ycymyjs** [comment]
Uploading lssues .mp4…

**Comment by ycymyjs** [comment]
https://user-images.githubusercontent.com/126383715/221898088-8c96f20a-c5fa-4958-8523-c7cb2ffa012f.mp4

**Comment by TheBv** [comment]
Fixed with 83f9da5
