### ISSUE TITLE
Chunk Loading Error

### ISSUE THREAD

**Issue by EtheralSnake** [Alex-the-666/Ice_and_Fire#476]
I found a dragon cave underground, and for some reason the chunk that it's in hasn't loaded properly. The dragon was stuck inside of the wall
![2017-11-24_18 18 29](https://user-images.githubusercontent.com/33048327/36364368-e6e71008-1597-11e8-85ab-cce3557103de.png)
![Uploading 2017-11-24_18.18.39.png…]()

PS: I'm sorry if this issue has been posted before, but I really couldn't be bothered to sort through over 50 issues

**Comment by EPIICTHUNDERCAT** [comment]
put what version of MC in your title please ex: [1.12.2] IN FRONT of your title

**Comment by AlexModGuy** [comment]
seems like this is just a vanilla failure to generate chunks.
