### ISSUE TITLE
keep getting same moditems error even though ive downloaded all the recent versions

### ISSUE THREAD

**Issue by GavynTheNoob** [Alex-the-666/Ice_and_Fire#4762]
im trying to play 1.12.2 with spartan fire, ive got spartan weaponry 1.5.1, ice and fire version 1.9.1, LLlib 1.7.2, and spartan fire 0.08 but it keeps giving me this error:

java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/core/ModItem

i have a decent amount of other mods, so maybe it sone of those if needed to see

**Comment by TheBv** [comment]
1.12 isn't being supported anymore
