### ISSUE TITLE
Pixie Theft - Dupe Bug

### ISSUE THREAD

**Issue by AllenSeitz** [Alex-the-666/Ice_and_Fire#477]
I had a pixie steal an Immersive Enginnering revolver from my inventory. (Not my hotbar.) I was surprised and impressed when killing it returned my item with all the metadata intact! (Improvements, ammo type and quantity, and shader.)

Except that I got two of my revolver back. And I think maybe my looting sword doubled the drop? I've tried to replicate the bug but I cannot. I think I might have duped other items, but not noticed, due to my other potential dupes being stacks of arrows and mundane things.

**Comment by AllenSeitz** [comment]
This was on version 1.3.1 of the mod.

**Comment by EPIICTHUNDERCAT** [comment]
put what version of MC in your title please ex: [1.12.2] IN FRONT of your title

**Comment by AllenSeitz** [comment]
Sorry. It was 1.12.2 for what it's worth. I can't seem to edit the title like I can the report.
