### ISSUE TITLE
[Bug]: Crash when try to summon dread Knight

### ISSUE THREAD

**Issue by david-rodriguez-stori** [Alex-the-666/Ice_and_Fire#4779]
### What happened?

The game crashes when summon the dread Knight i think it is probably because of the apotheosis mod and the enhanced mobs like this one 
![image](https://user-images.githubusercontent.com/97138938/224561716-1d4e4545-149d-4a50-a8a5-f1693e429522.png)
but i'm not sure.

Debug log
[debug.log](https://github.com/AlexModGuy/Ice_and_Fire/files/10951525/debug.log)
Lastest Log
[lastest.log](https://github.com/AlexModGuy/Ice_and_Fire/files/10951529/lastest.log)
Crash Log
[crash-2023-03-12_11.21.16-client.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/10951545/crash-2023-03-12_11.21.16-client.txt)

Video of the issue
https://youtu.be/Ugt2noElFc4

### Minecraft Version

1.18

### Ice and Fire version

iceandfire-2.1.12-1.18.2-beta

### Citadel version

citadel-1.11.3-1.18.2

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by NowaGIT** [comment]
I do not have Aphoteosis mod and it crashes when sumonning Dread Knight, tried summoning it using a spawn egg from creative and crashed

```
The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.resources.model.Material.m_119194_(net.minecraft.client.renderer.MultiBufferSource, java.util.function.Function)" because "$$13" is null
```

**Comment by eehunter** [comment]
I'm having a similar issue and it looks like Rubidium may have something to do with it. My pack has Rubidium, and the attached crash report mentions Rubidium mixins several times.

Edit: Rubidium may be a false lead. Another report of the same issue shows it occurring without Rubidium installed and the aforementioned references to Rubidium mixins appear to be lists of all mixin config files.

**Comment by TheBv** [comment]
Same as https://github.com/AlexModGuy/Ice_and_Fire/issues/4744
Closing/moving discussion to over there
