### ISSUE TITLE
[Suggestion] Stop Tamed Dragons From Aging/Growing

### ISSUE THREAD

**Issue by SuperSaiyanSolar** [Alex-the-666/Ice_and_Fire#478]
I've been using this mod on a small private server with some friends, and we utterly adore it! Sure, it has it's quirks and bugs (most of which have already been reported) but the mod is excellently done and one of our favorites.

However, after much preparation we have all set out to get our dragon eggs and dragons, but there is an issue that has come to mind. While testing the mod, we found that tier 5 tamed dragons are _very_ difficult to fly, and like to vanish when they get around 20 blocks away from the player. This, of course, makes it sort of a hassle to use them. The best size for riding a dragon seems to be tier 3, and there is currently no way to keep them at that perfect size to my knowledge.

What I am suggesting is some form of potion, command, item, anything, that would keep a tamed dragon from aging. That way, people could collect baby dragons or keep their dragons at the perfect size for lag control and rideability.  This would be beneficial to servers as well, as people having many tamed tier 5 dragons could cause large amounts of lag with how buggy their rendering seems.

Thank you for your time, and I do hope you take this into account. I believe it would be an excellent, lag-combating and fun feature.

**Comment by AlexModGuy** [comment]
https://github.com/Alex-the-666/Ice-and-Fire-Suggestions/issues
