### ISSUE TITLE
SPAM LOG

### ISSUE THREAD

**Issue by Willem07** [Alex-the-666/Ice_and_Fire#4780]
### What happened?

[latest.log](https://github.com/AlexModGuy/Ice_and_Fire/files/10951594/latest.log)

### Minecraft Version

1.18

### Ice and Fire version

2.1.12-beta

### Citadel version

1.11.3

### Relevant log output

```shell
[Worker-Main5/ERROR] [net.minecraft.Util/]: Detected setBlock in a far chunk [36, 50], pos: BlockPos{x=576, y=67, z=814}, status: minecraft:features, currently generating: Placed Direct{Configured: com.github.alexthe666.iceandfire.world.gen.WorldGenMyrmexHive@26e55188: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@6a532efa}
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by erazare** [comment]
this seems to happen with most of the generated mob biomes, i am getting the error most commonly for the MyrmexHive and the Reddragonhive but pretty sure i get one for all of them.. there are so many flying by..

**Comment by TheBv** [comment]
Addressed in the latest snapshot :)
