### ISSUE TITLE
[Bug]: Hippocampus

### ISSUE THREAD

**Issue by Willem07** [Alex-the-666/Ice_and_Fire#4782]
### What happened?

When I sit on the hippocampus, it starts to move backwards by itself until I press the forward key.

### Minecraft Version

1.18

### Ice and Fire version

2.1.12-beta

### Citadel version

1.11.3

### Other Information

- [ ] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by Scotterrr** [comment]
Anyone figure out what to do about this?

**Comment by TheBv** [comment]
Fixed in latest snapshot https://github.com/AlexModGuy/Ice_and_Fire/releases/tag/1.18.2-latest-snapshot

**Comment by ili0s** [comment]
This did indeed get sorta fixed, except they now go sideways instead of backwards
