### ISSUE TITLE
[Bug]Chains don't work in 2.1.12 for forge 1.18.2

### ISSUE THREAD

**Issue by Glicz1** [Alex-the-666/Ice_and_Fire#4790]
When trying to interact with anything using the chain line or the sticky chain line they break instantly and drop on the ground.

can't provide crash log as the game doesn't crash.

**Comment by TheBv** [comment]
Fixed https://github.com/AlexModGuy/Ice_and_Fire/releases/tag/1.18.2-latest-snapshot
