### ISSUE TITLE
[Question]: How do I use the advanced config files?

### ISSUE THREAD

**Issue by Mqony** [Alex-the-666/Ice_and_Fire#4796]
### What happened?

Hello. I'm trying to configure fire_dragons_biomes.json to allow fire dragons to spawn in the nether, but I can't seem to figure it out. Does anyone know how I would go about doing this? Any help would be greatly appreciated!

### Minecraft Version

1.18

### Ice and Fire version

2.1.12

### Citadel version

1.11.3

### Relevant log output

```shell
N/A
```

### Other Information

- [ ] I am using other mods besides Ice and Fire
- [x] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Take a look at this:
https://github.com/AlexModGuy/Ice_and_Fire/wiki/How-to-specify-the-regions-structures-and-mobs-can-be-spawned
`BIOME_DICT` is outdated though use `BIOME_TAG` instead
Refer to the other existing config files for more examples
