### ISSUE TITLE
[Suggestion] Add /locate for other structures with mobs

### ISSUE THREAD

**Issue by DeshiDesu** [Alex-the-666/Ice_and_Fire#4799]
I spend a lot of time locating dragon roosts and other related generated structures with the mobs in them to confirm that ice and fire is properly installed in my server. Only these specific structures except 3 others are not available in the list of the /locate command could you please explain why?

**Comment by TheBv** [comment]
The other generations aren't structures but features. So they don't support the locate command out of the box.
