### ISSUE TITLE
General dragon and dread issues

### ISSUE THREAD

**Issue by MioSignore** [Alex-the-666/Ice_and_Fire#4800]
### What happened?

If no key is pressed ice dragons swim backwards.

The power of dragon balls is diminished compared to the 1.16 version.

Ice dragons and dread mobs aren't immune to powder snow damage.

Also the safety measure of dragons landing first when dismounting mid-air with shift is missing, the player will just crash to the ground and die.

### Minecraft Version

1.18.2

### Ice and Fire version

2.1.12-1.18 beta

### Citadel version

1.11.13-1.18.2

### Relevant log output

```shell
Due no the absence of crash, no log can be given.
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Should've all been addressed: https://github.com/AlexModGuy/Ice_and_Fire/releases/tag/1.18.2-latest-snapshot
