### ISSUE TITLE
1.18.2 Beta port of Ice and Fire visual bug

### ISSUE THREAD

**Issue by JosephGallagher2001** [Alex-the-666/Ice_and_Fire#4809]
![2023-03-25_15 03 31](https://user-images.githubusercontent.com/61439639/227736548-b3ceb6a0-4f38-4d1d-90d8-648dcca06aa6.png)

So as you can see by the picture, the Fire Dragonsteel Leggings have some Z-fighting issues. This is the same with the ice and lightning variants as well. Is it possible to fix this?

**Comment by TheBv** [comment]
Fixed in the latest snapshot https://github.com/AlexModGuy/Ice_and_Fire/releases/tag/1.18.2-latest-snapshot
