### ISSUE TITLE
[Bug]: Can't put chains on dragons, dragons don't land and fire particles spawn in the wrong place

### ISSUE THREAD

**Issue by TheWaffleWasTaken** [Alex-the-666/Ice_and_Fire#4810]
### What happened?

So, I created a new world and in my survival world and other worlds it was working perfectly fine, then I changed to the version of I&F released on curseforge (1.18.2) and suddenly I couldn't put chains on dragons, whether tamed or owned and dragons wouldn't land either. The dragonflute also doesn't work. I also noticed that the dragon fire breath is spawning it's particles in the wrong area.
**Steps to reproduce**
1) Create new world
2) Get dragon
3) Ride dragon
4) Expect dragon to land

1) Create new world
2) Get dragon
3) Chain dragon
4) Expect dragon chain to stay on

I also did test the chains on other mobs and that doesn't work either.
[2023-03-26-1.log](https://github.com/AlexModGuy/Ice_and_Fire/files/11071462/2023-03-26-1.log)
Here is also a video describing my problems:
https://drive.google.com/file/d/1DeLEKjc5jRQLnkk3i63maO-j92tC3aBy/view?usp=share_link

### Minecraft Version

1.18.2

### Ice and Fire version

iceandfire-2.1.12-1.18.2-beta

### Citadel version

1.11.3

### Relevant log output

I don't have any but I did include the log

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Same as #4790
