### ISSUE TITLE
[Bug]: Severe lag is caused after installing this mod together with cracker's witherstorm mod

### ISSUE THREAD

**Issue by JerryHan3** [Alex-the-666/Ice_and_Fire#4818]
### What happened?

After installing this mod together with cracker's witherstorm mod, a severe lag happened on the server, making TPS drops to less than 10. Although the Spark profiler shows that the `WitherSicknessEvent` from cracker's witherstorm mod is the main cause of lag.  the lag only appears after installing this mod, and can't be removed by uninstalling your mod.

The Spark profile: https://spark.lucko.me/780ea82Jdg

### Minecraft Version

1.18

### Ice and Fire version

2.1.12-beta

### Citadel version

1.11.3

### Relevant log output

```shell
The log is too long and here's a pastebin: https://pastebin.com/Ff7cJJNc
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
I looked into it and it seems like this issue is entirely on them and some inefficient code/code structures.
Nothing I can do about it, literally, since their code is closed source.
