### ISSUE TITLE
[Bug]: Parcial structure incompatibility with Terralith

### ISSUE THREAD

**Issue by DarknesSeeker** [Alex-the-666/Ice_and_Fire#4821]
### What happened?

Almost none of the structures and biome-specific spawns from Ice and Fire spawn in a world generated with Terralith biomes, the only exception being the Graveyards (Probably because they only check if the biome is in the overworld surface and not water).

Other entities that have natural spawns, like the Amphithere spawn and work as they should.

Any chance a more expanded or alternative biome list could be created to work with advanced terrain generators?

### Minecraft Version

1.16

### Ice and Fire version

2.1.12

### Citadel version

1.11.3

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by Kev-Bru** [comment]
This bug is in the version 1.18.2 as Terralith is for 1.18.2 not 1.16

**Comment by TheBv** [comment]
Not sure if it was an update with ice and fire or terralith but this doesn't seem to be an issue anymore.
