### ISSUE TITLE
[Bug]: Chain line deattachment

### ISSUE THREAD

**Issue by JACL2004** [Alex-the-666/Ice_and_Fire#4823]
### What happened?

in the current port both chain lines do not work with any mob, they inmediatly come off, doesnt matter if there is a bone wall present 

### Minecraft Version

1.18

### Ice and Fire version

iceandfire-2.1.12-1.18.2-beta

### Citadel version

1.11.3

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Same as #4790
