### ISSUE TITLE
[Bug]: iceandfire-2.1.12-1.18.2-beta 

### ISSUE THREAD

**Issue by qqbone** [Alex-the-666/Ice_and_Fire#4825]
### What happened?

Ice and fire seems to heavily inject its village structure aggressively when used with the Bettervillager mod. It tends to force other modded structures as well like shrines from paraglider. I have tested it without Ice and Fire and it'll generate fine. I've tried this on multiple versions of Better Villages.
While Iceandfire is by itself there's always 2 per village if it generates.

The only other issues I've found is that the configs to edit dragonsteel's weapon values do not work. 
![vanillawithbettervillages](https://user-images.githubusercontent.com/92418035/230744974-7ddab01b-ab66-41a2-8e9c-331efc42c52d.png)
![villagesvanillaiceandfire](https://user-images.githubusercontent.com/92418035/230744980-295730a9-6416-4e0c-8df6-7890dd590c5e.png)
![iceandfireplainsvillage](https://user-images.githubusercontent.com/92418035/230744983-3b417202-c369-4170-8c33-e34f4bf8d116.png)
![iceandfireicevillage](https://user-images.githubusercontent.com/92418035/230744984-7af761a2-301b-4b66-a0c0-26fd8148c36e.png)

### Minecraft Version

1.18

### Ice and Fire version

iceandfire-2.1.12-1.18.2-beta 

### Citadel version

 citadel-1.11.3-1.18.2

### Relevant log output

```shell
If you can tell me what I need to grab to help I'd gladly do so. I'll be submitting this as well to  the Bettervillage developer.
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
I forgot to change the default value in the config file. My bad!
Go into the config (`config/iceandfire-common.toml`) and change `"Villager Scribe House Weight"` to 5 or a even lower value if you desire :)

**Comment by TheBv** [comment]
Has been fixed https://github.com/AlexModGuy/Ice_and_Fire/releases/tag/1.18.2-latest-snapshot
