### ISSUE TITLE
[Bug]: i can see the item but i dont see any  spawn of the mod in spec mode

### ISSUE THREAD

**Issue by CHICOCHOCOLATADA** [Alex-the-666/Ice_and_Fire#4827]
### What happened?

hi there i download the mod fore minecraft 1.6.5 and other time i can see the mods spawn in caves or little museums but this time dont load nothing of that

### Minecraft Version

1.16

### Ice and Fire version

iceandfire-2.1.9-1.16.5

### Citadel version

citadel-1.8.1-1.16.5

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Sounds like a mod dependency issue. Also please use the latest version of ice and fire that being 2.1.12
