### ISSUE TITLE
[Bug]: Cannot interact with Lectern in 1.17.1

### ISSUE THREAD

**Issue by Irellafael** [Alex-the-666/Ice_and_Fire#4828]
### What happened?

I tried to shift + right-click and just right-click on the lectern, but nothing happens. I tried this with an empty hand as well.

### Minecraft Version

1.17

### Ice and Fire version

iceandfire-2.1.12-1.17.1-beta

### Citadel version

citadel-1.9.5-1.17.1

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Has been fixed: https://github.com/AlexModGuy/Ice_and_Fire/releases/tag/1.17-latest-snapshot
