### ISSUE TITLE
[Bug]:  1.18.2 Beta - Client Crash when running with dragon on shoulder

### ISSUE THREAD

**Issue by ili0s** [Alex-the-666/Ice_and_Fire#4829]
### What happened?

encountered a crash when running with dragon on shoulder with chunks trying to render in, see crash report for details.

[crash-2023-04-11_11.31.30-client.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/11198963/crash-2023-04-11_11.31.30-client.txt)

### Minecraft Version

1.18

### Ice and Fire version

1.18.2 Beta 

### Citadel version

1.11.3 1.18.2

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Closing in favor of #4849
