### ISSUE TITLE
[1.12.2] More spawning Options are needed for creatures in the Configs

### ISSUE THREAD

**Issue by MokahTGS** [Alex-the-666/Ice_and_Fire#483]
Dragons seem to have dimensional control over spawning, but new creatures do not.  Spawning of structures and creatures needs to be universal to allow config setting of what dimension and biomes they are allowed to spawn in.  Currently Pixies, cyclops, Gorgons, and Hypogyphs don't seem to have the same options for spawning configuration that dragons do.

**Comment by ScottRadish** [comment]
Also, I'd love it if dragons were broken down by type. In my mod pack I'd like fire dragons to spawn in a different dimension than ice dragons, but the config treats all dragons the same.

**Comment by AlexModGuy** [comment]
https://github.com/Alex-the-666/Ice-and-Fire-Suggestions
