### ISSUE TITLE
[Bug]: ampithere is way too fast

### ISSUE THREAD

**Issue by RaccRegimist** [Alex-the-666/Ice_and_Fire#4830]
### What happened?

tamed ampitheres fly incredibly fast to the point where my pccant handle it, hippocampus also goes backwards when not swimming and is also incredibly fast when swimming, the hippocampus should be horse speed, and the ampithere should not be on steds when flying

### Minecraft Version

1.18

### Ice and Fire version

2.1.12

### Citadel version

1.11.3

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Fixed/adjusted with https://github.com/AlexModGuy/Ice_and_Fire/releases/tag/1.18.2-latest-snapshot
