### ISSUE TITLE
[Bug]: 1.18.2 - Hippocampi swims backwards when mounted 

### ISSUE THREAD

**Issue by ili0s** [Alex-the-666/Ice_and_Fire#4831]
### What happened?

Hippocampi swims backwards when mounted and ridden with saddle 

### Minecraft Version

1.18

### Ice and Fire version

1.18.2 Beta 

### Citadel version

1.11.3 1.18.2

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Same as #4782
