### ISSUE TITLE
[Bug]: dread knight crashing

### ISSUE THREAD

**Issue by TainanRezende** [Alex-the-666/Ice_and_Fire#4832]
### What happened?

I'm walking around the world and I found an ice and fire dungeon (the dungeon where there are dragon forge blocks), when I got close to the dungeon my game crashed when I enter again it always crashes and results in the same log pointing to this dread knight mod.

### Minecraft Version

1.16

### Ice and Fire version

iceandfire-2.1.12-1.18.2-beta

### Citadel version

citadel-1.11.3-1.18.2

### Relevant log output

```shell
https://gist.github.com/TainanRezende/f1ae788ab7aa16854cf6271f98f4c6bc
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Same as https://github.com/AlexModGuy/Ice_and_Fire/issues/4744

**Comment by TainanRezende** [comment]
can you update the file in curse? I have modpack there and I can't use files that aren't from there
