### ISSUE TITLE
[Crash]: world's aren't loading after i removed ice & fire

### ISSUE THREAD

**Issue by justawander** [Alex-the-666/Ice_and_Fire#4833]
### What happened?

so a while back i was testing ice and fire and decided it wasn't for me. later when i tried to enter my worlds the just kept loading not doing anything. my best guess is that this is due to be removing ice and fire. do you have any solutions beyond just reinstalling the mod?

### Minecraft Version

1.18

### Ice and Fire version

2.1.12-1.18.2-beta

### Citadel version

1.11.3

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by SiverDX** [comment]
not enough information to do anything
