### ISSUE TITLE
[Bug]: Chunk generation causing heavy lag and performance drops on servers

### ISSUE THREAD

**Issue by ili0s** [Alex-the-666/Ice_and_Fire#4835]
### What happened?

Chunk generation causing heavy lag and performance drops on servers - at times it causes players to get disconnected due to timeout error, seems to be related to dragon caves as the console log of the server usually has logs pointing to dragon caves whenever this connection timeout occurs 

`"16.04 13:00:08 [Server] Worker-Main-2/ERROR Detected setBlock in a far chunk [90, 81], pos: BlockPos{x=1447, y=17, z=1301}, status: minecraft:features, currently generating: Placed Direct{Configured: com.github.alexthe666.iceandfire.world.gen.WorldGenIceDragonCave@67bb3c8b: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@7183e962}" `

### Minecraft Version

1.18

### Ice and Fire version

1.18.2 Beta 

### Citadel version

1.11.3 1.18.2

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Not sure why this message still gets printed for you... I specifically "disabled" it. Could you perhaps provide your log files?

**Comment by ili0s** [comment]
The issue doesnt generate log files, just causes a huge connection timeout - next time it happens ill copy the entire log directly from console to hopefully provide a little more insight

**Comment by TheBv** [comment]
Everything that get logged in the console also produces a log file. There's two files `debug.log` and `latest.log` either would suffice.

**Comment by ili0s** [comment]
finally found a log that brings up the issue! Sorry for the delay, i thought you meant crash log at first

[latest.log](https://github.com/AlexModGuy/Ice_and_Fire/files/11276499/latest.log)

**Comment by TheBv** [comment]
Oh I see it now. I forgot that the fix for this isn't present in the current beta. If you want to try it out right now refer to this: https://github.com/AlexModGuy/Ice_and_Fire/releases/tag/1.18.2-latest-snapshot
Otherwise there will also be a new beta release near the end of the week

**Comment by ili0s** [comment]
excellent! does this cover the myrmex spawns aswell because they seem to be affected in a similar way

**Comment by TheBv** [comment]
Yeah should cover all of these types of messages :)
