### ISSUE TITLE
Hippogryph egg commands

### ISSUE THREAD

**Issue by LPTEole** [Alex-the-666/Ice_and_Fire#4838]
Hello,

In my RPG server, I have to add an NPC trader wich sell hippogryph eggs of all types.

I have found how to spawn an adult hippogryph with commands, but I don't find how to make for eggs, I know that we have the "Variant:n" to add, but I don't find the other parameters required for this. I only have the "black" version of eggs for know...

My command tested was : `/give @p iceandfire:hippogryph_egg{Variant:2}` (with quotes was tested, same with "Atributes" before).

I am in 1.16.5 Minecraft version, 2.1.9 for this mod (I don't use only this mod).

I hope you can help to have the informations,

Regards.

**Comment by TheBv** [comment]
Hippogryph eggs don't seem to support different types right now. You can only spawn different variants with commands; the eggs will always produce black hippogryphs

I'll add it to the things which might be nice to include in future releases.

**Comment by LPTEole** [comment]
Ok, thanks a lot ! I'll check the status of the feature so :)

**Comment by TheBv** [comment]
Sorry for the late reply but as it turns out there was an NBT tag to control this. It's called `EggOrdinal`.

**Comment by LPTEole** [comment]
Thanks a lot ! I confirm it works ! :D

I add the commands for people wich need it : 
/give "me" iceandfire:hippogryph_egg{EggOrdinal:?}

For an NPC, just add this in the tag buy/sell :
id:"iceandfire:hippogryph_egg",Count:1,tag:{EggOrdinal:?}

? is between 0 and 9 :) - 0 is default
