### ISSUE TITLE
Disabling Glacier biomes

### ISSUE THREAD

**Issue by Vampsku11** [Alex-the-666/Ice_and_Fire#484]
Is it possible to disable Glacier biomes entirely? I have tried setting the rarity to 0 and to 1000 but still 90% of the time an expansive glacier generates next to spawn.

MC 1.12.2
1.12.2-forge1.12.2-14.23.2.2611
iceandfire-1.3.1-1.12.2.jar

**Comment by NielsPilgaard** [comment]
I've tried setting it to 2147483647, and they're still common. It'd be really nice to be able to turn them off completely.

**Comment by Vampsku11** [comment]
I think the number is actually weight, not rarity. I tested again with a
very high number and filled several Minecraft maps with a single biome,
then again with 0 and haven't found one in several worlds.

**Comment by NielsPilgaard** [comment]
Man I feel stupid, should've guessed it was actually weight ^^'

**Comment by EPIICTHUNDERCAT** [comment]
is this fixed? if so close the issue.

**Comment by EvilDylan** [comment]
This is strange, because the wording of the config states:
"# glacier biome spawn chance - higher the number, higher the rarity"
Yet, a lower number seems to make it more rare, not a higher one. Perhaps the wording of the config should be updated to reflect this.
