### ISSUE TITLE
[Bug]: 1.18.2 I&F inconsistently crashes modpack on start up. 

### ISSUE THREAD

**Issue by toErIpNid** [Alex-the-666/Ice_and_Fire#4841]
### What happened?

Forge Ver: 40.2.1

Mod Ver: 2.1.12-1.18.2-beta2

Log: https://pastebin.com/YPt9rCh8

Note, this probably has something to do with the Essentials Mod, as when I tried to replicate the crash the game instead launched fully but didn't have any of the Essentials buttons or menus. 

### Minecraft Version

1.18

### Ice and Fire version

2.1.12-1.18.2-beta2

### Citadel version

citadel-1.11.3-1.18.2

### Relevant log output

```shell
https://pastebin.com/YPt9rCh8
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
The log you provided doesn't show any crashes. Could you maybe have another look? :)

**Comment by toErIpNid** [comment]
Yeah I can't get it to actually crash anymore, the main issue here now is that you can't see the Essentials Mod menu buttons on the title screen.

**Comment by TheBv** [comment]
You can disable the ice and fire menu in the client config, that should hopefully fix it.
