### ISSUE TITLE
1.18.2 Copper Shares Common Vanilla Block ID's

### ISSUE THREAD

**Issue by MalignantX** [Alex-the-666/Ice_and_Fire#4845]
Copper ingots and blocks randomly overwrite each other when adjusting them.

**Comment by TheBv** [comment]
It really shouldn't. One uses `iceandfire` as part of it's id the other uses `minecraft`. 
There's also no forge tags associated with copper so the iceandfire ore/ingot should be treated completely differently from others.
Also haven't experienced this myself
