### ISSUE TITLE
[Bug]: Cyclops attacks Bats and other Ambient Mobs

### ISSUE THREAD

**Issue by Reshy** [Alex-the-666/Ice_and_Fire#4847]
### What happened?

Cyclops will attack Bats and other ambient mobs like Terra Incognita's butterflies or Pyromancer's Scorch.  It doesn't target Alex's Mobs ambient mobs, but all other ambient mobs it will still target.

### Minecraft Version

1.18

### Ice and Fire version

iceandfire-2.1.12-1.18.2-beta2.jar

### Citadel version

 citadel-1.11.3-1.18.2.jar

### Relevant log output

```shell
N/A
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
I think it's supposed to be like that.
There's quite a long list of mobs that should/shouldn't get attacked.
In short: Entities that don't get attacked: "WaterAnimals", StoneStatues, Cyclops', Wolds, PolarBears, Dragons, Sheep(Like)-things. Not sure what AlexMobs does to avoid being attacked...
