### ISSUE TITLE
Hippogriff Disappeared 

### ISSUE THREAD

**Issue by tillasiren** [Alex-the-666/Ice_and_Fire#485]
My Hippogriff Disappeared instantly, I was riding and noticed a bit of lag so I assumed it was from my exploration so i decided to get off and grab some flowers. When I dismounted my hippogriff was gone

**Comment by EightBlade** [comment]
I've had a similar issue.

**Comment by EPIICTHUNDERCAT** [comment]
put what version of MC in your title please ex: [1.12.2] IN FRONT of your title

**Comment by AlexModGuy** [comment]
it flew away. Use a dragon flute to force them to land
