### ISSUE TITLE
[Bug]: Dragons/Cyclops Caves/Hydra dens are unable/inconsistently spawn with modded biomes 

### ISSUE THREAD

**Issue by DoctorN0va** [Alex-the-666/Ice_and_Fire#4859]
### What happened?

Specific structures(As listed in the title) seem to struggle a lot when it comes to modded biomes in the 1.18 release. I am currently running a server with Terralith and BoP and am unable to get any of these structures to spawn outside of one dragon roost. Removing the mods seems to make things roughly spawn as they would normally.

I attempted config wipe and edits to lessen restrictions on spawn rules. I'd also like to note that graveyards seem to spawn in overabundance (perhaps due to the lack of the other structures?) 

### Minecraft Version

1.18

### Ice and Fire version

2.1.12

### Citadel version

1.11.3

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by sadlyalive** [comment]
genuinely shocked nobody addressed this until now

**Comment by Stoutscientist** [comment]
same issue, exept i'm using way too many biome mods, i can find all the structures exept for dragons (which might be a slight issue)

**Comment by Stoutscientist** [comment]
I should probably attach a list:

Birch Forest Upgrade
Biomes O' Plenty
Oh The Biomes You'll Go
Quark
