### ISSUE TITLE
[1.12.2] Separate Loot Tables for Dragon Roosts and Dragon Dens

### ISSUE THREAD

**Issue by KAfable** [Alex-the-666/Ice_and_Fire#486]
Dragon Roosts are much easier to find above ground since you can just wander and explore the surface for the loot. Also early on, frequent amounts of Dragon Roosts can result in easy cheesing of materials since it's easy to find a dragon roost, wait for it to move away, and grab the loot, versus a Dragon Den which usually requires killing the dragon head-on before gathering the treasure.

Would it be possible to separate the dragon Roosts and Dragon Den Loot Tables?

**Comment by GundunUkan** [comment]
OR make the dragons stick to their roosts, like they used to do back in 1.11.2. That'd be even better.

**Comment by AlexModGuy** [comment]
https://github.com/Alex-the-666/Ice-and-Fire-Suggestions
