### ISSUE TITLE
[Bug]: Terralith underground dragon's den not generating?

### ISSUE THREAD

**Issue by qqbone** [Alex-the-666/Ice_and_Fire#4863]
### What happened?

So first off ty for a lot of the changes and fixes in the new release! Wanted to say that the swords do translate the damage server side respectively! Would love to see a config to edit axes and the tools as well for modpacks!

There's still some issues with Bettervillages and Iceandfire generating too many scribe's houses but I think they're trying to work it out with this datapack here!
https://www.curseforge.com/minecraft/texture-packs/better-villages-ice-and-fire-compat-datapack

I wanted to ask how and what config is needed for Dragon's Dens to spawn? What does it look for specifically, is it just biome then specific height?

### Minecraft Version

1.18

### Ice and Fire version

iceandfire-2.1.12-1.18.2-beta2

### Citadel version

citadel-1.11.3-1.18.2

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by gummie2022** [comment]
As far as I noticed, it cannot spawn Dragon Caverns even when configuring the Dragon Biome into Terralith biomes.

**Comment by gummie2022** [comment]
unfortunately in the recent snapshot, "iceandfire-2.1.12-1.18.2-SNAPSHOT+build.2023-06-19" still does not spawn even in modded vanilla biomes :(
