### ISSUE TITLE
[Bug]: Ghosts not dropping anything

### ISSUE THREAD

**Issue by Aceplante** [Alex-the-666/Ice_and_Fire#4867]
### What happened?

I killed at least 30-40 ghosts WITH looting 3, and didnt get anything at all, either ectoplasm or that ingot. Nothing.

Edit: now killed over 200 more, with smite, still nothing

Edit 2: I traveled to a naturally generated graveyard to test it there, and the first two dropped ectoplasm, but them I didnt get any more in the 50+ kills after that

### Minecraft Version

1.18

### Ice and Fire version

1.18.2

### Citadel version

idk what citadel is

### Relevant log output

```shell
Not relevant
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [ ] I have attached a log file from the session that I have experienced this issue

**Comment by Kings-Creed** [comment]
I cant replicate these conditions oddly enough. Are the ghosts spawning from a chest or from the graveyard soil? The drop rate is low either way, but definitely not 1/100 with fortune III low.

If its graveyard soil, how did you acquire it?

**Comment by Aceplante** [comment]
I spam opened the chest. I was thinking maybe they only drop if they're naturally generated/spawned...?

**Comment by TheBv** [comment]
Ghosts only drop loot if they naturally spawn. Or more precisely if they don't spawn from chests.

**Comment by Aceplante** [comment]
sadness
