### ISSUE TITLE
Flexible head and tail swing （Important advice）

### ISSUE THREAD

**Issue by ycymyjs** [Alex-the-666/Ice_and_Fire#4870]
### What happened?

In iceandfire -2.1.0-1.15.2, the dragon has a very flexible turn to animation. Such as the wagging of the tail and the rotation of the neck. Makes the dragon very vivid. However, this feature has been removed in the new version. This caused the dragon to be very stiff. It would be nice if it could be rejoined.
![2023-05-13_19 46 05](https://github.com/AlexModGuy/Ice_and_Fire/assets/126383715/98232699-1c09-43eb-b60d-9c7638a455a1)

### Minecraft Version

1.18

### Ice and Fire version

iceandfire-2.1.12-1.18.2-beta2

### Citadel version

1.11.3-1.18.2

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by ycymyjs** [comment]
I reposted it in Ice-and-Fire-Suggestions

**Comment by ycymyjs** [comment]
![2023-05-13_22 34 31](https://github.com/AlexModGuy/Ice_and_Fire/assets/126383715/11bd6421-eafc-43b4-bf49-b2213d8fd6cf)

**Comment by ycymyjs** [comment]
![2023-05-13_22 35 46](https://github.com/AlexModGuy/Ice_and_Fire/assets/126383715/3b4aa4a8-fc25-4499-a553-dd350e6eff32)

**Comment by TheBv** [comment]
Won't be fixed anytime soon unless we get around to rework the dragons completely. 
This feature was sadly causing other issues like jittery animations/neck snapping.

**Comment by ycymyjs** [comment]
I know , Excuse me Can the fix for jitter animation/neck break only remove flexible head-tail swing?
Or if you don't start completely redesigning Dragon, will this feature be gone forever? These are just some of my queries (Issue #4870)
