### ISSUE TITLE
[Bug]: The dragon's air stay animation is always delayed.

### ISSUE THREAD

**Issue by ycymyjs** [Alex-the-666/Ice_and_Fire#4872]
### What happened?

When the dragon rider stays in the air and still maintains the animation of flying forward, the switch takes a few seconds, hopefully this bug can be fixed.

### Minecraft Version

1.16

### Ice and Fire version

iceandfire-2.1.12-1.18.2-beta2

### Citadel version

1.11.3-1.18.2

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Fixed with #4850
