### ISSUE TITLE
Dragon Roosts and Caves are unbelievably rare, even if configured otherwise

### ISSUE THREAD

**Issue by CephalonAxii** [Alex-the-666/Ice_and_Fire#4873]
### What happened?

As the titles says, Dragon structures such as Roosts and Caves are almost nonexistent, even if configured to be more common. I noticed this issue in Sharkies mod pack Medieval Minecraft 1.18.2, where I wasn’t seeing any Dragons at all. I then changed the config for both Roosts and Caves to 100 in the configuration file. Then went spectator in a new world, and had the same results. Dragons were present, but it took solid 2-7 minutes flying around in Spectator. Then I removed all other mods and only kept Ice&Fire and citadel, changed the config again to 50 for Roosts and Caves, then created a new world and went spectator again. Same results. At 50, I should be seeing Roosts and Caves left and right, but no. 

### Minecraft Version

1.18

### Ice and Fire version

iceandfire-2.1.12-1.18.2-beta2

### Citadel version

citadel-1.11.3-1.18.2

### Other Information

- [ ] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by Kings-Creed** [comment]
This is an issue thats been raised several times over. Ive tested using the exact same parameters, both with and without modded biomes. Same issue occurs. 

Oddly enough, caves seem to spawn more often than their counterparts due to this, it would appear

**Comment by gummie2022** [comment]
yes since the cave and cliffs completely overhaul biomes and spawn rate of structures
