### ISSUE TITLE
[Bug] - Dragon structures won't spawn in WWOO generated worlds

### ISSUE THREAD

**Issue by JackTD** [Alex-the-666/Ice_and_Fire#4878]
**What happened?**
I have installed Ice and Fire along William Wythers' Overhauled Overworld mod and so far so long I've never spotted a dragon root or dragon lair (I tried with just these two mods and dependencies and tried with other mods but still the same issue occurs) . I've tried to configure generation rate but all in vain. Also I tried to include certain biomes in biome configuration for fire dragons but still nothing worked. I hope that I didn't configured properly. I attached log, and 2 config files

**Minecraft Version**
1.18.2

**Ice and Fire version**
2.1.12

**Citadel version**
1.11.3

**Relevant log output**
[2023-05-21-1.log.gz](https://github.com/AlexModGuy/Ice_and_Fire/files/11523898/2023-05-21-1.log.gz)

**Other Information**
- [x]  I am using other mods besides Ice and Fire.
- [x] I have attached a log file from the session that I have experienced this issue.  

[iceandfire-common.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/11523913/iceandfire-common.txt)
[fire_dragon_biomes.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/11523914/fire_dragon_biomes.txt)

**Comment by Wowwaw** [comment]
Saya mengalami hal yang sama, yang saya temukan hanya bangkai naga

**Comment by SiverDX** [comment]
See https://github.com/AlexModGuy/Ice_and_Fire/issues/4934#issuecomment-1891763336
