### ISSUE TITLE
Can't use nametag on hippogriff

### ISSUE THREAD

**Issue by EightBlade** [Alex-the-666/Ice_and_Fire#488]
I'm trying to name my hippogriff, but I can't seem to apply the nametag

**Comment by EPIICTHUNDERCAT** [comment]
put what version of MC in your title please ex: [1.12.2] IN FRONT of your title

**Comment by EvilDylan** [comment]
This was explained to me in the discord by a kind fellow.
Because of priorities, riding will always take presidence over naming; the solution is to remove the saddle before attempting to name your hippogryph.
