### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Firerose689** [Alex-the-666/Ice_and_Fire#4881]
### What happened?

While testing out the 1.18.2 ice and fire beta Ice and fire normal chains will not link to any mob when clicked on, it simply pops off as if the link was broken. 
Another bug I found throughout the world is dragon nests under ground are spawning with the ends cut off, or just half of one section, (leaving it often empty) or the nest in half across chunk boarders. 

### Minecraft Version

1.18

### Ice and Fire version

iceandfire-2.1.12-1.18-beta

### Citadel version

1.11.3-1.18.2

### Relevant log output

```shell
There is no log for this.
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Fixed in beta2
