### ISSUE TITLE
[suggestion]Have a configuration option to disable the title background dragon.

### ISSUE THREAD

**Issue by dragon3025** [Alex-the-666/Ice_and_Fire#489]
I'm using a custom resource pack for my background and when I installed this mod, I noticed there was an out of place section of the title background panorama, so I had make an overwrite to that. If I ever change my background, I'm going to have to keep overwriting the dragon picture.

I think it would be more convenient if the dragon picture could be disabled in the configuration.

**Comment by EPIICTHUNDERCAT** [comment]
picture plz xD
