### ISSUE TITLE
[Bug]: Clicking hippocampus to add saddle causes crash

### ISSUE THREAD

**Issue by TempAccount693** [Alex-the-666/Ice_and_Fire#4890]
### What happened?

The game crashed whilst container click
Error: java.lang.IndexOutOfBoundsException: Index 45 out of bounds for length 39. Exit Code -1.

https://pastebin.com/S1dqDrnh

Other mods installed (forge 1.18):
Aquaculture
Astikor Carts
Batty's Coordinates
Betteranimalsplus and betteranimalmodels
Building Gadgets
Connectible Chains
Corail Recycler
Exotic Birds
Forever A Child
Get in the bucket
Hole filler mod
Inventory Sorter
Lava Sponge
Mouse Tweaks
Rubidium + Rubidium Extra
Simply Jetpacks 2
Vanilla Hammers
WTHIT

### Minecraft Version

1.18

### Ice and Fire version

iceandfire-2.1.12-1.18.2-beta2

### Citadel version

citadel-1.11.3-1.18.2

### Relevant log output

```shell
https://pastebin.com/S1dqDrnh
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Can't replicate this. Probably some other mod causing this that is interferes with container/menu creation.
