### ISSUE TITLE
need help adding new biomes to mob spawns.

### ISSUE THREAD

**Issue by Sketano** [Alex-the-666/Ice_and_Fire#4894]
To me, The format for the biome configs are very confusing.

I want to add specific biomes, Do I do THIS?

      },
      {
        "type": "BIOME_TAG",
        "negate": false,
        "value": "terralith:terralith:wintry_forest"
        
 I'm really unsure of what to do. Should I place the type with REGISTRY_ID? I tried to make a config but it just doesnt seem to work, Heres the link: https://gist.github.com/Sketano/2b29caf68bae8e9e8086b147230a347e If you're able to tell me whats wrong, That'll be cool. Thanks

**Comment by TheBv** [comment]
You want to wrap each entry in another pair of `[ ]` 
Check out https://github.com/AlexModGuy/Ice_and_Fire/wiki/How-to-specify-the-regions-structures-and-mobs-can-be-spawned for some more guidance

**Comment by Sketano** [comment]
Thanks
