### ISSUE TITLE
Pixie Hovels look the same

### ISSUE THREAD

**Issue by EtheralSnake** [Alex-the-666/Ice_and_Fire#490]
I know you said you fixed it, but it's still happening for me. I am absolutely certain I am in the 1.3.1 version, and I have no texture packs or other mods installed except for Optifine
![screenshot 2 _li](https://user-images.githubusercontent.com/33048327/37016515-b7a61008-2160-11e8-9bee-803d05b0b41c.jpg)

**Comment by EPIICTHUNDERCAT** [comment]
latest version for me isnt broken. put what version of MC in your title please ex: [1.12.2] IN FRONT of your title

**Comment by AlexModGuy** [comment]
update your LLibrary
