### ISSUE TITLE
Gorgons Blood

### ISSUE THREAD

**Issue by Aceplante** [Alex-the-666/Ice_and_Fire#4903]
### What happened?

The decapitated bodies fall to the ground spurting blood for a few seconds. You already have the perfect functionality for Gorgons blood to exist, yet I was very surprised to find it does not.

Using a bottle on a Gorgon body can yield up to three bottles if you're fast enough (or only 2 then 1 if you are not and the blood is wasted).

Gorgons blood would basically be a fatal poison that deals damage much more rapidly. This of course would be extremely OP if it were able to be made into a splash potion, so it would not be able to be made into one. Perhaps it could be used to tip arrows or something instead?

### Minecraft Version

1.18

### Ice and Fire version

1.18.2

### Citadel version

idk what citadel is

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Please post your suggestions here: https://github.com/AlexModGuy/Ice-and-Fire-Suggestions/issues

**Comment by Aceplante** [comment]
Yea... but you dont look at those do you? There are tons of good suggestions, such as number 2 which is over 6 years old, received a ton of support, and still radio silence...

**Comment by TheBv** [comment]
I mean there hasn't been any new feature addition in the last 2+ years for this mod.
My main focusing is trying to maintain the code/upgrade it to the various minecraft versions and that is the focus of this github as well. If people start posting there suggestions here it will be even more of a nightmare for me to filter through all of the issues than it already is.

**Comment by Aceplante** [comment]
ah, fair point. As a newcomer to this mod, I was not aware of the state it was in. We appreciate at least updates to current versions.
