### ISSUE TITLE
[Feature Request]: Dread Invasion Add-on

### ISSUE THREAD

**Issue by somebodyandnobody** [Alex-the-666/Ice_and_Fire#4909]
### What happened?

I'm not exactly sure this is how to go about making a feature request for this mod, but I recently had this idea and think quite a few people might like it. I know I should probably go to the discord but I don't have discord and probably never will.
This would be an add-on to the game (because it would obviously mess it up otherwise).
This whole idea started when I saw the dread scuttler and it reminded me of the assimilated big spider from Scape and Run: Parasties. Then I thought: what if the dread horde could invade the overworld?
So it would work like SRP where the invasion happens gradually. At first, a few portals open and some dread minions come through. Then some dread minions start appearing in the world. Maybe it could start raining in savannas and deserts. After some time the grass and sky start turning darker, and more and more dread minions are spawning. They're soon building fortresses with beacons firing ice magic into the sky. Soon it starts snowing all over the world. Oceans freeze, crops stop growing, torches are so cold that they no longer burn. The blizzard soon blocks out the sun, letting dread creatures roam unfettered. Effectively, the world transforms into the dreadlands.
It makes ice and fire a bit more of a horror mod than a mob mod, but still, I love the concept of the world being overtaken by some otherworldly force.

### Minecraft Version

1.16

### Ice and Fire version

not sure

### Citadel version

erm...

### Relevant log output

```shell
not exactly sure what to put here, I know I checked the box but I didn't exactly put any log here.
```

### Other Information

- [ ] I am using other mods besides Ice and Fire
- [ ] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Please post your suggestions/feature requests here: https://github.com/AlexModGuy/Ice-and-Fire-Suggestions/issues
