### ISSUE TITLE
unable to breed dragon

### ISSUE THREAD

**Issue by IceFireplayer** [Alex-the-666/Ice_and_Fire#491]
I installed latest ICE-AND-FIRE mod:
I play hard to kill dragon and then I gotten two fire dragon eggs: 1emerald and 1red. I am able to hatch them into stage 5 dragon for both, however when I try to feed them fire lily mixture they didn't breed. I make a couple of tries still it is not breeding. Same happen to hippogrphy.  But the rest tamed animals are fine for breeding.

**Comment by GundunUkan** [comment]
Are you sure they aren't the same gender?

**Comment by IceFireplayer** [comment]
Yes. There are opposite gender. Emerald is female and red is male that's what I gotten.

**Comment by EPIICTHUNDERCAT** [comment]
put what version of MC in your title please ex: [1.12.2] IN FRONT of your title

**Comment by AlexModGuy** [comment]
fixed in 1.3 I think
