### ISSUE TITLE
[Bug]: Graveyards are spawned in the sea.

### ISSUE THREAD

**Issue by ycymyjs** [Alex-the-666/Ice_and_Fire#4911]
### What happened?

Mausoleums are spawned in the sea.This is also too unreasonable.
![2023-06-21_18 58 44](https://github.com/AlexModGuy/Ice_and_Fire/assets/126383715/0a00139b-06b5-4cae-a6ba-06654ab2e65e)

### Minecraft Version

1.18

### Ice and Fire version

iceandfire-2.1.12-1.18.2-SNAPSHOT+build.2023-06-19

### Citadel version

1.11.3-1.18.2

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by gummie2022** [comment]
Do you mean graveyard?

**Comment by ycymyjs** [comment]
yes
