### ISSUE TITLE
[1.12.2] Armor Stand - Dragon Scale Helmet

### ISSUE THREAD

**Issue by TheProtectedVoid** [Alex-the-666/Ice_and_Fire#492]
When you put a Dragon Scale Helmet it points to the left side...

http://prntscr.com/ioz2no

**Comment by Honzixx** [comment]
I have Ice and Fire mod on server too, and all parts of Dragon Scale armor are turned to South when putted on Armor stand. Armor stand can be turned on every side, but Dragon armor will every time turned to South. And the same think is with Dragon skulls, they are turning to South after restarting server.

**Comment by TheProtectedVoid** [comment]
Uhm...

**Comment by GundunUkan** [comment]
Tamed dragons themselves are always pointing south when called out of a horn.
