### ISSUE TITLE
[Bug]: Гром уничтожает предметы

### ISSUE THREAD

**Issue by K1wani** [Alex-the-666/Ice_and_Fire#4925]
### What happened?

Если убить существо каким нибудь предметом из грозовой драконостали, то лут с этих мобов просто уничтожится, просьба исправить

### Minecraft Version

1.16(CRASHES ONLY)

### Ice and Fire version

1.16.5

### Citadel version

1.16.5

### Other Information

- [X] I am using other mods besides Ice and Fire
- [ ] I have attached a log file from the session that I have experienced this issue

**Comment by XionioXMaster** [comment]
Обновитесь до последней версии или используйте уже имеющийся фикс на последней версии для 1.16.5, вероятно что так и задумано автором?

**Comment by DonorKrovi** [comment]
Так и должно быть.
