### ISSUE TITLE
1.3.1 Stone hippogryph still being ridden

### ISSUE THREAD

**Issue by Frosty8-0** [Alex-the-666/Ice_and_Fire#493]
A gorgon petrified my hippogryph and I can still ride it.  I cant fly but I can jump and still move on it

**Comment by TheProtectedVoid** [comment]
Yeah, you can't fly but you can do very HIGH JUMPS like HULK!

**Comment by EPIICTHUNDERCAT** [comment]
put what version of MC in your title please ex: [1.12.2] IN FRONT of your title
