### ISSUE TITLE
[Bug]: Unable to Tame Hippogryphs

### ISSUE THREAD

**Issue by Reshy** [Alex-the-666/Ice_and_Fire#4930]
### What happened?

Was testing out the mob taming for a 1.18.2 modpack and noticed that the Hippogryphs aren't taming correctly, they seem to ignore the rabbit's feet both in survival and creative.

### Minecraft Version

1.18

### Ice and Fire version

iceandfire-2.1.12-1.18.2.jar

### Citadel version

citadel-1.11.3-1.18.2.jar

### Relevant log output

```shell
https://pastebin.com/sw742Mjc

Tested with a couple common performance mods.
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by Irellafael** [comment]
I have the same issue sadly.

**Comment by nyrzeff** [comment]
Tested using only Ice and Fire and Citadel, same versions, both in survival and creative, and unfortunately the same problem happens.

**Comment by nyrzeff** [comment]
Tested more and had inconsistent results: sometimes the Hippogryph was immediately tamed, while in others it would take some time to eat the rabbit feet and, still, in others it would simply ignore it and walk away/attack me.

**Comment by quinnfrost** [comment]
https://github.com/AlexModGuy/Ice_and_Fire/blob/386b4bc185d2f277b5d3688bf6347080dd84787a/src/main/java/com/github/alexthe666/iceandfire/entity/ai/HippogryphAITargetItems.java#L58
The hippogryph tend to find nearby rabbit foot every 4 ticks (with some other randomization), however, its target selector actually update at an interval of 2 ticks, if the hippogryph entity is loaded at gametime of a odd number, it will never check for rabbit foot.

Which means, if the hippogryph is ignoring your rabbit foot, you'll have to leave the area or quit to menu, and back again to reload this entity. And theoretically if you're lucky enough the hippogryph will loaded at an even number of gametime, then it can be tamed normally. 

Not sure if this behavior is intended.

**Comment by SiverDX** [comment]
if a goal is running `canUse` doesn't get ticked (`canContinueToUse` is)

list gets upated in https://github.com/AlexModGuy/Ice_and_Fire/pull/5036/commits/5a383e0e70ef8554a30086e68d7839c99b2cdf73 which fixes this
