### ISSUE TITLE
[Bug]: Not compatible with Biomes O Plenty/Terralith

### ISSUE THREAD

**Issue by EnergizedHopper** [Alex-the-666/Ice_and_Fire#4935]
### What happened?

I was making a mod pack and while making it I ran into a problem with 3 mods not working together Ice and Fire, Terralith, and Biomes O Plenty. Structures and some mobs don't seem to want to spawn in them at all or cave dragons either.

[No_Pain_No_Gain.zip](https://github.com/AlexModGuy/Ice_and_Fire/files/12023228/No_Pain_No_Gain.zip)

### Minecraft Version

1.18

### Ice and Fire version

iceandfire-2.1.12-1.18.2.jar

### Citadel version

citadel-1.11.3-1.18.2.jar

### Relevant log output

```shell
No Crashes
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by EnergizedHopper** [comment]
I had submitted the wrong folder this is the correct one
[Attempt to fix dragons with BOP.zip](https://github.com/AlexModGuy/Ice_and_Fire/files/12023266/Attempt.to.fix.dragons.with.BOP.zip)

**Comment by Appa9** [comment]
Same for me, only amphitere spawn

**Comment by GirottoTommaso** [comment]
Did someone solve this?

**Comment by gummie2022** [comment]
Read this
https://github.com/AlexModGuy/Ice_and_Fire/issues/4920

**Comment by SiverDX** [comment]
See https://github.com/AlexModGuy/Ice_and_Fire/issues/4934#issuecomment-1891763336
