### ISSUE TITLE
[Bug]: Armors are incompatible with the second layer of player skins

### ISSUE THREAD

**Issue by Rocketcat19** [Alex-the-666/Ice_and_Fire#4936]
### What happened?

![skins](https://github.com/AlexModGuy/Ice_and_Fire/assets/113609599/ff6f049b-7f3f-4e68-9edc-527272121ee1)
like this

### Minecraft Version

1.18

### Ice and Fire version

iceandfire-2.1.12-1.18.2

### Citadel version

citadel-1.11.3-1.18.2

### Relevant log output

_sorry but there's no log_

### Other Information

- [ ] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by Thombias** [comment]
Really hoping for this to get fixed in the next and i believe likely last update for 1.18.2. (Now that there's a WIP 1.20.1 version of the mod.) I am stuck on 1.18.2 for my modpack due to important mods not being yet available for newer versions.

**Comment by TheBv** [comment]
fixed with 4768ff611fb5b124bd0d78d6135aef040256888e

**Comment by SammieJay** [comment]
> fixed with [4768ff6](https://github.com/AlexModGuy/Ice_and_Fire/commit/4768ff611fb5b124bd0d78d6135aef040256888e)

W dev
