### ISSUE TITLE
asset "borrowing"

### ISSUE THREAD

**Issue by Azarath20047** [Alex-the-666/Ice_and_Fire#4940]
hey, thought i should let you know that since your model files are made with .tbl format, someone is able to steal them if bcuz blockbench can import tbl files. ik i shouldnt know this, but i like to look through git repos for fun, and found this. if yall already know about this, i apologize for bringing it up again. if you didnt, then i have a small question. would i be able to download some of the mob files so i can mess with them in my free time? i promise not to use them in anything that will be published, unless you say it is allowed.

-Azarath

**Comment by TheBv** [comment]
This is an inherent issue with all open source code or I guess with everything people can download.
The textures and the likes are exempt from the LGPL license the code is being distributed with and hence fall under the copyright of their creators. Using any assets and the likes without explicit permission is therefor illegal. (Similar to how you can't just use the youtube logo and say it's yours and such) 
I'll make sure that this is more apparent on the github page and a later date.
