### ISSUE TITLE
[Bug]:  Dragon Stats dont have a limit

### ISSUE THREAD

**Issue by Daniel190403** [Alex-the-666/Ice_and_Fire#4952]
### What happened?

Dragons Stats grow withoit a limit (Movementspeed, Health, Meele attack damage, Armor). 
![20230811_124737](https://github.com/AlexModGuy/Ice_and_Fire/assets/90551683/927c5ae8-e27e-4dda-b6d3-ff07d111d6f1)

### Minecraft Version

1.18

### Ice and Fire version

2.1.12

### Citadel version

1.11.3

### Other Information

- [X] I am using other mods besides Ice and Fire
- [ ] I have attached a log file from the session that I have experienced this issue

**Comment by Daniel190403** [comment]
.

**Comment by TheBv** [comment]
fixed with a2335aec4b2bed7dff4e3eaa553f04d07e454d65
