### ISSUE TITLE
Dragonsteel armor and tools config do not work

### ISSUE THREAD

**Issue by Fiiter910** [Alex-the-666/Ice_and_Fire#4958]
I was changing the value of the tools and armor like the damage and protection they have and we I launch the game the values are on default but on the config files are changed idk why this happend.
Thanks.
![image](https://github.com/AlexModGuy/Ice_and_Fire/assets/81747601/f6a81dfd-cdc1-4fe5-89a2-935381bb6fb5)
![image](https://github.com/AlexModGuy/Ice_and_Fire/assets/81747601/fb5bbfb7-bf28-4d9f-b133-88807730c7c7)

**Comment by TheBv** [comment]
What version of the mod are you using?
