### ISSUE TITLE
Configering Spawn rate- 1.18.2

### ISSUE THREAD

**Issue by woobearrrrrrrr** [Alex-the-666/Ice_and_Fire#4961]
### What happened?

I was wanting to config the spawn rate of dragons to be lower because it was causing a lot of issues in my server. But when I went to do so I couldn't find anything in the config file that would change the spawn rate. 
Went looking for someone who might know but couldn't find anyone either.

### Minecraft Version

1.18

### Ice and Fire version

iceandfire-2.1.12-1.18.2

### Citadel version

citadel-1.11.3-1.18.2

### Relevant log output

```shell
[Generation.Dragon]
		#Whether to generate dragon skeletons or not
		"Generate Dragon Skeletons" = true
		#1 out of this number chance per chunk for generation
		#Range: 1 ~ 10000
		"Generate Dragon Skeleton Chance" = 300
		#Whether to generate dragon caves or not
		"Generate Dragon Caves" = true
		#1 out of this number chance per chunk for generation
		#Range: 1 ~ 10000
		"Generate Dragon Cave Chance" = 180
		#Whether to generate dragon roosts or not
		"Generate Dragon Roosts" = true
		#1 out of this number chance per chunk for generation
		#Range: 1 ~ 10000
		"Generate Dragon Roost Chance" = 360
		#1 out of this number chance per block that gold will generate in dragon lairs.
		#Range: 1 ~ 10000
		"Dragon Den Gold Amount" = 4
		#Ratio of Stone(this number) to Ores in Dragon Caves
		#Range: 1 ~ 10000
		"Dragon Cave Ore Ratio" = 45
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by Teddy-Maz** [comment]
Dragons don't spawn without an associated Roost or Cave, so tweaking the spawn rates of those structures will affect how many dragons you do/don't see. Are you using any worldgen mods that add biomes? There are some issues with certain mods not already being registered by Ice and Fire that might require going back and having the specific biomes be tagged in individual configs for all the dragon roosts/caves, and it seems that the world height increases of Caves and Cliffs might be affecting the spawns of certain other structures (not any dragon-related from what I'm aware).

**Comment by DrAzazelHirschAlkiren** [comment]
Everytime I edit the configure file it resets with the next world gen (after the edit so world gen isnt actually affected) Can you help? I cant find a way to make it accept the configure change.
