### ISSUE TITLE
[Bug]: 1.20.1 Alpha Cyclops, AI

### ISSUE THREAD

**Issue by DonorKrovi** [Alex-the-666/Ice_and_Fire#4970]
### What happened?

![image](https://github.com/AlexModGuy/Ice_and_Fire/assets/60231586/47ad7e24-0b00-48dd-9d25-3f38463f6f00)
![image](https://github.com/AlexModGuy/Ice_and_Fire/assets/60231586/afe60556-df5d-45f4-b5c5-1594d967f4b8)

Cycklops perform their spawn in the air, while freezing to death and unable to continue moving

### Minecraft Version

1.20

### Ice and Fire version

iceandfire-2.1.13-1.20.1+build.2.1.13-alpha-1

### Citadel version

2-5-4

### Other Information

- [ ] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by DonorKrovi** [comment]
![image](https://github.com/AlexModGuy/Ice_and_Fire/assets/60231586/fac1e0df-7862-4851-aec6-0e2cc1946df9)
and this

**Comment by TheBv** [comment]
fixed by 8719f42d28a2a523f58af879ff77d7a6566ec72e
