### ISSUE TITLE
[Bug]: dragons not spawning in my world

### ISSUE THREAD

**Issue by yoav156756** [Alex-the-666/Ice_and_Fire#4975]
### What happened?

I created a minecraft world like a week ago and I explored A LOT but no matter how much I search (even with creative and spectator mode) I cant find even a single dragon roost\layer or any dragon at all!

### Minecraft Version

1.18

### Ice and Fire version

iceandfire-2.1.12-1.18.2.jar

### Citadel version

citadel-1.11.3-1.18.2.jar

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
There should always be a `latest.log`/`debug.log` file that gets created. If you could provide that that would already help.
It's usually in your minecraft install directory under the folder `/config`.
Without it it's impossible for me to do anything.
