### ISSUE TITLE
[Bug]: Uncapped dragon stats

### ISSUE THREAD

**Issue by platypushasnohat** [Alex-the-666/Ice_and_Fire#4976]
### What happened?

Tamed dragon stats go beyond their stage 5 limits with each extra day lived or when dragon meal is used.

![2023-10-16_14 22 09](https://github.com/AlexModGuy/Ice_and_Fire/assets/58866828/2a64a4e8-2b55-44e4-95f6-f296044f9e12)
![2023-10-16_14 22 26](https://github.com/AlexModGuy/Ice_and_Fire/assets/58866828/1884e9a6-9b9a-48ae-aa4a-3c6dc9da5ed7)
![2023-10-16_14 22 29](https://github.com/AlexModGuy/Ice_and_Fire/assets/58866828/4db171b3-75e8-4308-ba8b-6ed065c72936)

[debug.log](https://github.com/AlexModGuy/Ice_and_Fire/files/12921535/debug.log)

[latest.log](https://github.com/AlexModGuy/Ice_and_Fire/files/12921540/latest.log)

### Minecraft Version

1.20.1

### Ice and Fire version

iceandfire-2.1.13-1.20.1+build.2.1.13-alpha-1

### Citadel version

citadel-2.4.5-1.20.1

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by daughter-patch** [comment]
FYI, This issue is observed also in iceandfire-2.1.12-1.18.2.

**Comment by TheBv** [comment]
Fixed with 03ef154edccdba655ec79b2be01ed2b60851e7f7
I'll try backport to earlier versions too
