### ISSUE TITLE
[Bug]: Any dragon that shows up freezes game. 

### ISSUE THREAD

**Issue by CephalonAxii** [Alex-the-666/Ice_and_Fire#4977]
### What happened?

As the title says, any dragons from ice and fire that load in my world, cause the world to freeze. Every other mob, including the dragon stops moving. When I try to go back to the main menu, it stays frozen to the point the only way I can unfreeze it is by restarting my computer. Because of this, I can't access a Crash log. 

### Minecraft Version

1.18

### Ice and Fire version

iceandfire-2.1.12-1.18.2

### Citadel version

citadel-1.11.3-1.18.2

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
There should always be a `latest.log`/`debug.log` file that gets created. If you could provide that that would already help.
It's usually in your minecraft install directory under the folder `/config`.
Without it it's impossible for me to do anything.

**Comment by CephalonAxii** [comment]
Okay, hold on. I think I found it. Because I'm using a Modpack, it was a tad different. But I found this in the Logs Folder.

**Comment by CephalonAxii** [comment]
[latest.log](https://github.com/AlexModGuy/Ice_and_Fire/files/12923264/latest.log)

**Comment by CephalonAxii** [comment]
Okay, nevermind. I figured it out. I painstakingly loaded the game with Ice and Fire with one mod at a time, loading and closing, loading and closing, until I figured out what was what. 
But hey, spread the word on how Dimentional-Threading-Reforged does not work with Ice and Fire.
