### ISSUE TITLE
[Bug]: Cannot Load World with Alpha Build #2

### ISSUE THREAD

**Issue by SuperStefan97** [Alex-the-666/Ice_and_Fire#4978]
### What happened?

Hi! Again, thanks again for taking into account our input on the game. I have seen how you almost fixed all the bugs found before.
In the same world I did the tests for the last bug report, I tried to enter with the new alpha 2 build. The game does not crash and seems to load properly, but when entering a world, the square that shows the world loading (the one with different squares inside generating with a % thing) won't show, it doesn't freezes nor it crashes... but doesn't either do anything else. 

I also add the latest log, and the crash report. In one of the last lines I read (as I know nothing of coding) something about the mode trying to generate a structure (?) I don't know, but I hope this throws a light.

Again, thanks for all
[latest.log](https://github.com/AlexModGuy/Ice_and_Fire/files/12923802/latest.log)

[crash-2023-10-16_20.53.17-server.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/12923812/crash-2023-10-16_20.53.17-server.txt)

### Minecraft Version

1.20.1

### Ice and Fire version

1.20.1 Alpha 2

### Citadel version

citadel-2.4.4-1.20.1

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by GizmoTheMoonPig** [comment]
looks like BV forgot to run datagen after adding the village house processor, so it cant find it as it doesnt exist

**Comment by TheBv** [comment]
Urgh I just forgot to commit it. I'll fix it tonight. :|
