### ISSUE TITLE
[Bug]: dragons and other mobs not spawning (1.20.1 alpha)

### ISSUE THREAD

**Issue by Hurricane-Lordus** [Alex-the-666/Ice_and_Fire#4980]
### What happened?

I'm trying to run the most recent ice and fire alpha with a modpack and for some reason, dragons and other certain mobs do not spawn at all. in this world i tried spawning fire dragons multiple times but nothing happens. I can spawn some of the dread mobs but nothing else
[latest.log](https://github.com/AlexModGuy/Ice_and_Fire/files/12966172/latest.log)

### Minecraft Version

1.20.1

### Ice and Fire version

Alpha Release 2.1.13-alpha-3-2.1.13-alpha-3

### Citadel version

Citadel 2.4.4-1.20.1

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
fixed with b85c983c7c351e2e5850cc4519f808c3e13791c7
