### ISSUE TITLE
[Bug]: Cyclops crash

### ISSUE THREAD

**Issue by platypushasnohat** [Alex-the-666/Ice_and_Fire#4981]
### What happened?

Cyclops crash the game when spawned or when generating.
[crash-2023-10-17_16.15.17-server.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/12966446/crash-2023-10-17_16.15.17-server.txt)

### Minecraft Version

1.20.1

### Ice and Fire version

iceandfire-2.1.13-1.20.1+build.2.1.13-alpha-3

### Citadel version

citadel-2.4.5-1.20.1

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
fixed with c4bb2e122418d4e405b215324ff977a886200090
