### ISSUE TITLE
There is no ice and fire mob spawning

### ISSUE THREAD

**Issue by aitrilmenta** [Alex-the-666/Ice_and_Fire#4985]
### What happened?

I've been since alpha 1 exploring and exploring different worlds, with or without world generation mods, and it didn't spawn any ice and fire mob. I explored desserts, snow biomes, oceans... but nothing. The only place were i found something was underground, but they were just the 4 and 5 class dragons in their nests.

### Minecraft Version

1.20.1

### Ice and Fire version

2.1.13 alpha 1-4

### Citadel version

2.4.5

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Can you provide the log files of your sessions. These exists in your minecraft install folder under the `/logs/` folder. Ideally the file `debug.log` or `latest.log` would be of relevance.
