### ISSUE TITLE
[Bug]: Alpha 4. Fire dragon spam console error

### ISSUE THREAD

**Issue by DonorKrovi** [Alex-the-666/Ice_and_Fire#4988]
### What happened?

I spawned a few dragons of different ages, and then I saw that the console just flew away with those dragons

### Minecraft Version

1.20.1

### Ice and Fire version

alpha-4

### Citadel version

citadel-2.4.5-1.20.1

### Relevant log output

```shell
https://mcpaste.io/ef6b792ff6efa8ee
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
fixed with 7c605d218d32828c4d8709c7b7b36b326d662a03
