### ISSUE TITLE
Missing mobs and items

### ISSUE THREAD

**Issue by Magikaprfainted** [Alex-the-666/Ice_and_Fire#499]
everything is working great except it looks like im missing some of the trial mobs (mermaids, trolls, ect) im also missing the dragon mount armor sets, so i can mount my dragons i just cant really make them do anything but walk around on them. would a reinstall help or am i just missing some data?

**Comment by GundunUkan** [comment]
Those mobs aren't implemented yet, the current mobs are the following:
Fire Dragon
Ice Dragon
Hippogryph
Pixies
Cyclops
Gorgon
Snow Villager
The next update will add sirens, hippocampi and maybe death worms. 

About the dragons, did you edit your controls? If you have other mods installed there's a big chance that some of the dragon control keys are gonna be blocked. By default the "fly up" key is spacebar, I don't remember what the other where.

**Comment by TheProtectedVoid** [comment]
GundunUkan is right, you need change the controls and those mobs that you mentioned will be added in a future updates.

**Comment by Magikaprfainted** [comment]
Oh ok cool, i got it figured out, the creative mode was hiding half of the mods items from me and i just didnt see the extra tab to get to them. All is well, thanks guys
