### ISSUE TITLE
[Bug]: 1.20.1 Crash on loading world without JEI

### ISSUE THREAD

**Issue by SodiumZH** [Alex-the-666/Ice_and_Fire#4990]
### What happened?

For 1.20.1 a `java.lang.NoClassDefFoundError: mezz/jei/api/recipe/RecipeType` crash occurs if only Citadel and IAF are added. After adding JEI the issue is solved.
[crash-2023-10-22_03.27.12-client.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/13061673/crash-2023-10-22_03.27.12-client.txt)

### Minecraft Version

1.20.1

### Ice and Fire version

2.1.13-alpha.4

### Citadel version

2.4.4

### Other Information

- [ ] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Will be addressed in next release #4982

**Comment by rainysux** [comment]
i built the one that works without jei. It doesnt work in servers but it does work in singleplayer. @TheBv
