### ISSUE TITLE
[Collection]: Ticking entity crash on world load

### ISSUE THREAD

**Issue by TheBv** [Alex-the-666/Ice_and_Fire#4996]
### What happened?

World crashes on load mentioning `"this.owner" is null`
Example log file can be seen as an attachment.
[crash-2023-10-23_21.35.58-server.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/13127889/crash-2023-10-23_21.35.58-server.txt)

I myself am not able to replicate this issue on a server or client with the forge(or neo forge) version 41.2.1
If anyone can provide their log files and maybe a 100% working setup to replicate the issue it'd be greatly appreciated!

### Minecraft Version

1.20.1

### Ice and Fire version

2.1.13-alpha-5

### Citadel version

2.4.5

### Relevant log output

```shell
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.LivingEntity.m_9236_()" because "this.owner" is null
```

### Other Information

- [ ] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by DaddyP1G** [comment]
[crash-2023-10-24_18.22.39-server.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/13128255/crash-2023-10-24_18.22.39-server.txt)
[latest.log](https://github.com/AlexModGuy/Ice_and_Fire/files/13128256/latest.log)


see if these help-  Alpha 5 as well

**Comment by Roxxors1987** [comment]
[crash-2023-10-24_19.11.07-server.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/13132065/crash-2023-10-24_19.11.07-server.txt)

From the latest Alpha 5

Modlist is Apotheosis 1.20.1-7.0.5
ApothicAttributes-1.20.1-1.1.4
citadel-2.4.5-1.20.1
jei-1.20.1-forge-15.2.0.27
Patchouli-1.20.1-81-FORGE
Placebo-1.20.1-8.3.7

World seed was from a world from my recent report; -5455514710601756564

**Comment by TheBv** [comment]
Alright thanks for the input! 
I found the common denominator and it seems to be `Apothic Attributes (AttributesLib)`
I'll look into it in the following days :)

Related Issue: https://github.com/Shadows-of-Fire/Apothic-Attributes/issues/6
