### ISSUE TITLE
[Bug]: Crash while / right after new world is created

### ISSUE THREAD

**Issue by CatAndPaste** [Alex-the-666/Ice_and_Fire#4999]
### What happened?

After adding latest Alpha version of Ice & Fire, the game would crash on world creation (with out-of-memory error) or right after world is created.

### Minecraft Version

1.20.1 (NeoForge 47.1.79)

### Ice and Fire version

iceandfire-2.1.13-1.20.1+build.2.1.13-alpha-5

### Citadel version

citadel-2.4.7-1.20.1

### Relevant log output

Crash log 1 (after world got created, I spawned and could play for 10-15 seconds): https://pastebin.com/DNSsvPEj

Crash log 2 (after world got created, I could play for quite some time, located one of the Ice & Fire structures, tried to teleport to it and then game crashed): https://pastebin.com/Gj8ZAD5G

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
fixed with b85c983c7c351e2e5850cc4519f808c3e13791c7
