### ISSUE TITLE
Laggin' Dragons [AI upgrades?]

### ISSUE THREAD

**Issue by JayZX535** [Alex-the-666/Ice_and_Fire#50]
This is also not a "bug" so much as it is a suggestion, but the first dragon I found MAJORLY lagged my game.  It almost immediately started blasting fire and dove into the ground, creating a massive canyon.
I have a beefy computer.  32 RAM, 6-core I7 processor, and a powerful graphics card (I had 4 gigs of RAM allotted to MC- I just bumped it up to 8 to see if this helps, but many people have only 8-16 gigs in their computer total, so this might not always be possible).  Just this one dragon flying through the ground caused moderate lag.
This is the canyon the dragon made:
https://i37.servimg.com/u/f37/19/01/25/95/dragon10.jpg
As you can see, it is very deep and very long.  Perhaps there could be a way to keep dragons from flying through and smashing the ground so much.  It would also make it more realistic, since I don't think dragons would normally fly through the ground that much, haha!

**Comment by Alex-the-666** [comment]
Turn your particles off, it's the lag from the block break particle the dragons make ;)
