### ISSUE TITLE
Error when 'loading chunk' in server.

### ISSUE THREAD

**Issue by SapphireDragons1** [Alex-the-666/Ice_and_Fire#500]
I went exploring in my server, and encountered an Emerald Dragon, and turned on survival to try and defeat it, (I failed) and it used the attack where it picks you up and shakes you until you die. After this, I re-spawned, there was a huge amount of lag. I checked the server's 'code' or 'log' (whatever), and it says there that "Ice and Fire loaded a new chunk (-5, 29  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config." I figured it was something worth mentioning, I'm not sure if resetting the server will stop the lag, though...

**Comment by AlexModGuy** [comment]
cascading world gen lag should be curtailed in 1.4.0.
