### ISSUE TITLE
[Bug]: Сrash after entering the world

### ISSUE THREAD

**Issue by Sova626** [Alex-the-666/Ice_and_Fire#5000]
### What happened?

Troll crash the game when spawned or when generating.
[crash-2023-10-25_17.19.24-server.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/13171245/crash-2023-10-25_17.19.24-server.txt)
[latest.log](https://github.com/AlexModGuy/Ice_and_Fire/files/13171272/latest.log)

### Minecraft Version

1.20.1

### Ice and Fire version

iceandfire-2.1.13-1.20.1+build.2.1.13-alpha-5

### Citadel version

citadel-2.4.7-1.20.1

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
fixed with b85c983c7c351e2e5850cc4519f808c3e13791c7
