### ISSUE TITLE
Dragons and Serpents spawn with 20 hp

### ISSUE THREAD

**Issue by Silk-Hood** [Alex-the-666/Ice_and_Fire#5001]
### What happened?

Dragons and sea serpents spawn with 20 hp

### Minecraft Version

1.20.1

### Ice and Fire version

 iceandfire-2.1.13-1.20.1+build.2.1.13-alpha-5.jar

### Citadel version

citadel-2.4.7-1.20.1.jar

### Relevant log output
https://paste.ee/p/ihUyC
_No response_

### Other Information

- [X] I am using other mods besides Ice and Fire
- [x] I have attached a log file from the session that I have experienced this issue

**Comment by ItzAlo-idk** [comment]
Same issue encountered here, naturally spawning dragons only have 20hp.
On top of that, the dragon's death animation does not play, it just stands with eyes closed.

**Comment by Silk-Hood** [comment]
Oh yeah i've also seen that

**Comment by DonorKrovi** [comment]
use last version

**Comment by DonorKrovi** [comment]
![image](https://github.com/AlexModGuy/Ice_and_Fire/assets/60231586/0373989f-ce74-49d2-9520-251f1b3a0e13)
Bruh, ok

**Comment by TheBv** [comment]
Are you using a custom server/launcher? (e.g magma)
I see your logs mentioning MultiMC but I think it still uses just the default forge implementation?
If not please let me know if there's anything custom going on.
