### ISSUE TITLE
Entity being ticked

### ISSUE THREAD

**Issue by Rasszusz221** [Alex-the-666/Ice_and_Fire#5002]
[
[crash-2023-10-26_22.29.26-server.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/13182711/crash-2023-10-26_22.29.26-server.txt)
](url)

**Comment by SiverDX** [comment]
don't recommend using https://www.curseforge.com/minecraft/mc-mods/no-see-no-tick

if you need such a mod use https://www.curseforge.com/minecraft/mc-mods/doespotatotick
due to it's wrapping of the crash it's not clear as to what the problem is
