### ISSUE TITLE
[Bug]: Bestiary consumes Manuscripts but doesn't unlock new entries in MP

### ISSUE THREAD

**Issue by Apotrox** [Alex-the-666/Ice_and_Fire#5007]
### What happened?

As the title states, the Bestiary consumes the Manuscripts when trying to unlock new entries, but no new entries get unlocked. No sound effects are being played and the selection isn't getting rerolled either. This happens specifically in multiplayer, in a singleplayer world it happens exactly as one would expect. 

Modlist (serverside): Alex's Caves, Alex's Mobs, badpackets, balm, citadel, cloudstorage, collective, corpse, cupboard, when dungeons arise, ferritecore, iceandfire, inventory sorter, jei, konkrete, map atlases, modernfix, moonlight, mousetweaks, radium, right click harvest, servercore, smoothchunk, sophisticated backpacks, sophisticated core, spark, starlight, supplementaries, terralith, treeharvester, waystones

Modlist (clientside): Alex's Caves, Alex's Mobs, Appleskin, badpackets, balm, citadel, cloudstorage, collective, corpse, cupboard, when dungeons arise, ferritecore, iceandfire, inventory sorter, jei, just enough resources, justzoom, konkrete, map atlases, modernfix, moonlight, mousetweaks, oculus, rubidium extras, rubidium, right click harvest, smoothchunk, sophisticated backpacks, sophisticated core, soundphysics, starlight, supplementaries, terralith, treeharvester, waystones, wthit
here the archives of yesterday's logs
[debug-2.log.gz](https://github.com/AlexModGuy/Ice_and_Fire/files/13229918/debug-2.log.gz)
[2023-10-31-2.log.gz](https://github.com/AlexModGuy/Ice_and_Fire/files/13229928/2023-10-31-2.log.gz)

### Minecraft Version

1.20.1

### Ice and Fire version

2.1.13-alpha-5

### Citadel version

2.4.7

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
fixed with 258f2a2317eca9ef868baeec66b785ad86dcb83a
