### ISSUE TITLE
Hippogryph falling out of the world[Bug]: 

### ISSUE THREAD

**Issue by Ale20k4** [Alex-the-666/Ice_and_Fire#5008]
### What happened?

Basically I was flying around with my hippogryph, then I landed and pressed "Shift" to dismount. The hippogryph sank underground and after a few seconds the following message appeared in chat: "Hippogryph fell out of the world".

The issue can be replicated simply by dismounting the hippogryph and not moving, this will always cause the hippogryph to fell out of the world. 
Please fix, the issue also happens when Ice and Fire is played alone. 
![image](https://github.com/AlexModGuy/Ice_and_Fire/assets/149807836/2dd5e6b5-a096-49e3-bd44-4436057c70d3)

### Minecraft Version

1.18

### Ice and Fire version

2.1.12

### Citadel version

1.11.3

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by SiverDX** [comment]
caused by setting `noPhysics` to `true`

https://github.com/AlexModGuy/Ice_and_Fire/blob/359f94ea0bfebbf4c1c20230fe1de1e29d7c6e91/src/main/java/com/github/alexthe666/iceandfire/entity/EntityHippogryph.java#L832

**Comment by Ale20k4** [comment]
And I can make it to "true" and it shouldn't be falling anymore?

**Comment by SiverDX** [comment]
it being true is the reason why it happens
i mean thats kinda what you would expect if you disable physics on an entity - it falls/moves through blocks
