### ISSUE TITLE
No structures or creatures spawning 1.20.1 [Bug]: 

### ISSUE THREAD

**Issue by Phyrra1** [Alex-the-666/Ice_and_Fire#5009]
### What happened?

Created several different worlds, and explored them extensively, tried using the Explorer's Compass to find structures as well, but I couldn't find any creatures or structures from Ice and Fire
[2023-11-03-3.log](https://github.com/AlexModGuy/Ice_and_Fire/files/13254402/2023-11-03-3.log)

### Minecraft Version

1.20.1

### Ice and Fire version

2.1.13-alpha-6

### Citadel version

2.4.5

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
You probably still have the old ice and fire config files in your minecraft install folder. Please remove them and see if that resolves the issue.

**Comment by Phyrra1** [comment]
Did that and structures and creatures are spawning now! Still haven't found a dragon yet, but I haven't been searching for one for long

**Comment by Phyrra1** [comment]
Found some dragons above ground and underground, all is working well, thank you!
