### ISSUE TITLE
[Bug]: Method of crashing a server with dragons alpha-6 

### ISSUE THREAD

**Issue by DonorKrovi** [Alex-the-666/Ice_and_Fire#5010]
### What happened?

I will provide you with a video, I will also clarify that the server did not crash due to the fact that my protection from the Neruina mod worked, but the dragon disappeared because it caused a critical problem

https://medal.tv/ru/games/minecraft/clips/1BQt8w7OIWdC3k/d1337p9PFFmq?invite=cr-MSxlR0MsMTI5ODExOTc0LA

Timecode 1:36

### Minecraft Version

1.20.1

### Ice and Fire version

Alpha Release 2.1.13-alpha-6-2.1.13-alpha-6

### Citadel version

citadel-2.4.5-1.20.1

### Relevant log output

```shell
https://mclo.gs/CkOOeDr
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
fixed with 5b1ece08d20a281caa9860b4303ed11b7cbc28f6
