### ISSUE TITLE
[Bug]: Crashing when tremorsaurus from Alex's Caves scares dragon

### ISSUE THREAD

**Issue by UncleSatgat** [Alex-the-666/Ice_and_Fire#5011]
### What happened?

Tremorsaurus roar that scares mobs nearby causes problem on ticking entities and crashes when it had done to dragons

[crash-2023-11-05_03.00.28-client.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/13257398/crash-2023-11-05_03.00.28-client.txt)

### Minecraft Version

1.20.1

### Ice and Fire version

iceandfire-2.1.13-1.20.1+build.2.1.13-alpha-6

### Citadel version

citadel-2.4.7-1.20.1

- [x] I am using other mods besides Ice and Fire
- [x] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
fixed with 7c605d218d32828c4d8709c7b7b36b326d662a03
