### ISSUE TITLE
[Bug]: Config Options Dont Work

### ISSUE THREAD

**Issue by Ieviath4n** [Alex-the-666/Ice_and_Fire#5018]
### What happened?

The in game config option are just greyed out so its inaccessible.

### Minecraft Version

1.20.1

### Ice and Fire version

Alpha-6

### Citadel version

2.4.9

### Other Information

- [ ] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
I don't know what you mean by that. Ice and Fire doesn't show any config values in any kind of UI.

**Comment by Ieviath4n** [comment]
> I don't know what you mean by that. Ice and Fire doesn't show any config values in any kind of UI.

So when you open the menu and go to the mods setting, there you can configure various mods and i thought i remembered being able to do this in previous versions of ice and fire. Its the mods option when you are in game i am referring to. There you can search for and configure your mods.

**Comment by TheBv** [comment]
I'm afraid that hasn't been a feature since at least the 1.16 version.
It is in the back of my mind and might be a feature I implement at some point in the future; not anytime soon though I'm afraid.

**Comment by Ieviath4n** [comment]
Sounds good. Cheers
