### ISSUE TITLE
Siren rocks do not generate below y0

### ISSUE THREAD

**Issue by Aceplante** [Alex-the-666/Ice_and_Fire#5021]
### What happened?

Title. I found a siren rock that only went down to y0, not the ocean floor

![float](https://github.com/AlexModGuy/Ice_and_Fire/assets/101857505/f5aa7529-54b9-4431-a0c8-746834753cbe)
![flaot2](https://github.com/AlexModGuy/Ice_and_Fire/assets/101857505/da24e4dd-d1e6-4073-ba8b-45d7a1e6d6a1)

### Minecraft Version

1.18

### Ice and Fire version

latest

### Citadel version

N/a

### Other Information

- [ ] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by gummie2022** [comment]
it definitely needs to diminish the width of the rock since it takes up too much space which makes it unnatural although that obviously requires skills to fix it entirely

**Comment by Aceplante** [comment]
this actually affects dragon caves too, but I dont remember if that was fixed or not
