### ISSUE TITLE
Question: How to revive dragon?

### ISSUE THREAD

**Issue by vatum20** [Alex-the-666/Ice_and_Fire#5025]
### What happened?

So we are playing on multiplayer and my friend's dragon died. What would be the command to make it alive again, if such command even exist?

### Minecraft Version

1.16(CRASHES ONLY)

### Ice and Fire version

doesn't matter

### Citadel version

doesn't matter

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by DonorKrovi** [comment]
doesn't matter

**Comment by quinnfrost** [comment]
I'll assume you know the basic about commands:
(this is for 1.18, grammar should be similar)

```
/data modify entity <entity_uuid> Health set value 1f
```
```
/data modify entity <entity_uuid> <relevant_tags> set value 0b
```
where:
<entity_uuid> is the uuid of **the dragon**, can be acquired by pointing to its body and [tab].
<relevant_tags> is the NBT tags required to do the resurrection, in this case: `NoAI` and `ModelDead`
There might be strange issue after you've done this.
You'll need cheat enabled on local or op 2+ on servers.

Even better: fork yourself a repo, merge relevant PR and compile yourself version that allows resurrection

**Comment by DrMalpracticewastaken** [comment]
you also need to set DeathProg to 0.0

> I'll assume you know the basic about commands: (this is for 1.18, grammar should be similar)
> 
> ```
> /data modify entity <entity_uuid> Health set value 1f
> ```
> 
> ```
> /data modify entity <entity_uuid> <relevant_tags> set value 0b
> ```
> 
> where: <entity_uuid> is the uuid of **the dragon**, can be acquired by pointing to its body and [tab]. <relevant_tags> is the NBT tags required to do the resurrection, in this case: `NoAI` and `ModelDead` There might be strange issue after you've done this. You'll need cheat enabled on local or op 2+ on servers.
> 
> Even better: fork yourself a repo, merge relevant PR and compile yourself version that allows resurrection
