### ISSUE TITLE
[Bug]: Bestiary

### ISSUE THREAD

**Issue by RLlufee** [Alex-the-666/Ice_and_Fire#5027]
### What happened?

I found an issue: on bestiary lectern, Bestiary can't be upgraded with a manuscript

### Minecraft Version

1.20.1

### Ice and Fire version

Alpha Release 2.1.13-alpha-6-2.1.13-alpha-6

### Citadel version

citadel-2.4.9-1.20.1

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
alpha 7 fixes this
