### ISSUE TITLE
[Bug]: Can't repair dragon scale armor

### ISSUE THREAD

**Issue by DracoKazenare** [Alex-the-666/Ice_and_Fire#5032]
### What happened?

I don't understand why but for some reason, no matter whether I use an anvil, grindstone, regular crafting grid, or smithing table, I can't repair my scale armor. I used scales of a matching color and type, even tried using scales of different colors, and nothing works. If you know why or how to fix it please tell me cuz I'd rather not make a whole new set of armor for zero reasoning.

### Minecraft Version

1.18

### Ice and Fire version

2.1.12-1.18.2

### Citadel version

1.11.3-1.18.2

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by SiverDX** [comment]
also 1.20 issue since https://github.com/AlexModGuy/Ice_and_Fire/blob/1.20/src/main/java/com/github/alexthe666/iceandfire/recipe/IafRecipeRegistry.java is never added to the event bus

lightning dragon bone items also dont set their repair material

fixed in the 1.19.2 port
