### ISSUE TITLE
Cant make dragons to spawn only in nether and twilight forest

### ISSUE THREAD

**Issue by khreen** [Alex-the-666/Ice_and_Fire#5033]
### What happened?

Hi!! I want to make dragons only spawn in  twilight forest dimension or the nether but not in the overworld. how can i make that posible?
because in 1.16.5 there was an option for that in the config file but im in 1.18.2 and there is not any similar option

### Minecraft Version

1.18

### Ice and Fire version

2.1.12

### Citadel version

1.11.3

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by Nycto97** [comment]
Maybe [In Control!](https://www.curseforge.com/minecraft/mc-mods/in-control) by [McJty](https://www.curseforge.com/members/mcjty/projects) can help you with this.

**Comment by TheBv** [comment]
You need to now do it with the individual config files I'm afraid.
Basically in `config/iceandfire` you'll find a bunch of files. What you will mostly want to do is replace everything related to "minecraft:is_overworld" to "twilightforest:in_twilight_forest".

**Comment by Xplodin** [comment]
> You need to now do it with the individual config files I'm afraid. Basically in `config/iceandfire` you'll find a bunch of files. What you will mostly want to do is replace everything related to "minecraft:is_overworld" to "twilightforest:in_twilight_forest".

sorry to bump, how would I get this to work to work in ways that allows dragons in datapack dimensions? example: teb:the_evergreen_beans is dimension
