### ISSUE TITLE
Question: How to change dragonsteel parameters 1.18.2

### ISSUE THREAD

**Issue by Kronvill** [Alex-the-666/Ice_and_Fire#5034]
on 1.16.5 and below it is clear how to do this, but how to do this on 18.2? I didn't find this parameter in the configs, although maybe I'm blind. I mean how to change weapon damage, armor protection level, durability, etc.

**Comment by TheBv** [comment]
They all still exist in the iceandfire-common.toml file. Nothing has changed. Around Line 360.
