### ISSUE TITLE
[Bug]: copper ingot

### ISSUE THREAD

**Issue by JoseSobrero** [Alex-the-666/Ice_and_Fire#5037]
### What happened?

Good afternoon, I have a personal world with the mod for version 1.18.2 of Minecraft and I have a problem. I converted Minecraft's common copper into blocks and when I wanted to convert it back to ingots, it transformed them into copper ingots from the mod. for what is this?

### Minecraft Version

1.18

### Ice and Fire version

2.1.12

### Citadel version

1.11.3

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
I've fixed this in the 1.20 version and will consider backporting it when I'm done with it.
