### ISSUE TITLE
Dragon disappers upon death

### ISSUE THREAD

**Issue by zezreli** [Alex-the-666/Ice_and_Fire#505]
Hey, so I have the newest version of ice and fire and when I kill the dragons I don't get any loot and the dragons body disappers directly after death, as soon as the killing blow is dealt its gone no matter what

**Comment by EvilDylan** [comment]
Question: If you reload the game, or go away for a while and come back, does the dragon reappear?

I had this issue and found it to be a conflict with Morph Mod, but may have been wrong in my conclusion.

**Comment by zezreli** [comment]
how you mean by reload? by the F3 + A does not work but leaving the chunk and come back works 

ah okey then i will remove that mod don't use it that much anyway

**Comment by AlexModGuy** [comment]
issue with morph
