### ISSUE TITLE
[Bug]: Doenst start up with Sinytra Connector

### ISSUE THREAD

**Issue by Kevenpvp** [Alex-the-666/Ice_and_Fire#5051]
### What happened?

Just use with sinytra connector, game wont even start up, doenst have crahs reports, so i got full debug log https://gist.github.com/Kevenpvp/1852223ad1ae2614a577c9cca56a6fb2

### Minecraft Version

1.20.1

### Ice and Fire version

Development Build 2023-12-28

### Citadel version

citadel-2.4.9-1.20.1

### Relevant log output

```shell
https://gist.github.com/Kevenpvp/1852223ad1ae2614a577c9cca56a6fb2
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by lSherozl** [comment]
sinytra connector is to allow the porting of fabric mods to be used on forge. Ice and Fire is already a forge mod, so I'm confused by this post? You cant use connector as far as I know to make forge mods work on fabric

**Comment by lSherozl** [comment]
If there is a problem using connector and ice and fire, post on the connector github too

**Comment by TheBv** [comment]
https://github.com/Sinytra/Connector/issues/660

**Comment by TheBv** [comment]
Should be fixed now with the latest snapshot 
https://github.com/AlexModGuy/Ice_and_Fire/releases/tag/1.20-latest-snapshot

Ideally we keep the issue up on the connector github though because it's something they'll have to deal with in the future.
