### ISSUE TITLE
[Bug]: Ice dragon eggs not hatching [1.19.2-2.1.13build.alpha-2]

### ISSUE THREAD

**Issue by CapiYT** [Alex-the-666/Ice_and_Fire#5052]
### What happened?

The ice dragon eggs does not hatch, I have waited an hour and a half and the egg does not seam to want to hatch it is red and spinning in the ice but nothing more.

### Minecraft Version

1.19

### Ice and Fire version

2.1.13build.alpha-2

### Citadel version

2.1.4

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by Limbollx** [comment]
same issue for me...
