### ISSUE TITLE
[Bug]: Latest Snapshot (build 12-28) instantly crashes server on startup 1.20.1

### ISSUE THREAD

**Issue by ComeMyChild** [Alex-the-666/Ice_and_Fire#5053]
### What happened?

As the title suggests, updating from a previous version of the I/f Snapshot (alpha 7) instantly crashes the server. Attached is the latest.log, though I do not believe it could be much use as it essentially crashes instantly. 
[latest.log](https://github.com/AlexModGuy/Ice_and_Fire/files/13790045/latest.log)

### Minecraft Version

1.20.1

### Ice and Fire version

Snapshot Build 12-28

### Citadel version

2.4.9

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
If possible try out the other jar I've uploaded to the release and let me know if that fixes your issue.
https://github.com/AlexModGuy/Ice_and_Fire/releases/tag/1.20-latest-snapshot
