### ISSUE TITLE
[Bug]: Weird Generation with Dragon Roost - 1.18.2

### ISSUE THREAD

**Issue by wabeb325** [Alex-the-666/Ice_and_Fire#5057]
### What happened?

When you explore new chunks with the last beta of 1.18.2, all the dragon roost gets spawned like this:

![image](https://github.com/AlexModGuy/Ice_and_Fire/assets/144356307/82e69db5-671b-4edc-a754-314f5e32144b)
![image](https://github.com/AlexModGuy/Ice_and_Fire/assets/144356307/e10ee818-e644-4e3b-950c-ba658758db28)

Btw, I'm using Terralith and I don't know if this happes in other scenarios.

### Minecraft Version

1.18

### Ice and Fire version

Beta Release 1.18.2-2.1.13-beta-2

### Citadel version

citadel-1.11.3-1.18.2

### Relevant log output

```shell
No crash was experienced, so no log, is just world generation.
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [x] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
I can't seem to replicate this.
Do you have any other worldgen/optimisation mods installed?
Or maybe running a non vanilla server like magma?

**Comment by wabeb325** [comment]
No other world generation mods except Terralith, Abnormal mods and BOP, and I was running this in my computer (client side) but I already tested this in a forge server and it happens as well, I'm using embeddium, ferritecore, lazyDFU, modernfix, memory leak fix and Ksyxis as performance mods. I'm going to try if it works without them.

**Comment by TheBv** [comment]
Yeah otherwise if you have a seed and coordinates that'd be great :)

**Comment by wabeb325** [comment]
I already tested the new version and somehow this error was hopefully fixed.
