### ISSUE TITLE
[Bug]: Game keeps crashing when I try to use the mod with BiomesOPlenty and Alex's Mobs

### ISSUE THREAD

**Issue by idkwhattoput12** [Alex-the-666/Ice_and_Fire#5058]
### What happened?

When I add Ice and Fire Dragons into my mods folder that contains 2 other big mods (BiomesOPlenty and Alex's Mobs) it always crashes but when i take ice and fire dragons out it works just fine 
![image](https://github.com/AlexModGuy/Ice_and_Fire/assets/155333659/5461c3aa-7fbc-46cd-bcc0-2f7087f1a485)
 

### Minecraft Version

1.17

### Ice and Fire version

iceandfire-2.1.12-1.17.1 

### Citadel version

citadel-1.9.5-1.17.1

### Relevant log output

```shell
it doesn't give me an output log. Upon loading up the game it just crashes and says exit code 1
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
There should still be a crash log created.
You can find it on your minecraft install location under `crash-reports`.
And if there's nothing there in the `logs` folder there should be a `latest.log` as well as a `debug.log` that should have all the relevant information.
