### ISSUE TITLE
Pet Dragon dissapears after save and exit

### ISSUE THREAD

**Issue by ORainKnightO** [Alex-the-666/Ice_and_Fire#506]
I've tried it on peaceful and on easy and it's really starting to make me frustrated. I had to go into creative because of this glitch to get another dragon because they keep disappearing. I just hatched a stage one dragon, fed it, put armor on it, named it, then after about 2 minutes, I saved and exited the world. When I came back the dragon was gone. No noise to indicate it was anywhere near me either. They were not set to wander and it didn't matter if it was sitting on my shoulder or not. Please fix this.
(Running the 1.12.2 version of Ice and Fire)

**Comment by ORainKnightO** [comment]
I might have found a small work around using the dragon horn to hold them, save and exit, go back to the world, then let them out.
If this is how I am meant to save, I highly recommend fixing it. I can only imagine how many people save and quit like normal then come back to have their dragon missing.

**Comment by AlexModGuy** [comment]
tested in 1.4.0, could not reproduce

try keeping your dragon either inside or outside, in a smaller place if you keep loosing it.
