### ISSUE TITLE
[Bug]: Dragon eggs do not hatch

### ISSUE THREAD

**Issue by f4r4ree** [Alex-the-666/Ice_and_Fire#5066]
### What happened?

I've put all the right eggs in the right places to hatch, and I've waited over half an hour on different worlds but the eggs dont seem to hatch.

### Minecraft Version

1.20.1

### Ice and Fire version

1.20.1 BETA

### Citadel version

1.20.1

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
fixed with 03243f3f7529acbf1195a5de01d5c824c01c5d36
