### ISSUE TITLE
[1.3.1-1.12.2] No Class Defined - Dedicated Server Crash

### ISSUE THREAD

**Issue by kreezxil** [Alex-the-666/Ice_and_Fire#507]
Seems to happen while a dragon is breaking a block. I have the config set to prevent dragons from breaking blocks tho.

server crash report: https://gist.github.com/b22bc048515d2ca159c8fc33bd4923da

server log from the time it happend: https://gist.github.com/8b5c720dd30936893c7c79f22a9e6282

**Comment by AlexModGuy** [comment]
Well, Im not able to replicate it but I did disable dragons breaking blocks when not allowed to.
