### ISSUE TITLE
[Bug]: Deepslate silver ore unmineable

### ISSUE THREAD

**Issue by mxnmnm** [Alex-the-666/Ice_and_Fire#5072]
### What happened?

You cannot mine deepslate silver ore with any pickaxe because it has no mining level (the one probe was just added for visual reference and this bug does happen with ice and fire installed alone) 
![2024-01-08_23 18 27](https://github.com/AlexModGuy/Ice_and_Fire/assets/8508976/834c9ade-99dc-4534-b46a-1b4cb5639e86)

### Minecraft Version

1.20.1

### Ice and Fire version

iceandfire-2.1.13-1.20.1+build.beta-1

### Citadel version

citadel-2.4.9-1.20.1

### Other Information

- [ ] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by SiverDX** [comment]
entry for deepslate variant is missing in https://github.com/AlexModGuy/Ice_and_Fire/blob/1.20/src/main/resources/data/minecraft/tags/blocks/mineable/pickaxe.json

you can temporarily fix it for yourself with a datapack by adding the block to that tag
