### ISSUE TITLE
Silver ore does not match vanilla in beta

### ISSUE THREAD

**Issue by mxnmnm** [Alex-the-666/Ice_and_Fire#5073]
Silver ore should really drop in item form just like all of the other ores in the game for consistency purposes.

**Comment by ffuentesm** [comment]
Yeah, just need to wait to add the Ore item before that happens.
But a quick fic could be that if can just use other mod silver ore to drop it, just need to detect the forge:raw_materials/silver, and have it drop that instead.
![image](https://github.com/AlexModGuy/Ice_and_Fire/assets/44974827/1b90a50d-a355-44bf-83a3-b6efbf5c2d88)

You can just make a datapack to temporarily change the drop
Here I used IE raw silver as the replacement
`{
  "type": "minecraft:block",
  "pools": [
    {
      "name": "silver_ore",
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "immersiveengineering:raw_silver"
        }
      ],
      "conditions": [
        {
          "condition": "minecraft:survives_explosion"
        }
      ]
    }
  ]
}`

**Comment by mxnmnm** [comment]
That assumes I'm using another mod that has silver, which I'm not and I really don't want to add a mod just to add silver. Guess I'll just wait for the fix

**Comment by rafaelkai** [comment]
The ore block itself needs a redesing too to match vanilla ores imo. Is there any way to make a datapack so the silver ore block form ice and fire doesn't spawn in the world?

**Comment by BugmanBugman** [comment]
Hopefully Ron can add an raw ore texture when he gets around to it

**Comment by boossiso** [comment]
A bug with the scales dragon armor. 
It's a bug of the armor in 1.16.5 it's as outstanding but in 1.20.1 it's as stuck to the body. The two first images are from 1.20.1 the third are from 1.16.5
![IMG_0564](https://github.com/AlexModGuy/Ice_and_Fire/assets/157433320/995513e1-b426-4759-810a-2ac50d962d9f)
![IMG_0563](https://github.com/AlexModGuy/Ice_and_Fire/assets/157433320/f82d5821-8af7-4bc2-b9e5-15abe7307cb0)
![IMG_0562](https://github.com/AlexModGuy/Ice_and_Fire/assets/157433320/ff897101-1fe1-4de9-8ee0-9739f2d8943c)

**Comment by BugmanBugman** [comment]
Bud you should make a new issue for this

**Comment by boossiso** [comment]
Is a uggly problem bro

**Comment by BugmanBugman** [comment]
Yeah but that’s not how issues work on GitHub tho

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mxnmnm** [comment]
Fixed with latest update
