### ISSUE TITLE
[Bug]:Ice dragons hatched in version 1.20.1 cannot be interacted with

### ISSUE THREAD

**Issue by wzq10314** [Alex-the-666/Ice_and_Fire#5074]
### What happened?

In version 1.20.1 of this mod, there is an issue where the ice dragon, once hatched, cannot be interacted with. The Dragon's Call Horn is also ineffective, and it's impossible to ride it on the shoulder. Interactions with the fire and thunder dragons are all normal.
The mod versions experiencing the issue are: iceandfire-2.1.13-1.20.1+build.beta-1 and iceandfire-2.1.13-1.20.1-SNAPSHOT+build.12-29

### Minecraft Version

1.20.1

### Ice and Fire version

 iceandfire-2.1.13-1.20.1+build.beta-1 and iceandfire-2.1.13-1.20.1-SNAPSHOT+build.12-29

### Citadel version

citadel-2.4.9-1.20.1

### Other Information

- [ ] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by wzq10314** [comment]
I have tried both locally and on the server, and there were no error reports in the console.

**Comment by TheBv** [comment]
Can't seem to be able to replicate this. Might've gotten fixed as well though with me addressing an issue with ice dragons not being hatchable.

**Comment by wzq10314** [comment]
> 似乎无法复制这一点。虽然我解决了冰龙无法孵化的问题，但也可能已经得到解决。

Thanks!it has been fixed!
