### ISSUE TITLE
[Bug]: Dragon eggs still do not hatch

### ISSUE THREAD

**Issue by f4r4ree** [Alex-the-666/Ice_and_Fire#5075]
### What happened?

I uninstalled and re-installed the beta mod but the eggs still do not hatch, what do i do to fix this?

### Minecraft Version

1.20.1

### Ice and Fire version

1.20.1 BETA

### Citadel version

citadel-2.4.9-1.20.1

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by mrkayar** [comment]
probably you have to wait new beta version
