### ISSUE TITLE
[Bug]: (Beta) Dragon cavern spawning inside of alex's caves

### ISSUE THREAD

**Issue by mxnmnm** [Alex-the-666/Ice_and_Fire#5077]
### What happened?

![2024-01-11_23 37 49](https://github.com/AlexModGuy/Ice_and_Fire/assets/8508976/0229fb6a-f20a-4c8c-8b9f-f3658760ff8d)
I think this image speaks for itself

### Minecraft Version

1.20.1

### Ice and Fire version

iceandfire-2.1.13-1.20.1+build.beta-1

### Citadel version

citadel-2.4.9-1.20.1

### Other Information

- [X] I am using other mods besides Ice and Fire
- [ ] I have attached a log file from the session that I have experienced this issue

**Comment by mxnmnm** [comment]
![2024-01-11_23 42 43](https://github.com/AlexModGuy/Ice_and_Fire/assets/8508976/872913c3-7526-44f3-b727-a57e06606ca8)

**Comment by SiverDX** [comment]
use the biome config to prevent that from happening

**Comment by SiverDX** [comment]
this can be closed imo

primordial caves are not part of any biome tags by default and https://www.curseforge.com/minecraft/mc-mods/tact adds it to `forge:is_cave` and `forge:is_lush` - none of those two are part of any default biome config

you'll have to use
`/forge tags minecraft:worldgen/biome query alexscaves:primordial_caves` to check which biome tag(s) it's part of
