### ISSUE TITLE
[Bug - Beta Build]: Cockatice crashing server

### ISSUE THREAD

**Issue by itsdinkd** [Alex-the-666/Ice_and_Fire#5078]
### What happened?

Dedicated server is crashing when starting due to Cockatice. Using the latest 1.18.2 beta build from github.

### Minecraft Version

1.16(CRASHES ONLY)

### Ice and Fire version

2.1.13-1.18.2+build.beta-3

### Citadel version

1.11.3

### Relevant log output

```shell
https://mclo.gs/w4COii6
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
I think right now I'd say this is caused by the tombstone mod. Possibly in combination with luckyperms?
When the cockatrice dies the Tombstone mod seems to try to do a bunch of stuff which then causes the crash.
Ideally post a bug report here: https://github.com/Corail31/tombstone_lite/issues

**Comment by itsdinkd** [comment]
Hmm, interesting, however, this does not happen with any other entities either from ice and fire, nor any other mod / vanilla mobs.

Disabling Cockatrice did not fix the crash either (it would crash after every restart due to the cockatrice being in spawn chunks). I disabled Cockatrice in the config, that did nothing as well. still crashed.

The only way i stopped this from crashing is by forcefully removing all cockatrice spawning events via KubeJS and canceling the event out. 

I don't believe this is just by tombstone. I will report to corail either way though but maybe this has something to do with both cockatrice itself and tombstone

**Comment by itsdinkd** [comment]
Ah i just received more info from a player that saw what happened before it crashed,

```
A fully grown cockatrice from ice and fire was glitched in the ground.
It was digged out and I started to kill it.
Then server crashed and there said something in the chat about "tickingentity".
The server kept crashing when started, most likely because the entity was constantly loaded with the chunkload.
```

**Comment by itsdinkd** [comment]
Tombstone dev is blaming luckperms, closed the ticket, being lazy. 

Luck perms in the stack trace is a wrapper that is only listening so not really sure where this is going to go. 

Since it's a Tombstone issue I'm going to close this issue as I don't want to deal with that asshole.
