### ISSUE TITLE
cascading worldgen lag

### ISSUE THREAD

**Issue by mandonnaud** [Alex-the-666/Ice_and_Fire#508]
Hello

my console spam message 

22.03 21:49:10 [Server] Server thread/WARN [FML]: Ice and Fire loaded a new chunk (-878, -260  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
22.03 21:49:11 [Server] Server thread/WARN [FML]: Ice and Fire loaded a new chunk (-878, -246  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
22.03 21:49:14 [Server] Server thread/WARN [FML]: Ice and Fire loaded a new chunk (-879, -261  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
22.03 21:49:15 [Server] Server thread/WARN [FML]: Ice and Fire loaded a new chunk (-879, -253  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
22.03 21:49:15 [Server] Server thread/WARN [FML]: Ice and Fire loaded a new chunk (-879, -255  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
22.03 21:49:20 [Server] Server thread/WARN Can't keep up! Did the system time change, or is the server overloaded? Running 8402ms behind, skipping 168 tick(s)
22.03 21:49:20 [Server] Server thread/WARN [FML]: Ice and Fire loaded a new chunk (-880, -261  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
22.03 21:49:20 [Server] Server thread/WARN [FML]: Ice and Fire loaded a new chunk (-881, -260  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
22.03 21:49:20 [Server] Server thread/WARN [FML]: Ice and Fire loaded a new chunk (-881, -261  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
22.03 21:49:20 [Server] Server thread/WARN [FML]: Ice and Fire loaded a new chunk (-881, -262  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
22.03 21:49:22 [Server] Server thread/WARN [FML]: Ice and Fire loaded a new chunk (-881, -256  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
22.03 21:49:27 [Server] Server thread/WARN [FML]: Ice and Fire loaded a new chunk (-882, -260  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
22.03 21:49:33 [Server] Server thread/WARN Can't keep up! Did the system time change, or is the server overloaded? Running 5598ms behind, skipping 111 tick(s)
22.03 21:49:34 [Server] Server thread/WARN [FML]: Ice and Fire loaded a new chunk (-882, -254  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
22.03 21:49:34 [Server] Server thread/WARN [FML]: Ice and Fire loaded a new chunk (-883, -255  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
22.03 21:49:34 [Server] Server thread/WARN [FML]: Ice and Fire loaded a new chunk (-884, -256  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
22.03 21:49:35 [Server] Server thread/WARN [FML]: Ice and Fire loaded a new chunk (-883, -259  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
22.03 21:49:35 [Server] Server thread/WARN [FML]: Ice and Fire loaded a new chunk (-883, -260  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

I recommend checking this out:
https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/

**Comment by AlexModGuy** [comment]
our structures are still bigger than 16 blocks. i'll offset them for you, but dragon dens will still cause this.
