### ISSUE TITLE
[Bug]: crashes on launch

### ISSUE THREAD

**Issue by usernamus1** [Alex-the-666/Ice_and_Fire#5086]
### What happened?

I&F makes minecraft crash on launch.

### Minecraft Version

1.19

### Ice and Fire version

iceandfire-1.19.2-2.1.13+build.beta-2

### Citadel version

citadel-2.1.4-1.19

### Other Information

- [ ] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by SiverDX** [comment]
post (crash) log or https://minecrafthopper.net/help/guides/getting-minecraft-game-output-log/

**Comment by usernamus1** [comment]
[crash-2024-01-16_23.28.44-client.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/13956023/crash-2024-01-16_23.28.44-client.txt)

**Comment by TheBv** [comment]
fixed and updated
