### ISSUE TITLE
[Bug]: Hippogryph moving very slowly and no walking animation (1.19.2)

### ISSUE THREAD

**Issue by vivagabe** [Alex-the-666/Ice_and_Fire#5093]
### What happened?

Hippogryph slides around slowly with no walking animation

### Minecraft Version

1.19

### Ice and Fire version

2.1.13 beta 3

### Citadel version

2.1.4

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by vivagabe** [comment]
[latest.log](https://github.com/AlexModGuy/Ice_and_Fire/files/13959077/latest.log)

**Comment by SiverDX** [comment]
try to replicate without oculus, it's known to break animations

**Comment by vivagabe** [comment]
Same result even with oculus removed. Not sure if it matters but this is with me using a spawn egg in creative mode.
