### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by pibblepower** [Alex-the-666/Ice_and_Fire#5096]
### What happened?

I loaded the game, and it said I needed a newer version for allthemodium (I was using the newest version, btw)

### Minecraft Version

1.19

### Ice and Fire version

iceandfire-1.19.2-2.1.13-beta-3

### Citadel version

citadel-2.1.4-1.19

### Relevant log output

```shell
[11:58:11] [Render thread/FATAL] [ne.mi.fm.ModLoader/CORE]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod §eallthemodium§r only supports §3iceandfire§r §o2.1 or above§r
§7Currently, §3iceandfire§r§7 is §o1.19.2-2.1.13+build.beta-3
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by JeremyCanDoIt** [comment]
You need to change the version number and it will work in gradle.properties, then rebuild gradle. It would be nice if they moved mod version before mc version though!

**Comment by SiverDX** [comment]
this is resolved in the latest update of that mod

![image](https://github.com/AlexModGuy/Ice_and_Fire/assets/22003703/6660e17d-d1be-4008-8ec4-9388f86b04ad)
