### ISSUE TITLE
[Bug]: Tools missing essential item tags that prevent them from working properly

### ISSUE THREAD

**Issue by ffuentesm** [Alex-the-666/Ice_and_Fire#5098]
### What happened?

All the tools are missing the new items tags used in the game, all tools only have the forge:tools tag. But by 1.20.x a lot of new tags were added to the game to the game. 

For example, an iron Pick has:
#minecraft:tools
#minecraft:breaks_decorated_pots
#forge:tools/iron
#minecraft:cluster_max_harvestables
#forge:tools
#minecraft:pickaxes
#forge:tools/pickaxes
#forge:pickaxes

Using a Copper pick or other tools in the mod, they are TOO SLOW, slower than a stone tool. 
https://github.com/AlexModGuy/Ice_and_Fire/assets/44974827/dee868b6-3173-4a06-932e-66fb9ca319b4

As you can see, they have the amethyst harvest tag missing, as well as the pickaxe tag, the way things are now the pickaxes are treated as non efficient tools to break blocks. 

A diamond axe has the tags: 
#forge:tools/axes
#minecraft:breaks_decorated_pots
#forge:tools/diamond
#forge:tools/metal/axes
#minecraft:axes
#minecraft:tools
#forge:axes
#forge:tools

Also tridents has tags now too
#forge:tools
#minecraft:tools
#forge:tools/tridents
#minecraft:breaks_decorated_pots

### Minecraft Version

1.20.1

### Ice and Fire version

2.1.13-1.20.1-beta-2

### Citadel version

citadel 2.4.9

### Other Information

- [X] I am using other mods besides Ice and Fire
- [x] I have attached a log file from the session that I have experienced this issue

**Comment by norfaremc** [comment]
Confirmed in 1.19.2, issue makes our modpack unplayable atm.

**Comment by SiverDX** [comment]
> Confirmed in 1.19.2, issue makes our modpack unplayable atm.

those tags don't even exist in 1.19.2
tools have no issues in that version, see https://github.com/AlexModGuy/Ice_and_Fire/tree/1.19.2/src/generated/resources/data/forge/tags/items/tools

**Comment by norfaremc** [comment]
Right now in our modpack, when we have ice and fire installed, pickaxes do not work. It functions like you’re breaking a block with your bare hand. It’s really slow to break, even with a modded or netherite pickaxe, and you don’t receive any blocks back.

**Comment by norfaremc** [comment]
Mo's Potions was the cause of the bug I was experiencing, but I thought it was ice and fire because it was the EXACT same bug. sorry about that!
