### ISSUE TITLE
Suggestions: Not a Bug

### ISSUE THREAD

**Issue by SuperStefan97** [Alex-the-666/Ice_and_Fire#5102]
### What happened?

Congrats Bv and your team if you had any on porting IaF. I know the efforts are centered on porting the mod now and solving bugs. If you had any time, I have found some old glitches and malfunctions you could give a check sometime:
- Keybind for Mounts to fly down. As of now, if you want to unmount a dragon or hyppogrif is certain death 
- Lightning Dragonsteel Weapons (Axe and Sword) damage their owner with their lightning, make them a threat to the player and mostly unuseable
- Dragons don't work with Domestication Innovation beds. Most likely because they are multi part mobs
This again, are just suggestions I think will do QoL changes to the mod, if you don't mind I will add more as I find them, I hope you find them useful at least. Again, thanks for porting the mod

### Minecraft Version

1.20.1

### Ice and Fire version

Beta

### Citadel version

Latest

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by SiverDX** [comment]
1. press `x` (there might be keybind conflicts you have to resolve through the keybind menu option)
2. the lightning bolt shouldn't damage the player (tested with just iceandfire and a also with a large personal modpack) - are you sure the damage didn't come from the fire?

**Comment by SuperStefan97** [comment]
Thanks! I will double check about the lightning. In the mean time, I will close the issue as it might me user sided. Again thanks for ur help.
