### ISSUE TITLE
ice and fire 1.12.2 , 3/25/2018

### ISSUE THREAD

**Issue by zezreli** [Alex-the-666/Ice_and_Fire#511]
hey so alex you told me to post the problem here with the crash report

so the crash appears between ice and fire and a mod called tinker's defense.

[crash-2018-03-25_12.31.29-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/1845192/crash-2018-03-25_12.31.29-client.txt)

**Comment by AlexModGuy** [comment]
fixed in 1.4.0
