### ISSUE TITLE
[Bug]: Crash during the battle with the ice dragon underground

### ISSUE THREAD

**Issue by Sergo467** [Alex-the-666/Ice_and_Fire#5110]
### What happened?

Crash during the battle with the ice dragon underground

### Minecraft Version

1.20.1

### Ice and Fire version

iceandfire-2.1.13-1.20.1-beta-2

### Citadel version

citadel-2.4.9-1.20.1

### Relevant log output
Debug and Crash log
https://gist.github.com/Sergo467/751942dc5b24136a55659632582755b6

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by SiverDX** [comment]
@TheBv see https://github.com/AlexModGuy/Ice_and_Fire/pull/5104
