### ISSUE TITLE
[Bug]: Cockatrice not spawning in savanas

### ISSUE THREAD

**Issue by LifelessAmir** [Alex-the-666/Ice_and_Fire#5113]
### What happened?

Used to see cockatrices in the savana, but when entering the savanas in the new 1.19.2 beta 3 update, there none to be found so no witherbone in the overworld!

### Minecraft Version

1.19

### Ice and Fire version

1.19.2-2.1.3-beta-3

### Citadel version

2.1.4-1.19

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by SiverDX** [comment]
![image](https://github.com/AlexModGuy/Ice_and_Fire/assets/22003703/002a5e20-af48-4b32-86a8-e01ffcbe30b7)

savanna is part of their default biome
check your biome configs

**Comment by LifelessAmir** [comment]
> ![image](https://private-user-images.githubusercontent.com/22003703/298841088-002a5e20-af48-4b32-86a8-e01ffcbe30b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTY5NDYsIm5iZiI6MTcwNTk5NjY0NiwicGF0aCI6Ii8yMjAwMzcwMy8yOTg4NDEwODgtMDAyYTVlMjAtYWY0OC00YjMyLTg2YTgtZTAxZmZjYmUzMGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA3NTcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NzRkZTdhNDU1OWMwZTRkYWFiOTUwYzYxOTIyYjY5NzRhN2Y1YzU0YzNmMDUyMDg0YTFmZTIxZmYzMGRkY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oLc4V9e2gmz5PCdBLKpFrqjnajQuk0fqot8C4PRUKsk)
> 
> savanna is part of their default biome check your biome configs

I know that, and I just checked. There were no problem with the config, but still they are not spawning, not even a single one.

**Comment by SiverDX** [comment]
then you are either in peaceful, spectator mode, some mod is breaking your biome tags due to invalid entries or some other mob is taking up all the spawns

example with terralith:
![image](https://github.com/AlexModGuy/Ice_and_Fire/assets/22003703/b70878af-aa2f-4ec6-9aa2-d787e79bb5d3)

example with just iceandfire:
![image](https://github.com/AlexModGuy/Ice_and_Fire/assets/22003703/ea6ae295-dd1a-4acb-b888-b24043cff8d4)

**Comment by LifelessAmir** [comment]
> then you are either in peaceful, spectator mode, some mod is breaking your biome tags due to invalid entries or some other mob is taking up all the spawns
> 
> example with terralith: ![image](https://private-user-images.githubusercontent.com/22003703/298879408-b70878af-aa2f-4ec6-9aa2-d787e79bb5d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjIwMzMsIm5iZiI6MTcwNjAyMTczMywicGF0aCI6Ii8yMjAwMzcwMy8yOTg4Nzk0MDgtYjcwODc4YWYtYWEyZi00ZWM2LTlhYTItZDc4N2U3OWJiNWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDE0NTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNDEyM2RkZTZiMjUwOWI3OTg2MWRmNGYwZDIwYWU2MGRjMjE3YjIzNzYxY2VhNTgyYjJmMzQzYmRhODRiNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VLycadlve2K6Wd7I8uZC0ZMfoxKN9KXF9Gk6bDx_fqk)
> 
> example with just iceandfire: ![image](https://private-user-images.githubusercontent.com/22003703/298885004-ea6ae295-dd1a-4acb-b888-b24043cff8d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjIwMzMsIm5iZiI6MTcwNjAyMTczMywicGF0aCI6Ii8yMjAwMzcwMy8yOTg4ODUwMDQtZWE2YWUyOTUtZGQxYS00YWNiLWI4ODgtYjI0MDQzY2ZmOGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDE0NTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlMTk4MDI2NGIzMjUwNDIyODg4YzZiNThhZGU1M2ZmNjc5MDlhYTFlZmM0NzA0YjVhNzM2ZTYwOGEzNTU4Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yPkhewpx8ibMcfNGKQBDxNYWZeVRBlKDFO-sPBzf2yU)

Well non of those except using mods.
Here they are. Would you know by any chance which one may be incompatible?
- alexsmobs
- create
- dungeon crawl
- irons spellbooks
- jade
- jei
- l ender cataclysm
- structory
- the graveyard
- towns and towers
- xaeros minimaps

**Comment by DigitalWendigo** [comment]
They spawn normally on my end as well. Just spotted 2 yesterday while looking for lightning dragons in the savanna. (1.19.2) 
I also use Create, Irons spellbooks, Cataclysm, Jade, JEi and other mods. (Just to point that the mentions can't be the culprits.)

**Comment by LifelessAmir** [comment]
> They spawn normally on my end as well. Just spotted 2 yesterday while looking for lightning dragons in the savanna. (1.19.2) I also use Create, Irons spellbooks, Cataclysm, Jade, JEi and other mods. (Just to point that the mentions can't be the culprits.)

Could it be that I loaded new chunks while downloded ice and fire in an existing world? Like I didn't make a new world for the mod.

**Comment by DigitalWendigo** [comment]
> > They spawn normally on my end as well. Just spotted 2 yesterday while looking for lightning dragons in the savanna. (1.19.2) I also use Create, Irons spellbooks, Cataclysm, Jade, JEi and other mods. (Just to point that the mentions can't be the culprits.)
> 
> Could it be that I loaded new chunks while downloded ice and fire in an existing world? Like I didn't make a new world for the mod.

Well, when you install the mod in an existing world, it's not going to populate Cockatrices in already visited savannas. 
As far as I know, (correct me if I'm wrong) Cockatrice only spawn once upon generating a new chunk, with only a chance that they actually do so. 
In the past weeks, I've visited three different Savannas and only 2 of them had Cockatrice spawn in them. 
Meaning the chances of encountering them is actually rather low. (You can change it in the configs, I believe.) 
Your most reliable way of getting your own Cockatrice, is by setting up an automatic egg farm with about 8-10 chickens atop a hopper. That'll give you a decent rate of rotten eggs without too many entities. (Increase per your own needs.)

**Comment by SiverDX** [comment]
it shouldn't matter if the chunk was generated or not since for this iceandfire just adds cockatrice to the mobs which can spawn in the configured biomes 

it's not worldgen

**Comment by LifelessAmir** [comment]
> > > They spawn normally on my end as well. Just spotted 2 yesterday while looking for lightning dragons in the savanna. (1.19.2) I also use Create, Irons spellbooks, Cataclysm, Jade, JEi and other mods. (Just to point that the mentions can't be the culprits.)
> > 
> > 
> > Could it be that I loaded new chunks while downloded ice and fire in an existing world? Like I didn't make a new world for the mod.
> 
> Well, when you install the mod in an existing world, it's not going to populate Cockatrices in already visited savannas. As far as I know, (correct me if I'm wrong) Cockatrice only spawn once upon generating a new chunk, with only a chance that they actually do so. In the past weeks, I've visited three different Savannas and only 2 of them had Cockatrice spawn in them. Meaning the chances of encountering them is actually rather low. (You can change it in the configs, I believe.) Your most reliable way of getting your own Cockatrice, is by setting up an automatic egg farm with about 8-10 chickens atop a hopper. That'll give you a decent rate of rotten eggs without too many entities. (Increase per your own needs.)

Yeah I know they wouldn't and that's why I generated new savanas, but still I found non.

**Comment by DigitalWendigo** [comment]
> it shouldn't matter if the chunk was generated or not since for this iceandfire just adds cockatrice to the mobs which can spawn in the configured biomes
> 
> it's not worldgen

Ahh, see that's my missunderstanding, I honestly believed Cockatrice only spawn on world gen, and not eventually over time. 
Though in that case, there is something off going on with their spawning. 
Since after killing all the cockatrice in one Savanna, they won't respawn over time. Neither day nor night.

**Comment by DigitalWendigo** [comment]
> > > > They spawn normally on my end as well. Just spotted 2 yesterday while looking for lightning dragons in the savanna. (1.19.2) I also use Create, Irons spellbooks, Cataclysm, Jade, JEi and other mods. (Just to point that the mentions can't be the culprits.)
> > > 
> > > 
> > > Could it be that I loaded new chunks while downloded ice and fire in an existing world? Like I didn't make a new world for the mod.
> > 
> > 
> > Well, when you install the mod in an existing world, it's not going to populate Cockatrices in already visited savannas. As far as I know, (correct me if I'm wrong) Cockatrice only spawn once upon generating a new chunk, with only a chance that they actually do so. In the past weeks, I've visited three different Savannas and only 2 of them had Cockatrice spawn in them. Meaning the chances of encountering them is actually rather low. (You can change it in the configs, I believe.) Your most reliable way of getting your own Cockatrice, is by setting up an automatic egg farm with about 8-10 chickens atop a hopper. That'll give you a decent rate of rotten eggs without too many entities. (Increase per your own needs.)
> 
> Yeah I know they wouldn't and that's why I generated new savanas, but still I found non.

- As for none spawning at all, maybe check what other mods you have installed that add other mobs? 
If you have many other mobs spawn in the savanna, then it's likely that they take up the spawn cap, and don't let cockatrice spawn. 
Or are all the mods you listed above, the only ones you use?

**Comment by SiverDX** [comment]
you can try increasing the spawn rate (default is 4), should be in the config
zombie is 100 e.g. and enderman is 10

**Comment by LifelessAmir** [comment]
> you can try increasing the spawn rate (default is 4), should be in the config zombie is 100 e.g. and enderman is 10

Just found only 1 in a savana biome so it works, but the only adjustment that I think should be made to the mod in an update is to increase the default spawn rate to a bigger number, cause the world is way deeper than 1.16 so there will be a lot more mobs underground and that will stop Cockatrices from spawning like normal.
Thanks for the support tho!

**Comment by SiverDX** [comment]
cockatrice is classified as `CREATURE` (same as animals) so monster spawning shouldn't limit it
