### ISSUE TITLE
[Bug]: No Lightning Lilys in the savana or messa biomes

### ISSUE THREAD

**Issue by LifelessAmir** [Alex-the-666/Ice_and_Fire#5114]
### What happened?

Strangly I'm finding ice lilys in the savana, but we all know it's lightning lily that should be there!

### Minecraft Version

1.19

### Ice and Fire version

1.19.2-2.1.3-beta-3

### Citadel version

2.1.4-1.19

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by DigitalWendigo** [comment]
Lightning lilly's seem to spawn in the tundra biomes now.
