### ISSUE TITLE
[Bug]: disable ore generation?

### ISSUE THREAD

**Issue by Enterprise12nx01** [Alex-the-666/Ice_and_Fire#5119]
### What happened?

i see no option to disable silver and deep slate silver ore generation in the config files 1.19.2

### Minecraft Version

1.19

### Ice and Fire version

2.1.13 beta 3

### Citadel version

2.1.4

### Relevant log output

```shell
NA
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by SiverDX** [comment]
remove biome entries in `ore_gen_biomes` config file

**Comment by Enterprise12nx01** [comment]
i did this and it still generates for me? 1.19
the config:

{
  "biomes": [
    [
    ]
  ]
}
