### ISSUE TITLE
A few bugs and issues

### ISSUE THREAD

**Issue by AguilaDaddy** [Alex-the-666/Ice_and_Fire#512]
- Dragons don't have the sitting animation anymore when they are in your shoulder
- Dragon eggs have different texture
- Cyclops have their eye again when you respawn after they kill you
- Ice Dragons move a lot upwards and downwards when walking or flying, making it harder to see forward
- When you throw arrows with a dragon in your shoulder it hits the dragon

**Comment by AlexModGuy** [comment]
I'm doing bugfixing right now so don't mind me

-1.4.0 they do
-not issue
-not in 1.4.0
-no
-fixed in 1.4.0
