### ISSUE TITLE
[Bug]: Dragon breath attack causing crash.

### ISSUE THREAD

**Issue by theblitz04** [Alex-the-666/Ice_and_Fire#5123]
### What happened?

When I am fighting dragons one breath attack or roar causes me to crash consistently.
[crash-2024-01-24_22.21.51-client.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/14046398/crash-2024-01-24_22.21.51-client.txt)

### Minecraft Version

1.20.1

### Ice and Fire version

2.1.13

### Citadel version

2.4.9

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by SiverDX** [comment]
See https://github.com/AlexModGuy/Ice_and_Fire/issues/5100
