### ISSUE TITLE
 [Bug]: Armor Glitches into Player Skin

### ISSUE THREAD

**Issue by Chiaracvt** [Alex-the-666/Ice_and_Fire#5125]
### What happened?

I put my Dragon Scale Armor on like normal and it just Glitches and looks all weird. I play in Version 

### Minecraft Version

1.20.1

### Ice and Fire version

2.1.13-1.20.1 beta

### Citadel version

2.4.9-1.20.1

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by Pivodur** [comment]
There is no problem when Optifine is not installed. The same issue also occurs in Alex's caves

**Comment by lepr3ch4un** [comment]
I'm having the same issue and I don't have optifine installed.

**Comment by lepr3ch4un** [comment]
Also, my legs disappear if I ever wear the boots without leggings

**Comment by TheBv** [comment]
Duplicate of #5112
