### ISSUE TITLE
[1.20.1] Citadel 2.5.0 unsupported.

### ISSUE THREAD

**Issue by VOLKOUL** [Alex-the-666/Ice_and_Fire#5132]
### What happened?

Ice and Fire crashes game with Citadel 2.5.0
Please update dependency requirements. (the new citadel update fixes a critical server bug)

### Minecraft Version

1.20.1

### Ice and Fire version

iceandfire-2.1.13-1.20.1-beta-2.jar

### Citadel version

citadel-2.5.0-1.20.1.jar

### Relevant log output

```shell
[28Jan2024 00:20:56.227] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'citadel', Requested by: 'iceandfire', Expected range: '[2.4.1,2.4.99]', Actual version: '2.5.0'
```

### Other Information

- [ ] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
fixed in beta 4
