### ISSUE TITLE
[Bug]: Invisible Dragons?

### ISSUE THREAD

**Issue by Caboose-4** [Alex-the-666/Ice_and_Fire#5133]
### What happened?

I'm on 1.20.1 and having an issue where only the dragons are invisible. I can't seem to spawn/summon any kind of dragon in creative. They're somehow in my survival world, been killed by an invisible ice dragon twice. Every other mob works just fine from the ice and fire mod pack. Any way to fix invisible mobs in configs maybe? 

### Minecraft Version

1.20.1

### Ice and Fire version

1.20.1

### Citadel version

2.4.9

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Most likely another mod causing this issue. Look into optimization mods and other mods that mess with entities/rendering

**Comment by francodea1** [comment]
did u manage to find a solution? i have the exact same problem, but im sure the are no mod causing issues cuz im playing on a server with friends and all of them can see the dragons
