### ISSUE TITLE
[Bug]: Armour textures not loading

### ISSUE THREAD

**Issue by Zory96** [Alex-the-666/Ice_and_Fire#5135]
### What happened?

![image_2024-01-30_012055557](https://github.com/AlexModGuy/Ice_and_Fire/assets/158065306/0411822c-58a5-480d-9991-7f2fd6ceaddd)
My textures for armour sets dont seem to be loading. I've reinstalled ice and fire and changed citadel multiple times (different versions), does anyone have a fix?

### Minecraft Version

1.20.1

### Ice and Fire version

1.20.1

### Citadel version

2.4.5

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by Sergo467** [comment]
I had this when using optifine, replace it with embeddium+oculus.

**Comment by DigitalWendigo** [comment]
Oculus is also often a culprit for breaking animations, so perhaps not use that one either. 
Embeddium however is a relatively safe bet. 
Optifine is a known cause for many issues, so always first remove that and see if the issue persists.
