### ISSUE TITLE
TOO MUCH DRAGONS

### ISSUE THREAD

**Issue by Yuuzinhozi** [Alex-the-666/Ice_and_Fire#5138]
On the server there is an option where I can reduce the chance of a dragon or its lair appearing.
But I can't say whether increasing the number reduces the chance, or decreasing the number reduces the chance. I wish it was super rare to find one.

Version:

1.20.1
iceandfire-2.1.13-1.20.1-beta-2
citadel-2.4.9-1.20.1

[Generation]

	[Generation.Dragon]
		#Whether to generate dragon skeletons or not
		"Generate Dragon Skeletons" = true
		#1 out of this number chance per chunk for generation
		#Range: 1 ~ 10000
		"Generate Dragon Skeleton Chance" = 680
		#1 out of this number chance per chunk for generation
		#Range: 1 ~ 10000
		"Generate Dragon Cave Chance" = 680
		#1 out of this number chance per chunk for generation
		#Range: 1 ~ 10000
		"Generate Dragon Roost Chance" = 680
		#1 out of this number chance per block that gold will generate in dragon lairs.
		#Range: 1 ~ 10000
		"Dragon Den Gold Amount" = 800
		#Ratio of Stone(this number) to Ores in Dragon Caves
		#Range: 1 ~ 10000
		"Dragon Cave Ore Ratio" = 700

![111](https://github.com/AlexModGuy/Ice_and_Fire/assets/145175473/03604d6d-c1c7-4ac3-ac55-87f46fc0b521)

**Comment by SiverDX** [comment]
higher number -> more rare
it's `1 in x `

in theory what you see in the screenshot can always happen with how the generation works
try to increase it to 2000 and see if it's much rarer (to check whether it properly works or not)

**Comment by Yuuzinhozi** [comment]
Thank u! I will try and let u know if works, but i guess it will!

**Comment by Yuuzinhozi** [comment]
it works! ty

**Comment by DarkClueee** [comment]
Were you using Biomes O'Plenty too cause in my case dragons barely spawn they spawn only on vanilla biomes
