### ISSUE TITLE
Suggestion Arrows

### ISSUE THREAD

**Issue by litjohn50** [Alex-the-666/Ice_and_Fire#515]
So I've installed the mod managed to get a bow and just a stack of regular arrows. But I'm a bit disappointed how easily the dragons can go down with normal arrows. Is there anyway you can let the arrows reflect off him or just do 0.01% damage, So its more needed to use the dragon bone arrows instead.

and/or add a cfg option for people who would like more challenge in their dragon slaying.

**Comment by AlexModGuy** [comment]
move to https://github.com/Alex-the-666/Ice-and-Fire-Suggestions please
