### ISSUE TITLE
Midair hippogryphs resist player control

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#516]
Have a tamed hippogryph flying
Jump on it while it is flying
Try to control it to your will, you can't and the gryph resist your commands
Land the mob completely, then take off again, the mob now follow your orders.

**Comment by AlexModGuy** [comment]
are you sure that isnt just friction, they slide like theyre on ice but thats normal

**Comment by AlexModGuy** [comment]
fixed in 1.8.4
