### ISSUE TITLE
[Bug]: myrmex hive

### ISSUE THREAD

**Issue by genisonvidalpereira** [Alex-the-666/Ice_and_Fire#5168]
### What happened?

I can't find myrmex hive in the jungle

### Minecraft Version

1.20.1

### Ice and Fire version

2.1.13 beta 2

### Citadel version

1,4.9

### Relevant log output

```shell
I can't find myrmex hive in the jungle
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [ ] I have attached a log file from the session that I have experienced this issue

**Comment by ffuentesm** [comment]
Not a bug, you need to look for it. I have found 2 of them in my world. 
You will find the hive opening on the wall of mountains or ravines. 
You can get a compass mod, or use the `/locate` command.

**Comment by genisonvidalpereira** [comment]
But did you find it in which biome?

**Comment by ffuentesm** [comment]
Twice on a jungle biome. 
They even grow on bamboo forests

**Comment by genisonvidalpereira** [comment]
Can you send me the structure compass mod you're using?

**Comment by ffuentesm** [comment]
https://www.curseforge.com/minecraft/mc-mods/nature-compass/files
Just set to jungle on the menu

**Comment by SiverDX** [comment]
you shouldn't be able to find myrmex hives with locate or structure compasses since it's not a structure, its a feature

**Comment by ffuentesm** [comment]
I use the `/locate` to find jungle biomes and then I just look around for the hive entrance.

**Comment by genisonvidalpereira** [comment]
the spawn rate of myrmex hive is so small why is it difficult to find myrmex

**Comment by SiverDX** [comment]
then increase it that's what the config is there for 

https://github.com/AlexModGuy/Ice_and_Fire/wiki/Configuration

**Comment by genisonvidalpereira** [comment]
I'm confused and can I reduce or increase the spawn rate value?

**Comment by SiverDX** [comment]
if you don't understand the explanation then I cannot help you

**Comment by genisonvidalpereira** [comment]
why can't I change this part #A chance of this number per piece to generate a myrmex hive.
#Range: 1 ~ 10,000
whenever I try it goes back to value 1

**Comment by genisonvidalpereira** [comment]
I managed to change the settings but the problem is that when the myrmex hive spawns it is very low and there is no hive entrance

**Comment by genisonvidalpereira** [comment]
> se você não entende a explicação então não posso te ajudar

my queen myrmex is despawning I don't why is this happening
