### ISSUE TITLE
[Bug]: Latest Ice and Fire crashes on server

### ISSUE THREAD

**Issue by vivagabe** [Alex-the-666/Ice_and_Fire#5179]
### What happened?

Server crashes at launch:
[crash-2024-02-19_15.51.23-fml.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/14337665/crash-2024-02-19_15.51.23-fml.txt)

### Minecraft Version

1.20.1

### Ice and Fire version

iceandfire-2.1.13-1.20.1-beta-3

### Citadel version

2.5.3

### Relevant log output

```shell
see above.
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by mxnmnm** [comment]
can confirm

**Comment by AngV01** [comment]
me too

**Comment by Tr0nDraws** [comment]
identical issue here

**Comment by TheBv** [comment]
Fixed in beta-4
