### ISSUE TITLE
[Bug]: Pixies and Sirens particles are buggy

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#5185]
### What happened?

![image](https://github.com/AlexModGuy/Ice_and_Fire/assets/156274940/024104dc-fe07-4638-83c3-1084845e281a)

I only noticed this issue with those two. It doesn't always bug out, but it happens often.

### Minecraft Version

1.21.1

### Ice and Fire version

iceandfire-2.1.13-1.20.1-beta-4.jar

### Citadel version

citadel-2.5.3-1.20.1.jar

### Relevant log output

```shell
Logs none relevant I'm assuming. If required please ask and I will provide them.
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Duplicate of #5150
(I know it's a slightly different issue but I'm already taking care of it)
