### ISSUE TITLE
[Bug]: Ice and Fire destroys our server's TPS

### ISSUE THREAD

**Issue by gisketch** [Alex-the-666/Ice_and_Fire#5186]
### What happened?

We play a 300+ mods modpack, it's great. We get 20 tps most of the time, but recently, Ice and Fire has been the reason the TPS goes down to 8 to 13, it is annoying and unplayable. Maybe there is a way to fix this without removing Ice and Fire.

This is a screenshot of the profiler with the TPS down to 7

![image](https://github.com/AlexModGuy/Ice_and_Fire/assets/78424395/fa406844-35c6-4ef0-bc89-3e4b6fc61947)

### Minecraft Version

1.20.1

### Ice and Fire version

2.1.13

### Citadel version

2.4.9

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by SiverDX** [comment]
update mod

**Comment by gisketch** [comment]
thanks, seems to have fixed it
