### ISSUE TITLE
Dragon spawns way to frequent?

### ISSUE THREAD

**Issue by Dakotsie** [Alex-the-666/Ice_and_Fire#52]
Dragons seem to spawn way to frequently. I can see like 3 or 4, even 5 at any one time while in the air. I didn't see this in any other report, but it could be related to issue #49.

![2016-11-23_19 35 14](https://cloud.githubusercontent.com/assets/8368983/20584035/83ee1e4e-b1b4-11e6-9d19-f1d6163eca53.png)

![2016-11-23_19 37 04](https://cloud.githubusercontent.com/assets/8368983/20584004/30183aca-b1b4-11e6-85f1-632291a9459c.png)

**Comment by JayZX535** [comment]
Agreed, dragon spawns do seem very frequent.  They probably need to be toned down some...

**Comment by Kusark** [comment]
![2016-11-23_16 29 07](https://cloud.githubusercontent.com/assets/16695546/20586772/253d32ba-b1bc-11e6-8c41-d2c5c20b543d.png)

**Comment by Kusark** [comment]
Just an extra screenshot to add onto this

**Comment by LeonelSaberTooth** [comment]
yes theres at least 1 dragon lair every 200 blocks or so

**Comment by Alex-the-666** [comment]
going to lower it to half its spawn chance.
