### ISSUE TITLE
gorgons won't petrified anymore statue if some are near her

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#527]
put some mobs near the gorgon, she will only petrified a few, but never petrified the rest

**Comment by mser7** [comment]
maybe put a lot

**Comment by AlexModGuy** [comment]
https://i.imgur.com/Njp0DjB.png

unable to replicate. this is a lot of mobs

**Comment by mser7** [comment]
oops, forgot to mention, build a block wall around her first to block her vision outside the boundry, then spawn the mobs inside of the wall

**Comment by AlexModGuy** [comment]
https://i.imgur.com/V8imGlv.png

still working

**Comment by mser7** [comment]
i meant closed up border

**Comment by mser7** [comment]
https://imgur.com/a/3clBM
