### ISSUE TITLE
[SUGGESTION] Support for various gravestone mods

### ISSUE THREAD

**Issue by Sunconure11** [Alex-the-666/Ice_and_Fire#536]
Some mods, since they add gravestones with your loot on death, sometimes get destroyed by dragon fire, even if they should not. An example is this:

https://minecraft.curseforge.com/projects/gravestone-mod-graves?gameCategorySlug=mc-mods&projectID=62929

**Comment by AlexModGuy** [comment]
this is really on them. the tombstone is destroyed by the dragons explosion, so modders should just increase the "resistance" modifier of their tombstones.
