### ISSUE TITLE
Stage 1 thoughts

### ISSUE THREAD

**Issue by JayZX535** [Alex-the-666/Ice_and_Fire#54]
Just a few thoughts on the stage 1 dragons...
I feel like stage 1 dragons have too many hitpoints.  Granted that they do have scales and everything, it still takes 10 or so hits to kill them with the corresponding sword (ice for fire and fire for ice), which seems like a lot for a baby/young juvenile.  They also drop way too much loot.
Secondly, killing them makes me feel like a heartless monster, gah!
I'm pretty sure I've never seen a wild stage 1 that didn't come from a spawn egg (also something I have yet to see spawning naturally).  And since the bestiary states that dragons have strong maternal instinct, I feel like any one that I found apart from the company of another dragon would be "out-of-place"-- most likely an orphan doomed to die anyway.
My thought is, since these guys are so rare anyway, perhaps there could be a way to tame them, too.  After all, they probably wouldn't be able to survive on their own, and if they're alone they either don't have a family, or you killed their family.  Taming would be extremely expensive, probably requiring a lot of fish and maybe precious metals, but it would give us a way to avoid murdering the poor little things before they grow up.  I would expect an orphaned dragon would be able to bond with a human at that age, still-- and they're rare enough that it probably wouldn't make the mod unbalanced.  Heck, I think even taming stage 2 dragons (at a HUGE cost) wouldn't be too unbalanced (stage 3 would be stretching it-- by then most dragons would have learned to fear/hate humans-- but at stage two they might still harbor enough curiosity to be able to be tamed, at least in my opinion).  But I definitely think stage 1 at least should be tameable.  Perhaps it could be a config option, if it proves to be a contested point?
Anywho, just a few thoughts on the adorable little guys XD

**Comment by raptorfarian** [comment]
Please don't report current thoughts on the Git Hub , if you have non bug related suggestions PM them to me.
