### ISSUE TITLE
Configurable dragon destruction

### ISSUE THREAD

**Issue by JayZX535** [Alex-the-666/Ice_and_Fire#55]
One of the major nitpicks I have with the dragons so far is how destructive they are.  They wreck stuff.  A lot.  It's gonna make it hard to build much of anything unless you start mass-exterminating dragons, and if you want to use (untamed) dragons in your build?  Good luck!
Perhaps dragon block destruction could be a config option, like it is for dinos in F/A.  That would enable us to potentially catch/contain untamed dragons we didn't want to kill, and suchnot.  Or, if we just want dragons to not be able to destroy blocks, it could help there (the block destruction while they fly is also VERY laggy sometimes, so it could be a lag-reducing feature as well).  Just some thoughts!

**Comment by Dakotsie** [comment]
I too, would like this. In fact, I was just going to check if they had an option for this.

**Comment by raptorfarian** [comment]
Configs will be added at a later date.
