### ISSUE TITLE
Instakill Dragon attack crashes game in Creative mode

### ISSUE THREAD

**Issue by acloserlookatthatsnout** [Alex-the-666/Ice_and_Fire#551]
Fighting a fire dragon in creative mode, the dragon grabs me and shakes its head in one of the new attacks, but I'm in creative mode. The screen goes completely black and the game crashes.

**Comment by AlexModGuy** [comment]
how are you fighting it in creative. it shouldn't even be targeting you. Crashlog?

**Comment by acloserlookatthatsnout** [comment]
NOTE: I was using the Ultimate Unicorn Mod along with Ice and Fire, and the dragon seemed to be targeting the horse I was riding.


---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-1.7.9-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 4/7/18 9:18 PM
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=iceandfire:ash, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at com.github.alexthe666.iceandfire.client.render.tile.RenderPixieHouse.render(RenderPixieHouse.java:36)
	at com.github.alexthe666.iceandfire.client.render.tile.RenderPixieHouse.func_192841_a(RenderPixieHouse.java:18)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:197)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:153)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:1008)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1781)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1606)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1377)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at com.github.alexthe666.iceandfire.client.render.tile.RenderPixieHouse.render(RenderPixieHouse.java:36)
	at com.github.alexthe666.iceandfire.client.render.tile.RenderPixieHouse.func_192841_a(RenderPixieHouse.java:18)

-- Block Entity Details --
Details:
	Name: minecraft:pixie_house // com.github.alexthe666.iceandfire.entity.tile.TileEntityPixieHouse
	Block type: ID #274 (tile.iceandfire.ash // com.github.alexthe666.iceandfire.block.BlockFallingGeneric)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-925,72,-613), Chunk: (at 3,4,11 in -58,-39; contains blocks -928,0,-624 to -913,255,-609), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
	Actual block type: ID #274 (tile.iceandfire.ash // com.github.alexthe666.iceandfire.block.BlockFallingGeneric)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:197)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:153)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:1008)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1781)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1606)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['ObsidianKitten'/3159, l='MpServer', x=-892.02, y=69.60, z=-597.98]]
	Chunk stats: MultiplayerChunkCache: 879, 879
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (56,64,256), Chunk: (at 8,4,0 in 3,16; contains blocks 48,0,256 to 63,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 9604 game time, 9604 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 117 total; [EntityPixie['Pixie'/9234, l='MpServer', x=-834.22, y=66.79, z=-566.41], EntityPixie['Pixie'/9236, l='MpServer', x=-947.91, y=68.24, z=-590.50], EntityPixie['Pixie'/9238, l='MpServer', x=-838.50, y=68.00, z=-540.50], EntityHippogryph['Hippogryph'/8221, l='MpServer', x=-846.94, y=89.54, z=-637.02], EntityItem['item.item.iceandfire.pixie_dust'/9248, l='MpServer', x=-928.59, y=73.21, z=-611.11], EntityItem['item.item.iceandfire.pixie_dust'/9249, l='MpServer', x=-921.31, y=74.08, z=-610.67], EntityItem['item.tile.iceandfire.pixie_house_3'/9253, l='MpServer', x=-924.86, y=72.00, z=-613.68], EntityItem['item.item.seeds'/9255, l='MpServer', x=-928.36, y=72.00, z=-614.13], EntityFallingBlock['Falling Block'/9260, l='MpServer', x=-922.50, y=74.94, z=-610.50], EntityFallingBlock['Falling Block'/9261, l='MpServer', x=-925.50, y=74.94, z=-610.50], EntityFallingBlock['Falling Block'/9262, l='MpServer', x=-919.50, y=74.94, z=-615.50], EntityFallingBlock['Falling Block'/9263, l='MpServer', x=-922.50, y=74.94, z=-615.50], EntityFallingBlock['Falling Block'/9264, l='MpServer', x=-926.50, y=73.94, z=-615.50], EntityFallingBlock['Falling Block'/9265, l='MpServer', x=-921.50, y=73.00, z=-615.50], EntityFallingBlock['Falling Block'/9266, l='MpServer', x=-922.50, y=74.00, z=-620.50], EntityFallingBlock['Falling Block'/9267, l='MpServer', x=-922.50, y=74.94, z=-617.50], EntityFallingBlock['Falling Block'/9268, l='MpServer', x=-922.50, y=75.94, z=-614.50], EntityFallingBlock['Falling Block'/9269, l='MpServer', x=-920.50, y=74.94, z=-614.50], EntityChicken['Chicken'/8246, l='MpServer', x=-881.50, y=71.00, z=-623.50], EntityFallingBlock['Falling Block'/9270, l='MpServer', x=-927.50, y=74.94, z=-614.50], EntityChicken['Chicken'/8247, l='MpServer', x=-882.50, y=72.00, z=-623.50], EntityFallingBlock['Falling Block'/9271, l='MpServer', x=-913.50, y=72.94, z=-614.50], EntityChicken['Chicken'/8248, l='MpServer', x=-882.50, y=72.00, z=-623.50], EntityChicken['Chicken'/8249, l='MpServer', x=-878.41, y=70.00, z=-632.18], EntityFallingBlock['Falling Block'/9284, l='MpServer', x=-922.50, y=76.63, z=-610.50], EntityFallingBlock['Falling Block'/9285, l='MpServer', x=-925.50, y=76.63, z=-610.50], EntityFallingBlock['Falling Block'/9286, l='MpServer', x=-922.50, y=76.63, z=-615.50], EntityFallingBlock['Falling Block'/9287, l='MpServer', x=-926.50, y=75.63, z=-615.50], EntityFallingBlock['Falling Block'/9288, l='MpServer', x=-921.50, y=74.63, z=-615.50], EntityFallingBlock['Falling Block'/9289, l='MpServer', x=-922.50, y=77.63, z=-614.50], EntityPlayerSP['ObsidianKitten'/3159, l='MpServer', x=-892.02, y=69.60, z=-597.98], EntityItem['item.tile.flower1.dandelion'/8333, l='MpServer', x=-862.13, y=61.00, z=-614.88], EntityItem['item.tile.flower1.dandelion'/8338, l='MpServer', x=-861.32, y=58.00, z=-606.06], EntityItem['item.tile.flower1.dandelion'/8339, l='MpServer', x=-871.13, y=64.00, z=-603.13], EntityItem['item.item.seeds'/8341, l='MpServer', x=-877.25, y=64.00, z=-591.97], EntityItem['item.item.seeds'/8342, l='MpServer', x=-875.13, y=63.00, z=-597.72], EntityItem['item.tile.flower1.dandelion'/8345, l='MpServer', x=-875.13, y=63.00, z=-591.13], EntityItem['item.item.seeds'/8347, l='MpServer', x=-900.88, y=69.00, z=-600.31], EntityItem['item.item.seeds'/8352, l='MpServer', x=-891.55, y=69.00, z=-593.13], EntityItem['item.item.seeds'/8353, l='MpServer', x=-879.79, y=63.00, z=-595.12], EntityItem['item.item.seeds'/8354, l='MpServer', x=-894.59, y=69.00, z=-592.41], EntityItem['item.item.seeds'/8355, l='MpServer', x=-884.42, y=67.00, z=-591.81], EntityItem['item.tile.flower2.poppy'/8356, l='MpServer', x=-893.50, y=69.00, z=-593.12], EntityItem['item.tile.flower2.poppy'/8357, l='MpServer', x=-892.18, y=69.00, z=-592.13], EntityItem['item.tile.flower2.poppy'/8358, l='MpServer', x=-896.32, y=69.00, z=-590.60], EntityItem['item.tile.flower2.poppy'/8359, l='MpServer', x=-894.13, y=69.00, z=-590.13], EntityFireDragon['Fire Dragon'/8360, l='MpServer', x=-897.76, y=69.00, z=-603.54], EntityPixie['Pixie'/8381, l='MpServer', x=-834.80, y=68.68, z=-539.58], EntityPixie['Pixie'/8384, l='MpServer', x=-835.24, y=70.00, z=-539.20], EntitySheep['Sheep'/8386, l='MpServer', x=-828.50, y=64.00, z=-533.50], EntitySheep['Sheep'/8387, l='MpServer', x=-834.49, y=66.00, z=-527.72], EntitySheep['Sheep'/8388, l='MpServer', x=-833.50, y=65.00, z=-533.50], EntitySheep['Sheep'/8389, l='MpServer', x=-836.50, y=66.00, z=-533.50], EntityPixie['Pixie'/8400, l='MpServer', x=-839.80, y=71.53, z=-540.05], EntityPixie['Pixie'/8402, l='MpServer', x=-828.56, y=66.55, z=-549.93], EntityBat['Bat'/8407, l='MpServer', x=-826.55, y=19.09, z=-614.82], EntityBat['Bat'/8439, l='MpServer', x=-825.49, y=23.85, z=-564.73], EntityPixie['Pixie'/8449, l='MpServer', x=-935.80, y=70.70, z=-598.80], EntityPixie['Pixie'/8450, l='MpServer', x=-941.89, y=70.29, z=-592.13], EntityPixie['Pixie'/8451, l='MpServer', x=-918.77, y=75.86, z=-608.57], EntityPixie['Pixie'/8452, l='MpServer', x=-938.80, y=66.49, z=-597.49], EntityPixie['Pixie'/8453, l='MpServer', x=-936.20, y=72.29, z=-593.25], EntityPixie['Pixie'/8454, l='MpServer', x=-939.80, y=69.04, z=-575.55], EntityPig['Pig'/8455, l='MpServer', x=-934.37, y=69.00, z=-570.55], EntityPig['Pig'/8456, l='MpServer', x=-925.76, y=70.00, z=-567.50], EntityPig['Pig'/8457, l='MpServer', x=-935.50, y=69.00, z=-573.50], EntityPig['Pig'/8458, l='MpServer', x=-936.35, y=70.00, z=-563.76], EntityPixie['Pixie'/8459, l='MpServer', x=-943.80, y=70.34, z=-581.80], EntityPixie['Pixie'/8460, l='MpServer', x=-927.71, y=70.57, z=-589.05], EntityPixie['Pixie'/8461, l='MpServer', x=-943.80, y=68.55, z=-576.20], EntityPixie['Pixie'/8462, l='MpServer', x=-944.08, y=76.00, z=-575.50], EntityPixie['Pixie'/8466, l='MpServer', x=-948.80, y=74.00, z=-588.80], EntityPixie['Pixie'/8467, l='MpServer', x=-930.80, y=74.79, z=-611.47], EntityPixie['Pixie'/8468, l='MpServer', x=-930.80, y=68.00, z=-590.61], EntityPixie['Pixie'/8469, l='MpServer', x=-948.47, y=69.15, z=-582.67], EntityPixie['Pixie'/8470, l='MpServer', x=-945.50, y=69.00, z=-570.80], EntityPig['Pig'/8472, l='MpServer', x=-966.50, y=71.00, z=-658.50], EntityPig['Pig'/8473, l='MpServer', x=-965.50, y=71.00, z=-655.50], EntityPig['Pig'/8475, l='MpServer', x=-966.50, y=71.00, z=-659.50], EntitySheep['Sheep'/8476, l='MpServer', x=-955.50, y=71.00, z=-635.50], EntitySheep['Sheep'/8477, l='MpServer', x=-957.50, y=70.00, z=-636.50], EntitySheep['Sheep'/8478, l='MpServer', x=-961.28, y=70.00, z=-641.17], EntitySheep['Sheep'/8479, l='MpServer', x=-956.50, y=70.00, z=-634.50], EntityPig['Pig'/8480, l='MpServer', x=-946.50, y=71.00, z=-615.50], EntityPig['Pig'/8481, l='MpServer', x=-945.50, y=71.00, z=-615.50], EntityPig['Pig'/8482, l='MpServer', x=-944.50, y=71.00, z=-615.50], EntityBat['Bat'/8554, l='MpServer', x=-856.50, y=59.96, z=-554.52], EntityBat['Bat'/8571, l='MpServer', x=-863.46, y=59.67, z=-555.54], EntityBat['Bat'/8601, l='MpServer', x=-831.91, y=51.53, z=-625.57], EntityBat['Bat'/8607, l='MpServer', x=-827.11, y=62.11, z=-613.61], EntityBat['Bat'/8608, l='MpServer', x=-880.57, y=61.08, z=-552.37], EntityChicken['Chicken'/8616, l='MpServer', x=-960.50, y=67.00, z=-519.50], EntityBat['Bat'/8620, l='MpServer', x=-885.87, y=58.45, z=-560.60], EntityBat['Bat'/8621, l='MpServer', x=-912.54, y=12.91, z=-556.88], EntityBat['Bat'/8681, l='MpServer', x=-911.27, y=16.10, z=-640.70], EntityBat['Bat'/8734, l='MpServer', x=-859.83, y=43.03, z=-653.26], EntityBat['Bat'/8739, l='MpServer', x=-840.78, y=39.02, z=-651.53], EntityBat['Bat'/8740, l='MpServer', x=-942.88, y=22.00, z=-569.46], EntityItem['item.item.iceandfire.pixie_dust'/8779, l='MpServer', x=-840.69, y=70.00, z=-537.58], EntityPixie['Pixie'/8889, l='MpServer', x=-936.41, y=70.55, z=-584.80], EntityMagicalHorse['entity.magical horse.name'/6914, l='MpServer', x=-892.02, y=69.00, z=-597.98], EntityPixie['Pixie'/9065, l='MpServer', x=-830.98, y=68.20, z=-541.14], EntityItem['item.tile.flower1.dandelion'/9149, l='MpServer', x=-876.13, y=68.00, z=-615.88], EntityPixie['Pixie'/9167, l='MpServer', x=-843.20, y=71.58, z=-544.52], EntityItem['item.tile.iceandfire.charedGrass'/9168, l='MpServer', x=-886.94, y=69.50, z=-607.52], EntityItem['item.tile.iceandfire.charedGrass'/9169, l='MpServer', x=-887.54, y=69.00, z=-608.80], EntityItem['item.tile.iceandfire.charedGrass'/9171, l='MpServer', x=-889.03, y=69.00, z=-608.18], EntityItem['item.tile.iceandfire.charedGrass'/9173, l='MpServer', x=-889.86, y=69.00, z=-608.60], EntityItem['item.tile.iceandfire.charedGrass'/9176, l='MpServer', x=-890.88, y=69.00, z=-605.65], EntityItem['item.item.goldNugget'/9178, l='MpServer', x=-890.64, y=69.00, z=-607.38], EntityPig['Pig'/8156, l='MpServer', x=-831.78, y=97.00, z=-675.58], EntityItem['item.tile.iceandfire.charedGrass'/9180, l='MpServer', x=-890.45, y=69.00, z=-606.44], EntityPig['Pig'/8157, l='MpServer', x=-829.66, y=92.00, z=-669.49], EntityItem['item.tile.iceandfire.charedGrass'/9181, l='MpServer', x=-890.88, y=69.00, z=-607.76], EntityPig['Pig'/8158, l='MpServer', x=-830.50, y=90.00, z=-667.50], EntityPig['Pig'/8159, l='MpServer', x=-827.50, y=89.00, z=-666.50], EntityItem['item.tile.sapling.oak'/9198, l='MpServer', x=-934.44, y=66.00, z=-587.95]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 390465248 bytes (372 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.1.2555 Optifine OptiFine_1.12.2_HD_U_C7 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                   | Version      | Source                          | Signature                                |
	|:--------- |:-------------------- |:------------ |:------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft            | 1.12.2       | minecraft.jar                   | None                                     |
	| UCHIJAAAA | mcp                  | 9.42         | minecraft.jar                   | None                                     |
	| UCHIJAAAA | FML                  | 8.0.99.99    | forge-1.12.2-14.23.1.2555.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                | 14.23.1.2555 | forge-1.12.2-14.23.1.2555.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | mercurius_updater    | 1.0          | MercuriusUpdater-1.12.2.jar     | None                                     |
	| UCHIJAAAA | llibrary             | 1.7.9        | llibrary-1.7.9-1.12.2.jar       | None                                     |
	| UCHIJAAAA | iceandfire           | 1.3.1        | iceandfire-1.3.1-1.12.2.jar     | None                                     |
	| UCHIJAAAA | ultimate_unicorn_mod | 1.5.14       | Ultimate-Unicorn-Mod-1.12.2.jar | None                                     |
	| UCHIJAAAA | worldedit            | 6.1.8        | WorldEdit-1.12.jar              | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-1.7.9-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4531' Renderer: 'Intel(R) HD Graphics 4400'
	Launched Version: 1.12.2-forge1.12.2-14.23.1.2555
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 20.19.15.4531, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: John Smith Legacy 1.11.2 v1.zip
	Current Language: English (Canada)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C7
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.3.0 - Build 20.19.15.4531
	OpenGlRenderer: Intel(R) HD Graphics 4400
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by AlexModGuy** [comment]
pixie hovel crashes fixed
