### ISSUE TITLE
GUI swallowing items

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#556]
Hippocampus, hippogryph and dragon's GUI will eat your unregistered items when shift-click the item while opening the GUI

**Comment by AlexModGuy** [comment]
what unregistered items ?

**Comment by mser7** [comment]
Registered items included saddle, armors and chest. Try to shift click a stack of diamond while opening the GUI

**Comment by mser7** [comment]
this is probably due to the chest behavior, when shift click it is supposed to put your item in the inventory chest of the mob, but it mistake even if there is no chest on the mob, and the result deleting your item.
