### ISSUE TITLE
player inside Giant death worm while riding

### ISSUE THREAD

**Issue by AguilaDaddy** [Alex-the-666/Ice_and_Fire#559]
When riding a giant death worm it seems like the player just sits inside the worm's body. (got no better way to describe it)

**Comment by mser7** [comment]
perhap the best way is to take a screenshot when it happen?

**Comment by AguilaDaddy** [comment]
https://i.imgur.com/CNsDZoM.png

**Comment by AlexModGuy** [comment]
fixed in 1.4.0
