### ISSUE TITLE
only death worm head is affected

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#564]
only the head hitbox are affected by the environment, such as burning, falling down, while the other hitboxes doesn't.

**Comment by mser7** [comment]
i realized this was poorly explained, let just imagine a 1 block wide hole, that doesn't make sense, the worm body hitboxes should also count if they're gonna fall down or not.

**Comment by AlexModGuy** [comment]
the worm hitboxes are solely for player interaction and combat purposes.
