### ISSUE TITLE
can't go up block while riding giant worm

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#567]
For some reason, you just can't go up a block when riding a giant death worm, the worm however can climb up 1 block when not being ridden

**Comment by Ormei** [comment]
Also vanilla horses are broken with this mod. Normally they can climb up one block steps, but with this mod they can't do that.

Tested with:
iceandfire-1.4.0-1.12.2.jar
llibrary-1.7.9-1.12.2.jar

Maybe it has the same cause.

**Comment by laserlemons** [comment]
Can confirm, all the horses on the server lost their ability to walk up blocks upon the installation of this mod.

**Comment by EvilDylan** [comment]
This also appears to break mod effects that give players this ability, such as Quark's changes to jump boost or Botania's sashes.
It affects hippogryphs as well.
