### ISSUE TITLE
Configurable egg hatch time?

### ISSUE THREAD

**Issue by JayZX535** [Alex-the-666/Ice_and_Fire#57]
Eggs take a really, REALLY long time to hatch.  I know that's understandable, but it honestly seems excessive.  I'd say one Minecraft day tops, or give us the option to configure how long it is.  Or perhaps there could be a way to speed up hatching?  I get that dragons are rare and special, but I'm not sure having such a long hatch time really adds to that.  It just feels kind of annoying to me.  If anything, I would say it's better to give dragons a long breeding cooldown than to give eggs a long hatch time.
Just some thoughts :)

**Comment by JayZX535** [comment]
Okay, this only seems to be the case with ice dragon eggs.  In fact, I cannot get those to hatch AT ALL.  But the fire dragon eggs hatched in a very reasonable amount of time, so my guess is that this is a bug with ice dragon eggs and not an actual issue.  Possibly related to Raptorfarian's bug report, only I appear to be having the opposite issue...

**Comment by raptorfarian** [comment]
As I stated on the forums please do not repost all ready noted bugs, Ice Dragon eggs are currently bugged and they do not take more a day to hatch. Have you been breeding them correctly i.e placing in fire or water?
