### ISSUE TITLE
[suggestion] break this mod up into smaller more manageable mods

### ISSUE THREAD

**Issue by kreezxil** [Alex-the-666/Ice_and_Fire#573]
Ice and Fire needs to concentrate on dragons. 

These new mobs you are adding should be in other mods. That way we can add them if you want. For instance If I don't want pixie homes, I wont add it.

This will make it easier for you to maintain and you won't be introducing new bugs like you just did.

**Comment by AlexModGuy** [comment]
1. this would make it extremely hard to maintain, not easier.
2.it's our decision want's added in and whats removed, and these things were decided fro some time(circa 2015/16)
3. this is not for suggestions, just bugs.

**Comment by kreezxil** [comment]
that's why I called it a suggest and not a demand
