### ISSUE TITLE
hippocampus and hippogryph forgot previous order

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#577]
order your mob to sit
hop on it and get off
it is now standing instead.

this is really frustrating since the hippocampus can sprint off immediately once unmounted.

**Comment by RealisticMC73309** [comment]
I know how you feel. I am not sure if there is any fix to it. If so then for now dismount your hippocampus on land and quickly right click it with a stick to get it to sit again. With hippogryphs go into a roofed off area(They don't take off when there is not enough space) and right click it with a stick. 

Hope this helps

**Comment by AlexModGuy** [comment]
should be fixed
