### ISSUE TITLE
dragons and hippogryphs attacks shared mounts

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#578]
So your tamed dragon and hippogryph will attack shared mounts even if they're tamed, in this case, its vanilla horses and hippocampi, they are treated as wild animal even if tamed by the player to these mobs, your tamed dragons will go rampage at your hippocampi. Tamed vanilla wolves doesn't attack tamed horses however.

**Comment by AlexModGuy** [comment]
shold be fixed in 1.5.0
