### ISSUE TITLE
dragons can't distinguish when to fly

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#584]
i was observing the behavior of dragons, they were killing hippogryphs, suddenly one hippogryph taken off while being targeted by the dragon. The dragon just crawling on the ground, chasing under the flying hippogryph, until much longer when it decided to perform the wings pin down attack and take off as well, flying after the prey. 

Dragon should know when to switch from grounding mode to flying mode, when it detect that its prey is too high for it to reach.

**Comment by AlexModGuy** [comment]
fixed
