### ISSUE TITLE
Snow Villagers Crash game 

### ISSUE THREAD

**Issue by AlmightyChan** [Alex-the-666/Ice_and_Fire#585]
[crash-2018-04-10_14.03.06-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/1896276/crash-2018-04-10_14.03.06-client.txt)
[crash-2018-04-10_14.11.46-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/1896278/crash-2018-04-10_14.11.46-client.txt)
This issue is keeping me and my friend off our server so please do what you can soon

**Comment by AlexModGuy** [comment]
>	at vazkii.neat.HealthBarRenderer.renderHealthBar(HealthBarRenderer.java:187)
take this up with vazkii
