### ISSUE TITLE
Incomplete snow village house spawning

### ISSUE THREAD

**Issue by JayZX535** [Alex-the-666/Ice_and_Fire#60]
I think this might be an issue that occurs with normal MC sometimes, too, but I haven't seen it with quite as much frequency... some of the villages have incomplete buildings.
![2016-11-23_17 37 54](https://cloud.githubusercontent.com/assets/14882581/20585708/02d87946-b1b2-11e6-9218-ca3edafe6735.png)

**Comment by LeonelSaberTooth** [comment]
ive seen this issue as well

**Comment by Kajtetto** [comment]
I have also seen this issue.

**Comment by Starza4TW** [comment]
This issue still exists as of v1.0.1.
![image](https://cloud.githubusercontent.com/assets/2940976/24842117/df944a08-1d60-11e7-8c86-0c078319cd84.png)

**Comment by Rutes** [comment]
also seen this, but you could just say it's a "feature" and that those houses were under construction, right? :)

**Comment by AlexModGuy** [comment]
doesnt seem to be an issue in 1.8.0
