### ISSUE TITLE
chunks do not render on a dragon

### ISSUE THREAD

**Issue by JayZX535** [Alex-the-666/Ice_and_Fire#61]
Riding my dragon while in creative caused unloaded chunks to fail to render when I entered them with my dragon.  The blocks were still there-- they were just invisible until I updated a block, which would then re-render the chunk.
This may be due to a conflict between the creative flight controls and the dragon flight controls.  I'm not positive-- haven't checked in survival yet......
![2016-11-23_20 25 15](https://cloud.githubusercontent.com/assets/14882581/20586673/16ff3bcc-b1bb-11e6-9d2f-ab53bcdf0245.png)
![2016-11-23_20 25 26](https://cloud.githubusercontent.com/assets/14882581/20586674/16ff5b84-b1bb-11e6-9124-58e9fe4fc339.png)
![2016-11-23_20 25 32](https://cloud.githubusercontent.com/assets/14882581/20586672/16fee05a-b1bb-11e6-9cd9-6326953517fc.png)

**Comment by JayZX535** [comment]
An update to this:
This seems to happen when you mount a dragon while flying in creative mode.  When I mounted from the air, it caused the glitch, but mounting from the ground did not.  Further testing is needed, though...

**Comment by AlexModGuy** [comment]
I havent noticed this in 1.5.2
