### ISSUE TITLE
[Not a bug] First survival impressions

### ISSUE THREAD

**Issue by JayZX535** [Alex-the-666/Ice_and_Fire#62]
Not sure where I should put this...?  I feel like posting in the forum thread would be too spoilerish haha.  Where would you like for us to post non-bug feedback?

This definitely adds weight to your actions in survival.  I ticked off a dragon within about three minutes of spawning and had to frantically burrow into a mountain to get away from it.  It completely demolished the area outside trying to get to me-- fire and scorched earth everywhere.
Survival is definitely more perilous now, and I like it.  I do still think dragons spawn way too frequently (and too close to spawn), but I definitely like the challenge!
![2016-11-23_22 31 06](https://cloud.githubusercontent.com/assets/14882581/20588782/b850a5d6-b1cc-11e6-9b03-2c692f73e429.png)

**Comment by raptorfarian** [comment]
Spawn frequencies have been noted and will be addressed.
