### ISSUE TITLE
1.4.0 Issues

### ISSUE THREAD

**Issue by Frosty8-0** [Alex-the-666/Ice_and_Fire#634]
Issue:  when riding dragons, they will bob up and down and engulf ur character, making 1st person riding impossible
(all for 1.4.0)
Issue 2: ice dragons (untested with fire) cant run up 1 block structures
Issue 3:  mined stone statues wont place
Issue 4:  Deathworms use the sand launching attack extremely often
thats all so far

**Comment by AlexModGuy** [comment]
fixed in 1.5.0
