### ISSUE TITLE
Dragon Riding Problem

### ISSUE THREAD

**Issue by random3421** [Alex-the-666/Ice_and_Fire#637]
I am in love with this mod! It is everything I've wanted involving dragons. However, with this recent update (April 7, 2018) the dragons can't get over blocks without having to fly over them. So instead of being able to ride the dragons across land without having to worry about pressing space, the dragons can't get over the blocks. This has affected how everything in minecraft rides as well. This is only a mounting issue, otherwise they have no problem getting over blocks. I really hope this is just a bug and it gets fixed at some point.

Really coming along great tho! Can't wait for the next update :)

**Comment by AlexModGuy** [comment]
fixed in 1.5.0
