### ISSUE TITLE
Dragons disappearing mid-combat

### ISSUE THREAD

**Issue by Jijuihin** [Alex-the-666/Ice_and_Fire#639]
I'm running a small server for myself and some friends, but we're having issues with dragons disappearing when we're trying to kill them via Melee fights. It seems related to https://github.com/Alex-the-666/Ice_and_Fire/issues/88 though I understand this was not fully looked into due to lack of correspondence. I initially asked on Discord if anyone else knew about this issue, and got 2 responses, one being a player agreeing this had happened to them, and the other saying I could fix it by not hunting dragons (extremely helpful...)

Out of 8 dragons (5 Fire, 3 Ice), that have been fought in Melee combat on my server, 5 of them have just disappeared from the map after they were taken down to about half health (with stage 3s, they seem to just sink through the ground and vanish, whereas stage 4/5s just disappear with no trace whatsoever). I really can't be sure how this happens, but I think it has something to do with the attack where the dragon picks you up/flies with you in their jaws/talons/whatever (hard to tell exactly from a 1st person view) - it has definitely happened right after this attack on at least 2 of the occasions, though.

It appears to happen much more often with Fire Dragons than Ice Dragons - we have only managed to kill one Fire Dragon successfully without it sinking into the ground and disappearing. Of the 3 Ice Dragons we fought, this has only happened with the stage 4 or 5 in a dragon lair. The 2 stage 3s we fought did not disappear.

I have tested it in a world with just Ice and Fire, HWYLA and JEI/a couple of JEI addons, and the bug still occurred against a stage 4/5 Fire Dragon in a lair, when it had roughly 80 HP left. It seemed to be just after a bite/grab attack again. I was using an Iced Dragon Bone Sword to fight it.

And just a note, this issue initially cropped up in version 1.3.1-1.12.2 and persisted after the update to 1.4.0-1.12.2 (the test world with just Ice and Fire/JEI/HWYLA is 1.4.0).

EDIT: I've been checking up on this issue for almost 2 months, waiting for the likely request to test again or supply more info, but you've not even acknowledged this issue. I get you've probably been busy, but I will no longer have time to test this in the future, so please don't ask me to give any further info or test in a newer build.

**Comment by mser7** [comment]
some guy told me a stage 5 emerged from underground to attack him then disappeared while they were fighting.

**Comment by RealisticMC73309** [comment]
Did you try going in the direction of the dragon? I noticed giant mobs tend to disappear from certain angles and distances. If the bug still happens then idk

**Comment by Jijuihin** [comment]
@MedievalPigeon213 This happens when fighting the dragons via melee attacks, so I'm right next to them when they disappear. They either sink through the ground (and yes, I have tried following, both by digging and when it happened again by spectator mode, but saw no trace of the dragons) or they just completely vanish altogether, without the sinking effect. Again, I searched around when this occurred, but no dragons were found nearby. One time was in a dragon nest with a Tier 5 ice dragon, so there weren't many places it could go, and even if it could, it would be hard to miss.

**Comment by kreezxil** [comment]
#896 is from my server which runs the World of Dragons pack of which I am the pack developer. To clarify what the players were saying in it because I don't think it was all that clear, and based on what I have read in this open thread it seems to be very true.

The dragons, all of them, especially the ones that are in lairs **near** bedrock, aka overworld bottom border, when they get to a certain hp they evade you by running away. however they seem to ignore the blocks that surround them to include bedrock and literally sink below the world. They haven't disappeared, they have literally gone under the world. As my staff members indicated they went into creative and got below the bedrock layer and there the dragons were. I suspect they found them there because of sounds or the occasional wing flapping up.

**Comment by AlexModGuy** [comment]
>especially the ones that are in lairs need bedrock

What does this mean?

**Comment by kreezxil** [comment]
Clearly that was a typo. the word is **near** not **need**.

**Comment by AlexModGuy** [comment]
#1448
