### ISSUE TITLE
Suggestion - setting that prevents Dragons from killing villagers

### ISSUE THREAD

**Issue by PurpleHel** [Alex-the-666/Ice_and_Fire#640]
I realize this isn't an option everyone would want to use, but I can't imagine I'm the only one who *would* use it. It's really frustrating to be exploring, especially in early game before I can effectively kill a dragon, and find a new village and most of the village is already dead.  I use MCA, and the guards from that mod can pretty much one shot every other hostile mob, (and they have 40 hearts) but dragons just kill *everyone*. From a plot standpoint, dragons staying away from human habitation would make sense.

**Comment by AlexModGuy** [comment]
fixed in 1.5.0

**Comment by PurpleHel** [comment]
Cool, thanks!
