### ISSUE TITLE
All Hatched Dragons are Untamed Ver. 1.0.1

### ISSUE THREAD

**Issue by TheColorDurple** [Alex-the-666/Ice_and_Fire#642]
We have a personal server up and for some reason this mod is bugged- hatched dragons are untamed no matter the circumstance for some reason. We put up a different server to test this issue and the dragons worked fine with all the mods running. We tried singleplayer too and it was A-OK. Its only on the server we are using [which is running the same modpack] that they don't seem to work!

The only relevant thing that I can think of is that the very first egg on the server hatched when the one who placed it was offline. None of us have a clue what could be going wrong. I was so excited for dragons, so to get some help would make my day! We are playing on 1.10.2, llibrary version 1.7.7

If there is a forcetame or spawn a tamed dragon command I would love to know.

**Comment by AlexModGuy** [comment]
1.10.2 is not supported anymore
