### ISSUE TITLE
[1.12.2] Make Sirens only spawn in oceans (not frozen oceans)?

### ISSUE THREAD

**Issue by KAfable** [Alex-the-666/Ice_and_Fire#643]
It's a minor bug but it does look weird when Sirens just spawn in a Frozen Ocean.
![image](https://user-images.githubusercontent.com/26587049/39087040-5b1e3af0-4568-11e8-91a6-76e0f4c4f74c.png)

**Comment by Bulldog83** [comment]
By the way, can you make configuration of spawn for mobs per biome (whitelist, or blacklist, or both)? And make spawnrate chance config for all mobs and objects?

**Comment by AlexModGuy** [comment]
fixed in 1.5.0
