### ISSUE TITLE
[1.12.2] {1.4.0} Ice and Fire mod disables block climbing of all mounts

### ISSUE THREAD

**Issue by Diamonddragon41** [Alex-the-666/Ice_and_Fire#644]
Reproducible: always
Forge ver: 14.23.3.2669
Mod ver: 1.4.0 for 1.12.2
Someone else here seemed to have a similar issue. When I have this mod installed, block climbing of every mount, even mounts from other mods, is disabled. This is only slightly annoying for horses etc. But makes dragons themselves almost unridable on the ground, since they fly instead of jumping. Normally, mounts can climb a ridge if it's only one block high, and large modded mounts are often enabled to climb ridges even higher than that.
When I remove this mod, all mounts can block climb again. When I run the game with the newest version of forge on a fresh install of minecraft with ONLY this mod, vanilla and Fire and Ice mounts still cannot climb blocks. I got everything fresh from curseforge myself, so you should be able to reproduce it pretty easily.

Gosh, I love this mod, and the monsters are so interesting and pretty, but the block climbing stuff is driving me up the wall! It makes dragons almost unridable on the ground, and messes with mounts from several of my other mods. Thanks for your time if you look over what might cause this issue.

**Comment by AlexModGuy** [comment]
dupe #633
