### ISSUE TITLE
Hippocampi spawning unregulated

### ISSUE THREAD

**Issue by DEX47** [Alex-the-666/Ice_and_Fire#648]
Can we get spawn rate control for the Hippocampi? They are starting to take over the seas.

**Comment by laserlemons** [comment]
I've also noticed a ton of them. Turning the spawn rate down in the config doesn't seem to help.

Edit: I read that as hippogryph. Both seem to have very high spawn rates.

**Comment by AlexModGuy** [comment]
@laserlemons spawn *rate* and spawn *weight* are different things. turning the spawn *rate* for the hippocampus down will make them spawn more frequently. turning the spawn *weight* for a hippogryph up will make them spawn more frequently. Config in 1.5.0 will be ajustable in game, and ive made hippocampus rarer aswell by default.
