### ISSUE TITLE
dragon helmet texture issues + silver armor lags the game

### ISSUE THREAD

**Issue by LeonelSaberTooth** [Alex-the-666/Ice_and_Fire#65]
the white dragon helmet makes the player's skin under it black, the gray dragon helmet has floating pixels in the front of it, and wearing a silver armor lags the game, even after taking it off.

![2016-11-24_17 53 18](https://cloud.githubusercontent.com/assets/20764209/20604575/c2c9b37e-b26f-11e6-84c1-7bb9507dd48d.png)

![2016-11-24_17 54 23](https://cloud.githubusercontent.com/assets/20764209/20604576/c2cfdac4-b26f-11e6-8c7b-c43be058cd0f.png)

**Comment by raptorfarian** [comment]
I'll take a look at the dragon helmet textures.

**Comment by Alex-the-666** [comment]
I'm not experiencing any lag with silver armor, and I'm running on a low end PC. are you sure that it is causing the lag?

**Comment by Alex-the-666** [comment]
I'm not able to replicate the black-cover on the face either.

**Comment by Alex-the-666** [comment]
was able to fix.
