### ISSUE TITLE
Scales and the water breathing poiton

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#650]
Scales should be used in a brewing stand with water bottles to make potions of water breathing. The current system is very unstable as you can put many things in the crafting table and still get a potion.
![screenshot 968](https://user-images.githubusercontent.com/23727270/39108489-874a8668-4696-11e8-80cb-c99de7049cd5.png)
![screenshot 969](https://user-images.githubusercontent.com/23727270/39108492-896279a6-4696-11e8-91d8-8db96eb4e63f.png)
![screenshot 970](https://user-images.githubusercontent.com/23727270/39108494-8b19a512-4696-11e8-93bd-de1101ee0fe3.png)
![screenshot 971](https://user-images.githubusercontent.com/23727270/39108497-8c51bc94-4696-11e8-8ff0-2822ffe3cab9.png)
![screenshot 972](https://user-images.githubusercontent.com/23727270/39108499-8df6a366-4696-11e8-836c-f06b2bc9641d.png)

**Comment by mser7** [comment]
Guy was too lazy to dig up the old files for this.

**Comment by EnderiumSmith** [comment]
brewing recipes are way easier than crafting than handles nbt. even making new effects is simpler. i dont see why it was done this way.

**Comment by AlexModGuy** [comment]
not an issue in 1.5.0
