### ISSUE TITLE
Hippocampus bugs

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#652]
1.when the hippocampus is sitting in the water it moves around a lot

2. the hippocampus is consistently able to jump 2 blocks on land, some times 3 if you can get it to bug out even more.

**Comment by Pyromanc3r** [comment]
I will also add:
3. Hippogryph Armor - this thing confuses with icon. I tried put it on Hippocampus lol and thought that it does not work;
4. Things can be put even there is no he has a chest (Shift+left click). But things can not be taken back.

**Comment by RealisticMC73309** [comment]
use normal horse armour on hippocampus
