### ISSUE TITLE
How can I remove dead dragons and petrified mobs?

### ISSUE THREAD

**Issue by djdanby** [Alex-the-666/Ice_and_Fire#654]
How can I remove dead dragons and petrified mobs? I have now on my map several dead dragons and several petrified animals standing around. How do I get those away?

**Comment by EvilDylan** [comment]
Hold-right-click dragon corpses to harvest their resources and remove them from the world. Using a bottle will give you blood as well.
Petrified (stone) mobs can be broken with a pickaxe and drop stone. If mined with a silk touch pick, they can be relocated.

**Comment by AlexModGuy** [comment]
read the in game documentation, the bestiary.
