### ISSUE TITLE
Texture missing

### ISSUE THREAD

**Issue by GansoHx** [Alex-the-666/Ice_and_Fire#659]
How i can fix this?  http://prntscr.com/jbhj0t

**Comment by AlexModGuy** [comment]
what version are you using?

**Comment by GansoHx** [comment]
Version 1.10.2

2018-04-29 16:00 GMT-03:00 Alexthe666 <notifications@github.com>:

**Comment by AlexModGuy** [comment]
1.10.2 versions are no longer supported. It's a conflict with AE2
