### ISSUE TITLE
Rendering Crash when rftools builder quarries pixie house

### ISSUE THREAD

**Issue by IronFractal** [Alex-the-666/Ice_and_Fire#660]
`Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at com.github.alexthe666.iceandfire.client.render.tile.RenderPixieHouse.render(RenderPixieHouse.java:36)
	at com.github.alexthe666.iceandfire.client.render.tile.RenderPixieHouse.func_192841_a(RenderPixieHouse.java:18)`

[crash-2018-04-28_20.38.29-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/1958456/crash-2018-04-28_20.38.29-client.txt)
[crash-2018-04-28_20.48.55-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/1958457/crash-2018-04-28_20.48.55-client.txt)

**Comment by AlexModGuy** [comment]
>iceandfire-1.3.1.jar

Update your mod! We're on version 1.4.0.

**Comment by R0gu3P403n1x** [comment]
I am not certain if it was the hovel, or the pixie that caused the crash, but when a player had both on screen it crashed the whole server. Just minecraft, not a BSOD or crashing windows, just for clarification.

Minecraft version is 1.12.2
Forge version is 14.23.3.2675
ice and fire version is 1.4.0

I do have other mods, so it could be a conflict there, but I am honestly not good enough at debugging to be certain.

[crash-2018-04-29_18.18.04-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/1959363/crash-2018-04-29_18.18.04-server.txt)
