### ISSUE TITLE
Horses can not overcome the height of one block

### ISSUE THREAD

**Issue by BlueWither** [Alex-the-666/Ice_and_Fire#662]
I am sorry if this problem is known to you.
When I am using this mod, I can not overcome the height of one block without jumping with a horse.(But the pig was overcome.)
My English is not good...

**Comment by aridhol** [comment]
This. This is related to my issue #665 - definitely noticed the same thing happening. It affects vanilla horses, and any mod that gives "step assist" to the player like a horse has by default.

**Comment by AlexModGuy** [comment]
fixed in 1.5.0
