### ISSUE TITLE
Deathworm and Conquest Reforged sand blocks not working

### ISSUE THREAD

**Issue by RealisticMC73309** [Alex-the-666/Ice_and_Fire#663]
Conquest Reforged changes deserts to spawn two new types of blocks. "Gravel and Sand" / "Vegetation and Sand" and "Natural Sandstone" These 3 blocks spawn with normal sand in deserts with CR(Conquest Reforged) and great inhibits the deathworm's ability to swim though the normal sand blocks. Encountering the CR blocks and being stopped. This forcing the deathworm to spawn more time above the sand then under it and well that defeats the scariness of it.

Perhaps if the deathworm can swim though these new blocks it will help the issue.

**Comment by AlexModGuy** [comment]
you'll need to ask the mod developer or CR to make those blocks have the material "sand". otherwise it wont work, they arent registered as sand
