### ISSUE TITLE
Snow villagers' skin do not correspond with their profession

### ISSUE THREAD

**Issue by PCAwesomeness** [Alex-the-666/Ice_and_Fire#666]
I've spawned snow villagers on my test world, and, for some reason, I got many villagers whose skin did not correspond with their profession, including a craftsman with a shaman skin, a shaman with a fisherman skin and a fishing spear in their hands, and a fisherman with a blue parka.

**Comment by mser7** [comment]
try carry one using Carry On

**Comment by BlueWither** [comment]
I think it is an important issue...

**Comment by mser7** [comment]
Atleast their profession isnt

**Comment by AlexModGuy** [comment]
dupe #369
