### ISSUE TITLE
Mod armor does not fit custom scaled player models.

### ISSUE THREAD

**Issue by Dakotsie** [Alex-the-666/Ice_and_Fire#67]
Probably not a bug, but the armor in this mod does not reshape itself to fit player models with custom sizes.

It's this: 
![2016-11-24_12 57 16](https://cloud.githubusercontent.com/assets/8368983/20608306/3c2590c8-b246-11e6-9525-b9d2bd425f5c.png)

Vs. this: 
![2016-11-24_12 58 01](https://cloud.githubusercontent.com/assets/8368983/20608313/4b8909fa-b246-11e6-8db5-e6005f0afe07.png)

**Comment by Alex-the-666** [comment]
why would it? we have no way to do that as i have no idea what mod increases custom player size. Also, you need to put the dragon egg in fire for it to hatch :P

**Comment by Dakotsie** [comment]
Aye, been wondering how to hatch the dang things for ages. I guess the armor would be something that the mod has custom support for, just thought I would bring it to your attention in case it was something you could support. This issue can be trashed now. :)
