### ISSUE TITLE
Conflict with StepUp by NotTooManyItems

### ISSUE THREAD

**Issue by Rensik** [Alex-the-666/Ice_and_Fire#673]
His last post makes me think he's already working with you on this, but I haven't seen anything official.

There seems to be a conflict between your mod and his that makes his mod stop working. What in your mod changes step height code, or would conflict with it? He's perusing all sources and coming up empty. I'm figuring reporting this issue to the mod author himself would help towards resolving this issue.

**Comment by NotTooManyItems** [comment]
I'm not working on it with the devs. However, I have compiled a version of Ice and Fire that works with StepUp. I'm figuring out how I want to release it and where.

**Comment by Rensik** [comment]
Works like a charm! Looking forward to an Official Release :)

**Comment by SgtRalphie** [comment]
Just thought I would say that this version crashes aether legacy because of duplicate entity id with the cockatrice, this might also be a problem with the upcoming release also.

[crash-2018-05-06_14.30.42-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/1977916/crash-2018-05-06_14.30.42-client.txt)

**Comment by NotTooManyItems** [comment]
The intention for my release was to fix a problem with step assist mods not working alongside Ice and Fire. I didn't change anything with entity id's. The source is a direct copy from the current master repo. So any errors found are from the current master repository.

**Comment by SgtRalphie** [comment]
Should I make this an issue separately for the next big update so the devs know of this issue before release?

**Comment by AlexModGuy** [comment]
dupe issue
