### ISSUE TITLE
The blindfold only partly covers the eyes

### ISSUE THREAD

**Issue by EnderiumSmith** [Alex-the-666/Ice_and_Fire#674]
![2018-05-05_21 59 08](https://user-images.githubusercontent.com/20334653/39667455-5efcf78a-50bf-11e8-862e-847f0bd7e03e.png)

**Comment by PCAwesomeness** [comment]
That's because your skin has the eyes a pixel lower than those on the regular player skin.

**Comment by EnderiumSmith** [comment]
no, all 2 tall eyes are like that. even for a steve skin only the bottom line covers it. the blindfold should be 1 layer lower so its centered on where 1 tall eyes are.

**Comment by AguilaDaddy** [comment]
Sorry man but this isn't even a bug. If u cant deal with how you look in game then just change your skin or quit the mod

**Comment by AguilaDaddy** [comment]
and that blindfold u suggest would be too big to be a blindfold. Itd look like a helmet. And other skins have their eyes on the lowest part so youre not only being selfish but also excluding others

**Comment by AlexModGuy** [comment]
thats just your weird-ass skin with low hanging eyeballs. you can fix this by making a better skin
