### ISSUE TITLE
Crash: ClassCastException: java.lang.Byte cannot be cast to java.lang.Boolean

### ISSUE THREAD

**Issue by olol5620** [Alex-the-666/Ice_and_Fire#678]
The following crashes happened when I was underground. The minimap showed me a little dragon hoard above ground.

Thanks in advance

[crash-2018-05-09_10.19.35-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/1986994/crash-2018-05-09_10.19.35-client.txt)
[crash-2018-05-09_10.24.15-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/1986995/crash-2018-05-09_10.24.15-client.txt)
[crash-2018-05-09_10.30.06-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/1986996/crash-2018-05-09_10.30.06-client.txt)

**Comment by AlexModGuy** [comment]
mod conflict; another mob(presumably one that adds in more mobs) is assigning properties to vanilla classes instead of its own
