### ISSUE TITLE
1.10 Missing Texture

### ISSUE THREAD

**Issue by Bradleh** [Alex-the-666/Ice_and_Fire#679]
Hi , I am trying to play on the 1.10 version of the mod and for some reason the majority of the textures and models are not rendering, I saw other users have exerpiereced this issue but could not find a fix , i have tried multiple versions of LLibary , re-set all of my video settings and reloaded textures within my game , looking in the .jar file i can see all of the textures and models are present but i have no idea why they are not rending within the game. Please help !

**Comment by PlatinumFox** [comment]
@Bradleh if you have the applied energistics mod it has been know to cause issues with the textures. also 1.10 version is no longer supported so the only true fix (other than finding out what mod incompatibility it could be and removing it) is to upgrade to the 1.12.2 version of the mod.

**Comment by Bradleh** [comment]
@PlatinumFox Thank you for the reply , i shall look into thid potential conflict. Once i am done with my older play-through i am looking forward to playing on your mor recent releases. Cheers.

**Comment by Bradleh** [comment]
YES , It was applied enegreestics causding the conflict , thank you !

**Comment by PlatinumFox** [comment]
@Bradleh np, glad to help, and they are not my releases lol Alexthe666 is the creator of the mod, i am just a fan who likes to help other people with problems every now and then. have fun tho and consider updating, theres a ton of cool new features that your missing out on
