### ISSUE TITLE
bugs?/broken features and a misspelling

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#68]
"but are mostly or crafting tools and weapons" i think or is supposed to be "for"
![2016-11-24_14 28 57](https://cloud.githubusercontent.com/assets/23727270/20608807/1706947e-b253-11e6-9291-01325950383c.png)

in my creative test world a huge upper stage dragon lair did not load in properly.

![2016-11-24_14 17 54](https://cloud.githubusercontent.com/assets/23727270/20608831/44c59ab8-b253-11e6-8df8-9ac2ffce7aa1.png)

also dragons are flying too low and getting stuck in trees, this makes it too easy to rob/loot their nests above ground. (i have 2 worlds a creative and survival the picture below is an example of what i am seeing in survival)

![2016-11-23_21 35 51](https://cloud.githubusercontent.com/assets/23727270/20608855/ba060b8c-b253-11e6-939c-bd6960caf133.png)

also the beastiary says to craft dragon armor the same way you craft normal armor but use blocks, i did this several times and it did not work

**Comment by Kusark** [comment]
Yeah, dragons do fly way too low.
