### ISSUE TITLE
Feeding TIme

### ISSUE THREAD

**Issue by Niconoko** [Alex-the-666/Ice_and_Fire#680]
Not quite a problem here but..,
I have been using a mod that extended the time cycle in the game, and feeding my Silvia is something that become too often, so If it's possible to have **a config to slow down the hunger of tamed Wyvern**, that would be nice.

Thanks in Adv. :3

**Comment by CommanderAM** [comment]
i second this request. or maybe add some kind of feeding trough that when filled with meat increases the Food of nearby tamed dragons/wyverns in a radius around it?
