### ISSUE TITLE
[1.12.2]Client-side crash java.lang.ClassCastException

### ISSUE THREAD

**Issue by Lunetouche** [Alex-the-666/Ice_and_Fire#681]
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean

Crashed while exploring and now attempting to login to server results in a client-side crash.
This has started happening to quite a few of the players on the server at wide spread locations, suspected incompatibility with thaumcraft (was added to the pack)
Version is 1.3.1
https://gist.github.com/Lunetouche/4d84b7a82258b6758f9eb6a0d4f5b7e4
Note: optifine is used for that crash log, however crash still occurs without it.

**Comment by AlexModGuy** [comment]
update mod, conflict with other mods possibly thaumcraft

**Comment by Discomanco** [comment]
Still an issue in I&F 1.4.0
https://pastebin.com/VyCqULwu

**Comment by olol5620** [comment]
can confirm, my issue (same as above) didn't happend when Thaumcraft is removed

**Comment by Lunetouche** [comment]
So looking over the other crash logs, i noticed one thing in common. B13 of thaumcraft. We didnt start having these crashes until we upgraded from B12 to B13, so im wondering if the api changes between the two versions are causing this (saw the api included in code as updated 20 days ago, with B13 being more recent than that)

**Comment by olol5620** [comment]
so I thought, but downgrading to B12 didn't prevent the crash.
Odly the crash only occurred after hours of playing.
New World no crashes

**Comment by Discomanco** [comment]
It's very inconsistent, and doesn't happen with every dragon.
Some dragons I load fine, others crashes me (I&F 1.4.0, TCB13).
Killed a total of 9 dragons so far, 3 of them crashed me once

**Comment by olol5620** [comment]
for me it was pretty consistent: I play on my local server and after I encounter this crash there was no way to me playing. I had to move my player in MCEdit.

**Comment by AlexModGuy** [comment]
@Lukas45 we checked through this issue last time and its definitely not IAF's issue. Mods that add new mobs might be registering their properties incorrectly. I suspect  animania   1.4.7 or twighlightforest

**Comment by olol5620** [comment]
I can't be an issue of animania, I didn't have it and it crashes: #678 
I have two new information pieces for you: 
As I removed TC-beta the server console spammed it removed some entity-properties, my client didn't crash.
As I moved my world form a local server (with a rollback to prior removing TC therefore same Client-Crash:Cast-Class-Exc.) to a singleplayer world, the game seems fine, so maybe it's an sync issue?
