### ISSUE TITLE
Stage 5 Dragons Disapearing

### ISSUE THREAD

**Issue by EerieKitsune** [Alex-the-666/Ice_and_Fire#682]
I'm running a personal server with some close friends and for some reason Tamed Dragons disappear. It's only when they're at stage 5, It happens the fastest when mounted upon them, typically mid flight. Dragons who aren't mounted will disappear too, but after a few (Real life) hours of reaching stage 5. 
I went into the Config to disable Dragons de-spawning in hopes it would resolve this problem but unfortunately It didn't fix this issue.

A side note; Sometimes when logging onto the server Dragons that are sitting will change to wandering.
I'm using forge version 1.12.2-14.23.3.2655

**Comment by AlexModGuy** [comment]
dupe #344
