### ISSUE TITLE
Upon releasing tamed dragon from mob-capsule, no dragon model.

### ISSUE THREAD

**Issue by DexterCostume** [Alex-the-666/Ice_and_Fire#685]
The same effect occurs with the dragon horn as well, I assume any capture/release tool will act the same.

mob imprisonment tool _(Industrial forgoing)_ * right clicks on ground (tree tops) 

* Dragon  (health points) *  <- name tag

 " Tamed dragon has no model, but the name plate is hovering, and sounds occur as if the dragon is still there "

This problem has been occurring in my private server, when releasing dragons from capsules far from the spawn area.

**Comment by DexterCostume** [comment]
Sometimes you get to see your dragon again, some times the horn empties, and no dragon comes out. And your dragon is gone forever.

**Comment by AlexModGuy** [comment]
dupe #1447
