### ISSUE TITLE
Ice and fire dragon mod. Dragons move away when I get close to them

### ISSUE THREAD

**Issue by PH0ENIX222** [Alex-the-666/Ice_and_Fire#686]
I'm trying to kill some dragons, but when I get anywhere of a 15 meter vicinity of them, they move away, no matter how high they are off the ground. Fix? And, I don't seem to be getting ANY rewards for killing a dragon, not even EXP

**Comment by RealisticMC73309** [comment]
That is their behaviour. And right click the dead dragon with an open hand to claim your rewards.
