### ISSUE TITLE
crash when cyclops attempts to bite the head off of a pneumaticcraft turret

### ISSUE THREAD

**Issue by lag42** [Alex-the-666/Ice_and_Fire#687]
crash log here:
https://paste.dimdev.org/emebiyacez.txt

mod version is 1.12.2-1.4.0

**Comment by desht** [comment]
Looks like it's crashing in ``EntityPlayerMP#setPositionAndUpdate()`` - the sentry turret uses a ``FakePlayer`` to manage firing the minigun, and its FakePlayer doesn't have an initialised net connection.  Looks like ``dismountRidingEntity()`` is what leads to this - I'm guessing the cyclops is trying to pick the turret up?

Can possibly be worked around by giving the turret's fake player a dummy connection.

**Comment by desht** [comment]
Can you give build ~~193~~ 194 a go from http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/ and see if that behaves better?

**Comment by lag42** [comment]
sorry for the late response, it works fine with that build
