### ISSUE TITLE
Minor config layout niggle

### ISSUE THREAD

**Issue by brisingraerowing** [Alex-the-666/Ice_and_Fire#690]
In the config file, a couple of Death Worm configs are under the Siren section. I would think they should be under their own section. Just a minor issue.

**Comment by AlexModGuy** [comment]
delete your config every update should fix this

**Comment by brisingraerowing** [comment]
Uh, no. [This](https://gist.github.com/BrisingrAerowing/a39ae3ce90e5bb909f496df96eb90085) is my config file from a fresh instance on version 1.4.0-1.12.2. There are two Death Worm configs in the Siren section at the bottom of the file.

**Comment by AlexModGuy** [comment]
will be fixed in 1.5.0
