### ISSUE TITLE
Crash Server [1.12.2] [Ice & Fire - 1.4.0]

### ISSUE THREAD

**Issue by Kocytos** [Alex-the-666/Ice_and_Fire#694]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  llibrary (llibrary-core-1.0.5-1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  BCModPlugin (backpacks+1.12.2+-+3.4.4.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.12 (2).jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.8-core.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 5/25/18 6:10 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.github.alexthe666.iceandfire.entity.FireExplosion.func_77278_a(FireExplosion.java:148)
	at com.github.alexthe666.iceandfire.entity.EntityDragonFireCharge.func_70227_a(EntityDragonFireCharge.java:141)
	at net.minecraft.entity.projectile.EntityFireball.func_70071_h_(EntityFireball.java:98)
	at com.github.alexthe666.iceandfire.entity.EntityDragonFireCharge.func_70071_h_(EntityDragonFireCharge.java:59)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.github.alexthe666.iceandfire.entity.FireExplosion.func_77278_a(FireExplosion.java:148)
	at com.github.alexthe666.iceandfire.entity.EntityDragonFireCharge.func_70227_a(EntityDragonFireCharge.java:141)
	at net.minecraft.entity.projectile.EntityFireball.func_70071_h_(EntityFireball.java:98)
	at com.github.alexthe666.iceandfire.entity.EntityDragonFireCharge.func_70071_h_(EntityDragonFireCharge.java:59)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: iceandfire:dragonfirecharge (com.github.alexthe666.iceandfire.entity.EntityDragonFireCharge)
	Entity ID: 187764
	Entity Name: Dragon Fire Charge
	Entity's Exact location: 1246.35, 63.48, 383.77
	Entity's Block location: World: (1246,63,383), Chunk: (at 14,3,15 in 77,23; contains blocks 1232,0,368 to 1247,255,383), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,0,0 to 1535,255,511)
	Entity's Momentum: -0.82, -0.47, 0.71
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['Feuerschimmer'/134657, l='world', x=1338.10, y=92.00, z=468.08]]
	Chunk stats: ServerChunkCache: 579 Drop: 0
	Level seed: 1776300521456954833
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-156,64,144), Chunk: (at 4,4,0 in -10,9; contains blocks -160,0,144 to -145,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 7018671 game time, 1457444 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 98845 (now: false), thunder time: 141529 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.4.0-121-generic
	Java Version: 1.8.0_162, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 8896881480 bytes (8484 MB) / 12699303936 bytes (12111 MB) up to 12699303936 bytes (12111 MB)
	JVM Flags: 2 total; -Xmx12288M -Xms12288M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.3.2691 75 mods loaded, 75 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                   | Version                      | Source                                           | Signature                                |
	|:--------- |:-------------------- |:---------------------------- |:------------------------------------------------ |:---------------------------------------- |
	| UCHIJAAAA | minecraft            | 1.12.2                       | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | mcp                  | 9.42                         | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | FML                  | 8.0.99.99                    | forge-1.12.2-14.23.3.2673-universal.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                | 14.23.3.2691                 | forge-1.12.2-14.23.3.2673-universal.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | appliedenergistics2  | rv5-stable-11                | appliedenergistics2-rv5-stable-11.jar            | None                                     |
	| UCHIJAAAA | bdlib                | 1.14.3.12                    | bdlib-1.14.3.12-mc1.12.2.jar                     | None                                     |
	| UCHIJAAAA | ae2stuff             | 0.7.0.4                      | ae2stuff-0.7.0.4-mc1.12.2.jar                    | None                                     |
	| UCHIJAAAA | orbis_api            | 1.12.2-1.1.2                 | orbis_api-1.12.2-1.1.2.jar                       | None                                     |
	| UCHIJAAAA | aether               | 1.12.2-1.0.5                 | aether_ii-1.12.2-1.0.5.jar                       | None                                     |
	| UCHIJAAAA | examplemod           | 1.0                          | Animus-2.0.0.jar                                 | None                                     |
	| UCHIJAAAA | guideapi             | 1.12-2.1.5-60                | Guide-API-1.12-2.1.5-60 (1).jar                  | None                                     |
	| UCHIJAAAA | bloodmagic           | 1.12.2-2.2.12-97             | BloodMagic-1.12.2-2.2.12-97.jar                  | None                                     |
	| UCHIJAAAA | animus               | 1                            | Animus-2.0.0.jar                                 | None                                     |
	| UCHIJAAAA | applecore            | 3.1.1                        | AppleCore-mc1.12.2-3.1.1.jar                     | None                                     |
	| UCHIJAAAA | jei                  | 4.9.1.191                    | jei_1.12.2-4.9.1.191.jar                         | None                                     |
	| UCHIJAAAA | appleskin            | 1.0.9                        | AppleSkin-mc1.12-1.0.9.jar                       | None                                     |
	| UCHIJAAAA | backpacks16840       | 3.4.4                        | backpacks+1.12.2+-+3.4.4.jar                     | None                                     |
	| UCHIJAAAA | baubles              | 1.5.2                        | Baubles-1.12-1.5.2.jar                           | None                                     |
	| UCHIJAAAA | betterbuilderswands  | 0.11.1                       | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar  | None                                     |
	| UCHIJAAAA | bibliocraft          | 2.4.4                        | BiblioCraft[v2.4.4][MC1.12.2].jar                | None                                     |
	| UCHIJAAAA | biomesoplenty        | 7.0.1.2390                   | BiomesOPlenty-1.12.2-7.0.1.2390-universal.jar    | None                                     |
	| UCHIJAAAA | codechickenlib       | 3.1.8.341                    | CodeChickenLib-1.12.2-3.1.8.341-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | redstoneflux         | 2.0.1                        | RedstoneFlux-1.12-2.0.1.2-universal (1).jar      | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | brandonscore         | 2.4.2                        | BrandonsCore-1.12-2.4.2.157-universal (1).jar    | None                                     |
	| UCHIJAAAA | carryon              | 1.9                          | CarryOn+MC1.12.2+v1.9 (1).jar                    | None                                     |
	| UCHIJAAAA | chineseworkshop      | 1.1.0.0                      | ChineseWorkshop_1.12.2-1.1.0.0 (1).jar           | None                                     |
	| UCHIJAAAA | chisel               | MC1.12.2-0.2.0.31            | Chisel-MC1.12.2-0.2.0.31.jar                     | None                                     |
	| UCHIJAAAA | chococraft           | 0.9.1.52                     | chococraft_1.12.1-0.9.1.52.jar                   | None                                     |
	| UCHIJAAAA | containerfix         | 1.0                          | ContainerFix+MC1.12.2+v1.0 (1).jar               | None                                     |
	| UCHIJAAAA | customnpcs           | 1.12                         | CustomNPCs_1.12.2(13may18).jar                   | None                                     |
	| UCHIJAAAA | ptrmodellib          | 1.0.2                        | PTRLib-1.0.2.jar                                 | None                                     |
	| UCHIJAAAA | props                | 2.6.0                        | Decocraft-2.6.0_1.12.2.jar                       | None                                     |
	| UCHIJAAAA | draconicevolution    | 2.3.11                       | Draconic-Evolution-1.12-2.3.11.290-universal.jar | None                                     |
	| UCHIJAAAA | lootablebodies       | 2.4.0                        | DrCyanosLootableBodies_1.12-2.4.0.jar            | None                                     |
	| UCHIJAAAA | erebus               | 1.0.22                       | Erebus-1.0.22 (1).jar                            | None                                     |
	| UCHIJAAAA | waila                | 1.8.25                       | Hwyla-1.8.25-B40_1.12.jar                        | None                                     |
	| UCHIJAAAA | extracells           | 2.5.13                       | ExtraCells-1.12.2-2.5.13a58.jar                  | None                                     |
	| UCHIJAAAA | fairylights          | 2.1.2                        | fairylights-2.1.2-1.12.x.jar                     | None                                     |
	| UCHIJAAAA | familiarfauna        | 1.0.10                       | FamiliarFauna-1.12.2-1.0.10.jar                  | None                                     |
	| UCHIJAAAA | fastleafdecay        | v14                          | FastLeafDecay-v14.jar                            | None                                     |
	| UCHIJAAAA | hopperducts          | 1.5                          | hopperducts-mc1.12-1.5 (1).jar                   | None                                     |
	| UCHIJAAAA | llibrary             | 1.7.11                       | llibrary-1.7.11-1.12.2.jar                       | None                                     |
	| UCHIJAAAA | iceandfire           | 1.4.0                        | iceandfire-1.4.0-1.12.2 (1).jar                  | None                                     |
	| UCHIJAAAA | ic2                  | 2.8.79-ex112                 | industrialcraft-2-2.8.79-ex112.jar               | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | inventorytweaks      | 1.64-dev+release.110.b4fac73 | InventoryTweaks-1.64-dev.jar                     | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | ironchest            | 1.12.2-7.0.42.827            | ironchest-1.12.2-7.0.42.827.jar                  | None                                     |
	| UCHIJAAAA | jjcoa                | 1.0.9                        | JJ+Coats+of+Arms+1.12-1.12.2-v1.0.9.jar          | None                                     |
	| UCHIJAAAA | journeymap           | 1.12.2-5.5.2b1               | journeymap-1.12.2-5.5.2b1.jar                    | None                                     |
	| UCHIJAAAA | malisiscore          | 1.12.2-6.4.0                 | malisiscore-1.12.2-6.4.0.jar                     | None                                     |
	| UCHIJAAAA | malisisdoors         | 1.12.2-7.3.0                 | malisisdoors-1.12.2-7.3.0.jar                    | None                                     |
	| UCHIJAAAA | mekanism             | 1.12.2-9.4.10.345            | Mekanism-1.12.2-9.4.10.345.jar                   | None                                     |
	| UCHIJAAAA | mekanismgenerators   | 9.4.10                       | MekanismGenerators-1.12.2-9.4.10.345.jar         | None                                     |
	| UCHIJAAAA | mekanismtools        | 9.4.10                       | MekanismTools-1.12.2-9.4.10.345.jar              | None                                     |
	| UCHIJAAAA | morpheus             | 1.12-3.3.2                   | Morpheus-1.12-3.3.2 (2).jar                      | None                                     |
	| UCHIJAAAA | netherportalfix      | 5.3.13                       | NetherPortalFix_1.12.1-5.3.13 (2).jar            | None                                     |
	| UCHIJAAAA | p455w0rdslib         | 2.0.29                       | p455w0rdslib-1.12-2.0.29.jar                     | None                                     |
	| UCHIJAAAA | placeableitems       | 3.3                          | placeableitems-3.3 (2).jar                       | None                                     |
	| UCHIJAAAA | thaumcraft           | 6.1.BETA13                   | Thaumcraft-1.12.2-6.1.BETA13.jar                 | None                                     |
	| UCHIJAAAA | planarartifice       | 0.0.8                        | planarartifice-0.8.jar                           | None                                     |
	| UCHIJAAAA | roguelike            | 1.8.0                        | RoguelikeDungeons-1.12.2-1.8.0.jar               | None                                     |
	| UCHIJAAAA | rustic               | 1.0.5                        | rustic-1.0.5.jar                                 | None                                     |
	| UCHIJAAAA | sgcraft              | 1.13.2                       | SGCraft-1.1-mc1.12.2.jar                         | None                                     |
	| UCHIJAAAA | soulshardsrespawn    | 1.12.2-1.0.5-7               | SoulShardsRespawn-1.12.2-1.0.5-7 (1).jar         | None                                     |
	| UCHIJAAAA | spartanshields       | 1.4.1                        | SpartanShields-1.12.2-1.4.1 (1).jar              | None                                     |
	| UCHIJAAAA | tcinventoryscan      | 2.0.10                       | ThaumicInventoryScanning_1.12.2-2.0.10 (2).jar   | None                                     |
	| UCHIJAAAA | thaumicperiphery     | 0.2.3                        | thaumicperiphery-0.2.3.jar                       | None                                     |
	| UCHIJAAAA | thebetweenlands      | 3.3.8                        | TheBetweenlands-3.3.8-universal.jar              | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| UCHIJAAAA | twilightforest       | 3.7.424                      | twilightforest-1.12.2-3.7.424-universal (1).jar  | None                                     |
	| UCHIJAAAA | vampirism            | 1.4.2                        | Vampirism-1.12.2-1.4.2.jar                       | None                                     |
	| UCHIJAAAA | teamlapen-lib        | 1.4.2                        | Vampirism-1.12.2-1.4.2.jar                       | None                                     |
	| UCHIJAAAA | wanionlib            | 1.12.2-1.5                   | WanionLib-1.12.2-1.5.jar                         | None                                     |
	| UCHIJAAAA | waystones            | 4.0.43                       | Waystones_1.12.2-4.0.43.jar                      | None                                     |
	| UCHIJAAAA | wct                  | 3.9.64                       | WirelessCraftingTerminal-1.12.2-3.9.64.jar       | None                                     |
	| UCHIJAAAA | immersiveengineering | 0.12-82                      | ImmersiveEngineering-0.12-82.jar                 | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAAAA | unidict              | 1.12.2-2.5c                  | UniDict-1.12.2-2.5c.jar                          | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  invtweaks.forge.asm.ContainerTransformer
llibrary (llibrary-core-1.0.5-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
BCModPlugin (backpacks+1.12.2+-+3.4.4.jar)
  brad16840.core.ClassTransformer
AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
CTMCorePlugin (CTM-MC1.12-0.2.3.12 (2).jar)
  team.chisel.ctm.client.asm.CTMTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.8-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	List of loaded APIs: 
		* AppleCoreAPI (3.1.0) from AppleCore-mc1.12.2-3.1.1.jar
		* appliedenergistics2|API (rv5) from appliedenergistics2-rv5-stable-11.jar
		* Baubles|API (1.4.0.2) from WirelessCraftingTerminal-1.12.2-3.9.64.jar
		* BetterWithModsAPI (Beta 0.6) from AppleSkin-mc1.12-1.0.9.jar
		* BetweenlandsAPI (1.10.0) from TheBetweenlands-3.3.8-universal.jar
		* bloodmagic-api (2.0.0) from BloodMagic-1.12.2-2.2.12-97.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12.2-0.2.0.31.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-0.2.0.31.jar
		* Core (0.1) from CustomNPCs_1.12.2(13may18).jar
		* Core|Blocks (0.1) from CustomNPCs_1.12.2(13may18).jar
		* Core|Constants (0.1) from CustomNPCs_1.12.2(13may18).jar
		* Core|Entities (0.1) from CustomNPCs_1.12.2(13may18).jar
		* Core|Entities|Data (0.1) from CustomNPCs_1.12.2(13may18).jar
		* Core|Entities|Data|Role (0.1) from CustomNPCs_1.12.2(13may18).jar
		* Core|Events (0.1) from CustomNPCs_1.12.2(13may18).jar
		* Core|Handlers (0.1) from CustomNPCs_1.12.2(13may18).jar
		* Core|Handlers|Data (0.1) from CustomNPCs_1.12.2(13may18).jar
		* CSLib|API (1.0.1) from PTRLib-1.0.2.jar
		* ctm-api (0.1.0) from CTM-MC1.12-0.2.3.12 (2).jar
		* ctm-api-events (0.1.0) from CTM-MC1.12-0.2.3.12 (2).jar
		* ctm-api-models (0.1.0) from CTM-MC1.12-0.2.3.12 (2).jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12-0.2.3.12 (2).jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12-0.2.3.12 (2).jar
		* DraconicEvolution|API (1.3) from Draconic-Evolution-1.12-2.3.11.290-universal.jar
		* Guide-API|API (2.0.0) from Guide-API-1.12-2.1.5-60 (1).jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-82.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-82.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.2b1.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.2b1.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.2b1.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.2b1.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.2b1.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.9.1.191.jar
		* MekanismAPI|core (9.0.0) from Mekanism-1.12.2-9.4.10.345.jar
		* MekanismAPI|energy (9.0.0) from Mekanism-1.12.2-9.4.10.345.jar
		* MekanismAPI|gas (9.0.0) from Mekanism-1.12.2-9.4.10.345.jar
		* MekanismAPI|infuse (9.0.0) from Mekanism-1.12.2-9.4.10.345.jar
		* MekanismAPI|laser (9.0.0) from Mekanism-1.12.2-9.4.10.345.jar
		* MekanismAPI|transmitter (9.0.0) from Mekanism-1.12.2-9.4.10.345.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.12.2-9.4.10.345.jar
		* ProjectEAPI (1.9.4-1.0.0) from p455w0rdslib-1.12-2.0.29.jar
		* Thaumcraft|API (6.0.2) from Thaumcraft-1.12.2-6.1.BETA13.jar
		* VampirismAPI (1.4) from Vampirism-1.12.2-1.4.2.jar
		* WailaAPI (1.3) from Hwyla-1.8.25-B40_1.12.jar
		* wct|api (1.1) from WirelessCraftingTerminal-1.12.2-3.9.64.jar
	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:ON, Mekanism:ON, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 10; [EntityPlayerMP['Feuerschimmer'/134657, l='world', x=1338.10, y=92.00, z=468.08]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by AlexModGuy** [comment]
#740
