### ISSUE TITLE
Fire dragons never stop eating

### ISSUE THREAD

**Issue by EnderiumSmith** [Alex-the-666/Ice_and_Fire#695]
If you spawn a fire dragon and keep spawning pigs nearby the dragon will go though them one by one, with the occasional fire breath. The ice dragon does not do this. even after being freshly spawned it wont immediately go after animals.

Also it seems that the dragon is able to damage itself with the explosive breath and it wont regen health back after eating.

**Comment by AlexModGuy** [comment]
fixed
