### ISSUE TITLE
Crash with NetherEx mod

### ISSUE THREAD

**Issue by Bulldog83** [Alex-the-666/Ice_and_Fire#696]
https://gist.github.com/Bulldog83/638cbbf6256ce7342d591efdfaf171cd

**Comment by Bulldog83** [comment]
And same, but without NEx: https://gist.github.com/Bulldog83/3bc1819e757723afcecf8ddb524e2991

**Comment by DWX12** [comment]
I'm using NEX and haven't had any issues, but as your report states:

 Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)

Try removing Foam Fix.  NEX doesn't seem to be the issue or the main cause.

**Comment by clubpetey** [comment]
I am receiving the same crash, also have NetherEx installed, but many other MODs as well. Tried removing foamFix, that's not the issue.

**Comment by clubpetey** [comment]
Also determined this issue only appears in Multiplayer mode.

**Comment by Bulldog83** [comment]
I have a very large set of mods and without FoamFIX it uses too much RAM. Unfortunately, I can't remove it. And yes, this crash only appears in multiplayer mode. I tried to run modifications in single player mode, everything was stable.
Sometimes there is NetherEx in the log, sometimes not. But the problem is always the same: java.lang.ClassCastException.

**Comment by CombatZAK** [comment]
Not running FoamFix or NetherEx; still seeing this issue. [crash report.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/2081756/crash.report.txt)

I did not experience this issue when running llibrary-1.7.9-1.12.2. To note, this version of LLibrary had an issue with its coremod where it would fail to load in 1.12.2 (expecting MC version 1.12). This was corrected in LLibrary version 1.10, so it's possible there is a bad interaction here.

**Comment by CombatZAK** [comment]
3 days ago, LLibrary updated from 1.7.12 to another file with the same version. My pack had this file on its server, and this was causing the crash, I just confirmed. Reverting to the previous LLibrary version server-side (also numbered 1.7.12) caused the crash to stop occurring.

**Comment by Iastre** [comment]
I recently started having this same issue. Through process of elimination, I discovered the issues occur when running the latest version of Thaumcraft, BETA16. If you have Thaumcraft installed, that may well be the source of the problem.

**Comment by AlexModGuy** [comment]
#740
