### ISSUE TITLE
Hippogryphs still use the old flying AI

### ISSUE THREAD

**Issue by EnderiumSmith** [Alex-the-666/Ice_and_Fire#697]
The hippogryphs didnt get the new flying AI the dragons have so once they take flight they practically never land.

**Comment by PCAwesomeness** [comment]
I'd be inclined to agree, but let's wait until the Stymphalian Birds get released before we say anything major

(One thing that definitely needs to go, however, is the turning animations and the loud Ender Dragon wing noises)

**Comment by AlexModGuy** [comment]
they dont
