### ISSUE TITLE
Gorgon temples not spawning

### ISSUE THREAD

**Issue by DWX12** [Alex-the-666/Ice_and_Fire#698]
Haven't seen anyone else with this issue, but could be a conflict with another world gen mod in my pack. I have not come across a single gorgon temple; however, everything thing else has generated just fine: cyclops', dragon roosts/lairs, pixie villages, etc.

No clue what the problem is or why it's happening or possibly what mod it's conflicting with. Strange that it only effects gorgon temples. I'm using a modified version of the latest 1.4.0 (unofficial), the step up fix; however, I still had the same problem before switching to that version.

**Comment by AlexModGuy** [comment]
could you test this by creating an all beach-biome world(in the Custom world option)? that seems to work

**Comment by st753m** [comment]
I'm having the same problem (version 1.4.0).  I did the Custom beach-only world test, looking both above and below ground with spectator mode.  Plenty of cyclopes and buried dragons, but not a single gorgon.

**Comment by DWX12** [comment]
I had first used the Dregora mod that used the OTG world generator, which put me in a stupidly huge beach biome. Main generation was Cyclops caves/spheres. I've had plenty of worlds after that, mainly using the realistic world generation from Quark, but also tested using standard minecraft generation. Everything else generated just fine except gorgon temples.

I have plenty of world generation from other mods, but everything, except gorgon temples, are spawning. I even have the spawn rate in the config set to 1:1, still nothing.

**Comment by st753m** [comment]
I decided to test another custom beach-only world, this time in a new profile with only forge, ice and fire, and LLibrary installed.  I still found tons of cyclopes and dragons, and no gorgons.

**Comment by DWX12** [comment]
Like I've stated, every world gen item from every mod I have installed is generating, including ice and fire, except for the gorgon temples. Maybe the schematics got removed by accident, code got jumbled around, or whatever else. The gorgon mob and related items are still in the mod and work fine, just no way for her to spawn naturally in survival.

Hopefully by next update it'll be fixed.

**Comment by AlexModGuy** [comment]
yeah they were trying to generate in the sky, not on the ground.
