### ISSUE TITLE
Sirens singing shader effect conflicting with the night vision shader from Vic's modern warfare mod

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#700]
Vic's modern warfare has a night vision goggles, but instead of using the night vision effect like other mods, it use a shader system for realism(https://youtu.be/9mdO21GhoDM?t=245). However, due to the mob Siren also has a shader effect when it is attracting you, the other shader become unusable. One can easily fix this by downgrade to a version before the siren update, therefore confirm the source of the issue.

**Comment by Nianor** [comment]
Honestly, it's hard to tell if this is an issue with Vic's or with Ice and Fire. Vic's has a whole bunch of weird compatibility issues with different mods that are a result of how Vic chooses to render things, like breaking the connected textures that IE uses, and it has totally avoidable incompatibility with Optifine. The list of mods that Vic's collides with is pretty long, so it's hard to say whose responsibility it is to actually fix this bug.
