### ISSUE TITLE
Ice and Fire draco aspect conflict with Thaumic Additions

### ISSUE THREAD

**Issue by DWX12** [Alex-the-666/Ice_and_Fire#701]
Using Ice and Fire 1.40 (unofficial)

Start up crash when adding Thaumic Additions along side Ice and Fire.
Draco aspect conflict:

Caused by: java.lang.IllegalArgumentException: draco already registered!
at thaumcraft.api.aspects.Aspect.(Aspect.java:39)
at com.github.alexthe666.iceandfire.IceAndFireAspectRegistry.(IceAndFireAspectRegistry.java:17)

https://hastebin.com/felexojana.bash

I opened up an issue on Thaumic Additions about this and this was the response I received:

"Either remove any of conflicting mods ("Thaumic Additions"  or "Ice and Fire") or ask them to rename the aspect. I am not going to rename my aspect." - Zeitheron

To resolve this issue:
1. Take his stance and not rename the thaumcraft aspect, in which case, everyone loses.
2. Rename the aspect and end up with multiple dragon type aspects.
3. Figure out a way to combine or use his aspect if Ice and Fire detects Thaumic Additions; although, that could still raise issues with the base aspects since those would be different.

Another possible conflict is with Fossils and Archaeology aspects, but at the moment it may just be discussions. I don't know much more than that. I'm certain that the draco aspect will end up popping up again in other mods too, which will result in the same issue.

Take this as an FYI and figure out how you want to handle it.

**Comment by Zeitheron** [comment]
My solution to Ice And Fire:

```
public static final Aspect DRAGON = getOrCreateAspect("draco", 0XA2271F, new Aspect[]{IceAndFireAspectRegistry.MYTHICAL, Aspect.DESIRE}, new ResourceLocation("iceandfire", "textures/thaumcraft/dragon.png"), 1);

public static Aspect getOrCreateAspect(String tag, int color, Aspect[] components, ResourceLocation image, int blend)
{
	Aspect a = Aspect.getAspect(tag);
	if(a != null) return a;
	return new Aspect(tag, color, components, image, blend);
}
```

Why I am not willing to do this is because Thaumic Additions is an ADDON to thaumcraft, it depends on it. But Ice And Fire just adds compat to Thaumcraft.

**Comment by DWX12** [comment]
It really doesn't make any difference if it's an add-on or simple compatibility; it would be the same issue regardless if it was say Thaumic Additions and Planarartifice or Harvestcraft and Ender IO. Both mods are adding things to Thaumcraft.

It's more beneficial to everyone to figure out a mutual solution or compromise to a problem than people arguing and whatnot. If it were just a simple matter of content overlap, it wouldn't be a problem, but it's causing a crash.

Since you presented a solution, we'll just have to wait until Alex-the-666 decides what he's going to do to fix the problem.

**Comment by Sunconure11** [comment]
I have spoken with Alex. He is likely to implement @Zeitheron's solution.

**Comment by AlexModGuy** [comment]
fixed
