### ISSUE TITLE
Dragons attacking skull

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#703]
No matter tamed or wild, ice or fire, they go for both type of skull.
https://cdn.discordapp.com/attachments/411302369553547275/451319985780817926/2018-05-30_16.17.23.png
https://cdn.discordapp.com/attachments/411302369553547275/451320104555380736/2018-05-30_16.17.03.png
https://cdn.discordapp.com/attachments/411302369553547275/451320127862997004/2018-05-30_16.17.06.png
https://cdn.discordapp.com/attachments/411302369553547275/451320064537264168/2018-05-30_16.17.55.png

**Comment by AlexModGuy** [comment]
fixed
