### ISSUE TITLE
Possible compatibility issue or terrain gen bug

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#71]
Floating ice village lamp post 

![2016-11-24_21 38 23](https://cloud.githubusercontent.com/assets/23727270/20613266/52560c0c-b290-11e6-8a9b-1551b3703acd.png)

could potentially be caused by tinkers construct slime islands and/or rough terrain below

![2016-11-24_21 38 41](https://cloud.githubusercontent.com/assets/23727270/20613282/72a62b04-b290-11e6-9204-76f92b21ebfd.png)

**Comment by Alex-the-666** [comment]
definitely it trying to generate on slime island.
