### ISSUE TITLE
Statues still retain living traits

### ISSUE THREAD

**Issue by Nianor** [Alex-the-666/Ice_and_Fire#722]
Because statues are basically normal mobs locked in place with a new texture, they continue to act like living mobs in a number of immersion-breaking ways. For instance: 

- Petrified zombies wearing armor will have their helmets degrade in sunlight
- Petrified hostile mobs will disappear when the game is set to peaceful.
- Petrified mobs with armor and weapons will have the equipment continue to follow the "living" animation set, meaning that while the body of the mob is petrified, the armor and weapon will float around.
- Certain mobs with less orthodox behaviors, such as CNPCs and Ice and Fire's own dragons, will continue to exhibit those behaviors while petrified. For instance, if I recall correctly, the Ice and Fire dragons will still play certain animations when rendering, even when petrified. However, I would need to test that again to confirm.

I don't know how feasible this is, my run-ins with MC's code haven't ever ventured into this territory. However, would it be possible to make the petrified creatures an actual separate entity (or, in an ideal world, a block, though I could see that being a royal pain) that just copies the model and pose from the original creature?

**Comment by mser7** [comment]
Try MCA Villagers

**Comment by AlexModGuy** [comment]
@Nianor  no that wouldn't really be possible without some massive issues. Say you petrified a wolf and created an entity using the ModelWolf. But the wolf's model casts the entity to an EntityWolf, which it wouldn't be if it was a stone statue mob. This would then crash the game. In order for this to work I would need to edit not only most of vanilla mob's model files but also those of other mobs... As of now the stone property works better and safer than a separate entity would.

**Comment by Nianor** [comment]
Even disregarding my suggestion at the end, is there no way to solve at least some of the issues I brought up?
