### ISSUE TITLE
Extremely common brown hippogryphs.

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#726]
The extreme hills biome, the spawning place for them is much bigger than other variants, making them extremely common in the biome. Possible solutions: editing the spawn height so that the tallest of extreme hills can spawn hippogryphs, or change their spawning biome to extreme hills M+ and the like.

**Comment by mser7** [comment]
correction: It isn't that common, but it just much more common than other variants, might happened to the savanna one as well.

**Comment by AlexModGuy** [comment]
this is minecrafts fault for generating more of those biomes than others.
