### ISSUE TITLE
Illogical craftsman trade

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#727]
First, the craftsman demand sapphire for a diamond shovel, but later, she demands again diamond shovel for sapphire, not only that, but she wants multiple diamond shovel stacked together.
https://cdn.discordapp.com/attachments/411302369553547275/453880705810956309/2018-05-29_19.18.22.png

**Comment by AlexModGuy** [comment]
lol whoops

**Comment by AlexModGuy** [comment]
fixed in 1.5.0
