### ISSUE TITLE
Hippogryph Boolean?

### ISSUE THREAD

**Issue by Niconoko** [Alex-the-666/Ice_and_Fire#728]
http://pastebin.com/ZhXuTE9k

**Comment by CombatZAK** [comment]
+1 for failing to cast integer to boolean. It looks like the most recent update to LLibrary might be the culprit.

Also this crash only seems to affect client-side.

**Comment by Niconoko** [comment]
http://pastebin.com/5BSH7q0s
Also with Wyvern.....

**Comment by Bulldog83** [comment]
Same as https://github.com/Alex-the-666/Ice_and_Fire/issues/696

**Comment by AlexModGuy** [comment]
#740
