### ISSUE TITLE
Can't fly down 

### ISSUE THREAD

**Issue by SkyDragon3735** [Alex-the-666/Ice_and_Fire#730]
I can't fly down with dragons or hippogryphs. I can go up and forward and sideways with no problem, I just can't go down. I changed the control and reset it back and I tried deleting and reinstalling the mod. Is it something I'm doing or is it a bug? How can I fix it?

**Comment by PlatinumFox** [comment]
@SkyDragon3735 try deleting the config file and the. Restarting Minecraft.

**Comment by AlexModGuy** [comment]
^
