### ISSUE TITLE
Client Crash when connecting to server Ice and Fire 1.4.0-1.12.2 Minecraft Forge 14.23.4.2705

### ISSUE THREAD

**Issue by renadi** [Alex-the-666/Ice_and_Fire#731]
I've been trying to run a server for my personal modpack and recently came upon this error.

The game crashed whilst ticking entity
The game crashed whilst ticking entity
Error: java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Integer

Full Pastebin:
https://pastebin.com/wHY7TNGx

I have only seen this when connecting to my server, and have seen many death worms in single player and that seems to be what this is referencing.

**Comment by AlexModGuy** [comment]
#740
