### ISSUE TITLE
[Request] Some improvement ideas

### ISSUE THREAD

**Issue by Flemmli97** [Alex-the-666/Ice_and_Fire#736]
- Make the tamed entites be able to wander around a specific (configurable) area. This can make for example pixie houses useful cause as it is now tamed pixies can't/won't use them.

- Add a block which deathworms can't pass through. I made a cage out of obsidian walls with sand inside in hope that the worms can't escape but they still did it. The reason for this is that first of the home area of deathworms is really large (maybe add a config for it also) and i have a mod which makes hostile mobs stronger so sooner or later the worms will die if i just left them.

**Comment by AlexModGuy** [comment]
please move suggestions to the suggestions repo
