### ISSUE TITLE
My hippogryph just ditched me!

### ISSUE THREAD

**Issue by NathanAnd** [Alex-the-666/Ice_and_Fire#738]
AAAH! My precious Griffon just threw me off his back, nearly killed me, and flew away! D: What do I do? Is this a feature or a bug, or does he just hate me!? I was in a ravine collecting iron so I took him with me so I could fly back up. Then I got on and he was like "Bye bitch". It added to his character but I really want him back. :'(

**Comment by AlexModGuy** [comment]
craft a dragon bone flute to get them to stop flying. make a dragon bone staff to set their home point... etc
