### ISSUE TITLE
Dragon skull lagging?

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#741]
It started when I decide to put down the 3 skulls down in my base, I then do my usual business, shortly after, my game experienced quick freeze and fps drop, after I destroyed the skulls, it went back to normal. I decide to test it more, it is not so bad just for one skull, but two skulls or more and it start to get really annoying, I even went out and slay a dragon, then carry its body back and put it in my base and continue to work, but there were no lag issue with the dead body, only when the skulls are place down, then it lag.

**Comment by mser7** [comment]
Update: I brought back two more dead dragon to live with my, so there are 3 corpse in total, and i experienced light lag, lighter than just only 2 skulls.

**Comment by AlexModGuy** [comment]
fixed it was the old texture system
