### ISSUE TITLE
Popping a dragon egg and skull doesn't actually counted as a kill.

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#743]
The mob just popped into its item form, this is really inconvinient if you want to make a spawner for them using the kill count method, like the soul shards mod, the only other way I can think of making a spawner for them is MFR Spawner or Ender IO soul vial

**Comment by AlexModGuy** [comment]
working as intended; dragons arent meant to be farmed like that ;)
