### ISSUE TITLE
No Ice Dragon Command Staff

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#746]
Even If you craft the staff using the Ice dragon head, it would just appeared as a fire head,

**Comment by mser7** [comment]
No Ice Dragon bones as well, despite the ice dragon skeleton reviewed different bone colors.

**Comment by PlatinumFox** [comment]
Pretty sure the staff is just meant to be a universal item

**Comment by mser7** [comment]
Well if I use an Ice Dragon Head for the recipe you would bet I want an command staff with the Ice Dragon Head

**Comment by AlexModGuy** [comment]
what PlatinnmFox said
