### ISSUE TITLE
Dragon attacks

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#747]
It seem that sometimes when the dragon bite you, and you press shift to escape, it still deal damage afterward.

In the forum there is suppose to be this tail whip move, but the dragon hasn't done it once, the only explanation is that it only does it when the player is near its tail, behind it, but the dragon will always point its head toward the player, making this attack impossible.

**Comment by AlexModGuy** [comment]
fixed in 1.5.0
