### ISSUE TITLE
Many, many things are lacking textures or models.

### ISSUE THREAD

**Issue by Sunconure11** [Alex-the-666/Ice_and_Fire#75]
https://www.dropbox.com/s/36q3suqhu9chdxq/Screenshot%202016-11-25%2014.48.32.png?dl=0

**Comment by raptorfarian** [comment]
Erm... are you sure that's not just due to the other mods you have and 'not enough items mod' ?

**Comment by Sunconure11** [comment]
NEI is obsolete. JEI (Just Enough Items) is what is used on newer versions of MC.

I plan on looking over this with a specific approach tomorrow, to see what is going on. I doubt it is JEI though.

**Comment by PlatinumFox** [comment]
i had a texture issue as well, i typed the command
/give name iceandfire:dragon_skull 2 3 (my aim was to get different stage dragon skulls from creative or commands_
it gave me a missing texture error while testing this

**Comment by Kusark** [comment]
@Sunconure11 that doesn't look right at all. That's clearly a problem with other mods because I'm using just the beta 03 version and all the textures and models are perfectly fine.

**Comment by PlatinumFox** [comment]
i got rid of all mods i was using except for back packs, optifine and nei/jei (or whatever its called now), and other than the command comment i stated above i have not seen any other texture errors. that command test was in beta 2.

**Comment by Sunconure11** [comment]
@PlatinumFox While I was going to do a similar approach tomorrow to narrow down the mod, can you try this approach?

Re-add all of your mods, in batches. When the textures start screwing up, remove each mod in the most recent batch until the textures are fixed.

This is basically what I was going to do.

**Comment by PlatinumFox** [comment]
@Sunconure11 i think i can try that i only had tinkers construct and advanced hooks mod besides backpacks optifine and nei. ill try it in a bit
(btw hooking a hook to a wild dragon and dangling from it while it flies is very fun to do XD)

**Comment by Sunconure11** [comment]
@PlatinumFox Any luck in replicating the bug?

**Comment by Sunconure11** [comment]
Chisel is behind this issue.

https://minecraft.curseforge.com/projects/chisel

**Comment by PlatinumFox** [comment]
i did not notice any graphical errors when i re added the mods (i took them out again bc tinkers construct slime biomes sort of messed with the generation of snow villages) the only graphical glitch i noticed was the command thing which seems to be in the ice and fir e mod itself
type the command
/give name iceandfire:dragon_skull 2 3
(again i was trying to see if there was a way to get different sized dragon skulls in creative)
by typing that command in you get 2 untextured items but when u place them they are an ice dragon skull

**Comment by Alex-the-666** [comment]
no shit doing that command would give you missing texture item.
0 metadata is for fire dragon skull, 1 metadata is for ice dragon skull. there are no other dragon skull types.
The size of the skull is determined by NBT data.

**Comment by Sunconure11** [comment]
Somehow resolved itself. Closing.
