### ISSUE TITLE
Nerf the swimming AI

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#751]
https://www.youtube.com/watch?v=MF4BnTPxZZw&t=254s
The swimming AI for the latest 3 mobs is kinda, chaotic, as Rayne has commented, it is very messy, mostly the swimming all over the place and never rest for the hippocampus and siren.

For the death worm, its speed need to be slowed down significant while in the sand. These worms swimming as if they're in a liquid environment, but they don't, sand is much dense substain compared to water, even irl earthworms move around slowly. The speed also cause problem for the worm to attack, especially small ones, depicted in the video,

**Comment by AlexModGuy** [comment]
i slowed down all 3 and gave the sirens and hippocampus more vanilla esque ai. they are still a bit erratic but they dont jump rapidly randomly anymore. In 1.13 i'll be giving them dolphin and fish AI.
