### ISSUE TITLE
Nerf the dragons running speed.

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#752]
Right now dragons run super fast, i'd say those speed should be applied to stage 5 since they are bigger. Another problem for nerfing is that right now they can outrun players, so if you're targeted, you must fight, there is no other way, The player should be given the chance to escape if they want, and considering dragons body isn't optimized for running, its safe to say their speed should be nerfed.

**Comment by AlexModGuy** [comment]
fixed
