### ISSUE TITLE
 1.5.0 Troll weapons invisible

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#753]
Troll weapons are invisible in the inventory and in the players hand.
![screenshot 7](https://user-images.githubusercontent.com/23727270/41319136-d20c4eb2-6e68-11e8-90d8-ecbc298e3373.png)

**Comment by AlexModGuy** [comment]
update llibrary

**Comment by PlatinumFox** [comment]
using LLibrary 1.7.13 1.12.2. not showing up

**Comment by AlexModGuy** [comment]
what other mods are you using

**Comment by PlatinumFox** [comment]
![screenshot 10](https://user-images.githubusercontent.com/23727270/41329246-6c14c33c-6e9a-11e8-86ef-b07df80b5eea.png)

**Comment by AlexModGuy** [comment]
its optifine causing it

**Comment by AlexModGuy** [comment]
ill try and fix, it might be on their side

**Comment by PlatinumFox** [comment]
let me know if u cant and ill go post it on Sp614x GitHub if its optifines fault

**Comment by PlatinumFox** [comment]
still happens in 1.5.0 alpha 2

**Comment by AlexModGuy** [comment]
https://github.com/sp614x/optifine/issues/1457

**Comment by sp614x** [comment]
Where can I get Ice and Fire 1.5.0 alpha?

**Comment by AlexModGuy** [comment]
@sp614x do you have a discord? I'll send it to you

**Comment by sp614x** [comment]
optifine discord: https://discord.gg/tKxWtyf

**Comment by sp614x** [comment]
Testing latest OptiFine preview E1 + IceAndFire_1.5.0_Alpha4 + Library-1.7.13-1.12.2, the troll weapons are rendered correctly:

![image](https://user-images.githubusercontent.com/16635441/41474516-76df9b56-70bc-11e8-9c27-7496cb5d7ace.png)

**Comment by AlexModGuy** [comment]
Use optifine latest preview should fix this bug

**Comment by sp614x** [comment]
The current OptiFine D3 for 1.12.2 also works for me.
