### ISSUE TITLE
Temple Spawning 1.5.0-ALPHA 

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#754]
I think that this screenshot speaks for it self...
![screenshot 8](https://user-images.githubusercontent.com/23727270/41324792-acc664dc-6e84-11e8-92ea-b5025cc905af.png)

**Comment by AlexModGuy** [comment]
Buggy temple spawns have existed since they were added though

**Comment by PlatinumFox** [comment]
true but they are not spawning in the current 1.4.1 version, thought they were fixed, i also thought they were limited to spawning on shores at the shore line level (y 64 ish i  think) this is y 90, posted just because this is way out there when it comes to the buggyness lol

**Comment by AlexModGuy** [comment]
yeah i just made it so they need to spawn on flat ground
