### ISSUE TITLE
Better homepoint mechanics

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#755]
Mobs that are supposed to have a homepoint registration like death worm, pixie and wild dragons doesn't really attach to it, it really got lured off miles away from their homepoint and never come back, usually due to it is busying with another different task rather than return to their homepoint, even for pixie, who only have a wander ai, eventually fly off forever from their mushroom home.

**Comment by mser7** [comment]
Also I would like if they can return to their home from far distances, if I bring my worm 500 blocks away I want it to eventually make its way to its original hunting ground.

**Comment by mser7** [comment]
It is important to make tamed pixie forget the homepoint and go with the player.

**Comment by AlexModGuy** [comment]
youll be able to add in home points for dragons and hippogryphs in 1..0 by shift clicking them with the dragon staff
