### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by tabular09** [Alex-the-666/Ice_and_Fire#758]
hello my game is crashing and it tells me that your mod or neatherex could be the issue here is the crash report
https://paste.dimdev.org/ruzoyexuve.mccrash

thanks for any help you can give.

**Comment by ProsperCraft** [comment]
Same on our server- https://paste.dimdev.org/bubodaxuca.mccrash

Pretty sure this is a dupe of a previous issue-

**Comment by AlexModGuy** [comment]
#740
