### ISSUE TITLE
Attacking a dragon egg causes it to break into two new eggs

### ISSUE THREAD

**Issue by Sunconure11** [Alex-the-666/Ice_and_Fire#76]
To clarify, this happened in creative, with an ice dragon egg.

**Comment by Alex-the-666** [comment]
Are you sure you did not place 2 eggs in the exact same spot? This happens.

**Comment by Sunconure11** [comment]
I'm pretty sure I didn't. I'll test it again tomorrow though.

**Comment by Sunconure11** [comment]
I can confirm it happens with only one egg.

**Comment by AlexModGuy** [comment]
dupe #236
