### ISSUE TITLE
1.5.0-ALPHA2 silver spawning in more than cold biomes

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#765]
![screenshot 16](https://user-images.githubusercontent.com/23727270/41376384-19104eb2-6f27-11e8-994b-b651cf14e51b.png)

**Comment by AlexModGuy** [comment]
im sorry, i checked the code and this is just  RNGesus messing with you. Nothing in the silver generation is determined by biome.
