### ISSUE TITLE
1.5.0-ALPHA2: Stuttering cockatrices

### ISSUE THREAD

**Issue by PCAwesomeness** [Alex-the-666/Ice_and_Fire#766]
Cockatrices stutter a lot when they're attacking players. They do get better over time, and they work just fine when they're not attacking, but it's still noticeable enough to be an issue.

**Comment by random3421** [comment]
Where did you download the link at?? I can't find the new updated one. I'm still in 1.4.0

**Comment by PlatinumFox** [comment]
@random3421 1.5.0 is in the testing phase there is no release yet. Bugs are just reported here on github
