### ISSUE TITLE
1.5.0-ALPHA2: Occasional crashes after being killed by a mob from this mod

### ISSUE THREAD

**Issue by PCAwesomeness** [Alex-the-666/Ice_and_Fire#770]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 6/13/18 8:54 PM
Description: Exception in server tick loop

java.lang.IllegalStateException: Entry was removed
	at java.util.IdentityHashMap$EntryIterator$Entry.checkIndexForEntryUse(Unknown Source)
	at java.util.IdentityHashMap$EntryIterator$Entry.getValue(Unknown Source)
	at net.ilexiconn.llibrary.server.ServerEventHandler.onServerTickEvent(ServerEventHandler.java:161)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_60_ServerEventHandler_onServerTickEvent_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:265)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 418326840 bytes (398 MB) / 1053818880 bytes (1005 MB) up to 1053818880 bytes (1005 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2707 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State                                                       | ID            | Version      | Source                                        | Signature                                |
	|:----------------------------------------------------------- |:------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | minecraft     | 1.12.2       | minecraft.jar                                 | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | mcp           | 9.42         | minecraft.jar                                 | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | FML           | 8.0.99.99    | forge-1.12.2-14.23.4.2707-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | forge         | 14.23.4.2707 | forge-1.12.2-14.23.4.2707-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | biomesoplenty | 7.0.1.2387   | BiomesOPlenty-1.12.2-7.0.1.2387-universal.jar | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | aqua_creepers | 1.2.3        | AquaCreepers-1.2.3.jar                        | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | familiarfauna | 1.0.8        | FamiliarFauna-1.12.2-1.0.8.jar                | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | llibrary      | 1.7.13       | llibrary-1.7.13-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | iceandfire    | 1.5.0        | iceandfire-1.5.0-ALPHA2.jar                   | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | jaff          | 1.7_for_1.12 | JustAFewFish-1.7_for_1.12.jar                 | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | primitivemobs | 1.1.5c       | primitivemobs-1.1.5c_beta.jar                 | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.6-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['PCAwesomeness'/1141953, l='Temporary', x=-749.59, y=64.00, z=686.71]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by AlexModGuy** [comment]
what mob is killing you

**Comment by PCAwesomeness** [comment]
Well, it doesn't happen all of the time, but it did happen a few times with the Cyclops and the Fire Dragon.

**Comment by jj7878** [comment]
I'm having the same crash and error after dying via firedragon.

Edit: The most recent llibrary update seems to have solved this
