### ISSUE TITLE
client crash 

### ISSUE THREAD

**Issue by Link1larc** [Alex-the-666/Ice_and_Fire#771]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1 (1).jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  FMLPlugin (elulib-0.1.12.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (FoamFix-1.12.2-0.9.4-Anarchy (1).jar)
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.1.2 (2).jar)
  GottaGoFastLoader (gottagofast-1.1.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 6/14/18 5:04 AM
Description: Ticking entity

java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Boolean
	at com.github.alexthe666.iceandfire.entity.EntityHippogryph.isFlying(EntityHippogryph.java:473)
	at com.github.alexthe666.iceandfire.entity.EntityHippogryph.func_70636_d(EntityHippogryph.java:726)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at com.github.alexthe666.iceandfire.entity.EntityHippogryph.func_70071_h_(EntityHippogryph.java:857)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.github.alexthe666.iceandfire.entity.EntityHippogryph.isFlying(EntityHippogryph.java:473)
	at com.github.alexthe666.iceandfire.entity.EntityHippogryph.func_70636_d(EntityHippogryph.java:726)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at com.github.alexthe666.iceandfire.entity.EntityHippogryph.func_70071_h_(EntityHippogryph.java:857)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: iceandfire:hippogryph (com.github.alexthe666.iceandfire.entity.EntityHippogryph)
	Entity ID: 54862
	Entity Name: Hippogryph
	Entity's Exact location: -163.62, 79.69, 416.18
	Entity's Block location: World: (-164,79,416), Chunk: (at 12,4,0 in -11,26; contains blocks -176,0,416 to -161,255,431), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: -0.37, -0.14, -0.11
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['Brendan1021'/51974, l='MpServer', x=-222.79, y=64.00, z=405.37], EntityOtherPlayerMP['Link1larc'/6214, l='MpServer', x=-223.35, y=64.00, z=408.19]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-216,64,236), Chunk: (at 8,4,12 in -14,14; contains blocks -224,0,224 to -209,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 169691 game time, 3762 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 88 total; [EntityCreeper['Creeper'/55553, l='MpServer', x=-160.50, y=15.00, z=425.50], EntityZombie['Zombie'/56196, l='MpServer', x=-239.50, y=63.00, z=453.50], EntityBasicVampire['Vampire'/56197, l='MpServer', x=-240.50, y=63.00, z=453.50], EntityItem['item.tile.sapling.oak'/56458, l='MpServer', x=-248.11, y=68.00, z=405.65], EntitySkeleton['Skeleton'/54925, l='MpServer', x=-273.70, y=58.00, z=446.50], EntityZombie['Zombie'/56078, l='MpServer', x=-274.50, y=52.00, z=464.50], EntityEnderman['Enderman'/55055, l='MpServer', x=-169.50, y=25.00, z=463.50], EntitySkeleton['Skeleton'/55951, l='MpServer', x=-286.50, y=32.00, z=458.50], EntitySkeleton['Skeleton'/55060, l='MpServer', x=-299.67, y=59.00, z=454.50], EntitySheep['Sheep'/52887, l='MpServer', x=-151.21, y=63.00, z=372.76], EntityBat['Bat'/55448, l='MpServer', x=-208.75, y=17.10, z=389.50], EntitySquid['Squid'/55576, l='MpServer', x=-218.58, y=59.94, z=348.29], EntityBat['Bat'/55832, l='MpServer', x=-207.65, y=45.10, z=402.33], EntitySheep['Sheep'/52888, l='MpServer', x=-149.61, y=63.00, z=381.19], EntityBat['Bat'/55705, l='MpServer', x=-236.38, y=57.94, z=474.05], EntitySheep['Sheep'/52889, l='MpServer', x=-156.39, y=63.00, z=384.20], EntitySquid['Squid'/55577, l='MpServer', x=-224.28, y=61.47, z=342.87], EntitySquid['Squid'/55578, l='MpServer', x=-218.29, y=60.96, z=344.55], EntitySheep['Sheep'/52891, l='MpServer', x=-154.29, y=63.00, z=385.19], EntityBasicHunter['Vampire Hunter'/46236, l='MpServer', x=-227.43, y=92.00, z=450.83], EntityBasicHunter['Vampire Hunter'/46237, l='MpServer', x=-230.52, y=92.00, z=445.82], EntityCreeper['Creeper'/55967, l='MpServer', x=-198.56, y=59.00, z=352.80], EntityCreeper['Creeper'/56096, l='MpServer', x=-206.50, y=32.00, z=395.50], EntityBat['Bat'/55841, l='MpServer', x=-237.84, y=16.10, z=328.75], EntityCreeper['Creeper'/53795, l='MpServer', x=-276.50, y=13.00, z=398.50], EntityBat['Bat'/54051, l='MpServer', x=-191.75, y=38.10, z=392.07], EntityBat['Bat'/55203, l='MpServer', x=-155.67, y=31.10, z=424.56], EntityBat['Bat'/55844, l='MpServer', x=-220.25, y=17.98, z=328.25], EntitySheep['Sheep'/22693, l='MpServer', x=-279.75, y=65.00, z=387.64], EntityPig['Pig'/53285, l='MpServer', x=-143.82, y=68.00, z=433.26], EntitySheep['Sheep'/167, l='MpServer', x=-147.77, y=69.00, z=349.52], EntityCreeper['Creeper'/54824, l='MpServer', x=-275.49, y=53.00, z=457.20], EntitySheep['Sheep'/169, l='MpServer', x=-154.52, y=65.00, z=335.82], EntitySheep['Sheep'/171, l='MpServer', x=-152.50, y=69.00, z=357.73], EntityZombieVillager['Zombie Villager'/55596, l='MpServer', x=-291.50, y=32.00, z=454.50], EntityZombie['Zombie'/55341, l='MpServer', x=-266.50, y=45.00, z=338.50], EntityCreeper['Creeper'/55597, l='MpServer', x=-283.50, y=35.00, z=464.50], EntityCreeper['Creeper'/55598, l='MpServer', x=-283.50, y=35.00, z=463.50], EntitySkeleton['Skeleton'/55472, l='MpServer', x=-166.29, y=24.00, z=465.50], EntityCreeper['Creeper'/56116, l='MpServer', x=-183.50, y=26.00, z=342.50], EntitySkeleton['Skeleton'/56117, l='MpServer', x=-184.50, y=26.00, z=342.50], EntitySkeleton['Skeleton'/56373, l='MpServer', x=-217.50, y=37.00, z=401.50], EntityItem['item.tile.sapling.oak'/56501, l='MpServer', x=-230.88, y=65.00, z=403.00], EntitySkeleton['Skeleton'/56118, l='MpServer', x=-184.50, y=26.00, z=341.50], EntityZombie['Zombie'/56374, l='MpServer', x=-218.50, y=37.00, z=401.50], EntitySkeleton['Skeleton'/56119, l='MpServer', x=-185.50, y=26.00, z=342.50], EntityWitch['Witch'/56503, l='MpServer', x=-150.50, y=18.00, z=364.50], EntityBat['Bat'/54712, l='MpServer', x=-200.28, y=16.49, z=360.61], EntitySkeleton['Skeleton'/55098, l='MpServer', x=-151.50, y=15.00, z=428.50], EntityZombieVillager['Zombie Villager'/55739, l='MpServer', x=-254.50, y=46.00, z=354.50], EntityZombieVillager['Zombie Villager'/55615, l='MpServer', x=-224.50, y=24.00, z=420.50], EntityBasicHunter['Vampire Hunter'/50368, l='MpServer', x=-176.22, y=64.00, z=451.51], EntityItem['item.tile.sapling.oak'/56512, l='MpServer', x=-218.07, y=64.00, z=403.88], EntityItem['item.tile.log.oak'/56514, l='MpServer', x=-222.30, y=69.07, z=405.41], EntityOtherPlayerMP['Link1larc'/6214, l='MpServer', x=-223.35, y=64.00, z=408.19], EntityZombie['Zombie'/56266, l='MpServer', x=-230.50, y=27.00, z=336.50], EntitySpider['Spider'/56394, l='MpServer', x=-207.50, y=43.00, z=382.50], EntityHippogryph['Hippogryph'/54862, l='MpServer', x=-163.62, y=79.69, z=416.18], EntityPlayerSP['Brendan1021'/51974, l='MpServer', x=-222.79, y=64.00, z=405.37], EntitySkeleton['Skeleton'/56275, l='MpServer', x=-152.50, y=13.00, z=425.50], EntityZombie['Zombie'/56276, l='MpServer', x=-194.22, y=32.00, z=409.51], EntityBasicVampire['Vampire'/55252, l='MpServer', x=-277.50, y=13.00, z=326.50], EntityZombie['Zombie'/53717, l='MpServer', x=-282.50, y=37.00, z=470.50], EntitySkeleton['Skeleton'/56277, l='MpServer', x=-188.50, y=30.00, z=415.50], EntitySkeleton['Skeleton'/56405, l='MpServer', x=-273.50, y=13.00, z=398.50], EntitySquid['Squid'/54742, l='MpServer', x=-176.60, y=58.00, z=435.40], EntityBasicHunter['Vampire Hunter'/52573, l='MpServer', x=-175.00, y=63.00, z=446.00], EntityCreeper['Creeper'/55135, l='MpServer', x=-182.50, y=25.00, z=388.50], EntityItem['item.tile.sapling.oak'/56160, l='MpServer', x=-247.13, y=65.00, z=408.36], EntityItem['item.tile.log.oak'/55777, l='MpServer', x=-246.52, y=65.00, z=406.44], EntityCreeper['Creeper'/55523, l='MpServer', x=-288.50, y=31.00, z=458.50], EntityItem['item.tile.sapling.oak'/56163, l='MpServer', x=-246.43, y=68.00, z=406.13], EntityEnderman['Enderman'/54889, l='MpServer', x=-220.47, y=44.00, z=397.52], EntityBat['Bat'/55786, l='MpServer', x=-152.24, y=16.92, z=443.66], EntityItem['item.tile.dirt.default'/53613, l='MpServer', x=-289.17, y=62.00, z=431.88], EntityItem['item.tile.dirt.default'/53618, l='MpServer', x=-287.13, y=61.00, z=430.82], EntityOtherPlayerMP['Link1larc'/6214, l='MpServer', x=-223.35, y=64.00, z=408.19], EntityItem['item.tile.dirt.default'/53621, l='MpServer', x=-287.63, y=61.00, z=429.65], EntityBat['Bat'/55032, l='MpServer', x=-239.51, y=52.81, z=468.47], EntityCreeper['Creeper'/55672, l='MpServer', x=-193.50, y=30.00, z=390.50], EntityItem['item.tile.dirt.default'/53625, l='MpServer', x=-286.97, y=62.00, z=428.53], EntityBat['Bat'/55033, l='MpServer', x=-213.80, y=55.10, z=465.48], EntityItem['item.tile.dirt.default'/53626, l='MpServer', x=-286.13, y=62.00, z=428.13], EntityItem['item.tile.dirt.default'/53628, l='MpServer', x=-287.33, y=62.00, z=427.13], EntityItem['item.tile.dirt.default'/53629, l='MpServer', x=-288.27, y=63.00, z=427.89], EntityZombie['Zombie'/55549, l='MpServer', x=-272.28, y=51.00, z=449.83], EntityBat['Bat'/56445, l='MpServer', x=-247.99, y=20.43, z=422.22], EntityItem['item.tile.dirt.default'/53630, l='MpServer', x=-289.89, y=63.00, z=427.49]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2738)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5351010400 bytes (5103 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms6144m -Xmx6144m -XX:+UseG1GC -XX:MaxGCPauseMillis=4
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.4.2708 73 mods loaded, 73 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version                  | Source                                             | Signature                                |
	|:------ |:--------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft             | 1.12.2                   | minecraft.jar                                      | None                                     |
	| UCHIJA | mcp                   | 9.42                     | minecraft.jar                                      | None                                     |
	| UCHIJA | FML                   | 8.0.99.99                | modpack.jar                                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge                 | 14.23.4.2708             | modpack.jar                                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | foamfixcore           | 7.7.4                    | minecraft.jar                                      | None                                     |
	| UCHIJA | elucore               | 1.0                      | minecraft.jar                                      | None                                     |
	| UCHIJA | gottagofast           | 1.1                      | gottagofast-1.1.jar                                | None                                     |
	| UCHIJA | torchbowmod           | 1.3                      | [1.12-1.12.2]TorchBowMod_v1.3 (1).jar              | None                                     |
	| UCHIJA | antiqueatlas          | 4.4.9                    | antiqueatlas-1.12.2-4.4.9 (1).jar                  | None                                     |
	| UCHIJA | antiqueatlasoverlay   | 1.2                      | antiqueatlas-1.12.2-4.4.9 (1).jar                  | None                                     |
	| UCHIJA | examplemod            | 1.0                      | antiqueatlas-1.12.2-4.4.9 (1).jar                  | None                                     |
	| UCHIJA | astikoor              | 1.0.0                    | astikoor-1.0.0 (1).jar                             | None                                     |
	| UCHIJA | backpack              | 3.0.2                    | backpack-3.0.2-1.12.2.jar                          | None                                     |
	| UCHIJA | baubles               | 1.5.2                    | Baubles-1.12-1.5.2 (2).jar                         | None                                     |
	| UCHIJA | xaerobetterpvp        | 1.14.7                   | BetterPvPFairPlay_1.14.7_Forge_1.12.jar            | None                                     |
	| UCHIJA | bibliocraft           | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0] (1).jar              | None                                     |
	| UCHIJA | classiccombat         | 1.0.0                    | ClassicCombat-1.12-1.0.0.jar                       | None                                     |
	| UCHIJA | cosmeticarmorreworked | 1.12.2-v1                | CosmeticArmorReworked-1.12.2-v1 (2).jar            | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCHIJA | crissaegrim           | 0.1.1                    | Crissaegrim-Mod-1.12.2.jar                         | None                                     |
	| UCHIJA | customnpcs            | 1.12                     | CustomNPCs_1.12.2(20jan18).jar                     | None                                     |
	| UCHIJA | cxlibrary             | 1.6.1                    | cxlibrary-1.12.1-1.6.1 (1).jar                     | None                                     |
	| UCHIJA | cyclopscore           | 0.11.5                   | CyclopsCore-1.12.2-0.11.5 (2).jar                  | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJA | ebwizardry            | 4.1.2                    | Electroblob's+Wizardry+-+4.1.2+-+MC+1.12.2 (1).jar | None                                     |
	| UCHIJA | csb_ench_table        | 1.1.3                    | EnchantingTable-1.12-1.1.3.jar                     | None                                     |
	| UCHIJA | enchdesc              | 1.1.6                    | EnchantmentDescriptions-1.12.2-1.1.6.jar           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJA | endercompass          | 1.2.6.1                  | EnderCompass-1.12-1.2.6.1 (1).jar                  | None                                     |
	| UCHIJA | everlastingabilities  | 1.3.16                   | EverlastingAbilities-1.12.2-1.3.16.jar             | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJA | jei                   | 4.9.0.163                | jei_1.12.2-4.9.0.163.jar                           | None                                     |
	| UCHIJA | mantle                | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24 (1).jar                       | None                                     |
	| UCHIJA | tconstruct            | 1.12.2-2.10.1.84         | TConstruct-1.12.2-2.10.1.84.jar                    | None                                     |
	| UCHIJA | extrautils2           | 1.0                      | extrautils2-1.12-1.7.3.jar                         | None                                     |
	| UCHIJA | fakename              | 1.1                      | Fakename+MC1.12.2+v1.1.jar                         | None                                     |
	| UCHIJA | foamfix               | 0.9.4-1.12.2             | FoamFix-1.12.2-0.9.4-Anarchy (1).jar               | None                                     |
	| UCHIJA | grapplemod            | 1.12.2-v10               | grapplemod-v10-1.12.2.jar                          | None                                     |
	| UCHIJA | guideapi              | 1.12-2.1.5-60            | Guide-API-1.12-2.1.5-60 (1).jar                    | None                                     |
	| UCHIJA | hardcoredarkness      | 2.0                      | HardcoreDarkness-MC1.12.2-2.0.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJA | howlingmoon           | 0.9                      | howlingmoon-1.12.2-0.9.jar                         | None                                     |
	| UCHIJA | iblis                 | 0.3.34                   | iblis-0.3.34 (1).jar                               | None                                     |
	| UCHIJA | llibrary              | 1.7.12                   | llibrary-1.7.12-1.12.2.jar                         | None                                     |
	| UCHIJA | iceandfire            | 1.4.0                    | iceandfire-1.4.0-1.12.2 (2).jar                    | None                                     |
	| UCHIJA | infernalmobs          | 1.7.5                    | InfernalMobs-1.12.2.jar                            | None                                     |
	| UCHIJA | inventorytweaks       | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJA | ironchest             | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824 (1).jar                | None                                     |
	| UCHIJA | kesutoweapons         | 1.3                      | Kesuto's+Weapons+1.12.2-1.3.jar                    | None                                     |
	| UCHIJA | lucraftcore           | 1.12.2-2.1.2             | LucraftCore-1.12.2-2.1.2 (2).jar                   | None                                     |
	| UCHIJA | magicarsenal          | MC1.12_ver1.2.5          | MagicArsenal-MC1.12_ver1.2.5.jar                   | None                                     |
	| UCHIJA | malisiscore           | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                       | None                                     |
	| UCHIJA | malisisdoors          | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                      | None                                     |
	| UCHIJA | testdummy             | 1.12                     | MmmMmmMmmMmm-1.12-1.14.jar                         | None                                     |
	| UCHIJA | mobrecipes            | 1.0.0                    | MobRecipes-1.12.2-1.0.2.jar                        | None                                     |
	| UCHIJA | monk                  | 1.0                      | monk-mod-1.2 (1).jar                               | None                                     |
	| UCHIJA | morefurnaces          | 1.10.5                   | MoreFurnaces-1.12.2-1.10.5.jar                     | None                                     |
	| UCHIJA | orecanes              | 1.3.0                    | Ore+Canes+1.3.0.jar                                | None                                     |
	| UCHIJA | overpoweredarmorbar   | 0.2.1                    | overpoweredarmorbar-1.12.2-0.2.1 (1).jar           | None                                     |
	| UCHIJA | harvestcraft          | 1.12.2t                  | Pam's+HarvestCraft+1.12.2t.jar                     | None                                     |
	| UCHIJA | jmilpol               | 0.1                      | PendantOfLife-1.2.jar                              | None                                     |
	| UCHIJA | projecte              | 1.12-PE1.0.0             | ProjectE-1.12-PE1.2.0.jar                          | None                                     |
	| UCHIJA | xreliquary            | 1.12.2-1.3.4.763         | Reliquary-1.12.2-1.3.4.763 (1).jar                 | None                                     |
	| UCHIJA | secretroomsmod        | 5.3.2                    | secretroomsmod-1.12.2-5.3.2.jar                    | None                                     |
	| UCHIJA | sgcraft               | 1.13.2                   | SGCraft-1.2-mc1.12.2.jar                           | None                                     |
	| UCHIJA | flammpfeil.slashblade | mc1.12-r13               | SlashBlade-mc1.12-r13.jar                          | None                                     |
	| UCHIJA | sleep                 | 1.12-1.0.1-CUSTOM        | Sleep-1.12-1.0.1 (1).jar                           | None                                     |
	| UCHIJA | somanyenchantments    | 0.3.0                    | SoManyEnchantments+V0.3.1+(1.12.2).jar             | None                                     |
	| UCHIJA | spectrite             | 1.6.6                    | spectrite-1.6.6 (1).jar                            | 00119cfc089819bbcd2f9166a50c7f3df88ded78 |
	| UCHIJA | thaumcraft            | 6.1.BETA16               | Thaumcraft-1.12.2-6.1.BETA16.jar                   | None                                     |
	| UCHIJA | thaumicjei            | 1.2.1                    | ThaumicJEI-1.12.2-1.3.1-12.jar                     | None                                     |
	| UCHIJA | thaumicperiphery      | 0.2.3                    | thaumicperiphery-0.2.3.jar                         | None                                     |
	| UCHIJA | theeightfabledblades  | 1.0.0                    | TheEightFabledBlades+V1.0.0.jar                    | None                                     |
	| UCHIJA | ultimate_unicorn_mod  | 1.5.16                   | ultimate_unicorn_mod-1.12.2-1.5.16.jar             | None                                     |
	| UCHIJA | vampirism             | 1.4.2                    | Vampirism-1.12.2-1.4.2.jar                         | None                                     |
	| UCHIJA | teamlapen-lib         | 1.4.2                    | Vampirism-1.12.2-1.4.2.jar                         | None                                     |
	| UCHIJA | walljump              | 1.12.2-1.1.1             | walljump-1.12.2-1.1.1.jar                          | None                                     |
	| UCHIJA | elulib                | 0.1.12                   | elulib-0.1.12.jar                                  | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
CXLibraryCore (cxlibrary-1.12.1-1.6.1 (1).jar)
  cubex2.cxlibrary.CoreModTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
FMLPlugin (elulib-0.1.12.jar)
  elucent.elulib.asm.ASMTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (FoamFix-1.12.2-0.9.4-Anarchy (1).jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
llibrary (llibrary-core-1.0.6-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
LucraftCoreCoreMod (LucraftCore-1.12.2-2.1.2 (2).jar)
  lucraft.mods.lucraftcore.core.LCTransformer
GottaGoFastLoader (gottagofast-1.1.jar)
  com.thiakil.gottagofast.coremod.GottaGoFastASMTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13492 Compatibility Profile Context 22.19.677.257' Renderer: 'AMD Radeon(TM) R7 Graphics'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.4.2708
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) R7 Graphics GL version 4.5.13492 Compatibility Profile Context 22.19.677.257, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A10-7870K Radeon R7, 12 Compute Cores 4C+8G

**Comment by AlexModGuy** [comment]
#740
