### ISSUE TITLE
Ice spikes are unaffected by Effeciency enchantment

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#778]
No matter how much effeciency you got on your pickaxe, it will always take the same amount of time to mine the spikes.
Also atm they can only be obtained by using ice dragon and a silk touch pick, it would be nice if they are directly craftable for convenient sake.

**Comment by PlatinumFox** [comment]
ice isnt craftable in vanilla it would make no sense for ice spikes to be craftable

**Comment by mser7** [comment]
Packed Ices generated in abundant in Glacier biome, and is a trade from Snow Villagers for sapphire, plus they require Silk Touch to obtain, making spikes harder to craft.
Many other materials isn't craftable but they can still be use in recipes
Same for obsidians, but they can be crafted into obsidian spikes(Fossil and Archeology mod)
Is a useful block, but can only be obtained from an Ice dragon's blast impact is quite a hassle.

**Comment by AlexModGuy** [comment]
I'll make it craft able, but with dragon ice. this isnt normal ice spikes, but dragon ice spikes.

I'll also let snow villagers trade dragon ice as well.
