### ISSUE TITLE
Ender Dragon is immuned to literally every attacks of I/F dragons

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#779]
Title.

**Comment by AlexModGuy** [comment]
only players can hurt the boss. no other mob. this is vanilla stuff

**Comment by mser7** [comment]
No it isn't, with the exception of projectile, Iron Golems can as well, the problem is that the boss swing every mob that is trying to melee it. But the dragons blast attack is completely ignored. Sorry for the cringe video but here it is
https://www.youtube.com/watch?v=Dss2KxHoV4E
