### ISSUE TITLE
Runaway tamed dragon

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#781]
It is simple, when a tamed dragon or hippgryph decide to start flying, they will fly away into the distance forever, since they doesn't have anything bound to the player.

**Comment by mser7** [comment]
I know this isn't really a bug since it is based of the default behavior of wild mobs but it is very frustrating that they alway got lost if you aren't careful and you will have to search all direction for them since they fly very fast. I propose the ability to make them bound to a location using homepoint mechanics.

**Comment by AlexModGuy** [comment]
should be fixed with home point behavior in 1.5.0
