### ISSUE TITLE
Bug with Cockatrice

### ISSUE THREAD

**Issue by DevilKitten** [Alex-the-666/Ice_and_Fire#788]
![2018-06-15_16 54 10](https://user-images.githubusercontent.com/31811686/41491360-4c59dfe8-70be-11e8-9715-05d280fe17f0.png)
Happened right after a creeper blew up a cockatrice, items got wither effect particles.

**Comment by AlexModGuy** [comment]
creepers with potion effects leave lingering potion effect. this is vanilla feature
