### ISSUE TITLE
Arrows Phase through Dragons

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#79]
when an arrow is shot at a dragon it does not harm the dragon, it looks as if the arrow is bouncing off the dragon when in reality they are going straight through the dragon. i testes to see if having a flame would harm the dragon with fire and the same thing happened, flaming arrow hit dragon looked like it bounced off of it but the arrow actually went through the dragon.
ill try to show it in pictures, i tried to record it but my recording software has issues with minecraft forge at the moment

![2016-11-25_21 37 18](https://cloud.githubusercontent.com/assets/23727270/20637515/6dc65064-b358-11e6-9d52-4477a8fc436d.png)

![2016-11-25_21 39 23](https://cloud.githubusercontent.com/assets/23727270/20637518/7edf74f2-b358-11e6-9c0c-04e31a5f6e05.png)

![2016-11-25_21 39 55](https://cloud.githubusercontent.com/assets/23727270/20637522/93f57346-b358-11e6-8c82-82b22cb2de97.png)

for the picture above the arrows on and behind the chest are arrows that i shot the dragon from when i was behind it they went through it.

**Comment by Alex-the-666** [comment]
you arent hitting its bounding box, which is small bcs dragons are huge. Vanilla issue.
