### ISSUE TITLE
Cockatrices auto attacking creepers

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#793]
This is bad, there is certainly times when the cocktrice won't be able to kill the creeper on time.

**Comment by PCAwesomeness** [comment]
Dragons, cyclopes, and death worms attack Creepers as well; a cockatrice following suit is not an issue.

**Comment by mser7** [comment]
I know, but this is bad, as creepers are griefing.

**Comment by mser7** [comment]
They should blacklist all mob with "creeper" in the name.

**Comment by PCAwesomeness** [comment]
Also, cockatrices, Stymphalian birds, and trolls don't bother anything other than players or villagers, so I don't see why this issue is relevant...

**Comment by mser7** [comment]
Sure, I guess getting your base blown up isnt relevant... The problen lies in most people will have them around their home, unlike other mobs.

**Comment by mser7** [comment]
Even in the preview they promote them as a guardian for your base.

**Comment by PCAwesomeness** [comment]
Ah, tamed cockatrice seem to be able to attack creepers.

They seem to kill them very quickly half the time, but it can still be an issue if one is near your base, I guess.

**Comment by mser7** [comment]
Oh yeah, I guess wild cockatrices doesnt care much aout creeper nor hostile mobs
