### ISSUE TITLE
Spawn setting of cockatrice and troll is wrong

### ISSUE THREAD

**Issue by BlueWither** [Alex-the-666/Ice_and_Fire#794]
When  I saw config file, I found a wrong thing.

**Troll** spawn weight. Lower = lower chance to spawn [range: 1 ~ 10000, default: 10]
  I:"**Cockatrice** Spawn Weight"=4

**Comment by mser7** [comment]
Yep that is the spawnrate for Trolls

**Comment by AlexModGuy** [comment]
fixed in 1.5.1
