### ISSUE TITLE
Pixie Jars all turn into Pink Pixie Jars after some time

### ISSUE THREAD

**Issue by angelnc1989** [Alex-the-666/Ice_and_Fire#796]
Minecraft 1.12.2
Forge 14.23.4.2708
Ice and Fire 1.5.0

I placed down a Pixie Jar of each color and after some time they all turned into Pink Pixie Jars. The chunk they were in was loaded by a chunkloader the whole time.

**Comment by mser7** [comment]
After chunks reloading
