### ISSUE TITLE
Dragon health got reseted when fed with meals

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#801]
Tame dragon, lets call its current hp X
Feed dragon meals, dragon get more empty heart to fill
Feed steak to fill all those new hearts
Feed meals again, all those extra hp from thr steak are gone, and the new hp is X + 1

**Comment by epicslayer999** [comment]
This is intended. A sort of price to pay to make your dragon grow faster, if you will.

**Comment by mser7** [comment]
Correction: if their health is greater than 1/2 of their total health than when fed with dragons meal it got resetted, otherwise it keep the health.

**Comment by AlexModGuy** [comment]
fixed in 1.5.1
