### ISSUE TITLE
Troll weapon textures are missing 

### ISSUE THREAD

**Issue by NaomiVezer** [Alex-the-666/Ice_and_Fire#802]
![image](https://user-images.githubusercontent.com/17001045/41501947-d05907ee-71b6-11e8-9979-fb7b80437982.png)

**Comment by wamc2017** [comment]
#753 

Do you got optifine or other mods installed?

**Comment by PlatinumFox** [comment]
@NaomiVezer update to Llibrary 1.7.14 and make sure you have optifine HD U D3 or greater
https://optifine.net/downloads

**Comment by AlexModGuy** [comment]
gotta update optifine to D3
