### ISSUE TITLE
Improve the item eating behavior of Cocokatrice

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#803]
Despite there are food drops on the ground, they rarely move themself toward to eat them, they still eat if you throw the food directly at them, but even if the items are near them, they still don't want to eat it, even when they walk right pass it in some occasion, despite being in need of recovery.

**Comment by PCAwesomeness** [comment]
That's because you're trying to feed them when they're on full health...

**Comment by mser7** [comment]
...despite in need of recovery.

**Comment by mser7** [comment]
No it isn't, I have witnessed many of mine died bc they doesn't eat the rotten flesh drops and heal.

**Comment by PCAwesomeness** [comment]
Didn't happen for me. Whenever a cockatrice took damage, I'd drop rotten flesh near it, and it would eat the flesh, but wouldn't take any if it was on full health.

If you still say it doesn't work, try hand-feeding them seeds.

**Comment by mser7** [comment]
.

**Comment by mser7** [comment]
I did mention that it work if you throw them yourself, but not automatically ,did I? I wont be around to hand fed them everytime

**Comment by PCAwesomeness** [comment]
Alright.

**Comment by AlexModGuy** [comment]
dupe #799
