### ISSUE TITLE
hippogryph stuck on homepoint border

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#804]
There should be a config option for the radius of their area of wander.
Gittering flying when they reach the border of said area but still try to fly foward instead of back to the homepoint, this resulted in the mob hover flying toward a direction but cant move forward, dragons doesnt suffered from this.

**Comment by PlatinumFox** [comment]
According to alex there is an option for this

"alright, dragon and hippogryph "homes" are in
they stay within 800 blocks
*80
whew
thats configurabel btw
technically you could set it to 1 block" - alex from the discord

**Comment by mser7** [comment]
You're right, but that still leave the gittering issue.

**Comment by kihgy** [comment]
yeah they should look for an opposite path once hit the border instead of keep flying the old direction, basically make it more similar to dragons
