### ISSUE TITLE
unable to harvest blocks

### ISSUE THREAD

**Issue by LordDecay26** [Alex-the-666/Ice_and_Fire#806]
i updated both LLibrary and Ice and fire and now when i break blocks they dont drop.... i dunno what to do?

**Comment by AlexModGuy** [comment]
what other mods are you using

**Comment by LordDecay26** [comment]
too many to list, it's not a mod incompatibility as i have no mods which affect block harvesting.

**Comment by AlexModGuy** [comment]
well by that logic neither does ice and fire
