### ISSUE TITLE
Trolls which turn to stone keep their AI

### ISSUE THREAD

**Issue by LordDecay26** [Alex-the-666/Ice_and_Fire#807]
i have a troll that turned to stone but still slides across the ground with no animation and attacks me when i come near it.... it's messed up dude.

**Comment by epicslayer999** [comment]
Do you have Mowzie's Mobs installed? It is known to screw up the AI for when a mob gets turned to stone.

**Comment by LordDecay26** [comment]
i do now, just not when i made this bug report.

**Comment by mser7** [comment]
Close it then
