### ISSUE TITLE
Troll weapons not visible

### ISSUE THREAD

**Issue by LordDecay26** [Alex-the-666/Ice_and_Fire#808]
even with the latest version of Optifine.

**Comment by mser7** [comment]
Optifine

**Comment by NaomiVezer** [comment]
Fix it, without optifine not visible to the skin(

**Comment by LordDecay26** [comment]
i have optifine...

**Comment by epicslayer999** [comment]
Try updating the latest version of OptiFine.

**Comment by LordDecay26** [comment]
i am in the latest version of optifine.

**Comment by AlexModGuy** [comment]
no you arent. Update to D3
