### ISSUE TITLE
Issue with skeletons of dragons

### ISSUE THREAD

**Issue by Vadimaldo** [Alex-the-666/Ice_and_Fire#809]
I`am playing on server with my friend, and when we come to the desert minecraft crashing. He can't generate skeletons. We have to remove all entities from the server, so we have no worms or skeletons in the deserts. What would you suggest that we fix this mistake? Or will there be some patch that fixes this? Thanks!

**Comment by AlexModGuy** [comment]
see #740 remove thaumcraft
