### ISSUE TITLE
Death worm has little hp

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#818]
The maximized giant sized worm I found only has 41 hp, while the little ones have only 15 ish hp, I propose revert their hp back to before so they can remain the title "death" in their name.

**Comment by PCAwesomeness** [comment]
They got nerfed because Alex felt they were incredibly cheap for a monster that lives in an early-game environment.

Besides, you can edit their HP and attack strength in the config.

**Comment by LordDecay26** [comment]
^^what he said.

**Comment by mser7** [comment]
Fair enough.
