### ISSUE TITLE
Trolls spawn too rare on normal world

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#819]
Despite I cranked up their spawn weight to 10000, they don't see to spawn at all, inspect all the caves and all. However, they spawn normal with a superflat world

**Comment by LordDecay26** [comment]
yeah i had this issue as well. among many others. seems that Trolls are very incomplete in this mod version, and should not have been released just yet, still cool to play around with them, tho.

**Comment by BlueWither** [comment]
I thought so too...

**Comment by mser7** [comment]
Superflat spawning
https://cdn.discordapp.com/attachments/381304640383483905/458266887831158785/2018-06-18_10.39.35.png
https://cdn.discordapp.com/attachments/381304640383483905/458266897239113729/2018-06-18_10.39.10.png

**Comment by mser7** [comment]
Trolls spawning as of now is ok.

**Comment by BlueWither** [comment]
Oh,how did you solve the problem?

**Comment by mser7** [comment]
I didnt solve it tbh, I just do some testing and find out they does spawn, and sometimes, can spawn in packs, just very rare, but the rarely spawn can be solved by crank up the spawnrate

**Comment by BlueWither** [comment]
I see.
