### ISSUE TITLE
Separated wander area for different mobs

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#820]
It kinda inconvenient to have them all based around the dragons, its best to have it separated for all mobs that can wander, or atleast have separated configs for flying and walking mobs.

**Comment by GundunUkan** [comment]
Tamed and wild dragons should have separate ones as well. For instance, I want wild dragons to stick around their roosts to protect their loot, but the price for this is my stage 5 dragon flies in a tiny for it circle.

**Comment by AlexModGuy** [comment]
move to suggestions
