### ISSUE TITLE
dragons walking not just on land

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#83]
version beta 3
dragons are still walking/standing in the air they also walk/stand on water now

![2016-11-26_19 36 19](https://cloud.githubusercontent.com/assets/23727270/20644827/f3115eb6-b412-11e6-925d-ac03a745a871.png)

![2016-11-26_19 44 44](https://cloud.githubusercontent.com/assets/23727270/20644830/facd430e-b412-11e6-9605-e69de94dc172.png)

i noticed for dragons in the air (whether its walking or flying) they stop moving forward and wont move until the player moves forward. it seems that they are unable to fly out side of the players chunk distance perhaps.

**Comment by Sunconure11** [comment]
I saw an Ice Dragon try to chase a mob that was underwater, and it was just spazzing out on the water's surface.

**Comment by Alex-the-666** [comment]
The "walking" on water is intended. The bounding boxes spam out in the water so they float on it.

However, shouldn't the one int he air be falling slowly? if so its doing what it is supposed to.

**Comment by PlatinumFox** [comment]
the one in the air was definitely not falling it was just sitting there.
if i stopped flying toward it the dragon just sat there not moving. as i flew closer to it the dragon started to walk in mid air.

**Comment by Zeklo** [comment]
I too have seen a dragon do this will ascending.

**Comment by Alex-the-666** [comment]
Has anyone seen this happening in betatest 06?

**Comment by PlatinumFox** [comment]
Yes. i Downloaded Beta 6 and found 2 naturally spawning dragons near each followed them and watched them for a while. The link below is a link to a short unlisted video i made (only with the link can it be viewed).
https://www.youtube.com/watch?v=Yc5foI6Svpc

**Comment by Alex-the-666** [comment]
Hmm. It appears they start flying when they sleep, but then wake up and continue flying.
