### ISSUE TITLE
Petrified chickens still walk around 1.5.0

### ISSUE THREAD

**Issue by Frosty8-0** [Alex-the-666/Ice_and_Fire#830]
Sometimes petrified chickens (by gorgon) still walk around.

**Comment by BlueWither** [comment]
No Mowzie's Mobs?

**Comment by Frosty8-0** [comment]
Yes I was using Mowzies Mobs..  Are they incompatible?

**Comment by BlueWither** [comment]
I do not know the cause, but when using Mowzie's Mobs the stone statue seems to move.
That problem has already been reported.

**Comment by AlexModGuy** [comment]
dupe of mowzies mob issue
