### ISSUE TITLE
Exiting mounts make them fall to the void

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#834]
Create a void wold, you then spawned on a stone platform
Spawn some hippogryphs and dragons at the rear of the platform to let them fall to the void, they automatically enter fly mode once got too low
Spawn a tamed mob and ride it above the void then get off, the mob fell straight down to the void and don't fly up.

**Comment by mser7** [comment]
Dragon flute should be taken into consideration as well

**Comment by GundunUkan** [comment]
Dismounted dragons do that so in a survival world you don't loose them. I think the survival mode should be prioritized rather than a void world.

**Comment by mser7** [comment]
What if you want to use them in The End? Also, the mobs dont keep flying, but they fall, it is just that at y=0, they start to fly so that they dont fall to the void, it is an intended behavior, but is glitched when players dismount them.

**Comment by mser7** [comment]
You also cannot access the void in a regular overworld, but the forced flying at y=0 behavior is still implemented.
