### ISSUE TITLE
Mid-flying mobs are hard to control

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#839]
Mob while in flying state retain their own AI instead of the player's.
How to replicate a flying state mob.
Tame two hippogryphs, put saddle on both.
Hop onto one hippogryph and enter fly mode, while having the other one sitting
Fly to the sitting one, carefully adjust so that the mob doesn't exit its flying state while the sitting one is in your reach, right click the sitting one to hop onto it, and the flying one should fly free according to its will.
Now hop onto the flying one while it is flying and try to control it, you can't and the mob go wherever it liked.

And yes, it happened to dragons too.

**Comment by AlexModGuy** [comment]
dupe #516
