### ISSUE TITLE
EntityProperties cap crash

### ISSUE THREAD

**Issue by mxnmnm** [Alex-the-666/Ice_and_Fire#842]
https://pastebin.com/SsSHmneX

forge 1.12.2-14.23.4.27055
ice and fire 1.5.0-1.12.2

I was opening a book from exotic birds and I might've accidentally tried to open a chest but I'm not sure.

edit- it makes the book completely unusable (it gives the same crash as above whenever I interact with it) and you should probably try to contact pavocado (the person who made exotic birds)

**Comment by pau101** [comment]
This should be getting this resolved soon: iLexiconn/LLibrary/issues/86

**Comment by mxnmnm** [comment]
Exotic birds updated so all is good now
