### ISSUE TITLE
Random crash. Not even moving.

### ISSUE THREAD

**Issue by lelosaiyan** [Alex-the-666/Ice_and_Fire#844]
https://pastebin.com/cueM5na2

**Comment by aridhol** [comment]
Similar crash has happened to me a few times - https://paste.dimdev.org/begewiwego.mccrash

**Comment by AlexModGuy** [comment]
> | UCHIJA | thaumcraft               | 6.1.BETA16


dupe #740 ... sometimes I think you guys don't know how to use the search button... or read the changelogs...
