### ISSUE TITLE
Ticking entity null pointer

### ISSUE THREAD

**Issue by aridhol** [Alex-the-666/Ice_and_Fire#845]
https://paste.dimdev.org/afacusisac.mccrash

Happening to me when playing SMP, I have not noticed it in SSP

**Comment by aridhol** [comment]
https://paste.dimdev.org/uzohocilif.mccrash another instance of the crash. If I wait for the entity to despawn on the server, I can log back in. Otherwise it insta-crashes

Seems to be related to the passenger tag

**Comment by aridhol** [comment]
https://paste.dimdev.org/hiconuyesu.mccrash in case another example is useful

**Comment by Alex-the-666** [comment]
dupe #740 
>thaumcraft        | 6.1.BETA16        
incompatable with ice and fire, on their end
