### ISSUE TITLE
Compatibility for the podiums

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#848]
Other eggs suck as hippogryph or death worm egg should also be displayable on the podium, not just dragon eggs.

**Comment by mser7** [comment]
This of course, would require a 3d model for those eggs and probably a revamp of the hatching mechanic into not just throw the egg at a wall

**Comment by PlatinumFox** [comment]
New hatching mechanics are not required. A 3D model would have to me made for the podium but the eggs would not be able to be placed on the ground. I think we should be able to put all eggs in podium to view. But this belongs in the suggestions section.

**Comment by mser7** [comment]
Agree on the mechanic, but this is an enhancing suggestion, those usually get posted here.

**Comment by mser7** [comment]
I would say, the dinosaur eggs from fossil and
