### ISSUE TITLE
Ice dragon hatchlings aren't tamed

### ISSUE THREAD

**Issue by JayZX535** [Alex-the-666/Ice_and_Fire#85]
Hatching an ice dragon results in an untamed hatchling.  It appears to be independent of color (I tested two of them- white and sapphire).  Fire dragon hatchlings seem to be fine still.

**Comment by Dakotsie** [comment]
This issue was already reported and fixed in issue #74 but hasn't been compiled into a playable version yet. Hopefully they get a new build out soon so we can have some fun, ahem, test the ice dragons. xD

**Comment by JayZX535** [comment]
Oh, okay XD  Thanks for the heads-up!
