### ISSUE TITLE
Cockatrice's vision

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#850]
The cockatrice's glare when vs.mobs must be looked directly at them, and the mob must be looking at the cockatrices as well, like when vs. Player, which greatly hold back their potential to glare everything to death

**Comment by AlexModGuy** [comment]
no, for the same reason as the gorgon,

It's difficult to get mobs to stare at something, especially a custom mob. It's much easier for the player to do that.
