### ISSUE TITLE
Rotten eggs popping STILL haven't fixed

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#851]
I waited 20 mins with the maximum egg drop rate and with 10 vanilla chickens and they only pops normal eggs

**Comment by AlexModGuy** [comment]
delete your config. this issue was caused by the config being an irrationally high number(10000) compared to what it was supposed to be (10)

**Comment by mser7** [comment]
Okay I will try thanks

**Comment by mser7** [comment]
Still normal eggs, config reseted and all

**Comment by mser7** [comment]
Reopen this if you would, this hasn't been solved at all.
