### ISSUE TITLE
Dragon Skulls too small

### ISSUE THREAD

**Issue by RealisticMC73309** [Alex-the-666/Ice_and_Fire#858]
Dragon skulls don't really match the dragon's real head size. They are very much smaller. Like 3 times smaller in stage one dragons for example.

**Comment by mser7** [comment]
Proof
https://cdn.discordapp.com/attachments/459015814394281985/460743495724957708/The_smallest_coffins_are_the_heaviest.png

**Comment by RealisticMC73309** [comment]
Yea the skulls are very tiny. Too small and out of scale with the living head of the dragon

**Comment by AlexModGuy** [comment]
fixed
