### ISSUE TITLE
Hatchlings on shoulder start to block view as they grow

### ISSUE THREAD

**Issue by JayZX535** [Alex-the-666/Ice_and_Fire#86]
I mean, maybe it's a bad idea to carry older hatchlings on your shoulder anyway (it looks painful o.o) but they do start to block the view...
![2016-11-27_00 52 32](https://cloud.githubusercontent.com/assets/14882581/20646968/f435fe36-b43b-11e6-9483-9a29463f40d2.png)
![2016-11-27_00 54 22](https://cloud.githubusercontent.com/assets/14882581/20646977/0f69c944-b43c-11e6-9505-66f416061d44.png)

**Comment by Alex-the-666** [comment]
then dont carry old ones on your shoulder :P
