### ISSUE TITLE
Eggs not hatching.

### ISSUE THREAD

**Issue by YoonaWolf** [Alex-the-666/Ice_and_Fire#861]
When I try to hatch a fire dragon egg, it just disappears in the fire. When I try to hatch a ice dragon egg, it turns into a item before even freezing in the ice. Now I can't tame any dragons...

**Comment by YoonaWolf** [comment]
I'm using version 1.5.1 of the mod.

**Comment by redwolf41** [comment]
I'm in 1.5.2 and also having this issue.

**Comment by AlexModGuy** [comment]
fixed ice eggs snapping
