### ISSUE TITLE
Tamed cockatrice attacking tamed dragons

### ISSUE THREAD

**Issue by MooniePie** [Alex-the-666/Ice_and_Fire#864]
A baby cockatrice attacked and killed my 10 day old dragon after I hit a chicken. The chicken may be unrelated, but the cockatrice was fine with the dragon until I had done that.

**Comment by AlexModGuy** [comment]
what version are you using

**Comment by MooniePie** [comment]
I am using version 1.5.0.

**Comment by AlexModGuy** [comment]
this bug was fixed in 1.5.1
