### ISSUE TITLE
Tamed Pixies consume cakes

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#868]
They shouldn't, they are already tamed.

**Comment by GundunUkan** [comment]
So? They still can enjoy a nice flavory cake, can't they? :P

**Comment by mser7** [comment]
No, cakes are pricey, a pixie consume an entire cakeon regular basis which is much bigger then then wouldnt make sense, that is why they obey you if you give cake, since a cake is considered a enormous offering to them.

**Comment by drakkensong21** [comment]
Cakes are not pricey what the heck are you talking about
