### ISSUE TITLE
Dragon Corpse Using Bite Attack

### ISSUE THREAD

**Issue by Zeklo** [Alex-the-666/Ice_and_Fire#87]
Either the dragon wasn't dead and fell asleep mid-combat (while still attacking), or the corpse was using the bite attack. Either way.

**Comment by JayZX535** [comment]
There's definitely something messed up with dragon deaths.  I'm not positive this is the same bug, but it sounds like it could be.  I got the dragon slayer achievement, but the dragon I "killed" was alive, killed me, and flew away _after_ I got the achievement.
