### ISSUE TITLE
stymphalianbirds 

### ISSUE THREAD

**Issue by Varg95** [Alex-the-666/Ice_and_Fire#872]
Hey, i noticed that stymphalianbirds don't show up on journey maps, go true force-fields of rftools and can't get killed when i kill all hostile or passives. i suspect that there is an error in the entity registry. i'm no coder so i can't check but all this things have one thing in common.  (also i checked all your other mobs and they worked fine with the things described above.)

**Comment by AlexModGuy** [comment]
fixed
