### ISSUE TITLE
Dragon roars/flight sound but no dragon?

### ISSUE THREAD

**Issue by BelatedBeta** [Alex-the-666/Ice_and_Fire#873]
I wouldn't really mind it so much except it decided to happen right in my base. The only dragon that spawned nearby is quite far and I haven't heard it from my doorstep. But, as I set out to capture some chickens, once I returned, ROAR. (I freaked out)
I looked around using Creative mode and I couldn't find it. And for some reason, it's the loudest at ground level? If I fly around, it's softer. If I move from this one spot, it's softer. I assumed it was glitched underground so I dug but no cigar. I am really confused.

Is there any way to despawn it? Or whatever "it" is? It's really annoying, especially since it ruins the fun of the real deal swooping in. Please save me from this roaring hell ;-;

**Comment by LordDecay26** [comment]
ever tried looking up?

**Comment by BelatedBeta** [comment]
Oh right, look for a flying creature in the sky! How did I not think of
that!

Regardless, I fixed it with the kill all entities command.

**Comment by AlexModGuy** [comment]
dupe #1447
