### ISSUE TITLE
Hippogryphs don't fly

### ISSUE THREAD

**Issue by Waynekosimoto** [Alex-the-666/Ice_and_Fire#875]
I held spacebar, I tapped spacebar, nothing works. The thing won't fly, It stays in the hover animation endlessly.

**Comment by HackerSombra** [comment]
It was a little hard at first to get my hippogryphs to fly but after double tapping the space bar a few times I got them to take off.

**Comment by AlexModGuy** [comment]
you have to hold the space bar down for like 3 seconds
