### ISSUE TITLE
Dragon Sinking into the Ground and Vanishing

### ISSUE THREAD

**Issue by Zeklo** [Alex-the-666/Ice_and_Fire#88]
I was mid-combat with an ice dragon. It grabbed me, and the moment it let go, it sank into the ground. I dug around for quite a while, and then switched to creative, but it was no where to be found.

**Comment by PlatinumFox** [comment]
something similar happened to me. i killed an ice dragon using the new fire sword (the name escapes me atm) and when i killed it it sank into the ground.

**Comment by Alex-the-666** [comment]
Does this still happen? I've killed 3 ice and fire dragons and haven't seen this.
