### ISSUE TITLE
Tamed dragon griefing

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#881]
No I was not prefered to the block destroying behavior, but the fact that they grief using their blast, they can target some mob near your house and BOOM, explosion and you have a crater to fix.
There need to be a way to tell them to only attack using thr melee, and Im thinking we need to dragon command stick to teach them, perhap G + right click to tell them to do or not to do.

**Comment by mser7** [comment]
A non-destructive blast attack would also be cool, like the dragon will only apply the burning/frozen effect to the mob and not destroy the terrain while melee it.

**Comment by AlexModGuy** [comment]
I made it so tamed dragons won't break blocks with a slam attack.

**Comment by mser7** [comment]
The problem is not the slam attack, but the blast, it changed normal blocks and sometimes will produce explosive charge, I would like my tamed dragon not use the blast attack on its own
