### ISSUE TITLE
explain, please.

### ISSUE THREAD

**Issue by LordDecay26** [Alex-the-666/Ice_and_Fire#886]
> --- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.6.0.jar)
  BCModPlugin (backpacks+1.12.2+-+3.4.4.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.1.4-universal (1).jar)
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.12.jar)
  CreativePatchingLoader (CreativeCore_v1.9.22_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 7/4/18 4:47 PM
Description: Exception in server tick loop

java.lang.RuntimeException: Couldn't load BCMod-Items.dat
	at brad16840.common.UniqueItemData.loadData(UniqueItemData.java:87)
	at brad16840.common.Common.loadEvent(Common.java:633)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_237_Common_loadEvent_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at Reflector.call(Reflector.java:955)
	at Reflector.postForgeBusEvent(Reflector.java:1182)
	at Reflector.postForgeBusEvent(Reflector.java:1168)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:113)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:209)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at net.minecraft.nbt.CompressedStreamTools.func_74796_a(CompressedStreamTools.java:26)
	at brad16840.common.UniqueItemData.loadData(UniqueItemData.java:51)
	... 15 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1127077592 bytes (1074 MB) / 2382364672 bytes (2272 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2712 Optifine OptiFine_1.12.2_HD_U_D3 99 mods loaded, 99 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID                                           | Version                         | Source                                        | Signature                                |
	|:------- |:-------------------------------------------- |:------------------------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAA | minecraft                                    | 1.12.2                          | minecraft.jar                                 | None                                     |
	| UCHIJAA | mcp                                          | 9.42                            | minecraft.jar                                 | None                                     |
	| UCHIJAA | FML                                          | 8.0.99.99                       | forge-1.12.2-14.23.4.2712.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAA | forge                                        | 14.23.4.2712                    | forge-1.12.2-14.23.4.2712.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAA | creativecoredummy                            | 1.0.0                           | minecraft.jar                                 | None                                     |
	| UCHIJAA | com.elytradev.movingworld.common.asm.coremod |                                 | minecraft.jar                                 | None                                     |
	| UCHIJAA | antiqueatlas                                 | 4.4.7                           | antiqueatlas-1.12.2-4.4.7.jar                 | None                                     |
	| UCHIJAA | antiqueatlasoverlay                          | 1.2                             | antiqueatlas-1.12.2-4.4.7.jar                 | None                                     |
	| UCHIJAA | examplemod                                   | 1.0                             | antiqueatlas-1.12.2-4.4.7.jar                 | None                                     |
	| UCHIJAA | aquaculture                                  | 1.6.0                           | Aquaculture-1.12.2-1.6.0.jar                  | None                                     |
	| UCHIJAA | astikoor                                     | 1.0.0                           | astikoor-1.0.0.jar                            | None                                     |
	| UCHIJAA | autoreglib                                   | 1.3-16                          | AutoRegLib-1.3-16.jar                         | None                                     |
	| UCHIJAA | babyanimals                                  | 1.11-2                          | BabyAnimals-1.11-2.jar                        | None                                     |
	| UCHIJAA | backpacks16840                               | 3.4.4                           | backpacks+1.12.2+-+3.4.4.jar                  | None                                     |
	| UCHIJAA | bamboozled                                   | 1.1.0                           | Bamboozled-1.12-1.1.0.jar                     | None                                     |
	| UCHIJAA | baubles                                      | 1.5.2                           | Baubles-1.12-1.5.2.jar                        | None                                     |
	| UCHIJAA | biomesoplenty                                | 7.0.1.2381                      | BiomesOPlenty-1.12.2-7.0.1.2381-universal.jar | None                                     |
	| UCHIJAA | birdsnests                                   | 2.1.0                           | BirdsNests1.12.2-2.1.0 (1).jar                | None                                     |
	| UCHIJAA | carbonado                                    | 1.4.2                           | carbonado-1.4.2-mc1.12.x.jar                  | None                                     |
	| UCHIJAA | ceramics                                     | 1.12-1.3.4                      | Ceramics-1.12-1.3.4.jar                       | None                                     |
	| UCHIJAA | codechickenlib                               | 3.1.6.339                       | CodeChickenLib-1.12.2-3.1.6.339-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAA | extendedrenderer                             | v1.0                            | coroutil-1.12.1-1.2.11.jar                    | None                                     |
	| UCHIJAA | coroutil                                     | 1.12.1-1.2.11                   | coroutil-1.12.1-1.2.11.jar                    | None                                     |
	| UCHIJAA | configmod                                    | v1.0                            | coroutil-1.12.1-1.2.11.jar                    | None                                     |
	| UCHIJAA | creativecore                                 | 1.9.9                           | CreativeCore_v1.9.22_mc1.12.2.jar             | None                                     |
	| UCHIJAA | culinaryconstruct                            | 1.1.0                           | culinaryconstruct-1.1.0.jar                   | None                                     |
	| UCHIJAA | movingworld                                  | 1.12-6.342                      | movingworld-1.12-6.342-full.jar               | None                                     |
	| UCHIJAA | davincisvessels                              | @DVESSELSVER@                   | davincisvessels-1.12-6.340-full.jar           | None                                     |
	| UCHIJAA | death_compass                                | 0.0.2                           | DeathCompass-0.0.2.jar                        | None                                     |
	| UCHIJAA | duckcraft                                    | 3.0.8                           | Duckcraft-1.12.2-3.0.8.jar                    | None                                     |
	| UCHIJAA | dsurround                                    | 3.4.9.12                        | DynamicSurroundings-1.12.2-3.4.9.12.jar       | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHIJAA | presets                                      | 3.4.9.12                        | DynamicSurroundings-1.12.2-3.4.9.12.jar       | None                                     |
	| UCHIJAA | enhancedvisuals                              | 1.0                             | EnhancedVisuals+v1.1.4+mc1.12.jar             | None                                     |
	| UCHIJAA | silentlib                                    | 2.2.18                          | SilentLib-1.12-2.2.18-100.jar                 | None                                     |
	| UCHIJAA | extendeddays                                 | 0.2.4                           | ExtendedDays-1.12-0.2.4-20.jar                | None                                     |
	| UCHIJAA | familiarfauna                                | 1.0.6                           | FamiliarFauna-1.12.2-1.0.6.jar                | None                                     |
	| UCHIJAA | felling                                      | 1.4.0                           | felling-1.4.0-1.12.x.jar                      | None                                     |
	| UCHIJAA | foragecraft                                  | 1.14.2                          | foragecraft-1.14.2.jar                        | None                                     |
	| UCHIJAA | forgelin                                     | 1.6.0                           | Forgelin-1.6.0.jar                            | None                                     |
	| UCHIJAA | ghastleather                                 | 1.0                             | ghastleather-1.0.jar                          | None                                     |
	| UCHIJAA | giacomos_bookshelf                           | 1.2                             | GiacomosBookshelf-1.12.2-1.2.jar              | None                                     |
	| UCHIJAA | giacomos_fishing_net                         | 1.6.1                           | GiacomosFishingNet-1.12.2-1.6.1.jar           | None                                     |
	| UCHIJAA | guideapi                                     | 1.12-2.1.4-57                   | Guide-API-1.12-2.1.4-57.jar                   | None                                     |
	| UCHIJAA | llibrary                                     | 1.7.14                          | llibrary-1.7.14-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHIJAA | iceandfire                                   | 1.5.1                           | iceandfire-1.5.1-1.12.2.jar                   | None                                     |
	| UCHIJAA | ichunutil                                    | 7.1.4                           | iChunUtil-1.12.2-7.1.4.jar                    | None                                     |
	| UCHIJAA | illagerspell                                 | 1.2                             | illagerspell-1.12.2-1.2.jar                   | None                                     |
	| UCHIJAA | jei                                          | 4.9.1.168                       | jei_1.12.2-4.9.1.168.jar                      | None                                     |
	| UCHIJAA | jaff                                         | 1.7_for_1.12                    | JustAFewFish-1.7_for_1.12.jar                 | None                                     |
	| UCHIJAA | keepequipment                                | 1.01                            | keepequipment-1.01.jar                        | None                                     |
	| UCHIJAA | leatherworks                                 | 1.71.2                          | LeatherWorks-1.12-1.71.2.26.jar               | None                                     |
	| UCHIJAA | loyaltymedals                                | 1.2                             | Loyalty+Medals-1.2.jar                        | None                                     |
	| UCHIJAA | maille                                       | 2.0                             | Maille1.12.2-2.0 (1).jar                      | None                                     |
	| UCHIJAA | testdummy                                    | 1.12                            | MmmMmmMmmMmm-1.12-1.14.jar                    | None                                     |
	| UCHIJAA | mowziesmobs                                  | 1.4.1                           | mowziesmobs-1.4.1.jar                         | None                                     |
	| UCHIJAA | naturalbabyanimals                           | 1.1.3                           | naturalbabyanimals-1.1.3-mc1.12.x.jar         | None                                     |
	| UCHIJAA | nbsplayer                                    | 1.1.0.1                         | NBS+Player+1.1.0.1+(Forge+1.12).jar           | None                                     |
	| UCHIJAA | nethergoldore                                | 1.1.2                           | nethergoldore-1.1.2-mc1.12.x.jar              | None                                     |
	| UCHIJAA | notenoughscaffold                            | 1.7                             | NotEnoughScaffold-1.12.2-1.7.jar              | None                                     |
	| UCHIJAA | opframe                                      | 1.4.0                           | OnlinePicFrame_v1.4.18_mc1.12.2.jar           | None                                     |
	| UCHIJAA | owls                                         | 1.12.2-1.0.1                    | Owls-1.12.2-1.0.1.jar                         | None                                     |
	| UCHIJAA | bonecraft                                    | 1.12.2a                         | Pam's+BoneCraft+1.12.2a.jar                   | None                                     |
	| UCHIJAA | desertcraft                                  | 1.12.2a                         | Pam's+DesertCraft+1.12.2a.jar                 | None                                     |
	| UCHIJAA | llamamilking                                 | 1.12.2b                         | Pam's+Llama+Milking+1.12.2b.jar               | None                                     |
	| UCHIJAA | sheepmilking                                 | 1.12.2b                         | Pam's+Sheep+Milking+1.12.2b.jar               | None                                     |
	| UCHIJAA | simplystrawberries                           | 1.12.2-1.0.0                    | Pam's+Simply+Strawberries+1.12.2+-+1.0.0.jar  | None                                     |
	| UCHIJAA | jmilpol                                      | 1.2                             | PendantOfLife-1.3.jar                         | None                                     |
	| UCHIJAA | petbat                                       | 1.4.8                           | PetBat-1.12.2.jar                             | None                                     |
	| UCHIJAA | placeableitems                               | 3.3                             | placeableitems-3.3.jar                        | None                                     |
	| UCHIJAA | platemail                                    | 1.0.3                           | Platemail1.3.jar                              | None                                     |
	| UCHIJAA | primitivetools                               | 1.0.0                           | PrimitiveTools-1.12-1.0.0.jar                 | None                                     |
	| UCHIJAA | pumpkincarving                               | 1.3.3                           | PumpkinCarving1.12-1.3.3.jar                  | None                                     |
	| UCHIJAA | reforged                                     | 0.7.5                           | Reforged-0.7.5-1.12+.jar                      | None                                     |
	| UCHIJAA | roost                                        | 1.2.0                           | roost-1.12-1.2.0.jar                          | None                                     |
	| UCHIJAA | rustic                                       | 1.0.3                           | rustic-1.0.3.jar                              | None                                     |
	| UCHIJAA | bonetorch                                    | @MAJOR@.@MINOR@.@REVIS@.@BUILD@ | SBM-BoneTorch-1.12-0.0.1b3.jar                | None                                     |
	| UCHIJAA | merpig                                       | 1.12.2-0.0.1.20180406032656     | SBM-Merpig-1.12.2-0.0.1b20180406032702.jar    | None                                     |
	| UCHIJAA | sereneseasons                                | 1.1.4                           | SereneSeasons-1.12.2-1.1.4-universal (1).jar  | None                                     |
	| UCHIJAA | sharpbone                                    | 1.0                             | SharpBone-1.12.2-1.0.jar                      | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| UCHIJAA | simplecorn                                   | 2.3.7                           | SimpleCorn1.12-2.3.7.jar                      | None                                     |
	| UCHIJAA | simplycoffee                                 | 1.2.0                           | Simply_Coffee_Release-1.2.0.jar               | None                                     |
	| UCHIJAA | simplytea                                    | 1.4                             | simplytea-1.4.jar                             | None                                     |
	| UCHIJAA | soulshardsrespawn                            | 1.12.2-1.0.5-7                  | SoulShardsRespawn-1.12.2-1.0.5-7.jar          | None                                     |
	| UCHIJAA | soundfilters                                 | 0.10_for_1.12                   | SoundFilters-0.10_for_1.12.jar                | None                                     |
	| UCHIJAA | sugiforest                                   | 1.4.0                           | SugiForest_1.12-v1.4.0.jar                    | None                                     |
	| UCHIJAA | thut_wearables                               | 3.1.6                           | thut-wearables-1.12.2-3.1.6.jar               | None                                     |
	| UCHIJAA | toast                                        | 1.12.2-1.0                      | toast-1.12.1-1.0 (1).jar                      | None                                     |
	| UCHIJAA | toolbelt                                     | 1.7.1                           | ToolBelt-1.12.0-1.7.1.jar                     | None                                     |
	| UCHIJAA | totemexpansion                               | 1.2.1                           | totemexpansion-1.2.1-1.12.2.jar               | None                                     |
	| UCHIJAA | transloc                                     | 1.0.5                           | transloc-1.12.2_1.0.5.jar                     | None                                     |
	| UCHIJAA | tumbleweed                                   | 1.11-0.4.5                      | tumbleweed-1.11-0.4.5.jar                     | None                                     |
	| UCHIJAA | veining                                      | 1.3.0                           | veining-1.3.0-1.12.x.jar                      | None                                     |
	| UCHIJAA | venomousfangs                                | 1.1                             | VenomousFangs1.12-1.1.jar                     | None                                     |
	| UCHIJAA | waddles                                      | 0.6.0                           | Waddles-1.12.2-0.6.0.jar                      | None                                     |
	| UCHIJAA | walljump                                     | 1.12.2-1.1.5                    | walljump-1.12.2-1.1.5.jar                     | None                                     |
	| UCHIJAA | wearablebackpacks                            | 3.1.2                           | WearableBackpacks-1.12.2-3.1.2.jar            | None                                     |
	| UCHIJAA | weeeflowers                                  | 1.12.2b                         | Weee!+Flowers+1.12.2b.jar                     | None                                     |
	| UCHIJAA | zombie_players                               | 1.12.1-1.1.1                    | zombie_players-1.12.1-1.1.1.jar               | None                                     |
	| UCHIJAA | gaspunk                                      | 1.3.3                           | gaspunk-1.12.2-1.3.3.jar                      | 0cfad38b57cdd4e6a62549ddef0eb461efb573b3 |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.6.0.jar)
  
BCModPlugin (backpacks+1.12.2+-+3.4.4.jar)
  brad16840.core.ClassTransformer
SSLoadingPlugin (SereneSeasons-1.12.2-1.1.4-universal (1).jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
llibrary (llibrary-core-1.0.6-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.12.jar)
  org.blockartistry.DynSurround.asm.Transformer
CreativePatchingLoader (CreativeCore_v1.9.22_mc1.12.2.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_D3
	OptiFine Build: 20180515-125031
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.201.1151.1008
	OpenGlRenderer: AMD Radeon HD 6670
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by Sunconure11** [comment]
Not related to ice and fire.

**Comment by AlexModGuy** [comment]
crash with brad16840 backpacks
