### ISSUE TITLE
Dragon lairs WAY too close to spawn!

### ISSUE THREAD

**Issue by JayZX535** [Alex-the-666/Ice_and_Fire#89]
Okay, I know this isn't so much a bug as it is a balance issue, but... this really needs to be addressed o.o
This is the spawn of a world I made for testing.
![2016-11-29_14 13 13](https://cloud.githubusercontent.com/assets/14882581/20731182/1e13921e-b63e-11e6-8006-94bd8b9f2346.png)
If you dig a hole straight down from the block you spawn on...
![2016-11-29_14 13 31](https://cloud.githubusercontent.com/assets/14882581/20731203/30166310-b63e-11e6-8aee-e1992011912f.png)
You find this.
![2016-11-29_14 13 42](https://cloud.githubusercontent.com/assets/14882581/20731207/3725b2a0-b63e-11e6-9761-44b0f752cc27.png)

This lair is literally directly under spawn.  In the survival world, the dragon actually BURST OUT from under spawn within a few Minecraft days of the world's creation.  I can live with the roosts being sort of near spawn, but even the level 3s and under have killed me pretty much instantly when I spawn.  My spawn point in the survival version of this world is actually now IN the dragon lair, after the dragon left it.  And yeah, that did give me an unholy amount of incredible loot.  But if I hadn't been in hiding when the dragon emerged, I'm pretty sure it would have turned into me dying and being pretty much insta-killed by the dragon every time I respawned.

It's one thing if a player leaves spawn and sets up over a dragon lair.  But having the lairs, or even the roosts, spawning so near to the actual world spawn is pretty unbalanced in my opinion.  Is there any way that you guys could stop that from happening?
Thanks, and again, sorry that this isn't so much a bug as it is a balance issue, but I really, really think it's important to fix if possible...

**Comment by Alex-the-666** [comment]
No. stop reopening issues that we have said we don't care about or see as important. You just got fucked by RNJesus in this case, not our fault. Happens in every mod/video game.
