### ISSUE TITLE
Lost dragon mount while fighting ice dragon

### ISSUE THREAD

**Issue by EnderiumSmith** [Alex-the-666/Ice_and_Fire#892]
I flew on my fire dragon above a fire dragon and started attacking it with fire. it caught up and threw me off when it was just on hit away from death. After i killed it i searched for the fire dragon but never found it. I tried teleporting all fire dragons to me but that only resulted in 2 stage 5 dragon(weirdly since it was an ice plain). I tried doing it in other places but nothing. In fact even the 2 stage 5 dragons were gone.

Dragons should land if dismounted in the air.

**Comment by WiseDragoon** [comment]
It also happened to me twice. My dragon disappeared when I got lured by a siren. It got me down from my dragon and it then despawned (I checked its home point too, it wasn't there).

**Comment by EnderiumSmith** [comment]
is it supposed to teleport home? its home point is on another continent.

**Comment by AlexModGuy** [comment]
dupe #707
