### ISSUE TITLE
Nest Dragons Dissapering

### ISSUE THREAD

**Issue by Aluriyasha** [Alex-the-666/Ice_and_Fire#896]
I and my friend had a recent issue with one or several dragons disappearing underground when we fought them they simply disappeared under the world. They refuse to come back up etc and stay there to killed or despawned. (confirmed since we flew all the way down there in creative and killed them), it's a repeating issue and would love if you looked into it thanks.

**Comment by AlexModGuy** [comment]
dupe #639
