### ISSUE TITLE
Right clicking tamed pixies with suger to heal them

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#908]
Doesnt implemented

**Comment by mser7** [comment]
Since pixie flying is chaotic, the more healing way the better

**Comment by mser7** [comment]
Just a site note: but its best to make pixies dont sit down or stand up if right clicked with sugar.

**Comment by mser7** [comment]
Can you reopen this? It doesnt work in 1.5.2

**Comment by AlexModGuy** [comment]
fixed
