### ISSUE TITLE
Silver ore cannot be smelted

### ISSUE THREAD

**Issue by JayZX535** [Alex-the-666/Ice_and_Fire#91]
Silver ore does not smelt into silver ingots.  I checked in NEI, and it shows up as having no smelting recipe at all.

[NOT A BUG]Are fishing spears supposed to be craftable?  If so, they also have no recipe.

**Comment by Alex-the-666** [comment]
please report issues separately, and the second issue is intended.

**Comment by JayZX535** [comment]
Okay, I wasn't sure.  How are you supposed to get fishing spears then?  Snow villagers will buy them off you, but I have yet to find one that sells fishing spears...
