### ISSUE TITLE
Dragon Bone Bow issue

### ISSUE THREAD

**Issue by javinyx** [Alex-the-666/Ice_and_Fire#914]
Hello,
I love this mod very very much, but there is an issue with the Dragon Bone Bow, it's not being picked up by other mods as it being a bow, while the ice and fire swords are and they're fine.
Could you please fix the bow to improve compatibility with some weapon enhancing mods? Thank you very much :3

**Comment by AlexModGuy** [comment]
what mods in question do not recognize it as a bow?

**Comment by javinyx** [comment]
Hi, the mod is Loot Slash Conquer.
