### ISSUE TITLE
Stymphalian birds spawning in mass quantities, everywhere

### ISSUE THREAD

**Issue by EinarAsgeir** [Alex-the-666/Ice_and_Fire#915]
The big ol' metal birds have been spawning non-stop in every single world i've tried to make in the last week. And, I don't mean a small amount, I mean in groups of up to 40-60, who know my exact location, even if im miles away, or just having spawned. I will start and have a look around. But lo and behold, I look over onto the Horizon, and see a flock of tiny winged creatures, headed right at me. So many that once I can tell what they are, I am from 50fps down to 1 or 2, and even if I respawn, they are *everywhere*. I've never run into this bug before this version, personally. But its making things very difficult. And I'll assume no one else has had it happen, but it might've. [On the detection radius, same seems to go for almost every creature so far, minus sirens]

**Comment by AlexModGuy** [comment]
I halved their spawnrates and spawn numbers
