### ISSUE TITLE
Siren shader soft incompatibility with Blur mod.

### ISSUE THREAD

**Issue by Ariannae** [Alex-the-666/Ice_and_Fire#918]
As stated in the title, when using the [Blur mod](https://minecraft.curseforge.com/projects/blur) with Ice and Fire, there is a soft incompatibility where the Blur effect does not occur when opening a GUI and the screen simply grows darker.

Changing "Use Siren Shader" to False fixes this at the cost of the siren shader, obviously, but I figured I would bring some attention to it.

**Comment by AlexModGuy** [comment]
care to take pictures of this? Is it in effect only when the sirens are trying to attract the player or all the time?

**Comment by Ariannae** [comment]
When Use Siren Shader is set to True, Blur does not work properly at all, ever. It only darkens the background [like this](https://user-images.githubusercontent.com/9761295/42724761-9e817c46-873d-11e8-9911-9aa566382193.png).

However, when Use Siren Shader is set to False, it [works as intended](https://user-images.githubusercontent.com/9761295/42724706-e92c505a-873c-11e8-9aad-016e95db4f8c.png).

So to answer, when Siren Shader is set to True, Blur never works as intended, regardless of whether the player is being attacked by a Siren or not.
