### ISSUE TITLE
Can't Fly Dragon

### ISSUE THREAD

**Issue by AnyaDinky** [Alex-the-666/Ice_and_Fire#921]
I tried making a dragon fly (Stage 3) I pressed the space bar longer than a minute and press it another time for another minute, It won't seem to fly into the air. It does the animation but won't go up.

**Comment by AlexModGuy** [comment]
Are you playing on a server or client? Mod List?

**Comment by AnyaDinky** [comment]
**I am playing on client.**



![image](https://user-images.githubusercontent.com/41029817/42713765-38a53e44-86b6-11e8-89b3-c5c8e4af5812.png)
![image](https://user-images.githubusercontent.com/41029817/42713779-43218e72-86b6-11e8-9327-d71466238480.png)

**Comment by AlexModGuy** [comment]
see if any other mod keybind overwrites "X" or "SPACEBAR"

**Comment by AnyaDinky** [comment]
i changed dragon down from _x to c_ and jump is the only thing using _SPACEBAR_

**Comment by AlexModGuy** [comment]
uninstall ultimate_unicorn_mod and see if the issue persists

**Comment by AnyaDinky** [comment]
I have uninstalled the mod, but the dragon still will not fly up.

**Comment by AlexModGuy** [comment]
what about without aether? I know they add a few flying tamed mobs

**Comment by juicebox89** [comment]
I am also having this problem. Nothing else is bound to X or space (except for jump). I can hold down space and they'll start flapping their wings, but there's no way to make them go up. I have a few mods that overlap with the ones above: baubles, BoP, betterfps, Guide APi, HwyLa, inventorypets, journeymap, quark, Thaumcraft (6.1BETA16 for me), Thaumic JEI, and Thaumic Inventoryscanning.

**Comment by AlexModGuy** [comment]
@juicebox89 make sure you update your thaumcraft, that version has issues with I&F
since you have a much smaller mod list, could you isolate which mod causes this?

**Comment by juicebox89** [comment]
It looks like it's inventorypets 1.5.2 that's doing it. Once I removed that, I was able to fly just fine.

**Comment by AlexModGuy** [comment]
Ok, I'll look into that

**Comment by AlexModGuy** [comment]
https://github.com/capnkirok/Inventory-Pets/issues/265

**Comment by AnyaDinky** [comment]
@Alex-the-666 Are you going to be fixing this bug so it can have compatibility with Inventory Pets, or are you going to contact the devs of the Pet Inventory so they can also make it Ice and Fire compatible?

**Comment by AnyaDinky** [comment]
Oh ya. I tried flying a moa from Aether II, The moas would not fly also.

**Comment by AlexModGuy** [comment]
@AnyaDinky It depends on what mod is causing this. I'm not certain since InventoryPets is closed source, so I have to message PurpoliciousCow about it.

**Comment by AlexModGuy** [comment]
@AnyaDinky Then the issue is likely with Inventory Pets

**Comment by AnyaDinky** [comment]
I see.. is there going to be an update pretty soon?

**Comment by AlexModGuy** [comment]
inventory pets issue not IAF

**Comment by Solverbolt** [comment]
None of your tamed mobs will fly. There is no keybinding even listed in controls anymore.
