### ISSUE TITLE
deathworms able to burrow through all blocks

### ISSUE THREAD

**Issue by LordDecay26** [Alex-the-666/Ice_and_Fire#928]
i keep trying to tame a deathworm but it just burrows out of my enclosure through pure stone! winds up in a cave and gets blown up by creepers, can you make it so that deathworms only burrow through sand? that would be nice, thanks! xoxox

**Comment by AlexModGuy** [comment]
not able to replicate in 1.5.2

**Comment by LordDecay26** [comment]
wait what? 1.5.2 exists now? i thought there was 1.51 and that was it? okay then, lets try this again with 1.5.2

**Comment by LordDecay26** [comment]
1.5.2 isn't a version, make a 10 block deep stone pit with 7 block deep pit of sand inside the 10 block deep pit, place in stone rocks inside the sand pit touching the walls, on top of the sand, watch the deathworm burrow right through the rock, through the walls, into the abyss.

**Comment by AlexModGuy** [comment]
1.5.2 will be released soon, I fixed it in that version

**Comment by AlexModGuy** [comment]
not fixed

**Comment by AlexModGuy** [comment]
fixded
