### ISSUE TITLE
[SUGGESTION] Randomized names for humanoid mobs

### ISSUE THREAD

**Issue by Sunconure11** [Alex-the-666/Ice_and_Fire#929]
Gorgons and Cyclops currently

Cyclops names could draw from various Greek cyclopses, plus names of giants from other cultures/folklore/mythology/religion.

Gorgons could draw from Greek mythology, plus entities associated with snakes

**Comment by LordDecay26** [comment]
i agree, but it should only show up when the cyclops/gorgon/whatever else down the line kills the player

**Comment by AlexModGuy** [comment]
https://github.com/Alex-the-666/Ice-and-Fire-Suggestions/issues/239
