### ISSUE TITLE
Dragon Overload! 

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#940]
My game was extremely slow, and I found a dragon nest-thingy, so I decided to take a look inside. Well, what I found was not expected. Take a look:
![2018-07-16_12 58 52](https://user-images.githubusercontent.com/41302383/42772592-ebe5031a-88f8-11e8-984e-cdb77a1cd7a5.png)
![2018-07-16_13 03 17](https://user-images.githubusercontent.com/41302383/42772600-f0e1bfd4-88f8-11e8-8247-5542c22ed9dd.png)
I mean holy crap! There are so. many. dragons! The pics I included don't show even half of the actual number of dragons in that one area. I did disable dragon despawning, but I don't think that would have caused that. Perhaps this was just a weird chance thing, but I don't know. I'd hate for all of my new worlds to have this dragon overload. Thanks in advance for any answers! :)

**Comment by ghost** [comment]
Adding on, I wasn't close enough to the area when I was taking the bottom picture, and this is why the dragon(s) didn't show up. They're in there in-game.

**Comment by ghost** [comment]
Back again! I created a new world, and there's still a dragon overload, but it's not nearly as laggy. 
![2018-07-16_13 16 38](https://user-images.githubusercontent.com/41302383/42773240-af60ef88-88fa-11e8-8dbb-ef209a39bcb1.png)
![2018-07-16_13 16 46](https://user-images.githubusercontent.com/41302383/42773247-b3d9cf4e-88fa-11e8-9745-09dce202fd89.png)
![2018-07-16_13 16 51](https://user-images.githubusercontent.com/41302383/42773250-b7151768-88fa-11e8-86ae-c6912d4033f0.png)
![2018-07-16_13 17 08](https://user-images.githubusercontent.com/41302383/42773261-bd85bfb2-88fa-11e8-84bb-033caf77b055.png)

**Comment by ghost** [comment]
![2018-07-16_13 21 10](https://user-images.githubusercontent.com/41302383/42773420-212577e2-88fb-11e8-8c89-58ff98231d8f.png)
How nice of them. They're sharing. :|

**Comment by Natrukei** [comment]
did you change the spawn settings in the config?

**Comment by AlexModGuy** [comment]
@grahaash000 could you send me your ice_and_fire.cfg file?

**Comment by ghost** [comment]
One minute. This could take a while.

**Comment by grahaash000** [comment]
Êþº¾   4R 1com/github/alexthe666/iceandfire/IceAndFireConfig  java/lang/Object  IceAndFireConfig.java customMainMenu Z logCascadingWorldGen generateSilverOre generateSapphireOre generateDragonSkeletons generateDragonSkeletonChance I generateDragonDens generateDragonDenChance generateDragonRoosts generateDragonRoostChance dragonDenGoldAmount generateSnowVillages generateSnowVillageChance dragonBlacklistedDimensions [I dragonWhitelistedDimensions useDimensionBlackList  snowVillageBlacklistedDimensions  snowVillageWhitelistedDimensions 
spawnGlaciers glacierSpawnChance oreToStoneRatioForDragonCaves 
dragonEggTime dragonGriefing dragonFlapNoiseDistance dragonFluteDistance dragonHealth dragonAttackDamage maxDragonFlight dragonGoldSearchLength canDragonsDespawn dragonDigWhenStuck dragonTargetSearchLength dragonWanderFromHomeDistance dragonHungerTickRate spawnHippogryphs hippogryphSpawnRate spawnGorgons spawnGorgonsChance gorgonMaxHealth D 
spawnPixies spawnPixiesChance pixieVillageSize pixiesStealItems generateCyclopsCaves spawnCyclopsChance cyclopesSheepSearchLength cyclopsMaxHealth cyclopsAttackStrength cyclopsBiteStrength sirenMaxHealth generateSirenIslands 
sirenShader generateSirenChance spawnHippocampus hippocampusSpawnChance deathWormTargetSearchLength deathWormMaxHealth deathWormAttackStrength spawnDeathWorm deathWormSpawnRate deathWormSpawnCheckChance cockatriceChickenSearchLength cockatriceEggChance spawnCockatrices cockatriceSpawnRate cockatriceSpawnCheckChance !stymphalianBirdTargetSearchLength #stymphalianBirdFeatherAttackStength F stymphalianBirdFlockLength stymphalianBirdFlightHeight spawnStymphalianBirds stymphalianBirdSpawnChance 
spawnTrolls trollSpawnRate trollSpawnCheckChance trollMaxHealth trollAttackStrength <init> ()V X Y
  Z  	  \  	  ^ 	 	  ` 
 	  b 
 	  d  
	  f  	  h  
	  j  	  l  
	  n  
	  p  	  r  
	  t  	  v  	  x  	  z  	  |  	  ~  	  €  
	  ‚  
	  „  
	  †  
	  ˆ   
	  Š ! 
	  Œ " 
	  Ž # 
	   $ 
	  ’ % 
	  ” & 	  – ' 	  ˜ ( 
	  š ) 
	  œ * 
	  ž + 	    , 
	  ¢ - 	  ¤ . 
	  ¦@Y       / 0	  ª 1 	  ¬ 2 
	  ® 3 
	  ° 4 	  ² 5 	  ´ 6 
	  ¶ 7 
	  ¸@bÀ      8 0	  ¼@.       9 0	  À@D       : 0	  Ä@I       ; 0	  È < 	  Ê = 	  Ì > 
	  Î ? 	  Ð @ 
	  Ò A 
	  Ô@$       B 0	  Ø@       C 0	  Ü D 	  Þ E 
	  à F 
	  â G 
	  ä H 
	  æ I 	  è J 
	  ê K 
	  ì L 
	  î M N	  ð O 
	  ò P 
	  ô Q 	  ö R 
	  ø S 	  ú T 
	  ü U 
	  þ V 0	   W 0	  this 3Lcom/github/alexthe666/iceandfire/IceAndFireConfig; init 3(Lnet/minecraftforge/common/config/Configuration;)V Custom main menu all
 5Whether to display the dragon on the main menu or not .net/minecraftforge/common/config/Configuration 
getBoolean :(Ljava/lang/String;Ljava/lang/String;ZLjava/lang/String;)Z
 Generate Silver Ore %Whether to generate silver ore or not Log Cascading World Gen „Whether to log cascading world gen lag. We hope to fix all cascading lag in the future, but the server console spam is over the top. Generate Sapphire Ore 'Whether to generate sapphire ore or not Generate Dragon Skeletons  +Whether to generate dragon skeletons or not" Generate Dragon Skeleton Chance$ 41 out of this number chance per chunk for generation& getInt <(Ljava/lang/String;Ljava/lang/String;IIILjava/lang/String;)I()
* Generate Dragon Caves, 'Whether to generate dragon caves or not. Generate Dragon Cave Chance0 Generate Dragon Roosts2 (Whether to generate dragon roosts or not4 Generate Dragon Roost Chance6 Dragon Den Gold Amount8 N1 out of this number chance per block that gold will generate in dragon lairs.: Generate Snow Villages< (Whether to generate snow villages or not> Generate Snow Village Chance@ Blacklisted Dragon DimensionsB -Dragons cannot spawn in these dimensions' IDsD get e(Ljava/lang/String;Ljava/lang/String;[ILjava/lang/String;)Lnet/minecraftforge/common/config/Property;FG
H )net/minecraftforge/common/config/PropertyJ 
getIntList ()[ILM
KN Whitelisted Dragon DimensionsP /Dragons can only spawn in these dimensions' IDsR use Dimension BlacklistT >true to use dimensional blacklist, false to use the whitelist.V #Blacklisted Snow Village DimensionsX 3Snow Villages cannot spawn in these dimensions' IDsZ #Whitelisted Snow Village Dimensions\ 5Snow Villages can only spawn in these dimensions' IDs^ Generate Glaciers` )Whether to generate glacier biomes or notb Glacier Spawn Weightd 1Glacier Spawn Weight. Higher number = more commonf Dragon Cave Ore Ratioh 3Ratio of Stone(this number) to Ores in Dragon Cavesj Dragon Egg Hatch Timelÿÿÿ 5How long it takes(in ticks) for a dragon egg to hatcho Dragon Griefingq KDragon griefing - 2 is no griefing, 1 is breaking weak blocks, 0 is defaults Dragon Flap Noise Distanceu HDragon Flap Noise Distance - Larger number, further away you can hear itw Dragon Flute Distancey KDragon Flute Distance - how many chunks away is the dragon flute effective?{ 
Dragon Health} †  +Max dragon health. Health is scaled to this€ Dragon Attack Damage‚ 9Max dragon attack damage. Attack Damage is scaled to this„ Max Dragon Flight Height† &How high dragons can fly, in Y height.ˆ Dragon Gold Search LengthŠ SHow far away dragons will detect gold blocks being destroyed or chests being openedŒ Dragons DespawnŽ XTrue if dragons can despawn. Note that if this is false there may be SERIOUS lag issues. Dragons Dig When Stuck’ cTrue if dragons can break blocks if they get stuck. Turn this off if your dragons randomly explode.” Dragon Target Search Length– `How many blocks away can dragons spot potential prey. Note that increasing this could cause lag.˜  Dragon Wander From Home Distanceš KHow many blocks away can dragons wander from their defined "home" position.œ Dragon Hunger Tick Ratež @Every interval of this number in ticks, dragon hunger decreases.  Spawn Hippogryphs¢ (True if hippogryphs are allowed to spawn¤ Hippogryph Spawn Weight¦ 7Hippogryph spawn weight. Lower = lower chance to spawn.¨ 
Spawn Gorgonsª +True if gorgon temples are allowed to spawn¬ Spawn Gorgon Chance® Gorgon Max Health°BÈ  F@  Maximum gorgon health´ getFloat <(Ljava/lang/String;Ljava/lang/String;FFFLjava/lang/String;)F¶·
¸ Spawn Pixiesº +True if pixie villages are allowed to spawn¼ Spawn Pixies Chance¾ Pixie Village SizeÀ size of pixie villagesÂ Pixies Steal ItemsÄ 0True if pixies are allowed to steal from playersÆ Spawn CyclopesÈ *True if cyclops caves are allowed to spawnÊ Spawn Cyclops ChanceÌ Cyclops Max HealthÎC   Maximum cyclops healthÑ Cyclopes Sheep Search LengthÓ ZHow many blocks away can cyclopes detect sheep. Note that increasing this could cause lag.Õ Cyclops Attack Strength×Ap   Cyclops attack strengthÚ Cyclops Bite StrengthÜB    /Amount of damage done with cyclops bite attack.ß Siren Max HealtháBH   Maximum siren healthä Spawn Sirensæ *True if siren islands are allowed to spawnè Use Siren Shaderê 8True to make the screen pink when sirens attract playersì Spawn Sirens Chanceî Spawn Hippocampusð 'True if hippocampi are allowed to spawnò Spawn Hippocampus Chanceô Death Worm Target Search Lengthö cHow many blocks away can death worms spot potential prey. Note that increasing this could cause lagø Death Worm Base HealthúA    FDefault deathworm health, this is scaled to the worm's particular sizeý Death Worm Base Attack Strengthÿ@@   ODefault deathworm attack strength, this is scaled to the worm's particular size Spawn Death Worms 'True if deathworms are allowed to spawn Death Worm Spawn Weight 5Deathworm spawn weight. Lower = lower chance to spawn
 Death Worm Spawn Check Chance _A double check to see if the game can spawn death worms. Higher number = lower chance to spawn.  Cockatrice chicken Search Length `How many blocks away can cockatrices detect chickens. Note that increasing this could cause lag. Q1 out of this number chance per 6000 ticks for a chicken to lay a cockatrice egg. Spawn Cockatrices (True if cockatrices are allowed to spawn Cockatrice Spawn Weight 6Cockatrice spawn weight. Lower = lower chance to spawn Cockatrice Spawn Check Chance _A double check to see if the game can spawn cockatrices. Higher number = lower chance to spawn.  %Stymphalian Bird Target Search Length" jHow many blocks away can stymphalian birds spot potential prey. Note that increasing this could cause lag.$ (Stymphalian Bird Feather Attack Strength& )Stymphalian bird feather attack strength.( Stymphalian Bird Flock Length* QHow far away stymphalian birds will consider other birds to be in the same flock., "Max Stymphalian Bird Flight Height. 0How high stymphalian birds can fly, in Y height.0 Spawn Stymphalian Birds2 .True if stymphalian birds are allowed to spawn4 Spawn Stymhphalian Bird Chance6 Spawn Trolls8 #True if trolls are allowed to spawn: Troll Spawn Weight< 1Troll spawn weight. Lower = lower chance to spawn> Troll Spawn Check Chance@ ZA double check to see if the game can spawn trolls. Higher number = lower chance to spawn.B Troll Max HealthD Maximum troll healthF Troll Attack StrengthH Troll attack strengthJ config 0Lnet/minecraftforge/common/config/Configuration; Code LocalVariableTable LineNumberTable 
SourceFile !     M            	     
     
      
          
          
     
          
                                   
     
     
     
      
    ! 
    " 
    # 
    $ 
    % 
    &     '     ( 
    ) 
    * 
    +     , 
    -     . 
    / 0    1     2 
    3 
    4     5     6 
    7 
    8 0    9 0    : 0    ; 0    <     =     > 
    ?     @ 
    A 
    B 0    C 0    D     E 
    F 
    G 
    H 
    I     J 
    K 
    L 
    M N    O 
    P 
    Q     R 
    S     T 
    U 
    V 0    W 0     X Y N  ;    Ý*· [*µ ]*µ _*µ a*µ c*µ e*,µ g*µ i* ´µ k*µ m*hµ o*µ q*µ s*dµ u*¼
YOYOµ w*¼
YOµ y*µ {*¼
YOYOµ }*¼
YOµ *µ *µ ƒ*-µ …* µ ‡*µ ‰*µ ‹*µ *ôµ *µ ‘* €µ “*µ •*µ —*µ ™*@µ ›*(µ *
¸µ Ÿ*µ ¡*µ £*µ ¥*Kµ §* ¨µ «*µ ­*<µ ¯*µ ±*µ ³*µ µ* ªµ ·*µ ¹* ºµ ½* ¾µ Á* Âµ Å* Æµ É*µ Ë*µ Í*,µ Ï*µ Ñ*Fµ Ó*@µ Õ* Öµ Ù* Úµ Ý*µ ß*µ á*µ ã*(µ å*
µ ç*µ é*µ ë*µ í*@µ ï*µ ñ*(µ ó*Pµ õ*µ ÷*2µ ù*µ û*
µ ý*µ ÿ* Æµ* Öµ±   O      Ý  P  : N      	   	  
  
   $ 
 )  0  5  <  A  F  L  [  f  k  z  …  Š    •  œ  ¡  ¦  ¬   ³ ! ¹ " À # Æ $ Ë % Ð & Ö ' Ü ( ã ) è * í + ò , ø - ÿ . /
 0 1 2 3  4& 5- 64 7; 8B 9G :L ;S <X =^ >d ?k @r Aw B| C D‡ E F’ G— Hœ I¢ J§ K­ L³ M¸ N¾ OÃ PÉ QÎ RÕ S  N      ¬*+	

¶µ ]*+
¶µ a*+
¶µ _*+
¶µ c*+!
#¶µ e*+%
,''¶+µ g*+-
/¶µ i*+1
 ´''¶+µ k*+3
5¶µ m*+7
h''¶+µ o*+9
';¶+µ q*+=
?¶µ s*+A
d''¶+µ u*+=
?¶µ s*+
C¼
YOYOE¶I¶Oµ w*+
Q¼
YOS¶I¶Oµ y*+U
W¶µ {*+
Y¼
YOYO[¶I¶Oµ }*+
]¼
YO_¶I¶Oµ *+a
c¶µ *+e
'g¶+µ ƒ*+i
-'k¶+µ …*+m
 np¶+µ ‡*+r
t¶+µ ‰*+v
'x¶+µ ‹*+z
'|¶+µ *+~
ô¶+µ *+ƒ
'…¶+µ ‘*+‡
 €
è‰¶+µ “*+‹
'¶+µ •*+
‘¶µ —*+“
•¶µ ™*+—
@'™¶+µ ›*+›
('¶+µ *+Ÿ

¸'¡¶+µ Ÿ*+£
??µ ?*+?
'??+µ ?*+?
??µ ?*+?
K''?+µ ?*+?
??µ???µ ?*+?
??µ ?*+?
<''?+µ ?*+Á
'Ã?+µ ?*+Å
Ç?µ ?*+É
Ë?µ µ*+Í
 ª''?+µ ?*+Ï
Ð?Ò???µ ?*+Ô
'Ö?+µ ?*+Ø
Ù?Û???µ Á*+Ý
Þ?à???µ Å*+â
ã?å???µ É*+ç
é?µ Ë*+ë
í?µ Í*+ï
,''?+µ Ï*+ñ
ó?µ Ñ*+õ
F''?+µ Ó*+?
@'ù?+µ Õ*+û
ü?þ???µ Ù*+ 
????µ Ý*+
?µ ß*+	
'
?+µ á*+

'?+µ ã*+
('?+µ å*+

n?+µ ç*+
?µ é*+
'?+µ ë*+
'!?+µ í*+#
@'%?+µ ï*+'

?)??µ ñ*++
('-?+µ ó*+/
P
è1?+µ õ*+3
5?µ ?*+7
2''?+µ ù*+9
;?µ û*+=

'??+µ ý*+A
'C?+µ ÿ*+E
ã?G???µ*+I
ü?K???µ?   O      ?    ?LM P  > O   V  W $ X 6 Y H Z Z [ r \ ? ] ? ^ ? _ Æ ` Ü a î b c d6 eQ fc g? h? i? jÅ kÜ mô n o p4 qL rc s| t? u? v? wÎ xå yý { |% ~7 N ?g ?y ?? ?? ?? ?Ê ?â ?û ? ?+ ?D ?] ?o ?? ?? ?? ?Â ?Ù ?ò ?
 ? ?3 ?I ?` ?w ?? ?? ?µ ?Ì ?â ?ù ? ?# ?: ªL ?c ?y ?? ?? ? Q    




I copy and pasted the text from the IceAndFireConfig.class. I hope this is the right file.

**Comment by AlexModGuy** [comment]
yeah, thats not what I was asking for. Thats actual code, I'm asking for your ice_and_fire.cfg file in .minecraft/config.

**Comment by ghost** [comment]
oh okay! I'm sorry! I'll do that now.

**Comment by ghost** [comment]
[ice_and_fire.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/2199350/ice_and_fire.txt)

I hope the format is still acceptable because this website doesn't allow me to add .cfg files to comments.

**Comment by AlexModGuy** [comment]
>
    # 1 out of this number chance per chunk for generation [range: 1 ~ 10000, default: 180]
    I:"Generate Dragon Cave Chance"=1

You set the dragon's generation chance to near 100% in your config. Changing this back to 180 or a higher number should fix the issue.

**Comment by AlexModGuy** [comment]
If not, delete your config

**Comment by ghost** [comment]
I didn't even know that I changed that. I'm sorry for wasting your time! Thank you for your help!
