### ISSUE TITLE
Dragon Disappeared after Dismounting

### ISSUE THREAD

**Issue by PiedPipecleaner** [Alex-the-666/Ice_and_Fire#942]
I was riding a grey stage 3 dragon, landed in the icy mountain biome thing, and when I dismounted my dragon just completely disappeared. 

Mods and Versions I'm currently using;
Forge 1.12.2-14.23.4.2736
CustomMobSpawner-3.11.4
DrZharks MoCreatures Mod-12.0.4
iceandfire-1.5.1-1.12.2
llibrary-1.7.14-1.12.2
twilightforest-1.12.2-3.6.345-universal

Edit: it seems it was fixed by exiting and re-entering minecraft. My dragon is now safely sleeping in the snow, but this is still a bit concerning...

**Comment by AlexModGuy** [comment]
fixed in 1.5.2
