### ISSUE TITLE
Falling damage as getting off dragons solution

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#947]
How about a bit of natural falling damage for the dragon scales boots to soften the damage?

**Comment by mser7** [comment]
Oops feather falling not falling damage

**Comment by mser7** [comment]
Video demonstration
https://www.youtube.com/watch?v=6glc1UD2sHw&feature=youtu.be

**Comment by AlexModGuy** [comment]
just made it so you wont take damage when falling off the dragon
