### ISSUE TITLE
Dragons don't turn while flying in a set area

### ISSUE THREAD

**Issue by GundunUkan** [Alex-the-666/Ice_and_Fire#949]
Dragons obey their homepoint's boundaries, but when they reach them and change direction it sometimes causes them to fly sideways or even backwards. And if they are brought out of their homepoint and start flying they head back tail first, which looks super weird.

On another note, when they aren't flying, dragons don't seem to obey their homepoint boundaries, but that isn't much of a big deal, since once they start flying they instantly return home.

**Comment by AlexModGuy** [comment]
dupe #804
