### ISSUE TITLE
Dragon strike attack on hippogryphs still effect tamed mobs

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#953]

**Comment by mser7** [comment]
Same for when on death worms

**Comment by AlexModGuy** [comment]
fixed

**Comment by mser7** [comment]
No it doesn't, reopen it please, this is a tamed dragon btw
![2018-12-30_16 18 04](https://user-images.githubusercontent.com/22555489/50545802-d7dbcf00-0c4e-11e9-9685-f04177dc7758.png)
![2018-12-30_16 18 06](https://user-images.githubusercontent.com/22555489/50545803-d7dbcf00-0c4e-11e9-81b7-ae5f6caa5f1e.png)
![2018-12-30_16 18 10](https://user-images.githubusercontent.com/22555489/50545804-d7dbcf00-0c4e-11e9-99ef-43d790b80125.png)
![2018-12-30_16 18 11](https://user-images.githubusercontent.com/22555489/50545805-d8746580-0c4e-11e9-823b-4e5b605dd973.png)

**Comment by mser7** [comment]
![2018-12-30_16 25 18](https://user-images.githubusercontent.com/22555489/50545861-f2fb0e80-0c4f-11e9-937d-920adb60fd4f.png)
![2018-12-30_16 24 56](https://user-images.githubusercontent.com/22555489/50545862-f2fb0e80-0c4f-11e9-8f1b-2fb0a607034f.png)
![2018-12-30_16 25 03](https://user-images.githubusercontent.com/22555489/50545863-f393a500-0c4f-11e9-8a1c-9463f6087a13.png)
![2018-12-30_16 25 05](https://user-images.githubusercontent.com/22555489/50545864-f393a500-0c4f-11e9-8b17-5f7e6ceb8d93.png)
![2018-12-30_16 25 12](https://user-images.githubusercontent.com/22555489/50545866-f393a500-0c4f-11e9-89ed-40c0269d7468.png)
