### ISSUE TITLE
Player sitting on a dragon is too high for pets to teleport to 

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#954]
Even with a stage 3, it is still to high

**Comment by mser7** [comment]
It would be great if they teleport to you but still not tp high enough to take fall damage

**Comment by AlexModGuy** [comment]
should be working as of 1.5.2 actually, if this is for pixies. if its for wolves, I wont fix because I'd have to mess with vanilla code.
