### ISSUE TITLE
Problems with translation

### ISSUE THREAD

**Issue by IXaar1** [Alex-the-666/Ice_and_Fire#958]
Dear developers,
Nice to meet you again.

Our team had troubles with translating a besteary book. 
When we were trying to translate it on russian we saw that book shows unreadable simbols.

Is it possible to make besteary using Unicode or not??

Best wishes,
Nikita

**Comment by PlatinumFox** [comment]
Hey Nikita 
I’m not a dev but it does appear to be a Unicode font. In the config for the latest version 1.5.2 there is an option to use the default Minecraft font. That may help.

**Comment by AlexModGuy** [comment]
Hi Nikita,

The issue is not a code issue but whoever made the russian translation did not encode the txt files in UTF-8.
