### ISSUE TITLE
Dragon jaw attack is broken

### ISSUE THREAD

**Issue by PCAwesomeness** [Alex-the-666/Ice_and_Fire#96]
I tried getting a Fire Dragon to nab a pig with its jaws; when it would do so, it would just be shaking its head with nothing in its mouth while the pig just stood there and didn't get hurt.

EDIT: I tried it a few more times, and the Fire Dragon does indeed kill the pig. The animation is still broken, though.

**Comment by Alex-the-666** [comment]
Hmm. sometimes it does pick it up, some times it does not. This is intresting.
