### ISSUE TITLE
Optimize siren EventLiving code - sirens should check for mobs, not the other way around

### ISSUE THREAD

**Issue by AlexModGuy** [Alex-the-666/Ice_and_Fire#960]

**Comment by superfluke** [comment]
![image](https://user-images.githubusercontent.com/20022336/44184537-90103d00-a0dd-11e8-9659-46a06cebca32.png)
Recent profile from my server. 6% of tick time and according to sampler, 0 loaded sirens in the world.

**Comment by AlexModGuy** [comment]
fixed
