### ISSUE TITLE
Dragon Dens break bedrock

### ISSUE THREAD

**Issue by brisingraerowing** [Alex-the-666/Ice_and_Fire#962]
As per title. Dragon dens can spawn through bedrock.

![2018-07-22_17 17 08](https://user-images.githubusercontent.com/250409/43050224-13ec12a2-8dd3-11e8-8a1d-c40c2b3d84ec.png)

(I found this out as the gun in my hotbar destroys a large area of blocks when charged, and I was using it to kill the dragon).

**Comment by mser7** [comment]
1.5.2? I thought this was fixed long ago

**Comment by brisingraerowing** [comment]
Yup. 1.5.2.

**Comment by AlexModGuy** [comment]
fixed
