### ISSUE TITLE
[1.5.2] Dragon "sleep paralysis"

### ISSUE THREAD

**Issue by GundunUkan** [Alex-the-666/Ice_and_Fire#966]
I've fought a few dragons with the new version and they don't wake up when you shoot them from a far distance. They start shaking and roaring and whatnot, but seem stuck sleeping, as if they're in sleep paralysis. If you go right next to them, they wake up though.
Also, when you kill a dragon with the "sleep paralysis" bug, it stays in the sleeping position, just with an opened mouth, unless you come closer to it, then it takes the position it's supposed to, but it's legs twist extremely weirdly.

A bit of a long one, but I hope it was helpful.

**Comment by mser7** [comment]
yeah dragons seemed to stuck in their sleeping state in 1.5.2

**Comment by mser7** [comment]
the dragon will not wake up if a mob was hitting it, only when a player in survival is nearby, so it technically can die in its sleep this way, which is quite fascinating and is worth keeping as an easter egg. If you mamage to kill it without waking it up, its dying stage will be the sleeping pose, like it is on 1 hp, is sleeping, and you shot an arrow from far away, killing it
https://cdn.discordapp.com/attachments/297893200918478848/473378299251261440/2018-07-30_13.24.47.png

**Comment by nina-egger** [comment]
This causses MASSIVE server lags as long as this dragon is stuck in the "sleep paralysis". Arrows wont hit it unless you go near it and trigger it to wake up.

**Comment by AlexModGuy** [comment]
fixed
