### ISSUE TITLE
Death Worms get stuck underground

### ISSUE THREAD

**Issue by SirSquidly** [Alex-the-666/Ice_and_Fire#968]
Death Worms moving around under the sand near blocks they cannot pass get stuck in place. I believe this is due to the death worm getting parts of its hit box snagged in blocks it cannot go through, which ends up causing the worm to completely stop.

**Comment by SirSquidly** [comment]
Upon investigation, I think the burrowing mechanic is what causes this problem.

![2018-07-24_09 13 41](https://user-images.githubusercontent.com/13826553/43152001-2c1b0194-8f22-11e8-964d-2f6e3b95d0b7.png)

In this test, I've gotten Death Worms to completely pass through the above structure, falling to the below platform.

I've also placed a single block of sand, which a large death worm could use to burrow straight into pure stone, as long as its head is on the sand.

I think that making the burrow mechanic check the below blocks better, and only go down a single block to prevent this could work, as the worm could do the rest of the diving.

**Comment by AlexModGuy** [comment]
fixed
