### ISSUE TITLE
Ice dragons have no eyes

### ISSUE THREAD

**Issue by redwolf41** [Alex-the-666/Ice_and_Fire#970]
I'm not sure if this is intentional or a bug since I couldnt find anything, and all the pics I see of Ice dragons have eyes, but none of my Ice dragons have eyes, wild or tamed. I have mod version 1.5.2 and I'm playing in the modpack World Of Dragons.

**Comment by AlexModGuy** [comment]
screenshots?

**Comment by AlexModGuy** [comment]
closing due to unable to reproduce
