### ISSUE TITLE
Baby dragon disappeared upon removal from shoulder

### ISSUE THREAD

**Issue by inkdear** [Alex-the-666/Ice_and_Fire#973]
I was carrying a baby fire dragon on my shoulder in creative mode. There were no drops/body (though there was a little 'smoke puff') and no apparent damage source, though it had taken DoT damage while on my shoulder (from electrobob's wizardry spells) and then been healed with splash potions while still on my shoulder. I had taken it on/off successfully a few times before. Reminds me of the vanilla horse-disappearance bug...? I logged in and out to see if reloading the chunk would help but it wasn't there. These are the mods I'm running: https://i.imgur.com/kV81MC4.png

**Comment by AlexModGuy** [comment]
dupe #211
