### ISSUE TITLE
Dragons get stuck in water easily/destroying ice 

### ISSUE THREAD

**Issue by inkdear** [Alex-the-666/Ice_and_Fire#974]
I've had two instances where ice dragons have gotten stuck underwater:
1. A stage 4/5 dragon dug its way to the surface through an icy river - the ice, when broken, turned to water and 'pinned' the dragon in the hole from what I could tell. It just kinda sat there spinning and it was really sad.
2. A dragon got stuck underwater in a swamp under lily pads. I'm not sure if the lily pads were actually keeping it down or if it was just having difficulty leaving the water, but it did eventually make its way out when I removed all the lily pads.
3. Semi-related, so I'll put it here: I've had multiple instances of large dragons getting stuck spinning when standing on small pillars with no other obstacles. As far as I can tell they can't take off.

**Comment by AlexModGuy** [comment]
should be fixed
