### ISSUE TITLE
Cockatrice tamed by staring still attack their owner

### ISSUE THREAD

**Issue by LagoonTheAbyssal** [Alex-the-666/Ice_and_Fire#980]
After taming a cockatrice via staring at them, they will still attack you as if they were wild. This has been tested in singleplayer with no mods, going into creative and back to survival or going far enough to have the chunk the cockatrice is in unloaded seems to fix the issue.

**Comment by mser7** [comment]
I noticed that when taming hippogryph, the mob attack you after tamed as well, and you need to "reset" it to calm it down.
