### ISSUE TITLE
Cockatrice isnt an undead

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#989]
A rotten egg is a dead egg, so the cockatrice should be an undead, if it is it will gain immunity to toxic and heal by harming potion from witches, how cool would that be? To have witch hunter cockatrice
No, they dont burn in the daylight just because they are undead, like undead horses

**Comment by LagoonTheAbyssal** [comment]
This is not an issue with the mod but rather just a feature you want added. If there is a bug, glitch, error, compatibility problem, etc. then post here.
For suggestions please post in this issue thread- https://github.com/Alex-the-666/Ice-and-Fire-Suggestions/issues

**Comment by mser7** [comment]
I was aware of that but still decided to post it here, since the current implement is an issue, and the suggestion is the solution, the witch part is just a bonus if the mob were changed, without it, the mob still seem more fitting as an undead, but fine, I will move it there

**Comment by AlexModGuy** [comment]
intended
