### ISSUE TITLE
Moving Corpse

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#99]
I know this was already posted but I do not see it anymore so I am assuming that it "got fixed". I am resubmitting this issue because it is not fixed. (beta 4). killed a fire dragon with an iced dragon boned sword and its corpse appeared to be almost trying to target other entities or trying to shake something in its jaw,  or at least that's my theory as it was swiveling its body in different directions and making the sound as if it was trying to shoot fire. the corpse moved both before and after shearing. I will attempt to show it in pictures below. 

![2016-12-03_16 53 39](https://cloud.githubusercontent.com/assets/23727270/20862526/4df52570-b97b-11e6-85c8-b4f64733a1df.png)

![2016-12-03_16 53 42](https://cloud.githubusercontent.com/assets/23727270/20862530/53ee9ab0-b97b-11e6-8666-656e8d695ae7.png)

![2016-12-03_16 53 44](https://cloud.githubusercontent.com/assets/23727270/20862532/58d20882-b97b-11e6-9e52-fd17b4e42359.png)

![2016-12-03_16 53 47](https://cloud.githubusercontent.com/assets/23727270/20862535/69497e2a-b97b-11e6-853a-da9394512f58.png)

![2016-12-03_16 54 31](https://cloud.githubusercontent.com/assets/23727270/20862542/918b7e1a-b97b-11e6-8137-b31602b69e59.png)

![2016-12-03_16 54 36](https://cloud.githubusercontent.com/assets/23727270/20862544/94472b68-b97b-11e6-8aac-63c18b44bbd0.png)

![2016-12-03_16 54 41](https://cloud.githubusercontent.com/assets/23727270/20862545/9728c86e-b97b-11e6-97e0-2e9afb88af71.png)

**Comment by Zeklo** [comment]
It might also be noted that upon loading and unloading the corpse entity, it replays the "to laying" animation each time.
