### ISSUE TITLE
Server lag

### ISSUE THREAD

**Issue by LemADEC** [Alex-the-666/Ice_and_Fire#993]
As of 1.5.2-1.12.2, mod is taking a lot of server CPU due to access to entity capabilities.
Consider filtering, throttling or caching to reduce TPS impact.
![image](https://user-images.githubusercontent.com/4776032/43680987-9e49620a-9847-11e8-801f-c3b75e16aa7c.png)
https://github.com/iLexiconn/LLibrary/issues/89

**Comment by Hornblower409** [comment]
For me the lag seems to be from the Cyclops.  If I kill them all, things run fine until new ones spawn.

![iceandfire - cyclops](https://user-images.githubusercontent.com/9989213/43896853-de44b8b8-9b9f-11e8-8061-69d59fc27de4.png)

**Comment by LemADEC** [comment]
We're not talking the same lag source here. This thread is about a lag applied to ALL entities due to systematic lookup done by the mod, with no cache.
Yours is about a specific mob. Please open a separate ticket for this one.

**Comment by LemADEC** [comment]
Any update on this?

**Comment by AlexModGuy** [comment]
this is an LLibrary issue.
