### ISSUE TITLE
Animania mobs, sleep walking in their sleep due to this mod making them run

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#994]
When being chased by perhap a dragon, and the animals is sleeping, this happened, watch the full gif
https://imgur.com/NLDr7LY

**Comment by capnkirok** [comment]
Hey Alex. Looks like you manually call vanilla's EntityAIPanic on the Animania mobs. Problem is the mob is set to Sleeping mode.

I don't think you can mess with my NBT Data... if so, you could setSleeping(false) not sure.

Any ideas?
