### ISSUE TITLE
Dragons Replaces Erebus Gravestone w/ Charred Stone

### ISSUE THREAD

**Issue by WenXin20** [Alex-the-666/Ice_and_Fire#995]
Forge v14.23.4.2745-1.12.2
Erebus v1.0.22
Ice and Fire v1.5.2
While in survival, I had a dragon attack and kill me. It appears that the Erebus Mod Block of Bones gravestone is replaced by charred stone. So all items in the gravestone is lost.

**Comment by AlexModGuy** [comment]
fixed
