### ISSUE TITLE
When dragon griefing is set to default/weak and GriefPrevention is installed, dragons do not break blocks

### ISSUE THREAD

**Issue by flamechair** [Alex-the-666/Ice_and_Fire#997]
I've set the correct flags (block-break iceandfire:any any default/override) in the wilderness yet dragons do not break blocks. Instead it seems like they attempt to break them but the event is immediately cancelled, causing block break particles to spam the screen and lag the game client

**Comment by AlexModGuy** [comment]
caused by grief prevention. We cant override other mods
