### ISSUE TITLE
Hitting Entities with a shot from Dragon Bone Bow crashes the game with the Avatar Mod

### ISSUE THREAD

**Issue by IAmRaptor** [Alex-the-666/Ice_and_Fire#998]
So I've read somewhere else in the issues that to use this bow you need the Dragon Bone Arrows, and that they are the only arrows that actually works with the Dragon Bone Bow, which makes sense.

But first, trying to fire the said bow with a vanilla arrow crashes the game.

And second, as said in the tittle, hitting any entity with Dragon Bone Bow crashes the game, making the Dragon Bone Bow useless. I've tried on Villagers, Zombies, Sheeps, mobs from another mods, Dragons and even accidentally myself in creative mode and it crashes each time. The hit entity still takes damage and the shot arrow is still taken from my inventory, but I don't see myself relaunching the game after each sucessful shot when fighting a Dragon.

I've got the latest forge version.
Here's one of the crash reports that I got while trying to figure this out. It's seems to be the same error every time.
[crash-2018-08-08_07.39.55-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/2269113/crash-2018-08-08_07.39.55-client.txt)

With only Ice and Fire and Llibrary installed, the Dragon Bone Bow functions normaly, and attempting to use vanilla arrows doens't make the game crash either, the arrow simply isn't shot. So I guess the problem comes from incompatiblity with another mod.

**Comment by AlexModGuy** [comment]
> at com.crowsofwar.avatar.common.bending.fire.StatCtrlInfernoPunch.onInfernoPunch(StatCtrlInfernoPunch.java:116)

Seems like this is an issue with the Avatar mod.
